/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Genus
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Lift
public import TauCeti.FieldTheory.FunctionField.Elliptic.Nonsingular
public import TauCeti.FieldTheory.FunctionField.RiemannRoch.Equiv

/-!
# Function fields presented by a Weierstrass equation

Let `F / k` be a field generated by two elements `x` and `y` satisfying the Weierstrass equation

`y² + a₁xy + a₃y = x³ + a₂x² + a₄x + a₆`, `aᵢ ∈ k`,

of a Weierstrass curve `W`, with `x` transcendental over `k`.  Then `F` is the function field
`k(W)` of the curve (`WeierstrassCurve.Affine.functionFieldEquivOfAdjoinEqTop`), and the place at
infinity of `k(W)` becomes a place `P` of degree one of `F` at which `x` and `y` are Weierstrass
coordinates: they have pole divisors `2P` and `3P`.  When `W` is elliptic, `F / k` is moreover
an elliptic function field with exact constant field `k`.  This is the converse of Stichtenoth's
Proposition 6.1.2 (`TauCeti.Place.exists_isWeierstrassCoordinates_of_genus_eq_one`).  It contains
parts (a) and (c) of his Proposition 6.1.3, which treats `y² = f(x)` in characteristic other than
two, for an arbitrary Weierstrass equation in every characteristic; the different of `F / k(x)`
(part (b)) is not computed here.

Together with `TauCeti.Place.IsWeierstrassCoordinates.isElliptic`, it shows that over a perfect
field, Weierstrass coordinates at a place of degree one of a function field are coordinates on
an elliptic curve exactly when the field has genus one.

## Main results

* `TauCeti.Place.isWeierstrassCoordinates_infinity`: the generic coordinates of a Weierstrass
  curve are Weierstrass coordinates at its place at infinity.
* `TauCeti.Place.exists_isWeierstrassCoordinates_of_equation`: a field generated by a solution of
  a Weierstrass equation has Weierstrass coordinates `x`, `y` at a place of degree one.
* `TauCeti.genus_eq_one_of_equation`, `TauCeti.isIntegrallyClosedIn_of_equation` and
  `TauCeti.isEllipticFunctionField_of_equation`: **a field generated by a solution of the equation
  of an elliptic curve is an elliptic function field with exact constant field**
  (Stichtenoth, Proposition 6.1.3).
* `TauCeti.Place.IsWeierstrassCoordinates.isElliptic_iff_genus_eq_one`: over a perfect field, the
  Weierstrass curve of Weierstrass coordinates at a place of degree one is elliptic exactly when
  the function field has genus one.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Propositions 6.1.2 and 6.1.3.
-/

public section

namespace TauCeti

open AlgebraicGeometry WeierstrassCurve _root_.Polynomial

open scoped _root_.IntermediateField

variable {k F : Type*} [Field k] [Field F] [Algebra k F]

namespace Place

/-- **The coordinate functions of a Weierstrass curve are Weierstrass coordinates at its place at
infinity**: on `k(W)`, the generic coordinates `x` and `y` have poles of orders two and three at
infinity, are regular elsewhere, and satisfy the equation of `W`. -/
theorem isWeierstrassCoordinates_infinity (W : WeierstrassCurve k) :
    (infinity W.toAffine).IsWeierstrassCoordinates W W.toAffine.genericX W.toAffine.genericY where
  ord_x := by
    rw [ord_def, valuation_infinity, Affine.genericX_def, Affine.CoordinateRing.mk_C_eq_algebraMap,
      Affine.infinityPlace.X, WithZero.log_exp]
  ord_x_nonneg _ hQ := by
    rw [Affine.genericX_def, ← mem_integers_iff_ord_nonneg, mem_integers_iff]
    exact valuation_algebraMap_le_one_of_ne_infinity hQ _
  ord_y := by
    rw [ord_def, valuation_infinity, Affine.genericY_def, Affine.infinityPlace.mk_Y,
      WithZero.log_exp]
  ord_y_nonneg _ hQ := by
    rw [Affine.genericY_def, ← mem_integers_iff_ord_nonneg, mem_integers_iff]
    exact valuation_algebraMap_le_one_of_ne_infinity hQ _
  equation := W.toAffine.equation_genericX_genericY

variable {W : WeierstrassCurve k} {x y : F}

/-- **Weierstrass coordinates of a field presented by a Weierstrass equation**: if `x` and `y`
generate `F` over `k`, satisfy the equation of `W` and `x` is transcendental, then they are
Weierstrass coordinates at the place of `F` corresponding to the place at infinity of `k(W)`. -/
theorem isWeierstrassCoordinates_map_infinity (h : (W.baseChange F).toAffine.Equation x y)
    (hx : Transcendental k x) (hxy : k⟮x, y⟯ = ⊤) :
    ((infinity W.toAffine).map (W.toAffine.functionFieldEquivOfAdjoinEqTop h hx hxy)
      ).IsWeierstrassCoordinates W x y := by
  simpa using (isWeierstrassCoordinates_infinity W).map
    (W.toAffine.functionFieldEquivOfAdjoinEqTop h hx hxy)

/-- **A field generated by a solution of a Weierstrass equation has Weierstrass coordinates at a
place of degree one** (Stichtenoth, Proposition 6.1.3): if `x` and `y` generate `F` over `k`,
satisfy the equation of `W` and `x` is transcendental, then there is a place of degree one at
which `x` and `y` have pole divisors `2P` and `3P`.  No nonsingularity of `W` is needed. -/
theorem exists_isWeierstrassCoordinates_of_equation (h : (W.baseChange F).toAffine.Equation x y)
    (hx : Transcendental k x) (hxy : k⟮x, y⟯ = ⊤) :
    ∃ P : Place k F, P.degree = 1 ∧ P.IsWeierstrassCoordinates W x y :=
  ⟨_, by rw [degree_map, degree_infinity], isWeierstrassCoordinates_map_infinity h hx hxy⟩

end Place

section Elliptic

variable {W : WeierstrassCurve k} [W.IsElliptic] {x y : F}

/-- **A field generated by a solution of the equation of an elliptic curve has genus one**
(Stichtenoth, Proposition 6.1.3): it is the function field of the curve. -/
theorem genus_eq_one_of_equation (h : (W.baseChange F).toAffine.Equation x y)
    (hx : Transcendental k x) (hxy : k⟮x, y⟯ = ⊤) : genus k F = 1 := by
  rw [genus_eq_of_ringEquiv (RingEquiv.refl k)
    (W.toAffine.functionFieldEquivOfAdjoinEqTop h hx hxy).toRingEquiv fun c ↦ by simp]
  exact W.toAffine.genus_functionField

/-- **A field generated by a solution of the equation of an elliptic curve has exact constant
field** (Stichtenoth, Proposition 6.1.3): `k` is algebraically closed in it. -/
theorem isIntegrallyClosedIn_of_equation (h : (W.baseChange F).toAffine.Equation x y)
    (hx : Transcendental k x) (hxy : k⟮x, y⟯ = ⊤) : IsIntegrallyClosedIn k F :=
  (W.toAffine.functionFieldEquivOfAdjoinEqTop h hx hxy).isIntegrallyClosedIn.mp
    W.toAffine.isIntegrallyClosedIn_functionField

/-- **A field generated by a solution of the equation of an elliptic curve is an elliptic function
field** (Stichtenoth, Proposition 6.1.3): it has genus one, and the place at infinity of the curve
is a place of degree one. -/
theorem isEllipticFunctionField_of_equation (h : (W.baseChange F).toAffine.Equation x y)
    (hx : Transcendental k x) (hxy : k⟮x, y⟯ = ⊤) : IsEllipticFunctionField k F := by
  obtain ⟨P, hP, -⟩ := Place.exists_isWeierstrassCoordinates_of_equation h hx hxy
  exact ⟨genus_eq_one_of_equation h hx hxy, WeilDivisor.ofPoint P, by
    rw [Divisor.degree_ofPoint, hP, Nat.cast_one]⟩

namespace Place.IsWeierstrassCoordinates

variable {P : Place k F}

/-- **Weierstrass coordinates for an elliptic curve force genus one**: at a place of degree one
of a function field, Weierstrass coordinates `x`, `y` for an elliptic curve generate the field,
which is therefore the function field of the curve. -/
theorem genus_eq_one (h : P.IsWeierstrassCoordinates W x y) (hF : IsFunctionField k F)
    (hP : P.degree = 1) : genus k F = 1 :=
  genus_eq_one_of_equation h.equation h.transcendental_x (h.adjoin_eq_top hF hP)

end Place.IsWeierstrassCoordinates

end Elliptic

/-- **Over a perfect field, Weierstrass coordinates lie on an elliptic curve exactly in genus
one**: at a place of degree one of a function field, the Weierstrass curve of Weierstrass
coordinates is elliptic if and only if the field has genus one.  Perfectness is used only in the
backward direction, where a singular point of `W` has to be rational. -/
theorem Place.IsWeierstrassCoordinates.isElliptic_iff_genus_eq_one [PerfectField k]
    {P : Place k F} {W : WeierstrassCurve k} {x y : F} (h : P.IsWeierstrassCoordinates W x y)
    (hF : IsFunctionField k F) (hP : P.degree = 1) : W.IsElliptic ↔ genus k F = 1 :=
  ⟨fun _ ↦ h.genus_eq_one hF hP, fun hg ↦ h.isElliptic hF hP (by omega)⟩

end TauCeti
