/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Verma
public import TauCeti.LinearAlgebra.RootSystem.KostantPartition.Basic

-- Non-public: `TauCeti.lie_mem_weightSpace_of_mem_weightSpace`, the weight shift by a root vector.
import TauCeti.Algebra.Lie.Weights.Eigenvector
-- Non-public: `Module.Basis.repr_eq_zero_of_weight_ne`, coordinates of a joint eigenvector.
import TauCeti.LinearAlgebra.Eigenspace.DiagonalBasis

/-!
# The weights of a Verma module and their multiplicities

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, `H` a splitting Cartan subalgebra and `b` a base of its root system. The
Verma module `M(lam)` is a free `U(n⁻)`-module of rank one on its canonical generator `v_lam`
(`TauCeti.universalEnvelopingEquivVermaModule`), so a Poincaré--Birkhoff--Witt basis of `U(n⁻)`
gives a basis of `M(lam)`: the vectors

`f_{i₁} ⋯ f_{iₖ} · v_lam`,   `i₁ ≤ ⋯ ≤ iₖ`,

for an ordered basis `(f_i)` of the negative nilradical `n⁻`. When every `f_i` is an
`H`-eigenvector of weight `w_i`, the vector attached to the exponent `n` is an `H`-eigenvector of
weight `lam + ∑ᵢ nᵢ wᵢ`, so the weight space `M(lam)_mu` is spanned by the basis vectors of that
weight and its dimension is the number of exponents `n` with `lam + ∑ᵢ nᵢ wᵢ = mu`
(`TauCeti.finrank_weightSpace_vermaModule_eq_natCard`).

The negative nilradical has such a basis made of root vectors, one for each positive root `α`,
lying in the line `L_{-α}` (`TauCeti.negativeNilradicalBasis`). With it the count becomes the
number of ways of writing `lam - mu` as a sum of positive roots with multiplicity, which is the
Kostant partition function: **the weight multiplicities of a Verma module are**

`dim M(lam)_mu = P(lam - mu)`

(`TauCeti.finrank_weightSpace_vermaModule`). In particular the weights of `M(lam)` are exactly the
elements of `lam` minus the monoid generated by the positive roots
(`TauCeti.weightSpace_vermaModule_ne_bot_iff`), and `M(lam)` is the direct sum of its weight
spaces (`TauCeti.isInternal_weightSpace_vermaModule`).

## Main definitions

* `TauCeti.vermaBasis`: the basis of `M(lam)` obtained by applying the ordered monomials in a basis
  of `n⁻` to the canonical generator.

## Main results

* `TauCeti.vermaBasis_mem_weightSpace`: for a basis of `n⁻` made of weight vectors, every vector of
  the associated basis of `M(lam)` is a weight vector, of the weight read off its exponent.
* `TauCeti.weightSpace_vermaModule_eq_span` and
  `TauCeti.finrank_weightSpace_vermaModule_eq_natCard`: a weight space of `M(lam)` is spanned by
  the basis vectors of that weight, so its dimension counts the exponents of that weight.
* `TauCeti.finrank_weightSpace_vermaModule`: **`dim M(lam)_mu = P(lam - mu)`**, the Kostant
  partition function of `lam - mu`.
* `TauCeti.weightSpace_vermaModule_ne_bot_iff`: `mu` is a weight of `M(lam)` exactly when
  `lam - mu` is a sum of positive roots.
* `TauCeti.iSup_weightSpace_vermaModule_eq_top` and `TauCeti.isInternal_weightSpace_vermaModule`:
  the Verma module is the sum, indeed the internal direct sum, of its weight spaces.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §20.3 and
  §24.1.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, §1.3.
-/

public section

open UniversalEnvelopingAlgebra

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]

local notation "U" => _root_.UniversalEnvelopingAlgebra K L

/-! ### The Poincaré--Birkhoff--Witt basis of a Verma module -/

section VermaBasis

variable (b : (IsKilling.rootSystem H).Base) (lam : Dual K H) {σ : Type w} [LinearOrder σ]
  (B : Basis σ K (negativeNilradical H b))

/-- The canonical generator `v_lam` is a weight vector of weight `lam`. -/
private theorem vermaGenerator_mem_weightSpace :
    vermaGenerator b lam ∈ weightSpace (VermaModule b lam) (lam : H → K) := by
  rw [mem_weightSpace]
  intro h
  simp only [LieSubalgebra.coe_bracket_of_module, lie_vermaGenerator_eq_smul]

/-- A product of eigenvectors of the adjoint action, applied to `v_lam`, is a weight vector whose
weight is `lam` shifted by their eigenvalues. -/
private theorem prod_smul_vermaGenerator_mem_weightSpace {κ : Type*} {f : κ → L}
    {w : κ → Dual K H} (hf : ∀ i (h : H), ⁅(h : L), f i⁆ = w i h • f i) (word : List κ) :
    ((word.map fun i ↦ ι K (f i)).prod : U) • vermaGenerator b lam ∈
      weightSpace (VermaModule b lam) ((lam + (word.map w).sum : Dual K H) : H → K) := by
  induction word with
  | nil => simpa using vermaGenerator_mem_weightSpace b lam
  | cons i word ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    rw [mul_smul, vermaModule_ι_smul]
    convert lie_mem_weightSpace_of_mem_weightSpace (hf i) ih using 2
    ext h
    simp only [LinearMap.add_apply, Pi.add_apply]
    ring

/-- **The Poincaré--Birkhoff--Witt basis of the Verma module** attached to an ordered basis `B` of
the negative nilradical: the vector of exponent `n` is the ordered monomial of
`Module.Basis.pbwBasis` in `B`, with exponent `n`, applied to the canonical generator
`v_lam` (`TauCeti.vermaBasis_apply`). It is a basis because `M(lam)` is a free `U(n⁻)`-module of
rank one on `v_lam`. -/
noncomputable def vermaBasis : Basis (σ →₀ ℕ) K (VermaModule b lam) :=
  B.pbwBasis.map (universalEnvelopingEquivVermaModule b lam)

/-- The basis vector of exponent `n` is the ordered monomial of exponent `n` in `B`, applied to the
canonical generator. -/
theorem vermaBasis_apply (n : σ →₀ ℕ) :
    vermaBasis b lam B n =
      UniversalEnvelopingAlgebra.map K (negativeNilradical H b).incl (B.pbwBasis n) •
        vermaGenerator b lam := by
  rw [vermaBasis, Basis.map_apply, universalEnvelopingEquivVermaModule_apply]

/-- **The basis vectors of a Verma module are weight vectors.** If the Cartan subalgebra acts on
each vector `B i` of the basis of `n⁻` through `w i`, then the basis vector of exponent `n` has
weight `lam + ∑ᵢ nᵢ w i`. -/
theorem vermaBasis_mem_weightSpace {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (n : σ →₀ ℕ) :
    vermaBasis b lam B n ∈ weightSpace (VermaModule b lam)
      ((lam + n.sum fun i k ↦ k • w i : Dual K H) : H → K) := by
  have hsum : ((n.toMultiset.sort (· ≤ ·)).map w).sum = n.sum fun i k ↦ k • w i := by
    rw [← Multiset.sum_coe, ← Multiset.map_coe, Multiset.sort_eq, Finsupp.toMultiset_map,
      Finsupp.sum_toMultiset, Finsupp.sum_mapDomain_index (h := fun a k ↦ k • a)
        (fun _ ↦ zero_nsmul _) fun _ _ _ ↦ add_nsmul _ _ _]
  rw [← hsum, vermaBasis_apply, Basis.pbwBasis_apply, UniversalEnvelopingAlgebra.pbwMonomial_def,
    map_list_prod,
    List.map_map, List.map_map]
  convert prod_smul_vermaGenerator_mem_weightSpace b lam hB (n.toMultiset.sort (· ≤ ·))
  simp [Function.comp_def]

/-- **A weight space of a Verma module is spanned by the basis vectors of that weight.** If the
Cartan subalgebra acts on each vector `B i` of the basis of `n⁻` through `w i`, the weight space
`M(lam)_mu` is spanned by the basis vectors whose exponent `n` satisfies `lam + ∑ᵢ nᵢ w i = mu`. -/
theorem weightSpace_vermaModule_eq_span {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (mu : Dual K H) :
    (weightSpace (VermaModule b lam) (mu : H → K)).toSubmodule =
      Submodule.span K
        (vermaBasis b lam B '' {n | lam + (n.sum fun i k ↦ k • w i) = mu}) := by
  set V := vermaBasis b lam B
  have hV (n : σ →₀ ℕ) : V n ∈ weightSpace (VermaModule b lam)
      ((lam + n.sum fun i k ↦ k • w i : Dual K H) : H → K) :=
    vermaBasis_mem_weightSpace b lam B hB n
  refine le_antisymm (fun m hm ↦ ?_) (Submodule.span_le.mpr ?_)
  · rw [Basis.mem_span_image]
    intro n hn
    rw [Finset.mem_coe, Finsupp.mem_support_iff] at hn
    by_contra hns
    -- the action of `H` is diagonal in the basis `V`, with the weights of the basis vectors
    refine hn (V.repr_eq_zero_of_weight_ne
      (f := fun h : H ↦ toEnd K L (VermaModule b lam) (h : L))
      (a := fun n ↦ ((lam + n.sum fun i k ↦ k • w i : Dual K H) : H → K)) (c := (mu : H → K))
      (fun n' h ↦ ?_) (fun h ↦ ?_) fun heq ↦ hns (DFunLike.coe_injective heq))
    · rw [toEnd_apply_apply, ← LieSubalgebra.coe_bracket_of_module]
      exact (mem_weightSpace _ _).mp (hV n') h
    · rw [toEnd_apply_apply, ← LieSubalgebra.coe_bracket_of_module]
      exact (mem_weightSpace _ _).mp hm h
  · rintro _ ⟨n, hn, rfl⟩
    have := hV n
    rwa [Set.mem_ofPred_eq.mp hn] at this

/-- **The weight multiplicities of a Verma module count exponents.** If the Cartan subalgebra acts
on each vector `B i` of the basis of `n⁻` through `w i`, then the weight space `M(lam)_mu` has
dimension the number of exponents `n` with `lam + ∑ᵢ nᵢ w i = mu`. When there are infinitely many
such exponents both sides are `0`. -/
theorem finrank_weightSpace_vermaModule_eq_natCard {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (mu : Dual K H) :
    finrank K (weightSpace (VermaModule b lam) (mu : H → K)) =
      Nat.card {n : σ →₀ ℕ // lam + (n.sum fun i k ↦ k • w i) = mu} := by
  have hli : LinearIndependent K
      fun n : ({n | lam + (n.sum fun i k ↦ k • w i) = mu} : Set (σ →₀ ℕ)) ↦ vermaBasis b lam B n :=
    (vermaBasis b lam B).linearIndependent.comp _ Subtype.val_injective
  -- a weight space and its underlying subspace have the same carrier
  have hfin : finrank K (weightSpace (VermaModule b lam) (mu : H → K)) =
      finrank K (weightSpace (VermaModule b lam) (mu : H → K)).toSubmodule := rfl
  rw [hfin, weightSpace_vermaModule_eq_span b lam B hB, Set.image_eq_range, Module.finrank,
    rank_span hli]
  exact Nat.card_range_of_injective hli.injective

/-- **The weights of a Verma module.** If the Cartan subalgebra acts on each vector `B i` of the
basis of `n⁻` through `w i`, then `mu` is a weight of `M(lam)` exactly when it is
`lam + ∑ᵢ nᵢ w i` for some exponent `n`. -/
theorem weightSpace_vermaModule_ne_bot_iff_exists {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (mu : Dual K H) :
    weightSpace (VermaModule b lam) (mu : H → K) ≠ ⊥ ↔
      ∃ n : σ →₀ ℕ, lam + (n.sum fun i k ↦ k • w i) = mu := by
  rw [ne_eq, ← LieSubmodule.toSubmodule_eq_bot, weightSpace_vermaModule_eq_span b lam B hB,
    Submodule.span_eq_bot]
  simp only [Set.mem_image, Set.mem_ofPred_eq, forall_exists_index, and_imp,
    forall_apply_eq_imp_iff₂, (vermaBasis b lam B).ne_zero, imp_false, not_forall, not_not]

end VermaBasis

/-! ### The multiplicities are given by the Kostant partition function -/

section Kostant

variable (b : (IsKilling.rootSystem H).Base) (lam : Dual K H)

/-- `TauCeti.lie_negativeNilradicalBasis` in the form the results of the previous section consume:
the Cartan subalgebra acts on the root vector of index `α` through the linear form `-α`. -/
private theorem lie_negativeNilradicalBasis_eq_neg_root_smul
    (i : posRoots (IsKilling.rootSystem H) b) (h : H) :
    ⁅(h : L), (negativeNilradicalBasis H b i : L)⁆ =
      (-(IsKilling.rootSystem H).root i) h • (negativeNilradicalBasis H b i : L) := by
  rw [lie_negativeNilradicalBasis, LinearMap.neg_apply]

/-- An exponent on the positive roots is a multiplicity function on all roots vanishing off the
positive ones: extend it by zero (`Finsupp.restrictSupportEquiv`) and forget finiteness of the
support, automatic on the finite set of roots (`Finsupp.equivFunOnFinite`). -/
private noncomputable def exponentEquivSupported :
    (posRoots (IsKilling.rootSystem H) b →₀ ℕ) ≃
      {c : H.root → ℕ // Function.support c ⊆ posRoots (IsKilling.rootSystem H) b} :=
  (Finsupp.restrictSupportEquiv _ ℕ).symm.trans <|
    Finsupp.equivFunOnFinite.subtypeEquiv fun f ↦ by
      -- `Finsupp.equivFunOnFinite f` is the coercion `⇑f` by definition
      rw [← Finsupp.fun_support_eq]
      rfl

private theorem sum_exponentEquivSupported (n : posRoots (IsKilling.rootSystem H) b →₀ ℕ) :
    ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
        (exponentEquivSupported b n).1 i • (IsKilling.rootSystem H).root i =
      n.sum fun i k ↦ k • (IsKilling.rootSystem H).root i := by
  classical
  have := Fintype.ofFinite (posRoots (IsKilling.rootSystem H) b)
  rw [Finset.sum_subtype _ (mem_posRootsFinset _ b),
    Finsupp.sum_fintype n (fun i k ↦ k • (IsKilling.rootSystem H).root i) fun _ ↦ zero_nsmul _]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  simp [exponentEquivSupported, i.2]

/-- The weight `lam + ∑ᵢ nᵢ (-αᵢ)` of a basis vector is `mu` exactly when `∑ᵢ nᵢ αᵢ = lam - mu`. -/
private theorem add_sum_smul_neg_eq_iff (n : posRoots (IsKilling.rootSystem H) b →₀ ℕ)
    (mu : Dual K H) :
    lam + (n.sum fun i k ↦ k • -(IsKilling.rootSystem H).root i) = mu ↔
      (n.sum fun i k ↦ k • (IsKilling.rootSystem H).root i) = lam - mu := by
  simp only [Finsupp.sum, smul_neg, Finset.sum_neg_distrib, ← sub_eq_add_neg]
  constructor
  · rintro rfl
    abel
  · intro h
    rw [h]
    abel

/-- The exponents on the positive roots whose basis vector of `M(lam)` has weight `mu` are the
Kostant partitions of `lam - mu`. -/
private noncomputable def exponentEquivKostantPartition (mu : Dual K H) :
    {n : posRoots (IsKilling.rootSystem H) b →₀ ℕ //
        lam + (n.sum fun i k ↦ k • -(IsKilling.rootSystem H).root i) = mu} ≃
      {c : H.root → ℕ // IsKostantPartition (IsKilling.rootSystem H) b (lam - mu) c} :=
  ((exponentEquivSupported b).subtypeEquiv
      (q := fun c ↦ ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
        c.1 i • (IsKilling.rootSystem H).root i = lam - mu) fun n ↦ by
      rw [add_sum_smul_neg_eq_iff, ← sum_exponentEquivSupported]).trans <|
    (Equiv.subtypeSubtypeEquivSubtypeInter
      (fun c : H.root → ℕ ↦ Function.support c ⊆ posRoots (IsKilling.rootSystem H) b)
      fun c ↦ ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
        c i • (IsKilling.rootSystem H).root i = lam - mu).trans <|
      Equiv.subtypeEquivRight fun c ↦ (isKostantPartition_iff _ _ _ _).symm

/-- **The weight multiplicities of a Verma module are given by the Kostant partition function**:
the weight space `M(lam)_mu` has dimension `P(lam - mu)`, the number of ways of writing `lam - mu`
as a sum of positive roots with multiplicity. -/
theorem finrank_weightSpace_vermaModule (mu : Dual K H) :
    finrank K (weightSpace (VermaModule b lam) (mu : H → K)) =
      kostantPartition (IsKilling.rootSystem H) b (lam - mu) := by
  let : LinearOrder (posRoots (IsKilling.rootSystem H) b) :=
    LinearOrder.lift' (Finite.equivFin _) (Finite.equivFin _).injective
  rw [finrank_weightSpace_vermaModule_eq_natCard b lam (negativeNilradicalBasis H b)
    (lie_negativeNilradicalBasis_eq_neg_root_smul b) mu, kostantPartition_def]
  exact Nat.card_congr (exponentEquivKostantPartition b lam mu)

/-- **The weights of a Verma module**: `mu` is a weight of `M(lam)` exactly when `lam - mu` is a
sum of positive roots with multiplicity. -/
theorem weightSpace_vermaModule_ne_bot_iff (mu : Dual K H) :
    weightSpace (VermaModule b lam) (mu : H → K) ≠ ⊥ ↔
      ∃ c, IsKostantPartition (IsKilling.rootSystem H) b (lam - mu) c := by
  let : LinearOrder (posRoots (IsKilling.rootSystem H) b) :=
    LinearOrder.lift' (Finite.equivFin _) (Finite.equivFin _).injective
  rw [weightSpace_vermaModule_ne_bot_iff_exists b lam (negativeNilradicalBasis H b)
    (lie_negativeNilradicalBasis_eq_neg_root_smul b) mu]
  exact ⟨fun ⟨n, hn⟩ ↦ ⟨_, (exponentEquivKostantPartition b lam mu ⟨n, hn⟩).2⟩,
    fun ⟨c, hc⟩ ↦ ⟨_, ((exponentEquivKostantPartition b lam mu).symm ⟨c, hc⟩).2⟩⟩

/-- **A Verma module is the sum of its weight spaces.** -/
theorem iSup_weightSpace_vermaModule_eq_top :
    ⨆ mu : Dual K H, weightSpace (VermaModule b lam) (mu : H → K) = ⊤ := by
  let : LinearOrder (posRoots (IsKilling.rootSystem H) b) :=
    LinearOrder.lift' (Finite.equivFin _) (Finite.equivFin _).injective
  rw [← LieSubmodule.toSubmodule_inj, LieSubmodule.iSup_toSubmodule,
    LieSubmodule.top_toSubmodule, eq_top_iff,
    ← (vermaBasis b lam (negativeNilradicalBasis H b)).span_eq, Submodule.span_le]
  rintro _ ⟨n, rfl⟩
  exact Submodule.mem_iSup_of_mem _
    (vermaBasis_mem_weightSpace b lam _ (lie_negativeNilradicalBasis_eq_neg_root_smul b) n)

open scoped Classical in
/-- **The weight-space decomposition of a Verma module**: `M(lam)` is the internal direct sum of
its weight spaces. -/
theorem isInternal_weightSpace_vermaModule :
    DirectSum.IsInternal
      fun mu : Dual K H ↦ (weightSpace (VermaModule b lam) (mu : H → K)).toSubmodule := by
  refine DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top ?_ ?_
  · rw [LieSubmodule.iSupIndep_toSubmodule]
    exact ((iSupIndep_genWeightSpace K H (VermaModule b lam)).comp
      (f := fun mu : Dual K H ↦ (mu : H → K)) DFunLike.coe_injective).mono
      fun mu ↦ weightSpace_le_genWeightSpace _ _
  · rw [← LieSubmodule.iSup_toSubmodule, iSup_weightSpace_vermaModule_eq_top,
      LieSubmodule.top_toSubmodule]

end Kostant

end TauCeti
