/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RepresentationTheory.Homological.GroupCohomology.Hilbert90

/-!
# Hilbert's Theorem 90 for cyclic extensions in every universe

Let `L/K` be a finite Galois extension whose Galois group is generated by `g`. Hilbert's
Theorem 90 says that an element `x` of `L` of norm one is `g y / y` for a unit `y` of `L`.

Mathlib proves this as `groupCohomology.exists_div_of_norm_eq_one` through the cohomology of
finite cyclic groups, which is set up for fields in `Type`. This file deduces the statement for
fields in an arbitrary universe from Noether's form of Hilbert 90,
`groupCohomology.isMulCoboundary₁_of_isMulCocycle₁_of_aut_to_units`, which is
universe-polymorphic: when `x` has norm one, the partial products `x · g x ⋯ g^{i-1} x` depend
only on `gⁱ` and form a multiplicative `1`-cocycle.

## Main results

* `TauCeti.exists_smul_div_eq_of_norm_eq_one`: Hilbert's Theorem 90 for a cyclic Galois
  extension.

## References

* J.-P. Serre, *Local Fields*, Chapter X, §1.
-/

public section

open groupCohomology

namespace TauCeti

variable {K L : Type*} [Field K] [Field L] [Algebra K L] [FiniteDimensional K L] [IsGalois K L]

/-- **Hilbert's Theorem 90 for cyclic extensions.** If `g` generates `Gal(L/K)` and the unit `x`
of `L` has norm one, then `x = g y / y` for a unit `y` of `L`. -/
theorem exists_smul_div_eq_of_norm_eq_one {g : L ≃ₐ[K] L} (hg : ∀ σ, σ ∈ Subgroup.zpowers g)
    {x : Lˣ} (hx : Algebra.norm K (x : L) = 1) : ∃ y : Lˣ, g • y / y = x := by
  classical
  have hfin : IsOfFinOrder g := isOfFinOrder_of_finite g
  -- The partial products `P i = x · g x ⋯ g^{i-1} x`.
  let P : ℕ → Lˣ := fun i ↦ ∏ j ∈ Finset.range i, g ^ j • x
  have hP_add (a b : ℕ) : P (a + b) = P a * g ^ a • P b := by
    simp only [P, Finset.prod_range_add, Finset.smul_prod', pow_add, mul_smul]
  -- A full period is the norm of `x`.
  have hP_orderOf : P (orderOf g) = 1 := by
    have hprod : P (orderOf g) = ∏ σ : L ≃ₐ[K] L, σ • x := by
      simp only [P]
      rw [Finset.prod_range]
      refine Fintype.prod_equiv ((finEquivZPowers hfin).trans (Equiv.subtypeUnivEquiv hg)) _ _
        fun j ↦ ?_
      simp [finEquivZPowers_apply]
    refine hprod.trans (Units.ext ?_)
    simp only [Units.coe_prod, AlgEquiv.smul_units_def, Units.coe_map, MonoidHom.coe_ofClass,
      Units.val_one]
    rw [← Algebra.norm_eq_prod_automorphisms, hx, map_one]
  have hP_mod (i : ℕ) : P (i % orderOf g) = P i := by
    conv_rhs => rw [← Nat.mod_add_div i (orderOf g)]
    induction i / orderOf g with
    | zero => simp
    | succ k ih => rw [Nat.mul_succ, ← add_assoc, hP_add, hP_orderOf, smul_one, mul_one, ih]
  -- The cocycle `gⁱ ↦ P i`.
  let f : (L ≃ₐ[K] L) → Lˣ := fun σ ↦ P ((finEquivZPowers hfin).symm ⟨σ, hg σ⟩)
  have hf (i : ℕ) : f (g ^ i) = P i := by
    simp only [f]
    rw [finEquivZPowers_symm_apply hfin i, hP_mod]
  have hsurj (σ : L ≃ₐ[K] L) : ∃ i : ℕ, g ^ i = σ :=
    ⟨_, pow_finEquivZPowers_symm_apply hfin ⟨σ, hg σ⟩⟩
  have hcocycle : IsMulCocycle₁ f := by
    intro σ τ
    obtain ⟨a, rfl⟩ := hsurj σ
    obtain ⟨b, rfl⟩ := hsurj τ
    rw [← pow_add, hf, hf, hf, hP_add, mul_comm]
  obtain ⟨y, hy⟩ := isMulCoboundary₁_of_isMulCocycle₁_of_aut_to_units f hcocycle
  refine ⟨y, (hy g).trans ?_⟩
  simpa only [pow_one, P, Finset.prod_range_one, pow_zero, one_smul] using hf 1

end TauCeti
