/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Complex.UpperHalfPlane.Polygon.SidePairing.Geometry
import Mathlib.Topology.Compactness.SigmaCompact
import TauCeti.Analysis.Complex.UpperHalfPlane.Polygon.Convex.Sides
import TauCeti.Analysis.Complex.UpperHalfPlane.Topology

/-!
# Locally finite tessellations by a side-paired polygon

Let `σ` be a side pairing of a convex hyperbolic polygon `P`, and let `Γ ≤ PSL(2, ℝ)` contain the
side-pairing maps. If the translates `γ • P` with `γ ∈ Γ` form a locally finite family, they cover
the upper half-plane. Near a point of `P` other than a vertex, `P` and the translates of `P` by the
side-pairing maps contain a neighbourhood, so the union of all translates is a neighbourhood of
each of its points off the countably many translated vertices. Local finiteness makes the union
closed, and the complement of a countable set in `ℍ` is connected and dense; hence the union is
everything. No angle or cycle condition enters, and the vertices may be finite or ideal.

If moreover distinct translates of the interior of `P` are disjoint, then `P` is a fundamental
polygon for `Γ`, and `Γ` is generated by the side-pairing maps: an element of `Γ` carries an
interior point of `P` into a translate by the generated subgroup, and disjointness of interiors
forces the two elements to agree.

These are the covering half of the fundamental-set theorem in Poincaré's polygon theorem, whose
hypotheses include local finiteness and no overlap of the translated interiors, and the statement
that the side pairings of a locally finite fundamental polygon generate the group, which is the
first step in reading off the presentation of `Γ` from the polygon.

## Main results

* `ConvexPolygon.SidePairing.mem_interior_carrier_union_iUnion_smul_carrier`: the polygon and its
  paired translates contain a neighbourhood of each of its points other than a vertex.
* `ConvexPolygon.SidePairing.iUnion_smul_carrier_eq_univ`: locally finite translates by a group
  containing the side-pairing maps cover the upper half-plane.
* `ConvexPolygon.eq_of_smul_interior_inter_smul_carrier_nonempty`: when distinct translated
  interiors are disjoint, two translates one of whose interiors meets the other are equal.
* `ConvexPolygon.SidePairing.closure_range_map_eq`: the side-pairing maps generate the group of a
  locally finite fundamental polygon.

## References

* Alan Beardon, *The Geometry of Discrete Groups*, Graduate Texts in Mathematics 91,
  Springer, 1983, Chapter 9 (locally finite fundamental polygons, side pairings, and Poincaré's
  theorem).
* Svetlana Katok, *Fuchsian Groups*, Chicago Lectures in Mathematics, University of Chicago
  Press, 1992, Chapter 3 (fundamental regions and generators of Fuchsian groups).
* Bernard Maskit, *On Poincaré's theorem for fundamental polygons*, Adv. Math. 7 (1971),
  219–230.
-/

public section

open Set Topology UpperHalfPlane
open scoped MatrixGroups Pointwise

namespace TauCeti.UpperHalfPlane.ConvexPolygon

variable {n : ℕ} [NeZero n] {P : ConvexPolygon n}

/-- **Overlapping translates of a polygon with disjoint translated interiors coincide.** Let
distinct translates of the interior of `P` by `Γ` be disjoint. If the interior of a translate
`g • P` meets a translate `g' • P`, with `g, g' ∈ Γ`, then `g = g'`. -/
theorem eq_of_smul_interior_inter_smul_carrier_nonempty {Γ : Subgroup PSL(2, ℝ)}
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier))
    {g g' : PSL(2, ℝ)} (hg : g ∈ Γ) (hg' : g' ∈ Γ)
    (h : (g • interior P.carrier ∩ g' • P.carrier).Nonempty) : g = g' := by
  obtain ⟨w, hw, hw'⟩ := h
  -- the closed tile `g' • P` is the closure of its interior, which the open set meets
  rw [← P.closure_interior_carrier, ← closure_smul] at hw'
  obtain ⟨v, hv, hv'⟩ := mem_closure_iff.1 hw' _ (isOpen_interior.smul g) hw
  let γ : Γ := ⟨g'⁻¹ * g, Γ.mul_mem (Γ.inv_mem hg') hg⟩
  by_contra hne
  have hγ : γ ≠ 1 := fun h1 ↦ hne (inv_mul_eq_one.1 (congrArg Subtype.val h1)).symm
  have hv'' : g'⁻¹ • v ∈ (g'⁻¹ * g) • interior P.carrier := by
    rw [mul_smul]
    exact smul_mem_smul_set hv
  exact disjoint_left.1 (hdisj γ hγ) hv'' (mem_smul_set_iff_inv_smul_mem.1 hv')

end TauCeti.UpperHalfPlane.ConvexPolygon

namespace TauCeti.UpperHalfPlane.ConvexPolygon.SidePairing

variable {n : ℕ} [NeZero n] {P : ConvexPolygon n} (σ : P.SidePairing)

/-- Near a point of the polygon other than a vertex, the polygon and its translates by the
side-pairing maps together contain a neighbourhood. -/
theorem mem_interior_carrier_union_iUnion_smul_carrier {z : ℍ} (hz : z ∈ P.carrier)
    (hv : ∀ i, P.vertex i ≠ .inl z) :
    z ∈ interior (P.carrier ∪ ⋃ i, σ.map i • P.carrier) := by
  by_cases hzi : z ∈ interior P.carrier
  · exact interior_mono subset_union_left hzi
  -- a boundary point lies on a side, away from its finite endpoints
  have hzf : z ∈ frontier P.carrier := ⟨subset_closure hz, hzi⟩
  obtain ⟨k, hk⟩ := mem_iUnion.1 (P.frontier_carrier ▸ hzf)
  have h := σ.mem_interior_union_smul_carrier_of_mem_side (σ.pair k)
    (by rwa [σ.pair_pair]) (by rw [σ.pair_pair]; exact hv k)
    (by rw [σ.pair_pair]; exact hv (k + 1))
  exact interior_mono (union_subset_union_right _
    (subset_iUnion (fun i ↦ σ.map i • P.carrier) (σ.pair k))) h

/-- **Locally finite translates of a side-paired polygon cover `ℍ`.** If a subgroup `Γ` of
`PSL(2, ℝ)` contains every side-pairing map and its translates of the polygon form a locally
finite family, then these translates cover the upper half-plane. -/
theorem iUnion_smul_carrier_eq_univ {Γ : Subgroup PSL(2, ℝ)} (hmap : ∀ i, σ.map i ∈ Γ)
    (hlf : LocallyFinite fun γ : Γ ↦ (γ : PSL(2, ℝ)) • P.carrier) :
    ⋃ γ : Γ, (γ : PSL(2, ℝ)) • P.carrier = univ := by
  set U := ⋃ γ : Γ, (γ : PSL(2, ℝ)) • P.carrier
  have hUc : IsClosed U := hlf.isClosed_iUnion fun γ ↦ P.isClosed_carrier.smul _
  -- every translate of the polygon together with its paired neighbours stays in `U`
  have hsub (γ : Γ) : (γ : PSL(2, ℝ)) • (P.carrier ∪ ⋃ i, σ.map i • P.carrier) ⊆ U := by
    rw [smul_set_union, smul_set_iUnion]
    refine union_subset (subset_iUnion_of_subset γ subset_rfl) (iUnion_subset fun i ↦ ?_)
    rw [smul_smul]
    exact subset_iUnion_of_subset ⟨_, Γ.mul_mem γ.2 (hmap i)⟩ subset_rfl
  -- the translated vertices in `ℍ` form a countable set `V`
  have : Countable Γ := countable_univ_iff.1
    (hlf.countable_univ fun _ ↦ (P.nonempty_interior_carrier.mono interior_subset).smul_set)
  set V := ⋃ (γ : Γ) (i : Fin n), (γ : PSL(2, ℝ)) • {z : ℍ | P.vertex i = .inl z}
  have hV : V.Countable := countable_iUnion fun γ ↦ countable_iUnion fun i ↦ by
    rw [← image_smul]
    exact (Subsingleton.countable fun _ ha _ hb ↦ Sum.inl_injective (ha.symm.trans hb)).image _
  -- off `V`, the union `U` is a neighbourhood of each of its points
  have hint (y : ℍ) (hy : y ∈ U) (hyV : y ∉ V) : y ∈ interior U := by
    obtain ⟨γ, hγ⟩ := mem_iUnion.1 hy
    obtain ⟨x, hx, rfl⟩ := mem_smul_set.1 hγ
    have hv (i : Fin n) : P.vertex i ≠ .inl x := fun hi ↦
      hyV (mem_iUnion₂.2 ⟨γ, i, smul_mem_smul_set hi⟩)
    have h := smul_mem_smul_set (a := (γ : PSL(2, ℝ)))
      (σ.mem_interior_carrier_union_iUnion_smul_carrier hx hv)
    rw [← interior_smul] at h
    exact interior_mono (hsub γ) h
  -- hence `U` contains the connected dense set `Vᶜ`, and so everything
  obtain ⟨q, hq, hqV⟩ := hV.dense_compl_upperHalfPlane.inter_open_nonempty _ isOpen_interior
    P.nonempty_interior_carrier
  have hqU : q ∈ U := mem_iUnion.2 ⟨1, by simpa using interior_subset hq⟩
  have hVU : Vᶜ ⊆ interior U :=
    hV.isPathConnected_compl_upperHalfPlane.isConnected.isPreconnected.subset_left_of_subset_union
      isOpen_interior hUc.isOpen_compl (disjoint_compl_right.mono_left interior_subset)
      (fun y hy ↦ by
        by_cases hyU : y ∈ U
        · exact Or.inl (hint y hyU hy)
        · exact Or.inr hyU)
      ⟨q, hqV, hint q hqU hqV⟩
  exact eq_univ_of_univ_subset (hV.dense_compl_upperHalfPlane.closure_eq ▸
    closure_minimal (hVU.trans interior_subset) hUc)

/-- **The side pairings generate the group of a locally finite fundamental polygon.** Let a
subgroup `Γ` of `PSL(2, ℝ)` contain every side-pairing map, let its translates of the polygon be
locally finite, and let distinct translates of the interior be disjoint. Then `Γ` is generated
by the side-pairing maps. -/
theorem closure_range_map_eq {Γ : Subgroup PSL(2, ℝ)} (hmap : ∀ i, σ.map i ∈ Γ)
    (hlf : LocallyFinite fun γ : Γ ↦ (γ : PSL(2, ℝ)) • P.carrier)
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier)) :
    Subgroup.closure (range σ.map) = Γ := by
  have hle : Subgroup.closure (range σ.map) ≤ Γ :=
    (Subgroup.closure_le _).2 (range_subset_iff.2 hmap)
  refine le_antisymm hle fun γ hγ ↦ ?_
  -- the translates by the generated subgroup are locally finite, so they cover `ℍ`
  have hcover := σ.iUnion_smul_carrier_eq_univ
    (fun i ↦ Subgroup.subset_closure (mem_range_self i))
    (hlf.comp_injective (Subgroup.inclusion_injective hle))
  obtain ⟨p, hp⟩ := P.nonempty_interior_carrier
  obtain ⟨g, hg⟩ := mem_iUnion.1 (hcover ▸ mem_univ (γ • p))
  -- `γ • p` lies in the interior of `γ • P` and in `g • P`, so these translates coincide
  have hγg : γ = g := P.eq_of_smul_interior_inter_smul_carrier_nonempty hdisj hγ (hle g.2)
    ⟨γ • p, smul_mem_smul_set hp, hg⟩
  exact hγg ▸ g.2

end TauCeti.UpperHalfPlane.ConvexPolygon.SidePairing
