/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Scheme
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic
public import Mathlib.LinearAlgebra.Matrix.Block
import TauCeti.CategoryTheory.Comma.Over

/-!
# Weight-unipotent subgroup schemes of the general linear group

An integer weight `w i` on each coordinate of `GL_N` defines a decreasing filtration. The
unipotent subgroup attached to this filtration consists of the invertible matrices which are
block triangular and induce the identity on every associated-graded weight space. Equivalently,
its `(i,j)` entry is the identity-matrix entry whenever `w i ≤ w j`.

This file represents that subgroup over an arbitrary commutative base ring. The defining ideal
is generated by `Xᵢⱼ - δᵢⱼ` for `w i ≤ w j`. Its Hopf-ideal closure is checked directly: the
relations are stable under matrix multiplication, the identity matrix satisfies them, and the
inverse of a block-unitriangular matrix is block unitriangular.

## Main declarations

* `TauCeti.GeneralLinear.weightUnipotentDefiningHopfIdeal`: the Hopf ideal generated by the
  block-unitriangular relations.
* `TauCeti.GeneralLinear.weightUnipotentGroupScheme`: the resulting finite-type closed subgroup
  scheme of `GL_N`.
* `TauCeti.GeneralLinear.mem_weightUnipotentDefiningPointsSubgroup_iff`: its algebra-valued
  points are the block-triangular matrices acting trivially on the associated graded.

## References

* G. R. Kempf, *Instability in invariant theory*, Annals of Mathematics 108 (1978), §2.
* J. S. Milne, *Algebraic Groups* (2017), Chapter 13.

This advances the dynamic-unipotent route in Layer 7, "Structure theory", of the
ReductiveGroups roadmap by constructing the scheme-level unipotent subgroup attached to a weight
cocharacter.
-/

public section

open AlgebraicGeometry CategoryTheory

namespace TauCeti.GeneralLinear

universe u

variable (R : Type u) [CommRing R] {N : ℕ}

/-- The matrix-coordinate relations saying that entries on and above the weight-block diagonal
agree with the identity matrix. -/
def weightUnipotentRelationSet (w : Fin N → ℤ) :
    Set (coordinateHopfAlgebra R N) :=
  {x | ∃ i j, w i ≤ w j ∧
    x = (genericMatrix R N) i j -
      (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j}

/-- Membership in the weight-unipotent relation set means being a block-unitriangular matrix
relation. -/
@[simp]
theorem mem_weightUnipotentRelationSet_iff (w : Fin N → ℤ)
    (x : coordinateHopfAlgebra R N) :
    x ∈ weightUnipotentRelationSet R w ↔
      ∃ i j, w i ≤ w j ∧
        x = (genericMatrix R N) i j -
          (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j :=
  Iff.rfl

/-- A block-unitriangular coordinate relation belongs to the defining relation set. -/
theorem sub_one_apply_mem_weightUnipotentRelationSet (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i ≤ w j) :
    (genericMatrix R N) i j -
        (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j ∈
      weightUnipotentRelationSet R w :=
  ⟨i, j, hij, rfl⟩

/-- A matrix coordinate on or above the weight-block diagonal is fixed in the quotient by the
explicit weight-unipotent relation ideal. -/
theorem quotient_genericMatrix_apply_of_le (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i ≤ w j) :
    Ideal.Quotient.mkₐ R (Ideal.span (weightUnipotentRelationSet R w))
        ((genericMatrix R N) i j) =
      (1 : Matrix (Fin N) (Fin N)
        (coordinateHopfAlgebra R N ⧸ Ideal.span (weightUnipotentRelationSet R w))) i j := by
  have hrel := Ideal.subset_span
    (sub_one_apply_mem_weightUnipotentRelationSet R w hij)
  by_cases hEq : i = j
  · subst j
    simp only [Matrix.one_apply, ↓reduceIte]
    rw [Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.mk_eq_one_iff_sub_mem]
    simpa [Matrix.one_apply] using hrel
  · simp only [Matrix.one_apply, hEq, ↓reduceIte]
    rw [Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem]
    simpa [Matrix.one_apply, hEq] using hrel

private theorem sum_quotient_genericMatrix_tmul (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i ≤ w j) :
    let J := Ideal.span (weightUnipotentRelationSet R w)
    let q := Ideal.Quotient.mkₐ R J
    (∑ k, q ((genericMatrix R N) i k) ⊗ₜ[R] q ((genericMatrix R N) k j)) =
      if i = j then 1 else 0 := by
  dsimp only
  classical
  by_cases hij' : i = j
  · subst j
    simp only [↓reduceIte]
    rw [Finset.sum_eq_single i]
    · rw [quotient_genericMatrix_apply_of_le R w le_rfl]
      simpa only [Matrix.one_apply, ↓reduceIte] using
        (Algebra.TensorProduct.one_def (R := R)
          (A := coordinateHopfAlgebra R N ⧸ Ideal.span (weightUnipotentRelationSet R w))
          (B := coordinateHopfAlgebra R N ⧸ Ideal.span (weightUnipotentRelationSet R w))).symm
    · intro k _ hki
      by_cases hweight : w i ≤ w k
      · rw [quotient_genericMatrix_apply_of_le R w hweight]
        simp [hki.symm]
      · have hkiw : w k ≤ w i := (lt_of_not_ge hweight).le
        rw [quotient_genericMatrix_apply_of_le R w hkiw]
        simp [hki]
    · simp
  · simp only [hij', ↓reduceIte]
    apply Finset.sum_eq_zero
    intro k _
    by_cases hik : w i ≤ w k
    · rw [quotient_genericMatrix_apply_of_le R w hik]
      by_cases hEq : i = k
      · subst k
        rw [quotient_genericMatrix_apply_of_le R w hij]
        simp [hij']
      · simp [hEq]
    · have hkj : w k ≤ w j := (lt_of_not_ge hik).le.trans hij
      rw [quotient_genericMatrix_apply_of_le R w hkj]
      have hne : k ≠ j := fun hEq ↦ hik (hEq ▸ hij)
      simp [hne]

private theorem comul_sub_one_apply_mem (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i ≤ w j) :
    Coalgebra.comul (R := R)
        ((genericMatrix R N) i j -
          (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j) ∈
      HopfIdeal.leftTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
          (Ideal.span (weightUnipotentRelationSet R w)) ⊔
        HopfIdeal.rightTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
          (Ideal.span (weightUnipotentRelationSet R w)) := by
  let J : Ideal (coordinateHopfAlgebra R N) :=
    Ideal.span (weightUnipotentRelationSet R w)
  let q : coordinateHopfAlgebra R N →ₐ[R] (coordinateHopfAlgebra R N ⧸ J) :=
    Ideal.Quotient.mkₐ R J
  -- Fold the repeated defining span to `J`; this is only the local abbreviation above.
  change Coalgebra.comul (R := R)
      ((genericMatrix R N) i j -
        (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j) ∈
    HopfIdeal.leftTensorIdeal (R := R) (H := coordinateHopfAlgebra R N) J ⊔
      HopfIdeal.rightTensorIdeal (R := R) (H := coordinateHopfAlgebra R N) J
  have hker :
      RingHom.ker (Algebra.TensorProduct.map q q) =
        HopfIdeal.leftTensorIdeal (R := R) (H := coordinateHopfAlgebra R N) J ⊔
          HopfIdeal.rightTensorIdeal (R := R) (H := coordinateHopfAlgebra R N) J := by
    rw [Algebra.TensorProduct.map_ker (f := q) (g := q)
      (Ideal.Quotient.mkₐ_surjective R J) (Ideal.Quotient.mkₐ_surjective R J)]
    rw [← RingHom.ker_coe_toRingHom q]
    simp only [q, Ideal.Quotient.mkₐ_ker]
    rfl
  rw [← hker]
  apply RingHom.mem_ker.mpr
  simp only [Matrix.one_apply]
  simp only [map_sub]
  rw [genericMatrix_apply, coordinateHopfAlgebra_comul_X, map_sum]
  simp only [Algebra.TensorProduct.map_tmul]
  simp only [← genericMatrix_apply]
  rw [sum_quotient_genericMatrix_tmul R w hij]
  by_cases hEq : i = j <;> simp [hEq]

private theorem counit_sub_one_apply {i j : Fin N} :
    Coalgebra.counit (R := R)
      ((genericMatrix R N) i j -
        (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j) = 0 := by
  rw [map_sub, genericMatrix_apply, coordinateHopfAlgebra_counit_X]
  simp only [Matrix.one_apply]
  split <;> simp

private theorem inverse_apply_eq_one_apply_of_weight_le
    {S : Type*} [CommRing S] (w : Fin N → ℤ) (M : Matrix (Fin N) (Fin N) S)
    [Invertible M]
    (hM : ∀ i j, w i ≤ w j → M i j = (1 : Matrix (Fin N) (Fin N) S) i j)
    {i j : Fin N} (hij : w i ≤ w j) :
    M⁻¹ i j = (1 : Matrix (Fin N) (Fin N) S) i j := by
  have htri : M.BlockTriangular (OrderDual.toDual ∘ w) := by
    intro a b hab
    have hw : w a < w b := OrderDual.toDual_lt_toDual.mp hab
    have hne : a ≠ b := fun h ↦ hw.ne (congrArg w h)
    simpa [Matrix.one_apply, hne] using hM a b hw.le
  have hinv := Matrix.blockTriangular_inv_of_blockTriangular htri
  by_cases hwij : w i = w j
  · have hprod := congrArg
      (fun X : Matrix (Fin N) (Fin N) S ↦ X i j)
      (Matrix.inv_mul_of_invertible M)
    rw [Matrix.mul_apply] at hprod
    have hsum :
        (∑ k, M⁻¹ i k * M k j) = M⁻¹ i j := by
      calc
        (∑ k, M⁻¹ i k * M k j) =
            ∑ k, M⁻¹ i k * (1 : Matrix (Fin N) (Fin N) S) k j := by
              apply Finset.sum_congr rfl
              intro k _
              by_cases hik : w i < w k
              · rw [hinv (OrderDual.toDual_lt_toDual.mpr hik)]
                simp
              · rw [hM k j ((not_lt.mp hik).trans_eq hwij)]
        _ = (M⁻¹ * (1 : Matrix (Fin N) (Fin N) S)) i j := by
          rw [Matrix.mul_apply]
        _ = M⁻¹ i j := by rw [Matrix.mul_one]
    exact hsum.symm.trans hprod
  · have hlt : w i < w j := lt_of_le_of_ne hij hwij
    have hne : i ≠ j := fun h ↦ hwij (congrArg w h)
    simpa [Matrix.one_apply, hne] using
      hinv (OrderDual.toDual_lt_toDual.mpr hlt)

private theorem antipode_sub_one_apply_mem (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i ≤ w j) :
    HopfAlgebra.antipode R
        ((genericMatrix R N) i j -
          (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j) ∈
      Ideal.span (weightUnipotentRelationSet R w) := by
  let J : Ideal (coordinateHopfAlgebra R N) :=
    Ideal.span (weightUnipotentRelationSet R w)
  let q : coordinateHopfAlgebra R N →ₐ[R] (coordinateHopfAlgebra R N ⧸ J) :=
    Ideal.Quotient.mkₐ R J
  let Xq : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N ⧸ J) :=
    (genericMatrix R N).map q
  have hXq : ∀ a b, w a ≤ w b →
      Xq a b = (1 : Matrix (Fin N) (Fin N)
        (coordinateHopfAlgebra R N ⧸ J)) a b := by
    intro a b hab
    exact quotient_genericMatrix_apply_of_le R w hab
  have hdetXq : IsUnit Xq.det := by
    simp only [Xq, ← AlgHom.mapMatrix_apply, ← AlgHom.map_det]
    exact (isUnit_det_genericMatrix R N).map q
  let _ : Invertible Xq := Matrix.invertibleOfIsUnitDet Xq hdetXq
  -- Fold the repeated defining span to `J`; this is only the local abbreviation above.
  change HopfAlgebra.antipode R
      ((genericMatrix R N) i j -
        (1 : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N)) i j) ∈ J
  apply (Ideal.Quotient.eq_zero_iff_mem).mp
  rw [map_sub, genericMatrix_apply, coordinateHopfAlgebra_antipode_X]
  have hinv := inverse_apply_eq_one_apply_of_weight_le w Xq hXq hij
  rw [← map_inv_genericMatrix R N q, Matrix.map_apply, genericMatrix_inv_apply] at hinv
  simp only [q, Ideal.Quotient.mkₐ_eq_mk] at hinv
  by_cases hEq : i = j
  · subst j
    simpa [Matrix.one_apply] using sub_eq_zero.mpr hinv
  · simpa [Matrix.one_apply, hEq] using sub_eq_zero.mpr hinv

/-- The Hopf ideal cutting out matrices which are block triangular for `w` and act as the
identity on each associated-graded weight space. -/
noncomputable def weightUnipotentDefiningHopfIdeal (w : Fin N → ℤ) :
    HopfIdeal R (coordinateHopfAlgebra R N) :=
  HopfIdeal.ofSpan (weightUnipotentRelationSet R w)
    (fun x hx => by
      obtain ⟨i, j, hij, rfl⟩ := hx
      exact comul_sub_one_apply_mem R w hij)
    (fun x hx => by
      obtain ⟨i, j, _, rfl⟩ := hx
      exact counit_sub_one_apply R)
    (fun x hx => by
      obtain ⟨i, j, hij, rfl⟩ := hx
      exact antipode_sub_one_apply_mem R w hij)

/-- The underlying ideal is generated by the block-unitriangular coordinate relations. -/
@[simp]
theorem weightUnipotentDefiningHopfIdeal_toIdeal (w : Fin N → ℤ) :
    (weightUnipotentDefiningHopfIdeal R w).toIdeal =
      Ideal.span (weightUnipotentRelationSet R w) := by
  rw [weightUnipotentDefiningHopfIdeal, HopfIdeal.ofSpan_toIdeal]

/-- The coordinate Hopf algebra of the weight-unipotent subgroup attached to `w`. -/
noncomputable abbrev weightUnipotentCoordinateHopfAlgebra (w : Fin N → ℤ) :
    _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (coordinateHopfAlgebra R N)
    (weightUnipotentDefiningHopfIdeal R w)

/-- The affine group scheme represented by the weight-unipotent coordinate Hopf algebra. -/
noncomputable abbrev weightUnipotentGroupScheme (w : Fin N → ℤ) :=
  CommHopfAlgCat.quotientSpec (coordinateHopfAlgebra R N)
    (weightUnipotentDefiningHopfIdeal R w)

/-- The closed immersion from the weight-unipotent subgroup into the named general linear group
scheme. -/
noncomputable def weightUnipotentInclusion (w : Fin N → ℤ) :
    weightUnipotentGroupScheme R w ⟶ groupScheme R N :=
  hopfIdealInclusion R N (weightUnipotentDefiningHopfIdeal R w)

/-- The weight-unipotent inclusion is the quotient-spectrum inclusion followed by the named
identification with `GL_N`. -/
theorem weightUnipotentInclusion_def (w : Fin N → ℤ) :
    weightUnipotentInclusion R w =
      CommHopfAlgCat.quotientSpecι (coordinateHopfAlgebra R N)
          (weightUnipotentDefiningHopfIdeal R w) ≫
        (eqToIso (groupScheme_def R N).symm).hom := by
  rw [weightUnipotentInclusion, hopfIdealInclusion_def]

/-- The weight-unipotent inclusion into `GL_N` is a closed immersion. -/
instance isClosedImmersion_weightUnipotentInclusion (w : Fin N → ℤ) :
    IsClosedImmersion (weightUnipotentInclusion R w).hom.hom.left := by
  rw [weightUnipotentInclusion]
  infer_instance

/-- The subgroup cut out by the weight-unipotent ideal consists exactly of matrices whose
`(i,j)` entry agrees with the identity matrix whenever `w i ≤ w j`. -/
@[simp]
theorem mem_weightUnipotentDefiningPointsSubgroup_iff (w : Fin N → ℤ)
    {A : Type*} [CommRing A] [Algebra R A]
    (g : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R N)
      (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup (coordinateHopfAlgebra R N)
        (weightUnipotentDefiningHopfIdeal R w) (CommAlgCat.of R A) ↔
      ∀ i j, w i ≤ w j →
        (pointsMulEquiv N g : Matrix (Fin N) (Fin N) A) i j =
          (1 : Matrix (Fin N) (Fin N) A) i j := by
  rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff]
  constructor
  · intro h i j hij
    have hrel := h _ (HopfIdeal.mem_toIdeal.mp <|
      (weightUnipotentDefiningHopfIdeal_toIdeal R w).symm ▸
        Ideal.subset_span (sub_one_apply_mem_weightUnipotentRelationSet R w hij))
    rw [map_sub, sub_eq_zero] at hrel
    rw [genericMatrix_apply, ← pointToGeneralLinear_apply, ← pointsMulEquiv_apply] at hrel
    by_cases hEq : i = j
    · subst j
      simpa [Matrix.one_apply] using hrel
    · simpa [Matrix.one_apply, hEq] using hrel
  · intro h x hx
    have hx' : x ∈ Ideal.span (weightUnipotentRelationSet R w) :=
      weightUnipotentDefiningHopfIdeal_toIdeal R w ▸ HopfIdeal.mem_toIdeal.mpr hx
    apply RingHom.mem_ker.mp
    refine (Ideal.span_le.2 ?_) hx'
    rintro y ⟨i, j, hij, rfl⟩
    apply RingHom.mem_ker.mpr
    rw [map_sub, sub_eq_zero, genericMatrix_apply,
      ← pointToGeneralLinear_apply, ← pointsMulEquiv_apply]
    by_cases hEq : i = j
    · subst j
      simpa [Matrix.one_apply] using h i i hij
    · simpa [Matrix.one_apply, hEq] using h i j hij

end TauCeti.GeneralLinear
