/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Category.GradedModuleCat.CartanMap.Ideal
public import TauCeti.Algebra.Category.GradedModuleCat.CartanMap.Matrix

/-!
# Idempotent coordinates on the graded Grothendieck group of finite graded modules

Let `A` be a finite-dimensional algebra over a field `k`, with homogeneous pieces
`𝒜 : ℤ → Submodule k A`, and let `e ∈ 𝒜 0` be an idempotent of degree zero. For a finitely
generated graded `A`-module `M`, the subspaces `e • Mₚ` are finite-dimensional and vanish for all
but finitely many degrees `p`, so they have a graded dimension

```text
gdim_e(M) = ∑ₚ dim_k(e • Mₚ) qᵖ ∈ ℤ[q,q⁻¹].
```

Because `e` is an idempotent of degree zero, `M ↦ e • Mₚ` is exact in each degree, so `gdim_e` is
additive on short exact sequences of graded modules. Shifting the grading multiplies it by a power
of `q`, so it descends to a `ℤ[q,q⁻¹]`-linear coordinate

```text
TauCeti.gradedIdempotentCoordinate : G₀^gr(mod A) ⟶ ℤ[q,q⁻¹]
```

on the Laurent Grothendieck group of finite graded modules, the target of the graded Cartan map
`TauCeti.gradedCartanMap`.

For `e = 1` this is the graded dimension of `M`. In general `e • Mₚ` is the degree-`p` piece of
the summand `e • M`. Suppose the graded simple modules are the shifts `Sᵢ{d}` of modules `Sᵢ`
concentrated in degree zero, and the idempotents `eᵢ` satisfy `dim_k(eᵢ • Sⱼ) = δᵢⱼ`, as for the
vertex idempotents of a basic algebra whose simple modules are one-dimensional. Then additivity
along a graded composition series shows that `dim_k(eᵢ • Mₚ)` counts the composition factors of
`M` isomorphic to `Sᵢ{p}`, so these coordinates read graded composition multiplicities, and in
particular the entries of the graded Cartan matrix. Kronecker-delta coordinates give linear
independence of classes over `ℤ[q,q⁻¹]`.

On the graded projective `Af` generated by an idempotent `f`, the `e`-coordinate of the image
under the graded Cartan map is the graded dimension `∑ₚ dim_k(eAf ∩ 𝒜 p) qᵖ` of the corner `eAf`.
Consequently, in a module basis dual to the idempotent coordinates of `e₁, …, eₙ` and a projective
basis containing the classes `[A fⱼ]`, the graded Cartan matrix has entries
`∑ₚ dim_k(eᵢ A fⱼ ∩ 𝒜 p) qᵖ`.

## Main definitions

* `TauCeti.gradedIdempotentCoordinate`: the induced `ℤ[q,q⁻¹]`-linear coordinate on the graded
  Grothendieck group of finite graded modules.

## Main results

* `TauCeti.gradedIdempotentCoordinate_of`: the coordinate of the class of `M` is `gdim_e(M)`.
* `TauCeti.linearIndependent_laurentK0_of_smulGradedDimension`: classes with Kronecker-delta
  idempotent coordinates are linearly independent over `ℤ[q,q⁻¹]`.
* `TauCeti.coeff_gradedIdempotentCoordinate_gradedCartanMap_ofIdeal_span_singleton`: the
  idempotent coordinates of the graded Cartan map at `[Af]` are the graded dimensions of the
  corners `eAf`.
* `TauCeti.coeff_gradedCartanMatrix_of_ofIdeal_span_singleton`: the entries of the graded Cartan
  matrix in a module basis dual to idempotent coordinates, at a column given by `[A fⱼ]`.

## References

* C. Năstăsescu and F. Van Oystaeyen, *Methods of Graded Rings*, Section 2.3, for graded modules
  and their degree shifts.
* Z. Dancso and A. Licata, "Koszul algebras and flow lattices", Section 2.2, for the graded
  Grothendieck group as a `ℤ[q,q⁻¹]`-module and graded dimensions.
* Ibrahim Assem, Daniel Simson and Andrzej Skowroński, *Elements of the Representation Theory of
  Associative Algebras I*, Chapter III, Section 3, for the ungraded coordinates `dim_k(e M)` on the
  Grothendieck group and the Cartan matrix.
-/

public section

noncomputable section

namespace TauCeti

open CategoryTheory LaurentPolynomial

universe uk uA

/-! ### The coordinate on the graded Grothendieck group -/

section Coordinate

variable {k : Type uk} [Field k] {A : Type uA} [Ring A] [Algebra k A]
  {𝒜 : ℤ → Submodule k A} [Module.Finite k A]

variable {e : A}

/-- The graded dimension of `e • M` as a shift-compatible invariant of finite graded modules. -/
private def smulGradedDimensionInvariant (he : IsIdempotentElem e) (he₀ : e ∈ 𝒜 0) :
    GradedExactStructure.ShiftInvariant (gradedFiniteModulesExactStructure 𝒜)
      (laurentTAut ℤ (LaurentPolynomial ℤ)) where
  obj M := M.obj.smulGradedDimension e
  map_conflation S hS := by
    rw [gradedFiniteModulesExactStructure_conflation_iff] at hS
    have : Module.Finite k (S.map (gradedFiniteModules 𝒜).ι).X₁ :=
      inferInstanceAs (Module.Finite k S.X₁.obj)
    have : Module.Finite k (S.map (gradedFiniteModules 𝒜).ι).X₂ :=
      inferInstanceAs (Module.Finite k S.X₂.obj)
    have : Module.Finite k (S.map (gradedFiniteModules 𝒜).ι).X₃ :=
      inferInstanceAs (Module.Finite k S.X₃.obj)
    exact GradedModuleCat.smulGradedDimension_shortExact he he₀ hS
  map_shift M := by
    -- The restricted shift agrees with the ambient shift `M ↦ M{1}` up to isomorphism.
    have : Module.Finite k
        (((gradedFiniteModules 𝒜).ι ⋙ (GradedModuleCat.shift 𝒜).functor).obj M) :=
      inferInstanceAs (Module.Finite k M.obj)
    have : Module.Finite k
        (((gradedFiniteModulesExactStructure 𝒜).shift.functor ⋙
          (gradedFiniteModules 𝒜).ι).obj M) :=
      inferInstanceAs
        (Module.Finite k ((gradedFiniteModulesExactStructure 𝒜).shift.functor.obj M).obj)
    refine (GradedModuleCat.smulGradedDimension_congr e
      ((gradedFiniteModulesExactStructureShiftFunctorCompιIso (𝒜 := 𝒜)).app M)).trans ?_
    rw [laurentTAut_apply, smul_eq_mul]
    exact M.obj.smulGradedDimension_shiftObj e 1

/-- **The idempotent coordinate** on the graded Grothendieck group of finite graded modules over a
finite-dimensional algebra: the `ℤ[q,q⁻¹]`-linear map sending the class of `M` to the graded
dimension `∑ₚ dim_k(e • Mₚ) qᵖ` of `e • M`, for an idempotent `e` of degree zero. -/
def gradedIdempotentCoordinate (he : IsIdempotentElem e) (he₀ : e ∈ 𝒜 0) :
    LaurentK0.{uA} (gradedFiniteModulesExactStructure 𝒜) →ₗ[LaurentPolynomial ℤ]
      LaurentPolynomial ℤ :=
  LaurentK0.lift _ (smulGradedDimensionInvariant he he₀)

/-- **The idempotent coordinate of a class.** Evaluating `gradedIdempotentCoordinate` on the class
`[M]` of a finite graded module recovers the graded dimension `∑ₚ dim_k(e • Mₚ) qᵖ` of `e • M`. -/
@[simp]
theorem gradedIdempotentCoordinate_of (he : IsIdempotentElem e) (he₀ : e ∈ 𝒜 0)
    (M : (gradedFiniteModules 𝒜).FullSubcategory) :
    gradedIdempotentCoordinate he he₀
        (LaurentK0.of.{uA} (gradedFiniteModulesExactStructure 𝒜) M) =
      M.obj.smulGradedDimension e :=
  LaurentK0.lift_of.{uA} _ M

/-- **Classes with Kronecker-delta idempotent coordinates are linearly independent.** If the
graded dimension of `eᵢ • Sⱼ` is `1` for `i = j` and `0` otherwise, the classes of the finite
graded modules `Sⱼ` are linearly independent over `ℤ[q,q⁻¹]`. -/
theorem linearIndependent_laurentK0_of_smulGradedDimension {I : Type*} {e : I → A}
    (he : ∀ i, IsIdempotentElem (e i)) (he₀ : ∀ i, e i ∈ 𝒜 0)
    (S : I → (gradedFiniteModules 𝒜).FullSubcategory)
    (hne : Pairwise fun i j => (S j).obj.smulGradedDimension (e i) = 0)
    (hself : ∀ i, (S i).obj.smulGradedDimension (e i) = 1) :
    LinearIndependent (LaurentPolynomial ℤ) fun i =>
      LaurentK0.of.{uA} (gradedFiniteModulesExactStructure 𝒜) (S i) :=
  LinearIndependent.of_pairwise_dual_eq_zero_one _
    (fun i => gradedIdempotentCoordinate (he i) (he₀ i))
    (fun i j hij => by simpa using hne hij) (fun i => by simpa using hself i)

end Coordinate

/-! ### The columns of the graded Cartan map at the projectives `Af` -/

section CartanColumn

variable {k : Type uk} [Field k] {A : Type uA} [Ring A] [Algebra k A]
  {𝒜 : ℤ → Submodule k A} [Module.Finite k A] [GradedAlgebra 𝒜] {e f : A}

/-- **The idempotent coordinates of the graded Cartan map at `Af` are graded corner dimensions.**
For idempotents `e` of degree zero and `f`, the coefficient of `qᵖ` in the `e`-coordinate of the
image of `[Af]` in `G₀^gr(mod A)` is `dim_k(eAf ∩ 𝒜 p)`. -/
theorem coeff_gradedIdempotentCoordinate_gradedCartanMap_ofIdeal_span_singleton
    (he : IsIdempotentElem e) (he₀ : e ∈ 𝒜 0) (hf : IsIdempotentElem f)
    (hI : (Ideal.span {f} : Ideal A).IsHomogeneous 𝒜) (p : ℤ) :
    (gradedIdempotentCoordinate he he₀ (gradedCartanMap 𝒜
        (LaurentK0.of.{uA} (gradedFiniteProjectiveModulesExactStructure 𝒜)
          ⟨GradedModuleCat.ofIdeal 𝒜 (Ideal.span {f}) hI,
            gradedFiniteProjectiveModules_ofIdeal_span_singleton hf hI⟩))).coeff p =
      Module.finrank k ↥(cornerSubmodule k e f ⊓ 𝒜 p) := by
  rw [gradedCartanMap_of, gradedIdempotentCoordinate_of]
  exact GradedModuleCat.coeff_smulGradedDimension_ofIdeal_span_singleton he he₀ hf hI p

/-- **The graded Cartan matrix in idempotent coordinates.** Let `bM` be a basis of
`G₀^gr(mod A)` dual to the idempotent coordinates of degree-zero idempotents `eᵢ`, in the sense
that the `eᵢ`-coordinate of `bM i'` is `1` for `i' = i` and `0` otherwise, and let the
`j`-th projective basis vector be the class of `A fⱼ` for an idempotent `fⱼ`. Then the coefficient
of `qᵖ` in the `(i, j)` entry of the graded Cartan matrix is `dim_k(eᵢ A fⱼ ∩ 𝒜 p)`. -/
theorem coeff_gradedCartanMatrix_of_ofIdeal_span_singleton {I J : Type*} [Fintype I] [Finite J]
    (bP : Module.Basis I (LaurentPolynomial ℤ)
      (LaurentK0.{uA} (gradedFiniteProjectiveModulesExactStructure 𝒜)))
    (bM : Module.Basis J (LaurentPolynomial ℤ)
      (LaurentK0.{uA} (gradedFiniteModulesExactStructure 𝒜)))
    {e : J → A} (he : ∀ i, IsIdempotentElem (e i)) (he₀ : ∀ i, e i ∈ 𝒜 0)
    (hne : Pairwise fun i i' => gradedIdempotentCoordinate (he i) (he₀ i) (bM i') = 0)
    (hself : ∀ i, gradedIdempotentCoordinate (he i) (he₀ i) (bM i) = 1)
    (j : I) (hf : IsIdempotentElem f) (hI : (Ideal.span {f} : Ideal A).IsHomogeneous 𝒜)
    (hj : bP j = LaurentK0.of.{uA} (gradedFiniteProjectiveModulesExactStructure 𝒜)
      ⟨GradedModuleCat.ofIdeal 𝒜 (Ideal.span {f}) hI,
        gradedFiniteProjectiveModules_ofIdeal_span_singleton hf hI⟩)
    (i : J) (p : ℤ) :
    (gradedCartanMatrix 𝒜 bP bM i j).coeff p =
      Module.finrank k ↥(cornerSubmodule k (e i) f ⊓ 𝒜 p) := by
  -- The `i`-th coordinate function of `bM` is the idempotent coordinate of `e i`.
  have hcoord : bM.coord i = gradedIdempotentCoordinate (he i) (he₀ i) := by
    classical
    refine bM.ext fun i' => ?_
    rw [Module.Basis.coord_apply, Module.Basis.repr_self, Finsupp.single_apply]
    split_ifs with h
    · rw [h, hself]
    · rw [hne (Ne.symm h)]
  rw [gradedCartanMatrix_apply, ← Module.Basis.coord_apply, hcoord, hj]
  exact coeff_gradedIdempotentCoordinate_gradedCartanMap_ofIdeal_span_singleton
    (he i) (he₀ i) hf hI p

end CartanColumn

end TauCeti
