/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Quadratic.GenusCharacter.PrincipalGenus
public import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.NarrowClassGroup
import TauCeti.NumberTheory.NumberField.Quadratic.Norm
import TauCeti.NumberTheory.Multiquadratic.Quadratic.Ramification

/-!
# The ordinary `2`-rank of a real quadratic field

Let `K = ℚ(√d)` with `d > 0` squarefree, and let `D = ∏ P ∈ s, P` be the factorization of its
fundamental discriminant into prime discriminants, so that `t = #s` rational primes ramify in `K`.
Genus theory gives the narrow `2`-rank `2-rank Cl⁺(K) = t - 1`
(`narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one`), and the ordinary `2`-rank is `t - 1` or `t - 2`
(`twoRank_eq_ncard_ramifiedPrimes_sub_one_or_sub_two`). This file decides which:

`2-rank Cl(K) = t - 1  ↔  every prime discriminant dividing D is positive`,

and otherwise `2-rank Cl(K) = t - 2`.

The kernel of the forgetful surjection `Cl⁺(K) → Cl(K)` is generated by the narrow class `[θ]⁺` of
the principal ideal `(θ)`, `θ² = d` (`NumberField.mkPrincipal_eq_one_or_eq_mkPrincipal_gen`), and
a surjection keeps the `2`-rank exactly when its kernel consists of squares
(`MonoidHom.twoRank_eq_twoRank_iff_ker_le_square`). By the principal genus theorem
(`isSquare_iff_forall_genusCharFunNarrowClassGroupHom_eq_one`) it remains to evaluate the genus
characters on `[θ]⁺`, and this is the arithmetic heart of the file:

`χ_P([θ]⁺) = sign P` for every `P ∈ s`.

The generator `θ` itself has norm `-d`, which is not coprime to `D`, so the character is
evaluated instead at `x = 1 + 2θ`. Its norm `1 - 4d` is negative, which puts `(x)` in the narrow
class of `(θ)` (`NumberField.mkPrincipal_eq_mkPrincipal_gen_of_norm_neg`), and coprime to `4d`,
hence to `D`. For a generator `x` whose norm `n` is coprime to `P`, the genus character at the
ideal `(x)` is `χ_P(|n|) = χ_P(sign n) · χ_P(n)`, and `χ_P(n) = 1` because `n` is a norm
(`genusCharFunNarrowClassGroupHom_mkPrincipal`). So `χ_P([θ]⁺) = χ_P(-1)`, and the character of a
prime discriminant is odd exactly when the discriminant is negative
(`primeDiscriminantCharFun_neg_one`).

In the dictionary between narrow classes and sign patterns on the prime discriminants, `[θ]⁺` is
thus the pattern `(sign P)_{P ∈ s}`. This is the pattern that complex conjugation puts on the
square roots `√P` in the genus field. Identifying the ordinary genus field of a real quadratic
field with the corresponding fixed field is not done here.

The criterion is classical: the ordinary and narrow `2`-ranks agree exactly when `-1` is a norm
from `K` everywhere locally, that is, when no prime `p ≡ 3 [MOD 4]` divides `d`. See
F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2, and D. A. Cox,
*Primes of the Form x² + ny²*, §6.A.

## Main results

* `TauCeti.Multiquadratic.genusCharFunNarrowClassGroupHom_mkPrincipal`: the genus character of a
  principal class `[x]⁺` with norm coprime to `P` is `χ_P(sign N(x))`.
* `TauCeti.Multiquadratic.genusCharFunNarrowClassGroupHom_mkPrincipal_gen`: for `d > 0`,
  `χ_P([θ]⁺) = sign P`.
* `TauCeti.Multiquadratic.isSquare_mkPrincipal_gen_iff` and
  `TauCeti.Multiquadratic.ker_toClassGroup_le_square_iff`: `[θ]⁺`, equivalently the whole kernel
  of `Cl⁺(K) → Cl(K)`, consists of squares exactly when every `P ∈ s` is positive.
* `TauCeti.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one_iff` and
  `TauCeti.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_two_of_neg`: the ordinary `2`-rank
  of a real quadratic field.
* `TauCeti.Multiquadratic.twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three` and
  `TauCeti.Multiquadratic.twoRank_eq_one_of_minpoly_eq_X_sq_sub_thirty_four`: `ℚ(√3)` has
  `2`-rank `0 = t - 2`, and `ℚ(√34)` has `2`-rank `1 = t - 1`.
-/

public section

open Polynomial NumberField
open scoped NumberField nonZeroDivisors

namespace TauCeti.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-! ### Genus characters of principal classes -/

/-- **The genus character of a principal class is the character at the sign of the norm.** Let
`K = ℚ(√d)` with a prime-discriminant factorization `s` of its discriminant, and let `x` be a
nonzero algebraic integer whose norm `n` is coprime to `P ∈ s`. Then the genus character at `P` of
the narrow class of `(x)` is `χ_P(sign n)`: it is `1` when `n > 0` and `χ_P(-1)` when `n < 0`. -/
theorem genusCharFunNarrowClassGroupHom_mkPrincipal {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) {P : ℤ} (hP : P ∈ s) {x : 𝓞 K} (hx : x ≠ 0)
    (hcop : IsCoprime (Algebra.norm ℤ x) P) :
    ((genusCharFunNarrowClassGroupHom hs heven hprod hmin hgen hsf
        (Finset.singleton_subset_iff.mpr hP)
        (NarrowClassGroup.mkPrincipal
          (Units.mk0 (x : K) (RingOfIntegers.coe_ne_zero_iff.mpr hx))) : ℤˣ) : ℤ) =
      primeDiscriminantCharFun P (Algebra.norm ℤ x).sign := by
  have hI : Ideal.span {x} ∈ (Ideal (𝓞 K))⁰ := by
    rw [mem_nonZeroDivisors_iff_ne_zero, ne_eq, Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot]
    exact hx
  have habs : (Ideal.absNorm (Ideal.span {x}) : ℤ) = ((Algebra.norm ℤ x).natAbs : ℤ) := by
    rw [Ideal.absNorm_span_singleton]
  rw [NarrowClassGroup.mkPrincipal_coe_eq_mk0 hx (I := ⟨Ideal.span {x}, hI⟩) rfl,
    genusCharFunNarrowClassGroupHom_mk0_eq_primeDiscriminantCharFun_absNorm hs heven hprod hmin
      hgen hsf _ hI P hP (by rw [habs, Int.natCast_natAbs]; exact hcop.abs_left), habs,
    ← Int.sign_mul_self_eq_natAbs, primeDiscriminantCharFun_mul_right,
    primeDiscriminantCharFun_norm_eq_one hs heven hprod hmin hgen hsf hP x hcop, mul_one]

/-- **The genus characters of `[θ]⁺` are the signs of the prime discriminants.** For a real
quadratic field `K = ℚ(√d)`, `d > 0`, presented by `θ² = d`, the genus character at each prime
discriminant `P ∈ s` takes the value `sign P` on the narrow class of the principal ideal `(θ)`. -/
theorem genusCharFunNarrowClassGroupHom_mkPrincipal_gen {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 0 < d) {P : ℤ} (hP : P ∈ s) :
    ((genusCharFunNarrowClassGroupHom hs heven hprod hmin hgen hsf
        (Finset.singleton_subset_iff.mpr hP)
        (NarrowClassGroup.mkPrincipal (Units.mk0 (θ : K) (coe_gen_ne_zero hmin))) : ℤˣ) : ℤ) =
      P.sign := by
  set x : 𝓞 K := 1 + 2 * θ with hxdef
  have hnormQ : Algebra.norm ℚ (x : K) = 1 - 4 * (d : ℚ) := by
    have hxK : (x : K) = ((1 : ℚ) : K) + ((2 : ℚ) : K) * (θ : K) := by
      rw [hxdef]
      push_cast
      rfl
    rw [hxK, norm_add_mul_gen hmin hgen]
    ring
  have hnorm : Algebra.norm ℤ x = 1 - 4 * d := by
    have h := hnormQ
    rw [← Algebra.coe_norm_int] at h
    exact_mod_cast h
  have hx : x ≠ 0 := by
    intro h0
    rw [h0] at hnormQ
    simp only [map_zero, Algebra.norm_zero] at hnormQ
    have h1 : (1 : ℤ) = 4 * d := by exact_mod_cast (by linarith : (1 : ℚ) = 4 * d)
    omega
  -- `P` divides `D`, which divides `4d`, and `1 - 4d` is coprime to `4d`.
  have hdvd : P ∣ 4 * d := by
    refine (Finset.dvd_prod_of_mem (fun P => P) hP).trans ?_
    rw [hprod]
    by_cases h4 : d % 4 = 1
    · rw [fundamentalDiscriminant_of_mod_four_eq_one h4]
      exact Dvd.intro_left 4 rfl
    · rw [fundamentalDiscriminant_of_mod_four_ne_one h4]
  have hcop : IsCoprime (Algebra.norm ℤ x) P := by
    rw [hnorm]
    exact IsCoprime.of_isCoprime_of_dvd_right ⟨1, 1, by ring⟩ hdvd
  have hclass : NarrowClassGroup.mkPrincipal
      (Units.mk0 (x : K) (RingOfIntegers.coe_ne_zero_iff.mpr hx)) =
      NarrowClassGroup.mkPrincipal (Units.mk0 (θ : K) (coe_gen_ne_zero hmin)) := by
    refine mkPrincipal_eq_mkPrincipal_gen_of_norm_neg hmin hgen ?_
    have hd1 : (1 : ℚ) ≤ d := by exact_mod_cast (show (1 : ℤ) ≤ d by omega)
    rw [Units.val_mk0, hnormQ]
    linarith
  rw [← hclass,
    genusCharFunNarrowClassGroupHom_mkPrincipal hs heven hprod hmin hgen hsf hP hx hcop, hnorm,
    Int.sign_eq_neg_one_of_neg (by omega), primeDiscriminantCharFun_neg_one (hs P hP)]

/-! ### The kernel of `Cl⁺(K) → Cl(K)` in the principal genus -/

/-- **`[θ]⁺` is a square exactly when every prime discriminant is positive.** For a real quadratic
field `K = ℚ(√d)` with prime-discriminant factorization `s`, the narrow class of `(θ)` lies in
`Cl⁺(K)²` if and only if every `P ∈ s` is positive. -/
theorem isSquare_mkPrincipal_gen_iff {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 0 < d) :
    IsSquare (NarrowClassGroup.mkPrincipal (Units.mk0 (θ : K) (coe_gen_ne_zero hmin))) ↔
      ∀ P ∈ s, 0 < P := by
  rw [isSquare_iff_forall_genusCharFunNarrowClassGroupHom_eq_one hs heven hprod hmin hgen hsf]
  refine forall₂_congr fun P hP => ?_
  rw [Units.ext_iff, Units.val_one,
    genusCharFunNarrowClassGroupHom_mkPrincipal_gen hs heven hprod hmin hgen hsf hd hP,
    Int.sign_eq_one_iff_pos]

/-- **The narrow defect lies in the principal genus exactly when every prime discriminant is
positive.** For a real quadratic field `K = ℚ(√d)` with prime-discriminant factorization `s`, the
kernel of the forgetful surjection `Cl⁺(K) → Cl(K)` consists of squares if and only if every
`P ∈ s` is positive. -/
theorem ker_toClassGroup_le_square_iff {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 0 < d) :
    MonoidHom.ker (NarrowClassGroup.toClassGroup (K := K)) ≤
        Subgroup.square (NarrowClassGroup K) ↔
      ∀ P ∈ s, 0 < P := by
  rw [← isSquare_mkPrincipal_gen_iff hs heven hprod hmin hgen hsf hd,
    NarrowClassGroup.toClassGroup_ker]
  refine ⟨fun h => h ⟨_, rfl⟩, ?_⟩
  rintro h _ ⟨x, rfl⟩
  rcases mkPrincipal_eq_one_or_eq_mkPrincipal_gen hmin hgen x with h1 | h1
  · rw [h1]
    exact Subgroup.one_mem _
  · rwa [h1, Subgroup.mem_square]

/-! ### The ordinary `2`-rank -/

/-- **The ordinary `2`-rank of a real quadratic field is `t - 1` exactly when every prime
discriminant is positive.** Let `K = ℚ(√d)` with `d > 0` squarefree, let `s` be the
prime-discriminant factorization of its discriminant, and let `t` be the number of rational primes
ramifying in `K`. Then `2-rank Cl(K) = t - 1` if and only if every `P ∈ s` is positive. -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_one_iff {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 0 < d) :
    TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 ↔ ∀ P ∈ s, 0 < P := by
  rw [← ker_toClassGroup_le_square_iff hs heven hprod hmin hgen hsf hd,
    ← MonoidHom.twoRank_eq_twoRank_iff_ker_le_square _
      NarrowClassGroup.toClassGroup_surjective,
    ← narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hsf,
    TauCeti.ClassGroup.twoRank_def, NarrowClassGroup.twoRank_def, TauCeti.twoRank_def,
    TauCeti.twoRank_def]

/-- **A negative prime discriminant drops the ordinary `2`-rank to `t - 2`.** For a real quadratic
field `K = ℚ(√d)` whose discriminant has a negative prime-discriminant factor `P ∈ s`, the
`2`-rank of `Cl(K)` is `t - 2`, where `t` is the number of ramified rational primes. -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_two_of_neg {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 0 < d) {P : ℤ} (hP : P ∈ s) (hneg : P < 0) :
    TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 2 := by
  refine (twoRank_eq_ncard_ramifiedPrimes_sub_one_or_sub_two
    (finrank_rat_eq_two hmin hgen)).resolve_left fun h => ?_
  have hpos :=
    (twoRank_eq_ncard_ramifiedPrimes_sub_one_iff hs heven hprod hmin hgen hsf hd).mp h P hP
  omega

/-! ### Worked examples -/

/-- **`ℚ(√3)` has class-group `2`-rank `0`.** Its discriminant `12 = (-4) · (-3)` has two negative
prime-discriminant factors, so two primes ramify and the `2`-rank is `t - 2 = 0`, one less than
the narrow `2`-rank `t - 1 = 1`. -/
theorem twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three
    (hmin : minpoly ℤ θ = X ^ 2 - C (3 : ℤ)) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    TauCeti.ClassGroup.twoRank (𝓞 K) = 0 := by
  have hsf : Squarefree (3 : ℤ) := by
    rw [← Int.squarefree_natAbs]
    exact (by decide : Nat.Prime 3).squarefree
  have hs : ∀ P ∈ ({-4, -3} : Finset ℤ), IsPrimeDiscriminant P := by
    intro P hP
    fin_cases hP
    · exact isPrimeDiscriminant_neg_four
    · simpa [oddPrimeDiscriminant_of_mod_four_eq_three (by norm_num : 3 % 4 = 3)]
        using isPrimeDiscriminant_oddPrimeDiscriminant (p := 3) (by decide) (by decide)
  have heven : ∀ P ∈ ({-4, -3} : Finset ℤ), ∀ Q ∈ ({-4, -3} : Finset ℤ),
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q := by
    intro P hP Q hQ
    fin_cases hP <;> fin_cases hQ <;> simp only [IsEvenPrimeDiscriminant] <;> decide
  have hprod : ∏ P ∈ ({-4, -3} : Finset ℤ), P = fundamentalDiscriminant (3 : ℤ) := by
    rw [Finset.prod_pair (by decide : (-4 : ℤ) ≠ -3),
      fundamentalDiscriminant_of_mod_four_ne_one (by decide : (3 : ℤ) % 4 ≠ 1)]
    norm_num
  have hncard : (ramifiedPrimes K).ncard = 2 := by
    rw [ncard_ramifiedPrimes_eq_card hmin hgen hsf hs heven hprod,
      Finset.card_pair (by decide : (-4 : ℤ) ≠ -3)]
  rw [twoRank_eq_ncard_ramifiedPrimes_sub_two_of_neg hs heven hprod hmin hgen hsf (by norm_num)
    (P := -4) (by simp) (by norm_num), hncard]

/-- **`ℚ(√34)` has class-group `2`-rank `1`.** Its discriminant `136 = 8 · 17` has only positive
prime-discriminant factors, so the `2`-rank is `t - 1 = 1`, with `t = 2` ramified primes. This
does not follow from `twoRank_eq_ncard_ramifiedPrimes_sub_one_of_exists_norm_eq_neg_one`: the
negative Pell equation `x² - 34 y² = -1` has no integer solution, so no unit of `ℚ(√34)` has norm
`-1`, although `-1 = (3/5)² - 34 (1/5)²` is a norm from the field. -/
theorem twoRank_eq_one_of_minpoly_eq_X_sq_sub_thirty_four
    (hmin : minpoly ℤ θ = X ^ 2 - C (34 : ℤ)) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    TauCeti.ClassGroup.twoRank (𝓞 K) = 1 := by
  have hsf : Squarefree (34 : ℤ) := by
    rw [← Int.squarefree_natAbs]
    simpa using (Nat.squarefree_mul (by decide : Nat.Coprime 2 17)).mpr
      ⟨(by decide : Nat.Prime 2).squarefree, (by decide : Nat.Prime 17).squarefree⟩
  have hs : ∀ P ∈ ({8, 17} : Finset ℤ), IsPrimeDiscriminant P := by
    intro P hP
    fin_cases hP
    · exact isPrimeDiscriminant_eight
    · simpa [oddPrimeDiscriminant_of_mod_four_eq_one (by norm_num : 17 % 4 = 1)]
        using isPrimeDiscriminant_oddPrimeDiscriminant (p := 17) (by decide) (by decide)
  have heven : ∀ P ∈ ({8, 17} : Finset ℤ), ∀ Q ∈ ({8, 17} : Finset ℤ),
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q := by
    intro P hP Q hQ
    fin_cases hP <;> fin_cases hQ <;> simp only [IsEvenPrimeDiscriminant] <;> decide
  have hprod : ∏ P ∈ ({8, 17} : Finset ℤ), P = fundamentalDiscriminant (34 : ℤ) := by
    rw [Finset.prod_pair (by decide : (8 : ℤ) ≠ 17),
      fundamentalDiscriminant_of_mod_four_ne_one (by decide : (34 : ℤ) % 4 ≠ 1)]
    norm_num
  have hncard : (ramifiedPrimes K).ncard = 2 := by
    rw [ncard_ramifiedPrimes_eq_card hmin hgen hsf hs heven hprod,
      Finset.card_pair (by decide : (8 : ℤ) ≠ 17)]
  have hrank := (twoRank_eq_ncard_ramifiedPrimes_sub_one_iff hs heven hprod hmin hgen hsf
    (by norm_num)).mpr (by simp)
  rw [hrank, hncard]

end TauCeti.Multiquadratic
