/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.Coxeter

/-!
# A transcribed presentation of the second Fischer group

This file records presentation `GPLTable.Fi23.1` from Roderik Lindenbergh's Group Presentations
Library as a `TauCeti.GroupPresentation`, together with the exact source, generator convention,
transcription notes, expected counts, and decidable checks on the transcription.

The presentation uses the Coxeter graph

```text
a --3-- b --3-- c --3-- d --3-- e --3-- f --3-- g --3-- j
                              |
                              3
                              |
                              h --3-- i
```

where all ten generators are involutions and every omitted edge has label `2`. The source encodes
this graph by the two paths `a3b3c3d3e3f3g3j,d3h3i`. It then appends

```text
(d c b d e f d h i)^10,  (a b c d e f h)^9.
```

Thus the graph contributes ten square relations, nine label-three relations, and thirty-six
omitted-edge relations. With the two appended words, the presentation has `57` relators and its
compiled words have `371` signed letters. The theorems below check those figures and cyclic
reduction from the transcribed data.

The library identifies this record as a presentation of `Fi₂₃` originating in Praeger--Soicher,
whose construction uses low-rank representations and graphs for sporadic groups. As a separate
computational check, GAP 4.15.1 enumerates `31671` cosets of the subgroup generated by `a` through
`i`; the source identifies that subgroup as `2·Fi₂₂`, and `31671` is its index in `Fi₂₃`. This
computation is provenance rather than a Lean theorem: this file asserts no order, finiteness,
simplicity, or identification result.

## Independent source-to-Lean read-through

An independent read-through used the bytes of `gpl.g` whose SHA-256 digest is
`8b90a7a65317a585b5b74d015083bd2fa3db8a969c117a220d00d7e8773103c8`. The exact source record is

```text
presdef := [ "a3b3c3d3e3f3g3j,d3h3i", ,
    "(dcbdefdhi)^(10),(abcdefh)^9",,  ],
```

With `GPL_PCE := true`, `DeCoxList` and its calls to `AddTrivialRelations` and
`AddNonEdgeRelations` expand that record. The theorem below records the same relations regrouped
by kind: entries 1--10 are the squares of `a,b,c,d,e,f,g,h,i,j`; entries 11--19 are
`(ab)³,(bc)³,(cd)³,(de)³,(ef)³,(fg)³,(gj)³,(dh)³,(hi)³`; and entries 20--55 are the exponent-two
pairs

```text
ac,ad,ae,af,ag,ah,ai,aj, bd,be,bf,bg,bh,bi,bj, ce,cf,cg,ch,ci,cj,
df,dg,di,dj, eg,eh,ei,ej, fh,fi,fj, gh,gi, hj,ij.
```

Entries 56 and 57 are `(dcbdefdhi)¹⁰` and `(abcdefh)⁹`. Translating source letters to zero-based
generator indices gives exactly `fi23Presentation_relatorLetters`: there is no change to any word
or exponent and no dropped or duplicated relation, only the presentation-irrelevant regrouping by
kind just described.

The row publishes an equation for each of its fields: the transcribed relator expressions with
their generator indices written out, and the provenance a manifest row exists to record. Together
with `TauCeti.GroupPresentation.relators_def` and `TauCeti.GroupPresentation.mem_relatorSet_iff`
the first of those determines the compiled words and the relations defining the presented group, so
a consumer reasons about the row without unfolding it.

## The graph itself, and not only its expansion

The graph is recorded directly as the edge list `TauCeti.Sporadic.fi23Edges` and the simply laced
Coxeter matrix it determines. The generated Coxeter relations are compared with the transcribed
relations by compiled-word membership, accounting for their different expressions and ordering.

The row presents the quotient of the Coxeter group of its graph obtained by imposing the two
additional relations from the source.

## Main definitions and results

* `TauCeti.Sporadic.fi23Presentation`: the GPL finite presentation of the Fischer group `Fi₂₃`.
* `TauCeti.Sporadic.fi23Presentation_transcribed` and the equations for the remaining fields: the
  characterization of the row.
* `TauCeti.Sporadic.fi23Presentation_relatorLetters`: the fifty-seven compiled words checked
  against the decoder output in the independent source-to-Lean read-through.
* `TauCeti.Sporadic.fi23Presentation_map_length_relators`,
  `TauCeti.Sporadic.fi23Presentation_totalLength` and
  `TauCeti.Sporadic.fi23Presentation_relatorsCyclicallyReduced`: the three checks on the compiled
  words.
* `TauCeti.Sporadic.fi23Edges` and `TauCeti.Sporadic.fi23CoxeterMatrix`: the graph the source's two
  paths encode, and its Coxeter matrix.
* `TauCeti.Sporadic.fi23Presentation_mem_map_toWord_iff`: the transcribed relations are the ones
  that matrix generates, together with the two appended words.
* `TauCeti.Sporadic.fi23MulEquivPresentedGroupCoxeterAppend`: the row presents the Coxeter group of
  the graph cut down by those two words.

## References

* R. Lindenbergh, *Group Presentations Library*, version 1.0, record `GPLTable.Fi23.1`,
  <https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g>.
* C. E. Praeger and L. H. Soicher, *Low Rank Representations and Graphs for Sporadic Groups*,
  Cambridge University Press, 1997, Chapter 4, doi:10.1017/CBO9780511526039.005.
* The presentation-row characterization and audit theorem scaffold is adapted from the Janko-row
  formalization in <https://github.com/TauCetiProject/TauCeti/pull/5283>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 10) := .gen 0

private abbrev b : Relator (Fin 10) := .gen 1

private abbrev c : Relator (Fin 10) := .gen 2

private abbrev d : Relator (Fin 10) := .gen 3

private abbrev e : Relator (Fin 10) := .gen 4

private abbrev f : Relator (Fin 10) := .gen 5

private abbrev g : Relator (Fin 10) := .gen 6

private abbrev h : Relator (Fin 10) := .gen 7

private abbrev i : Relator (Fin 10) := .gen 8

private abbrev j : Relator (Fin 10) := .gen 9

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The ten involution relations and the nine labeled-edge relations decoded from the two Coxeter
paths `a3b3c3d3e3f3g3j` and `d3h3i` in `GPLTable.Fi23.1`. -/
private def fi23NodeAndEdgeRelators : List (Relator (Fin 10)) :=
  [ .pow a 2,
    .pow b 2,
    .pow c 2,
    .pow d 2,
    .pow e 2,
    .pow f 2,
    .pow g 2,
    .pow h 2,
    .pow i 2,
    .pow j 2,
    .pow (a ⬝ b) 3,
    .pow (b ⬝ c) 3,
    .pow (c ⬝ d) 3,
    .pow (d ⬝ e) 3,
    .pow (e ⬝ f) 3,
    .pow (f ⬝ g) 3,
    .pow (g ⬝ j) 3,
    .pow (d ⬝ h) 3,
    .pow (h ⬝ i) 3 ]

/-- The thirty-six omitted-edge relations decoded from the two Coxeter paths in
`GPLTable.Fi23.1`. Each omitted edge has label two. -/
private def fi23NonedgeRelators : List (Relator (Fin 10)) :=
  [ .pow (a ⬝ c) 2,
    .pow (a ⬝ d) 2,
    .pow (a ⬝ e) 2,
    .pow (a ⬝ f) 2,
    .pow (a ⬝ g) 2,
    .pow (a ⬝ h) 2,
    .pow (a ⬝ i) 2,
    .pow (a ⬝ j) 2,
    .pow (b ⬝ d) 2,
    .pow (b ⬝ e) 2,
    .pow (b ⬝ f) 2,
    .pow (b ⬝ g) 2,
    .pow (b ⬝ h) 2,
    .pow (b ⬝ i) 2,
    .pow (b ⬝ j) 2,
    .pow (c ⬝ e) 2,
    .pow (c ⬝ f) 2,
    .pow (c ⬝ g) 2,
    .pow (c ⬝ h) 2,
    .pow (c ⬝ i) 2,
    .pow (c ⬝ j) 2,
    .pow (d ⬝ f) 2,
    .pow (d ⬝ g) 2,
    .pow (d ⬝ i) 2,
    .pow (d ⬝ j) 2,
    .pow (e ⬝ g) 2,
    .pow (e ⬝ h) 2,
    .pow (e ⬝ i) 2,
    .pow (e ⬝ j) 2,
    .pow (f ⬝ h) 2,
    .pow (f ⬝ i) 2,
    .pow (f ⬝ j) 2,
    .pow (g ⬝ h) 2,
    .pow (g ⬝ i) 2,
    .pow (h ⬝ j) 2,
    .pow (i ⬝ j) 2 ]

/-- The nine edges of the `Fi₂₃` Coxeter graph, in the order the source's two paths
`a3b3c3d3e3f3g3j` and `d3h3i` list them. The numbering is `a, …, j = 0, …, 9`, and each pair is
oriented along its path. -/
def fi23Edges : List (Fin 10 × Fin 10) :=
  [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 9), (3, 7), (7, 8)]

/-- The nine edges, in source order. The body is sealed, so this equation is what lets a consumer
reduce the graph — and with it the membership test of
`TauCeti.Sporadic.fi23CoxeterMatrix_apply` — to the pairs the source's two paths draw. -/
@[simp]
theorem fi23Edges_def :
    fi23Edges = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 9), (3, 7), (7, 8)] := by
  rw [fi23Edges]

/-- The Coxeter matrix of the `Fi₂₃` graph, the simply laced matrix of its edge list: diagonal
entries are one, an edge has label three, and every other pair has label two. This is the
`m`-labelled data the source's two paths encode, before any expansion into relations. -/
def fi23CoxeterMatrix : CoxeterMatrix (Fin 10) := coxeterMatrixOfEdges fi23Edges

/-- Evaluation of the `Fi₂₃` Coxeter matrix directly from its edge list. -/
@[simp]
theorem fi23CoxeterMatrix_apply (i j : Fin 10) :
    fi23CoxeterMatrix i j =
      if i = j then 1 else if (i, j) ∈ fi23Edges ∨ (j, i) ∈ fi23Edges then 3 else 2 := by
  rw [fi23CoxeterMatrix, coxeterMatrixOfEdges_apply]

/-- The two words following the Coxeter paths in `GPLTable.Fi23.1`: the source appends them to the
relations its diagram encodes. -/
def fi23AdditionalRelators : List (Relator (Fin 10)) :=
  [ .pow (d ⬝ c ⬝ b ⬝ d ⬝ e ⬝ f ⬝ d ⬝ h ⬝ i) 10,
    .pow (a ⬝ b ⬝ c ⬝ d ⬝ e ⬝ f ⬝ h) 9 ]

/-- The two appended words, with their generator indices written out. The body is sealed and is
written with this file's private letter abbreviations, so this equation is what publishes the two
words `(dcbdefdhi)¹⁰` and `(abcdefh)⁹` themselves. -/
@[simp]
theorem fi23AdditionalRelators_def :
    fi23AdditionalRelators =
      [ .pow (.gen 3 ⬝ .gen 2 ⬝ .gen 1 ⬝ .gen 3 ⬝ .gen 4 ⬝ .gen 5 ⬝ .gen 3 ⬝ .gen 7 ⬝ .gen 8) 10,
        .pow (.gen 0 ⬝ .gen 1 ⬝ .gen 2 ⬝ .gen 3 ⬝ .gen 4 ⬝ .gen 5 ⬝ .gen 7) 9 ] := by
  rw [fi23AdditionalRelators]

/-- The complete relator list transcribed for `Fi₂₃`: the Coxeter-path expansion followed by the
two words that the source appends. This is a grouping helper: what it names is published by
`TauCeti.Sporadic.fi23Presentation_transcribed`. -/
private def fi23RelatorList : List (Relator (Fin 10)) :=
  fi23NodeAndEdgeRelators ++ fi23NonedgeRelators ++ fi23AdditionalRelators

/-- The Group Presentations Library finite presentation `GPLTable.Fi23.1` of the Fischer group
`Fi₂₃` on generators `a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, and `j`.

The source describes this as a full presentation of the abstract group and identifies its origin
as Praeger--Soicher. No structural property of the presented group is asserted here: this
definition records only the cited generators and relations. -/
def fi23Presentation : GroupPresentation where
  generatorNames := ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
  source := "R. Lindenbergh, Group Presentations Library, version 1.0; presentation attributed \
    there to C. E. Praeger and L. H. Soicher, Low Rank Representations and Graphs for Sporadic \
    Groups, Cambridge University Press, 1997"
  sourceLocator := "GPLTable.Fi23.1 in \
    https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g; Praeger--Soicher, Chapter 4, \
    doi:10.1017/CBO9780511526039.005"
  generatorConvention := "Generators have source order a,b,c,d,e,f,g,h,i,j, so indices 0 through \
    9 have those names. A Coxeter path declares each node to be an involution, a labeled edge \
    x-m-y declares (x*y)^m = 1, and an omitted edge declares (x*y)^2 = 1. Products are read left \
    to right."
  transcriptionNotes := "Expand the paths a3b3c3d3e3f3g3j and d3h3i to ten square relations, \
    nine labeled-edge relations, and thirty-six omitted-edge relations. Append the two words in \
    presdef[3]. The expected relator count and total length are derived from this exact expansion. \
    The module documentation records the completed itemized source-to-Lean read-through. GAP \
    4.15.1 enumerates 31671 cosets of the subgroup generated by a through i, which the source \
    labels 2.Fi22."
  expectedGeneratorCount := 10
  expectedRelatorCount := 57
  transcribed := fi23RelatorList

/-- The generator names recorded for `Fi₂₃`. This is what lets a consumer see that it is a
ten-generator presentation, and it is what bounds the generator indices of
`TauCeti.Sporadic.fi23Presentation_transcribed`. -/
@[simp]
theorem fi23Presentation_generatorNames :
    fi23Presentation.generatorNames = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"] := by
  simp [fi23Presentation]

/-- The source recorded for `Fi₂₃`. This equation is what publishes the citation itself, rather
than only the row's name, to a downstream audit. -/
@[simp]
theorem fi23Presentation_source :
    fi23Presentation.source = "R. Lindenbergh, Group Presentations Library, version 1.0; \
      presentation attributed there to C. E. Praeger and L. H. Soicher, Low Rank Representations \
      and Graphs for Sporadic Groups, Cambridge University Press, 1997" := by
  simp [fi23Presentation]

/-- The locator recorded for `Fi₂₃`, pointing at the presentation inside its source. -/
@[simp]
theorem fi23Presentation_sourceLocator :
    fi23Presentation.sourceLocator = "GPLTable.Fi23.1 in \
      https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g; Praeger--Soicher, Chapter 4, \
      doi:10.1017/CBO9780511526039.005" := by
  simp [fi23Presentation]

/-- The generator convention recorded for `Fi₂₃`, fixing which generator each relator index names
and how the source's Coxeter paths decode into relations. -/
@[simp]
theorem fi23Presentation_generatorConvention :
    fi23Presentation.generatorConvention = "Generators have source order a,b,c,d,e,f,g,h,i,j, so \
      indices 0 through 9 have those names. A Coxeter path declares each node to be an \
      involution, a labeled edge x-m-y declares (x*y)^m = 1, and an omitted edge declares \
      (x*y)^2 = 1. Products are read left to right." := by
  simp [fi23Presentation]

/-- The transcription notes recorded for `Fi₂₃`. -/
@[simp]
theorem fi23Presentation_transcriptionNotes :
    fi23Presentation.transcriptionNotes = "Expand the paths a3b3c3d3e3f3g3j and d3h3i to ten \
      square relations, nine labeled-edge relations, and thirty-six omitted-edge relations. \
      Append the two words in presdef[3]. The expected relator count and total length are derived \
      from this exact expansion. The module documentation records the completed itemized \
      source-to-Lean read-through. GAP 4.15.1 enumerates 31671 cosets of the subgroup generated by \
      a through i, which the source labels 2.Fi22." := by
  simp [fi23Presentation]

/-- The generator count `Fi₂₃`'s source states. With
`TauCeti.Sporadic.fi23Presentation_generatorNames` this is what makes
`TauCeti.Sporadic.fi23Presentation_matchesMetadata` an equation between two visible numbers. -/
@[simp]
theorem fi23Presentation_expectedGeneratorCount : fi23Presentation.expectedGeneratorCount = 10 := by
  simp [fi23Presentation]

/-- The relator count derived from `Fi₂₃`'s source expansion. With
`TauCeti.Sporadic.fi23Presentation_transcribed` this is what makes
`TauCeti.Sporadic.fi23Presentation_matchesMetadata` an equation between two visible numbers. -/
@[simp]
theorem fi23Presentation_expectedRelatorCount : fi23Presentation.expectedRelatorCount = 57 := by
  simp [fi23Presentation]

/-- The relator expressions transcribed for `Fi₂₃`, with their generator indices written out and
the local abbreviations and grouping lists of this file expanded.

This is the equation that characterizes the row: with
`TauCeti.GroupPresentation.relators_def` it determines the compiled words, and with
`TauCeti.GroupPresentation.mem_relatorSet_iff` it determines the relations defining
`TauCeti.GroupPresentation.Group`, so a consumer never has to unfold the row. Indices `0` through
`9` are the generators `a` through `j`, and the bounds come from
`TauCeti.Sporadic.fi23Presentation_generatorNames`. -/
@[simp]
theorem fi23Presentation_transcribed :
    fi23Presentation.transcribed =
      [ -- the ten involutions a², …, j²
        .pow (.gen ⟨0, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩) 2,
        .pow (.gen ⟨2, by simp⟩) 2,
        .pow (.gen ⟨3, by simp⟩) 2,
        .pow (.gen ⟨4, by simp⟩) 2,
        .pow (.gen ⟨5, by simp⟩) 2,
        .pow (.gen ⟨6, by simp⟩) 2,
        .pow (.gen ⟨7, by simp⟩) 2,
        .pow (.gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨9, by simp⟩) 2,
        -- the nine labeled edges (ab)³, …, (hi)³
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) 3,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨2, by simp⟩) 3,
        .pow (.gen ⟨2, by simp⟩ ⬝ .gen ⟨3, by simp⟩) 3,
        .pow (.gen ⟨3, by simp⟩ ⬝ .gen ⟨4, by simp⟩) 3,
        .pow (.gen ⟨4, by simp⟩ ⬝ .gen ⟨5, by simp⟩) 3,
        .pow (.gen ⟨5, by simp⟩ ⬝ .gen ⟨6, by simp⟩) 3,
        .pow (.gen ⟨6, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 3,
        .pow (.gen ⟨3, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 3,
        .pow (.gen ⟨7, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 3,
        -- the thirty-six omitted edges (ac)², …, (ij)²
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨2, by simp⟩) 2,
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨3, by simp⟩) 2,
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨4, by simp⟩) 2,
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨5, by simp⟩) 2,
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨6, by simp⟩) 2,
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 2,
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨3, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨4, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨5, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨6, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨1, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        .pow (.gen ⟨2, by simp⟩ ⬝ .gen ⟨4, by simp⟩) 2,
        .pow (.gen ⟨2, by simp⟩ ⬝ .gen ⟨5, by simp⟩) 2,
        .pow (.gen ⟨2, by simp⟩ ⬝ .gen ⟨6, by simp⟩) 2,
        .pow (.gen ⟨2, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 2,
        .pow (.gen ⟨2, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨2, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        .pow (.gen ⟨3, by simp⟩ ⬝ .gen ⟨5, by simp⟩) 2,
        .pow (.gen ⟨3, by simp⟩ ⬝ .gen ⟨6, by simp⟩) 2,
        .pow (.gen ⟨3, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨3, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        .pow (.gen ⟨4, by simp⟩ ⬝ .gen ⟨6, by simp⟩) 2,
        .pow (.gen ⟨4, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 2,
        .pow (.gen ⟨4, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨4, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        .pow (.gen ⟨5, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 2,
        .pow (.gen ⟨5, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨5, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        .pow (.gen ⟨6, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 2,
        .pow (.gen ⟨6, by simp⟩ ⬝ .gen ⟨8, by simp⟩) 2,
        .pow (.gen ⟨7, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        .pow (.gen ⟨8, by simp⟩ ⬝ .gen ⟨9, by simp⟩) 2,
        -- (dcbdefdhi)¹⁰
        .pow (.gen ⟨3, by simp⟩ ⬝ .gen ⟨2, by simp⟩ ⬝ .gen ⟨1, by simp⟩ ⬝ .gen ⟨3, by simp⟩ ⬝
          .gen ⟨4, by simp⟩ ⬝ .gen ⟨5, by simp⟩ ⬝ .gen ⟨3, by simp⟩ ⬝ .gen ⟨7, by simp⟩ ⬝
          .gen ⟨8, by simp⟩) 10,
        -- (abcdefh)⁹
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩ ⬝ .gen ⟨2, by simp⟩ ⬝ .gen ⟨3, by simp⟩ ⬝
          .gen ⟨4, by simp⟩ ⬝ .gen ⟨5, by simp⟩ ⬝ .gen ⟨7, by simp⟩) 9 ] := by
  simp [fi23Presentation, fi23RelatorList, fi23NodeAndEdgeRelators, fi23NonedgeRelators,
    fi23AdditionalRelators]

/-- The compiled relator words of `Fi₂₃`, generated from the nodes, edges, nonedges, and two
additional words of `GPLTable.Fi23.1`. A letter `(i, true)` is generator `i`; all source letters
are positive. -/
theorem fi23Presentation_relatorLetters :
    fi23Presentation.relatorLetters =
      let powWord (w : List (Nat × Bool)) (n : ℕ) := (List.replicate n w).flatten
      let squareWords := (List.range 10).map fun k => [(k, true), (k, true)]
      let edgePairs : List (Nat × Nat) :=
        [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 9), (3, 7), (7, 8)]
      let edgeWords := edgePairs.map fun (r, s) => powWord [(r, true), (s, true)] 3
      let nonedgePairs : List (Nat × Nat) :=
        [(0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9),
          (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9),
          (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9),
          (3, 5), (3, 6), (3, 8), (3, 9),
          (4, 6), (4, 7), (4, 8), (4, 9),
          (5, 7), (5, 8), (5, 9), (6, 7), (6, 8), (7, 9), (8, 9)]
      let nonedgeWords := nonedgePairs.map fun (r, s) => powWord [(r, true), (s, true)] 2
      squareWords ++ edgeWords ++ nonedgeWords ++
        [powWord [(3, true), (2, true), (1, true), (3, true), (4, true), (5, true),
            (3, true), (7, true), (8, true)] 10,
          powWord [(0, true), (1, true), (2, true), (3, true), (4, true), (5, true),
            (7, true)] 9] := by
  simp only [GroupPresentation.relatorLetters_def, GroupPresentation.relators_def,
    fi23Presentation_transcribed, List.map_cons, List.map_nil, Relator.toWord_mul,
    Relator.toWord_pow, Relator.toWord_gen]
  decide

/-- The lengths of the fifty-seven compiled relator words for `Fi₂₃`, in the order in which the
source's Coxeter paths and appended words expand: ten involutions, nine labeled edges, thirty-six
omitted edges, and the two further relators.

Reading the counts off one relator at a time is what lets a reviewer locate a discrepancy, rather
than only observe one in the total of `TauCeti.Sporadic.fi23Presentation_totalLength`. -/
theorem fi23Presentation_map_length_relators :
    fi23Presentation.relators.map List.length =
      List.replicate 10 2 ++ List.replicate 9 6 ++ List.replicate 36 4 ++ [90, 63] := by
  rw [← GroupPresentation.map_length_relatorLetters, fi23Presentation_relatorLetters]
  simp only [List.reduceReplicate, List.flatten_cons, List.flatten_nil, List.append_nil,
    List.cons_append, List.nil_append, List.map_cons, List.map_nil, List.append_assoc,
    List.map_append, List.map_map, List.length_cons, List.length_nil, zero_add, Nat.reduceAdd]
  decide

/-- The generator and relator counts recorded for `Fi₂₃` agree with the transcribed data. -/
theorem fi23Presentation_matchesMetadata : fi23Presentation.matchesMetadata := by
  simp [GroupPresentation.matchesMetadata_iff, GroupPresentation.generatorCount,
    fi23Presentation, fi23RelatorList, fi23NodeAndEdgeRelators, fi23NonedgeRelators,
    fi23AdditionalRelators]

/-- The compiled relators of the `Fi₂₃` presentation contain `371` signed letters in total. -/
theorem fi23Presentation_totalLength : fi23Presentation.totalLength = 371 := by
  rw [GroupPresentation.totalLength_def, fi23Presentation_map_length_relators]
  decide

/-- Every compiled relator of the `Fi₂₃` presentation is cyclically reduced. -/
theorem fi23Presentation_relatorsCyclicallyReduced :
    fi23Presentation.relatorsCyclicallyReduced := by
  simp [GroupPresentation.relatorsCyclicallyReduced_iff, GroupPresentation.relators_def,
    fi23Presentation, fi23RelatorList, fi23NodeAndEdgeRelators, fi23NonedgeRelators,
    fi23AdditionalRelators, FreeGroup.IsCyclicallyReduced]

/-! ### The row against the Coxeter group of its graph -/

-- The row records ten generator names, so `Fin fi23Presentation.generatorCount` and `Fin 10` are
-- the same type by definition and this cast transports along an equality of a type with itself;
-- the transcribed field is `fi23RelatorList` by definition as well. Both sides are therefore the
-- same list, which is what `rfl` checks. Transporting once here keeps the rewrites in
-- `fi23Presentation_mem_map_toWord_iff` at the literal index type.
private theorem fi23Presentation_transcribed_cast :
    (cast (by simp [fi23Presentation_generatorNames]) fi23Presentation.transcribed :
      List (Relator (Fin 10))) = fi23RelatorList := by
  rfl

/-- **The transcribed relations are exactly the ones the source's Coxeter graph encodes, together
with the two appended words.**

The row transcribes the source's two paths by hand, as ten square relations, nine labelled-edge
relations and thirty-six omitted-edge relations. This compares that expansion, letter by letter,
with the relations generated from `TauCeti.Sporadic.fi23CoxeterMatrix`, so the expansion is
checked against the graph rather than only read against it. The comparison is of compiled-word
membership rather than expressions or multiplicities, because the row writes an involution
relation as `sᵢ ^ 2` where the generated list writes `(sᵢ sᵢ) ^ 1` and groups its relations by
kind. -/
theorem fi23Presentation_mem_map_toWord_iff (w : PresentationWord (Fin 10)) :
    w ∈ (cast (by simp [fi23Presentation_generatorNames]) fi23Presentation.transcribed :
        List (Relator (Fin 10))).map Relator.toWord ↔
      w ∈ (coxeterRelators fi23CoxeterMatrix ++ fi23AdditionalRelators).map Relator.toWord := by
  -- The row's relators are this append by definition; stating the comparison at that index type
  -- keeps the rewrites below away from the record's generator count.
  have key :
      ((fi23NodeAndEdgeRelators ++ fi23NonedgeRelators ++ fi23AdditionalRelators).map
        Relator.toWord).Perm
          ((coxeterRelators fi23CoxeterMatrix ++ fi23AdditionalRelators).map Relator.toWord) := by
    rw [coxeterRelators_def, coxeterRelatorsOfList_def]
    simp only [List.map_append, List.map_map, Function.comp_def, toWord_coxeterRelator,
      fi23CoxeterMatrix_apply, fi23Edges]
    rw [fi23NodeAndEdgeRelators, fi23NonedgeRelators, fi23AdditionalRelators]
    simp only [List.map_cons, List.map_nil, Relator.toWord_pow, Relator.toWord_mul,
      Relator.toWord_gen]
    decide
  rw [fi23Presentation_transcribed_cast, fi23RelatorList]
  exact key.mem_iff

/-- **The row presents the Coxeter group of its graph cut down by the two appended relations**,
which is the shape in which the source states the presentation: a Coxeter graph, given by two
paths, followed by two words.

This is an identification of the presented group with a quotient built from Mathlib's
`CoxeterMatrix.relationsSet`; it asserts nothing about the order or the structure of either
side. -/
def fi23MulEquivPresentedGroupCoxeterAppend :
    fi23Presentation.Group ≃*
      PresentedGroup
        (fi23CoxeterMatrix.relationsSet ∪ Relator.relatorSet fi23AdditionalRelators) := by
  -- The generic equivalence indexes its Coxeter matrix and extra relators by
  -- `Fin fi23Presentation.generatorCount`. That is `Fin 10` by definition but not syntactically,
  -- because the row is sealed, so the row is unfolded here to make the two index types meet.
  unfold fi23Presentation
  apply GroupPresentation.mulEquivPresentedGroupCoxeterAppend
  exact congrArg Subgroup.normalClosure <|
    Relator.relatorSet_eq_of_mem_map_toWord_iff fi23Presentation_mem_map_toWord_iff

/-- The Coxeter equivalence sends each canonical generator to the corresponding canonical
generator. -/
@[simp]
theorem fi23MulEquivPresentedGroupCoxeterAppend_apply_of
    (i : Fin 10) :
    fi23MulEquivPresentedGroupCoxeterAppend
        (PresentedGroup.of
          (Fin.cast (by simp [GroupPresentation.generatorCount, fi23Presentation]) i)) =
      PresentedGroup.of i := by
  -- Same reduction as in the equivalence itself: `Fin.cast` moves the index from `Fin 10` to
  -- `Fin fi23Presentation.generatorCount`, and unfolding the sealed row identifies the two.
  unfold fi23MulEquivPresentedGroupCoxeterAppend fi23Presentation
  apply GroupPresentation.mulEquivPresentedGroupCoxeterAppend_apply_of

end TauCeti.Sporadic
