/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.PowerSubgroup.Basic
public import TauCeti.NumberTheory.LocalField.RootsOfUnity.Basic
import TauCeti.Algebra.CharP.LocalRing

/-!
# The group of roots of unity of a local field

Let `K` be a nonarchimedean local field whose residue field `𝓀[K]` has `q` elements and
characteristic `p`. The roots of unity of `K` form the torsion subgroup `μ(K)` of `Kˣ`. This file
proves that `μ(K)` is finite and splits into its prime-to-`p` part and its `p`-part:

`μ(K) ≃* μ_{q-1}(K) × μ_{p^∞}(K)`, hence `#μ(K) = (q - 1) · #μ_{p^∞}(K)`.

The prime-to-`p` part `μ_{q-1}(K)` is the group of Teichmüller representatives of `𝓀[K]ˣ`, and
it contains every root of unity whose order is prime to `p`. The `p`-part `μ_{p^∞}(K)` is
`TauCeti.pPowerRootsOfUnity p K`. In equal characteristic it is trivial, so `μ(K) = μ_{q-1}(K)`;
in mixed characteristic it is the finite cyclic group of `TauCeti.finite_pPowerRootsOfUnity`.

The proofs read a root of unity through the Teichmüller splitting `U(K,0) ≃ μ_{q-1}(K) × U(K,1)` of
`TauCeti.unitFiltrationZeroEquivProd`. Every root of unity has valuation zero, and a principal unit
of finite order has `p`-power order, because no nontrivial root of unity of order prime to `p` is
a principal unit.

## Main results

* `TauCeti.mem_pPowerRootsOfUnity_of_mem_unitFiltration_one`: a principal unit of finite order
  is a root of unity of `p`-power order.
* `TauCeti.rootsOfUnity_le_rootsOfUnity_natCard_residueField_sub_one`: `μ_m(K) ≤ μ_{q-1}(K)` for
  `m` prime to `p`.
* `TauCeti.torsion_units_eq_rootsOfUnity_sup_pPowerRootsOfUnity`: `μ(K)` is generated by its
  prime-to-`p` part and its `p`-part, which intersect trivially
  (`TauCeti.disjoint_rootsOfUnity_natCard_residueField_sub_one_pPowerRootsOfUnity`).
* `TauCeti.torsionUnitsEquivProd`: the isomorphism `μ(K) ≃* μ_{q-1}(K) × μ_{p^∞}(K)`.
* `TauCeti.finite_torsion_units` and `TauCeti.natCard_torsion_units`: `μ(K)` is finite, of order
  `(q - 1) · #μ_{p^∞}(K)`.
* `TauCeti.torsion_units_eq_rootsOfUnity_of_natCast_eq_zero`: in equal characteristic,
  `μ(K) = μ_{q-1}(K)`.

## References

* J.-P. Serre, *Local Fields*, Chapter II, §§4–5.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §5, Proposition 5.7.
-/

public section

noncomputable section

open IsLocalRing ValuativeRel

namespace TauCeti

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- Every root of unity of `K` has valuation zero: `μ(K) ≤ U(K,0)`. -/
theorem torsion_units_le_unitFiltration_zero : CommGroup.torsion Kˣ ≤ unitFiltration K 0 :=
  fun x hx ↦ by
    rw [← ker_normalizedValuation]
    exact normalizedValuation_eq_one_of_isOfFinOrder ((CommGroup.mem_torsion x).1 hx)

variable {K} in
/-- A principal unit of finite order is a root of unity of `p`-power order, where `p` is the
residue characteristic. -/
theorem mem_pPowerRootsOfUnity_of_mem_unitFiltration_one {x : Kˣ}
    (hx : x ∈ unitFiltration K 1) (hfin : IsOfFinOrder x) :
    x ∈ pPowerRootsOfUnity (ringChar 𝓀[K]) K := by
  obtain ⟨a, m, hm, ha⟩ := Nat.exists_eq_pow_mul_and_not_dvd hfin.orderOf_pos.ne'
    (ringChar 𝓀[K]) (CharP.prime_ringChar 𝓀[K]).ne_one
  refine (mem_pPowerRootsOfUnity_iff _ K x).2 ⟨a, ?_⟩
  have hroot : x ^ ringChar 𝓀[K] ^ a ∈ rootsOfUnity m K := by
    rw [mem_rootsOfUnity, ← pow_mul, ← ha, pow_orderOf_eq_one]
  exact Subgroup.disjoint_def.mp
    (disjoint_rootsOfUnity_unitFiltration_one_of_isUnit (isUnit_natCast_iff_not_dvd.2 hm))
    hroot (pow_mem hx _)

variable {K} in
/-- The roots of unity of order prime to the residue characteristic are Teichmüller
representatives: `μ_m(K) ≤ μ_{q-1}(K)` whenever `m` is invertible in `𝒪[K]`. -/
theorem rootsOfUnity_le_rootsOfUnity_natCard_residueField_sub_one {m : ℕ}
    (hm : IsUnit (m : 𝒪[K])) :
    rootsOfUnity m K ≤ rootsOfUnity (Nat.card 𝓀[K] - 1) K := by
  intro x hx
  have hm0 : m ≠ 0 := by
    rintro rfl
    simp at hm
  let y := unitFiltrationZeroEquivProd K ⟨x, rootsOfUnity_le_unitFiltration_zero K hm0 hx⟩
  -- The principal-unit component of `x` is again killed by `m`, so it is trivial.
  have hy : y ^ m = 1 := by
    rw [← map_pow, ← map_one (unitFiltrationZeroEquivProd K)]
    exact congrArg _ (Subtype.ext ((mem_rootsOfUnity m x).1 hx))
  have hy₂ : (y.2 : Kˣ) = 1 :=
    Subgroup.disjoint_def.mp (disjoint_rootsOfUnity_unitFiltration_one_of_isUnit hm)
      ((mem_rootsOfUnity m _).2 (congrArg (fun z ↦ (z.2 : Kˣ)) hy)) y.2.2
  have hxy : x = (y.1 : Kˣ) := by
    simpa only [y, ContinuousMulEquiv.symm_apply_apply, hy₂, mul_one] using
      coe_unitFiltrationZeroEquivProd_symm_apply K y
  exact hxy ▸ y.1.2

/-- The prime-to-`p` part and the `p`-part of `μ(K)` intersect trivially: `q - 1` is prime to
the residue characteristic `p`. -/
theorem disjoint_rootsOfUnity_natCard_residueField_sub_one_pPowerRootsOfUnity :
    Disjoint (rootsOfUnity (Nat.card 𝓀[K] - 1) K) (pPowerRootsOfUnity (ringChar 𝓀[K]) K) := by
  have hcop : (Nat.card 𝓀[K] - 1).Coprime (ringChar 𝓀[K]) := by
    have h := isUnit_natCast_natCard_pow_sub_one K one_ne_zero
    rw [pow_one, isUnit_natCast_iff_not_dvd] at h
    exact ((CharP.prime_ringChar 𝓀[K]).coprime_iff_not_dvd.2 h).symm
  refine Subgroup.disjoint_def.2 fun {x} hx hxp ↦ ?_
  obtain ⟨k, hk⟩ := (mem_pPowerRootsOfUnity_iff _ K x).1 hxp
  simpa only [(hcop.pow_right k).gcd_eq_one, pow_one] using
    pow_gcd_eq_one.2 ⟨(mem_rootsOfUnity _ x).1 hx, hk⟩

/-- The roots of unity of `K` are generated by the Teichmüller representatives `μ_{q-1}(K)` and
the roots of unity of `p`-power order. -/
theorem torsion_units_eq_rootsOfUnity_sup_pPowerRootsOfUnity :
    CommGroup.torsion Kˣ =
      rootsOfUnity (Nat.card 𝓀[K] - 1) K ⊔ pPowerRootsOfUnity (ringChar 𝓀[K]) K := by
  refine le_antisymm (fun x hx ↦ ?_) (sup_le (fun x hx ↦ ?_) fun x hx ↦ ?_)
  · let y := unitFiltrationZeroEquivProd K ⟨x, torsion_units_le_unitFiltration_zero K hx⟩
    have hxy : x = (y.1 : Kˣ) * (y.2 : Kˣ) := by
      simpa only [y, ContinuousMulEquiv.symm_apply_apply] using
        coe_unitFiltrationZeroEquivProd_symm_apply K y
    have hfin₁ : IsOfFinOrder (y.1 : Kˣ) :=
      isOfFinOrder_iff_pow_eq_one.2 ⟨_, Nat.pos_of_ne_zero
        (card_residueField_sub_one_ne_zero 𝒪[K]), (mem_rootsOfUnity _ _).1 y.1.2⟩
    have hfin₂ : IsOfFinOrder (y.2 : Kˣ) := by
      rw [coe_unitFiltrationZeroEquivProd_apply_snd]
      exact ((CommGroup.mem_torsion x).1 hx).mul hfin₁.inv
    exact hxy ▸ Subgroup.mul_mem_sup y.1.2
      (mem_pPowerRootsOfUnity_of_mem_unitFiltration_one y.2.2 hfin₂)
  · exact isOfFinOrder_iff_pow_eq_one.2 ⟨_, Nat.pos_of_ne_zero
      (card_residueField_sub_one_ne_zero 𝒪[K]), (mem_rootsOfUnity _ _).1 hx⟩
  · obtain ⟨k, hk⟩ := (mem_pPowerRootsOfUnity_iff _ K x).1 hx
    exact isOfFinOrder_iff_pow_eq_one.2
      ⟨_, pow_pos (CharP.prime_ringChar 𝓀[K]).pos k, hk⟩

/-- Multiplication `μ_{q-1}(K) × μ_{p^∞}(K) → μ(K)`, the inverse of `torsionUnitsEquivProd`. -/
private def torsionUnitsMulHom :
    rootsOfUnity (Nat.card 𝓀[K] - 1) K × pPowerRootsOfUnity (ringChar 𝓀[K]) K →*
      CommGroup.torsion Kˣ :=
  ((rootsOfUnity _ K).subtype.coprod (pPowerRootsOfUnity _ K).subtype).codRestrict _ fun y ↦ by
    rw [torsion_units_eq_rootsOfUnity_sup_pPowerRootsOfUnity]
    exact Subgroup.mul_mem_sup y.1.2 y.2.2

private theorem torsionUnitsMulHom_bijective : Function.Bijective (torsionUnitsMulHom K) := by
  refine ⟨fun y z h ↦ Subgroup.mul_injective_of_disjoint
    (disjoint_rootsOfUnity_natCard_residueField_sub_one_pPowerRootsOfUnity K)
    (congrArg Subtype.val h), fun x ↦ ?_⟩
  obtain ⟨y, hy, z, hz, hyz⟩ :=
    Subgroup.mem_sup.1 ((torsion_units_eq_rootsOfUnity_sup_pPowerRootsOfUnity K).le x.2)
  exact ⟨(⟨y, hy⟩, ⟨z, hz⟩), Subtype.ext hyz⟩

/-- **The structure of `μ(K)`.** The roots of unity of a nonarchimedean local field `K` are the
internal direct product of the Teichmüller representatives `μ_{q-1}(K)`, which form the
prime-to-`p` part, and of the roots of unity of `p`-power order, which form the `p`-part, where
`q = #𝓀[K]` and `p` is the residue characteristic. -/
def torsionUnitsEquivProd :
    CommGroup.torsion Kˣ ≃*
      rootsOfUnity (Nat.card 𝓀[K] - 1) K × pPowerRootsOfUnity (ringChar 𝓀[K]) K :=
  (MulEquiv.ofBijective _ (torsionUnitsMulHom_bijective K)).symm

/-- The inverse of `torsionUnitsEquivProd` is multiplication, `(ζ, ξ) ↦ ζ ξ`. -/
@[simp]
theorem coe_torsionUnitsEquivProd_symm_apply
    (y : rootsOfUnity (Nat.card 𝓀[K] - 1) K × pPowerRootsOfUnity (ringChar 𝓀[K]) K) :
    ((torsionUnitsEquivProd K).symm y : Kˣ) = y.1 * y.2 :=
  (rfl)

/-- A nonarchimedean local field has only finitely many roots of unity. -/
instance finite_torsion_units : Finite (CommGroup.torsion Kˣ) := by
  have : Finite (rootsOfUnity (Nat.card 𝓀[K] - 1) K) :=
    .of_equiv _ (rootsOfUnityAlgebraMulEquivUnitsResidueField 𝒪[K] K).symm.toEquiv
  have : Finite (pPowerRootsOfUnity (ringChar 𝓀[K]) K) := by
    have hp := CharP.prime_ringChar 𝓀[K]
    by_cases hpK : ((ringChar 𝓀[K] : ℕ) : K) = 0
    · have : CharP K (ringChar 𝓀[K]) := (CharP.charP_iff_prime_eq_zero hp).2 hpK
      have : ExpChar K (ringChar 𝓀[K]) := .prime hp
      rw [pPowerRootsOfUnity_eq_bot]
      infer_instance
    · have : Fact (ringChar 𝓀[K]).Prime := ⟨hp⟩
      exact finite_pPowerRootsOfUnity hpK
  exact .of_equiv _ (torsionUnitsEquivProd K).symm.toEquiv

/-- **The order of `μ(K)`.** A nonarchimedean local field has `(q - 1) · #μ_{p^∞}(K)` roots of
unity, where `q = #𝓀[K]` and `p` is the residue characteristic. -/
theorem natCard_torsion_units :
    Nat.card (CommGroup.torsion Kˣ) =
      (Nat.card 𝓀[K] - 1) * Nat.card (pPowerRootsOfUnity (ringChar 𝓀[K]) K) := by
  rw [Nat.card_congr (torsionUnitsEquivProd K).toEquiv, Nat.card_prod,
    Nat.card_congr (rootsOfUnityAlgebraMulEquivUnitsResidueField 𝒪[K] K).toEquiv, Nat.card_units]

variable {K} in
/-- In equal characteristic, every root of unity of `K` is a Teichmüller representative:
`μ(K) = μ_{q-1}(K)`. -/
theorem torsion_units_eq_rootsOfUnity_of_natCast_eq_zero
    (hpK : ((ringChar 𝓀[K] : ℕ) : K) = 0) :
    CommGroup.torsion Kˣ = rootsOfUnity (Nat.card 𝓀[K] - 1) K := by
  have hp := CharP.prime_ringChar 𝓀[K]
  have : CharP K (ringChar 𝓀[K]) := (CharP.charP_iff_prime_eq_zero hp).2 hpK
  have : ExpChar K (ringChar 𝓀[K]) := .prime hp
  rw [torsion_units_eq_rootsOfUnity_sup_pPowerRootsOfUnity, pPowerRootsOfUnity_eq_bot, sup_bot_eq]

end TauCeti
