import VersoBlog
open Verso Genre Blog
open Verso.Output Verso.Output.Html

/-- The two "lines of code by date" charts. The SVGs are regenerated at each site
deploy (and daily) into `static_files/` by the `pages` workflow, so this page never
needs touching as the project grows. They are embedded as a raw HTML blob: each
`<img>` simply points at the static asset. -/
def locGraphs : Html := {{
  <div class="loc-graphs">
    <figure class="loc-figure">
      <img class="loc-graph" src="static/loc-tauceti.svg"
           alt="Tau Ceti: lines of Lean by date"/>
      <figcaption>"The Lean library under " <code>"TauCeti/"</code> ", total lines by date."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/loc-roadmap.svg"
           alt="Roadmap specification lines over time, with the archived Completed roadmaps highlighted"/>
      <figcaption>"All roadmap specifications, including " <code>"Completed/"</code> ". The highlighted portion is archived as complete; generated status and progress reports are excluded."</figcaption>
    </figure>
  </div>
}}

/-- Completion uses the existing coverage reports and human archival decisions. -/
private def roadmapCompletionGraphs : Html := {{
  <div class="loc-graphs">
    <figure class="loc-figure">
      <img class="loc-graph" src="static/roadmap-layers.svg"
           alt="Total and completed roadmap layers and lanes over time, including unassessed layers"
           loading="lazy"/>
      <figcaption>"Each lane or layer counts once, including the constituent roadmaps of an umbrella. Partial and unassessed layers receive no completion credit; archived roadmaps count as complete."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/roadmap-exhaustion.svg"
           alt="Estimated time to exhaust roadmap work, with authoring stopped or continued at its recent pace"
           loading="lazy"/>
      <figcaption>"Two scenarios: stop adding roadmap work, or continue authoring at the past seven complete days' pace. Estimates use roadmap size and layer counts as separate measures."</figcaption>
    </figure>
  </div>
}}

/-- The per-roadmap chart: cumulative net lines of Lean, split by the roadmap each
merged PR advances (its `roadmap/<Area>` label). Regenerated at each deploy by the
`pages` workflow (`scripts/loc_roadmap_graph.py`), from the PR labels rather than git,
so it too needs no committed state. Embedded as a raw HTML blob pointing at the asset. -/
def roadmapGraph : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/loc-per-roadmap.svg"
         alt="Tau Ceti: cumulative net lines of Lean per roadmap, over time"/>
    <figcaption>"Net lines added or refactored per roadmap, stacked, by the date each PR merged."</figcaption>
  </figure>
}}

/-- A current snapshot of participation across the four project repositories: the GitHub
accounts that remain once recognised automation is excluded, which is not the same as a
verified count of people. Regenerated daily by the `pages` workflow
(`scripts/participant_graph.py`) from GitHub PR/issue participant connections and
default-branch commit contributors. -/
private def participationGraph : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/participation.svg"
         alt="Participation across the four Tau Ceti repositories, by repository"/>
    <figcaption>"Participating accounts by repository, once recognised automation is excluded; an account active in several repositories appears in several bars."</figcaption>
  </figure>
}}

/-- Current queue health and historical PR throughput. These SVGs and the exact JSON
data are regenerated by `scripts/pr_stats_graphs.py` in the scheduled Pages workflow. -/
private def prPipelineGraphs : Html := {{
  <div class="loc-graphs">
    <figure class="loc-figure">
      <img class="loc-graph" src="static/pr-queue-age.svg"
           alt="Open pull request age, followed by time awaiting author and time in review"
           loading="lazy"/>
      <figcaption>"Age of every open PR, then elapsed time in its current author-action or review cycle."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/rolling-seven-day-history.svg"
           alt="Trailing-seven-day pull request throughput, participation, and merge latency"
           loading="lazy"/>
      <figcaption>"Merges, active PR authors, and creation-to-merge latency in trailing seven-day UTC windows."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/review-cycles-reached.svg"
           alt="Pull requests reaching each successive review cycle"
           loading="lazy"/>
      <figcaption>"PRs reaching each review cycle; a cycle begins whenever a PR returns to " <code>"awaiting-review"</code> " after its author's turn."</figcaption>
    </figure>
  </div>
}}

/-- Cumulative merged-PR and review histories, split by contributor. -/
private def contributorGraphs : Html := {{
  <div class="loc-graphs">
    <figure class="loc-figure">
      <img class="loc-graph" src="static/cumulative-merges-by-contributor.svg"
           alt="Cumulative merged pull requests by contributor"
           loading="lazy"/>
      <figcaption>"Cumulative merged PRs by author since project inception."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/cumulative-reviews-by-contributor.svg"
           alt="Cumulative reviews by contributor"
           loading="lazy"/>
      <figcaption>"Cumulative reviews by contributor since project inception. Each review is one canonical v1 scoreboard; edits to an existing scoreboard do not add counts."</figcaption>
    </figure>
  </div>
}}

/-- Who works where: one grid for merged PRs, one for reviews, with a column for each arXiv
category, as declared by the roadmap a PR advances in its `metadata.toml` in TauCetiRoadmap.
Regenerated with the rest of the pull-request statistics by `scripts/pr_stats_graphs.py`; both
slices are a local join over the same snapshot, so neither costs an extra API call. -/
private def roadmapContributorGraphs : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/merges-by-roadmap-and-contributor.svg"
         alt="Merged pull requests per contributor per arXiv category, over the trailing ninety days"
         loading="lazy"/>
    <figcaption>"Merged PRs per contributor per arXiv category over the trailing ninety days. Each PR counts under the category of the roadmap it advances."</figcaption>
  </figure>
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/reviews-by-roadmap-and-contributor.svg"
         alt="Reviews per contributor per arXiv category, over the trailing ninety days"
         loading="lazy"/>
    <figcaption>"Reviews per contributor per arXiv category over the same window and the same columns."</figcaption>
  </figure>
}}

#doc (Page) "Statistics" =>

How much mathematics has Tau Ceti formalized, and how fast is the roadmap that
directs it growing? The volume charts count the lines present in git history through
the last complete UTC day and are rebuilt at each deploy.

:::blob locGraphs
:::

The library figure counts the mathematics under `TauCeti/`, plus `TauCeti.lean`.
Roadmap size counts Markdown and Lean files, including target statements and reference
notes, in both active and archived roadmap directories. Moving a roadmap to `Completed/`
keeps it in the total and moves its size into the completed portion. Machine-generated reports are excluded,
so writing a progress report does not look like authoring more work.

:::blob roadmapCompletionGraphs
:::

The second chart measures the fraction of named layers and lanes that are complete.
It uses generated coverage reports. Older reports without recorded layer assessments
appear as unassessed here, even if the Progress page has a manual reading. A roadmap archived by its maintainers
counts as complete even if its last report predates that decision. The shaded unassessed
portion remains in the total. Layer sizes differ, so this is a fraction of goals, rather
than a fraction of effort. Reports may lag the code, and a changed specification may need
a new assessment; the [Progress](progress) page shows those individual cases.

The exhaustion estimates ask how much more library growth would consume the recorded
backlog. We divide completions over recorded roadmap history by the increase in library
lines over that history, then apply the library's last seven complete days of growth to
convert the result into days. For roadmap size, completion credit is the specification's
size when it was archived; for layers, it is when a report first records them done.
Those dates are approximate observations, not exact implementation dates.

With authoring stopped, the estimate is remaining work divided by inferred daily
completion. With authoring continuing, we subtract the recent daily increase in total
roadmap size or layer count from that completion rate. If authoring keeps up with
completion, there is no exhaustion at that pace. These are rough extrapolations:
lines and layers are unequal, reports can recognize old work in a batch, and neither
the remaining difficulty nor future throughput is known. Exact histories, assumptions,
completion events and estimates are downloadable as
[`roadmap-completion.json`](static/roadmap-completion.json).

Which roadmap is all that Lean serving? Every pull request is labelled with the
roadmap it advances, so we can split the library by roadmap. The chart below stacks
the net lines each roadmap has accrued — every merged PR's additions minus its
deletions, attributed to its roadmap — by the day the PR merged. Because it sums
diffs rather than counting the lines in the tree, a line later rewritten counts under
both PRs, so this measures work landed per roadmap, not a snapshot line count.
Infrastructure and refactor PRs, which advance no roadmap, are left out. How far each roadmap
has got against its own specification is a different question, answered on the
[Progress](progress) page.

:::blob roadmapGraph
:::

How is the contribution and review pipeline behaving? The first chart separates a
PR's total age from the clock on its current state. The author-action clock covers both
states that wait on a human, a failed build and a review that requested changes. PRs
outside the author-action and review states appear in total time open but not in the two
current-state panels.
The rolling history uses complete UTC days. The review-cycle chart counts durable label
transitions rather than scoreboard comments, because a scoreboard
may be edited in place as later rounds complete. A cycle is one entry into review from
an author or CI state, so the pipeline swapping `awaiting-review` for
`review-in-progress` and back within a single round stays one cycle. Its subtitle states
when those review-state transitions first appear in project history.

:::blob prPipelineGraphs
:::

Who has taken part? The snapshot below counts GitHub accounts that have
opened a pull request or issue, participated in those conversations (including
reviews), or authored a commit on the default branch of TauCeti, TauCetiRoadmap,
TauCetiWorker, or TauCetiReview. Accounts recognised as automation are dropped:
logins carrying GitHub's `[bot]` suffix, together with the project's own automation
aliases. Nothing verifies that the accounts left over belong to people, so any
automation the filter does not recognise is still counted. The headline
deduplicates accounts across all four repositories; the repository bars
deliberately overlap.

:::blob participationGraph
:::

How have merged contributions and reviews accumulated? Like the rolling charts above, these
histories are drawn through the last complete UTC day, so a few hours of today never read as
a slowdown. They show every contributor while that remains legible, then cap themselves at 24
named lines and combine the remaining long tail. Exact totals for every login, counted right
through the snapshot instant, remain available in the generated
[`pr-stats.json`](static/pr-stats.json). A review is one canonical v1 scoreboard whose
posting login also authors a merged PR in the fetched snapshot.

:::blob contributorGraphs
:::

Who works where? The two grids below slice the same merges and reviews by area, over the trailing
ninety days. Each pull request counts under the arXiv category of the roadmap it carries, as that
roadmap declares it in its `metadata.toml` in TauCetiRoadmap; a roadmap that declares none counts
as `Unsorted`. Between them the grids answer the questions the cumulative histories cannot: who
already knows an area well enough to review for it, whether an area is resting on one person, and
where somebody has been spending their effort.

The columns are the categories with the most merges in that window, busiest first — every one of
those questions is about now. Both grids use the same columns, so they can be read against each
other. Past twenty categories the rest would share one `Other` column, and the quietest
contributors are summed into one `Other` row, so nothing is dropped; exact
per-contributor, per-category counts are in [`pr-stats.json`](static/pr-stats.json).

:::blob roadmapContributorGraphs
:::
