/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Perm.TransitiveGroupLabel.Basic
public import TauCeti.GroupTheory.SpecificGroups.Dihedral.Basic
import TauCeti.GroupTheory.Perm.OrbitCount.FinRotate

/-!
# The dihedral reference permutation groups in degrees four and five

The reference subgroup `4T3` acts as the symmetry group of a square, and `5T2` as the symmetry
group of a regular pentagon. In each, the full cycle is a rotation and the other generator is a
reflection: the transposition `(0 2)` of opposite vertices of the square, and the double
transposition `i ↦ 3 - i` of the pentagon. We identify them with `DihedralGroup 4` and
`DihedralGroup 5` using the recognition theorem for groups generated by two involutions.
-/

public section

open Equiv Equiv.Perm

namespace TauCeti

private abbrev D4 : Subgroup (Perm (Fin 4)) := referenceSubgroup 4 ⟨2, by simp⟩

private def reflection : D4 := ⟨swap 0 2, by
  rw [D4, referenceSubgroup_four_two]
  exact Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩

private def secondReflection : D4 := ⟨finRotate 4 * swap 0 2, by
  rw [D4, referenceSubgroup_four_two]
  exact (Subgroup.closure {finRotate 4, swap 0 2}).mul_mem
    (Subgroup.subset_closure (Set.mem_insert _ _))
    (Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _)))⟩

/-- The reference subgroup `4T3` is the dihedral group of the square, of order eight. -/
noncomputable def referenceSubgroupFourTwoMulEquivDihedralGroup :
    referenceSubgroup 4 ⟨2, by simp⟩ ≃* DihedralGroup 4 := by
  let s : D4 := reflection
  let t : D4 := secondReflection
  have hs : s * s = 1 := by ext x; fin_cases x <;> decide
  have ht : t * t = 1 := by ext x; fin_cases x <;> decide
  have hs1 : s ≠ 1 := by decide
  have ht1 : t ≠ 1 := by decide
  have hn : orderOf (s * t) = 4 := by
    have hst : s * t = (⟨(finRotate 4)⁻¹, by
      rw [D4, referenceSubgroup_four_two]
      exact (Subgroup.closure {finRotate 4, swap 0 2}).inv_mem
        (Subgroup.subset_closure (Set.mem_insert _ _))⟩ : D4) := by
      ext x
      fin_cases x <;> decide
    rw [hst, Subgroup.orderOf_mk, orderOf_inv, orderOf_finRotate (by decide)]
  have hgen : Subgroup.closure ({s, t} : Set D4) = ⊤ := by
    let H : Subgroup D4 := Subgroup.closure {s, t}
    have hr : t * s = (⟨finRotate 4, by
        rw [D4, referenceSubgroup_four_two]
        exact Subgroup.subset_closure (Set.mem_insert _ _)⟩ : D4) := by
      ext x
      fin_cases x <;> decide
    have hle : D4 ≤ H.map D4.subtype := by
      have hD : D4 = Subgroup.closure ({finRotate 4, swap 0 2} : Set (Perm (Fin 4))) := by
        exact referenceSubgroup_four_two
      calc
        D4 = Subgroup.closure ({finRotate 4, swap 0 2} : Set (Perm (Fin 4))) := hD
        _ ≤ H.map D4.subtype := by
          apply (Subgroup.closure_le _).mpr
          intro x hx
          rcases Set.mem_insert_iff.mp hx with rfl | hx
          · exact ⟨t * s, H.mul_mem
              (Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _)))
              (Subgroup.subset_closure (Set.mem_insert _ _)),
              congrArg Subtype.val hr⟩
          · have : x = swap 0 2 := Set.mem_singleton_iff.mp hx
            subst this
            exact ⟨s, Subgroup.subset_closure (Set.mem_insert _ _), rfl⟩
    apply eq_top_iff.mpr
    intro g _
    obtain ⟨h, hh, heq⟩ := hle g.property
    have : h = g := Subtype.ext heq
    exact this ▸ hh
  exact (dihedralGroupMulEquiv hs ht hs1 ht1 hn hgen).symm

/-- The standard dihedral reflection gives the diagonal swap in the reference action. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_symm_apply_sr_zero :
    referenceSubgroupFourTwoMulEquivDihedralGroup.symm (.sr 0) =
      (⟨swap 0 2, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure
          (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) := by
  simp [referenceSubgroupFourTwoMulEquivDihedralGroup, dihedralGroupMulEquiv_apply,
    reflection]

/-- The inverse standard dihedral rotation gives the four-cycle in the reference action. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_symm_apply_r_three :
    referenceSubgroupFourTwoMulEquivDihedralGroup.symm (.r (3 : ZMod 4)) =
      (⟨finRotate 4, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure (Set.mem_insert _ _)⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) := by
  simp only [referenceSubgroupFourTwoMulEquivDihedralGroup,
    MulEquiv.symm_symm, dihedralGroupMulEquiv_apply, dihedralHom_r]
  ext x
  fin_cases x <;> decide

/-- The concrete reflection maps to the standard dihedral reflection. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_apply_swap :
    referenceSubgroupFourTwoMulEquivDihedralGroup
      (⟨swap 0 2, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure
          (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) = .sr 0 := by
  apply referenceSubgroupFourTwoMulEquivDihedralGroup.symm.injective
  simp

/-- The concrete four-cycle maps to the inverse of the standard dihedral rotation. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_apply_finRotate :
    referenceSubgroupFourTwoMulEquivDihedralGroup
      (⟨finRotate 4, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure (Set.mem_insert _ _)⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) = .r (3 : ZMod 4) := by
  apply referenceSubgroupFourTwoMulEquivDihedralGroup.symm.injective
  simp

/-- Every permutation subgroup with label `4T3` is abstractly the dihedral group of the
square. The isomorphism depends on the conjugating permutation used to read the label. -/
theorem TransitiveGroupLabel.nonempty_mulEquiv_dihedralGroup_four_two
    {G : Subgroup (Perm (Fin 4))}
    (h : TransitiveGroupLabel (⟨2, by simp⟩ : TransitiveGroupIndex 4) G) :
    Nonempty (G ≃* DihedralGroup 4) := by
  obtain ⟨e⟩ := h.nonempty_mulEquiv_referenceSubgroup
  exact ⟨e.trans referenceSubgroupFourTwoMulEquivDihedralGroup⟩

/-- The reflection `i ↦ 3 - i` of the pentagon. -/
private abbrev pentagonReflection : Perm (Fin 5) := swap 0 3 * swap 1 2

private theorem pentagonReflection_mul_self : pentagonReflection * pentagonReflection = 1 := by
  decide

private theorem pentagonReflection_mul_rotation_mul_self :
    pentagonReflection * finRotate 5 * (pentagonReflection * finRotate 5) = 1 := by
  decide

private theorem pentagonReflection_mul_pentagonReflection_mul_rotation :
    pentagonReflection * (pentagonReflection * finRotate 5) = finRotate 5 := by
  rw [← mul_assoc, pentagonReflection_mul_self, one_mul]

private theorem orderOf_pentagonReflection_mul_pentagonReflection_mul_rotation :
    orderOf (pentagonReflection * (pentagonReflection * finRotate 5)) = 5 := by
  rw [pentagonReflection_mul_pentagonReflection_mul_rotation, orderOf_finRotate (by decide)]

/-- The dihedral group of the pentagon, realized by the rotation `finRotate 5` and the reflection
`i ↦ 3 - i`. -/
private noncomputable def pentagonHom : DihedralGroup 5 →* Perm (Fin 5) :=
  dihedralHom pentagonReflection_mul_self pentagonReflection_mul_rotation_mul_self
    (by simpa only [orderOf_pentagonReflection_mul_pentagonReflection_mul_rotation] using
      pow_orderOf_eq_one (pentagonReflection * (pentagonReflection * finRotate 5)))

private theorem pentagonHom_injective : Function.Injective pentagonHom :=
  dihedralHom_injective _ _ (by decide) (by decide)
    orderOf_pentagonReflection_mul_pentagonReflection_mul_rotation

private theorem range_pentagonHom : pentagonHom.range = referenceSubgroup 5 ⟨1, by simp⟩ := by
  rw [pentagonHom, range_dihedralHom, referenceSubgroup_five_one]
  have hr : finRotate 5 ∈
      Subgroup.closure {pentagonReflection, pentagonReflection * finRotate 5} := by
    have h := mul_mem (Subgroup.subset_closure (Set.mem_insert pentagonReflection
        {pentagonReflection * finRotate 5}))
      (Subgroup.subset_closure (Set.mem_insert_of_mem pentagonReflection
        (Set.mem_singleton (pentagonReflection * finRotate 5))))
    rwa [pentagonReflection_mul_pentagonReflection_mul_rotation] at h
  have hs : pentagonReflection ∈ Subgroup.closure {finRotate 5, pentagonReflection} :=
    Subgroup.subset_closure (by simp)
  refine le_antisymm ((Subgroup.closure_le _).mpr ?_) ((Subgroup.closure_le _).mpr ?_)
  · rintro σ (rfl | rfl)
    · exact hs
    · exact mul_mem hs (Subgroup.subset_closure (by simp))
  · rintro σ (rfl | rfl)
    · exact hr
    · exact Subgroup.subset_closure (by simp)

/-- The reference subgroup `5T2` is the dihedral group of the pentagon, of order ten. -/
noncomputable def referenceSubgroupFiveOneMulEquivDihedralGroup :
    referenceSubgroup 5 ⟨1, by simp⟩ ≃* DihedralGroup 5 :=
  ((MonoidHom.ofInjective pentagonHom_injective).trans
    (MulEquiv.subgroupCongr range_pentagonHom)).symm

private theorem coe_referenceSubgroupFiveOneMulEquivDihedralGroup_symm_apply
    (g : DihedralGroup 5) :
    (referenceSubgroupFiveOneMulEquivDihedralGroup.symm g : Perm (Fin 5)) = pentagonHom g := by
  simp [referenceSubgroupFiveOneMulEquivDihedralGroup, MonoidHom.ofInjective_apply]

/-- A dihedral rotation acts on the pentagon by a power of the rotation `finRotate 5`. -/
@[simp]
theorem coe_referenceSubgroupFiveOneMulEquivDihedralGroup_symm_apply_r (i : ZMod 5) :
    (referenceSubgroupFiveOneMulEquivDihedralGroup.symm (.r i) : Perm (Fin 5)) =
      finRotate 5 ^ (ZMod.cast i : ℤ) := by
  rw [coe_referenceSubgroupFiveOneMulEquivDihedralGroup_symm_apply, pentagonHom, dihedralHom_r,
    pentagonReflection_mul_pentagonReflection_mul_rotation]

/-- A dihedral reflection acts on the pentagon by the reflection `i ↦ 3 - i` after a power of the
rotation `finRotate 5`. -/
@[simp]
theorem coe_referenceSubgroupFiveOneMulEquivDihedralGroup_symm_apply_sr (i : ZMod 5) :
    (referenceSubgroupFiveOneMulEquivDihedralGroup.symm (.sr i) : Perm (Fin 5)) =
      swap 0 3 * swap 1 2 * finRotate 5 ^ (ZMod.cast i : ℤ) := by
  rw [coe_referenceSubgroupFiveOneMulEquivDihedralGroup_symm_apply, pentagonHom, dihedralHom_sr,
    pentagonReflection_mul_pentagonReflection_mul_rotation]

/-- The concrete rotation of the pentagon maps to the standard dihedral rotation. -/
@[simp]
theorem referenceSubgroupFiveOneMulEquivDihedralGroup_apply_finRotate :
    referenceSubgroupFiveOneMulEquivDihedralGroup
      (⟨finRotate 5, by
        rw [referenceSubgroup_five_one]
        exact Subgroup.subset_closure (by simp)⟩ :
        referenceSubgroup 5 ⟨1, by simp⟩) = .r 1 := by
  apply referenceSubgroupFiveOneMulEquivDihedralGroup.symm.injective
  ext x
  rw [MulEquiv.symm_apply_apply, coe_referenceSubgroupFiveOneMulEquivDihedralGroup_symm_apply_r]
  fin_cases x <;> decide

/-- The concrete reflection of the pentagon maps to the standard dihedral reflection. -/
@[simp]
theorem referenceSubgroupFiveOneMulEquivDihedralGroup_apply_swap_mul_swap :
    referenceSubgroupFiveOneMulEquivDihedralGroup
      (⟨swap 0 3 * swap 1 2, by
        rw [referenceSubgroup_five_one]
        exact Subgroup.subset_closure (by simp)⟩ :
        referenceSubgroup 5 ⟨1, by simp⟩) = .sr 0 := by
  apply referenceSubgroupFiveOneMulEquivDihedralGroup.symm.injective
  ext x
  rw [MulEquiv.symm_apply_apply, coe_referenceSubgroupFiveOneMulEquivDihedralGroup_symm_apply_sr]
  fin_cases x <;> decide

/-- Every permutation subgroup with label `5T2` is abstractly the dihedral group of the pentagon.
The isomorphism depends on the conjugating permutation used to read the label. -/
theorem TransitiveGroupLabel.nonempty_mulEquiv_dihedralGroup_five_one
    {G : Subgroup (Perm (Fin 5))}
    (h : TransitiveGroupLabel (⟨1, by simp⟩ : TransitiveGroupIndex 5) G) :
    Nonempty (G ≃* DihedralGroup 5) := by
  obtain ⟨e⟩ := h.nonempty_mulEquiv_referenceSubgroup
  exact ⟨e.trans referenceSubgroupFiveOneMulEquivDihedralGroup⟩

end TauCeti
