/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Adjoint.RootSpace
public import TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Smooth
public import TauCeti.Algebra.AlgebraicGroup.Tangent.Smooth
public import TauCeti.Algebra.AlgebraicGroup.Tangent.RootSpace

/-!
# Integral adjoint comodule root spaces of the special linear group

For the diagonal torus of `SL_{r+1}` over a commutative ring, the adjoint comodule's
weight space at the root `ε_i - ε_j` is the line generated by the normalized matrix unit
`E_ij`. The Lie algebra is modeled as the dual of the augmentation cotangent module.
Smoothness makes that module finite projective, so the existing universal-point tangent
calculation detects membership in the actual comodule weight space over every base ring.
`mem_adjointWeightSpace_iff` gives the entrywise criterion for an arbitrary character,
which can also be used to exclude characters not appearing among the matrix entries.

`adjointWeightSpace_root_eq_span` supplies the root lines and their generators needed for
pinnings over `ℤ`. Over a nontrivial ring these generators are nonzero. No reducedness,
field, or characteristic assumption is imposed.

## References

* J. S. Milne, *Algebraic Groups* (2017), §21.1 and Example 21.2.
* B. Conrad, *Reductive Group Schemes*, §5.1 (root spaces and pinnings).
* The universal-point calculation is
  `TauCeti.SpecialLinear.adDerivation_universalDiagonalTorus_root_iff`; the conversion
  to comodule weights uses `Derivation.mem_adjointWeightSpace_iff_universalPointAction`.
-/

public section

open CategoryTheory WithConv
open scoped TensorProduct

namespace TauCeti.SpecialLinear

universe u

noncomputable section

variable {R : Type u} [CommRing R] {r : ℕ}

/-- A cotangent-dual tangent vector has weight `α` exactly when its matrix entries
of every other weight vanish. This criterion uses the full torus coaction. -/
theorem mem_adjointWeightSpace_iff
    (α : Multiplicative (ULift.{u} (Fin r) →₀ ℤ))
    (x : Module.Dual R (Bialgebra.CotangentSpace R (coordinateHopfAlgebra R (r + 1)))) :
    x ∈ Derivation.adjointWeightSpace (diagonalTorusCoordinateMap r R).hom α ↔
      ∀ i j : Fin (r + 1),
        SplitTorus.weightCharacter (diagonalTorusWeight r i - diagonalTorusWeight r j) ≠ α →
          (tangentMatrix (r + 1) (Derivation.cotangentLinearEquiv (B := R) x) :
            Matrix (Fin (r + 1)) (Fin (r + 1)) R) i j = 0 := by
  rw [tangentMatrix_apply_coe]
  have hπ := congrArg (fun f => f.hom)
    (coordinateMap_comp_diagonalTorusCoordinateMap r R)
  exact
    HopfIdeal.mem_adjointWeightSpace_iff_of_weightTorus (definingHopfIdeal R (r + 1))
      (diagonalTorusWeight r) (diagonalTorusCoordinateMap r R).hom hπ α x

/-- A cotangent-dual tangent vector lies in a root weight space of the adjoint comodule
exactly when its trace-zero matrix lies in the corresponding matrix-unit line. -/
@[simp]
theorem mem_adjointWeightSpace_root_iff
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1)))
    (x : Module.Dual R (Bialgebra.CotangentSpace R (coordinateHopfAlgebra R (r + 1)))) :
    x ∈ Derivation.adjointWeightSpace (diagonalTorusCoordinateMap r R).hom
        (Multiplicative.ofAdd ((diagonalRootDatum.{u} r).root p)) ↔
      tangentMatrix (r + 1) (Derivation.cotangentLinearEquiv (B := R) x) ∈
        R ∙ LieAlgebra.SpecialLinear.single p.1.1 p.1.2 p.2 (1 : R) := by
  -- The torus characters are stored as the indexed copy of the exponent lattice.
  erw [mem_adjointWeightSpace_iff,
    ← adDerivation_universalDiagonalTorus_eq_iff,
    adDerivation_universalDiagonalTorus_root_iff]

/-- The normalized root vector of `SL_{r+1}` in the cotangent-dual model of its Lie algebra:
the tangent vector whose trace-zero matrix is `E_ij` for the root `ε_i - ε_j`. -/
def rootVector (p : SplitTorus.CoordinateRootIndex (Fin (r + 1))) :
    Module.Dual R (Bialgebra.CotangentSpace R (coordinateHopfAlgebra R (r + 1))) :=
  (Derivation.cotangentLinearEquiv (R := R)
    (A := coordinateHopfAlgebra R (r + 1)) (B := R)).symm
      ((tangentLieEquivSl (R := R) (B := R) (r + 1)).symm
        (LieAlgebra.SpecialLinear.single p.1.1 p.1.2 p.2 1))

/-- The matrix of a normalized cotangent-dual root vector is its normalized matrix unit. -/
@[simp]
theorem tangentMatrix_cotangentLinearEquiv_rootVector
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1))) :
    tangentMatrix (r + 1) (Derivation.cotangentLinearEquiv (B := R) (rootVector (R := R) p)) =
      LieAlgebra.SpecialLinear.single p.1.1 p.1.2 p.2 (1 : R) := by
  rw [rootVector, LinearEquiv.apply_symm_apply, ← tangentLieEquivSl_apply,
    LieEquiv.apply_symm_apply]

/-- Each integral adjoint root space is generated by its normalized root vector. -/
theorem adjointWeightSpace_root_eq_span
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1))) :
    Derivation.adjointWeightSpace (diagonalTorusCoordinateMap r R).hom
        (Multiplicative.ofAdd ((diagonalRootDatum.{u} r).root p)) =
      R ∙ rootVector (R := R) p := by
  ext x
  rw [mem_adjointWeightSpace_root_iff, Submodule.mem_span_singleton,
    Submodule.mem_span_singleton]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    apply (Derivation.cotangentLinearEquiv (R := R)
      (A := coordinateHopfAlgebra R (r + 1)) (B := R)).injective
    apply (tangentLieEquivSl (R := R) (B := R) (r + 1)).injective
    simp only [LieEquiv.coe_toLieHom]
    -- Injectivity elaborates the coordinate algebra as its quotient presentation.
    erw [tangentLieEquivSl_apply, tangentLieEquivSl_apply, map_smul, map_smul,
      tangentMatrix_cotangentLinearEquiv_rootVector]
    exact hc
  · rintro ⟨c, rfl⟩
    refine ⟨c, ?_⟩
    -- The cotangent equivalence has the same quotient-indexed scalar structure.
    erw [map_smul, map_smul, tangentMatrix_cotangentLinearEquiv_rootVector]

/-- Multiplication by a normalized root vector is injective, including over rings with
zero divisors. Its distinguished matrix entry recovers the scalar. -/
theorem rootVector_smul_left_injective
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1))) :
    Function.Injective (fun c : R => c • rootVector (R := R) p) := by
  intro a b h
  have hm := congrArg (fun x =>
    (tangentMatrix (r + 1) (Derivation.cotangentLinearEquiv (B := R) x) :
      Matrix (Fin (r + 1)) (Fin (r + 1)) R) p.1.1 p.1.2) h
  -- Match the scalar structure on the quotient-indexed cotangent module.
  erw [map_smul, map_smul, map_smul, map_smul,
    tangentMatrix_cotangentLinearEquiv_rootVector] at hm
  simpa [LieAlgebra.SpecialLinear.val_single, Matrix.single_apply] using hm

/-- Each integral adjoint root space is a free rank-one module, with scalar `1`
corresponding to its normalized root vector. -/
def rootSpaceEquiv (p : SplitTorus.CoordinateRootIndex (Fin (r + 1))) :
    R ≃ₗ[R] Derivation.adjointWeightSpace (diagonalTorusCoordinateMap r R).hom
      (Multiplicative.ofAdd ((diagonalRootDatum.{u} r).root p)) :=
  (LinearEquiv.ofInjective (LinearMap.toSpanSingleton R _ (rootVector (R := R) p))
    (rootVector_smul_left_injective p)).trans
      (LinearEquiv.ofEq _ _ (by
        rw [LinearMap.range_toSpanSingleton, adjointWeightSpace_root_eq_span]))

/-- The root-space parametrization sends a scalar to that multiple of the normalized
root vector. -/
@[simp]
theorem rootSpaceEquiv_apply_coe
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1))) (c : R) :
    (rootSpaceEquiv (R := R) p c :
      Module.Dual R (Bialgebra.CotangentSpace R (coordinateHopfAlgebra R (r + 1)))) =
      c • rootVector (R := R) p := by
  rw [rootSpaceEquiv, LinearEquiv.trans_apply, LinearEquiv.coe_ofEq_apply]
  -- `ofInjective` stores the cotangent module with its quotient presentation.
  erw [LinearEquiv.ofInjective_apply]
  exact LinearMap.toSpanSingleton_apply _ _ _ _

/-- The coefficient from the inverse root-space parametrization reconstructs the vector. -/
theorem rootSpaceEquiv_symm_apply_smul
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1)))
    (x : Derivation.adjointWeightSpace (diagonalTorusCoordinateMap r R).hom
      (Multiplicative.ofAdd ((diagonalRootDatum.{u} r).root p))) :
    (rootSpaceEquiv (R := R) p).symm x • rootVector (R := R) p = x := by
  rw [← rootSpaceEquiv_apply_coe]
  exact congrArg Subtype.val ((rootSpaceEquiv (R := R) p).apply_symm_apply x)

/-- The inverse root-space parametrization is the distinguished matrix entry. -/
@[simp]
theorem rootSpaceEquiv_symm_apply
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1)))
    (x : Derivation.adjointWeightSpace (diagonalTorusCoordinateMap r R).hom
      (Multiplicative.ofAdd ((diagonalRootDatum.{u} r).root p))) :
    (rootSpaceEquiv (R := R) p).symm x =
      (tangentMatrix (r + 1) (Derivation.cotangentLinearEquiv (R := R) (B := R) x) :
        Matrix (Fin (r + 1)) (Fin (r + 1)) R) p.1.1 p.1.2 := by
  have hm := congrArg (fun y =>
    (tangentMatrix (r + 1) (Derivation.cotangentLinearEquiv (B := R) y) :
      Matrix (Fin (r + 1)) (Fin (r + 1)) R) p.1.1 p.1.2)
    (rootSpaceEquiv_symm_apply_smul p x)
  -- Match the scalar structure on the quotient-indexed cotangent module.
  erw [map_smul, map_smul, tangentMatrix_cotangentLinearEquiv_rootVector] at hm
  simpa [LieAlgebra.SpecialLinear.val_single, Matrix.single_apply] using hm

/-- The normalized root vector is nonzero over every nontrivial commutative base ring. -/
theorem rootVector_ne_zero [Nontrivial R]
    (p : SplitTorus.CoordinateRootIndex (Fin (r + 1))) :
    rootVector (R := R) p ≠ 0 := by
  intro h
  have hc : (1 : R) = 0 := rootVector_smul_left_injective p (by simp [h])
  exact one_ne_zero hc

end

end TauCeti.SpecialLinear
