/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Idempotents.Primitive.Basic

/-!
# Simple modules and primitive idempotents of semisimple rings

Over a semisimple ring `R`, an idempotent `e` is primitive exactly when the left ideal `Re`
is simple. Every simple `R`-module is isomorphic to such an ideal. Thus primitive idempotents
represent all simple-module isomorphism classes; distinct primitive idempotents can represent
the same class.

This identifies the minimal left ideals of `R` as concrete representatives of its simple
modules, relating module simplicity to primitivity of idempotents in the ring.
No finite-dimensionality or base field is needed.

## Main results

* `TauCeti.isPrimitiveIdempotent_iff_isSimpleModule`: an idempotent generates a simple left
  ideal exactly when it is primitive.
* `TauCeti.isSimpleModule_iff_exists_isPrimitiveIdempotent`: a module is simple exactly when
  it is isomorphic to the left ideal generated by some primitive idempotent.

## References

* `TauCeti.RingTheory.Idempotents.Primitive.Basic`: the primitive-idempotent/indecomposable-ideal
  correspondence.
* Mathlib's `IsSemisimpleRing.exists_linearEquiv_ideal_of_isSimpleModule` and
  `IsSemisimpleRing.ideal_eq_span_idempotent`: simple-module representatives and idempotent
  generators of left ideals.
* T. Y. Lam, *A First Course in Noncommutative Rings*, 2nd ed., Section 3 (semisimple rings).
-/

public section

namespace TauCeti

variable {R : Type*} [Ring R] [IsSemisimpleRing R]

/-- The simple modules over a semisimple ring are precisely the left ideals generated by
primitive idempotents, up to linear equivalence. The module may lie in any universe. -/
theorem isSimpleModule_iff_exists_isPrimitiveIdempotent (M : Type*)
    [AddCommGroup M] [Module R M] :
    IsSimpleModule R M ↔
      ∃ e : R, IsPrimitiveIdempotent e ∧
        Nonempty (M ≃ₗ[R] (Ideal.span {e} : Ideal R)) := by
  constructor
  · intro h
    have := h
    obtain ⟨I, ⟨f⟩⟩ := IsSemisimpleRing.exists_linearEquiv_ideal_of_isSimpleModule R M
    have : IsSimpleModule R I := IsSimpleModule.congr f.symm
    obtain ⟨e, he, rfl⟩ := IsSemisimpleRing.ideal_eq_span_idempotent I
    exact ⟨e, isPrimitiveIdempotent_of_isSimpleModule he, ⟨f⟩⟩
  · rintro ⟨e, he, ⟨f⟩⟩
    have := (isPrimitiveIdempotent_iff_isSimpleModule he.isIdempotentElem).mp he
    exact IsSimpleModule.congr f

end TauCeti
