/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Quotient.Comap

/-!
# The largest Hopf ideal in a family of kernels

Given morphisms `f i : H ⟶ K i` of commutative Hopf algebras, the ordinary intersection of
their ring-theoretic kernels need not come equipped with the structure of a Hopf ideal. This file
instead takes the supremum of all Hopf ideals contained in every kernel. The result is the largest
Hopf ideal through which every `f i` factors after quotienting `H`.

Contravariantly, this is the coordinate-algebra construction of the smallest closed subgroup
scheme containing a family of affine group-scheme morphisms into `Spec H`. In particular, it
forms the closed subgroup scheme generated by a family of Kostant root subgroups and a weight
torus.

## Main declarations

* `TauCeti.CommHopfAlgCat.commonKernelHopfIdeal`: the largest Hopf ideal contained in all the
  kernels.
* `TauCeti.CommHopfAlgCat.le_commonKernelHopfIdeal_iff`: its universal property.
* `TauCeti.CommHopfAlgCat.comapOfSurjective_commonKernelHopfIdeal`: surjective pullback
  commutes with taking the common kernel of a family.
* `TauCeti.CommHopfAlgCat.map_commonKernelHopfIdeal`: an ambient isomorphism transports a
  common kernel to the common kernel of the transported family.
* `TauCeti.CommHopfAlgCat.commonKernelHopfIdeal_comp_of_injective`: postcomposing the members of
  a family with injective morphisms does not change its common kernel.
* `TauCeti.CommHopfAlgCat.commonKernelHopfIdeal_eq_of_toIdeal_le_ker`: members of the family
  that kill the common kernel of the others may be dropped.
* `TauCeti.CommHopfAlgCat.comapOfSurjective_commonKernelHopfIdeal_le_of_comp_eq`: an
  endomorphism that intertwines the family along a reindexing pulls the common-kernel ideal back
  into itself.
* `TauCeti.CommHopfAlgCat.comapOfSurjective_commonKernelHopfIdeal_le_of_comp_eq_comp`: the
  dependent-codomain version, allowing injective postcomposition maps.
* `TauCeti.CommHopfAlgCat.commonKernelLift`: the induced morphism from the quotient to each
  codomain.
* `TauCeti.CommHopfAlgCat.commonKernelLift_surjective_of_surjective`: a surjective member of the
  family remains surjective after factoring through the common-kernel quotient.
* `TauCeti.CommHopfAlgCat.commonKernelHopfIdeal_eq_map_mkQuotient_of_comp`: the common kernel of
  a family factored through a quotient is the image of its original common kernel.
* `TauCeti.CommHopfAlgCat.commonKernelHopfIdeal_commonKernelLift_eq_bot`: the quotient carries no
  further common kernel for the lifted family.
-/

public section

namespace TauCeti.CommHopfAlgCat

open CategoryTheory

universe u v w

variable {R : Type u} [CommRing R]
variable {H : _root_.CommHopfAlgCat.{v} R}
variable {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} R}

/-- The largest Hopf ideal of `H` contained in the kernels of every morphism in `f`.

The supremum is taken in the complete upper semilattice of Hopf ideals. It is preferable to an
ordinary intersection of kernels: no assertion that a ring-theoretic kernel is itself a Hopf
ideal is needed. -/
noncomputable def commonKernelHopfIdeal (f : ∀ i, H ⟶ K i) : HopfIdeal R H :=
  sSup {I | ∀ i, I.toIdeal ≤ RingHom.ker (f i).hom.toAlgHom.toRingHom}

/-- The common-kernel Hopf ideal is contained in the kernel of each member of the family. -/
theorem commonKernelHopfIdeal_toIdeal_le_ker (f : ∀ i, H ⟶ K i) (i : ι) :
    (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker (f i).hom.toAlgHom.toRingHom := by
  rw [commonKernelHopfIdeal, HopfIdeal.sSup_toIdeal]
  exact iSup_le fun I ↦ I.2 i

/-- A Hopf ideal lies below the common-kernel ideal exactly when every morphism kills it. -/
theorem le_commonKernelHopfIdeal_iff (f : ∀ i, H ⟶ K i) (I : HopfIdeal R H) :
    I ≤ commonKernelHopfIdeal f ↔
      ∀ i, I.toIdeal ≤ RingHom.ker (f i).hom.toAlgHom.toRingHom := by
  rw [commonKernelHopfIdeal]
  constructor
  · intro h i
    exact (HopfIdeal.toIdeal_le_toIdeal.mpr h).trans
      (commonKernelHopfIdeal_toIdeal_le_ker f i)
  · intro h
    exact le_sSup h

-- The transported common-kernel comparison follows the arguments in
-- `TauCeti.Algebra.Lie.F4.ShortRoot.PrimeField.Generated.Basic` and
-- `TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.Generated.Basic`.
/-- Pulling a common-kernel Hopf ideal back along a surjective ambient morphism gives the
common kernel of the precomposed family. -/
theorem comapOfSurjective_commonKernelHopfIdeal {H' : _root_.CommHopfAlgCat.{v} R}
    (f : ∀ i, H ⟶ K i) (g : H' ⟶ H) (hg : Function.Surjective g.hom) :
    (commonKernelHopfIdeal f).comapOfSurjective g.hom hg =
      commonKernelHopfIdeal (fun i ↦ g ≫ f i) := by
  apply le_antisymm
  · refine (le_commonKernelHopfIdeal_iff _ _).2 fun i x hx ↦ ?_
    -- Expose the composite Hopf morphism application beneath the kernel's ring-hom coercions.
    change (f i).hom (g.hom x) = 0
    exact RingHom.mem_ker.mp (commonKernelHopfIdeal_toIdeal_le_ker _ i
      (HopfIdeal.mem_comapOfSurjective.mp hx))
  · intro x hx
    apply HopfIdeal.mem_comapOfSurjective.mpr
    have hle : (commonKernelHopfIdeal (fun i ↦ g ≫ f i)).map g.hom ≤
        commonKernelHopfIdeal f := by
      refine (le_commonKernelHopfIdeal_iff _ _).2 fun i ↦ ?_
      rw [HopfIdeal.map_toIdeal, Ideal.map_le_iff_le_comap]
      intro y hy
      exact commonKernelHopfIdeal_toIdeal_le_ker (fun i ↦ g ≫ f i) i hy
    exact hle (HopfIdeal.mem_map_of_mem g.hom hx)

/-- An ambient isomorphism carries a common-kernel Hopf ideal to the common kernel of the
family precomposed with its inverse. -/
theorem map_commonKernelHopfIdeal {H' : _root_.CommHopfAlgCat.{v} R}
    (f : ∀ i, H ⟶ K i) (e : H ≅ H') :
    (commonKernelHopfIdeal f).map e.hom.hom =
      commonKernelHopfIdeal (fun i ↦ e.inv ≫ f i) := by
  rw [← comapOfSurjective_commonKernelHopfIdeal f e.inv
    (ConcreteCategory.bijective_of_isIso e.inv).2]
  ext y
  rw [HopfIdeal.mem_map_iff_of_surjective (ConcreteCategory.bijective_of_isIso e.hom).2,
    HopfIdeal.mem_comapOfSurjective]
  refine ⟨?_, fun hy ↦ ⟨e.inv.hom y, hy, _root_.CommHopfAlgCat.hom_inv_apply e y⟩⟩
  rintro ⟨x, hx, rfl⟩
  exact (congrArg (· ∈ commonKernelHopfIdeal f)
    (_root_.CommHopfAlgCat.inv_hom_apply e x)).mpr hx

/-- Postcomposing every member of a family with an injective morphism does not change the common
kernel. In particular the generated closed subgroup is unchanged when the codomains of the
generators are replaced by isomorphic Hopf algebras. -/
theorem commonKernelHopfIdeal_comp_of_injective {K' : ι → _root_.CommHopfAlgCat.{v} R}
    (f : ∀ i, H ⟶ K i) (m : ∀ i, K i ⟶ K' i) (hm : ∀ i, Function.Injective (m i).hom) :
    commonKernelHopfIdeal (fun i ↦ f i ≫ m i) = commonKernelHopfIdeal f := by
  have hker (i : ι) : RingHom.ker (f i ≫ m i).hom.toAlgHom.toRingHom =
      RingHom.ker (f i).hom.toAlgHom.toRingHom := by
    ext x
    simp only [RingHom.mem_ker, _root_.CommHopfAlgCat.hom_comp]
    exact (hm i).eq_iff' (map_zero _)
  simp only [commonKernelHopfIdeal, hker]

/-- **Dropping redundant members of a family.** If every member indexed by `κ` kills the
common-kernel ideal of the members indexed by `ι`, then adjoining them does not change the
common-kernel ideal.

Contravariantly, generators whose images already lie in the closed subgroup scheme generated by
the others may be dropped. -/
theorem commonKernelHopfIdeal_eq_of_toIdeal_le_ker {κ : Type*}
    {L : ι ⊕ κ → _root_.CommHopfAlgCat.{v} R} (f : ∀ j, H ⟶ L j)
    (hker : ∀ k, (commonKernelHopfIdeal fun i ↦ f (.inl i)).toIdeal ≤
      RingHom.ker (f (.inr k)).hom.toAlgHom.toRingHom) :
    commonKernelHopfIdeal f = commonKernelHopfIdeal fun i ↦ f (.inl i) := by
  apply le_antisymm
  · rw [le_commonKernelHopfIdeal_iff]
    exact fun i ↦ commonKernelHopfIdeal_toIdeal_le_ker f (.inl i)
  · rw [le_commonKernelHopfIdeal_iff]
    rintro (i | k)
    · exact commonKernelHopfIdeal_toIdeal_le_ker (fun i ↦ f (.inl i)) i
    · exact hker k

/-- **An endomorphism which intertwines a family up to injective maps of the codomains pulls the
common-kernel ideal back into itself.** This is the version of
`comapOfSurjective_commonKernelHopfIdeal_le_of_comp_eq` for a dependent family of codomains and
commuting squares `φ ≫ f (s i) = f i ≫ m i`. Injectivity of `m i` is exactly what lets vanishing
after postcomposition imply vanishing under `f i`. -/
theorem comapOfSurjective_commonKernelHopfIdeal_le_of_comp_eq_comp
    (f : ∀ i, H ⟶ K i) (φ : H ⟶ H) (hφ : Function.Surjective φ.hom) (s : ι → ι)
    (m : ∀ i, K i ⟶ K (s i)) (hm : ∀ i, Function.Injective (m i).hom)
    (hs : ∀ i, φ ≫ f (s i) = f i ≫ m i) :
    (commonKernelHopfIdeal f).comapOfSurjective φ.hom hφ ≤ commonKernelHopfIdeal f := by
  rw [le_commonKernelHopfIdeal_iff]
  intro i x hx
  -- Membership in the displayed ring-hom kernel reduces definitionally to evaluation by the
  -- bundled Hopf-algebra morphism; exposing it lets us use injectivity of the postcomposition.
  change (f i).hom x = 0
  apply hm i
  rw [map_zero]
  have hsx := congrArg (fun g : H ⟶ K (s i) => g.hom x) (hs i)
  simp only [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply] at hsx
  rw [← hsx]
  exact
    RingHom.mem_ker.mp
      (commonKernelHopfIdeal_toIdeal_le_ker f (s i) (HopfIdeal.mem_comapOfSurjective.mp hx))

/-- **An endomorphism that intertwines the family along a reindexing pulls the common-kernel ideal
back into itself.** If every `f i` factors as `φ` followed by some other member `f (s i)` of the
family, then the inverse image of the common-kernel ideal along `φ` is again contained in it.

The conclusion is one containment, not invariance: an automorphism fixing the ideal needs this
lemma once for itself and once for its inverse.

The reindexing `s` is an arbitrary function `ι → ι`; at `s = id` the hypothesis reads `φ ≫ f i =
f i`, so the statement specialises to an endomorphism fixing the family pointwise. -/
theorem comapOfSurjective_commonKernelHopfIdeal_le_of_comp_eq {L : _root_.CommHopfAlgCat.{v} R}
    (f : ι → (H ⟶ L)) (φ : H ⟶ H) (hφ : Function.Surjective φ.hom) (s : ι → ι)
    (hs : ∀ i, φ ≫ f (s i) = f i) :
    (commonKernelHopfIdeal f).comapOfSurjective φ.hom hφ ≤ commonKernelHopfIdeal f := by
  apply comapOfSurjective_commonKernelHopfIdeal_le_of_comp_eq_comp
    (K := fun _ => L) f φ hφ s (fun _ => 𝟙 L) (fun _ _ _ hxy => hxy)
  simpa using hs

/-- The morphism from the common-kernel quotient induced by the `i`th member of the family. -/
noncomputable def commonKernelLift (f : ∀ i, H ⟶ K i) (i : ι) :
    quotient H (commonKernelHopfIdeal f) ⟶ K i :=
  liftQuotient (commonKernelHopfIdeal f) (f i)
    (commonKernelHopfIdeal_toIdeal_le_ker f i)

/-- The quotient morphism followed by a common-kernel lift is the original morphism. -/
@[simp]
theorem mkQuotient_comp_commonKernelLift (f : ∀ i, H ⟶ K i) (i : ι) :
    mkQuotient H (commonKernelHopfIdeal f) ≫ commonKernelLift f i = f i :=
  mkQuotient_comp_liftQuotient (commonKernelHopfIdeal f) (f i)
    (commonKernelHopfIdeal_toIdeal_le_ker f i)

/-- A surjective member of a family remains surjective after factoring through the common-kernel
quotient. Equivalently, its contravariant map of affine group schemes remains a closed immersion
after the target is replaced by the closed subgroup generated by the family. -/
theorem commonKernelLift_surjective_of_surjective (f : ∀ i, H ⟶ K i) (i : ι)
    (hi : Function.Surjective (f i).hom) :
    Function.Surjective (commonKernelLift f i).hom :=
  liftQuotient_surjective_of_surjective (commonKernelHopfIdeal f) (f i)
    (commonKernelHopfIdeal_toIdeal_le_ker f i) hi

/-- A morphism from the common-kernel quotient is determined by its composite with the quotient
morphism. -/
theorem commonKernelLift_unique (f : ∀ i, H ⟶ K i) (i : ι)
    (g : quotient H (commonKernelHopfIdeal f) ⟶ K i)
    (hg : mkQuotient H (commonKernelHopfIdeal f) ≫ g = f i) :
    g = commonKernelLift f i :=
  liftQuotient_unique (commonKernelHopfIdeal f) (f i)
    (commonKernelHopfIdeal_toIdeal_le_ker f i) g hg

/-- If a family of Hopf-algebra morphisms factors through `H ⟶ H ⧸ I`, then its common
kernel after quotienting is the image of its original common kernel in `H ⧸ I`.

This identifies the defining Hopf ideal of the same generated closed subgroup when the ambient
affine group scheme is replaced by a quotient containing it. -/
theorem commonKernelHopfIdeal_eq_map_mkQuotient_of_comp (f : ∀ i, H ⟶ K i)
    (I : HopfIdeal R H) (c : ∀ i, quotient H I ⟶ K i)
    (hc : ∀ i, mkQuotient H I ≫ c i = f i) :
    commonKernelHopfIdeal c =
      (commonKernelHopfIdeal f).map (mkQuotient H I).hom := by
  have hI : I ≤ commonKernelHopfIdeal f :=
    (le_commonKernelHopfIdeal_iff f I).mpr fun i =>
      toIdeal_le_ker_of_mkQuotient_comp (hc i)
  let q := mkQuotient H I
  have hq : Function.Surjective q.hom := mkQuotient_surjective H I
  rw [← HopfIdeal.comapOfSurjective_eq_comapOfSurjective_iff q.hom hq]
  have hcomap_map :
      ((commonKernelHopfIdeal f).map q.hom).comapOfSurjective q.hom hq =
        commonKernelHopfIdeal f := by
    simpa only [q, hom_mkQuotient] using
      HopfIdeal.comapOfSurjective_map_mkBialgHom hI
  rw [hcomap_map]
  apply le_antisymm
  · rw [le_commonKernelHopfIdeal_iff]
    intro i x hx
    -- Kernel membership is phrased through the underlying ring homomorphism, while `hc` is an
    -- equality of bundled Hopf-algebra morphisms; expose their definitionally equal evaluations.
    change (f i).hom x = 0
    rw [← hc i, _root_.CommHopfAlgCat.comp_apply]
    exact RingHom.mem_ker.mp
      (commonKernelHopfIdeal_toIdeal_le_ker c i
        (HopfIdeal.mem_comapOfSurjective.mp hx))
  · rw [← hcomap_map]
    apply HopfIdeal.comapOfSurjective_mono q.hom hq
    rw [le_commonKernelHopfIdeal_iff]
    intro i y hy
    obtain ⟨x, hx, rfl⟩ := (HopfIdeal.mem_map_iff_of_surjective hq).mp hy
    apply RingHom.mem_ker.mpr
    -- As above, expose evaluation by the bundled morphism so the factorization equation rewrites.
    change (c i).hom (q.hom x) = 0
    rw [← _root_.CommHopfAlgCat.comp_apply, hc i]
    exact RingHom.mem_ker.mp (commonKernelHopfIdeal_toIdeal_le_ker f i hx)

/-- The common-kernel quotient carries no further common kernel: the lifted family separates it.

Contravariantly, the closed subgroup scheme generated by a family of morphisms is generated by
their factorizations through it. -/
theorem commonKernelHopfIdeal_commonKernelLift_eq_bot (f : ∀ i, H ⟶ K i) :
    commonKernelHopfIdeal (commonKernelLift f) = ⊥ := by
  refine eq_bot_of_comapOfSurjective_le _ ?_
  rw [le_commonKernelHopfIdeal_iff]
  intro i x hx
  have hxJ : (mkQuotient H (commonKernelHopfIdeal f)).hom x ∈
      commonKernelHopfIdeal (commonKernelLift f) := HopfIdeal.mem_comapOfSurjective.1 hx
  have hzero : (commonKernelLift f i).hom
      ((mkQuotient H (commonKernelHopfIdeal f)).hom x) = 0 :=
    RingHom.mem_ker.1 (commonKernelHopfIdeal_toIdeal_le_ker (commonKernelLift f) i hxJ)
  have hcomp : (commonKernelLift f i).hom
      ((mkQuotient H (commonKernelHopfIdeal f)).hom x) = (f i).hom x :=
    congrArg (fun m : H ⟶ K i => m.hom x) (mkQuotient_comp_commonKernelLift f i)
  rw [RingHom.mem_ker]
  simpa only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe] using
    hcomp.symm.trans hzero

end TauCeti.CommHopfAlgCat
