/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel.Reduced
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.BaseChange
public import Mathlib.RingTheory.Nilpotent.GeometricallyReduced
import Mathlib.RingTheory.Etale.Descent

/-!
# Smooth subgroups generated by geometrically reduced affine groups

A finite-type closed subgroup generated by geometrically reduced affine groups over a field
is smooth, including over imperfect fields. The generator coordinate algebras need not be of
finite type. This applies in particular to groups generated by root subgroups and split tori.

## References

* W. C. Waterhouse, *Introduction to Affine Group Schemes*, §11.4.
* J. S. Milne, *Algebraic Groups* (2017), Proposition 1.26 and Corollary 1.27.
-/

public section

open CategoryTheory
open scoped TensorProduct

namespace TauCeti.CommHopfAlgCat

universe u v w

/-- A finite-type subgroup generated by geometrically reduced affine groups is smooth over
any field. No perfectness assumption or finite-type assumption on the generators is needed. -/
theorem smoothCommHopfAlgProperty_quotient_commonKernelHopfIdeal_of_geometricallyReduced
    {k : Type u} [Field k] {H : _root_.CommHopfAlgCat.{v} k}
    {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} k}
    (f : ∀ i, H ⟶ K i) [∀ i, Algebra.IsGeometricallyReduced k (K i)]
    [Algebra.FiniteType k (quotient H (commonKernelHopfIdeal f))] :
    smoothCommHopfAlgProperty k (quotient H (commonKernelHopfIdeal f)) := by
  let L := AlgebraicClosure k
  let Q := quotient H (commonKernelHopfIdeal f)
  let e := quotientBaseChangeIso (K := L) (commonKernelHopfIdeal f)
  let _ : ∀ i, IsReduced (baseChange (K := L) (K i)) := fun i =>
    (Algebra.isGeometricallyReduced_field_iff k (K i)).mp inferInstance
  have hfinite : Algebra.FiniteType L
      (quotient (baseChange (K := L) H)
        (commonKernelHopfIdeal fun i => baseChangeMap (K := L) (f i))) := by
    rw [← baseChangeHopfIdeal_commonKernelHopfIdeal f]
    exact Algebra.FiniteType.of_surjective e.inv.hom.toAlgHom
      (ConcreteCategory.bijective_of_isIso e.inv).2
  have hsmooth : smoothCommHopfAlgProperty L (baseChange (K := L) Q) := by
    have h := smoothCommHopfAlgProperty_quotient_commonKernelHopfIdeal
      (fun i => baseChangeMap (K := L) (f i))
    rw [← baseChangeHopfIdeal_commonKernelHopfIdeal f] at h
    exact (smoothCommHopfAlgProperty L).prop_of_iso e h
  -- `baseChange` bundles the tensor product; `coe_of` identifies its underlying algebra.
  let _ : Algebra.Smooth L (L ⊗[k] Q) := by
    simpa only [baseChange, _root_.CommHopfAlgCat.coe_of] using
      (smoothCommHopfAlgProperty_iff _).mp hsmooth
  rw [smoothCommHopfAlgProperty_iff]
  exact Algebra.Smooth.of_smooth_tensorProduct_of_faithfullyFlat (R := k) (S := Q) L

end TauCeti.CommHopfAlgCat
