/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Maps
public import Mathlib.RingTheory.GradedAlgebra.TensorProduct

/-!
# Graded coefficient inclusion and images of the irrelevant ideal

For a surjective graded ring homomorphism `f : 𝒜 →+*ᵍ ℬ`, the irrelevant ideal `ℬ₊` is contained
in the image `𝒜₊.map f` of the irrelevant ideal `𝒜₊`. This containment is the hypothesis under
which `f` induces `AlgebraicGeometry.Proj.map f : Proj ℬ ⟶ Proj 𝒜`.

Degreewise rescaling by powers of a unit preserves the condition that a coordinate map
sends the irrelevant ideal to the unit ideal, allowing the rescaled coordinates to define
a morphism to `Proj` as well.

Coefficient inclusion also satisfies this containment, although it need not be surjective.
`TauCeti.GradedAlgebra.baseChangeMap` uses the same ring inclusion as Mathlib's
`GradedAlgHom.includeRight`, with the target grading over the extended coefficient ring.
This is the form needed for homogeneous localizations and projective coefficient projections.

## Main results

* `HomogeneousIdeal.irrelevant_le_map_of_surjective`: `ℬ₊ ≤ 𝒜₊.map f` for a surjective `f`.
* `HomogeneousIdeal.irrelevant_le_map_baseChangeMap`: the same containment for extension
  of the coefficient ring.
-/

public section

namespace HomogeneousIdeal

variable {ι A B σ τ : Type*} [Semiring A] [Semiring B] [SetLike σ A] [SetLike τ B]
  [AddSubmonoidClass σ A] [AddSubmonoidClass τ B] [DecidableEq ι] [AddCommMonoid ι]
  [PartialOrder ι] [CanonicallyOrderedAdd ι] {𝒜 : ι → σ} {ℬ : ι → τ} [GradedRing 𝒜] [GradedRing ℬ]

/-- For a surjective graded ring homomorphism `f : 𝒜 →+*ᵍ ℬ`, the irrelevant ideal `ℬ₊` is
contained in the image `𝒜₊.map f` of the irrelevant ideal `𝒜₊`. -/
theorem irrelevant_le_map_of_surjective (f : 𝒜 →+*ᵍ ℬ) (hf : Function.Surjective f) :
    irrelevant ℬ ≤ (irrelevant 𝒜).map f := by
  refine (irrelevant_le _).mpr fun i hi b hb ↦ ?_
  obtain ⟨a, rfl⟩ := hf b
  -- `f a` is homogeneous of degree `i`, so it is the image of the degree-`i` component of `a`
  rw [← DirectSum.decompose_of_mem_same ℬ (hb : f a ∈ ℬ i), ← f.map_directSumDecompose]
  exact Ideal.mem_map_of_mem _ (mem_irrelevant_of_mem _ hi (SetLike.coe_mem _))

end HomogeneousIdeal

namespace TauCeti.HomogeneousIdeal

variable {A B σ : Type*} [Semiring A] [CommSemiring B] [SetLike σ A]
  [AddSubmonoidClass σ A] (𝒜 : ℕ → σ) [GradedRing 𝒜]

/-- Unit rescaling in positive degrees preserves the condition that the irrelevant ideal maps
to the unit ideal. -/
theorem map_irrelevant_eq_top_of_unit_rescaling
    (f g : A →+* B) (c : Bˣ)
    (h : ∀ n, 0 < n → ∀ a ∈ 𝒜 n, g a = c ^ n * f a)
    (hf : (HomogeneousIdeal.irrelevant 𝒜).toIdeal.map f = ⊤) :
    (HomogeneousIdeal.irrelevant 𝒜).toIdeal.map g = ⊤ := by
  have hle : (HomogeneousIdeal.irrelevant 𝒜).toIdeal.map f ≤
      (HomogeneousIdeal.irrelevant 𝒜).toIdeal.map g := by
    rw [Ideal.map_le_iff_le_comap, HomogeneousIdeal.toIdeal_irrelevant_le]
    intro n hn a ha
    exact (Ideal.unit_mul_mem_iff_mem _ (c.isUnit.pow n)).mp
      (h n hn a ha ▸ Ideal.mem_map_of_mem g (HomogeneousIdeal.mem_irrelevant_of_mem 𝒜 hn ha))
  rw [hf] at hle
  exact top_unique hle

end TauCeti.HomogeneousIdeal

namespace TauCeti.GradedAlgebra

open scoped TensorProduct

variable {ι R A : Type*}
  [CommSemiring R] [CommSemiring A] [Algebra R A]
  (S : Type*) [CommSemiring S] [Algebra R S]
  (𝒜 : ι → Submodule R A)

/-- The coefficient inclusion as a graded ring map, using the grading over the extended
coefficient ring rather than its restriction of scalars. -/
-- The inclusion must compute in dependent types such as `Away ℬ (baseChangeMap S 𝒜 f)`.
@[expose]
def baseChangeMap : 𝒜 →+*ᵍ (fun n ↦ (𝒜 n).baseChange S) where
  __ := (Algebra.TensorProduct.includeRight : A →ₐ[R] S ⊗[R] A).toRingHom
  map_mem hx := Submodule.tmul_mem_baseChange_of_mem 1 hx

/-- Coefficient extension sends a homogeneous element to its pure tensor with one. -/
@[simp]
theorem baseChangeMap_apply (a : A) : baseChangeMap S 𝒜 a = 1 ⊗ₜ[R] a := (rfl)

end TauCeti.GradedAlgebra

namespace HomogeneousIdeal

open scoped TensorProduct
open TauCeti.GradedAlgebra

variable {R A : Type*} [CommSemiring R] [CommSemiring A] [Algebra R A]
  (S : Type*) [CommSemiring S] [Algebra R S]
  (𝒜 : ℕ → Submodule R A) [GradedAlgebra 𝒜]

/-- The irrelevant ideal after scalar extension lies in the ideal generated by the images
of the original positive-degree elements. In particular, coefficient extension defines a morphism
of `Proj`. -/
theorem irrelevant_le_map_baseChangeMap :
    irrelevant (fun n ↦ (𝒜 n).baseChange S) ≤ (irrelevant 𝒜).map (baseChangeMap S 𝒜) := by
  refine (irrelevant_le _).mpr fun n hn x hx ↦ ?_
  obtain ⟨y, hy⟩ := (𝒜 n).toBaseChange_surjective S ⟨x, hx⟩
  have hmem : ∀ y : S ⊗[R] 𝒜 n, ((𝒜 n).toBaseChange S y : S ⊗[R] A) ∈
      ((irrelevant 𝒜).map (baseChangeMap S 𝒜)).toIdeal := by
    intro y
    induction y using TensorProduct.inductionOn with
    | add y z hy hz => simpa only [map_add, Submodule.coe_add] using add_mem hy hz
    | tmul s a =>
      rw [HomogeneousIdeal.toIdeal_map]
      have ha := Ideal.mem_map_of_mem (baseChangeMap S 𝒜)
        (mem_irrelevant_of_mem 𝒜 hn a.2)
      simpa only [Submodule.coe_toBaseChange_tmul, baseChangeMap_apply,
        Algebra.TensorProduct.tmul_mul_tmul, one_mul, mul_one] using
        Ideal.mul_mem_left _ (s ⊗ₜ[R] (1 : A)) ha
  -- `irrelevant_le` presents membership in the additive submonoid; the tensor induction
  -- uses membership in the ideal, with the same underlying carrier.
  change x ∈ ((irrelevant 𝒜).map (baseChangeMap S 𝒜)).toIdeal
  simpa only [hy] using hmem y

end HomogeneousIdeal
