/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.FreeAlgebra
public import Mathlib.Algebra.Algebra.Opposite
public import Mathlib.RingTheory.Noetherian.Basic

/-!
# Finite algebras of operators detected by a pairing

Suppose a module embeds into functionals on a Noetherian module, and a family of operators is
adjoint to operators on that Noetherian module. Then the algebra generated by the first family
is finite over the base ring. In particular, a finite module over a Noetherian ring suffices.
This transfers an integral structure on cycles to an algebra of operators on functions,
without choosing a lattice in the function space.

The symbol-side evaluation takes values in the opposite endomorphism ring. Precomposition
reverses products, so this convention extends generator equivariance to the free algebra
without any commutativity assumption on the operators.

The pairing need only be bilinear over the base ring, even when the first family is linear
over a scalar algebra.
-/

public section

open MulOpposite

namespace LinearMap

section Semiring

variable {R K M V ι : Type*} [CommSemiring R] [Semiring K] [Algebra R K]
  [AddCommMonoid M] [Module R M] [AddCommMonoid V] [Module K V]
  [Module R V] [IsScalarTower R K V]

/-- An adjointness identity on generators extends to the free algebra, with the adjoint
operators evaluated in the opposite endomorphism ring. -/
theorem pairing_freeAlgebra_lift
    (P : V →ₗ[R] M →ₗ[R] K) (t : ι → Module.End K V) (u : ι → Module.End R M)
    (h : ∀ i v x, P (t i v) x = P v (u i x)) (a : FreeAlgebra R ι) (v : V) (x : M) :
    P (FreeAlgebra.lift R t a v) x =
      P v ((FreeAlgebra.lift R (fun i ↦ op (u i)) a).unop x) := by
  induction a using FreeAlgebra.induction generalizing v x with
  | grade0 r =>
      simp [Algebra.algebraMap_eq_smul_one, map_smul]
  | grade1 i => simpa only [FreeAlgebra.lift_ι_apply, unop_op] using h i v x
  | mul a b ha hb =>
      simp only [map_mul, Module.End.mul_apply, ha, hb, unop_mul]
  | add a b ha hb =>
      simp only [map_add, LinearMap.add_apply, unop_add, ha, hb]

end Semiring

variable {R K M V ι : Type*} [CommRing R] [Semiring K] [Algebra R K]
  [AddCommGroup M] [Module R M] [AddCommGroup V] [Module K V]
  [Module R V] [IsScalarTower R K V]

/-- If an injective pairing detects a family of operators by adjoint operators on a Noetherian
module, its generated algebra is finite over the base ring. The operators need not commute,
and the module carrying the first family need not be finite. -/
theorem finite_adjoin_of_injective_pairing [IsNoetherian R M]
    (P : V →ₗ[R] M →ₗ[R] K) (hP : Function.Injective P)
    (t : ι → Module.End K V) (u : ι → Module.End R M)
    (h : ∀ i v x, P (t i v) x = P v (u i x)) :
    Module.Finite R (Algebra.adjoin R (Set.range t)) := by
  let s := FreeAlgebra.lift R t
  let m := (FreeAlgebra.lift R (fun i ↦ op (u i))).toLinearMap
  -- The pairing makes the first evaluation factor through the quotient by the adjoint kernel.
  have hker : m.ker ≤ s.rangeRestrict.toLinearMap.ker := by
    intro a ha
    have hm : m a = 0 := mem_ker.mp ha
    apply Subtype.ext
    simp only [AlgHom.toLinearMap_apply, AlgHom.coe_codRestrict, ZeroMemClass.coe_zero]
    ext v
    apply hP
    ext x
    simpa only [s, m, AlgHom.toLinearMap_apply, pairing_freeAlgebra_lift P t u h,
      unop_zero, LinearMap.zero_apply, map_zero] using
      congrArg (fun z : (Module.End R M)ᵐᵒᵖ ↦ P v (z.unop x)) hm
  let : IsNoetherian R (Module.End R M)ᵐᵒᵖ :=
    isNoetherian_of_linearEquiv (opLinearEquiv R (M := Module.End R M))
  have : Module.Finite R (FreeAlgebra R ι ⧸ m.ker) :=
    Module.Finite.equiv m.quotKerEquivRange.symm
  let f := m.ker.liftQ s.rangeRestrict.toLinearMap hker
  have hf : Function.Surjective f := by
    intro y
    obtain ⟨a, ha⟩ := s.rangeRestrict_surjective y
    refine ⟨Submodule.Quotient.mk a, ?_⟩
    simpa only [f, Submodule.liftQ_apply, AlgHom.toLinearMap_apply] using ha
  rw [Algebra.adjoin_range_eq_range_freeAlgebra_lift]
  exact Module.Finite.of_surjective f hf

end LinearMap
