/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Classical
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Tangent
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Tangent
public import TauCeti.Algebra.AlgebraicGroup.Tangent.Naturality
public import TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Basic

/-!
# The tangent Lie algebra of the special linear group

The tangent Lie algebra of `SLₙ` is the special linear Lie algebra of trace-zero matrices.  The
closed immersion `SLₙ → GLₙ` identifies a tangent derivation of the determinant-one quotient
with an ambient derivation which vanishes on the ideal generated by `det - 1`.  Under the existing
tangent-matrix equivalence for `GLₙ`, this condition is exactly vanishing of the matrix trace.

The key calculation is valid over any commutative coefficient algebra.  A tangent point of `GLₙ`
over the dual numbers has matrix `1 + εX`; the first-order part of its determinant is `trace X`.
Consequently, the resulting equivalence is linear over the coefficient algebra and preserves the
convolution and matrix-commutator Lie brackets.

This gives the standard `SLₙ` worked example in the ReductiveGroups roadmap's Layer 2 target on
the tangent space at the identity / `Lie(G)` and the Lie algebra of a closed subgroup.

## Main declarations

* `TauCeti.SpecialLinear.mem_lieSubalgebra_definingHopfIdeal_iff`: an ambient tangent derivation
  lies in the determinant-one Lie subalgebra exactly when its tangent matrix has trace zero.
* `TauCeti.SpecialLinear.tangentMatrix`: a tangent vector to `SLₙ`, as a trace-zero matrix.
* `TauCeti.SpecialLinear.tangentLieEquivSl`: the tangent Lie algebra of `SLₙ` is its classical
  special linear Lie algebra.

## References

* J. S. Milne, *Algebraic Groups* (2017), §10.
* The target Lie algebra is Mathlib's `LieAlgebra.SpecialLinear.sl`.
-/

public section

namespace TauCeti

universe u w

/-! ### Trace-zero matrices from the determinant-one quotient -/

namespace SpecialLinear

open LieAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing

variable {R : Type u} [CommRing R] {B : Type w} [CommRing B] [Algebra R B]
variable (n : ℕ)

/-- An ambient tangent derivation lies in the Lie algebra cut out by the determinant-one ideal
exactly when its tangent matrix has trace zero. -/
theorem mem_lieSubalgebra_definingHopfIdeal_iff
    (d : Derivation R (GeneralLinear.coordinateHopfAlgebra R n)
      (Bialgebra.CounitAlgebra R (GeneralLinear.coordinateHopfAlgebra R n) B)) :
    d ∈ HopfIdeal.lieSubalgebra (B := B) (definingHopfIdeal R n) ↔
      Matrix.trace (GeneralLinear.tangentMatrix n d) = 0 := by
  rw [HopfIdeal.mem_lieSubalgebra_iff_of_toIdeal_eq_span (B := B) (definingHopfIdeal R n)
    (definingHopfIdeal_toIdeal R n) d]
  simp only [Set.mem_singleton_iff, forall_eq, map_sub, d.map_one_eq_zero, sub_zero]
  rw [GeneralLinear.trace_tangentMatrix]
  exact Iff.rfl

/-- The trace-zero matrix of a tangent vector to `SLₙ`. It is obtained by including the
derivation into the tangent Lie algebra of `GLₙ` and evaluating on the generic matrix entries. -/
noncomputable def tangentMatrix :
    Derivation R (coordinateHopfAlgebra R n)
        (Bialgebra.CounitAlgebra R (coordinateHopfAlgebra R n) B) →ₗ[B]
      LieAlgebra.SpecialLinear.sl (Fin n) B :=
  let ambient := (GeneralLinear.tangentMatrix (R := R) (B := B) n).comp
    (HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n)).toLinearMap
  ambient.codRestrict (LieAlgebra.SpecialLinear.sl (Fin n) B) fun d => by
    apply (mem_lieSubalgebra_definingHopfIdeal_iff n _).mp
    -- Expose application of the Lie morphism's underlying linear map.
    change HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n) d ∈
      HopfIdeal.lieSubalgebra (B := B) (definingHopfIdeal R n)
    simpa only [HopfIdeal.quotientLieEquiv_apply_coe] using
      (HopfIdeal.quotientLieEquiv (B := B) (definingHopfIdeal R n) d).property

/-- The underlying matrix of `SpecialLinear.tangentMatrix` is the ambient `GLₙ` tangent matrix
after precomposition with the determinant-one quotient. -/
@[simp]
theorem tangentMatrix_apply_coe
    (d : Derivation R (coordinateHopfAlgebra R n)
      (Bialgebra.CounitAlgebra R (coordinateHopfAlgebra R n) B)) :
    (tangentMatrix n d : Matrix (Fin n) (Fin n) B) =
      GeneralLinear.tangentMatrix n
        (HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n) d) := by
  rw [tangentMatrix]
  -- This theorem is the application rule for the codomain restriction. Its proof must expose
  -- that restriction and the composed map once because their stored `toFun` fields have no
  -- equation lemma that rewrites this goal.
  change GeneralLinear.tangentMatrix n
    (HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n) d) = _
  rfl

/-- Changing the coefficient algebra of a tangent vector applies the coefficient map to
each entry of its trace-zero matrix. -/
@[simp]
theorem tangentMatrix_mapValue_coe {C : Type*} [CommRing C] [Algebra R C]
    (φ : B →ₐ[R] C)
    (d : Derivation R (coordinateHopfAlgebra R n)
      (Bialgebra.CounitAlgebra R (coordinateHopfAlgebra R n) B)) :
    (tangentMatrix n (Derivation.mapValue φ d) : Matrix (Fin n) (Fin n) C) =
      (tangentMatrix n d : Matrix (Fin n) (Fin n) B).map φ := by
  rw [tangentMatrix_apply_coe, tangentMatrix_apply_coe,
    HopfIdeal.quotientLieHom_mapValue, GeneralLinear.tangentMatrix_mapValue]

/-- An entry of the special-linear tangent matrix is the derivation evaluated on the image of
the corresponding generic matrix coordinate in the determinant-one quotient. -/
@[simp]
theorem tangentMatrix_apply
    (d : Derivation R (coordinateHopfAlgebra R n)
      (Bialgebra.CounitAlgebra R (coordinateHopfAlgebra R n) B)) (i j : Fin n) :
    (tangentMatrix n d : Matrix (Fin n) (Fin n) B) i j =
      Bialgebra.CounitAlgebra.algEquivSelf R (coordinateHopfAlgebra R n) B
        (d ((coordinateMap R n).hom (GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
          (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j)))))) := by
  rw [tangentMatrix_apply_coe, GeneralLinear.tangentMatrix_apply,
    HopfIdeal.quotientLieHom_apply_apply, coordinateMap_apply]
  exact Bialgebra.CounitAlgebra.algEquivSelf_apply R _ B _

private theorem tangentMatrix_injective :
    Function.Injective (tangentMatrix (R := R) (B := B) n) := by
  intro d e hde
  apply HopfIdeal.quotientLieHom_injective (B := B) (definingHopfIdeal R n)
  have hval := congrArg Subtype.val hde
  rw [tangentMatrix_apply_coe, tangentMatrix_apply_coe] at hval
  apply (GeneralLinear.tangentLinearEquivMatrix (R := R) (B := B) n).injective
  simpa only [GeneralLinear.tangentLinearEquivMatrix_apply] using hval

private theorem tangentMatrix_surjective :
    Function.Surjective (tangentMatrix (R := R) (B := B) n) := by
  intro X
  let d := (GeneralLinear.tangentLieEquivMatrix (R := R) (B := B) n).symm X.val
  have htraceX : Matrix.trace X.val = 0 := X.property
  have hdtrace : Matrix.trace (GeneralLinear.tangentMatrix n d) = 0 := by
    rw [← GeneralLinear.tangentLieEquivMatrix_apply]
    rw [(GeneralLinear.tangentLieEquivMatrix (R := R) (B := B) n).apply_symm_apply]
    exact htraceX
  have hdmem : d ∈ HopfIdeal.lieSubalgebra (B := B) (definingHopfIdeal R n) :=
    (mem_lieSubalgebra_definingHopfIdeal_iff n d).mpr hdtrace
  let d' : HopfIdeal.lieSubalgebra (B := B) (definingHopfIdeal R n) := ⟨d, hdmem⟩
  let e := (HopfIdeal.quotientLieEquiv (B := B) (definingHopfIdeal R n)).symm d'
  refine ⟨e, ?_⟩
  apply Subtype.ext
  rw [tangentMatrix_apply_coe]
  have he : HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n) e = d := by
    rw [← HopfIdeal.quotientLieEquiv_apply_coe]
    exact congrArg Subtype.val
      ((HopfIdeal.quotientLieEquiv (B := B) (definingHopfIdeal R n)).apply_symm_apply d')
  rw [he, ← GeneralLinear.tangentLieEquivMatrix_apply]
  exact (GeneralLinear.tangentLieEquivMatrix (R := R) (B := B) n).apply_symm_apply X.val

/-- The tangent-matrix map for `SLₙ` preserves the Lie bracket, carrying convolution commutators
to matrix commutators. -/
@[simp]
theorem tangentMatrix_lie
    (d e : Derivation R (coordinateHopfAlgebra R n)
      (Bialgebra.CounitAlgebra R (coordinateHopfAlgebra R n) B)) :
    tangentMatrix n ⁅d, e⁆ = ⁅tangentMatrix n d, tangentMatrix n e⁆ := by
  apply Subtype.ext
  calc
    (tangentMatrix n ⁅d, e⁆ : Matrix (Fin n) (Fin n) B) =
        GeneralLinear.tangentMatrix n
          (HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n) ⁅d, e⁆) :=
      tangentMatrix_apply_coe n ⁅d, e⁆
    _ = ⁅GeneralLinear.tangentMatrix n
          (HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n) d),
        GeneralLinear.tangentMatrix n
          (HopfIdeal.quotientLieHom (B := B) (definingHopfIdeal R n) e)⁆ := by
      rw [LieHom.map_lie, GeneralLinear.tangentMatrix_lie]
    _ = (⁅tangentMatrix n d, tangentMatrix n e⁆ :
        LieAlgebra.SpecialLinear.sl (Fin n) B) := by
      rw [LieSubalgebra.coe_bracket, tangentMatrix_apply_coe, tangentMatrix_apply_coe]

/-- **The tangent Lie algebra of `SLₙ` is the special linear Lie algebra.** The equivalence is
valid after extension to every commutative `R`-algebra `B`. -/
noncomputable def tangentLieEquivSl :
    LieEquiv B
      (Derivation R (coordinateHopfAlgebra R n)
        (Bialgebra.CounitAlgebra R (coordinateHopfAlgebra R n) B))
      (LieAlgebra.SpecialLinear.sl (Fin n) B) :=
  LieEquiv.ofBijective
    { tangentMatrix (R := R) (B := B) n with
      map_lie' := fun {d e} => tangentMatrix_lie n d e }
    ⟨tangentMatrix_injective n, tangentMatrix_surjective n⟩

/-- The tangent Lie equivalence is implemented by `SpecialLinear.tangentMatrix`. -/
@[simp]
theorem tangentLieEquivSl_apply
    (d : Derivation R (coordinateHopfAlgebra R n)
      (Bialgebra.CounitAlgebra R (coordinateHopfAlgebra R n) B)) :
    tangentLieEquivSl n d = tangentMatrix n d := by
  rfl

end SpecialLinear

end TauCeti
