/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.DirectSum.Idempotents
public import Mathlib.RingTheory.HopkinsLevitzki
public import TauCeti.RingTheory.Idempotents.Module
public import TauCeti.RingTheory.KrullSchmidt.Existence
public import TauCeti.RingTheory.KrullSchmidt.Uniqueness
public import TauCeti.RingTheory.Idempotents.Primitive.Basic

/-!
# Decomposing `1` into primitive orthogonal idempotents

Decompositions of the unit of a ring `A` into orthogonal idempotents are the same thing as
decompositions of the left regular module `A` into left ideals:

* a decomposition `A = V₁ ⊕ ⋯ ⊕ Vₙ` into left ideals produces, from the components of
  `1 = e₁ + ⋯ + eₙ`, a complete family of orthogonal idempotents
  (Mathlib's `DirectSum.completeOrthogonalIdempotents_idempotent`), and `eᵢ` generates `Vᵢ`
  (`DirectSum.span_singleton_idempotent`);
* conversely, a complete family of orthogonal idempotents `e` decomposes `A` as the internal direct
  sum of the left ideals `Aeᵢ` (`CompleteOrthogonalIdempotents.isInternal_span_singleton`): the
  component of `x` in `Aeᵢ` is `x eᵢ`.

Under this dictionary a summand `Aeᵢ` is indecomposable exactly when `eᵢ` is primitive
(`TauCeti.isPrimitiveIdempotent_iff_isIndecomposableModule`), so the Krull-Schmidt theorem for the
left regular module of a left Artinian ring becomes a statement about idempotents: `1` is a sum of
finitely many primitive orthogonal idempotents
(`TauCeti.exists_completeOrthogonalIdempotents_isPrimitiveIdempotent`), and any two such
decompositions have the same number of terms and are matched by a bijection under which the left
ideals `Aeᵢ` and `Afⱼ` are isomorphic
(`CompleteOrthogonalIdempotents.exists_equiv_linearEquiv_span_singleton`). The left ideals `Aeᵢ`
are projective, being direct summands of `A`, and every simple module is a quotient of one of them
(`CompleteOrthogonalIdempotents.exists_surjective_of_isSimpleModule`): this is the first half of
the correspondence between the primitive idempotents of a finite-dimensional algebra and its
simple modules.

## Main results

* `DirectSum.span_singleton_idempotent`: the idempotent attached to a summand of a decomposition
  of `A` into left ideals generates that summand.
* `CompleteOrthogonalIdempotents.isInternal_span_singleton`: a complete family of orthogonal
  idempotents decomposes `A` as `⨁ᵢ Aeᵢ`.
* `TauCeti.exists_completeOrthogonalIdempotents_isPrimitiveIdempotent`: **in a left Artinian ring,
  `1` is a finite sum of primitive orthogonal idempotents.**
* `TauCeti.exists_surjective_span_singleton_of_sum_eq_one`: if a finite family sums to `1`, every
  simple module is a quotient of the left ideal generated by one of its terms.
* `CompleteOrthogonalIdempotents.exists_equiv_linearEquiv_span_singleton`: **uniqueness** of such a
  decomposition up to reindexing and isomorphism of the left ideals `Aeᵢ`, and
  `CompleteOrthogonalIdempotents.card_eq_card_of_isPrimitiveIdempotent`: the number of terms is
  an invariant of the ring.
* `CompleteOrthogonalIdempotents.exists_surjective_of_isSimpleModule`: every simple module is a
  quotient of some `Aeᵢ`.

## References

* I. Assem, D. Simson, A. Skowroński, *Elements of the Representation Theory of Associative
  Algebras, Vol. 1*, Section I.4.
* T. Y. Lam, *A First Course in Noncommutative Rings*, 2nd ed., §21 and §22.
-/

public section

open DirectSum

open scoped Pointwise

namespace TauCeti

variable {A ι : Type*} [Ring A] [Fintype ι] {e : ι → A}

/-- **Every simple module is a quotient of a left ideal generated by one term of a decomposition
of `1`.** If `∑ i, e i = 1` and `m` is nonzero, some `e i • m` is nonzero, so `x ↦ x • m` maps
`A(e i)` onto the simple module. Neither idempotence nor orthogonality of `e` is needed. -/
theorem exists_surjective_span_singleton_of_sum_eq_one (he : ∑ i, e i = 1)
    (M : Type*) [AddCommGroup M] [Module A M] [IsSimpleModule A M] :
    ∃ (i : ι) (f : (Ideal.span {e i} : Ideal A) →ₗ[A] M), Function.Surjective f := by
  have := IsSimpleModule.nontrivial A M
  obtain ⟨m, hm⟩ := exists_ne (0 : M)
  obtain ⟨i, hi⟩ : ∃ i, e i • m ≠ 0 := by
    by_contra! h
    exact hm <| by
      rw [← sum_smul_eq_self_of_sum_eq_one he m, Finset.sum_eq_zero fun i _ ↦ h i]
  let f : (Ideal.span {e i} : Ideal A) →ₗ[A] M :=
    LinearMap.toSpanSingleton A M m ∘ₗ (Ideal.span {e i} : Ideal A).subtype
  refine ⟨i, f, LinearMap.range_eq_top.1 ?_⟩
  refine (eq_bot_or_eq_top (LinearMap.range f)).resolve_left fun h ↦ hi ?_
  have : f (spanSingletonGenerator (e i)) ∈ LinearMap.range f :=
    LinearMap.mem_range_self _ _
  rw [h, Submodule.mem_bot] at this
  simpa [f] using this

end TauCeti

namespace DirectSum

variable {A ι : Type*} [Semiring A] [DecidableEq ι] (V : ι → Ideal A) [Decomposition V]

/-- **The idempotent attached to a summand generates it.** If `A = ⨁ᵢ Vᵢ` as left ideals and
`1 = ∑ᵢ eᵢ` with `eᵢ ∈ Vᵢ`, then `Vᵢ = Aeᵢ`: every `x ∈ Vᵢ` is its own `i`-th component, which is
`x eᵢ`. -/
theorem span_singleton_idempotent (i : ι) : Ideal.span {idempotent V i} = V i := by
  refine le_antisymm ((Ideal.span_singleton_le_iff_mem _).2 (decompose V 1 i).2) fun x hx ↦ ?_
  rw [← decompose_of_mem_same V hx, decompose_eq_mul_idempotent]
  exact Ideal.mul_mem_left _ x (Ideal.mem_span_singleton_self _)

end DirectSum

namespace IsIdempotentElem

/-- An idempotent stays idempotent in the opposite multiplication. -/
theorem op {M : Type*} [Mul M] {e : M} (he : IsIdempotentElem e) :
    IsIdempotentElem (MulOpposite.op e) :=
  congrArg MulOpposite.op he.eq

variable {A : Type*} [Semiring A] {e : A}

/-- **The left ideal `Ae` is the piece `e • A` cut out by `e` acting on the right**, that is, by
`MulOpposite.op e` acting through the opposite ring; this is the bridge to the Peirce
decomposition `TauCeti.isInternal_smul_top`. -/
theorem span_singleton_eq_op_smul_top (he : IsIdempotentElem e) :
    (Ideal.span {e} : Ideal A) = MulOpposite.op e • (⊤ : Submodule A A) := by
  ext x
  rw [TauCeti.mem_span_singleton_iff_mul_eq_self he, he.op.mem_smul_top_iff_smul_eq_self,
    MulOpposite.smul_eq_mul_unop, MulOpposite.unop_op]

end IsIdempotentElem

namespace OrthogonalIdempotents

variable {A ι : Type*} [Semiring A] {e : ι → A}

/-- A family of orthogonal idempotents stays orthogonal in the opposite ring. -/
theorem op (he : OrthogonalIdempotents e) : OrthogonalIdempotents (MulOpposite.op ∘ e) where
  idem i := (he.idem i).op
  ortho _ _ hij := congrArg MulOpposite.op (he.ortho hij.symm)

end OrthogonalIdempotents

namespace CompleteOrthogonalIdempotents

section Semiring

variable {A ι : Type*} [Semiring A] [Fintype ι] {e : ι → A}

/-- A complete family of orthogonal idempotents stays complete in the opposite ring. -/
theorem op (he : CompleteOrthogonalIdempotents e) :
    CompleteOrthogonalIdempotents (MulOpposite.op ∘ e) where
  __ := he.toOrthogonalIdempotents.op
  complete := by
    rw [Function.comp_def, ← Finset.op_sum, he.complete, MulOpposite.op_one]

/-- **A complete family of orthogonal idempotents decomposes the ring** as the internal direct sum
`A = ⨁ᵢ Aeᵢ` of the left ideals it generates, the component of `x` in `Aeᵢ` being `x eᵢ`. This is
the converse of Mathlib's `DirectSum.completeOrthogonalIdempotents_idempotent`, and the Peirce
decomposition `TauCeti.isInternal_smul_top` of `A` under right multiplication. -/
theorem isInternal_span_singleton [DecidableEq ι] (he : CompleteOrthogonalIdempotents e) :
    IsInternal fun i ↦ (Ideal.span {e i} : Ideal A) := by
  simpa only [(he.idem _).span_singleton_eq_op_smul_top, Function.comp_apply] using
    TauCeti.isInternal_smul_top (S := A) (M := A) he.op

end Semiring

section Ring

variable {A : Type*} [Ring A] {ι : Type*} [Fintype ι] {e : ι → A}

/-- **Every simple module is a quotient of one of the left ideals `Aeᵢ`** of a complete family of
orthogonal idempotents. A nonzero `m : M` is `∑ᵢ eᵢ m`, so some `eᵢ m` is nonzero, and then
`x ↦ x m` maps `Aeᵢ` onto the simple module `M`. -/
theorem exists_surjective_of_isSimpleModule (he : CompleteOrthogonalIdempotents e)
    (M : Type*) [AddCommGroup M] [Module A M] [IsSimpleModule A M] :
    ∃ (i : ι) (f : (Ideal.span {e i} : Ideal A) →ₗ[A] M), Function.Surjective f :=
  TauCeti.exists_surjective_span_singleton_of_sum_eq_one he.complete M

/-- **Uniqueness of a decomposition of `1` into primitive orthogonal idempotents.** In a left
Artinian ring, two complete families `e` and `f` of primitive orthogonal idempotents are matched
by a bijection `σ` of their index sets under which `Aeᵢ ≅ Af_{σ i}`. This is the Krull-Schmidt
theorem for the left regular module, read through
`CompleteOrthogonalIdempotents.isInternal_span_singleton`. -/
theorem exists_equiv_linearEquiv_span_singleton [IsArtinianRing A] {κ : Type*} [Fintype κ]
    {f : κ → A} (he : CompleteOrthogonalIdempotents e) (hf : CompleteOrthogonalIdempotents f)
    (hpe : ∀ i, TauCeti.IsPrimitiveIdempotent (e i))
    (hpf : ∀ j, TauCeti.IsPrimitiveIdempotent (f j)) :
    ∃ σ : ι ≃ κ, ∀ i,
      Nonempty ((Ideal.span {e i} : Ideal A) ≃ₗ[A] (Ideal.span {f (σ i)} : Ideal A)) :=
  open scoped Classical in
  TauCeti.exists_equiv_linearEquiv_of_iSupIndep he.isInternal_span_singleton.submodule_iSupIndep
    he.isInternal_span_singleton.submodule_iSup_eq_top (fun i ↦ (hpe i).isIndecomposableModule)
    hf.isInternal_span_singleton.submodule_iSupIndep
    hf.isInternal_span_singleton.submodule_iSup_eq_top (fun j ↦ (hpf j).isIndecomposableModule)

/-- In a left Artinian ring, the number of terms in a decomposition of `1` into primitive
orthogonal idempotents does not depend on the decomposition. -/
theorem card_eq_card_of_isPrimitiveIdempotent [IsArtinianRing A] {κ : Type*} [Fintype κ]
    {f : κ → A} (he : CompleteOrthogonalIdempotents e) (hf : CompleteOrthogonalIdempotents f)
    (hpe : ∀ i, TauCeti.IsPrimitiveIdempotent (e i))
    (hpf : ∀ j, TauCeti.IsPrimitiveIdempotent (f j)) :
    Fintype.card ι = Fintype.card κ :=
  let ⟨σ, _⟩ := he.exists_equiv_linearEquiv_span_singleton hf hpe hpf
  Fintype.card_congr σ

end Ring

end CompleteOrthogonalIdempotents

namespace TauCeti

variable (A : Type*) [Ring A]

/-- **Existence of a decomposition of `1` into primitive orthogonal idempotents.** In a left
Artinian ring — for instance a finite-dimensional algebra over a field — `1 = e₀ + ⋯ + eₙ₋₁` for a
complete family of orthogonal idempotents each of which is primitive.

The left regular module is the internal direct sum of finitely many indecomposable left ideals
(`TauCeti.exists_isInternal_isIndecomposableModule`); the components of `1` along that
decomposition are complete orthogonal idempotents generating the summands
(`DirectSum.span_singleton_idempotent`), hence primitive. -/
theorem exists_completeOrthogonalIdempotents_isPrimitiveIdempotent [IsArtinianRing A] :
    ∃ (n : ℕ) (e : Fin n → A), CompleteOrthogonalIdempotents e ∧
      ∀ i, IsPrimitiveIdempotent (e i) := by
  classical
  obtain ⟨s, hs, hint⟩ := exists_isInternal_isIndecomposableModule (A := A) (M := A)
  let V : s → Ideal A := fun N ↦ N
  let : Decomposition V := hint.chooseDecomposition
  let σ := Fintype.equivFin s
  refine ⟨Fintype.card s, idempotent V ∘ σ.symm,
    (CompleteOrthogonalIdempotents.equiv σ.symm).2 (completeOrthogonalIdempotents_idempotent V),
    fun i ↦ isPrimitiveIdempotent_of_isIndecomposableModule (isIdempotentElem_idempotent V _) ?_⟩
  rw [Function.comp_apply, span_singleton_idempotent]
  exact hs _ (σ.symm i).2

end TauCeti
