/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.LowerCentralSeries.Graded.Subgroup
public import TauCeti.Topology.Algebra.Group.Profinite.Free.BasisModification
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Character.Kernel
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicUnits

/-!
# The kernel of an exponent sum of a free pro-`p` group and its graded pieces

Let `F = freeProP p X` be the free pro-`p` group on a finite type `X` with generators `x_i`, and
fix `i ∈ X`. The **kernel of the `i`-th exponent sum** `X_i := ker (F → ℤ_p, y ↦ (exponentSum y)_i)`
(`TauCeti.freeProP.exponentSumKer`) is the closed normal subgroup of `F` topologically generated,
as a normal subgroup, by the generators `x_j` with `j ≠ i`; it contains the closed commutator
subgroup. When a continuous character `χ : F → ℤ_pˣ` is trivial on the `x_j` with `j ≠ i` and takes
`x_i` to an element of infinite order, its kernel is exactly `X_i`: this is the kernel `X = ker χ`
of the orientation of a Demushkin group in Labute's normal form, on whose graded Lie algebra his
classification of the dyadic even-rank Demushkin groups runs (Labute, §4).

The graded pieces `gr_m(X_i) ≤ gr_m(F)` of `X_i` along the lower `p`-series
(`TauCeti.gradedPieceOf`) are computed by three statements, which are Labute's Lemmas 1–3 in our
`0`-based indexing:

* **Complement** (Lemma 1). The class of `y ∈ λ_m(F)` lies in `gr_m(X_i)` exactly when `p ^ (m + 1)`
  divides the `i`-th exponent sum of `y`, and `gr_m(F) = gr_m(X_i) ⊕ 𝔽_p π^m ξ_i`, where `ξ_i` is
  the class of `x_i` and `π` the `p`-power operator
  (`TauCeti.freeProP.isCompl_gradedPieceOf_exponentSumKer_span_gradedPowIter`).
* **Generation** (Lemma 2). For `m ≥ 1`, `gr_{m+1}(X_i)` is generated by the `p`-powers `π τ` and
  the brackets `[τ, ξ_j]` with `τ ∈ gr_m(X_i)`, stated as a criterion for a subspace to contain
  `gr_{m+1}(X_i)` (`TauCeti.freeProP.gradedPieceOf_exponentSumKer_succ_le`). The proof decomposes a
  class of `gr_m(F)` along the complement of Lemma 1; the only bracket not covered by the hypotheses
  is `[π^m ξ_i, y]`, which is `π [π^{m-1} ξ_i, y]` for `m ≥ 2` and
  `π [ξ_i, y] - (p choose 2) • [[ξ_i, y], ξ_i]` for `m = 1`.
* **The constrained span statement** (Lemma 3). Let `ρ ∈ gr_1(F)` be the class of a relator whose
  partial derivatives `∂_k ρ` span `gr_0(F)`, whose `p`-power part sits on a single generator
  `x_{i₀}`, and whose derivatives at the generators other than `x_{i₀}` span every generator class
  `ξ_j` with `j ≠ i₁`. Then for every `m ≥ 1`

    `gr_{m+1}(X_{i₁}) = δ_ρ(gr_m(X_{i₁})^X) + T_{m+1}`,

  where `δ_ρ` is the basis-modification map of `TauCeti.freeProP.basisModificationDelta` and the
  tail `T_{m+1}` is spanned by the `π^{m+1} ξ_a` with `a ≠ i₁`
  (`gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_span_gradedPowIter` in
  `TauCeti.freeProP`). This refines the unconstrained span statements of
  `Free/BasisModification.lean`: the basis corrections `ω ∈ gr_m(F)^X` realizing a discrepancy in
  `gr_{m+1}(X_{i₁})` may be chosen in `gr_m(X_{i₁})^X`, that is, inside the kernel of the
  orientation, which is what keeps the orientation fixed along a successive approximation. The
  statement holds for every prime `p`; the relators `x₁^q (x₁, x₂)(x₃, x₄) ⋯ (x_{n-1}, x_n)` with
  `p ∣ q` satisfy its hypotheses with `i₀ = x₁` and `i₁ = x₂`.
* **The exceptional generator** (Lemma 3 of Labute's §4.2). When one further generator class
  `ξ_{i₂}` can only be reached through the derivative `∂_{i₀} ρ` at the `p`-power generator, the
  same argument gives

    `gr_{m+1}(X_{i₁}) = δ_ρ(gr_m(X_{i₁})^X) + T_{m+1} + 𝔽_p π^m [ξ_{i₂}, ξ_{i₁}]`

  (`gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket`), and
  when the coefficient of `∂_{i₀} ρ` in `ξ_{i₂}` is nonzero the tail `π^{m+1} ξ_{i₂}` lies in the
  image of `δ_ρ`, so the tail may be taken over the `a ≠ i₁, i₂`
  (`gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket_of_ne`).
  The extra vector `π^m [ξ_{i₂}, ξ_{i₁}]` is genuinely needed at `p = 2`: the relator
  `x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯` has `i₀ = x₁`, `i₁ = x₄` and `i₂ = x₂`.

## Main definitions

* `TauCeti.freeProP.exponentSumKer`: the kernel `X_i` of the `i`-th exponent sum.

## Main results

* `TauCeti.freeProP.exponentSumKer_eq_topologicalClosure_normalClosure`: `X_i` is the closed
  normal closure of the generators `x_j`, `j ≠ i`; hence a continuous homomorphism trivial on
  those generators is trivial on `X_i` (`ContinuousMonoidHom.exponentSumKer_le_ker`), and a
  dyadic character whose values at those generators square to `1` is trivial on `X_i ∩ λ_1(F)`
  (`ContinuousMonoidHom.apply_eq_one_of_mem_exponentSumKer_of_mem_pLowerCentralSeries_one`).
* `ContinuousMonoidHom.exponentSumKer_eq_ker`: `X_i` is the kernel of every continuous character
  trivial on the generators `x_j`, `j ≠ i`, and of infinite order at `x_i`.
* `ContinuousMonoidHom.apply_mem_exponentSumKer_iff_of_forall_inv_mul_apply_mem`: a continuous
  endomorphism moving each generator inside `X_i` preserves `X_i`.
* `TauCeti.freeProP.gradedMk_mem_gradedPieceOf_exponentSumKer_iff`: the class of `y ∈ λ_m(F)`
  lies in `gr_m(X_i)` exactly when `p ^ (m + 1)` divides its `i`-th exponent sum.
* `TauCeti.freeProP.isCompl_gradedPieceOf_exponentSumKer_span_gradedPowIter`:
  `gr_m(F) = gr_m(X_i) ⊕ 𝔽_p π^m ξ_i`.
* `TauCeti.freeProP.gradedPieceOf_exponentSumKer_le_of_le_sup_span_gradedPowIter`: a subspace of
  `gr_m(X_i)` which together with `π^m ξ_i` spans `gr_m(X_i)` is `gr_m(X_i)`.
* `TauCeti.freeProP.gradedPieceOf_exponentSumKer_succ_le`: the generation criterion for
  `gr_{m+1}(X_i)`.
* `gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_span_gradedPowIter`,
  `gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket` and
  `gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket_of_ne` (in
  `TauCeti.freeProP`): the constrained span statement, without and with an exceptional
  generator.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, §4,
  Lemmas 1–3.
-/

public section

namespace TauCeti

open Subgroup Submodule
open scoped commutatorElement

universe u

namespace freeProP

variable {p : ℕ} [Fact p.Prime] {X : Type u}

/-! ### The kernel of an exponent sum -/

variable (p X) in
/-- **The kernel of the `i`-th exponent sum** of the free pro-`p` group on `X`: the closed normal
subgroup of the elements whose exponent sum at the generator `x_i` vanishes
(`TauCeti.freeProP.mem_exponentSumKer_iff`). It contains the closed commutator subgroup and the
generators `x_j` for `j ≠ i`, and it is their closed normal closure
(`TauCeti.freeProP.exponentSumKer_eq_topologicalClosure_normalClosure`). -/
noncomputable def exponentSumKer (i : X) : Subgroup (freeProP p X) :=
  ((Pi.evalAddMonoidHom (fun _ : X ↦ ℤ_[p]) i).toMultiplicative.comp
    (exponentSum p X).toMonoidHom).ker

@[simp]
theorem mem_exponentSumKer_iff {i : X} {y : freeProP p X} :
    y ∈ exponentSumKer p X i ↔ (exponentSum p X y).toAdd i = 0 := by
  rw [exponentSumKer, MonoidHom.mem_ker, MonoidHom.comp_apply,
    AddMonoidHom.coe_toMultiplicative, Function.comp_apply, Function.comp_apply, ofAdd_eq_one,
    Pi.evalAddMonoidHom_apply, ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass]

instance (i : X) : (exponentSumKer p X i).Normal :=
  MonoidHom.normal_ker _

theorem isClosed_exponentSumKer (i : X) :
    IsClosed (exponentSumKer p X i : Set (freeProP p X)) := by
  have : (exponentSumKer p X i : Set (freeProP p X)) =
      (fun y ↦ (exponentSum p X y).toAdd i) ⁻¹' {0} := by
    ext y
    rw [SetLike.mem_coe, mem_exponentSumKer_iff, Set.mem_preimage, Set.mem_singleton_iff]
  rw [this]
  exact isClosed_singleton.preimage
    ((continuous_apply i).comp (continuous_toAdd.comp (exponentSum p X).continuous))

theorem commutator_le_exponentSumKer (i : X) :
    commutator (freeProP p X) ≤ exponentSumKer p X i :=
  Abelianization.commutator_subset_ker _

/-- The generator `x_j` lies in the kernel of the `i`-th exponent sum exactly when `j ≠ i`. Not a
`simp` lemma: `simp` rewrites the left-hand side with `TauCeti.freeProP.mem_exponentSumKer_iff`
first (and, given `DecidableEq X`, evaluates the resulting exponent sum itself). -/
theorem of_mem_exponentSumKer_iff {i j : X} : of j ∈ exponentSumKer p X i ↔ j ≠ i := by
  classical
  rw [mem_exponentSumKer_iff, exponentSum_of, toAdd_ofAdd, Pi.single_apply]
  split_ifs with h
  · simp [h]
  · simp [Ne.symm h]

theorem of_mem_exponentSumKer {i j : X} (h : j ≠ i) : of j ∈ exponentSumKer p X i :=
  of_mem_exponentSumKer_iff.2 h

theorem of_notMem_exponentSumKer (i : X) : of i ∉ exponentSumKer p X i := fun h ↦
  of_mem_exponentSumKer_iff.1 h rfl

omit [Fact p.Prime] in
/-- The generator `x_i` together with the other generators `x_j`, `j ≠ i`, topologically generates
`F`: this is the generating family of `TauCeti.freeProP.topologicalClosure_closure_range_of_eq_top`
split at `i`. -/
theorem topologicalClosure_closure_insert_of_image_eq_top (i : X) :
    (Subgroup.closure (insert (of i) (of '' {j : X | j ≠ i}))).topologicalClosure =
      (⊤ : Subgroup (freeProP p X)) := by
  rw [← topologicalClosure_closure_range_of_eq_top p X]
  congr 2
  ext y
  simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_image, Set.mem_ofPred_eq]
  constructor
  · rintro (rfl | ⟨j, -, rfl⟩)
    · exact ⟨i, rfl⟩
    · exact ⟨j, rfl⟩
  · rintro ⟨j, rfl⟩
    by_cases h : j = i
    · exact Or.inl (by rw [h])
    · exact Or.inr ⟨j, h, rfl⟩

/-- **The kernel of the `i`-th exponent sum is the closed normal closure of the other
generators.** -/
theorem exponentSumKer_eq_topologicalClosure_normalClosure (i : X) :
    exponentSumKer p X i =
      (Subgroup.normalClosure (of '' {j : X | j ≠ i})).topologicalClosure := by
  classical
  refine (isProP_freeProP p X).ker_eq_topologicalClosure_normalClosure_of_not_isOfFinOrder _
    (isClosed_exponentSumKer i) (topologicalClosure_closure_insert_of_image_eq_top i) ?_ ?_
  · rintro _ ⟨j, hj, rfl⟩
    exact MonoidHom.mem_ker.1 (of_mem_exponentSumKer hj)
  · intro h
    obtain ⟨n, hn, hpow⟩ := isOfFinOrder_iff_pow_eq_one.1 h
    rw [← map_pow, MonoidHom.comp_apply, AddMonoidHom.coe_toMultiplicative,
      Function.comp_apply, Function.comp_apply, ofAdd_eq_one, Pi.evalAddMonoidHom_apply,
      ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass, map_pow, exponentSum_of,
      toAdd_pow, toAdd_ofAdd, Pi.smul_apply, Pi.single_eq_same, nsmul_eq_mul, mul_one] at hpow
    exact hn.ne' (Nat.cast_eq_zero.1 hpow)

/-- **A continuous homomorphism trivial on the generators `x_j`, `j ≠ i`, is trivial on the kernel
of the `i`-th exponent sum**, for a `T1` target: its kernel is a closed normal subgroup containing
those generators, and `X` is their closed normal closure. -/
theorem _root_.ContinuousMonoidHom.exponentSumKer_le_ker {H : Type*} [Group H]
    [TopologicalSpace H] [T1Space H] (φ : freeProP p X →ₜ* H) {i : X}
    (h : ∀ j, j ≠ i → φ (of j) = 1) : exponentSumKer p X i ≤ φ.ker := by
  rw [exponentSumKer_eq_topologicalClosure_normalClosure]
  exact topologicalClosure_normalClosure_le_ker (by rintro _ ⟨j, hj, rfl⟩; exact h j hj)

/-! ### Endomorphisms preserving the kernel of an exponent sum -/

/-- **An endomorphism moving each generator inside `X` preserves the `i`-th exponent sum**, for
`X` the kernel of that exponent sum: the exponent vector is linear,
`exponentSum (φ y) = ∑ x, (exponentSum y)_x • exponentSum (φ x_x)`
(`TauCeti.freeProP.toAdd_exponentSum_apply_eq_sum_smul`), and the `i`-th coordinate of each
column `exponentSum (φ x_x)` is `δ_{xi}`, so the `i`-th coordinate of `exponentSum (φ y)` is
`(exponentSum y)_i`. -/
theorem _root_.ContinuousMonoidHom.toAdd_exponentSum_apply_apply_eq_of_forall_inv_mul_apply_mem
    [Finite X]
    (φ : freeProP p X →ₜ* freeProP p X) {i : X}
    (hφ : ∀ j, (of j)⁻¹ * φ (of j) ∈ exponentSumKer p X i) (y : freeProP p X) :
    (exponentSum p X (φ y)).toAdd i = (exponentSum p X y).toAdd i := by
  classical
  cases nonempty_fintype X
  have h : ∀ x, (exponentSum p X (φ (of x))).toAdd i = if i = x then 1 else 0 := fun x ↦ by
    rw [← mul_inv_cancel_left (of x) (φ (of x)), map_mul, toAdd_mul, Pi.add_apply,
      mem_exponentSumKer_iff.1 (hφ x), add_zero, exponentSum_of, toAdd_ofAdd, Pi.single_apply]
  rw [toAdd_exponentSum_apply_eq_sum_smul, Finset.sum_apply]
  simp only [Pi.smul_apply, h, smul_eq_mul, mul_ite, mul_one, mul_zero, Finset.sum_ite_eq,
    Finset.mem_univ, ite_true]

/-- **An endomorphism moving each generator inside `X` preserves `X`**, for `X` the kernel of an
exponent sum. -/
theorem _root_.ContinuousMonoidHom.apply_mem_exponentSumKer_iff_of_forall_inv_mul_apply_mem
    [Finite X]
    (φ : freeProP p X →ₜ* freeProP p X) {i : X}
    (hφ : ∀ j, (of j)⁻¹ * φ (of j) ∈ exponentSumKer p X i) (y : freeProP p X) :
    φ y ∈ exponentSumKer p X i ↔ y ∈ exponentSumKer p X i := by
  rw [mem_exponentSumKer_iff, mem_exponentSumKer_iff,
    φ.toAdd_exponentSum_apply_apply_eq_of_forall_inv_mul_apply_mem hφ]

/-- **The kernel of a character trivial on all generators but one is the kernel of the exponent
sum at that generator**, when the value at that generator has infinite order: both are the closed
normal closure of the other generators
(`TauCeti.freeProP.exponentSumKer_eq_topologicalClosure_normalClosure` and
`TauCeti.IsProP.ker_eq_topologicalClosure_normalClosure_of_not_isOfFinOrder`). -/
theorem _root_.ContinuousMonoidHom.exponentSumKer_eq_ker {H : Type*} [Group H]
    [TopologicalSpace H] [T1Space H] (φ : freeProP p X →ₜ* H) {i : X}
    (h : ∀ j, j ≠ i → φ (of j) = 1) (hi : ¬ IsOfFinOrder (φ (of i))) :
    exponentSumKer p X i = φ.toMonoidHom.ker := by
  rw [exponentSumKer_eq_topologicalClosure_normalClosure]
  exact ((isProP_freeProP p X).ker_eq_topologicalClosure_normalClosure_of_not_isOfFinOrder
    φ.toMonoidHom φ.isClosed_ker (topologicalClosure_closure_insert_of_image_eq_top i)
    (by rintro _ ⟨j, hj, rfl⟩; exact h j hj) hi).symm

/-- **A dyadic character whose values at the generators `x_j`, `j ≠ i`, square to `1` is trivial
on `X_i ∩ λ_1(F)`**: on `X_i` its values square to `1`, since `X_i` is the closed normal closure of
those generators, and on `λ_1(F)` they lie in `1 + 4ℤ_2`, which contains no element of order two.
This is how the kernel of the orientation `χ(x₂) = -1`, `χ(x₄) = (1 - 2^f)⁻¹`, `χ(x_i) = 1`
otherwise, of the dyadic even-rank normal form `x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯` meets the lower
`2`-series: `ker χ ∩ λ_1(F) = X_{x₄} ∩ λ_1(F)`. -/
theorem _root_.ContinuousMonoidHom.apply_eq_one_of_mem_exponentSumKer_of_mem_pLowerCentralSeries_one
    (χ : freeProP 2 X →ₜ* ℤ_[2]ˣ) {i : X} (h : ∀ j, j ≠ i → χ (of j) ^ 2 = 1) {w : freeProP 2 X}
    (hw : w ∈ exponentSumKer 2 X i) (hw₁ : w ∈ pLowerCentralSeries 2 (freeProP 2 X) 1) :
    χ w = 1 := by
  have hsq : (χ ^ 2) w = 1 := MonoidHom.mem_ker.1 ((χ ^ 2).exponentSumKer_le_ker (i := i)
    (fun j hj ↦ by rw [ContinuousMonoidHom.pow_apply]; exact h j hj) hw)
  rw [ContinuousMonoidHom.pow_apply] at hsq
  have hU : χ w ∈ unitsPrincipal 2 2 :=
    mem_unitsPrincipal_of_mem_pLowerCentralSeries
      ((isProP_freeProP 2 X).mem_unitsPrincipal_one χ) hw₁
  have hval : (χ w : ℤ_[2]) * χ w = 1 := by
    rw [← sq, ← Units.val_pow_eq_pow_val, hsq, Units.val_one]
  rcases mul_self_eq_one_iff.1 hval with h1 | h1
  · exact Units.val_eq_one.1 h1
  · have : χ w = -1 := Units.ext (by rw [h1, Units.val_neg, Units.val_one])
    rw [this, neg_one_mem_unitsPrincipal_two_iff] at hU
    omega

/-! ### The graded pieces of the kernel of an exponent sum -/

section GradedPieces

variable (i : X) {m : ℕ}

/-- **The graded pieces of the kernel of an exponent sum**: the class in `gr_m(F)` of `y ∈ λ_m(F)`
lies in `gr_m(X)`, for `X` the kernel of the `i`-th exponent sum, exactly when `p ^ (m + 1)` divides
the `i`-th exponent sum of `y`; the exponent sums of an element of `λ_m(F)` are always divisible by
`p ^ m`. -/
@[simp]
theorem gradedMk_mem_gradedPieceOf_exponentSumKer_iff (y : pLowerCentralSeries p (freeProP p X) m) :
    gradedMk p (freeProP p X) m y ∈ gradedPieceOf p (exponentSumKer p X i) m ↔
      (p : ℤ_[p]) ^ (m + 1) ∣ (exponentSum p X (y : freeProP p X)).toAdd i := by
  classical
  constructor
  · intro h
    obtain ⟨x, hxK, hxy⟩ := mem_gradedPieceOf_iff.1 h
    rw [gradedMk_eq_gradedMk_iff, QuotientGroup.eq] at hxy
    have hy : (y : freeProP p X) = x * ((x : freeProP p X)⁻¹ * y) := by group
    rw [hy, map_mul, toAdd_mul, Pi.add_apply, mem_exponentSumKer_iff.1 hxK, zero_add]
    exact dvd_exponentSum_of_mem_pLowerCentralSeries hxy i
  · rintro ⟨a, ha⟩
    -- `z = (x_i ^ a) ^ (p ^ (m + 1))` lies in `λ_{m+1}(F)` and has `i`-th exponent sum
    -- `p ^ (m + 1) * a`, so `y * z⁻¹` lies in the kernel and has the class of `y`.
    set z : freeProP p X := (isProP_freeProP p X).padicPow (of i) a ^ p ^ (m + 1) with hz
    have hzmem : z ∈ pLowerCentralSeries p (freeProP p X) (m + 1) := by
      simpa using pow_pow_mem_pLowerCentralSeries (mem_pLowerCentralSeries_zero p
        ((isProP_freeProP p X).padicPow (of i) a)) (m + 1)
    have hzmem' : z ∈ pLowerCentralSeries p (freeProP p X) m :=
      pLowerCentralSeries_antitone (Nat.le_succ m) hzmem
    have hzsum : (exponentSum p X z).toAdd i = (p : ℤ_[p]) ^ (m + 1) * a := by
      rw [hz, map_pow, exponentSum_padicPow_of, toAdd_pow, toAdd_ofAdd, Pi.smul_apply,
        Pi.single_eq_same, nsmul_eq_mul, Nat.cast_pow]
    refine mem_gradedPieceOf_iff.2 ⟨y * ⟨z, hzmem'⟩⁻¹, ?_, ?_⟩
    · rw [mem_exponentSumKer_iff, coe_mul, coe_inv, Subgroup.coe_mk, map_mul, map_inv, toAdd_mul,
        toAdd_inv, Pi.add_apply, Pi.neg_apply, hzsum, ha, add_neg_cancel]
    · rw [gradedMk_mul, gradedMk_inv, (gradedMk_eq_zero_iff (x := ⟨z, hzmem'⟩)).2 hzmem, neg_zero,
        add_zero]

/-- **The `p`-power `π^m ξ_i` of the class of the generator `x_i` does not lie in `gr_m(X)`**, for
`X` the kernel of the `i`-th exponent sum: its `i`-th exponent sum is `p ^ m`. -/
theorem gradedPowIter_gradedMkZero_of_notMem_gradedPieceOf_exponentSumKer (m : ℕ) :
    gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i)) ∉
      gradedPieceOf p (exponentSumKer p X i) m := by
  classical
  rw [gradedPowIter_gradedMkZero, gradedMk_mem_gradedPieceOf_exponentSumKer_iff, Subgroup.coe_mk,
    toAdd_exponentSum_of_pow_apply, ite_eq_left rfl, Nat.cast_pow]
  rw [pow_dvd_pow_iff (Nat.cast_ne_zero.2 (Fact.out : p.Prime).ne_zero)
    PadicInt.irreducible_p.not_isUnit]
  omega

/-- **`gr_m(F)` is spanned by `gr_m(X)` and `π^m ξ_i`**, for `X` the kernel of the `i`-th exponent
sum: the class of `y ∈ λ_m(F)` with `i`-th exponent sum `p ^ m * a` differs from `ā • π^m ξ_i`,
where `ā ∈ 𝔽_p` is the residue of `a`, by a class in `gr_m(X)`. -/
theorem gradedPieceOf_exponentSumKer_sup_span_gradedPowIter_eq_top (m : ℕ) :
    gradedPieceOf p (exponentSumKer p X i) m ⊔
      span (ZMod p) {gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i))} =
      ⊤ := by
  classical
  rw [eq_top_iff]
  rintro z -
  obtain ⟨y, rfl⟩ := gradedMk_surjective m z
  obtain ⟨a, ha⟩ := dvd_exponentSum_of_mem_pLowerCentralSeries y.2 i
  set c : ZMod p := PadicInt.toZMod a with hc
  have hwmem : of i ^ p ^ m ∈ pLowerCentralSeries p (freeProP p X) m := by
    simpa using pow_pow_mem_pLowerCentralSeries (mem_pLowerCentralSeries_zero p (of i)) m
  set w : pLowerCentralSeries p (freeProP p X) m := ⟨of i ^ p ^ m, hwmem⟩ with hw
  have hwsum : (exponentSum p X (w : freeProP p X)).toAdd i = (p : ℤ_[p]) ^ m := by
    rw [hw, Subgroup.coe_mk, toAdd_exponentSum_of_pow_apply, ite_eq_left rfl, Nat.cast_pow]
  have hπ : gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i)) =
      gradedMk p (freeProP p X) m w := by
    rw [gradedPowIter_gradedMkZero]
  -- The scalar `c` acts as the `c.val`-th power on classes.
  have hsmul : c • gradedMk p (freeProP p X) m w = gradedMk p (freeProP p X) m (w ^ c.val) := by
    rw [gradedMk_pow, ← Nat.cast_smul_eq_nsmul (ZMod p), ZMod.natCast_zmod_val]
  -- `p` divides `a - c.val`.
  have hdvd : (p : ℤ_[p]) ∣ a - (c.val : ℤ_[p]) := by
    rw [← Ideal.mem_span_singleton, ← PadicInt.maximalIdeal_eq_span_p, ZMod.natCast_val, hc]
    exact PadicInt.toZMod_spec a
  have hmem : gradedMk p (freeProP p X) m (y * (w ^ c.val)⁻¹) ∈
      gradedPieceOf p (exponentSumKer p X i) m := by
    rw [gradedMk_mem_gradedPieceOf_exponentSumKer_iff, coe_mul, coe_inv, coe_pow, map_mul, map_inv,
      map_pow, toAdd_mul, toAdd_inv, toAdd_pow, Pi.add_apply, Pi.neg_apply, Pi.smul_apply, ha,
      hwsum, nsmul_eq_mul, pow_succ, ← sub_eq_add_neg,
      (by ring : (p : ℤ_[p]) ^ m * a - (c.val : ℤ_[p]) * (p : ℤ_[p]) ^ m =
        (p : ℤ_[p]) ^ m * (a - c.val))]
    exact mul_dvd_mul_left _ hdvd
  rw [gradedMk_mul, gradedMk_inv] at hmem
  have : gradedMk p (freeProP p X) m y =
      (gradedMk p (freeProP p X) m y + -gradedMk p (freeProP p X) m (w ^ c.val)) +
        c • gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i)) := by
    rw [hπ, hsmul, neg_add_cancel_right]
  rw [this]
  exact add_mem (mem_sup_left hmem) (mem_sup_right (smul_mem _ _ (subset_span rfl)))

/-- **`gr_m(F) = gr_m(X) ⊕ 𝔽_p π^m ξ_i`**, for `X` the kernel of the `i`-th exponent sum
(Labute, §4, Lemma 1). -/
theorem isCompl_gradedPieceOf_exponentSumKer_span_gradedPowIter (m : ℕ) :
    IsCompl (gradedPieceOf p (exponentSumKer p X i) m)
      (span (ZMod p)
        {gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i))}) :=
  ⟨(disjoint_span_singleton' ((linearIndependent_gradedPowIter_gradedMkZero_of p X m).ne_zero i)).2
      (gradedPowIter_gradedMkZero_of_notMem_gradedPieceOf_exponentSumKer i m),
    codisjoint_iff.2 (gradedPieceOf_exponentSumKer_sup_span_gradedPowIter_eq_top i m)⟩

/-- Every class in `gr_m(F)` is a class in `gr_m(X)` plus a multiple of `π^m ξ_i`. -/
theorem exists_mem_gradedPieceOf_exponentSumKer_add_smul_gradedPowIter_eq (m : ℕ)
    (z : gradedPiece p (freeProP p X) m) :
    ∃ h ∈ gradedPieceOf p (exponentSumKer p X i) m, ∃ c : ZMod p,
      h + c • gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i)) = z := by
  have hz : z ∈ gradedPieceOf p (exponentSumKer p X i) m ⊔
      span (ZMod p) {gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i))} := by
    rw [gradedPieceOf_exponentSumKer_sup_span_gradedPowIter_eq_top]
    exact mem_top
  obtain ⟨h, hh, t, ht, rfl⟩ := mem_sup.1 hz
  obtain ⟨c, rfl⟩ := mem_span_singleton.1 ht
  exact ⟨h, hh, c, rfl⟩

/-- **A subspace of `gr_m(X)` which together with `π^m ξ_i` spans `gr_m(X)` is all of `gr_m(X)`.**
-/
theorem gradedPieceOf_exponentSumKer_le_of_le_sup_span_gradedPowIter (m : ℕ)
    {W : Submodule (ZMod p) (gradedPiece p (freeProP p X) m)}
    (hW : W ≤ gradedPieceOf p (exponentSumKer p X i) m)
    (h : gradedPieceOf p (exponentSumKer p X i) m ≤ W ⊔
      span (ZMod p) {gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i))}) :
    gradedPieceOf p (exponentSumKer p X i) m ≤ W := by
  -- By the modular law, `gr_m(X) = (W ⊔ 𝔽_p π^m ξ_i) ⊓ gr_m(X) = W ⊔ (𝔽_p π^m ξ_i ⊓ gr_m(X)) = W`.
  refine le_of_eq ?_
  set L := span (ZMod p) {gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i))}
  calc gradedPieceOf p (exponentSumKer p X i) m
      = (W ⊔ L) ⊓ gradedPieceOf p (exponentSumKer p X i) m := (inf_eq_right.2 h).symm
    _ = W ⊔ L ⊓ gradedPieceOf p (exponentSumKer p X i) m := sup_inf_assoc_of_le _ hW
    _ = W := by
        rw [(isCompl_gradedPieceOf_exponentSumKer_span_gradedPowIter i m).disjoint.symm.eq_bot,
          sup_bot_eq]

/-- The tail `T_j` spanned by the `π^j ξ_a` with `a ≠ i` lies in `gr_j(X)`, for `X` the kernel of
the `i`-th exponent sum. -/
theorem span_range_gradedPowIter_le_gradedPieceOf_exponentSumKer (j : ℕ) :
    span (ZMod p) (Set.range fun a : {a : X // a ≠ i} ↦
        gradedPowIter p (freeProP p X) j (gradedMkZero p (freeProP p X) (of a))) ≤
      gradedPieceOf p (exponentSumKer p X i) j := by
  rw [span_le]
  rintro _ ⟨a, rfl⟩
  exact gradedPowIter_gradedMkZero_mem_gradedPieceOf (of_mem_exponentSumKer a.2) j

end GradedPieces

/-! ### Generation of the graded pieces of the kernel -/

section Generation

variable [Finite X] (i : X) {m : ℕ}

/-- **Generation of `gr_{m+1}(X)` from `gr_m(X)`** (Labute, §4, Lemma 2): for `m ≥ 1`, a subspace
of `gr_{m+1}(F)` containing the `p`-powers `π τ` and the brackets `[τ, ξ_j]` with the generator
classes, for every `τ ∈ gr_m(X)`, contains `gr_{m+1}(X)`; here `X` is the kernel of the `i`-th
exponent sum. The proof writes a class of `gr_m(F)` as `h + c • π^m ξ_i` with `h ∈ gr_m(X)`, so that
`π` and the brackets carry `gr_m(F)` into the subspace enlarged by `𝔽_p π^{m+1} ξ_i`, which is then
all of `gr_{m+1}(F)`, and the component along `π^{m+1} ξ_i` of a class of `gr_{m+1}(X)` vanishes. -/
theorem gradedPieceOf_exponentSumKer_succ_le (hm : 1 ≤ m)
    {W : Submodule (ZMod p) (gradedPiece p (freeProP p X) (m + 1))}
    (hpow : ∀ τ ∈ gradedPieceOf p (exponentSumKer p X i) m, gradedPow p (freeProP p X) m τ ∈ W)
    (hbr : ∀ τ ∈ gradedPieceOf p (exponentSumKer p X i) m, ∀ j : X,
      gradedBracket p (freeProP p X) m 0 τ (gradedMkZero p (freeProP p X) (of j)) ∈ W) :
    gradedPieceOf p (exponentSumKer p X i) (m + 1) ≤ W := by
  have hK : commutator (freeProP p X) ≤ exponentSumKer p X i := commutator_le_exponentSumKer i
  -- Work with `W' = W ⊓ gr_{m+1}(X)`, which satisfies the same hypotheses.
  set W' := W ⊓ gradedPieceOf p (exponentSumKer p X i) (m + 1) with hW'
  have hpow' : ∀ τ ∈ gradedPieceOf p (exponentSumKer p X i) m,
      gradedPow p (freeProP p X) m τ ∈ W' :=
    fun τ hτ ↦ ⟨hpow τ hτ, gradedPow_mem_gradedPieceOf hτ⟩
  -- Brackets with arbitrary degree-zero classes, by bilinearity from the generator classes.
  have hbr' : ∀ τ ∈ gradedPieceOf p (exponentSumKer p X i) m,
      ∀ y : gradedPiece p (freeProP p X) 0, gradedBracket p (freeProP p X) m 0 τ y ∈ W' := by
    intro τ hτ y
    have hy : y ∈ span (ZMod p) (gradedMkZero p (freeProP p X) '' Set.range of) := by
      rw [span_gradedMkZero_image_range_of_eq_top]
      exact mem_top
    refine span_induction (p := fun y _ ↦ gradedBracket p (freeProP p X) m 0 τ y ∈ W') ?_ ?_ ?_ ?_
      hy
    · rintro _ ⟨_, ⟨j, rfl⟩, rfl⟩
      exact ⟨hbr τ hτ j, gradedBracket_mem_gradedPieceOf_left (k := 0) hτ _⟩
    · rw [← gradedBracketLinear_apply, map_zero]
      exact zero_mem _
    · intro a b _ _ ha hb
      have h := add_mem ha hb
      rwa [← gradedBracketLinear_apply, ← gradedBracketLinear_apply, ← map_add,
        gradedBracketLinear_apply] at h
    · intro c a _ ha
      have h := smul_mem _ c ha
      rwa [← gradedBracketLinear_apply, ← map_smul, gradedBracketLinear_apply] at h
  -- The brackets `[π^m ξ_i, y]` lie in `W'`: for `m ≥ 2` they are `π [π^{m-1} ξ_i, y]`, and for
  -- `m = 1` they are `π [ξ_i, y] - (p choose 2) • [[ξ_i, y], ξ_i]`.
  have hline : ∀ y : gradedPiece p (freeProP p X) 0,
      gradedBracket p (freeProP p X) m 0
        (gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i))) y ∈ W' := by
    intro y
    obtain ⟨k, rfl⟩ : ∃ k, m = k + 1 := ⟨m - 1, by omega⟩
    rw [gradedPowIter_succ]
    rcases Nat.eq_zero_or_pos k with rfl | hk
    · rw [gradedPowIter_zero]
      have h := gradedPow_gradedBracket_zero_zero (gradedMkZero p (freeProP p X) (of i)) y
      rw [← sub_eq_iff_eq_add] at h
      rw [← h]
      exact sub_mem
        (hpow' _ (gradedBracket_mem_gradedPieceOf_of_commutator_le hK (j := 0) (k := 0) _ _))
        (nsmul_mem
          (hbr' _ (gradedBracket_mem_gradedPieceOf_of_commutator_le hK (j := 0) (k := 0) _ _) _) _)
    · rw [← gradedPow_gradedBracket_left_zero hk]
      exact hpow' _ (gradedBracket_mem_gradedPieceOf_of_commutator_le hK (j := k) (k := 0) _ _)
  -- `π` is linear in degree `m ≥ 1`.
  have hπsmul (c : ZMod p) (v : gradedPiece p (freeProP p X) m) :
      gradedPow p (freeProP p X) m (c • v) = c • gradedPow p (freeProP p X) m v := by
    have h := map_smul ((gradedPowAddMonoidHom p (freeProP p X) hm).toZModLinearMap p) c v
    simpa only [AddMonoidHom.coe_toZModLinearMap, gradedPowAddMonoidHom_apply] using h
  -- `W' ⊔ 𝔽_p π^{m+1} ξ_i` is all of `gr_{m+1}(F)`.
  have htop : W' ⊔ span (ZMod p)
      {gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of i))} = ⊤ := by
    refine eq_top_of_forall_gradedPow_mem_of_forall_gradedBracket_mem
      ((isTopologicallyFinitelyGenerated_freeProP p X).isOpen_pLowerCentralSeries Fact.out
        (m + 1 + 1)) (fun τ ↦ ?_) fun τ y ↦ ?_
    · obtain ⟨h, hh, c, rfl⟩ :=
        exists_mem_gradedPieceOf_exponentSumKer_add_smul_gradedPowIter_eq i m τ
      rw [gradedPow_add_of_one_le hm, hπsmul, ← gradedPowIter_succ]
      exact add_mem (mem_sup_left (hpow' h hh)) (mem_sup_right (smul_mem _ _ (subset_span rfl)))
    · obtain ⟨h, hh, c, rfl⟩ :=
        exists_mem_gradedPieceOf_exponentSumKer_add_smul_gradedPowIter_eq i m τ
      rw [← gradedBracketLinear_apply, map_add, map_smul, LinearMap.add_apply,
        LinearMap.smul_apply, gradedBracketLinear_apply, gradedBracketLinear_apply]
      exact mem_sup_left (add_mem (hbr' h hh y) (smul_mem _ _ (hline y)))
  exact (gradedPieceOf_exponentSumKer_le_of_le_sup_span_gradedPowIter i (m + 1) inf_le_right
    (htop ▸ le_top)).trans inf_le_left

end Generation

/-! ### The constrained span statement -/

section ConstrainedSpan

variable [LinearOrder X] {m : ℕ} {ρ : gradedPiece p (freeProP p X) 1} {i₀ i₁ : X}

section

variable [Finite X]

/-- The image of `δ_ρ` on families of classes of `gr_m(X)` lies in `gr_{m+1}(X)`, for `X` the kernel
of the `i₁`-th exponent sum. -/
theorem map_basisModificationDelta_pi_gradedPieceOf_exponentSumKer_le (hm : 1 ≤ m)
    (ρ : gradedPiece p (freeProP p X) 1) (i₁ : X) :
    (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
        (basisModificationDelta p X hm ρ) ≤
      gradedPieceOf p (exponentSumKer p X i₁) (m + 1) := by
  cases nonempty_fintype X
  rintro _ ⟨v, hv, rfl⟩
  rw [basisModificationDelta_eq_gradedPow_add_sum]
  exact add_mem (gradedPow_mem_gradedPieceOf (sum_mem fun k _ ↦
      smul_mem _ _ (Submodule.mem_pi.1 hv k (Set.mem_univ k))))
    (sum_mem fun k _ ↦ gradedBracket_mem_gradedPieceOf_left (k := 0) (Submodule.mem_pi.1 hv k
      (Set.mem_univ k)) _)

/-- For `τ ∈ gr_m(X)` and any `y ∈ gr_0(F)`, the bracket `[τ, y]` is `δ_ρ` of a family of classes
of `gr_m(X)` up to a multiple of `π τ`, when the derivatives of `ρ` span `gr_0(F)`. -/
private theorem gradedBracket_mem_map_basisModificationDelta_pi_sup_span_gradedPow (hm : 1 ≤ m)
    (hρ : span (ZMod p) (Set.range fun j ↦ degreeOneDeriv p X j ρ) = ⊤)
    {τ : gradedPiece p (freeProP p X) m} (hτ : τ ∈ gradedPieceOf p (exponentSumKer p X i₁) m)
    (y : gradedPiece p (freeProP p X) 0) :
    gradedBracket p (freeProP p X) m 0 τ y ∈
      (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
        (basisModificationDelta p X hm ρ) ⊔ span (ZMod p) {gradedPow p (freeProP p X) m τ} := by
  obtain ⟨b, c, hbc⟩ := exists_basisModificationDelta_smul_eq hm hρ τ y
  rw [← add_sub_cancel_left (c • gradedPow p (freeProP p X) m τ)
    (gradedBracket p (freeProP p X) m 0 τ y), ← hbc]
  exact sub_mem (mem_sup_left ⟨_, Submodule.mem_pi.2 fun k _ ↦ smul_mem _ _ hτ, rfl⟩)
    (mem_sup_right (smul_mem _ _ (subset_span rfl)))

end

variable [Fintype X]

/-- For `τ ∈ gr_m(X)` and `a ≠ i₁, i₂`, the bracket `[τ, ξ_a]` is `δ_ρ` of a family of classes of
`gr_m(X)`, when `ξ_a` is a combination of the derivatives `∂_k ρ` with `k ≠ i₀` and `x_{i₀}` is the
only generator with a `p`-power coefficient in `ρ`. -/
private theorem gradedBracket_gradedMkZero_mem_map_basisModificationDelta_pi (hm : 1 ≤ m)
    (hc : ∀ j, j ≠ i₀ → (degreeOneBasis p X).repr ρ (Sum.inl j) = 0)
    (hd : ∀ j, j ≠ i₁ → j ≠ i₂ → ∃ b : X → ZMod p, b i₀ = 0 ∧
      ∑ k, b k • degreeOneDeriv p X k ρ = gradedMkZero p (freeProP p X) (of j))
    {τ : gradedPiece p (freeProP p X) m} (hτ : τ ∈ gradedPieceOf p (exponentSumKer p X i₁) m)
    {a : X} (ha : a ≠ i₁) (ha₂ : a ≠ i₂) :
    gradedBracket p (freeProP p X) m 0 τ (gradedMkZero p (freeProP p X) (of a)) ∈
      (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
        (basisModificationDelta p X hm ρ) := by
  obtain ⟨b, hb₀, hb⟩ := hd a ha ha₂
  refine ⟨fun k ↦ b k • τ, Submodule.mem_pi.2 fun k _ ↦ smul_mem _ _ hτ, ?_⟩
  rw [basisModificationDelta_smul_eq_gradedBracket_of_eq_zero hm hc hb₀, hb]

/-- The degree-one case of the `p`-power step of the constrained span statement: for
`τ ∈ gr_1(X)`, `π τ` lies in `δ_ρ(gr_1(X)^X) + T_2 + 𝔽_p π [ξ_{i₂}, ξ_{i₁}]`. -/
private theorem gradedPow_mem_map_basisModificationDelta_pi_sup_span_gradedPowIter_one
    (hρ : span (ZMod p) (Set.range fun j ↦ degreeOneDeriv p X j ρ) = ⊤)
    (hc : ∀ j, j ≠ i₀ → (degreeOneBasis p X).repr ρ (Sum.inl j) = 0)
    (hd : ∀ j, j ≠ i₁ → j ≠ i₂ → ∃ b : X → ZMod p, b i₀ = 0 ∧
      ∑ k, b k • degreeOneDeriv p X k ρ = gradedMkZero p (freeProP p X) (of j))
    {τ : gradedPiece p (freeProP p X) 1} (hτ : τ ∈ gradedPieceOf p (exponentSumKer p X i₁) 1) :
    gradedPow p (freeProP p X) 1 τ ∈
      (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) 1).map
        (basisModificationDelta p X le_rfl ρ) ⊔
      span (ZMod p) (Set.range fun a : {a : X // a ≠ i₁} ↦
        gradedPowIter p (freeProP p X) (1 + 1) (gradedMkZero p (freeProP p X) (of a))) ⊔
      span (ZMod p) {gradedPowIterBracket p (freeProP p X) 1 (of i₂) (of i₁)} := by
  have hK : commutator (freeProP p X) ≤ exponentSumKer p X i₁ := commutator_le_exponentSumKer i₁
  set H := (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) 1).map
    (basisModificationDelta p X le_rfl ρ) ⊔
      span (ZMod p) (Set.range fun a : {a : X // a ≠ i₁} ↦
        gradedPowIter p (freeProP p X) (1 + 1) (gradedMkZero p (freeProP p X) (of a))) ⊔
      span (ZMod p) {gradedPowIterBracket p (freeProP p X) 1 (of i₂) (of i₁)} with hH
  -- The `p`-power classes `π ξ_a` with `a ≠ i₁` lie in `gr_1(X)`, and their `p`-powers `π² ξ_a`
  -- in the tail.
  have hξ (a : X) (ha : a ≠ i₁) :
      gradedPow p (freeProP p X) 0 (gradedMkZero p (freeProP p X) (of a)) ∈
        gradedPieceOf p (exponentSumKer p X i₁) 1 := by
    have h := gradedPowIter_gradedMkZero_mem_gradedPieceOf (p := p)
      (of_mem_exponentSumKer (p := p) ha) 1
    rwa [gradedPowIter_succ, gradedPowIter_zero] at h
  have hξ₂ (a : X) (ha : a ≠ i₁) :
      gradedPow p (freeProP p X) 1 (gradedPow p (freeProP p X) 0
        (gradedMkZero p (freeProP p X) (of a))) ∈ H :=
    mem_sup_left (mem_sup_right (subset_span ⟨⟨a, ha⟩, by
      dsimp only
      rw [gradedPowIter_succ, gradedPowIter_succ, gradedPowIter_zero]⟩))
  -- The exceptional class `π [ξ_{i₂}, ξ_{i₁}]` is the last spanning vector.
  have hB : gradedPow p (freeProP p X) 1 (gradedBracket p (freeProP p X) 0 0
      (gradedMkZero p (freeProP p X) (of i₂)) (gradedMkZero p (freeProP p X) (of i₁))) ∈ H := by
    rw [← gradedPowIterBracket_zero, gradedPow_gradedPowIterBracket]
    exact mem_sup_right (subset_span rfl)
  -- `π [ξ_a, ξ_b] = -π [ξ_b, ξ_a]`.
  have hswap (a b : X) :
      gradedPow p (freeProP p X) 1 (gradedBracket p (freeProP p X) 0 0
        (gradedMkZero p (freeProP p X) (of a)) (gradedMkZero p (freeProP p X) (of b))) =
      -gradedPow p (freeProP p X) 1 (gradedBracket p (freeProP p X) 0 0
        (gradedMkZero p (freeProP p X) (of b)) (gradedMkZero p (freeProP p X) (of a))) := by
    have h := gradedCast_gradedBracket_swap (gradedMkZero p (freeProP p X) (of b))
      (gradedMkZero p (freeProP p X) (of a))
    rw [gradedCast_rfl] at h
    rw [h, gradedPow_neg]
  -- `π [ξ_a, ξ_b] = [π ξ_a, ξ_b] + (p choose 2) • [[ξ_a, ξ_b], ξ_a]` lies in `H` for `a ≠ i₁, i₂`.
  have hgen (a : X) (ha : a ≠ i₁) (ha₂ : a ≠ i₂) (b : X) :
      gradedPow p (freeProP p X) 1 (gradedBracket p (freeProP p X) 0 0
        (gradedMkZero p (freeProP p X) (of a)) (gradedMkZero p (freeProP p X) (of b))) ∈ H := by
    rw [gradedPow_gradedBracket_zero_zero]
    refine add_mem ?_ (nsmul_mem (mem_sup_left (mem_sup_left
      (gradedBracket_gradedMkZero_mem_map_basisModificationDelta_pi le_rfl hc hd
        (gradedBracket_mem_gradedPieceOf_of_commutator_le hK (j := 0) (k := 0) _ _) ha ha₂))) _)
    exact sup_le (le_sup_left.trans le_sup_left)
      (span_le.2 (Set.singleton_subset_iff.2 (hξ₂ a ha)))
      (gradedBracket_mem_map_basisModificationDelta_pi_sup_span_gradedPow le_rfl hρ (hξ a ha) _)
  -- The preimage of `H` under `π`, inside `gr_1(X)`, contains every basis vector of `gr_1(F)`
  -- other than `π ξ_{i₁}`, so it is all of `gr_1(X)`.
  set L₁ : gradedPiece p (freeProP p X) 1 →ₗ[ZMod p] gradedPiece p (freeProP p X) 2 :=
    (gradedPowAddMonoidHom p (freeProP p X) le_rfl).toZModLinearMap p with hL₁
  have hL₁' (v : gradedPiece p (freeProP p X) 1) : L₁ v = gradedPow p (freeProP p X) 1 v := by
    rw [hL₁, AddMonoidHom.coe_toZModLinearMap, gradedPowAddMonoidHom_apply]
  suffices hW : gradedPieceOf p (exponentSumKer p X i₁) 1 ≤
      H.comap L₁ ⊓ gradedPieceOf p (exponentSumKer p X i₁) 1 by
    have h := (Submodule.mem_inf.1 (hW hτ)).1
    rwa [Submodule.mem_comap, hL₁'] at h
  refine gradedPieceOf_exponentSumKer_le_of_le_sup_span_gradedPowIter i₁ 1 inf_le_right
    (le_top.trans ?_)
  rw [← span_range_degreeOneFamily_of_eq_top p X, span_le]
  rintro _ ⟨k, rfl⟩
  rcases k with a | ⟨⟨a, b⟩, hab⟩
  · rw [degreeOneFamily_inl]
    by_cases ha : a = i₁
    · subst ha
      exact mem_sup_right (subset_span (Set.mem_singleton_iff.2
        (by rw [gradedPowIter_succ, gradedPowIter_zero])))
    · refine mem_sup_left (Submodule.mem_inf.2 ⟨?_, hξ a ha⟩)
      rw [Submodule.mem_comap, hL₁']
      exact hξ₂ a ha
  · rw [degreeOneFamily_inr]
    dsimp only at hab ⊢
    refine mem_sup_left (Submodule.mem_inf.2
      ⟨?_, gradedBracket_mem_gradedPieceOf_of_commutator_le hK (j := 0) (k := 0) _ _⟩)
    rw [Submodule.mem_comap, hL₁']
    by_cases ha : a = i₁
    · -- `[ξ_{i₁}, ξ_b] = -[ξ_b, ξ_{i₁}]` with `b ≠ i₁`.
      subst ha
      have hb : b ≠ a := hab.ne'
      by_cases hb₂ : b = i₂
      · subst hb₂
        rw [hswap]
        exact neg_mem hB
      · rw [hswap]
        exact neg_mem (hgen b hb hb₂ a)
    · by_cases ha₂ : a = i₂
      · -- `[ξ_{i₂}, ξ_b]`: the exceptional class when `b = i₁`, otherwise `-[ξ_b, ξ_{i₂}]`.
        subst ha₂
        by_cases hb : b = i₁
        · subst hb
          exact hB
        · rw [hswap]
          exact neg_mem (hgen b hb hab.ne' a)
      · exact hgen a ha ha₂ b

/-- **The constrained span statement with an exceptional generator** (Labute, §4, Lemma 3 in both
its forms). Let `F` be the free pro-`p` group on a finite linearly ordered type `X`, let
`ρ ∈ gr_1(F)` have partial derivatives spanning `gr_0(F)`, let `x_{i₀}` be the only generator
whose coefficient of `π ξ_i` in `ρ` may be nonzero, and let every generator class `ξ_j` with
`j ≠ i₁, i₂` be a combination of the derivatives `∂_k ρ` with `k ≠ i₀`. Let `X = ker` be the
kernel of the `i₁`-th exponent sum. Then for every `m ≥ 1`

  `gr_{m+1}(X) = δ_ρ(gr_m(X)^X) + T_{m+1} + 𝔽_p π^m [ξ_{i₂}, ξ_{i₁}]`,

where the tail `T_{m+1}` is spanned by the `p`-powers `π^{m+1} ξ_a` with `a ≠ i₁`. The exceptional
generator `x_{i₂}`, whose class needs the derivative `∂_{i₀} ρ`, contributes the extra spanning
vector `π^m [ξ_{i₂}, ξ_{i₁}]`, which for `p = 2` need not lie in the other two terms; with
`i₂ = i₁` it vanishes and the statement is
`gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_span_gradedPowIter`. The two
even-rank dyadic Demushkin relators `x₁^{2+2^f} (x₁, x₂)(x₃, x₄) ⋯` and
`x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯` have `i₀ = x₁`, and respectively `i₂ = i₁ = x₂` and
`i₁ = x₄`, `i₂ = x₂`. -/
theorem gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket
    (hm : 1 ≤ m) (hρ : span (ZMod p) (Set.range fun j ↦ degreeOneDeriv p X j ρ) = ⊤)
    (hc : ∀ j, j ≠ i₀ → (degreeOneBasis p X).repr ρ (Sum.inl j) = 0)
    (hd : ∀ j, j ≠ i₁ → j ≠ i₂ → ∃ b : X → ZMod p, b i₀ = 0 ∧
      ∑ k, b k • degreeOneDeriv p X k ρ = gradedMkZero p (freeProP p X) (of j)) :
    gradedPieceOf p (exponentSumKer p X i₁) (m + 1) =
      (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
        (basisModificationDelta p X hm ρ) ⊔
      span (ZMod p) (Set.range fun a : {a : X // a ≠ i₁} ↦
        gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of a))) ⊔
      span (ZMod p) {gradedPowIterBracket p (freeProP p X) m (of i₂) (of i₁)} := by
  -- `π` is linear in degree `m ≥ 1`.
  have hπsmul (m : ℕ) (hm : 1 ≤ m) (c : ZMod p) (v : gradedPiece p (freeProP p X) m) :
      gradedPow p (freeProP p X) m (c • v) = c • gradedPow p (freeProP p X) m v := by
    have h := map_smul ((gradedPowAddMonoidHom p (freeProP p X) hm).toZModLinearMap p) c v
    simpa only [AddMonoidHom.coe_toZModLinearMap, gradedPowAddMonoidHom_apply] using h
  -- `π τ` lies in the sum for every `τ ∈ gr_m(X)`, by induction on `m`.
  have hpow : ∀ (m : ℕ) (hm : 1 ≤ m), ∀ τ ∈ gradedPieceOf p (exponentSumKer p X i₁) m,
      gradedPow p (freeProP p X) m τ ∈
        (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
          (basisModificationDelta p X hm ρ) ⊔
        span (ZMod p) (Set.range fun a : {a : X // a ≠ i₁} ↦
          gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of a))) ⊔
        span (ZMod p) {gradedPowIterBracket p (freeProP p X) m (of i₂) (of i₁)} := by
    intro m hm
    induction m, hm using Nat.le_induction with
    | base =>
      exact fun τ hτ ↦
        gradedPow_mem_map_basisModificationDelta_pi_sup_span_gradedPowIter_one hρ hc hd hτ
    | succ m hm ih =>
      -- `gr_{m+1}(X)` lies in the sum at level `m`, and `π` carries that sum to level `m + 1`.
      have hle : gradedPieceOf p (exponentSumKer p X i₁) (m + 1) ≤
          (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
            (basisModificationDelta p X hm ρ) ⊔
          span (ZMod p) (Set.range fun a : {a : X // a ≠ i₁} ↦
            gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of a))) ⊔
          span (ZMod p) {gradedPowIterBracket p (freeProP p X) m (of i₂) (of i₁)} :=
        gradedPieceOf_exponentSumKer_succ_le i₁ hm ih fun τ hτ j ↦
          sup_le (le_sup_left.trans le_sup_left)
            (span_le.2 (Set.singleton_subset_iff.2 (ih τ hτ)))
            (gradedBracket_mem_map_basisModificationDelta_pi_sup_span_gradedPow hm hρ hτ _)
      intro τ hτ
      obtain ⟨_, hx, _, hy, rfl⟩ := mem_sup.1 (hle hτ)
      obtain ⟨_, ⟨v, hv, rfl⟩, t, ht, rfl⟩ := mem_sup.1 hx
      obtain ⟨c, rfl⟩ := mem_span_singleton.1 hy
      rw [gradedPow_add_of_one_le (by omega), gradedPow_add_of_one_le (by omega),
        gradedPow_basisModificationDelta, hπsmul _ (by omega), gradedPow_gradedPowIterBracket]
      refine add_mem (mem_sup_left (add_mem (mem_sup_left ⟨_, Submodule.mem_pi.2 fun k _ ↦
          gradedPow_mem_gradedPieceOf (Submodule.mem_pi.1 hv k (Set.mem_univ k)), rfl⟩)
        (mem_sup_right (gradedPow_mem_span_range_gradedPowIter_succ _ (by omega) ht))))
        (mem_sup_right (smul_mem _ _ (subset_span rfl)))
  refine le_antisymm ?_ (sup_le (sup_le
    (map_basisModificationDelta_pi_gradedPieceOf_exponentSumKer_le hm ρ i₁)
    (span_range_gradedPowIter_le_gradedPieceOf_exponentSumKer i₁ (m + 1)))
    (span_le.2 (Set.singleton_subset_iff.2
      (gradedPowIterBracket_mem_gradedPieceOf (commutator_le_exponentSumKer i₁) m _ _))))
  exact gradedPieceOf_exponentSumKer_succ_le i₁ hm (hpow m hm) fun τ hτ j ↦
    sup_le (le_sup_left.trans le_sup_left)
      (span_le.2 (Set.singleton_subset_iff.2 (hpow m hm τ hτ)))
      (gradedBracket_mem_map_basisModificationDelta_pi_sup_span_gradedPow hm hρ hτ _)

/-- **The constrained span statement** (Labute, §4, Lemma 3). Let `F` be the free pro-`p` group on
a finite linearly ordered type `X`, let `ρ ∈ gr_1(F)` have partial derivatives spanning `gr_0(F)`,
let `x_{i₀}` be the only generator whose coefficient of `π ξ_i` in `ρ` may be nonzero, and let every
generator class `ξ_j` with `j ≠ i₁` be a combination of the derivatives `∂_k ρ` with `k ≠ i₀`. Let
`X = ker` be the kernel of the `i₁`-th exponent sum. Then for every `m ≥ 1`

  `gr_{m+1}(X) = δ_ρ(gr_m(X)^X) + T_{m+1}`,

where the tail `T_{m+1}` is spanned by the `p`-powers `π^{m+1} ξ_a` with `a ≠ i₁`. This is the
form of the span statement in which the basis corrections are constrained to lie in the kernel of
the orientation, as the uniqueness half of the dyadic even-rank classification requires; for the
relator `x₁^q (x₁, x₂)(x₃, x₄) ⋯` the generators are `i₀ = x₁` and `i₁ = x₂`. -/
theorem gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_span_gradedPowIter
    (hm : 1 ≤ m) (hρ : span (ZMod p) (Set.range fun j ↦ degreeOneDeriv p X j ρ) = ⊤)
    (hc : ∀ j, j ≠ i₀ → (degreeOneBasis p X).repr ρ (Sum.inl j) = 0)
    (hd : ∀ j, j ≠ i₁ → ∃ b : X → ZMod p, b i₀ = 0 ∧
      ∑ k, b k • degreeOneDeriv p X k ρ = gradedMkZero p (freeProP p X) (of j)) :
    gradedPieceOf p (exponentSumKer p X i₁) (m + 1) =
      (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
        (basisModificationDelta p X hm ρ) ⊔
      span (ZMod p) (Set.range fun a : {a : X // a ≠ i₁} ↦
        gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of a))) := by
  rw [gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket
      hm hρ hc (i₂ := i₁) fun j hj _ ↦ hd j hj,
    gradedPowIterBracket_self, span_zero_singleton, sup_bot_eq]

/-- **The `p`-power tail at the exceptional generator lies in the image of `δ_ρ`**: if `ξ_{i₂}` is
a combination `Σ_k b_k ∂_k ρ` of the derivatives in which the coefficient `b_{i₀} c_{i₀}` of the
`p`-power term `π` is nonzero, then `π^{m+1} ξ_{i₂} ∈ δ_ρ(gr_m(X)^X)` for `m ≥ 1` and `i₂ ≠ i₁`,
since `δ_ρ(b • π^m ξ_{i₂}) = (b_{i₀} c_{i₀}) • π^{m+1} ξ_{i₂} + [π^m ξ_{i₂}, ξ_{i₂}]` and the
bracket vanishes. -/
theorem gradedPowIter_gradedMkZero_mem_map_basisModificationDelta_pi (hm : 1 ≤ m)
    (hc : ∀ j, j ≠ i₀ → (degreeOneBasis p X).repr ρ (Sum.inl j) = 0)
    (hb : ∃ b : X → ZMod p,
      ∑ k, b k • degreeOneDeriv p X k ρ = gradedMkZero p (freeProP p X) (of i₂) ∧
        b i₀ * (degreeOneBasis p X).repr ρ (Sum.inl i₀) ≠ 0)
    (hi : i₂ ≠ i₁) :
    gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of i₂)) ∈
      (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
        (basisModificationDelta p X hm ρ) := by
  obtain ⟨b, hb, hb₀⟩ := hb
  have hτ : gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i₂)) ∈
      gradedPieceOf p (exponentSumKer p X i₁) m :=
    gradedPowIter_gradedMkZero_mem_gradedPieceOf (of_mem_exponentSumKer hi) m
  have key : basisModificationDelta p X hm ρ
      (fun k ↦ b k • gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i₂))) =
      (b i₀ * (degreeOneBasis p X).repr ρ (Sum.inl i₀)) •
        gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of i₂)) := by
    rw [basisModificationDelta_smul, hb, gradedBracket_gradedPowIter_self, add_zero,
      gradedPowIter_succ, Finset.sum_eq_single i₀ (fun k _ hk ↦ by rw [hc k hk, mul_zero])
        fun h ↦ (h (Finset.mem_univ _)).elim]
  refine ⟨fun k ↦ (b i₀ * (degreeOneBasis p X).repr ρ (Sum.inl i₀))⁻¹ •
    (b k • gradedPowIter p (freeProP p X) m (gradedMkZero p (freeProP p X) (of i₂))),
    Submodule.mem_pi.2 fun k _ ↦ smul_mem _ _ (smul_mem _ _ hτ), ?_⟩
  rw [← Pi.smul_def, map_smul, key, smul_smul, inv_mul_cancel₀ hb₀, one_smul]

/-- **The constrained span statement with an exceptional generator, sharp form** (Labute, §4.2,
Lemma 3). Under the hypotheses of
`gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket`, if moreover
`ξ_{i₂}` is a combination of the derivatives with nonzero coefficient `b_{i₀} c_{i₀}` at the
`p`-power generator and `i₂ ≠ i₁`, then the tail at `x_{i₂}` is absorbed by the image of `δ_ρ`:

  `gr_{m+1}(X) = δ_ρ(gr_m(X)^X) + T'_{m+1} + 𝔽_p π^m [ξ_{i₂}, ξ_{i₁}]`,

with `T'_{m+1}` spanned by the `π^{m+1} ξ_a` for `a ≠ i₁, i₂`. For the relator
`x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯` these are Labute's spanning vectors `π^{m+1} ξ_a` (`a ≠ x₂, x₄`)
and `π^m [ξ₂, ξ₄]`. -/
theorem gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket_of_ne
    (hm : 1 ≤ m) (hρ : span (ZMod p) (Set.range fun j ↦ degreeOneDeriv p X j ρ) = ⊤)
    (hc : ∀ j, j ≠ i₀ → (degreeOneBasis p X).repr ρ (Sum.inl j) = 0)
    (hd : ∀ j, j ≠ i₁ → j ≠ i₂ → ∃ b : X → ZMod p, b i₀ = 0 ∧
      ∑ k, b k • degreeOneDeriv p X k ρ = gradedMkZero p (freeProP p X) (of j))
    (hb : ∃ b : X → ZMod p,
      ∑ k, b k • degreeOneDeriv p X k ρ = gradedMkZero p (freeProP p X) (of i₂) ∧
        b i₀ * (degreeOneBasis p X).repr ρ (Sum.inl i₀) ≠ 0)
    (hi : i₂ ≠ i₁) :
    gradedPieceOf p (exponentSumKer p X i₁) (m + 1) =
      (Submodule.pi Set.univ fun _ : X ↦ gradedPieceOf p (exponentSumKer p X i₁) m).map
        (basisModificationDelta p X hm ρ) ⊔
      span (ZMod p) (Set.range fun a : {a : X // a ≠ i₁ ∧ a ≠ i₂} ↦
        gradedPowIter p (freeProP p X) (m + 1) (gradedMkZero p (freeProP p X) (of a))) ⊔
      span (ZMod p) {gradedPowIterBracket p (freeProP p X) m (of i₂) (of i₁)} := by
  refine le_antisymm ?_ (sup_le (sup_le
    (map_basisModificationDelta_pi_gradedPieceOf_exponentSumKer_le hm ρ i₁) (span_le.2 ?_))
    (span_le.2 (Set.singleton_subset_iff.2
      (gradedPowIterBracket_mem_gradedPieceOf (commutator_le_exponentSumKer i₁) m _ _))))
  · rw [gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket
      hm hρ hc hd]
    refine sup_le (sup_le (le_sup_left.trans le_sup_left) (span_le.2 ?_)) le_sup_right
    rintro _ ⟨a, rfl⟩
    by_cases ha : (a : X) = i₂
    · dsimp only
      rw [ha]
      exact mem_sup_left (mem_sup_left
        (gradedPowIter_gradedMkZero_mem_map_basisModificationDelta_pi hm hc hb hi))
    · exact mem_sup_left (mem_sup_right (subset_span ⟨⟨a, a.2, ha⟩, rfl⟩))
  · rintro _ ⟨a, rfl⟩
    exact gradedPowIter_gradedMkZero_mem_gradedPieceOf (of_mem_exponentSumKer a.2.1) _

end ConstrainedSpan

end freeProP

end TauCeti
