/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.TrivialFp.Cup
public import TauCeti.Topology.Algebra.Group.LowerCentralSeries.Graded.Heisenberg
public import TauCeti.Topology.Algebra.Group.Profinite.Free.DegreeOneForm
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Relation.Rank

/-!
# The relator functional of a minimal presentation and the cup product

Let `F = freeProP p X` be a free pro-`p` group, let `R ≤ Φ(F)` be a closed normal subgroup
contained in its pro-`p` Frattini subgroup, and let `G ≅ F ⧸ R`, so that `1 → R → F → G → 1` is a
minimal presentation of `G`. The transgression `H¹(R, 𝔽_p)^F → H²(G, 𝔽_p)` is bijective and
`H¹(R, 𝔽_p)^F` is the continuous `𝔽_p`-dual of `R ⧸ Rᵖ[R, F]` (`TauCeti.h2DualEquiv`). Evaluating at
a relator `r ∈ R` therefore defines a linear functional on `H²(G, 𝔽_p)`, the **relator functional**
`TauCeti.freeProP.relatorFunctional`; `TauCeti.freeProP.relatorEval` is the same functional on the
explicit model `H2 G (ZMod p)`, for an arbitrary trivial action of `G` on `𝔽_p`.

The main theorem computes the relator functional on cup products. For `a, b ∈ H¹(G, 𝔽_p)`, with
characters `χ, ψ : F → 𝔽_p` obtained by composing the characters of `G` attached to `a` and `b` with
`F → G`,

  `relatorFunctional r (a ⌣ b) = - B_{⟦r⟧}(χ, ψ)`,

where `B_{⟦r⟧}` is the degree-one form (`TauCeti.freeProP.degreeOneForm`) of the class of `r` in
`gr_1(F) = λ_1(F) ⧸ λ_2(F)`. This is Labute's Proposition 3: the cup product on `H¹(G, 𝔽_p)` is read
off the coordinates of the relator class in the standard basis of `gr_1(F)`, the commutator
coordinates off the diagonal and `(p choose 2)` times the `p`-power coordinates on it. The proof
lifts the cup product through a Heisenberg cochain `h` of `(χ, ψ)`, which exists because
`H²(F, 𝔽_p) = 0`; the transgression formula `tg [-h|_R] = a ⌣ b` is
`TauCeti.ContCohomology.IsHeisenbergCochain.transgression_negRestrict`, and on `λ_1(F)` the cochain
`h` is the Heisenberg functional of `(χ, ψ)`
(`TauCeti.ContCohomology.IsHeisenbergCochain.apply_eq_heisenbergFunctional`).

When `R` is the closed normal closure of the single relator `r`, the relator functional is injective
(`TauCeti.freeProP.relatorFunctional_injective`): `R ⧸ Rᵖ[R, F]` is then topologically generated by
the class of `r`, so a character of it vanishing at `r` vanishes identically. For a one-relator
group with `H²(G, 𝔽_p) ≠ 0` this makes the relator functional the trace isomorphism
`H²(G, 𝔽_p) ≅ 𝔽_p` attached to the relator.

## Main definitions

* `TauCeti.freeProP.relatorEval`: evaluation of the inverse transgression at a relator, on the
  explicit model `H2 G (ZMod p)`.
* `TauCeti.freeProP.relatorFunctional`: the relator functional `H²(G, 𝔽_p) → 𝔽_p`, on the canonical
  carrier `cohomFp p G 2`.

## Main results

* `TauCeti.ContCohomology.IsHeisenbergCochain.apply_eq_heisenbergFunctional`: a Heisenberg cochain
  of two `𝔽_p`-characters of a free pro-`p` group of finite rank agrees on `λ_1(F)` with their
  Heisenberg functional.
* `TauCeti.freeProP.relatorEval_h2QuotientEquiv_transgression`,
  `TauCeti.freeProP.relatorFunctional_apply`: the defining equations.
* `TauCeti.freeProP.relatorEval_explicitCup11`, `TauCeti.freeProP.relatorFunctional_cupFp`: **the
  relator functional of a cup product is minus the degree-one form of the relator class**.
* `TauCeti.freeProP.relatorEval_injective`, `TauCeti.freeProP.relatorFunctional_injective`: for a
  single relator, the relator functional is injective.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, §1.4 and
  Proposition 3.
* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (3.9.5) and
  Chapter III, §9.
-/

public section

namespace TauCeti

open ContCohomology Subgroup

universe u v

-- Preferring the ring path keeps a single additive structure on `ZMod p`, so that the trivial
-- actions below are the ones the explicit models are stated against.
attribute [local instance 2000] Ring.toAddCommGroup

variable {p : ℕ} [Fact p.Prime] {X : Type u}

/-! ### Heisenberg cochains and the Heisenberg functional -/

section Heisenberg

variable [Finite X] [DistribMulAction (freeProP p X) (ZMod p)]
  {a b : Z1 (freeProP p X) (ZMod p)} {h : freeProP p X → ZMod p}
  (hh : IsHeisenbergCochain (AddMonoidHom.mul : ZMod p →+ ZMod p →+ ZMod p) a b h)
  (htriv : ∀ (g : freeProP p X) (x : ZMod p), g • x = x)
include hh htriv

/-- **A Heisenberg cochain of two `𝔽_p`-characters of a free pro-`p` group is their Heisenberg
functional on `λ_1(F)`.** Let `F` be the free pro-`p` group on a finite type, let `a`, `b` be
continuous `1`-cocycles for a trivial action on `𝔽_p`, that is continuous characters `χ`, `ψ` of
`F`, and let `h` be a Heisenberg cochain for `(a, b)` and multiplication. Then on `n ∈ λ_1(F)` the
value `h n` is the Heisenberg functional of `χ` and `ψ` at the class of `n` in `gr_1(F)`. -/
theorem ContCohomology.IsHeisenbergCochain.apply_eq_heisenbergFunctional
    (n : pLowerCentralSeries p (freeProP p X) 1) :
    h n = freeProP.heisenbergFunctional (Additive.toMul (Z1EquivOfSmulEqSelf htriv a))
      (Additive.toMul (Z1EquivOfSmulEqSelf htriv b)) (gradedMk p (freeProP p X) 1 n) := by
  have hpM : ∀ x : ZMod p, p • x = 0 := ZModModule.char_nsmul_eq_zero p
  have haN : ∀ n : pLowerCentralSeries p (freeProP p X) 1, (a : freeProP p X → ZMod p) n = 0 :=
    fun n ↦ apply_eq_zero_of_mem_Z1_of_mem_pLowerCentralSeries_one htriv hpM a.2 n.2
  have hbN : ∀ n : pLowerCentralSeries p (freeProP p X) 1, (b : freeProP p X → ZMod p) n = 0 :=
    fun n ↦ apply_eq_zero_of_mem_Z1_of_mem_pLowerCentralSeries_one htriv hpM b.2 n.2
  have key : (hh.gradedRestrict htriv haN hbN hpM).toZModLinearMap p =
      freeProP.heisenbergFunctional (Additive.toMul (Z1EquivOfSmulEqSelf htriv a))
        (Additive.toMul (Z1EquivOfSmulEqSelf htriv b)) := by
    refine freeProP.heisenbergFunctional_unique _ _ (fun u v ↦ ?_) fun u ↦ ?_
    · simp only [AddMonoidHom.coe_toZModLinearMap,
        hh.gradedRestrict_gradedBracket_gradedMkZero htriv haN hbN hpM htriv htriv,
        AddMonoidHom.mul_apply, Z1EquivOfSmulEqSelf_apply, toAdd_ofAdd]
    · simp only [AddMonoidHom.coe_toZModLinearMap,
        hh.gradedRestrict_gradedPow_gradedMkZero htriv haN hbN hpM htriv htriv,
        AddMonoidHom.mul_apply, Z1EquivOfSmulEqSelf_apply, toAdd_ofAdd]
  rw [← key, AddMonoidHom.coe_toZModLinearMap, gradedRestrict_gradedMk]

end Heisenberg

/-! ### The relator functional -/

namespace freeProP

variable {R : Subgroup (freeProP p X)} [R.Normal]
  {G : Type v} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  (hRc : IsClosed (R : Set (freeProP p X))) (hR : R ≤ proPFrattini p (freeProP p X))
  (e : freeProP p X ⧸ R ≃ₜ* G)

section Explicit

variable [DistribMulAction (freeProP p X) (ZMod p)] [ContinuousSMul (freeProP p X) (ZMod p)]
  [DistribMulAction G (ZMod p)] [ContinuousSMul G (ZMod p)]
  (htrivF : ∀ (g : freeProP p X) (m : ZMod p), g • m = m)
  (htriv : ∀ (g : G) (m : ZMod p), g • m = m)

/-- **Evaluation at a relator, on the explicit model.** Let `F` be the free pro-`p` group on `X`,
let `R ≤ Φ(F)` be a closed normal subgroup, and let `G ≅ F ⧸ R` be a group acting trivially on
`𝔽_p`, as does `F`. A class in `H²(G, 𝔽_p)` corresponds under the inverse transgression to a
character of `R ⧸ Rᵖ[R, F]` (`TauCeti.h2DualEquiv`); evaluating that character at the class of a
relator `r ∈ R` is the relator functional of `r`, an additive map `H2 G (ZMod p) →+ ZMod p`. -/
noncomputable def relatorEval (r : R) : H2 G (ZMod p) →+ ZMod p where
  toFun x := Multiplicative.toAdd (Additive.toMul (h2DualEquiv hRc hR e htrivF htriv x)
    (r : R ⧸ (pLowerCentralStep p R).subgroupOf R))
  map_zero' := by simp
  map_add' x y := by simp [toMul_add, ContinuousMonoidHom.mul_apply, toAdd_mul]

/-- The defining equation of `TauCeti.freeProP.relatorEval`: the value at the class of `r` of the
character of `R ⧸ Rᵖ[R, F]` attached to `x` by `TauCeti.h2DualEquiv`. -/
@[simp]
theorem relatorEval_apply (r : R) (x : H2 G (ZMod p)) :
    relatorEval hRc hR e htrivF htriv r x =
      Multiplicative.toAdd (Additive.toMul (h2DualEquiv hRc hR e htrivF htriv x)
        (r : R ⧸ (pLowerCentralStep p R).subgroupOf R)) :=
  (rfl)

/-- **The relator functional inverts the transgression**: on the class transgressed from an
invariant class `y ∈ H¹(R, 𝔽_p)^F`, the relator functional of `r` is the value at `r` of the
continuous homomorphism `R → 𝔽_p` representing `y`. -/
theorem relatorEval_h2QuotientEquiv_transgression (r : R)
    (y : H1ConjInvariants (freeProP p X) (ZMod p) R) :
    relatorEval hRc hR e htrivF htriv r
        (h2QuotientEquiv e htrivF htriv (transgression (freeProP p X) (ZMod p) R hRc y)) =
      Multiplicative.toAdd
        (Additive.toMul (H1EquivOfSmulEqSelf (fun (n : R) (m : ZMod p) ↦ htrivF n m) y.1) r) := by
  rw [relatorEval_apply, h2DualEquiv_h2QuotientEquiv_transgression,
    H1ConjInvariantsEquivOfSmulEqSelf_apply_mk]

/-- **The relator functional of a single relator is injective.** If `R` is the closed normal
closure of `r`, then `R ⧸ Rᵖ[R, F]` is topologically generated by the class of `r`, so a character
of it vanishing at `r` is trivial. -/
theorem relatorEval_injective (r : R)
    (hgen : (normalClosure {(r : freeProP p X)}).topologicalClosure = R) :
    Function.Injective (relatorEval hRc hR e htrivF htriv r) := by
  refine (injective_iff_map_eq_zero _).2 fun x hx ↦ ?_
  rw [relatorEval_apply, toAdd_eq_zero] at hx
  rw [← (h2DualEquiv hRc hR e htrivF htriv).map_eq_zero_iff]
  set ψ := h2DualEquiv hRc hR e htrivF htriv x
  -- `R ⧸ Rᵖ[R, F]` is topologically generated by the class of `r`.
  have hgen' : (Subgroup.closure (QuotientGroup.mk' ((pLowerCentralStep p R).subgroupOf R) ''
      ({r} : Set R))).topologicalClosure = ⊤ := by
    refine ((isProP_freeProP p X).topologicalClosure_normalClosure_eq_iff_quotient_pLowerCentralStep
      Fact.out hRc {r}).1 ?_
    rwa [Set.image_singleton]
  -- The kernel of the character is closed and contains the class of `r`, hence everything.
  have hker : IsClosed (((Additive.toMul ψ).toMonoidHom.ker : Subgroup _) :
      Set (R ⧸ (pLowerCentralStep p R).subgroupOf R)) := by
    rw [MonoidHom.coe_ker]
    exact isClosed_singleton.preimage (Additive.toMul ψ).continuous
  have hle : (Subgroup.closure (QuotientGroup.mk' ((pLowerCentralStep p R).subgroupOf R) ''
      ({r} : Set R))).topologicalClosure ≤ (Additive.toMul ψ).toMonoidHom.ker := by
    refine Subgroup.topologicalClosure_minimal _ ((Subgroup.closure_le _).2 ?_) hker
    rw [Set.image_singleton, Set.singleton_subset_iff, SetLike.mem_coe, MonoidHom.mem_ker]
    exact hx
  rw [hgen', top_le_iff] at hle
  refine Additive.toMul.injective (ContinuousMonoidHom.ext fun q ↦ ?_)
  have hq := MonoidHom.mem_ker.1 (hle ▸ Subgroup.mem_top q)
  simpa using hq

variable [Finite X]

/-- **Labute's Proposition 3, on the explicit model.** Let `F` be the free pro-`p` group on a
finite type `X`, let `R ≤ Φ(F)` be a closed normal subgroup, let `G ≅ F ⧸ R` act trivially on `𝔽_p`,
as does `F`, and let `r ∈ R`. For two classes `a, b ∈ H¹(G, 𝔽_p)`, the relator functional of `r` on
the explicit cup product `a ⌣ b` is minus the degree-one form of the class of `r` in `gr_1(F)`,
evaluated at the characters of `F` obtained from `a` and `b` by composing with `F → G`. -/
theorem relatorEval_explicitCup11 (r : R) (a b : H1 G (ZMod p)) :
    relatorEval hRc hR e htrivF htriv r
        (explicitCup11 G (ZMod p) (ZMod p) (ZMod p) AddMonoidHom.mul continuous_mul
          (smul_mul_smul_of_smul_eq_self htriv) a b) =
      -degreeOneForm (gradedMk p (freeProP p X) 1
          ⟨r, (pLowerCentralSeries_one_eq_proPFrattini Fact.out).symm.le (hR r.2)⟩)
        (((e : freeProP p X ⧸ R →ₜ* G).comp
          (ContinuousMonoidHom.quotientMk R)).continuousZModDualMap (H1EquivOfSmulEqSelf htriv a))
        (((e : freeProP p X ⧸ R →ₜ* G).comp
          (ContinuousMonoidHom.quotientMk R)).continuousZModDualMap
            (H1EquivOfSmulEqSelf htriv b)) := by
  induction a using QuotientAddGroup.induction_on with
  | _ c =>
  induction b using QuotientAddGroup.induction_on with
  | _ d =>
  have := freeProP.subsingleton_H2_zmod (p := p) (X := X)
  set φ : freeProP p X →ₜ* G :=
    (e : freeProP p X ⧸ R →ₜ* G).comp (ContinuousMonoidHom.quotientMk R) with hφ
  -- The pullback to `F` of a cocycle on `G`, as a cocycle; it vanishes on `R`.
  let pull (c : Z1 G (ZMod p)) : Z1 (freeProP p X) (ZMod p) :=
    (Z1EquivOfSmulEqSelf htrivF).symm
      (Additive.ofMul ((Additive.toMul (Z1EquivOfSmulEqSelf htriv c)).comp φ))
  have hpull (c : Z1 G (ZMod p)) (g : freeProP p X) :
      (pull c : freeProP p X → ZMod p) g = (c : G → ZMod p) (φ g) := by
    simp [pull]
  have hφ_coe (n : R) : φ n = 1 := by
    rw [hφ, ContinuousMonoidHom.comp_toFun, ContinuousMonoidHom.quotientMk_apply,
      (QuotientGroup.eq_one_iff (n : freeProP p X)).2 n.2, map_one]
  have hpullR (c : Z1 G (ZMod p)) (n : R) : (pull c : freeProP p X → ZMod p) n = 0 := by
    rw [hpull, hφ_coe]
    exact groupCohomology.map_one_of_isCocycle₁ (mem_Z1_iff.1 c.2).2
  -- A Heisenberg cochain for the pulled-back cocycles: `H²(F, 𝔽_p) = 0`.
  obtain ⟨h, hh⟩ := exists_isHeisenbergCochain_of_subsingleton_H2
    (μ := (AddMonoidHom.mul : ZMod p →+ ZMod p →+ ZMod p)) continuous_mul
    (smul_mul_smul_of_smul_eq_self htrivF) (pull c) (pull d)
  have haR := hpullR c
  have hbR := hpullR d
  have htg := hh.transgression_negRestrict continuous_mul (smul_mul_smul_of_smul_eq_self htrivF)
    hRc haR hbR
  -- The descent of a pulled-back cocycle to `F ⧸ R`, read on `G`, is the original class.
  have hfix : ∀ (g : G) (m : FixedPoints.addSubgroup R (ZMod p)),
      (FixedPoints.addSubgroup R (ZMod p)).subtype ((e.symm : G →ₜ* freeProP p X ⧸ R) g • m) =
        g • (FixedPoints.addSubgroup R (ZMod p)).subtype m := fun g m ↦
    (congrArg Subtype.val (quotient_smul_fixedPoints_addSubgroup_eq_of_smul_eq htrivF
      (e.symm g) m)).trans (htriv g m).symm
  have hdesc (c : Z1 G (ZMod p)) :
      explicitMap1 (freeProP p X ⧸ R) (FixedPoints.addSubgroup R (ZMod p)) G (ZMod p)
        (e.symm : G →ₜ* freeProP p X ⧸ R) (FixedPoints.addSubgroup R (ZMod p)).subtype
        continuous_of_discreteTopology hfix
        ((descendZ1 (pull c) (hpullR c) : Z1 _ _) : H1 (freeProP p X ⧸ R) _) =
      (c : H1 G (ZMod p)) := by
    rw [explicitMap1_mk]
    refine congrArg (fun z : Z1 G (ZMod p) => (z : H1 G (ZMod p)))
      (Subtype.ext (funext fun g ↦ ?_))
    obtain ⟨f, hf⟩ := QuotientGroup.mk_surjective (e.symm g)
    have hφf : φ f = g := by
      rw [hφ, ContinuousMonoidHom.comp_toFun, ContinuousMonoidHom.quotientMk_apply, hf]
      exact e.apply_symm_apply g
    have hef : (e.symm : G →ₜ* freeProP p X ⧸ R) g = (f : freeProP p X ⧸ R) := hf.symm
    rw [cocyclesMap1_apply, hef, AddSubgroup.coe_subtype, coe_descendZ1_apply_mk, hpull, hφf]
  have hpair : ∀ (m x : FixedPoints.addSubgroup R (ZMod p)),
      (FixedPoints.addSubgroup R (ZMod p)).subtype
          (Subgroup.fixedPointsPairing R AddMonoidHom.mul
            (fun n ↦ smul_mul_smul_of_smul_eq_self htrivF (n : freeProP p X)) m x) =
        AddMonoidHom.mul ((FixedPoints.addSubgroup R (ZMod p)).subtype m)
          ((FixedPoints.addSubgroup R (ZMod p)).subtype x) := fun m x ↦ by
    simp only [AddSubgroup.coe_subtype]
    exact Subgroup.coe_fixedPointsPairing R AddMonoidHom.mul _ m x
  -- The transgression formula, read on `G`.
  have key : explicitCup11 G (ZMod p) (ZMod p) (ZMod p) AddMonoidHom.mul continuous_mul
      (smul_mul_smul_of_smul_eq_self htriv) (c : H1 G (ZMod p)) (d : H1 G (ZMod p)) =
      h2QuotientEquiv e htrivF htriv (transgression (freeProP p X) (ZMod p) R hRc
        ⟨hh.negRestrict haR hbR, hh.negRestrict_mem_H1ConjInvariants haR hbR⟩) := by
    rw [htg, h2QuotientEquiv_apply, explicitMap2_explicitCup11 (freeProP p X ⧸ R) _ _ _ _ _ _ G
      (ZMod p) (ZMod p) (ZMod p) AddMonoidHom.mul continuous_mul
      (smul_mul_smul_of_smul_eq_self htriv) (e.symm : G →ₜ* freeProP p X ⧸ R)
      (FixedPoints.addSubgroup R (ZMod p)).subtype (FixedPoints.addSubgroup R (ZMod p)).subtype
      (FixedPoints.addSubgroup R (ZMod p)).subtype continuous_of_discreteTopology
      continuous_of_discreteTopology continuous_of_discreteTopology hfix hfix hfix hpair,
      hdesc c, hdesc d]
  have hr : h r = heisenbergFunctional (Additive.toMul (Z1EquivOfSmulEqSelf htrivF (pull c)))
      (Additive.toMul (Z1EquivOfSmulEqSelf htrivF (pull d))) (gradedMk p (freeProP p X) 1
        ⟨r, (pLowerCentralSeries_one_eq_proPFrattini Fact.out).symm.le (hR r.2)⟩) :=
    hh.apply_eq_heisenbergFunctional htrivF
      ⟨r, (pLowerCentralSeries_one_eq_proPFrattini Fact.out).symm.le (hR r.2)⟩
  rw [key, relatorEval_h2QuotientEquiv_transgression]
  simp only [H1EquivOfSmulEqSelf_mk, Z1EquivOfSmulEqSelf_apply, toAdd_ofAdd,
    hh.coe_negRestrict haR hbR, hr, degreeOneForm_apply, pull, AddEquiv.apply_symm_apply,
    toMul_ofMul, ContinuousMonoidHom.toMul_continuousZModDualMap]

end Explicit

variable [LocallyCompactSpace G]

/-- **The relator functional.** Let `F` be the free pro-`p` group on `X`, let `R ≤ Φ(F)` be a
closed normal subgroup, and let `G ≅ F ⧸ R`, so that `1 → R → F → G → 1` is a minimal presentation
of `G`. A class in `H²(G, 𝔽_p)` corresponds under the inverse transgression to a continuous
homomorphism `R ⧸ Rᵖ[R, F] → 𝔽_p`; evaluating it at the class of a relator `r ∈ R` is the relator
functional of `r`, an `𝔽_p`-linear functional on `H²(G, 𝔽_p)`. On a cup product it is minus the
degree-one form of the class of `r` in `gr_1(F)` (`TauCeti.freeProP.relatorFunctional_cupFp`), and
for a single relator it is injective (`TauCeti.freeProP.relatorFunctional_injective`). -/
noncomputable def relatorFunctional (r : R) : cohomFp p G 2 →ₗ[ZMod p] ZMod p :=
  letI := trivialZModAction p (freeProP p X)
  letI := trivialZModAction p G
  haveI : ContinuousSMul (freeProP p X) (ZMod p) := ⟨continuous_snd⟩
  haveI : ContinuousSMul G (ZMod p) := ⟨continuous_snd⟩
  AddMonoidHom.toZModLinearMap p
    ((relatorEval hRc hR e (fun _ _ ↦ rfl) (fun _ _ ↦ rfl) r).comp
      (cohomFpAddEquivH2 p G fun _ _ ↦ rfl).toAddMonoidHom)

/-- **The defining equation of the relator functional**: on the canonical carrier it is the
explicit relator functional `TauCeti.freeProP.relatorEval`, for the trivial actions
`trivialZModAction`, composed with the identification `cohomFpAddEquivH2` of `H²(G, 𝔽_p)` with its
explicit model. -/
@[simp]
theorem relatorFunctional_apply (r : R) (x : cohomFp p G 2) :
    letI := trivialZModAction p (freeProP p X)
    letI := trivialZModAction p G
    haveI : ContinuousSMul (freeProP p X) (ZMod p) := ⟨continuous_snd⟩
    haveI : ContinuousSMul G (ZMod p) := ⟨continuous_snd⟩
    relatorFunctional hRc hR e r x =
      relatorEval hRc hR e (fun _ _ ↦ rfl) (fun _ _ ↦ rfl) r
        (cohomFpAddEquivH2 p G (fun _ _ ↦ rfl) x) :=
  (rfl)

/-- **The relator functional of a single relator is injective.** If `R` is the closed normal
closure of `r`, the relator functional of `r` is injective on `H²(G, 𝔽_p)`. -/
theorem relatorFunctional_injective (r : R)
    (hgen : (normalClosure {(r : freeProP p X)}).topologicalClosure = R) :
    Function.Injective (relatorFunctional hRc hR e r) := by
  let _ := trivialZModAction p (freeProP p X)
  let _ := trivialZModAction p G
  have : ContinuousSMul (freeProP p X) (ZMod p) := ⟨continuous_snd⟩
  have : ContinuousSMul G (ZMod p) := ⟨continuous_snd⟩
  have : (relatorFunctional hRc hR e r : cohomFp p G 2 → ZMod p) =
      relatorEval hRc hR e (fun _ _ ↦ rfl) (fun _ _ ↦ rfl) r ∘
        cohomFpAddEquivH2 p G (fun _ _ ↦ rfl) :=
    funext fun x ↦ relatorFunctional_apply hRc hR e r x
  rw [this]
  exact (relatorEval_injective hRc hR e _ _ r hgen).comp (cohomFpAddEquivH2 p G _).injective

variable [Finite X]

/-- **Labute's Proposition 3: the relator functional of a cup product is minus the degree-one form
of the relator class.** Let `F` be the free pro-`p` group on a finite type `X`, let `R ≤ Φ(F)` be a
closed normal subgroup, let `G ≅ F ⧸ R`, and let `r ∈ R`. For `a, b ∈ H¹(G, 𝔽_p)`, with characters
`χ, ψ : F → 𝔽_p` obtained by composing the characters of `G` attached to `a` and `b` with `F → G`,

  `relatorFunctional r (a ⌣ b) = - B_{⟦r⟧}(χ, ψ)`,

where `B_{⟦r⟧}` is the degree-one form of the class of `r` in `gr_1(F)`: the cup product on
`H¹(G, 𝔽_p)` is read off the coordinates of the relator class in the standard basis of `gr_1(F)`. -/
theorem relatorFunctional_cupFp (r : R) (a b : cohomFp p G 1) :
    relatorFunctional hRc hR e r (cupFp p G a b) =
      -degreeOneForm (gradedMk p (freeProP p X) 1
          ⟨r, (pLowerCentralSeries_one_eq_proPFrattini Fact.out).symm.le (hR r.2)⟩)
        (((e : freeProP p X ⧸ R →ₜ* G).comp
          (ContinuousMonoidHom.quotientMk R)).continuousZModDualMap
            (cohomFpLinearEquivContinuousZModDual p G a))
        (((e : freeProP p X ⧸ R →ₜ* G).comp
          (ContinuousMonoidHom.quotientMk R)).continuousZModDualMap
            (cohomFpLinearEquivContinuousZModDual p G b)) := by
  let _ := trivialZModAction p (freeProP p X)
  let _ := trivialZModAction p G
  have : ContinuousSMul (freeProP p X) (ZMod p) := ⟨continuous_snd⟩
  have : ContinuousSMul G (ZMod p) := ⟨continuous_snd⟩
  rw [relatorFunctional_apply, cohomFpAddEquivH2_cupFp, relatorEval_explicitCup11,
    cohomFpLinearEquivContinuousZModDual_apply, cohomFpLinearEquivContinuousZModDual_apply]

end freeProP

end TauCeti
