/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
public import TauCeti.AlgebraicGeometry.IdealSheaf.Module
public import TauCeti.AlgebraicGeometry.Modules.Pullback.Basic

/-!
# Pullback of an ideal sheaf as a sheaf of modules

Let `g : X ⟶ Y` be a morphism of schemes and `I ⊆ 𝒪_Y` an ideal sheaf. There are two ways to pull
`I` back to `X`: the inverse image `I.comap g`, the ideal sheaf of the fibre product
`X ×_Y V(I)`, and the pullback `g^* I` of `I` as an `𝒪_Y`-module. Pulling back the inclusion
`I ⟶ 𝒪_Y` gives `g^* I ⟶ g^* 𝒪_Y ≅ 𝒪_X`, whose image is generated by the functions `g^♯ s` for
sections `s` of `I`; these lie in `I.comap g` (`app_mem_sections_comap`). So the composite factors
through `I.comap g ⊆ 𝒪_X`, giving the comparison morphism `g^* I ⟶ I.comap g`.

The comparison is not an isomorphism in general: for the inclusion `g` of `V(I)`, the pullback
`g^* I` is `I / I²` while `I.comap g` is zero. It is one for effective Cartier divisors whose
inverse image is again effective Cartier (`Scheme.IdealSheafData.isIso_pullbackSheafHom` in
`TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.Pullback`).

## Main declarations

* `Scheme.IdealSheafData.app_mem_sections_comap`: `g^♯` carries sections of `I` to sections of
  `I.comap g`;
* `Scheme.IdealSheafData.pullbackSheafHom`: the comparison morphism `g^* I ⟶ I.comap g`,
  characterized by `pullbackSheafHom_sheafι`, and computed on the images of sections of `I`
  under the unit of the pullback–pushforward adjunction by `pullbackSheafHom_app_unit_app`.

## References

* The Stacks Project, *Divisors*, Section *Effective Cartier divisors* (Tag 01WQ), where the
  pullback of an effective Cartier divisor is defined.
-/

public section

open CategoryTheory Limits

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

noncomputable section

variable {X Y : Scheme.{u}}

/-- Pulling back along `g` carries sections of `I` to sections of the inverse image of `I`. -/
theorem app_mem_sections_comap (I : Y.IdealSheafData) (g : X ⟶ Y) {U : Y.Opens}
    {s : Γ(Y, U)} (hs : s ∈ I.sections U) : g.app U s ∈ (I.comap g).sections (g ⁻¹ᵁ U) := by
  rw [mem_sections_iff] at hs ⊢
  -- The closed subscheme of `I.comap g` maps to that of `I` compatibly with `g`.
  have hcomm : (I.comap g).subschemeι ≫ g =
      ((I.comapIso g).hom ≫ pullback.snd g I.subschemeι) ≫ I.subschemeι := by
    rw [← I.comapIso_hom_fst g, Category.assoc, Category.assoc, pullback.condition]
  obtain ⟨ψ, e⟩ : ∃ ψ, g.app U ≫ (I.comap g).subschemeι.app (g ⁻¹ᵁ U) =
      I.subschemeι.app U ≫ ψ := by
    have h := Scheme.Hom.congr_app hcomm U
    rw [Scheme.Hom.comp_app, Scheme.Hom.comp_app] at h
    exact ⟨_, h.trans (Category.assoc _ _ _)⟩
  rw [← ConcreteCategory.comp_apply, e, ConcreteCategory.comp_apply, hs, map_zero]

variable (I : Y.IdealSheafData) (g : X ⟶ Y)

/-- The transpose of `g^* I ⟶ g^* 𝒪_Y ≅ 𝒪_X` is the inclusion `I ⟶ 𝒪_Y` followed by the map
`𝒪_Y ⟶ g_* 𝒪_X` given by `g` on sections. -/
private lemma unit_app_comp_pushforward_map :
    (Scheme.Modules.pullbackPushforwardAdjunction g).unit.app I.sheaf ≫
        (Scheme.Modules.pushforward g).map ((Scheme.Modules.pullback g).map I.sheafι ≫
          (Scheme.Modules.pullbackObjUnitIso g).hom) =
      I.sheafι ≫ SheafOfModules.unitToPushforwardObjUnit g.toRingCatSheafHom :=
  ((Scheme.Modules.pullbackPushforwardAdjunction g).homEquiv_unit _ _ _).symm.trans <|
    ((Scheme.Modules.pullbackPushforwardAdjunction g).homEquiv_naturality_left _ _).trans <|
      congrArg (I.sheafι ≫ ·)
        (Scheme.Modules.pullbackPushforwardAdjunction_homEquiv_pullbackObjUnitIso_hom g)

/-- The composite `g^* I ⟶ g^* 𝒪_Y ≅ 𝒪_X` sends the image of a section `t` of `I` under the unit
of the adjunction to `g^♯ t`. -/
private lemma app_unit_app (U : Y.Opens) (t : Γ(I.sheaf, U)) :
    ((Scheme.Modules.pullback g).map I.sheafι ≫ (Scheme.Modules.pullbackObjUnitIso g).hom).app
        (g ⁻¹ᵁ U) (((Scheme.Modules.pullbackPushforwardAdjunction g).unit.app I.sheaf).app U t) =
      g.app U (I.sheafι.app U t) :=
  congrArg (fun φ ↦ Scheme.Modules.Hom.app φ U t) (unit_app_comp_pushforward_map I g)

/-- The composite `g^* I ⟶ g^* 𝒪_Y ≅ 𝒪_X` lands in the inverse image ideal sheaf `I.comap g`. -/
private lemma comp_cokernel_π_eq_zero :
    ((Scheme.Modules.pullback g).map I.sheafι ≫ (Scheme.Modules.pullbackObjUnitIso g).hom) ≫
      cokernel.π (I.comap g).sheafι = 0 := by
  apply ((Scheme.Modules.pullbackPushforwardAdjunction g).homEquiv _ _).injective
  rw [Adjunction.homEquiv_unit, Adjunction.homEquiv_unit, Functor.map_comp, ← Category.assoc,
    unit_app_comp_pushforward_map, Functor.map_zero, Limits.comp_zero]
  refine Scheme.Modules.hom_ext _ _ fun U ↦ ?_
  ext t
  have h : g.app U (I.sheafι.app U t) = (I.comap g).sheafι.app (g ⁻¹ᵁ U)
      ((I.comap g).sectionMk _ (app_mem_sections_comap I g (I.sheafι_app_mem U t))) :=
    ((I.comap g).sheafι_app_sectionMk _ _).symm
  -- Unfolding the composite on sections over `U`, the left-hand side is `π` applied to `g^♯ t`,
  -- which is a section of `I.comap g`, hence zero.
  change (cokernel.π (I.comap g).sheafι).app (g ⁻¹ᵁ U) (g.app U (I.sheafι.app U t)) = 0
  rw [h]
  exact (congrArg (fun φ ↦ Scheme.Modules.Hom.app φ (g ⁻¹ᵁ U) _)
    (cokernel.condition (I.comap g).sheafι)).trans rfl

/-- The canonical morphism `g^* I ⟶ I.comap g` from the pullback of an ideal sheaf to the ideal
sheaf of its inverse image: the pullback `g^* I ⟶ g^* 𝒪_Y ≅ 𝒪_X` of the inclusion `I ⟶ 𝒪_Y`
factors through `I.comap g ⊆ 𝒪_X` (`pullbackSheafHom_sheafι`). -/
def pullbackSheafHom : (Scheme.Modules.pullback g).obj I.sheaf ⟶ (I.comap g).sheaf :=
  Abelian.monoLift (I.comap g).sheafι _ (comp_cokernel_π_eq_zero I g)

/-- The morphism `pullbackSheafHom` followed by the inclusion `I.comap g ⟶ 𝒪_X` is the pullback
of the inclusion `I ⟶ 𝒪_Y`. -/
@[reassoc, simp]
lemma pullbackSheafHom_sheafι :
    I.pullbackSheafHom g ≫ (I.comap g).sheafι =
      (Scheme.Modules.pullback g).map I.sheafι ≫ (Scheme.Modules.pullbackObjUnitIso g).hom :=
  Abelian.monoLift_comp _ _ _

/-- The morphism `pullbackSheafHom` sends the image of a section `t` of `I` under the unit of the
adjunction to the section `g^♯ t` of `I.comap g`. -/
lemma pullbackSheafHom_app_unit_app (U : Y.Opens) (t : Γ(I.sheaf, U)) :
    (I.pullbackSheafHom g).app (g ⁻¹ᵁ U)
        (((Scheme.Modules.pullbackPushforwardAdjunction g).unit.app I.sheaf).app U t) =
      (I.comap g).sectionMk _ (app_mem_sections_comap I g (I.sheafι_app_mem U t)) := by
  apply (I.comap g).sheafι_app_injective
  rw [sheafι_app_sectionMk]
  exact (congrArg (fun φ ↦ Scheme.Modules.Hom.app φ (g ⁻¹ᵁ U)
    (((Scheme.Modules.pullbackPushforwardAdjunction g).unit.app I.sheaf).app U t))
      (pullbackSheafHom_sheafι I g)).trans (app_unit_app I g U t)

end

end AlgebraicGeometry.Scheme.IdealSheafData
