/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Galois.AbsoluteGaloisGroup.Basic
public import TauCeti.FieldTheory.Galois.Restriction

/-!
# The map of absolute Galois groups induced by a field extension

Let `L/K` be an arbitrary field extension, not necessarily algebraic, and let
`τ : Kˢ →ₐ[K] Lˢ` be a `K`-embedding of separable closures; one always exists, since `Lˢ` is
separably closed and `Kˢ/K` is separable algebraic. Every automorphism `g` of `Lˢ` over `L` maps
`τ(Kˢ)` to itself, because `Kˢ/K` is normal, and so restricts along `τ` to an automorphism of
`Kˢ` over `K`. This gives a continuous homomorphism

```text
absoluteGaloisGroupMap τ : G_L →ₜ* G_K,   τ (absoluteGaloisGroupMap τ g x) = g (τ x).
```

For a completion `K_v` of a global field `K` it is the inclusion of the decomposition group, and
it is the group-theoretic input of the localization maps of Galois cohomology. It is the analogue,
at the separable closures on which `TauCeti.AbsoluteGaloisGroup` is built, of Mathlib's
`Field.absoluteGaloisGroup.mapOfAlgebra` for algebraic closures (María Inés de
Frutos-Fernández), whose continuity proof is followed here.

The embedding `τ` is a choice: two embeddings differ by an automorphism `h` of `Kˢ` over `K`
(`AlgHom.exists_comp_eq_of_normal`), and then the two maps differ by conjugation by `h`
(`absoluteGaloisGroupMap_comp`), which is invisible in cohomology.

The last section concerns Mathlib's map `Field.absoluteGaloisGroup.mapOfAlgebra K L` itself,
along a `K`-embedding of algebraic closures. When `algebraMap K L` is bijective, that embedding is
onto, because `Lᵃˡᵍ` is algebraic over `K` and `Kᵃˡᵍ` is algebraically closed, and the map of
absolute Galois groups is bijective. So an isomorphism of fields `e : K ≃+* L` induces an
isomorphism of topological groups `G_L ≃ₜ* G_K`, through which statements about absolute Galois
groups transport between isomorphic fields.

## Main definitions

* `TauCeti.absoluteGaloisGroupMap τ`: the continuous homomorphism `G_L →ₜ* G_K` along `τ`.
* `TauCeti.absoluteGaloisGroupMapEquiv e`: for an isomorphism of fields `e : K ≃+* L`, Mathlib's
  map `Field.absoluteGaloisGroup.map e` as an isomorphism `G_L ≃ₜ* G_K`.

## Main results

* `TauCeti.absoluteGaloisGroupMap_commutes`: `τ (absoluteGaloisGroupMap τ g x) = g (τ x)`.
* `TauCeti.absoluteGaloisGroupMap_comp`: changing `τ` by an automorphism `h` of `Kˢ` conjugates
  the map by `h`.
* `TauCeti.absoluteGaloisGroupMap_absoluteGaloisGroupMap`: the maps are compatible with
  composition of extensions.
* `TauCeti.absoluteGaloisGroup_mapOfAlgebra_commutes`: Mathlib's map
  `Field.absoluteGaloisGroup.mapOfAlgebra K L g` is intertwined with `g` by the embedding of
  algebraic closures.
* `TauCeti.bijective_absoluteGaloisGroup_mapOfAlgebra`,
  `TauCeti.bijective_absoluteGaloisGroup_map`: the map is bijective along an isomorphism of
  fields.
-/

public section

noncomputable section

namespace TauCeti

open IntermediateField

variable {K : Type*} [Field K] {L : Type*} [Field L] [Algebra K L]

/-- **The map of absolute Galois groups along an extension `L/K`**, given a `K`-embedding
`τ : Kˢ →ₐ[K] Lˢ` of separable closures: an automorphism `g` of `Lˢ` over `L` is in particular
an automorphism over `K`, and it restricts along `τ` to the automorphism of the normal extension
`Kˢ/K` intertwined with `g` by `τ` (`absoluteGaloisGroupMap_commutes`). It is continuous for the
Krull topologies: an automorphism of `Lˢ` fixing the finite extension of `L` generated by the image
of a finite subextension `F` of `Kˢ/K` is sent to one fixing `F`. -/
def absoluteGaloisGroupMap (τ : SeparableClosure K →ₐ[K] SeparableClosure L) :
    AbsoluteGaloisGroup L →ₜ* AbsoluteGaloisGroup K where
  toMonoidHom := τ.restrictNormalHom.comp (AlgEquiv.restrictScalarsHom K)
  continuous_toFun := by
    classical
    refine continuous_of_continuousAt_one (τ.restrictNormalHom.comp
      (AlgEquiv.restrictScalarsHom K)) ?_
    rw [ContinuousAt, map_one]
    refine ((galGroupBasis L (SeparableClosure L)).nhds_one_hasBasis.tendsto_iff
      (galGroupBasis K (SeparableClosure K)).nhds_one_hasBasis).mpr ?_
    rintro _ ⟨_, ⟨F, hF : FiniteDimensional _ _, rfl⟩, rfl⟩
    refine ⟨_, ⟨_, ⟨adjoin L (F.map τ), ?_, rfl⟩, rfl⟩, fun g hg x ↦ ?_⟩
    · -- The image of a finitely generated extension generates a finite extension of `L`.
      suffices Algebra.EssFiniteType L (adjoin L (F.map τ : Set (SeparableClosure L))) from
        Algebra.finite_of_essFiniteType_of_isAlgebraic
      replace hF : Algebra.EssFiniteType K F := inferInstance
      rw [essFiniteType_iff] at hF ⊢
      obtain ⟨s, rfl⟩ := hF
      refine ⟨s.image τ, ?_⟩
      rw [adjoin_map, adjoin_adjoin_right, Finset.coe_image]
    · exact τ.injective <| (τ.restrictNormalHom_commutes _ x).trans <|
        hg ⟨τ x, subset_adjoin _ _ ⟨_, x.2, rfl⟩⟩

variable (τ : SeparableClosure K →ₐ[K] SeparableClosure L)

/-- `absoluteGaloisGroupMap τ g` is intertwined with `g` by `τ`. -/
@[simp]
theorem absoluteGaloisGroupMap_commutes (g : AbsoluteGaloisGroup L) (x : SeparableClosure K) :
    τ (absoluteGaloisGroupMap τ g x) = g (τ x) :=
  τ.restrictNormalHom_commutes _ x

/-- `absoluteGaloisGroupMap τ g` is the unique automorphism of `Kˢ` intertwined with `g` by `τ`. -/
theorem absoluteGaloisGroupMap_eq_iff {g : AbsoluteGaloisGroup L} {h : AbsoluteGaloisGroup K} :
    absoluteGaloisGroupMap τ g = h ↔ ∀ x, g (τ x) = τ (h x) :=
  τ.restrictNormalHom_eq_iff

/-- **Changing the embedding conjugates the map**: precomposing `τ` with an automorphism `h` of
`Kˢ` over `K` replaces `absoluteGaloisGroupMap τ g` by its conjugate `h⁻¹ * _ * h`. -/
theorem absoluteGaloisGroupMap_comp (h : AbsoluteGaloisGroup K) (g : AbsoluteGaloisGroup L) :
    absoluteGaloisGroupMap (τ.comp (h : SeparableClosure K →ₐ[K] SeparableClosure K)) g =
      h⁻¹ * absoluteGaloisGroupMap τ g * h :=
  τ.restrictNormalHom_comp h _

/-- **The maps are compatible with composition of extensions** `K → L → M`: if `τ'' : Kˢ → Mˢ`
is the composite of `τ : Kˢ → Lˢ` and `τ' : Lˢ → Mˢ`, the map `G_M → G_K` along `τ''` is the
composite of the maps `G_M → G_L → G_K`. -/
theorem absoluteGaloisGroupMap_absoluteGaloisGroupMap {M : Type*} [Field M] [Algebra K M]
    [Algebra L M] (τ' : SeparableClosure L →ₐ[L] SeparableClosure M)
    (τ'' : SeparableClosure K →ₐ[K] SeparableClosure M) (hτ : ∀ x, τ'' x = τ' (τ x))
    (g : AbsoluteGaloisGroup M) :
    absoluteGaloisGroupMap τ (absoluteGaloisGroupMap τ' g) = absoluteGaloisGroupMap τ'' g := by
  refine ((absoluteGaloisGroupMap_eq_iff τ'').2 fun x ↦ ?_).symm
  rw [hτ, hτ, absoluteGaloisGroupMap_commutes, absoluteGaloisGroupMap_commutes]

/-! ### Mathlib's map along algebraic closures -/

section MapOfAlgebra

variable (K L) [Algebra (AlgebraicClosure K) (AlgebraicClosure L)]
  [IsScalarTower K (AlgebraicClosure K) (AlgebraicClosure L)]

/-- `Field.absoluteGaloisGroup.mapOfAlgebra K L g` is intertwined with `g` by the embedding of
algebraic closures `Kᵃˡᵍ → Lᵃˡᵍ`.

The coercions to functions carry their type arguments explicitly because
`Field.absoluteGaloisGroup` is a plain definition. -/
theorem absoluteGaloisGroup_mapOfAlgebra_commutes (g : Field.absoluteGaloisGroup L)
    (x : AlgebraicClosure K) :
    algebraMap (AlgebraicClosure K) (AlgebraicClosure L)
        (DFunLike.coe (F := Gal(AlgebraicClosure K/K))
          (Field.absoluteGaloisGroup.mapOfAlgebra K L g) x) =
      DFunLike.coe (F := Gal(AlgebraicClosure L/L)) g
        (algebraMap (AlgebraicClosure K) (AlgebraicClosure L) x) :=
  AlgEquiv.restrictNormal_commutes _ _ x

variable {K L} in
/-- **Along an isomorphism of fields the map of absolute Galois groups is bijective.** If
`algebraMap K L` is bijective, the embedding `Kᵃˡᵍ → Lᵃˡᵍ` is onto, since `Lᵃˡᵍ` is algebraic over
`K` and `Kᵃˡᵍ` is algebraically closed, and conjugation by it inverts
`Field.absoluteGaloisGroup.mapOfAlgebra K L`. -/
theorem bijective_absoluteGaloisGroup_mapOfAlgebra (h : Function.Bijective (algebraMap K L)) :
    Function.Bijective (Field.absoluteGaloisGroup.mapOfAlgebra K L) := by
  let φ := algebraMap (AlgebraicClosure K) (AlgebraicClosure L)
  have : Algebra.IsIntegral K L := Algebra.isIntegral_of_surjective h.2
  have : Algebra.IsIntegral K (AlgebraicClosure L) := Algebra.IsIntegral.trans L
  have : Algebra.IsIntegral (AlgebraicClosure K) (AlgebraicClosure L) :=
    Algebra.IsIntegral.tower_top K
  have hφ : Function.Bijective φ := IsAlgClosed.algebraMap_bijective_of_isIntegral
  refine ⟨fun g₁ g₂ hg ↦ AlgEquiv.ext fun y ↦ ?_, fun τ ↦ ?_⟩
  · obtain ⟨x, rfl⟩ := hφ.2 y
    rw [← absoluteGaloisGroup_mapOfAlgebra_commutes, ← absoluteGaloisGroup_mapOfAlgebra_commutes,
      hg]
  · -- `φ` is an isomorphism over `K`, and conjugating `τ` by it gives the preimage of `τ`; it is
    -- `L`-linear because `L` is the image of `K`.
    let E : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure L :=
      AlgEquiv.ofBijective (IsScalarTower.toAlgHom K _ _) hφ
    let g : Field.absoluteGaloisGroup L :=
      AlgEquiv.ofRingEquiv (f := E.symm.trans ((τ : Gal(AlgebraicClosure K/K)).trans E))
        fun l ↦ by
          obtain ⟨k, rfl⟩ := h.2 l
          rw [← IsScalarTower.algebraMap_apply]
          exact AlgEquiv.commutes _ k
    refine ⟨g, AlgEquiv.ext fun x ↦ hφ.1 ?_⟩
    rw [absoluteGaloisGroup_mapOfAlgebra_commutes]
    -- By construction `g (φ x)` is `E (τ (E.symm (E x)))`, and `E` is `φ`.
    exact congrArg E ((τ : Gal(AlgebraicClosure K/K)).congr_arg (E.symm_apply_apply x))

end MapOfAlgebra

section Isomorphism

omit [Algebra K L]

/-- **Along a bijective ring homomorphism the map of absolute Galois groups is bijective**, for
any choice of embedding of algebraic closures made by `Field.absoluteGaloisGroup.map`. -/
theorem bijective_absoluteGaloisGroup_map {f : K →+* L} (hf : Function.Bijective f) :
    Function.Bijective (Field.absoluteGaloisGroup.map f) :=
  letI := f.toAlgebra
  letI : Algebra (AlgebraicClosure K) (AlgebraicClosure L) :=
    (IsAlgClosed.lift : AlgebraicClosure K →ₐ[K] AlgebraicClosure L).toAlgebra
  bijective_absoluteGaloisGroup_mapOfAlgebra hf

/-- **The isomorphism of absolute Galois groups induced by an isomorphism of fields**
`e : K ≃+* L`: Mathlib's continuous map `Field.absoluteGaloisGroup.map e : G_L → G_K`, which is
bijective (`bijective_absoluteGaloisGroup_map`) and hence a homeomorphism, as `G_L` is compact
and `G_K` is Hausdorff. Like `Field.absoluteGaloisGroup.map`, it goes from `G_L` to `G_K`, and it
depends on the embedding of algebraic closures over `e` chosen by `Field.absoluteGaloisGroup.map`.
-/
def absoluteGaloisGroupMapEquiv (e : K ≃+* L) :
    Field.absoluteGaloisGroup L ≃ₜ* Field.absoluteGaloisGroup K where
  toMulEquiv := MulEquiv.ofBijective (Field.absoluteGaloisGroup.map e.toRingHom)
    (bijective_absoluteGaloisGroup_map e.bijective)
  continuous_toFun := (Field.absoluteGaloisGroup.map e.toRingHom).continuous
  continuous_invFun := Continuous.continuous_symm_of_equiv_compact_to_t2
    (f := (MulEquiv.ofBijective (Field.absoluteGaloisGroup.map e.toRingHom)
      (bijective_absoluteGaloisGroup_map e.bijective)).toEquiv)
    (Field.absoluteGaloisGroup.map e.toRingHom).continuous

/-- `absoluteGaloisGroupMapEquiv e` is Mathlib's map `Field.absoluteGaloisGroup.map e`. -/
@[simp]
theorem absoluteGaloisGroupMapEquiv_apply (e : K ≃+* L) (g : Field.absoluteGaloisGroup L) :
    absoluteGaloisGroupMapEquiv e g = Field.absoluteGaloisGroup.map e.toRingHom g :=
  (rfl)

end Isomorphism

end TauCeti
