/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.NoncommCoprod
public import Mathlib.NumberTheory.Padics.ProperSpace
public import TauCeti.Topology.Algebra.ContinuousMulEquiv
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Order
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicPow
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Product
public import TauCeti.Topology.Algebra.Group.Profinite.Rank
public import TauCeti.NumberTheory.Padics.RingHoms
public import Mathlib.Topology.MetricSpace.Ultra.TotallySeparated
import Mathlib.Topology.Separation.Connected

/-!
# The additive group of the p-adic integers

The additive group of `ℤ_[p]`, written multiplicatively as `Multiplicative ℤ_[p]`, is a
pro-`p` group. Its **levels** are the open normal subgroups `p ^ m ℤ_p`
(`TauCeti.padicIntLevel p m`), the kernels of the truncations `ℤ_[p] → ZMod (p ^ m)`; they have
index `p ^ m` and every open subgroup contains one of them, so every open normal quotient is a
quotient of a finite `p`-group.

The element `1 : ℤ_[p]` topologically generates this group because the integers are dense in
the `p`-adic integers. Consequently its topological generator rank is one.

The group is moreover the pro-`p` group on one generator: for every pro-`p` group `P` and
`a : P`, the `p`-adic power `l ↦ a ^ l` is the unique continuous homomorphism
`Multiplicative ℤ_[p] →ₜ* P` sending `1` to `a`. This universal property is what identifies
`Multiplicative ℤ_[p]` with the free pro-`p` group on one generator.

The powers `ℤ_[p] ^ X`, for an arbitrary index type `X`, are treated at the end: they are pro-`p`,
topologically generated by the coordinate vectors, so that a continuous homomorphism out of
`Multiplicative (X → ℤ_[p])` is determined by its values on them, and the `p`-adic power by `l` is
scalar multiplication by `l`, that is coordinatewise multiplication by `l`.

## Main results

* `TauCeti.padicIntLevel`: the level `p ^ m ℤ_p` of `Multiplicative ℤ_[p]`, as an open normal
  subgroup, with `TauCeti.mem_padicIntLevel_iff`, `TauCeti.index_padicIntLevel` and
  `TauCeti.exists_padicIntLevel_le`: it consists of the multiples of `p ^ m`, has index `p ^ m`,
  and every open subgroup contains some level.
* `TauCeti.isProP_multiplicative_padicInt`: `Multiplicative ℤ_[p]` is pro-`p`.
* `TauCeti.profiniteOrder_multiplicative_padicInt`: its supernatural order is `p ^ ∞`.
* `TauCeti.topologicallyGenerates_ofAdd_one_padicInt`: the element `1` topologically
  generates `Multiplicative ℤ_[p]`.
* `TauCeti.topologicalGeneratorRank_multiplicative_padicInt`: its topological generator rank is
  one.
* `TauCeti.IsProP.padicPowHom`: the continuous homomorphism `Multiplicative ℤ_[p] →ₜ* P` into a
  pro-`p` group `P` sending `1` to a given element, namely the `p`-adic power.
* `TauCeti.IsProP.existsUnique_continuousMonoidHom_multiplicative_padicInt`: the universal
  property, that this homomorphism is the unique one with that value at `1`.
* `TauCeti.IsProP.topologicalClosure_closure_singleton_eq_range_padicPowHom`,
  `TauCeti.IsProP.mem_topologicalClosure_closure_singleton_iff`: the closed subgroup
  topologically generated by an element is the range of its `p`-adic power map.
* `TauCeti.IsProP.exists_padicPow_mul_padicPow_eq_of_commute`: a pro-`p` group topologically
  generated by two commuting elements consists of the products of their `p`-adic powers.
* `TauCeti.toAdd_apply_multiplicative_padicInt`: a continuous endomorphism of the additive group
  of `ℤ_[p]` is multiplication by its value at `1`.
* `TauCeti.isProP_multiplicative_pi_padicInt`,
  `TauCeti.topologicallyGenerates_ofAdd_single_padicInt`,
  `TauCeti.isTopologicallyFinitelyGenerated_multiplicative_pi_padicInt`,
  `TauCeti.continuousMonoidHom_ext_multiplicative_pi_padicInt`: `ℤ_[p] ^ X` is pro-`p`, is
  topologically generated by the coordinate vectors (so is topologically finitely generated for
  finite `X`), and continuous homomorphisms out of it are determined by their values on them.
* `TauCeti.IsProP.padicPow_ofAdd_pi`, `TauCeti.IsProP.map_padicPow_pi`: in `ℤ_[p] ^ X` the
  `p`-adic power by `l` is scalar multiplication by `l`, also after a continuous homomorphism.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Sections 2.2 and 4.3.
-/

public section

namespace TauCeti

section Level

variable (p : ℕ) [Fact p.Prime] (m : ℕ)

/-- Reduction modulo `p ^ m`, as a homomorphism
`Multiplicative ℤ_[p] →* Multiplicative (ZMod (p ^ m))` of the additive groups written
multiplicatively, is continuous. -/
theorem continuous_toMultiplicative_toZModPow :
    Continuous (PadicInt.toZModPow (p := p) m).toAddMonoidHom.toMultiplicative := by
  rw [AddMonoidHom.coe_toMultiplicative]
  exact continuous_ofAdd.comp ((PadicInt.continuous_toZModPow m).comp continuous_toAdd)

/-- Reduction modulo `p ^ m`, as a homomorphism
`Multiplicative ℤ_[p] →* Multiplicative (ZMod (p ^ m))` of the additive groups written
multiplicatively, is surjective. -/
theorem surjective_toMultiplicative_toZModPow :
    Function.Surjective (PadicInt.toZModPow (p := p) m).toAddMonoidHom.toMultiplicative := by
  intro y
  obtain ⟨x, hx⟩ := ZMod.ringHom_surjective (PadicInt.toZModPow (p := p) m) y.toAdd
  exact ⟨Multiplicative.ofAdd x, by simp [hx]⟩

/-- **The level `p ^ m` of `ℤ_p`.** The open normal subgroup `p ^ m ℤ_p` of `Multiplicative ℤ_[p]`,
the kernel of reduction modulo `p ^ m`. It consists of the multiples of `p ^ m`
(`mem_padicIntLevel_iff`), has index `p ^ m` (`index_padicIntLevel`), and the levels are cofinal
among the open subgroups (`exists_padicIntLevel_le`). -/
noncomputable def padicIntLevel : OpenNormalSubgroup (Multiplicative ℤ_[p]) :=
  (openNormalSubgroupBot (Multiplicative (ZMod (p ^ m)))).comap
    (PadicInt.toZModPow m).toAddMonoidHom.toMultiplicative
    (continuous_toMultiplicative_toZModPow p m)

/-- The underlying subgroup of the level `p ^ m` is the kernel of reduction modulo `p ^ m`. -/
theorem padicIntLevel_toSubgroup :
    (padicIntLevel p m).toSubgroup =
      ((PadicInt.toZModPow (p := p) m).toAddMonoidHom.toMultiplicative).ker := by
  rw [padicIntLevel, OpenNormalSubgroup.toSubgroup_comap, openNormalSubgroupBot_toSubgroup,
    MonoidHom.comap_bot]

/-- The level `p ^ m` of `ℤ_p` consists of the multiples of `p ^ m`. -/
@[simp]
theorem mem_padicIntLevel_iff {x : Multiplicative ℤ_[p]} :
    x ∈ padicIntLevel p m ↔ (p : ℤ_[p]) ^ m ∣ x.toAdd := by
  rw [padicIntLevel, OpenNormalSubgroup.mem_comap, mem_openNormalSubgroupBot,
    ← Ideal.mem_span_singleton, ← PadicInt.ker_toZModPow, RingHom.mem_ker]
  simp only [AddMonoidHom.coe_toMultiplicative, Function.comp_apply, ofAdd_eq_one,
    RingHom.toAddMonoidHom_eq_coe, AddMonoidHom.coe_ofClass]

/-- The level `p ^ m` of `ℤ_p` has index `p ^ m`. -/
@[simp]
theorem index_padicIntLevel : (padicIntLevel p m).toSubgroup.index = p ^ m := by
  rw [padicIntLevel, OpenNormalSubgroup.toSubgroup_comap, openNormalSubgroupBot_toSubgroup,
    Subgroup.index_comap_of_surjective ⊥ (surjective_toMultiplicative_toZModPow p m),
    Subgroup.index_bot, Nat.card_congr Multiplicative.toAdd, Nat.card_zmod]

/-- **The levels of `ℤ_p` are cofinal.** Every open subgroup of `Multiplicative ℤ_[p]` contains the
level `p ^ m ℤ_p` for some `m`: an open subgroup contains a ball around `1`, and the balls around
`1` are the levels. -/
theorem exists_padicIntLevel_le (U : OpenSubgroup (Multiplicative ℤ_[p])) :
    ∃ m, (padicIntLevel p m).toOpenSubgroup ≤ U := by
  obtain ⟨ε, hε, hεU⟩ := Metric.mem_nhds_iff.mp (U.isOpen.mem_nhds U.one_mem)
  obtain ⟨m, hm⟩ := PadicInt.exists_pow_neg_lt p hε
  refine ⟨m, fun x hx ↦ hεU ?_⟩
  have hx' : ‖x.toAdd‖ ≤ (p : ℝ) ^ (-m : ℤ) :=
    (PadicInt.norm_le_pow_iff_mem_span_pow _ m).mpr
      (Ideal.mem_span_singleton.mpr ((mem_padicIntLevel_iff p m).mp hx))
  simpa [Metric.mem_ball, dist_zero_right] using hx'.trans_lt hm

end Level

/-- The additive group of the `p`-adic integers, written multiplicatively, is pro-`p`: every open
normal subgroup contains a level `p ^ m ℤ_p`, whose quotient is `ℤ ⧸ p ^ m`. -/
theorem isProP_multiplicative_padicInt (p : ℕ) [Fact p.Prime] :
    IsProP p (Multiplicative ℤ_[p]) := by
  rw [isProP_iff]
  intro U
  obtain ⟨m, hm⟩ := exists_padicIntLevel_le p U.toOpenSubgroup
  have htarget : IsPGroup p (Multiplicative (ZMod (p ^ m))) :=
    IsPGroup.of_card (n := m) (by simp)
  have hsource : IsPGroup p (Multiplicative ℤ_[p] ⧸ (padicIntLevel p m).toSubgroup) :=
    htarget.of_equiv ((QuotientGroup.quotientMulEquivOfEq (padicIntLevel_toSubgroup p m)).trans
      (QuotientGroup.quotientKerEquivOfSurjective _
        (surjective_toMultiplicative_toZModPow p m))).symm
  exact hsource.of_surjective (QuotientGroup.map _ U.toSubgroup (MonoidHom.id _) fun x hx ↦ hm hx)
    (QuotientGroup.map_surjective_of_surjective _ _ _
      ((QuotientGroup.mk'_surjective U.toSubgroup).comp Function.surjective_id) _)

/-- **The supernatural order of `ℤ_p` is `p ^ ∞`.** The additive group of the `p`-adic integers is
pro-`p`, so no other prime divides its order, and its quotient by the level `p ^ m ℤ_p` has order
`p ^ m` for every `m`. -/
@[simp]
theorem profiniteOrder_multiplicative_padicInt (p : ℕ) [Fact p.Prime] :
    profiniteOrder (Multiplicative ℤ_[p]) =
      Supernatural.primePower (⟨p, Fact.out⟩ : Nat.Primes) ⊤ := by
  refine le_antisymm
    (isProP_iff_profiniteOrder_le_primePower.mp (isProP_multiplicative_padicInt p))
    ((Supernatural.primePower_le_iff _ _ _).mpr (top_le_iff.mpr ?_))
  exact (profiniteOrder_apply_eq_top_iff _ _).mpr fun m ↦
    ⟨padicIntLevel p m, by rw [← Subgroup.index_eq_card, index_padicIntLevel]⟩

/-- The element `1 : ℤ_[p]` topologically generates the additive group of the `p`-adic
integers. -/
@[simp]
theorem topologicallyGenerates_ofAdd_one_padicInt (p : ℕ) [Fact p.Prime] :
    (Subgroup.closure ({Multiplicative.ofAdd (1 : ℤ_[p])} : Set _)).topologicalClosure = ⊤ := by
  let f : Multiplicative ℤ →* Multiplicative ℤ_[p] :=
    (Int.castAddHom ℤ_[p]).toMultiplicative
  have hclosure :
      Subgroup.closure ({Multiplicative.ofAdd (1 : ℤ)} : Set (Multiplicative ℤ)) = ⊤ := by
    apply top_unique
    intro x _
    rw [Subgroup.mem_closure_singleton]
    refine ⟨x.toAdd, ?_⟩
    cases x
    rw [← ofAdd_zsmul]
    simp
  have hgen :
      (Subgroup.closure
        ({Multiplicative.ofAdd (1 : ℤ)} : Set (Multiplicative ℤ))).topologicalClosure = ⊤ := by
    rw [hclosure]
    exact top_unique (Subgroup.le_topologicalClosure ⊤)
  have hf : Continuous f := continuous_of_discreteTopology
  have hdense : DenseRange f := PadicInt.denseRange_intCast
  convert topologicalClosure_closure_image_eq_top hgen hf hdense using 1
  simp only [Set.image_singleton, f, AddMonoidHom.coe_toMultiplicative,
    Function.comp_apply, toAdd_ofAdd, Int.coe_castAddHom, Int.cast_one]

/-- The additive group of the `p`-adic integers is topologically finitely generated. -/
theorem isTopologicallyFinitelyGenerated_multiplicative_padicInt (p : ℕ) [Fact p.Prime] :
    IsTopologicallyFinitelyGenerated (Multiplicative ℤ_[p]) :=
  (Set.finite_singleton (Multiplicative.ofAdd (1 : ℤ_[p]))).isTopologicallyFinitelyGenerated
    (topologicallyGenerates_ofAdd_one_padicInt p)

/-- The natural-number topological generator rank of the additive group of `ℤ_[p]` is one. -/
@[simp]
theorem topologicalGeneratorRankNat_multiplicative_padicInt (p : ℕ) [Fact p.Prime] :
    topologicalGeneratorRankNat (Multiplicative ℤ_[p])
      (isTopologicallyFinitelyGenerated_multiplicative_padicInt p) = 1 := by
  let hfg := isTopologicallyFinitelyGenerated_multiplicative_padicInt p
  have hle : topologicalGeneratorRankNat (Multiplicative ℤ_[p]) hfg ≤ 1 := by
    simpa using topologicalGeneratorRankNat_le hfg
      (s := {Multiplicative.ofAdd (1 : ℤ_[p])})
      (by simp)
  have hne : topologicalGeneratorRankNat (Multiplicative ℤ_[p]) hfg ≠ 0 := by
    intro hzero
    have hrank : topologicalGeneratorRank (Multiplicative ℤ_[p]) = 0 := by
      rw [← topologicalGeneratorRankNat_eq_topologicalGeneratorRank hfg, hzero]
      simp
    have hsub := topologicalGeneratorRank_eq_zero_iff.mp hrank
    exact zero_ne_one (congrArg Multiplicative.toAdd
      (hsub.elim (Multiplicative.ofAdd (0 : ℤ_[p])) (Multiplicative.ofAdd 1)))
  omega

/-- The cardinal-valued topological generator rank of the additive group of `ℤ_[p]` is one. -/
@[simp]
theorem topologicalGeneratorRank_multiplicative_padicInt (p : ℕ) [Fact p.Prime] :
    topologicalGeneratorRank (Multiplicative ℤ_[p]) = 1 := by
  rw [← topologicalGeneratorRankNat_eq_topologicalGeneratorRank
    (isTopologicallyFinitelyGenerated_multiplicative_padicInt p),
    topologicalGeneratorRankNat_multiplicative_padicInt]
  simp

/-! ## The universal property of `ℤ_p` among pro-`p` groups -/

/-- Two continuous homomorphisms out of the additive group of the `p`-adic integers into a
Hausdorff monoid that agree at `1` are equal. -/
@[ext]
theorem continuousMonoidHom_ext_multiplicative_padicInt {p : ℕ} [Fact p.Prime] {Q : Type*}
    [Monoid Q] [TopologicalSpace Q] [T2Space Q] {f g : Multiplicative ℤ_[p] →ₜ* Q}
    (h : f (Multiplicative.ofAdd 1) = g (Multiplicative.ofAdd 1)) : f = g :=
  ContinuousMonoidHom.toMonoidHom_injective
    (MonoidHom.eq_of_eqOn_of_topologicalClosure_closure_eq_top
      (topologicallyGenerates_ofAdd_one_padicInt p) f.continuous g.continuous
      (Set.eqOn_singleton.mpr h))

namespace IsProP

variable {p : ℕ} [Fact p.Prime] {P : Type*} [Group P] [TopologicalSpace P]
  [IsTopologicalGroup P] [CompactSpace P] [TotallyDisconnectedSpace P]

/-- **The `p`-adic power as a homomorphism out of `ℤ_p`.** For an element `a` of a pro-`p`
group, `hP.padicPowHom a` is the continuous homomorphism `Multiplicative ℤ_[p] →ₜ* P` sending
`l` to the `p`-adic power `a ^ l`, so `1 ↦ a`. It is the unique continuous homomorphism with
that value at `1`, by `TauCeti.IsProP.padicPowHom_unique`. -/
noncomputable def padicPowHom (hP : IsProP p P) (a : P) : Multiplicative ℤ_[p] →ₜ* P where
  toFun l := hP.padicPow a l.toAdd
  map_one' := by simp
  map_mul' l l' := by simp
  continuous_toFun :=
    hP.continuous_padicPow.comp (continuous_toAdd.prodMk continuous_const)

/-- The homomorphism `TauCeti.IsProP.padicPowHom` evaluates as the `p`-adic power. -/
@[simp]
theorem padicPowHom_apply (hP : IsProP p P) (a : P) (l : Multiplicative ℤ_[p]) :
    hP.padicPowHom a l = hP.padicPow a l.toAdd :=
  (rfl)

/-- The homomorphism `TauCeti.IsProP.padicPowHom a` sends `1` to `a`. -/
theorem padicPowHom_ofAdd_one (hP : IsProP p P) (a : P) :
    hP.padicPowHom a (Multiplicative.ofAdd 1) = a := by
  simp

/-- A continuous homomorphism from the additive group of `ℤ_[p]` into a pro-`p` group is the
`p`-adic power map of its value at `1`. -/
theorem eq_padicPowHom (hP : IsProP p P) (f : Multiplicative ℤ_[p] →ₜ* P) :
    f = hP.padicPowHom (f (Multiplicative.ofAdd 1)) :=
  continuousMonoidHom_ext_multiplicative_padicInt (by simp)

/-- A continuous homomorphism from the additive group of `ℤ_[p]` into a pro-`p` group sending
`1` to `a` is `TauCeti.IsProP.padicPowHom a`. -/
theorem padicPowHom_unique (hP : IsProP p P) {a : P} (f : Multiplicative ℤ_[p] →ₜ* P)
    (hf : f (Multiplicative.ofAdd 1) = a) : f = hP.padicPowHom a :=
  continuousMonoidHom_ext_multiplicative_padicInt (by simp [hf])

/-- **The universal property of `ℤ_p` among pro-`p` groups.** For every element `a` of a pro-`p`
group there is a unique continuous homomorphism from the additive group of `ℤ_[p]` sending `1`
to `a`. -/
theorem existsUnique_continuousMonoidHom_multiplicative_padicInt (hP : IsProP p P) (a : P) :
    ∃! f : Multiplicative ℤ_[p] →ₜ* P, f (Multiplicative.ofAdd 1) = a :=
  ⟨hP.padicPowHom a, hP.padicPowHom_ofAdd_one a, fun f hf ↦ hP.padicPowHom_unique f hf⟩

/-- The homomorphism `TauCeti.IsProP.padicPowHom` is natural in the target. -/
@[simp]
theorem comp_padicPowHom {Q : Type*} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q]
    [CompactSpace Q] [TotallyDisconnectedSpace Q] (hP : IsProP p P) (hQ : IsProP p Q)
    (g : P →ₜ* Q) (a : P) : g.comp (hP.padicPowHom a) = hQ.padicPowHom (g a) :=
  continuousMonoidHom_ext_multiplicative_padicInt (by simp)

/-- **The closed subgroup topologically generated by an element `a` of a pro-`p` group is the
range of its `p`-adic power map** `l ↦ a ^ l`. -/
theorem topologicalClosure_closure_singleton_eq_range_padicPowHom (hP : IsProP p P) (a : P) :
    (Subgroup.closure ({a} : Set P)).topologicalClosure =
      (hP.padicPowHom a : Multiplicative ℤ_[p] →* P).range := by
  -- The range is compact, hence closed, and contains `a`; conversely every `p`-adic power of `a`
  -- lies in every closed subgroup containing `a`.
  refine le_antisymm (Subgroup.topologicalClosure_minimal _ ?_ ?_) ?_
  · rw [Subgroup.closure_le, Set.singleton_subset_iff, SetLike.mem_coe, MonoidHom.mem_range]
    exact ⟨Multiplicative.ofAdd 1, by rw [MonoidHom.coe_ofClass, hP.padicPowHom_ofAdd_one]⟩
  · rw [MonoidHom.coe_range, MonoidHom.coe_ofClass]
    exact (isCompact_range (map_continuous (hP.padicPowHom a))).isClosed
  · rintro _ ⟨l, rfl⟩
    rw [MonoidHom.coe_ofClass, hP.padicPowHom_apply]
    simpa only [closedZpowers_def, Subgroup.zpowers_eq_closure] using
      hP.padicPow_mem_closedZpowers a l.toAdd

/-- An element of a pro-`p` group lies in the closed subgroup topologically generated by `a`
exactly when it is a `p`-adic power of `a`. -/
theorem mem_topologicalClosure_closure_singleton_iff (hP : IsProP p P) {a x : P} :
    x ∈ (Subgroup.closure ({a} : Set P)).topologicalClosure ↔
      ∃ l : ℤ_[p], hP.padicPow a l = x := by
  rw [hP.topologicalClosure_closure_singleton_eq_range_padicPowHom, MonoidHom.mem_range,
    MonoidHom.coe_ofClass]
  exact ⟨fun ⟨l, hl⟩ ↦ ⟨l.toAdd, by rwa [hP.padicPowHom_apply] at hl⟩,
    fun ⟨l, hl⟩ ↦ ⟨Multiplicative.ofAdd l, by rwa [hP.padicPowHom_apply, toAdd_ofAdd]⟩⟩

/-- **A pro-`p` group topologically generated by two commuting elements consists of the products
of their `p`-adic powers**: every element is `a ^ s * b ^ t` for some `s t : ℤ_[p]`. -/
theorem exists_padicPow_mul_padicPow_eq_of_commute (hP : IsProP p P) {a b : P}
    (hab : Commute a b) (hgen : (Subgroup.closure {a, b}).topologicalClosure = ⊤) (g : P) :
    ∃ s t : ℤ_[p], hP.padicPow a s * hP.padicPow b t = g := by
  let ψ : Multiplicative ℤ_[p] × Multiplicative ℤ_[p] →* P :=
    (hP.padicPowHom a).toMonoidHom.noncommCoprod (hP.padicPowHom b).toMonoidHom
      fun s t ↦ by
        simpa only [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass,
          IsProP.padicPowHom_apply] using hP.commute_padicPow hab s.toAdd t.toAdd
  have hψ : Continuous ψ :=
    ((map_continuous (hP.padicPowHom a)).comp continuous_fst).mul
      ((map_continuous (hP.padicPowHom b)).comp continuous_snd)
  have hle : (Subgroup.closure {a, b}).topologicalClosure ≤ ψ.range := by
    refine Subgroup.topologicalClosure_minimal _ ((Subgroup.closure_le _).2 ?_)
      (isCompact_range hψ).isClosed
    rintro x (rfl | rfl)
    · exact ⟨(Multiplicative.ofAdd 1, 1), by simp [ψ]⟩
    · exact ⟨(1, Multiplicative.ofAdd 1), by simp [ψ]⟩
  obtain ⟨⟨s, t⟩, hst⟩ := hle (hgen ▸ Subgroup.mem_top g)
  refine ⟨s.toAdd, t.toAdd, ?_⟩
  simpa only [ψ, MonoidHom.noncommCoprod_apply, ContinuousMonoidHom.coe_toMonoidHom,
    MonoidHom.coe_ofClass, IsProP.padicPowHom_apply] using hst

/-- In the additive group of `ℤ_[p]`, the `p`-adic power of `1` by `l` is `l` itself. -/
@[simp]
theorem padicPow_ofAdd_one_padicInt (p : ℕ) [Fact p.Prime] (l : ℤ_[p]) :
    (isProP_multiplicative_padicInt p).padicPow (Multiplicative.ofAdd 1) l =
      Multiplicative.ofAdd l :=
  ((isProP_multiplicative_padicInt p).eq_padicPow_of_continuous
    (f := fun l : ℤ_[p] ↦ Multiplicative.ofAdd l) continuous_ofAdd
    (fun k ↦ by rw [← ofAdd_nsmul, nsmul_one]) l).symm

/-- The `p`-adic power homomorphism of `1` in the additive group of `ℤ_[p]` is the identity. -/
@[simp]
theorem padicPowHom_ofAdd_one_padicInt (p : ℕ) [Fact p.Prime] :
    (isProP_multiplicative_padicInt p).padicPowHom (Multiplicative.ofAdd 1) =
      ContinuousMonoidHom.id (Multiplicative ℤ_[p]) :=
  continuousMonoidHom_ext_multiplicative_padicInt (by simp)

end IsProP

/-- **A continuous endomorphism of the additive group of `ℤ_[p]` is multiplication by its value
at `1`.** -/
theorem toAdd_apply_multiplicative_padicInt {p : ℕ} [Fact p.Prime]
    (f : Multiplicative ℤ_[p] →ₜ* Multiplicative ℤ_[p]) (x : Multiplicative ℤ_[p]) :
    (f x).toAdd = (f (Multiplicative.ofAdd 1)).toAdd * x.toAdd := by
  have hZ := isProP_multiplicative_padicInt p
  have h := hZ.padicPow_ofAdd_apply_one
    (AddMonoidHom.mulLeft (f (Multiplicative.ofAdd 1)).toAdd) (continuous_const.mul continuous_id)
    x.toAdd
  simp only [AddMonoidHom.coe_mulLeft, mul_one, ofAdd_toAdd] at h
  have hf := DFunLike.congr_fun (hZ.eq_padicPowHom f) x
  rw [hZ.padicPowHom_apply, h] at hf
  rw [hf, toAdd_ofAdd]

/-! ## Powers of `ℤ_p` -/

section Pi

open Multiplicative

variable (p : ℕ) [Fact p.Prime] (X : Type*)

/-- The additive group `ℤ_[p] ^ X` is pro-`p`. -/
theorem isProP_multiplicative_pi_padicInt : IsProP p (Multiplicative (X → ℤ_[p])) :=
  (IsProP.pi fun _ : X ↦ isProP_multiplicative_padicInt p).of_equiv
    (ContinuousMulEquiv.piMultiplicative fun _ : X ↦ ℤ_[p]).symm

/-- In `ℤ_[p] ^ X` the `p`-adic power of a vector `v` by `l` is `l • v`. -/
@[simp]
theorem IsProP.padicPow_ofAdd_pi (v : X → ℤ_[p]) (l : ℤ_[p]) :
    (isProP_multiplicative_pi_padicInt p X).padicPow (ofAdd v) l = ofAdd (l • v) := by
  have h := (isProP_multiplicative_pi_padicInt p X).padicPow_ofAdd_apply_one
    (LinearMap.toSpanSingleton ℤ_[p] (X → ℤ_[p]) v).toAddMonoidHom
    (continuous_id.smul continuous_const) l
  simpa using h

variable {p X} in
/-- A continuous homomorphism from a pro-`p` group to `ℤ_[p] ^ X` carries the `p`-adic power by
`l` to the scalar multiple by `l`. -/
theorem IsProP.map_padicPow_pi {P : Type*} [Group P] [TopologicalSpace P] [IsTopologicalGroup P]
    [CompactSpace P] [TotallyDisconnectedSpace P] (hP : IsProP p P)
    (f : P →ₜ* Multiplicative (X → ℤ_[p])) (y : P) (l : ℤ_[p]) :
    f (hP.padicPow y l) = ofAdd (l • (f y).toAdd) := by
  have h := hP.map_padicPow (isProP_multiplicative_pi_padicInt p X) (f : P →* _) f.continuous y l
  rwa [MonoidHom.coe_ofClass, ← ofAdd_toAdd (f y), padicPow_ofAdd_pi] at h

variable [DecidableEq X]

/-- The coordinate vectors topologically generate the additive group `ℤ_[p] ^ X`: the closed
subgroup they generate contains every vector supported at one coordinate, because the integers
are dense in `ℤ_[p]`, hence every finitely supported vector, and these are dense in the product
topology. -/
theorem topologicallyGenerates_ofAdd_single_padicInt :
    (Subgroup.closure
      (Set.range fun x : X ↦ ofAdd (Pi.single x (1 : ℤ_[p])))).topologicalClosure = ⊤ := by
  set S := Subgroup.closure (Set.range fun x : X ↦ ofAdd (Pi.single x (1 : ℤ_[p])))
  -- Every vector supported at one coordinate lies in the closure of `S`: the integer multiples of
  -- a coordinate vector lie in `S`, and the integers are dense.
  have hsingle : ∀ (x : X) (a : ℤ_[p]), ofAdd (Pi.single x a) ∈ S.topologicalClosure := by
    intro x a
    have hc : Continuous fun a : ℤ_[p] ↦ ofAdd (Pi.single x a : X → ℤ_[p]) :=
      continuous_ofAdd.comp (continuous_single (A := fun _ : X ↦ ℤ_[p]) x)
    rw [← SetLike.mem_coe, Subgroup.topologicalClosure_coe]
    refine map_mem_closure (f := fun a : ℤ_[p] ↦ ofAdd (Pi.single x a : X → ℤ_[p])) hc
      (PadicInt.denseRange_intCast a) ?_
    rintro _ ⟨n, rfl⟩
    have h : (Pi.single x (n : ℤ_[p]) : X → ℤ_[p]) = n • Pi.single x 1 := by
      ext y
      simp [Pi.single_apply]
    beta_reduce
    rw [h, ofAdd_zsmul]
    exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_range_self x)) _
  -- Every vector is the limit, along the finite subsets of `X`, of its finitely supported
  -- truncations, which lie in the closure of `S`.
  refine eq_top_iff.mpr fun v _ ↦ S.isClosed_topologicalClosure.mem_of_tendsto
    (f := fun s : Finset X ↦ ofAdd (∑ x ∈ s, Pi.single x (v.toAdd x))) (b := Filter.atTop) ?_
    (Filter.Eventually.of_forall fun s ↦ ?_)
  · refine (continuous_ofAdd.tendsto v.toAdd).comp (tendsto_pi_nhds.mpr fun y ↦ ?_)
    refine tendsto_const_nhds.congr' ((Filter.eventually_ge_atTop {y}).mono fun s hs ↦ ?_)
    simp [Finset.singleton_subset_iff.mp hs]
  · rw [ofAdd_sum]
    exact Subgroup.prod_mem _ fun x _ ↦ hsingle x _

omit [DecidableEq X] in
/-- **`ℤ_p^X` is topologically finitely generated** for finite `X`, by the coordinate vectors. -/
theorem isTopologicallyFinitelyGenerated_multiplicative_pi_padicInt [Finite X] :
    IsTopologicallyFinitelyGenerated (Multiplicative (X → ℤ_[p])) := by
  classical
  exact (Set.finite_range fun x : X ↦
    ofAdd (Pi.single x (1 : ℤ_[p]))).isTopologicallyFinitelyGenerated
      (topologicallyGenerates_ofAdd_single_padicInt p X)

/-- Two continuous homomorphisms out of the additive group `ℤ_[p] ^ X` into a Hausdorff monoid
that agree on the coordinate vectors are equal. -/
theorem continuousMonoidHom_ext_multiplicative_pi_padicInt {Q : Type*} [Monoid Q]
    [TopologicalSpace Q] [T2Space Q] {f g : Multiplicative (X → ℤ_[p]) →ₜ* Q}
    (h : ∀ x, f (ofAdd (Pi.single x 1)) = g (ofAdd (Pi.single x 1))) : f = g :=
  ContinuousMonoidHom.toMonoidHom_injective
    (MonoidHom.eq_of_eqOn_of_topologicalClosure_closure_eq_top
      (topologicallyGenerates_ofAdd_single_padicInt p X) f.continuous g.continuous
      (by rintro _ ⟨x, rfl⟩; exact h x))

end Pi

end TauCeti
