/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Sl2.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.SquareZeroCoroot
public import TauCeti.Algebra.Lie.Symplectic.StandardCarrier.Scheme

/-!
# The standard type-`C` carrier is generated by its root subgroups

`TauCeti.SpStd.groupScheme n` is defined as the closed subgroup scheme of `GL_(2n+2)` over `ℤ`
generated jointly by the numbered positive and negative simple-root subgroups of type `C_(n+1)` and
by the weight torus of the standard lattice. This file shows that the weight torus is redundant:
the carrier is already the subgroup scheme generated by the root subgroups alone, the two defining
Hopf ideals agree, and a homomorphism out of the carrier is determined by its restrictions to the
root subgroups.

The long simple root `2 e_(n+1)` of `C_(n+1)` is the obstruction to the coprimality criterion for
coroot values in the group generated by the root subgroups: its row of the Cartan
matrix is `(0, …, 0, -2, 2)`, so the values of that root on the weight torus are the squares, not
all units. What is used instead is that every numbered root generator squares to zero in the
standard representation, whose weights `± e_k` pair with every simple coroot to `1`, `0` or `-1`;
the square-zero rank-one identity then reaches each coroot value at an arbitrary unit.

## Main results

* `TauCeti.SpStd.isSl2Triple_rep_rootGenerator`: the represented generators at a Bourbaki node form
  an `sl₂` triple.
* `TauCeti.SpStd.weightTorusSubgroup_le_elementarySubgroup`: over every commutative ring the
  represented weight torus lies in the group generated by the root subgroups.
* `TauCeti.SpStd.definingIdeal_eq_kostantGeneratedDefiningIdeal` and
  `TauCeti.SpStd.groupScheme_eq_kostantGeneratedGroupScheme`: the carrier is the root-generated
  group scheme.
* `TauCeti.SpStd.groupScheme_hom_ext_of_rootSubgroup`: a morphism out of the carrier is determined
  by its restrictions to the numbered root subgroups, with no hypothesis on the weight torus.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, §3.
* R. W. Carter, *Simple Groups of Lie Type*, §§6.4 and 7.1.
-/

public section

open CategoryTheory WithConv
open scoped TensorProduct

namespace TauCeti.SpStd

open TauCeti.UniversalEnvelopingAlgebra

universe v

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

variable (n : ℕ)

/-! ## The represented `sl₂` triples -/

/-- The weight of the standard basis vector `e_i` at the Bourbaki node `i` of `C_(n+1)` is one. -/
private theorem weight_inl_self (i : Fin (n + 1)) : weight n (.inl i) i = 1 := by
  rw [weight_inl, DynkinType.TypeC.weight_apply]
  simp

/-- The represented Cartan generator at a Bourbaki node is nonzero: it scales the standard basis
vector `e_i` by the weight one. -/
private theorem rep_cartanGenerator_ne_zero (i : Fin (n + 1)) :
    rep n (_root_.UniversalEnvelopingAlgebra.ι ℚ (cartanGenerator n i)) ≠ 0 := by
  intro hz
  have hwv := (isCartanWeightVector_iff (cartanGenerator n) (rep n)).1
    (isCartanWeightVector_single n (.inl i)) i
  rw [hz, weight_inl_self] at hwv
  have hcoord := congrFun hwv (Sum.inl i)
  simp at hcoord

/-- **The represented generators at a Bourbaki node form an `sl₂` triple.** This is the `sl₂` triple
of `TauCeti.SpStd.isSl2Triple_rootGenerator` carried along the standard representation. -/
theorem isSl2Triple_rep_rootGenerator (i : Fin (n + 1)) :
    _root_.IsSl2Triple (rep n (_root_.UniversalEnvelopingAlgebra.ι ℚ (cartanGenerator n i)))
      (rep n (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGenerator n (.inl i))))
      (rep n (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGenerator n (.inr i)))) := by
  have hne : ((rep n).toLieHom.comp (_root_.UniversalEnvelopingAlgebra.ι ℚ))
      (cartanGenerator n i) ≠ 0 := rep_cartanGenerator_ne_zero n i
  have h := (isSl2Triple_rootGenerator n i).map
    ((rep n).toLieHom.comp (_root_.UniversalEnvelopingAlgebra.ι ℚ)) hne
  simpa only [LieHom.comp_apply, AlgHom.toLieHom_apply] using h

/-! ## Generation of the weight torus -/

/-- Every coroot value of the standard type-`C` carrier lies in the group generated by the numbered
root subgroups, at every unit of every value ring. -/
theorem coordinateCocharacter_mem_elementarySubgroup (A : CommAlgCat.{v} ℤ) (d : Fin (n + 1))
    (u : (A : Type v)ˣ) :
    kostantCoordinateCocharacter (lattice n).toAddSubgroup (latticeBasis n) (basisWeight n) A d u ∈
      kostantElementarySubgroup (rootGenerator n) (cartanGenerator n) (rep n)
        (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
        (isNilpotent_rep_rootGenerator n) A :=
  kostantCoordinateCocharacter_mem_kostantElementarySubgroup_of_sq_eq_zero (rootGenerator n)
    (cartanGenerator n) (rep n) (lattice n).toAddSubgroup
    (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
    (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n)
    (isCartanWeightVector_latticeBasis n) (isSl2Triple_rep_rootGenerator n d)
    (pow_two_rep_rootGenerator_eq_zero n _) (pow_two_rep_rootGenerator_eq_zero n _) A u

/-- **Over every commutative ring the weight torus of the standard type-`C` carrier lies in the
group generated by its numbered root subgroups.** -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup (lattice n).toAddSubgroup (latticeBasis n) (basisWeight n) A ≤
      kostantElementarySubgroup (rootGenerator n) (cartanGenerator n) (rep n)
        (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
        (isNilpotent_rep_rootGenerator n) A :=
  kostantTorusSubgroup_le_kostantElementarySubgroup_of_forall_coordinateCocharacter
    (rootGenerator n) (cartanGenerator n) (rep n) (lattice n).toAddSubgroup
    (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
    (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n) A
    (coordinateCocharacter_mem_elementarySubgroup n A)

/-! ## Scheme-theoretic generation -/

private theorem universalWeightTorus_mem_elementarySubgroup :
    let T := (DiagonalizableGroup.coordinateRing ℤ
      (SplitTorus.characterGroup (Fin (n + 1)))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin (n + 1)))) A :=
      WithConv.toConv (AlgHom.id ℤ T)
    kostantTorusPoints (lattice n).toAddSubgroup (latticeBasis n) (basisWeight n) A
        (SplitTorus.pointsMulEquiv q) ∈
      kostantElementarySubgroup (rootGenerator n) (cartanGenerator n) (rep n)
        (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
        (isNilpotent_rep_rootGenerator n) A := by
  intro T A q
  apply weightTorusSubgroup_le_elementarySubgroup n A
  exact (kostantTorusSubgroup_eq_range _ _ _ A).ge ⟨_, rfl⟩

/-- **The full-weight standard type-`C_(n+1)` carrier is generated scheme-theoretically by its
numbered root subgroups.** Adjoining the represented weight torus does not change the integral
defining Hopf ideal. -/
theorem definingIdeal_eq_kostantGeneratedDefiningIdeal :
    definingIdeal n =
      kostantGeneratedDefiningIdeal (rootGenerator n) (cartanGenerator n) (rep n)
        (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
        (isNilpotent_rep_rootGenerator n) (latticeBasis n) := by
  rw [definingIdeal_def]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      _ _ _ _ _ _ _ (basisWeight n) (universalWeightTorus_mem_elementarySubgroup n)

/-- The full-weight standard type-`C_(n+1)` carrier is the group scheme generated by its numbered
positive and negative simple root subgroups. -/
theorem groupScheme_eq_kostantGeneratedGroupScheme :
    groupScheme n =
      kostantGeneratedGroupScheme (rootGenerator n) (cartanGenerator n) (rep n)
        (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
        (isNilpotent_rep_rootGenerator n) (latticeBasis n) :=
  kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ (basisWeight n) (universalWeightTorus_mem_elementarySubgroup n)

/-- The canonical inclusion of the root-generated standard type-`C_(n+1)` carrier into its toral
closure is an isomorphism. -/
instance isIso_kostantGeneratedToToral :
    CategoryTheory.IsIso (kostantGeneratedToToral (rootGenerator n) (cartanGenerator n) (rep n)
      (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
      (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n)) :=
  isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary _ _ _ _ _ _ _ (basisWeight n)
    (universalWeightTorus_mem_elementarySubgroup n)

/-- **A morphism out of the standard type-`C_(n+1)` carrier is determined by the numbered root
subgroups**, with no hypothesis on the weight torus. -/
@[ext high]
theorem groupScheme_hom_ext_of_rootSubgroup {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : groupScheme n ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup n k ≫ φ = rootSubgroup n k ≫ ψ) : φ = ψ := by
  refine kostantToralGroupScheme_hom_ext_of_universal_torus_mem_elementary _ _ _ _ _ _ _
    (basisWeight n) (universalWeightTorus_mem_elementarySubgroup n) φ ψ fun k => ?_
  rw [← rootSubgroup_def n k]
  exact hroot k

/-- The transported toral and root-generated presentations of the standard type-`C_(n+1)` carrier
agree over every commutative ring. -/
theorem baseChangePresentationIdeal_eq_generated (A : Type v) [CommRing A] :
    kostantToralBaseChangePresentationIdeal (rootGenerator n) (cartanGenerator n) (rep n)
        (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
        (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n) A =
      kostantGeneratedGeneralLinearBaseChangeIdeal (rootGenerator n) (cartanGenerator n) (rep n)
        (lattice n).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice n hu hv)
        (isNilpotent_rep_rootGenerator n) (latticeBasis n) A :=
  kostantToralBaseChangePresentationIdeal_eq_generated_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ (basisWeight n) (universalWeightTorus_mem_elementarySubgroup n) A

end TauCeti.SpStd
