/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Ramification
public import TauCeti.NumberTheory.NumberField.InfinitePlace.Basic
public import TauCeti.NumberTheory.Multiquadratic.Unramified.Maximality
import Mathlib.NumberTheory.NumberField.CMField
import Mathlib.RingTheory.RingHom.Unramified
import TauCeti.FieldTheory.AlgHom
import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
import TauCeti.NumberTheory.RamificationInertia.Tower

/-!
# The genus-field candidate of a real quadratic field

For positive squarefree nonsquare `d`, the prime-discriminant compositum `candidateGenusField hd`
is the narrow genus field of `ℚ(√d)`, but it can ramify at the real places. Its maximal totally
real subfield is the candidate for the ordinary genus field. This file defines that field and
relates it to the embedded quadratic base. Since the full compositum is unramified over the base
at every finite prime, its real subfield is too.

The key archimedean fact is intrinsic: an extension of a totally real field is unramified at all
infinite places exactly when it is totally real. Consequently every abelian Galois extension of
`ℚ` containing the chosen square root and unramified everywhere over the quadratic base maps into
this maximal real subfield.

The construction is classical; see F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*,
Section 2.2, and D. A. Cox, *Primes of the Form x² + ny²*, Section 6.A.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldReal`: the maximal totally real subfield of the
  prime-discriminant compositum.
* `TauCeti.Multiquadratic.candidateGenusFieldRealBaseRoot`: its chosen square root of `d`.

## Main results

* `TauCeti.Multiquadratic.candidateGenusFieldBase_le_candidateGenusFieldReal`: the real quadratic
  base lies in the real candidate.
* `TauCeti.Multiquadratic.isAbelianGalois_candidateGenusFieldReal`: the real candidate is abelian
  and Galois over `ℚ`.
* `TauCeti.Multiquadratic.isUnramifiedIn_candidateGenusFieldReal`: the real candidate is
  unramified over its quadratic base at every finite prime.
* `TauCeti.Multiquadratic.exists_algHom_candidateGenusFieldReal`: every abelian Galois extension
  of `ℚ` containing the chosen square root and unramified over the quadratic base at all places
  embeds into the real candidate.
-/

public section

open IntermediateField NumberField
open scoped NumberField

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- **The ordinary genus-field candidate of a real quadratic field.** This is the maximal totally
real subfield of the prime-discriminant compositum. It is viewed as an intermediate field over
`ℚ`; rational elements belong because every embedding into `ℂ` fixes them and hence has real
image. -/
noncomputable def candidateGenusFieldReal (hd : Squarefree d) :
    IntermediateField ℚ (candidateGenusField hd) :=
  (maximalRealSubfield (candidateGenusField hd)).toIntermediateField fun q => by
    rw [mem_maximalRealSubfield_iff]
    intro φ
    simp

/-- Membership in the real candidate means that every complex embedding has real value. -/
@[simp] theorem mem_candidateGenusFieldReal_iff (hd : Squarefree d)
    (x : candidateGenusField hd) :
    x ∈ candidateGenusFieldReal hd ↔ ∀ φ : candidateGenusField hd →+* ℂ, star (φ x) = φ x :=
  by
    unfold candidateGenusFieldReal
    rw [← mem_maximalRealSubfield_iff x]
    exact Set.ext_iff.mp (Subfield.coe_toIntermediateField (maximalRealSubfield _) _) x

/-- For positive `d`, the subfield generated by the chosen square root of `d` is totally real. -/
theorem isTotallyReal_candidateGenusFieldBase (hd : Squarefree d)
    (hpos : 0 < d) : IsTotallyReal (candidateGenusFieldBase hd) :=
  NumberField.isTotallyReal_of_sq_ratCast_of_nonneg
    (x := ((candidateGenusFieldBaseGen hd : 𝓞 (candidateGenusFieldBase hd)) :
      candidateGenusFieldBase hd)) (r := ((d : ℤ) : ℚ))
    (by
      rw [coe_candidateGenusFieldBaseGen, candidateGenusFieldBaseSqrt_sq,
        IsScalarTower.algebraMap_apply ℤ ℚ]
      norm_num)
    (adjoin_candidateGenusFieldBaseGen_eq_top hd) (by exact_mod_cast hpos.le)

/-- **The embedded base generated by the chosen root lies in the real genus-field candidate.** -/
theorem candidateGenusFieldBase_le_candidateGenusFieldReal (hd : Squarefree d)
    (hpos : 0 < d) :
    candidateGenusFieldBase hd ≤ candidateGenusFieldReal hd := by
  let _ : IsTotallyReal (candidateGenusFieldBase hd) :=
    isTotallyReal_candidateGenusFieldBase hd hpos
  exact IsTotallyReal.le_maximalRealSubfield (candidateGenusFieldBase hd).toSubfield

/-- The chosen square root of `d`, regarded as an element of the real genus-field candidate. -/
noncomputable def candidateGenusFieldRealBaseRoot (hd : Squarefree d)
    (hpos : 0 < d) :
    candidateGenusFieldReal hd :=
  ⟨candidateGenusFieldBaseRoot hd,
    candidateGenusFieldBase_le_candidateGenusFieldReal hd hpos
      (candidateGenusFieldBaseRoot_mem hd)⟩

/-- The chosen root in the real candidate coerces to
`candidateGenusFieldBaseRoot hd`. -/
@[simp] theorem coe_candidateGenusFieldRealBaseRoot (hd : Squarefree d)
    (hpos : 0 < d) :
    (candidateGenusFieldRealBaseRoot hd hpos : candidateGenusField hd) =
      candidateGenusFieldBaseRoot hd :=
  (rfl)

/-- The chosen root in the real candidate squares to `d`. -/
@[simp] theorem candidateGenusFieldRealBaseRoot_sq (hd : Squarefree d)
    (hpos : 0 < d) :
    candidateGenusFieldRealBaseRoot hd hpos ^ 2 =
      algebraMap ℚ (candidateGenusFieldReal hd) ((d : ℤ) : ℚ) := by
  apply Subtype.ext
  simpa only [IntermediateField.coe_pow, coe_candidateGenusFieldRealBaseRoot,
    IntermediateField.coe_algebraMap_apply]
    using candidateGenusFieldBaseRoot_sq hd

/-- The real genus-field candidate is totally real. -/
noncomputable instance isTotallyReal_candidateGenusFieldReal (hd : Squarefree d) :
    IsTotallyReal (candidateGenusFieldReal hd) :=
  isTotallyReal_maximalRealSubfield

/-- The real genus-field candidate is an abelian Galois extension of `ℚ`. -/
noncomputable instance isAbelianGalois_candidateGenusFieldReal (hd : Squarefree d) :
    IsAbelianGalois ℚ (candidateGenusFieldReal hd) :=
  inferInstance

/-- The quadratic subfield generated by the chosen base root inside the real candidate has degree
two over `ℚ`. -/
theorem finrank_adjoin_candidateGenusFieldRealBaseRoot (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) (hpos : 0 < d) :
    Module.finrank ℚ
      (adjoin ℚ {candidateGenusFieldRealBaseRoot hd hpos} :
        IntermediateField ℚ (candidateGenusFieldReal hd)) = 2 := by
  have hsq : candidateGenusFieldRealBaseRoot hd hpos ^ 2 ∈
      (⊥ : IntermediateField ℚ (candidateGenusFieldReal hd)) := by
    rw [candidateGenusFieldRealBaseRoot_sq]
    exact IntermediateField.algebraMap_mem _ _
  have hnot : candidateGenusFieldRealBaseRoot hd hpos ∉
      (⊥ : IntermediateField ℚ (candidateGenusFieldReal hd)) := by
    intro hmem
    rw [IntermediateField.mem_bot] at hmem
    obtain ⟨q, hq⟩ := hmem
    apply hnsq
    refine ⟨q, ?_⟩
    apply (algebraMap ℚ (candidateGenusFieldReal hd)).injective
    rw [map_mul, hq]
    simpa only [pow_two] using
      (candidateGenusFieldRealBaseRoot_sq hd hpos).symm
  have hfin :=
    (⊥ : IntermediateField ℚ (candidateGenusFieldReal hd)).finrank_sup_adjoin_simple_eq_mul_two
      hsq hnot
  rwa [bot_sup_eq, IntermediateField.finrank_bot, one_mul] at hfin

private noncomputable def candidateGenusFieldRealBaseEquiv (hd : Squarefree d)
    (hpos : 0 < d) :
    (adjoin ℚ {candidateGenusFieldRealBaseRoot hd hpos} :
      IntermediateField ℚ (candidateGenusFieldReal hd)) ≃ₐ[ℚ]
      candidateGenusFieldBase hd := by
  let B := (adjoin ℚ {candidateGenusFieldRealBaseRoot hd hpos} :
    IntermediateField ℚ (candidateGenusFieldReal hd))
  let i : candidateGenusFieldReal hd →ₐ[ℚ] candidateGenusField hd :=
    (candidateGenusFieldReal hd).val
  have hmap : B.map i = candidateGenusFieldBase hd := by
    dsimp only [B, i]
    rw [IntermediateField.adjoin_map, Set.image_singleton]
    have hroot : (candidateGenusFieldReal hd).val
        (candidateGenusFieldRealBaseRoot hd hpos) = candidateGenusFieldBaseRoot hd :=
      coe_candidateGenusFieldRealBaseRoot hd hpos
    rw [hroot, ← candidateGenusFieldBase_def]
  exact (B.equivMap i).trans (IntermediateField.equivOfEq hmap)

/-- The canonical equivalence between the two copies of the quadratic base commutes with their
inclusions into the real candidate. -/
private theorem candidateGenusFieldRealBaseEquiv_commutes (hd : Squarefree d)
    (hpos : 0 < d)
    (x : (adjoin ℚ {candidateGenusFieldRealBaseRoot hd hpos} :
      IntermediateField ℚ (candidateGenusFieldReal hd))) :
    (⟨((candidateGenusFieldRealBaseEquiv hd hpos) x : candidateGenusFieldBase hd),
      candidateGenusFieldBase_le_candidateGenusFieldReal hd hpos
        ((candidateGenusFieldRealBaseEquiv hd hpos) x).property⟩ : candidateGenusFieldReal hd) =
      (x : candidateGenusFieldReal hd) := by
  apply Subtype.ext
  simp only [candidateGenusFieldRealBaseEquiv, AlgEquiv.trans_apply,
    IntermediateField.equivOfEq_apply, IntermediateField.coe_equivMap_apply]
  rw [IntermediateField.coe_val]

/-- **The real genus-field candidate is unramified over its quadratic base at every finite
place.** This descends from finite-place unramifiedness of the full prime-discriminant compositum;
the canonical equivalence between the two copies of `ℚ(√d)` then identifies the base rings. -/
theorem isUnramifiedIn_candidateGenusFieldReal (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) (hpos : 0 < d)
    (q : Ideal (𝓞 (adjoin ℚ {candidateGenusFieldRealBaseRoot hd hpos} :
      IntermediateField ℚ (candidateGenusFieldReal hd)))) :
    Algebra.IsUnramifiedIn (𝓞 (candidateGenusFieldReal hd)) q := by
  let B := (adjoin ℚ {candidateGenusFieldRealBaseRoot hd hpos} :
    IntermediateField ℚ (candidateGenusFieldReal hd))
  let A := candidateGenusFieldBase hd
  let R := candidateGenusFieldReal hd
  let F := candidateGenusField hd
  let e : B ≃ₐ[ℚ] A := candidateGenusFieldRealBaseEquiv hd hpos
  let hAR : A ≤ R := candidateGenusFieldBase_le_candidateGenusFieldReal hd hpos
  let _ : Algebra A R := (IntermediateField.inclusion hAR).toAlgebra
  let _ : Algebra R F := R.val.toAlgebra
  let _ : IsScalarTower A R F := IsScalarTower.of_algebraMap_eq fun x => rfl
  let _ : IsScalarTower (𝓞 A) (𝓞 R) (𝓞 F) :=
    IsScalarTower.of_algebraMap_eq fun x => by apply RingOfIntegers.ext; rfl
  intro Q hQ _
  let qA : Ideal (𝓞 A) := Q.under (𝓞 A)
  have : qA.IsPrime := inferInstance
  have hurF : Algebra.IsUnramifiedIn (𝓞 F) qA :=
    isUnramifiedIn_candidateGenusField hd hnsq qA
  have : Q.LiesOver qA := inferInstance
  have hA : Algebra.IsUnramifiedAt (𝓞 A) Q :=
    TauCeti.RamificationInertia.isUnramifiedAt_of_isUnramifiedIn
      (A := 𝓞 A) (R := 𝓞 R) (S := 𝓞 F) hurF Q
  -- `IsUnramifiedAt` abbreviates precisely this localization statement.
  change Algebra.FormallyUnramified (𝓞 B) (Localization.AtPrime Q)
  rw [← RingHom.formallyUnramified_algebraMap]
  let eO : 𝓞 B ≃+* 𝓞 A := RingOfIntegers.mapRingEquiv e.toRingEquiv
  have heO : (eO : 𝓞 B →+* 𝓞 A).FormallyUnramified :=
    RingHom.FormallyUnramified.of_surjective eO.surjective
  have hA' : (algebraMap (𝓞 A) (Localization.AtPrime Q)).FormallyUnramified :=
    RingHom.formallyUnramified_algebraMap.mpr hA
  have hcomp := RingHom.FormallyUnramified.comp heO hA'
  have hmaps : (algebraMap (𝓞 A) (Localization.AtPrime Q)).comp eO =
      algebraMap (𝓞 B) (Localization.AtPrime Q) := by
    ext x
    -- Expose the two ring-of-integers inclusions so the compatibility lemma applies.
    change algebraMap (𝓞 R) (Localization.AtPrime Q) (algebraMap (𝓞 A) (𝓞 R) (eO x)) =
      algebraMap (𝓞 R) (Localization.AtPrime Q) (algebraMap (𝓞 B) (𝓞 R) x)
    apply congrArg (algebraMap (𝓞 R) (Localization.AtPrime Q))
    apply RingOfIntegers.ext
    exact candidateGenusFieldRealBaseEquiv_commutes hd hpos (x : B)
  rw [hmaps] at hcomp
  exact hcomp

/-- The real genus-field candidate is unramified at every infinite place over its embedded base.
In fact its total reality makes it unramified at infinity over every subfield. -/
theorem isUnramifiedAtInfinitePlaces_candidateGenusFieldReal (hd : Squarefree d)
    (hpos : 0 < d) :
    IsUnramifiedAtInfinitePlaces
      (adjoin ℚ {candidateGenusFieldRealBaseRoot hd hpos} :
        IntermediateField ℚ (candidateGenusFieldReal hd))
      (candidateGenusFieldReal hd) :=
  IsTotallyReal.isUnramifiedAtInfinitePlaces

/-- **Every abelian Galois extension of `ℚ` containing the chosen square root and unramified
everywhere over the quadratic base embeds into the real candidate.** The narrow genus-field
maximality first embeds it into the full prime-discriminant compositum. Unramifiedness at infinity
over the real quadratic base makes the source totally real, so its image lies in the maximal
totally real subfield. The embedding can then be adjusted to carry the chosen square root to the
chosen root in the real candidate. -/
theorem exists_algHom_candidateGenusFieldReal {M : Type*} [Field M] [NumberField M]
    [IsAbelianGalois ℚ M] (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    (hpos : 0 < d) {z : M} (hz : z ^ 2 = algebraMap ℤ M d)
    (hfinite : ∀ q : Ideal (𝓞 (adjoin ℚ {z} : IntermediateField ℚ M)),
      q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q)
    (hinfinite : IsUnramifiedAtInfinitePlaces (adjoin ℚ {z} : IntermediateField ℚ M) M) :
    ∃ φ : M →ₐ[ℚ] candidateGenusFieldReal hd,
      φ z = candidateGenusFieldRealBaseRoot hd hpos := by
  -- The chosen quadratic base is totally real; infinite unramifiedness then forces `M` to be
  -- totally real as well.
  let _ : IsTotallyReal (adjoin ℚ {z} : IntermediateField ℚ M) :=
    NumberField.isTotallyReal_of_sq_ratCast_of_nonneg
      (x := IntermediateField.AdjoinSimple.gen ℚ z)
      (r := ((d : ℤ) : ℚ))
      (by
        apply Subtype.ext
        rw [IntermediateField.coe_pow, IntermediateField.AdjoinSimple.coe_gen, hz,
          IsScalarTower.algebraMap_apply ℤ ℚ M]
        norm_num)
      (by
        rw [← IntermediateField.adjoin_eq_top_iff]
        exact IntermediateField.adjoin_adjoinSimple_gen_eq_top z)
      (by exact_mod_cast hpos.le)
  let _ : IsUnramifiedAtInfinitePlaces (adjoin ℚ {z} : IntermediateField ℚ M) M := hinfinite
  let _ : IsTotallyReal M := IsTotallyReal.of_isUnramifiedAtInfinitePlaces
    (k := (adjoin ℚ {z} : IntermediateField ℚ M)) (K := M)
  -- Finite unramifiedness supplies an embedding into the full candidate. Its totally real image
  -- lies in the maximal real subfield, so the embedding factors through the real candidate.
  obtain ⟨φ⟩ := nonempty_algHom_candidateGenusField hd hnsq hz hfinite
  let e : M ≃+* φ.fieldRange := (AlgEquiv.ofInjective φ φ.injective).toRingEquiv
  let _ : IsTotallyReal φ.fieldRange := IsTotallyReal.ofRingEquiv e
  have hrange : φ.fieldRange.toSubfield ≤ maximalRealSubfield (candidateGenusField hd) :=
    IsTotallyReal.le_maximalRealSubfield φ.fieldRange.toSubfield
  let ψ : M →ₐ[ℚ] candidateGenusFieldReal hd :=
    φ.codRestrict (candidateGenusFieldReal hd).toSubalgebra fun x => hrange ⟨x, rfl⟩
  apply TauCeti.exists_algHom_apply_eq_of_sq_eq
    (r := ((d : ℤ) : ℚ)) (y := candidateGenusFieldRealBaseRoot hd hpos) (z := z)
  · rw [candidateGenusFieldRealBaseRoot_sq]
  · exact finrank_adjoin_candidateGenusFieldRealBaseRoot hd hnsq hpos
  · rw [hz, IsScalarTower.algebraMap_apply ℤ ℚ M]
    norm_num
  · exact ⟨ψ⟩

end TauCeti.Multiquadratic
