/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Probability.Process.PathLaw.Shift
public import TauCeti.Probability.Process.Tail.Basic
public import Mathlib.MeasureTheory.MeasurableSpace.Invariants

/-!
# The shift-invariant σ-algebra: its place below the path tail, and its stability under reindexing

For the one-sided shift on path space `ℕ → α`, an ambient-measurable event fixed by the shift is
fixed by every iterate of the shift, and therefore depends only on the coordinates from an
arbitrarily late time onward.  This file proves that comparison,

`MeasurableSpace.invariants (shift α) ≤ pathTail α`,

and shows that the inclusion is **strict**: for `Bool`-valued paths, the tail event "the value
`true` occurs at infinitely many even times" is not shift-invariant, because the shift exchanges
even and odd times.  So for one-sided sequences the tail and shift-invariant σ-algebras must not be
silently identified, and these two results are the exact form of their comparison.

The engine of the positive direction is `tailFamily_coord_eq_comap_shift_iterate`: the future path
σ-algebra from time `n` onward *is* the σ-algebra generated by the `n`-fold shift.  That identity
also gives the shift description `pathTail_eq_iInf_comap_shift_iterate` of the path tail
σ-algebra.

The file also records how shift-invariant events behave under **time reindexing**: a reindexing
that is eventually a translation leaves every invariants-measurable event and function unchanged.
These are the invariants-measurable forms of the raw statements
`preimage_reindex_eq_of_preimage_shift_eq_of_eventually_add` and
`comp_reindex_apply_eq_of_comp_shift_eq_of_eventually_add` in
`TauCeti.Probability.Process.PathLaw.Shift`, which assume only that the event or function is fixed
by the shift; the function-level form composes the raw one with Mathlib's
`MeasurableSpace.comp_eq_of_measurable_invariants`.  They let a block argument move an invariant
event through a reindexing; measure preservation of the reindexing is a separate input.

## Main results

* `tailFamily_coord_eq_comap_shift_iterate`, `pathTail_eq_iInf_comap_shift_iterate` — future and
  tail path σ-algebras as σ-algebras generated by shift iterates;
* `invariants_shift_le_pathTail` — a shift-invariant event is a tail event;
* `not_pathTail_le_invariants_shift`, `invariants_shift_lt_pathTail` — the inclusion is strict for
  `Bool`-valued paths;
* `preimage_reindex_eq_of_measurableSet_invariants_of_eventually_add` — an eventually translating
  reindexing fixes every invariants-measurable event;
* `comp_reindex_apply_eq_of_measurable_invariants_of_eventually_add` — and leaves every
  invariants-measurable function unchanged, pointwise.
-/

public section

noncomputable section

open MeasureTheory

namespace TauCeti

namespace Probability

variable {α : Type*} [MeasurableSpace α]

/-! ## Future σ-algebras as shift preimages -/

/-- The future path σ-algebra from time `n` onward is the σ-algebra generated by the `n`-fold
shift: an event depends only on the coordinates `n, n + 1, …` exactly when it is the preimage of an
ambient-measurable event under `(shift α)^[n]`. -/
theorem tailFamily_coord_eq_comap_shift_iterate (n : ℕ) :
    tailFamily (fun k (x : ℕ → α) => x k) n =
      MeasurableSpace.comap ((shift α)^[n]) inferInstance := by
  rw [tailFamily_eq_comap_shift, shift_iterate_eq_reindex n]
  simp only [Nat.add_comm]

/-- The path tail σ-algebra is the intersection of the σ-algebras generated by the iterated
shifts. -/
theorem pathTail_eq_iInf_comap_shift_iterate :
    pathTail α = ⨅ n : ℕ, MeasurableSpace.comap ((shift α)^[n]) inferInstance := by
  rw [pathTail_eq_tailProcess, tailProcess_eq_iInf_tailFamily]
  exact iInf_congr fun n => tailFamily_coord_eq_comap_shift_iterate n

/-! ## Shift-invariant events are tail events -/

/-- **A shift-invariant event is a tail event.**  A shift-invariant event is fixed by every iterate
of the one-sided shift, hence for each `n` it is the preimage under `(shift α)^[n]` of an
ambient-measurable event, so it depends only on the coordinates from time `n` onward. -/
theorem invariants_shift_le_pathTail :
    MeasurableSpace.invariants (shift α) ≤ pathTail α := by
  intro s hs
  rw [pathTail_eq_tailProcess, tailProcess_eq_iInf_tailFamily, MeasurableSpace.measurableSet_iInf]
  intro n
  have hn : MeasurableSet[MeasurableSpace.invariants ((shift α)^[n])] s :=
    MeasurableSpace.le_invariants_iterate (shift α) n s hs
  obtain ⟨hs_meas, hs_inv⟩ := MeasurableSpace.measurableSet_invariants.mp hn
  rw [tailFamily_coord_eq_comap_shift_iterate]
  exact ⟨s, hs_meas, hs_inv⟩

/-! ## The inclusion is strict

The one-sided shift moves even times to odd times, so a tail event that refers to the even times
only need not be shift-invariant.  The witness below is the `Bool`-valued event "the value `true`
occurs at infinitely many even times". -/

/-- The path-space event that a `Bool`-valued path takes the value `true` at infinitely many even
times.  It is a tail event which the one-sided shift does not preserve. -/
private def trueFrequentlyAtEvenTimes : Set (ℕ → Bool) :=
  ⋂ N : ℕ, ⋃ n : ℕ, {x : ℕ → Bool | x (2 * (N + n)) = true}

/-- Membership in `trueFrequentlyAtEvenTimes` says that `true` occurs at arbitrarily late even
times. -/
private theorem mem_trueFrequentlyAtEvenTimes {x : ℕ → Bool} :
    x ∈ trueFrequentlyAtEvenTimes ↔ ∀ N, ∃ n, N ≤ n ∧ x (2 * n) = true := by
  simp only [trueFrequentlyAtEvenTimes, Set.mem_iInter, Set.mem_iUnion, Set.mem_ofPred_eq]
  constructor
  · intro h N
    obtain ⟨n, hn⟩ := h N
    exact ⟨N + n, Nat.le_add_right N n, hn⟩
  · intro h N
    obtain ⟨n, hNn, hn⟩ := h N
    exact ⟨n - N, by rwa [Nat.add_sub_cancel' hNn]⟩

/-- `trueFrequentlyAtEvenTimes` can be written using only the even times beyond any prescribed
cutoff `r`; this is what makes it measurable for every future σ-algebra. -/
private theorem trueFrequentlyAtEvenTimes_eq_iInter_iUnion (r : ℕ) :
    trueFrequentlyAtEvenTimes =
      ⋂ N : ℕ, ⋃ n : ℕ, {x : ℕ → Bool | x (2 * (r + N + n)) = true} := by
  ext x
  simp only [mem_trueFrequentlyAtEvenTimes, Set.mem_iInter, Set.mem_iUnion, Set.mem_ofPred_eq]
  constructor
  · intro h N
    obtain ⟨n, hn, hx⟩ := h (r + N)
    exact ⟨n - (r + N), by rwa [Nat.add_sub_cancel' hn]⟩
  · intro h N
    obtain ⟨n, hx⟩ := h N
    exact ⟨r + N + n, by omega, hx⟩

/-- `trueFrequentlyAtEvenTimes` belongs to every future path σ-algebra. -/
private theorem measurableSet_tailFamily_trueFrequentlyAtEvenTimes (r : ℕ) :
    MeasurableSet[tailFamily (fun k (x : ℕ → Bool) => x k) r] trueFrequentlyAtEvenTimes := by
  rw [trueFrequentlyAtEvenTimes_eq_iInter_iUnion r]
  refine MeasurableSet.iInter fun N => MeasurableSet.iUnion fun n => ?_
  have hset : {x : ℕ → Bool | x (2 * (r + N + n)) = true} =
      (fun x : ℕ → Bool => x (2 * (r + N + n))) ⁻¹' {true} := rfl
  rw [hset]
  exact measurable_tailFamily_of_le (X := fun k (x : ℕ → Bool) => x k)
    (by omega) (measurableSet_singleton true)

/-- `trueFrequentlyAtEvenTimes` is a tail event. -/
private theorem measurableSet_pathTail_trueFrequentlyAtEvenTimes :
    MeasurableSet[pathTail Bool] trueFrequentlyAtEvenTimes := by
  rw [pathTail_eq_tailProcess, tailProcess_eq_iInf_tailFamily, MeasurableSpace.measurableSet_iInf]
  exact measurableSet_tailFamily_trueFrequentlyAtEvenTimes

/-- The one-sided shift does not preserve `trueFrequentlyAtEvenTimes`: the alternating path lies
in the event, while its shift, which is `true` exactly at the odd times, does not. -/
private theorem preimage_shift_trueFrequentlyAtEvenTimes_ne :
    shift Bool ⁻¹' trueFrequentlyAtEvenTimes ≠ trueFrequentlyAtEvenTimes := by
  intro h
  set x : ℕ → Bool := fun k => decide (k % 2 = 0) with hx
  have hmem : x ∈ trueFrequentlyAtEvenTimes := by
    rw [mem_trueFrequentlyAtEvenTimes]
    refine fun N => ⟨N, le_rfl, ?_⟩
    simp [hx, Nat.mul_mod_right]
  have hshift : shift Bool x ∉ trueFrequentlyAtEvenTimes := by
    intro hmem_shift
    obtain ⟨n, -, hn⟩ := mem_trueFrequentlyAtEvenTimes.mp hmem_shift 0
    have hodd : (2 * n + 1) % 2 = 1 := by omega
    simp [hx, shift_apply, hodd] at hn
  have hpre : x ∈ shift Bool ⁻¹' trueFrequentlyAtEvenTimes := by rw [h]; exact hmem
  exact hshift hpre

/-- **The path tail σ-algebra is not contained in the shift-invariant σ-algebra**: for `Bool`-valued
paths, the tail event "the value `true` occurs at infinitely many even times" is not fixed by the
one-sided shift, which carries the even times onto the odd ones. -/
theorem not_pathTail_le_invariants_shift :
    ¬ pathTail Bool ≤ MeasurableSpace.invariants (shift Bool) := fun h =>
  preimage_shift_trueFrequentlyAtEvenTimes_ne
    (MeasurableSpace.measurableSet_invariants.mp
      (h _ measurableSet_pathTail_trueFrequentlyAtEvenTimes)).2

/-- For `Bool`-valued paths the inclusion `invariants_shift_le_pathTail` is strict: the
shift-invariant σ-algebra is a proper sub-σ-algebra of the path tail σ-algebra. -/
theorem invariants_shift_lt_pathTail :
    MeasurableSpace.invariants (shift Bool) < pathTail Bool :=
  lt_of_le_not_ge invariants_shift_le_pathTail not_pathTail_le_invariants_shift

/-- **Invariant events are fixed by an eventually-translating reindexing**, in the
`MeasurableSpace.invariants`-measurable form.

Deliberately **not** `@[simp]`: `m` and `C` occur only in the hypothesis `hφ`, never in the
left-hand side, so `simp` cannot infer them and the rule would never fire. -/
theorem preimage_reindex_eq_of_measurableSet_invariants_of_eventually_add {m C : ℕ} {φ : ℕ → ℕ}
    {A : Set (ℕ → α)} (hA : MeasurableSet[MeasurableSpace.invariants (shift α)] A)
    (hφ : ∀ n, m ≤ n → φ n = n + C) :
    (fun x : ℕ → α => fun k => x (φ k)) ⁻¹' A = A :=
  preimage_reindex_eq_of_preimage_shift_eq_of_eventually_add
    (MeasurableSpace.measurableSet_invariants.1 hA).2 hφ

/-- **An invariants-measurable function is unchanged by such a reindexing**, pointwise.

The invariants-measurable form of the above. Measurable singletons are needed only to pass from
invariants-measurability to `w ∘ shift α = w`, which is Mathlib's
`MeasurableSpace.comp_eq_of_measurable_invariants`; the displacement itself needs neither. -/
theorem comp_reindex_apply_eq_of_measurable_invariants_of_eventually_add {m C : ℕ} {φ : ℕ → ℕ}
    {β : Type*} [MeasurableSpace β] [MeasurableSingletonClass β] {w : (ℕ → α) → β}
    (hw : Measurable[MeasurableSpace.invariants (shift α)] w)
    (hφ : ∀ n, m ≤ n → φ n = n + C) (x : ℕ → α) :
    w (fun k => x (φ k)) = w x :=
  comp_reindex_apply_eq_of_comp_shift_eq_of_eventually_add
    (MeasurableSpace.comp_eq_of_measurable_invariants hw) hφ x

end Probability

end TauCeti
