/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Subalgebra
public import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Decomposition
public import TauCeti.Algebra.Lie.Weights.Borel

/-!
# Factorizations of the universal enveloping algebra

Let `L` be a finite-dimensional Killing-semisimple Lie algebra in characteristic zero, with a
splitting Cartan subalgebra `H` and a base of its root system. The spanning statements identify
`U(n⁻) · U(𝔟)` and `U(n⁻) · U(H) · U(n⁺)` with `U(L)`, where each factor is viewed as a
subalgebra of `U(L)`.

For the Borel algebra, the sharper tensor decomposition is available:
`borelMulEquiv` is the linear equivalence `U(H) ⊗ U(n⁺) ≃ U(𝔟)` given by multiplication.
It has forward and inverse computation rules on products. This factorization separates the
Cartan part from the positive root operators in triangular decomposition and highest weight
constructions.

Combined with the decomposition `L = n⁻ ⊕ 𝔟`, it gives the **triangular decomposition**
`triangularMulEquiv : U(n⁻) ⊗ (U(H) ⊗ U(n⁺)) ≃ U(L)`, `f ⊗ h ⊗ e ↦ f h e`: every element of `U(L)`
is uniquely a sum of such ordered products, up to the relations of the tensor product. Its inverse
is what the Harish-Chandra projection `U(L) → U(H)` is built from.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §17.4 and §20.3.
-/

public section

namespace TauCeti.UniversalEnvelopingAlgebra

open LieAlgebra LieModule Module
open scoped TensorProduct

universe u v

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  (H : LieSubalgebra K L) [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  (b : (IsKilling.rootSystem H).Base)

/-- **`U(n⁻) · U(𝔟) = U(L)`**: the enveloping algebra of `L` is spanned by the products of the
enveloping subalgebra of the negative nilradical with that of the Borel subalgebra.

This is the enveloping-algebra form of the spanning statement `L = n⁻ + 𝔟`
(`TauCeti.negativeNilradical_sup_borelSubalgebra_eq_top`); it does not assert that the factors of
a product are determined by it. -/
theorem negativeNilradical_mul_borelSubalgebra_eq_top :
    Subalgebra.toSubmodule (envelopingSubalgebra K (negativeNilradical H b)) *
        Subalgebra.toSubmodule (envelopingSubalgebra K (borelSubalgebra H b)) = ⊤ :=
  envelopingSubalgebra_mul_envelopingSubalgebra_eq_top
    (negativeNilradical_sup_borelSubalgebra_eq_top H b)

/-- **`U(H) · U(n⁺) = U(𝔟)`**: the enveloping subalgebra of the Borel subalgebra is spanned by the
products of the enveloping subalgebra of the Cartan subalgebra with that of the positive
nilradical. -/
theorem cartan_mul_positiveNilradical_eq_envelopingSubalgebra_borelSubalgebra :
    Subalgebra.toSubmodule (envelopingSubalgebra K H) *
        Subalgebra.toSubmodule (envelopingSubalgebra K (positiveNilradical H b)) =
      Subalgebra.toSubmodule (envelopingSubalgebra K (borelSubalgebra H b)) :=
  envelopingSubalgebra_mul_envelopingSubalgebra_eq_envelopingSubalgebra
    (borelSubalgebra_toSubmodule H b)

/-- **The triangular decomposition of `U(L)`, in its spanning form**:
`U(n⁻) · U(H) · U(n⁺) = U(L)`.

Every element of `U(L)` is a sum of products `f · h · e` with `f` in the subalgebra generated by
the negative root vectors, `h` in the subalgebra generated by the Cartan subalgebra, and `e` in the
subalgebra generated by the positive root vectors. Uniqueness of such an expression is the
Poincaré--Birkhoff--Witt half and is not claimed. -/
theorem negativeNilradical_mul_cartan_mul_positiveNilradical_eq_top :
    Subalgebra.toSubmodule (envelopingSubalgebra K (negativeNilradical H b)) *
        Subalgebra.toSubmodule (envelopingSubalgebra K H) *
        Subalgebra.toSubmodule (envelopingSubalgebra K (positiveNilradical H b)) = ⊤ := by
  rw [mul_assoc, cartan_mul_positiveNilradical_eq_envelopingSubalgebra_borelSubalgebra H b,
    negativeNilradical_mul_borelSubalgebra_eq_top H b]

local notation "U" => _root_.UniversalEnvelopingAlgebra K

private theorem isCompl_cartan_positiveNilradical_ofLe :
    IsCompl ((H.ofLe (le_borelSubalgebra H b)) : Submodule K (borelSubalgebra H b))
      (((positiveNilradical H b).ofLe (positiveNilradical_le_borelSubalgebra H b)) :
        Submodule K (borelSubalgebra H b)) := by
  rw [(borelSubalgebra H b : Submodule K L).mapIic.isCompl_iff, Set.Iic.isCompl_iff]
  simp only [Submodule.coe_mapIic_apply, LieSubalgebra.coe_ofLe,
    Submodule.map_subtype_range_inclusion]
  exact ⟨disjoint_cartan_positiveNilradical H b, (borelSubalgebra_toSubmodule H b).symm⟩

/-- Multiplication identifies the Cartan and positive enveloping factors with the Borel
enveloping algebra. -/
noncomputable def borelMulEquiv :
    U H ⊗[K] U (positiveNilradical H b) ≃ₗ[K] U (borelSubalgebra H b) :=
  (TensorProduct.congr
    (UniversalEnvelopingAlgebra.mapEquiv K
      (LieSubalgebra.equivOfLe (le_borelSubalgebra H b))).toLinearEquiv
    (UniversalEnvelopingAlgebra.mapEquiv K
      (LieSubalgebra.equivOfLe (positiveNilradical_le_borelSubalgebra H b))).toLinearEquiv).trans
    (LieSubalgebra.mulEquiv _ _ (isCompl_cartan_positiveNilradical_ofLe H b))

/-- The Borel decomposition sends a pure tensor to the ordered product of its two images. -/
@[simp]
theorem borelMulEquiv_tmul (h : U H) (n : U (positiveNilradical H b)) :
    borelMulEquiv H b (h ⊗ₜ n) =
      UniversalEnvelopingAlgebra.map K (LieSubalgebra.inclusion (le_borelSubalgebra H b)) h *
        UniversalEnvelopingAlgebra.map K
          (LieSubalgebra.inclusion (positiveNilradical_le_borelSubalgebra H b)) n := by
  have hc (A : LieSubalgebra K L) (hA : A ≤ borelSubalgebra H b) :
      (UniversalEnvelopingAlgebra.map K (A.ofLe hA).incl).comp
          (UniversalEnvelopingAlgebra.mapEquiv K (LieSubalgebra.equivOfLe hA)).toAlgHom =
        UniversalEnvelopingAlgebra.map K (LieSubalgebra.inclusion hA) := by
    rw [UniversalEnvelopingAlgebra.mapEquiv_toAlgHom, ← UniversalEnvelopingAlgebra.map_comp]
    congr 1
  simp only [borelMulEquiv, LinearEquiv.trans_apply, TensorProduct.congr_tmul,
    LieSubalgebra.mulEquiv_tmul, AlgEquiv.toLinearEquiv_apply]
  exact congrArg₂ (· * ·) (AlgHom.congr_fun (hc H _) h)
    (AlgHom.congr_fun (hc (positiveNilradical H b) _) n)

/-- The inverse Borel decomposition recovers the Cartan and positive factors of a product. -/
@[simp]
theorem borelMulEquiv_symm_mul (h : U H) (n : U (positiveNilradical H b)) :
    (borelMulEquiv H b).symm
      (UniversalEnvelopingAlgebra.map K (LieSubalgebra.inclusion (le_borelSubalgebra H b)) h *
        UniversalEnvelopingAlgebra.map K
          (LieSubalgebra.inclusion (positiveNilradical_le_borelSubalgebra H b)) n) = h ⊗ₜ n := by
  rw [← borelMulEquiv_tmul H b, LinearEquiv.symm_apply_apply]

/-- **The triangular decomposition of `U(L)`**: multiplication identifies
`U(n⁻) ⊗ (U(H) ⊗ U(n⁺))` with `U(L)`, sending `f ⊗ h ⊗ e` to the ordered product `f h e` of the
images of the three factors (`TauCeti.UniversalEnvelopingAlgebra.triangularMulEquiv_tmul`). It is
the Borel decomposition `TauCeti.UniversalEnvelopingAlgebra.borelMulEquiv` followed by the
decomposition of `U(L)` along `L = n⁻ ⊕ 𝔟`. -/
noncomputable def triangularMulEquiv :
    U (negativeNilradical H b) ⊗[K] (U H ⊗[K] U (positiveNilradical H b)) ≃ₗ[K] U L :=
  (TensorProduct.congr (LinearEquiv.refl K _) (borelMulEquiv H b)).trans
    (LieSubalgebra.mulEquiv _ _ (isCompl_negativeNilradical_borelSubalgebra H b))

/-- The triangular decomposition sends a pure tensor to the ordered product of its three
images. -/
@[simp]
theorem triangularMulEquiv_tmul (f : U (negativeNilradical H b)) (h : U H)
    (e : U (positiveNilradical H b)) :
    triangularMulEquiv H b (f ⊗ₜ (h ⊗ₜ e)) =
      UniversalEnvelopingAlgebra.map K (negativeNilradical H b).incl f *
        UniversalEnvelopingAlgebra.map K H.incl h *
          UniversalEnvelopingAlgebra.map K (positiveNilradical H b).incl e := by
  simp only [triangularMulEquiv, LinearEquiv.trans_apply, TensorProduct.congr_tmul,
    LinearEquiv.refl_apply, borelMulEquiv_tmul, LieSubalgebra.mulEquiv_tmul, map_mul,
    ← AlgHom.comp_apply, map_incl_comp_map_inclusion, mul_assoc]

/-- The inverse triangular decomposition recovers the three factors of an ordered product. -/
@[simp]
theorem triangularMulEquiv_symm_mul_mul (f : U (negativeNilradical H b)) (h : U H)
    (e : U (positiveNilradical H b)) :
    (triangularMulEquiv H b).symm
        (UniversalEnvelopingAlgebra.map K (negativeNilradical H b).incl f *
          UniversalEnvelopingAlgebra.map K H.incl h *
            UniversalEnvelopingAlgebra.map K (positiveNilradical H b).incl e) =
      f ⊗ₜ (h ⊗ₜ e) := by
  rw [← triangularMulEquiv_tmul H b, LinearEquiv.symm_apply_apply]

end TauCeti.UniversalEnvelopingAlgebra
