/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Perm.Cycle.Basic
public import TauCeti.Topology.Homotopy.Monodromy.Basic
public import TauCeti.Topology.Homotopy.Path

/-!
# Path components of the preimage of a subset under a covering map

Let `p : E → X` be a covering map, let `V ⊆ X` be path connected, and fix `v ∈ V`. The path
components of `p ⁻¹' V` are read off from the monodromy of the loops of `V` on the single fibre
over `v`:

* two points of that fibre are joined by a path inside `p ⁻¹' V` exactly when monodromy along
  the image of a loop of `V` carries one to the other
  (`IsCoveringMap.joinedIn_preimage_iff`): project a joining path to a loop of `V`, and
  conversely lift a loop of `V`, whose lift stays over `V`;
* every point of `p ⁻¹' V` is joined inside `p ⁻¹' V` to a point of that fibre
  (`IsCoveringMap.exists_joinedIn_preimage`), by lifting a path of `V`.

When `π₁(V, v)` is generated by one class `c`, the orbits of loops of `V` on the fibre are the
cycles of the single monodromy permutation of `c`. The path components of `p ⁻¹' V` are then in
bijection with the cycles of that permutation
(`IsCoveringMap.sameCycleQuotientEquivZerothHomotopy`). This is the local input for filling in
the punctures of a cover of a punctured surface: over a punctured-disc neighbourhood of a
puncture, the components of the preimage, and so the points to be added, are the cycles of the
local monodromy.

## Main declarations

* `IsCoveringMap.joinedIn_preimage_iff`: points of the fibre over `v ∈ V` are joined inside
  `p ⁻¹' V` exactly when they differ by the monodromy of a loop of `V`.
* `IsCoveringMap.exists_joinedIn_preimage`: for a path-connected `V`, every point of `p ⁻¹' V`
  is joined inside `p ⁻¹' V` to the fibre over `v`.
* `IsCoveringMap.sameCycle_monodromyPerm_iff_joinedIn_preimage`: when `c` generates `π₁(V, v)`,
  two points of the fibre lie in the same cycle of the monodromy of `c` exactly when they are
  joined inside `p ⁻¹' V`.
* `IsCoveringMap.sameCycleQuotientEquivZerothHomotopy`: the cycles of that monodromy
  permutation are the path components of `p ⁻¹' V`.

## References

* A. Hatcher, *Algebraic Topology*, Cambridge University Press, 2002, §1.3: Proposition 1.30
  (lifting of paths) and the action of `π₁` on a fibre by monodromy.
-/

public section

namespace TauCeti

open Equiv Equiv.Perm

variable {E X : Type*} [TopologicalSpace E] [TopologicalSpace X] {p : E → X}

/-- **Points of a fibre joined over `V`.** Two points of the fibre over `v ∈ V` are joined by a
path inside `p ⁻¹' V` exactly when monodromy along the image in `π₁(X, v)` of some loop of `V`
carries the first to the second. -/
theorem _root_.IsCoveringMap.joinedIn_preimage_iff (hp : IsCoveringMap p) {V : Set X} {v : X}
    (hv : v ∈ V) (e e' : p ⁻¹' {v}) :
    JoinedIn (p ⁻¹' V) (e : E) (e' : E) ↔
      ∃ g : FundamentalGroup V ⟨v, hv⟩,
        hp.monodromy (FundamentalGroup.map ⟨Subtype.val, continuous_subtype_val⟩ ⟨v, hv⟩ g) e =
          e' := by
  have he : p (e : E) = v := e.2
  have he' : p (e' : E) = v := e'.2
  constructor
  · intro h
    -- The projection of a joining path is a loop at `v` lying in `V`.
    let γ : Path v v := (h.somePath.map hp.continuous).cast he.symm he'.symm
    have hγ : ∀ t, γ t ∈ V := fun t => h.somePath_mem t
    have hδ : FundamentalGroup.map ⟨Subtype.val, continuous_subtype_val⟩ ⟨v, hv⟩
        (FundamentalGroup.fromPath (.mk (γ.codRestrict (x := ⟨v, hv⟩) (y := ⟨v, hv⟩) hγ))) =
          FundamentalGroup.fromPath (.mk γ) := by
      rw [FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.mk_map]
      exact congrArg _ (Path.map_codRestrict (x := ⟨v, hv⟩) (y := ⟨v, hv⟩) γ hγ)
    refine ⟨FundamentalGroup.fromPath (.mk (γ.codRestrict (x := ⟨v, hv⟩) (y := ⟨v, hv⟩) hγ)), ?_⟩
    rw [hδ]
    refine hp.monodromy_eq_of_map_eq (.mk h.somePath) ?_
    -- Both sides are the class of the projected path, up to casts of its endpoints.
    exact eq_of_heq ((Path.Homotopic.Quotient.cast_heq _ _).trans
      (Path.Homotopic.Quotient.cast_heq _ _)).symm
  · rintro ⟨g, rfl⟩
    induction g using Path.Homotopic.Quotient.ind with | mk δ => ?_
    let γ : Path v v := δ.map continuous_subtype_val
    have hγ : γ.toContinuousMap 0 = p e := by simp [γ, he]
    -- The lift of a loop of `V` is a path in `p ⁻¹' V`.
    refine ⟨⟨hp.liftPath γ.toContinuousMap e hγ, hp.liftPath_zero .., ?_⟩, fun t => ?_⟩
    · rw [FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.mk_map, hp.coe_monodromy_mk γ e hγ]
      rfl
    · rw [Set.mem_preimage, Path.coe_mk', ← Function.comp_apply (f := p), hp.liftPath_lifts]
      exact (δ t).2

/-- **Every point over a path-connected `V` is joined over `V` to the fibre over `v`.** Lifting a
path of `V` from `p e` to `v`, starting at `e`, gives a path inside `p ⁻¹' V` ending over `v`. -/
theorem _root_.IsCoveringMap.exists_joinedIn_preimage (hp : IsCoveringMap p) {V : Set X}
    (hV : IsPathConnected V) {v : X} (hv : v ∈ V) {e : E} (he : p e ∈ V) :
    ∃ e' : p ⁻¹' {v}, JoinedIn (p ⁻¹' V) e e' := by
  have hjoin := hV.joinedIn (p e) he v hv
  let β := hjoin.somePath
  let Λ := hp.liftPath β.toContinuousMap e β.source
  have hΛ (t) : p (Λ t) = β t := congrFun (hp.liftPath_lifts β.toContinuousMap e β.source) t
  refine ⟨⟨Λ 1, by simp [hΛ]⟩, ⟨⟨Λ, hp.liftPath_zero .., rfl⟩, fun t => ?_⟩⟩
  rw [Set.mem_preimage, Path.coe_mk', hΛ]
  exact hjoin.somePath_mem t

/-- **Cycles of a generating loop are the components over `V`.** If the class `c` generates
`π₁(V, v)`, two points of the fibre over `v` lie in the same cycle of the monodromy permutation
of `c` exactly when they are joined by a path inside `p ⁻¹' V`. -/
theorem _root_.IsCoveringMap.sameCycle_monodromyPerm_iff_joinedIn_preimage (hp : IsCoveringMap p)
    {V : Set X} {v : X} (hv : v ∈ V) {c : FundamentalGroup V ⟨v, hv⟩}
    (hc : Subgroup.zpowers c = ⊤) (e e' : p ⁻¹' {v}) :
    (hp.monodromyPerm v
        (FundamentalGroup.map ⟨Subtype.val, continuous_subtype_val⟩ ⟨v, hv⟩ c)).SameCycle e e' ↔
      JoinedIn (p ⁻¹' V) (e : E) (e' : E) := by
  rw [hp.joinedIn_preimage_iff hv]
  constructor
  · rintro ⟨k, hk⟩
    refine ⟨c ^ k, ?_⟩
    rwa [map_zpow, ← IsCoveringMap.coe_monodromyPerm, map_zpow]
  · rintro ⟨g, hg⟩
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hc ▸ Subgroup.mem_top g)
    refine ⟨k, ?_⟩
    rwa [← map_zpow, ← map_zpow]

/-- **The cycles of the local monodromy are the path components over `V`.** For a
path-connected `V ∋ v` whose fundamental group is generated by `c`, sending a point of the fibre
over `v` to its path component in `p ⁻¹' V` identifies the cycles of the monodromy permutation of
`c` with the path components of `p ⁻¹' V`. -/
noncomputable def _root_.IsCoveringMap.sameCycleQuotientEquivZerothHomotopy (hp : IsCoveringMap p)
    {V : Set X} (hV : IsPathConnected V) {v : X} (hv : v ∈ V) {c : FundamentalGroup V ⟨v, hv⟩}
    (hc : Subgroup.zpowers c = ⊤) :
    Quotient (SameCycle.setoid (hp.monodromyPerm v
        (FundamentalGroup.map ⟨Subtype.val, continuous_subtype_val⟩ ⟨v, hv⟩ c))) ≃
      ZerothHomotopy (p ⁻¹' V) :=
  have hmem (e : p ⁻¹' {v}) : (e : E) ∈ p ⁻¹' V := by
    rw [Set.mem_preimage, e.2]
    exact hv
  have hrel (e e' : p ⁻¹' {v}) :
      (hp.monodromyPerm v
          (FundamentalGroup.map ⟨Subtype.val, continuous_subtype_val⟩ ⟨v, hv⟩ c)).SameCycle e e' ↔
        Joined (⟨e, hmem e⟩ : p ⁻¹' V) ⟨e', hmem e'⟩ := by
    rw [hp.sameCycle_monodromyPerm_iff_joinedIn_preimage hv hc, joinedIn_iff_joined]
  Equiv.ofBijective
    (Quotient.lift (fun e => ZerothHomotopy.mk (⟨e, hmem e⟩ : p ⁻¹' V))
      fun e e' h => Quotient.sound ((hrel e e').mp h))
    ⟨fun a b => Quotient.inductionOn₂ a b fun e e' h =>
        Quotient.sound ((hrel e e').mpr (Quotient.exact h)),
      fun a => by
        induction a with
        | mk x =>
          obtain ⟨e', h⟩ := hp.exists_joinedIn_preimage hV hv x.2
          exact ⟨Quotient.mk _ e', Quotient.sound ((joinedIn_iff_joined (hmem e') x.2).mp h.symm)⟩⟩

/-- The identification of cycles with path components sends the cycle of a point of the fibre
to the path component containing that point. -/
theorem _root_.IsCoveringMap.sameCycleQuotientEquivZerothHomotopy_mk (hp : IsCoveringMap p)
    {V : Set X} (hV : IsPathConnected V) {v : X} (hv : v ∈ V) {c : FundamentalGroup V ⟨v, hv⟩}
    (hc : Subgroup.zpowers c = ⊤) (e : p ⁻¹' {v}) :
    hp.sameCycleQuotientEquivZerothHomotopy hV hv hc (Quotient.mk _ e) =
      ZerothHomotopy.mk ⟨(e : E), by rw [Set.mem_preimage, e.2]; exact hv⟩ :=
  (rfl)

end TauCeti
