/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.PGroup
public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.Basic
public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.Basic
import TauCeti.GroupTheory.QuotientGroup.KerEquiv
import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.Transfer.StrictDimension
import TauCeti.RepresentationTheory.Homological.ContCohomology.FiniteCyclic
import TauCeti.Topology.Algebra.Group.TopologicalAbelianization.MaximalProP
import TauCeti.Algebra.GroupAction.TypeTags

/-!
# The class of the pro-p class module generates `H²` for a cyclic quotient

Let `G` be a profinite group with `scd_p G ≤ 2` and let `V` be an open normal subgroup such
that `G ⧸ V` is a cyclic `p`-group. Then `H²(G ⧸ V, V^ab(p))` is cyclic of order `#(G ⧸ V)`,
generated by the class `u_{G/V}(p)` of the factor set of the extension of `G ⧸ V` by `V^ab(p)`
(`TauCeti.abelianizationProPClass`). This is the degree-two half of NSW (3.6.4), (ii) ⇒ (iii),
for a cyclic quotient; it is the class formation axiom that, together with the vanishing of
`H¹`, makes the modules `V^ab(p)` a `p`-class formation for `G`. The prime-order case is the base
case of the induction over `p`-group quotients in NSW (3.6.4).

The computation runs through the description `H²(Γ, A) ≅ A^Γ / N(A)` of the second cohomology of
a finite cyclic group `Γ = ⟨σ⟩` (`TauCeti.ContCohomology.explicitH2CyclicEquiv`), which sends
`u_{G/V}(p)` to the class of `∑_τ u(τ, σ)`, that is, of the transfer `Ver σ.out`
(`TauCeti.abelianizationProPTransfer_out`). Reading the transfer `Ver : G → V^ab(p)` in
`A^Γ / N(A)` gives a homomorphism from `G`:

* it is onto, because under `scd_p G ≤ 2` the image of `Ver` is the subgroup of invariants
  (`TauCeti.abelianizationProPTransfer_range`);
* its kernel is `V`. On `V` the transfer is the norm
  (`TauCeti.abelianizationProPTransfer_apply_of_mem`). Conversely, if `Ver g` is the norm of the
  class of `v ∈ V`, then `Ver (g v⁻¹) = 1`, so `g v⁻¹` dies in `G^ab(p)`
  (`TauCeti.abelianizationProPTransfer_eq_one_iff`), and hence in the abelian `p`-group `G ⧸ V`,
  which is a quotient of `G^ab(p)`.

So `A^Γ / N(A)` is isomorphic to `G ⧸ V`, the image of `u_{G/V}(p)` corresponding to the
generator `σ`.

## Main results

* `TauCeti.abelianizationProPClass_generates_of_isCyclic`: for a cyclic `p`-group quotient
  `G ⧸ V`, the class `u_{G/V}(p)` generates `H²(G ⧸ V, V^ab(p))`, a group of order `#(G ⧸ V)`.
* `TauCeti.abelianizationProPClass_generates_of_card_eq_prime`: the case `#(G ⧸ V) = p`.

## References

* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed.,
  the proof of (3.6.4), (ii) ⇒ (iii).
-/

public section

namespace TauCeti

open ContCohomology

universe u

variable {p : ℕ} {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] {V : Subgroup G} [V.Normal]

section FiniteIndex

variable [TotallyDisconnectedSpace G] [V.FiniteIndex]

attribute [local instance] Subgroup.fintypeQuotientOfFiniteIndex

omit [CompactSpace G] [TotallyDisconnectedSpace G] in
/-- On `V`, the transfer is the norm of the class: `N [v] = Ver v`. -/
private theorem groupNorm_ofMul_abelianizationProPMk (v : V) :
    groupNorm (G ⧸ V) (Additive (abelianizationProP p G V))
        (Additive.ofMul (abelianizationProPMk p G V v)) =
      Additive.ofMul (abelianizationProPTransfer p G V v) := by
  rw [groupNorm_apply, abelianizationProPTransfer_apply_of_mem, ofMul_prod]
  simp only [Additive.ofMul_smul]

omit [CompactSpace G] [TotallyDisconnectedSpace G] in
/-- The transfer, read additively, is invariant. -/
private theorem ofMul_abelianizationProPTransfer_mem_H0 (g : G) :
    Additive.ofMul (abelianizationProPTransfer p G V g) ∈
      H0 (G ⧸ V) (Additive (abelianizationProP p G V)) :=
  (FixedPoints.mem_addSubgroup _ _ _).2 fun q ↦ by
    rw [← Additive.ofMul_smul, smul_abelianizationProPTransfer]

/-- The transfer `Ver : G → V^ab(p)`, read in the quotient `A^Γ / N(A)` of the invariants by the
norms that computes the second cohomology of the cyclic group `Γ = G ⧸ V`. -/
private noncomputable def transferModNorm :
    G →* Multiplicative (H0 (G ⧸ V) (Additive (abelianizationProP p G V)) ⧸
      (groupNorm (G ⧸ V) (Additive (abelianizationProP p G V))).range.addSubgroupOf
        (H0 (G ⧸ V) (Additive (abelianizationProP p G V)))) :=
  MonoidHom.mk' (fun g ↦ Multiplicative.ofAdd (QuotientAddGroup.mk
      ⟨Additive.ofMul (abelianizationProPTransfer p G V g),
        ofMul_abelianizationProPTransfer_mem_H0 g⟩)) fun g g' ↦ by
    rw [← ofAdd_add, ← QuotientAddGroup.mk_add]
    congr 2
    exact Subtype.ext (by simp only [map_mul, ofMul_mul, AddSubgroup.coe_add])

omit [CompactSpace G] [TotallyDisconnectedSpace G] in
/-- `transferModNorm g` is the class of the invariant `Ver g`. -/
private theorem transferModNorm_apply (g : G) :
    transferModNorm (p := p) (V := V) g = Multiplicative.ofAdd (QuotientAddGroup.mk
      ⟨Additive.ofMul (abelianizationProPTransfer p G V g),
        ofMul_abelianizationProPTransfer_mem_H0 g⟩) :=
  (rfl)

/-- Under `scd_p G ≤ 2`, every invariant is a transfer, so `transferModNorm` is onto. -/
private theorem transferModNorm_surjective (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) :
    Function.Surjective (transferModNorm (p := p) (V := V)) := by
  intro y
  obtain ⟨y, rfl⟩ := Multiplicative.ofAdd.surjective y
  induction y using QuotientAddGroup.induction_on with
  | H x =>
    have hx : x.val.toMul ∈ (abelianizationProPTransfer p G V).range := by
      rw [abelianizationProPTransfer_range hp h hV, FixedPoints.mem_subgroup]
      intro q
      rw [← Additive.toMul_smul, (FixedPoints.mem_addSubgroup _ _ _).1 x.property q]
    obtain ⟨g, hg⟩ := hx
    exact ⟨g, congrArg Multiplicative.ofAdd
      (congrArg QuotientAddGroup.mk (Subtype.ext hg))⟩

/-- Under `scd_p G ≤ 2`, for a commutative `p`-group quotient `G ⧸ V`, the kernel of
`transferModNorm` is `V`: on `V` the transfer is a norm, and if `Ver g = N [v] = Ver v` then
`g v⁻¹` dies in `G^ab(p)`, hence lies in `V`. -/
private theorem transferModNorm_eq_one_iff (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (hpV : IsPGroup p (G ⧸ V)) [IsMulCommutative (G ⧸ V)] (g : G) :
    transferModNorm (p := p) (V := V) g = 1 ↔ g ∈ V := by
  rw [transferModNorm_apply, ← ofAdd_zero, Multiplicative.ofAdd.apply_eq_iff_eq,
    QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_addSubgroupOf, AddMonoidHom.mem_range]
  constructor
  · rintro ⟨a, ha⟩
    obtain ⟨v, hv⟩ := abelianizationProPMk_surjective p G V a.toMul
    rw [← ofMul_toMul a, ← hv, groupNorm_ofMul_abelianizationProPMk] at ha
    have hVer : abelianizationProPTransfer p G V (g * (v : G)⁻¹) = 1 := by
      rw [map_mul, map_inv, ← Additive.ofMul.injective ha, mul_inv_cancel]
    let : DiscreteTopology (G ⧸ V) := QuotientGroup.discreteTopology hV
    let : CommGroup (G ⧸ V) := { mul_comm := IsMulCommutative.is_comm.comm }
    let π : G →ₜ* G ⧸ V := ⟨QuotientGroup.mk' V, QuotientGroup.continuous_mk⟩
    have hπ := eq_one_of_maximalProPQuotient_mk_eq_one hpV.isProP π
      ((abelianizationProPTransfer_eq_one_iff hp h hV _).mp hVer)
    have hgv := (QuotientGroup.eq_one_iff _).mp hπ
    exact (V.mul_mem_cancel_right (V.inv_mem v.property)).mp hgv
  · intro hg
    exact ⟨_, groupNorm_ofMul_abelianizationProPMk ⟨g, hg⟩⟩

/-- Under `scd_p G ≤ 2`, for a commutative `p`-group quotient `G ⧸ V`, `transferModNorm` induces
an isomorphism of `G ⧸ V` with the quotient `A^Γ / N(A)` of the invariants by the norms. -/
private noncomputable def quotientEquivTransferModNorm (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (hpV : IsPGroup p (G ⧸ V)) [IsMulCommutative (G ⧸ V)] :
    G ⧸ V ≃* Multiplicative (H0 (G ⧸ V) (Additive (abelianizationProP p G V)) ⧸
      (groupNorm (G ⧸ V) (Additive (abelianizationProP p G V))).range.addSubgroupOf
        (H0 (G ⧸ V) (Additive (abelianizationProP p G V)))) :=
  (QuotientGroup.quotientMulEquivOfEq
      (SetLike.ext fun g ↦ (transferModNorm_eq_one_iff hp h hV hpV g).symm)).trans
    (QuotientGroup.quotientKerEquivOfSurjective _ (transferModNorm_surjective hp h hV))

/-- `quotientEquivTransferModNorm` sends the class of `g` to `transferModNorm g`. -/
private theorem quotientEquivTransferModNorm_mk (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (hpV : IsPGroup p (G ⧸ V)) [IsMulCommutative (G ⧸ V)] (g : G) :
    quotientEquivTransferModNorm hp h hV hpV g = transferModNorm g := by
  simp only [quotientEquivTransferModNorm, MulEquiv.trans_apply,
    QuotientGroup.quotientMulEquivOfEq_mk,
    TauCeti.QuotientGroup.quotientKerEquivOfSurjective_apply_mk]

omit [CompactSpace G] [TotallyDisconnectedSpace G] in
/-- Under the cyclic `H²` computation at a generator `σ`, the class `u_{G/V}(p)` goes to the
class of `Ver σ.out`. -/
private theorem explicitH2CyclicEquiv_abelianizationProPClass [DiscreteTopology (G ⧸ V)]
    (hV : IsOpen (V : Set G)) (σ : G ⧸ V) (hσ : ∀ q : G ⧸ V, q ∈ Subgroup.zpowers σ) :
    explicitH2CyclicEquiv (G ⧸ V) (Additive (abelianizationProP p G V)) σ hσ
        (abelianizationProPClass p G V hV) =
      Multiplicative.toAdd (transferModNorm (p := p) (V := V) σ.out) := by
  rw [abelianizationProPClass_def, transferModNorm_apply, toAdd_ofAdd]
  refine (explicitH2CyclicEquiv_mk _ _ σ hσ _).trans (congrArg QuotientAddGroup.mk ?_)
  exact Subtype.ext (abelianizationProPTransfer_out p G V σ).symm

/-- Under the cyclic `H²` computation at a generator `σ`, the class `u_{G/V}(p)` corresponds to
`σ` under `quotientEquivTransferModNorm`. -/
private theorem quotientEquivTransferModNorm_generator [DiscreteTopology (G ⧸ V)] (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (hpV : IsPGroup p (G ⧸ V)) [IsMulCommutative (G ⧸ V)] (σ : G ⧸ V)
    (hσ : ∀ q : G ⧸ V, q ∈ Subgroup.zpowers σ) :
    quotientEquivTransferModNorm hp h hV hpV σ = Multiplicative.ofAdd
      (explicitH2CyclicEquiv (G ⧸ V) (Additive (abelianizationProP p G V)) σ hσ
        (abelianizationProPClass p G V hV)) := by
  rw [explicitH2CyclicEquiv_abelianizationProPClass hV σ hσ, ofAdd_toAdd,
    ← quotientEquivTransferModNorm_mk hp h hV hpV, QuotientGroup.out_eq']

end FiniteIndex

variable [TotallyDisconnectedSpace G]

/-- **The class of the pro-`p` class module generates `H²` for a cyclic quotient**
(NSW (3.6.4), (ii) ⇒ (iii), in degree two and `p`-primary form). For a profinite group `G` with
`scd_p G ≤ 2` and an open normal subgroup `V` whose quotient `G ⧸ V` is a cyclic `p`-group, the
class `u_{G/V}(p)` generates `H²(G ⧸ V, V^ab(p))`, and this group has order `#(G ⧸ V)`. -/
theorem abelianizationProPClass_generates_of_isCyclic (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (hpV : IsPGroup p (G ⧸ V)) [IsCyclic (G ⧸ V)] :
    AddSubgroup.zmultiples (abelianizationProPClass p G V hV) = ⊤ ∧
      Nat.card (H2 (G ⧸ V) (Additive (abelianizationProP p G V))) = Nat.card (G ⧸ V) := by
  have : Finite (G ⧸ V) := V.quotient_finite_of_isOpen hV
  have : V.FiniteIndex := Subgroup.finiteIndex_of_finite_quotient
  have : DiscreteTopology (G ⧸ V) := QuotientGroup.discreteTopology hV
  let : Fintype (G ⧸ V) := Subgroup.fintypeQuotientOfFiniteIndex
  obtain ⟨σ, hσ⟩ := IsCyclic.exists_generator (α := G ⧸ V)
  let e := explicitH2CyclicEquiv (G ⧸ V) (Additive (abelianizationProP p G V)) σ hσ
  let ψ := quotientEquivTransferModNorm hp h hV hpV
  constructor
  · -- `ψ⁻¹ (e y) = σ ^ k` gives `e y = ψ σ ^ k = e (k • u_{G/V}(p))`.
    refine (AddSubgroup.eq_top_iff' _).2 fun y ↦ ?_
    obtain ⟨k, hk : σ ^ k = ψ.symm (Multiplicative.ofAdd (e y))⟩ :=
      hσ (ψ.symm (Multiplicative.ofAdd (e y)))
    refine AddSubgroup.mem_zmultiples_iff.2 ⟨k, e.injective (Multiplicative.ofAdd.injective ?_)⟩
    rw [map_zsmul, ofAdd_zsmul, ← quotientEquivTransferModNorm_generator hp h hV hpV σ hσ,
      ← map_zpow, hk, ψ.apply_symm_apply]
  · -- `ψ` identifies `G ⧸ V` with the target `A^Γ / N(A)` of `e`.
    exact (Nat.card_congr (e.toEquiv.trans Multiplicative.ofAdd)).trans
      (Nat.card_congr ψ.toEquiv).symm

/-- **The class of the pro-`p` class module generates `H²` for a quotient of prime order.** For
a profinite group `G` with `scd_p G ≤ 2` and an open normal subgroup `V` of prime index `p`, the
class `u_{G/V}(p)` generates `H²(G ⧸ V, V^ab(p))`, a group of order `p`. This is the base case of
the induction over `p`-group quotients in NSW (3.6.4). -/
theorem abelianizationProPClass_generates_of_card_eq_prime (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (hcard : Nat.card (G ⧸ V) = p) :
    AddSubgroup.zmultiples (abelianizationProPClass p G V hV) = ⊤ ∧
      Nat.card (H2 (G ⧸ V) (Additive (abelianizationProP p G V))) = p := by
  have : Fact p.Prime := ⟨hp⟩
  have : IsCyclic (G ⧸ V) := isCyclic_of_prime_card hcard
  simpa only [hcard] using abelianizationProPClass_generates_of_isCyclic hp h hV
    (.of_card (n := 1) (by rw [hcard, pow_one]))

end TauCeti
