/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Homology.AInfinity.Module.Right.Suspension

/-!
# Right A-infinity modules: arity components and component equations

This file splits the Taylor map of a right `A∞` module `MM` over `AA` into its arity
components, and spells out the module Stasheff law component by component.

As for the operations `m n` of an `A∞` algebra, the components are indexed by their total arity
`n`, counting the module input, so `b n` and `m n` take `n - 1` algebra inputs.  There is no
arity-zero operation, and `b 0` and `m 0` are the junk value `0`.

* `MM.b n : M ⊗ A^⊗(n-1) → M` is the suspended operation `b_n^M`: the restriction of the Taylor
  map to the summand `sM ⊗ (sA)^⊗(n-1)` of the cofree bar comodule.
* `MM.m n : M → A^(n-1) → M` is the unsuspended operation `m_n^M`, obtained from `MM.b n` by the
  Koszul sign of the degree-`-1` suspension of its `n` inputs.  This is the convention used for
  the unsuspended operations of an `A∞` algebra.

The bar differential is the coderivation `gradedCoderiv` generated by its Taylor map
(`barDifferential_eq`).  Conversely, `ofTaylor` builds a module from any degree-one Taylor map
whose generated coderivation squares to zero, checked on the Taylor component.  Composing with the
Taylor map turns the square-zero law into the suspended module Stasheff equations of every arity
(`stasheff_tmul_of_tprod`), with the algebra bar differential written out in
`stasheff_tmul_of_tprod_splice`.  On homogeneous inputs, these become
the unsuspended module Stasheff equations in the operations `m` of the module and of the algebra
(`stasheff`).  Conversely, `ofStasheff` builds a module from unsuspended operations of the right
degrees satisfying these equations.

The generic module-first unsuspension and the sign calculations shared with module morphisms live
in `TauCeti.Algebra.Homology.AInfinity.Module.Right.Suspension`.

## Main definitions

* `TauCeti.AInfinityRightModule.b`: the suspended arity components of the Taylor map.
* `TauCeti.AInfinityRightModule.m`: the unsuspended module operations.
* `TauCeti.AInfinityRightModule.gradedCoderiv`: the coderivation over the algebra bar
  differential generated by a map `sM ⊗ Tᶜ(sA) → sM`.
* `TauCeti.AInfinityRightModule.ofTaylor`: construct a module from its Taylor map.
* `TauCeti.AInfinityRightModule.ofStasheff`: construct a module from unsuspended operations
  satisfying the unsuspended module Stasheff equations.

## Main results

* `TauCeti.AInfinityRightModule.isHomogeneous_b_tmul_tprod` and
  `TauCeti.AInfinityRightModule.m_mem_piece`: the suspended components have degree one and the
  unsuspended operation of arity `n` has degree `2 - n`.
* `TauCeti.AInfinityRightModule.ext_b` and `TauCeti.AInfinityRightModule.ext_m`: a module is
  determined by its grading and either family of operations.
* `TauCeti.AInfinityRightModule.isGradedCoderivationOver_gradedCoderiv` and
  `TauCeti.AInfinityRightModule.rid_comp_lTensor_counit_comp_gradedCoderiv`: the map generated by
  `F` is a coderivation over the algebra bar differential with counit component `F`.
* `TauCeti.AInfinityRightModule.barDifferential_eq` and
  `TauCeti.AInfinityRightModule.ofTaylor_self`: the bar differential is the coderivation generated
  by the Taylor map, and every module is built from its Taylor map.
* `TauCeti.AInfinityRightModule.b_tmul_tprod_of_mem`: on homogeneous inputs, the suspended
  components are the unsuspended operations up to the Koszul sign of the suspension.
* `TauCeti.AInfinityRightModule.stasheff_tmul_of_tprod`: the suspended module Stasheff equation
  of each arity.
* `TauCeti.AInfinityRightModule.stasheff`: the unsuspended module Stasheff equation of each arity
  on homogeneous inputs, with `stasheff_arity_one` its arity-one case on arbitrary inputs.

## References

* E. Getzler and J. D. S. Jones, *A-infinity algebras and the cyclic bar complex*, Sections 1--2.
* B. Keller, *Introduction to A-infinity algebras and modules*, Section 4.
-/

public section

open scoped BigOperators TensorProduct
open _root_.MultilinearMap (evalNat evalNat_def suspExp suspExp_def suspExp_add)

namespace TauCeti

universe uR uA uM uN

variable {R : Type uR} {A : Type uA} {M : Type uM}
  [CommRing R] [AddCommGroup A] [Module R A] [AddCommGroup M] [Module R M]

namespace AInfinityRightModule

variable {AA : AInfinityAlgebra R A}

open TensorWords

section Components

/-- The suspended arity-`n` component `b_n^M` of a right `A∞` module: the Taylor map restricted
to the summand `sM ⊗ (sA)^⊗(n-1)` of the cofree bar comodule.  There is no arity-zero operation,
and `b 0` is the junk value `0`. -/
noncomputable def b (MM : AInfinityRightModule AA M) :
    (n : ℕ) → M ⊗[R] TensorPower R (n - 1) A →ₗ[R] M
  | 0 => 0
  | n + 1 => MM.taylor ∘ₗ (TensorWords.of R A n).lTensor M

/-- The arity-zero component is the junk value `0`. -/
@[simp]
theorem b_zero (MM : AInfinityRightModule AA M) : MM.b 0 = 0 :=
  (rfl)

/-- The arity component `b (n + 1)` is the Taylor map composed with the inclusion of words of
length `n`. -/
theorem b_def (MM : AInfinityRightModule AA M) (n : ℕ) :
    MM.b (n + 1) = MM.taylor ∘ₗ (TensorWords.of R A n).lTensor M :=
  (rfl)

/-- On a word of length `n`, the Taylor map is the arity component `b (n + 1)`. -/
theorem taylor_tmul_of (MM : AInfinityRightModule AA M) (n : ℕ) (x : M)
    (w : TensorPower R n A) :
    MM.taylor (x ⊗ₜ[R] TensorWords.of R A n w) = MM.b (n + 1) (x ⊗ₜ[R] w) :=
  (rfl)

/-- The arity component `b (n + 1)` has degree one: it sends a homogeneous suspended module
element and `n` homogeneous suspended letters to the suspended module degree one higher than the
total. -/
theorem isHomogeneous_b_tmul_tprod (MM : AInfinityRightModule AA M) (n : ℕ) {x : M} {p : ℤ}
    (hx : x ∈ (MM.grading.shift 1).piece p) (a : Fin n → A) (d : Fin n → ℤ)
    (ha : ∀ i, a i ∈ (AA.grading.shift 1).piece (d i)) :
    MM.b (n + 1) (x ⊗ₜ[R] PiTensorProduct.tprod R a) ∈
      (MM.grading.shift 1).piece (p + ∑ i, d i + 1) := by
  rw [← taylor_tmul_of]
  refine MM.isHomogeneous_taylor.map_mem ?_
  rw [barGrading_piece]
  exact InternalGrading.tmul_mem_tensorProduct _ _ hx
    (by simpa only [grading_piece] using mem_gradedPiece_of_tprod _ a d ha)

/-- The Taylor maps of two right `A∞` modules agree exactly when all their arity components
agree. -/
theorem taylor_eq_taylor_iff {MM NN : AInfinityRightModule AA M} :
    MM.taylor = NN.taylor ↔ ∀ n, MM.b n = NN.b n := by
  refine ⟨fun h n ↦ ?_, fun h ↦ TensorProduct.ext' fun x w ↦ ?_⟩
  · cases n with
    | zero => rfl
    | succ n => rw [b_def, b_def, h]
  have hx : MM.taylor ∘ₗ TensorProduct.mk R M (TensorWords R A) x =
      NN.taylor ∘ₗ TensorProduct.mk R M (TensorWords R A) x :=
    DirectSum.linearMap_ext R fun n ↦ LinearMap.ext fun z ↦ by
      simp only [← of_def, LinearMap.comp_apply, TensorProduct.mk_apply, taylor_tmul_of,
        h (n + 1)]
  exact LinearMap.congr_fun hx w

/-- Right `A∞` modules on a fixed carrier are determined by their grading and their suspended
arity components. -/
theorem ext_b {MM NN : AInfinityRightModule AA M} (hG : MM.grading = NN.grading)
    (hb : ∀ n, MM.b n = NN.b n) : MM = NN :=
  ext hG (taylor_eq_taylor_iff.2 hb)

end Components

section Unsuspended

variable {N : Type uN} [AddCommGroup N] [Module R N]

/-- The unsuspended arity-`n` operation `m_n^M` of a right `A∞` module, with the module input
first: for `n = k + 1`, the module-first unsuspension of `b n`.  On homogeneous inputs its Koszul
twists multiply to the Koszul sign of the suspension of `n` inputs.  There is no arity-zero
operation, and `m 0` is the junk value `0`. -/
noncomputable def m (MM : AInfinityRightModule AA M) :
    (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M
  | 0 => 0
  | n + 1 => unsuspend MM.grading AA.grading n (MM.b (n + 1))

/-- The arity-zero operation is the junk value `0`. -/
@[simp]
theorem m_zero (MM : AInfinityRightModule AA M) : MM.m 0 = 0 :=
  (rfl)

/-- The unsuspended operation evaluates the suspended component on Koszul-twisted inputs. -/
theorem m_apply (MM : AInfinityRightModule AA M) (n : ℕ) (x : M) (a : Fin n → A) :
    MM.m (n + 1) x a =
      MM.b (n + 1) (MM.grading.koszulTwist n x ⊗ₜ[R]
        PiTensorProduct.tprod R fun i ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i)) :=
  unsuspend_apply _ _ _ _ _ _

/-- The suspended component evaluates the unsuspended operation on Koszul-twisted inputs: the
twists defining `m` are involutions. -/
theorem b_tmul_tprod (MM : AInfinityRightModule AA M) (n : ℕ) (x : M) (a : Fin n → A) :
    MM.b (n + 1) (x ⊗ₜ[R] PiTensorProduct.tprod R a) =
      MM.m (n + 1) (MM.grading.koszulTwist n x)
        fun i : Fin n ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i) :=
  apply_tmul_tprod_eq_unsuspend _ _ n _ x a

/-- A Taylor map `F` that evaluates a family `m` on Koszul-twisted inputs is, on homogeneous
inputs, `m` multiplied by the Koszul sign of suspending the module input of degree `e` and the `k`
algebra inputs of degrees `d 0, …, d (k - 1)`. -/
private theorem apply_tmul_of_tprod_of_mem {G : InternalGrading R M}
    {F : (M ⊗[R] TensorWords R A) →ₗ[R] M}
    {m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M}
    (hFm : ∀ (n : ℕ) (x : M) (a : Fin n → A),
      F (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a)) =
        m (n + 1) (G.koszulTwist n x)
          fun i : Fin n ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i))
    (k : ℕ) {x : M} {e : ℤ} (hx : x ∈ G.piece e) (d : ℕ → ℤ) (a : ℕ → A)
    (ha : ∀ i < k, a i ∈ AA.grading.piece (d i)) :
    F (x ⊗ₜ[R] TensorWords.of R A k (PiTensorProduct.tprod R fun i : Fin k ↦ a i)) =
      negOnePowCast R (k * e + suspExp k d) • evalNat (m (k + 1) x) a := by
  rw [hFm]
  -- `m (k + 1)` is multilinear in `k + 1 - 1` arguments, which is `k` only up to unfolding.
  exact apply_koszulTwist_of_mem (n := k) G AA.grading (m (k + 1)) hx d a ha

/-- On a pure word, the Taylor map evaluates the unsuspended operation on Koszul-twisted
inputs. -/
theorem taylor_tmul_of_tprod (MM : AInfinityRightModule AA M) (n : ℕ) (x : M) (a : Fin n → A) :
    MM.taylor (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a)) =
      MM.m (n + 1) (MM.grading.koszulTwist n x)
        fun i : Fin n ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i) := by
  rw [taylor_tmul_of, b_tmul_tprod]

/-- On homogeneous inputs, the suspended component is the unsuspended operation multiplied by the
Koszul sign of suspending the module input of degree `e` and the `k` algebra inputs of degrees
`d 0, …, d (k - 1)`. -/
theorem b_tmul_tprod_of_mem (MM : AInfinityRightModule AA M) (k : ℕ) {x : M} {e : ℤ}
    (hx : x ∈ MM.grading.piece e) (d : ℕ → ℤ) (a : ℕ → A)
    (ha : ∀ i < k, a i ∈ AA.grading.piece (d i)) :
    MM.b (k + 1) (x ⊗ₜ[R] PiTensorProduct.tprod R fun i : Fin k ↦ a i) =
      negOnePowCast R (k * e + suspExp k d) • evalNat (MM.m (k + 1) x) a := by
  rw [← taylor_tmul_of]
  exact apply_tmul_of_tprod_of_mem MM.taylor_tmul_of_tprod k hx d a ha

/-- The suspended arity components are determined by the grading and the unsuspended
operations. -/
theorem b_eq_b_of_m_eq_m {MM NN : AInfinityRightModule AA M} (hG : MM.grading = NN.grading)
    (n : ℕ) (hm : MM.m n = NN.m n) : MM.b n = NN.b n := by
  obtain _ | n := n
  · rfl
  refine TensorProduct.ext' fun x w ↦ ?_
  induction w using PiTensorProduct.induction_on with
  | smul_tprod r a =>
    rw [TensorProduct.tmul_smul, map_smul, map_smul, b_tmul_tprod, b_tmul_tprod, hm, hG]
  | add u v hu hv => simp only [TensorProduct.tmul_add, map_add, hu, hv]

/-- Right `A∞` modules on a fixed carrier are determined by their grading and their unsuspended
operations. -/
theorem ext_m {MM NN : AInfinityRightModule AA M} (hG : MM.grading = NN.grading)
    (hm : ∀ n, MM.m n = NN.m n) : MM = NN :=
  ext_b hG fun n ↦ b_eq_b_of_m_eq_m hG n (hm n)

/-- The unsuspended operation `m_{n+1}^M` of arity `n + 1` has cohomological degree `1 - n`. -/
theorem m_mem_piece (MM : AInfinityRightModule AA M) (n : ℕ) {x : M} {p : ℤ}
    (hx : x ∈ MM.grading.piece p) (a : Fin n → A) (d : Fin n → ℤ)
    (ha : ∀ i, a i ∈ AA.grading.piece (d i)) :
    MM.m (n + 1) x a ∈ MM.grading.piece (p + ∑ i, d i + (1 - n)) := by
  have h := unsuspend_mem_piece MM.grading AA.grading n 1
    (fun hx a d ha ↦ MM.isHomogeneous_b_tmul_tprod n hx a d ha) hx a d ha
  -- Reading the output of `b_{n+1}^M` in the unshifted grading of `M` adds one to its degree.
  rw [InternalGrading.shift_piece, sub_self, add_zero] at h
  have hdeg : p + ∑ i, d i + (1 - n) = p + ∑ i, d i - n + 1 := by ring
  rw [hdeg]
  exact h

end Unsuspended

section OfTaylor

attribute [local instance] Comodule.cofree

variable (AA) in
/-- The coderivation over the bar differential of `AA` generated by a map `F : sM ⊗ Tᶜ(sA) → sM`:
the cofree comodule lift of `F`, which on `x ⊗ w` applies `F` to each prefix of the
deconcatenation of `w`, plus the algebra bar differential applied to `w`, with the Koszul sign of
moving it past the suspended module input. -/
noncomputable def gradedCoderiv (G : InternalGrading R M)
    (F : (M ⊗[R] TensorWords R A) →ₗ[R] M) :
    (M ⊗[R] TensorWords R A) →ₗ[R] M ⊗[R] TensorWords R A :=
  (Comodule.Hom.cofreeLift (C := TensorWords R A) F).toLinearMap +
    AA.coaugmentedBarDifferential.lTensor M ∘ₗ
      ((G.shift 1).koszulTwist 1).rTensor (TensorWords R A)

variable (AA) in
/-- The coderivation generated by `F` applies `F` after deconcatenation, and adds the
Koszul-twisted algebra bar differential. -/
theorem gradedCoderiv_def (G : InternalGrading R M) (F : (M ⊗[R] TensorWords R A) →ₗ[R] M) :
    gradedCoderiv AA G F =
      F.rTensor (TensorWords R A) ∘ₗ
          (TensorProduct.assoc R M (TensorWords R A) (TensorWords R A)).symm.toLinearMap ∘ₗ
            (deconcatenation R A).lTensor M +
        AA.coaugmentedBarDifferential.lTensor M ∘ₗ
          ((G.shift 1).koszulTwist 1).rTensor (TensorWords R A) :=
  (rfl)

variable (AA) in
/-- The coderivation generated by `F` on the word `x ⊗ a₀ ⊗ ⋯ ⊗ aₙ₋₁`: the sum over the cuts of
the word of `F` applied to the prefix, tensored with the suffix, plus the Koszul-twisted module
input tensored with the algebra bar differential of the word. -/
theorem gradedCoderiv_tmul_of_tprod (G : InternalGrading R M)
    (F : (M ⊗[R] TensorWords R A) →ₗ[R] M) (n : ℕ) (x : M) (a : Fin n → A) :
    gradedCoderiv AA G F (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a)) =
      ∑ k ∈ Finset.range (n + 1), F (x ⊗ₜ[R] subword R a 0 k) ⊗ₜ[R] subword R a k (n - k) +
        (G.shift 1).koszulTwist 1 x ⊗ₜ[R]
          AA.coaugmentedBarDifferential (TensorWords.of R A n (PiTensorProduct.tprod R a)) := by
  rw [gradedCoderiv, LinearMap.add_apply, cofreeLift_tmul_of_tprod, LinearMap.comp_apply,
    LinearMap.rTensor_tmul, LinearMap.lTensor_tmul]

/-- The bar grading is the tensor product of the suspended module grading and the suspended
tensor-word grading. -/
private theorem barGrading_eq (G : InternalGrading R M) :
    barGrading AA G =
      (G.shift 1).tensorProduct (TensorWords.grading (AA.grading.shift 1)) := by
  ext p
  rw [barGrading_piece]

/-- The coderivation generated by a degree-one map has degree one. -/
theorem isHomogeneous_gradedCoderiv (G : InternalGrading R M)
    {F : (M ⊗[R] TensorWords R A) →ₗ[R] M}
    (hF : LinearMap.IsHomogeneous F (barGrading AA G).piece (G.shift 1).piece 1) :
    LinearMap.IsHomogeneous (gradedCoderiv AA G F) (barGrading AA G).piece
      (barGrading AA G).piece 1 := by
  rw [barGrading_eq] at hF ⊢
  have hid := LinearMap.isHomogeneous_id (R := R) (G.shift 1).piece
  let W := TensorWords.grading (AA.grading.shift 1)
  have hwid := LinearMap.isHomogeneous_id (R := R) W.piece
  have hL := (hF.tensorProduct hwid).comp
    ((InternalGrading.isHomogeneous_assoc_symm (G.shift 1) W W).comp
      (hid.tensorProduct (isHomogeneous_deconcatenation (AA.grading.shift 1))))
  have htw : LinearMap.IsHomogeneous ((G.shift 1).koszulTwist 1) (G.shift 1).piece
      (G.shift 1).piece 0 := LinearMap.isHomogeneous_def.2 fun _ _ hx ↦ by
    simpa only [add_zero] using (G.shift 1).koszulTwist_mem_piece hx 1
  have hb : LinearMap.IsHomogeneous AA.coaugmentedBarDifferential W.piece W.piece 1 := by
    simpa only [W, grading_piece] using AA.isHomogeneous_coaugmentedBarDifferential
  have hH := (hid.tensorProduct hb).comp (htw.tensorProduct hwid)
  simp only [add_zero, zero_add] at hL hH
  exact hL.add hH

/-- The coderivation generated by any map is a coderivation over the algebra bar differential:
its first summand is the comodule morphism lifting `F` along the cofree coaction, and its second
summand satisfies the co-Leibniz law because the algebra bar differential does. -/
theorem isGradedCoderivationOver_gradedCoderiv (G : InternalGrading R M)
    (F : (M ⊗[R] TensorWords R A) →ₗ[R] M) :
    Comodule.IsGradedCoderivationOver (barGrading AA G) 1 AA.coaugmentedBarDifferential
      (gradedCoderiv AA G F) := by
  let C := TensorWords R A
  let ρ := Comodule.coact (R := R) (C := C) (M := M ⊗[R] C)
  let L : M ⊗[R] C →ₗ[R] M ⊗[R] C := F.rTensor C ∘ₗ ρ
  let H : M ⊗[R] C →ₗ[R] M ⊗[R] C :=
    AA.coaugmentedBarDifferential.lTensor M ∘ₗ ((G.shift 1).koszulTwist 1).rTensor C
  let E := AA.coaugmentedBarDifferential.lTensor (M ⊗[R] C) ∘ₗ
    ((barGrading AA G).koszulTwist 1).rTensor C
  have hL : ρ ∘ₗ L = L.rTensor C ∘ₗ ρ :=
    (Comodule.Hom.cofreeLift (C := C) (P := M ⊗[R] C) F).map_coact_eq.symm
  have htw : (barGrading AA G).koszulTwist 1 =
      TensorProduct.map ((G.shift 1).koszulTwist 1) (map ((AA.grading.shift 1).koszulTwist 1)) := by
    rw [barGrading_eq, InternalGrading.koszulTwist_tensorProduct, koszulTwist_grading]
  have hH : ρ ∘ₗ H = H.rTensor C ∘ₗ ρ + E ∘ₗ ρ := by
    refine TensorProduct.ext' fun x w ↦ ?_
    have key : ∀ t : C ⊗[R] C,
        (TensorProduct.assoc R M C C).symm ((G.shift 1).koszulTwist 1 x ⊗ₜ[R]
          (AA.coaugmentedBarDifferential.rTensor C t +
            AA.coaugmentedBarDifferential.lTensor C
              ((map ((AA.grading.shift 1).koszulTwist 1)).rTensor C t))) =
          H.rTensor C ((TensorProduct.assoc R M C C).symm (x ⊗ₜ[R] t)) +
            E ((TensorProduct.assoc R M C C).symm (x ⊗ₜ[R] t)) := by
      intro t
      induction t using TensorProduct.inductionOn with
      | tmul u v =>
        simp only [H, E, htw, LinearMap.rTensor_tmul, LinearMap.lTensor_tmul,
          TensorProduct.assoc_symm_tmul, TensorProduct.tmul_add, map_add, LinearMap.comp_apply,
          TensorProduct.map_tmul]
      | add t t' ht ht' =>
        simp only [map_add, TensorProduct.tmul_add] at ht ht' ⊢
        convert congrArg₂ (· + ·) ht ht' using 1 <;> abel
    have hcomul : ∀ v : C, (CoalgebraStruct.comul v : C ⊗[R] C) = deconcatenation R A v :=
      fun v ↦ LinearMap.congr_fun (comul_eq_deconcatenation R A) v
    simp only [LinearMap.comp_apply, LinearMap.add_apply, ρ, Comodule.cofree_coact_tmul, H,
      LinearMap.lTensor_tmul, LinearMap.rTensor_tmul, hcomul,
      AA.isGradedCoderivation_coaugmentedBarDifferential.deconcatenation_apply]
    exact key _
  have hD : ρ ∘ₗ (L + H) = (L + H).rTensor C ∘ₗ ρ + E ∘ₗ ρ := by
    rw [LinearMap.comp_add, hL, hH, LinearMap.rTensor_add, LinearMap.add_comp, add_assoc]
  have hLH : gradedCoderiv AA G F = L + H := (rfl)
  rw [Comodule.isGradedCoderivationOver_iff_coact_apply, hLH]
  exact fun z ↦ LinearMap.congr_fun hD z

/-- Applying the coalgebra counit after the coderivation generated by `F` recovers `F`: the
algebra bar differential has no counit component. -/
theorem rid_comp_lTensor_counit_comp_gradedCoderiv (G : InternalGrading R M)
    (F : (M ⊗[R] TensorWords R A) →ₗ[R] M) :
    (TensorProduct.rid R M).toLinearMap ∘ₗ
        (Coalgebra.counit (R := R) (A := TensorWords R A)).lTensor M ∘ₗ gradedCoderiv AA G F =
      F := by
  have hb : Coalgebra.counit (R := R) (A := TensorWords R A) ∘ₗ AA.coaugmentedBarDifferential =
      0 := LinearMap.ext fun w ↦ by
    rw [LinearMap.comp_apply, AA.coaugmentedBarDifferential_def, extendReduced_apply,
      counit_eq_counit, counit_reducedInclusion, LinearMap.zero_apply]
  have hL := (Comodule.Hom.cofreeEquiv (R := R) (C := TensorWords R A) (M := M)
    (P := M ⊗[R] TensorWords R A)).apply_symm_apply F
  rw [Comodule.Hom.cofreeEquiv_symm_apply, Comodule.Hom.cofreeEquiv_apply,
    Comodule.Hom.cofreeLift_toLinearMap] at hL
  rw [gradedCoderiv_def, LinearMap.comp_add, LinearMap.comp_add, ← LinearMap.comp_assoc
    (((G.shift 1).koszulTwist 1).rTensor (TensorWords R A)), ← LinearMap.lTensor_comp, hb,
    LinearMap.lTensor_zero, LinearMap.zero_comp, LinearMap.comp_zero, add_zero]
  exact hL

/-- Construct a right `A∞` module from a degree-one Taylor map whose generated coderivation squares
to zero.  By cofreeness, the square-zero law is checked on the Taylor component. -/
noncomputable def ofTaylor (G : InternalGrading R M) (F : (M ⊗[R] TensorWords R A) →ₗ[R] M)
    (hF : LinearMap.IsHomogeneous F (barGrading AA G).piece (G.shift 1).piece 1)
    (hsq : F ∘ₗ gradedCoderiv AA G F = 0) : AInfinityRightModule AA M :=
  ofBarDifferential G (gradedCoderiv AA G F) (isHomogeneous_gradedCoderiv G hF)
    (isGradedCoderivationOver_gradedCoderiv G F)
    (by rw [rid_comp_lTensor_counit_comp_gradedCoderiv, hsq])

/-- The grading of the module built from a Taylor map is the given grading. -/
@[simp]
theorem ofTaylor_grading (G : InternalGrading R M) (F : (M ⊗[R] TensorWords R A) →ₗ[R] M)
    (hF : LinearMap.IsHomogeneous F (barGrading AA G).piece (G.shift 1).piece 1)
    (hsq : F ∘ₗ gradedCoderiv AA G F = 0) : (ofTaylor G F hF hsq).grading = G :=
  ofBarDifferential_grading _ _ _ _ _

/-- The bar differential of the module built from a Taylor map is the coderivation it
generates. -/
@[simp]
theorem ofTaylor_barDifferential (G : InternalGrading R M)
    (F : (M ⊗[R] TensorWords R A) →ₗ[R] M)
    (hF : LinearMap.IsHomogeneous F (barGrading AA G).piece (G.shift 1).piece 1)
    (hsq : F ∘ₗ gradedCoderiv AA G F = 0) :
    (ofTaylor G F hF hsq).barDifferential = gradedCoderiv AA G F :=
  ofBarDifferential_barDifferential _ _ _ _ _

/-- The Taylor map of the module built from a Taylor map is that map. -/
@[simp]
theorem ofTaylor_taylor (G : InternalGrading R M) (F : (M ⊗[R] TensorWords R A) →ₗ[R] M)
    (hF : LinearMap.IsHomogeneous F (barGrading AA G).piece (G.shift 1).piece 1)
    (hsq : F ∘ₗ gradedCoderiv AA G F = 0) : (ofTaylor G F hF hsq).taylor = F := by
  rw [ofTaylor, ofBarDifferential_taylor, rid_comp_lTensor_counit_comp_gradedCoderiv]

/-- The bar differential is the coderivation generated by the Taylor map: on `x ⊗ w` it applies
the Taylor map to each prefix of the deconcatenation of `w`, and adds the algebra bar differential
applied to `w`, with the Koszul sign of moving it past the suspended module input. -/
theorem barDifferential_eq (MM : AInfinityRightModule AA M) :
    MM.barDifferential = gradedCoderiv AA MM.grading MM.taylor :=
  MM.isGradedCoderivation_barDifferential.eq_of_counit_comp_eq (barGrading AA MM.grading)
    AA.coaugmentedBarDifferential _ _ (isGradedCoderivationOver_gradedCoderiv _ _)
    (by rw [rid_comp_lTensor_counit_comp_gradedCoderiv, taylor_def])

/-- The Taylor map vanishes after the coderivation it generates. -/
theorem taylor_comp_gradedCoderiv (MM : AInfinityRightModule AA M) :
    MM.taylor ∘ₗ gradedCoderiv AA MM.grading MM.taylor = 0 := by
  rw [← barDifferential_eq, taylor_comp_barDifferential]

/-- Every right `A∞` module is built from its own Taylor map. -/
@[simp]
theorem ofTaylor_self (MM : AInfinityRightModule AA M) :
    ofTaylor MM.grading MM.taylor MM.isHomogeneous_taylor MM.taylor_comp_gradedCoderiv = MM :=
  ext (ofTaylor_grading _ _ _ _) (ofTaylor_taylor _ _ _ _)

end OfTaylor

section ComponentEquations

attribute [local instance] Comodule.cofree

/-- The module Stasheff law in operator form: the Taylor map applied after the Taylor map on each
prefix, plus the Taylor map applied after the algebra bar differential, vanishes. -/
theorem taylor_comp_rTensor_taylor_add_taylor_comp_lTensor_eq_zero
    (MM : AInfinityRightModule AA M) :
    MM.taylor ∘ₗ MM.taylor.rTensor (TensorWords R A) ∘ₗ
          (TensorProduct.assoc R M (TensorWords R A) (TensorWords R A)).symm.toLinearMap ∘ₗ
            (deconcatenation R A).lTensor M +
        MM.taylor ∘ₗ AA.coaugmentedBarDifferential.lTensor M ∘ₗ
          ((MM.grading.shift 1).koszulTwist 1).rTensor (TensorWords R A) = 0 := by
  rw [← LinearMap.comp_add, ← gradedCoderiv_def, ← barDifferential_eq,
    taylor_comp_barDifferential]

/-- The suspended module Stasheff equation of arity `n + 1`, on the word `x ⊗ a₀ ⊗ ⋯ ⊗ aₙ₋₁`:
the sum over the cuts of the word of the Taylor map applied after the Taylor map on the prefix,
plus the Taylor map applied after the algebra bar differential of the word, vanishes. -/
theorem stasheff_tmul_of_tprod (MM : AInfinityRightModule AA M) (n : ℕ) (x : M)
    (a : Fin n → A) :
    ∑ k ∈ Finset.range (n + 1),
        MM.taylor (MM.taylor (x ⊗ₜ[R] subword R a 0 k) ⊗ₜ[R] subword R a k (n - k)) +
      MM.taylor ((MM.grading.shift 1).koszulTwist 1 x ⊗ₜ[R]
        AA.coaugmentedBarDifferential (TensorWords.of R A n (PiTensorProduct.tprod R a))) = 0 := by
  have h := LinearMap.congr_fun MM.taylor_comp_gradedCoderiv
    (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a))
  rwa [LinearMap.comp_apply, gradedCoderiv_tmul_of_tprod, map_add, map_sum,
    LinearMap.zero_apply] at h

/-- The suspended module Stasheff equation of arity `n + 1`, with the algebra bar differential
expanded: its terms collapse each nonempty block of letters by the algebra Taylor map, twisting the
letters before the block. -/
theorem stasheff_tmul_of_tprod_splice (MM : AInfinityRightModule AA M) (n : ℕ) (x : M)
    (a : Fin n → A) :
    ∑ k ∈ Finset.range (n + 1),
        MM.taylor (MM.taylor (x ⊗ₜ[R] subword R a 0 k) ⊗ₜ[R] subword R a k (n - k)) +
      ∑ p ∈ Finset.range n, ∑ s ∈ Finset.Icc 1 (n - p),
        MM.taylor ((MM.grading.shift 1).koszulTwist 1 x ⊗ₜ[R]
          reducedInclusion R A
            (ReducedTensorWords.splice R
              (InternalGrading.twistedTuple (AA.grading.shift 1) 1 a 0 p) 0 n p s
              (AA.taylor (ReducedTensorWords.subword R a p s)))) = 0 := by
  rw [← apply_coaugmentedBarDifferential_of_tprod]
  exact MM.stasheff_tmul_of_tprod n x a

/-- The suspended module Stasheff expression of a Taylor map `F` evaluating a family `m` on
Koszul-twisted inputs is, on homogeneous inputs, the unsuspended module Stasheff expression of `m`
multiplied by the Koszul sign of suspending all the inputs. -/
private theorem suspendedStasheff_eq_smul {G : InternalGrading R M}
    {F : (M ⊗[R] TensorWords R A) →ₗ[R] M}
    {m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M}
    (hFm : ∀ (n : ℕ) (x : M) (a : Fin n → A),
      F (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a)) =
        m (n + 1) (G.koszulTwist n x)
          fun i : Fin n ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i))
    (hm : ∀ (n : ℕ) {x : M} {p : ℤ}, x ∈ G.piece p → ∀ (a : Fin n → A) (d : Fin n → ℤ),
      (∀ i, a i ∈ AA.grading.piece (d i)) → m (n + 1) x a ∈ G.piece (p + ∑ i, d i + (1 - n)))
    (n : ℕ) {x : M} {e : ℤ} (hx : x ∈ G.piece e) (d : ℕ → ℤ) (a : ℕ → A)
    (ha : ∀ i < n, a i ∈ AA.grading.piece (d i)) :
    ∑ k ∈ Finset.range (n + 1),
        F (F (x ⊗ₜ[R] subword R (fun i : Fin n ↦ a i) 0 k) ⊗ₜ[R]
          subword R (fun i : Fin n ↦ a i) k (n - k)) +
      F ((G.shift 1).koszulTwist 1 x ⊗ₜ[R] AA.coaugmentedBarDifferential
        (TensorWords.of R A n (PiTensorProduct.tprod R fun i : Fin n ↦ a i))) =
      negOnePowCast R (n * e + suspExp n d) •
        (∑ k ∈ Finset.range (n + 1),
            negOnePowCast R (((k : ℤ) + 1) * ((n : ℤ) - k)) •
              evalNat (m (n - k + 1) (evalNat (m (k + 1) x) a)) (fun j ↦ a (k + j)) +
          ∑ p ∈ Finset.range n, ∑ s ∈ Finset.Icc 1 (n - p),
            negOnePowCast R ((p : ℤ) + 1 + s * ((n : ℤ) - p - s) +
                (2 - s) * (e + ∑ i ∈ Finset.range p, d i)) •
              evalNat (m (p + 1 + (n - p - s) + 1) x)
                (replaceBlock a p s (evalNat (AA.m s) fun j ↦ a (p + j)))) := by
  rw [apply_coaugmentedBarDifferential_of_tprod F n ((G.shift 1).koszulTwist 1 x)
      (fun i : Fin n ↦ a i),
    Finset.sum_congr rfl fun k hk ↦
      apply_comp_subword_of_mem (f := fun r ↦ m (r + 1)) (h := fun r ↦ m (r + 1))
        hFm hm hFm (q := 1) (Nat.lt_succ_iff.1 (Finset.mem_range.1 hk)) hx d a ha,
    Finset.sum_congr rfl fun p hp ↦ Finset.sum_congr rfl fun s hs ↦
      apply_algebra_splice_of_mem (f := fun r ↦ m (r + 1)) hFm (Finset.mem_Icc.1 hs).1
        (by have := (Finset.mem_Icc.1 hs).2; have := Finset.mem_range.1 hp; omega) hx d a ha]
  simp only [← Finset.smul_sum, ← smul_add]

/-- **The unsuspended module Stasheff equation** of arity `n + 1`, on a homogeneous module input
`x` of degree `e` and homogeneous algebra inputs `a 0, …, a (n - 1)` of degrees `d`.  Indexing
the inputs `x, a 0, …, a (n - 1)` by `0, …, n`, the term in which an operation of arity `s`
collapses the block starting at position `r` carries the sign `(-1) ^ (r + s * t)`, with `t`
inputs after the block, times the Koszul sign of the degree-`2 - s` inner operation crossing the
`r` inputs before it.  The first sum collects the terms with `r = 0`, whose inner operation is
`m (k + 1)` of `MM`, and the second those with `r = p + 1`, whose inner operation is `m s` of
`AA`. -/
theorem stasheff (MM : AInfinityRightModule AA M) (n : ℕ) {x : M} {e : ℤ}
    (hx : x ∈ MM.grading.piece e) (d : ℕ → ℤ) (a : ℕ → A)
    (ha : ∀ i < n, a i ∈ AA.grading.piece (d i)) :
    ∑ k ∈ Finset.range (n + 1),
        negOnePowCast R (((k : ℤ) + 1) * ((n : ℤ) - k)) •
          evalNat (MM.m (n - k + 1) (evalNat (MM.m (k + 1) x) a)) (fun j ↦ a (k + j)) +
      ∑ p ∈ Finset.range n, ∑ s ∈ Finset.Icc 1 (n - p),
        negOnePowCast R ((p : ℤ) + 1 + s * ((n : ℤ) - p - s) +
            (2 - s) * (e + ∑ i ∈ Finset.range p, d i)) •
          evalNat (MM.m (p + 1 + (n - p - s) + 1) x)
            (replaceBlock a p s (evalNat (AA.m s) fun j ↦ a (p + j))) = 0 := by
  have h := MM.stasheff_tmul_of_tprod n x fun i : Fin n ↦ a i
  rw [suspendedStasheff_eq_smul MM.taylor_tmul_of_tprod MM.m_mem_piece n hx d a ha] at h
  exact (negOnePowCast_smul_eq_zero_iff _ _).1 h

/-- The unsuspended module Stasheff equation of arity one: the unary module operation squares to
zero. -/
theorem stasheff_arity_one (MM : AInfinityRightModule AA M) (x : M) (a c : Fin 0 → A) :
    MM.m 1 (MM.m 1 x a) c = 0 := by
  have hone : ∀ e : Fin 0 → A, TensorWords.of R A 0 (PiTensorProduct.tprod R e) = 1 :=
    fun e ↦ by
      rw [one_eq_of_zero]
      exact of_tprod_congr R A fun j ↦ j.elim0
  have h := MM.stasheff_tmul_of_tprod 0 x a
  rw [hone, AA.coaugmentedBarDifferential_one, TensorProduct.tmul_zero, map_zero, add_zero,
    Finset.sum_range_one, Nat.sub_self, subword_length_zero R a le_rfl] at h
  rw [m_apply MM 0, m_apply MM 0, ← taylor_tmul_of, ← taylor_tmul_of, hone, hone, Nat.cast_zero,
    InternalGrading.koszulTwist_zero, LinearMap.id_apply, LinearMap.id_apply, h]

/-- On the empty algebra word, the Taylor map is the unsuspended unary operation. -/
theorem taylor_tmul_one (MM : AInfinityRightModule AA M) (x : M) (a : Fin 0 → A) :
    MM.taylor (x ⊗ₜ[R] (1 : TensorWords R A)) = MM.m 1 x a := by
  have hone (e : Fin 0 → A) : TensorWords.of R A 0 (PiTensorProduct.tprod R e) = 1 := by
    rw [TensorWords.of_tprod_eq_subword, TensorWords.subword_length_zero R e le_rfl]
  rw [m_apply MM 0, Nat.cast_zero, InternalGrading.koszulTwist_zero, LinearMap.id_apply,
    ← taylor_tmul_of, hone]

/-- On the empty algebra word, the bar differential is the unary module operation tensored
with the empty word. -/
theorem barDifferential_tmul_one (MM : AInfinityRightModule AA M) (x : M) :
    MM.barDifferential (x ⊗ₜ[R] (1 : TensorWords R A)) =
      MM.taylor (x ⊗ₜ[R] (1 : TensorWords R A)) ⊗ₜ[R] (1 : TensorWords R A) := by
  rw [barDifferential_eq, gradedCoderiv_def]
  simp only [LinearMap.add_apply, LinearMap.comp_apply, LinearMap.lTensor_tmul,
    TensorWords.deconcatenation_one, LinearEquiv.coe_coe, TensorProduct.assoc_symm_tmul,
    LinearMap.rTensor_tmul, AA.coaugmentedBarDifferential_one, TensorProduct.tmul_zero, add_zero]

end ComponentEquations

section OfStasheff

attribute [local instance] Comodule.cofree

/-- A Taylor map evaluating a family of operations of degree `1 - n` in arity `n + 1` on
Koszul-twisted inputs has degree one. -/
private theorem isHomogeneous_of_apply_tmul_of_tprod {G : InternalGrading R M}
    {F : (M ⊗[R] TensorWords R A) →ₗ[R] M}
    {m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M}
    (hFm : ∀ (n : ℕ) (x : M) (a : Fin n → A),
      F (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a)) =
        m (n + 1) (G.koszulTwist n x)
          fun i : Fin n ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i))
    (hm : ∀ (n : ℕ) {x : M} {p : ℤ}, x ∈ G.piece p → ∀ (a : Fin n → A) (d : Fin n → ℤ),
      (∀ i, a i ∈ AA.grading.piece (d i)) → m (n + 1) x a ∈ G.piece (p + ∑ i, d i + (1 - n))) :
    LinearMap.IsHomogeneous F (barGrading AA G).piece (G.shift 1).piece 1 := by
  rw [LinearMap.isHomogeneous_def]
  intro p z hz
  rw [barGrading_piece, InternalGrading.tensorProduct_piece_eq_iSup] at hz
  refine (iSup_le fun q ↦ Submodule.map₂_le.2 fun x hx w hw ↦ ?_ :
    _ ≤ ((G.shift 1).piece (p + 1)).comap F) hz
  rw [TensorProduct.mk_apply, Submodule.mem_comap]
  rw [InternalGrading.shift_piece] at hx
  rw [TensorWords.grading_piece] at hw
  refine gradedPiece_induction (motive := fun w ↦ F (x ⊗ₜ[R] w) ∈ (G.shift 1).piece (p + 1)) hw
    ?_ (by rw [TensorProduct.tmul_zero, map_zero]; exact zero_mem _) ?_ ?_
  · intro n 𝒟 a ha hsum
    have ha' : ∀ i, AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i) ∈
        AA.grading.piece (𝒟 i + 1) := fun i ↦
      AA.grading.koszulTwist_mem_piece (by simpa only [InternalGrading.shift_piece] using ha i) _
    have h := hm n (G.koszulTwist_mem_piece hx n) _ _ ha'
    rw [Finset.sum_add_distrib, Finset.sum_const, Finset.card_univ, Fintype.card_fin,
      nsmul_eq_mul, mul_one, hsum] at h
    -- The inputs have total degree `(q + 1) + ((p - q) + n)` in the unshifted gradings, and the
    -- operation of arity `n + 1` lowers it by `n - 1`.
    have hdeg : p + 1 + 1 = q + 1 + (p - q + n) + (1 - n) := by ring
    rw [hFm, InternalGrading.shift_piece, hdeg]
    exact h
  · intro u v _ _ hu hv
    rw [TensorProduct.tmul_add, map_add]
    exact add_mem hu hv
  · intro r u _ hu
    rw [TensorProduct.tmul_smul, map_smul]
    exact Submodule.smul_mem _ r hu

/-- The Taylor map `F` of a family `m` satisfying the unsuspended module Stasheff equations
vanishes after the coderivation it generates. -/
private theorem apply_comp_gradedCoderiv_eq_zero {G : InternalGrading R M}
    {F : (M ⊗[R] TensorWords R A) →ₗ[R] M}
    {m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M}
    (hFm : ∀ (n : ℕ) (x : M) (a : Fin n → A),
      F (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a)) =
        m (n + 1) (G.koszulTwist n x)
          fun i : Fin n ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i))
    (hm : ∀ (n : ℕ) {x : M} {p : ℤ}, x ∈ G.piece p → ∀ (a : Fin n → A) (d : Fin n → ℤ),
      (∀ i, a i ∈ AA.grading.piece (d i)) → m (n + 1) x a ∈ G.piece (p + ∑ i, d i + (1 - n)))
    (hSI : ∀ (n : ℕ) {x : M} {e : ℤ}, x ∈ G.piece e → ∀ (d : ℕ → ℤ) (a : ℕ → A),
      (∀ i < n, a i ∈ AA.grading.piece (d i)) →
        ∑ k ∈ Finset.range (n + 1),
            negOnePowCast R (((k : ℤ) + 1) * ((n : ℤ) - k)) •
              evalNat (m (n - k + 1) (evalNat (m (k + 1) x) a)) (fun j ↦ a (k + j)) +
          ∑ p ∈ Finset.range n, ∑ s ∈ Finset.Icc 1 (n - p),
            negOnePowCast R ((p : ℤ) + 1 + s * ((n : ℤ) - p - s) +
                (2 - s) * (e + ∑ i ∈ Finset.range p, d i)) •
              evalNat (m (p + 1 + (n - p - s) + 1) x)
                (replaceBlock a p s (evalNat (AA.m s) fun j ↦ a (p + j))) = 0) :
    F ∘ₗ gradedCoderiv AA G F = 0 := by
  refine TensorProduct.ext (G.linearMap_ext fun e x hx ↦ DirectSum.linearMap_ext R fun n ↦
    AA.grading.piTensorProduct_ext fun q ↦ ?_)
  let d : ℕ → ℤ := fun i ↦ if h : i < n then (q ⟨i, h⟩).1 else 0
  let a : ℕ → A := fun i ↦ if h : i < n then (q ⟨i, h⟩).2 else 0
  have ha : ∀ i < n, a i ∈ AA.grading.piece (d i) := by
    intro i hi
    simp only [a, d, hi, dite_true]
    exact (q ⟨i, hi⟩).2.property
  have haq : (fun i : Fin n ↦ ((q i).2 : A)) = fun i : Fin n ↦ a i :=
    funext fun i ↦ by simp only [a, i.isLt, dite_true]
  simp only [LinearMap.compr₂ₛₗ_apply, TensorProduct.mk_apply, LinearMap.comp_apply, ← of_def,
    LinearMap.zero_apply]
  rw [haq, gradedCoderiv_tmul_of_tprod, map_add, map_sum,
    suspendedStasheff_eq_smul hFm hm n hx d a ha, hSI n hx d a ha, smul_zero]

/-- Construct a right `A∞` module from unsuspended operations `m` of degree `1 - n` in arity
`n + 1` satisfying the unsuspended module Stasheff equations on homogeneous inputs, together with a
Taylor map `F` evaluating `m` on Koszul-twisted inputs. -/
noncomputable def ofStasheff (G : InternalGrading R M)
    (m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M)
    (hm : ∀ (n : ℕ) {x : M} {p : ℤ}, x ∈ G.piece p → ∀ (a : Fin n → A) (d : Fin n → ℤ),
      (∀ i, a i ∈ AA.grading.piece (d i)) → m (n + 1) x a ∈ G.piece (p + ∑ i, d i + (1 - n)))
    (F : (M ⊗[R] TensorWords R A) →ₗ[R] M)
    (hFm : ∀ (n : ℕ) (x : M) (a : Fin n → A),
      F (x ⊗ₜ[R] TensorWords.of R A n (PiTensorProduct.tprod R a)) =
        m (n + 1) (G.koszulTwist n x)
          fun i : Fin n ↦ AA.grading.koszulTwist ((n : ℤ) - 1 - i) (a i))
    (hSI : ∀ (n : ℕ) {x : M} {e : ℤ}, x ∈ G.piece e → ∀ (d : ℕ → ℤ) (a : ℕ → A),
      (∀ i < n, a i ∈ AA.grading.piece (d i)) →
        ∑ k ∈ Finset.range (n + 1),
            negOnePowCast R (((k : ℤ) + 1) * ((n : ℤ) - k)) •
              evalNat (m (n - k + 1) (evalNat (m (k + 1) x) a)) (fun j ↦ a (k + j)) +
          ∑ p ∈ Finset.range n, ∑ s ∈ Finset.Icc 1 (n - p),
            negOnePowCast R ((p : ℤ) + 1 + s * ((n : ℤ) - p - s) +
                (2 - s) * (e + ∑ i ∈ Finset.range p, d i)) •
              evalNat (m (p + 1 + (n - p - s) + 1) x)
                (replaceBlock a p s (evalNat (AA.m s) fun j ↦ a (p + j))) = 0) :
    AInfinityRightModule AA M :=
  ofTaylor G F (isHomogeneous_of_apply_tmul_of_tprod hFm hm)
    (apply_comp_gradedCoderiv_eq_zero hFm hm hSI)

/-- The grading of the module built from unsuspended operations is the given grading. -/
@[simp]
theorem ofStasheff_grading (G : InternalGrading R M)
    (m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M) (hm F hFm hSI) :
    (ofStasheff (AA := AA) G m hm F hFm hSI).grading = G := by
  rw [ofStasheff, ofTaylor_grading]

/-- The Taylor map of the module built from unsuspended operations is the given Taylor map. -/
@[simp]
theorem ofStasheff_taylor (G : InternalGrading R M)
    (m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M) (hm F hFm hSI) :
    (ofStasheff (AA := AA) G m hm F hFm hSI).taylor = F := by
  rw [ofStasheff, ofTaylor_taylor]

/-- The unsuspended operations of the module built from unsuspended operations `m` are `m`, as
soon as the junk value `m 0` vanishes. -/
@[simp]
theorem ofStasheff_m (G : InternalGrading R M)
    (m : (n : ℕ) → M →ₗ[R] MultilinearMap R (fun _ : Fin (n - 1) ↦ A) M) (hm F hFm hSI)
    (hm0 : m 0 = 0) : (ofStasheff (AA := AA) G m hm F hFm hSI).m = m := by
  funext n
  obtain _ | n := n
  · rw [m_zero, hm0]
  · ext x a
    rw [m_apply, ← taylor_tmul_of, ofStasheff_taylor, ofStasheff_grading, hFm]
    simp only [InternalGrading.koszulTwist_koszulTwist]

end OfStasheff

end AInfinityRightModule

end TauCeti
