/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.SheafCriterion
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.StandardCover.Basic
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.Empty

import Mathlib.CategoryTheory.Functor.KanExtension.Preserves
import Mathlib.CategoryTheory.Sites.Coverage
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.OpenEmbedding
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Refinement
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.KanExtension
import TauCeti.CategoryTheory.Sites.IsSheafFor

/-!
# The sheaf condition for rational covers of rational subsets, and on all opens

Let `C` be a predicate on Tate rings satisfying `TauCeti.ValuationSpectrum.LaurentGluing`: it
passes to completed rational localisations, and on rings satisfying it two-piece Laurent covers of
rational subsets glue. Strong noetherianness is the basic example. Let `A` be a Tate ring
satisfying `C`, `P` a pair of definition whose ring of definition lies in `A⁺`, and `A⁺` a subring
of power-bounded elements. This file proves that the presentation-limit presheaf of
`X = Spa(A, A⁺)`, as a presheaf of sets, satisfies the sheaf condition for every cover of a
rational subset `W ⊆ X` by rational subsets `U i ⊆ W`
(`isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_of_laurentGluing`): sections over the `U i` that
agree on the pairwise overlaps glue uniquely to a section over `W`. The cover may be infinite.

This is Wedhorn's Lemma 8.34 in degree zero for an arbitrary rational cover. Following Wedhorn, the
statement is reduced to standard rational covers, for which it is
`isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing`.

* Write `W = R(T/s)` and `B = A⟨T/s⟩`. Wedhorn's Remark 8.4
  (`isSheafFor_ofArrows_iff_locOpensComap`) transports the sheaf condition to the pullbacks of the
  `U i` along `j : Spa(B, A_U⁺) → Spa(A, A⁺)`, which cover all of `Spa(B, A_U⁺)`. The ring `B`
  is again a Tate ring satisfying `C`, now complete and Hausdorff, and `A_U⁺` is a ring of
  integral elements of `B`.
* Over a complete Hausdorff Tate ring, Wedhorn's Lemma 7.54
  (`exists_span_eq_top_forall_rationalSubset_subset_of_isTateRing`) refines a cover of the whole
  adic spectrum by a standard rational cover `(R(S/f))_{f ∈ S}`, with `S` generating the unit
  ideal. That standard cover satisfies the sheaf condition, and so does its restriction to each
  `U i`, which is the standard cover of `U i` generated by `S`. Hence so does the original cover.

Intersections of rational opens are rational, so gluing along rational covers of rational opens is
the sheaf condition on the basis of rational opens (`isSheaf_rational_comp_of_isSheafFor_ofArrows`).
Since the presentation-limit presheaf is the limit of its values on that basis, the presheaf of
sets underlying it is then a sheaf on all opens
(`isSheaf_underlying_presentationLimitPresheaf_of_laurentGluing`).

The statements concern the sheaf condition in degree zero, for the presentation-limit presheaf as a
presheaf of sets; neither the topology on the sections nor higher Čech cohomology is treated here.

## Main results

* `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_of_laurentGluing` : a
  cover of a rational subset by rational subsets satisfies the sheaf condition, over a Tate ring
  satisfying a predicate with `LaurentGluing`.
* `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq` : the same over a
  strongly noetherian Tate ring.
* `TauCeti.ValuationSpectrum.isSheaf_rational_comp_of_isSheafFor_ofArrows` : gluing along rational
  covers of rational opens is the sheaf condition on the basis of rational opens.
* `TauCeti.ValuationSpectrum.isSheaf_underlying_presentationLimitPresheaf_of_laurentGluing` : over
  a Tate ring satisfying a predicate with `LaurentGluing`, the presheaf of sets underlying the
  presentation-limit presheaf is a sheaf.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Remark 8.4, Lemma 7.54,
  Lemma 8.34 and Theorem 8.28.
* R. Huber, *A generalization of formal schemes and rigid analytic varieties*, Math. Z. 217 (1994),
  Lemma 2.6 and Theorem 2.5.
-/

public section

open CategoryTheory TopologicalSpace TauCeti.Huber TauCeti.Huber.PairOfDefinition

universe v w

namespace TauCeti.ValuationSpectrum

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  (P : PairOfDefinition A) {Aplus : Subring A}
  {C : ∀ (A : Type v) [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A], Prop}

/-- The case of a cover of the whole adic spectrum of a complete Hausdorff ring, with `A⁺` a ring
of integral elements: Wedhorn's Lemma 7.54 refines the cover by a standard rational cover, to which
`isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing` applies. The open `W` is
`⊤`, but is kept as a variable so that the lemma applies to opens that are only propositionally
`⊤`. -/
private theorem isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_top (hC : LaurentGluing C)
    (hA : C A) [IsUniformAddGroup A] [CompleteSpace A] [T2Space A] (hP : P.ringOfDefinition ≤ Aplus)
    (hplus : IsRingOfIntegralElements Aplus) {W : Opens ↥(spa Aplus)} (hW : W = ⊤) {ι : Type*}
    [Nonempty ι] {U : ι → Opens ↥(spa Aplus)} (hU : ∀ i, U i ∈ spaRationalOpens Aplus)
    (hcov : ⨆ i, U i = W) :
    (Presieve.ofArrows U fun i ↦ homOfLE ((le_iSup U i).trans_eq hcov)).IsSheafFor
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        forget _root_.TopCommRingCat) := by
  classical
  subst hW
  -- a standard rational cover `(R(S/f))_{f ∈ S}` refining the `U i` (Wedhorn's Lemma 7.54)
  obtain ⟨S, hS, hSU⟩ := exists_span_eq_top_forall_rationalSubset_subset_of_isTateRing Aplus hplus
    (fun i ↦ (U i : Set ↥(spa Aplus))) (fun i ↦ (U i).isOpen) (by
      rw [← Opens.coe_iSup, hcov, Opens.coe_top])
  rcases S.eq_empty_or_nonempty with rfl | hSne
  · -- `S = ∅` generates the unit ideal only over the zero ring, whose adic spectrum is empty, so
    -- the cover contains the identity
    have hspa : spa Aplus = ∅ := by
      simpa using spa_eq_biUnion_rationalSubset_of_span_eq_top Aplus hS
    obtain ⟨i⟩ := ‹Nonempty ι›
    have hle : ⊤ ≤ U i := fun v _ ↦ absurd v.2 (by simp [hspa])
    rw [Presieve.isSheafFor_iff_generate, (Sieve.id_mem_iff_eq_top (S := Sieve.generate _)).mp
      ⟨_, homOfLE hle, _, Presieve.ofArrows.mk i, rfl⟩]
    exact Presieve.isSheafFor_top _
  have hAplus := hplus.isPowerBounded_of_mem
  -- the standard cover of `⊤` generated by `S` satisfies the sheaf condition and refines the `U i`;
  -- on each `U i`, the standard cover of `U i` generated by `S` is separated and refines it
  refine Presieve.isSheafFor_of_factorsThru _
    (S := Presieve.ofArrows (fun f : S ↦ ⊤ ⊓ spaBasicOpen Aplus S f) fun _ ↦ homOfLE inf_le_left)
    (fun V g hg ↦ ?_) (isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing P hC hA
      hP hAplus hSne hS (top_mem_spaRationalOpens Aplus)) fun V g hg ↦ ?_
  · obtain ⟨f⟩ := hg
    obtain ⟨i, hi⟩ := hSU f f.2
    exact ⟨U i, homOfLE fun v hv ↦ hi (mem_spaBasicOpen.mp hv.2), homOfLE le_top,
      Presieve.ofArrows.mk i, rfl⟩
  · obtain ⟨i⟩ := hg
    refine ⟨Presieve.ofArrows (fun f : S ↦ U i ⊓ spaBasicOpen Aplus S f)
      fun _ ↦ homOfLE inf_le_left,
      (isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing P hC hA hP hAplus
        hSne hS (hU i)).isSeparatedFor, fun Z g hg ↦ ?_⟩
    obtain ⟨f⟩ := hg
    exact ⟨_, homOfLE (inf_le_inf_right _ le_top), homOfLE inf_le_left, Presieve.ofArrows.mk f,
      rfl⟩

/-- **Wedhorn's Lemma 8.34 in degree zero: rational covers of rational subsets.** Let `C` be a
predicate on Tate rings satisfying `LaurentGluing`, and `A` a Tate ring satisfying `C`. Let `P` be
a pair of definition whose ring of definition lies in `A⁺`, `A⁺` a subring of power-bounded
elements and `W` a rational subset of `Spa(A, A⁺)`. Let `(U i)` be a family of rational subsets of
`W` whose union is `W`. The presentation-limit presheaf, as a presheaf of sets, satisfies the sheaf
condition for this cover: sections over the `U i` that agree on the pairwise overlaps glue uniquely
to a section over `W`.

`A` itself need not be complete, and the family may be infinite or empty. An empty family covers
the empty open, whose sections form a singleton. -/
theorem isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_of_laurentGluing
    (hC : LaurentGluing C) (hA : C A) (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) {ι : Type*} {U : ι → Opens ↥(spa Aplus)}
    (hU : ∀ i, U i ∈ spaRationalOpens Aplus) (hcov : ⨆ i, U i = W) :
    (Presieve.ofArrows U fun i ↦ homOfLE ((le_iSup U i).trans_eq hcov)).IsSheafFor
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        forget _root_.TopCommRingCat) := by
  cases isEmpty_or_nonempty ι with
  | inl hempty =>
    have hbot : W = ⊥ := by simpa using hcov.symm
    subst hbot
    have := subsingleton_presentationLimit_bot P hAplus
    rw [isSheafFor_ofArrows_iff_existsUnique_presentationLimitMap]
    exact fun _ _ ↦ ⟨0, fun i ↦ isEmptyElim i, fun _ _ ↦ Subsingleton.elim _ _⟩
  | inr hnonempty =>
    have _ : IsHuberRing A := ⟨⟨P⟩⟩
    obtain ⟨T, s, hT, hWT⟩ := mem_spaRationalFamily_iff.mp (mem_spaRationalOpens.mp hW)
    obtain rfl : W = spaBasicOpen Aplus T s :=
      Opens.ext (hWT.trans (Set.ext fun _ ↦ mem_spaBasicOpen.symm))
    -- `B = A⟨T/s⟩` is a complete Hausdorff Tate ring satisfying `C`, and `A_U⁺` is a ring of
    -- integral elements of `B`
    have hden := hasDenominatorPower_of_isOpen_span P T s (Localization.Away s) hT
    let _ := locUniformSpace P T s _ hden
    have _ := isUniformAddGroup_locUniformSpace P T s _ hden
    have _ := isTopologicalRing_locUniformSpace P T s _ hden
    have _ := isTateRing_completion_locTopology_of_isTateRing P T s _ hden
    have hB : C (UniformSpace.Completion (Localization.Away s)) :=
      hC.completion_localization P T s hT hA
    -- transport to the pullbacks along `Spa(B, A_U⁺) → Spa(A, A⁺)` (Wedhorn's Remark 8.4), which
    -- cover `Spa(B, A_U⁺)`
    rw [isSheafFor_ofArrows_iff_locOpensComap P Aplus T s _ hden hAplus hT hW le_rfl hU
      fun i ↦ (le_iSup U i).trans_eq hcov]
    refine isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_top (completionLocalization P T s _ hden)
      hC hB
      (completionLocalization_ringOfDefinition_le_completedPlusSubring P Aplus hP T s _ hden)
      (isRingOfIntegralElements_completedPlusSubring P Aplus (fun j _ ↦ hP j.2) hAplus T s _ hden)
      (locOpensComap_spaBasicOpen_self P Aplus T s _ hden)
      (fun i ↦ locOpensComap_mem_spaRationalOpens P Aplus T s _ hden (hU i)) ?_
    rw [← hcov]
    exact SetLike.ext fun v ↦ by simp [Opens.mem_iSup]

/-! ### The sheaf condition on all opens -/

/-- **The sheaf condition on the rational basis.** Let `G` be a functor from complete separated
topological rings into types. If the presentation-limit presheaf followed by `G` satisfies the
sheaf condition for every cover of a rational open by rational opens, then its restriction to the
rational opens is a sheaf for the topology restricted from `Spa(A, A⁺)`. Intersections of
rational opens are rational, which is what lets compatibility on the basis stand in for
compatibility on pairwise intersections. -/
theorem isSheaf_rational_comp_of_isSheafFor_ofArrows
    (G : TopCommRingCat.isCompleteSeparated.{v}.FullSubcategory ⥤ Type w)
    (hrat : ∀ {W : Opens ↥(spa Aplus)} {ι : Type v} {U : ι → Opens ↥(spa Aplus)},
      W ∈ spaRationalOpens Aplus → (∀ i, U i ∈ spaRationalOpens Aplus) → ∀ hcov : ⨆ i, U i = W,
      (Presieve.ofArrows U fun i ↦ homOfLE ((le_iSup U i).trans_eq hcov)).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ G)) :
    Presieve.IsSheaf
      ((rationalOpensFunctor Aplus).restrictedTopology (Opens.grothendieckTopology ↥(spa Aplus)))
      ((rationalOpensFunctor Aplus).op ⋙ presentationLimitPresheaf P Aplus ⋙ G) := by
  intro W S hS
  obtain ⟨ι, U, π, rfl⟩ := S.exists_eq_ofArrows
  rw [Functor.mem_restrictedTopology_iff, Sieve.functorPushforward_ofArrows] at hS
  have hcov : ⨆ i, (U i).1 = W.1 := by
    apply le_antisymm (iSup_le fun i ↦ (π i).hom.le)
    intro x hx
    obtain ⟨V, f, hf, hxV⟩ := hS x hx
    obtain ⟨V', g, f', hf', rfl⟩ := hf
    obtain ⟨i⟩ := hf'
    exact Opens.mem_iSup.mpr ⟨i, g.le hxV⟩
  have hrat := hrat W.2 (fun i ↦ (U i).2) hcov
  have hπ (i : ι) : (rationalOpensFunctor Aplus).map (π i) =
      homOfLE ((le_iSup (fun i ↦ (U i).1) i).trans_eq hcov) := Subsingleton.elim _ _
  rw [← Presieve.isSheafFor_iff_generate, Presieve.isSheafFor_arrows_iff]
  rw [Presieve.isSheafFor_arrows_iff] at hrat
  intro x hx
  -- Intersections of rational opens are rational, so compatibility on the basis supplies the
  -- pairwise-intersection compatibility required in the ambient category of opens.
  have hcompat : Presieve.Arrows.Compatible (presentationLimitPresheaf P Aplus ⋙ G)
      (fun i ↦ homOfLE ((le_iSup (fun i ↦ (U i).1) i).trans_eq hcov)) x := by
    apply (Presieve.Arrows.compatible_homOfLE_iff _ _).mpr
    intro i j
    let V : spaRationalOpens Aplus :=
      ⟨(U i).1 ⊓ (U j).1, inf_mem_spaRationalOpens (U i).2 (U j).2⟩
    exact hx i j V (InducedCategory.homMk (homOfLE inf_le_left))
      (InducedCategory.homMk (homOfLE inf_le_right)) (Subsingleton.elim _ _)
  obtain ⟨a, ha, hu⟩ := hrat x hcompat
  refine ⟨a, ?_, ?_⟩
  · intro i
    simpa only [Functor.comp_map, Functor.op_map, Quiver.Hom.unop_op, hπ] using ha i
  · intro b hb
    exact hu b fun i ↦ by
      simpa only [Functor.comp_map, Functor.op_map, Quiver.Hom.unop_op, hπ] using hb i

/-- **The structure presheaf of sets is a sheaf under Laurent gluing.** Let `C` be a predicate on
Tate rings satisfying `LaurentGluing`, and `A` a Tate ring satisfying `C`. If the ring of
definition of `P` lies in `A⁺` and `A⁺` consists of power-bounded elements, the presheaf of sets
underlying the presentation-limit structure presheaf is a sheaf on all opens of `Spa(A, A⁺)`. The
ring need not be complete or Hausdorff. -/
theorem isSheaf_underlying_presentationLimitPresheaf_of_laurentGluing
    (hC : LaurentGluing C) (hA : C A) (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) :
    Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Aplus))
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        forget _root_.TopCommRingCat) := by
  have : IsHuberRing A := ⟨⟨P⟩⟩
  let G := TopCommRingCat.isCompleteSeparated.ι ⋙ forget _root_.TopCommRingCat
  have h := (presentationLimitPresheafIsPointwiseRightKanExtension
    (P := P) (Aplus := Aplus)).postcompose G
  have hAdapted : TopCat.Presheaf.IsAdapted (X := TopCat.of ↥(spa Aplus))
      (presentationLimitPresheaf P Aplus ⋙ G) (spaRationalOpens Aplus) := by
    exact ⟨h⟩
  apply TopCat.Presheaf.isSheaf_of_isAdapted_of_isSheaf_restrictedTopology
    (X := TopCat.of ↥(spa Aplus)) _ _ (isBasis_spaRationalOpens Aplus) hAdapted
  exact (isSheaf_iff_isSheaf_of_type _ _).mpr
    (isSheaf_rational_comp_of_isSheafFor_ofArrows P G fun hW hU hcov ↦
      isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_of_laurentGluing P hC hA hP hAplus hW hU
        hcov)

/-! ### The strongly noetherian case -/

/-- **Wedhorn's Lemma 8.34 in degree zero for a strongly noetherian Tate ring.** Let `A` be a
strongly noetherian Tate ring, `P` a pair of definition whose ring of definition lies in `A⁺`, `A⁺`
a subring of power-bounded elements and `W` a rational subset of `Spa(A, A⁺)`. The
presentation-limit presheaf, as a presheaf of sets, satisfies the sheaf condition for every family
of rational subsets of `W` whose union is `W`. This is
`isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_of_laurentGluing` for strong noetherianness
(`laurentGluing_isStronglyNoetherian`). -/
theorem isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq [IsStronglyNoetherian A]
    (hP : P.ringOfDefinition ≤ Aplus) (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) {ι : Type*}
    {U : ι → Opens ↥(spa Aplus)} (hU : ∀ i, U i ∈ spaRationalOpens Aplus) (hcov : ⨆ i, U i = W) :
    (Presieve.ofArrows U fun i ↦ homOfLE ((le_iSup U i).trans_eq hcov)).IsSheafFor
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        forget _root_.TopCommRingCat) :=
  isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_of_laurentGluing P
    laurentGluing_isStronglyNoetherian (inferInstanceAs (IsStronglyNoetherian A)) hP hAplus hW hU
    hcov

end TauCeti.ValuationSpectrum
