/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Exact.Basic
public import Mathlib.Algebra.Module.Submodule.Defs
public import Mathlib.Algebra.Module.Torsion.PrimaryComponent
public import Mathlib.GroupTheory.Torsion

/-!
# Primary components of modules

## The `p`-power torsion of a module over an arbitrary ring

For a natural number `p` and a module `M` over an arbitrary, possibly noncommutative, semiring
`A`, the elements of `M` killed by some power of `p` form an `A`-submodule: multiplication by
`p ^ n` is additive, so it commutes with every scalar. As an additive submonoid it is Mathlib's
`p`-primary component `AddCommMonoid.primaryComponent M p`.

Mathlib's `Submodule.torsion'` requires a commutative base ring. Here the ring is typically a
group algebra `ℤ_p[G]` of a nonabelian group, whose modules — such as the `p`-completed units of a
Galois extension of `p`-adic fields — have a `p`-power torsion that must be compared as
`ℤ_p[G]`-modules (NSW (7.4.1)). An extension by a module without `p`-power torsion does not change
the `p`-power torsion.

## The primary component of an ideal

For an ideal `𝔞` of a commutative ring `R`, Mathlib's `Ideal.primaryComponent` is the submodule
`Γ_𝔞(N)` of elements of `N` killed by some power of `𝔞`. This file adds two facts about it: a
finitely generated submodule of `Γ_𝔞(N)` is killed by a single power of `𝔞`, and, when `𝔞` is
generated by a finite set `G`, an element lies in `Γ_𝔞(N)` exactly when each `g ∈ G` kills it
after raising to some power.

## Main definitions

* `TauCeti.pPowerTorsion`: the `A`-submodule of elements killed by a power of `p`.

## Main statements

* `TauCeti.map_pPowerTorsion_of_exact`: in an exact sequence `0 → M → N → P` with `P` free of
  `p`-power torsion, the `p`-power torsion of `N` is that of `M`;
* `Ideal.exists_le_torsionBySet_pow_of_le_primaryComponent`: a finitely generated submodule of
  `Γ_𝔞(N)` is killed by a single power of `𝔞`;
* `Ideal.mem_primaryComponent_span_iff`: membership in `Γ_𝔞(N)` when `𝔞` is generated by a finite
  set.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, proof of (7.4.1).
-/

public section

namespace TauCeti

variable (p : ℕ) (A : Type*) [Semiring A] (M : Type*) [AddCommMonoid M] [Module A M]

/-- The `p`-power torsion of an `A`-module `M`: the `A`-submodule of elements killed by some power
of `p`. Its underlying additive submonoid is the `p`-primary component of `M`. -/
def pPowerTorsion : Submodule A M :=
  { AddCommMonoid.primaryComponent M p with
    smul_mem' a x := fun ⟨k, hk⟩ ↦ ⟨k, by rw [smul_comm, hk, smul_zero]⟩ }

variable {p A M}

/-- An element lies in the `p`-power torsion exactly when some power of `p` kills it. -/
@[simp]
theorem mem_pPowerTorsion_iff {x : M} : x ∈ pPowerTorsion p A M ↔ ∃ k : ℕ, p ^ k • x = 0 :=
  .rfl

variable (p A M)

/-- The additive submonoid underlying the `p`-power torsion is the `p`-primary component. -/
@[simp]
theorem toAddSubmonoid_pPowerTorsion :
    (pPowerTorsion p A M).toAddSubmonoid = AddCommMonoid.primaryComponent M p :=
  AddSubmonoid.ext fun _ ↦ .rfl

variable {p A M}

/-- In an exact sequence `0 → M → N → P` whose last term has no `p`-power torsion, the `p`-power
torsion of `N` is the image of that of `M`. -/
theorem map_pPowerTorsion_of_exact {N P : Type*} [AddCommMonoid N] [Module A N]
    [AddCommMonoid P] [Module A P] {f : M →ₗ[A] N} {g : N →ₗ[A] P} (hfg : Function.Exact f g)
    (hf : Function.Injective f) (hP : pPowerTorsion p A P = ⊥) :
    (pPowerTorsion p A M).map f = pPowerTorsion p A N := by
  ext y
  simp only [Submodule.mem_map, mem_pPowerTorsion_iff]
  constructor
  · rintro ⟨z, ⟨k, hk⟩, rfl⟩
    exact ⟨k, by rw [← map_nsmul, hk, map_zero]⟩
  · rintro ⟨k, hk⟩
    have hy : g y ∈ pPowerTorsion p A P := ⟨k, by rw [← map_nsmul, hk, map_zero]⟩
    obtain ⟨z, rfl⟩ := (hfg y).mp (by rwa [hP, Submodule.mem_bot] at hy)
    exact ⟨z, ⟨k, hf (by rw [map_nsmul, hk, map_zero])⟩, rfl⟩

end TauCeti

namespace Ideal

open Submodule

variable {R : Type*} [CommRing R]

/-- A finitely generated submodule of the `𝔞`-primary component is killed by a single power of
`𝔞`: the primary component is the directed union of the submodules killed by `𝔞ⁿ`. -/
theorem exists_le_torsionBySet_pow_of_le_primaryComponent {N : Type*} [AddCommMonoid N]
    [Module R N] (𝔞 : Ideal R) {P : Submodule R N} (hP : P.FG)
    (h : P ≤ 𝔞.primaryComponent N) : ∃ n, P ≤ torsionBySet R N ↑(𝔞 ^ n) := by
  obtain ⟨_, ⟨n, rfl⟩, hn⟩ := (isCompactElement_iff_le_of_directed_sSup_le _).mp
    ((fg_iff_compact _).mp hP) (Set.range fun n ↦ torsionBySet R N ↑(𝔞 ^ n))
    (Set.range_nonempty _)
    (Monotone.directed_le fun i j hij ↦ torsionBySet_le_torsionBySet_pow i j hij 𝔞).directedOn_range
    (by rwa [sSup_range])
  exact ⟨n, hn⟩

/-- For an ideal generated by a finite set `G`, an element lies in the primary component exactly
when each generator `g ∈ G` kills it after raising to some power. -/
theorem mem_primaryComponent_span_iff {N : Type*} [AddCommMonoid N] [Module R N] (G : Finset R)
    {y : N} : y ∈ (span (G : Set R)).primaryComponent N ↔ ∀ g ∈ G, ∃ n : ℕ, g ^ n • y = 0 := by
  simp only [primaryComponent_mem, mem_torsionBySet_iff, Subtype.forall, SetLike.mem_coe]
  constructor
  · rintro ⟨n, hn⟩ g hg
    exact ⟨n, hn _ (pow_mem_pow (subset_span hg) n)⟩
  · intro h
    obtain ⟨n, hn⟩ := exists_pow_le_of_le_radical_of_fg (J := torsionOf R N y)
      (span_le.mpr fun g hg ↦ by
        obtain ⟨n, hn⟩ := h g hg
        exact ⟨n, (mem_torsionOf_iff _ _).mpr hn⟩)
      ⟨G, rfl⟩
    exact ⟨n, fun r hr ↦ (mem_torsionOf_iff _ _).mp (hn hr)⟩

end Ideal
