/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.SpecialLinear.StandardCarrier.BaseChange
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.SquareZeroCoroot

/-!
# The standard type-`A` carrier is generated by its root subgroups

`TauCeti.SlStd.groupScheme r` is the closed subgroup scheme of `GL_{r+1}` over `ℤ` generated
jointly by the Bourbaki-numbered positive and negative simple-root subgroups of `sl_{r+1}` and by
the weight torus of the standard lattice. This file shows that the weight torus is redundant: the
carrier is already the subgroup scheme generated by the root subgroups alone, the two defining
Hopf ideals agree, and a morphism out of the carrier is determined by its restrictions to the root
subgroups.

The criterion used is that every numbered root generator `E_{i, i+1}` and `E_{i+1, i}` squares to
zero on the standard module: it writes into a coordinate it does not read from. Equivalently, the
weights `ε₀, …, ε_r` of the standard module pair with every simple coroot to `1`, `0` or `-1`, so
each simple root string through them has length at most two. The square-zero rank-one identity then
reaches the coroot value `h_i(u)` at an arbitrary unit `u`, and not merely at the values of the
`i`-th simple root on the weight torus. That distinction is what makes the statements below
uniform in the rank: at rank one the only row of the Cartan matrix is `(2)`, whose values on the
weight torus are the squares rather than all units, so the coprimality criterion for coroot values
does not apply there.

## Main results

* `TauCeti.SlStd.weightTorusSubgroup_le_elementarySubgroup`: over every commutative ring the
  represented weight torus lies in the group generated by the root subgroups.
* `TauCeti.SlStd.definingIdeal_eq_kostantGeneratedDefiningIdeal` and
  `TauCeti.SlStd.groupScheme_eq_kostantGeneratedGroupScheme`: the carrier is the root-generated
  group scheme, with
  `TauCeti.SlStd.baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal` the same
  equality of ideals after base change to any commutative ring.
* `TauCeti.SlStd.groupScheme_hom_ext_of_rootSubgroup`: a morphism out of the carrier is determined
  by its restrictions to the numbered root subgroups, with no hypothesis on the weight torus.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, §3.
* R. W. Carter, *Simple Groups of Lie Type*, §§6.4 and 7.1.
* `TauCeti.Algebra.Lie.Symplectic.StandardCarrier.ToralGeneration`, which runs the same
  square-zero argument on the standard type-`C` carrier.
-/

public section

open CategoryTheory WithConv
open scoped TensorProduct

namespace TauCeti.SlStd

open TauCeti.UniversalEnvelopingAlgebra

universe v

attribute [local instance high] Algebra.toModule

variable (r : ℕ)

/-! ## Generation of the weight torus -/

/-- Every coroot value of the standard type-`A` carrier lies in the group generated by the numbered
root subgroups, at every unit of every value ring. -/
theorem coordinateCocharacter_mem_elementarySubgroup (A : CommAlgCat.{v} ℤ) (d : Fin r)
    (u : (A : Type v)ˣ) :
    kostantCoordinateCocharacter (lattice r).toAddSubgroup (latticeBasis r) (weight r) A d u ∈
      kostantElementarySubgroup (rootGenerator r) (cartanGenerator r) (rep r)
        (lattice r).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
        (isNilpotent_rep_rootGenerator r) A :=
  kostantCoordinateCocharacter_mem_kostantElementarySubgroup_of_sq_eq_zero (rootGenerator r)
    (cartanGenerator r) (rep r) (lattice r).toAddSubgroup
    (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
    (isNilpotent_rep_rootGenerator r) (latticeBasis r) (weight r)
    (isCartanWeightVector_latticeBasis r) (isSl2Triple_rep_rootGenerator r d)
    (pow_two_rep_rootGenerator_eq_zero r _) (pow_two_rep_rootGenerator_eq_zero r _) A u

/-- **Over every commutative ring the weight torus of the standard type-`A` carrier lies in the
group generated by its numbered root subgroups.** -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup (lattice r).toAddSubgroup (latticeBasis r) (weight r) A ≤
      kostantElementarySubgroup (rootGenerator r) (cartanGenerator r) (rep r)
        (lattice r).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
        (isNilpotent_rep_rootGenerator r) A :=
  kostantTorusSubgroup_le_kostantElementarySubgroup_of_forall_coordinateCocharacter
    (rootGenerator r) (cartanGenerator r) (rep r) (lattice r).toAddSubgroup
    (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
    (isNilpotent_rep_rootGenerator r) (latticeBasis r) (weight r) A
    (coordinateCocharacter_mem_elementarySubgroup r A)

/-! ## Scheme-theoretic generation -/

private theorem universalWeightTorus_mem_elementarySubgroup :
    let T := (DiagonalizableGroup.coordinateRing ℤ
      (SplitTorus.characterGroup (Fin r))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin r))) A :=
      WithConv.toConv (AlgHom.id ℤ T)
    kostantTorusPoints (lattice r).toAddSubgroup (latticeBasis r) (weight r) A
        (SplitTorus.pointsMulEquiv q) ∈
      kostantElementarySubgroup (rootGenerator r) (cartanGenerator r) (rep r)
        (lattice r).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
        (isNilpotent_rep_rootGenerator r) A := by
  intro T A q
  apply weightTorusSubgroup_le_elementarySubgroup r A
  exact (kostantTorusSubgroup_eq_range _ _ _ A).ge ⟨_, rfl⟩

/-- **The full-weight standard type-`A_r` carrier is generated scheme-theoretically by its numbered
root subgroups.** Adjoining the represented weight torus does not change the integral defining Hopf
ideal. -/
theorem definingIdeal_eq_kostantGeneratedDefiningIdeal :
    definingIdeal r =
      kostantGeneratedDefiningIdeal (rootGenerator r) (cartanGenerator r) (rep r)
        (lattice r).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
        (isNilpotent_rep_rootGenerator r) (latticeBasis r) := by
  rw [definingIdeal_def]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      _ _ _ _ _ _ _ (weight r) (universalWeightTorus_mem_elementarySubgroup r)

/-- The full-weight standard type-`A_r` carrier is the group scheme generated by its numbered
positive and negative simple root subgroups. -/
theorem groupScheme_eq_kostantGeneratedGroupScheme :
    groupScheme r =
      kostantGeneratedGroupScheme (rootGenerator r) (cartanGenerator r) (rep r)
        (lattice r).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
        (isNilpotent_rep_rootGenerator r) (latticeBasis r) :=
  kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ (weight r) (universalWeightTorus_mem_elementarySubgroup r)

/-- The canonical inclusion of the root-generated standard type-`A_r` carrier into its toral
closure is an isomorphism. -/
instance isIso_kostantGeneratedToToral :
    CategoryTheory.IsIso (kostantGeneratedToToral (rootGenerator r) (cartanGenerator r) (rep r)
      (lattice r).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
      (isNilpotent_rep_rootGenerator r) (latticeBasis r) (weight r)) :=
  isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary _ _ _ _ _ _ _ (weight r)
    (universalWeightTorus_mem_elementarySubgroup r)

/-- After base change to any commutative ring, the transported defining ideal of the standard
type-`A_r` carrier is the ideal of the root-generated carrier. -/
theorem baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal
    (A : Type v) [CommRing A] :
    baseChangeDefiningIdeal r A =
      kostantGeneratedGeneralLinearBaseChangeIdeal (rootGenerator r) (cartanGenerator r) (rep r)
        (lattice r).toAddSubgroup (fun _ hu _ hv => rep_kostantForm_mem_lattice r hu hv)
        (isNilpotent_rep_rootGenerator r) (latticeBasis r) A := by
  rw [baseChangeDefiningIdeal_def]
  exact kostantToralBaseChangePresentationIdeal_eq_generated_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ (weight r) (universalWeightTorus_mem_elementarySubgroup r) A

/-- **A morphism out of the standard type-`A_r` carrier is determined by the numbered root
subgroups**, with no hypothesis on the weight torus. -/
theorem groupScheme_hom_ext_of_rootSubgroup {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : groupScheme r ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup r k ≫ φ = rootSubgroup r k ≫ ψ) : φ = ψ := by
  refine kostantToralGroupScheme_hom_ext_of_universal_torus_mem_elementary _ _ _ _ _ _ _
    (weight r) (universalWeightTorus_mem_elementarySubgroup r) φ ψ fun k => ?_
  rw [← rootSubgroup_def r k]
  exact hroot k

end TauCeti.SlStd
