/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.Orders.Quadratic
public import Mathlib.RingTheory.DedekindDomain.Different
import TauCeti.NumberTheory.NumberField.Global.Orders.Lattice
import TauCeti.RingTheory.FractionalIdeal.Operations

/-!
# Gorenstein orders and the trace dual

For a nonzero fractional ideal `I` of an order `O` in a number field `K`, the trace dual
`Iᵛ = {x ∈ K | Tr_{K/ℚ}(x I) ⊆ ℤ}` is again a nonzero fractional ideal of `O`, and `Iᵛᵛ = I`.
The multiplier ring of `I` is the trace dual of `I Iᵛ`, so `I` is proper exactly when
`I Iᵛ = Oᵛ`. The trace dual of the zero ideal is all of `K`, which is not fractional, so the
packaged dual `NumberFieldOrder.dual` assigns the junk value `0` to the zero ideal.

The order `O` is *Gorenstein* when its trace dual `Oᵛ`, the codifferent, is an invertible
fractional ideal. The criterion above then shows that a fractional ideal of a Gorenstein order is
proper if and only if it is invertible. Conversely `Oᵛ` is always proper, so this equivalence
characterizes Gorenstein orders.

The maximal order is Gorenstein, since all its nonzero fractional ideals are invertible. So is
every monogenic order `ℤ[x]`: by Euler's formula its trace dual is generated by `f'(x)⁻¹`, where `f`
is the minimal polynomial of `x`. In particular, every quadratic order is Gorenstein.

## Main definitions

* `TauCeti.GlobalNumberFields.NumberFieldOrder.traceDual`: the trace-dual fractional ideal of an
  order.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.dual`: the trace dual of an arbitrary fractional
  ideal of an order.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.IsGorenstein`: an order is Gorenstein when its
  trace dual is invertible.

## Main results

* `TauCeti.GlobalNumberFields.NumberFieldOrder.dual_dual`: the trace dual is an involution.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.isProperFractionalIdeal_iff_mul_dual_eq_dual_one`:
  a fractional ideal `I` is proper if and only if `I Iᵛ = Oᵛ`.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.isProperFractionalIdeal_iff_isUnit_of_isGorenstein`:
  in a Gorenstein order, proper fractional ideals are exactly the invertible ones.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.isGorenstein_iff_forall_isUnit`: an order is
  Gorenstein if and only if each of its proper fractional ideals is invertible.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.isGorenstein_maximalNumberFieldOrder`: the maximal
  order is Gorenstein.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.isGorenstein_of_toSubalgebra_eq_adjoin`: a
  monogenic order is Gorenstein.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.isGorenstein_of_finrank_eq_two`: every quadratic
  order is Gorenstein.

## Implementation notes

The underlying submodule of `traceDual` is Mathlib's `Submodule.traceDual ℤ ℚ 1` (see
`coe_traceDual`), so Mathlib's general trace-dual API applies to it directly.

## References

* J. Buchmann and H. W. Lenstra, Jr., *Approximating rings of integers in number fields*,
  J. Théor. Nombres Bordeaux 6 (1994), §2.
* G. S. Kopp and J. C. Lagarias, *Class Field Theory for Orders of Number Fields*, §2.
* J. Neukirch, *Algebraic Number Theory*, Chapter I, §2.
* J.-P. Serre, *Local Fields*, Chapter III, §6, Lemma 2 (Euler's formula, available in Mathlib as
  `traceForm_dualSubmodule_adjoin`).
-/

public section
noncomputable section

open Module NumberField Submodule
open scoped nonZeroDivisors

namespace TauCeti.GlobalNumberFields

namespace NumberFieldOrder

universe u

variable {K : Type u} [Field K] [NumberField K]

private abbrev FractionalOrderIdeal (O : NumberFieldOrder K) :=
  FractionalIdeal (nonZeroDivisors O.toSubalgebra) K

private noncomputable def integerBasis (O : NumberFieldOrder K) :=
  Module.Free.chooseBasis ℤ (1 : FractionalOrderIdeal O)

private noncomputable def rationalBasis (O : NumberFieldOrder K) :
    Module.Basis (Module.Free.ChooseBasisIndex ℤ (1 : FractionalOrderIdeal O)) ℚ K := by
  let b := O.integerBasis
  refine Module.Basis.mk ?_ (O.span_rat_range_basis one_ne_zero b).ge
  exact (LinearIndependent.iff_fractionRing ℤ ℚ).mp
    (b.linearIndependent.map'
      ((((1 : FractionalOrderIdeal O) : Submodule O.toSubalgebra K).restrictScalars ℤ).subtype)
      (Submodule.ker_subtype _))

private theorem range_rationalBasis (O : NumberFieldOrder K) :
    Set.range O.rationalBasis = Set.range fun i ↦ (O.integerBasis i : K) := by
  rw [rationalBasis, Module.Basis.coe_mk]

private theorem restrictScalars_one_eq_span_integerBasis (O : NumberFieldOrder K) :
    ((1 : Submodule O.toSubalgebra K).restrictScalars ℤ) =
      Submodule.span ℤ (Set.range O.rationalBasis) := by
  apply SetLike.coe_injective
  rw [O.range_rationalBasis, O.span_int_range_basis, Submodule.coe_restrictScalars,
    ← FractionalIdeal.coe_one, FractionalIdeal.coeToSet_coeToSubmodule]

private theorem traceDual_restrictScalars_eq_span (O : NumberFieldOrder K) :
    (Submodule.traceDual ℤ ℚ (1 : Submodule O.toSubalgebra K)).restrictScalars ℤ =
      Submodule.span ℤ (Set.range O.rationalBasis.traceDual) := by
  exact Submodule.traceDual_span_of_basis ℤ (1 : Submodule O.toSubalgebra K)
    O.rationalBasis (O.restrictScalars_one_eq_span_integerBasis)

private theorem traceDual_fg (O : NumberFieldOrder K) :
    (Submodule.traceDual ℤ ℚ (1 : Submodule O.toSubalgebra K)).FG := by
  rw [← Submodule.FG.restrictScalars_iff (R := ℤ), O.traceDual_restrictScalars_eq_span]
  exact Submodule.fg_span (Set.finite_range _)

/-- The trace dual (or complementary module) of an order `O`:
the fractional ideal of `x : K` such that `Tr_{K/ℚ}(xy)` is an integer for every `y ∈ O`. -/
def traceDual (O : NumberFieldOrder K) :
    FractionalIdeal (nonZeroDivisors O.toSubalgebra) K :=
  ⟨Submodule.traceDual ℤ ℚ (1 : Submodule O.toSubalgebra K),
    FractionalIdeal.isFractional_of_fg O.traceDual_fg⟩

@[simp]
theorem coe_traceDual (O : NumberFieldOrder K) :
    (O.traceDual : Submodule O.toSubalgebra K) =
      Submodule.traceDual ℤ ℚ (1 : Submodule O.toSubalgebra K) :=
  (rfl)

/-- Membership in the trace dual means that the trace pairing against every element of the order
is integral. -/
@[simp]
theorem mem_traceDual_iff (O : NumberFieldOrder K) (x : K) :
    x ∈ O.traceDual ↔
      ∀ y : O.toSubalgebra,
        Algebra.trace ℚ K (x * y) ∈ (algebraMap ℤ ℚ).range := by
  rw [← FractionalIdeal.mem_coe, O.coe_traceDual, Submodule.mem_traceDual]
  constructor
  · intro h y
    simpa [Algebra.traceForm_apply] using h (y : K) (Submodule.mem_one.mpr ⟨y, rfl⟩)
  · intro h y hy
    obtain ⟨z, rfl⟩ := Submodule.mem_one.mp hy
    simpa [Algebra.traceForm_apply] using h z

/-- The order, viewed as the unit fractional ideal, is contained in its trace dual. -/
theorem one_le_traceDual (O : NumberFieldOrder K) :
    (1 : FractionalIdeal (nonZeroDivisors O.toSubalgebra) K) ≤ O.traceDual := by
  intro x hx
  obtain ⟨a, rfl⟩ := (FractionalIdeal.mem_one_iff _).mp hx
  rw [O.mem_traceDual_iff]
  intro y
  have htr : IsIntegral ℤ (Algebra.trace ℚ K ((a * y : O.toSubalgebra) : K)) :=
    Algebra.isIntegral_trace (R := ℤ) (L := ℚ) (F := K) (O.isIntegral (a * y))
  simpa using IsIntegrallyClosed.isIntegral_iff.mp htr

/-- The unit element belongs to the trace dual of every number-field order. -/
theorem one_mem_traceDual (O : NumberFieldOrder K) : (1 : K) ∈ O.traceDual :=
  O.one_le_traceDual (FractionalIdeal.one_mem_one _)

/-- The trace dual of an order is nonzero. -/
theorem traceDual_ne_zero (O : NumberFieldOrder K) : O.traceDual ≠ 0 := by
  intro h
  have := O.one_mem_traceDual
  rw [h, FractionalIdeal.mem_zero_iff] at this
  exact one_ne_zero this

/-- Taking the trace dual twice recovers the original order. -/
theorem traceDual_traceDual (O : NumberFieldOrder K) :
    Submodule.traceDual ℤ ℚ (O.traceDual : Submodule O.toSubalgebra K) =
      (1 : Submodule O.toSubalgebra K) := by
  rw [O.coe_traceDual]
  apply Submodule.restrictScalars_injective ℤ
  rw [Submodule.traceDual_span_of_basis ℤ
      (Submodule.traceDual ℤ ℚ (1 : Submodule O.toSubalgebra K))
      O.rationalBasis.traceDual O.traceDual_restrictScalars_eq_span,
    Module.Basis.traceDual_traceDual, ← O.restrictScalars_one_eq_span_integerBasis]

/-- The multiplier ring of the trace dual is the order itself. Thus the trace dual is always a
proper fractional ideal, whether or not it is invertible. -/
@[simp]
theorem multiplierRing_traceDual (O : NumberFieldOrder K) :
    O.multiplierRing O.traceDual = O.toSubalgebra.toSubring := by
  apply le_antisymm ?_ (O.order_le_multiplierRing O.traceDual)
  intro x hx
  have hx' : x ∈ Submodule.traceDual ℤ ℚ
      (O.traceDual : Submodule O.toSubalgebra K) := by
    rw [Submodule.mem_traceDual]
    intro y hy
    have hxy : x * y ∈ O.traceDual := (O.mem_multiplierRing_iff O.traceDual x).mp hx y hy
    simpa [Algebra.traceForm_apply] using (O.mem_traceDual_iff (x * y)).mp hxy 1
  rw [O.traceDual_traceDual] at hx'
  obtain ⟨z, rfl⟩ := Submodule.mem_one.mp hx'
  exact z.property

/-- The trace dual is a proper fractional ideal. -/
@[simp]
theorem isProperFractionalIdeal_traceDual (O : NumberFieldOrder K) :
    O.IsProperFractionalIdeal O.traceDual := by
  rw [O.isProperFractionalIdeal_def]
  exact O.multiplierRing_traceDual

/-! ### The trace dual of a fractional ideal -/

variable (O : NumberFieldOrder K)

/-- The trace dual of a nonzero fractional ideal is the `ℤ`-span of the trace-dual basis of a
`ℚ`-basis spanning the ideal over `ℤ`. -/
private theorem exists_basis_traceDual
    {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) :
    ∃ b : Basis (Fin (finrank ℚ K)) ℚ K,
      (I : Submodule O.toSubalgebra K).restrictScalars ℤ = span ℤ (Set.range b) ∧
      (Submodule.traceDual ℤ ℚ (I : Submodule O.toSubalgebra K)).restrictScalars ℤ =
        span ℤ (Set.range b.traceDual) := by
  obtain ⟨b, hb⟩ := O.exists_basis_restrictScalars_eq_span hI
  exact ⟨b, hb, Submodule.traceDual_span_of_basis ℤ _ b hb⟩

/-- The trace dual of a nonzero fractional ideal of an order is a fractional ideal. -/
theorem isFractional_traceDual {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) :
    IsFractional O.toSubalgebra⁰ (Submodule.traceDual ℤ ℚ (I : Submodule O.toSubalgebra K)) := by
  obtain ⟨b, -, hb⟩ := O.exists_basis_traceDual hI
  refine FractionalIdeal.isFractional_of_fg (Submodule.FG.of_restrictScalars ℤ ?_)
  rw [hb]
  exact Submodule.fg_span (Set.finite_range _)

/-- The trace dual of a nonzero fractional ideal of an order is not zero. -/
private theorem traceDual_ne_bot {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) :
    Submodule.traceDual ℤ ℚ (I : Submodule O.toSubalgebra K) ≠ ⊥ := by
  obtain ⟨b, -, hb⟩ := O.exists_basis_traceDual hI
  obtain ⟨i⟩ := b.index_nonempty
  intro h
  have hi : b.traceDual i ∈
      (Submodule.traceDual ℤ ℚ (I : Submodule O.toSubalgebra K)).restrictScalars ℤ :=
    hb ▸ Submodule.subset_span ⟨i, rfl⟩
  rw [h, Submodule.restrictScalars_bot, Submodule.mem_bot] at hi
  exact b.traceDual.ne_zero i hi

/-- Taking the trace dual twice returns a nonzero fractional ideal of an order. -/
private theorem traceDual_traceDual_of_ne_zero
    {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) :
    Submodule.traceDual ℤ ℚ (Submodule.traceDual ℤ ℚ (I : Submodule O.toSubalgebra K)) = I := by
  obtain ⟨b, hI', hb⟩ := O.exists_basis_traceDual hI
  apply Submodule.restrictScalars_injective ℤ
  rw [Submodule.traceDual_span_of_basis ℤ _ b.traceDual hb,
    Module.Basis.traceDual_traceDual, hI']

/-- The trace dual `Iᵛ = {x ∈ K | Tr_{K/ℚ}(x I) ⊆ ℤ}` of a fractional ideal `I` of an order, as a
fractional ideal. For `I = 0` the trace dual is all of `K`, which is not fractional, and the
junk value `0` is used instead. -/
def dual (I : FractionalIdeal O.toSubalgebra⁰ K) : FractionalIdeal O.toSubalgebra⁰ K :=
  open scoped Classical in
  if hI : I = 0 then 0 else
    (⟨Submodule.traceDual ℤ ℚ (I : Submodule O.toSubalgebra K), O.isFractional_traceDual hI⟩ :
      FractionalIdeal O.toSubalgebra⁰ K)

variable {O : NumberFieldOrder K}

/-- The trace dual of a nonzero fractional ideal is Mathlib's `Submodule.traceDual` over
`ℤ ⊆ ℚ`. -/
theorem coe_dual {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) :
    (O.dual I : Submodule O.toSubalgebra K) =
      Submodule.traceDual ℤ ℚ (I : Submodule O.toSubalgebra K) := by
  simp [dual, hI]

/-- An element lies in the trace dual of a nonzero fractional ideal `I` exactly when its products
with the elements of `I` have integral trace. -/
theorem mem_dual {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) {x : K} :
    x ∈ O.dual I ↔ ∀ y ∈ I, Algebra.trace ℚ K (x * y) ∈ (algebraMap ℤ ℚ).range := by
  simp only [← FractionalIdeal.mem_coe, coe_dual hI, Submodule.mem_traceDual,
    Algebra.traceForm_apply]

variable (O) in
/-- The junk value of the trace dual at the zero ideal is zero. -/
@[simp]
theorem dual_zero : O.dual 0 = 0 := by
  simp [dual]

/-- The trace dual of a nonzero fractional ideal is nonzero. -/
theorem dual_ne_zero {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) : O.dual I ≠ 0 := by
  rw [ne_eq, ← FractionalIdeal.coeToSubmodule_inj, coe_dual hI, FractionalIdeal.coe_zero]
  exact O.traceDual_ne_bot hI

/-- The trace dual of a fractional ideal vanishes exactly when the ideal does. -/
@[simp]
theorem dual_eq_zero_iff {I : FractionalIdeal O.toSubalgebra⁰ K} : O.dual I = 0 ↔ I = 0 :=
  ⟨not_imp_not.mp dual_ne_zero, fun h ↦ h ▸ O.dual_zero⟩

/-- **Trace duality is perfect:** the trace dual of the trace dual of a fractional ideal of an
order is the ideal itself. -/
@[simp]
theorem dual_dual (I : FractionalIdeal O.toSubalgebra⁰ K) : O.dual (O.dual I) = I := by
  rcases eq_or_ne I 0 with rfl | hI
  · simp
  rw [← FractionalIdeal.coeToSubmodule_inj, coe_dual (dual_ne_zero hI), coe_dual hI,
    O.traceDual_traceDual_of_ne_zero hI]

variable (O) in
/-- The trace dual is an involution on the fractional ideals of an order. -/
theorem dual_involutive : Function.Involutive O.dual :=
  dual_dual

variable (O) in
/-- The trace dual is injective on the fractional ideals of an order. -/
theorem dual_injective : Function.Injective O.dual :=
  (dual_involutive O).injective

/-- The trace dual of the unit fractional ideal agrees with the trace dual of the order. -/
@[simp]
theorem dual_one_eq_traceDual (O : NumberFieldOrder K) : O.dual 1 = O.traceDual := by
  apply FractionalIdeal.coeToSubmodule_injective
  exact (coe_dual one_ne_zero).trans (by
    rw [FractionalIdeal.coe_one]
    exact O.coe_traceDual.symm)

/-! ### Proper ideals and the trace dual -/

/-- The product of a nonzero fractional ideal with its trace dual is nonzero. -/
private theorem mul_dual_ne_zero {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0) :
    I * O.dual I ≠ 0 := by
  obtain ⟨x, hxI, hx⟩ := Submodule.exists_mem_ne_zero_of_ne_bot
    (FractionalIdeal.coeToSubmodule_ne_bot.mpr hI)
  obtain ⟨y, hyI, hy⟩ := Submodule.exists_mem_ne_zero_of_ne_bot
    (FractionalIdeal.coeToSubmodule_ne_bot.mpr (dual_ne_zero hI))
  intro h
  have hxy := FractionalIdeal.mul_mem_mul hxI hyI
  rw [h, FractionalIdeal.mem_zero_iff] at hxy
  exact mul_ne_zero hx hy hxy

/-- **The multiplier ring of a nonzero fractional ideal `I` is the trace dual of `I Iᵛ`.** -/
theorem mem_multiplierRing_iff_mem_dual {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : I ≠ 0)
    {x : K} : x ∈ O.multiplierRing I ↔ x ∈ O.dual (I * O.dual I) := by
  let J := (I : Submodule O.toSubalgebra K)
  have hdual : x ∈ Submodule.traceDual ℤ ℚ (J * Submodule.traceDual ℤ ℚ J) ↔
      Submodule.span O.toSubalgebra {x} * J ≤ J := by
    rw [← Submodule.span_singleton_le_iff_mem, Submodule.le_traceDual_mul_iff,
      O.traceDual_traceDual_of_ne_zero hI]
  have hmul : Submodule.span O.toSubalgebra {x} * J ≤ J ↔ x ∈ O.multiplierRing I := by
    rw [← Submodule.le_div_iff_mul_le, Submodule.span_singleton_le_iff_mem,
      Submodule.mem_div_iff_forall_mul_mem, O.mem_multiplierRing_iff]
    simp [J]
  rw [← hmul, ← hdual, ← FractionalIdeal.mem_coe, coe_dual (mul_dual_ne_zero hI),
    FractionalIdeal.coe_mul, coe_dual hI]

/-- **A fractional ideal `I` is proper exactly when `I Iᵛ = Oᵛ`.** -/
theorem isProperFractionalIdeal_iff_mul_dual_eq_dual_one
    {I : FractionalIdeal O.toSubalgebra⁰ K} :
    O.IsProperFractionalIdeal I ↔ I * O.dual I = O.dual 1 := by
  rcases eq_or_ne I 0 with rfl | hI
  · rw [zero_mul, eq_comm, dual_eq_zero_iff]
    exact iff_of_false (fun h ↦ h.ne_zero rfl) one_ne_zero
  rw [← (dual_injective O).eq_iff, dual_dual, O.isProperFractionalIdeal_def,
    SetLike.ext_iff, FractionalIdeal.ext_iff]
  refine forall_congr' fun x ↦ ?_
  rw [mem_multiplierRing_iff_mem_dual hI, FractionalIdeal.mem_one_iff]
  exact iff_congr Iff.rfl
    ⟨fun h ↦ ⟨⟨x, h⟩, rfl⟩, fun ⟨y, hy⟩ ↦ hy ▸ y.2⟩

variable (O) in
/-- The trace dual `Oᵛ` of an order, its codifferent, is a proper fractional ideal. -/
theorem isProperFractionalIdeal_dual_one : O.IsProperFractionalIdeal (O.dual 1) := by
  rw [O.dual_one_eq_traceDual]
  exact O.isProperFractionalIdeal_traceDual

/-! ### Gorenstein orders -/

/-- A number-field order is **Gorenstein** when its trace-dual fractional ideal is invertible. -/
@[mk_iff]
structure IsGorenstein (O : NumberFieldOrder K) : Prop where
  /-- The trace dual of a Gorenstein order is invertible. -/
  isUnit_traceDual : IsUnit O.traceDual

attribute [simp] isGorenstein_iff

/-- **In a Gorenstein order every proper fractional ideal is invertible.** -/
theorem IsGorenstein.isUnit_of_isProperFractionalIdeal (hO : O.IsGorenstein)
    {I : FractionalIdeal O.toSubalgebra⁰ K} (hI : O.IsProperFractionalIdeal I) : IsUnit I := by
  have h := isProperFractionalIdeal_iff_mul_dual_eq_dual_one.mp hI
  have hdual : IsUnit (O.dual 1) := by
    rw [O.dual_one_eq_traceDual]
    exact hO.isUnit_traceDual
  exact isUnit_of_mul_isUnit_left (h ▸ hdual : IsUnit (I * O.dual I))

/-- **In a Gorenstein order a fractional ideal is proper exactly when it is invertible.** -/
theorem isProperFractionalIdeal_iff_isUnit_of_isGorenstein (hO : O.IsGorenstein)
    (I : FractionalIdeal O.toSubalgebra⁰ K) : O.IsProperFractionalIdeal I ↔ IsUnit I :=
  ⟨hO.isUnit_of_isProperFractionalIdeal, O.isProperFractionalIdeal_of_isUnit⟩

variable (O) in
/-- **An order is Gorenstein exactly when all of its proper fractional ideals are invertible.** -/
theorem isGorenstein_iff_forall_isUnit :
    O.IsGorenstein ↔ ∀ I : FractionalIdeal O.toSubalgebra⁰ K,
      O.IsProperFractionalIdeal I → IsUnit I := by
  constructor
  · exact fun hO _ ↦ hO.isUnit_of_isProperFractionalIdeal
  · intro h
    refine ⟨?_⟩
    rw [← O.dual_one_eq_traceDual]
    exact h _ O.isProperFractionalIdeal_dual_one

/-- An order that is a Dedekind domain is Gorenstein, since every nonzero fractional ideal of a
Dedekind domain is invertible. -/
theorem isGorenstein_of_isDedekindDomain (O : NumberFieldOrder K)
    [IsDedekindDomain O.toSubalgebra] : O.IsGorenstein :=
  ⟨isUnit_iff_ne_zero.mpr O.traceDual_ne_zero⟩

/-- The maximal order of a number field is Gorenstein. -/
theorem isGorenstein_maximalNumberFieldOrder :
    (maximalNumberFieldOrder K).IsGorenstein := by
  let _ : IsDedekindDomain (maximalNumberFieldOrder K).toSubalgebra := by
    rw [maximalNumberFieldOrder_toSubalgebra]
    exact IsIntegralClosure.isDedekindDomain ℤ ℚ K _
  exact isGorenstein_of_isDedekindDomain _

/-- **Euler's formula**: the trace dual of a monogenic order `ℤ[x]` is generated by the inverse
of the derivative of the minimal polynomial of `x`, evaluated at `x`. -/
theorem traceDual_eq_spanSingleton_of_toSubalgebra_eq_adjoin {x : K}
    (hx : O.toSubalgebra = Algebra.adjoin ℤ {x}) :
    O.traceDual = FractionalIdeal.spanSingleton _
      (Polynomial.aeval x (Polynomial.derivative (minpoly ℚ x)))⁻¹ := by
  have hxint : IsIntegral ℤ x := O.isIntegral ⟨x, hx ▸ Algebra.self_mem_adjoin_singleton ℤ x⟩
  have htop : Algebra.adjoin ℚ {x} = ⊤ := by
    refine Subalgebra.toSubmodule_injective (eq_top_iff.mpr ?_)
    rw [← O.spans, Submodule.span_le, hx]
    exact Algebra.adjoin_le (S := (Algebra.adjoin ℚ {x}).restrictScalars ℤ)
      (Set.singleton_subset_iff.mpr (Algebra.self_mem_adjoin_singleton ℚ x))
  have h1 : (1 : Submodule O.toSubalgebra K).restrictScalars ℤ =
      Subalgebra.toSubmodule (Algebra.adjoin ℤ {x}) := by
    ext y
    simp [← hx]
  rw [← FractionalIdeal.coeToSubmodule_inj, O.coe_traceDual]
  apply Submodule.restrictScalars_injective ℤ
  rw [Submodule.restrictScalars_traceDual, h1,
    traceForm_dualSubmodule_adjoin ℤ ℚ htop hxint]
  ext y
  rw [Submodule.mem_smul_pointwise_iff_exists, Submodule.restrictScalars_mem,
    FractionalIdeal.mem_coe, FractionalIdeal.mem_spanSingleton, ← hx]
  exact ⟨fun ⟨b, hb, hby⟩ ↦ ⟨⟨b, hb⟩, by simp [← hby, Subalgebra.smul_def, mul_comm]⟩,
    fun ⟨b, hby⟩ ↦ ⟨b, b.2, by simp [← hby, Subalgebra.smul_def, mul_comm]⟩⟩

/-- **A monogenic order `ℤ[x]` is Gorenstein**, since by Euler's formula its trace dual is
principal. -/
theorem isGorenstein_of_toSubalgebra_eq_adjoin {x : K}
    (hx : O.toSubalgebra = Algebra.adjoin ℤ {x}) : O.IsGorenstein := by
  refine ⟨?_⟩
  rw [traceDual_eq_spanSingleton_of_toSubalgebra_eq_adjoin hx]
  exact FractionalIdeal.isUnit_spanSingleton (isUnit_iff_ne_zero.mpr (inv_ne_zero
    ((Algebra.IsSeparable.isSeparable ℚ x).aeval_derivative_ne_zero (minpoly.aeval ℚ x))))

/-- Every order in a quadratic number field is Gorenstein. -/
theorem isGorenstein_of_finrank_eq_two (O : NumberFieldOrder K)
    (hK : Module.finrank ℚ K = 2) : O.IsGorenstein :=
  ⟨IsProperFractionalIdeal.isUnit_of_finrank_eq_two hK O.isProperFractionalIdeal_traceDual⟩

end NumberFieldOrder

end TauCeti.GlobalNumberFields
