/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.MonoidAlgebra.Basic
public import Mathlib.Algebra.Group.Submonoid.Finsupp
public import Mathlib.Analysis.Complex.Basic
public import Mathlib.GroupTheory.Finiteness

/-!
# Complex points of an affine semigroup and their monomial-embedding topology

The complex points of the affine scheme of a commutative additive monoid `S` are the
`ℂ`-algebra homomorphisms `ℂ[S] →ₐ[ℂ] ℂ` out of the monoid algebra, equivalently the
multiplicative characters `Multiplicative S →* ℂ`. Evaluating such a point on a finite family
`g : Fin r → S` that generates `S` as an additive monoid gives a map into `ℂ^r`, and the
topology of the complex points is the one induced by that map.

This file constructs that topology and proves the facts a chart needs before any coordinates
are chosen: the evaluation map is injective, its range is the closed subset of `ℂ^r` cut out
by the binomial relations of the generating family, and the induced topology does not depend
on which finite generating family is used. Consequently the complex points form a Hausdorff,
second countable, locally compact space, and evaluation at every monomial is continuous.

Independence of the generating family is what makes the space, rather than one presentation of
it, the object of study: a semigroup that arises as the dual of a cone has no preferred finite
generating family, and later coordinate descriptions must be compared with a topology that was
not defined using them.

The construction is contravariantly functorial in the semigroup: a homomorphism `S →+ T` pulls
the complex points of `T` back to those of `S` through the induced map of monoid algebras, and
the pulled-back map is continuous whichever generating families topologize the two sides. These
are the maps by which face localizations and morphisms of fans act on affine charts, and an
isomorphism of semigroups, such as a choice of coordinates on the dual semigroup of a regular
cone, induces a homeomorphism.

## Main declarations

* `TauCeti.Toric.AffineSemigroupComplexPoint`: the complex points of an affine semigroup.
* `TauCeti.Toric.AffineSemigroupComplexPoint.ext`: a complex point is determined by its values
  on monomials.
* `TauCeti.Toric.AddGeneratingFamily`: a finite family generating an additive monoid, which
  exists exactly for a finitely generated additive monoid.
* `TauCeti.Toric.monomialEmbedding`: evaluation of a complex point on such a family.
* `TauCeti.Toric.range_monomialEmbedding`: the range of the monomial embedding is the locus of
  the binomial relations of the family.
* `TauCeti.Toric.affinePointTopology`: the topology induced by a monomial embedding.
* `TauCeti.Toric.affinePointTopology_eq`: it does not depend on the generating family.
* `TauCeti.Toric.continuous_iff_forall_continuous_apply_single`: a map into the complex points is
  continuous exactly when evaluation at every monomial is.
* `TauCeti.Toric.isClosedEmbedding_monomialEmbedding`: the monomial embedding is a closed
  embedding, whence the Hausdorff, second countable and locally compact conclusions.
* `TauCeti.Toric.isCompact_setOf_forall_norm_apply_single_le_one`: the points at which every
  monomial has absolute value at most `1` form a compact set, and
  `TauCeti.Toric.isCompact_setOf_forall_norm_apply_single_toFun_le`: so do the points at which
  the monomials of a generating family are bounded by any constant.
* `TauCeti.Toric.AffineSemigroupComplexPoint.comap`: the map on complex points induced by a
  homomorphism of additive monoids, with `TauCeti.Toric.AffineSemigroupComplexPoint.comap_id`
  and `TauCeti.Toric.AffineSemigroupComplexPoint.comap_comp`.
* `TauCeti.Toric.AffineSemigroupComplexPoint.continuous_comap`: it is continuous for the
  monomial-embedding topologies of arbitrary finite generating families.
* `TauCeti.Toric.AffineSemigroupComplexPoint.comapHomeomorph`: an isomorphism of additive monoids
  induces a homeomorphism of complex points.
* `TauCeti.Toric.AffineSemigroupComplexPoint.exists_comap_inclusion_eq_iff` and
  `TauCeti.Toric.AffineSemigroupComplexPoint.isClosed_setOf_exists_comap_inclusion_eq`: when a
  submonoid is generated by two submonoids, the pairs of points of the two that come from a point
  of the join are cut out by closed binomial conditions.

## References

* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §§1.1–1.3.
* W. Fulton, *Introduction to Toric Varieties*, §1.2.
-/

public section

open Multiplicative Topology

namespace TauCeti.Toric

variable {S : Type*} [AddCommMonoid S] {r r' : ℕ}

/-- The complex points of the affine scheme attached to a commutative additive monoid `S`: the
`ℂ`-algebra homomorphisms out of the monoid algebra of `S`. This is the functor-of-points
carrier; no topology is part of the data. -/
abbrev AffineSemigroupComplexPoint (S : Type*) [AddCommMonoid S] :=
  MonoidAlgebra ℂ (Multiplicative S) →ₐ[ℂ] ℂ

/-- The complex points of every affine semigroup are inhabited: the distinguished point sends
every monomial to `1`. -/
noncomputable instance : Inhabited (AffineSemigroupComplexPoint S) where
  default := MonoidAlgebra.lift ℂ ℂ (Multiplicative S) 1

/-- The distinguished complex point is the algebra homomorphism induced by the trivial
character. -/
theorem default_def :
    (default : AffineSemigroupComplexPoint S) = MonoidAlgebra.lift ℂ ℂ (Multiplicative S) 1 :=
  (rfl)

/-- The distinguished complex point takes the value `1` on every monomial. -/
@[simp]
theorem default_apply_single (s : S) :
    (default : AffineSemigroupComplexPoint S) (MonoidAlgebra.single (ofAdd s) 1) = 1 := by
  rw [default_def, MonoidAlgebra.lift_single, one_smul, MonoidHom.one_apply]

/-- Two complex points of `S` that agree on every monomial are equal. -/
@[ext]
theorem AffineSemigroupComplexPoint.ext {x y : AffineSemigroupComplexPoint S}
    (h : ∀ s : S, x (MonoidAlgebra.single (ofAdd s) 1) = y (MonoidAlgebra.single (ofAdd s) 1)) :
    x = y :=
  MonoidAlgebra.algHom_ext (fun m ↦ h (toAdd m)) (Subsingleton.elim _ _)

/-- A complex point is multiplicative on monomials: its value on the monomial of a sum is the
product of its values on the monomials of the summands. -/
theorem AffineSemigroupComplexPoint.apply_single_add (x : AffineSemigroupComplexPoint S)
    (s t : S) :
    x (MonoidAlgebra.single (ofAdd (s + t)) 1) =
      x (MonoidAlgebra.single (ofAdd s) 1) * x (MonoidAlgebra.single (ofAdd t) 1) := by
  rw [← map_mul, MonoidAlgebra.single_mul_single, ofAdd_add, mul_one]

/-- The value of a complex point on the monomial of a multiple is the corresponding power of its
value on the monomial. -/
theorem AffineSemigroupComplexPoint.apply_single_nsmul (x : AffineSemigroupComplexPoint S)
    (n : ℕ) (s : S) :
    x (MonoidAlgebra.single (ofAdd (n • s)) 1) = x (MonoidAlgebra.single (ofAdd s) 1) ^ n := by
  rw [← map_pow, MonoidAlgebra.single_pow, ofAdd_nsmul, one_pow]

/-- A finite family generating a commutative additive monoid. The affine complex points of `S`
are topologized through evaluation on such a family, so the chosen indexed family, and not just
the finite generation of `S`, is part of the data. -/
@[ext]
structure AddGeneratingFamily (S : Type*) [AddCommMonoid S] (r : ℕ) where
  /-- The family of generators. -/
  toFun : Fin r → S
  /-- The family generates the additive monoid. -/
  spans : AddSubmonoid.closure (Set.range toFun) = ⊤

/-- A monoid with a finite generating family is finitely generated. -/
theorem AddGeneratingFamily.fg (g : AddGeneratingFamily S r) : AddMonoid.FG S := by
  classical
  exact AddMonoid.isAddFG_iff.2 ⟨Finset.univ.image g.toFun, by simpa using g.spans⟩

/-- Conversely, a finitely generated additive monoid carries a finite generating family, so the
constructions below apply to every finitely generated additive monoid. -/
theorem exists_addGeneratingFamily (S : Type*) [AddCommMonoid S] [AddMonoid.FG S] :
    ∃ r, Nonempty (AddGeneratingFamily S r) := by
  obtain ⟨T, hT⟩ := AddMonoid.exists_of_isAddFG S
  refine ⟨T.card, ⟨⟨((↑) : {x // x ∈ T} → S) ∘ T.equivFin.symm, ?_⟩⟩⟩
  rw [T.equivFin.symm.surjective.range_comp]
  simpa using hT

/-- Evaluation of the affine complex points of `S` on a finite generating family. -/
noncomputable def monomialEmbedding (g : AddGeneratingFamily S r) :
    AffineSemigroupComplexPoint S → Fin r → ℂ :=
  fun x j ↦ x (MonoidAlgebra.single (ofAdd (g.toFun j)) 1)

/-- The `j`-th coordinate of the monomial embedding is evaluation at the monomial of the `j`-th
generator. -/
@[simp]
theorem monomialEmbedding_apply (g : AddGeneratingFamily S r)
    (x : AffineSemigroupComplexPoint S) (j : Fin r) :
    monomialEmbedding g x j = x (MonoidAlgebra.single (ofAdd (g.toFun j)) 1) := (rfl)

/-- Evaluation at any monomial is a monomial in the coordinates of a monomial embedding, with
exponents given by any expression of the monoid element through the generating family. -/
theorem apply_single_eq_prod_monomialEmbedding (g : AddGeneratingFamily S r) {s : S}
    {a : Fin r → ℕ} (ha : s = ∑ j, a j • g.toFun j) (x : AffineSemigroupComplexPoint S) :
    x (MonoidAlgebra.single (ofAdd s) 1) = ∏ j, monomialEmbedding g x j ^ a j := by
  have key : ∀ t : S, x (MonoidAlgebra.single (ofAdd t) 1) =
      (MonoidAlgebra.lift ℂ ℂ (Multiplicative S)).symm x (ofAdd t) := fun t =>
    (MonoidAlgebra.lift_symm_apply x (ofAdd t)).symm
  rw [ha]
  simp only [monomialEmbedding_apply, key]
  simp only [ofAdd_sum, ofAdd_nsmul, map_prod, map_pow]

/-- An affine complex point is determined by its values on a finite generating family. -/
theorem monomialEmbedding_injective (g : AddGeneratingFamily S r) :
    Function.Injective (monomialEmbedding g) := by
  intro x y hxy
  refine AffineSemigroupComplexPoint.ext fun s ↦ ?_
  obtain ⟨a, ha⟩ := AddSubmonoid.exists_of_mem_closure_range g.toFun s (by
    rw [g.spans]
    trivial)
  rw [apply_single_eq_prod_monomialEmbedding g ha x,
    apply_single_eq_prod_monomialEmbedding g ha y, hxy]

/-- The range of a monomial embedding is the locus of the binomial relations of the generating
family: a point of `ℂ^r` extends to an affine complex point exactly when every additive relation
between the generators is matched by the corresponding multiplicative relation. -/
theorem range_monomialEmbedding (g : AddGeneratingFamily S r) :
    Set.range (monomialEmbedding g) =
      {z : Fin r → ℂ | ∀ a b : Fin r → ℕ, ∑ j, a j • g.toFun j = ∑ j, b j • g.toFun j →
        ∏ j, z j ^ a j = ∏ j, z j ^ b j} := by
  ext z
  constructor
  · rintro ⟨x, rfl⟩ a b hab
    rw [← apply_single_eq_prod_monomialEmbedding g rfl x,
      ← apply_single_eq_prod_monomialEmbedding g rfl x, hab]
  · intro hz
    choose a ha using fun s ↦ AddSubmonoid.exists_of_mem_closure_range g.toFun s (by
      rw [g.spans]
      trivial)
    -- The relations satisfied by `z` make `s ↦ ∏ j, z j ^ a s j` a well-defined character.
    have hprod : ∀ b : Fin r → ℕ, ∀ s : S, s = ∑ j, b j • g.toFun j →
        ∏ j, z j ^ a s j = ∏ j, z j ^ b j := fun b s hs ↦ hz _ _ (by rw [← ha s, ← hs])
    have hone : ∏ j, z j ^ a 0 j = 1 := by
      rw [hprod 0 0 (by simp)]
      simp
    have hmul : ∀ s t : S, ∏ j, z j ^ a (s + t) j =
        (∏ j, z j ^ a s j) * ∏ j, z j ^ a t j := by
      intro s t
      rw [hprod (a s + a t) (s + t)
        (by simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib, ← ha])]
      simp [pow_add, Finset.prod_mul_distrib]
    refine ⟨MonoidAlgebra.lift ℂ ℂ (Multiplicative S)
      ⟨⟨fun m ↦ ∏ j, z j ^ a (toAdd m) j, hone⟩, fun m n ↦ hmul _ _⟩, ?_⟩
    funext j
    have hsingle : g.toFun j = ∑ k, (Pi.single j 1 : Fin r → ℕ) k • g.toFun k := by
      simp [Pi.single_apply, ite_smul, Finset.sum_ite_eq']
    simp only [monomialEmbedding_apply, MonoidAlgebra.lift_single, one_smul, MonoidHom.coe_mk,
      OneHom.coe_mk, toAdd_ofAdd]
    rw [hprod (Pi.single j 1) (g.toFun j) hsingle]
    simp [Pi.single_apply, pow_ite, Finset.prod_ite_eq']

/-- The range of a monomial embedding is closed: it is the common zero locus of the differences
of the binomials attached to the additive relations of the generating family. -/
theorem isClosed_range_monomialEmbedding (g : AddGeneratingFamily S r) :
    IsClosed (Set.range (monomialEmbedding g)) := by
  rw [range_monomialEmbedding]
  have : {z : Fin r → ℂ | ∀ a b : Fin r → ℕ, ∑ j, a j • g.toFun j = ∑ j, b j • g.toFun j →
        ∏ j, z j ^ a j = ∏ j, z j ^ b j} =
      ⋂ a : Fin r → ℕ, ⋂ b : Fin r → ℕ,
        ⋂ _ : ∑ j, a j • g.toFun j = ∑ j, b j • g.toFun j,
          {z : Fin r → ℂ | ∏ j, z j ^ a j = ∏ j, z j ^ b j} := by
    ext z; simp
  rw [this]
  exact isClosed_iInter fun a ↦ isClosed_iInter fun b ↦ isClosed_iInter fun _ ↦
    isClosed_eq (by fun_prop) (by fun_prop)

/-- The topology on the affine complex points of `S` induced by evaluation on a finite
generating family. It is independent of the family by `affinePointTopology_eq`. -/
@[instance_reducible]
noncomputable def affinePointTopology (g : AddGeneratingFamily S r) :
    TopologicalSpace (AffineSemigroupComplexPoint S) :=
  TopologicalSpace.induced (monomialEmbedding g) inferInstance

/-- The monomial embedding is continuous for the topology it induces. -/
theorem continuous_monomialEmbedding (g : AddGeneratingFamily S r) :
    Continuous[affinePointTopology g, inferInstance] (monomialEmbedding g) :=
  continuous_iff_le_induced.mpr le_rfl

/-- Evaluation at a fixed monomial is continuous for the monomial-embedding topology: it is a
monomial in the coordinates of the embedding. -/
theorem continuous_apply_single (g : AddGeneratingFamily S r) (s : S) :
    Continuous[affinePointTopology g, inferInstance]
      fun x : AffineSemigroupComplexPoint S ↦ x (MonoidAlgebra.single (ofAdd s) 1) := by
  -- install the induced topology as an instance so that the continuity combinators apply
  let _ := affinePointTopology g
  obtain ⟨a, ha⟩ := AddSubmonoid.exists_of_mem_closure_range g.toFun s (by
    rw [g.spans]
    trivial)
  simp only [apply_single_eq_prod_monomialEmbedding g ha]
  exact continuous_finsetProd _ fun k _ ↦
    ((continuous_apply k).comp (continuous_monomialEmbedding g)).pow _

/-- Evaluation at a fixed element of the coordinate ring is continuous for the
monomial-embedding topology: such an element is a finite linear combination of monomials, and
evaluation at each monomial is continuous. -/
theorem continuous_eval_const (g : AddGeneratingFamily S r)
    (f : MonoidAlgebra ℂ (Multiplicative S)) :
    Continuous[affinePointTopology g, inferInstance]
      fun x : AffineSemigroupComplexPoint S ↦ x f := by
  let _ := affinePointTopology g
  have hf : ∀ x : AffineSemigroupComplexPoint S,
      x f = ∑ m ∈ f.coeff.support, f.coeff m * x (MonoidAlgebra.single m 1) := by
    intro x
    conv_lhs => rw [← MonoidAlgebra.sum_coeff_single f]
    rw [Finsupp.sum, map_sum]
    refine Finset.sum_congr rfl fun m _ ↦ ?_
    have hsingle : MonoidAlgebra.single m (f.coeff m) =
        f.coeff m • MonoidAlgebra.single (R := ℂ) m 1 := by
      rw [MonoidAlgebra.smul_single', mul_one]
    rw [hsingle, map_smul, smul_eq_mul]
  simp only [hf]
  exact continuous_finsetSum _ fun m _ ↦
    continuous_const.mul (continuous_apply_single g (toAdd m))

/-- The monomial-embedding topology is the coarsest one making evaluation at every monomial
continuous. This description mentions no generating family, so it identifies the topologies
induced by any two of them. -/
theorem affinePointTopology_eq_iInf (g : AddGeneratingFamily S r) :
    affinePointTopology g =
      ⨅ s : S, TopologicalSpace.induced
        (fun x : AffineSemigroupComplexPoint S ↦ x (MonoidAlgebra.single (ofAdd s) 1))
        inferInstance := by
  refine le_antisymm (le_iInf fun s ↦ (continuous_apply_single g s).le_induced) ?_
  rw [affinePointTopology, induced_to_pi]
  simp only [monomialEmbedding_apply]
  exact le_iInf fun j ↦ iInf_le _ (g.toFun j)

/-- A map into the affine complex points is continuous for the monomial-embedding topology exactly
when its composite with evaluation at every monomial is continuous. -/
theorem continuous_iff_forall_continuous_apply_single {X : Type*} [TopologicalSpace X]
    (g : AddGeneratingFamily S r) (φ : X → AffineSemigroupComplexPoint S) :
    Continuous[inferInstance, affinePointTopology g] φ ↔
      ∀ s : S, Continuous fun x ↦ φ x (MonoidAlgebra.single (ofAdd s) 1) := by
  rw [affinePointTopology_eq_iInf g, continuous_iInf_rng]
  exact forall_congr' fun s ↦ continuous_induced_rng

/-- The monomial-embedding topology does not depend on the chosen finite generating family. -/
theorem affinePointTopology_eq (g : AddGeneratingFamily S r) (h : AddGeneratingFamily S r') :
    affinePointTopology g = affinePointTopology h :=
  (affinePointTopology_eq_iInf g).trans (affinePointTopology_eq_iInf h).symm

/-- A monomial embedding is a closed embedding for the topology it induces. -/
theorem isClosedEmbedding_monomialEmbedding (g : AddGeneratingFamily S r) :
    letI := affinePointTopology g
    Topology.IsClosedEmbedding (monomialEmbedding g) :=
  letI := affinePointTopology g
  ⟨⟨⟨rfl⟩, monomialEmbedding_injective g⟩,
    isClosed_range_monomialEmbedding g⟩

/-- The affine complex points of a finitely generated additive monoid are Hausdorff. -/
theorem t2Space_affinePointTopology (g : AddGeneratingFamily S r) :
    letI := affinePointTopology g
    T2Space (AffineSemigroupComplexPoint S) :=
  letI := affinePointTopology g
  (isClosedEmbedding_monomialEmbedding g).isEmbedding.t2Space

/-- The affine complex points of a finitely generated additive monoid are second countable. -/
theorem secondCountableTopology_affinePointTopology (g : AddGeneratingFamily S r) :
    letI := affinePointTopology g
    SecondCountableTopology (AffineSemigroupComplexPoint S) :=
  letI := affinePointTopology g
  (isClosedEmbedding_monomialEmbedding g).isEmbedding.secondCountableTopology

/-- The affine complex points of a finitely generated additive monoid are locally compact: the
monomial embedding realizes them as a closed subset of a complex affine space. -/
theorem locallyCompactSpace_affinePointTopology (g : AddGeneratingFamily S r) :
    letI := affinePointTopology g
    LocallyCompactSpace (AffineSemigroupComplexPoint S) :=
  letI := affinePointTopology g
  (isClosedEmbedding_monomialEmbedding g).locallyCompactSpace

/-- The complex points at which the monomials of a finite generating family have absolute value at
most `R` form a compact set: it is the preimage of a closed polydisc under the monomial embedding,
which is a closed embedding. -/
theorem isCompact_setOf_forall_norm_apply_single_toFun_le (g : AddGeneratingFamily S r) (R : ℝ) :
    letI := affinePointTopology g
    IsCompact {x : AffineSemigroupComplexPoint S |
      ∀ j, ‖x (MonoidAlgebra.single (ofAdd (g.toFun j)) 1)‖ ≤ R} := by
  let _ := affinePointTopology g
  have h : {x : AffineSemigroupComplexPoint S |
      ∀ j, ‖x (MonoidAlgebra.single (ofAdd (g.toFun j)) 1)‖ ≤ R} =
      monomialEmbedding g ⁻¹' Set.univ.pi fun _ ↦ Metric.closedBall 0 R := by
    ext x
    simp
  rw [h]
  exact (isClosedEmbedding_monomialEmbedding g).isCompact_preimage
    (isCompact_univ_pi fun _ ↦ isCompact_closedBall 0 R)

/-- The complex points at which every monomial has absolute value at most `1` form a compact set.
For the dual semigroup of a cone, this is the part of the affine chart lying over the cone under
the logarithm of absolute values; for a complete fan these parts of the charts cover the analytic
realization. -/
theorem isCompact_setOf_forall_norm_apply_single_le_one (g : AddGeneratingFamily S r) :
    letI := affinePointTopology g
    IsCompact {x : AffineSemigroupComplexPoint S |
      ∀ s : S, ‖x (MonoidAlgebra.single (ofAdd s) 1)‖ ≤ 1} := by
  -- A monomial is a product of powers of generators, so it suffices to bound the generators.
  have h : {x : AffineSemigroupComplexPoint S |
      ∀ s : S, ‖x (MonoidAlgebra.single (ofAdd s) 1)‖ ≤ 1} =
      {x | ∀ j, ‖x (MonoidAlgebra.single (ofAdd (g.toFun j)) 1)‖ ≤ 1} := by
    ext x
    refine ⟨fun hx j ↦ hx (g.toFun j), fun hx s ↦ ?_⟩
    obtain ⟨a, ha⟩ := AddSubmonoid.exists_of_mem_closure_range g.toFun s (by
      rw [g.spans]
      trivial)
    rw [apply_single_eq_prod_monomialEmbedding g ha, norm_prod]
    exact Finset.prod_le_one₀ (fun _ _ ↦ norm_nonneg _) fun j _ ↦ by
      rw [norm_pow]
      exact pow_le_one₀ (norm_nonneg _) (hx j)
  rw [h]
  exact isCompact_setOf_forall_norm_apply_single_toFun_le g 1

/-! ### Functoriality in the semigroup -/

namespace AffineSemigroupComplexPoint

variable {T U : Type*} [AddCommMonoid T] [AddCommMonoid U]

/-- The map on affine complex points induced by a homomorphism `f : S →+ T` of additive monoids:
a point of `T` is pulled back to a point of `S` by precomposing it with the map `ℂ[S] → ℂ[T]` of
monoid algebras induced by `f`. The construction is contravariant in the semigroup. -/
noncomputable def comap (f : S →+ T) :
    AffineSemigroupComplexPoint T → AffineSemigroupComplexPoint S :=
  fun x ↦ x.comp (MonoidAlgebra.mapDomainAlgHom ℂ ℂ (AddMonoidHom.toMultiplicative f))

/-- The pulled-back point is the original point composed with the induced map of monoid
algebras. -/
@[simp]
theorem comap_apply (f : S →+ T) (x : AffineSemigroupComplexPoint T)
    (a : MonoidAlgebra ℂ (Multiplicative S)) :
    comap f x a = x (MonoidAlgebra.mapDomainAlgHom ℂ ℂ (AddMonoidHom.toMultiplicative f) a) :=
  (rfl)

/-- The pulled-back point takes the value of the original point on the image monomial. -/
theorem comap_apply_single (f : S →+ T) (x : AffineSemigroupComplexPoint T) (s : S) :
    comap f x (MonoidAlgebra.single (ofAdd s) 1) = x (MonoidAlgebra.single (ofAdd (f s)) 1) := by
  simp [comap_apply]

/-- Pulling back preserves the distinguished point whose monomial values are all one. -/
@[simp]
theorem comap_default (f : S →+ T) :
    comap f (default : AffineSemigroupComplexPoint T) = default :=
  AffineSemigroupComplexPoint.ext fun s ↦ by rw [comap_apply_single]; simp

/-- Pulling back along the identity does nothing. -/
@[simp]
theorem comap_id : comap (AddMonoidHom.id S) = id := by
  funext x
  rw [comap, AddMonoidHom.toMultiplicative_id, MonoidAlgebra.mapDomainAlgHom_id,
    AlgHom.comp_id]
  rfl

/-- Pulling back along two homomorphisms in turn is pulling back along their composite. -/
@[simp]
theorem comap_comap (f : S →+ T) (f' : T →+ U) (x : AffineSemigroupComplexPoint U) :
    comap f (comap f' x) = comap (f'.comp f) x := by
  -- Mathlib supplies `AddMonoidHom.toMultiplicative_id` but no composition counterpart.
  have hcomp : AddMonoidHom.toMultiplicative (f'.comp f) =
      (AddMonoidHom.toMultiplicative f').comp (AddMonoidHom.toMultiplicative f) := by
    ext s
    simp
  simp only [comap, hcomp, MonoidAlgebra.mapDomainAlgHom_comp, AlgHom.comp_assoc]

/-- The pullback of complex points is contravariant for composition. -/
theorem comap_comp (f : S →+ T) (f' : T →+ U) : comap (f'.comp f) = comap f ∘ comap f' := by
  funext x
  exact (comap_comap f f' x).symm

/-- The map induced by a homomorphism of additive monoids is continuous for the
monomial-embedding topologies attached to any finite generating families of the source and the
target. -/
theorem continuous_comap (g : AddGeneratingFamily S r) (h : AddGeneratingFamily T r')
    (f : S →+ T) : Continuous[affinePointTopology h, affinePointTopology g] (comap f) := by
  -- install the source topology as an instance so that `continuous_apply_single` applies
  let _ := affinePointTopology h
  rw [affinePointTopology_eq_iInf g, continuous_iInf_rng]
  intro s
  rw [continuous_induced_rng]
  simpa [Function.comp_def] using continuous_apply_single h (f s)

/-- An isomorphism of additive monoids induces a bijection between their affine complex
points. -/
noncomputable def comapEquiv (e : S ≃+ T) :
    AffineSemigroupComplexPoint T ≃ AffineSemigroupComplexPoint S where
  toFun := comap (e : S →+ T)
  invFun := comap (e.symm : T →+ S)
  left_inv x := by simp
  right_inv x := by simp

@[simp]
theorem coe_comapEquiv (e : S ≃+ T) : ⇑(comapEquiv e) = comap (e : S →+ T) := (rfl)

@[simp]
theorem comapEquiv_symm (e : S ≃+ T) : (comapEquiv e).symm = comapEquiv e.symm := (rfl)

/-- An isomorphism of additive monoids induces a homeomorphism between their affine complex
points, for the monomial-embedding topologies attached to any finite generating families. -/
noncomputable def comapHomeomorph (e : S ≃+ T) (g : AddGeneratingFamily S r)
    (h : AddGeneratingFamily T r') :
    @Homeomorph (AffineSemigroupComplexPoint T) (AffineSemigroupComplexPoint S)
      (affinePointTopology h) (affinePointTopology g) :=
  @Homeomorph.mk _ _ (affinePointTopology h) (affinePointTopology g) (comapEquiv e)
    (continuous_comap g h _) (continuous_comap h g _)

@[simp]
theorem coe_comapHomeomorph (e : S ≃+ T) (g : AddGeneratingFamily S r)
    (h : AddGeneratingFamily T r') :
    ⇑(comapHomeomorph e g h) = comap (e : S →+ T) :=
  (rfl)

@[simp]
theorem comapHomeomorph_symm (e : S ≃+ T) (g : AddGeneratingFamily S r)
    (h : AddGeneratingFamily T r') :
    @Homeomorph.symm _ _ (affinePointTopology h) (affinePointTopology g)
      (comapHomeomorph e g h) = comapHomeomorph e.symm h g :=
  (rfl)

end AffineSemigroupComplexPoint

/-! ### Points of a join of submonoids -/

namespace AffineSemigroupComplexPoint

variable {M : Type*} [AddCommMonoid M] {S₁ S₂ S₃ : AddSubmonoid M}

/-- Let `S₃` be a submonoid generated by two submonoids `S₁` and `S₂` that it contains. A point of
`S₁` and a point of `S₂` are the restrictions of a common point of `S₃` exactly when they are
compatible with every additive relation `s + t = s' + t'` between elements of `S₁` and of `S₂`.
For the dual semigroups of two cones meeting in a common face, this describes the chart of the
common face inside the product of the two charts by binomial equations. -/
theorem exists_comap_inclusion_eq_iff (h₁ : S₁ ≤ S₃) (h₂ : S₂ ≤ S₃) (h₃ : S₃ ≤ S₁ ⊔ S₂)
    (x : AffineSemigroupComplexPoint S₁) (y : AffineSemigroupComplexPoint S₂) :
    (∃ z : AffineSemigroupComplexPoint S₃,
        comap (AddSubmonoid.inclusion h₁) z = x ∧ comap (AddSubmonoid.inclusion h₂) z = y) ↔
      ∀ (s s' : S₁) (t t' : S₂), (s : M) + t = s' + t' →
        x (MonoidAlgebra.single (ofAdd s) 1) * y (MonoidAlgebra.single (ofAdd t) 1) =
          x (MonoidAlgebra.single (ofAdd s') 1) * y (MonoidAlgebra.single (ofAdd t') 1) := by
  constructor
  · rintro ⟨z, rfl, rfl⟩ s s' t t' h
    simp only [comap_apply_single, ← apply_single_add]
    congr 3
    exact Subtype.ext h
  intro h
  -- Every element of `S₃` is a sum of an element of `S₁` and an element of `S₂`.
  let π : S₁ × S₂ →+ S₃ := (AddSubmonoid.inclusion h₁).coprod (AddSubmonoid.inclusion h₂)
  have hπ : Function.Surjective π := fun w ↦ by
    obtain ⟨s, hs, t, ht, hst⟩ := AddSubmonoid.mem_sup.1 (h₃ w.2)
    exact ⟨(⟨s, hs⟩, ⟨t, ht⟩), Subtype.ext hst⟩
  -- The product character on `S₁ × S₂` is constant on the fibres of `π`, so it descends to `S₃`.
  let χ : S₁ × S₂ → ℂ := fun p ↦
    x (MonoidAlgebra.single (ofAdd p.1) 1) * y (MonoidAlgebra.single (ofAdd p.2) 1)
  have hχ : ∀ p, χ (Function.surjInv hπ (π p)) = χ p := fun p ↦
    h _ _ _ _ (congrArg Subtype.val (Function.surjInv_eq hπ (π p)))
  have hχ_add : ∀ p q, χ (p + q) = χ p * χ q := fun p q ↦ by
    simp only [χ, Prod.fst_add, Prod.snd_add, apply_single_add]
    ring
  let f : Multiplicative S₃ →* ℂ :=
    { toFun w := χ (Function.surjInv hπ (toAdd w))
      map_one' := by
        have : π 0 = toAdd (1 : Multiplicative S₃) := by ext; simp [π]
        rw [← this, hχ]
        simp [χ, ← MonoidAlgebra.one_def]
      map_mul' w w' := by
        have : toAdd (w * w') =
            π (Function.surjInv hπ (toAdd w) + Function.surjInv hπ (toAdd w')) := by
          rw [map_add, Function.surjInv_eq hπ, Function.surjInv_eq hπ, toAdd_mul]
        rw [this, hχ, hχ_add] }
  refine ⟨MonoidAlgebra.lift ℂ ℂ (Multiplicative S₃) f, ext fun s ↦ ?_, ext fun t ↦ ?_⟩ <;>
    simp only [comap_apply_single, MonoidAlgebra.lift_single, one_smul]
  · have : AddSubmonoid.inclusion h₁ s = π (s, 0) := by simp [π]
    simp only [f, MonoidHom.coe_mk, OneHom.coe_mk, toAdd_ofAdd, this, hχ]
    simp [χ, ← MonoidAlgebra.one_def]
  · have : AddSubmonoid.inclusion h₂ t = π (0, t) := by simp [π]
    simp only [f, MonoidHom.coe_mk, OneHom.coe_mk, toAdd_ofAdd, this, hχ]
    simp [χ, ← MonoidAlgebra.one_def]

/-- Let `S₃` be a submonoid generated by two submonoids `S₁` and `S₂` that it contains. The pairs
consisting of a point of `S₁` and a point of `S₂` that are restrictions of a common point of `S₃`
form a closed subset of the product of the two monomial-embedding topologies. -/
theorem isClosed_setOf_exists_comap_inclusion_eq (h₁ : S₁ ≤ S₃) (h₂ : S₂ ≤ S₃) (h₃ : S₃ ≤ S₁ ⊔ S₂)
    (g : AddGeneratingFamily S₁ r) (h : AddGeneratingFamily S₂ r') :
    IsClosed[@instTopologicalSpaceProd _ _ (affinePointTopology g) (affinePointTopology h)]
      {p : AffineSemigroupComplexPoint S₁ × AffineSemigroupComplexPoint S₂ |
        ∃ z : AffineSemigroupComplexPoint S₃,
          comap (AddSubmonoid.inclusion h₁) z = p.1 ∧
            comap (AddSubmonoid.inclusion h₂) z = p.2} := by
  let _ := affinePointTopology g
  let _ := affinePointTopology h
  simp only [exists_comap_inclusion_eq_iff h₁ h₂ h₃, Set.ofPred_forall]
  refine isClosed_iInter fun s ↦ isClosed_iInter fun s' ↦ isClosed_iInter fun t ↦
    isClosed_iInter fun t' ↦ isClosed_iInter fun _ ↦ isClosed_eq ?_ ?_ <;>
  exact (((continuous_apply_single g _).comp continuous_fst).mul
    ((continuous_apply_single h _).comp continuous_snd))

end AffineSemigroupComplexPoint

end TauCeti.Toric
