/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Scheme
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic
public import Mathlib.LinearAlgebra.Matrix.Block

/-!
# Weight-parabolic subgroup schemes of the general linear group

An integer weight `w i` on each coordinate of `GL_N` cuts out the matrices whose `(i,j)` entry
vanishes whenever `w i < w j`. This file represents that weight parabolic by a finite-type closed
subgroup scheme over an arbitrary commutative base ring.

The defining Hopf ideal is generated by the forbidden matrix coordinates `X_ij` with
`w i < w j`. Comultiplication preserves this ideal because, for every intermediate index `k`,
either `w i < w k` or `w k < w j`. Antipode stability follows because the inverse of a
block-triangular invertible matrix is block triangular.

## Main declarations

* `TauCeti.GeneralLinear.weightParabolicDefiningHopfIdeal`: the Hopf ideal generated by the
  forbidden coordinates.
* `TauCeti.GeneralLinear.weightParabolicGroupScheme`: the resulting closed subgroup scheme.
* `TauCeti.GeneralLinear.weightParabolicInclusion`: its closed immersion into `GL_N`.
* `TauCeti.GeneralLinear.mem_weightParabolicDefiningPointsSubgroup_iff_blockTriangular`: a point
  of `GL_N` over an `R`-algebra lies in the subgroup cut out by the ideal exactly when its matrix
  is block triangular for the order dual of `w`, that is, its `(i,j)` entry vanishes whenever
  `w i < w j`.

## References

* G. R. Kempf, *Instability in invariant theory*, Annals of Mathematics 108 (1978), §2.
* J. S. Milne, *Algebraic Groups* (2017), Chapter 13.
* The Hopf-ideal quotient, closed-subgroup packaging, and algebra-valued points construction
  were adapted from the original construction of
  `TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Borel`, which in turn adapted
  `TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Basic`.
-/

public section

open AlgebraicGeometry CategoryTheory

namespace TauCeti.GeneralLinear

universe u

variable (R : Type u) [CommRing R] {N : ℕ}

/-- The set of matrix coordinates forbidden by the decreasing weight filtration. -/
def weightParabolicRelationSet (w : Fin N → ℤ) :
    Set (coordinateHopfAlgebra R N) :=
  {x | ∃ i j, w i < w j ∧
    x = coordinateHopfAlgebraAlgEquiv R N
      (coordinateRingMap R N (MvPolynomial.X (i, j)))}

/-- Membership in the weight-parabolic relation set means being a forbidden matrix coordinate. -/
@[simp]
theorem mem_weightParabolicRelationSet_iff (w : Fin N → ℤ)
    (x : coordinateHopfAlgebra R N) :
    x ∈ weightParabolicRelationSet R w ↔
      ∃ i j, w i < w j ∧
        x = coordinateHopfAlgebraAlgEquiv R N
          (coordinateRingMap R N (MvPolynomial.X (i, j))) :=
  Iff.rfl

/-- A forbidden matrix coordinate belongs to the weight-parabolic relation set. -/
theorem X_mem_weightParabolicRelationSet (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    coordinateHopfAlgebraAlgEquiv R N
        (coordinateRingMap R N (MvPolynomial.X (i, j))) ∈
      weightParabolicRelationSet R w :=
  ⟨i, j, hij, rfl⟩

private theorem comul_X_mem (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    Coalgebra.comul (R := R)
        (coordinateHopfAlgebraAlgEquiv R N
          (coordinateRingMap R N (MvPolynomial.X (i, j)))) ∈
      HopfIdeal.leftTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
          (Ideal.span (weightParabolicRelationSet R w)) ⊔
        HopfIdeal.rightTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
          (Ideal.span (weightParabolicRelationSet R w)) := by
  rw [coordinateHopfAlgebra_comul_X]
  apply Submodule.sum_mem
  intro k _
  by_cases hik : w i < w k
  · exact Ideal.mem_sup_left <|
      HopfIdeal.tmul_mem_leftTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
        (Ideal.subset_span (X_mem_weightParabolicRelationSet R w hik)) _
  · have hkj : w k < w j := (not_lt.mp hik).trans_lt hij
    exact Ideal.mem_sup_right <|
      HopfIdeal.tmul_mem_rightTensorIdeal (R := R) (H := coordinateHopfAlgebra R N) _
        (Ideal.subset_span (X_mem_weightParabolicRelationSet R w hkj))

private theorem counit_forbidden_X (w : Fin N → ℤ) {i j : Fin N} (hij : w i < w j) :
    Coalgebra.counit (R := R)
      (coordinateHopfAlgebraAlgEquiv R N
        (coordinateRingMap R N (MvPolynomial.X (i, j)))) = 0 := by
  rw [coordinateHopfAlgebra_counit_X]
  simp only [ite_eq_right_iff]
  exact fun h ↦ (hij.ne (congrArg w h)).elim

private theorem antipode_X_mem (w : Fin N → ℤ) {i j : Fin N} (hij : w i < w j) :
    HopfAlgebra.antipode R
        (coordinateHopfAlgebraAlgEquiv R N
          (coordinateRingMap R N (MvPolynomial.X (i, j)))) ∈
      Ideal.span (weightParabolicRelationSet R w) := by
  let J : Ideal (coordinateHopfAlgebra R N) :=
    Ideal.span (weightParabolicRelationSet R w)
  let q : coordinateHopfAlgebra R N →ₐ[R] (coordinateHopfAlgebra R N ⧸ J) :=
    Ideal.Quotient.mkₐ R J
  let Xq : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N ⧸ J) :=
    (genericMatrix R N).map q
  have hXq : Xq.BlockTriangular (OrderDual.toDual ∘ w) := by
    intro a b hab
    have hw : w a < w b := OrderDual.toDual_lt_toDual.mp hab
    simp only [Xq, Matrix.map_apply, genericMatrix_apply]
    simpa only [q, Ideal.Quotient.mkₐ_eq_mk] using
      (Ideal.Quotient.eq_zero_iff_mem.mpr <|
        Ideal.subset_span (X_mem_weightParabolicRelationSet R w hw))
  have hdetXq : IsUnit Xq.det := by
    simp only [Xq, ← AlgHom.mapMatrix_apply, ← AlgHom.map_det]
    exact (isUnit_det_genericMatrix R N).map q
  let _ : Invertible Xq := Matrix.invertibleOfIsUnitDet Xq hdetXq
  have hXqInv : Xq⁻¹.BlockTriangular (OrderDual.toDual ∘ w) :=
    Matrix.blockTriangular_inv_of_blockTriangular hXq
  rw [coordinateHopfAlgebra_antipode_X]
  apply (Ideal.Quotient.eq_zero_iff_mem).mp
  have hzero := hXqInv (OrderDual.toDual_lt_toDual.mpr hij)
  rw [← map_inv_genericMatrix R N q, Matrix.map_apply, genericMatrix_inv_apply] at hzero
  exact hzero

/-- The Hopf ideal cutting out matrices block triangular for the decreasing weight filtration. -/
noncomputable def weightParabolicDefiningHopfIdeal (w : Fin N → ℤ) :
    HopfIdeal R (coordinateHopfAlgebra R N) :=
  HopfIdeal.ofSpan (weightParabolicRelationSet R w)
    (fun x hx => by
      obtain ⟨i, j, hij, rfl⟩ := hx
      exact comul_X_mem R w hij)
    (fun x hx => by
      obtain ⟨i, j, hij, rfl⟩ := hx
      exact counit_forbidden_X R w hij)
    (fun x hx => by
      obtain ⟨i, j, hij, rfl⟩ := hx
      exact antipode_X_mem R w hij)

/-- The underlying ideal is generated by precisely the forbidden matrix coordinates. -/
@[simp]
theorem weightParabolicDefiningHopfIdeal_toIdeal (w : Fin N → ℤ) :
    (weightParabolicDefiningHopfIdeal R w).toIdeal =
      Ideal.span (weightParabolicRelationSet R w) := by
  rw [weightParabolicDefiningHopfIdeal, HopfIdeal.ofSpan_toIdeal]

/-- The coordinate Hopf algebra of the weight parabolic attached to `w`. -/
noncomputable abbrev weightParabolicCoordinateHopfAlgebra (w : Fin N → ℤ) :
    _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (coordinateHopfAlgebra R N)
    (weightParabolicDefiningHopfIdeal R w)

/-- The quotient coordinate morphism from `O(GL_N)` to the weight-parabolic coordinate algebra. -/
noncomputable def weightParabolicCoordinateMap (w : Fin N → ℤ) :
    coordinateHopfAlgebra R N ⟶ weightParabolicCoordinateHopfAlgebra R w :=
  CommHopfAlgCat.mkQuotient (coordinateHopfAlgebra R N)
    (weightParabolicDefiningHopfIdeal R w)

/-- The weight-parabolic coordinate morphism sends an ambient coordinate to its quotient
class. -/
theorem weightParabolicCoordinateMap_apply (w : Fin N → ℤ)
    (h : coordinateHopfAlgebra R N) :
    (weightParabolicCoordinateMap R w).hom h =
      Ideal.Quotient.mkₐ R (weightParabolicDefiningHopfIdeal R w).toIdeal h := by
  rw [weightParabolicCoordinateMap]
  exact CommHopfAlgCat.mkQuotient_apply
    (coordinateHopfAlgebra R N) (weightParabolicDefiningHopfIdeal R w) h

/-- The quotient coordinate morphism defining the weight parabolic is surjective. -/
theorem weightParabolicCoordinateMap_surjective (w : Fin N → ℤ) :
    Function.Surjective (weightParabolicCoordinateMap R w).hom :=
  CommHopfAlgCat.mkQuotient_surjective
    (coordinateHopfAlgebra R N) (weightParabolicDefiningHopfIdeal R w)

/-- A forbidden coordinate vanishes in the weight-parabolic coordinate algebra. -/
@[simp]
theorem weightParabolicCoordinateMap_X (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    (weightParabolicCoordinateMap R w).hom
        (coordinateHopfAlgebraAlgEquiv R N
          (coordinateRingMap R N (MvPolynomial.X (i, j)))) = 0 := by
  rw [weightParabolicCoordinateMap_apply, Ideal.Quotient.mkₐ_eq_mk,
    Ideal.Quotient.eq_zero_iff_mem, weightParabolicDefiningHopfIdeal_toIdeal]
  exact Ideal.subset_span (X_mem_weightParabolicRelationSet R w hij)

/-- The affine group scheme represented by the weight-parabolic coordinate Hopf algebra. -/
noncomputable abbrev weightParabolicGroupScheme (w : Fin N → ℤ) :=
  CommHopfAlgCat.quotientSpec (coordinateHopfAlgebra R N)
    (weightParabolicDefiningHopfIdeal R w)

/-- The closed immersion from the weight parabolic into the named general linear group scheme. -/
noncomputable def weightParabolicInclusion (w : Fin N → ℤ) :
    weightParabolicGroupScheme R w ⟶ groupScheme R N :=
  hopfIdealInclusion R N (weightParabolicDefiningHopfIdeal R w)

/-- The weight-parabolic inclusion is the quotient-spectrum inclusion followed by the named
identification with `GL_N`. -/
theorem weightParabolicInclusion_def (w : Fin N → ℤ) :
    weightParabolicInclusion R w =
      CommHopfAlgCat.quotientSpecι (coordinateHopfAlgebra R N)
          (weightParabolicDefiningHopfIdeal R w) ≫
        (eqToIso (groupScheme_def R N).symm).hom := by
  rw [weightParabolicInclusion, hopfIdealInclusion_def]

/-- The coordinate morphism recovered from the weight-parabolic inclusion is the quotient
coordinate map. -/
@[simp]
theorem weightParabolicInclusion_coordinateMap (w : Fin N → ℤ) :
    ((AlgebraicGeometry.hopfSpec.fullyFaithful (R := CommRingCat.of R)).preimage
      (weightParabolicInclusion R w ≫ eqToHom (groupScheme_def R N))).unop =
      weightParabolicCoordinateMap R w := by
  refine Quiver.Hom.op_inj
    ((AlgebraicGeometry.hopfSpec.fullyFaithful (R := CommRingCat.of R)).map_injective ?_)
  rw [Quiver.Hom.op_unop,
    (AlgebraicGeometry.hopfSpec.fullyFaithful (R := CommRingCat.of R)).map_preimage]
  rw [weightParabolicInclusion_def]
  rw [CommHopfAlgCat.quotientSpecι_def]
  rw [weightParabolicCoordinateMap]
  simp

/-- The weight-parabolic inclusion into `GL_N` is a closed immersion. -/
instance isClosedImmersion_weightParabolicInclusion (w : Fin N → ℤ) :
    IsClosedImmersion (weightParabolicInclusion R w).hom.hom.left := by
  rw [weightParabolicInclusion]
  infer_instance

/-- The weight-parabolic coordinate Hopf algebra with its finite-type property. -/
noncomputable def weightParabolicFiniteTypeCoordinateHopfAlgebra (w : Fin N → ℤ) :
    FiniteTypeCommHopfAlgCat R :=
  ⟨weightParabolicCoordinateHopfAlgebra R w,
    inferInstanceAs (Algebra.FiniteType R (weightParabolicCoordinateHopfAlgebra R w))⟩

/-- The finite-type package has the weight-parabolic coordinate Hopf algebra as its object. -/
@[simp]
theorem weightParabolicFiniteTypeCoordinateHopfAlgebra_obj (w : Fin N → ℤ) :
    (weightParabolicFiniteTypeCoordinateHopfAlgebra R w).obj =
      weightParabolicCoordinateHopfAlgebra R w := by
  rfl

/-- The subgroup cut out by the weight-parabolic ideal consists exactly of block-triangular
ambient points. -/
@[simp]
theorem mem_weightParabolicDefiningPointsSubgroup_iff_blockTriangular (w : Fin N → ℤ)
    {A : Type*} [CommRing A] [Algebra R A]
    (g : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R N)
      (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup (coordinateHopfAlgebra R N)
        (weightParabolicDefiningHopfIdeal R w) (CommAlgCat.of R A) ↔
      (pointsMulEquiv N g : Matrix (Fin N) (Fin N) A).BlockTriangular
        (OrderDual.toDual ∘ w) := by
  rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff]
  simp only [Matrix.BlockTriangular, Function.comp_apply, OrderDual.toDual_lt_toDual]
  constructor
  · intro h i j hij
    rw [pointsMulEquiv_apply, pointToGeneralLinear_apply]
    exact h _ (HopfIdeal.mem_toIdeal.mp <|
      (weightParabolicDefiningHopfIdeal_toIdeal R w).symm ▸
        Ideal.subset_span (X_mem_weightParabolicRelationSet R w hij))
  · intro h x hx
    have hx' : x ∈ Ideal.span (weightParabolicRelationSet R w) :=
      weightParabolicDefiningHopfIdeal_toIdeal R w ▸ HopfIdeal.mem_toIdeal.mpr hx
    apply RingHom.mem_ker.mp
    refine (Ideal.span_le.2 ?_) hx'
    rintro y ⟨i, j, hij, rfl⟩
    apply RingHom.mem_ker.mpr
    rw [← pointToGeneralLinear_apply, ← pointsMulEquiv_apply]
    exact h hij

end TauCeti.GeneralLinear
