/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.AdjoinRoot
public import TauCeti.Algebra.Subalgebra.Center
public import TauCeti.LinearAlgebra.CliffordAlgebra.Center

import Mathlib.Algebra.Algebra.Prod
import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.FieldTheory.KummerPolynomial
import TauCeti.LinearAlgebra.CliffordAlgebra.Basic
import TauCeti.LinearAlgebra.CliffordAlgebra.Dimension
import TauCeti.LinearAlgebra.CliffordAlgebra.Grading
import TauCeti.LinearAlgebra.QuadraticForm.OrthogonalBasis

/-!
# The centre of the even Clifford algebra in even dimension

Let `Q` be a nondegenerate quadratic form on a vector space of even positive dimension `n` over a
field of characteristic different from two, let `v₁, …, vₙ` be an anisotropic orthogonal basis,
and let `ω = v₁ ⋯ vₙ` be its volume element. Then `ω` lies in the even Clifford algebra `C₀`, and

```text
  center C₀ = K ⊕ Kω ≅ K[X] ⧸ (X² - d),   d = (-1) ^ (n.choose 2) * Q v₁ ⋯ Q vₙ,
```

the root of `X² - d` going to `ω`. Up to squares, `d` is the signed discriminant of `Q`, so the
centre is the discriminant quadratic algebra of `Q`. This is the even-dimensional companion of
`CliffordAlgebra.center_eq_adjoin_volume`, which computes the centre of the full Clifford algebra in
odd dimension; in even dimension the full Clifford algebra is central
(`TauCeti.CliffordAlgebra.isCentral_of_even_finrank`) and the two-dimensional centre appears in
`C₀` instead. In dimension four this centre is the discriminant quadratic algebra over which `C₀`
is a quaternion algebra (a product of two quaternion algebras over `K` when it splits).

The volume element of an orthogonal spanning list of even length anticommutes with every vector,
hence commutes with every product of two vectors and so with all of `C₀`
(`CliffordAlgebra.prod_map_ι_mem_center_even_of_even_length`; this needs no field). For the
converse, splitting off a line identifies `C₀` with the full Clifford algebra of a regular form in
odd dimension `n - 1` (`TauCeti.CliffordAlgebra.exists_nonempty_algEquiv_even_of_finrank_pos`),
whose centre is two-dimensional by `CliffordAlgebra.mem_center_iff_exists_eq_add_smul_volume`.
Since `ω` is central but not a scalar (`CliffordAlgebra.prod_map_ι_ne_algebraMap_of_even_length`),
it spans the centre together with `1`.

## Main results

* `CliffordAlgebra.prod_map_ι_mem_center_even_of_even_length`: the volume element of an orthogonal
  spanning list of even length is central in the even Clifford algebra.
* `CliffordAlgebra.mem_center_even_iff_exists_eq_add_smul_volume`: in even positive dimension, an
  element of the even Clifford algebra is central exactly when it is of the form `a + b • ω`.
* `CliffordAlgebra.center_even_eq_adjoin_volume`: the centre of the even Clifford algebra is
  generated by the volume element.
* `CliffordAlgebra.adjoinRootEquivCenterEven`: the centre of the even Clifford algebra is
  `K[X] ⧸ (X² - d)`, the root going to the volume element.
* `CliffordAlgebra.isField_center_even_iff_not_isSquare_discriminant`: this centre is a field
  exactly when its signed discriminant is not a square.
* `CliffordAlgebra.nonempty_center_even_algEquiv_prod_iff_isSquare_discriminant`: this centre is
  isomorphic to `K × K` exactly when its signed discriminant is a square.
* `CliffordAlgebra.finite_even_over_center`: the even Clifford algebra is module-finite over its
  centre when the quadratic space is finite-dimensional.
* `CliffordAlgebra.finrank_center_even`: this centre has dimension two over the base field.
* `CliffordAlgebra.finrank_even_over_center`: when the centre is a field, the even Clifford
  algebra has dimension `2 ^ (finrank K V - 2)` over its centre, with
  `CliffordAlgebra.finrank_even_over_center_of_finrank_eq_four` the dimension-four case.
* `TauCeti.CliffordAlgebra.exists_mem_center_even_forall_ne_algebraMap`: in even positive
  dimension, the centre contains a non-scalar element.

## References

* M.-A. Knus, *Quadratic and Hermitian Forms over Rings* (1991), Chapter IV, §3.
* T. Y. Lam, *Introduction to Quadratic Forms over Fields* (2005), Chapter V, §2.
-/

public section

namespace CliffordAlgebra

open Module Polynomial

universe u v

section CommRing

variable {R : Type u} {M : Type v} [CommRing R] [AddCommGroup M] [Module R M]
  {Q : QuadraticForm R M}

/-- An ordered product of evenly many generators lies in the even Clifford algebra. -/
theorem prod_map_ι_mem_even_of_even_length {l : List M} (hlen : Even l.length) :
    (l.map (ι Q)).prod ∈ even Q := by
  rw [← Subalgebra.mem_toSubmodule, even_toSubmodule]
  exact prod_map_ι_mem_evenOdd_zero_of_even_length hlen

/-- **The volume element of even length is central in the even Clifford algebra.** The ordered
product of a pairwise orthogonal spanning list of even length anticommutes with every vector
(`CliffordAlgebra.prod_map_ι_mul_ι_of_even_length`), hence commutes with every product of two
vectors, and these generate the even Clifford algebra. -/
theorem prod_map_ι_mem_center_even_of_even_length {l : List M} (hl : l.Pairwise Q.IsOrtho)
    (hlen : Even l.length) (hspan : Submodule.span R {x : M | x ∈ l} = ⊤) :
    (⟨(l.map (ι Q)).prod, prod_map_ι_mem_even_of_even_length hlen⟩ : even Q) ∈
      Subalgebra.center R (even Q) := by
  set ω := (l.map (ι Q)).prod
  have key (m : M) : ω * ι Q m = -(ι Q m * ω) :=
    prod_map_ι_mul_ι_of_even_length hl hlen (hspan.ge Submodule.mem_top)
  have hcomm (y : CliffordAlgebra Q) (hy : y ∈ evenOdd Q 0) : y * ω = ω * y := by
    induction y, hy using even_induction with
    | algebraMap r => exact Algebra.commutes r ω
    | add x y _ _ hx hy => rw [add_mul, mul_add, hx, hy]
    | ι_mul_ι_mul m₁ m₂ x _ hx =>
      have key' (m : M) : ι Q m * ω = -(ω * ι Q m) := by rw [key, neg_neg]
      calc ι Q m₁ * ι Q m₂ * x * ω = ι Q m₁ * (ι Q m₂ * ω) * x := by
            rw [mul_assoc, hx]; simp only [mul_assoc]
        _ = -(ι Q m₁ * ω * ι Q m₂ * x) := by
            rw [key' m₂]; simp only [mul_neg, neg_mul, mul_assoc]
        _ = ω * (ι Q m₁ * ι Q m₂ * x) := by
            rw [key' m₁]; simp only [neg_mul, neg_neg, mul_assoc]
  rw [Subalgebra.mem_center_iff]
  rintro ⟨y, hy⟩
  rw [Subtype.ext_iff, MulMemClass.coe_mul, MulMemClass.coe_mul]
  rw [← Subalgebra.mem_toSubmodule, even_toSubmodule] at hy
  exact hcomm y hy

end CommRing

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V] {Q : QuadraticForm K V}

/-- **The volume element of even positive length is not a scalar.** The ordered product `ω` of a
nonempty pairwise orthogonal anisotropic list of even length anticommutes with each member `v` of
the list, while a scalar commutes with `ι Q v ≠ 0`; away from characteristic two this forces the
scalar to vanish, but `ω` is a unit. -/
theorem prod_map_ι_ne_algebraMap_of_even_length [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ []) (hQl : ∀ v ∈ l, Q v ≠ 0)
    (c : K) : (l.map (ι Q)).prod ≠ algebraMap K (CliffordAlgebra Q) c := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  obtain ⟨v, hv⟩ := List.exists_mem_of_ne_nil l hne
  intro hω
  have hanti := prod_map_ι_mul_ι_of_even_length hl hlen (m := v)
    (Submodule.subset_span (by exact hv))
  rw [hω, ← Algebra.commutes, ← Algebra.smul_def] at hanti
  have h2 : (2 * c) • ι Q v = 0 := by
    rw [mul_smul, two_smul]
    exact add_eq_zero_iff_eq_neg.mpr hanti
  have hιv : ι Q v ≠ 0 := by
    intro h0
    apply hQl v hv
    apply algebraMap_injective Q
    rw [← ι_sq_scalar, h0, mul_zero, map_zero]
  have hc : c = 0 := by
    simpa [NeZero.ne (2 : K), hιv] using h2
  have hunit : IsUnit (l.map (ι Q)).prod :=
    isUnit_prod_map_ι (List.prod_ne_zero (by simpa using fun v hv h => hQl v hv h)).isUnit
  rw [hω, hc, map_zero] at hunit
  exact not_isUnit_zero hunit

/-- The scalar and volume coordinates `a + b • ω` are unique for the volume element `ω` of a
nonempty pairwise orthogonal anisotropic list of even length: the even-length companion of
`CliffordAlgebra.add_smul_volume_injective`. Here both summands are even, so the grading does not
separate them; instead `ω` is not a scalar
(`CliffordAlgebra.prod_map_ι_ne_algebraMap_of_even_length`). -/
theorem add_smul_volume_injective_of_even_length [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ []) (hQl : ∀ v ∈ l, Q v ≠ 0) :
    Function.Injective fun p : K × K ↦
      algebraMap K (CliffordAlgebra Q) p.1 + p.2 • (l.map (ι Q)).prod := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  rintro ⟨a, b⟩ ⟨a', b'⟩ h
  simp only at h
  have hb : b = b' := by
    by_contra hbb
    have h' : (b - b') • (l.map (ι Q)).prod = (a' - a) • 1 := by
      simp only [Algebra.algebraMap_eq_smul_one] at h
      linear_combination (norm := module) h
    apply prod_map_ι_ne_algebraMap_of_even_length hl hlen hne hQl ((b - b')⁻¹ * (a' - a))
    rw [Algebra.algebraMap_eq_smul_one, mul_smul, ← h', inv_smul_smul₀ (sub_ne_zero.mpr hbb)]
  subst hb
  rw [add_left_inj] at h
  rw [algebraMap_injective Q h]

/-- **The centre of the even Clifford algebra in even dimension is `K ⊕ Kω`.** Let `l` be a
nonempty anisotropic orthogonal spanning list of even length and let `ω` be the ordered product of
its Clifford generators. An element of the even Clifford algebra is central in it exactly when it
is a scalar plus a scalar multiple of `ω`.

Such a list is a basis, so the form is nondegenerate and the dimension even and positive.
Conversely, every nondegenerate form on a space of even positive finite dimension (over a field of
characteristic different from two) has such a list:
`QuadraticMap.Nondegenerate.exists_list_pairwise_isOrtho` gives an anisotropic orthogonal spanning
list whose length is the dimension. -/
theorem mem_center_even_iff_exists_eq_add_smul_volume [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ [])
    (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) (hQl : ∀ v ∈ l, Q v ≠ 0) {x : even Q} :
    x ∈ Subalgebra.center K (even Q) ↔
      ∃ a b : K, (x : CliffordAlgebra Q) =
        algebraMap K (CliffordAlgebra Q) a + b • (l.map (ι Q)).prod := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  let ωE : even Q := ⟨(l.map (ι Q)).prod, prod_map_ι_mem_even_of_even_length hlen⟩
  have hωE : ωE ∈ Subalgebra.center K (even Q) :=
    prod_map_ι_mem_center_even_of_even_length hl hlen hspan
  constructor
  · intro hx
    obtain ⟨hQ, hlenV⟩ :=
      QuadraticMap.nondegenerate_and_length_eq_finrank_of_pairwise_isOrtho hl hspan hQl
    have hpos : 0 < l.length := List.length_pos_iff.mpr hne
    have _ : FiniteDimensional K V := .of_finrank_pos (hlenV ▸ hpos)
    -- Transport to the full Clifford algebra of a regular form `P` in odd dimension `n`.
    obtain ⟨n, P, hP, hn, ⟨e⟩⟩ :=
      TauCeti.CliffordAlgebra.exists_nonempty_algEquiv_even_of_finrank_pos hQ (hlenV ▸ hpos)
    obtain ⟨l', hl', hlen', hspan', hQl'⟩ := hP.exists_list_pairwise_isOrtho
    have hodd : Odd l'.length := by
      rw [hlen', Module.finrank_fin_fun, ← Nat.not_even_iff_odd, ← Nat.even_add_one, hn,
        ← hlenV]
      exact hlen
    have hcenter (y : even Q) (hy : y ∈ Subalgebra.center K (even Q)) :
        ∃ a b : K, e y = algebraMap K (CliffordAlgebra P) a + b • (l'.map (ι P)).prod :=
      (mem_center_iff_exists_eq_add_smul_volume hl' hodd hspan' hQl').mp
        ((MulEquivClass.apply_mem_center_iff e).mpr hy)
    obtain ⟨a₁, b₁, hx₁⟩ := hcenter x hx
    obtain ⟨a₀, b₀, hω₀⟩ := hcenter ωE hωE
    -- The image of `ω` is not a scalar, so it determines the volume element of `P`.
    have hb₀ : b₀ ≠ 0 := by
      rintro rfl
      rw [zero_smul, add_zero, ← AlgEquiv.commutes e a₀] at hω₀
      exact prod_map_ι_ne_algebraMap_of_even_length hl hlen hne hQl a₀
        (by simpa [ωE] using congrArg Subtype.val (e.injective hω₀))
    refine ⟨a₁ - b₁ * b₀⁻¹ * a₀, b₁ * b₀⁻¹, ?_⟩
    have hx' : x = algebraMap K (even Q) (a₁ - b₁ * b₀⁻¹ * a₀) + (b₁ * b₀⁻¹) • ωE := by
      apply e.injective
      rw [map_add, map_smul, AlgEquiv.commutes, hx₁, hω₀]
      simp only [Algebra.algebraMap_eq_smul_one]
      match_scalars
      · field_simp
        ring
      · field_simp
    rw [hx', Subalgebra.coe_add, Subalgebra.coe_algebraMap, Subalgebra.coe_smul]
  · rintro ⟨a, b, hx⟩
    have hx' : x = algebraMap K (even Q) a + b • ωE := Subtype.ext hx
    rw [hx']
    exact Subalgebra.add_mem _ (Subalgebra.algebraMap_mem _ a) (Subalgebra.smul_mem _ hωE b)

/-- **The centre of the even Clifford algebra in even dimension is generated by a volume
element.** For a nonempty anisotropic orthogonal spanning list `l` of even length, its ordered
Clifford product `ω`, an element of the even Clifford algebra, generates the centre of that algebra
as a `K`-subalgebra. Equivalently, the centre is the two-dimensional space `K ⊕ Kω` described by
`CliffordAlgebra.mem_center_even_iff_exists_eq_add_smul_volume`. -/
theorem center_even_eq_adjoin_volume [NeZero (2 : K)] {l : List V} (hl : l.Pairwise Q.IsOrtho)
    (hlen : Even l.length) (hne : l ≠ []) (hspan : Submodule.span K {x : V | x ∈ l} = ⊤)
    (hQl : ∀ v ∈ l, Q v ≠ 0) :
    Subalgebra.center K (even Q) =
      Algebra.adjoin K {⟨(l.map (ι Q)).prod, prod_map_ι_mem_even_of_even_length hlen⟩} := by
  apply le_antisymm
  · intro x hx
    obtain ⟨a, b, hab⟩ :=
      (mem_center_even_iff_exists_eq_add_smul_volume hl hlen hne hspan hQl).mp hx
    have hx' : x = algebraMap K (even Q) a +
        b • ⟨(l.map (ι Q)).prod, prod_map_ι_mem_even_of_even_length hlen⟩ := Subtype.ext hab
    rw [hx']
    exact Subalgebra.add_mem _ (Subalgebra.algebraMap_mem _ a)
      (Subalgebra.smul_mem _ (Algebra.subset_adjoin (Set.mem_singleton _)) b)
  · apply Algebra.adjoin_le
    rintro _ rfl
    exact prod_map_ι_mem_center_even_of_even_length hl hlen hspan

/-- The volume element of a pairwise orthogonal spanning list of even length, as an element of the
centre of the even Clifford algebra, is a root of `X² - d` for
`d = (-1) ^ (n.choose 2) * Q v₁ ⋯ Q vₙ`. -/
private theorem eval₂_volume_eq_zero {l : List V} (hl : l.Pairwise Q.IsOrtho)
    (hlen : Even l.length) (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) :
    (X ^ 2 - C ((-1 : K) ^ l.length.choose 2 * (l.map Q).prod)).eval₂
      (Algebra.ofId K (Subalgebra.center K (even Q)) : K →+* Subalgebra.center K (even Q))
      ⟨⟨(l.map (ι Q)).prod, prod_map_ι_mem_even_of_even_length hlen⟩,
        prod_map_ι_mem_center_even_of_even_length hl hlen hspan⟩ = 0 := by
  rw [eval₂_sub, eval₂_X_pow, eval₂_C, sub_eq_zero, AlgHom.coe_toRingHom, Algebra.ofId_apply]
  apply Subtype.ext
  apply Subtype.ext
  simpa [sq] using prod_map_ι_sq_scalar hl

/-- The algebra map `K[X] ⧸ (X² - d) → center C₀` sending the root to the volume element is
bijective: injective because `1` and the volume element are linearly independent, and surjective
by `CliffordAlgebra.mem_center_even_iff_exists_eq_add_smul_volume`. -/
private theorem liftAlgHom_volume_bijective [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ [])
    (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) (hQl : ∀ v ∈ l, Q v ≠ 0) :
    Function.Bijective (AdjoinRoot.liftAlgHom
      (X ^ 2 - C ((-1 : K) ^ l.length.choose 2 * (l.map Q).prod))
      (Algebra.ofId K (Subalgebra.center K (even Q)))
      ⟨⟨(l.map (ι Q)).prod, prod_map_ι_mem_even_of_even_length hlen⟩,
        prod_map_ι_mem_center_even_of_even_length hl hlen hspan⟩
      (eval₂_volume_eq_zero hl hlen hspan)) := by
  constructor
  · rw [injective_iff_map_eq_zero]
    intro z hz
    induction z using AdjoinRoot.induction_on with
    | ih p =>
    rw [AdjoinRoot.liftAlgHom_mk] at hz
    rw [AdjoinRoot.mk_eq_zero]
    set g := X ^ 2 - C ((-1 : K) ^ l.length.choose 2 * (l.map Q).prod)
    have hg : g.Monic := monic_X_pow_sub_C _ two_ne_zero
    -- The remainder of `p` modulo `g` also vanishes at the volume element, and has degree at
    -- most one, so its two coefficients vanish.
    have hmod := modByMonic_eq_sub_mul_div p g
    rw [← modByMonic_eq_zero_iff_dvd hg]
    have hr : p %ₘ g = C ((p %ₘ g).coeff 1) * X + C ((p %ₘ g).coeff 0) := by
      apply eq_X_add_C_of_degree_le_one
      have := degree_modByMonic_lt p hg
      rw [degree_X_pow_sub_C two_pos] at this
      exact Order.le_of_lt_succ this
    have hz' := congrArg (eval₂ (Algebra.ofId K (Subalgebra.center K (even Q)) :
      K →+* Subalgebra.center K (even Q)) ⟨⟨(l.map (ι Q)).prod,
        prod_map_ι_mem_even_of_even_length hlen⟩,
          prod_map_ι_mem_center_even_of_even_length hl hlen hspan⟩) hmod
    rw [eval₂_sub, eval₂_mul, eval₂_volume_eq_zero hl hlen hspan, hz, zero_mul, sub_zero,
      hr] at hz'
    have hz'' := congrArg (fun y : Subalgebra.center K (even Q) =>
      ((y : even Q) : CliffordAlgebra Q)) hz'
    simp only [eval₂_add, eval₂_mul, eval₂_C, eval₂_X, AlgHom.coe_toRingHom,
      Algebra.ofId_apply] at hz''
    have hcoeff : ((p %ₘ g).coeff 0, (p %ₘ g).coeff 1) = (0, 0) := by
      apply add_smul_volume_injective_of_even_length hl hlen hne hQl
      simpa [Algebra.smul_def, add_comm] using hz''
    simp only [Prod.mk.injEq] at hcoeff
    rw [hr, hcoeff.1, hcoeff.2, map_zero, zero_mul, add_zero]
  · rintro ⟨y, hy⟩
    obtain ⟨a, b, hab⟩ :=
      (mem_center_even_iff_exists_eq_add_smul_volume hl hlen hne hspan hQl).mp hy
    refine ⟨AdjoinRoot.of _ a + AdjoinRoot.of _ b * AdjoinRoot.root _, ?_⟩
    apply Subtype.ext
    apply Subtype.ext
    simp [hab, Algebra.smul_def]

/-- **The centre of the even Clifford algebra in even dimension is the quadratic algebra
`K[X] ⧸ (X² - d)`.** For a nonempty anisotropic orthogonal spanning list `v₁, …, vₙ` of even
length, with `d = (-1) ^ (n.choose 2) * Q v₁ ⋯ Q vₙ` (the signed discriminant of `Q`, up to
squares), the root of `X² - d` goes to the volume element `ω = v₁ ⋯ vₙ`
(`CliffordAlgebra.coe_adjoinRootEquivCenterEven_root`). -/
noncomputable def adjoinRootEquivCenterEven [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ [])
    (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) (hQl : ∀ v ∈ l, Q v ≠ 0) :
    AdjoinRoot (X ^ 2 - C ((-1 : K) ^ l.length.choose 2 * (l.map Q).prod)) ≃ₐ[K]
      Subalgebra.center K (even Q) :=
  AlgEquiv.ofBijective _ (liftAlgHom_volume_bijective hl hlen hne hspan hQl)

/-- `CliffordAlgebra.adjoinRootEquivCenterEven` sends the root of `X² - d` to the volume element. -/
@[simp]
theorem coe_adjoinRootEquivCenterEven_root [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ [])
    (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) (hQl : ∀ v ∈ l, Q v ≠ 0) :
    ((adjoinRootEquivCenterEven hl hlen hne hspan hQl (AdjoinRoot.root _) : even Q) :
      CliffordAlgebra Q) = (l.map (ι Q)).prod := by
  simp [adjoinRootEquivCenterEven]

/-- The centre of an even Clifford algebra is a field exactly when the signed discriminant of an
anisotropic orthogonal spanning list is not a square. -/
theorem isField_center_even_iff_not_isSquare_discriminant [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ [])
    (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) (hQl : ∀ v ∈ l, Q v ≠ 0) :
    IsField (Subalgebra.center K (even Q)) ↔
      ¬ IsSquare ((-1 : K) ^ l.length.choose 2 * (l.map Q).prod) := by
  let e := adjoinRootEquivCenterEven hl hlen hne hspan hQl
  rw [← e.toMulEquiv.isField_congr, AdjoinRoot.isField_iff_irreducible,
    X_pow_sub_C_irreducible_iff_of_prime Nat.prime_two, isSquare_iff_exists_sq]
  simp only [not_exists]
  exact forall_congr' fun _ ↦ not_congr eq_comm

/-- The centre of an even Clifford algebra is a split quadratic algebra exactly when the signed
discriminant of an anisotropic orthogonal spanning list is a square. -/
theorem nonempty_center_even_algEquiv_prod_iff_isSquare_discriminant [NeZero (2 : K)]
    {l : List V} (hl : l.Pairwise Q.IsOrtho) (hlen : Even l.length) (hne : l ≠ [])
    (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) (hQl : ∀ v ∈ l, Q v ≠ 0) :
    Nonempty (Subalgebra.center K (even Q) ≃ₐ[K] K × K) ↔
      IsSquare ((-1 : K) ^ l.length.choose 2 * (l.map Q).prod) := by
  let d : K := (-1 : K) ^ l.length.choose 2 * (l.map Q).prod
  let e := adjoinRootEquivCenterEven hl hlen hne hspan hQl
  constructor
  · rintro ⟨g⟩
    let h := e.trans g
    refine (isSquare_iff_exists_sq d).mpr ⟨(h (AdjoinRoot.root _)).1, ?_⟩
    have hsquare := congrArg h (root_X_pow_sub_C_pow 2 d)
    have hsquare' := congrArg Prod.fst hsquare
    have hscalar : h (AdjoinRoot.of _ d) = (d, d) := h.commutes d
    rw [hscalar] at hsquare'
    simpa [h, d] using hsquare'.symm
  · intro hd
    obtain ⟨t, ht⟩ := (isSquare_iff_exists_sq d).mp hd
    have hd0 : d ≠ 0 := by
      dsimp [d]
      apply mul_ne_zero (pow_ne_zero _ (neg_ne_zero.mpr one_ne_zero))
      apply List.prod_ne_zero
      intro hzero
      obtain ⟨v, hv, hQv⟩ := List.mem_map.mp hzero
      exact hQl v hv hQv
    have ht0 : t ≠ 0 := by
      intro ht0
      apply hd0
      rw [ht, ht0, zero_pow two_ne_zero]
    let I : Ideal K[X] := Ideal.span {X - C t}
    let J : Ideal K[X] := Ideal.span {X - C (-t)}
    have hcoprime : IsCoprime I J := by
      dsimp only [I, J]
      rw [Ideal.isCoprime_span_singleton_iff]
      apply isCoprime_X_sub_C_of_isUnit_sub
      simpa [sub_neg_eq_add, two_mul] using (mul_ne_zero two_ne_zero ht0).isUnit
    have hfactor : X ^ 2 - C d = (X - C t) * (X - C (-t)) := by
      rw [ht]
      simp only [map_neg, map_pow]
      ring
    have hideal : Ideal.span ({X ^ 2 - C d} : Set K[X]) = I * J := by
      dsimp only [I, J]
      rw [Ideal.span_singleton_mul_span_singleton, hfactor]
    let crtRing := Ideal.quotientMulEquivQuotientProd I J hcoprime
    let crtAlg : (K[X] ⧸ I * J) ≃ₐ[K] (K[X] ⧸ I) × (K[X] ⧸ J) :=
      AlgEquiv.ofRingEquiv (f := crtRing) (by intro k; rfl)
    exact ⟨e.symm.trans <| (Ideal.quotientEquivAlgOfEq K hideal).trans <|
      crtAlg.trans <| AlgEquiv.prodCongr
        (Polynomial.quotientSpanXSubCAlgEquiv t)
        (Polynomial.quotientSpanXSubCAlgEquiv (-t))⟩

section FiniteDimensional

variable [FiniteDimensional K V] [NeZero (2 : K)]

/-- The even Clifford algebra of a finite-dimensional quadratic space is module-finite over its
center. -/
theorem finite_even_over_center (Q : QuadraticForm K V) :
    Module.Finite (Subalgebra.center K (even Q)) (even Q) := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  exact Subalgebra.finite_centerAlgebra_of_finite

/-- The centre of the even Clifford algebra of a regular, positive even-dimensional quadratic
space has dimension two over the base field. -/
theorem finrank_center_even (Q : QuadraticForm K V) (hQ : Q.Nondegenerate)
    (heven : Even (finrank K V)) (hpos : 0 < finrank K V) :
    finrank K (Subalgebra.center K (even Q)) = 2 := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  obtain ⟨l, hl, hlen, hspan, hQl⟩ := hQ.exists_list_pairwise_isOrtho
  have hlen' : Even l.length := by rwa [hlen]
  have hne : l ≠ [] := List.length_pos_iff.mp (hlen ▸ hpos)
  let p : K[X] := X ^ 2 - C ((-1 : K) ^ l.length.choose 2 * (l.map Q).prod)
  let e := adjoinRootEquivCenterEven hl hlen' hne hspan hQl
  calc
    finrank K (Subalgebra.center K (even Q)) = finrank K (AdjoinRoot p) :=
      e.toLinearEquiv.finrank_eq.symm
    _ = p.natDegree := (AdjoinRoot.powerBasis (X_pow_sub_C_ne_zero two_pos _)).finrank
    _ = 2 := natDegree_X_pow_sub_C

/-- If the centre of a regular, positive even-dimensional even Clifford algebra is a field, then
the algebra has dimension `2 ^ (finrank K V - 2)` over its centre. -/
theorem finrank_even_over_center (Q : QuadraticForm K V) (hQ : Q.Nondegenerate)
    (heven : Even (finrank K V)) (hpos : 0 < finrank K V)
    (hfield : IsField (Subalgebra.center K (even Q))) :
    finrank (Subalgebra.center K (even Q)) (even Q) = 2 ^ (finrank K V - 2) := by
  let _ := hfield.toField
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  let _ : Nontrivial V := Module.nontrivial_of_finrank_pos hpos
  let _ : IsScalarTower K (Subalgebra.center K (even Q)) (even Q) :=
    Subalgebra.isScalarTower_centerAlgebra
  let _ : Module.Finite (Subalgebra.center K (even Q)) (even Q) :=
    finite_even_over_center Q
  have hcenter := finrank_center_even Q hQ heven hpos
  have htower := Module.finrank_mul_finrank K (Subalgebra.center K (even Q)) (even Q)
  rw [hcenter, finrank_even Q] at htower
  obtain ⟨m, hm⟩ := heven
  have hpow : 2 * 2 ^ (finrank K V - 2) = 2 ^ (finrank K V - 1) := by
    rw [← pow_succ']
    congr
    omega
  omega

/-- If the discriminant centre of a regular four-dimensional even Clifford algebra is a field,
then the even Clifford algebra has dimension four over that centre. -/
theorem finrank_even_over_center_of_finrank_eq_four (Q : QuadraticForm K V)
    (hQ : Q.Nondegenerate) (hV : finrank K V = 4)
    (hfield : IsField (Subalgebra.center K (even Q))) :
    finrank (Subalgebra.center K (even Q)) (even Q) = 4 := by
  rw [finrank_even_over_center Q hQ (by rw [hV]; exact ⟨2, by norm_num⟩)
    (by simp [hV]) hfield, hV]
  norm_num

end FiniteDimensional

end CliffordAlgebra

namespace TauCeti.CliffordAlgebra

open _root_.CliffordAlgebra Module

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V] [FiniteDimensional K V]
  [NeZero (2 : K)] {Q : QuadraticForm K V}

/-- The centre of the even Clifford algebra of a regular quadratic space of even positive
dimension contains a non-scalar element. -/
theorem exists_mem_center_even_forall_ne_algebraMap (hQ : Q.Nondegenerate)
    (heven : Even (finrank K V)) (hpos : 0 < finrank K V) :
    ∃ x ∈ Subalgebra.center K (even Q), ∀ a : K, x ≠ algebraMap K (even Q) a := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  obtain ⟨l, hl, hlen, hspan, hQl⟩ := hQ.exists_list_pairwise_isOrtho
  have hle : Even l.length := hlen ▸ heven
  have hne : l ≠ [] := List.length_pos_iff.mp (hlen ▸ hpos)
  refine ⟨⟨(l.map (ι Q)).prod, prod_map_ι_mem_even_of_even_length hle⟩,
    prod_map_ι_mem_center_even_of_even_length hl hle hspan, ?_⟩
  intro a ha
  exact prod_map_ι_ne_algebraMap_of_even_length hl hle hne hQl a
    (by simpa only [Subalgebra.coe_algebraMap] using congrArg Subtype.val ha)

end TauCeti.CliffordAlgebra
