/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Homology.Curved.Frobenius
public import TauCeti.CategoryTheory.Exact.Stable.Shift

/-!
# The shift on the homotopy category of curved duplexes

The parity shift, which swaps the two components of a curved duplex and negates both
differentials, is a self-equivalence of the homotopy category `CurvedDuplex.HomotopyCategory C w`.
This file equips the homotopy category with the shift by `ℤ` that it generates, so that the shift
by `1` is the parity shift.

This is the shift of Happel's triangulation. The componentwise split exact structure on curved
duplexes is Frobenius, and every curved duplex `X` has the relative injective presentation

`X ⟶ diskSum X ⟶ X[1]`

whose middle term is the contractible disk sum on the components of `X` and whose cokernel term
is the parity shift `X[1]`. Since stable suspension may be computed from any relative injective
presentation, stable suspension is the parity shift in the stable category. Consequently the
equivalence `ExactStructure.curvedDuplexSplitStableToHomotopy` between the stable category and the
homotopy category commutes coherently with the shifts by `ℤ`: the one generated by stable
suspension and the one generated by the parity shift. This is the compatibility needed to
transport Happel's triangulated structure from the stable category to the homotopy category.

## Main definitions

* `TauCeti.CurvedDuplex.HomotopyCategory.instHasShift`: the shift by `ℤ` on the homotopy category
  of curved duplexes generated by the parity shift.
* `TauCeti.CurvedDuplex.HomotopyCategory.parityShiftCompQuotientFunctorIso`: the image of the
  parity shift of a curved duplex is the shift by `1` of its image.
* `TauCeti.ExactStructure.curvedDuplexSplitSuspensionPresentation`: the componentwise split
  injective presentation `X ⟶ diskSum X ⟶ X[1]`.
* `TauCeti.ExactStructure.curvedDuplexSplitStableSuspensionIsoParityShift`: stable suspension of
  curved duplexes is the parity shift.
* `TauCeti.ExactStructure.stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso`: the
  stable-to-homotopy comparison intertwines stable suspension with the parity shift.
* `TauCeti.ExactStructure.curvedDuplexSplitStableToHomotopyCommShift`: the stable-to-homotopy
  comparison commutes with the shifts by `ℤ`.

## References

* Dieter Happel, *Triangulated Categories in the Representation Theory of Finite Dimensional
  Algebras*, Chapter I, Section 2: suspension in the stable category of a Frobenius category.
* Bernhard Keller, *Chain complexes and stable categories*, Manuscripta Mathematica **67**
  (1990), 379–417, Section 1, for complexes with the componentwise split exact structure, whose
  stable category is their homotopy category.
* I. Frenkel, M. Khovanov, O. Schiffmann, *Homological realization of Nakajima varieties and Weyl
  group actions*, Compos. Math. **141** (2005), 1479–1503, Sections 2–3, for curved duplexes,
  their parity shift and their homotopy category.
-/

public section

namespace TauCeti

open CategoryTheory CategoryTheory.Limits CurvedDuplex

universe w' v u

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasBinaryBiproducts C]
  {R : Type w'} [Semiring R] [Linear R C] {w : R}

namespace CurvedDuplex.HomotopyCategory

variable (C w)

/-- The shift by `ℤ` on the homotopy category of curved duplexes generated by the parity shift. -/
noncomputable instance instHasShift : HasShift (HomotopyCategory C w) ℤ :=
  (parityShiftEquivalence C w).hasShift

/-- The shift by `1` on the homotopy category of curved duplexes is the parity shift. -/
noncomputable def shiftFunctorOneIso :
    shiftFunctor (HomotopyCategory C w) (1 : ℤ) ≅ (parityShiftEquivalence C w).functor :=
  (parityShiftEquivalence C w).shiftFunctorOneIso

omit [HasBinaryBiproducts C] in
/-- The identification of the shift by `1` with the parity shift is the one carried by the shift
generated by the parity-shift autoequivalence. -/
theorem shiftFunctorOneIso_def :
    shiftFunctorOneIso C w = (parityShiftEquivalence C w).shiftFunctorOneIso :=
  (rfl)

/-- Every shift functor of the homotopy category of curved duplexes is additive. -/
instance (n : ℤ) : (shiftFunctor (HomotopyCategory C w) n).Additive :=
  (parityShiftEquivalence C w).shiftFunctor_additive n

/-- The image in the homotopy category of the parity shift of a curved duplex is the shift by `1`
of its image, naturally. -/
noncomputable def parityShiftCompQuotientFunctorIso :
    parityShift C w ⋙ (nullHomotopic C w).quotientFunctor ≅
      (nullHomotopic C w).quotientFunctor ⋙ shiftFunctor (HomotopyCategory C w) (1 : ℤ) :=
  eqToIso quotientFunctor_comp_parityShiftEquivalence_functor.symm ≪≫
    Functor.isoWhiskerLeft _ (shiftFunctorOneIso C w).symm

omit [HasBinaryBiproducts C] in
/-- The component of `parityShiftCompQuotientFunctorIso` at `X` identifies the image of the
parity shift of `X` with the parity shift of its image, followed by `shiftFunctorOneIso`. -/
@[simp]
theorem parityShiftCompQuotientFunctorIso_hom_app (X : CurvedDuplex C w) :
    (parityShiftCompQuotientFunctorIso C w).hom.app X =
      eqToHom (parityShiftEquivalence_functor_obj_quotientFunctor_obj X).symm ≫
        (shiftFunctorOneIso C w).inv.app ((nullHomotopic C w).quotientFunctor.obj X) := by
  simp [parityShiftCompQuotientFunctorIso, eqToHom_app]

end CurvedDuplex.HomotopyCategory

namespace ExactStructure

variable [HasZeroObject C]

/-- The componentwise split injective presentation `X ⟶ diskSum X ⟶ X[1]` of a curved duplex:
its middle term is the contractible disk sum on the components of `X`, and its cokernel term is
the parity shift of `X`. -/
-- Exposed so that its middle and cokernel terms are definitionally the disk sum and the parity
-- shift, which the typing of the maps between these presentations requires.
@[expose] noncomputable def curvedDuplexSplitSuspensionPresentation (X : CurvedDuplex C w) :
    ((split C).curvedDuplex w).InjectivePresentation X where
  I := diskSum X
  K := (parityShift C w).obj X
  i := toDiskSum X
  p := diskSumToParityShift X
  zero := toDiskSum_comp_diskSumToParityShift X
  conflation := by
    rw [curvedDuplex_conflation_iff]
    refine ⟨(ExactStructure.split C).conflation_of_iso ?_
        (split_conflation_biprod_lift_id_right X.d₀),
      (ExactStructure.split C).conflation_of_iso ?_
        (split_conflation_biprod_lift_id_left (-X.d₁))⟩
    -- The components of the curved short complex live over `eval₀` and `eval₁`; compare them with
    -- the biproduct short complexes by identities.
    all_goals refine ShortComplex.isoMk (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ ?_
    all_goals
      simp only [Iso.refl_hom, ShortComplex.map_f, ShortComplex.map_g, eval₀_map, eval₁_map,
        toDiskSum_f₀, toDiskSum_f₁, diskSumToParityShift_f₀, diskSumToParityShift_f₁]
      exact (Category.id_comp _).trans (Category.comp_id _).symm
  isInjective :=
    curvedDuplex_split_isInjective_of_mem_nullHomotopic (id_diskSum_mem_nullHomotopic X)

@[simp]
theorem curvedDuplexSplitSuspensionPresentation_I (X : CurvedDuplex C w) :
    (curvedDuplexSplitSuspensionPresentation X).I = diskSum X := (rfl)

@[simp]
theorem curvedDuplexSplitSuspensionPresentation_K (X : CurvedDuplex C w) :
    (curvedDuplexSplitSuspensionPresentation X).K = (parityShift C w).obj X := (rfl)

@[simp]
theorem curvedDuplexSplitSuspensionPresentation_i (X : CurvedDuplex C w) :
    (curvedDuplexSplitSuspensionPresentation X).i = toDiskSum X := (rfl)

@[simp]
theorem curvedDuplexSplitSuspensionPresentation_p (X : CurvedDuplex C w) :
    (curvedDuplexSplitSuspensionPresentation X).p = diskSumToParityShift X := (rfl)

/-- In the stable category, the morphism induced by `f` on the cokernel terms of the disk-sum
presentations is the parity shift of `f`. -/
theorem projectiveStableFunctor_map_curvedDuplexSplitSuspensionPresentation_cokernelMap
    {X Y : CurvedDuplex C w} (f : X ⟶ Y) :
    ((split C).curvedDuplex w).projectiveStableFunctor.map
        ((curvedDuplexSplitSuspensionPresentation X).cokernelMap
          (curvedDuplexSplitSuspensionPresentation Y) f) =
      ((split C).curvedDuplex w).projectiveStableFunctor.map ((parityShift C w).map f) :=
  projectiveStableFunctor_map_cokernelMap_eq (curvedDuplexSplitSuspensionPresentation X)
    (curvedDuplexSplitSuspensionPresentation Y)
    (curvedDuplex_split_isProjective_of_mem_nullHomotopic (id_diskSum_mem_nullHomotopic Y)) f
    (diskSumMap f) ((parityShift C w).map f) (toDiskSum_comp_diskSumMap f)
    (diskSumToParityShift_comp_parityShift_map f)

variable (C w)

/-- **Stable suspension of curved duplexes is the parity shift.** For the componentwise split
exact structure, the stable suspension of (the image of) a curved duplex is (the image of) its
parity shift, naturally. -/
noncomputable def curvedDuplexSplitStableSuspensionIsoParityShift :
    ((split C).curvedDuplex w).projectiveStableFunctor ⋙
        (curvedDuplex_split_isFrobenius C w).stableSuspension ≅
      parityShift C w ⋙ ((split C).curvedDuplex w).projectiveStableFunctor :=
  -- The implicit endpoints are given so that they are syntactically those of the two functors.
  (NatIso.ofComponents (fun X ↦ Iso.trans
    (X := (parityShift C w ⋙ ((split C).curvedDuplex w).projectiveStableFunctor).obj X)
    (Z := (((split C).curvedDuplex w).projectiveStableFunctor ⋙
      (curvedDuplex_split_isFrobenius C w).stableSuspension).obj X)
    ((curvedDuplex_split_isFrobenius C w).projectiveStableIsoSuspensionObj
        (curvedDuplexSplitSuspensionPresentation X))
    (eqToIso ((curvedDuplex_split_isFrobenius C w).stableSuspension_obj_projectiveStableFunctor_obj
        X).symm)) (fun {X Y} f ↦ by
    have h := (curvedDuplex_split_isFrobenius C w).projectiveStableIsoSuspensionObj_hom_naturality
      (curvedDuplexSplitSuspensionPresentation X) (curvedDuplexSplitSuspensionPresentation Y) f
    rw [projectiveStableFunctor_map_curvedDuplexSplitSuspensionPresentation_cokernelMap] at h
    rw [Functor.comp_map, Functor.comp_map,
      IsFrobenius.stableSuspension_map_projectiveStableFunctor_map]
    -- The endpoints of `Iso.trans` are the functor composites, which are only definitionally
    -- equal to the endpoints of the presentation comparison; `rw` cannot see through them.
    erw [Iso.trans_hom, Iso.trans_hom]
    rw [eqToIso.hom, eqToIso.hom]
    simp only [Category.assoc, eqToHom_trans_assoc, eqToHom_refl, Category.id_comp]
    exact (Category.assoc _ _ _).symm.trans ((reassoc_of% h) _))).symm

/-- The component of `curvedDuplexSplitStableSuspensionIsoParityShift` at `X` is induced by the
identity of `X`, from the chosen suspension presentation to the disk-sum presentation. -/
@[simp]
theorem curvedDuplexSplitStableSuspensionIsoParityShift_hom_app (X : CurvedDuplex C w) :
    (curvedDuplexSplitStableSuspensionIsoParityShift C w).hom.app X =
      eqToHom ((curvedDuplex_split_isFrobenius C w).stableSuspension_obj_projectiveStableFunctor_obj
        X) ≫ ((split C).curvedDuplex w).projectiveStableFunctor.map
          (((curvedDuplex_split_isFrobenius C w).suspensionPresentation X).cokernelMap
            (curvedDuplexSplitSuspensionPresentation X) (𝟙 X)) := by
  simp only [curvedDuplexSplitStableSuspensionIsoParityShift, Iso.symm_hom,
    NatIso.ofComponents_inv_app]
  -- As in the definition, the endpoints agree with those of the composite only definitionally.
  erw [Iso.trans_inv]
  rw [eqToIso.inv, IsFrobenius.projectiveStableIsoSuspensionObj_inv]
  rfl

/-- The inverse component of `curvedDuplexSplitStableSuspensionIsoParityShift` at `X` is induced
by the identity of `X`, from the disk-sum presentation to the chosen suspension presentation. -/
@[simp]
theorem curvedDuplexSplitStableSuspensionIsoParityShift_inv_app (X : CurvedDuplex C w) :
    (curvedDuplexSplitStableSuspensionIsoParityShift C w).inv.app X =
      ((split C).curvedDuplex w).projectiveStableFunctor.map
          ((curvedDuplexSplitSuspensionPresentation X).cokernelMap
            ((curvedDuplex_split_isFrobenius C w).suspensionPresentation X) (𝟙 X)) ≫
        eqToHom
          ((curvedDuplex_split_isFrobenius C w).stableSuspension_obj_projectiveStableFunctor_obj
            X).symm := by
  simp only [curvedDuplexSplitStableSuspensionIsoParityShift, Iso.symm_inv,
    NatIso.ofComponents_hom_app]
  -- As in the definition, the endpoints agree with those of the composite only definitionally.
  erw [Iso.trans_hom]
  rw [eqToIso.hom, IsFrobenius.projectiveStableIsoSuspensionObj_hom]
  rfl

/-- The comparison from the componentwise split stable category to the homotopy category of
curved duplexes intertwines stable suspension with the parity shift. -/
noncomputable def stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso :
    (curvedDuplex_split_isFrobenius C w).stableSuspension ⋙
        curvedDuplexSplitStableToHomotopy C w ≅
      curvedDuplexSplitStableToHomotopy C w ⋙
        (HomotopyCategory.parityShiftEquivalence C w).functor :=
  Quotient.natIsoLift _ <|
    (Functor.associator _ _ _).symm ≪≫
      Functor.isoWhiskerRight (curvedDuplexSplitStableSuspensionIsoParityShift C w) _ ≪≫
      Functor.associator _ _ _ ≪≫
      Functor.isoWhiskerLeft _
        (eqToIso (projectiveStableFunctor_comp_curvedDuplexSplitStableToHomotopy C w)) ≪≫
      eqToIso HomotopyCategory.quotientFunctor_comp_parityShiftEquivalence_functor.symm ≪≫
      Functor.isoWhiskerRight
        (eqToIso (projectiveStableFunctor_comp_curvedDuplexSplitStableToHomotopy C w).symm) _ ≪≫
      Functor.associator _ _ _

/-- On the stable image of a curved duplex `X`, the intertwining isomorphism is the homotopy
class of the map induced by the identity of `X` from the chosen suspension presentation to the
disk-sum presentation. -/
theorem stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso_hom_app (X : CurvedDuplex C w) :
    (stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso C w).hom.app
        (((split C).curvedDuplex w).projectiveStableFunctor.obj X) =
      eqToHom (by simp [IsFrobenius.stableSuspension_obj_projectiveStableFunctor_obj]) ≫
        (nullHomotopic C w).quotientFunctor.map
          (((curvedDuplex_split_isFrobenius C w).suspensionPresentation X).cokernelMap
            (curvedDuplexSplitSuspensionPresentation X) (𝟙 X)) ≫
        eqToHom (by simp) := by
  have h : (stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso C w).hom.app
      (((split C).curvedDuplex w).projectiveStableFunctor.obj X) =
        (curvedDuplexSplitStableToHomotopy C w).map
          ((curvedDuplexSplitStableSuspensionIsoParityShift C w).hom.app X) ≫
            eqToHom (by simp) := by
    simp [stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso, eqToHom_map]
  rw [h, curvedDuplexSplitStableSuspensionIsoParityShift_hom_app]
  -- The component is typed at the parity shift, while the cokernel map is typed at the cokernel
  -- term of the presentation; unfolding the presentation makes the two agree reducibly.
  dsimp only [curvedDuplexSplitSuspensionPresentation]
  simp [eqToHom_map, curvedDuplexSplitStableToHomotopy_map_projectiveStableFunctor_map]

/-- The comparison from the componentwise split stable category to the homotopy category of
curved duplexes commutes with the shifts by `ℤ`: the one generated by stable suspension and the
one generated by the parity shift. -/
@[instance_reducible]
noncomputable def curvedDuplexSplitStableToHomotopyCommShift :
    letI := (curvedDuplex_split_isFrobenius C w).stableHasShift
    (curvedDuplexSplitStableToHomotopy C w).CommShift ℤ :=
  (curvedDuplex_split_isFrobenius C w).commShiftOfIntertwiningStableSuspension
    (HomotopyCategory.parityShiftEquivalence C w) _
    (stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso C w)

/-- In degree one, the shift compatibility of the stable-to-homotopy comparison is the
identification of stable suspension with the parity shift. -/
theorem curvedDuplexSplitStableToHomotopyCommShift_iso_one :
    letI := (curvedDuplex_split_isFrobenius C w).stableHasShift
    letI := curvedDuplexSplitStableToHomotopyCommShift C w
    (curvedDuplexSplitStableToHomotopy C w).commShiftIso (1 : ℤ) =
      Functor.isoWhiskerRight (curvedDuplex_split_isFrobenius C w).stableShiftFunctorOneIso _ ≪≫
        stableSuspensionCompCurvedDuplexSplitStableToHomotopyIso C w ≪≫
          Functor.isoWhiskerLeft _ (HomotopyCategory.shiftFunctorOneIso C w).symm :=
  (curvedDuplex_split_isFrobenius C w).commShiftOfIntertwiningStableSuspension_iso_one _ _ _

end ExactStructure

end TauCeti
