/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.UpperTriangular.Basic

/-!
# The upper-triangular Borel subgroup scheme of `GL₂`

For a commutative ring `R`, this file specializes the standard upper-triangular subgroup of
`GL_n` to rank two. For the weights `(1, 0)` the only forbidden coordinate is the lower-left
one, so the defining Hopf ideal in the coordinate Hopf algebra of `GL₂` is the principal ideal
`(X₁₀)`.

Everything else about this subgroup is the general-rank `UpperTriangular` API at `n = 2`: the
closed subgroup scheme `TauCeti.GeneralLinear.UpperTriangular.groupScheme R 2`, its closed
immersion `TauCeti.GeneralLinear.UpperTriangular.inclusion R 2` into `GL₂`, the description of
its points as upper-triangular matrices
(`TauCeti.GeneralLinear.UpperTriangular.pointsMulEquiv`), and the fact that it is a Borel
subgroup over every field (`TauCeti.GeneralLinear.UpperTriangular.isBorel_definingHopfIdeal`).

## Main declarations

* `TauCeti.GeneralLinear.Borel.lowerLeftCoordinate`: the coordinate `X₁₀` of `O(GL₂)`.
* `TauCeti.GeneralLinear.Borel.definingHopfIdeal`: the Hopf ideal `(X₁₀)` in `O(GL₂)`.
* `TauCeti.GeneralLinear.Borel.definingHopfIdeal_toIdeal`: its underlying ideal is generated by
  `X₁₀`.
* `TauCeti.GeneralLinear.Borel.coordinateHopfAlgebra`: the quotient coordinate Hopf algebra.

## References

* J. S. Milne, *Algebraic Groups* (2017), §§12 and 21.
* R. W. Carter, *Simple Groups of Lie Type* (1972), §8.2.
-/

public section

namespace TauCeti.GeneralLinear.Borel

universe u

variable (R : Type u) [CommRing R]

/-- The lower-left coordinate of the localized generic `2 × 2` matrix. -/
noncomputable def lowerLeftCoordinate : GeneralLinear.coordinateHopfAlgebra R 2 :=
  GeneralLinear.coordinateHopfAlgebraAlgEquiv R 2
    (GeneralLinear.coordinateRingMap R 2 (MvPolynomial.X ((1 : Fin 2), (0 : Fin 2))))

/-- The lower-left coordinate is the image of the corresponding generic matrix variable. -/
theorem lowerLeftCoordinate_def :
    lowerLeftCoordinate R =
      GeneralLinear.coordinateHopfAlgebraAlgEquiv R 2
        (GeneralLinear.coordinateRingMap R 2
          (MvPolynomial.X ((1 : Fin 2), (0 : Fin 2)))) := by
  unfold lowerLeftCoordinate
  rfl

/-- The weights `(1, 0)` whose weight parabolic is the standard upper-triangular Borel. -/
abbrev weights : Fin 2 → ℤ :=
  UpperTriangular.weights 2

/-- For the weights `(1, 0)`, the weight-parabolic relation set is the singleton containing the
lower-left coordinate. -/
theorem weightParabolicRelationSet_weights :
    GeneralLinear.weightParabolicRelationSet R weights = {lowerLeftCoordinate R} := by
  ext x
  simp [Fin.exists_fin_two, lowerLeftCoordinate_def]

/-- The Hopf ideal `(X₁₀)` cutting out the upper-triangular matrices inside `GL₂`. -/
noncomputable abbrev definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R 2) :=
  GeneralLinear.weightParabolicDefiningHopfIdeal R weights

/-- The underlying ideal of the Borel Hopf ideal is the principal ideal `(X₁₀)`. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R).toIdeal = Ideal.span {lowerLeftCoordinate R} := by
  rw [definingHopfIdeal, GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal,
    weightParabolicRelationSet_weights]

/-- The coordinate Hopf algebra of the upper-triangular Borel subgroup scheme of `GL₂`. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  GeneralLinear.weightParabolicCoordinateHopfAlgebra R weights

end TauCeti.GeneralLinear.Borel
