/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Separable
import Mathlib.FieldTheory.SeparableDegree
import Mathlib.RingTheory.IntegralClosure.IsIntegralClosure.Basic

/-!
# Separable subalgebras generated by commuting elements

In a possibly noncommutative domain over a field, a pairwise commuting set of separable
elements generates a separable commutative subalgebra. This permits adjoining separable
elements to subfields of a division algebra without requiring the ambient algebra to be
commutative.
-/

public section

open Algebra

open scoped IsMulCommutative

namespace Set.Pairwise

variable {K A : Type*} [Field K] [Ring A] [IsDomain A] [Algebra K A]

/-- A pairwise commuting set in a domain generates a separable subalgebra if and only if
all of its generators are separable. The ambient domain need not be commutative or finite
dimensional. -/
theorem isSeparable_adjoin_iff {s : Set A} (hcomm : s.Pairwise Commute) :
    Algebra.IsSeparable K (adjoin K s) ↔ ∀ x ∈ s, IsSeparable K x := by
  refine ⟨fun h x hx ↦ (Subalgebra.isSeparable_iff.mp h) x (subset_adjoin hx), fun hsep ↦ ?_⟩
  have : IsMulCommutative (adjoin K s) := isMulCommutative_adjoin K hcomm
  -- Mathlib's `Field.isSeparable_add` and `Field.isSeparable_mul` apply inside
  -- the generated commutative domain, which is a field by integrality.
  have : Algebra.IsIntegral K (adjoin K s) := ⟨fun x ↦ by
    obtain ⟨x, hx⟩ := x
    induction hx using adjoin_induction with
    | mem x hx =>
      exact (isIntegral_algHom_iff (adjoin K s).val Subtype.val_injective).mp
        (hsep x hx).isIntegral
    | algebraMap r => exact isIntegral_algebraMap
    | add x y hx hy ihx ihy => exact ihx.add ihy
    | mul x y hx hy ihx ihy => exact ihx.mul ihy⟩
  let _ : Field (adjoin K s) := (isField_of_isIntegral_of_isField' (Field.toIsField K)).toField
  refine ⟨fun x ↦ ?_⟩
  obtain ⟨x, hx⟩ := x
  induction hx using adjoin_induction with
  | mem x hx =>
    exact (isSeparable_map_iff (adjoin K s).val Subtype.val_injective).mp (hsep x hx)
  | algebraMap r => exact isSeparable_algebraMap r
  | add x y hx hy ihx ihy => exact Field.isSeparable_add ihx ihy
  | mul x y hx hy ihx ihy => exact Field.isSeparable_mul ihx ihy

end Set.Pairwise
