/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Separable
import Mathlib.FieldTheory.SeparableDegree

/-!
# Separability in towers with a noncommutative ambient domain

If `L / K` is a separable field extension and an element of an `L`-algebra without zero divisors
is separable over `L`, it is separable over `K`. The ambient algebra need not be commutative or
finite-dimensional. This allows separable elements of a centralizer to be read over the original
base field when enlarging a separable subfield of a division algebra.

`IsSeparable.restrictScalars` extends Mathlib's
`IsSeparable.of_algebra_isSeparable_of_isSeparable`, whose ambient type is a field. The
commutative algebra generated by the element is a finite-dimensional domain over `L`, hence a
field, so the existing field theorem applies there.

## References

See R. S. Pierce, *Associative Algebras*, Chapter 13, for separable maximal subfields of central
division algebras.
-/

public section

open scoped IsMulCommutative

namespace IsSeparable

variable {K L A : Type*} [Field K] [Field L] [Ring A] [IsDomain A]
  [Algebra K L] [Algebra K A] [Algebra L A] [IsScalarTower K L A]
  [Algebra.IsSeparable K L]

/-- An element of a possibly noncommutative domain that is separable over a separable field
extension is separable over the base field. -/
theorem restrictScalars {x : A} (hx : IsSeparable L x) : IsSeparable K x := by
  let M := Algebra.adjoin L ({x} : Set A)
  have : Module.Finite L M := Algebra.finite_adjoin_simple_of_isIntegral hx.isIntegral
  let : Field M := (IsField.of_isDomain_of_finite L M).toField
  let y : M := ⟨x, Algebra.subset_adjoin (Set.mem_singleton x)⟩
  have hy : IsSeparable L y :=
    (isSeparable_map_iff M.val Subtype.val_injective).mp hx
  exact (IsSeparable.of_algebra_isSeparable_of_isSeparable K hy).map
    (M.val.restrictScalars K) Subtype.val_injective

end IsSeparable
