/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.LinearAlgebra.ExteriorAlgebra.Contraction
public import TauCeti.LinearAlgebra.ExteriorPower.Basis

/-!
# Recovering a subspace from its exterior line

A finite subset of a basis spans a direct summand. Its top exterior product recovers that
summand: a vector belongs to it exactly when its exterior product with the top product vanishes.
Consequently a linear automorphism stabilizes the summand exactly when its induced exterior
algebra automorphism stabilizes the line of the top product. All results hold over arbitrary
commutative rings, so they apply after scalar extension to nonreduced value algebras as well.

This is the linear algebra in the passage from subspace stabilizers to line stabilizers in
Chevalley's theorem; see J. S. Milne, *Algebraic Groups* (2017), Lemma 4.28 and Theorem 4.27.
The recovery argument uses the contraction formulas in
`TauCeti.LinearAlgebra.ExteriorAlgebra.Contraction`.
-/

public section

open Submodule

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

namespace ExteriorAlgebra

/-- The exterior product of a family in the span of another family of the same length belongs
to the line generated by the exterior product of that family. -/
theorem ιMulti_mem_span_of_mem_span {n : ℕ} (v w : Fin n → M)
    (hw : ∀ i, w i ∈ span R (Set.range v)) :
    ιMulti R n w ∈ span R {ιMulti R n v} := by
  let b := Pi.basisFun R (Fin n)
  let f := b.constr R v
  have hrange : LinearMap.range f = span R (Set.range v) := b.constr_range R
  have hw' (i : Fin n) : w i ∈ LinearMap.range f := by
    rw [hrange]
    exact hw i
  choose w' hw' using hw'
  have h := congrArg (fun x : ⋀[R]^n (Fin n → R) ↦
    (map f) (x : ExteriorAlgebra R (Fin n → R)))
    (b.exteriorPower_ιMulti_eq_det_smul w')
  have heq : ιMulti R n w = b.det w' • ιMulti R n v := by
    simpa [f, Function.comp_def, hw'] using h
  rw [heq]
  exact smul_mem _ _ (subset_span (Set.mem_singleton _))

end ExteriorAlgebra

namespace Module.Basis

variable {I : Type*} [LinearOrder I] (b : Basis I R M) (s : Finset I)

/-- A vector belongs to the span of a finite subset of a basis exactly when wedging it with
the exterior product of that subset gives zero. This includes the empty subset. -/
@[simp]
theorem ι_mul_exteriorAlgebra_eq_zero_iff (v : M) :
    ExteriorAlgebra.ι R v * b.ExteriorAlgebra s = 0 ↔
      v ∈ span R (b '' (s : Set I)) := by
  classical
  constructor
  · intro h
    rw [b.mem_span_image]
    intro i hi
    by_contra his
    have his' : i ∉ s := his
    have hc := congrArg
      (CliffordAlgebra.contractLeft (Q := (0 : QuadraticForm R M)) (b.coord i)) h
    rw [CliffordAlgebra.contractLeft_ι_mul,
      TauCeti.ExteriorAlgebra.contractLeft_coord_basis, ite_eq_right his',
      mul_zero, sub_zero, map_zero] at hc
    have hz := congrArg (fun x ↦ b.ExteriorAlgebra.repr x s) hc
    simp only [map_smul, Finsupp.smul_apply, Basis.repr_self, Finsupp.single_eq_same,
      smul_eq_mul, mul_one, map_zero, Finsupp.zero_apply, Basis.coord_apply] at hz
    exact (Finsupp.mem_support_iff.mp hi) hz
  · intro h
    induction h using Submodule.span_induction with
    | mem x hx =>
        obtain ⟨i, hi, rfl⟩ := hx
        have hi' : i ∈ s := hi
        simp [TauCeti.ExteriorAlgebra.ι_mul_basis, hi']
    | zero => simp
    | add x y _ _ hx hy => simp [add_mul, hx, hy]
    | smul r x _ hx => simp [hx]

/-- Exterior products are natural under a change of basis induced by a linear equivalence. -/
@[simp]
theorem map_exteriorAlgebra {N : Type*} [AddCommGroup N] [Module R N]
    (f : M ≃ₗ[R] N) :
    ExteriorAlgebra.map f.toLinearMap (b.ExteriorAlgebra s) =
      (b.map f).ExteriorAlgebra s := by
  simp [ExteriorAlgebra.basis_apply, ExteriorAlgebra.ιMulti_family, Function.comp_def]

/-- Preserving a coordinate summand preserves its top exterior line. -/
theorem map_span_exteriorAlgebra_le (f : M →ₗ[R] M)
    (hf : (span R (b '' (s : Set I))).map f ≤ span R (b '' (s : Set I))) :
    (span R {b.ExteriorAlgebra s}).map (ExteriorAlgebra.map f).toLinearMap ≤
      span R {b.ExteriorAlgebra s} := by
  rw [Submodule.map_span, Set.image_singleton, span_le, Set.singleton_subset_iff]
  let t : Set.powersetCard I s.card := (Set.powersetCard.prodEquiv.symm s).2
  let e : Fin s.card ↪o I := Set.powersetCard.ofFinEmbEquiv.symm t
  have hrange : Set.range (b ∘ e) = b '' (s : Set I) := by
    rw [Set.range_comp]
    congr 1
    ext i
    exact Set.powersetCard.mem_range_ofFinEmbEquiv_symm_iff_mem t i
  have hw (i : Fin s.card) : f (b (e i)) ∈ span R (Set.range (b ∘ e)) := by
    rw [hrange]
    apply hf
    exact Submodule.mem_map_of_mem (subset_span (hrange ▸ Set.mem_range_self i))
  have h := ExteriorAlgebra.ιMulti_mem_span_of_mem_span
    (b ∘ e) (f ∘ b ∘ e) hw
  simpa [ExteriorAlgebra.basis_apply, ExteriorAlgebra.ιMulti_family,
    t, e, Function.comp_def] using h

/-- A linear automorphism stabilizes the top exterior line of a coordinate summand exactly
when it stabilizes that summand. No field or reducedness assumption on the scalars is needed. -/
@[simp]
theorem map_span_exteriorAlgebra_eq_iff (f : M ≃ₗ[R] M) :
    (span R {b.ExteriorAlgebra s}).map (ExteriorAlgebra.map f.toLinearMap).toLinearMap =
        span R {b.ExteriorAlgebra s} ↔
      (span R (b '' (s : Set I))).map f.toLinearMap = span R (b '' (s : Set I)) := by
  constructor
  · intro h
    have hann (v : M) :
        ExteriorAlgebra.ι R v * (b.map f).ExteriorAlgebra s = 0 ↔
          ExteriorAlgebra.ι R v * b.ExteriorAlgebra s = 0 := by
      have hline : span R {(b.map f).ExteriorAlgebra s} = span R {b.ExteriorAlgebra s} := by
        simpa [Submodule.map_span] using h
      have hk := congrArg (fun p : Submodule R (_root_.ExteriorAlgebra R M) ↦
        p ≤ LinearMap.ker (LinearMap.mulLeft R (ExteriorAlgebra.ι R v))) hline
      simpa only [span_singleton_le_iff_mem, LinearMap.mem_ker, LinearMap.mulLeft_apply] using
        (Iff.of_eq hk)
    rw [Submodule.map_span, ← Set.image_comp]
    ext v
    have hv := hann v
    rw [(b.map f).ι_mul_exteriorAlgebra_eq_zero_iff, b.ι_mul_exteriorAlgebra_eq_zero_iff] at hv
    simpa only [Basis.coe_map, Function.comp_def, LinearEquiv.coe_coe] using hv
  · intro h
    apply le_antisymm (b.map_span_exteriorAlgebra_le s f.toLinearMap h.le)
    have hi : (span R (b '' (s : Set I))).map f.symm.toLinearMap =
        span R (b '' (s : Set I)) := (Submodule.map_symm_eq_iff f).mpr h
    have hl := b.map_span_exteriorAlgebra_le s f.symm.toLinearMap hi.le
    have hm := Submodule.map_mono (f := (ExteriorAlgebra.map f.toLinearMap).toLinearMap) hl
    simpa [← Submodule.map_comp, ← AlgHom.comp_toLinearMap,
      ExteriorAlgebra.map_comp_map, LinearEquiv.comp_coe] using hm

/-- Stabilizing a coordinate summand is equivalent to stabilizing its top exterior line in the
corresponding exterior power. This is the form used for finite-dimensional representations. -/
@[simp↓]
theorem map_span_exteriorPower_eq_iff {n : ℕ} (t : Set.powersetCard I n)
    (f : M ≃ₗ[R] M) :
    (span R {b.exteriorPower n t}).map (exteriorPower.map n f.toLinearMap) =
        span R {b.exteriorPower n t} ↔
      (span R (b '' (t.val : Set I))).map f.toLinearMap =
        span R (b '' (t.val : Set I)) := by
  rw [← (Submodule.map_injective_of_injective
    (Submodule.subtype_injective (⋀[R]^n M))).eq_iff]
  simpa only [Submodule.map_span, Set.image_singleton, Submodule.coe_subtype,
    exteriorPower.coe_map, ← ExteriorAlgebra.basis_eq_coe_basis, AlgHom.toLinearMap_apply] using
    b.map_span_exteriorAlgebra_eq_iff t.val f

end Module.Basis
