/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.ExteriorAlgebra.Subspace
public import TauCeti.LinearAlgebra.ExteriorPower.Basic
public import Mathlib.LinearAlgebra.TensorProduct.Basis
public import TauCeti.LinearAlgebra.Basis.Submodule

/-!
# The top exterior line of a subspace

For a subspace `W` of dimension `d`, the submodule `(W.map (ExteriorAlgebra.ι k)) ^ d`
is its top exterior line inside the exterior algebra of the ambient space. After extension
to any commutative value algebra, a linear automorphism stabilizes this line exactly when
it stabilizes the extended subspace. No reducedness assumption on the value algebra is needed.

This supplies the linear-algebra step in Chevalley's realization of a closed subgroup as a
line stabilizer. The line is described intrinsically by a submodule power, independently of
an adapted basis. Its comparison with scalar extension of the original exterior representation
is a separate construction.

## References

* J. S. Milne, *Algebraic Groups* (2017), Lemma 4.28 and Theorem 4.27.
-/

public section

open scoped TensorProduct
open Submodule

namespace Module.Basis

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- The top exterior power, viewed inside the exterior algebra, is generated by the
exterior product of a basis. -/
theorem exteriorPower_eq_span_ιMulti {n : ℕ} (b : Basis (Fin n) R M) :
    (⋀[R]^n M) = span R {ExteriorAlgebra.ιMulti R n b} := by
  rw [← exteriorPower.ιMulti_span_fixedDegree]
  apply le_antisymm
  · apply span_le.mpr
    rintro _ ⟨v, rfl⟩
    have h := congrArg (fun x : ⋀[R]^n M ↦ (x : _root_.ExteriorAlgebra R M))
      (b.exteriorPower_ιMulti_eq_det_smul v)
    simp only [Submodule.coe_smul, exteriorPower.ιMulti_apply_coe] at h
    rw [h]
    exact smul_mem _ _ (subset_span (Set.mem_singleton _))
  · exact span_mono (Set.singleton_subset_iff.mpr
      (Set.mem_range_self (f := ExteriorAlgebra.ιMulti R n) (⇑b)))

variable {I : Type*} [LinearOrder I] (b : Basis I R M) (s : Finset I)

/-- The top exterior power of a coordinate summand is its exterior basis line. -/
theorem map_ι_span_pow_eq_span_exteriorAlgebra :
    ((span R (b '' (s : Set I))).map (ExteriorAlgebra.ι R)) ^ s.card =
      span R {b.ExteriorAlgebra s} := by
  classical
  let t : Set.powersetCard I s.card := (Set.powersetCard.prodEquiv.symm s).2
  let e : Fin s.card ↪o I := Set.powersetCard.ofFinEmbEquiv.symm t
  have hrange : Set.range (b ∘ e) = b '' (s : Set I) := by
    rw [Set.range_comp]
    congr 1
    ext i
    exact Set.powersetCard.mem_range_ofFinEmbEquiv_symm_iff_mem t i
  let c := Module.Basis.span (b.linearIndependent.comp e e.injective)
  have htop := congrArg (Submodule.map (ExteriorAlgebra.map
    (span R (Set.range (b ∘ e))).subtype).toLinearMap)
    c.exteriorPower_eq_span_ιMulti
  rw [TauCeti.ExteriorAlgebra.exteriorPower_map_map, Submodule.range_subtype] at htop
  rw [← hrange, Submodule.map_span]
  simp only [Submodule.map_span, Set.image_singleton, AlgHom.toLinearMap_apply,
    ExteriorAlgebra.map_apply_ιMulti, c, Function.comp_def,
    Module.Basis.coe_span_apply, Submodule.subtype_apply] at htop
  simpa only [ExteriorAlgebra.basis_apply, ExteriorAlgebra.ιMulti_family, t, e,
    Function.comp_def] using htop

end Module.Basis

namespace Submodule

variable {k V : Type*} [Field k] [AddCommGroup V] [Module k V] [Module.Finite k V]

/-- The top exterior image of a subspace is a line, including when the subspace is zero. -/
theorem finrank_topExteriorLine (W : Submodule k V) :
    Module.finrank k ↥((W.map (ExteriorAlgebra.ι k)) ^ Module.finrank k W) = 1 := by
  obtain ⟨b, s, hW, hs⟩ := W.exists_basis_span_image_eq
  rw [← hs, ← hW, b.map_ι_span_pow_eq_span_exteriorAlgebra s]
  exact finrank_span_singleton (b.ExteriorAlgebra.ne_zero s)

/-- After arbitrary scalar extension, the top exterior image of a subspace has a basis
indexed by a singleton, including over the zero value algebra. -/
theorem nonempty_basis_topExteriorLine_baseChange (W : Submodule k V)
    (A : Type*) [CommRing A] [Algebra k A] :
    Nonempty (Module.Basis Unit A
      ↥(((W.baseChange A).map (ExteriorAlgebra.ι A)) ^ Module.finrank k W)) := by
  obtain ⟨b, s, hW, hs⟩ := W.exists_basis_span_image_eq
  have hWA : W.baseChange A = span A ((b.baseChange A) '' (s : Set _)) := by
    rw [← hW, Submodule.baseChange_span, Set.image_image]
    congr 1
    ext x
    simp only [Set.mem_image, Module.Basis.baseChange_apply, TensorProduct.mk_apply]
  rw [← hs, hWA, (b.baseChange A).map_ι_span_pow_eq_span_exteriorAlgebra s]
  let c := Module.Basis.span ((b.baseChange A).ExteriorAlgebra.linearIndependent.comp
    (fun _ : Unit ↦ s) (by intro x y _; exact Subsingleton.elim x y))
  have hr : Set.range (fun _ : Unit ↦ (b.baseChange A).ExteriorAlgebra s) =
      {(b.baseChange A).ExteriorAlgebra s} := Set.range_const
  exact ⟨hr ▸ c⟩

/-- Over any commutative value algebra, an automorphism stabilizes the top exterior line
of an extended subspace if and only if it stabilizes that subspace. The exponent is the
dimension over the original field, so this also applies to the zero value algebra. -/
theorem map_topExteriorLine_baseChange_eq_iff (W : Submodule k V)
    (A : Type*) [CommRing A] [Algebra k A] (f : A ⊗[k] V ≃ₗ[A] A ⊗[k] V) :
    (((W.baseChange A).map (ExteriorAlgebra.ι A)) ^ Module.finrank k W).map
        (ExteriorAlgebra.map f.toLinearMap).toLinearMap =
      ((W.baseChange A).map (ExteriorAlgebra.ι A)) ^ Module.finrank k W ↔
        (W.baseChange A).map f.toLinearMap = W.baseChange A := by
  obtain ⟨b, s, hW, hs⟩ := W.exists_basis_span_image_eq
  have hWA : W.baseChange A = span A ((b.baseChange A) '' (s : Set _)) := by
    rw [← hW, Submodule.baseChange_span, Set.image_image]
    congr 1
    ext x
    simp only [Set.mem_image, Module.Basis.baseChange_apply, TensorProduct.mk_apply]
  rw [← hs, hWA, (b.baseChange A).map_ι_span_pow_eq_span_exteriorAlgebra s]
  exact (b.baseChange A).map_span_exteriorAlgebra_eq_iff s f

end Submodule
