/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.CharacterTable.ProductOne

/-!
# Product-one triples generating a subgroup

The Frobenius formula counts all product-one triples in three conjugacy classes of a finite
group. To count covers with prescribed monodromy, one must also require that the first two
entries generate the specified subgroup. Every product-one triple belongs to exactly one
generation stratum, indexed by the subgroup generated by its first two entries. This file
states the resulting subgroup-lattice recursion for the counts.

The classes remain classes of the ambient group throughout: intersecting them with a subgroup
does not in general produce a single conjugacy class of that subgroup.

-/

public section

namespace TauCeti

variable {G : Type*} [Group G]

/-- The subgroup generated by the first two entries of a triple. For a product-one triple, the
third entry belongs to this subgroup as well. -/
def productOneGeneratedSubgroup (p : G × G × G) : Subgroup G :=
  Subgroup.closure {p.1, p.2.1}

/-- The subgroup generated by a triple is the closure of its first two entries. -/
theorem productOneGeneratedSubgroup_def (p : G × G × G) :
    productOneGeneratedSubgroup p = Subgroup.closure {p.1, p.2.1} := (rfl)

/-- A homomorphism sends the subgroup generated by the first two entries to the subgroup
generated by their images. -/
@[simp] theorem productOneGeneratedSubgroup_map {H : Type*} [Group H]
    (f : G →* H) (p : G × G × G) :
    productOneGeneratedSubgroup (f p.1, f p.2.1, f p.2.2) =
      (productOneGeneratedSubgroup p).map f := by
  simp [productOneGeneratedSubgroup_def, MonoidHom.map_closure, Set.image_insert_eq,
    Set.image_singleton]

@[simp] theorem productOneGeneratedSubgroup_le_iff (p : G × G × G) (H : Subgroup G) :
    productOneGeneratedSubgroup p ≤ H ↔ p.1 ∈ H ∧ p.2.1 ∈ H := by
  rw [productOneGeneratedSubgroup_def, Subgroup.closure_le]
  simp only [Set.insert_subset_iff, Set.singleton_subset_iff, SetLike.mem_coe]

variable [Fintype G]

open scoped Classical in
/-- The product-one triples in three ambient conjugacy classes whose entries lie in `H`.
It suffices to check the first two entries, since the product-one equation determines the
third. -/
noncomputable def productOneTriplesIn (C0 C1 Cinf : ConjClasses G) (H : Subgroup G) :
    Finset (G × G × G) :=
  (productOneTriples C0 C1 Cinf).filter fun p ↦ p.1 ∈ H ∧ p.2.1 ∈ H

open Classical in
@[simp] theorem mem_productOneTriplesIn {C0 C1 Cinf : ConjClasses G}
    {H : Subgroup G} {p : G × G × G} :
    p ∈ productOneTriplesIn C0 C1 Cinf H ↔
      p ∈ productOneTriples C0 C1 Cinf ∧ p.1 ∈ H ∧ p.2.1 ∈ H := by
  simp [productOneTriplesIn]

open Classical in
/-- The third entry also lies in `H`: the product-one equation forces it to be the inverse
of the product of the first two entries. -/
theorem productOneTriplesIn.third_mem {C0 C1 Cinf : ConjClasses G}
    {H : Subgroup G} {p : G × G × G} (hp : p ∈ productOneTriplesIn C0 C1 Cinf H) :
    p.2.2 ∈ H := by
  obtain ⟨hprod, hx, hy⟩ := mem_productOneTriplesIn.mp hp
  have hrel : p.2.2 * (p.2.1 * p.1) = 1 := by
    simpa only [mul_assoc] using (mem_productOneTriples.mp hprod).2.2.2
  rw [eq_inv_of_mul_eq_one_left hrel]
  exact H.inv_mem (H.mul_mem hy hx)

open scoped Classical in
/-- The triples in three ambient classes that generate exactly `H`. -/
noncomputable def generatingProductOneTriples (C0 C1 Cinf : ConjClasses G) (H : Subgroup G) :
    Finset (G × G × G) :=
  (productOneTriples C0 C1 Cinf).filter fun p ↦ productOneGeneratedSubgroup p = H

open Classical in
@[simp] theorem mem_generatingProductOneTriples {C0 C1 Cinf : ConjClasses G}
    {H : Subgroup G} {p : G × G × G} :
    p ∈ generatingProductOneTriples C0 C1 Cinf H ↔
      p ∈ productOneTriples C0 C1 Cinf ∧ productOneGeneratedSubgroup p = H := by
  simp [generatingProductOneTriples]

open Classical in
/-- A generating product-one triple lies in the subgroup it generates. -/
theorem generatingProductOneTriples_subset_in (C0 C1 Cinf : ConjClasses G)
    (H : Subgroup G) :
    generatingProductOneTriples C0 C1 Cinf H ⊆ productOneTriplesIn C0 C1 Cinf H := by
  intro p hp
  rcases mem_generatingProductOneTriples.mp hp with ⟨hprod, hgen⟩
  exact mem_productOneTriplesIn.mpr
    ⟨hprod, (productOneGeneratedSubgroup_le_iff p H).mp hgen.le⟩

open Classical in
/-- Restricting product-one triples to the whole group changes nothing. -/
@[simp] theorem productOneTriplesIn_top (C0 C1 Cinf : ConjClasses G) :
    productOneTriplesIn C0 C1 Cinf ⊤ = productOneTriples C0 C1 Cinf := by
  ext p
  simp

open scoped Classical in
/-- **Subgroup-lattice partition.** Every product-one triple in `H` generates a unique
subgroup `K ≤ H`. The conjugacy classes are those of `G`, even when `K` is proper. -/
theorem card_productOneTriplesIn_eq_sum_generating (C0 C1 Cinf : ConjClasses G)
    (H : Subgroup G) :
    (productOneTriplesIn C0 C1 Cinf H).card =
      ∑ K ∈ Finset.univ.filter (· ≤ H),
        (generatingProductOneTriples C0 C1 Cinf K).card := by
  classical
  rw [Finset.card_eq_sum_card_fiberwise
    (f := productOneGeneratedSubgroup)
    (t := Finset.univ.filter (· ≤ H))]
  · refine Finset.sum_congr rfl fun K hK ↦ ?_
    have hKH : K ≤ H := (Finset.mem_filter.mp hK).2
    apply congrArg Finset.card
    ext p
    simp only [Finset.mem_filter, mem_productOneTriplesIn,
      mem_generatingProductOneTriples]
    constructor
    · rintro ⟨⟨hp, -, -⟩, hgen⟩
      exact ⟨hp, hgen⟩
    · rintro ⟨hp, hgen⟩
      have ⟨hx, hy⟩ := (productOneGeneratedSubgroup_le_iff p H).mp (hgen ▸ hKH)
      exact ⟨⟨hp, hx, hy⟩, hgen⟩
  · intro p hp
    obtain ⟨-, hx, hy⟩ := mem_productOneTriplesIn.mp hp
    exact Finset.mem_filter.mpr ⟨Finset.mem_univ _,
      (productOneGeneratedSubgroup_le_iff p H).mpr ⟨hx, hy⟩⟩

open scoped Classical in
/-- The Frobenius count splits into generating counts over all subgroups. -/
theorem card_productOneTriples_eq_sum_generating (C0 C1 Cinf : ConjClasses G) :
    (productOneTriples C0 C1 Cinf).card =
      ∑ K : Subgroup G, (generatingProductOneTriples C0 C1 Cinf K).card := by
  rw [← productOneTriplesIn_top, card_productOneTriplesIn_eq_sum_generating]
  simp

open scoped Classical in
/-- **Downward recursion.** The count generating `H` is the total count of product-one
triples in `H` minus the counts generating its proper subgroups. -/
theorem card_generatingProductOneTriples (C0 C1 Cinf : ConjClasses G)
    (H : Subgroup G) :
    (generatingProductOneTriples C0 C1 Cinf H).card =
      (productOneTriplesIn C0 C1 Cinf H).card -
        ∑ K ∈ Finset.univ.filter (· < H),
          (generatingProductOneTriples C0 C1 Cinf K).card := by
  classical
  have hH : H ∈ Finset.univ.filter (· ≤ H) := by simp
  have hsplit := card_productOneTriplesIn_eq_sum_generating C0 C1 Cinf H
  rw [← Finset.add_sum_erase _ _ hH] at hsplit
  have herase : (Finset.univ.filter (· ≤ H)).erase H = Finset.univ.filter (· < H) := by
    ext K
    simp only [Finset.mem_erase, Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨fun ⟨hne, hle⟩ ↦ lt_of_le_of_ne hle hne,
      fun hlt ↦ ⟨ne_of_lt hlt, le_of_lt hlt⟩⟩
  rw [herase] at hsplit
  omega

open scoped Classical in
/-- The downward recursion determines the generating counts uniquely. Thus one can compute
them from the total counts in subgroups without enumerating the generating triples themselves. -/
theorem generatingProductOneTriples_card_eq_of_recursion
    (C0 C1 Cinf : ConjClasses G) (f : Subgroup G → ℕ)
    (hf : ∀ H, f H = (productOneTriplesIn C0 C1 Cinf H).card -
      ∑ K ∈ Finset.univ.filter (· < H), f K) (H : Subgroup G) :
    f H = (generatingProductOneTriples C0 C1 Cinf H).card := by
  classical
  induction H using WellFoundedLT.induction with
  | ind H ih =>
    calc
      f H = (productOneTriplesIn C0 C1 Cinf H).card -
          ∑ K ∈ Finset.univ.filter (· < H), f K := hf H
      _ = (productOneTriplesIn C0 C1 Cinf H).card -
          ∑ K ∈ Finset.univ.filter (· < H),
            (generatingProductOneTriples C0 C1 Cinf K).card := by
              congr 1
              apply Finset.sum_congr rfl
              intro K hK
              exact ih K (Finset.mem_filter.mp hK).2
      _ = (generatingProductOneTriples C0 C1 Cinf H).card :=
        (card_generatingProductOneTriples C0 C1 Cinf H).symm

end TauCeti
