/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.FiniteExtension.IntermediateField
public import TauCeti.NumberTheory.LocalField.TamelyRamified.Basic
import TauCeti.Algebra.CharP.LocalRing
import TauCeti.FieldTheory.IntermediateField.Adjoin.Defs
import TauCeti.FieldTheory.IntermediateField.Adjoin.EqTop
import TauCeti.NumberTheory.LocalField.Unramified.Factorization

/-!
# Base change and composita of tamely ramified extensions of local fields

This file proves that tame ramification of extensions of nonarchimedean local fields is stable
under base change and under composita, with no Galois hypothesis. Let `L/K` be tamely ramified,
and let `M/F/K` be a tower in which `M` is generated over `F` by the image of a `K`-embedding
`ι : L →ₐ[K] M`. Then `M/F` is tamely ramified. Combined with transitivity in towers
(`TauCeti.isTamelyRamified_tower_iff`), this shows that the compositum, inside any extension `M`
of `K`, of two tamely ramified extensions of `K` is tamely ramified over `K`.

The basic case is a radical extension `L = K(β)` with `β^n = a ∈ Kˣ` and `n` prime to the
residue characteristic `p`: writing `g = gcd(v_K(a), n)` and `n = g n'`, the field `K(β^{n'})` is
unramified over `K` (`TauCeti.isUnramified_of_adjoin_eq_top_of_pow_eq`), and the valuation of `β`
forces `e(L/K) = n'`, which is prime to `p`. A general tame `L/K` is generated over `K` by a root
of unity of order prime to `p` and by an `e`-th root of an element of its maximal unramified
subextension (`TauCeti.IsTotallyRamified.exists_pow_eq_uniformizer_of_isTamelyRamified`), so its
base change is a tower of two such radical extensions.

## Main results

* `TauCeti.isTamelyRamified_of_adjoin_eq_top_of_pow_eq`: `K(a^{1/n})/K` is tamely ramified when
  `n` is prime to the residue characteristic.
* `TauCeti.IsTamelyRamified.of_adjoin_range_eq_top`: **base change**; if `L/K` is tamely ramified
  and `M` is generated over `F` by the image of `L`, then `M/F` is tamely ramified.
* `TauCeti.IsTamelyRamified.of_fieldRange_sup_fieldRange_eq_top`: **composita**; if `M` is the
  compositum of the images of two tamely ramified extensions of `K`, then `M/K` is tamely
  ramified.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter IV, §2.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §7.
-/

public section

open ValuativeRel Polynomial IntermediateField

namespace TauCeti

section Radical

variable {K L : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]

/-- **Radical extensions of exponent prime to `p` are tamely ramified.** Let `L = K(β)` with
`β^n = a` for some `a ∈ Kˣ`, where the residue characteristic of `K` does not divide `n`. Then
`L/K` is tamely ramified. -/
theorem isTamelyRamified_of_adjoin_eq_top_of_pow_eq {n : ℕ} (hn : ¬ ringChar 𝓀[K] ∣ n) {β : L}
    (hβ : K⟮β⟯ = ⊤) {a : Kˣ} (ha : β ^ n = algebraMap K L a) : IsTamelyRamified K L := by
  have := finite_of_valuativeExtension K L
  have hn0 : n ≠ 0 := by rintro rfl; exact hn (dvd_zero _)
  have hβ0 : β ≠ 0 := by
    rintro rfl
    rw [zero_pow hn0, eq_comm, map_eq_zero] at ha
    exact a.ne_zero ha
  -- The valuation equation `n · v_L(β) = e(L/K) · v_K(a)`.
  set m := (normalizedValuation K a).toAdd
  set s := (normalizedValuation L (Units.mk0 β hβ0)).toAdd
  have hval : (n : ℤ) * s = ramificationIndex K L * m := by
    have h : Units.mk0 β hβ0 ^ n = Units.map (algebraMap K L : K →* L) a :=
      Units.ext (by simp [ha])
    have h' := congrArg (fun x ↦ (normalizedValuation L x).toAdd) h
    simpa only [map_pow, normalizedValuation_algebraMap, toAdd_pow, nsmul_eq_mul] using h'
  -- Write `m = m' g` and `n = n' g` with `m'` and `n'` coprime.
  obtain ⟨g, m', n', hg0, hcop, hm, hng⟩ :=
    Int.exists_gcd_one' (Int.gcd_pos_of_ne_zero_right m (Int.natCast_ne_zero.2 hn0))
  have hn'0 : 0 < n' :=
    pos_of_mul_pos_left (hng ▸ Int.natCast_pos.2 (Nat.pos_of_ne_zero hn0)) (Int.natCast_nonneg g)
  set e' : ℕ := n'.toNat
  have he' : (e' : ℤ) = n' := Int.toNat_of_nonneg hn'0.le
  have hne : n = e' * g := by exact_mod_cast (he' ▸ hng :)
  -- The intermediate field `E = K(β^{n'})` is unramified over `K`: it is generated by a `g`-th
  -- root of `a`, and `g` divides `v_K(a)`.
  set E : IntermediateField K L := K⟮β ^ e'⟯
  let _ := finiteIntermediateFieldValuativeRel K L E
  let _ := finiteIntermediateFieldTopology K L E
  have := finiteIntermediateField_isNonarchimedeanLocalField K L E
  have := finiteIntermediateField_valuativeExtension K L E
  have hEK : IsUnramified K E :=
    isUnramified_of_adjoin_eq_top_of_pow_eq (fun h ↦ hn (hne ▸ h.mul_left e'))
      (AdjoinSimple.adjoin_gen_eq_top (β ^ e')) (a := a)
      (Subtype.ext (by simp [← pow_mul, ← hne, ha])) ⟨m', hm.trans (mul_comm _ _)⟩
  -- So `e(L/K) = e(L/E)`, which is at most `[L : E] ≤ n'`, as `β` is a root of `X^{n'} − β^{n'}`.
  have hLE : ramificationIndex K L = ramificationIndex E L :=
    (IsUnramified.ramificationIndex_tower_eq K E L).symm
  have hβE : E⟮β⟯ = ⊤ := by
    refine restrictScalars_eq_top_iff.1 (top_le_iff.1 (hβ ▸ adjoin_simple_le_iff.2 ?_))
    exact mem_adjoin_simple_self E β
  have hfin : Module.finrank E L ≤ e' := by
    have hroot : aeval β (X ^ e' - C (AdjoinSimple.gen K (β ^ e')) : E[X]) = 0 := by simp
    rw [← finrank_top', ← hβE, adjoin.finrank (.of_finite E β)]
    refine (natDegree_le_of_dvd (minpoly.dvd E β hroot)
      (X_pow_sub_C_ne_zero (Nat.pos_of_ne_zero fun h ↦ hn0 (by simp [hne, h])) _)).trans ?_
    exact natDegree_X_pow_sub_C.le
  have hle : ramificationIndex E L ≤ e' :=
    (Nat.le_of_dvd Module.finrank_pos
      (Dvd.intro _ (ramificationIndex_mul_inertiaDegree E L))).trans hfin
  -- Conversely `n' ∣ e(L/E)`: cancelling `g` gives `n' · v_L(β) = e(L/E) · m'`, and `n'` is
  -- prime to `m'`.
  have hdvd : e' ∣ ramificationIndex E L := by
    have h : n' * s = ramificationIndex E L * m' := by
      rw [hLE, hng, hm] at hval
      refine mul_right_cancel₀ (Int.natCast_ne_zero.2 hg0.ne') ?_
      linear_combination hval
    have hc : IsCoprime n' m' := (Int.isCoprime_iff_gcd_eq_one.2 hcop).symm
    exact Int.natCast_dvd_natCast.1 (he' ▸ hc.dvd_of_dvd_mul_right ⟨s, h.symm⟩)
  have heq : ramificationIndex K L = e' :=
    hLE.trans (le_antisymm hle (Nat.le_of_dvd ramificationIndex_pos hdvd))
  rw [isTamelyRamified_iff, heq]
  exact fun h ↦ hn (hne ▸ h.mul_right g)

end Radical

section BaseChange

variable {K L F M : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]
  [Field F] [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
  [Algebra K F] [ValuativeExtension K F]
  [Field M] [ValuativeRel M] [TopologicalSpace M] [IsNonarchimedeanLocalField M]
  [Algebra F M] [ValuativeExtension F M] [Algebra K M] [IsScalarTower K F M]

/-- **Base change of a tamely ramified extension.** Let `L/K` be a tamely ramified extension and
`M/F/K` a tower of nonarchimedean local fields. If `M` is generated over `F` by the image of a
`K`-embedding `ι : L →ₐ[K] M`, then `M/F` is tamely ramified. -/
theorem IsTamelyRamified.of_adjoin_range_eq_top (hL : IsTamelyRamified K L) (ι : L →ₐ[K] M)
    (h : IntermediateField.adjoin F (Set.range ι) = ⊤) : IsTamelyRamified F M := by
  have := finite_of_valuativeExtension K L
  have := finite_of_valuativeExtension F M
  -- Factor `L/K` through its maximal unramified subextension `L₀ = K(ζ)`, with `ζ` a root of
  -- unity of order `q^f − 1`, and write `L = L₀(α)` with `α^e ∈ L₀`.
  obtain ⟨ζ, hζ⟩ := exists_isPrimitiveRoot_natCard_pow_inertiaDegree_sub_one K L
  set L₀ := unramifiedExtension K L (inertiaDegree K L)
  have hL₀ : L₀ = K⟮ζ⟯ := unramifiedExtension_eq_adjoin_simple inertiaDegree_pos.ne' hζ
  let _ := finiteIntermediateFieldValuativeRel K L L₀
  let _ := finiteIntermediateFieldTopology K L L₀
  have := finiteIntermediateField_isNonarchimedeanLocalField K L L₀
  have := finiteIntermediateField_valuativeExtension K L L₀
  have htame : IsTamelyRamified L₀ L := ((isTamelyRamified_tower_iff (K := K) (L := L₀) L).1 hL).2
  obtain ⟨π, α, -, -, hα, hαtop⟩ :=
    IsTotallyRamified.exists_pow_eq_uniformizer_of_isTamelyRamified
      (isTotallyRamified_unramifiedExtension_inertiaDegree K L) htame
  have hgen : K⟮ζ, (α : L)⟯ = ⊤ := by
    refine top_le_iff.1 ?_
    rw [← restrictScalars_eq_top_iff.2 hαtop, restrictScalars_adjoin, adjoin_le_iff]
    rintro x (hx | rfl)
    · exact adjoin.mono _ _ _ (by simp) (hL₀ ▸ hx : x ∈ K⟮ζ⟯)
    · exact subset_adjoin _ _ (by simp)
  -- In `M`, the intermediate field `F₁ = F(ι ζ)` is generated by a root of unity of order prime
  -- to `p`, and `M = F₁(ι α)` with `(ι α)^e ∈ F₁`.
  have hMgen : F⟮ι ζ, ι α⟯ = ⊤ := by
    rw [← h, TauCeti.IntermediateField.adjoin_range_eq_adjoin_image ι hgen, Set.image_pair]
  set F₁ : IntermediateField F M := F⟮ι ζ⟯
  let _ := finiteIntermediateFieldValuativeRel F M F₁
  let _ := finiteIntermediateFieldTopology F M F₁
  have := finiteIntermediateField_isNonarchimedeanLocalField F M F₁
  have := finiteIntermediateField_valuativeExtension F M F₁
  have hcharF : ringChar 𝓀[F] = ringChar 𝓀[K] := (Algebra.ringChar_eq 𝓀[K] 𝓀[F]).symm
  have hF₁ : IsTamelyRamified F F₁ := by
    refine isTamelyRamified_of_adjoin_eq_top_of_pow_eq
      (n := Nat.card 𝓀[K] ^ inertiaDegree K L - 1) ?_ (AdjoinSimple.adjoin_gen_eq_top (ι ζ))
      (a := 1) (Subtype.ext (by simp [← map_pow, hζ.pow_eq_one]))
    rw [hcharF, ← IsLocalRing.isUnit_natCast_iff_not_dvd (R := 𝒪[K])]
    exact isUnit_natCast_natCard_pow_sub_one K inertiaDegree_pos.ne'
  -- The image of `α^e ∈ L₀ = K(ζ)` lies in `F₁`.
  have hπ : ι (π : L) ∈ F₁ := by
    have hmem : ι (π : L) ∈ (K⟮ζ⟯).map (ι : L →ₐ[K] M) := ⟨_, hL₀ ▸ (π : L₀).2, rfl⟩
    rw [adjoin_map, Set.image_singleton] at hmem
    have hle : K⟮ι ζ⟯ ≤ F₁.restrictScalars K := adjoin_simple_le_iff.2 (mem_adjoin_simple_self F _)
    exact hle hmem
  have hπ0 : (⟨ι (π : L), hπ⟩ : F₁) ≠ 0 := fun h0 ↦ by simpa using congrArg Subtype.val h0
  have hM : IsTamelyRamified F₁ M := by
    refine isTamelyRamified_of_adjoin_eq_top_of_pow_eq (n := ramificationIndex L₀ L) ?_
      (β := ι α) ?_ (a := Units.mk0 _ hπ0) ?_
    · rw [← Algebra.ringChar_eq 𝓀[F] 𝓀[F₁], hcharF, Algebra.ringChar_eq 𝓀[K] 𝓀[L₀]]
      exact (isTamelyRamified_iff L₀ L).1 htame
    · rw [← restrictScalars_eq_top_iff (K := F), adjoin_simple_adjoin_simple]
      exact hMgen
    · rw [← map_pow, hα]
      rfl
  exact (isTamelyRamified_tower_iff (K := F) (L := F₁) M).2 ⟨hF₁, hM⟩

end BaseChange

section Compositum

variable {K L₁ L₂ M : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]
  [Field L₁] [ValuativeRel L₁] [TopologicalSpace L₁] [IsNonarchimedeanLocalField L₁]
  [Algebra K L₁] [ValuativeExtension K L₁]
  [Field L₂] [ValuativeRel L₂] [TopologicalSpace L₂] [IsNonarchimedeanLocalField L₂]
  [Algebra K L₂] [ValuativeExtension K L₂]
  [Field M] [ValuativeRel M] [TopologicalSpace M] [IsNonarchimedeanLocalField M]
  [Algebra K M] [ValuativeExtension K M]

/-- **The compositum of tamely ramified extensions is tamely ramified.** If a finite extension
`M` of a nonarchimedean local field `K` is the compositum of the images of two `K`-embeddings of
tamely ramified extensions `L₁/K` and `L₂/K`, then `M/K` is tamely ramified. -/
theorem IsTamelyRamified.of_fieldRange_sup_fieldRange_eq_top (h₁ : IsTamelyRamified K L₁)
    (h₂ : IsTamelyRamified K L₂) (ι₁ : L₁ →ₐ[K] M) (ι₂ : L₂ →ₐ[K] M)
    (h : ι₁.fieldRange ⊔ ι₂.fieldRange = ⊤) : IsTamelyRamified K M := by
  have := finite_of_valuativeExtension K L₂
  -- View `M` as an extension of `L₂` through `ι₂`.
  let _ := ι₂.toAlgebra
  have : IsScalarTower K L₂ M := .of_algebraMap_eq fun x ↦ (ι₂.commutes x).symm
  have : ValuativeExtension L₂ M := ι₂.valuativeExtension
  -- `M` is generated over `L₂` by the image of `L₁`, so `M/L₂` is tamely ramified by base change,
  -- and `M/K` by transitivity.
  have hM := h₁.of_adjoin_range_eq_top (F := L₂) ι₁
    (TauCeti.IntermediateField.adjoin_range_eq_top_of_fieldRange_sup_fieldRange_eq_top ι₁
      ((sup_comm _ _).trans h))
  exact (isTamelyRamified_tower_iff (K := K) (L := L₂) M).2 ⟨h₂, hM⟩

end Compositum

end TauCeti
