/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.KummerPolynomial
public import TauCeti.NumberTheory.LocalField.Norm.Unramified.Basic
public import TauCeti.NumberTheory.LocalField.Padic
public import TauCeti.NumberTheory.LocalField.ResidueCorrespondence
public import TauCeti.NumberTheory.LocalField.Unramified.Criterion
import TauCeti.RingTheory.Norm.Quadratic

/-!
# The unramified quadratic extension `ℚ_2(√5)`

Since `5` is not a square in `ℚ_2`, adjoining a root of `X² − 5` gives a quadratic extension
`ℚ_2(√5)` of `ℚ_2`. This file equips it with the structure of a nonarchimedean local field
extending `ℚ_2`, through the spectral norm of `TauCeti.finiteExtensionValuativeRel`, and computes
its Frobenius.

The extension is unramified: the golden ratio `φ = (1 + √5) / 2` is a root of `X² − X − 1`, whose
derivative at `φ` is `2φ − 1 = √5`, a unit because its square `5` is a unit of `ℤ_2`. So the
residue field is `𝔽_4`, and the Galois group is generated by the arithmetic Frobenius, which
lifts `x ↦ x²` on `𝔽_4`. Being nontrivial, Frobenius is the conjugation `√5 ↦ −√5`.

Since a local field has, up to isomorphism, a unique unramified extension of each degree,
`ℚ_2(√5)` is an explicit model of the unramified quadratic extension of `ℚ_2`. It makes the
residue correspondence `Gal(ℚ_2(√5)/ℚ_2) ≃ Gal(𝔽_4/𝔽_2)` concrete, with the Frobenius of `𝔽_4`
lifting to an explicit automorphism of `ℚ_2(√5)`.

It also makes the norm-equation criterion for unramified extensions concrete. Since the residue
degree is `2`, an element of `ℚ_2ˣ` is a norm from `ℚ_2(√5)` exactly when its `2`-adic valuation
is even. So `a² − 5b² = 3` is solvable in `ℚ_2`, while `a² − 5b² = 2` is not. The first equation
has no solution in `ℚ`, since `3` is not a square modulo `5`, so its solvability in `ℚ_2` is a
genuinely local fact.

## Main definitions

* `TauCeti.DyadicSqrtFive`: the field `ℚ_2(√5)`, as a nonarchimedean local field over `ℚ_2`.
* `TauCeti.DyadicSqrtFive.sqrtFive`: the square root of `5` generating it.

## Main results

* `TauCeti.DyadicSqrtFive.finrank_eq_two`: `[ℚ_2(√5) : ℚ_2] = 2`.
* The instance `IsUnramified ℚ_[2] DyadicSqrtFive`: `ℚ_2(√5)/ℚ_2` is unramified.
* `TauCeti.DyadicSqrtFive.inertiaDegree_eq_two` and
  `TauCeti.DyadicSqrtFive.natCard_residueField`: the residue field has `2 ^ 2 = 4` elements.
* `TauCeti.DyadicSqrtFive.frobeniusAlgEquiv_sqrtFive`: arithmetic Frobenius sends `√5` to `−√5`.
* `TauCeti.DyadicSqrtFive.norm_add_mul_sqrtFive`: the norm of `a + b√5` is `a² − 5b²`.
* `TauCeti.DyadicSqrtFive.mem_normGroup_iff_even_valuation`: `x ∈ ℚ_2ˣ` is a norm from `ℚ_2(√5)`
  exactly when its `2`-adic valuation is even.
* `TauCeti.DyadicSqrtFive.exists_sq_sub_five_mul_sq_eq_three` and
  `TauCeti.DyadicSqrtFive.not_exists_sq_sub_five_mul_sq_eq_two`: the norm equation
  `a² − 5b² = 3` is solvable in `ℚ_2`, and `a² − 5b² = 2` is not.

## References

* J.-P. Serre, *Local Fields*, Chapter III, §5 and Chapter V, §2.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §7.
-/

public section
noncomputable section

open Polynomial ValuativeRel

namespace TauCeti

/-- The field `ℚ_2(√5)`, obtained from `ℚ_2` by adjoining a root of `X² − 5`. It carries the
nonarchimedean local field structure of `TauCeti.finiteExtensionValuativeRel`, which is the
unique one extending that of `ℚ_2`. -/
def DyadicSqrtFive : Type := AdjoinRoot (X ^ 2 - C 5 : ℚ_[2][X])

namespace DyadicSqrtFive

/-- `X² − 5` is irreducible over `ℚ_2`, because `5` is not a square in `ℚ_2`. -/
local instance : Fact (Irreducible (X ^ 2 - C 5 : ℚ_[2][X])) :=
  ⟨X_pow_sub_C_irreducible_of_prime Nat.prime_two fun b hb ↦
    Padic.not_isSquare_five ⟨b, by rw [← hb, sq]⟩⟩

instance : Field DyadicSqrtFive := inferInstanceAs (Field (AdjoinRoot (X ^ 2 - C 5 : ℚ_[2][X])))

instance : Algebra ℚ_[2] DyadicSqrtFive :=
  inferInstanceAs (Algebra ℚ_[2] (AdjoinRoot (X ^ 2 - C 5 : ℚ_[2][X])))

/-- The power basis `1, √5` of `ℚ_2(√5)` over `ℚ_2`. -/
private def powerBasis : PowerBasis ℚ_[2] DyadicSqrtFive :=
  AdjoinRoot.powerBasis (Fact.out : Irreducible (X ^ 2 - C 5 : ℚ_[2][X])).ne_zero

instance : FiniteDimensional ℚ_[2] DyadicSqrtFive := powerBasis.finite

instance : CharZero DyadicSqrtFive :=
  charZero_of_injective_algebraMap (algebraMap ℚ_[2] DyadicSqrtFive).injective

instance : ValuativeRel DyadicSqrtFive := finiteExtensionValuativeRel ℚ_[2] DyadicSqrtFive

instance : TopologicalSpace DyadicSqrtFive :=
  finiteExtensionNormedFieldTopology ℚ_[2] DyadicSqrtFive

instance : ValuativeExtension ℚ_[2] DyadicSqrtFive :=
  finiteExtension_valuativeExtension ℚ_[2] DyadicSqrtFive

instance : IsNonarchimedeanLocalField DyadicSqrtFive :=
  finiteExtension_isNonarchimedeanLocalField ℚ_[2] DyadicSqrtFive

/-- The square root `√5` of `5` in `ℚ_2(√5)`, the class of `X`. -/
def sqrtFive : DyadicSqrtFive := AdjoinRoot.root (X ^ 2 - C 5 : ℚ_[2][X])

/-- The square of `√5` is `5`. -/
@[simp]
theorem sqrtFive_sq : sqrtFive ^ 2 = 5 := by
  have h := AdjoinRoot.eval₂_root (X ^ 2 - C 5 : ℚ_[2][X])
  simp only [eval₂_sub, eval₂_X_pow, eval₂_C] at h
  rw [map_ofNat (AdjoinRoot.of (X ^ 2 - C 5 : ℚ_[2][X])) 5, sub_eq_zero] at h
  exact h

/-- `√5` generates `ℚ_2(√5)` over `ℚ_2`. -/
theorem adjoin_sqrtFive_eq_top : IntermediateField.adjoin ℚ_[2] {sqrtFive} = ⊤ :=
  IntermediateField.adjoin_root_eq_top _

/-- `ℚ_2(√5)` is a quadratic extension of `ℚ_2`. -/
theorem finrank_eq_two : Module.finrank ℚ_[2] DyadicSqrtFive = 2 := by
  rw [powerBasis.finrank, powerBasis, AdjoinRoot.powerBasis_dim, natDegree_X_pow_sub_C]

instance : Algebra.IsQuadraticExtension ℚ_[2] DyadicSqrtFive := ⟨finrank_eq_two⟩

/-- The golden ratio `(1 + √5) / 2`, a root of `X² − X − 1`. -/
private def goldenRatio : DyadicSqrtFive := (1 + sqrtFive) / 2

private theorem goldenRatio_sq : goldenRatio ^ 2 = goldenRatio + 1 := by
  rw [goldenRatio]
  linear_combination sqrtFive_sq / 4

/-- `ℚ_2(√5)/ℚ_2` is unramified: it is generated by the golden ratio `φ`, a root of the integral
polynomial `X² − X − 1` at which the derivative `2φ − 1 = √5` is a unit. -/
instance : IsUnramified ℚ_[2] DyadicSqrtFive := by
  have hint : IsIntegral 𝒪[ℚ_[2]] goldenRatio :=
    ⟨X ^ 2 - X - 1, by monicity!, by simp [goldenRatio_sq]⟩
  let b : 𝒪[DyadicSqrtFive] := ⟨goldenRatio, (Valuation.Integers.isIntegral_iff_valuation_le_one
    (Valuation.integer.integers (valuation ℚ_[2])) _).1 hint⟩
  have hb : (b : DyadicSqrtFive) = goldenRatio := rfl
  refine isUnramified_of_adjoin_eq_top_of_isUnit_aeval_derivative (b := b)
    (p := X ^ 2 - X - 1) ?_ ?_ ?_
  · -- `√5 = 2φ − 1` lies in `ℚ_2(φ)`.
    have hsqrt : sqrtFive = 2 * goldenRatio - 1 := by
      rw [goldenRatio]
      ring
    rw [eq_top_iff, ← adjoin_sqrtFive_eq_top, IntermediateField.adjoin_simple_le_iff, hsqrt]
    exact sub_mem (mul_mem (ofNat_mem _ 2) (IntermediateField.mem_adjoin_simple_self _ _))
      (one_mem _)
  · apply Subtype.ext
    simp [hb, goldenRatio_sq]
  · -- The derivative `2φ − 1` is `√5`, whose square `5` is a unit of `ℤ_2`.
    set u := aeval b (derivative (X ^ 2 - X - 1 : 𝒪[ℚ_[2]][X]))
    have hu : (u : DyadicSqrtFive) = sqrtFive := by
      simp [u, hb, goldenRatio]
      ring
    have h5 : u * u = 5 := by
      apply Subtype.ext
      rw [MulMemClass.coe_mul, hu, ← sq, sqrtFive_sq]
      exact (map_ofNat 𝒪[DyadicSqrtFive].subtype 5).symm
    have h5K : IsUnit (5 : 𝒪[ℚ_[2]]) := by
      simpa using (natCastValuation_eq_zero_iff (K := ℚ_[2]) 5 (by norm_num)).1 (by
        rw [Padic.natCastValuation_eq_padicValNat]
        exact padicValNat.eq_zero_of_not_dvd (by norm_num))
    have h5L : IsUnit (5 : 𝒪[DyadicSqrtFive]) := by
      rw [← map_ofNat (algebraMap 𝒪[ℚ_[2]] 𝒪[DyadicSqrtFive]) 5]
      exact h5K.map _
    exact isUnit_of_mul_isUnit_left (h5 ▸ h5L)

/-- The residue degree of `ℚ_2(√5)/ℚ_2` is `2`. -/
theorem inertiaDegree_eq_two : inertiaDegree ℚ_[2] DyadicSqrtFive = 2 := by
  rw [IsUnramified.inertiaDegree_eq_finrank, finrank_eq_two]

/-- The residue field of `ℚ_2(√5)` has `4` elements. -/
@[simp high] -- Compute the cardinality before `Nat.card_eq_fintype_card` changes its form.
theorem natCard_residueField : Nat.card 𝓀[DyadicSqrtFive] = 4 := by
  rw [TauCeti.natCard_residueField (K := ℚ_[2]), Padic.natCard_residueField, inertiaDegree_eq_two]
  norm_num

/-- The arithmetic Frobenius of `ℚ_2(√5)/ℚ_2` is nontrivial, since its order is the residue
degree `2`. -/
private theorem frobeniusAlgEquiv_ne_one :
    frobeniusAlgEquiv (K := ℚ_[2]) (L := DyadicSqrtFive) ≠ 1 := fun h ↦ by
  have h2 := orderOf_frobeniusAlgEquiv (K := ℚ_[2]) (L := DyadicSqrtFive)
  rw [h, orderOf_one, inertiaDegree_eq_two] at h2
  exact absurd h2 (by norm_num)

/-- The arithmetic Frobenius of `ℚ_2(√5)/ℚ_2` is the conjugation `√5 ↦ −√5`. -/
@[simp]
theorem frobeniusAlgEquiv_sqrtFive :
    frobeniusAlgEquiv (K := ℚ_[2]) (L := DyadicSqrtFive) sqrtFive = -sqrtFive := by
  -- Frobenius is nontrivial, so it does not fix the generator `√5`.
  have hσ := frobeniusAlgEquiv_ne_one
  have hsq :
      frobeniusAlgEquiv (K := ℚ_[2]) (L := DyadicSqrtFive) sqrtFive ^ 2 = sqrtFive ^ 2 := by
    rw [← map_pow, sqrtFive_sq, map_ofNat]
  refine (sq_eq_sq_iff_eq_or_eq_neg.1 hsq).resolve_left fun h ↦ hσ ?_
  exact AlgEquiv.coe_toAlgHom_injective (AdjoinRoot.algHom_ext h)

/-- Every element of `ℚ_2(√5)` is `a + b√5` for some `a b : ℚ_2`. -/
theorem exists_eq_add_mul_sqrtFive (y : DyadicSqrtFive) :
    ∃ a b : ℚ_[2], y = algebraMap ℚ_[2] DyadicSqrtFive a +
      algebraMap ℚ_[2] DyadicSqrtFive b * sqrtFive := by
  -- `√5` lies outside `ℚ_2`, since Frobenius moves it.
  have hθ : sqrtFive ∉ Set.range (algebraMap ℚ_[2] DyadicSqrtFive) := by
    rintro ⟨c, hc⟩
    have h := congrArg (frobeniusAlgEquiv (K := ℚ_[2]) (L := DyadicSqrtFive)) hc
    rw [AlgEquiv.commutes, hc, frobeniusAlgEquiv_sqrtFive, self_eq_neg] at h
    simpa [h] using sqrtFive_sq
  obtain ⟨b, a, rfl⟩ :=
    Algebra.IsQuadraticExtension.exists_eq_algebraMap_add_algebraMap_mul ℚ_[2] DyadicSqrtFive hθ y
  exact ⟨a, b, rfl⟩

/-- **The norm form of `ℚ_2(√5)/ℚ_2`.** The norm of `a + b√5` is `a² − 5b²`. -/
theorem norm_add_mul_sqrtFive (a b : ℚ_[2]) :
    Algebra.norm ℚ_[2] (algebraMap ℚ_[2] DyadicSqrtFive a +
      algebraMap ℚ_[2] DyadicSqrtFive b * sqrtFive) = a ^ 2 - 5 * b ^ 2 := by
  -- The norm is `y σ(y)` for the Frobenius `σ : √5 ↦ −√5`.
  apply (algebraMap ℚ_[2] DyadicSqrtFive).injective
  rw [Algebra.IsQuadraticExtension.algebraMap_norm_eq_mul ℚ_[2] DyadicSqrtFive
    frobeniusAlgEquiv_ne_one]
  simp only [map_add, map_mul, AlgEquiv.commutes,
    frobeniusAlgEquiv_sqrtFive, map_sub, map_pow, map_ofNat]
  linear_combination (-(algebraMap ℚ_[2] DyadicSqrtFive b) ^ 2) * sqrtFive_sq

/-- **The norm group of `ℚ_2(√5)/ℚ_2`.** An element of `ℚ_2ˣ` is a norm from `ℚ_2(√5)` exactly
when its `2`-adic valuation is even. -/
theorem mem_normGroup_iff_even_valuation {x : ℚ_[2]ˣ} :
    x ∈ normGroup ℚ_[2] DyadicSqrtFive ↔ Even (x : ℚ_[2]).valuation := by
  rw [mem_normGroup_iff_dvd_normalizedValuation, inertiaDegree_eq_two,
    Padic.toAdd_normalizedValuation_eq_valuation, Nat.cast_two, even_iff_two_dvd]

/-- **The norm equation of `ℚ_2(√5)/ℚ_2`.** For `x : ℚ_2`, the equation `a² − 5b² = x` has a
solution in `ℚ_2` exactly when the `2`-adic valuation of `x` is even. For `x = 0` both sides hold
trivially, the valuation of `0` being `0`. -/
theorem exists_sq_sub_five_mul_sq_eq_iff {x : ℚ_[2]} :
    (∃ a b : ℚ_[2], a ^ 2 - 5 * b ^ 2 = x) ↔ Even x.valuation := by
  rcases eq_or_ne x 0 with rfl | hx
  · exact iff_of_true ⟨0, 0, by ring⟩ (by simp)
  rw [← Units.val_mk0 hx, ← mem_normGroup_iff_even_valuation, mem_normGroup_iff]
  constructor
  · rintro ⟨a, b, hab⟩
    have hy0 : algebraMap ℚ_[2] DyadicSqrtFive a +
        algebraMap ℚ_[2] DyadicSqrtFive b * sqrtFive ≠ 0 := by
      intro h
      rw [← norm_add_mul_sqrtFive, h, Algebra.norm_zero] at hab
      exact hx hab.symm
    exact ⟨Units.mk0 _ hy0, by rw [Units.val_mk0, norm_add_mul_sqrtFive, hab]⟩
  · rintro ⟨y, hy⟩
    obtain ⟨a, b, hab⟩ := exists_eq_add_mul_sqrtFive (y : DyadicSqrtFive)
    exact ⟨a, b, by rw [← norm_add_mul_sqrtFive, ← hab, hy]⟩

/-- **A solvable norm equation.** `3` is a norm from `ℚ_2(√5)`: the equation `a² − 5b² = 3` has a
solution in `ℚ_2`, because `3` has even valuation `0`. -/
theorem exists_sq_sub_five_mul_sq_eq_three : ∃ a b : ℚ_[2], a ^ 2 - 5 * b ^ 2 = 3 := by
  rw [exists_sq_sub_five_mul_sq_eq_iff, Padic.valuation_ofNat,
    padicValNat.eq_zero_of_not_dvd (by norm_num)]
  simp

/-- **An unsolvable norm equation.** `2` is not a norm from `ℚ_2(√5)`: the equation
`a² − 5b² = 2` has no solution in `ℚ_2`, because `2` has odd valuation. -/
theorem not_exists_sq_sub_five_mul_sq_eq_two : ¬∃ a b : ℚ_[2], a ^ 2 - 5 * b ^ 2 = 2 := by
  rw [exists_sq_sub_five_mul_sq_eq_iff, Padic.valuation_ofNat, padicValNat_self]
  exact Int.not_even_one

end DyadicSqrtFive

end TauCeti
