/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.Basic
public import TauCeti.RepresentationTheory.Homological.ContCohomology.ContinuousCohomologyIso
public import TauCeti.RepresentationTheory.Homological.ContCohomology.Corestriction.Conjugation
public import TauCeti.RepresentationTheory.Homological.ContCohomology.Corestriction.TraceExact
public import TauCeti.RepresentationTheory.Homological.ContCohomology.Torsion

/-!
# Corestriction in the top degree of strict cohomological dimension

Let `G` be a profinite group with `scd_p G ≤ n` and `U` an open subgroup. Then every `p`-primary
class of `Hⁿ(G, M)` is the corestriction of a `p`-primary class of `Hⁿ(U, M)`, for every discrete
`G`-module `M` (the surjectivity half of NSW (3.3.11)). In the class-module theorem for groups of
strict cohomological dimension two, this is what makes the transfer `G^ab(p) → U^ab(p)` injective.

For `U` normal, corestriction is moreover injective on the `p`-primary part of the coinvariants of
`G ⧸ U` (the injectivity half of NSW (3.3.11)): a `p`-primary class of `Hⁿ(U, M)` whose
corestriction vanishes lies in the subgroup generated by the differences `(g)_* w - w` of
`p`-primary classes `w`, where `(g)_*` is the conjugation
`TauCeti.ContinuousCohomology.conjNormalMap`. NSW state (3.3.11) as an isomorphism
`Hⁿ(U, M)(p)_{G ⧸ U} ≅ Hⁿ(G, M)(p)` induced by corestriction; its injectivity half is stated here
as this description of the kernel, which avoids forming the coinvariants. Both halves hold in every
degree `n`, including `n = 0`, and only need `n` to bound the strict cohomological dimension at `p`.

## Main results

* `TauCeti.StrictCohomologicalDimensionLE.corestriction_surjOn_primaryComponent`: under
  `StrictCohomologicalDimensionLE p G n`, corestriction maps the `p`-primary component of
  `Hⁿ(U, M)` onto that of `Hⁿ(G, M)`.
* `TauCeti.corestriction_surjOn_primaryComponent_of_strictCohomologicalDimensionAt_le`: the same
  statement under `scd_p G ≤ n`.
* `TauCeti.StrictCohomologicalDimensionLE.corestriction_ker_primaryComponent`: under
  `StrictCohomologicalDimensionLE p G n` and for `U` normal, a `p`-primary class of `Hⁿ(U, M)` with
  trivial corestriction lies in the subgroup generated by the `(g)_* w - w`.
* `TauCeti.corestriction_ker_primaryComponent_of_strictCohomologicalDimensionAt_le`: the same
  statement under `scd_p G ≤ n`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (3.3.11).
-/

public section

namespace TauCeti

open CategoryTheory ContCohomology _root_.TauCeti.ContinuousCohomology

universe u

variable {p : ℕ} {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G] {U : Subgroup G} [U.FiniteIndex]

/-- Under `StrictCohomologicalDimensionLE p G n`, every `p`-primary class of `Hⁿ(G, M)` is a
corestriction from an open subgroup, of a class that need not be `p`-primary. -/
private theorem StrictCohomologicalDimensionLE.exists_corestriction_eq {n : ℕ}
    (h : StrictCohomologicalDimensionLE.{u} p G n) (hU : IsOpen (U : Set G)) (M : Type u)
    [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M] [DistribMulAction G M]
    [ContinuousSMul G M] {x : continuousCohomology n (ofDiscreteModule ℤ G M)}
    (hx : x ∈ AddCommGroup.primaryComponent _ p) :
    ∃ y, corestriction U M hU n y = x := by
  -- the image of corestriction is the kernel of the trace connecting map
  -- (`exact_corestriction_delta`), which sends `x` into `Hⁿ⁺¹(G, traceKer G U M)(p) = 0`
  refine ((exact_corestriction_delta U M hU n) x).1 ?_
  obtain ⟨k, hk⟩ := hx
  have hδ : (DiscreteCoind.traceShortExact G U M hU).delta n x ∈
      AddCommGroup.primaryComponent _ p :=
    ⟨k, by rw [← map_nsmul, hk, _root_.map_zero]⟩
  rwa [strictCohomologicalDimensionLE_iff.1 h _ (n + 1) n.lt_succ_self,
    AddSubgroup.mem_bot] at hδ

/-- **Corestriction in the top degree of strict cohomological dimension** (NSW (3.3.11),
surjectivity). For a profinite group `G` with `StrictCohomologicalDimensionLE p G n`, a prime `p`
and an open subgroup `U`, every `p`-primary class of `Hⁿ(G, M)` is the corestriction of a
`p`-primary class of `Hⁿ(U, M)`, for every discrete `G`-module `M`. -/
theorem StrictCohomologicalDimensionLE.corestriction_surjOn_primaryComponent (hp : p.Prime)
    {n : ℕ} (h : StrictCohomologicalDimensionLE.{u} p G n) (hU : IsOpen (U : Set G)) (M : Type u)
    [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M] [DistribMulAction G M]
    [ContinuousSMul G M] :
    Set.SurjOn (corestriction U M hU n)
      (AddCommGroup.primaryComponent (continuousCohomology n (ofDiscreteModule ℤ U M)) p)
      (AddCommGroup.primaryComponent (continuousCohomology n (ofDiscreteModule ℤ G M)) p) := by
  intro x hx
  have : CompactSpace U := isCompact_iff_compactSpace.mp (U.isClosed_of_isOpen hU).isCompact
  cases n with
  | succ n =>
    -- `Hⁿ⁺¹(U, M)` is torsion, so a preimage of `x` can be replaced by a `p`-primary one
    obtain ⟨y, rfl⟩ := h.exists_corestriction_eq hU M hx
    exact exists_mem_primaryComponent_apply_eq (corestriction U M hU (n + 1)).hom hp
      (isAddTorsion_continuousCohomology n y) hx
  | zero =>
    -- `x` comes from `H⁰(G, M[p ^ k])`, whose classes are corestrictions of classes killed by
    -- `p ^ k`; corestriction is natural in the coefficients `M[p ^ k] → M`
    obtain ⟨k, hk⟩ := hx
    set K := (nsmulAddMonoidHom (p ^ k) : M →+ M).ker
    have hK : ∀ g : G, ∀ m ∈ K, g • m ∈ K := fun g m hm ↦ by
      rw [AddMonoidHom.mem_ker, nsmulAddMonoidHom_apply] at hm ⊢
      rw [smul_comm, hm, smul_zero]
    let := K.restrictDistribMulAction hK
    have : ContinuousSMul G K := K.restrictDistribMulAction_continuousSMul hK
    let ι : K →+[G] M :=
      { K.subtype with map_smul' := K.restrictDistribMulAction_coe_smul hK }
    have hKk (v : K) : p ^ k • v = 0 := Subtype.ext (AddMonoidHom.mem_ker.1 v.2)
    obtain ⟨z, rfl⟩ := exists_coeffMap_ker_nsmul_eq M hK hk
    obtain ⟨y, rfl⟩ := h.exists_corestriction_eq hU K
      ⟨k, nsmul_continuousCohomology_eq_zero (X := ofDiscreteModule ℤ G K) hKk 0 z⟩
    refine ⟨coeffMap (ofDiscreteModuleMap (G := U) ι.toAddMonoidHom.toIntLinearMap
      fun u m ↦ _root_.map_smul ι (u : G) m) 0 y, ⟨k, ?_⟩, ?_⟩
    · rw [← map_nsmul, nsmul_continuousCohomology_eq_zero (X := ofDiscreteModule ℤ U K) hKk 0 y,
        _root_.map_zero]
    · exact (ConcreteCategory.congr_hom (corestriction_naturality U K hU ι 0) y).symm

/-- **Corestriction in the top degree of strict cohomological dimension** (NSW (3.3.11),
surjectivity), stated through `scd_p G ≤ n`: for an open subgroup `U` of a profinite group `G`,
corestriction maps the `p`-primary component of `Hⁿ(U, M)` onto that of `Hⁿ(G, M)`. -/
theorem corestriction_surjOn_primaryComponent_of_strictCohomologicalDimensionAt_le (hp : p.Prime)
    {n : ℕ} (h : strictCohomologicalDimensionAt.{u} p G ≤ n) (hU : IsOpen (U : Set G)) (M : Type u)
    [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M] [DistribMulAction G M]
    [ContinuousSMul G M] :
    Set.SurjOn (corestriction U M hU n)
      (AddCommGroup.primaryComponent (continuousCohomology n (ofDiscreteModule ℤ U M)) p)
      (AddCommGroup.primaryComponent (continuousCohomology n (ofDiscreteModule ℤ G M)) p) :=
  ((strictCohomologicalDimensionAt_le_iff p G n).1 h).corestriction_surjOn_primaryComponent hp hU M

/-! ### Injectivity on the coinvariants -/

section Ker

attribute [local instance] Subgroup.fintypeQuotientOfFiniteIndex

variable [U.Normal]

/- Proof outline (NSW (3.3.11)). Under Shapiro's isomorphism a class of `Hⁿ(U, M)` with trivial
corestriction is a class of `Hⁿ(G, Coind_U^G M)` killed by the trace, so it comes from the kernel
of the trace (`TauCeti.DiscreteCoind.traceShortExact`). That kernel is covered by
`∏_{G ⧸ U} Coind_U^G M` through the differences `conj σ - 1`
(`TauCeti.DiscreteCoind.traceKerCoverShortExact`), and the vanishing of the `p`-primary part of
`Hⁿ⁺¹(G, -)` makes the cover surjective on `p`-primary parts of `Hⁿ(G, -)`; Shapiro's map carries
the coefficient map of `conj σ` to `(σ)_*`
(`TauCeti.ContinuousCohomology.shapiroMap_comp_conjNormalMap`). In positive degree the groups are
torsion, so `p`-primary preimages can be chosen (`TauCeti.exists_mem_primaryComponent_apply_eq`);
in degree zero the class is first lifted to the `p ^ k`-torsion submodule of `M`, whose cohomology
is killed by `p ^ k`. -/

/-- The subgroup of `Hⁿ(U, M)` generated by the differences `(g)_* w - w` of `p`-primary classes
`w`, the conjugation `(g)_*` being `TauCeti.ContinuousCohomology.conjNormalMap`. -/
private noncomputable abbrev conjDiffClosure (p : ℕ) (U : Subgroup G) [U.Normal] (M : Type u)
    [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M] [DistribMulAction G M] (n : ℕ) :
    AddSubgroup (continuousCohomology n (ofDiscreteModule ℤ U M)) :=
  AddSubgroup.closure {z | ∃ (g : G) (w : continuousCohomology n (ofDiscreteModule ℤ U M)),
    w ∈ AddCommGroup.primaryComponent (continuousCohomology n (ofDiscreteModule ℤ U M)) p ∧
      z = conjNormalMap U M g n w - w}

section Core

variable (M : Type u) [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M]
  [DistribMulAction G M] [ContinuousSMul G M] (hU : IsOpen (U : Set G))

omit [TotallyDisconnectedSpace G] in
/-- **The cover on cohomology**: the coefficient map of the cover of the kernel of the trace,
followed by Shapiro's map, is the sum over `σ ∈ G ⧸ U` of `(σ.out⁻¹)_* - 1` on the Shapiro images
of the components. -/
private theorem shapiroMap_coeffMap_traceKerCover (n : ℕ)
    (a : continuousCohomology n (ofDiscreteModule ℤ G (G ⧸ U → DiscreteCoind G U M))) :
    shapiroMap U M n
        (coeffMap (ofDiscreteModuleMap (DiscreteCoind.traceShortExact G U M hU).incl.toIntLinearMap
          (DiscreteCoind.traceShortExact G U M hU).incl_equivariant) n
        (coeffMap (ofDiscreteModuleMap
          (DiscreteCoind.traceKerCoverShortExact U M hU).proj.toIntLinearMap
          (DiscreteCoind.traceKerCoverShortExact U M hU).proj_equivariant) n a)) =
      ∑ x : G ⧸ U, (conjNormalMap U M x.out⁻¹ n (shapiroMap U M n (coeffMap
          (ofDiscreteModuleMap (Pi.evalAddMonoidHom (fun _ => DiscreteCoind G U M) x).toIntLinearMap
            fun _ _ => rfl) n a)) -
        shapiroMap U M n (coeffMap
          (ofDiscreteModuleMap (Pi.evalAddMonoidHom (fun _ => DiscreteCoind G U M) x).toIntLinearMap
            fun _ _ => rfl) n a)) := by
  let ev (x : G ⧸ U) : ofDiscreteModule ℤ G (G ⧸ U → DiscreteCoind G U M) ⟶
      ofDiscreteModule ℤ G (DiscreteCoind G U M) :=
    ofDiscreteModuleMap (Pi.evalAddMonoidHom (fun _ => DiscreteCoind G U M) x).toIntLinearMap
      fun _ _ => rfl
  let cj (x : G ⧸ U) : ofDiscreteModule ℤ G (DiscreteCoind G U M) ⟶
      ofDiscreteModule ℤ G (DiscreteCoind G U M) :=
    ofDiscreteModuleMap (DiscreteCoind.conj U U M x.out⁻¹
        (show U.map (MulAut.conj x.out⁻¹).toMonoidHom = U from
          Subgroup.Normal.map_conj_eq U _).ge).toAddMonoidHom.toIntLinearMap
      fun h F => _root_.map_smul (DiscreteCoind.conj U U M x.out⁻¹
        (show U.map (MulAut.conj x.out⁻¹).toMonoidHom = U from
          Subgroup.Normal.map_conj_eq U _).ge) h F
  let π₂ := ofDiscreteModuleMap (DiscreteCoind.traceKerCoverShortExact U M hU).proj.toIntLinearMap
    (DiscreteCoind.traceKerCoverShortExact U M hU).proj_equivariant
  let ι₁ := ofDiscreteModuleMap (DiscreteCoind.traceShortExact G U M hU).incl.toIntLinearMap
    (DiscreteCoind.traceShortExact G U M hU).incl_equivariant
  -- On coefficients, the cover followed by the inclusion of the kernel of the trace is the sum of
  -- the components followed by `conj σ - 1`.
  have hmor : π₂ ≫ ι₁ = ∑ x : G ⧸ U, (ev x ≫ cj x - ev x) := by
    refine TopRep.hom_ext (DFunLike.ext _ _ fun (φ : G ⧸ U → DiscreteCoind G U M) => ?_)
    -- Evaluation at `φ` is additive in the morphism.
    let E : (ofDiscreteModule ℤ G (G ⧸ U → DiscreteCoind G U M) ⟶
        ofDiscreteModule ℤ G (DiscreteCoind G U M)) →+ DiscreteCoind G U M :=
      AddMonoidHom.mk' (fun f => f.hom φ) fun _ _ => rfl
    have h₁ : (π₂ ≫ ι₁).hom φ = DiscreteCoind.traceKerCover U M φ := by
      rw [← DiscreteCoind.traceKerCoverShortExact_proj_apply U M hU φ]
      -- `ofDiscreteModuleMap` evaluates as its underlying map (`ofDiscreteModuleMap_hom_apply`,
      -- which holds by `rfl`), here the inclusion of the kernel of the trace.
      exact (TopRep.comp_apply π₂ ι₁ φ).trans (by
        simp only [π₂, ι₁, DiscreteCoind.traceShortExact_incl]
        rfl)
    have h₂ (x : G ⧸ U) : E (ev x ≫ cj x - ev x) =
        DiscreteCoind.conj U U M x.out⁻¹ (show U.map (MulAut.conj x.out⁻¹).toMonoidHom = U from
          Subgroup.Normal.map_conj_eq U _).ge (φ x) - φ x := by
      rw [_root_.map_sub]
      -- As above, `ev x` and `cj x` evaluate as evaluation at `x` and conjugation, by `rfl`.
      exact congrArg₂ (· - ·) (TopRep.comp_apply (ev x) (cj x) φ) rfl
    exact h₁.trans ((DiscreteCoind.traceKerCover_apply U M φ).trans
      ((Finset.sum_congr rfl fun x _ => (h₂ x).symm).trans (map_sum E _ Finset.univ).symm))
  have hcoeff : coeffMap π₂ n ≫ coeffMap ι₁ n =
      ∑ x : G ⧸ U, (coeffMap (ev x) n ≫ coeffMap (cj x) n - coeffMap (ev x) n) := by
    have h := congrArg (continuousCohomologyFunctor ℤ G n).map hmor
    simp only [Functor.map_comp, Functor.map_sum, Functor.map_sub] at h
    simp only [continuousCohomologyFunctor_map] at h
    exact h
  -- Read the two coefficient maps as one composite (`ConcreteCategory.comp_apply`, by `rfl`), so
  -- that `hcoeff` rewrites it.
  change shapiroMap U M n ((coeffMap π₂ n ≫ coeffMap ι₁ n) a) = _
  rw [hcoeff]
  -- Evaluation at `a` is additive in the morphism.
  let E : (continuousCohomology n (ofDiscreteModule ℤ G (G ⧸ U → DiscreteCoind G U M)) ⟶
      continuousCohomology n (ofDiscreteModule ℤ G (DiscreteCoind G U M))) →+
      continuousCohomology n (ofDiscreteModule ℤ G (DiscreteCoind G U M)) :=
    AddMonoidHom.mk' (fun f => f a) fun _ _ => rfl
  rw [show (∑ x : G ⧸ U, (coeffMap (ev x) n ≫ coeffMap (cj x) n - coeffMap (ev x) n)) a =
    E (∑ x : G ⧸ U, (coeffMap (ev x) n ≫ coeffMap (cj x) n - coeffMap (ev x) n)) from rfl,
    map_sum, _root_.map_sum]
  refine Finset.sum_congr rfl fun x _ => ?_
  rw [_root_.map_sub, _root_.map_sub]
  congr 1
  exact (ConcreteCategory.congr_hom (shapiroMap_comp_conjNormalMap U M x.out⁻¹ n)
    (coeffMap (ev x) n a)).symm

/-- **The core of NSW (3.3.11), injectivity**, under the hypothesis that `p`-primary preimages
can be chosen along the two short exact sequences, that is, that `Hⁿ` of the kernel of the trace
and of its cover is torsion. -/
private theorem mem_conjDiffClosure_of_isAddTorsion (hp : p.Prime) {n : ℕ}
    (h : StrictCohomologicalDimensionLE.{u} p G n)
    (hB : IsAddTorsion
      (continuousCohomology n (ofDiscreteModule ℤ G (DiscreteCoind.traceKer G U M))))
    (hP : IsAddTorsion
      (continuousCohomology n (ofDiscreteModule ℤ G (G ⧸ U → DiscreteCoind G U M))))
    {y : continuousCohomology n (ofDiscreteModule ℤ U M)}
    (hy : y ∈ AddCommGroup.primaryComponent _ p) (hcor : corestriction U M hU n y = 0) :
    y ∈ conjDiffClosure p U M n := by
  let S₁ := DiscreteCoind.traceShortExact G U M hU
  let S₂ := DiscreteCoind.traceKerCoverShortExact U M hU
  let e := shapiroIso U (U.isClosed_of_isOpen hU) M n
  -- The Shapiro preimage `c` of `y` is `p`-primary and killed by the trace.
  let c := e.inv y
  have hc : shapiroMap U M n c = y := by
    rw [← shapiroIso_hom U (U.isClosed_of_isOpen hU) M n]
    exact e.inv_hom_id_apply y
  obtain ⟨k, hk⟩ := hy
  have hcp : c ∈ AddCommGroup.primaryComponent _ p :=
    ⟨k, by rw [← map_nsmul, hk, _root_.map_zero]⟩
  have hτ : ofDiscreteModuleMap S₁.proj.toIntLinearMap S₁.proj_equivariant =
      ofDiscreteModuleMap (DiscreteCoind.trace G U M).toAddMonoidHom.toIntLinearMap
        fun g f => _root_.map_smul (DiscreteCoind.trace G U M) g f := by
    simp only [S₁, DiscreteCoind.traceShortExact_proj]
  have htr : coeffMap (ofDiscreteModuleMap S₁.proj.toIntLinearMap S₁.proj_equivariant) n c = 0 := by
    rw [hτ]
    exact (ConcreteCategory.congr_hom (corestriction_def U M hU n) y).symm.trans hcor
  -- So `c` comes from a `p`-primary class `b` of the kernel of the trace.
  obtain ⟨b₀, hb₀⟩ := (S₁.longExact_exact₂ n c).1 htr
  obtain ⟨b, hbp, hbb⟩ := exists_mem_primaryComponent_apply_eq
    (coeffMap (ofDiscreteModuleMap S₁.incl.toIntLinearMap S₁.incl_equivariant) n).hom hp (hB b₀)
    (hb₀ ▸ hcp)
  -- Its connecting image is `p`-primary in degree `n + 1`, hence zero, so `b` comes from a
  -- `p`-primary class `a` of the cover.
  have hδ : S₂.delta n b = 0 := by
    obtain ⟨j, hj⟩ := hbp
    have hδp : S₂.delta n b ∈ AddCommGroup.primaryComponent _ p :=
      ⟨j, by rw [← map_nsmul, hj, _root_.map_zero]⟩
    rwa [strictCohomologicalDimensionLE_iff.1 h _ (n + 1) n.lt_succ_self,
      AddSubgroup.mem_bot] at hδp
  obtain ⟨a₀, ha₀⟩ := (S₂.longExact_exact₃ n b).1 hδ
  obtain ⟨a, hap, haa⟩ := exists_mem_primaryComponent_apply_eq
    (coeffMap (ofDiscreteModuleMap S₂.proj.toIntLinearMap S₂.proj_equivariant) n).hom hp (hP a₀)
    (ha₀ ▸ hbp)
  -- Then `y` is the sum of the differences `(σ)_* w - w` of the Shapiro images of the components.
  have hy' := shapiroMap_coeffMap_traceKerCover M hU n a
  rw [haa, ha₀, hbb, hb₀, hc] at hy'
  rw [hy']
  refine AddSubgroup.sum_mem _ fun x _ => AddSubgroup.subset_closure ⟨x.out⁻¹, _, ?_, rfl⟩
  obtain ⟨j, hj⟩ := hap
  exact ⟨j, by rw [← map_nsmul, ← map_nsmul, hj, _root_.map_zero, _root_.map_zero]⟩

end Core

/-- **Corestriction in the top degree of strict cohomological dimension is injective on the
coinvariants** (NSW (3.3.11), injectivity). For a profinite group `G` with
`StrictCohomologicalDimensionLE p G n`, a prime `p` and an open normal subgroup `U`, a `p`-primary
class of `Hⁿ(U, M)` whose corestriction to `Hⁿ(G, M)` vanishes lies in the subgroup generated by
the differences `(g)_* w - w` of `p`-primary classes `w ∈ Hⁿ(U, M)`, for every discrete
`G`-module `M`. -/
theorem StrictCohomologicalDimensionLE.corestriction_ker_primaryComponent (hp : p.Prime)
    {n : ℕ} (h : StrictCohomologicalDimensionLE.{u} p G n) (hU : IsOpen (U : Set G))
    (M : Type u) [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M]
    [DistribMulAction G M] [ContinuousSMul G M]
    {y : continuousCohomology n (ofDiscreteModule ℤ U M)}
    (hy : y ∈ AddCommGroup.primaryComponent _ p) (hcor : corestriction U M hU n y = 0) :
    y ∈ AddSubgroup.closure {z | ∃ (g : G) (w : continuousCohomology n (ofDiscreteModule ℤ U M)),
      w ∈ AddCommGroup.primaryComponent (continuousCohomology n (ofDiscreteModule ℤ U M)) p ∧
        z = conjNormalMap U M g n w - w} := by
  cases n with
  | succ n =>
    exact mem_conjDiffClosure_of_isAddTorsion M hU hp h (isAddTorsion_continuousCohomology n)
      (isAddTorsion_continuousCohomology n) hy hcor
  | zero =>
    -- Lift `y` to a class `z` of the `p ^ k`-torsion submodule `K` of `M`, whose cohomology is
    -- killed by `p ^ k`, so that the core applies to `K`.
    obtain ⟨k, hk⟩ := hy
    set K := (nsmulAddMonoidHom (p ^ k) : M →+ M).ker
    have hK : ∀ g : G, ∀ m ∈ K, g • m ∈ K := fun g m hm ↦ by
      rw [AddMonoidHom.mem_ker, nsmulAddMonoidHom_apply] at hm ⊢
      rw [smul_comm, hm, smul_zero]
    let := K.restrictDistribMulAction hK
    have : ContinuousSMul G K := K.restrictDistribMulAction_continuousSMul hK
    let ι : K →+[G] M :=
      { K.subtype with map_smul' := K.restrictDistribMulAction_coe_smul hK }
    have hKk (v : K) : p ^ k • v = 0 := Subtype.ext (AddMonoidHom.mem_ker.1 v.2)
    have hpk : 0 < p ^ k := pow_pos hp.pos k
    let ιV := coeffMap (ofDiscreteModuleMap (G := U) ι.toAddMonoidHom.toIntLinearMap
      fun v m ↦ _root_.map_smul ι (v : G) m) 0
    obtain ⟨z, rfl⟩ : ∃ z, ιV z = y := exists_coeffMap_ker_nsmul_eq (G := U) M
      (fun v m hm ↦ hK v m hm) hk
    -- The corestriction of `z` vanishes, the coefficient map of `K → M` being injective on `H⁰`.
    have hcorz : corestriction U K hU 0 z = 0 :=
      coeffMap_zero_injective ι Subtype.val_injective <|
        ((ConcreteCategory.congr_hom (corestriction_naturality U K hU ι 0) z).trans hcor).trans
          (_root_.map_zero _).symm
    have hB : IsAddTorsion (continuousCohomology 0
        (ofDiscreteModule ℤ G (DiscreteCoind.traceKer G U K))) := fun x ↦
      isOfFinAddOrder_iff_nsmul_eq_zero.2 ⟨p ^ k, hpk, nsmul_continuousCohomology_eq_zero
        (fun b : DiscreteCoind.traceKer G U K ↦ Subtype.ext (DiscreteCoind.nsmul_eq_zero hKk b.1))
        0 x⟩
    have hP : IsAddTorsion (continuousCohomology 0
        (ofDiscreteModule ℤ G (G ⧸ U → DiscreteCoind G U K))) := fun x ↦
      isOfFinAddOrder_iff_nsmul_eq_zero.2 ⟨p ^ k, hpk, nsmul_continuousCohomology_eq_zero
        (fun φ : G ⧸ U → DiscreteCoind G U K ↦ funext fun q ↦ DiscreteCoind.nsmul_eq_zero hKk (φ q))
        0 x⟩
    have hz := mem_conjDiffClosure_of_isAddTorsion K hU hp h hB hP
      ⟨k, nsmul_continuousCohomology_eq_zero (X := ofDiscreteModule ℤ U K) hKk 0 z⟩ hcorz
    -- The coefficient map of `K → M` carries the differences `(g)_* w - w` to differences.
    have hmem (x : continuousCohomology 0 (ofDiscreteModule ℤ U K))
        (hx : ∃ (g : G) (w : continuousCohomology 0 (ofDiscreteModule ℤ U K)),
          w ∈ AddCommGroup.primaryComponent (continuousCohomology 0 (ofDiscreteModule ℤ U K)) p ∧
            x = conjNormalMap U K g 0 w - w) :
        ιV x ∈ conjDiffClosure p U M 0 := by
      obtain ⟨g, w, ⟨j, hj⟩, rfl⟩ := hx
      refine AddSubgroup.subset_closure ⟨g, ιV w, ⟨j, by rw [← map_nsmul, hj, _root_.map_zero]⟩, ?_⟩
      rw [_root_.map_sub]
      exact congrArg (· - ιV w)
        (ConcreteCategory.congr_hom (conjNormalMap_naturality U K M ι g 0) w)
    exact AddSubgroup.closure_induction (p := fun z _ ↦ ιV z ∈ conjDiffClosure p U M 0)
      (fun x hx ↦ hmem x hx) (by rw [_root_.map_zero]; exact zero_mem _)
      (fun x x' _ _ hx hx' ↦ by rw [_root_.map_add]; exact add_mem hx hx')
      (fun x _ hx ↦ by rw [_root_.map_neg]; exact neg_mem hx) hz

/-- **Corestriction in the top degree of strict cohomological dimension is injective on the
coinvariants** (NSW (3.3.11), injectivity), stated through `scd_p G ≤ n`: for an open normal
subgroup `U` of a profinite group `G`, a `p`-primary class of `Hⁿ(U, M)` with trivial
corestriction lies in the subgroup generated by the differences `(g)_* w - w` of `p`-primary
classes. -/
theorem corestriction_ker_primaryComponent_of_strictCohomologicalDimensionAt_le (hp : p.Prime)
    {n : ℕ} (h : strictCohomologicalDimensionAt.{u} p G ≤ n) (hU : IsOpen (U : Set G))
    (M : Type u) [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M]
    [DistribMulAction G M] [ContinuousSMul G M]
    {y : continuousCohomology n (ofDiscreteModule ℤ U M)}
    (hy : y ∈ AddCommGroup.primaryComponent _ p) (hcor : corestriction U M hU n y = 0) :
    y ∈ AddSubgroup.closure {z | ∃ (g : G) (w : continuousCohomology n (ofDiscreteModule ℤ U M)),
      w ∈ AddCommGroup.primaryComponent (continuousCohomology n (ofDiscreteModule ℤ U M)) p ∧
        z = conjNormalMap U M g n w - w} :=
  ((strictCohomologicalDimensionAt_le_iff p G n).1 h).corestriction_ker_primaryComponent hp hU M
    hy hcor

end Ker

end TauCeti
