/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClosedSubgroup
public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.Strict
public import TauCeti.RepresentationTheory.Homological.ContCohomology.Torsion
public import TauCeti.Topology.Algebra.Group.OpenSubgroup.FiniteIndex

/-!
# The strict cohomological dimension through integral coefficients

Let `G` be a profinite group and `p` a prime. Then `scd_p G ≤ n` if and only if `cd_p G ≤ n` and
the `p`-primary component of `Hⁿ⁺¹(U, ℤ)` vanishes for every open subgroup `U`, the integers
carrying the trivial action (NSW (3.3.4)). NSW states the criterion as "if `cd_p G = n` is finite,
then `scd_p G = n` if and only if …"; the inequality form below holds for every `n`.

The forward direction is `cd_p G ≤ scd_p G` together with `scd_p U ≤ scd_p G` for the closed
subgroup `U`, read on the trivial module `ℤ` through
`TauCeti.StrictCohomologicalDimensionLE.primaryComponent_eq_bot_of_isSmoothDiscrete`. For the
converse, `scd_p G ≤ cd_p G + 1` disposes of every degree above `n + 1`, and the work is in degree
`n + 1`, where the `p`-primary component of `Hⁿ⁺¹(G, M)` has to vanish for every discrete
`G`-module `M`.

* **Exactness on `p`-primary components.** For a short exact sequence `0 → A → B → C → 0` of
  discrete modules over a compact group, cohomology in positive degree is torsion, and a `p`-primary
  class in the image of a map of torsion groups has a `p`-primary preimage
  (`TauCeti.exists_mem_primaryComponent_apply_eq`). So the long exact sequence stays exact on
  `p`-primary components: if those of `Hⁱ(G, A)` and `Hⁱ(G, C)` vanish, so does that of `Hⁱ(G, B)`,
  and if those of `Hⁱ(G, B)` and `Hⁱ⁺¹(G, A)` vanish, so does that of `Hⁱ(G, C)`
  (`TauCeti.ContCohomology.DiscreteShortExact.primaryComponent_middle_eq_bot` and
  `TauCeti.ContCohomology.DiscreteShortExact.primaryComponent_right_eq_bot`).
* **Cyclic modules.** A discrete `G`-module `Q` generated by the orbit of one element `q` is a
  quotient of `Coind_U^G ℤ` for the stabilizer `U` of `q`, by the trace of the coinduction of the
  map `ℤ → Q`, `1 ↦ q`. Shapiro's lemma identifies `Hⁿ⁺¹(G, Coind_U^G ℤ)` with `Hⁿ⁺¹(U, ℤ)`, and
  `Hⁿ⁺²` of the kernel has vanishing `p`-primary component because `scd_p G ≤ n + 1`.
* **Finitely generated modules.** A module generated by the orbits of finitely many elements is an
  extension of a cyclic module by a module generated by fewer orbits.
* **All modules.** Every class of `Hⁿ⁺¹(G, M)` comes from a submodule generated by the orbits of
  the finitely many values of a representing cocycle
  (`TauCeti.ContinuousCohomology.exists_finite_forall_mem_range_coeffMap`).

## Main results

* `TauCeti.CohomologicalDimensionLE.strictCohomologicalDimensionLE_of_forall_openSubgroup`: the
  converse direction, as vanishing predicates.
* `TauCeti.strictCohomologicalDimensionLE_iff_forall_openSubgroup`,
  `TauCeti.strictCohomologicalDimensionAt_le_iff_forall_openSubgroup`: **the criterion**,
  `scd_p G ≤ n ↔ cd_p G ≤ n ∧ ∀ U open, Hⁿ⁺¹(U, ℤ)(p) = 0`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (3.3.4) and its
  proof.
-/

public section

open CategoryTheory

universe u

namespace TauCeti

open ContCohomology _root_.ContinuousCohomology _root_.TauCeti.ContinuousCohomology

variable {p : ℕ} {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G] {n : ℕ}

attribute [local instance] TopRep.distribMulAction TopRep.smulCommClass
  Subgroup.fintypeQuotientOfFiniteIndex

/-! ### Cyclic modules -/

section Cyclic

variable (hp : p.Prime) (hs : StrictCohomologicalDimensionLE.{u} p G (n + 1))
include hp hs

/-- The cyclic case, with the trivial `U`-module `ℤ` abstracted to a smooth discrete object `Z`
with trivial action and an additive identification `e : Z ≃+ ℤ`: if `U` is an open subgroup fixing
`q`, whose orbit generates `Q`, and the `p`-primary component of `Hⁿ⁺¹(U, Z)` vanishes, then so
does that of `Hⁿ⁺¹(G, Q)`. The module `Q` is the quotient of `Coind_U^G Z` by the trace of the map
`Z → Q`, `a ↦ e a • q`. -/
private theorem primaryComponent_eq_bot_of_cyclic_aux (U : OpenSubgroup G)
    (Z : TopRep.{u} ℤ (U : Subgroup G)) (hZs : IsSmoothDiscrete ℤ Z)
    (hZtriv : ∀ (u : (U : Subgroup G)) (a : Z.V), Z.ρ u a = a) (e : Z.V ≃+ ℤ)
    (hZ : AddCommGroup.primaryComponent (continuousCohomology (n + 1) Z) p = ⊥)
    (Q : Type u) [AddCommGroup Q] [TopologicalSpace Q] [DiscreteTopology Q] [DistribMulAction G Q]
    (q : Q) (hqU : ∀ u : (U : Subgroup G), (u : G) • q = q)
    (hq : ∀ x : Q, x ∈ AddSubgroup.closure (Set.range fun g : G ↦ g • q)) :
    AddCommGroup.primaryComponent
      (continuousCohomology (n + 1) (ofDiscreteModule ℤ G Q)) p = ⊥ := by
  have := hZs.discreteTopology
  have : ContinuousSMul (U : Subgroup G) Z.V := (isSmoothDiscrete_iff_continuousSMul Z).1 hZs
  -- the `U`-equivariant map `ψ : Z → Q`, `a ↦ e a • q`, and its coinduction followed by the trace
  let ψ : Z.V →ₗ[ℤ] Q := ((zmultiplesHom Q q).comp e.toAddMonoidHom).toIntLinearMap
  have hψ (u : (U : Subgroup G)) (a : Z.V) : ψ (u • a) = u • ψ a := by
    rw [TopRep.distribMulAction_smul, hZtriv, Subgroup.smul_def]
    simp [ψ, smul_comm (u : G) (e a) q, hqU]
  let θ : DiscreteCoind G U Z.V →+ Q :=
    (DiscreteCoind.trace G U Q).toAddMonoidHom.comp (DiscreteCoind.map ψ hψ).toAddMonoidHom
  have hθ (g : G) (f : DiscreteCoind G U Z.V) : θ (g • f) = g • θ f := by
    simp only [θ, AddMonoidHom.comp_apply, LinearMap.toAddMonoidHom_coe, DiscreteCoind.map_smul]
    exact _root_.map_smul (DiscreteCoind.trace G U Q) g _
  -- `θ` sends the coinduced function supported on `U` with value `e⁻¹ 1` to `q`
  have hθq : θ (DiscreteCoind.single G U Z.V U.isOpen 1 (e.symm 1)) = q := by
    refine (DiscreteCoind.trace_map_single U.isOpen ψ hψ 1 (e.symm 1)).trans ?_
    simp [ψ]
  have hθsurj : Function.Surjective θ := fun x ↦ by
    have hle : AddSubgroup.closure (Set.range fun g : G ↦ g • q) ≤ θ.range := by
      rw [AddSubgroup.closure_le]
      rintro _ ⟨g, rfl⟩
      exact ⟨g • DiscreteCoind.single G U Z.V U.isOpen 1 (e.symm 1), by rw [hθ, hθq]⟩
    exact hle (hq x)
  -- the short exact sequence `0 → ker θ → Coind_U^G Z → Q → 0`
  have hK (g : G) (f : DiscreteCoind G U Z.V) (hf : f ∈ θ.ker) : g • f ∈ θ.ker := by
    rw [AddMonoidHom.mem_ker] at hf ⊢
    rw [hθ, hf, smul_zero]
  let := θ.ker.restrictDistribMulAction hK
  have : ContinuousSMul G θ.ker := θ.ker.restrictDistribMulAction_continuousSMul hK
  let S : DiscreteShortExact G θ.ker (DiscreteCoind G U Z.V) Q :=
    { incl := θ.ker.subtype
      proj := θ
      incl_equivariant := θ.ker.restrictDistribMulAction_coe_smul hK
      proj_equivariant := hθ
      incl_injective := θ.ker.subtype_injective
      proj_surjective := hθsurj
      exact := fun f ↦ ⟨fun hf ↦ ⟨⟨f, hf⟩, rfl⟩, fun ⟨a, ha⟩ ↦ ha ▸ a.2⟩ }
  refine S.primaryComponent_right_eq_bot hp ?_
    (strictCohomologicalDimensionLE_iff.1 hs θ.ker (n + 2) (by omega))
  -- Shapiro's lemma: `Hⁿ⁺¹(G, Coind_U^G Z) ≅ Hⁿ⁺¹(U, Z)`
  refine (AddSubgroup.eq_bot_iff_forall _).2 fun x ⟨k, hk⟩ ↦ ?_
  set σ := ContinuousCohomology.shapiroIso (U : Subgroup G) U.isClosed Z.V (n + 1)
  have hσx : σ.hom x ∈ AddCommGroup.primaryComponent _ p :=
    ⟨k, by rw [← map_nsmul, hk, _root_.map_zero]⟩
  have hZ' : AddCommGroup.primaryComponent
      (continuousCohomology (n + 1) (ofDiscreteModule ℤ (U : Subgroup G) Z.V)) p = ⊥ := by
    -- `ofDiscreteModule` reads `Z` through the canonical `ℤ`-module structure of an additive
    -- group, which agrees with that of `Z` because a `ℤ`-module structure is unique
    have hZZ : ofDiscreteModule ℤ (U : Subgroup G) Z.V = Z := by
      convert ofDiscreteModule_eq_self Z
      exact Subsingleton.elim _ _
    rw [hZZ]
    exact hZ
  rw [hZ', AddSubgroup.mem_bot] at hσx
  rw [← σ.hom_inv_id_apply x, hσx, _root_.map_zero]

variable (hZ : ∀ U : OpenSubgroup G, AddCommGroup.primaryComponent (continuousCohomology (n + 1)
    (TopRep.of (ContRepresentation.trivial ℤ (U : Subgroup G) (ULift.{u} ℤ)))) p = ⊥)
include hZ

/-- Under `scd_p G ≤ n + 1` and the vanishing of the `p`-primary components of `Hⁿ⁺¹(U, ℤ)` for
the open subgroups `U`, the `p`-primary component of `Hⁿ⁺¹(G, Q)` vanishes for every discrete
`G`-module `Q` generated by the orbit of a single element `q`. The module `Q` is a quotient of
`Coind_U^G ℤ` for the stabilizer `U` of `q`. -/
private theorem primaryComponent_eq_bot_of_cyclic (Q : Type u) [AddCommGroup Q]
    [TopologicalSpace Q] [DiscreteTopology Q] [DistribMulAction G Q] [ContinuousSMul G Q] (q : Q)
    (hq : ∀ x : Q, x ∈ AddSubgroup.closure (Set.range fun g : G ↦ g • q)) :
    AddCommGroup.primaryComponent (continuousCohomology (n + 1) (ofDiscreteModule ℤ G Q)) p = ⊥ :=
  let U : OpenSubgroup G :=
    ⟨MulAction.stabilizer G q, continuousSMul_iff_stabilizer_isOpen.1 inferInstance q⟩
  primaryComponent_eq_bot_of_cyclic_aux hp hs U _ (isSmoothDiscrete_trivial ℤ (ULift.{u} ℤ))
    (fun u a ↦ ContRepresentation.trivial_apply u a) AddEquiv.ulift (hZ U) Q q (fun u ↦ u.2) hq

end Cyclic

/-! ### Finitely generated modules -/

section FinitelyGenerated

variable (hp : p.Prime) (hs : StrictCohomologicalDimensionLE.{u} p G (n + 1))
  (hZ : ∀ U : OpenSubgroup G, AddCommGroup.primaryComponent (continuousCohomology (n + 1)
    (TopRep.of (ContRepresentation.trivial ℤ (U : Subgroup G) (ULift.{u} ℤ)))) p = ⊥)
include hp hs hZ

/-- Under `scd_p G ≤ n + 1` and the vanishing of the `p`-primary components of `Hⁿ⁺¹(U, ℤ)` for
the open subgroups `U`, the `p`-primary component of `Hⁿ⁺¹(G, B)` vanishes for every discrete
`G`-module `B` generated by the orbits of a finite family `v`, by induction on the family: `B` is
an extension of the cyclic module generated by the orbit of one member by the submodule generated
by the orbits of the others. -/
private theorem primaryComponent_eq_bot_of_finite (ι : Type u) [Finite ι] (B : Type u)
    [AddCommGroup B] [TopologicalSpace B] [DiscreteTopology B] [DistribMulAction G B]
    [ContinuousSMul G B] (v : ι → B)
    (hv : ∀ b : B, b ∈ AddSubgroup.closure (Set.range fun x : G × ι ↦ x.1 • v x.2)) :
    AddCommGroup.primaryComponent
      (continuousCohomology (n + 1) (ofDiscreteModule ℤ G B)) p = ⊥ := by
  induction ι using Finite.induction_empty_option generalizing B with
  | of_equiv e h =>
    refine h B (v ∘ e) fun b ↦ AddSubgroup.closure_mono ?_ (hv b)
    rintro _ ⟨⟨g, i⟩, rfl⟩
    exact ⟨⟨g, e.symm i⟩, by simp⟩
  | h_empty =>
    have : Subsingleton B := ⟨fun a b ↦ by
      have ha := hv a
      have hb := hv b
      rw [Set.range_eq_empty, AddSubgroup.closure_empty, AddSubgroup.mem_bot] at ha hb
      rw [ha, hb]⟩
    have := subsingleton_continuousCohomology_ofDiscreteModule_of_subsingleton (R := ℤ) (G := G) B
      (n + 1)
    exact AddSubgroup.eq_bot_of_subsingleton _
  | @h_option ι _ h =>
    -- the submodule `K` generated by the orbits of the members `v (some i)`
    set K := AddSubgroup.closure (Set.range fun x : G × ι ↦ x.1 • v (some x.2))
    have hK : ∀ g : G, ∀ b ∈ K, g • b ∈ K := AddSubgroup.smul_mem_closure_orbits (v ∘ some)
    let := K.restrictDistribMulAction hK
    let := K.quotientDistribMulAction hK
    have : ContinuousSMul G K := K.restrictDistribMulAction_continuousSMul hK
    have : ContinuousAdd B := ⟨continuous_of_discreteTopology⟩
    have : ContinuousSMul G (B ⧸ K) := K.quotientDistribMulAction_continuousSMul hK
    refine (DiscreteShortExact.ofAddSubgroup K hK).primaryComponent_middle_eq_bot hp
      (h K (AddSubgroup.orbitsGenerator (v ∘ some))
        (AddSubgroup.mem_closure_orbits_orbitsGenerator (v ∘ some)))
      (primaryComponent_eq_bot_of_cyclic hp hs hZ (B ⧸ K) (QuotientAddGroup.mk (v none))
        fun b ↦ ?_)
    -- the quotient `B ⧸ K` is generated by the orbit of the class of `v none`
    induction b using QuotientAddGroup.induction_on with | H b => ?_
    have hle : AddSubgroup.closure (Set.range fun x : G × Option ι ↦ x.1 • v x.2) ≤
        (AddSubgroup.closure
          (Set.range fun g : G ↦ g • (QuotientAddGroup.mk (v none) : B ⧸ K))).comap
            (QuotientAddGroup.mk' K) := by
      rw [AddSubgroup.closure_le]
      rintro _ ⟨⟨g, i⟩, rfl⟩
      cases i with
      | none =>
        exact AddSubgroup.subset_closure ⟨g, (K.quotientDistribMulAction_smul_mk hK g (v none))⟩
      | some i =>
        have hg : g • v (some i) ∈ K := AddSubgroup.subset_closure ⟨⟨g, i⟩, rfl⟩
        rw [SetLike.mem_coe, AddSubgroup.mem_comap, QuotientAddGroup.mk'_apply,
          (QuotientAddGroup.eq_zero_iff _).2 hg]
        exact zero_mem _
    exact hle (hv b)

/-- Under `scd_p G ≤ n + 1` and the vanishing of the `p`-primary components of `Hⁿ⁺¹(U, ℤ)` for
the open subgroups `U`, the `p`-primary component of `Hⁿ⁺¹(G, M)` vanishes for every discrete
`G`-module `M`: each class comes from the submodule generated by the orbits of the finitely many
values of a representing cocycle. -/
private theorem primaryComponent_succ_eq_bot (M : Type u) [AddCommGroup M] [TopologicalSpace M]
    [DiscreteTopology M] [DistribMulAction G M] [ContinuousSMul G M] :
    AddCommGroup.primaryComponent
      (continuousCohomology (n + 1) (ofDiscreteModule ℤ G M)) p = ⊥ := by
  refine (AddSubgroup.eq_bot_iff_forall _).2 fun x hx ↦ ?_
  obtain ⟨S, hS, hxS⟩ := exists_finite_forall_mem_range_coeffMap (n + 1) x
  -- the submodule `N` generated by the orbits of the values `S`, read in `M`
  let w : S → M := Subtype.val
  set N := AddSubgroup.closure (Set.range fun y : G × S ↦ y.1 • w y.2)
  have hN : ∀ g : G, ∀ m ∈ N, g • m ∈ N := AddSubgroup.smul_mem_closure_orbits w
  let := N.restrictDistribMulAction hN
  have : ContinuousSMul G N := N.restrictDistribMulAction_continuousSMul hN
  have : Finite S := hS.to_subtype
  obtain ⟨y, rfl⟩ := hxS (ofDiscreteModule ℤ G N)
    (ofDiscreteModuleMap N.subtype.toIntLinearMap (N.restrictDistribMulAction_coe_smul hN))
    Subtype.val_injective fun s hs ↦
      ⟨AddSubgroup.orbitsGenerator w ⟨s, hs⟩, AddSubgroup.coe_orbitsGenerator w _⟩
  -- the class `y` may be replaced by a `p`-primary one with the same image, and that one vanishes
  obtain ⟨y', hy', hy'x⟩ := exists_mem_primaryComponent_apply_eq
    (coeffMap (ofDiscreteModuleMap N.subtype.toIntLinearMap
      (N.restrictDistribMulAction_coe_smul hN)) (n + 1)).hom hp
    (isAddTorsion_continuousCohomology n y) hx
  rw [primaryComponent_eq_bot_of_finite hp hs hZ S N (AddSubgroup.orbitsGenerator w)
    (AddSubgroup.mem_closure_orbits_orbitsGenerator w), AddSubgroup.mem_bot] at hy'
  rw [← hy'x, hy', _root_.map_zero]

end FinitelyGenerated

/-! ### The criterion -/

/-- **The converse half of NSW (3.3.4)**, as vanishing predicates. For a profinite group `G` and a
prime `p`, if `CohomologicalDimensionLE p G n` holds and the `p`-primary component of `Hⁿ⁺¹(U, ℤ)`
vanishes for every open subgroup `U`, the integers carrying the trivial action, then
`StrictCohomologicalDimensionLE p G n` holds. -/
theorem CohomologicalDimensionLE.strictCohomologicalDimensionLE_of_forall_openSubgroup
    (hp : p.Prime) (h : CohomologicalDimensionLE.{u} p G n)
    (hZ : ∀ U : OpenSubgroup G, AddCommGroup.primaryComponent (continuousCohomology (n + 1)
      (TopRep.of (ContRepresentation.trivial ℤ (U : Subgroup G) (ULift.{u} ℤ)))) p = ⊥) :
    StrictCohomologicalDimensionLE.{u} p G n := by
  -- above degree `n + 1` this is `scd_p G ≤ cd_p G + 1`
  have hs := h.strictCohomologicalDimensionLE_add_one
  refine strictCohomologicalDimensionLE_iff.2 fun M _ _ _ _ _ i hi ↦ ?_
  obtain rfl | hi' := (Nat.succ_le_of_lt hi).eq_or_lt
  · exact primaryComponent_succ_eq_bot hp hs hZ M
  · exact strictCohomologicalDimensionLE_iff.1 hs M i hi'

/-- **The strict cohomological dimension through integral coefficients** (NSW (3.3.4)), as
vanishing predicates. For a profinite group `G` and a prime `p`,
`StrictCohomologicalDimensionLE p G n` holds if and only if `CohomologicalDimensionLE p G n` holds
and the `p`-primary component of `Hⁿ⁺¹(U, ℤ)` vanishes for every open subgroup `U`, the integers
carrying the trivial action. -/
theorem strictCohomologicalDimensionLE_iff_forall_openSubgroup (hp : p.Prime) :
    StrictCohomologicalDimensionLE.{u} p G n ↔ CohomologicalDimensionLE.{u} p G n ∧
      ∀ U : OpenSubgroup G, AddCommGroup.primaryComponent (continuousCohomology (n + 1)
        (TopRep.of (ContRepresentation.trivial ℤ (U : Subgroup G) (ULift.{u} ℤ)))) p = ⊥ :=
  ⟨fun h ↦ ⟨h.cohomologicalDimensionLE, fun U ↦
      (h.of_isClosed U.isClosed).primaryComponent_eq_bot_of_isSmoothDiscrete _
        (isSmoothDiscrete_trivial ℤ (ULift.{u} ℤ)) n.lt_succ_self⟩,
    fun ⟨h, hZ⟩ ↦ h.strictCohomologicalDimensionLE_of_forall_openSubgroup hp hZ⟩

/-- **The strict cohomological dimension through integral coefficients** (NSW (3.3.4)). For a
profinite group `G` and a prime `p`, `scd_p G ≤ n` if and only if `cd_p G ≤ n` and the `p`-primary
component of `Hⁿ⁺¹(U, ℤ)` vanishes for every open subgroup `U`, the integers carrying the trivial
action. -/
theorem strictCohomologicalDimensionAt_le_iff_forall_openSubgroup (hp : p.Prime) (n : ℕ) :
    strictCohomologicalDimensionAt.{u} p G ≤ n ↔ cohomologicalDimensionAt.{u} p G ≤ n ∧
      ∀ U : OpenSubgroup G, AddCommGroup.primaryComponent (continuousCohomology (n + 1)
        (TopRep.of (ContRepresentation.trivial ℤ (U : Subgroup G) (ULift.{u} ℤ)))) p = ⊥ := by
  rw [strictCohomologicalDimensionAt_le_iff, cohomologicalDimensionAt_le_iff,
    strictCohomologicalDimensionLE_iff_forall_openSubgroup hp]

end TauCeti
