/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Scheme
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic
public import TauCeti.LinearAlgebra.Matrix.IdealEntries

/-!
# The subgroup scheme of `GLₙ` preserving a constant bilinear multiplication

For a commutative ring `R`, a natural number `n`, and a family of **constant** structure
matrices `C : Fin n → Matrix (Fin n) (Fin n) R`, read `Cₖ` as the matrix of left multiplication
by the `k`th basis vector of `Rⁿ`, so that the bilinear multiplication is the one with structure
constants `eₖ * eⱼ = ∑ᵢ (Cₖ)ᵢⱼ eᵢ`. A matrix `M` is multiplicative for that product exactly when

```text
M Cₖ = (∑ₐ Mₐₖ Cₐ) M
```

for every `k`: the left-hand side sends `x` to `M (eₖ * x)`, the right-hand side sends `x` to
`(M eₖ) * (M x)`, and linearity in the first argument reduces multiplicativity to the basis
vectors. The entries of the relation matrices `X Cₖ − (∑ₐ Xₐₖ Cₐ) X` — `X` the localized generic
matrix of `GL n`, the `Cₐ` read in the coordinate Hopf algebra through the structure morphism —
generate a Hopf ideal in the coordinate Hopf algebra of `GL n`. Its quotient represents the
closed subgroup scheme of `GL n` preserving the multiplication, whose points over a commutative
`R`-algebra `A` are the invertible matrices multiplicative for the transported product.

Nothing is assumed of `C`: the multiplication is an arbitrary bilinear map `Rⁿ × Rⁿ → Rⁿ`, not
required to be associative, commutative, alternating, or unital, and the construction includes
`n = 0` and the zero ring. Multiplication by a fixed constant matrix, composition algebras, and
Lie brackets are all instances.

The three Hopf-ideal closure conditions are proved by matrix algebra rather than coordinate by
coordinate, from three identities satisfied by the relation matrices `f_k(M) := M Cₖ − (∑ₐ Mₐₖ
Cₐ) M` of an arbitrary matrix `M` over an arbitrary commutative `R`-algebra:

* `f_k(1) = 0`, so the counit, which sends `X` to the identity matrix, kills every generator;
* `f_k(M N) = M f_k(N) + (∑ₐ Nₐₖ f_a(M)) N`, so the comultiplication, which sends `X` to `Y Z`
  for `Y` and `Z` the two tensor inclusions of `X`, sends a generator into the sum of the right
  and left tensor ideals of the generators;
* `f_k(N) = −N (∑ₐ Nₐₖ f_a(M)) N` whenever `M N = N M = 1`, so the antipode, which sends `X` to
  its inverse matrix, sends a generator into the span of the generators.

The middle identity also says that the matrices preserving the multiplication are closed under
multiplication, and the last that they are closed under inversion.

## Main declarations

* `TauCeti.ConstantMultiplication.imageStructureMatrix` and
  `TauCeti.ConstantMultiplication.relationMatrix`: the matrix `∑ₐ Mₐₖ Cₐ` of left multiplication
  by `M eₖ`, and the matrix of defining relations `M Cₖ − (∑ₐ Mₐₖ Cₐ) M`, with
  `TauCeti.ConstantMultiplication.imageStructureMatrix_map` and
  `TauCeti.ConstantMultiplication.relationMatrix_map` transporting both along an algebra
  morphism of value rings.
* `TauCeti.ConstantMultiplication.Preserves`: multiplicativity of a matrix for the product, with
  `TauCeti.ConstantMultiplication.preserves_one`,
  `TauCeti.ConstantMultiplication.Preserves.mul`,
  `TauCeti.ConstantMultiplication.Preserves.of_mul_eq_one`, and
  `TauCeti.ConstantMultiplication.Preserves.map`.
* `TauCeti.ConstantMultiplication.preserves_toMatrix_iff`: when `C` consists of the structure
  matrices of an algebra in a basis, a matrix preserves the multiplication exactly when the
  linear endomorphism it represents is multiplicative.
* `TauCeti.ConstantMultiplication.definingHopfIdeal`: the Hopf ideal generated by the entries of
  the relation matrices of the generic matrix.
* `TauCeti.ConstantMultiplication.definingHopfIdeal_toIdeal_le_ker_of_preserves_map_genericMatrix`:
  a coordinate morphism whose generic matrix preserves the multiplication kills the defining
  ideal.
* `TauCeti.ConstantMultiplication.coordinateHopfAlgebra` and
  `TauCeti.ConstantMultiplication.coordinateMap`: the quotient coordinate Hopf algebra and the
  quotient morphism onto it, with
  `TauCeti.ConstantMultiplication.preserves_map_genericMatrix_coordinateMap` saying that the
  transported generic matrix preserves the multiplication.
* `TauCeti.ConstantMultiplication.groupScheme` and
  `TauCeti.ConstantMultiplication.inclusion`: the subgroup scheme preserving the multiplication
  and its closed immersion into the general linear group scheme.
* `TauCeti.ConstantMultiplication.mem_definingPointsSubgroup_iff`: an ambient point is cut out
  exactly when its matrix preserves the multiplication.

## References

* J. S. Milne, *Algebraic Groups* (2017), §2.3, where subgroups of `GLₙ` are cut out by the
  entries of a matrix relation, and §24, where automorphism group schemes of algebras appear.
* W. C. Waterhouse, *Introduction to Affine Group Schemes* (1979), Chapter 1, for such groups as
  representable functors on commutative rings.
* The Stacks Project, [Tag 022W](https://stacks.math.columbia.edu/tag/022W), for the ambient
  general linear group scheme.

The declaration order and the shape of the closure proofs follow
`TauCeti.ConstantForm`, which carries out the same programme for the relation `X C Xᵀ − C` of a
single constant matrix; the three identities above and the reduction of the closure conditions
to them are specific to this file.
-/

public section

open CategoryTheory Matrix WithConv

namespace TauCeti.ConstantMultiplication

universe u v w

variable (R : Type u) [CommRing R] (n : ℕ) (C : Fin n → Matrix (Fin n) (Fin n) R)

section Matrices

variable {S : Type v} [CommRing S] [Algebra R S]

/-- The structure matrix of the image of the `k`th basis vector under `M`: the combination
`∑ₐ Mₐₖ Cₐ`, which is the matrix of left multiplication by `M eₖ`. -/
def imageStructureMatrix (M : Matrix (Fin n) (Fin n) S) (k : Fin n) :
    Matrix (Fin n) (Fin n) S :=
  ∑ a, M a k • (C a).map (algebraMap R S)

/-- The image structure matrix is the combination of the structure matrices weighted by the
`k`th column of `M`. -/
theorem imageStructureMatrix_def (M : Matrix (Fin n) (Fin n) S) (k : Fin n) :
    imageStructureMatrix R n C M k = ∑ a, M a k • (C a).map (algebraMap R S) := by
  rw [imageStructureMatrix]

/-- **The matrix of defining relations** of `M` at the index `k`: `M Cₖ − (∑ₐ Mₐₖ Cₐ) M`. -/
def relationMatrix (M : Matrix (Fin n) (Fin n) S) (k : Fin n) : Matrix (Fin n) (Fin n) S :=
  M * (C k).map (algebraMap R S) - imageStructureMatrix R n C M k * M

/-- The relation matrix compares left multiplication by `eₖ` transported by `M` with left
multiplication by the image of `eₖ`. -/
theorem relationMatrix_def (M : Matrix (Fin n) (Fin n) S) (k : Fin n) :
    relationMatrix R n C M k =
      M * (C k).map (algebraMap R S) - imageStructureMatrix R n C M k * M := by
  rw [relationMatrix]

/-- A matrix **preserves the multiplication** given by the structure matrices `C` when it is
multiplicative for it, `M (x * y) = (M x) * (M y)`, written as one matrix identity for each
basis vector of the first argument. -/
def Preserves (M : Matrix (Fin n) (Fin n) S) : Prop :=
  ∀ k, M * (C k).map (algebraMap R S) = imageStructureMatrix R n C M k * M

/-- Preserving the multiplication is one matrix identity per basis vector. -/
theorem preserves_def (M : Matrix (Fin n) (Fin n) S) :
    Preserves R n C M ↔
      ∀ k, M * (C k).map (algebraMap R S) = imageStructureMatrix R n C M k * M := by
  rw [Preserves]

/-- Preserving the multiplication is the vanishing of every relation matrix. -/
theorem preserves_iff_relationMatrix_eq_zero (M : Matrix (Fin n) (Fin n) S) :
    Preserves R n C M ↔ ∀ k, relationMatrix R n C M k = 0 := by
  rw [preserves_def]
  exact forall_congr' fun k => (sub_eq_zero (a := M * (C k).map (algebraMap R S))).symm

/-! ### Behaviour of the relation matrices under the group operations -/

/-- The image structure matrix of the identity is the structure matrix itself. -/
@[simp] theorem imageStructureMatrix_one (k : Fin n) :
    imageStructureMatrix R n C (1 : Matrix (Fin n) (Fin n) S) k =
      (C k).map (algebraMap R S) := by
  rw [imageStructureMatrix_def]
  simp [Matrix.one_apply, ite_smul]

/-- The identity matrix satisfies every defining relation. -/
@[simp] theorem relationMatrix_one (k : Fin n) :
    relationMatrix R n C (1 : Matrix (Fin n) (Fin n) S) k = 0 := by
  rw [relationMatrix_def, imageStructureMatrix_one, Matrix.one_mul, Matrix.mul_one, sub_self]

/-- The image structure matrices of a product are recombined from those of the left factor by
the column of the right factor. -/
theorem sum_smul_imageStructureMatrix (M N : Matrix (Fin n) (Fin n) S) (k : Fin n) :
    ∑ a, N a k • imageStructureMatrix R n C M a = imageStructureMatrix R n C (M * N) k := by
  simp only [imageStructureMatrix_def, Finset.smul_sum, smul_smul]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun bb _ => ?_
  rw [← Finset.sum_smul, Matrix.mul_apply]
  exact congrArg (· • (C bb).map (algebraMap R S)) (Finset.sum_congr rfl fun a _ => mul_comm _ _)

/-- **Left multiplication distributes across the image structure matrix**: framing
`imageStructureMatrix N k` on the left by `M` frames each structure matrix separately,
`M * imageStructureMatrix N k = ∑ₐ Nₐₖ • (M Cₐ)`, the structure matrices read in the value ring
through its structure morphism. -/
theorem mul_imageStructureMatrix (M N : Matrix (Fin n) (Fin n) S) (k : Fin n) :
    M * imageStructureMatrix R n C N k = ∑ a, N a k • (M * (C a).map (algebraMap R S)) := by
  rw [imageStructureMatrix_def, Finset.mul_sum]
  exact Finset.sum_congr rfl fun a _ => Matrix.mul_smul _ _ _

/-- **The relation matrices of a product** decompose into the relations of the two factors:
`f_k(M N) = M f_k(N) + (∑ₐ Nₐₖ f_a(M)) N`. -/
theorem relationMatrix_mul (M N : Matrix (Fin n) (Fin n) S) (k : Fin n) :
    relationMatrix R n C (M * N) k =
      M * relationMatrix R n C N k + (∑ a, N a k • relationMatrix R n C M a) * N := by
  have hsum : ∑ a, N a k • relationMatrix R n C M a =
      M * imageStructureMatrix R n C N k - imageStructureMatrix R n C (M * N) k * M := by
    simp only [relationMatrix_def, smul_sub, Finset.sum_sub_distrib]
    rw [mul_imageStructureMatrix, ← sum_smul_imageStructureMatrix, Finset.sum_mul]
    exact congrArg₂ _ rfl (Finset.sum_congr rfl fun a _ => (Matrix.smul_mul _ _ _).symm)
  rw [hsum]
  simp only [relationMatrix_def]
  rw [Matrix.mul_sub, Matrix.sub_mul]
  simp only [Matrix.mul_assoc]
  abel

/-- **The relation matrices of an inverse**: `f_k(N) = −N (∑ₐ Nₐₖ f_a(M)) N` whenever `M N = 1`.
For square matrices over a commutative ring that identity already makes `N` a two-sided
inverse. -/
theorem relationMatrix_of_mul_eq_one {M N : Matrix (Fin n) (Fin n) S} (h₁ : M * N = 1)
    (k : Fin n) :
    relationMatrix R n C N k = -(N * (∑ a, N a k • relationMatrix R n C M a) * N) := by
  have h₂ : N * M = 1 := mul_eq_one_comm.mp h₁
  have h := relationMatrix_mul R n C M N k
  rw [h₁, relationMatrix_one] at h
  have h₃ : (∑ a, N a k • relationMatrix R n C M a) * N =
      -(M * relationMatrix R n C N k) := by
    rw [eq_neg_iff_add_eq_zero, add_comm]
    exact h.symm
  rw [Matrix.mul_assoc N, h₃, Matrix.mul_neg, ← Matrix.mul_assoc, h₂, Matrix.one_mul, neg_neg]

/-- The structure matrices are constant, so an algebra morphism of value rings carries each entry
of one to the corresponding entry of the same matrix read in the target. -/
private theorem map_structureMatrix_apply {T : Type w} [CommRing T] [Algebra R T] (φ : S →ₐ[R] T)
    (a i j : Fin n) :
    φ (((C a).map (algebraMap R S)) i j) = ((C a).map (algebraMap R T)) i j := by
  rw [Matrix.map_apply, Matrix.map_apply]
  exact φ.commutes _

/-- An algebra morphism of value rings maps each structure matrix to itself. -/
private theorem map_structureMatrix {T : Type w} [CommRing T] [Algebra R T] (φ : S →ₐ[R] T)
    (a : Fin n) : ((C a).map (algebraMap R S)).map φ = (C a).map (algebraMap R T) := by
  ext i j
  rw [Matrix.map_apply]
  exact map_structureMatrix_apply R n C φ a i j

/-- **Mapping an image structure matrix through an algebra morphism** gives the image structure
matrix of the image matrix: the combination is taken with the entries of the matrix, which map
along, and the structure matrices are constant. -/
@[simp] theorem imageStructureMatrix_map {T : Type w} [CommRing T] [Algebra R T] (φ : S →ₐ[R] T)
    (M : Matrix (Fin n) (Fin n) S) (l : Fin n) :
    (imageStructureMatrix R n C M l).map φ = imageStructureMatrix R n C (M.map φ) l := by
  ext i j
  rw [Matrix.map_apply, imageStructureMatrix_def, imageStructureMatrix_def, Matrix.sum_apply,
    Matrix.sum_apply, map_sum]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [Matrix.smul_apply, Matrix.smul_apply, smul_eq_mul, smul_eq_mul, map_mul,
    map_structureMatrix_apply]
  simp only [Matrix.map_apply]

/-- Mapping a relation matrix through an algebra morphism gives the relation matrix of the image
matrix: the structure matrices are constant, so they map to themselves. -/
@[simp] theorem relationMatrix_map {T : Type w} [CommRing T] [Algebra R T] (φ : S →ₐ[R] T)
    (M : Matrix (Fin n) (Fin n) S) (k : Fin n) :
    (relationMatrix R n C M k).map φ = relationMatrix R n C (M.map φ) k := by
  rw [relationMatrix_def, relationMatrix_def, Matrix.map_sub, Matrix.map_mul, Matrix.map_mul,
    map_structureMatrix, imageStructureMatrix_map]
  exact fun a b => map_sub φ a b

/-! ### The matrices preserving the multiplication -/

/-- The identity matrix preserves the multiplication. -/
@[simp] theorem preserves_one : Preserves R n C (1 : Matrix (Fin n) (Fin n) S) :=
  (preserves_iff_relationMatrix_eq_zero R n C _).2 (relationMatrix_one R n C)

/-- A product of matrices preserving the multiplication preserves it. -/
theorem Preserves.mul {M N : Matrix (Fin n) (Fin n) S} (hM : Preserves R n C M)
    (hN : Preserves R n C N) : Preserves R n C (M * N) := by
  rw [preserves_iff_relationMatrix_eq_zero] at hM hN ⊢
  intro k
  rw [relationMatrix_mul, hN k, Matrix.mul_zero]
  simp only [hM, smul_zero, Finset.sum_const_zero, Matrix.zero_mul, add_zero]

/-- An inverse of a matrix preserving the multiplication preserves it. Only one of the two
inverse identities is needed: for square matrices over a commutative ring it implies the
other. -/
theorem Preserves.of_mul_eq_one {M N : Matrix (Fin n) (Fin n) S} (hM : Preserves R n C M)
    (h₁ : M * N = 1) : Preserves R n C N := by
  rw [preserves_iff_relationMatrix_eq_zero] at hM ⊢
  intro k
  rw [relationMatrix_of_mul_eq_one R n C h₁ k]
  simp only [hM, smul_zero, Finset.sum_const_zero, Matrix.mul_zero, Matrix.zero_mul, neg_zero]

/-- Preserving the multiplication is stable under an algebra morphism of value rings. -/
theorem Preserves.map {T : Type w} [CommRing T] [Algebra R T] {M : Matrix (Fin n) (Fin n) S}
    (hM : Preserves R n C M) (φ : S →ₐ[R] T) : Preserves R n C (M.map φ) := by
  rw [preserves_iff_relationMatrix_eq_zero] at hM ⊢
  intro k
  rw [← relationMatrix_map R n C φ M k, hM k]
  exact Matrix.map_zero _ (map_zero φ)

end Matrices

/-! ### Structure matrices of an algebra with a basis

When the structure matrices `C k` are those of an actual algebra `B` over `S` with a basis `b`,
that is, when `C k` read in `S` is the matrix in `b` of left multiplication by `b k`, preserving
the multiplication is exactly multiplicativity of the linear endomorphism of `B` that the matrix
represents in `b`. -/

section Basis

variable {S : Type v} [CommRing S] [Algebra R S]
variable {B : Type w} [NonUnitalNonAssocSemiring B] [Module S B] [IsScalarTower S B B]
  [SMulCommClass S B B]

/-- If the structure matrices of a basis `b` are the `C k`, then the image structure matrix at
`k` of the matrix of a linear endomorphism `f` is the matrix of left multiplication by
`f (b k)`. -/
theorem imageStructureMatrix_toMatrix (b : Module.Basis (Fin n) S B)
    (hC : ∀ k, LinearMap.toMatrix b b (LinearMap.mulLeft S (b k)) = (C k).map (algebraMap R S))
    (f : B →ₗ[S] B) (k : Fin n) :
    imageStructureMatrix R n C (LinearMap.toMatrix b b f) k =
      LinearMap.toMatrix b b (LinearMap.mulLeft S (f (b k))) := by
  have hsum : LinearMap.mulLeft S (f (b k)) =
      ∑ a, b.repr (f (b k)) a • LinearMap.mulLeft S (b a) := by
    ext x
    rw [LinearMap.mulLeft_apply, LinearMap.sum_apply]
    conv_lhs => rw [← b.sum_repr (f (b k))]
    rw [Finset.sum_mul]
    simp only [LinearMap.smul_apply, LinearMap.mulLeft_apply, smul_mul_assoc]
  rw [imageStructureMatrix_def, hsum, map_sum]
  simp [← hC, LinearMap.toMatrix_apply]

/-- **Preserving the multiplication is multiplicativity.** If the structure matrices of a basis
`b` of a non-unital, non-associative `S`-algebra `B` are the `C k`, then the matrix in `b` of a
linear endomorphism `f` of `B` preserves the multiplication exactly when `f` is
multiplicative. -/
theorem preserves_toMatrix_iff (b : Module.Basis (Fin n) S B)
    (hC : ∀ k, LinearMap.toMatrix b b (LinearMap.mulLeft S (b k)) = (C k).map (algebraMap R S))
    (f : B →ₗ[S] B) :
    Preserves R n C (LinearMap.toMatrix b b f) ↔ ∀ x y, f (x * y) = f x * f y := by
  rw [preserves_def]
  simp_rw [imageStructureMatrix_toMatrix R n C b hC, ← hC, ← LinearMap.toMatrix_comp,
    (LinearMap.toMatrix b b).injective.eq_iff]
  constructor
  · intro h x y
    have hx : f ∘ₗ LinearMap.mulRight S y = LinearMap.mulRight S (f y) ∘ₗ f :=
      b.ext fun k => by simpa using LinearMap.congr_fun (h k) y
    simpa using LinearMap.congr_fun hx x
  · intro h k
    ext y
    simp [h]

end Basis

/-! ### The defining relations over the coordinate Hopf algebra of `GLₙ` -/

/-- The set of defining relations: the entries of the relation matrices of the generic
matrix. -/
def relationSet : Set (GeneralLinear.coordinateHopfAlgebra R n) :=
  Set.range fun p : Fin n × Fin n × Fin n =>
    relationMatrix R n C (GeneralLinear.genericMatrix R n) p.1 p.2.1 p.2.2

/-- Every entry of every relation matrix of the generic matrix is a defining relation. -/
theorem relationMatrix_genericMatrix_mem_relationSet (k i j : Fin n) :
    relationMatrix R n C (GeneralLinear.genericMatrix R n) k i j ∈ relationSet R n C :=
  ⟨(k, i, j), rfl⟩

/-- An element is a defining relation exactly when it is an entry of a relation matrix of the
generic matrix. -/
@[simp] theorem mem_relationSet_iff {x : GeneralLinear.coordinateHopfAlgebra R n} :
    x ∈ relationSet R n C ↔
      ∃ k i j, relationMatrix R n C (GeneralLinear.genericMatrix R n) k i j = x := by
  rw [relationSet, Set.mem_range]
  exact ⟨fun ⟨p, hp⟩ => ⟨p.1, p.2.1, p.2.2, hp⟩, fun ⟨k, i, j, h⟩ => ⟨(k, i, j), h⟩⟩

/-- Every entry of the relation matrix of a transported generic matrix is the image of a
defining relation. -/
private theorem relationMatrix_map_genericMatrix_mem {T : Type*} [CommRing T] [Algebra R T]
    (φ : GeneralLinear.coordinateHopfAlgebra R n →ₐ[R] T) (K : Ideal T)
    (hK : ∀ x ∈ relationSet R n C, φ x ∈ K) (k p q : Fin n) :
    relationMatrix R n C ((GeneralLinear.genericMatrix R n).map φ) k p q ∈ K := by
  rw [← relationMatrix_map R n C φ (GeneralLinear.genericMatrix R n) k, Matrix.map_apply]
  exact hK _ (relationMatrix_genericMatrix_mem_relationSet R n C k p q)

/-! ### The three Hopf-ideal closure conditions -/

/-- The counit vanishes on every defining relation. -/
private theorem counit_relationMatrix (k i j : Fin n) :
    Coalgebra.counit (R := R)
      (relationMatrix R n C (GeneralLinear.genericMatrix R n) k i j) = 0 := by
  have h := congrFun (congrFun (relationMatrix_map R n C
    (Bialgebra.counitAlgHom R (GeneralLinear.coordinateHopfAlgebra R n))
    (GeneralLinear.genericMatrix R n) k) i) j
  rw [Matrix.map_apply, Bialgebra.counitAlgHom_apply] at h
  rw [h, GeneralLinear.map_counit_genericMatrix, relationMatrix_one, Matrix.zero_apply]

/-- The comultiplication of every defining relation lies in the sum of the left and right tensor
ideals of the span of the relations: the comultiplication sends the generic matrix to the
product of its two tensor inclusions, and the relation matrices of a product decompose into
those of the two factors. -/
private theorem comul_relationMatrix_mem (k i j : Fin n) :
    Coalgebra.comul (R := R) (relationMatrix R n C (GeneralLinear.genericMatrix R n) k i j) ∈
      HopfIdeal.leftTensorIdeal (R := R)
          (H := GeneralLinear.coordinateHopfAlgebra R n)
          (Ideal.span (relationSet R n C)) ⊔
        HopfIdeal.rightTensorIdeal (R := R)
          (H := GeneralLinear.coordinateHopfAlgebra R n)
          (Ideal.span (relationSet R n C)) := by
  have hmap := relationMatrix_map R n C
    (Bialgebra.comulAlgHom R (GeneralLinear.coordinateHopfAlgebra R n))
    (GeneralLinear.genericMatrix R n) k
  rw [GeneralLinear.map_comul_genericMatrix, relationMatrix_mul] at hmap
  have h := congrFun (congrFun hmap i) j
  rw [Matrix.map_apply, Bialgebra.comulAlgHom_apply] at h
  rw [h, Matrix.add_apply]
  refine Ideal.add_mem _ (Ideal.mem_sup_right ?_) (Ideal.mem_sup_left ?_)
  · have hr : ∀ p q : Fin n, relationMatrix R n C
        ((GeneralLinear.genericMatrix R n).map
          (Algebra.TensorProduct.includeRight (R := R))) k p q ∈
        HopfIdeal.rightTensorIdeal (R := R)
          (H := GeneralLinear.coordinateHopfAlgebra R n)
          (Ideal.span (relationSet R n C)) := by
      intro p q
      refine relationMatrix_map_genericMatrix_mem R n C _ _ (fun x hx => ?_) k p q
      exact HopfIdeal.includeRight_mem_rightTensorIdeal (R := R)
        (H := GeneralLinear.coordinateHopfAlgebra R n) (Ideal.subset_span hx)
    have hmem := Matrix.mul_mul_apply_mem hr
      ((GeneralLinear.genericMatrix R n).map
        (Algebra.TensorProduct.includeLeft (R := R) (S := R))) 1 i j
    rwa [Matrix.mul_one] at hmem
  · have hl : ∀ a p q : Fin n, relationMatrix R n C
        ((GeneralLinear.genericMatrix R n).map
          (Algebra.TensorProduct.includeLeft (R := R) (S := R))) a p q ∈
        HopfIdeal.leftTensorIdeal (R := R)
          (H := GeneralLinear.coordinateHopfAlgebra R n)
          (Ideal.span (relationSet R n C)) := by
      intro a p q
      refine relationMatrix_map_genericMatrix_mem R n C _ _ (fun x hx => ?_) a p q
      exact HopfIdeal.includeLeft_mem_leftTensorIdeal (R := R)
        (H := GeneralLinear.coordinateHopfAlgebra R n) (Ideal.subset_span hx)
    have hsum : ∀ p q : Fin n,
        (∑ a, ((GeneralLinear.genericMatrix R n).map
              (Algebra.TensorProduct.includeRight (R := R))) a k •
            relationMatrix R n C ((GeneralLinear.genericMatrix R n).map
              (Algebra.TensorProduct.includeLeft (R := R) (S := R))) a) p q ∈
          HopfIdeal.leftTensorIdeal (R := R)
            (H := GeneralLinear.coordinateHopfAlgebra R n)
            (Ideal.span (relationSet R n C)) :=
      fun p q => Matrix.sum_smul_apply_mem hl _ p q
    have hmem := Matrix.mul_mul_apply_mem hsum 1
      ((GeneralLinear.genericMatrix R n).map
        (Algebra.TensorProduct.includeRight (R := R))) i j
    rwa [Matrix.one_mul] at hmem

/-- The antipode image of a relation matrix is a combination of the relation matrices framed by
the bundled inverse of the generic matrix. -/
private theorem relationMatrix_genericMatrix_map_antipode (k : Fin n) :
    (relationMatrix R n C (GeneralLinear.genericMatrix R n) k).map
        (HopfAlgebra.antipodeAlgHom (R := R)
          (A := GeneralLinear.coordinateHopfAlgebra R n)) =
      -((GeneralLinear.genericMatrix R n)⁻¹ *
        (∑ a, ((GeneralLinear.genericMatrix R n)⁻¹) a k •
          relationMatrix R n C (GeneralLinear.genericMatrix R n) a) *
        (GeneralLinear.genericMatrix R n)⁻¹) := by
  rw [relationMatrix_map, GeneralLinear.map_antipode_genericMatrix,
    relationMatrix_of_mul_eq_one R n C
      (Matrix.mul_nonsing_inv _ (GeneralLinear.isUnit_det_genericMatrix R n)) k]

/-- The antipode carries every defining relation into the span of the relations. -/
private theorem antipode_relationMatrix_mem (k i j : Fin n) :
    HopfAlgebra.antipode R (relationMatrix R n C (GeneralLinear.genericMatrix R n) k i j) ∈
      Ideal.span (relationSet R n C) := by
  have h := congrFun (congrFun (relationMatrix_genericMatrix_map_antipode R n C k) i) j
  rw [Matrix.map_apply, HopfAlgebra.antipodeAlgHom_apply] at h
  rw [h, Matrix.neg_apply]
  exact neg_mem (Matrix.mul_mul_apply_mem
    (fun p q => Matrix.sum_smul_apply_mem
      (fun a p q => Ideal.subset_span
        (relationMatrix_genericMatrix_mem_relationSet R n C a p q)) _ p q)
    (GeneralLinear.genericMatrix R n)⁻¹ (GeneralLinear.genericMatrix R n)⁻¹ i j)

/-! ### The defining Hopf ideal and quotient -/

/-- **The Hopf ideal preserving the multiplication**: the ideal of the coordinate Hopf algebra
of `GL n` generated by the entries of the relation matrices `X Cₖ − (∑ₐ Xₐₖ Cₐ) X`, with the
three closure conditions extended from the generators across the span. -/
noncomputable def definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R n) :=
  HopfIdeal.ofSpan (relationSet R n C)
    (fun x hx => by
      obtain ⟨p, rfl⟩ := hx
      exact comul_relationMatrix_mem R n C p.1 p.2.1 p.2.2)
    (fun x hx => by
      obtain ⟨p, rfl⟩ := hx
      exact counit_relationMatrix R n C p.1 p.2.1 p.2.2)
    (fun x hx => by
      obtain ⟨p, rfl⟩ := hx
      exact antipode_relationMatrix_mem R n C p.1 p.2.1 p.2.2)

/-- The underlying ideal of the defining Hopf ideal is the span of the defining relations. -/
@[simp]
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R n C).toIdeal = Ideal.span (relationSet R n C) := by
  rw [definingHopfIdeal, HopfIdeal.ofSpan_toIdeal]

/-- **A coordinate morphism whose generic matrix preserves the multiplication kills the defining
ideal.** This is the criterion by which a subgroup of `GL n` given by generating morphisms is
shown to lie in the subgroup scheme preserving the multiplication: it suffices to evaluate the
relations on the generic matrix of each generator. -/
theorem definingHopfIdeal_toIdeal_le_ker_of_preserves_map_genericMatrix
    {T : Type w} [CommRing T] [Algebra R T]
    (φ : GeneralLinear.coordinateHopfAlgebra R n →ₐ[R] T)
    (hφ : Preserves R n C ((GeneralLinear.genericMatrix R n).map φ)) :
    (definingHopfIdeal R n C).toIdeal ≤ RingHom.ker (φ : _ →+* T) := by
  rw [preserves_iff_relationMatrix_eq_zero] at hφ
  rw [definingHopfIdeal_toIdeal, Ideal.span_le]
  intro x hx
  obtain ⟨k, i, j, rfl⟩ := (mem_relationSet_iff R n C).mp hx
  have h := congrFun (congrFun
    (relationMatrix_map R n C φ (GeneralLinear.genericMatrix R n) k) i) j
  rw [Matrix.map_apply] at h
  simp only [SetLike.mem_coe, RingHom.mem_ker, RingHom.coe_coe]
  rw [h, hφ k, Matrix.zero_apply]

/-- The coordinate Hopf algebra of the subgroup scheme of `GL n` preserving the
multiplication. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n C)

/-- The quotient coordinate morphism from `O(GL n)` to the coordinate Hopf algebra of the
subgroup scheme preserving the multiplication. -/
noncomputable def coordinateMap :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ coordinateHopfAlgebra R n C :=
  CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n C)

/-- The coordinate map is the canonical quotient morphism by the defining Hopf ideal. -/
theorem coordinateMap_def :
    coordinateMap R n C =
      CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R n)
        (definingHopfIdeal R n C) := by
  unfold coordinateMap
  rfl

/-- Every defining relation vanishes in the quotient coordinate Hopf algebra. -/
@[simp]
theorem coordinateMap_relationMatrix (k i j : Fin n) :
    (coordinateMap R n C).hom
      (relationMatrix R n C (GeneralLinear.genericMatrix R n) k i j) = 0 := by
  rw [coordinateMap_def]
  exact (CommHopfAlgCat.mkQuotient_eq_zero_iff _ _ _).mpr
    (HopfIdeal.mem_toIdeal.mp (definingHopfIdeal_toIdeal R n C ▸
      Ideal.subset_span (relationMatrix_genericMatrix_mem_relationSet R n C k i j)))

/-- **The generic matrix of the quotient preserves the multiplication**: transporting the generic
matrix of `GL n` along the quotient coordinate morphism gives a matrix over the quotient
coordinate Hopf algebra that is multiplicative for the product, since exactly the entries of its
relation matrices were divided out. -/
@[simp]
theorem preserves_map_genericMatrix_coordinateMap :
    Preserves R n C
      ((GeneralLinear.genericMatrix R n).map (coordinateMap R n C).hom) := by
  rw [preserves_iff_relationMatrix_eq_zero]
  intro k
  ext i j
  rw [← BialgHom.coe_toAlgHom,
    ← relationMatrix_map R n C (coordinateMap R n C).hom.toAlgHom, Matrix.map_apply,
    Matrix.zero_apply]
  exact coordinateMap_relationMatrix R n C k i j

/-! ### The group scheme and its closed immersion -/

/-- The subgroup scheme of `GL n` preserving the multiplication. -/
noncomputable abbrev groupScheme :=
  CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n C)

/-- The subgroup scheme preserving the multiplication is the quotient spectrum of its coordinate
Hopf algebra. -/
theorem groupScheme_def :
    groupScheme R n C =
      CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra R n)
        (definingHopfIdeal R n C) :=
  rfl

/-- The closed-subgroup inclusion into the named general linear group scheme: the generic
Hopf-ideal closed immersion `GeneralLinear.hopfIdealInclusion` at the defining Hopf ideal. -/
noncomputable def inclusion : groupScheme R n C ⟶ GeneralLinear.groupScheme R n :=
  GeneralLinear.hopfIdealInclusion R n (definingHopfIdeal R n C)

/-- The inclusion is the generic Hopf-ideal closed immersion at the defining Hopf ideal. -/
theorem inclusion_def :
    inclusion R n C = GeneralLinear.hopfIdealInclusion R n (definingHopfIdeal R n C) := by
  unfold inclusion
  rfl

/-- The inclusion into the named general linear group scheme is a closed immersion. -/
instance isClosedImmersion_inclusion :
    AlgebraicGeometry.IsClosedImmersion (inclusion R n C).hom.hom.left := by
  rw [inclusion_def]
  infer_instance

/-! ### Algebra-valued points -/

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- Evaluating a relation matrix at a point gives the relation matrix of its matrix. -/
private theorem ofConv_relationMatrix
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) (k : Fin n) :
    (relationMatrix R n C (GeneralLinear.genericMatrix R n) k).map g.ofConv =
      relationMatrix R n C
        (GeneralLinear.pointToGeneralLinear n g : Matrix (Fin n) (Fin n) A) k := by
  have hg : (GeneralLinear.genericMatrix R n).map g.ofConv =
      (GeneralLinear.pointToGeneralLinear n g : Matrix (Fin n) (Fin n) A) := by
    rw [GeneralLinear.map_genericMatrix_eq_coe_pointToGeneralLinear, WithConv.toConv_ofConv]
  rw [relationMatrix_map R n C g.ofConv, hg]

/-- **The ambient membership criterion**: an ambient point belongs to the subgroup cut out by
the defining Hopf ideal exactly when its matrix preserves the multiplication. -/
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n C)
        (CommAlgCat.of R A) ↔
      Preserves R n C
        (GeneralLinear.pointsMulEquiv n g : Matrix (Fin n) (Fin n) A) := by
  rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff, GeneralLinear.pointsMulEquiv_apply,
    preserves_iff_relationMatrix_eq_zero]
  constructor
  · intro h k
    rw [← ofConv_relationMatrix R n C g k]
    ext i j
    rw [Matrix.map_apply, Matrix.zero_apply]
    exact h _ (HopfIdeal.mem_toIdeal.mp
      (definingHopfIdeal_toIdeal R n C ▸
        Ideal.subset_span (relationMatrix_genericMatrix_mem_relationSet R n C k i j)))
  · intro h y hy
    have hpres : Preserves R n C ((GeneralLinear.genericMatrix R n).map
        (g.ofConv : GeneralLinear.coordinateHopfAlgebra R n →ₐ[R] A)) := by
      rw [GeneralLinear.map_genericMatrix_eq_coe_pointToGeneralLinear, WithConv.toConv_ofConv,
        preserves_iff_relationMatrix_eq_zero]
      exact h
    exact definingHopfIdeal_toIdeal_le_ker_of_preserves_map_genericMatrix R n C _ hpres
      (HopfIdeal.mem_toIdeal.mpr hy)

end Points

end TauCeti.ConstantMultiplication
