/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Etale.Basic
public import Mathlib.RingTheory.Polynomial.Ideal
public import Mathlib.RingTheory.RingHom.StandardSmooth
public import TauCeti.RingTheory.Unramified.Section

/-!
# Sections of smooth algebras of relative dimension one

Let `B` be an `A`-algebra together with an `A`-algebra retraction `σ : B →ₐ[A] A`, the algebraic
form of a section of `Spec B → Spec A`. If `B` is standard smooth of relative dimension one over
`A`, the ideal `ker σ` of the section is, near the section, generated by a single
nonzerodivisor: there are `t ∈ ker σ`, a nonzerodivisor of `B`, and `r ∈ B` with `σ r = 1` and
`r • ker σ ≤ (t)`, so that `ker σ` becomes the principal ideal `(t)` after inverting `r`.
Geometrically, a section of a smooth relative
curve is an effective Cartier divisor.

The proof uses an étale coordinate: a standard smooth algebra of relative dimension one is étale
over a polynomial ring `P = A[X₀]` in one variable
(`Algebra.IsStandardSmoothOfRelativeDimension.exists_etale_mvPolynomial`). The retraction `σ`
restricts to the evaluation of `P` at `a = σ X₀`, whose kernel is generated by the nonzerodivisor
`u = X₀ - a`, and its image `t` in `B` is a nonzerodivisor of `B` by flatness. Since `B` is
formally unramified over `P`, `Algebra.FormallyUnramified.exists_smul_ker_le_span_singleton`
provides `r`.

## Main results

* `Algebra.IsStandardSmoothOfRelativeDimension.exists_isSMulRegular_smul_ker_le_span_singleton`:
  for a standard smooth algebra of relative dimension one, a nonzerodivisor `t ∈ ker σ` and an
  `r` with `σ r = 1` and `r • ker σ ≤ (t)`.

## References

* The Stacks Project, *Divisors*, sections *Regular immersions* and *Relative effective Cartier
  divisors*: a section of a smooth morphism of relative dimension one is a relative effective
  Cartier divisor.
-/

public section

open Polynomial

open scoped Pointwise

namespace Algebra.IsStandardSmoothOfRelativeDimension

/-- **The local equation of a section of a smooth relative curve.** Let `B` be a standard smooth
`A`-algebra of relative dimension one and `σ : B →ₐ[A] A` a retraction. Then `ker σ` contains a
nonzerodivisor `t` of `B`, and some `r ∈ B` with `σ r = 1` satisfies `r • ker σ ≤ (t)`; so after
inverting `r`, an element which is a unit along the section, `ker σ` is generated by `t`. -/
theorem exists_isSMulRegular_smul_ker_le_span_singleton {A B : Type*} [CommRing A] [CommRing B]
    [Algebra A B] [IsStandardSmoothOfRelativeDimension 1 A B] (σ : B →ₐ[A] A) :
    ∃ t ∈ RingHom.ker σ, IsSMulRegular B t ∧
      ∃ r : B, σ r = 1 ∧ r • RingHom.ker σ ≤ Ideal.span {t} := by
  have := IsStandardSmoothOfRelativeDimension.isStandardSmooth 1 (R := A) (S := B)
  -- An étale coordinate `x : B`, the image of the variable of `A[X₀]`.
  obtain ⟨g, hg⟩ := exists_etale_mvPolynomial 1 A B
  algebraize [g.toRingHom]
  have : IsScalarTower A (MvPolynomial (Fin 1) A) B := .of_algebraMap_eq' g.comp_algebraMap.symm
  let e := MvPolynomial.uniqueAlgEquiv A (Fin 1)
  set a := σ (algebraMap (MvPolynomial (Fin 1) A) B (MvPolynomial.X 0))
  set u : MvPolynomial (Fin 1) A := MvPolynomial.X 0 - MvPolynomial.C a
  have heu : e u = X - C a := by simp [e, u]
  -- The equation `u = X₀ - a` of the point is a nonzerodivisor, since `e u` is monic.
  have hu : IsSMulRegular (MvPolynomial (Fin 1) A) u := fun p q hpq ↦ e.injective <|
    (monic_X_sub_C a).isRegular.left (by simpa [heu] using congrArg e hpq)
  -- The induced point `A[X₀] → A` is evaluation at `a`, whose kernel is generated by `u`.
  have hpt : σ.comp (IsScalarTower.toAlgHom A (MvPolynomial (Fin 1) A) B) =
      (aeval a).comp e.toAlgHom :=
    MvPolynomial.algHom_ext fun i ↦ by fin_cases i; simp [e, a]
  have hker : RingHom.ker (σ.comp (IsScalarTower.toAlgHom A (MvPolynomial (Fin 1) A) B)) =
      Ideal.span {u} := by
    rw [hpt]
    ext p
    rw [RingHom.mem_ker, Ideal.mem_span_singleton']
    constructor
    · intro hp
      have hp' : e p ∈ RingHom.ker (evalRingHom a) := by
        simpa [RingHom.mem_ker, ← coe_aeval_eq_evalRingHom] using hp
      obtain ⟨q, hq⟩ := Ideal.mem_span_singleton'.mp (ker_evalRingHom a ▸ hp')
      exact ⟨e.symm q, e.injective (by simp [heu, hq])⟩
    · rintro ⟨q, rfl⟩
      simp [heu]
  obtain ⟨r, hr, hle⟩ := FormallyUnramified.exists_smul_ker_le_span_singleton σ
    (FinitePresentation.ker_fG_of_surjective σ fun c ↦ ⟨algebraMap A B c, σ.commutes c⟩) hker
  refine ⟨_, ?_, hu.of_flat, r, hr, hle⟩
  have hmem := hker ▸ Ideal.mem_span_singleton_self u
  simpa [RingHom.mem_ker] using hmem

end Algebra.IsStandardSmoothOfRelativeDimension
