/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RepresentationTheory.Coinvariants

/-!
# The coinvariant kernel of representations

Let `k` be a commutative ring and `ρ` a `k`-linear representation of a monoid `G`. The coinvariant
kernel `Representation.Coinvariants.ker ρ` is the submodule spanned by the elements `ρ g v - v`.
This file records its functoriality and describes it through orbit sums and generators.

Precomposing with a monoid homomorphism shrinks the augmentation submodule; surjective
precomposition leaves it unchanged. An action-compatible linear map carries the augmentation
submodule into that of its target, even when the function between acting monoids is not a
homomorphism.

* For the permutation representation `k[X]` of a group action on a type `X`, it is the kernel
  of the orbit-sum map `k[X] → k[X ⧸ G]`, which sums the coefficients of an element along each
  `G`-orbit.
* For an arbitrary representation of a group generated by a set `s`, it is the sum of the ranges
  of `ρ g - 1` for `g ∈ s`. In particular, if `G` is generated by a single element `g` it is the
  range of `ρ g - 1`; unlike `Representation.FiniteCyclicGroup.coinvariantsKer_eq_range`, no
  finiteness of `G` is needed.
* For an arbitrary representation of a finite monoid, it is the set of sums
  `∑ g, (ρ g (y g) - y g)` with one term for each monoid element.

Combining the first two gives, for any action of a group `G` on `X` and any `g : G`, a criterion
for membership in the range of `ρ g - 1` on `k[X]`: an element lies in it if and only if its
coefficients sum to zero along every orbit of the cyclic subgroup generated by `g`.

For a finite group and any semiring `k`, the orbit sums of the norm `∑ g, g • v` of `v ∈ k[X]`
are `|G|` times those of `v`. Over a commutative ring, when multiplication by `|G|` is injective
on `k`, an element of norm zero has vanishing orbit sums and lies in the coinvariant kernel:
the degree `-1` Tate cohomology of a permutation module vanishes.

Finally, if a finset `s ⊆ X` meets every `G`-orbit in exactly one point, then for `r : k` the
element `∑ x ∈ s, single x r` has every orbit sum equal to `r`.

## Main results

* `Representation.coinvariantsKer_map_le`: an action-compatible linear map carries the
  augmentation submodule into that of its target.
* `Representation.coinvariantsKer_comp_le`: precomposition with a monoid homomorphism shrinks
  the augmentation submodule.
* `Representation.coinvariantsKer_comp_of_surjective`: surjective precomposition preserves
  the augmentation submodule.
* `Representation.coinvariantsKer_ofMulAction_eq_ker`: the coinvariant kernel of the permutation
  representation `k[X]` is the kernel of the orbit-sum map `k[X] → k[X ⧸ G]`.
* `MonoidAlgebra.mapDomainLinearMap_orbitRel_mk_norm_ofMulAction`: over a semiring, the orbit sums
  of the norm of `v : k[X]` are `|G|` times those of `v`.
* `Representation.ker_norm_ofMulAction_le_coinvariantsKer`: if multiplication by `|G|` is
  injective on `k`, the kernel of the norm of `k[X]` lies in the coinvariant kernel.
* `Representation.coinvariantsKer_eq_iSup_range`: if `s` generates `G`, the coinvariant kernel is
  `⨆ g ∈ s, range (ρ g - 1)`.
* `Representation.coinvariantsKer_eq_range_of_forall_mem_zpowers`: if `g` generates `G`, the
  coinvariant kernel is `range (ρ g - 1)`.
* `Representation.mem_coinvariantsKer_iff_exists_sum`: for finite `G`, the coinvariant kernel
  is the set of sums `∑ g, (ρ g (y g) - y g)`.
* `Representation.mem_range_ofMulAction_sub_id_iff`: an element of `k[X]` lies in the range of
  `ρ g - 1` if and only if its coefficient sums along the orbits of `⟨g⟩` vanish.
* `MonoidAlgebra.coeff_mapDomainLinearMap_orbitRel_sum_single`: the orbit sums of
  `∑ x ∈ s, single x r` are all equal to `r` when the finset `s` is a set of orbit representatives.

## Implementation notes

As in Mathlib's `Representation.FiniteCyclicGroup.coinvariantsKer_eq_range`, the operator
`ρ g - 1` is written `ρ g - LinearMap.id`. The orbit-sum map is
`MonoidAlgebra.mapDomainLinearMap k k (Quotient.mk (MulAction.orbitRel G X))`. Its kernel lies in
the coinvariant kernel by `Representation.sub_mapDomainLinearMap_mem_coinvariantsKer`, applied to
the map `Quotient.out ∘ Quotient.mk _` that sends each point of `X` to a chosen representative of
its orbit. A set `s` of orbit representatives is described by the two hypotheses
`∀ x, ∃ g : G, g • x ∈ s` (every orbit meets `s`) and `∀ x ∈ s, ∀ g : G, g • x ∈ s → g • x = x`
(every orbit meets `s` at most once).

## References

* A. Popa and D. Zagier, *An elementary proof of the Eichler–Selberg trace formula*,
  J. Reine Angew. Math. **762** (2020), 105–122, arXiv:1711.00327. The motivating application is
  the period relation (A) of §1; in §3 an element `ζ` of the permutation module `ℚ[ℳ]` is shown
  to lie in `(1 - T) ℚ[ℳ]` if and only if its coefficients sum to zero along every `T`-orbit.
-/

public section

open MonoidAlgebra MulAction

namespace Representation

/-! ### Change of representation and acting monoid -/

section Functoriality

variable {k G V : Type*} [CommRing k] [Monoid G] [AddCommGroup V] [Module k V]
  (ρ : Representation k G V)

/-- An intertwining linear map carries the augmentation submodule into the augmentation
submodule, allowing an extension of the coefficient ring. Only the compatibility of the actions
is used, so `e` need not be a homomorphism. -/
theorem coinvariantsKer_map_le {K G' V' : Type*} [CommRing K] [Algebra k K]
    [Monoid G'] [AddCommGroup V'] [Module k V'] [Module K V'] [IsScalarTower k K V']
    {ρ' : Representation K G' V'} (e : G → G') (φ : V →ₗ[k] V')
    (hφ : ∀ g x, φ (ρ g x) = ρ' (e g) (φ x)) :
    (Coinvariants.ker ρ).map φ ≤ (Coinvariants.ker ρ').restrictScalars k := by
  rw [Coinvariants.ker, Submodule.map_span_le]
  rintro _ ⟨⟨g, x⟩, rfl⟩
  rw [map_sub, hφ]
  exact Coinvariants.sub_mem_ker _ _

/-- Restricting a representation along a monoid homomorphism shrinks its augmentation submodule. -/
theorem coinvariantsKer_comp_le {G' : Type*} [Monoid G'] (ψ : G' →* G) :
    Coinvariants.ker (ρ.comp ψ) ≤ Coinvariants.ker ρ := by
  rw [Coinvariants.ker, Coinvariants.ker, Submodule.span_le]
  rintro _ ⟨⟨g, x⟩, rfl⟩
  exact Submodule.subset_span ⟨(ψ g, x), rfl⟩

/-- Precomposing a representation with a surjective monoid homomorphism does not change its
augmentation submodule. -/
@[simp]
theorem coinvariantsKer_comp_of_surjective {G' : Type*} [Monoid G'] (ψ : G' →* G)
    (hψ : Function.Surjective ψ) :
    Coinvariants.ker (ρ.comp ψ) = Coinvariants.ker ρ := by
  rw [Coinvariants.ker, Coinvariants.ker]
  exact congrArg (Submodule.span k)
    ((Prod.map_surjective.2 ⟨hψ, Function.surjective_id⟩).range_comp
      fun gv : G × V => ρ gv.1 gv.2 - gv.2)

end Functoriality

/-! ### Orbit sums are invariant -/

section Semiring

variable {k G X : Type*} [Semiring k]

/-- The orbit-sum map `k[X] → k[X ⧸ G]` is invariant under the permutation representation. -/
@[simp]
theorem mapDomainLinearMap_orbitRel_mk_ofMulAction [Group G] [MulAction G X] (g : G) (v : k[X]) :
    mapDomainLinearMap k k (Quotient.mk (orbitRel G X)) (ofMulAction k G X g v) =
      mapDomainLinearMap k k (Quotient.mk (orbitRel G X)) v := by
  induction v using induction_linear <;> simp [*]

/-- The orbit sums of the norm `∑ g, g • v` of `v : k[X]` are `|G|` times those of `v`. -/
@[simp]
theorem _root_.MonoidAlgebra.mapDomainLinearMap_orbitRel_mk_norm_ofMulAction
    [Group G] [Fintype G] [MulAction G X] (v : k[X]) :
    mapDomainLinearMap k k (Quotient.mk (orbitRel G X)) ((ofMulAction k G X).norm v) =
      Fintype.card G • mapDomainLinearMap k k (Quotient.mk (orbitRel G X)) v := by
  simp [Representation.norm, LinearMap.sum_apply]

/-- The permutation representation of a subgroup `H` on `k[X]` is the restriction of that of
`G`. -/
theorem ofMulAction_subgroup [Group G] [MulAction G X] (H : Subgroup G) (h : H) :
    ofMulAction k H X h = ofMulAction k G X h := by
  ext
  simp [Subgroup.smul_def]

end Semiring

/-! ### The coinvariant kernel of a permutation representation -/

section Permutation

variable {k G X : Type*} [CommRing k]

/-- If every `x : X` lies in the `G`-orbit of `f x`, then `v` minus its pushforward along `f`
lies in the coinvariant kernel of the permutation representation `k[X]`. -/
theorem sub_mapDomainLinearMap_mem_coinvariantsKer [Monoid G] [MulAction G X] {f : X → X}
    (hf : ∀ x, ∃ g : G, g • f x = x) (v : k[X]) :
    v - mapDomainLinearMap k k f v ∈ Coinvariants.ker (ofMulAction k G X) := by
  induction v using induction_linear with
  | zero => simp
  | add v w hv hw => simpa [add_sub_add_comm] using add_mem hv hw
  | single x r =>
    obtain ⟨g, hg⟩ := hf x
    exact Coinvariants.mem_ker_of_eq g (single (f x) r) _ <| by simp [hg]

/-- **The coinvariant kernel of a permutation representation.** An element of `k[X]` lies in the
coinvariant kernel of the permutation representation if and only if its coefficients sum to zero
along every `G`-orbit. -/
theorem coinvariantsKer_ofMulAction_eq_ker [Group G] [MulAction G X] :
    Coinvariants.ker (ofMulAction k G X) =
      LinearMap.ker (mapDomainLinearMap k k (Quotient.mk (orbitRel G X))) := by
  refine le_antisymm (Submodule.span_le.2 <| Set.range_subset_iff.2 fun _ ↦ by simp) fun v hv ↦ ?_
  simpa [LinearMap.mem_ker.1 hv] using sub_mapDomainLinearMap_mem_coinvariantsKer
    (f := Quotient.out ∘ Quotient.mk (orbitRel G X))
    (fun x ↦ mem_orbit_symm.1 (Quotient.mk_out (s := orbitRel G X) x)) v

/-- If multiplication by `|G|` is injective on the coefficient ring, an element of the permutation
representation `k[X]` of a finite group `G` with vanishing norm lies in the coinvariant kernel: its
orbit sums are killed by `|G|`, hence vanish. -/
theorem ker_norm_ofMulAction_le_coinvariantsKer [Group G] [Fintype G] [MulAction G X]
    (hk : IsSMulRegular k (Fintype.card G)) :
    LinearMap.ker (ofMulAction k G X).norm ≤ Coinvariants.ker (ofMulAction k G X) := by
  intro v hv
  rw [coinvariantsKer_ofMulAction_eq_ker, LinearMap.mem_ker]
  have h := v.mapDomainLinearMap_orbitRel_mk_norm_ofMulAction (G := G)
  rw [LinearMap.mem_ker.1 hv, map_zero] at h
  ext ω
  have hω := congr($(h).coeff ω)
  simp only [coeff_zero, Finsupp.coe_zero, Pi.zero_apply, coeff_smul_apply] at hω
  exact hk (hω.symm.trans (smul_zero _).symm)

end Permutation

/-! ### The coinvariant kernel of a representation of a generated group -/

section Generators

variable {k G V : Type*} [CommRing k] [Group G] [AddCommGroup V] [Module k V]
  (ρ : Representation k G V)

/-- If `s` generates `G`, the coinvariant kernel of `ρ` is the sum of the ranges of `ρ g - 1` for
`g ∈ s`. -/
theorem coinvariantsKer_eq_iSup_range {s : Set G} (hs : Subgroup.closure s = ⊤) :
    Coinvariants.ker ρ = ⨆ g ∈ s, LinearMap.range (ρ g - LinearMap.id) := by
  refine le_antisymm (Submodule.span_le.2 ?_) <|
    iSup₂_le fun g _ _ ⟨v, hv⟩ ↦ Coinvariants.mem_ker_of_eq g v _ hv
  rintro _ ⟨⟨g, v⟩, rfl⟩
  induction hs.ge (Subgroup.mem_top g) using Subgroup.closure_induction generalizing v with
  | mem g hg => exact Submodule.mem_iSup_of_mem g (Submodule.mem_iSup_of_mem hg ⟨v, rfl⟩)
  | one => simp
  | mul g h _ _ hg hh => simpa [sub_add_sub_cancel] using add_mem (hg (ρ h v)) (hh v)
  | inv g _ hg => simpa using neg_mem (hg (ρ g⁻¹ v))

/-- If `g` generates `G`, the coinvariant kernel of `ρ` is the range of `ρ g - 1`. Unlike
`Representation.FiniteCyclicGroup.coinvariantsKer_eq_range`, `G` need not be finite. -/
theorem coinvariantsKer_eq_range_of_forall_mem_zpowers (g : G) (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    Coinvariants.ker ρ = LinearMap.range (ρ g - LinearMap.id) :=
  (coinvariantsKer_eq_iSup_range ρ <| (Subgroup.zpowers_eq_closure g).symm.trans <|
    (Subgroup.eq_top_iff' _).2 hg).trans iSup_singleton

end Generators

/-! ### The coinvariant kernel of a representation of a finite monoid -/

section Finite

variable {k G V : Type*} [CommRing k] [Monoid G] [Fintype G] [AddCommGroup V] [Module k V]
  {ρ : Representation k G V}

/-- For a finite monoid `G`, the coinvariant kernel of `ρ` consists of the sums
`∑ g, (ρ g (y g) - y g)`, with one term for each monoid element. -/
theorem mem_coinvariantsKer_iff_exists_sum {x : V} :
    x ∈ Coinvariants.ker ρ ↔ ∃ y : G → V, ∑ g, (ρ g (y g) - y g) = x := by
  classical
  refine ⟨fun hx ↦ ?_, fun ⟨y, hy⟩ ↦ hy ▸ Submodule.sum_mem _ fun g _ ↦
    Coinvariants.mem_ker_of_eq g (y g) _ rfl⟩
  induction hx using Submodule.span_induction with
  | mem _ h =>
    obtain ⟨⟨g, v⟩, rfl⟩ := h
    refine ⟨Pi.single g v, ?_⟩
    rw [Finset.sum_eq_single g (fun b _ hb ↦ by simp [hb]) (by simp)]
    simp
  | zero => exact ⟨0, by simp⟩
  | add _ _ _ _ ha hb =>
    obtain ⟨y, rfl⟩ := ha
    obtain ⟨z, rfl⟩ := hb
    exact ⟨y + z, by simp [Finset.sum_add_distrib, sub_add_sub_comm]⟩
  | smul r _ _ ha =>
    obtain ⟨y, rfl⟩ := ha
    exact ⟨r • y, by simp [Finset.smul_sum, smul_sub]⟩

end Finite

/-! ### Orbit sums -/

section OrbitSum

variable {k G X : Type*}

/-- **Membership in the range of `ρ g - 1` via orbit sums.** For the permutation representation
`k[X]`, an element lies in the range of `ρ g - 1` if and only if its coefficients sum to zero along
every orbit of the cyclic subgroup generated by `g`. -/
theorem mem_range_ofMulAction_sub_id_iff [CommRing k] [Group G] [MulAction G X] (g : G) {v : k[X]} :
    v ∈ LinearMap.range (ofMulAction k G X g - LinearMap.id) ↔
      mapDomainLinearMap k k (Quotient.mk (orbitRel (Subgroup.zpowers g) X)) v = 0 := by
  -- `⟨g, _⟩` generates `zpowers g`, whose permutation representation restricts that of `G`
  have hg : ∀ x : Subgroup.zpowers g, x ∈ Subgroup.zpowers ⟨g, Subgroup.mem_zpowers g⟩ :=
    Subgroup.forall_zpowers.2 fun m ↦ ⟨m, Subtype.ext (by simp)⟩
  rw [← ofMulAction_subgroup (Subgroup.zpowers g) ⟨g, Subgroup.mem_zpowers g⟩,
    ← coinvariantsKer_eq_range_of_forall_mem_zpowers _ _ hg, coinvariantsKer_ofMulAction_eq_ker,
    LinearMap.mem_ker]

end OrbitSum

end Representation

namespace MonoidAlgebra

variable {k G X : Type*} [Semiring k] [Group G] [MulAction G X]

/-- If a finset `s` meets every `G`-orbit exactly once, then the element `∑ x ∈ s, single x r` of
`k[X]` has all its orbit sums equal to `r`. -/
theorem coeff_mapDomainLinearMap_orbitRel_sum_single {s : Finset X}
    (hex : ∀ x, ∃ g : G, g • x ∈ s) (hfix : ∀ x ∈ s, ∀ g : G, g • x ∈ s → g • x = x) (r : k)
    (q : orbitRel.Quotient G X) :
    (mapDomainLinearMap k k (Quotient.mk (orbitRel G X)) (∑ x ∈ s, single x r)).coeff q = r := by
  obtain ⟨y, rfl⟩ := Quotient.mk_surjective q
  obtain ⟨g, hg⟩ := hex y
  have hq : Quotient.mk (orbitRel G X) (g • y) = Quotient.mk _ y := Quotient.sound ⟨g, rfl⟩
  simp only [map_sum, mapDomainLinearMap_single, coeff_sum, coeff_single, Finsupp.finsetSum_apply]
  rw [Finset.sum_eq_single_of_mem (g • y) hg fun x hx hne ↦ ?_]
  · simp [hq]
  refine Finsupp.single_eq_of_ne' fun hxy ↦ hne ?_
  obtain ⟨h, rfl⟩ := orbitRel_apply.1 (Quotient.exact (hxy.trans hq.symm))
  exact hfix _ hg h hx

end MonoidAlgebra
