/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Galois.ConjugateFields
public import TauCeti.FieldTheory.GaloisGroups.Embeddings
import Mathlib.FieldTheory.Galois.Infinite

/-!
# Conjugate fields of a polynomial root

Let `x` lie in a normal extension of `F`, and put `N` for the normal closure of `F⟮x⟯` in
that extension.  The simple field `F⟮x⟯` embeds in `N`; this file records its orbit under
`Gal(N/F)`.  These are the distinct conjugate fields generated by the roots of `minpoly F x`.

When the minimal polynomial is separable, the number of these fields is

`[Gal(N/F) : N_G(H)]`,

where `H` is the point stabilizer in the polynomial Galois group, transported to `Gal(N/F)` by
`TauCeti.galEquivNormalClosure`.  Thus conjugate fields are indexed by the normalizer quotient,
not by the generally larger root quotient `G / H`, which indexes the embeddings of `F⟮x⟯`
(see `TauCeti.FieldTheory.GaloisGroups.Embeddings`).

## Main definitions

* `TauCeti.conjugateSimpleFields`: its set of conjugates under `Gal(N/F)`.
* `TauCeti.quotientNormalizerEquivConjugateSimpleFields`: the normalizer quotient indexing
  those fields.
* `TauCeti.quotientGalNormalizerEquivConjugateSimpleFields`: the same indexing through the
  polynomial Galois group.

## Main results

* `TauCeti.quotientGalStabilizerEquivAlgHomSimpleField_fieldRange`: the embedding indexed by
  a root-stabilizer coset has as image the conjugate field indexed by its projection to the
  normalizer quotient.
* `TauCeti.conjugateSimpleFieldsEquivConjugateSubgroups`: the conjugate fields
  correspond to conjugates of a point stabilizer in the polynomial Galois group.
* `TauCeti.ncard_conjugateSimpleFields`: the number of conjugate simple fields is the index of
  the normalizer of their fixing subgroup.
* `TauCeti.exists_root_ncard_conjugateSimpleFields_eq_index_normalizer`: the same formula with
  that fixing subgroup identified as a transported point stabilizer of `minpoly F x`.
-/

public section

namespace TauCeti

open _root_.IntermediateField MulAction Polynomial
open scoped Pointwise

variable {F E : Type*} [Field F] [Field E] [Algebra F E]

/-- The distinct conjugates of `F⟮x⟯` inside its normal closure. -/
def conjugateSimpleFields (x : E) :
    Set (IntermediateField F (normalClosure F F⟮x⟯ E)) :=
  IntermediateField.conjugateFields (F⟮x⟯.restrict (le_normalClosure F⟮x⟯))

/-- A field is conjugate to `F⟮x⟯` exactly when it is the image of that field under an
automorphism of its normal closure. -/
theorem mem_conjugateSimpleFields_iff {x : E}
    {K : IntermediateField F (normalClosure F F⟮x⟯ E)} :
    K ∈ conjugateSimpleFields (F := F) x ↔
      ∃ σ : normalClosure F F⟮x⟯ E ≃ₐ[F] normalClosure F F⟮x⟯ E,
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).map σ.toAlgHom = K :=
  IntermediateField.mem_conjugateFields_iff

variable [Normal F E]

/-- The conjugate simple fields are precisely the fields generated by roots of the minimal
polynomial inside the normal closure. -/
@[simp]
theorem mem_conjugateSimpleFields_iff_adjoin_root {x : E}
    {K : IntermediateField F (normalClosure F F⟮x⟯ E)} :
    K ∈ conjugateSimpleFields (F := F) x ↔
      ∃ y : (minpoly F x).rootSet (normalClosure F F⟮x⟯ E),
        K = F⟮(y : normalClosure F F⟮x⟯ E)⟯ := by
  let N := normalClosure F F⟮x⟯ E
  let a : N := ⟨x, le_normalClosure F⟮x⟯ (mem_adjoin_simple_self F x)⟩
  have ha : a ∈ (minpoly F x).rootSet N := by
    rw [mem_rootSet_of_ne (minpoly.ne_zero (Algebra.IsIntegral.isIntegral x))]
    apply N.val.injective
    rw [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
      ← aeval_algHom_apply N.val, map_zero]
    exact minpoly.aeval F x
  have hbase : F⟮x⟯.restrict (le_normalClosure F⟮x⟯) = F⟮a⟯ := by
    apply lift_injective N
    rw [lift_adjoin_simple, lift_restrict]
  constructor
  · intro hK
    obtain ⟨σ, hσ⟩ := mem_conjugateSimpleFields_iff.mp hK
    let y : (minpoly F x).rootSet N := ⟨σ a, smul_mem_rootSet σ ha⟩
    refine ⟨y, ?_⟩
    rw [← hσ, hbase, adjoin_map]
    simp only [Set.image_singleton]
    rfl
  · rintro ⟨y, rfl⟩
    obtain ⟨σ, hσ⟩ := mem_orbit_iff.mp
      ((Set.ext_iff.mp (coe_rootSet_eq_orbit_of_irreducible
        (minpoly.irreducible (Algebra.IsIntegral.isIntegral x)) ha) y).mp y.2)
    apply mem_conjugateSimpleFields_iff.mpr
    refine ⟨σ, ?_⟩
    rw [hbase, adjoin_map, Set.image_singleton]
    exact congrArg (fun z : N ↦ F⟮z⟯) hσ

/-- For a root whose point stabilizer fixes `F⟮x⟯`, conjugates of the simple field correspond
to conjugates of that stabilizer in the polynomial Galois group. Such a root exists by
`exists_root_map_stabilizer_eq_fixingSubgroup`. -/
noncomputable def conjugateSimpleFieldsEquivConjugateSubgroups (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup) :
    conjugateSimpleFields (F := F) x ≃
      MulAction.orbit (ConjAct (minpoly F x).Gal) (stabilizer (minpoly F x).Gal y) := by
  let _ : FiniteDimensional F (normalClosure F F⟮x⟯ E) :=
    finiteDimensional_normalClosure_adjoin_simple (Algebra.IsIntegral.isIntegral x)
  let _ : IsGalois F (normalClosure F F⟮x⟯ E) :=
    isGalois_normalClosure_adjoin_simple x hsep
  let e := MulEquiv.conjugateSubgroupsEquiv (galEquivNormalClosure (F := F) (E := E) x)
    (stabilizer (minpoly F x).Gal y)
  have he : MulAction.orbit (ConjAct (minpoly F x).Gal) (stabilizer (minpoly F x).Gal y) ≃
      MulAction.orbit (ConjAct Gal(normalClosure F F⟮x⟯ E/F))
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup :=
    e.trans (Equiv.subtypeEquivRight fun J ↦ by
      rw [← hy, MulEquiv.toMonoidHom_eq_coe])
  exact (IntermediateField.conjugateFieldsEquivConjugateSubgroups
    (F⟮x⟯.restrict (le_normalClosure F⟮x⟯))).trans he.symm

/-- The polynomial-group correspondence sends a conjugate simple field to the inverse image
of its fixing subgroup under the normal-closure Galois-group equivalence. -/
@[simp]
theorem conjugateSimpleFieldsEquivConjugateSubgroups_apply (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup)
    (K : conjugateSimpleFields (F := F) x) :
    ((conjugateSimpleFieldsEquivConjugateSubgroups x hsep y hy K).1).map
      ((galEquivNormalClosure (F := F) (E := E) x) : _ →* _) = K.1.fixingSubgroup := by
  let _ : FiniteDimensional F (normalClosure F F⟮x⟯ E) :=
    finiteDimensional_normalClosure_adjoin_simple (Algebra.IsIntegral.isIntegral x)
  let _ : IsGalois F (normalClosure F F⟮x⟯ E) :=
    isGalois_normalClosure_adjoin_simple x hsep
  let E₀ := F⟮x⟯.restrict (le_normalClosure F⟮x⟯)
  let e := galEquivNormalClosure (F := F) (E := E) x
  let f := IntermediateField.conjugateFieldsEquivConjugateSubgroups E₀
  let g := MulEquiv.conjugateSubgroupsEquiv e (stabilizer (minpoly F x).Gal y)
  let h : MulAction.orbit (ConjAct (minpoly F x).Gal)
      (stabilizer (minpoly F x).Gal y) ≃
      MulAction.orbit (ConjAct Gal(normalClosure F F⟮x⟯ E/F)) E₀.fixingSubgroup :=
    g.trans (Equiv.subtypeEquivRight fun J ↦ by
      rw [← hy, MulEquiv.toMonoidHom_eq_coe])
  -- Expose the composite's inverse: `h.symm` transports the subgroup, then `f` takes
  -- the fixing subgroup. The remaining calculation uses the two component apply lemmas.
  change ((h.symm (f K)).1).map (e : _ →* _) = K.1.fixingSubgroup
  have hh (J) : (h J).1 = J.1.map (e : _ →* _) := by
    -- The subtype transport along `hy` preserves the subgroup value.
    change (g J).1 = J.1.map (e : _ →* _)
    exact MulEquiv.conjugateSubgroupsEquiv_apply e _ J
  calc
    ((h.symm (f K)).1).map (e : _ →* _) = (h (h.symm (f K))).1 := (hh _).symm
    _ = (f K).1 := congrArg Subtype.val (h.apply_symm_apply _)
    _ = K.1.fixingSubgroup :=
      IntermediateField.conjugateFieldsEquivConjugateSubgroups_apply E₀ K

/-- The fixing subgroup of the field corresponding to a conjugate point stabilizer is its
transported subgroup. -/
theorem fixingSubgroup_conjugateSimpleFieldsEquivConjugateSubgroups_symm_apply (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup)
    (H : MulAction.orbit (ConjAct (minpoly F x).Gal)
      (stabilizer (minpoly F x).Gal y)) :
    (((conjugateSimpleFieldsEquivConjugateSubgroups x hsep y hy).symm H).1).fixingSubgroup =
      H.1.map ((galEquivNormalClosure (F := F) (E := E) x) : _ →* _) := by
  rw [← conjugateSimpleFieldsEquivConjugateSubgroups_apply x hsep y hy
    ((conjugateSimpleFieldsEquivConjugateSubgroups x hsep y hy).symm H),
    Equiv.apply_symm_apply]

/-- The field corresponding to a conjugate point stabilizer is the fixed field of its
transported subgroup. -/
@[simp]
theorem conjugateSimpleFieldsEquivConjugateSubgroups_symm_apply (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup)
    (H : MulAction.orbit (ConjAct (minpoly F x).Gal)
      (stabilizer (minpoly F x).Gal y)) :
    ((conjugateSimpleFieldsEquivConjugateSubgroups x hsep y hy).symm H).1 =
      fixedField (H.1.map ((galEquivNormalClosure (F := F) (E := E) x) : _ →* _)) := by
  let _ : IsGalois F (normalClosure F F⟮x⟯ E) :=
    isGalois_normalClosure_adjoin_simple x hsep
  rw [← fixingSubgroup_conjugateSimpleFieldsEquivConjugateSubgroups_symm_apply x hsep y hy H,
    InfiniteGalois.fixedField_fixingSubgroup]

/-- A normalizer coset for the simple field specifies one of its conjugate images. -/
noncomputable def quotientNormalizerEquivConjugateSimpleFields (x : E)
    (hsep : (minpoly F x).Separable) :
    Gal(normalClosure F F⟮x⟯ E/F) ⧸
      Subgroup.normalizer
        ((F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup :
          Set Gal(normalClosure F F⟮x⟯ E/F)) ≃ conjugateSimpleFields (F := F) x := by
  let _ : FiniteDimensional F (normalClosure F F⟮x⟯ E) :=
    finiteDimensional_normalClosure_adjoin_simple (Algebra.IsIntegral.isIntegral x)
  let _ : IsGalois F (normalClosure F F⟮x⟯ E) :=
    isGalois_normalClosure_adjoin_simple x hsep
  exact IntermediateField.quotientNormalizerEquivConjugateFields
    (F⟮x⟯.restrict (le_normalClosure F⟮x⟯))

/-- A coset representative sends the simple field to its image under that automorphism. -/
@[simp]
theorem quotientNormalizerEquivConjugateSimpleFields_mk (x : E)
    (hsep : (minpoly F x).Separable) (σ : Gal(normalClosure F F⟮x⟯ E/F)) :
    ((quotientNormalizerEquivConjugateSimpleFields x hsep (QuotientGroup.mk σ)).1) =
      σ • (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)) := by
  let _ : FiniteDimensional F (normalClosure F F⟮x⟯ E) :=
    finiteDimensional_normalClosure_adjoin_simple (Algebra.IsIntegral.isIntegral x)
  let _ : IsGalois F (normalClosure F F⟮x⟯ E) :=
    isGalois_normalClosure_adjoin_simple x hsep
  exact IntermediateField.quotientNormalizerEquivConjugateFields_mk
    (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)) σ

/-- The normalizer-coset parametrization of simple fields is Galois-equivariant. -/
@[simp]
theorem quotientNormalizerEquivConjugateSimpleFields_smul (x : E)
    (hsep : (minpoly F x).Separable) (σ : Gal(normalClosure F F⟮x⟯ E/F))
    (q : Gal(normalClosure F F⟮x⟯ E/F) ⧸
      Subgroup.normalizer
        ((F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup :
          Set Gal(normalClosure F F⟮x⟯ E/F))) :
    (quotientNormalizerEquivConjugateSimpleFields x hsep (σ • q)).1 =
      σ • (quotientNormalizerEquivConjugateSimpleFields x hsep q).1 := by
  let _ : FiniteDimensional F (normalClosure F F⟮x⟯ E) :=
    finiteDimensional_normalClosure_adjoin_simple (Algebra.IsIntegral.isIntegral x)
  let _ : IsGalois F (normalClosure F F⟮x⟯ E) :=
    isGalois_normalClosure_adjoin_simple x hsep
  exact IntermediateField.quotientNormalizerEquivConjugateFields_smul
    (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)) σ q

/-- When a point stabilizer corresponds to the fixing subgroup of the simple field, the
polynomial Galois group equivalence sends its normalizer to the normalizer of that fixing
subgroup. -/
private theorem map_normalizer_stabilizer_galEquivNormalClosure (x : E)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup) :
    (Subgroup.normalizer
      (stabilizer (minpoly F x).Gal y : Set (minpoly F x).Gal)).map
        ((galEquivNormalClosure (F := F) (E := E) x) : _ →* _) =
      Subgroup.normalizer
        ((F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup :
          Set Gal(normalClosure F F⟮x⟯ E/F)) := by
  rw [← hy]
  simpa only [MulEquiv.toMonoidHom_eq_coe] using
    Subgroup.map_equiv_normalizer_eq (stabilizer (minpoly F x).Gal y)
      (galEquivNormalClosure (F := F) (E := E) x)

/-- Cosets of the normalizer of a point stabilizer in the polynomial Galois group index
the conjugate images of the simple field. -/
noncomputable def quotientGalNormalizerEquivConjugateSimpleFields (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup) :
    (minpoly F x).Gal ⧸
      Subgroup.normalizer (stabilizer (minpoly F x).Gal y : Set (minpoly F x).Gal) ≃
        conjugateSimpleFields (F := F) x := by
  let e := galEquivNormalClosure (F := F) (E := E) x
  have hn := map_normalizer_stabilizer_galEquivNormalClosure x y hy
  exact (QuotientGroup.congrOfMapEq e hn).trans
    (quotientNormalizerEquivConjugateSimpleFields x hsep)

/-- A polynomial Galois coset represented by `σ` gives the field obtained by the
corresponding automorphism of the normal closure. -/
@[simp]
theorem quotientGalNormalizerEquivConjugateSimpleFields_mk (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup)
    (σ : (minpoly F x).Gal) :
    ((quotientGalNormalizerEquivConjugateSimpleFields x hsep y hy
      (QuotientGroup.mk σ)).1) =
        galEquivNormalClosure x σ • (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)) := by
  let e := galEquivNormalClosure (F := F) (E := E) x
  have hn := map_normalizer_stabilizer_galEquivNormalClosure x y hy
  -- The composite equivalence is defined with local transports; expose its final
  -- application so the quotient transport rule can rewrite the representative.
  change ((quotientNormalizerEquivConjugateSimpleFields x hsep
    (QuotientGroup.congrOfMapEq e hn (QuotientGroup.mk σ))).1) = _
  rw [QuotientGroup.congrOfMapEq_mk]
  exact quotientNormalizerEquivConjugateSimpleFields_mk x hsep _

/-- The field range of the embedding indexed by a root-stabilizer coset is the conjugate
field indexed by the image of that coset in the normalizer quotient. -/
theorem quotientGalStabilizerEquivAlgHomSimpleField_fieldRange (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup)
    (q : (minpoly F x).Gal ⧸ stabilizer (minpoly F x).Gal y) :
    (quotientGalStabilizerEquivAlgHomSimpleField x y q).fieldRange =
      (quotientGalNormalizerEquivConjugateSimpleFields x hsep y hy
        (Subgroup.quotientMapOfLE Subgroup.le_normalizer q)).1 := by
  obtain ⟨σ, rfl⟩ := QuotientGroup.mk_surjective q
  let N := normalClosure F F⟮x⟯ E
  let e := splittingFieldEquivNormalClosure (F := F) (E := E) x
  have hgen : (F⟮AdjoinSimple.gen F x⟯ : IntermediateField F F⟮x⟯) = ⊤ := by
    apply (IntermediateField.lift_injective F⟮x⟯)
    rw [IntermediateField.lift_adjoin_simple, IntermediateField.lift_top]
    rfl
  have hrange (φ : F⟮x⟯ →ₐ[F] N) :
      φ.fieldRange = F⟮φ (AdjoinSimple.gen F x)⟯ := by
    rw [AlgHom.fieldRange_eq_map, ← hgen, IntermediateField.adjoin_map]
    simp only [Set.image_singleton]
  let _ : IsGalois F N := isGalois_normalClosure_adjoin_simple x hsep
  have hbase : F⟮(e y : N)⟯ = F⟮x⟯.restrict (le_normalClosure F⟮x⟯) := by
    apply (InfiniteGalois.fixedField_fixingSubgroup _).symm.trans
    rw [← InfiniteGalois.fixedField_fixingSubgroup
      (F⟮x⟯.restrict (le_normalClosure F⟮x⟯))]
    congr 1
    exact (map_stabilizer_galEquivNormalClosure (F := F) (E := E) x y).symm.trans hy
  rw [hrange, quotientGalStabilizerEquivAlgHomSimpleField_mk_gen,
    Subgroup.quotientMapOfLE_apply_mk, quotientGalNormalizerEquivConjugateSimpleFields_mk]
  have heval : e (σ • (y : (minpoly F x).SplittingField)) =
      galEquivNormalClosure x σ (e y) :=
    (galEquivNormalClosure_apply x σ y).symm
  rw [heval]
  simpa only [IntermediateField.adjoin_map, Set.image_singleton,
    AlgEquiv.toAlgHom_apply, AlgEquiv.smul_intermediateField_def] using
    congrArg (fun K : IntermediateField F N ↦
      K.map (galEquivNormalClosure x σ).toAlgHom) hbase

/-- The polynomial normalizer-coset parametrization respects the transported Galois action. -/
@[simp]
theorem quotientGalNormalizerEquivConjugateSimpleFields_smul (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup)
    (σ : (minpoly F x).Gal)
    (q : (minpoly F x).Gal ⧸
      Subgroup.normalizer (stabilizer (minpoly F x).Gal y : Set (minpoly F x).Gal)) :
    (quotientGalNormalizerEquivConjugateSimpleFields x hsep y hy (σ • q)).1 =
      galEquivNormalClosure x σ •
        (quotientGalNormalizerEquivConjugateSimpleFields x hsep y hy q).1 := by
  induction q using Quotient.inductionOn' with
  | _ τ =>
    -- The quotient action on representatives reduces definitionally to multiplication.
    change (quotientGalNormalizerEquivConjugateSimpleFields x hsep y hy
      (QuotientGroup.mk (σ * τ))).1 = _
    simp [quotientGalNormalizerEquivConjugateSimpleFields_mk, mul_smul]

/-- For a separable minimal polynomial, the number of conjugates of `F⟮x⟯` is the index of
the normalizer of its fixing subgroup in the Galois group of the normal closure. -/
@[simp]
theorem ncard_conjugateSimpleFields (x : E) (hsep : (minpoly F x).Separable) :
    (conjugateSimpleFields (F := F) x).ncard =
      (Subgroup.normalizer
        ((F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup :
          Set Gal(normalClosure F F⟮x⟯ E/F))).index := by
  let _ : FiniteDimensional F (normalClosure F F⟮x⟯ E) :=
    finiteDimensional_normalClosure_adjoin_simple (Algebra.IsIntegral.isIntegral x)
  let _ : IsGalois F (normalClosure F F⟮x⟯ E) :=
    isGalois_normalClosure_adjoin_simple x hsep
  exact IntermediateField.ncard_conjugateFields
    (F⟮x⟯.restrict (le_normalClosure F⟮x⟯))

/-- The number of conjugate simple fields is the index of the normalizer of a point
stabilizer in the polynomial Galois group, when that stabilizer fixes the original field. -/
theorem ncard_conjugateSimpleFields_eq_index_normalizer (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField)
    (hy : (stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup) :
    (conjugateSimpleFields (F := F) x).ncard =
      (Subgroup.normalizer
        (stabilizer (minpoly F x).Gal y : Set (minpoly F x).Gal)).index := by
  let e := galEquivNormalClosure (F := F) (E := E) x
  rw [ncard_conjugateSimpleFields (F := F) x hsep, ← hy]
  rw [← Subgroup.map_equiv_normalizer_eq]
  exact Subgroup.index_map_equiv _ e

/-- A root corresponding to the original generator identifies the fixing subgroup of `F⟮x⟯`
with its point stabilizer.  Hence the number of conjugate fields is the index of the normalizer
of that transported stabilizer. -/
theorem exists_root_ncard_conjugateSimpleFields_eq_index_normalizer (x : E)
    (hsep : (minpoly F x).Separable) :
    ∃ y : (minpoly F x).rootSet (minpoly F x).SplittingField,
      (splittingFieldEquivNormalClosure (F := F) (E := E) x y : E) = x ∧
      (conjugateSimpleFields (F := F) x).ncard =
        (Subgroup.normalizer
          (((stabilizer (minpoly F x).Gal y).map
            (galEquivNormalClosure (F := F) (E := E) x).toMonoidHom :
              Subgroup Gal(normalClosure F F⟮x⟯ E/F)) :
            Set Gal(normalClosure F F⟮x⟯ E/F))).index := by
  obtain ⟨y, hy, hstabilizer⟩ :=
    exists_root_map_stabilizer_eq_fixingSubgroup (F := F) (E := E) x
  refine ⟨y, hy, ?_⟩
  rw [ncard_conjugateSimpleFields (F := F) x hsep, hstabilizer]

end TauCeti
