/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Polynomial.Tschirnhaus
public import Mathlib.FieldTheory.PolynomialGaloisGroup

/-!
# Tschirnhaus transforms and the Galois group

A Tschirnhaus transform `Polynomial.tschirnhausPolynomial f T` replaces the roots `α` of `f` by
the values `T(α)`. The coefficient-side construction and the root correspondence are developed in
`TauCeti/RingTheory/Polynomial/Tschirnhaus.lean`. This file shows that for a separable `f`
an *admissible* transform — one that separates the roots of `f` — changes neither the splitting
field nor the Galois group.

Separability of `f` is assumed by the two splitting-field results. The Galois correspondence
enters in one place only, the splitting-field argument
`Polynomial.TschirnhausAdmissible.isSplittingField`, which computes the fixing subgroup of the
field generated by the values `T(α)`. The conjugacy of the Galois images needs only that the
transform is admissible.

For any `f` and any field extension `E` in which `f` splits, the roots of the transform are
exactly the values of `T` at the roots of `f`, with multiplicity, so the transform splits in `E`
as well.
Consequently restriction along Mathlib's chosen embedding of splitting fields gives a surjection
from the Galois group of `f` onto the Galois group of any Tschirnhaus transform. On roots, this
quotient map intertwines the polynomial map `α ↦ T(α)`. These declarations specialize
`Polynomial.Gal.restrict`, `Polynomial.Gal.restrict_surjective`, and
`Polynomial.Gal.galActionHom_restrict` from Mathlib's `Mathlib.FieldTheory.PolynomialGaloisGroup`.
Admissibility is `Polynomial.TschirnhausAdmissible f T`: injectivity of `α ↦ T(α)` on the root set
of `f` in its splitting field. Under it, a separable `f` has a separable transform and each
splitting field of `f` is a splitting field of the transform. For any `f`, the Galois groups are
isomorphic and their images inside the permutations of their respective root sets are conjugate
along `α ↦ T(α)`. When `f = 0`, the root sets are empty and both Galois groups are trivial.

That last statement is what carries information back: a constraint on the Galois image of the
transform — typically an upper bound read off a resolvent that became separable after the
substitution — is a constraint on the Galois image of `f`.

## Main results

* `Polynomial.Gal.restrictTschirnhaus` and
  `Polynomial.Gal.restrictTschirnhaus_surjective`: a transform's Galois group is a quotient of
  the original Galois group.
* `Polynomial.Gal.tschirnhausActionHom_apply_rootMap`: the induced action intertwines the map
  `α ↦ T(α)` on roots.
* `Polynomial.TschirnhausAdmissible.isSplittingField` and
  `Polynomial.TschirnhausAdmissible.nonempty_algEquiv_splittingField`: the splitting fields agree.
* `Polynomial.TschirnhausAdmissible.nonempty_mulEquiv_gal`: the Galois groups are isomorphic.
* `Polynomial.TschirnhausAdmissible.range_galActionHom_eq_map_rootSetEquiv`: the two Galois
  images are conjugate along the canonical bijection `α ↦ T(α)` of root sets.
* `Polynomial.TschirnhausAdmissible.map_range_galActionHom_tschirnhausPolynomial`: numbering the
  roots of the transform through that bijection, the two Galois images are the same subgroup.

## References

* H. Cohen, *A Course in Computational Algebraic Number Theory*, §6.3.
-/

public section

noncomputable section

open Polynomial

namespace Polynomial

variable {F : Type*} [Field F] {f T : F[X]}

section Extension

variable {E : Type*} [Field E] [Algebra F E]

/-- Automorphisms that agree on the roots of an admissible Tschirnhaus transform agree on the
roots of the original polynomial. -/
theorem TschirnhausAdmissible.eqOn_rootSet (h : TschirnhausAdmissible f T)
    (hs : (f.map (algebraMap F E)).Splits) {φ ψ : E ≃ₐ[F] E}
    (hφψ : Set.EqOn φ ψ ((f.tschirnhausPolynomial T).rootSet E)) :
    Set.EqOn φ ψ (f.rootSet E) := by
  intro x hx
  apply (tschirnhausAdmissible_iff_injOn hs).mp h
  · exact rootSet_mapsTo φ.toAlgHom hx
  · exact rootSet_mapsTo ψ.toAlgHom hx
  · have hmem : aeval x T ∈ (f.tschirnhausPolynomial T).rootSet E := by
      exact (h.bijOn_rootSet hs).mapsTo hx
    simpa only [aeval_algHom_apply] using hφψ hmem

/-- Two automorphisms of a splitting field of `f` are equal if they agree on every `T(α)`, when
`T` is admissible for `f`. -/
theorem TschirnhausAdmissible.algEquiv_ext [IsSplittingField F E f]
    (h : TschirnhausAdmissible f T) {φ ψ : E ≃ₐ[F] E}
    (hφψ : ∀ x ∈ f.rootSet E, φ (aeval x T) = ψ (aeval x T)) : φ = ψ := by
  have hs : (f.map (algebraMap F E)).Splits := IsSplittingField.splits E f
  have hroots : Set.EqOn φ ψ (f.rootSet E) := h.eqOn_rootSet hs fun y hy ↦ by
    obtain ⟨x, hx, rfl⟩ := (h.bijOn_rootSet hs).surjOn hy
    exact hφψ x hx
  have heq := AlgHom.ext_of_adjoin_eq_top
    (φ₁ := φ.toAlgHom) (φ₂ := ψ.toAlgHom)
    (IsSplittingField.adjoin_rootSet (L := E) f) hroots
  exact AlgEquiv.ext fun x ↦ DFunLike.congr_fun heq x

end Extension

namespace Gal

/-- Restriction from the Galois group of a polynomial to that of a Tschirnhaus transform.

The transform splits in the splitting field of the original polynomial, so restriction along
the embedding of splitting fields chosen by `Polynomial.Gal.restrict` defines this homomorphism
without an admissibility hypothesis. -/
noncomputable def restrictTschirnhaus (f T : F[X]) :
    f.Gal →* (f.tschirnhausPolynomial T).Gal := by
  letI : Fact (((f.tschirnhausPolynomial T).map
      (algebraMap F f.SplittingField)).Splits) :=
    ⟨splits_map_tschirnhausPolynomial_field (SplittingField.splits f) T⟩
  exact restrict (f.tschirnhausPolynomial T) f.SplittingField

/-- The Galois group of a Tschirnhaus transform is a quotient of the Galois group of the
original polynomial. No separation hypothesis on the transformed roots is needed. -/
theorem restrictTschirnhaus_surjective (f T : F[X]) :
    Function.Surjective (restrictTschirnhaus f T) := by
  let _ : Fact (((f.tschirnhausPolynomial T).map
      (algebraMap F f.SplittingField)).Splits) :=
    ⟨splits_map_tschirnhausPolynomial_field (SplittingField.splits f) T⟩
  let _ : Normal F f.SplittingField := Normal.of_isSplittingField f
  rw [restrictTschirnhaus]
  exact restrict_surjective (f.tschirnhausPolynomial T) f.SplittingField

/-- The action of the original Galois group on the roots of a Tschirnhaus transform, obtained by
restricting to the transform's Galois group. -/
noncomputable def tschirnhausActionHom (f T : F[X]) :
    f.Gal →* Equiv.Perm ((f.tschirnhausPolynomial T).rootSet f.SplittingField) := by
  letI : Fact (((f.tschirnhausPolynomial T).map
      (algebraMap F f.SplittingField)).Splits) :=
    ⟨splits_map_tschirnhausPolynomial_field (SplittingField.splits f) T⟩
  exact (galActionHom (f.tschirnhausPolynomial T) f.SplittingField).comp
    (restrictTschirnhaus f T)

/-- The action induced by restriction on each transformed root is the original splitting-field
automorphism. -/
@[simp]
theorem coe_tschirnhausActionHom_apply (f T : F[X]) (g : f.Gal)
    (y : (f.tschirnhausPolynomial T).rootSet f.SplittingField) :
    ↑(tschirnhausActionHom f T g y) = g y := by
  let _ : Fact (((f.tschirnhausPolynomial T).map
      (algebraMap F f.SplittingField)).Splits) :=
    ⟨splits_map_tschirnhausPolynomial_field (SplittingField.splits f) T⟩
  rw [tschirnhausActionHom, MonoidHom.comp_apply, restrictTschirnhaus]
  exact galActionHom_restrict (f.tschirnhausPolynomial T) f.SplittingField g y

/-- The root map `α ↦ T(α)` is equivariant for restriction to the Galois group of the
Tschirnhaus transform. -/
@[simp]
theorem tschirnhausActionHom_apply_rootMap (f T : F[X]) (g : f.Gal)
    (x : f.rootSet f.SplittingField) :
    tschirnhausActionHom f T g (tschirnhausRootMap f T x) =
      tschirnhausRootMap f T ⟨g (x : f.SplittingField), rootSet_mapsTo g.toAlgHom x.2⟩ := by
  apply Subtype.ext
  rw [coe_tschirnhausActionHom_apply, coe_tschirnhausRootMap,
    coe_tschirnhausRootMap, aeval_algHom_apply]

end Gal

/-- **Every splitting field of `f` is a splitting field of an admissible transform.** For a
separable `f` and an admissible `T`, the transform splits in any splitting field `L` of `f` and
its roots generate `L` over `F`. -/
theorem TschirnhausAdmissible.isSplittingField {L : Type*} [Field L] [Algebra F L]
    [IsSplittingField F L f] (h : TschirnhausAdmissible f T) (hsep : f.Separable) :
    IsSplittingField F L (f.tschirnhausPolynomial T) := by
  have hsp : (f.map (algebraMap F L)).Splits := IsSplittingField.splits L f
  let _ : FiniteDimensional F L := IsSplittingField.finiteDimensional L f
  have : IsGalois F L := IsGalois.of_separable_splitting_field hsep
  have hTsp := splits_map_tschirnhausPolynomial_field hsp T
  refine ⟨hTsp, ?_⟩
  rw [← IntermediateField.adjoin_eq_top_iff]
  set M := IntermediateField.adjoin F ((f.tschirnhausPolynomial T).rootSet L) with hM
  have hfix : M.fixingSubgroup = ⊥ := by
    rw [eq_bot_iff]
    intro ϕ hϕ
    apply Subgroup.mem_bot.mpr
    apply h.algEquiv_ext
    intro α hα
    have hmem : aeval α T ∈ (f.tschirnhausPolynomial T).rootSet L := by
      exact (h.bijOn_rootSet hsp).mapsTo hα
    have h1 : ϕ (aeval α T) = aeval α T :=
        (mem_fixingSubgroup_iff Gal(L/F)).mp hϕ _
          (hM ▸ IntermediateField.subset_adjoin F _ hmem)
    simpa using h1
  rw [← IsGalois.fixedField_fixingSubgroup M, hfix, IntermediateField.fixedField_bot]

/-- The splitting field of `f` is a splitting field of an admissible transform, so the two
splitting fields agree up to an `F`-algebra equivalence. -/
theorem TschirnhausAdmissible.nonempty_algEquiv_splittingField (h : TschirnhausAdmissible f T)
    (hsep : f.Separable) :
    Nonempty (f.SplittingField ≃ₐ[F] (f.tschirnhausPolynomial T).SplittingField) :=
  haveI := h.isSplittingField (L := f.SplittingField) hsep
  ⟨IsSplittingField.algEquiv f.SplittingField (f.tschirnhausPolynomial T)⟩

/-- **An admissible Tschirnhaus transform has the same Galois group as the original polynomial.**
This includes `f = 0`, when both Galois groups are trivial. -/
theorem TschirnhausAdmissible.nonempty_mulEquiv_gal (h : TschirnhausAdmissible f T) :
    Nonempty ((f.tschirnhausPolynomial T).Gal ≃* f.Gal) := by
  have hsp : (f.map (algebraMap F f.SplittingField)).Splits := SplittingField.splits f
  let _ : Fact (((f.tschirnhausPolynomial T).map
      (algebraMap F f.SplittingField)).Splits) :=
    ⟨splits_map_tschirnhausPolynomial_field hsp T⟩
  let _ : Normal F f.SplittingField := Normal.of_isSplittingField f
  refine ⟨(MulEquiv.ofBijective (Gal.restrict (f.tschirnhausPolynomial T) f.SplittingField)
    ⟨?_, Gal.restrict_surjective (f.tschirnhausPolynomial T) f.SplittingField⟩).symm⟩
  intro φ ψ hφψ
  apply h.algEquiv_ext
  intro x hx
  let y := h.rootSetEquiv hsp ⟨x, hx⟩
  have heq := congrArg (fun σ ↦
    (((Gal.galActionHom (f.tschirnhausPolynomial T) f.SplittingField) σ y :
      (f.tschirnhausPolynomial T).rootSet f.SplittingField) : f.SplittingField)) hφψ
  rw [Gal.galActionHom_restrict, Gal.galActionHom_restrict] at heq
  simpa [y] using heq

section GaloisImage

variable {E : Type*} [Field E] [Algebra F E]

/-- The canonical root-set equivalence for an admissible Tschirnhaus transform intertwines the
root actions induced by every automorphism of a common splitting extension. -/
theorem TschirnhausAdmissible.galActionHom_restrict_rootSetEquiv
    (h : TschirnhausAdmissible f T)
    [hfsp : Fact ((f.map (algebraMap F E)).Splits)]
    [Fact (((f.tschirnhausPolynomial T).map (algebraMap F E)).Splits)]
    (φ : Gal(E/F)) (x : f.rootSet E) :
    (Gal.galActionHom (f.tschirnhausPolynomial T) E)
        ((Gal.restrict (f.tschirnhausPolynomial T) E) φ)
        (h.rootSetEquiv hfsp.out x) =
      h.rootSetEquiv hfsp.out
        ((Gal.galActionHom f E) ((Gal.restrict f E) φ) x) := by
  apply Subtype.ext
  rw [Gal.galActionHom_restrict, h.coe_rootSetEquiv_apply,
    h.coe_rootSetEquiv_apply, Gal.galActionHom_restrict, aeval_algHom_apply]

/-- **The Galois images of `f` and of an admissible transform are conjugate.** In any normal
extension where both polynomials split, they are conjugate along the canonical root equivalence
`α ↦ T(α)`. -/
theorem TschirnhausAdmissible.range_galActionHom_eq_map_rootSetEquiv
    [Normal F E] (h : TschirnhausAdmissible f T)
    [hfsp : Fact ((f.map (algebraMap F E)).Splits)]
    [Fact (((f.tschirnhausPolynomial T).map (algebraMap F E)).Splits)] :
    (Gal.galActionHom (f.tschirnhausPolynomial T) E).range =
      (Gal.galActionHom f E).range.map
        (Equiv.permCongrHom (h.rootSetEquiv hfsp.out)).toMonoidHom := by
  let e := h.rootSetEquiv hfsp.out
  have hcomp : (Gal.galActionHom (f.tschirnhausPolynomial T) E).comp
      (Gal.restrict (f.tschirnhausPolynomial T) E) =
      (Equiv.permCongrHom e).toMonoidHom.comp
        ((Gal.galActionHom f E).comp (Gal.restrict f E)) := by
    refine MonoidHom.ext fun φ ↦ Equiv.ext fun y ↦ ?_
    simpa [e] using h.galActionHom_restrict_rootSetEquiv φ (e.symm y)
  have hg : (Gal.galActionHom (f.tschirnhausPolynomial T) E).range =
      ((Gal.galActionHom (f.tschirnhausPolynomial T) E).comp
        (Gal.restrict (f.tschirnhausPolynomial T) E)).range := by
    rw [MonoidHom.range_comp,
      MonoidHom.range_eq_top.mpr (Gal.restrict_surjective (f.tschirnhausPolynomial T) E),
      ← MonoidHom.range_eq_map]
  rw [hg, hcomp, MonoidHom.range_comp, MonoidHom.range_comp,
    MonoidHom.range_eq_top.mpr (Gal.restrict_surjective f E), ← MonoidHom.range_eq_map]

/-- **The Galois images agree once the roots are numbered compatibly.** Number the roots of `f`
by `e`, and the roots of an admissible transform by `T(α) ↦ e α`. Read through these numberings,
the Galois images of `f` and of the transform are the same subgroup of `Equiv.Perm ι`. A
statement about the image of the transform read through some numbering, such as the subgroup bound
that a resolvent of the transform provides, is therefore a statement about the image of `f`. -/
theorem TschirnhausAdmissible.map_range_galActionHom_tschirnhausPolynomial
    [Normal F E] (h : TschirnhausAdmissible f T)
    [hfsp : Fact ((f.map (algebraMap F E)).Splits)]
    [Fact (((f.tschirnhausPolynomial T).map (algebraMap F E)).Splits)]
    {ι : Type*} (e : f.rootSet E ≃ ι) :
    (Gal.galActionHom (f.tschirnhausPolynomial T) E).range.map
        (((h.rootSetEquiv hfsp.out).symm.trans e).permCongrHom : _ →* Equiv.Perm ι) =
      (Gal.galActionHom f E).range.map (e.permCongrHom : _ →* Equiv.Perm ι) := by
  rw [h.range_galActionHom_eq_map_rootSetEquiv, Subgroup.map_map]
  congr 1
  ext σ x
  simp

end GaloisImage

end Polynomial
