/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Category.FGModuleCat.Basic
public import Mathlib.Algebra.Category.ModuleCat.Algebra
public import Mathlib.LinearAlgebra.Quotient.Basic
public import Mathlib.RingTheory.Ideal.Span
public import TauCeti.RingTheory.AdjoinRoot.Basic

/-!
# Cyclic modules and maps out of them

Let `A` be a ring and let `a : A`. The cyclic right `A`-module `A ⧸ aA` is represented as the
quotient of the regular module `Aᵐᵒᵖ` by the left ideal generated by `op a`, which is `op (aA)`:
right `A`-modules are left `Aᵐᵒᵖ`-modules.

A map of right `A`-modules out of `A ⧸ aA` is determined by the image `m` of the generator, which
can be any element with `m * a = 0`, written `op a • m = 0`. When `A` is an algebra over a field
`k`, evaluation at the generator is a `k`-linear equivalence; the `k`-vector space structure on
morphisms is Mathlib's `ModuleCat.linearOverField`.

For the truncated polynomial algebra `A = K[X]/(X ^ n)` over a field `K`, with `x` the class of
`X` and `M_i = A ⧸ (x ^ i)`, the elements of `M_j` killed by `x ^ i` form a space of dimension
`min i j`, so `dim_K Hom(M_i, M_j) = min i j` for `j ≤ n`.

## Main definitions

* `TauCeti.FGModuleCat.cyclicModule`: the cyclic right module `A ⧸ aA`.
* `TauCeti.FGModuleCat.cyclicModuleLift`: the map `A ⧸ aA ⟶ M` sending the generator to an
  element `m` with `op a • m = 0`.
* `TauCeti.FGModuleCat.cyclicModuleHomEquiv`: the `k`-linear equivalence between maps
  `A ⧸ aA ⟶ M` and elements of `M` killed by `op a`.

## Main results

* `TauCeti.FGModuleCat.cyclicModule_hom_ext`: maps out of `A ⧸ aA` agree when they agree on the
  generator.
* `TauCeti.FGModuleCat.smul_cyclicModule_hom_mk_one_eq_zero`: the image of the generator under a
  map out of `A ⧸ aA` is killed by `op a`.
* `TauCeti.FGModuleCat.finrank_ker_smul_op_root_pow`: over `K[X]/(X ^ n)`, the elements of `M_j`
  killed by `x ^ i` have dimension `min i j`.
* `TauCeti.FGModuleCat.finrank_cyclicModule_hom_root_pow`: over the truncated polynomial algebra
  `A = K[X]/(X ^ n)`, with `x` the class of `X` and `M_i = A ⧸ (x ^ i)`, the space of maps
  `M_i ⟶ M_j` has dimension `min i j` for `j ≤ n`.
* `TauCeti.FGModuleCat.finrank_map_ker_smul_op_root_pow`: over `K[X]/(X ^ n)`, the image in `M_j`
  of the annihilator of `x ^ i` has dimension `j - min j (n - i)`.
-/

public section

namespace TauCeti

open CategoryTheory MulOpposite

universe w u

namespace FGModuleCat

variable {A : Type u} [Ring A]

/-- The cyclic right `A`-module `A ⧸ aA`, as a finitely generated `Aᵐᵒᵖ`-module: the quotient of
the regular module `Aᵐᵒᵖ` by the left ideal generated by `op a`, which is `op (aA)`. -/
noncomputable abbrev cyclicModule (a : A) : FGModuleCat.{u} Aᵐᵒᵖ :=
  FGModuleCat.of Aᵐᵒᵖ (Aᵐᵒᵖ ⧸ Ideal.span {op a})

/-! ### Maps out of a cyclic module -/

section Hom

variable {M : Type u} [AddCommGroup M] [Module Aᵐᵒᵖ M] [Module.Finite Aᵐᵒᵖ M]

/-- The map of right `A`-modules `A ⧸ aA ⟶ M` sending the class of `c` to `c • m`, for an element
`m` with `op a • m = 0`. -/
noncomputable def cyclicModuleLift (a : A) (m : M) (hm : op a • m = 0) :
    cyclicModule a ⟶ FGModuleCat.of Aᵐᵒᵖ M :=
  FGModuleCat.ofHom <| Submodule.liftQSpanSingleton (op a) (LinearMap.toSpanSingleton Aᵐᵒᵖ M m) <|
    (LinearMap.toSpanSingleton_apply _ _ _ _).trans hm

@[simp]
theorem cyclicModuleLift_mk (a : A) (m : M) (hm : op a • m = 0) (c : Aᵐᵒᵖ) :
    (cyclicModuleLift a m hm).hom.hom (Submodule.Quotient.mk c) = c • m :=
  (rfl)

/-- Two maps out of the cyclic module `A ⧸ aA` agree when they agree on the generator. -/
@[ext]
theorem cyclicModule_hom_ext {a : A} {N : FGModuleCat.{u} Aᵐᵒᵖ} {f g : cyclicModule a ⟶ N}
    (h : f.hom.hom (Submodule.Quotient.mk 1) = g.hom.hom (Submodule.Quotient.mk 1)) : f = g :=
  FGModuleCat.hom_ext <| Submodule.linearMap_qext _ <| LinearMap.ext_ring h

/-- The image of the generator under a map out of `A ⧸ aA` is killed by `op a`. -/
theorem smul_cyclicModule_hom_mk_one_eq_zero {a : A} {N : FGModuleCat.{u} Aᵐᵒᵖ}
    (f : cyclicModule a ⟶ N) : op a • f.hom.hom (Submodule.Quotient.mk 1) = 0 := by
  rw [← LinearMap.map_smul, ← Submodule.Quotient.mk_smul, smul_eq_mul, mul_one,
    (Submodule.Quotient.mk_eq_zero _).2 (Ideal.mem_span_singleton_self _), map_zero]

variable (k : Type w) [Field k] [Algebra k A] [Module k M] [IsScalarTower k Aᵐᵒᵖ M]

/-- **Maps out of a cyclic module.** Evaluation at the generator is a `k`-linear equivalence
between maps of right `A`-modules `A ⧸ aA ⟶ M` and elements of `M` killed by `op a`. -/
noncomputable def cyclicModuleHomEquiv (a : A) :
    (cyclicModule a ⟶ FGModuleCat.of Aᵐᵒᵖ M) ≃ₗ[k]
      LinearMap.ker (DistribSMul.toLinearMap k M (op a)) where
  toFun f := ⟨f.hom.hom (Submodule.Quotient.mk 1), by
    rw [LinearMap.mem_ker, DistribSMul.toLinearMap_apply]
    exact smul_cyclicModule_hom_mk_one_eq_zero f⟩
  invFun m := cyclicModuleLift a m <| by
    rw [← DistribSMul.toLinearMap_apply k M (op a), ← LinearMap.mem_ker]
    exact m.2
  map_add' _ _ := rfl
  map_smul' c f := Subtype.ext (algebraMap_smul Aᵐᵒᵖ c _)
  left_inv f := cyclicModule_hom_ext <| by
    dsimp only
    rw [cyclicModuleLift_mk, one_smul]
  right_inv m := Subtype.ext <| by
    dsimp only
    rw [cyclicModuleLift_mk, one_smul]

@[simp]
theorem cyclicModuleHomEquiv_apply_coe (a : A) (f : cyclicModule a ⟶ FGModuleCat.of Aᵐᵒᵖ M) :
    (cyclicModuleHomEquiv k a f : M) = f.hom.hom (Submodule.Quotient.mk 1) :=
  (rfl)

@[simp]
theorem cyclicModuleHomEquiv_symm_apply (a : A)
    (m : LinearMap.ker (DistribSMul.toLinearMap k M (op a))) :
    (cyclicModuleHomEquiv k a).symm m = cyclicModuleLift a (m : M)
      ((DistribSMul.toLinearMap_apply k M (op a) m).symm.trans (LinearMap.mem_ker.1 m.2)) :=
  (rfl)

end Hom

/-! ### The truncated polynomial algebra `K[X]/(X ^ n)` -/

section TruncatedPolynomial

open Module Polynomial

variable {K : Type u} [Field K] {n : ℕ}

/-- Over `K[X]/(X ^ n)`, the elements of `M_j` killed by `x ^ i` form a space of dimension
`min i j`: multiplication by `x ^ i` on `M_j` has cokernel `M_(min i j)`. -/
theorem finrank_ker_smul_op_root_pow {i j : ℕ} (hj : j ≤ n) :
    finrank K (LinearMap.ker (DistribSMul.toLinearMap K ((AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸
      Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ j)})
        (op (AdjoinRoot.root (X ^ n : K[X]) ^ i)))) = min i j := by
  set x := AdjoinRoot.root (X ^ n : K[X])
  set φ := DistribSMul.toLinearMap K ((AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸ Ideal.span {op (x ^ j)})
    (op (x ^ i))
  have hrange : LinearMap.range φ =
      (Submodule.map (Ideal.span {op (x ^ j)}).mkQ
        (Ideal.span {op (x ^ i)})).restrictScalars K := by
    ext y
    obtain ⟨y, rfl⟩ := Submodule.Quotient.mk_surjective _ y
    simp only [LinearMap.mem_range, Submodule.restrictScalars_mem, Submodule.mem_map,
      Ideal.mem_span_singleton', Submodule.mkQ_apply]
    constructor
    · rintro ⟨z, hz⟩
      obtain ⟨c, rfl⟩ := Submodule.Quotient.mk_surjective _ z
      exact ⟨op (x ^ i) * c, ⟨c, mul_comm _ _⟩, hz⟩
    · rintro ⟨_, ⟨c, rfl⟩, hc⟩
      refine ⟨Submodule.Quotient.mk c, ?_⟩
      rw [← hc, DistribSMul.toLinearMap_apply, ← Submodule.Quotient.mk_smul, smul_eq_mul, mul_comm]
  have := (monic_X_pow n).finite_adjoinRoot (R := K)
  have h₁ := LinearMap.finrank_range_add_finrank_ker φ
  have h₂ := Submodule.finrank_quotient_add_finrank (LinearMap.range φ)
  rw [AdjoinRoot.finrank_quotient_span_op_root_X_pow_pow hj] at h₁ h₂
  have h₃ : finrank K (_ ⧸ LinearMap.range φ) = min j i := by
    rw [hrange]
    exact AdjoinRoot.finrank_quotient_map_mkQ_span_op_root_X_pow_pow hj i
  omega

/-- Over `K[X]/(X ^ n)`, with `x` the class of `X` and `M_j = A ⧸ (x ^ j)`, the image in `M_j` of
the annihilator `x ^ (n - i) A` of `x ^ i` has dimension `j - min j (n - i)`, for `i, j ≤ n`. -/
theorem finrank_map_ker_smul_op_root_pow {i j : ℕ} (hi : i ≤ n) (hj : j ≤ n) :
    finrank K ((LinearMap.ker (DistribSMul.toLinearMap K (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ
        (op (AdjoinRoot.root (X ^ n : K[X]) ^ i)))).map
      ((Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ j)}).mkQ.restrictScalars K)) =
      j - min j (n - i) := by
  set x := AdjoinRoot.root (X ^ n : K[X])
  have hker : LinearMap.ker (DistribSMul.toLinearMap K (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ
      (op (x ^ i))) = (Ideal.span {op (x ^ (n - i))}).restrictScalars K := by
    ext c
    obtain ⟨d, rfl⟩ := (RingEquiv.toOpposite (AdjoinRoot (X ^ n : K[X]))).surjective c
    simp only [LinearMap.mem_ker, DistribSMul.toLinearMap_apply, smul_eq_mul,
      Submodule.restrictScalars_mem, Ideal.mem_span_singleton]
    rw [← RingEquiv.toOpposite_apply, ← RingEquiv.toOpposite_apply, ← map_mul,
      map_eq_zero_iff _ (RingEquiv.injective _), map_dvd_iff,
      AdjoinRoot.root_X_pow_pow_mul_eq_zero_iff hi]
  have := (monic_X_pow n).finite_adjoinRoot (R := K)
  have h := Submodule.finrank_quotient_add_finrank ((Submodule.map (Ideal.span {op (x ^ j)}).mkQ
    (Ideal.span {op (x ^ (n - i))})).restrictScalars K)
  rw [AdjoinRoot.finrank_quotient_map_mkQ_span_op_root_X_pow_pow hj,
    AdjoinRoot.finrank_quotient_span_op_root_X_pow_pow hj] at h
  rw [hker, ← Submodule.restrictScalars_map]
  omega

/-- **Morphisms between the cyclic modules of `K[X]/(X ^ n)`.** With `x` the class of `X` and
`M_i = A ⧸ (x ^ i)`, the space of maps `M_i ⟶ M_j` has dimension `min i j` for `j ≤ n`. -/
theorem finrank_cyclicModule_hom_root_pow {i j : ℕ} (hj : j ≤ n) :
    finrank K (cyclicModule (AdjoinRoot.root (X ^ n : K[X]) ^ i) ⟶
      cyclicModule (AdjoinRoot.root (X ^ n : K[X]) ^ j)) = min i j :=
  (cyclicModuleHomEquiv K _).finrank_eq.trans (finrank_ker_smul_op_root_pow hj)

end TruncatedPolynomial

end FGModuleCat

end TauCeti
