/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Nakayama
public import Mathlib.RingTheory.Unramified.Basic

/-!
# Sections of formally unramified algebras

Let `P` and `B` be `R`-algebras, with `B` a formally unramified `P`-algebra, and let
`σ : B →ₐ[R] R` be a retraction, the algebraic form of a section of `Spec B → Spec R`. The
composite `P → B → R` is a point of `Spec P`. Formal unramifiedness says that the conormal
module `ker σ / (ker σ)²` of the section is generated by the equations of this point: every
element of `ker σ` is, modulo `(ker σ)²`, a combination of images of the kernel of `P → R`.
When that kernel is principal and `ker σ` is finitely generated (as it is when `B` is finitely
presented over `R`), Nakayama's lemma turns this into a single local equation for the section,
away from an element `r` with `σ r = 1`.

For an étale coordinate `P = R[X]` of a smooth relative curve this produces the local equation
of a section; see `TauCeti.RingTheory.Smooth.Section`.

## Main results

* `Algebra.FormallyUnramified.ker_le_map_ker_sup_pow_two`: `ker σ` is generated modulo
  `(ker σ)²` by the image of the kernel of the induced point `P → R`.
* `Algebra.FormallyUnramified.exists_smul_ker_le_span_singleton`: if moreover `ker σ` is finitely
  generated and the kernel of the point `P → R` is generated by `u`, then some `r` with
  `σ r = 1` satisfies `r • ker σ ≤ (u)`.

## References

* [Stacks Project, Tag 00DV](https://stacks.math.columbia.edu/tag/00DV): Nakayama's lemma.
-/

public section

open scoped Pointwise

namespace Algebra.FormallyUnramified

variable {R P B : Type*} [CommRing R] [CommRing P] [CommRing B] [Algebra R P] [Algebra R B]
  [Algebra P B] [IsScalarTower R P B]

/-- Let `B` be a formally unramified `P`-algebra, where `P` and `B` are `R`-algebras, and let
`σ : B →ₐ[R] R` be a retraction. Then `ker σ` is generated modulo `(ker σ)²` by the image of the
kernel of the composite `P → B → R`: the conormal module of the section is spanned by equations
coming from `P`. -/
theorem ker_le_map_ker_sup_pow_two [FormallyUnramified P B] (σ : B →ₐ[R] R) :
    RingHom.ker σ ≤
      (RingHom.ker (σ.comp (IsScalarTower.toAlgHom R P B))).map (algebraMap P B) ⊔
        RingHom.ker σ ^ 2 := by
  set N := (RingHom.ker (σ.comp (IsScalarTower.toAlgHom R P B))).map (algebraMap P B) ⊔
    RingHom.ker σ ^ 2
  -- In `B ⧸ N`, the image `J` of `ker σ` is a square-zero ideal.
  let J : Ideal (B ⧸ N) := (RingHom.ker σ).map (Ideal.Quotient.mk N)
  have hJ : J ^ 2 = ⊥ := by
    rw [eq_bot_iff, ← Ideal.map_pow, Ideal.map_le_iff_le_comap, ← RingHom.ker_eq_comap_bot,
      Ideal.mk_ker]
    exact le_sup_right
  -- The second `P`-algebra map `B → B ⧸ N`, through the retraction `σ`.
  let g : B →ₐ[P] B ⧸ N :=
    { (algebraMap R (B ⧸ N)).comp σ.toRingHom with
      commutes' := fun p ↦ by
        have hp : p - algebraMap R P (σ (algebraMap P B p)) ∈
            RingHom.ker (σ.comp (IsScalarTower.toAlgHom R P B)) := by
          simp [RingHom.mem_ker, ← IsScalarTower.algebraMap_apply]
        have hmem : algebraMap P B p - algebraMap R B (σ (algebraMap P B p)) ∈ N := by
          rw [IsScalarTower.algebraMap_apply R P B, ← map_sub]
          exact le_sup_left (b := RingHom.ker σ ^ 2) (Ideal.mem_map_of_mem (algebraMap P B) hp)
        simp only [AlgHom.toRingHom_eq_coe, ← Ideal.Quotient.mk_algebraMap]
        exact (Ideal.Quotient.eq.mpr hmem).symm }
  have hg (b : B) : g b = algebraMap R (B ⧸ N) (σ b) := rfl
  -- The two maps agree modulo `J`, so they agree by formal unramifiedness.
  have heq : Ideal.Quotient.mkₐ P N = g := by
    refine comp_injective (R := P) J hJ (AlgHom.ext fun b ↦ ?_)
    simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk, hg, ← Ideal.Quotient.mk_algebraMap]
    refine Ideal.Quotient.eq.mpr ?_
    rw [← map_sub]
    exact Ideal.mem_map_of_mem _ (by simp [RingHom.mem_ker])
  intro b hb
  rw [← Ideal.Quotient.eq_zero_iff_mem, ← Ideal.Quotient.mkₐ_eq_mk P, heq, hg,
    (RingHom.mem_ker).mp hb, map_zero]

/-- Let `B` be an `R`-algebra which is formally unramified over an `R`-algebra `P`, and let
`σ : B →ₐ[R] R` be a retraction with finitely generated kernel (for instance, `B` finitely
presented over `R`, by `Algebra.FinitePresentation.ker_fG_of_surjective`). If the kernel of the
induced point `P → R` is generated by a single element `u`, then some `r ∈ B` with `σ r = 1`
satisfies `r • ker σ ≤ (u)`; so after inverting `r`, the ideal `ker σ` is generated by the image
of `u`. -/
theorem exists_smul_ker_le_span_singleton [FormallyUnramified P B] (σ : B →ₐ[R] R)
    (hfg : (RingHom.ker σ).FG) {u : P}
    (hu : RingHom.ker (σ.comp (IsScalarTower.toAlgHom R P B)) = Ideal.span {u}) :
    ∃ r : B, σ r = 1 ∧ r • RingHom.ker σ ≤ Ideal.span {algebraMap P B u} := by
  have hker : RingHom.ker σ ≤
      Ideal.span {algebraMap P B u} ⊔ RingHom.ker σ • RingHom.ker σ := by
    have h := ker_le_map_ker_sup_pow_two (P := P) σ
    rwa [hu, Ideal.map_span, Set.image_singleton, pow_two, ← Ideal.smul_eq_mul] at h
  obtain ⟨r, hr, hle⟩ :=
    Submodule.exists_sub_one_mem_and_smul_le_of_fg_of_le_sup hfg le_rfl hker
  exact ⟨r, by simpa [RingHom.mem_ker, sub_eq_zero] using hr, hle⟩

end Algebra.FormallyUnramified

