/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.CompleteReducibility
public import TauCeti.Algebra.Lie.HighestWeight.Irreducible
public import TauCeti.Algebra.Lie.HighestWeight.Verma
public import TauCeti.Algebra.Lie.UniversalEnveloping.Isotypic
-- Non-public: these appear only inside proofs, never in the type of an exported declaration.
import TauCeti.Algebra.Lie.HighestWeight.Existence
import TauCeti.Algebra.Lie.Submodule.Atom

/-!
# The copy of `L(lam)` generated by a highest weight vector, and the single-weight criterion

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero. This file proves the two statements that turn Weyl's complete
reducibility theorem into a usable decomposition tool.

* **A highest weight vector of a finite-dimensional module generates an irreducible submodule**,
  necessarily a copy of the irreducible highest weight module `L(lam)`
  (`TauCeti.isIrreducible_lieSpan_of_isHighestWeightVector`). Finite-dimensionality is essential:
  in general a highest weight vector generates only a quotient of a Verma module.
* **The single-weight criterion**: if every highest weight vector of a finite-dimensional module
  has the same weight `lam`, the module is `L(lam)`-isotypic
  (`TauCeti.isotypicComponent_eq_top_of_forall_isHighestWeightVector`). This is what a
  decomposition argument consumes verbatim: exhibit the highest weight vectors, check that they
  share one weight, conclude that the module is a direct sum of copies of a single irreducible.

Each statement is proved twice over. The general form takes the copy of `L(lam)` as a parameter: an
irreducible module carrying a highest weight vector of weight `lam` is unique up to equivalence
(`TauCeti.nonempty_lieModuleEquiv_iff_eq_of_isHighestWeightVector`), so an equivalence with an
arbitrary such module says exactly "a copy of `L(lam)`". The form the roadmap pins fixes the
carrier to be `TauCeti.irreducibleQuotient b lam`, with nothing quantified over: that quotient is
irreducible and carries a highest weight vector of weight `lam`
(`TauCeti.isHighestWeightVector_irreducibleQuotientGenerator`).

## The argument

Everything rests on one observation about a highest weight module `M`, that is a module generated
by a highest weight vector `v` of weight `lam`. If `P` and `P'` are complementary Lie submodules
of `M`, then `v` lies in one of them. Indeed, write `v = p + p'` along the decomposition. For
`x` in the Cartan subalgebra the vector `⁅x, p⁆ - lam x • p` lies in `P` and is the negative of
`⁅x, p'⁆ - lam x • p'`, which lies in `P'`; the two submodules being disjoint, both vanish. The
same argument at a positive root vector shows that `p` and `p'` are each either zero or a highest
weight vector of weight `lam`, hence a *nonzero* multiple of `v`
(`TauCeti.exists_eq_smul_of_isHighestWeightVector_of_lieSpan_eq_top`). They cannot both be nonzero,
since then `v` would lie in `P ⊓ P' = ⊥`.

Weyl's theorem (`TauCeti.exists_isCompl_of_isKilling`) supplies a complement for every Lie
submodule of a finite-dimensional module, so this dichotomy says exactly that a finite-dimensional
highest weight module is irreducible. The statement about the submodule generated by a highest
weight vector of an arbitrary finite-dimensional module is that statement applied to the submodule,
which is again a highest weight module by
`TauCeti.lieSpan_singleton_eq_top_of_lieSpan_eq`. The rank-one precedent is
`TauCeti.isIrreducible_lieSpan_singleton`, which says the same for a primitive vector of an `sl₂`
triple spanning `L`; that one is proved by the elementary weight-string argument of Layer 0, since
Weyl's theorem is not yet available where it is used.

For the single-weight criterion, every irreducible Lie submodule of a finite-dimensional module
carries a highest weight vector (`TauCeti.exists_isHighestWeightVector`), whose weight is `lam` by
hypothesis; two irreducible modules with highest weight vectors of the same weight are equivalent,
so the module is isotypic of that type. Passing from isotypy to the isotypic component being
everything is Mathlib's `isotypicComponent_eq_top_iff` read through the enveloping-algebra
dictionary, `LieModule.isotypicComponent_eq_top_iff_of_ι_smul`.

## Main results

* `TauCeti.isIrreducible_of_isHighestWeightVector_of_lieSpan_eq_top`: a finite-dimensional highest
  weight module is irreducible.
* `TauCeti.isIrreducible_lieSpan_of_isHighestWeightVector` and
  `TauCeti.nonempty_lieModuleEquiv_lieSpan_of_isHighestWeightVector`: **a highest weight vector of
  a finite-dimensional module generates a copy of `L(lam)`**, and
  `TauCeti.finrank_le_of_isHighestWeightVector` reads off `dim L(lam) ≤ dim M`.
* `TauCeti.lieSpan_equiv_irreducibleQuotient_of_isHighestWeightVector` and
  `TauCeti.finrank_irreducibleQuotient_le_of_isHighestWeightVector`: the same two statements at the
  fixed carrier `L(lam)`.
* `TauCeti.isIsotypicOfType_of_forall_isHighestWeightVector` and
  `TauCeti.isotypicComponent_eq_top_of_isHighestWeightVector_of_forall_isHighestWeightVector`:
  **the single-weight isotypic criterion**, with
  `TauCeti.isotypicComponent_eq_top_of_forall_isHighestWeightVector` its form at the fixed carrier,
  which reads the conclusion off the weight hypothesis alone.

## References

This supplies the milestone "a highest weight vector generates a copy of `L(λ)`, and the
single-weight criterion" of the decomposition toolkit in Layer 6 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`.

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §§6.3, 20.3.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w w₁

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L]
  [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  {N : Type w₁} [AddCommGroup N] [Module K N] [LieRingModule L N] [LieModule K L N]

section Triangularizable

variable [IsTriangularizable K H L] {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-! ### The submodule generated by a highest weight vector -/

/-- The generator of the Lie submodule spanned by a highest weight vector is a highest weight
vector of that submodule, of the same weight. -/
private theorem isHighestWeightVector_generator (hv : IsHighestWeightVector b lam v) :
    IsHighestWeightVector b lam
      (⟨v, LieSubmodule.subset_lieSpan rfl⟩ :
        (LieSubmodule.lieSpan K L ({v} : Set M) : LieSubmodule K L M)) :=
  isHighestWeightVector_coe_iff.mp hv

/-! ### A finite-dimensional highest weight module is irreducible -/

/-- **A highest weight vector lies in one half of a direct-sum decomposition.** The two components
of the generator of a highest weight module along a pair of complementary Lie submodules are each
either zero or again a highest weight vector of the same weight, hence a nonzero multiple of the
generator; they cannot both be, since the two submodules meet in `⊥`. -/
private theorem mem_or_mem_of_isCompl_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {P P' : LieSubmodule K L M} (hcompl : IsCompl P P') : v ∈ P ∨ v ∈ P' := by
  have hmem : v ∈ P ⊔ P' := by rw [hcompl.sup_eq_top]; exact LieSubmodule.mem_top v
  obtain ⟨p, hp, q, hq, hpq⟩ := (LieSubmodule.mem_sup P P' v).mp hmem
  -- the two components of a vector of `P ⊓ P' = ⊥` summing to zero both vanish
  have hsplit : ∀ y ∈ P, ∀ z ∈ P', y + z = 0 → y = 0 := by
    intro y hy z hz hyz
    have hyP' : y ∈ P' := by
      rw [eq_neg_of_add_eq_zero_left hyz]
      exact neg_mem hz
    exact (LieSubmodule.mem_bot y).mp
      (hcompl.disjoint.le_bot ((LieSubmodule.mem_inf P P' y).mpr ⟨hy, hyP'⟩))
  by_cases hp0 : p = 0
  · exact Or.inr (by rw [← hpq, hp0, zero_add]; exact hq)
  refine Or.inl ?_
  have hcartan : ∀ x : H, ⁅(x : L), p⁆ = lam x • p := by
    intro x
    have hyP : ⁅(x : L), p⁆ - lam x • p ∈ P := sub_mem (P.lie_mem hp) (P.smul_mem _ hp)
    have hzP' : ⁅(x : L), q⁆ - lam x • q ∈ P' := sub_mem (P'.lie_mem hq) (P'.smul_mem _ hq)
    have hsum : ⁅(x : L), p⁆ + ⁅(x : L), q⁆ = lam x • p + lam x • q := by
      rw [← lie_add, ← smul_add, hpq]
      exact hv.lie_eq_smul x
    refine sub_eq_zero.mp (hsplit _ hyP _ hzP' ?_)
    rw [sub_add_sub_comm, hsum, sub_self]
  have hnil : ∀ x ∈ positiveNilradical H b, ⁅x, p⁆ = 0 := by
    intro x hx
    have hyP : ⁅x, p⁆ ∈ P := P.lie_mem hp
    have hzP' : ⁅x, q⁆ ∈ P' := P'.lie_mem hq
    refine hsplit _ hyP _ hzP' ?_
    rw [← lie_add, hpq]
    exact hv.lie_eq_zero_of_mem_positiveNilradical hx
  obtain ⟨c, hc, hcp⟩ := exists_eq_smul_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen
    (isHighestWeightVector_iff.mpr ⟨hp0, hcartan, hnil⟩)
  have hvp : v = c⁻¹ • p := by rw [hcp, smul_smul, inv_mul_cancel₀ hc, one_smul]
  rw [hvp]
  exact P.smul_mem _ hp

end Triangularizable

section AlgClosed

variable [IsAlgClosed K] {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-- **A finite-dimensional highest weight module is irreducible.** Every Lie submodule has a
complement by Weyl's theorem, and the generator lies in one of the two halves; the half containing
it is everything. -/
theorem isIrreducible_of_isHighestWeightVector_of_lieSpan_eq_top [FiniteDimensional K M]
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    LieModule.IsIrreducible K L M := by
  have : Nontrivial M := nontrivial_of_ne v 0 hv.ne_zero
  refine LieModule.IsIrreducible.mk fun P hP => ?_
  obtain ⟨P', hcompl⟩ := exists_isCompl_of_isKilling P
  have hle : ∀ Q : LieSubmodule K L M, v ∈ Q → Q = ⊤ := fun Q hQ =>
    top_le_iff.mp (hgen ▸ LieSubmodule.lieSpan_le.mpr (Set.singleton_subset_iff.mpr hQ))
  rcases mem_or_mem_of_isCompl_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen hcompl with h | h
  · exact hle P h
  · exact absurd (disjoint_top.mp (hle P' h ▸ hcompl.disjoint)) hP

/-! ### The copy of `L(lam)` generated by a highest weight vector -/

/-- **A highest weight vector of a finite-dimensional module generates an irreducible submodule.**
The submodule it generates is a highest weight module, and a finite-dimensional highest weight
module is irreducible. -/
theorem isIrreducible_lieSpan_of_isHighestWeightVector [FiniteDimensional K M]
    (hv : IsHighestWeightVector b lam v) :
    LieModule.IsIrreducible K L (LieSubmodule.lieSpan K L {v}) := by
  have hmem : v ∈ (LieSubmodule.lieSpan K L ({v} : Set M) : LieSubmodule K L M) :=
    LieSubmodule.subset_lieSpan rfl
  have hgen : LieSubmodule.lieSpan K L
      {(⟨v, hmem⟩ : (LieSubmodule.lieSpan K L ({v} : Set M) : LieSubmodule K L M))} = ⊤ :=
    lieSpan_singleton_eq_top_of_lieSpan_eq rfl
  exact isIrreducible_of_isHighestWeightVector_of_lieSpan_eq_top
    (isHighestWeightVector_generator hv) hgen

/-- **A highest weight vector generates a copy of `L(lam)`.** In a finite-dimensional module the
Lie submodule generated by a highest weight vector of weight `lam` is equivalent to every
irreducible module carrying a highest weight vector of that weight, so it is a copy of `L(lam)`.

Finite-dimensionality is essential: in general a highest weight vector generates a quotient of the
Verma module of its weight, not necessarily an irreducible one. -/
theorem nonempty_lieModuleEquiv_lieSpan_of_isHighestWeightVector [FiniteDimensional K M]
    [LieModule.IsIrreducible K L N] {w : N} (hv : IsHighestWeightVector b lam v)
    (hw : IsHighestWeightVector b lam w) :
    Nonempty ((LieSubmodule.lieSpan K L {v} : LieSubmodule K L M) ≃ₗ⁅K,L⁆ N) :=
  have _ := isIrreducible_lieSpan_of_isHighestWeightVector hv
  nonempty_lieModuleEquiv_of_isHighestWeightVector (isHighestWeightVector_generator hv) hw

/-- **`dim L(lam) ≤ dim M` whenever `M` has a highest weight vector of weight `lam`.** The copy of
`L(lam)` generated by that vector is a subspace of `M`. -/
theorem finrank_le_of_isHighestWeightVector [FiniteDimensional K M]
    [LieModule.IsIrreducible K L N] {w : N} (hv : IsHighestWeightVector b lam v)
    (hw : IsHighestWeightVector b lam w) : finrank K N ≤ finrank K M := by
  obtain ⟨e⟩ := nonempty_lieModuleEquiv_lieSpan_of_isHighestWeightVector hv hw
  rw [← e.toLinearEquiv.finrank_eq]
  exact Submodule.finrank_le (LieSubmodule.lieSpan K L {v} : LieSubmodule K L M).toSubmodule

/-! ### The same statements at the named carrier `L(lam)`

`TauCeti.irreducibleQuotient b lam` is `L(lam)`, the quotient of the Verma module `M(lam)` by its
maximal submodule; it is irreducible and carries a highest weight vector of weight `lam`. So each
statement above is recorded again at that one fixed carrier, with nothing quantified over. -/

/-- **A highest weight vector generates a copy of `L(lam)`.** In a finite-dimensional module the
Lie submodule generated by a highest weight vector of weight `lam` is equivalent to `L(lam)`. -/
theorem lieSpan_equiv_irreducibleQuotient_of_isHighestWeightVector
    [FiniteDimensional K M] (hv : IsHighestWeightVector b lam v) :
    Nonempty ((LieSubmodule.lieSpan K L {v} : LieSubmodule K L M) ≃ₗ⁅K,L⁆
      irreducibleQuotient b lam) :=
  nonempty_lieModuleEquiv_lieSpan_of_isHighestWeightVector hv
    (isHighestWeightVector_irreducibleQuotientGenerator b lam)

/-- **`dim L(lam) ≤ dim M`**, the copy of `L(lam)` generated by a highest weight vector of weight
`lam` being a subspace of `M`. -/
theorem finrank_irreducibleQuotient_le_of_isHighestWeightVector [FiniteDimensional K M]
    (hv : IsHighestWeightVector b lam v) :
    finrank K (irreducibleQuotient b lam) ≤ finrank K M :=
  finrank_le_of_isHighestWeightVector hv
    (isHighestWeightVector_irreducibleQuotientGenerator b lam)

/-! ### The single-weight isotypic criterion -/

/-- **The single-weight isotypic criterion.** If every highest weight vector of a
finite-dimensional module `M` has weight `lam`, then every irreducible Lie submodule of `M` is a
copy of `L(lam)`: each such submodule carries a highest weight vector, whose weight is `lam` by
hypothesis, and irreducible modules with highest weight vectors of the same weight agree. -/
theorem isIsotypicOfType_of_forall_isHighestWeightVector [FiniteDimensional K M]
    [LieModule.IsIrreducible K L N] {w : N} (hw : IsHighestWeightVector b lam w)
    (h : ∀ (nu : Dual K H) (u : M), IsHighestWeightVector b nu u → nu = lam) :
    LieModule.IsIsotypicOfType K L M N := by
  rw [LieModule.isIsotypicOfType_iff]
  intro P _
  have : Nontrivial P := LieModule.nontrivial_of_isIrreducible (R := K) (L := L) (M := P)
  obtain ⟨nu, u, hu⟩ := exists_isHighestWeightVector (M := P) b
  have hnu : nu = lam := h nu (u : M) (isHighestWeightVector_coe_iff.mpr hu)
  subst hnu
  exact nonempty_lieModuleEquiv_of_isHighestWeightVector hu hw

section IsotypicComponent

attribute [local instance] UniversalEnvelopingAlgebra.asModule
  UniversalEnvelopingAlgebra.isScalarTower_asModule

/-- **The single-weight isotypic criterion, as a statement about the isotypic component.** If every
highest weight vector of a finite-dimensional module `M` has weight `lam`, then the
`L(lam)`-isotypic component of `M` is all of `M`, so `M` is a direct sum of copies of `L(lam)`.
Here `L(lam)` is presented as an arbitrary irreducible module carrying a highest weight vector of
weight `lam`; `TauCeti.isotypicComponent_eq_top_of_forall_isHighestWeightVector` is the same
statement at the fixed carrier. -/
theorem isotypicComponent_eq_top_of_isHighestWeightVector_of_forall_isHighestWeightVector
    [FiniteDimensional K M] [LieModule.IsIrreducible K L N] {w : N}
    (hw : IsHighestWeightVector b lam w)
    (h : ∀ (nu : Dual K H) (u : M), IsHighestWeightVector b nu u → nu = lam) :
    LieModule.isotypicComponent K L M N = ⊤ :=
  have _ : ComplementedLattice (LieSubmodule K L M) :=
    complementedLattice_lieSubmodule_of_isKilling K L M
  (LieModule.isotypicComponent_eq_top_iff_of_ι_smul
      (UniversalEnvelopingAlgebra.asModule_ι_smul K L M) N
      (UniversalEnvelopingAlgebra.asModule_ι_smul K L N)).mpr
    (isIsotypicOfType_of_forall_isHighestWeightVector hw h)

/-- **The single-weight isotypic criterion at the fixed carrier `L(lam)`**, which is the criterion
read off the weight hypothesis alone: a finite-dimensional module all of whose highest weight
vectors have weight `lam` is a direct sum of copies of `L(lam)`. -/
theorem isotypicComponent_eq_top_of_forall_isHighestWeightVector [FiniteDimensional K M]
    (h : ∀ (nu : Dual K H) (u : M), IsHighestWeightVector b nu u → nu = lam) :
    LieModule.isotypicComponent K L M (irreducibleQuotient b lam) = ⊤ :=
  isotypicComponent_eq_top_of_isHighestWeightVector_of_forall_isHighestWeightVector
    (isHighestWeightVector_irreducibleQuotientGenerator b lam) h

end IsotypicComponent

end AlgClosed

end TauCeti
