/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Maximal
public import TauCeti.Algebra.Lie.UniversalEnveloping.Module
public import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Character
-- Non-public: `U(n⁻)` is a domain containing `n⁻`, used only to prove that lowering the canonical
-- generator never gives zero.
import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Domain
import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Embedding

/-!
# Verma modules

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, let `H` be a splitting Cartan subalgebra and let `b` be a base of the root
system `LieAlgebra.IsKilling.rootSystem H`, so that the Borel subalgebra `𝔟 = H + n⁺` of
`TauCeti/Algebra/Lie/Weights/Borel.lean` is available. For a linear form `lam` on `H` this file
builds the **Verma module** `M(lam)`, the universal module generated by a vector on which `H` acts
through `lam` and which the positive nilradical annihilates.

## The presentation

`M(lam)` is classically written `U(L) ⊗_{U(𝔟)} K_lam`, where `K_lam` is the one-dimensional
`𝔟`-module on which `x = h + n` acts by `lam h`. Since `U(L)` is a free right `U(𝔟)`-module only
after Poincaré--Birkhoff--Witt, and since Mathlib's tensor product is taken over a *commutative*
base, this file instead uses a quotient presentation:

`TauCeti.vermaIdeal b lam` is the left ideal generated by the elements `ι x - lam x` for `x : H`
together with `ι x` for `x` in the positive nilradical, and
`TauCeti.VermaModule b lam := U(L) ⧸ vermaIdeal b lam`.

For a decomposition `x = h + n` of an element of `𝔟`, the associated degree-one relation satisfies
`ι x - lam h = (ι h - lam h) + ι n` and hence belongs to this ideal. This containment is the content
of `TauCeti.exists_ι_sub_algebraMap_mem_vermaIdeal_of_mem_borelSubalgebra` below.

Reading the quotient as a Lie module is what
`TauCeti/Algebra/Lie/UniversalEnveloping/Module.lean` was built for: a left ideal is exactly a
`U(L)`-submodule of `U(L)`, so the quotient is a `U(L)`-module, and
`TauCeti.UniversalEnvelopingAlgebra.asLieRingModule` turns that into an `L`-module. The same file
supplies the two dictionary results the universal property runs on: Lie module homomorphisms out of
`M(lam)` are `U(L)`-linear maps, and the Lie submodule generated by the canonical vector is its
`U(L)`-span.

## The universal property, and nonvanishing

The universal property `TauCeti.existsUnique_lieModuleHom_apply_vermaGenerator` is proved in the
form that does *not* presuppose `M(lam) ≠ 0`: for **any** vector `v` of **any** `L`-module on which
`H` acts through `lam` and which `n⁺` annihilates — `v = 0` allowed — there is a unique Lie module
homomorphism `M(lam) → N` sending the canonical generator to `v`. Everything below is a consequence
of it.

That `M(lam)` is nonzero is exactly the statement that the left ideal `vermaIdeal b lam` is proper
(`TauCeti.vermaGenerator_eq_zero_iff`). The Verma relations are the elements `ι x - χ x` for `x` in
the Borel subalgebra, where `χ = TauCeti.borelCharacter H b lam` is the character `h + n ↦ lam h`
of `𝔟`, and the left ideal these generate is proper by the freeness of `U(L)` as a right
`U(𝔟)`-module, a consequence of Poincaré--Birkhoff--Witt
(`TauCeti.UniversalEnvelopingAlgebra.span_range_ι_sub_algebraMap_ne_top`). This is
`TauCeti.vermaIdeal_ne_top`, so the canonical generator is a highest weight vector of weight `lam`
for every `lam` (`TauCeti.isHighestWeightVector_vermaGenerator`) and `L(lam)` is irreducible for
every `lam`.

## Freeness over `U(n⁻)`

The same relative Poincaré--Birkhoff--Witt input gives more than nonvanishing. Since
`L = n⁻ ⊕ 𝔟` (`TauCeti.isCompl_negativeNilradical_borelSubalgebra`), `U(L)` is a free right
`U(𝔟)`-module on the ordered monomials in a basis of `n⁻`, and the induced module `M(lam)` is
therefore a free `U(n⁻)`-module of rank one on `v_lam`: the map `U(n⁻) → M(lam)`, `y ↦ y · v_lam`,
is a linear equivalence (`TauCeti.universalEnvelopingEquivVermaModule`). Through the PBW basis of
`U(n⁻)` this is the input for computing the weight multiplicities of `M(lam)`.

## Main definitions

* `TauCeti.vermaRelations b lam` and `TauCeti.vermaIdeal b lam`: the defining relations of weight
  `lam` and the left ideal of `U(L)` they generate.
* `TauCeti.VermaModule b lam`: the Verma module `M(lam)`, with its `K`-module, `U(L)`-module and
  `L`-module structures.
* `TauCeti.vermaMk b lam`: the canonical projection `U(L) → M(lam)`, as a `U(L)`-linear map.
* `TauCeti.vermaGenerator b lam`: the canonical generator `v_lam`, the class of `1`.
* `TauCeti.irreducibleQuotient b lam`: the irreducible quotient `L(lam)`, the quotient of `M(lam)`
  by its maximal submodule, with its `K`-module and `L`-module structures.
* `TauCeti.irreducibleQuotientMk b lam`: the canonical projection `M(lam) → L(lam)`, as a Lie
  module homomorphism.
* `TauCeti.irreducibleQuotientGenerator b lam`: the canonical generator of `L(lam)`, the class of
  the canonical generator of `M(lam)`.

## Main results

* `TauCeti.lie_vermaGenerator_eq_smul` and
  `TauCeti.lie_vermaGenerator_eq_zero_of_mem_positiveNilradical`: the Cartan subalgebra acts on the
  canonical generator through `lam`, and the positive nilradical annihilates it.
* `TauCeti.lieSpan_vermaGenerator_eq_top`: the canonical generator generates `M(lam)`, so `M(lam)`
  is a highest weight module of weight `lam` as soon as the generator is nonzero.
* `TauCeti.existsUnique_lieModuleHom_apply_vermaGenerator`: **the universal property**.
* `TauCeti.exists_surjective_lieModuleHom_of_isHighestWeightVector`: **every highest weight module
  of weight `lam` is a quotient of `M(lam)`**, which is what makes `M(lam)` universal in the sense
  the classification uses.
* `TauCeti.isHighestWeightVector_vermaGenerator_iff`, `TauCeti.vermaGenerator_eq_zero_iff` and
  `TauCeti.subsingleton_vermaModule_iff`: the nonvanishing of `M(lam)` is the properness of
  `TauCeti.vermaIdeal`.
* `TauCeti.vermaIdeal_eq_span_range_ι_sub_algebraMap`: the Verma ideal is the left ideal generated
  by the elements `ι x - χ x` for `x` in `𝔟`, `χ` the Borel character of weight `lam`, so that
  `M(lam)` is induced from the one-dimensional `𝔟`-module `K_lam`.
* `TauCeti.vermaIdeal_ne_top`, `TauCeti.vermaGenerator_ne_zero` and
  `TauCeti.isHighestWeightVector_vermaGenerator`: **`M(lam) ≠ 0` for every `lam`**, and its
  canonical generator is a highest weight vector of weight `lam`.
* `TauCeti.universalEnvelopingEquivVermaModule`, with
  `TauCeti.universalEnvelopingEquivVermaModule_apply` and
  `TauCeti.universalEnvelopingEquivVermaModule_mul`: **`M(lam)` is a free `U(n⁻)`-module of rank
  one on `v_lam`**, the map `y ↦ y · v_lam` being a `U(n⁻)`-linear equivalence `U(n⁻) ≃ M(lam)`.
* `TauCeti.pow_toEnd_vermaGenerator_ne_zero`: lowering `v_lam` by a nonzero element of `n⁻`, any
  number of times, never gives zero.
* `TauCeti.irreducibleQuotientMk_surjective` and
  `TauCeti.lieSpan_irreducibleQuotientGenerator_eq_top`: every vector of `L(lam)` is the class of
  one of `M(lam)`, and the canonical generator generates `L(lam)`.
* `TauCeti.isIrreducible_irreducibleQuotient` and
  `TauCeti.isHighestWeightVector_irreducibleQuotientGenerator`: **`L(lam)` is irreducible and its
  canonical generator is a highest weight vector of weight `lam`**, for every `lam`.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §20.3.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, §1.3.
-/

public section

open UniversalEnvelopingAlgebra

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]

local notation "U" => _root_.UniversalEnvelopingAlgebra K L

variable (b : (IsKilling.rootSystem H).Base) (lam : Dual K H)

/-! ### The defining left ideal -/

/-- The **Verma relations** of weight `lam`: the elements `ι x - lam x` of `U(L)` for `x` in the
Cartan subalgebra, together with the elements `ι x` for `x` in the positive nilradical. Their
image in `M(lam)` is what forces the Cartan subalgebra to act on the class of `1` through `lam`
and the positive nilradical to annihilate it. Those are two of the three conditions defining a
highest weight vector, so that class is a highest weight vector of weight `lam` exactly when it
is nonzero; see `TauCeti.isHighestWeightVector_vermaGenerator_iff`. -/
def vermaRelations : Set U :=
  Set.range (fun x : H => (ι K (x : L) : U) - algebraMap K U (lam x)) ∪
    (fun x : L => (ι K x : U)) '' (positiveNilradical H b : Set L)

/-- The **Verma ideal** of weight `lam`: the left ideal of `U(L)` generated by the Verma
relations. -/
def vermaIdeal : Submodule U U :=
  Submodule.span U (vermaRelations b lam)

/-- The relation `ι x - lam x` lies in the Verma ideal, for `x` in the Cartan subalgebra. -/
theorem ι_sub_algebraMap_mem_vermaIdeal (x : H) :
    (ι K (x : L) : U) - algebraMap K U (lam x) ∈ vermaIdeal b lam :=
  Submodule.subset_span (Or.inl ⟨x, rfl⟩)

/-- The relation `ι x` lies in the Verma ideal, for `x` in the positive nilradical. -/
theorem ι_mem_vermaIdeal_of_mem_positiveNilradical {x : L}
    (hx : x ∈ positiveNilradical H b) : (ι K x : U) ∈ vermaIdeal b lam :=
  Submodule.subset_span (Or.inr ⟨x, hx, rfl⟩)

/-- For an element `x = h + n` of the Borel subalgebra, the degree-one relation `ι x - lam h`
belongs to the Verma ideal, since it is the sum of the two kinds of generator. -/
theorem exists_ι_sub_algebraMap_mem_vermaIdeal_of_mem_borelSubalgebra {x : L}
    (hx : x ∈ borelSubalgebra H b) :
    ∃ h : H, (ι K x : U) - algebraMap K U (lam h) ∈ vermaIdeal b lam := by
  rw [← LieSubalgebra.mem_toSubmodule, borelSubalgebra_toSubmodule, Submodule.mem_sup] at hx
  obtain ⟨h, hh, n, hn, rfl⟩ := hx
  refine ⟨⟨h, hh⟩, ?_⟩
  have hsplit : (ι K ((h : L) + n) : U) - algebraMap K U (lam ⟨h, hh⟩)
      = ((ι K h : U) - algebraMap K U (lam ⟨h, hh⟩)) + (ι K n : U) := by
    rw [map_add]
    abel
  rw [hsplit]
  exact Submodule.add_mem _ (ι_sub_algebraMap_mem_vermaIdeal b lam ⟨h, hh⟩)
    (ι_mem_vermaIdeal_of_mem_positiveNilradical b lam hn)

/-! ### The Verma module and its structures -/

/-- **The Verma module** `M(lam)`, defined here as the quotient of `U(L)` by the left ideal
`TauCeti.vermaIdeal` of Verma relations. -/
def VermaModule : Type max u v :=
  U ⧸ vermaIdeal b lam

instance : AddCommGroup (VermaModule b lam) :=
  inferInstanceAs (AddCommGroup (U ⧸ vermaIdeal b lam))

instance : Module U (VermaModule b lam) :=
  inferInstanceAs (Module U (U ⧸ vermaIdeal b lam))

instance : Module K (VermaModule b lam) :=
  inferInstanceAs (Module K (U ⧸ vermaIdeal b lam))

instance : IsScalarTower K U (VermaModule b lam) :=
  inferInstanceAs (IsScalarTower K U (U ⧸ vermaIdeal b lam))

noncomputable instance : LieRingModule L (VermaModule b lam) :=
  UniversalEnvelopingAlgebra.asLieRingModule K L (VermaModule b lam)

noncomputable instance : LieModule K L (VermaModule b lam) :=
  UniversalEnvelopingAlgebra.asLieModule K L (VermaModule b lam)

/-- The `L`-action on the Verma module is the action of the canonical Lie generators of `U(L)`.
This is the compatibility hypothesis the enveloping-algebra dictionary consumes. -/
theorem vermaModule_ι_smul (x : L) (m : VermaModule b lam) : (ι K x : U) • m = ⁅x, m⁆ :=
  (UniversalEnvelopingAlgebra.asLieRingModule_bracket K L (VermaModule b lam) x m).symm

/-- **The enveloping representation of the Verma module is its `U(L)`-module structure**: the
action of `U(L)` induced by the `L`-action, `TauCeti.UniversalEnvelopingAlgebra.representation`,
is the scalar action of `U(L)` on the quotient `U(L) ⧸ vermaIdeal b lam`. -/
theorem representation_vermaModule_apply (u : U) (m : VermaModule b lam) :
    UniversalEnvelopingAlgebra.representation K L (VermaModule b lam) u m = u • m := by
  induction u using UniversalEnvelopingAlgebra.induction_ι generalizing m with
  | ι x => rw [UniversalEnvelopingAlgebra.representation_ι_apply, vermaModule_ι_smul]
  | algebraMap r => rw [AlgHom.commutes, Module.algebraMap_end_apply, algebraMap_smul]
  | add u w hu hw => rw [map_add, LinearMap.add_apply, hu, hw, add_smul]
  | mul u w hu hw => rw [map_mul, Module.End.mul_apply, hw, hu, mul_smul]

/-- **The canonical projection** `U(L) → M(lam)`, bundled as a `U(L)`-linear map so that its
algebraic behaviour — `map_zero`, `map_add`, `map_smul` — is available from the `LinearMap` API
without unfolding the quotient. -/
def vermaMk : U →ₗ[U] VermaModule b lam :=
  Submodule.mkQ (vermaIdeal b lam)

theorem vermaMk_surjective : Function.Surjective (vermaMk b lam) :=
  Submodule.mkQ_surjective _

theorem vermaMk_eq_iff {u w : U} :
    vermaMk b lam u = vermaMk b lam w ↔ u - w ∈ vermaIdeal b lam :=
  Submodule.Quotient.eq _

@[simp]
theorem vermaMk_eq_zero_iff {u : U} : vermaMk b lam u = 0 ↔ u ∈ vermaIdeal b lam :=
  Submodule.Quotient.mk_eq_zero _

@[simp]
theorem smul_vermaMk (u w : U) : u • vermaMk b lam w = vermaMk b lam (u * w) :=
  (Submodule.Quotient.mk_smul _ u w).symm

/-- **The canonical generator** `v_lam` of the Verma module, the class of `1`. It is a highest
weight vector of weight `lam` exactly when it is nonzero, which is
`TauCeti.isHighestWeightVector_vermaGenerator_iff`. -/
def vermaGenerator : VermaModule b lam :=
  vermaMk b lam 1

@[simp]
theorem smul_vermaGenerator (u : U) : u • vermaGenerator b lam = vermaMk b lam u := by
  rw [vermaGenerator, smul_vermaMk, mul_one]

/-- **The Cartan subalgebra acts on the canonical generator through `lam`.** -/
@[simp]
theorem lie_vermaGenerator_eq_smul (x : H) :
    ⁅(x : L), vermaGenerator b lam⁆ = lam x • vermaGenerator b lam := by
  rw [← vermaModule_ι_smul b lam, smul_vermaGenerator, vermaGenerator, ← algebraMap_smul U (lam x),
    smul_vermaMk, mul_one, vermaMk_eq_iff]
  exact ι_sub_algebraMap_mem_vermaIdeal b lam x

/-- **The positive nilradical annihilates the canonical generator.** -/
theorem lie_vermaGenerator_eq_zero_of_mem_positiveNilradical {x : L}
    (hx : x ∈ positiveNilradical H b) : ⁅x, vermaGenerator b lam⁆ = 0 := by
  rw [← vermaModule_ι_smul b lam, smul_vermaGenerator, vermaMk_eq_zero_iff]
  exact ι_mem_vermaIdeal_of_mem_positiveNilradical b lam hx

/-- The canonical generator spans the Verma module over `U(L)`. -/
theorem span_vermaGenerator_eq_top :
    Submodule.span U {vermaGenerator b lam} = ⊤ := by
  refine top_le_iff.mp fun m _ => ?_
  obtain ⟨u, rfl⟩ := vermaMk_surjective b lam m
  rw [← smul_vermaGenerator]
  exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)

/-- **The canonical generator generates the Verma module** as a Lie module, by the dictionary
carrying generated Lie submodules to `U(L)`-spans. Together with
`TauCeti.isHighestWeightVector_vermaGenerator_iff` this exhibits `M(lam)` as a highest weight
module of weight `lam` whenever it is nonzero. -/
theorem lieSpan_vermaGenerator_eq_top :
    LieSubmodule.lieSpan K L {vermaGenerator b lam} = ⊤ := by
  refine (UniversalEnvelopingAlgebra.lieSubmoduleOrderIso
    (vermaModule_ι_smul b lam)).injective ?_
  rw [UniversalEnvelopingAlgebra.lieSubmoduleOrderIso_lieSpan, span_vermaGenerator_eq_top,
    OrderIso.map_top]

/-! ### The universal property -/

variable {N : Type w} [AddCommGroup N] [Module K N] [LieRingModule L N] [LieModule K L N]

/-- **The universal property of the Verma module.** If `H` acts on a vector `v` of an `L`-module
`N` through `lam` and the positive nilradical annihilates `v`, then there is a unique homomorphism
of `L`-modules `M(lam) → N` carrying the canonical generator to `v`.

The vector `v` is *not* assumed nonzero, so this does not presuppose that `M(lam)` is nonzero. -/
theorem existsUnique_lieModuleHom_apply_vermaGenerator (v : N)
    (hcartan : ∀ x : H, ⁅(x : L), v⁆ = lam x • v)
    (hpos : ∀ x ∈ positiveNilradical H b, ⁅x, v⁆ = 0) :
    ∃! φ : VermaModule b lam →ₗ⁅K,L⁆ N, φ (vermaGenerator b lam) = v := by
  let _ : Module U N := UniversalEnvelopingAlgebra.asModule K L N
  have _ : IsScalarTower K U N := UniversalEnvelopingAlgebra.isScalarTower_asModule K L N
  have hN : ∀ (x : L) (n : N), (ι K x : U) • n = ⁅x, n⁆ :=
    UniversalEnvelopingAlgebra.asModule_ι_smul K L N
  have hM := vermaModule_ι_smul b lam
  set f : U →ₗ[U] N := LinearMap.toSpanSingleton U N v
  have hf : ∀ u : U, f u = u • v := by
    intro u
    simp only [f, LinearMap.toSpanSingleton_apply]
  have hker : vermaIdeal b lam ≤ LinearMap.ker f := by
    rw [vermaIdeal, Submodule.span_le]
    rintro u (⟨x, rfl⟩ | ⟨x, hx, rfl⟩)
    · simp only [SetLike.mem_coe, LinearMap.mem_ker, hf, sub_smul, hN, hcartan x,
        algebraMap_smul, sub_self]
    · simp only [SetLike.mem_coe, LinearMap.mem_ker, hf, hN, hpos x hx]
  set g : VermaModule b lam →ₗ[U] N := Submodule.liftQ (vermaIdeal b lam) f hker
  have hg : ∀ u : U, g (vermaMk b lam u) = u • v := by
    intro u
    calc
      g (vermaMk b lam u) = f u := by
        apply Submodule.liftQ_apply
      _ = u • v := hf u
  have hcoe : ⇑((UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).symm g) = ⇑g :=
    UniversalEnvelopingAlgebra.coe_lieModuleHomEquiv_symm hM hN g
  have hval : ((UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).symm g)
      (vermaGenerator b lam) = v := by
    rw [hcoe, vermaGenerator, hg, one_smul]
  refine ⟨(UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).symm g, hval, fun ψ hψ => ?_⟩
  refine (UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).injective ?_
  rw [LinearEquiv.apply_symm_apply]
  refine LinearMap.ext_on (span_vermaGenerator_eq_top b lam) ?_
  rintro x rfl
  rw [UniversalEnvelopingAlgebra.coe_lieModuleHomEquiv, hψ, vermaGenerator, hg, one_smul]

/-! ### Highest weight vectors and nonvanishing -/

/-- **The canonical generator is a highest weight vector exactly when it is nonzero.** The other
two conditions hold unconditionally, by `TauCeti.lie_vermaGenerator_eq_smul` and
`TauCeti.lie_vermaGenerator_eq_zero_of_mem_positiveNilradical`. -/
theorem isHighestWeightVector_vermaGenerator_iff :
    IsHighestWeightVector b lam (vermaGenerator b lam) ↔ vermaGenerator b lam ≠ 0 :=
  ⟨fun h => h.ne_zero, fun h => isHighestWeightVector_iff.mpr ⟨h, lie_vermaGenerator_eq_smul b lam,
    fun _ hx => lie_vermaGenerator_eq_zero_of_mem_positiveNilradical b lam hx⟩⟩

/-- **Every highest weight module of weight `lam` is a quotient of the Verma module.** This is the
sense in which `M(lam)` is the universal highest weight module of weight `lam`, and the form in
which the classification of the irreducible highest weight modules consumes it. -/
theorem exists_surjective_lieModuleHom_of_isHighestWeightVector {v : N}
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    ∃ φ : VermaModule b lam →ₗ⁅K,L⁆ N,
      Function.Surjective φ ∧ φ (vermaGenerator b lam) = v := by
  obtain ⟨φ, hφ, -⟩ := existsUnique_lieModuleHom_apply_vermaGenerator b lam v hv.lie_eq_smul
    fun _ hx => hv.lie_eq_zero_of_mem_positiveNilradical hx
  refine ⟨φ, ?_, hφ⟩
  rw [← LieModuleHom.range_eq_top, ← top_le_iff, ← hgen, LieSubmodule.lieSpan_le]
  rintro w rfl
  exact ⟨vermaGenerator b lam, hφ⟩

/-- **The canonical generator vanishes exactly when the Verma ideal is improper.** So `M(lam) ≠ 0`
says that the left ideal generated by the Verma relations is proper, which follows from the
freeness of `U(L)` as a right `U(𝔟)`-module (`TauCeti.vermaIdeal_ne_top`). -/
theorem vermaGenerator_eq_zero_iff : vermaGenerator b lam = 0 ↔ vermaIdeal b lam = ⊤ := by
  rw [vermaGenerator, vermaMk_eq_zero_iff]
  refine ⟨fun h => eq_top_iff.mpr fun u _ => ?_, fun h => h ▸ trivial⟩
  simpa using Submodule.smul_mem (vermaIdeal b lam) u h

/-- **The Verma module vanishes exactly when its canonical generator does**, the generator
spanning it. -/
theorem subsingleton_vermaModule_iff :
    Subsingleton (VermaModule b lam) ↔ vermaGenerator b lam = 0 := by
  -- The quotient criterion is stated for a literal quotient, so unfold the named carrier before
  -- rewriting with it.
  change Subsingleton (U ⧸ vermaIdeal b lam) ↔ vermaGenerator b lam = 0
  rw [Submodule.Quotient.subsingleton_iff, ← vermaGenerator_eq_zero_iff]

/-! ### The Verma module is induced from the Borel character -/

/-- **The Verma ideal is the left ideal induced by the Borel character**: it is generated by the
elements `ι x - χ x` for `x` in the Borel subalgebra, where `χ = TauCeti.borelCharacter H b lam`
is the character `h + n ↦ lam h` of `𝔟 = H + n⁺`. So `M(lam)` is the module
`U(L) ⊗_{U(𝔟)} K_lam` induced from the one-dimensional `𝔟`-module of weight `lam`, presented as a
quotient of `U(L)`. -/
theorem vermaIdeal_eq_span_range_ι_sub_algebraMap :
    vermaIdeal b lam = Submodule.span U (Set.range fun x : borelSubalgebra H b ↦
      (ι K (x : L) : U) - algebraMap K U (borelCharacter H b lam x)) := by
  refine le_antisymm (Submodule.span_le.mpr ?_) (Submodule.span_le.mpr ?_)
  · rintro _ (⟨x, rfl⟩ | ⟨x, hx, rfl⟩)
    · exact Submodule.subset_span ⟨⟨x, le_borelSubalgebra H b x.2⟩, by
        dsimp only
        rw [borelCharacter_apply_of_mem_cartan H b lam x.2]⟩
    · exact Submodule.subset_span ⟨⟨x, positiveNilradical_le_borelSubalgebra H b hx⟩, by
        dsimp only
        rw [borelCharacter_apply_of_mem_positiveNilradical H b lam hx, map_zero, sub_zero]⟩
  · rintro _ ⟨⟨x, hx⟩, rfl⟩
    have hx' := hx
    rw [← LieSubalgebra.mem_toSubmodule, borelSubalgebra_toSubmodule, Submodule.mem_sup] at hx'
    obtain ⟨h, hh, n, hn, rfl⟩ := hx'
    have hsplit : (⟨h + n, hx⟩ : borelSubalgebra H b) =
        ⟨h, le_borelSubalgebra H b hh⟩ + ⟨n, positiveNilradical_le_borelSubalgebra H b hn⟩ := by
      ext
      simp
    have hχ : borelCharacter H b lam ⟨h + n, hx⟩ = lam ⟨h, hh⟩ := by
      rw [hsplit, map_add, borelCharacter_apply_of_mem_cartan H b lam hh,
        borelCharacter_apply_of_mem_positiveNilradical H b lam hn, add_zero]
    simp only [SetLike.mem_coe, hχ]
    convert Submodule.add_mem _ (ι_sub_algebraMap_mem_vermaIdeal b lam ⟨h, hh⟩)
      (ι_mem_vermaIdeal_of_mem_positiveNilradical b lam hn) using 1
    rw [map_add]
    abel

/-! ### The Verma module is nonzero -/

/-- **The Verma ideal is proper.** Its generators `ι x - lam x` for `x` in the Cartan subalgebra
and `ι x` for `x` in the positive nilradical are all of the form `ι x - χ x` for `x` in the Borel
subalgebra, where `χ = TauCeti.borelCharacter H b lam` is the character `h + n ↦ lam h`. The left
ideal generated by those is proper, by the freeness of `U(L)` as a right `U(𝔟)`-module
(`TauCeti.UniversalEnvelopingAlgebra.span_range_ι_sub_algebraMap_ne_top`). -/
@[simp]
theorem vermaIdeal_ne_top : vermaIdeal b lam ≠ ⊤ := by
  rw [vermaIdeal_eq_span_range_ι_sub_algebraMap]
  exact UniversalEnvelopingAlgebra.span_range_ι_sub_algebraMap_ne_top _ _

/-- **The Verma module is nonzero**: its canonical generator does not vanish, for every weight
`lam`. -/
@[simp]
theorem vermaGenerator_ne_zero : vermaGenerator b lam ≠ 0 :=
  fun h ↦ vermaIdeal_ne_top b lam ((vermaGenerator_eq_zero_iff b lam).mp h)

/-- **The canonical generator of the Verma module is a highest weight vector of weight `lam`**,
for every weight `lam`. -/
theorem isHighestWeightVector_vermaGenerator :
    IsHighestWeightVector b lam (vermaGenerator b lam) :=
  (isHighestWeightVector_vermaGenerator_iff b lam).mpr (vermaGenerator_ne_zero b lam)

instance : Nontrivial (VermaModule b lam) :=
  ⟨⟨vermaGenerator b lam, 0, vermaGenerator_ne_zero b lam⟩⟩

/-! ### The Verma module is free of rank one over `U(n⁻)` -/

/-- **The Verma module is a free `U(n⁻)`-module of rank one on its canonical generator**: the map
`U(n⁻) → M(lam)`, `y ↦ y · v_lam`, is a linear equivalence, where `U(n⁻)` acts on `M(lam)` through
the map `U(n⁻) → U(L)` induced by the inclusion of the negative nilradical. Its value is
`TauCeti.universalEnvelopingEquivVermaModule_apply`, and it intertwines left multiplication on
`U(n⁻)` with the action on `M(lam)` (`TauCeti.universalEnvelopingEquivVermaModule_mul`). -/
noncomputable def universalEnvelopingEquivVermaModule :
    _root_.UniversalEnvelopingAlgebra K (negativeNilradical H b) ≃ₗ[K] VermaModule b lam :=
  LinearEquiv.ofBijective
    (((vermaMk b lam).restrictScalars K).comp
      (UniversalEnvelopingAlgebra.map K (negativeNilradical H b).incl).toLinearMap)
    ⟨(injective_iff_map_eq_zero _).mpr fun y hy ↦ by
      rw [LinearMap.comp_apply, LinearMap.restrictScalars_apply, AlgHom.toLinearMap_apply,
        vermaMk_eq_zero_iff, vermaIdeal_eq_span_range_ι_sub_algebraMap] at hy
      exact (UniversalEnvelopingAlgebra.map_mem_span_range_ι_sub_algebraMap_iff_of_isCompl _
        (isCompl_negativeNilradical_borelSubalgebra H b)).mp hy,
    fun m ↦ by
      obtain ⟨u, rfl⟩ := vermaMk_surjective b lam m
      obtain ⟨y, hy⟩ := UniversalEnvelopingAlgebra.exists_sub_map_mem_span_range_ι_sub_algebraMap
        (borelCharacter H b lam) (negativeNilradical_sup_borelSubalgebra_eq_top H b) u
      rw [← vermaIdeal_eq_span_range_ι_sub_algebraMap, ← vermaMk_eq_iff] at hy
      exact ⟨y, hy.symm⟩⟩

/-- The equivalence `U(n⁻) ≃ M(lam)` sends `y` to `y · v_lam`. -/
@[simp]
theorem universalEnvelopingEquivVermaModule_apply
    (y : _root_.UniversalEnvelopingAlgebra K (negativeNilradical H b)) :
    universalEnvelopingEquivVermaModule b lam y =
      UniversalEnvelopingAlgebra.map K (negativeNilradical H b).incl y • vermaGenerator b lam := by
  rw [smul_vermaGenerator]
  -- The forward map is `vermaMk` after the induced map `U(n⁻) → U(L)`, composed as linear maps.
  exact LinearEquiv.ofBijective_apply _ _

/-- The equivalence `U(n⁻) ≃ M(lam)` sends `1` to the canonical generator `v_lam`. -/
theorem universalEnvelopingEquivVermaModule_one :
    universalEnvelopingEquivVermaModule b lam 1 = vermaGenerator b lam := by
  simp

/-- **The equivalence `U(n⁻) ≃ M(lam)` is `U(n⁻)`-linear**: it carries left multiplication by `y`
on `U(n⁻)` to the action of `y` on `M(lam)`. -/
theorem universalEnvelopingEquivVermaModule_mul
    (y z : _root_.UniversalEnvelopingAlgebra K (negativeNilradical H b)) :
    universalEnvelopingEquivVermaModule b lam (y * z) =
      UniversalEnvelopingAlgebra.map K (negativeNilradical H b).incl y •
        universalEnvelopingEquivVermaModule b lam z := by
  simp [mul_smul]

/-- **Lowering the canonical generator never gives zero**: for a nonzero `f` in the negative
nilradical, `f^k · v_lam ≠ 0` in `M(lam)` for every `k`. Through the freeness `U(n⁻) ≃ M(lam)` the
vector is the image of `(ι f)^k`, which is nonzero because `U(n⁻)` is a domain containing `n⁻`, by
Poincaré--Birkhoff--Witt. -/
theorem pow_toEnd_vermaGenerator_ne_zero {f : L} (hf : f ∈ negativeNilradical H b) (hf0 : f ≠ 0)
    (k : ℕ) : ((toEnd K L (VermaModule b lam) f) ^ k) (vermaGenerator b lam) ≠ 0 := by
  have key : ((toEnd K L (VermaModule b lam) f) ^ k) (vermaGenerator b lam) =
      universalEnvelopingEquivVermaModule b lam
        ((_root_.UniversalEnvelopingAlgebra.ι K (⟨f, hf⟩ : negativeNilradical H b)) ^ k) := by
    rw [universalEnvelopingEquivVermaModule_apply, map_pow, UniversalEnvelopingAlgebra.map_ι]
    induction k with
    | zero => simp
    | succ k ih =>
      rw [pow_succ', Module.End.mul_apply, ih, pow_succ', mul_smul, LieSubalgebra.coe_incl,
        vermaModule_ι_smul, toEnd_apply_apply]
  rw [key, LinearEquiv.map_ne_zero_iff]
  refine pow_ne_zero _ fun h ↦ hf0 ?_
  have := UniversalEnvelopingAlgebra.ι_injective K (negativeNilradical H b)
    (h.trans (map_zero _).symm)
  simpa using congrArg Subtype.val this

/-- **The irreducible quotient `L(lam)`**: the quotient of the Verma module by the maximal
submodule of `TauCeti/Algebra/Lie/HighestWeight/Maximal.lean`. As with
`TauCeti.VermaModule`, the carrier is a definition with its module structures declared
one by one, so that statements about `L(lam)` are made against this name rather than against the
quotient it is built from.

Nothing about it is irreducible by fiat: irreducibility is
`TauCeti.isIrreducible_irreducibleQuotient`, which rests on `M(lam) ≠ 0`. Naming the carrier is what
lets a statement about `L(lam)` be phrased at one fixed module instead of at an arbitrary
irreducible module carrying a highest weight vector of weight `lam`. -/
def irreducibleQuotient : Type max u v :=
  VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam

noncomputable instance : AddCommGroup (irreducibleQuotient b lam) :=
  inferInstanceAs
    (AddCommGroup (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

noncomputable instance : Module K (irreducibleQuotient b lam) :=
  inferInstanceAs
    (Module K (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

noncomputable instance : LieRingModule L (irreducibleQuotient b lam) :=
  inferInstanceAs
    (LieRingModule L (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

noncomputable instance : LieModule K L (irreducibleQuotient b lam) :=
  inferInstanceAs
    (LieModule K L (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

/-- **The canonical projection** `M(lam) → L(lam)`, bundled as a Lie module homomorphism, so that
its algebraic behaviour — `map_zero`, `map_add`, `map_smul`, `map_lie` — is available from the
`LieModuleHom` API without unfolding the quotient. It is the analogue for `L(lam)` of
`TauCeti.vermaMk`, and together with `TauCeti.irreducibleQuotientMk_surjective` it is how every
vector of `L(lam)` is reached. -/
noncomputable def irreducibleQuotientMk : VermaModule b lam →ₗ⁅K,L⁆ irreducibleQuotient b lam :=
  LieSubmodule.Quotient.mk' (maximalSubmodule H (VermaModule b lam) lam)

/-- **The canonical projection onto `L(lam)` is surjective**: every vector of `L(lam)` is the
class of one of `M(lam)`. This is the elimination rule matching
`TauCeti.irreducibleQuotientMk`, and it is what lets a statement about `L(lam)` be checked on
representatives without unfolding the quotient. -/
theorem irreducibleQuotientMk_surjective : Function.Surjective (irreducibleQuotientMk b lam) :=
  fun q => LieSubmodule.Quotient.surjective_mk' _ q

/-- **The canonical generator of `L(lam)`**, the class of the canonical generator of `M(lam)`.
It is a highest weight vector of weight `lam`
(`TauCeti.isHighestWeightVector_irreducibleQuotientGenerator`), and it is the introduction rule
through which `L(lam)` is populated without unfolding the quotient. The body is not exposed: the
public equation is `TauCeti.irreducibleQuotientMk_vermaGenerator`. -/
noncomputable def irreducibleQuotientGenerator : irreducibleQuotient b lam :=
  irreducibleQuotientMk b lam (vermaGenerator b lam)

@[simp]
theorem irreducibleQuotientMk_vermaGenerator :
    irreducibleQuotientMk b lam (vermaGenerator b lam) = irreducibleQuotientGenerator b lam :=
  (rfl)

/-- **The canonical generator generates `L(lam)`**, the canonical generator of `M(lam)` generating
`M(lam)` and the projection being surjective. So `L(lam)` is a highest weight module of weight
`lam`. -/
theorem lieSpan_irreducibleQuotientGenerator_eq_top :
    LieSubmodule.lieSpan K L {irreducibleQuotientGenerator b lam} = ⊤ :=
  lieSpan_mk_eq_top_of_lieSpan_eq_top (lieSpan_vermaGenerator_eq_top b lam) _

/-- **`L(lam)` is irreducible, for every weight `lam`.** The Verma module is nonzero, so it is a
highest weight module of weight `lam`, and its quotient by the maximal submodule is irreducible.
By `TauCeti.quotientMaximalSubmoduleEquivOfSurjectiveOfIsIrreducible` it is then the only
irreducible highest weight module of weight `lam`, up to isomorphism. -/
theorem isIrreducible_irreducibleQuotient :
    LieModule.IsIrreducible K L (irreducibleQuotient b lam) :=
  isIrreducible_quotient_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top
    (isHighestWeightVector_vermaGenerator b lam) (lieSpan_vermaGenerator_eq_top b lam)

instance : LieModule.IsIrreducible K L (irreducibleQuotient b lam) :=
  isIrreducible_irreducibleQuotient b lam

/-- **`L(lam)` carries a highest weight vector of weight `lam`**, its canonical generator; the
anti-vacuity companion of `TauCeti.isIrreducible_irreducibleQuotient`, without which any family of
pairwise non-isomorphic irreducibles would do. -/
theorem isHighestWeightVector_irreducibleQuotientGenerator :
    IsHighestWeightVector b lam (irreducibleQuotientGenerator b lam) :=
  isHighestWeightVector_mk_of_isHighestWeightVector_of_lieSpan_eq_top
    (isHighestWeightVector_vermaGenerator b lam) (lieSpan_vermaGenerator_eq_top b lam)

end TauCeti
