/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Galois.AbsoluteGaloisGroup.Cyclotomic.MarkedCase
public import TauCeti.NumberTheory.Padics.DyadicUnits
import TauCeti.FieldTheory.Galois.AbsoluteGaloisGroup.Cyclotomic.Range
import TauCeti.NumberTheory.Padics.PadicIntegers

/-!
# The dyadic cyclotomic image in the even-degree cases

For a finite extension `K` of `ℚ₂` with exactly two `2`-power roots of unity and even degree, the
marked classification of `G_K(2)` has two branches, separated by whether `-1` lies in the image of
the cyclotomic character `χ`. This file computes that image in each branch, as one of Labute's
closed subgroups of `ℤ₂ˣ` (`closedSubgroup_units_two_classification`):

* if `-1 ∈ Im χ`, then `Im χ = V^(f) = {±1} × U^(f)` for some `f ≥ 2`;
* if `-1 ∉ Im χ` and `K` contains no primitive fourth root of unity, then `Im χ` is the twisted
  subgroup `U^[f]` topologically generated by a unit `u` with `u = -1 + 2 ^ f`, `f ≥ 2`.

The image is closed since the absolute Galois group is compact. In the first branch it is not
`{±1}` because it is infinite (`infinite_range_localCyclotomicCharacter`). In the second it is not
contained in `U^(2) = 1 + 4ℤ₂`, since otherwise `K` would contain a primitive fourth root of
unity (`range_localCyclotomicCharacter_le_unitsPrincipal_iff`). The exponent `f` is the parameter
that the even marked normal forms take from the image.

## Main results

* `TauCeti.exists_range_localCyclotomicCharacter_eq_unitsPlusMinus`: `Im χ = V^(f)` when
  `-1 ∈ Im χ`.
* `TauCeti.exists_range_localCyclotomicCharacter_eq_topologicalClosure_zpowers`: `Im χ = U^[f]`
  when `-1 ∉ Im χ` and `μ₄ ⊄ K`.
* `TauCeti.range_localCyclotomicCharacter_of_degree_even_plusMinus`,
  `TauCeti.range_localCyclotomicCharacter_of_degree_even_principal`: the same computations under
  the branch predicates `IsDyadicEvenPlusMinusCase` and `IsDyadicEvenPrincipalCase`.

## References

* J. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), §5.
* J.-P. Serre, *Local Fields*, Chapter IV, §4.
-/

public section

namespace TauCeti

variable (K : Type*) [Field K]

/-- If `-1` is a value of the cyclotomic character of a finite extension `K` of `ℚ₂`, its image is
`V^(f) = {±1} × U^(f)` for some `f ≥ 2`. -/
theorem exists_range_localCyclotomicCharacter_eq_unitsPlusMinus [Algebra ℚ_[2] K]
    [FiniteDimensional ℚ_[2] K] (hneg : (-1 : ℤ_[2]ˣ) ∈ (localCyclotomicCharacter 2 K).range) :
    ∃ f : ℕ, 2 ≤ f ∧ (localCyclotomicCharacter 2 K).range = unitsPlusMinus f := by
  -- The even part `Im χ ⊓ U^(2)` is nontrivial: otherwise `Im χ = {±1}` would be finite.
  have hA : (localCyclotomicCharacter 2 K).range ⊓ unitsPrincipal 2 2 ≠ ⊥ := by
    intro h
    have hbot : (localCyclotomicCharacter 2 K).range ≠ ⊥ := fun hbot ↦
      PadicInt.units_neg_one_ne_one (by rwa [hbot, Subgroup.mem_bot] at hneg)
    have hinf := infinite_range_localCyclotomicCharacter 2 K
    rw [eq_zpowers_neg_one_of_inf_unitsPrincipal_two_eq_bot hbot h] at hinf
    exact not_finite_iff_infinite.mpr hinf
      (finite_zpowers.mpr (isOfFinOrder_iff_pow_eq_one.mpr ⟨2, two_pos, by simp⟩))
  obtain ⟨f, hf, h⟩ := exists_eq_unitsPrincipal_of_isClosed two_pos (fun _ ↦ le_rfl)
    ((isClosed_range_localCyclotomicCharacter 2 K).inter (isClosed_unitsPrincipal 2 2))
    inf_le_right hA
  exact ⟨f, hf, eq_unitsPlusMinus_of_inf_unitsPrincipal_two_eq h hneg⟩

/-- If `K` contains no primitive fourth root of unity and `-1` is not a value of its cyclotomic
character, the image of the character is the twisted subgroup `U^[f]`, topologically generated
by a unit `u = -1 + 2 ^ f` with `f ≥ 2`. -/
theorem exists_range_localCyclotomicCharacter_eq_topologicalClosure_zpowers [NeZero (2 : K)]
    (hmu : ¬ ∃ ζ : K, IsPrimitiveRoot ζ 4)
    (hneg : (-1 : ℤ_[2]ˣ) ∉ (localCyclotomicCharacter 2 K).range) :
    ∃ (f : ℕ) (u : ℤ_[2]ˣ), 2 ≤ f ∧ (u : ℤ_[2]) = -1 + 2 ^ f ∧
      (localCyclotomicCharacter 2 K).range = (Subgroup.zpowers u).topologicalClosure := by
  -- Without a primitive fourth root of unity the image is not contained in `U^(2)`.
  have : NeZero ((2 : ℕ) : K) := ⟨by exact_mod_cast NeZero.ne (2 : K)⟩
  have hle : ¬ (localCyclotomicCharacter 2 K).range ≤ unitsPrincipal 2 2 := by
    rw [range_localCyclotomicCharacter_le_unitsPrincipal_iff]
    simpa using hmu
  have hbot : (localCyclotomicCharacter 2 K).range ≠ ⊥ := fun h ↦ hle (h ▸ bot_le)
  rcases closedSubgroup_units_two_classification (isClosed_range_localCyclotomicCharacter 2 K)
    hbot with ⟨f, hf, h⟩ | ⟨f, -, h⟩ | h | h
  · exact (hle (h ▸ unitsPrincipal_antitone 2 hf)).elim
  · exact (hneg (h ▸ neg_one_mem_unitsPlusMinus f)).elim
  · exact (hneg (h ▸ Subgroup.mem_zpowers _)).elim
  · exact h

section MarkedCase

variable [Algebra ℚ_[2] K] [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]

/-- **The cyclotomic image in the even plus-minus branch** is `V^(f) = {±1} × U^(f)` for some
`f ≥ 2`. -/
theorem range_localCyclotomicCharacter_of_degree_even_plusMinus [FiniteDimensional ℚ_[2] K]
    (hcase : IsDyadicEvenPlusMinusCase K) :
    ∃ f : ℕ, 2 ≤ f ∧ (localCyclotomicCharacter 2 K).range = unitsPlusMinus f :=
  exists_range_localCyclotomicCharacter_eq_unitsPlusMinus K hcase.neg_one_mem_range

/-- **The cyclotomic image in the even principal branch** is the twisted subgroup `U^[f]`,
topologically generated by a unit `u = -1 + 2 ^ f` with `f ≥ 2`. -/
theorem range_localCyclotomicCharacter_of_degree_even_principal
    (hcase : IsDyadicEvenPrincipalCase K) :
    ∃ (f : ℕ) (u : ℤ_[2]ˣ), 2 ≤ f ∧ (u : ℤ_[2]) = -1 + 2 ^ f ∧
      (localCyclotomicCharacter 2 K).range = (Subgroup.zpowers u).topologicalClosure := by
  have : CharZero K := charZero_of_injective_algebraMap (algebraMap ℚ_[2] K).injective
  -- Exactly two `2`-power roots of unity means no primitive fourth root of unity.
  refine exists_range_localCyclotomicCharacter_eq_topologicalClosure_zpowers K (fun hmu ↦ ?_)
    hcase.neg_one_notMem_range
  exact (localRootOfUnityOrder_ne_two_iff two_ne_zero).mpr hmu
    hcase.localRootOfUnityOrder_eq_two

end MarkedCase

end TauCeti
