/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.ClassGroup.Basic
import TauCeti.RingTheory.FractionalIdeal.CoprimeRepresentative

/-!
# Coprime representatives of invertible ideal classes

Let `R` be a domain, and let `𝔞` be an ideal of `R` contained in only finitely many maximal ideals,
for instance an ideal with finite quotient ring (`Ideal.finite_setOfPred_isMaximal_and_le`). Every
class of invertible ideals of `R` is then represented by an integral ideal coprime to `𝔞`. This is
the class-group form of `FractionalIdeal.exists_coeIdeal_eq_spanSingleton_mul_and_sup_eq_top`.

No Dedekind hypothesis is made. The motivating case is a non-maximal order `O` in a number field
and the conductor of `O`, where the result says that the Picard group of `O` is generated by ideals
coprime to the conductor. Those are the ideals that extension and contraction match with ideals of
the maximal order.

## Main results

* `ClassGroup.exists_mk_eq_and_sup_eq_top`: every class of invertible ideals is the class of an
  invertible integral ideal coprime to `𝔞`.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, §7, Corollary 7.17 (orders in quadratic fields).
* G. S. Kopp and J. C. Lagarias, *Class Field Theory for Orders of Number Fields*, §2.
-/

open scoped nonZeroDivisors

public section

namespace ClassGroup

variable {R K : Type*} [CommRing R] [IsDomain R] [Field K] [Algebra R K] [IsFractionRing R K]

/-- **Coprime representatives of ideal classes.** If an ideal `𝔞` of a domain `R` lies in only
finitely many maximal ideals, then every class of invertible ideals of `R` is the class of an
invertible integral ideal coprime to `𝔞`. -/
theorem exists_mk_eq_and_sup_eq_top {𝔞 : Ideal R}
    (h𝔞 : {P : Ideal R | P.IsMaximal ∧ 𝔞 ≤ P}.Finite) (c : ClassGroup R) :
    ∃ (I : Ideal R) (hI : IsUnit (I : FractionalIdeal R⁰ K)), mk K hI.unit = c ∧ I ⊔ 𝔞 = ⊤ := by
  refine ClassGroup.induction (K := K) (fun J => ?_) c
  obtain ⟨a, ha, I, hI, hI𝔞⟩ :=
    FractionalIdeal.exists_coeIdeal_eq_spanSingleton_mul_and_sup_eq_top J h𝔞
  set u := toPrincipalIdeal R K (Units.mk0 a ha) * J
  -- `↑u = ↑(toPrincipalIdeal (a)) * ↑J = spanSingleton a * ↑J = ↑I`.
  have hu : (I : FractionalIdeal R⁰ K) = u := by
    rw [hI, Units.val_mul, coe_toPrincipalIdeal, Units.val_mk0]
  have hIu : IsUnit (I : FractionalIdeal R⁰ K) := hu ▸ u.isUnit
  have hIu_unit : hIu.unit = u := Units.ext hu
  refine ⟨I, hIu, ?_, hI𝔞⟩
  rw [hIu_unit, map_mul, mk_eq_one_iff.mpr ⟨⟨a, by simp [coe_toPrincipalIdeal]⟩⟩, one_mul]

end ClassGroup
