/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Comap

/-!
# Images of Hopf ideals under morphisms into commutative Hopf algebras

This file records the pushforward of a Hopf ideal along a bialgebra morphism
`f : H →ₐc[R] K` with commutative codomain: the extension `Ideal.map f I` of a Hopf ideal
`I` — the ideal of `K` generated by the image of `I` — is again a Hopf ideal. Commutativity
of the codomain makes the generated ideal two-sided and the antipode an algebra
endomorphism; the coideal and counit conditions transport along `f` because `f`
intertwines the comultiplications and counits.

Commutativity of the codomain is one of two independent sufficient conditions for the
generated ideal to be antipode-stable and two-sided (the other is surjectivity of `f`,
where the generated ideal is the set-theoretic image); for a general morphism of
noncommutative Hopf algebras the left ideal generated by the image need not be two-sided,
and the standard construction uses the two-sided ideal `K f(I) K` instead. The commutative
case is the one the affine group-scheme dictionary consumes.

Together with `TauCeti.HopfIdeal.comapOfSurjective`, this gives both variance directions for Hopf
ideals. The two are adjoint along surjective morphisms
(`TauCeti.HopfIdeal.map_le_iff_le_comapOfSurjective`).

This is a Layer 3 prerequisite for the reductive-groups roadmap target "Hopf ideals ↔
closed subgroup schemes", specifically the "kernels" part of the dictionary: the kernel of
the affine group-scheme morphism induced by `f` is cut out by the image of the
augmentation ideal under `f`.

## Main declarations

* `TauCeti.HopfIdeal.map`: the image of a Hopf ideal under a bialgebra morphism with
  commutative codomain.
* `TauCeti.HopfIdeal.map_toIdeal` and `TauCeti.HopfIdeal.mem_map_of_mem`: characteristic
  API, with the universal property `TauCeti.HopfIdeal.map_le_iff`.
* `TauCeti.HopfIdeal.map_tensor_leftTensorIdeal` and
  `TauCeti.HopfIdeal.map_tensor_rightTensorIdeal`: compatibility of the left and right tensor
  ideals with a tensor-square map.
* `TauCeti.HopfIdeal.map_bot`, `TauCeti.HopfIdeal.map_sup`, `TauCeti.HopfIdeal.map_iSup`,
  and `TauCeti.HopfIdeal.map_sSup`: the image preserves the join structure.
* `TauCeti.HopfIdeal.map_id` and `TauCeti.HopfIdeal.map_map`: identity and composition
  laws.
* `TauCeti.HopfIdeal.map_le_iff_le_comapOfSurjective`: the image is left adjoint to the inverse
  image along a surjective morphism, with the correspondence lemmas
  `TauCeti.HopfIdeal.map_comapOfSurjective`, `TauCeti.HopfIdeal.comapOfSurjective_map`,
  `TauCeti.HopfIdeal.comapOfSurjective_map_of_bijective`, and
  `TauCeti.HopfIdeal.map_eq_bot_iff_le_ker`.
* `TauCeti.HopfIdeal.comapOfSurjective_map_mkBialgHom`: pulling the image of `J` back from
  `H ⧸ I` along the quotient morphism recovers `J`, provided `I ≤ J`.

## References

The construction is the standard image of a Hopf ideal; see for instance
[Milne, *Algebraic Groups*][milne2017] around Definition 3.10, where quotients by such
images cut out closed subgroup schemes.
-/

public section

open scoped TensorProduct

namespace TauCeti

universe u v w x

namespace HopfIdeal

section Semiring

variable {R : Type u} [CommSemiring R]
section TensorIdeals

variable {H : Type v} {K : Type w} [Semiring H] [Semiring K]
variable [Algebra R H] [Algebra R K]

/-- The tensor square of an algebra morphism carries the left tensor ideal generated by `I`
onto the left tensor ideal generated by the image of `I`. -/
@[simp] theorem map_tensor_leftTensorIdeal (f : H →ₐ[R] K) (I : Ideal H) :
    Ideal.map (Algebra.TensorProduct.map f f : (H ⊗[R] H) →+* (K ⊗[R] K))
      (leftTensorIdeal (R := R) (H := H) I) =
      leftTensorIdeal (R := R) (H := K) (Ideal.map f.toRingHom I) := by
  rw [leftTensorIdeal, leftTensorIdeal, Ideal.map_map, Ideal.map_map]
  congr 1
  ext x
  exact DFunLike.congr_fun
    (Algebra.TensorProduct.map_comp_includeLeft f f) x

/-- The tensor square of an algebra morphism carries the right tensor ideal generated by `I`
onto the right tensor ideal generated by the image of `I`.

This is the ideal-theoretic compatibility used to transport conjugation stability, hence
normality, along a morphism of commutative Hopf algebras. -/
@[simp] theorem map_tensor_rightTensorIdeal (f : H →ₐ[R] K) (I : Ideal H) :
    Ideal.map (Algebra.TensorProduct.map f f : (H ⊗[R] H) →+* (K ⊗[R] K))
      (rightTensorIdeal (R := R) (H := H) I) =
      rightTensorIdeal (R := R) (H := K) (Ideal.map f.toRingHom I) := by
  rw [rightTensorIdeal, rightTensorIdeal, Ideal.map_map, Ideal.map_map]
  congr 1
  ext x
  exact DFunLike.congr_fun
    (Algebra.TensorProduct.map_comp_includeRight f f) x

end TensorIdeals

variable {H : Type v} {K : Type w} [Semiring H] [CommSemiring K]
variable [HopfAlgebra R H] [HopfAlgebra R K]

private theorem comul_mem_map (I : HopfIdeal R H) (f : H →ₐc[R] K) ⦃x : K⦄
    (hx : x ∈ Ideal.map (f : H →+* K) I.toIdeal) :
    Coalgebra.comul (R := R) x ∈
      leftTensorIdeal (R := R) (H := K) (Ideal.map (f : H →+* K) I.toIdeal) ⊔
        rightTensorIdeal (R := R) (H := K) (Ideal.map (f : H →+* K) I.toIdeal) := by
  have h : Ideal.map (f : H →+* K) I.toIdeal ≤
      Ideal.comap (Bialgebra.comulAlgHom R K).toRingHom
        (leftTensorIdeal (R := R) (H := K) (Ideal.map (f : H →+* K) I.toIdeal) ⊔
          rightTensorIdeal (R := R) (H := K) (Ideal.map (f : H →+* K) I.toIdeal)) := by
    rw [Ideal.map_le_iff_le_comap]
    intro i hi
    simp only [Ideal.mem_comap, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
      Bialgebra.comulAlgHom_apply]
    have hbridge : TensorProduct.map (f : H →ₗ[R] K) (f : H →ₗ[R] K)
          (Coalgebra.comul (R := R) i) =
        Algebra.TensorProduct.map (f : H →ₐ[R] K) (f : H →ₐ[R] K)
          (Coalgebra.comul (R := R) i) := by
      rw [← TensorProduct.AlgebraTensorModule.map_eq]
      exact (LinearMap.congr_fun
        (Algebra.TensorProduct.toLinearMap_map (f : H →ₐ[R] K) (f : H →ₐ[R] K)) _).symm
    have hmap : f.toAlgHom.toRingHom = (f : H →+* K) := by
      ext
      rfl
    rw [(CoalgHomClass.map_comp_comul_apply f i).symm.trans hbridge,
      ← hmap, ← map_tensor_leftTensorIdeal f.toAlgHom,
      ← map_tensor_rightTensorIdeal f.toAlgHom, ← Ideal.map_sup]
    exact Ideal.mem_map_of_mem _ (I.comul_mem hi)
  simpa using Ideal.mem_comap.mp (h hx)

private theorem counit_eq_zero_map (I : HopfIdeal R H) (f : H →ₐc[R] K) ⦃x : K⦄
    (hx : x ∈ Ideal.map (f : H →+* K) I.toIdeal) : Coalgebra.counit (R := R) x = 0 := by
  have h : Ideal.map (f : H →+* K) I.toIdeal ≤
      Ideal.comap (Bialgebra.counitAlgHom R K).toRingHom ⊥ := by
    rw [Ideal.map_le_iff_le_comap]
    intro i hi
    simp only [Ideal.mem_comap, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
      Bialgebra.counitAlgHom_apply, Ideal.mem_bot, CoalgHomClass.counit_comp_apply]
    exact I.counit_eq_zero hi
  simpa using Ideal.mem_comap.mp (h hx)

private theorem antipode_mem_map (I : HopfIdeal R H) (f : H →ₐc[R] K) ⦃x : K⦄
    (hx : x ∈ Ideal.map (f : H →+* K) I.toIdeal) :
    HopfAlgebra.antipode R x ∈ Ideal.map (f : H →+* K) I.toIdeal := by
  have h : Ideal.map (f : H →+* K) I.toIdeal ≤
      Ideal.comap (HopfAlgebra.antipodeAlgHom R K).toRingHom
        (Ideal.map (f : H →+* K) I.toIdeal) := by
    rw [Ideal.map_le_iff_le_comap]
    intro i hi
    simp only [Ideal.mem_comap, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
      HopfAlgebra.antipodeAlgHom_apply]
    rw [← BialgHomClass.map_antipode]
    exact Ideal.mem_map_of_mem _ (I.antipode_mem hi)
  simpa using Ideal.mem_comap.mp (h hx)

/-- The image of a Hopf ideal under a bialgebra morphism into a commutative Hopf algebra:
the Hopf ideal generated by the set-theoretic image.

Its underlying ideal is the ideal-theoretic extension `Ideal.map`. -/
def map (I : HopfIdeal R H) (f : H →ₐc[R] K) : HopfIdeal R K :=
  ofIdeal (Ideal.map (f : H →+* K) I.toIdeal) (comul_mem_map I f)
    (counit_eq_zero_map I f) (antipode_mem_map I f)

/-- The underlying ideal of `I.map f` is the ordinary ideal-theoretic image. -/
@[simp]
theorem map_toIdeal (I : HopfIdeal R H) (f : H →ₐc[R] K) :
    (I.map f).toIdeal = Ideal.map (f : H →+* K) I.toIdeal := by
  -- `map` has no equation lemma to rewrite with; `change` spells out its definitional
  -- unfolding to an `ofIdeal` application, whose underlying ideal is definitionally the
  -- ideal it was built from.
  change (ofIdeal (Ideal.map (f : H →+* K) I.toIdeal) _ _ _).toIdeal = _
  rfl

/-- The image of a Hopf ideal contains the image of each of its elements. -/
theorem mem_map_of_mem (f : H →ₐc[R] K) {I : HopfIdeal R H} {x : H} (hx : x ∈ I) :
    f x ∈ I.map f :=
  Ideal.mem_map_of_mem _ hx

/-- Image of Hopf ideals is monotone. -/
theorem map_mono (f : H →ₐc[R] K) {I J : HopfIdeal R H} (hIJ : I ≤ J) :
    I.map f ≤ J.map f :=
  Ideal.map_mono (toIdeal_le_toIdeal.mpr hIJ)

/-- The universal property of the image: `I.map f` is below `J` exactly when `f` sends
`I` into `J`. Membership in `I.map f` itself is characterized only along surjective
morphisms (`TauCeti.HopfIdeal.mem_map_iff_of_surjective`), since the image Hopf ideal is
generated by, and in general larger than, the set-theoretic image of `I`. -/
theorem map_le_iff {f : H →ₐc[R] K} {I : HopfIdeal R H} {J : HopfIdeal R K} :
    I.map f ≤ J ↔ ∀ ⦃x : H⦄, x ∈ I → f x ∈ J := by
  rw [← toIdeal_le_toIdeal, map_toIdeal, Ideal.map_le_iff_le_comap]
  exact ⟨fun h x hx => mem_toIdeal.mp (Ideal.mem_comap.mp (h (mem_toIdeal.mpr hx))),
    fun h x hx => Ideal.mem_comap.mpr (mem_toIdeal.mpr (h (mem_toIdeal.mp hx)))⟩

/-- The image of the zero Hopf ideal is zero. -/
@[simp]
theorem map_bot (f : H →ₐc[R] K) : (⊥ : HopfIdeal R H).map f = ⊥ :=
  ext fun _ => by
    rw [← mem_toIdeal, map_toIdeal, bot_toIdeal, Ideal.map_bot]
    exact Ideal.mem_bot.trans mem_bot.symm

/-- For a surjective morphism, membership in the image Hopf ideal means being the value
of a member. -/
@[simp]
theorem mem_map_iff_of_surjective {f : H →ₐc[R] K} (hf : Function.Surjective f)
    {I : HopfIdeal R H} {y : K} : y ∈ I.map f ↔ ∃ x ∈ I, f x = y := by
  rw [← mem_toIdeal, map_toIdeal]
  simp only [Ideal.mem_map_iff_of_surjective (f : H →+* K) hf, mem_toIdeal]
  rfl

/-- The image vanishes exactly when the Hopf ideal is contained in the kernel of the
underlying ring homomorphism. For surjective morphisms the right side is the kernel Hopf
ideal (`TauCeti.HopfIdeal.map_eq_bot_iff_le_ker`). -/
theorem map_eq_bot_iff (I : HopfIdeal R H) (f : H →ₐc[R] K) :
    I.map f = ⊥ ↔ I.toIdeal ≤ RingHom.ker (f : H →+* K) := by
  rw [← le_bot_iff, ← toIdeal_le_toIdeal, map_toIdeal, bot_toIdeal, le_bot_iff,
    Ideal.map_eq_bot_iff_le_ker]

/-- Image of Hopf ideals preserves binary joins. -/
@[simp]
theorem map_sup (I J : HopfIdeal R H) (f : H →ₐc[R] K) :
    (I ⊔ J).map f = I.map f ⊔ J.map f :=
  ext fun _ => by
    rw [← mem_toIdeal, map_toIdeal, sup_toIdeal, Ideal.map_sup, ← mem_toIdeal, sup_toIdeal,
      map_toIdeal, map_toIdeal]

/-- Image of Hopf ideals preserves indexed suprema. -/
@[simp]
theorem map_iSup {ι : Sort*} (I : ι → HopfIdeal R H) (f : H →ₐc[R] K) :
    (⨆ i, I i).map f = ⨆ i, (I i).map f :=
  ext fun _ => by
    rw [← mem_toIdeal, map_toIdeal, iSup_toIdeal, Ideal.map_iSup, ← mem_toIdeal, iSup_toIdeal]
    simp only [map_toIdeal]

/-- Image of Hopf ideals preserves suprema of sets. -/
@[simp]
theorem map_sSup (S : Set (HopfIdeal R H)) (f : H →ₐc[R] K) :
    (sSup S).map f = sSup ((fun I => I.map f) '' S) := by
  rw [sSup_eq_iSup', map_iSup, sSup_image']

end Semiring

section Id

variable {R : Type u} [CommSemiring R]
variable {H : Type v} [CommSemiring H] [HopfAlgebra R H]

/-- The image of a Hopf ideal under the identity morphism. -/
@[simp]
theorem map_id (I : HopfIdeal R H) : I.map (BialgHom.id R H) = I :=
  le_antisymm (map_le_iff.mpr fun x hx => by rw [BialgHom.coe_id]; exact hx)
    fun x hx => by simpa [BialgHom.coe_id] using mem_map_of_mem (BialgHom.id R H) hx

end Id

section Comp

variable {R : Type u} [CommSemiring R]
variable {H : Type v} {K : Type w} {L : Type x}
variable [Semiring H] [CommSemiring K] [CommSemiring L]
variable [HopfAlgebra R H] [HopfAlgebra R K] [HopfAlgebra R L]

/-- Image of Hopf ideals is functorial. -/
@[simp]
theorem map_map (I : HopfIdeal R H) (f : H →ₐc[R] K) (g : K →ₐc[R] L) :
    (I.map f).map g = I.map (g.comp f) :=
  le_antisymm
    (by
      rw [← toIdeal_le_toIdeal, map_toIdeal, map_toIdeal, Ideal.map_map,
        Ideal.map_le_iff_le_comap]
      intro i hi
      have h := mem_map_of_mem (g.comp f) (mem_toIdeal.mp hi)
      rw [BialgHom.coe_comp] at h
      exact Ideal.mem_comap.mpr (mem_toIdeal.mpr h))
    (map_le_iff.mpr fun x hx => by
      rw [BialgHom.coe_comp]
      exact mem_map_of_mem g (mem_map_of_mem f hx))

end Comp

section Adjunction

variable {R : Type u} [CommRing R]
variable {H : Type v} {K : Type w} [Ring H] [CommRing K]
variable [HopfAlgebra R H] [HopfAlgebra R K]

/-- Along a surjective morphism, the image of Hopf ideals is left adjoint to the inverse
image. -/
theorem map_le_iff_le_comapOfSurjective {f : H →ₐc[R] K} (hf : Function.Surjective f)
    {I : HopfIdeal R H} {J : HopfIdeal R K} :
    I.map f ≤ J ↔ I ≤ J.comapOfSurjective f hf := by
  rw [map_le_iff, le_def]
  exact ⟨fun h x hx => mem_comapOfSurjective.mpr (h hx),
    fun h x hx => mem_comapOfSurjective.mp (h hx)⟩

/-- Along a surjective morphism, image after inverse image recovers the Hopf ideal. -/
@[simp]
theorem map_comapOfSurjective (J : HopfIdeal R K) (f : H →ₐc[R] K)
    (hf : Function.Surjective f) : (J.comapOfSurjective f hf).map f = J :=
  ext fun _ => by
    rw [← mem_toIdeal, map_toIdeal, comapOfSurjective_toIdeal,
      Ideal.map_comap_of_surjective (f : H →+* K) hf, mem_toIdeal]

/-- Along a surjective morphism, inverse image after image is the join with the kernel. -/
theorem comapOfSurjective_map (I : HopfIdeal R H) (f : H →ₐc[R] K)
    (hf : Function.Surjective f) : (I.map f).comapOfSurjective f hf = I ⊔ kerOfSurjective f hf :=
  ext fun x => by
    rw [← mem_toIdeal, comapOfSurjective_toIdeal, map_toIdeal,
      Ideal.comap_map_of_surjective (f : H →+* K) hf, ← mem_toIdeal, sup_toIdeal,
      kerOfSurjective_toIdeal, RingHom.ker_eq_comap_bot]
    exact Iff.rfl

/-- Along a bijective morphism, inverse image after image recovers the Hopf ideal. -/
theorem comapOfSurjective_map_of_bijective (I : HopfIdeal R H) (f : H →ₐc[R] K)
    (hf : Function.Bijective f) : (I.map f).comapOfSurjective f hf.2 = I := by
  rw [comapOfSurjective_map, (kerOfSurjective_eq_bot_iff f hf.2).2 hf.1, sup_bot_eq]

/-- The image vanishes exactly on Hopf ideals contained in the kernel Hopf ideal: the
surjective bundled form of `TauCeti.HopfIdeal.map_eq_bot_iff`. -/
theorem map_eq_bot_iff_le_ker (I : HopfIdeal R H) (f : H →ₐc[R] K)
    (hf : Function.Surjective f) : I.map f = ⊥ ↔ I ≤ kerOfSurjective f hf := by
  rw [map_eq_bot_iff]
  constructor
  · intro h x hx
    exact (mem_kerOfSurjective f hf).mpr (RingHom.mem_ker.mp (h (mem_toIdeal.mpr hx)))
  · intro h x hx
    exact RingHom.mem_ker.mpr ((mem_kerOfSurjective f hf).mp (h (mem_toIdeal.mp hx)))

end Adjunction

section Quotient

variable {R : Type u} [CommRing R]
variable {H : Type v} [CommRing H] [HopfAlgebra R H]

/-- Pulling the image of `J` in `H ⧸ I` back along the quotient morphism recovers `J`
when `I ≤ J`. -/
@[simp]
theorem comapOfSurjective_map_mkBialgHom {I J : HopfIdeal R H} (hIJ : I ≤ J) :
    (J.map (Bialgebra.Quotient.mkBialgHom I.toIdeal)).comapOfSurjective
        (Bialgebra.Quotient.mkBialgHom I.toIdeal)
        (by
          intro q
          obtain ⟨h, rfl⟩ := Ideal.Quotient.mk_surjective q
          exact ⟨h, Bialgebra.Quotient.mkBialgHom_apply I.toIdeal h⟩) = J := by
  rw [comapOfSurjective_map, kerOfSurjective_mkBialgHom, sup_eq_left]
  exact hIJ

end Quotient

end HopfIdeal

end TauCeti
