/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.Basic
public import TauCeti.AlgebraicGeometry.IdealSheaf.Module
public import TauCeti.AlgebraicGeometry.LineBundle.Basic
public import TauCeti.Algebra.Category.ModuleCat.Sheaf.Over

/-!
# The ideal sheaf of an effective Cartier divisor is invertible

Let `D ⊆ X` be an effective Cartier divisor, given by an ideal sheaf `I` which near every point is
generated, on an affine open `U`, by a single nonzerodivisor `a` of `Γ(X, U)`. Then the ideal sheaf
`I ⊆ 𝒪_X` (`Scheme.IdealSheafData.sheaf`) is an invertible sheaf: over `U`, multiplication by `a`
is an isomorphism `𝒪_U ≅ I|_U`.

No integrality assumption is made on `X`, so this applies to the relative effective Cartier
divisors on the base changes `X_T = T ×_S X`, whatever the scheme `T`. The dual of this invertible
sheaf is the line bundle `𝒪_X(D)`, the value of the Abel map on `D`.

Over an open `V ⊆ U` which is not affine, the sections of `I` are still the multiples of `a`
(`exists_mul_eq_of_ideal_eq_span`): on the affine opens inside `V` they are, by the
quasi-coherence of `I`, and the local quotients glue because `a` remains a nonzerodivisor on every
open subset of `U` (`AlgebraicGeometry.IsAffineOpen.isSMulRegular_map`).

The converse, that a closed subscheme whose ideal sheaf is invertible is an effective Cartier
divisor, is not proved here.

## Main declarations

* `Scheme.IdealSheafData.exists_mul_eq_of_ideal_eq_span`: if `I` is generated by a nonzerodivisor
  `a` on an affine open `U`, then every section of `I` over an open `V ⊆ U` is a multiple of `a`,
  and `Scheme.IdealSheafData.bijective_smul_map_sectionMk` makes `a` a basis of `I` over `V`;
* `Scheme.IdealSheafData.unitOverIsoOfIdealEqSpan`: the resulting trivialization `𝒪_U ≅ I|_U`,
  which is multiplication by `a` (`sheafι_app_unitOverIsoOfIdealEqSpan_hom`);
* `Scheme.IdealSheafData.IsEffectiveCartier.isInvertible_sheaf`: the ideal sheaf of an effective
  Cartier divisor is invertible, packaged as `IsEffectiveCartier.toInvertibleSheaf`.

## References

* The Stacks Project, *Divisors*, Section *Effective Cartier divisors* (Tag 01WQ), where the ideal
  sheaf of an effective Cartier divisor is shown to be invertible.
-/

public section

open CategoryTheory Opposite TopologicalSpace

universe u

namespace AlgebraicGeometry

noncomputable section

variable {X : Scheme.{u}}

namespace Scheme.IdealSheafData

variable (I : X.IdealSheafData)

/-- If the ideal sheaf `I` is generated on an affine open `U` by a nonzerodivisor `a`, then over
every open `V ⊆ U` the sections of `I` are the multiples of the restriction of `a`. -/
theorem exists_mul_eq_of_ideal_eq_span {U : X.affineOpens} {a : Γ(X, U)}
    (ha : IsSMulRegular Γ(X, U) a) (hIa : I.ideal U = Ideal.span {a}) {V : X.Opens}
    (hVU : V ≤ U.1) {s : Γ(X, V)} (hs : s ∈ I.sections V) :
    ∃ t : Γ(X, V), X.presheaf.map (homOfLE hVU).op a * t = s := by
  -- The affine opens contained in `V`, which cover it.
  let ι := {W : X.affineOpens // W.1 ≤ V}
  have hcover : V ≤ ⨆ W : ι, W.1.1 := by
    intro x hx
    obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWV⟩ :=
      X.isBasis_affineOpens.exists_subset_of_mem_open hx V.isOpen
    exact Opens.mem_iSup.mpr ⟨⟨⟨W, hW⟩, hWV⟩, hxW⟩
  -- On each affine open `W ⊆ V`, quasi-coherence gives `I(W) = a Γ(X, W)`, hence a quotient `t_W`.
  have hloc (W : ι) : ∃ t : Γ(X, W.1),
      X.presheaf.map (homOfLE (W.2.trans hVU)).op a * t = X.presheaf.map (homOfLE W.2).op s := by
    have hsW : X.presheaf.map (homOfLE W.2).op s ∈ I.ideal W.1 := by
      rw [← I.sections_eq_ideal]
      exact I.map_mem_sections _ hs
    rw [← I.map_ideal (U := W.1) (V := U) (W.2.trans hVU), hIa, Ideal.map_span,
      Set.image_singleton, Ideal.mem_span_singleton'] at hsW
    obtain ⟨t, ht⟩ := hsW
    exact ⟨t, (mul_comm _ _).trans ht⟩
  choose t ht using hloc
  -- The local quotients agree on overlaps, since `a` is a nonzerodivisor on every open of `U`.
  obtain ⟨t', ht', -⟩ : ∃! t' : Γ(X, V), ∀ W : ι, X.presheaf.map (homOfLE W.2).op t' = t W :=
    X.sheaf.existsUnique_gluing' (fun W : ι ↦ W.1.1) V (fun W ↦ homOfLE W.2) hcover t
      fun W₁ W₂ ↦ by
      refine U.2.isSMulRegular_map (inf_le_left.trans (W₁.2.trans hVU)) ha ?_
      have h₁ := congrArg (X.presheaf.map (homOfLE (inf_le_left : W₁.1.1 ⊓ W₂.1.1 ≤ _)).op)
        (ht W₁)
      have h₂ := congrArg (X.presheaf.map (homOfLE (inf_le_right : W₁.1.1 ⊓ W₂.1.1 ≤ _)).op)
        (ht W₂)
      simp only [map_mul] at h₁ h₂
      simp only [← ConcreteCategory.comp_apply, ← Functor.map_comp, ← op_comp, homOfLE_comp]
        at h₁ h₂
      exact h₁.trans h₂.symm
  refine ⟨t', X.IsSheaf.section_ext fun x hx ↦ ?_⟩
  obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWV⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open hx V.isOpen
  replace hWV : W ≤ V := hWV
  refine ⟨W, hWV, hxW, ?_⟩
  have h := ht ⟨⟨W, hW⟩, hWV⟩
  rw [← ht' ⟨⟨W, hW⟩, hWV⟩] at h
  simp only [map_mul]
  simp only [← ConcreteCategory.comp_apply, ← Functor.map_comp, ← op_comp, homOfLE_comp]
  exact h

/-- If the ideal sheaf `I` is generated on an affine open `U` by `a`, then `a` is a section of `I`
over `U`. -/
lemma mem_sections_of_ideal_eq_span {U : X.affineOpens} {a : Γ(X, U)}
    (hIa : I.ideal U = Ideal.span {a}) : a ∈ I.sections U.1 := by
  rw [I.sections_eq_ideal U, hIa]
  exact Ideal.mem_span_singleton_self a

/-- If the ideal sheaf `I` is generated on an affine open `U` by a nonzerodivisor `a`, then over
every open `V ⊆ U`, multiplication by the restriction of `a` is a bijection from `Γ(X, V)` onto
the sections of `I` over `V`. -/
theorem bijective_smul_map_sectionMk {U : X.affineOpens} {a : Γ(X, U)}
    (ha : IsSMulRegular Γ(X, U) a) (hIa : I.ideal U = Ideal.span {a}) {V : X.Opens}
    (hVU : V ≤ U.1) :
    Function.Bijective fun r : Γ(X, V) ↦
      r • I.sheaf.presheaf.map (homOfLE hVU).op
        (I.sectionMk a (I.mem_sections_of_ideal_eq_span hIa)) := by
  have hs (r : Γ(X, V)) : Scheme.Modules.Hom.app I.sheafι V
      (r • I.sheaf.presheaf.map (homOfLE hVU).op
        (I.sectionMk a (I.mem_sections_of_ideal_eq_span hIa))) =
      X.presheaf.map (homOfLE hVU).op a * r := by
    refine (Scheme.Modules.Hom.app_smul I.sheafι r _).trans ?_
    rw [sheafι_app_map, sheafι_app_sectionMk]
    -- The scalar action of `Γ(X, V)` on the sections of `𝒪_X` is multiplication.
    exact mul_comm r _
  refine ⟨fun r₁ r₂ h ↦ U.2.isSMulRegular_map hVU ha ?_, fun y ↦ ?_⟩
  · have h' := congrArg (Scheme.Modules.Hom.app I.sheafι V) h
    rw [hs, hs] at h'
    -- `h'` lives in the sections of `𝒪_X` as a module over itself, the goal in `Γ(X, V)`.
    exact h'
  · obtain ⟨t, ht⟩ := I.exists_mul_eq_of_ideal_eq_span ha hIa hVU (I.sheafι_app_mem V y)
    exact ⟨t, I.sheafι_app_injective V ((hs t).trans ht)⟩

/-- If the ideal sheaf `I` is generated on an affine open `U` by a nonzerodivisor `a`, then `a` is a
global basis of `I` over `U`: multiplication by `a` is an isomorphism `𝒪_U ≅ I|_U`. -/
def unitOverIsoOfIdealEqSpan {U : X.affineOpens} {a : Γ(X, U)}
    (ha : IsSMulRegular Γ(X, U) a) (hIa : I.ideal U = Ideal.span {a}) :
    SheafOfModules.unit (X.ringCatSheaf.over U.1) ≅ I.sheaf.over U.1 :=
  have : IsIso ((I.sheaf.over U.1).unitHomEquiv.symm ((I.sheaf.overSectionsEquiv U.1).symm
      (I.sectionMk a (I.mem_sections_of_ideal_eq_span hIa)))) :=
    TauCeti.SheafOfModules.isIso_unitHomEquiv_symm _ fun W ↦ by
      induction W using Opposite.rec with | op W => ?_
      -- Over `W ⟶ U`, the sections of `𝒪_X` and of `I` restricted to the slice are those over
      -- `W`, so the condition is `bijective_smul_map_sectionMk` over `W`.
      -- `rw` cannot match the evaluation lemma: the slice's coefficient sheaf
      -- `X.ringCatSheaf.over U` is elaborated through `TopCat.Sheaf`, so instances differ
      -- syntactically.
      erw [SheafOfModules.overSectionsEquiv_symm_apply_eval]
      exact I.bijective_smul_map_sectionMk ha hIa W.hom.le
  asIso ((I.sheaf.over U.1).unitHomEquiv.symm ((I.sheaf.overSectionsEquiv U.1).symm
    (I.sectionMk a (I.mem_sections_of_ideal_eq_span hIa))))

/-- Over an open `V ⊆ U`, the trivialization `unitOverIsoOfIdealEqSpan` is multiplication by the
local equation `a`: composed with the inclusion `I ⟶ 𝒪_X`, it sends a scalar `r` to `a|_V * r`. -/
@[simp]
lemma sheafι_app_unitOverIsoOfIdealEqSpan_hom {U : X.affineOpens} {a : Γ(X, U)}
    (ha : IsSMulRegular Γ(X, U) a) (hIa : I.ideal U = Ideal.span {a}) {V : X.Opens}
    (hVU : V ≤ U.1) (r : Γ(X, V)) :
    Scheme.Modules.Hom.app I.sheafι V
      ((I.unitOverIsoOfIdealEqSpan ha hIa).hom.val.app (op (Over.mk (homOfLE hVU))) r) =
      X.presheaf.map (homOfLE hVU).op a * r := by
  unfold unitOverIsoOfIdealEqSpan
  rw [asIso_hom]
  -- As in `unitOverIsoOfIdealEqSpan`, the slice's instances differ syntactically from `rw`'s.
  erw [TauCeti.SheafOfModules.unitHomEquiv_symm_val_app,
    SheafOfModules.overSectionsEquiv_symm_apply_eval]
  refine (Scheme.Modules.Hom.app_smul I.sheafι r _).trans ?_
  erw [sheafι_app_map, sheafι_app_sectionMk]
  exact mul_comm r _

/-- **The ideal sheaf of an effective Cartier divisor is invertible.** Near every point, the ideal
sheaf is generated on an affine open by a nonzerodivisor `a`, and multiplication by `a` trivializes
it there. -/
theorem IsEffectiveCartier.isInvertible_sheaf {I : X.IdealSheafData} (hI : I.IsEffectiveCartier) :
    TauCeti.AlgebraicGeometry.SheafOfModules.isInvertible X I.sheaf := by
  choose U hxU a ha hIa using (isEffectiveCartier_iff I).mp hI
  exact (TauCeti.AlgebraicGeometry.SheafOfModules.LocalTrivializations.ofForallMem X
    (fun x ↦ (U x).1) hxU fun x ↦ I.unitOverIsoOfIdealEqSpan (ha x) (hIa x)).isInvertible

/-- The ideal sheaf of an effective Cartier divisor, as an invertible sheaf. -/
def IsEffectiveCartier.toInvertibleSheaf {I : X.IdealSheafData} (hI : I.IsEffectiveCartier) :
    TauCeti.AlgebraicGeometry.InvertibleSheaf X :=
  ⟨I.sheaf, hI.isInvertible_sheaf⟩

/-- The underlying sheaf of `IsEffectiveCartier.toInvertibleSheaf` is the ideal sheaf. -/
@[simp]
lemma IsEffectiveCartier.toInvertibleSheaf_obj {I : X.IdealSheafData}
    (hI : I.IsEffectiveCartier) : hI.toInvertibleSheaf.obj = I.sheaf :=
  (rfl)

end Scheme.IdealSheafData

end

end AlgebraicGeometry
