/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.Invertible
public import TauCeti.AlgebraicGeometry.IdealSheaf.Affine
public import TauCeti.AlgebraicGeometry.IdealSheaf.Pullback
public import TauCeti.AlgebraicGeometry.LineBundle.Functoriality
public import TauCeti.AlgebraicGeometry.LineBundle.LocalBasis

import TauCeti.RingTheory.Ideal.Operations

/-!
# Pullback of the ideal sheaf of an effective Cartier divisor

Let `D` be an effective Cartier divisor on a scheme `Y`, with ideal sheaf `I`, and let
`g : X ⟶ Y` be a morphism such that the inverse image `g⁻¹ D`, with ideal sheaf `I.comap g`, is
again an effective Cartier divisor. This holds for flat `g`, and for the base change of a relative
effective Cartier divisor along any morphism of bases. Then the pullback `g^* I` of the line
bundle `I` is the ideal sheaf of `g⁻¹ D`: the comparison morphism `g^* I ⟶ I.comap g` is an
isomorphism (`Scheme.IdealSheafData.isIso_pullbackSheafHom`). Consequently, pulling back the
line-bundle class of `I` gives the line-bundle class of `I.comap g`
(`Scheme.IdealSheafData.IsEffectiveCartier.pullback_mk_toInvertibleSheaf`); dually, `𝒪(D)` pulls
back to `𝒪(g⁻¹ D)`.

Near a point of `X`, the ideal `I` is generated on an affine open `U` of `Y` by a nonzerodivisor
`a`, and `I.comap g` is then generated by `g^♯ a` on small affine opens `V`
(`Scheme.IdealSheafData.ideal_comap_of_le`). Since `I.comap g` is effective Cartier, `g^♯ a` is a
nonzerodivisor there, so it is a basis of `I.comap g` over `V`. The
comparison morphism sends the image of the section `a` of `I` in `g^* I` to `g^♯ a`, and a morphism
out of a line bundle sending a local section onto a local basis is an isomorphism
(`AlgebraicGeometry.Scheme.Modules.isIso_of_forall_exists_bijective_smul`).

## References

* The Stacks Project, *Divisors*, Section *Effective Cartier divisors* (Tag 01WQ): the pullback of
  an effective Cartier divisor, and its invertible ideal sheaf.
-/

public section

open CategoryTheory Opposite

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X Y : Scheme.{u}} (I : Y.IdealSheafData) (g : X ⟶ Y)

/-- **The ideal sheaf of an effective Cartier divisor commutes with pullback.** If `I` is an
effective Cartier divisor on `Y` whose inverse image along `g : X ⟶ Y` is again an effective
Cartier divisor, then `pullbackSheafHom : g^* I ⟶ I.comap g` is an isomorphism. -/
theorem isIso_pullbackSheafHom (hI : I.IsEffectiveCartier)
    (hI' : (I.comap g).IsEffectiveCartier) : IsIso (I.pullbackSheafHom g) := by
  have := hI.isInvertible_sheaf
  refine Scheme.Modules.isIso_of_forall_exists_bijective_smul _ fun x ↦ ?_
  obtain ⟨U, hxU, a, -, hIa⟩ := (isEffectiveCartier_iff I).mp hI (g x)
  obtain ⟨V₀, hxV₀, b, hb, hIb⟩ := (isEffectiveCartier_iff _).mp hI' x
  -- The `show` fixes the open set: `exists_subset_of_mem_open` takes it as an implicit set, so a
  -- bare `⟨hxV₀, hxU⟩` fails with "the expected type of this term could not be determined".
  obtain ⟨_, ⟨V, hV, rfl⟩, hxV, hVle⟩ := X.isBasis_affineOpens.exists_subset_of_mem_open
    (show x ∈ V₀.1 ⊓ g ⁻¹ᵁ U.1 from ⟨hxV₀, hxU⟩) (V₀.1 ⊓ g ⁻¹ᵁ U.1).isOpen
  replace hVle : V ≤ V₀.1 ⊓ g ⁻¹ᵁ U.1 := hVle
  have hVU : V ≤ g ⁻¹ᵁ U.1 := hVle.trans inf_le_right
  have hVV₀ : V ≤ V₀.1 := hVle.trans inf_le_left
  -- On `V`, the ideal of `I.comap g` is generated by `c = g^♯ a`, and also by `b|_V`.
  let c := g.appLE U.1 V hVU a
  have hIc : (I.comap g).ideal ⟨V, hV⟩ = Ideal.span {c} := by
    rw [ideal_comap_of_le I g U ⟨V, hV⟩ hVU, hIa, Ideal.map_span, Set.image_singleton]
  have hIb' : (I.comap g).ideal ⟨V, hV⟩ = Ideal.span {X.presheaf.map (homOfLE hVV₀).op b} := by
    rw [← (I.comap g).map_ideal (U := ⟨V, hV⟩) (V := V₀) hVV₀, hIb, Ideal.map_span,
      Set.image_singleton]
    rfl
  -- `c` generates the same ideal as the non-zero-divisor `b|_V`, so it is a non-zero-divisor.
  have hc : IsSMulRegular Γ(X, V) c := by
    have hb' := V₀.2.isSMulRegular_map hVV₀ hb
    rw [hIc] at hIb'
    exact IsSMulRegular.of_span_singleton_le hb' hIb'.ge
  refine ⟨V, hxV, ((Scheme.Modules.pullback g).obj I.sheaf).presheaf.map (homOfLE hVU).op
    (((Scheme.Modules.pullbackPushforwardAdjunction g).unit.app I.sheaf).app U.1
      (I.sectionMk a (I.mem_sections_of_ideal_eq_span hIa))), fun W i ↦ ?_⟩
  -- The chosen section of `g^* I` is sent to the section `c` of `I.comap g`.
  have hs : (I.pullbackSheafHom g).app V (((Scheme.Modules.pullback g).obj I.sheaf).presheaf.map
      (homOfLE hVU).op (((Scheme.Modules.pullbackPushforwardAdjunction g).unit.app I.sheaf).app
        U.1 (I.sectionMk a (I.mem_sections_of_ideal_eq_span hIa)))) =
      (I.comap g).sectionMk c ((I.comap g).mem_sections_of_ideal_eq_span (U := ⟨V, hV⟩) hIc) := by
    apply (I.comap g).sheafι_app_injective
    have hnat := (I.pullbackSheafHom g).mapPresheaf.naturality_apply (homOfLE hVU).op
      (((Scheme.Modules.pullbackPushforwardAdjunction g).unit.app I.sheaf).app
        U.1 (I.sectionMk a (I.mem_sections_of_ideal_eq_span hIa)))
    simp only [Scheme.Modules.mapPresheaf_app, unop_op] at hnat
    rw [hnat, sheafι_app_map, pullbackSheafHom_app_unit_app, sheafι_app_sectionMk,
      sheafι_app_sectionMk, sheafι_app_sectionMk]
    rfl
  rw [hs]
  exact (I.comap g).bijective_smul_map_sectionMk (U := ⟨V, hV⟩) hc hIc i.le

variable {I g} in
/-- **The class of the ideal sheaf of an effective Cartier divisor commutes with pullback.** If `I`
and its inverse image along `g` are effective Cartier divisors, then pulling back the line-bundle
class of `I` along `g` gives the line-bundle class of `I.comap g`. -/
theorem IsEffectiveCartier.pullback_mk_toInvertibleSheaf (hI : I.IsEffectiveCartier)
    (hI' : (I.comap g).IsEffectiveCartier) :
    TauCeti.AlgebraicGeometry.LineBundleClass.pullback g
        (TauCeti.AlgebraicGeometry.LineBundleClass.mk hI.toInvertibleSheaf) =
      TauCeti.AlgebraicGeometry.LineBundleClass.mk hI'.toInvertibleSheaf := by
  rw [TauCeti.AlgebraicGeometry.LineBundleClass.pullback_mk,
    TauCeti.AlgebraicGeometry.LineBundleClass.mk_eq_mk_iff,
    TauCeti.AlgebraicGeometry.InvertibleSheaf.pullback_obj_obj, toInvertibleSheaf_obj,
    toInvertibleSheaf_obj]
  have := isIso_pullbackSheafHom I g hI hI'
  exact ⟨asIso (I.pullbackSheafHom g)⟩

end AlgebraicGeometry.Scheme.IdealSheafData
