/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.Invertible
public import TauCeti.AlgebraicGeometry.LineBundle.Class
public import TauCeti.AlgebraicGeometry.Modules.TensorProduct

/-!
# Ideal sheaves of sums of effective Cartier divisors

The sum of two effective Cartier divisors `D` and `E` on a scheme `X` is cut out by the product
`I_D * I_E` of their ideal sheaves. Multiplication of local functions sends sections of `I` and
`J` to sections of `I * J`, and when `J` is the ideal sheaf of an effective Cartier divisor this
gives an isomorphism `I ⊗ J ≅ I * J` of `𝒪_X`-modules, for an arbitrary ideal sheaf `I`. Over an
affine open on which `J` is generated by a nonzerodivisor `b`, every section of `I ⊗ J` is a
pure tensor `s ⊗ b`, which multiplication sends to `s * b`; this is injective because `b` is a
nonzerodivisor, and surjective because `(I * J)(V) = I(V) * (b)`.

No integrality or noetherian hypothesis is placed on `X`, so this applies to the relative
effective Cartier divisors on the base changes `X_T = T ×_S X` for every scheme `T`. In the Picard
group it says that the class of `𝒪_X(-D) = I_D` is additive in `D`; since `𝒪_X(D)` is the dual
of `I_D`, inverting gives `[𝒪_X(D + E)] = [𝒪_X(D)] * [𝒪_X(E)]`, which is what makes the Abel map
`D ↦ 𝒪_X(D)` on effective Cartier divisors additive.

## Main declarations

* `Scheme.IdealSheafData.mul_mem_sections_mul`: products of sections of `I` and `J` are sections
  of `I * J`, and `Scheme.IdealSheafData.sectionsMul` is the resulting multiplication map
  `Γ(I, U) × Γ(J, U) → Γ(I * J, U)`;
* `Scheme.IdealSheafData.tensorProductSheafIso`: `I ⊗ J ≅ I * J` when `J` is effective Cartier,
  with `Scheme.IdealSheafData.tensorProductSheafIso_hom_tmul` computing it on pure tensors;
* `TauCeti.AlgebraicGeometry.LineBundleClass.mk_toInvertibleSheaf_mul`: the line-bundle class of
  the ideal sheaf of `D + E` is the product of the classes of the ideal sheaves of `D` and `E`.

## References

* The Stacks Project, *Divisors*, Section *Effective Cartier divisors* (Tag 01WQ): the sum
  `D + E` is cut out by `I_D I_E`, and `𝒪_X(D + E) ≅ 𝒪_X(D) ⊗ 𝒪_X(E)`.
* The construction of the multiplication map follows the Cartier divisor version
  `Scheme.CartierDivisor.tensorProductSheafIso` in
  `TauCeti/AlgebraicGeometry/CartierDivisor/TensorProduct.lean`.
-/

public section

open CategoryTheory Opposite TensorProduct TopologicalSpace

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

noncomputable section

variable {X : Scheme.{u}}

/-- Products of sections of two ideal sheaves are sections of their product. -/
theorem mul_mem_sections_mul {I J : X.IdealSheafData} {U : X.Opens} {s t : Γ(X, U)}
    (hs : s ∈ I.sections U) (ht : t ∈ J.sections U) : s * t ∈ (I * J).sections U := by
  refine (I * J).mem_sections_of_forall_exists fun x hx ↦ ?_
  obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWU⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open hx U.isOpen
  refine ⟨W, homOfLE hWU, hxW, ?_⟩
  have hsW := I.map_mem_sections (homOfLE hWU) hs
  have htW := J.map_mem_sections (homOfLE hWU) ht
  rw [I.sections_eq_ideal ⟨W, hW⟩] at hsW
  rw [J.sections_eq_ideal ⟨W, hW⟩] at htW
  rw [map_mul, (I * J).sections_eq_ideal ⟨W, hW⟩, ideal_mul]
  exact Ideal.mul_mem_mul hsW htW

variable (I J : X.IdealSheafData) (U : X.Opens)

/-- Multiplication of local functions, as a map from sections of `I` and `J` to sections of
`I * J`. -/
def sectionsMul (s : Γ(I.sheaf, U)) (t : Γ(J.sheaf, U)) : Γ((I * J).sheaf, U) :=
  (I * J).sectionMk _ (mul_mem_sections_mul (I.sheafι_app_mem U s) (J.sheafι_app_mem U t))

/-- On sections built from local functions `a` and `b`, `sectionsMul` is the product `a * b`. -/
@[simp]
lemma sectionsMul_sectionMk {a b : Γ(X, U)} (ha : a ∈ I.sections U) (hb : b ∈ J.sections U) :
    sectionsMul I J U (I.sectionMk a ha) (J.sectionMk b hb) =
      (I * J).sectionMk (a * b) (mul_mem_sections_mul ha hb) :=
  (I * J).sheafι_app_injective U <| by
    simp only [sectionsMul, sheafι_app_sectionMk]
    -- The two products agree up to the identification of the sections of `𝒪_X` over `U`, as a
    -- module over itself, with the ring `Γ(X, U)`.
    rfl

variable {I J U}

/-- `sectionsMul` is additive in its first argument. -/
@[simp]
lemma sectionsMul_add_left (s s' : Γ(I.sheaf, U)) (t : Γ(J.sheaf, U)) :
    sectionsMul I J U (s + s') t = sectionsMul I J U s t + sectionsMul I J U s' t :=
  (I * J).sheafι_app_injective U <| by
    simp only [sectionsMul, map_add, sheafι_app_sectionMk]
    exact add_mul (R := Γ(X, U)) _ _ _

/-- `sectionsMul` is additive in its second argument. -/
@[simp]
lemma sectionsMul_add_right (s : Γ(I.sheaf, U)) (t t' : Γ(J.sheaf, U)) :
    sectionsMul I J U s (t + t') = sectionsMul I J U s t + sectionsMul I J U s t' :=
  (I * J).sheafι_app_injective U <| by
    simp only [sectionsMul, map_add, sheafι_app_sectionMk]
    exact mul_add (R := Γ(X, U)) _ _ _

/-- `sectionsMul` is `Γ(X, U)`-linear in its first argument. -/
@[simp]
lemma sectionsMul_smul_left (r : Γ(X, U)) (s : Γ(I.sheaf, U)) (t : Γ(J.sheaf, U)) :
    sectionsMul I J U (r • s) t = r • sectionsMul I J U s t :=
  (I * J).sheafι_app_injective U <| by
    refine Eq.trans ?_ (Scheme.Modules.Hom.app_smul (I * J).sheafι r _).symm
    simp only [sectionsMul, sheafι_app_sectionMk]
    refine (congrArg (fun x : Γ(X, U) ↦ x * _)
      (Scheme.Modules.Hom.app_smul I.sheafι r s)).trans ?_
    exact mul_assoc (G := Γ(X, U)) _ _ _

/-- `sectionsMul` is `Γ(X, U)`-linear in its second argument. -/
@[simp]
lemma sectionsMul_smul_right (r : Γ(X, U)) (s : Γ(I.sheaf, U)) (t : Γ(J.sheaf, U)) :
    sectionsMul I J U s (r • t) = r • sectionsMul I J U s t :=
  (I * J).sheafι_app_injective U <| by
    refine Eq.trans ?_ (Scheme.Modules.Hom.app_smul (I * J).sheafι r _).symm
    simp only [sectionsMul, sheafι_app_sectionMk]
    refine (congrArg (fun x : Γ(X, U) ↦ _ * x)
      (Scheme.Modules.Hom.app_smul J.sheafι r t)).trans ?_
    exact mul_left_comm (G := Γ(X, U)) _ _ _

/-- Restriction commutes with multiplication of sections. -/
@[simp]
lemma sectionsMul_map {V : X.Opens} (i : V ⟶ U) (s : Γ(I.sheaf, U)) (t : Γ(J.sheaf, U)) :
    sectionsMul I J V (I.sheaf.presheaf.map i.op s) (J.sheaf.presheaf.map i.op t) =
      (I * J).sheaf.presheaf.map i.op (sectionsMul I J U s t) :=
  (I * J).sheafι_app_injective V <| by
    simp only [sectionsMul, sheafι_app_sectionMk, sheafι_app_map]
    exact (map_mul (X.presheaf.map i.op).hom _ _).symm

variable (I J U)

/-- Multiplication, as a linear map on the tensor product of the sections. -/
private def sectionsMulLift :
    TensorProduct Γ(X, U) Γ(I.sheaf, U) Γ(J.sheaf, U) →ₗ[Γ(X, U)] Γ((I * J).sheaf, U) :=
  TensorProduct.lift <| LinearMap.mk₂ Γ(X, U) (sectionsMul I J U)
    sectionsMul_add_left sectionsMul_smul_left sectionsMul_add_right sectionsMul_smul_right

private lemma sectionsMulLift_tmul (s : Γ(I.sheaf, U)) (t : Γ(J.sheaf, U)) :
    sectionsMulLift I J U (s ⊗ₜ t) = sectionsMul I J U s t :=
  (rfl)

/-- The multiplication morphism of presheaves of modules `I ⊗ J ⟶ I * J`. -/
private def tensorPresheafHom :
    PresheafOfModulesOfCommRing.Monoidal.tensorObj (R := X.sheaf.obj) I.sheaf.val
      J.sheaf.val ⟶ (I * J).sheaf.val where
  app U := ModuleCat.MonoidalCategory.tensorLift (fun s t ↦ sectionsMul I J U.unop s t)
    sectionsMul_add_left sectionsMul_smul_left sectionsMul_add_right sectionsMul_smul_right
  naturality f := ModuleCat.MonoidalCategory.tensor_ext fun s t ↦ sectionsMul_map f.unop s t

section LocalEquation

variable {I J} {V : X.affineOpens} {b : Γ(X, V)} (hJb : J.ideal V = Ideal.span {b})

include hJb

/-- Where `J` is generated by `b`, every section of `I ⊗ J` is a pure tensor `s ⊗ b`. -/
private lemma exists_tmul_eq (w : TensorProduct Γ(X, V) Γ(I.sheaf, V.1) Γ(J.sheaf, V.1)) :
    ∃ s : Γ(I.sheaf, V.1), s ⊗ₜ J.sectionMk b (J.mem_sections_of_ideal_eq_span hJb) = w := by
  induction w using TensorProduct.inductionOn with
  | tmul s t =>
    have ht : Scheme.Modules.Hom.app J.sheafι V.1 t ∈ Ideal.span {b} := by
      rw [← hJb, ← J.sections_eq_ideal V]
      exact J.sheafι_app_mem V.1 t
    obtain ⟨r, hr⟩ : ∃ r : Γ(X, V), r * b = _ := Ideal.mem_span_singleton'.mp ht
    refine ⟨r • s, ?_⟩
    rw [TensorProduct.smul_tmul]
    congr 1
    -- The scalar action of `Γ(X, V)` on the sections of `𝒪_X` is multiplication.
    exact J.sheafι_app_injective V.1 ((Scheme.Modules.Hom.app_smul J.sheafι r _).trans
      ((congrArg (fun x : Γ(X, V) ↦ r * x) (J.sheafι_app_sectionMk b _)).trans hr))
  | add w w' hw hw' =>
    obtain ⟨s, rfl⟩ := hw
    obtain ⟨s', rfl⟩ := hw'
    exact ⟨s + s', TensorProduct.add_tmul _ _ _⟩

/-- Where `J` is generated by `b`, every section of `I * J` is a product with `b`. -/
private lemma exists_sectionsMul_eq (z : Γ((I * J).sheaf, V.1)) :
    ∃ s : Γ(I.sheaf, V.1),
      sectionsMul I J V.1 s (J.sectionMk b (J.mem_sections_of_ideal_eq_span hJb)) = z := by
  have hz : Scheme.Modules.Hom.app (I * J).sheafι V.1 z ∈ I.ideal V * Ideal.span {b} := by
    rw [← hJb, ← Pi.mul_apply, ← ideal_mul, ← sections_eq_ideal]
    exact (I * J).sheafι_app_mem V.1 z
  obtain ⟨s, hs, hsz⟩ : ∃ s ∈ I.ideal V, s * b = _ := Ideal.mem_mul_span_singleton.mp hz
  rw [← I.sections_eq_ideal V] at hs
  refine ⟨I.sectionMk s hs, ?_⟩
  rw [sectionsMul_sectionMk]
  exact (I * J).sheafι_app_injective V.1 ((sheafι_app_sectionMk _ _ _).trans hsz)

/-- Where `J` is generated by a nonzerodivisor, multiplication `I ⊗ J ⟶ I * J` is injective on
sections. -/
private lemma sectionsMulLift_injective (hb : IsSMulRegular Γ(X, V) b) :
    Function.Injective (sectionsMulLift I J V.1) := by
  refine (injective_iff_map_eq_zero _).mpr fun w hw ↦ ?_
  obtain ⟨s, rfl⟩ := exists_tmul_eq hJb w
  rw [sectionsMulLift_tmul] at hw
  have hs : Scheme.Modules.Hom.app I.sheafι V.1 s = 0 := by
    refine hb ?_
    have := congrArg (Scheme.Modules.Hom.app (I * J).sheafι V.1) hw
    simp only [sectionsMul, sheafι_app_sectionMk, map_zero] at this
    -- `b • x` is the product `b * x` in `Γ(X, V)`.
    exact (mul_comm (G := Γ(X, V)) _ _).trans (this.trans (mul_zero (M₀ := Γ(X, V)) b).symm)
  rw [I.sheafι_app_injective V.1 (hs.trans (map_zero _).symm), TensorProduct.zero_tmul]

end LocalEquation

variable {J} (hJ : J.IsEffectiveCartier)

include hJ

/-- Multiplication `I ⊗ J ⟶ I * J` is locally surjective. -/
private lemma isLocallySurjective_tensorPresheafHom :
    Presheaf.IsLocallySurjective (Opens.grothendieckTopology X)
      ((PresheafOfModules.toPresheaf X.ringCatSheaf.obj).map (tensorPresheafHom I J)) where
  imageSieve_mem {U} z x hx := by
    obtain ⟨V, hVU, hxV, b, -, hJb⟩ := hJ.exists_eq_span_singleton_le U hx
    obtain ⟨s, hs⟩ := exists_sectionsMul_eq hJb ((I * J).sheaf.presheaf.map (homOfLE hVU).op z)
    exact ⟨V.1, homOfLE hVU, ⟨s ⊗ₜ J.sectionMk b (J.mem_sections_of_ideal_eq_span hJb), hs⟩, hxV⟩

/-- Multiplication `I ⊗ J ⟶ I * J` is locally injective. -/
private lemma isLocallyInjective_tensorPresheafHom :
    Presheaf.IsLocallyInjective (Opens.grothendieckTopology X)
      ((PresheafOfModules.toPresheaf X.ringCatSheaf.obj).map (tensorPresheafHom I J)) where
  equalizerSieve_mem {U} z z' h x hx := by
    obtain ⟨V, hVU, hxV, b, hb, hJb⟩ := hJ.exists_eq_span_singleton_le U.unop hx
    refine ⟨V.1, homOfLE hVU, sectionsMulLift_injective hJb hb ?_, hxV⟩
    exact (PresheafOfModules.naturality_apply (tensorPresheafHom I J) (homOfLE hVU).op z).trans
      ((congrArg ((I * J).sheaf.val.map (homOfLE hVU).op) h).trans
        (PresheafOfModules.naturality_apply (tensorPresheafHom I J) (homOfLE hVU).op z').symm)

/-- Sheafified multiplication `I ⊗ J ⟶ I * J` is an isomorphism, being locally bijective. -/
private lemma isIso_sheafification_map_tensorPresheafHom :
    IsIso ((PresheafOfModules.sheafification (R := X.ringCatSheaf)
      (𝟙 X.ringCatSheaf.obj)).map (tensorPresheafHom I J)) := by
  have := isLocallySurjective_tensorPresheafHom I hJ
  have := isLocallyInjective_tensorPresheafHom I hJ
  -- Mathlib identifies local bijectivity with the inverse image of isomorphisms under
  -- sheafification; the two sides have different categorical wrappers.
  change ((MorphismProperty.isomorphisms _).inverseImage
    (PresheafOfModules.sheafification (R := X.ringCatSheaf) (𝟙 X.ringCatSheaf.obj)))
      (tensorPresheafHom I J)
  rw [← PresheafOfModules.inverseImage_W_toPresheaf_eq_inverseImage_isomorphisms]
  exact (Opens.grothendieckTopology X).W_of_isLocallyBijective _

/-- **The ideal sheaf of a sum of divisors.** If `J` is the ideal sheaf of an effective Cartier
divisor, multiplication of local functions is an isomorphism `I ⊗ J ≅ I * J` for every ideal
sheaf `I`. -/
def tensorProductSheafIso :
    TauCeti.SheafOfModules.tensorProduct X.sheaf I.sheaf J.sheaf ≅ (I * J).sheaf :=
  TauCeti.SheafOfModules.tensorProductIso X.sheaf I.sheaf J.sheaf ≪≫
    @asIso _ _ _ _ _ (isIso_sheafification_map_tensorPresheafHom I hJ) ≪≫
    TauCeti.SheafOfModules.sheafificationIso X.ringCatSheaf (I * J).sheaf

/-- On a pure tensor of local sections, the isomorphism `I ⊗ J ≅ I * J` multiplies the two
functions. The sheafification unit sends the sectionwise pure tensor into the tensor product
sheaf. -/
@[simp]
theorem tensorProductSheafIso_hom_tmul (U : X.Opens) (s : Γ(I.sheaf, U)) (t : Γ(J.sheaf, U)) :
    Scheme.Modules.Hom.app
      ((TauCeti.SheafOfModules.tensorProductIso X.sheaf I.sheaf J.sheaf).inv ≫
        (tensorProductSheafIso I hJ).hom) U
      (((PresheafOfModules.sheafificationAdjunction (𝟙 X.ringCatSheaf.obj)).unit.app
        (PresheafOfModulesOfCommRing.Monoidal.tensorObj (R := X.sheaf.obj)
          I.sheaf.val J.sheaf.val)).app (op U) (s ⊗ₜ t)) =
      sectionsMul I J U s t := by
  let P := PresheafOfModulesOfCommRing.Monoidal.tensorObj (R := X.sheaf.obj)
    I.sheaf.val J.sheaf.val
  let F := PresheafOfModules.sheafification (R := X.ringCatSheaf) (𝟙 X.ringCatSheaf.obj)
  let adj := PresheafOfModules.sheafificationAdjunction (𝟙 X.ringCatSheaf.obj)
  -- The isomorphism is the sheafification of `tensorPresheafHom`, which the unit factors.
  have h₁ : adj.unit.app P ≫
      (SheafOfModules.forget X.ringCatSheaf ⋙
        PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).map
        (F.map (tensorPresheafHom I J) ≫
          (TauCeti.SheafOfModules.sheafificationIso X.ringCatSheaf (I * J).sheaf).hom) =
      tensorPresheafHom I J :=
    (adj.unit_comp_map_eq_iff _ _).2 (congrArg (fun g ↦ F.map (tensorPresheafHom I J) ≫ g)
      (TauCeti.SheafOfModules.sheafificationIso_hom X.ringCatSheaf (I * J).sheaf))
  have hmap : (TauCeti.SheafOfModules.tensorProductIso X.sheaf I.sheaf J.sheaf).inv ≫
      (tensorProductSheafIso I hJ).hom = F.map (tensorPresheafHom I J) ≫
        (TauCeti.SheafOfModules.sheafificationIso X.ringCatSheaf (I * J).sheaf).hom :=
    Iso.inv_hom_id_assoc _ _
  have h : adj.unit.app P ≫
      (SheafOfModules.forget X.ringCatSheaf ⋙
        PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).map
        ((TauCeti.SheafOfModules.tensorProductIso X.sheaf I.sheaf J.sheaf).inv ≫
          (tensorProductSheafIso I hJ).hom) = tensorPresheafHom I J :=
    (congrArg (fun g ↦ adj.unit.app P ≫ (SheafOfModules.forget X.ringCatSheaf ⋙
      PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).map g) hmap).trans h₁
  -- Evaluate both sides at `U` on the pure tensor `s ⊗ t`; the forgetful functor and the
  -- sheafification unit unfold to `Hom.app` on the sectionwise pure tensor.
  exact congrArg (fun f ↦ f.app (op U) (s ⊗ₜ t)) h

end

end AlgebraicGeometry.Scheme.IdealSheafData

namespace TauCeti.AlgebraicGeometry.LineBundleClass

open _root_.AlgebraicGeometry _root_.AlgebraicGeometry.Scheme.IdealSheafData

variable {X : Scheme.{u}} {I J : X.IdealSheafData}

/-- The line-bundle class of the ideal sheaf of a sum `D + E` of effective Cartier divisors is the
product of the classes of the ideal sheaves of `D` and `E`. -/
theorem mk_toInvertibleSheaf_mul (hI : I.IsEffectiveCartier) (hJ : J.IsEffectiveCartier) :
    mk (TauCeti.isEffectiveCartier_mul hI hJ).toInvertibleSheaf =
      mk hI.toInvertibleSheaf * mk hJ.toInvertibleSheaf := by
  rw [← mk_tensorProduct, mk_eq_mk_iff]
  refine ⟨?_⟩
  simp only [IsEffectiveCartier.toInvertibleSheaf_obj, InvertibleSheaf.tensorProduct_obj]
  exact (tensorProductSheafIso I hJ).symm

end TauCeti.AlgebraicGeometry.LineBundleClass
