/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Category.FGModuleCat.Cyclic
public import TauCeti.Algebra.Category.FGModuleCat.Stable.Basic
public import TauCeti.CategoryTheory.Exact.Stable.Loop
public import TauCeti.RingTheory.AdjoinRoot.Basic
public import TauCeti.RingTheory.Noetherian.MulOpposite

/-!
# Syzygies of cyclic modules in the stable module category

Let `A` be a ring and let `a, b : A` be such that the right annihilator of `a` is `bA`, that is,
`a * c = 0` exactly when `b ∣ c`. Then left multiplication by `a` and the quotient map form a
short exact sequence of right `A`-modules

`0 ⟶ A ⧸ bA ⟶ A ⟶ A ⧸ aA ⟶ 0`,

whose middle term is free. It is therefore a projective presentation of `A ⧸ aA`, and the
syzygy (loop) functor `Ω` of the stable module category sends `A ⧸ aA` to `A ⧸ bA`. If moreover
the right annihilator of `b` is `aA`, then `Ω² (A ⧸ aA) ≅ A ⧸ aA`: the module is periodic of
period at most two in the stable module category.

The basic example is the truncated polynomial ring `A = R[X]/(X ^ n)` over a commutative
Noetherian ring `R`, with `x` the class of `X`. For `i ≤ n` the annihilator of `x ^ i` is
generated by `x ^ (n - i)` (`AdjoinRoot.root_X_pow_pow_mul_eq_zero_iff`), so the modules
`M_i = A ⧸ (x ^ i)` satisfy `Ω M_i ≅ M_(n - i)` and `Ω² M_i ≅ M_i` in `stmod-A`. The module
`M_n = A` is projective and hence zero there. Over a field `k`, the algebra `k[X]/(X ^ n)` is a
symmetric Frobenius algebra (`AdjoinRoot.isSymmetricFrobeniusFunctional_lastCoeff_X_pow`), hence
self-injective, so its finite-dimensional modules form a Frobenius exact category
(`FGModuleCat.abelian_isFrobenius`) on whose stable category `Ω` is quasi-inverse to the
suspension (`TauCeti.ExactStructure.IsFrobenius.stableSuspensionEquivalence`).

Right `A`-modules are left `Aᵐᵒᵖ`-modules. The cyclic right module `A ⧸ aA` is represented as the
quotient of the regular module `Aᵐᵒᵖ` by the left ideal generated by `op a`, which is `op (aA)`
(`TauCeti.FGModuleCat.cyclicModule`).

## Main definitions

* `TauCeti.FGModuleCat.cyclicMulLeft`: left multiplication by `a`, as a map `A ⧸ bA ⟶ A`.
* `TauCeti.FGModuleCat.cyclicShortComplex`: the short complex `A ⧸ bA ⟶ A ⟶ A ⧸ aA`.
* `TauCeti.FGModuleCat.cyclicPresentation`: the resulting projective presentation of `A ⧸ aA`.
* `TauCeti.FGModuleCat.stableModuleLoop`: the loop functor `Ω` of the stable module category.
* `TauCeti.FGModuleCat.stableModuleLoopCyclicModuleIso`: `Ω (A ⧸ aA) ≅ A ⧸ bA`.
* `TauCeti.FGModuleCat.stableModuleLoopLoopCyclicModuleIso`: `Ω² (A ⧸ aA) ≅ A ⧸ aA`.
* `TauCeti.FGModuleCat.stableModuleLoopCyclicModuleRootPowIso`,
  `TauCeti.FGModuleCat.stableModuleLoopLoopCyclicModuleRootPowIso`: over `R[X]/(X ^ n)`,
  `Ω M_i ≅ M_(n - i)` and `Ω² M_i ≅ M_i`.

## Main results

* `TauCeti.FGModuleCat.cyclicShortComplex_shortExact`: the short complex is short exact.
* `TauCeti.FGModuleCat.isZero_stableModuleFunctor_obj_cyclicModule_zero`: the module `A ⧸ 0A`,
  the free module of rank one, is zero in the stable module category.
* `TauCeti.FGModuleCat.isZero_stableModuleFunctor_obj_cyclicModule_root_pow_self`: the module
  `M_n = R[X]/(X ^ n)` is zero in the stable module category.

## References

* David Eisenbud, *Homological algebra on a complete intersection, with an application to group
  representations*, Trans. Amer. Math. Soc. **260** (1980), 35–64, Section 5: the periodic
  resolution `⋯ ⟶ A --x^(n-i)--> A --x^i--> A ⟶ A/(x^i) ⟶ 0`.
* Dieter Happel, *Triangulated Categories in the Representation Theory of Finite Dimensional
  Algebras*, Chapter I, Section 2: the loop functor of a stable category.
-/

public section

namespace TauCeti

open CategoryTheory CategoryTheory.Limits MulOpposite

universe u

namespace FGModuleCat

variable {A : Type u} [Ring A]

/-- For `a * b = 0`, left multiplication by `a`, as a map of right `A`-modules
`A ⧸ bA ⟶ A`. On `Aᵐᵒᵖ` it is right multiplication by `op a`, which kills `op b`. -/
noncomputable def cyclicMulLeft (a b : A) (hab : a * b = 0) :
    (Aᵐᵒᵖ ⧸ Ideal.span {op b}) →ₗ[Aᵐᵒᵖ] Aᵐᵒᵖ :=
  (Ideal.span {op b}).liftQ (LinearMap.toSpanSingleton Aᵐᵒᵖ Aᵐᵒᵖ (op a)) <| by
    rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, LinearMap.mem_ker,
      LinearMap.toSpanSingleton_apply, smul_eq_mul, ← op_mul, hab, MulOpposite.op_zero]

/-- Left multiplication by `a` sends the class of `c` to `c * op a = op (a * unop c)`. -/
@[simp]
theorem cyclicMulLeft_mk (a b : A) (hab : a * b = 0) (c : Aᵐᵒᵖ) :
    cyclicMulLeft a b hab (Submodule.Quotient.mk c) = c * op a := by
  rw [cyclicMulLeft, Submodule.liftQ_apply, LinearMap.toSpanSingleton_apply, smul_eq_mul]

/-- The image of left multiplication by `a` is `aA`, the kernel of the quotient map onto
`A ⧸ aA`. -/
theorem exact_cyclicMulLeft_mkQ (a b : A) (hab : a * b = 0) :
    Function.Exact (cyclicMulLeft a b hab) (Ideal.span {op a}).mkQ := by
  rw [LinearMap.exact_iff, Submodule.ker_mkQ, cyclicMulLeft, Submodule.range_liftQ,
    ← LinearMap.span_singleton_eq_range]

/-- If the right annihilator of `a` is `bA`, then left multiplication by `a` is injective on
`A ⧸ bA`. -/
theorem cyclicMulLeft_injective {a b : A} (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    Function.Injective (cyclicMulLeft a b ((hab b).2 dvd_rfl)) := by
  rw [← LinearMap.ker_eq_bot, cyclicMulLeft]
  refine Submodule.ker_liftQ_eq_bot _ _ _ fun c hc ↦ ?_
  rw [LinearMap.mem_ker, LinearMap.toSpanSingleton_apply, smul_eq_mul, ← op_unop c, ← op_mul,
    op_eq_zero_iff, hab] at hc
  obtain ⟨d, hd⟩ := hc
  exact Ideal.mem_span_singleton'.2 ⟨op d, by rw [← op_mul, ← hd, op_unop]⟩

/-- For `a * b = 0`, the short complex of right `A`-modules `A ⧸ bA ⟶ A ⟶ A ⧸ aA`, whose maps
are left multiplication by `a` and the quotient map. -/
@[expose, simps X₁ X₂ X₃ f g]
noncomputable def cyclicShortComplex (a b : A) (hab : a * b = 0) :
    ShortComplex (FGModuleCat.{u} Aᵐᵒᵖ) where
  X₁ := cyclicModule b
  X₂ := FGModuleCat.of Aᵐᵒᵖ Aᵐᵒᵖ
  X₃ := cyclicModule a
  f := FGModuleCat.ofHom (cyclicMulLeft a b hab)
  g := FGModuleCat.ofHom (Ideal.span {op a}).mkQ
  zero := FGModuleCat.hom_ext (exact_cyclicMulLeft_mkQ a b hab).linearMap_comp_eq_zero

variable [IsNoetherianRing Aᵐᵒᵖ]

/-- If the right annihilator of `a` is `bA`, then `0 ⟶ A ⧸ bA ⟶ A ⟶ A ⧸ aA ⟶ 0` is short exact. -/
theorem cyclicShortComplex_shortExact {a b : A} (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    (cyclicShortComplex a b ((hab b).2 dvd_rfl)).ShortExact := by
  refine ShortComplex.ShortExact.mk' ?_
    (ConcreteCategory.mono_of_injective _ (cyclicMulLeft_injective hab))
    (ConcreteCategory.epi_of_surjective _ (Submodule.mkQ_surjective _))
  rw [← ShortComplex.exact_map_iff_of_faithful _
      (forget₂ (FGModuleCat.{u} Aᵐᵒᵖ) (ModuleCat.{u} Aᵐᵒᵖ)),
    ShortComplex.ShortExact.moduleCat_exact_iff_function_exact]
  exact exact_cyclicMulLeft_mkQ a b ((hab b).2 dvd_rfl)

/-- If the right annihilator of `a` is `bA`, then `A ⧸ bA ⟶ A ⟶ A ⧸ aA` is a projective
presentation of `A ⧸ aA`: its middle term is the free module of rank one. -/
@[expose]
noncomputable def cyclicPresentation {a b : A} (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    (ExactStructure.abelian (FGModuleCat.{u} Aᵐᵒᵖ)).ProjectivePresentation (cyclicModule a) where
  K := cyclicModule b
  P := FGModuleCat.of Aᵐᵒᵖ Aᵐᵒᵖ
  i := FGModuleCat.ofHom (cyclicMulLeft a b ((hab b).2 dvd_rfl))
  p := FGModuleCat.ofHom (Ideal.span {op a}).mkQ
  zero := (cyclicShortComplex a b ((hab b).2 dvd_rfl)).zero
  conflation := (ExactStructure.abelian_conflation _).2 (cyclicShortComplex_shortExact hab)
  isProjective := (ExactStructure.abelian_isProjective_iff _).2
    (_root_.FGModuleCat.projective_of_free Aᵐᵒᵖ _)

/-- The kernel term of `cyclicPresentation` is `A ⧸ bA`. -/
@[simp]
theorem cyclicPresentation_K {a b : A} (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    (cyclicPresentation hab).K = cyclicModule b :=
  (rfl)

/-- The middle term of `cyclicPresentation` is the regular module. -/
@[simp]
theorem cyclicPresentation_P {a b : A} (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    (cyclicPresentation hab).P = FGModuleCat.of Aᵐᵒᵖ Aᵐᵒᵖ :=
  (rfl)

/-- The inflation of `cyclicPresentation` is left multiplication by `a`. -/
@[simp]
theorem cyclicPresentation_i {a b : A} (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    (cyclicPresentation hab).i = FGModuleCat.ofHom (cyclicMulLeft a b ((hab b).2 dvd_rfl)) :=
  (rfl)

/-- The deflation of `cyclicPresentation` is the quotient map. -/
@[simp]
theorem cyclicPresentation_p {a b : A} (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    (cyclicPresentation hab).p = FGModuleCat.ofHom (Ideal.span {op a}).mkQ :=
  (rfl)

variable (A) in
/-- The loop (syzygy) functor `Ω` of the stable module category of finitely generated right
`A`-modules: it sends a module to the kernel of a chosen epimorphism onto it from a projective
module. -/
noncomputable abbrev stableModuleLoop : stableModuleCategory A ⥤ stableModuleCategory A :=
  (ExactStructure.abelian_enoughProjectives (A := FGModuleCat.{u} Aᵐᵒᵖ)).stableLoop

/-- If the right annihilator of `a` is `bA`, then `Ω (A ⧸ aA) ≅ A ⧸ bA` in the stable module
category. -/
noncomputable def stableModuleLoopCyclicModuleIso {a b : A}
    (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) :
    (stableModuleLoop A).obj ((stableModuleFunctor A).obj (cyclicModule a)) ≅
      (stableModuleFunctor A).obj (cyclicModule b) :=
  ExactStructure.EnoughProjectives.stableLoopObjIso _ (cyclicPresentation hab)

/-- If the right annihilators of `a` and of `b` are `bA` and `aA`, then `Ω² (A ⧸ aA) ≅ A ⧸ aA`
in the stable module category. -/
noncomputable def stableModuleLoopLoopCyclicModuleIso {a b : A}
    (hab : ∀ c : A, a * c = 0 ↔ b ∣ c) (hba : ∀ c : A, b * c = 0 ↔ a ∣ c) :
    (stableModuleLoop A).obj
        ((stableModuleLoop A).obj ((stableModuleFunctor A).obj (cyclicModule a))) ≅
      (stableModuleFunctor A).obj (cyclicModule a) :=
  (stableModuleLoop A).mapIso (stableModuleLoopCyclicModuleIso hab) ≪≫
    stableModuleLoopCyclicModuleIso hba

/-- The module `A ⧸ 0A`, which is the free module of rank one, is zero in the stable module
category. -/
theorem isZero_stableModuleFunctor_obj_cyclicModule_zero :
    IsZero ((stableModuleFunctor A).obj (cyclicModule (0 : A))) := by
  have h : Ideal.span {op (0 : A)} = ⊥ := by
    rw [MulOpposite.op_zero, Ideal.span_singleton_eq_bot]
  have : Module.Projective Aᵐᵒᵖ (Aᵐᵒᵖ ⧸ Ideal.span {op (0 : A)}) :=
    Module.Projective.of_equiv (Submodule.quotEquivOfEqBot _ h).symm
  exact (_root_.FGModuleCat.isZero_stableModuleFunctor_obj_iff _).2
    (_root_.FGModuleCat.projective_of_moduleProjective _ _)

/-! ### The truncated polynomial ring `R[X]/(X ^ n)` -/

section TruncatedPolynomial

open Polynomial

variable (R : Type u) [CommRing R] [IsNoetherianRing R] {n i : ℕ}

/-- Over `R[X]/(X ^ n)`, with `x` the class of `X` and `M_i = A ⧸ (x ^ i)`, the stable syzygy
`Ω M_i` is `M_(n - i)` for `i ≤ n`. -/
noncomputable def stableModuleLoopCyclicModuleRootPowIso (hi : i ≤ n) :
    (stableModuleLoop (AdjoinRoot (X ^ n : R[X]))).obj
        ((stableModuleFunctor _).obj (cyclicModule (AdjoinRoot.root (X ^ n : R[X]) ^ i))) ≅
      (stableModuleFunctor _).obj (cyclicModule (AdjoinRoot.root (X ^ n : R[X]) ^ (n - i))) :=
  stableModuleLoopCyclicModuleIso (AdjoinRoot.root_X_pow_pow_mul_eq_zero_iff hi)

/-- Over `R[X]/(X ^ n)`, with `x` the class of `X` and `M_i = A ⧸ (x ^ i)`, the module `M_i` is
periodic of period at most two in the stable module category: `Ω² M_i ≅ M_i` for `i ≤ n`. -/
noncomputable def stableModuleLoopLoopCyclicModuleRootPowIso (hi : i ≤ n) :
    (stableModuleLoop (AdjoinRoot (X ^ n : R[X]))).obj ((stableModuleLoop _).obj
        ((stableModuleFunctor _).obj (cyclicModule (AdjoinRoot.root (X ^ n : R[X]) ^ i)))) ≅
      (stableModuleFunctor _).obj (cyclicModule (AdjoinRoot.root (X ^ n : R[X]) ^ i)) :=
  stableModuleLoopLoopCyclicModuleIso (AdjoinRoot.root_X_pow_pow_mul_eq_zero_iff hi) <| by
    simpa only [Nat.sub_sub_self hi] using
      AdjoinRoot.root_X_pow_pow_mul_eq_zero_iff (R := R) (Nat.sub_le n i)

variable (n) in
/-- Over `R[X]/(X ^ n)`, the module `M_n = A ⧸ (x ^ n)`, which is the free module `A` since
`x ^ n = 0`, is zero in the stable module category. -/
theorem isZero_stableModuleFunctor_obj_cyclicModule_root_pow_self :
    IsZero ((stableModuleFunctor (AdjoinRoot (X ^ n : R[X]))).obj
      (cyclicModule (AdjoinRoot.root (X ^ n : R[X]) ^ n))) := by
  rw [← AdjoinRoot.mk_X, ← map_pow, AdjoinRoot.mk_self]
  exact isZero_stableModuleFunctor_obj_cyclicModule_zero

end TruncatedPolynomial

end FGModuleCat

end TauCeti
