/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Laurent.Basic
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Laurent.Sieve
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.IsSheafFor
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Sheaf
public import TauCeti.RingTheory.Huber.StronglyNoetherian

import Mathlib.CategoryTheory.Sites.Coverage
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.OpenEmbedding
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.Units

/-!
# The sheaf condition for standard rational covers

Let `A` be a Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of
`X = Spa(A, A⁺)` and `T ⊆ A` a nonempty finite set. The *standard rational cover* of `W` generated
by `T` consists of the pieces

```text
W ∩ R(T/t) = W ∩ {v | v(t') ≤ v(t) ≠ 0 for t' ∈ T},    t ∈ T.
```

When every `t ∈ T` is a unit, the Laurent cover generated by the ratios `t t'⁻¹` refines this
cover (`exists_rationalSubset_superset_laurentPiece_mul_inverse`, Wedhorn's Lemma 8.34(iii)). So a
presheaf of sets satisfying the sheaf condition for Laurent covers of rational subsets satisfies it
for the standard cover too (`isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit_of_isSheafFor`).

In Wedhorn's proof of Lemma 8.34, part (iii) is applied to standard covers of a rational subset `W`
generated by elements that are units of the coordinate ring of `W` rather than of `A`: they vanish
nowhere on `W`, as the generators of sign `≥` do on a piece of the Laurent cover of part (ii)
(`not_vle_zero_of_mem_laurentPiece_inv_mul`). Writing `W = R(U/s)` and `B = A⟨U/s⟩`, the elements
of `T` become units of `B` (`isUnit_toCompletionLoc_iff_forall_notMem_supp`), the pieces pull back
to the standard cover of `Spa(B, A_U⁺)` generated by their images, and the sheaf condition is
transported back along Wedhorn's Remark 8.4 (`isSheafFor_ofArrows_iff_locOpensComap`). This needs
Laurent gluing over `B` rather than over `A`, so it is proved for the presentation-limit presheaf
of a Tate ring satisfying a predicate `C` with `LaurentGluing C`, which passes to `B`
(`isSheafFor_ofArrows_inf_spaBasicOpen_of_laurentGluing`).

Part (ii) of Lemma 8.34 removes the restriction on `T`: it suffices that `T` generate the unit
ideal of `A` (`isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing`). Choose a
unit `ϖ` strictly dominated at every point by an element of `T`
(`exists_unit_forall_mem_spa_exists_vlt`). On a rational subset of a piece of the Laurent cover
generated by the `ϖ⁻¹ t`, the standard cover is generated by the elements of sign `≥`, which vanish
nowhere there, so it satisfies the sheaf condition
(`isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece_of_isSheafFor`). Since the Laurent
cover itself satisfies the sheaf condition, sections over the pieces of the standard cover glue
first on each Laurent piece and then over `W` (`TauCeti.TopologicalSpace.Opens.isSheafFor_trans`).

Strong noetherianness satisfies `LaurentGluing` (`laurentGluing_isStronglyNoetherian`), which gives
the statements for a strongly noetherian Tate ring.

All these statements concern the sheaf condition in degree zero, for the presentation-limit
presheaf as a presheaf of sets; higher Čech cohomology is not treated here.

## Main results

* `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit_of_isSheafFor` : a
  presheaf of sets satisfying the sheaf condition for Laurent covers of rational subsets satisfies
  it for the standard cover of a rational subset generated by units of `A`.
* `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_laurentGluing` : the standard
  cover of a rational subset `W` generated by elements vanishing nowhere on `W` satisfies the sheaf
  condition.
* `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing` :
  the standard cover of a rational subset generated by a finite set generating the unit ideal
  satisfies the sheaf condition.
* `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit`,
  `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen`,
  `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece` and
  `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top` : the
  corresponding statements over a strongly noetherian Tate ring.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Remark 8.4 and
  Lemma 8.34(ii), (iii).
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemmas 3 and 4, the
  rigid-analytic originals of the two reductions.
-/

public section

open CategoryTheory TopologicalSpace TauCeti.Huber TauCeti.Huber.PairOfDefinition

universe v w

namespace TauCeti.ValuationSpectrum

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  (P : PairOfDefinition A) {Aplus : Subring A}

omit [IsTateRing A] in
/-- **Wedhorn's Lemma 8.34(iii) in degree zero for a presheaf of sets.** Let `W` be a rational
subset of `Spa(A, A⁺)` and `T` a nonempty finite set of units of `A`, and let `F` be a presheaf of
sets that satisfies the sheaf condition for the Laurent cover of every rational subset generated by
a finite set. Then `F` satisfies the sheaf condition for the standard rational cover
`(W ∩ R(T/t))_{t ∈ T}` of `W`, which the Laurent cover generated by the ratios `t t'⁻¹` refines. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit_of_isSheafFor [IsHuberRing A]
    {T : Finset A} (hT : T.Nonempty) (hu : ∀ t ∈ T, IsUnit t) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) (F : (Opens ↥(spa Aplus))ᵒᵖ ⥤ Type w)
    (hlaurent : ∀ (R : Finset A) {V : Opens ↥(spa Aplus)},
      V ∈ spaRationalOpens Aplus → (laurentSieve Aplus R V).arrows.IsSheafFor F) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor F := by
  classical
  -- the ratios `t t'⁻¹` generating the refining Laurent cover
  let f : T × T → A := fun p ↦ (p.1 : A) * Ring.inverse (p.2 : A)
  let R : Finset A := Finset.univ.image f
  -- `T` contains a unit, so it generates the unit ideal, which is open
  have hTopen : IsOpen (Ideal.span (T : Set A) : Set A) := by
    obtain ⟨t, ht⟩ := hT
    rw [Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span ht) (hu t ht)]
    exact isOpen_univ
  have hWt (t : T) : W ⊓ spaBasicOpen Aplus T t ∈ spaRationalOpens Aplus :=
    inf_mem_spaRationalOpens hW (spaBasicOpen_mem_spaRationalOpens hTopen)
  refine Presieve.isSheafFor_of_factorsThru _ (S := (laurentSieve Aplus R W).arrows)
    (fun _ g hg ↦ laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen hT hu W g hg)
    (hlaurent R hW) fun Y e he ↦ ?_
  -- on each piece of the standard cover, the Laurent sieve restricts to a Laurent sieve
  obtain ⟨t⟩ := he
  refine ⟨(laurentSieve Aplus R _).arrows,
    (hlaurent R (hWt t)).isSeparatedFor,
    fun Z g hg ↦ ⟨Z, 𝟙 Z, g ≫ homOfLE inf_le_left, ?_, Category.id_comp _⟩⟩
  rw [← laurentSieve_pullback R (homOfLE inf_le_left : W ⊓ spaBasicOpen Aplus T t ⟶ W)] at hg
  exact hg

/-- **Standard covers generated by elements vanishing nowhere.** Let `C` be a predicate on Tate
rings satisfying `LaurentGluing`, and `A` a Tate ring satisfying `C`. Let `P` be a pair of
definition whose ring of definition lies in `A⁺`, `A⁺` a subring of power-bounded elements, `W` a
rational subset of `Spa(A, A⁺)` and `T` a nonempty finite subset of `A` that vanishes at no point
of `W`. The presentation-limit presheaf, as a presheaf of sets, satisfies the sheaf condition for
the standard rational cover `(W ∩ R(T/t))_{t ∈ T}` of `W`.

The elements of `T` are units of the coordinate ring `B` of `W`, though not necessarily of `A`.
The cover pulls back to the standard cover of `Spa(B, A_U⁺)` generated by these units, to which
`isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit_of_isSheafFor` applies since `B` again satisfies
`C`. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_laurentGluing
    {C : ∀ (A : Type v) [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A], Prop}
    (hC : LaurentGluing C) (hA : C A) (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (hTW : ∀ t ∈ T, ∀ v ∈ W, t ∉ supp (v : Spv A)) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) := by
  classical
  obtain ⟨U, s, hU, hWU⟩ := mem_spaRationalFamily_iff.mp (mem_spaRationalOpens.mp hW)
  obtain rfl : W = spaBasicOpen Aplus U s :=
    Opens.ext (hWU.trans (Set.ext fun _ ↦ mem_spaBasicOpen.symm))
  -- `B = A⟨U/s⟩` is again a Tate ring satisfying `C`, with plus ring of power-bounded elements
  have hden := hasDenominatorPower_of_isOpen_span P U s (Localization.Away s) hU
  let _ := locUniformSpace P U s _ hden
  have _ := isUniformAddGroup_locUniformSpace P U s _ hden
  have _ := isTopologicalRing_locUniformSpace P U s _ hden
  have _ := isTateRing_completion_locTopology_of_isTateRing P U s _ hden
  have hB : C (UniformSpace.Completion (Localization.Away s)) :=
    hC.completion_localization P U s hU hA
  have hBplus := isPowerBounded_of_mem_completedPlusSubring P Aplus hAplus U s _ hden
  let ρ := toCompletionLoc P U s _ hden
  -- the elements of `T` vanish nowhere on `R(U/s)`, so they become units of `B`
  have hu : ∀ t' ∈ T.image ρ, IsUnit t' := by
    simp only [Finset.mem_image]
    rintro _ ⟨t, ht, rfl⟩
    exact (isUnit_toCompletionLoc_iff_forall_notMem_supp P Aplus hP hAplus U s _ hden t).2
      fun v hv ↦ hTW t ht ⟨v, rationalSubset_subset_spa Aplus U s hv⟩ (mem_spaBasicOpen.mpr hv)
  obtain ⟨t₀, ht₀⟩ := hT.image ρ
  -- the pieces pull back to the standard cover of `B` generated by the image of `T`
  have hpull (t : T) : locOpensComap P Aplus U s _ hden
      (spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t) =
        locOpensComap P Aplus U s _ hden (spaBasicOpen Aplus U s) ⊓
          spaBasicOpen (completedPlusSubring P Aplus U s _ hden) (T.image ρ) (ρ t) := by
    rw [locOpensComap_inf, locOpensComap_spaBasicOpen P Aplus U s _ hden T]
  -- the pieces are rational, being the images of rational opens of `Spa(B, A_U⁺)`
  have hrat (t : T) : spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t ∈ spaRationalOpens Aplus := by
    rw [← spaComapLoc_functor_obj_locOpensComap P Aplus hP U s _ hden inf_le_left]
    refine spaComapLoc_functor_obj_mem_spaRationalOpens P Aplus hP U s _ hden hU _ ?_
    rw [hpull]
    exact inf_mem_spaRationalOpens (locOpensComap_mem_spaRationalOpens P Aplus U s _ hden hW)
      (spaBasicOpen_mem_spaRationalOpens <| by
        rw [Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span ht₀) (hu t₀ ht₀)]
        exact isOpen_univ)
  rw [isSheafFor_ofArrows_iff_locOpensComap P Aplus U s _ hden hAplus hU hW le_rfl hrat
    fun _ ↦ inf_le_left]
  -- reindex the standard cover of `B`, generated by the units `ρ t`, by `T`
  have hB := isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit_of_isSheafFor (hT.image ρ) hu
    (locOpensComap_mem_spaRationalOpens P Aplus U s _ hden hW) _ fun R _ hV ↦
      isSheafFor_laurentSieve_of_isSheafFor
        (hC.isSheafFor_ofArrows_inf_laurentCoverOpen (completionLocalization P U s _ hden) hB
          hBplus) R hV
  rw [← Presieve.ofArrows_comp_eq_of_surjective _ (a := fun t : T ↦
    (⟨ρ t, Finset.mem_image_of_mem ρ t.2⟩ : T.image ρ)) ?_] at hB
  · -- a family of inclusions into `Z` is determined by its domains
    have key {Y Y' : T → Opens ↥(spa (completedPlusSubring P Aplus U s _ hden))} (e : Y = Y')
        {Z : Opens ↥(spa (completedPlusSubring P Aplus U s _ hden))} (h : ∀ t, Y t ≤ Z)
        (h' : ∀ t, Y' t ≤ Z) :
        Presieve.ofArrows Y (fun t ↦ homOfLE (h t)) = Presieve.ofArrows Y' fun t ↦ homOfLE (h' t) :=
      by subst e; rfl
    rwa [key (funext hpull)]
  · rintro ⟨_, h⟩
    obtain ⟨t, ht, rfl⟩ := Finset.mem_image.mp h
    exact ⟨⟨t, ht⟩, rfl⟩

/-! ### Standard covers generated by the unit ideal -/

omit [IsTopologicalRing A] [IsTateRing A] in
/-- The sieve-theoretic reduction of a standard cover on a Laurent piece to the subcover whose
generators have positive sign. This is independent of the target functor: it only requires the
sheaf condition for standard covers whose generators vanish nowhere. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece_of_isSheafFor
    {T : Finset A} (hT : T.Nonempty) {ϖ : Aˣ}
    (hϖ : ∀ v ∈ spa Aplus, ∃ t ∈ T, v.toValuativeRel.vlt (ϖ : A) t) {J : Set T}
    {V : Opens ↥(spa Aplus)}
    (hVJ : (V : Set ↥(spa Aplus)) ⊆
      Subtype.val ⁻¹' laurentPiece Aplus (fun t : T ↦ (ϖ⁻¹ : Aˣ) * (t : A)) J)
    (F : (Opens ↥(spa Aplus))ᵒᵖ ⥤ Type v)
    (hstandard : ∀ {T' : Finset A}, T'.Nonempty →
      (∀ t ∈ T', ∀ v ∈ V, t ∉ supp (v : Spv A)) →
      (Presieve.ofArrows (fun t : T' ↦ V ⊓ spaBasicOpen Aplus T' t)
        fun _ ↦ homOfLE inf_le_left).IsSheafFor F) :
    (Presieve.ofArrows (fun t : T ↦ V ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor F := by
  classical
  -- the generators of sign `≥` on the Laurent piece
  let TJ : Finset A := T.filter fun a ↦ ∃ h : a ∈ T, (⟨a, h⟩ : T) ∈ J
  have hmemTJ {a : A} : a ∈ TJ ↔ ∃ h : a ∈ T, (⟨a, h⟩ : T) ∈ J := by
    simp only [TJ, Finset.mem_filter]
    exact ⟨fun h ↦ h.2, fun h ↦ ⟨h.1, h⟩⟩
  -- the pieces of sign `≤` are empty on `V`
  have hempty (t : T) (ht : t ∉ J) : V ⊓ spaBasicOpen Aplus T t = ⊥ :=
    eq_bot_iff.mpr fun v hv ↦ (Set.eq_empty_iff_forall_notMem.mp
      (rationalSubset_inter_laurentPiece_inv_mul_eq_empty hϖ ht) v.1
        ⟨mem_spaBasicOpen.mp hv.2, hVJ hv.1⟩).elim
  -- the pieces of sign `≥` are cut out by `TJ`
  have hpiece (t : T) (ht : t ∈ J) :
      V ⊓ spaBasicOpen Aplus T t = V ⊓ spaBasicOpen Aplus TJ t := by
    refine SetLike.ext fun v ↦ ?_
    simp only [Opens.mem_inf, mem_spaBasicOpen]
    refine and_congr_right fun hv ↦ ⟨fun h ↦ rationalSubset_subset_rationalSubset_of_subset Aplus
      (Finset.filter_subset _ T) t h, fun h ↦ ?_⟩
    exact (mem_rationalSubset_iff_of_mem_laurentPiece_inv_mul ϖ ht (hVJ hv)).mpr fun t' ht' ↦
      ((mem_rationalSubset_iff _ _ _ _).mp h).2.1 t' (hmemTJ.mpr ⟨t'.2, ht'⟩)
  rw [Presieve.isSheafFor_iff_generate]
  rcases TJ.eq_empty_or_nonempty with hTJ | hTJ
  · -- no generator has sign `≥`, so `V` is empty and the cover is trivial
    obtain ⟨t₀, ht₀⟩ := hT
    have hV₀ : V ≤ V ⊓ spaBasicOpen Aplus T t₀ := fun v hv ↦ by
      obtain ⟨t, ht, hlt⟩ := hϖ v.1 v.2
      have htJ : (⟨t, ht⟩ : T) ∉ J := fun h ↦ by simpa [hTJ] using hmemTJ.mpr ⟨ht, h⟩
      exact (hlt (@TauCeti.ValuativeRel.vle_of_inv_mul_vle A _ v.1.toValuativeRel ϖ t
        ((((mem_laurentPiece_iff _ _ _ _).mp (hVJ hv)).2 ⟨t, ht⟩).2 htJ))).elim
    rw [(Sieve.id_mem_iff_eq_top (S := Sieve.generate _)).mp
      ⟨_, homOfLE hV₀, _, Presieve.ofArrows.mk (⟨t₀, ht₀⟩ : T), rfl⟩]
    exact Presieve.isSheafFor_top _
  · -- otherwise the pieces of `T` and of `TJ` generate the same sieve on `V`
    have h := hstandard hTJ fun a ha v hv hsupp ↦ by
      obtain ⟨haT, haJ⟩ := hmemTJ.mp ha
      exact not_vle_zero_of_mem_laurentPiece_inv_mul ϖ haJ (hVJ hv) ((mem_supp_iff _ _).mp hsupp)
    rw [Presieve.isSheafFor_iff_generate] at h
    refine (congrArg (fun S : Sieve V ↦ S.arrows.IsSheafFor _) (Sieve.ext fun U g ↦ ?_)).mp h
    simp only [Sieve.mem_ofArrows_iff]
    constructor
    · rintro ⟨⟨a, ha⟩, e, -⟩
      obtain ⟨haT, haJ⟩ := hmemTJ.mp ha
      exact ⟨⟨a, haT⟩, homOfLE (e.le.trans (hpiece _ haJ).symm.le), rfl⟩
    · rintro ⟨t, e, -⟩
      by_cases ht : t ∈ J
      · exact ⟨⟨t, hmemTJ.mpr ⟨t.2, ht⟩⟩, homOfLE (e.le.trans (hpiece t ht).le), rfl⟩
      · obtain ⟨a, ha⟩ := hTJ
        exact ⟨⟨a, ha⟩, homOfLE (e.le.trans ((hempty t ht).le.trans bot_le)), rfl⟩

/-- The sieve-theoretic reduction from standard covers generated by the unit ideal to standard
covers on Laurent pieces. This is independent of the target functor: it only requires the sheaf
conditions for Laurent covers and for standard covers whose generators vanish nowhere. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_isSheafFor
    {T : Finset A} (hT : T.Nonempty) (hspan : Ideal.span (T : Set A) = ⊤)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (F : (Opens ↥(spa Aplus))ᵒᵖ ⥤ Type v)
    (hstandard : ∀ {T' : Finset A}, T'.Nonempty → {V : Opens ↥(spa Aplus)} →
      V ∈ spaRationalOpens Aplus → (∀ t ∈ T', ∀ v ∈ V, t ∉ supp (v : Spv A)) →
      (Presieve.ofArrows (fun t : T' ↦ V ⊓ spaBasicOpen Aplus T' t)
        fun _ ↦ homOfLE inf_le_left).IsSheafFor F)
    (hlaurent : ∀ (R : Finset A) {V : Opens ↥(spa Aplus)},
      V ∈ spaRationalOpens Aplus → (laurentSieve Aplus R V).arrows.IsSheafFor F) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor F := by
  classical
  obtain ⟨ϖ, hϖ⟩ := exists_unit_forall_mem_spa_exists_vlt Aplus hspan
  let f : T → A := fun t ↦ (ϖ⁻¹ : Aˣ) * (t : A)
  -- the pieces `Y J` of the Laurent cover of `W` generated by the `ϖ⁻¹ t`, indexed by sign sets
  let Y (J : Set T) : Opens ↥(spa Aplus) := W ⊓
    ⟨_, (isTopologicalBasis_spaRationalFamily Aplus).isOpen
      (val_preimage_laurentPiece_mem_spaRationalFamily Aplus f J)⟩
  have hY (J : Set T) : Y J ∈ spaRationalOpens Aplus :=
    inf_mem_spaRationalOpens hW
      (mem_spaRationalOpens.mpr (val_preimage_laurentPiece_mem_spaRationalFamily Aplus f J))
  -- the Laurent sieve generated by the `ϖ⁻¹ t` consists of the opens inside some `Y J`
  let R : Finset A := Finset.univ.image f
  have hRY {U V : Opens ↥(spa Aplus)} (g : U ⟶ V) (hVW : V ≤ W)
      (hg : laurentSieve Aplus R V g) : ∃ J, U ≤ Y J :=
    ((laurentSieve_image_apply_iff_exists_laurentPiece f g).mp hg).imp fun _ hJ ↦
      le_inf (g.le.trans hVW) hJ
  -- the sieve of the opens of `W` inside both a piece `Y J` and a piece of the standard cover
  let S : Sieve W :=
    { arrows U _ := (∃ J, U ≤ Y J) ∧ ∃ t ∈ T, U ≤ spaBasicOpen Aplus T t
      downward_closed := fun ⟨⟨J, hJ⟩, t, ht, hUt⟩ g ↦
        ⟨⟨J, g.le.trans hJ⟩, t, ht, g.le.trans hUt⟩ }
  -- on a rational open inside some `Y J`, `S` restricts to the standard cover
  have hSV (J : Set T) {V : Opens ↥(spa Aplus)} (hV : V ∈ spaRationalOpens Aplus)
      (hVJ : V ≤ Y J) : (S.pullback (homOfLE (hVJ.trans inf_le_left))).arrows.IsSheafFor F := by
    have h := isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece_of_isSheafFor hT hϖ
      (fun v hv ↦ (hVJ hv).2) F (fun hT' hT'V ↦ hstandard hT' hV hT'V)
    rw [Presieve.isSheafFor_iff_generate] at h
    refine (congrArg (fun S' : Sieve V ↦ S'.arrows.IsSheafFor _) (Sieve.ext fun U g ↦ ?_)).mp h
    simp only [Sieve.mem_ofArrows_iff, Sieve.pullback_apply]
    constructor
    · rintro ⟨t, e, -⟩
      exact ⟨⟨J, e.le.trans (inf_le_left.trans hVJ)⟩, t, t.2, e.le.trans inf_le_right⟩
    · rintro ⟨-, t, ht, hUt⟩
      exact ⟨⟨t, ht⟩, homOfLE (le_inf g.le hUt), rfl⟩
  -- `S` satisfies the sheaf condition: glue over each `Y J`, then over `W`
  have hS : S.arrows.IsSheafFor F := by
    refine TopologicalSpace.Opens.isSheafFor_trans Y (fun _ ↦ inf_le_left) S ?_
      (fun J ↦ hSV J (hY J) le_rfl)
      (fun J J' ↦ (hSV J (inf_mem_spaRationalOpens (hY J) (hY J')) inf_le_left).isSeparatedFor)
      fun _ _ hg ↦ hg.1
    -- the pieces `Y J` satisfy the sheaf condition, since the Laurent sieve does
    refine Presieve.isSheafFor_of_factorsThru _ (S := (laurentSieve Aplus R W).arrows)
      (fun U g hg ↦ ?_) (hlaurent R hW) fun Z e he ↦ ?_
    · obtain ⟨J, hJ⟩ := hRY g le_rfl hg
      exact ⟨Y J, homOfLE hJ, homOfLE inf_le_left, Presieve.ofArrows.mk J, rfl⟩
    · obtain ⟨J⟩ := he
      refine ⟨(laurentSieve Aplus R _).arrows, (hlaurent R (hY J)).isSeparatedFor,
        fun U g hg ↦ ⟨U, 𝟙 U, g ≫ homOfLE inf_le_left,
          (laurentSieve_apply _).mpr ((laurentSieve_apply g).mp hg), Category.id_comp _⟩⟩
  -- every member of `S` lies in a piece of the standard cover, and on each piece the Laurent
  -- sieve, which is separated there, refines `S`
  have hTopen : IsOpen (Ideal.span (T : Set A) : Set A) := by
    rw [hspan]
    exact isOpen_univ
  refine Presieve.isSheafFor_of_factorsThru _ (S := S.arrows) (fun U g hg ↦ ?_) hS
    fun Z e he ↦ ?_
  · obtain ⟨-, t, ht, hUt⟩ := hg
    exact ⟨W ⊓ spaBasicOpen Aplus T t, homOfLE (le_inf g.le hUt), homOfLE inf_le_left,
      Presieve.ofArrows.mk (⟨t, ht⟩ : T), rfl⟩
  · obtain ⟨t⟩ := he
    refine ⟨(laurentSieve Aplus R _).arrows,
      (hlaurent R
        (inf_mem_spaRationalOpens hW (spaBasicOpen_mem_spaRationalOpens hTopen))).isSeparatedFor,
      fun U g hg ↦ ⟨U, 𝟙 U, g ≫ homOfLE inf_le_left,
        ⟨hRY g inf_le_left hg, t, t.2, g.le.trans inf_le_right⟩, Category.id_comp _⟩⟩

/-- **Wedhorn's Lemma 8.34 in degree zero for standard covers.** Let `C` be a predicate on Tate
rings satisfying `LaurentGluing`, and `A` a Tate ring satisfying `C`. Let `P` be a pair of
definition whose ring of definition lies in `A⁺`, `A⁺` a subring of power-bounded elements, `W` a
rational subset of `Spa(A, A⁺)` and `T` a nonempty finite subset of `A` generating the unit ideal.
The presentation-limit presheaf, as a presheaf of sets, satisfies the sheaf condition for the
standard rational cover `(W ∩ R(T/t))_{t ∈ T}` of `W`: sections over the pieces that agree on the
overlaps glue uniquely to a section over `W`.

Following Wedhorn, choose a unit `ϖ` strictly dominated at every point by an element of `T`
(`exists_unit_forall_mem_spa_exists_vlt`). The Laurent cover of `W` generated by the `ϖ⁻¹ t`
satisfies the sheaf condition (`isSheafFor_laurentSieve_of_isSheafFor`), and on each of its
pieces, and on their overlaps, the restricted standard cover is generated by elements vanishing
nowhere (`isSheafFor_ofArrows_inf_spaBasicOpen_of_laurentGluing`). -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing
    {C : ∀ (A : Type v) [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A], Prop}
    (hC : LaurentGluing C) (hA : C A) (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hspan : Ideal.span (T : Set A) = ⊤) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) :=
  isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_isSheafFor hT hspan hW _
    (fun hT' _ hV hT'V ↦ isSheafFor_ofArrows_inf_spaBasicOpen_of_laurentGluing P hC hA hP hAplus hT'
      hV hT'V)
    fun R _ hV ↦ isSheafFor_laurentSieve_of_isSheafFor
      (hC.isSheafFor_ofArrows_inf_laurentCoverOpen P hA hAplus) R hV

/-! ### The strongly noetherian case -/

section StronglyNoetherian

variable [IsStronglyNoetherian A]

/-- **Wedhorn's Lemma 8.34(iii) in degree zero: standard covers generated by units.** Let `A` be a
strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of
`Spa(A, A⁺)` and `T` a nonempty finite set of units of `A`. The presentation-limit presheaf, as a
presheaf of sets, satisfies the sheaf condition for the standard rational cover
`(W ∩ R(T/t))_{t ∈ T}` of `W`: sections over the pieces that agree on the overlaps glue uniquely
to a section over `W`. `A` itself need not be complete. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hu : ∀ t ∈ T, IsUnit t) {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) :=
  isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit_of_isSheafFor hT hu hW _ fun R _ hV ↦
    isSheafFor_laurentSieve P hAplus R hV

/-- **Standard covers generated by elements vanishing nowhere.** Let `A` be a strongly noetherian
Tate ring, `P` a pair of definition whose ring of definition lies in `A⁺`, `A⁺` a subring of
power-bounded elements, `W` a rational subset of `Spa(A, A⁺)` and `T` a nonempty finite subset of
`A` that vanishes at no point of `W`. The presentation-limit presheaf, as a presheaf of sets,
satisfies the sheaf condition for the standard rational cover `(W ∩ R(T/t))_{t ∈ T}` of `W`.

The elements of `T` are units of the coordinate ring of `W`, though not necessarily of `A`; when
they are units of `A`, see `isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit`, which needs no
hypothesis on `P`. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (hTW : ∀ t ∈ T, ∀ v ∈ W, t ∉ supp (v : Spv A)) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) :=
  isSheafFor_ofArrows_inf_spaBasicOpen_of_laurentGluing P laurentGluing_isStronglyNoetherian
    (inferInstanceAs (IsStronglyNoetherian A)) hP hAplus hT hW hTW

/-- **Wedhorn's Lemma 8.34(ii) in degree zero: a standard cover restricted to a Laurent piece.**
Let `A` be a strongly noetherian Tate ring, `P` a pair of definition whose ring of definition lies
in `A⁺`, `A⁺` a subring of power-bounded elements, `T ⊆ A` a nonempty finite set and `ϖ` a unit of
`A` strictly dominated at every point of `Spa(A, A⁺)` by some element of `T`. Let `V` be a rational
subset contained in the piece with sign set `J` of the Laurent cover generated by the `ϖ⁻¹ t`,
`t ∈ T`. The presentation-limit presheaf, as a presheaf of sets, satisfies the sheaf condition for
the restriction `(V ∩ R(T/t))_{t ∈ T}` of the standard cover generated by `T` to `V`.

On `V`, the pieces with `t ∉ J` are empty (`rationalSubset_inter_laurentPiece_inv_mul_eq_empty`),
and the others form the standard cover of `V` generated by the elements of `J`
(`mem_rationalSubset_iff_of_mem_laurentPiece_inv_mul`), which vanish nowhere on `V`
(`not_vle_zero_of_mem_laurentPiece_inv_mul`). -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece
    (hP : P.ringOfDefinition ≤ Aplus) (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    {T : Finset A} (hT : T.Nonempty) {ϖ : Aˣ}
    (hϖ : ∀ v ∈ spa Aplus, ∃ t ∈ T, v.toValuativeRel.vlt (ϖ : A) t) {J : Set T}
    {V : Opens ↥(spa Aplus)} (hV : V ∈ spaRationalOpens Aplus)
    (hVJ : (V : Set ↥(spa Aplus)) ⊆
      Subtype.val ⁻¹' laurentPiece Aplus (fun t : T ↦ (ϖ⁻¹ : Aˣ) * (t : A)) J) :
    (Presieve.ofArrows (fun t : T ↦ V ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) := by
  apply isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece_of_isSheafFor hT hϖ hVJ
  intro T' hT' hT'V
  exact isSheafFor_ofArrows_inf_spaBasicOpen P hP hAplus hT' hV hT'V

/-- **Wedhorn's Lemma 8.34 in degree zero for standard covers.** Let `A` be a strongly noetherian
Tate ring, `P` a pair of definition whose ring of definition lies in `A⁺`, `A⁺` a subring of
power-bounded elements, `W` a rational subset of `Spa(A, A⁺)` and `T` a nonempty finite subset of
`A` generating the unit ideal. The presentation-limit presheaf, as a presheaf of sets, satisfies
the sheaf condition for the standard rational cover `(W ∩ R(T/t))_{t ∈ T}` of `W`: sections over
the pieces that agree on the overlaps glue uniquely to a section over `W`.

This is `isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing` for strong
noetherianness (`laurentGluing_isStronglyNoetherian`). -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hspan : Ideal.span (T : Set A) = ⊤) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) :=
  isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_of_laurentGluing P
    laurentGluing_isStronglyNoetherian (inferInstanceAs (IsStronglyNoetherian A)) hP hAplus hT
    hspan hW

end StronglyNoetherian

end TauCeti.ValuationSpectrum
