/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.MonoidAlgebra.RelationModule.Basic
public import TauCeti.NumberTheory.LocalField.TameFrameModule.Torsion
public import TauCeti.NumberTheory.Padics.MultiplicativeCompletion.Rational
import Mathlib.LinearAlgebra.TensorProduct.Prod
import TauCeti.Algebra.MonoidAlgebra.FractionRing
import TauCeti.NumberTheory.Padics.GroupAlgebra.RelationModule
import TauCeti.NumberTheory.Padics.GroupAlgebra.StableIsomorphism
import TauCeti.NumberTheory.Padics.GroupAlgebra.Transpose

/-!
# The integral decomposition of an extension of the augmentation ideal by `A(L)`

Let `L/K` be a finite Galois extension of `p`-adic fields with group `G = Gal(L/K)`, let
`N = [K : ℚ_p]`, and let `A(L) = lim_m Lˣ/(Lˣ)^(p^m)` be the `p`-adic completion of `Lˣ`, a
`ℤ_p[G]`-module. Let `Y` be a `ℤ_p[G]`-module of projective dimension at most one which is an
extension

`0 → A(L) → Y → I_G → 0`

of the augmentation ideal `I_G` of `ℤ_p[G]` by `A(L)`. The Tate module `I_{G_K} / I_{G_L} I_{G_K}`
of the layer (NSW (5.6.5)) is such a module: its projective dimension is at most one by Tate's
theorem for the fundamental class of `L/K`.

This file proves that every such `Y` is isomorphic to `M₀ ⊕ ℤ_p[G]^N`, where
`M₀ = ℤ_p[G]² / ℤ_p[G]·(σ - a, τ - b)` is the tame-frame module of a generating pair `σ, τ` of
`G` with sharp exponents `a, b` (`TauCeti.exists_tameFrame_exponents`). This is the isomorphism
`(∗∗)` in the proof of NSW (7.4.1). It is an integral statement: `Y` is generated by `N + 2`
elements, since `M₀` is a quotient of `ℤ_p[G]²`, and no such count can be read off the rational
representation of `Y`.

The proof applies the cancellation theory of `ℤ_p[G]`-modules.

* The `p`-power torsion of `Y` is that of `A(L)`, because `I_G ⊆ ℤ_p[G]` is torsion-free, and
  this is the `p`-power torsion of `M₀` for sharp exponents
  (`TauCeti.tameFrameModule_torsion_linearEquiv`). Both `Y` and `M₀` have projective dimension at
  most one, so they are stably isomorphic
  (`TauCeti.exists_projective_prod_linearEquiv_of_torsion`).
* Rationally, the extensions `0 → A(L) → Y → I_G → 0` and `0 → I_G → ℤ_p[G] → ℤ_p → 0` split
  (`TauCeti.IsFractionRing.nonempty_tensor_linearEquiv_prod_of_exact`). With the rational
  decomposition `A(L) ⊗ ℚ_p ≃ ℚ_p[G]^N ⊕ ℚ_p`
  (`TauCeti.nonempty_padicCompletionUnits_tensorRat_linearEquiv`) and `M₀ ⊗ ℚ_p ≃ ℚ_p[G]`
  (`TauCeti.nonempty_tameFrameModule_tensorRat_linearEquiv`), this gives
  `Y ⊗ ℚ_p ≃ (M₀ ⊕ ℤ_p[G]^N) ⊗ ℚ_p`.
* A stable isomorphism together with this rational identity is an isomorphism
  (`TauCeti.nonempty_linearEquiv_prod_of_stable`).

When `σ, τ` generate `G` and `τ` has order prime to `p`, sharp exponents exist, and the
decomposition makes `Y` a quotient of `ℤ_p[G]^(N + 2) = ℤ_p[G]² ⊕ ℤ_p[G]^N` by a copy of
`ℤ_p[G]`. Comparing the induced presentation of `I_G` with the one by any generating family `g` of
size `N + 2` (`TauCeti.exists_relationModule_surjective_of_exact`), the relation module of `g`,
which is `R^ab(p)` for the presentation of `G` on `g` by Lyndon's theorem, maps onto `A(L)` with
kernel `ℤ_p[G]`: the integral sequence `0 → ℤ_p[G] → R^ab(p) → A(L) → 0` of the proof of
NSW (7.4.1).

## Main results

* `TauCeti.nonempty_linearEquiv_tameFrameModule_prod`: an extension of `I_G` by `A(L)` of
  projective dimension at most one is isomorphic to `M₀ ⊕ ℤ_p[G]^N`.
* `TauCeti.exists_relationModule_surjective_of_tameFrame`: on a layer with a generating pair
  `σ, τ`, `τ` of order prime to `p`, the relation module of every generating family of size
  `N + 2` maps onto `A(L)` with kernel `ℤ_p[G]`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., proof of (7.4.1),
  and (5.6.5), (5.6.6).
-/

public section

open scoped TensorProduct

namespace TauCeti

open _root_.MonoidAlgebra

variable {p : ℕ} [Fact p.Prime] {L : Type*} [Field L] {K : Type*} [Field K] [Algebra K L]

local notation "Λ" => MonoidAlgebra ℤ_[p] (L ≃ₐ[K] L)

/-- **The integral decomposition of an extension of `I_G` by `A(L)`** (the isomorphism `(∗∗)` in
the proof of NSW (7.4.1), for the Tate module of a tame layer). Let `L/K` be a finite Galois
extension of `p`-adic fields with group `G`, and `N = [K : ℚ_p]`. Let `Y` be a `ℤ_p[G]`-module with
a resolution `0 → P₁ → P₀ → Y → 0` by finitely generated projective `ℤ_p[G]`-modules, which is an
extension `0 → A(L) → Y → I_G → 0` of the augmentation ideal by the `p`-adic completion `A(L)` of
`Lˣ`. Let `σ, τ` generate `G` and let `a, b` be sharp exponents for them: `σ, τ` act on the
`p`-power roots of unity of `L` as the `a`-th and `b`-th powers, and `ℤ_p[G] ⧸ (σ - a, τ - b)` has
order `q(L)`. Then `Y ≃ M₀ ⊕ ℤ_p[G]^N`, for `M₀` the tame-frame module of `σ, τ, a, b`. -/
theorem nonempty_linearEquiv_tameFrameModule_prod [Algebra ℚ_[p] L] [Module.Finite ℚ_[p] L]
    [Algebra ℚ_[p] K] [IsScalarTower ℚ_[p] K L] [IsGalois K L]
    {Y P₀ P₁ : Type*} [AddCommGroup Y] [Module Λ Y]
    [AddCommGroup P₀] [Module Λ P₀] [Module.Finite Λ P₀] [Module.Projective Λ P₀]
    [AddCommGroup P₁] [Module Λ P₁] [Module.Finite Λ P₁] [Module.Projective Λ P₁]
    {d : P₁ →ₗ[Λ] P₀} {ρ : P₀ →ₗ[Λ] Y}
    (hdρ : Function.Exact d ρ) (hd : Function.Injective d) (hρ : Function.Surjective ρ)
    {ι : Additive ↑(padicCompletionUnits p L) →ₗ[Λ] Y}
    {π : Y →ₗ[Λ] RingHom.ker (MonoidAlgebra.augmentation ℤ_[p] (L ≃ₐ[K] L))}
    (hιπ : Function.Exact ι π) (hι : Function.Injective ι) (hπ : Function.Surjective π)
    (h : Finite (pPowerRootsOfUnity p L)) (σ τ : L ≃ₐ[K] L)
    (hgen : Subgroup.closure {σ, τ} = ⊤) (a b : ℕ)
    (ha : ∀ ζ ∈ pPowerRootsOfUnity p L, Units.map (σ : L →* L) ζ = ζ ^ a)
    (hb : ∀ ζ ∈ pPowerRootsOfUnity p L, Units.map (τ : L →* L) ζ = ζ ^ b)
    (hcard : Nat.card (Λ ⧸ Ideal.span {single σ (1 : ℤ_[p]) - a, single τ (1 : ℤ_[p]) - b}) =
      localRootOfUnityOrder p L h) :
    Nonempty (Y ≃ₗ[Λ] (TameFrameModule ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p]) ×
      (Fin (Module.finrank ℚ_[p] K) → Λ))) := by
  have := Module.Finite.right ℚ_[p] K L
  have : NeZero (Nat.card (L ≃ₐ[K] L) : ℤ_[p]) := ⟨Nat.cast_ne_zero.mpr Nat.card_pos.ne'⟩
  -- Restrict the scalars of `Y` to `ℤ_p`.
  let _ : Module ℤ_[p] Y := .compHom Y (algebraMap ℤ_[p] Λ)
  have : IsScalarTower ℤ_[p] Λ Y := .of_compHom _ _ _
  -- The tame-frame module is presented by `0 → ℤ_p[G] → ℤ_p[G]² → M₀ → 0`.
  have hcard₀ := hcard ▸ (localRootOfUnityOrder_pos p L h).ne'
  have hcard₁ := hcard₀
  simp only [natCast_def] at hcard₁
  have hrel : Function.Exact (tameFrameRelationMap ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p]))
      (tameFrameRelations ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p])).toQuotient := by
    rw [LinearMap.exact_iff, Module.Relations.ker_toQuotient, range_tameFrameRelationMap]
  have : Module.Finite Λ (TameFrameModule ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p])) :=
    .of_surjective _ (tameFrameRelations ℤ_[p] _ σ τ (a : ℤ_[p]) (b : ℤ_[p])).surjective_toQuotient
  have : Module.Finite ℤ_[p] (TameFrameModule ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p])) :=
    .trans Λ _
  -- The `p`-power torsion of `Y` is that of `A(L)`, since `I_G ⊆ ℤ_p[G]` has none.
  have hI : pPowerTorsion p Λ (RingHom.ker (MonoidAlgebra.augmentation ℤ_[p] (L ≃ₐ[K] L))) = ⊥ :=
    (Submodule.eq_bot_iff _).mpr fun x hx ↦ by
      obtain ⟨k, hx⟩ := mem_pPowerTorsion_iff.mp hx
      rw [← Nat.cast_smul_eq_nsmul ℤ_[p]] at hx
      exact (smul_eq_zero.mp hx).resolve_left
        (Nat.cast_ne_zero.mpr (pow_ne_zero _ (Fact.out : p.Prime).ne_zero))
  obtain ⟨eT⟩ := tameFrameModule_torsion_linearEquiv h σ τ hgen a b ha hb hcard
  -- So `Y` and `M₀` are stably isomorphic.
  obtain ⟨P, Q, _, _, _, _, _, _, _, _, hst⟩ := exists_projective_prod_linearEquiv_of_torsion
    hdρ hd hρ hrel (tameFrameRelationMap_injective_of_card_ne_zero (isOfFinOrder_of_finite σ)
      (isOfFinOrder_of_finite τ) hcard₁)
    (tameFrameRelations ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p])).surjective_toQuotient
    (((Submodule.equivMapOfInjective ι hι _).trans
      (LinearEquiv.ofEq _ _ (map_pPowerTorsion_of_exact hιπ hι hI))).symm.trans eT.symm)
  -- Rationally, `Y ≃ A(L) ⊕ I_G ≃ (ℤ_p[G]^N ⊕ ℤ_p) ⊕ I_G ≃ ℤ_p[G]^N ⊕ ℤ_p[G] ≃ ℤ_p[G]^N ⊕ M₀`.
  obtain ⟨eY⟩ := IsFractionRing.nonempty_tensor_linearEquiv_prod_of_exact ℚ_[p] hιπ hι hπ
  obtain ⟨eA⟩ := IsFractionRing.nonempty_tensor_linearEquiv_prod_of_exact ℚ_[p]
    (LinearMap.exact_subtype_mkQ (RingHom.ker (MonoidAlgebra.augmentation ℤ_[p] (L ≃ₐ[K] L))))
    (Submodule.injective_subtype _) (Submodule.mkQ_surjective _)
  obtain ⟨eL⟩ := nonempty_padicCompletionUnits_tensorRat_linearEquiv (p := p) (L := L) (K := K)
  obtain ⟨eM⟩ := nonempty_tameFrameModule_tensorRat_linearEquiv σ τ a b hcard₀
  exact nonempty_linearEquiv_prod_of_stable p hst ⟨eY ≪≫ₗ TensorProduct.prodLeft _ _ _ _ _ ≪≫ₗ
    (eL ≪≫ₗ TensorProduct.prodLeft _ _ _ _ _).prodCongr (.refl Λ _) ≪≫ₗ
    LinearEquiv.prodAssoc Λ _ _ _ ≪≫ₗ (LinearEquiv.refl Λ _).prodCongr
      (LinearEquiv.prodComm Λ _ _ ≪≫ₗ (eA ≪≫ₗ TensorProduct.prodLeft _ _ _ _ _).symm ≪≫ₗ
        eM.symm) ≪≫ₗ
    LinearEquiv.prodComm Λ _ _ ≪≫ₗ (TensorProduct.prodLeft _ _ _ _ _).symm⟩

/-- **The relation-module surjection on a tame layer** (the first half of the proof of
NSW (7.4.1)). Let `L/K` be a finite Galois extension of `p`-adic fields with group `G`, and
`N = [K : ℚ_p]`. Let `Y` be a `ℤ_p[G]`-module with a resolution `0 → P₁ → P₀ → Y → 0` by finitely
generated projective `ℤ_p[G]`-modules, which is an extension `0 → A(L) → Y → I_G → 0` of the
augmentation ideal by the `p`-adic completion `A(L)` of `Lˣ`. Let `σ, τ` generate `G`, with the
order of `τ` prime to `p`. Then for every generating family `g` of `G` of size `N + 2`, the relation
module of `g` maps onto `A(L)` with kernel isomorphic to `ℤ_p[G]`. -/
theorem exists_relationModule_surjective_of_tameFrame [Algebra ℚ_[p] L] [Module.Finite ℚ_[p] L]
    [Algebra ℚ_[p] K] [IsScalarTower ℚ_[p] K L] [IsGalois K L]
    {Y P₀ P₁ : Type*} [AddCommGroup Y] [Module Λ Y]
    [AddCommGroup P₀] [Module Λ P₀] [Module.Finite Λ P₀] [Module.Projective Λ P₀]
    [AddCommGroup P₁] [Module Λ P₁] [Module.Finite Λ P₁] [Module.Projective Λ P₁]
    {d : P₁ →ₗ[Λ] P₀} {ρ : P₀ →ₗ[Λ] Y}
    (hdρ : Function.Exact d ρ) (hd : Function.Injective d) (hρ : Function.Surjective ρ)
    {ι : Additive ↑(padicCompletionUnits p L) →ₗ[Λ] Y}
    {π : Y →ₗ[Λ] RingHom.ker (MonoidAlgebra.augmentation ℤ_[p] (L ≃ₐ[K] L))}
    (hιπ : Function.Exact ι π) (hι : Function.Injective ι) (hπ : Function.Surjective π)
    (h : Finite (pPowerRootsOfUnity p L)) (σ τ : L ≃ₐ[K] L)
    (hgen : Subgroup.closure {σ, τ} = ⊤) (hτ : ¬ p ∣ orderOf τ)
    {g : Fin (Module.finrank ℚ_[p] K + 2) → L ≃ₐ[K] L} (hg : Subgroup.closure (Set.range g) = ⊤) :
    ∃ β : MonoidAlgebra.relationModule ℤ_[p] (L ≃ₐ[K] L) g →ₗ[Λ]
        Additive (padicCompletionUnits p L),
      Function.Surjective β ∧ Nonempty (LinearMap.ker β ≃ₗ[Λ] Λ) := by
  have := Module.Finite.right ℚ_[p] K L
  obtain ⟨a, b, ha, hb, hcard, -⟩ := exists_tameFrame_exponents h σ τ hgen hτ
  obtain ⟨eY⟩ := nonempty_linearEquiv_tameFrameModule_prod hdρ hd hρ hιπ hι hπ h σ τ hgen a b ha hb
    hcard
  set N := Module.finrank ℚ_[p] K
  set rel := tameFrameRelations ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p])
  set k := tameFrameRelationMap ℤ_[p] (L ≃ₐ[K] L) σ τ (a : ℤ_[p]) (b : ℤ_[p])
  -- `M₀ = ℤ_p[G]² / ℤ_p[G]·(σ - a, τ - b)`, and `1 ↦ (σ - a, τ - b)` is injective.
  have hrel : Function.Exact k rel.toQuotient := by
    rw [LinearMap.exact_iff, Module.Relations.ker_toQuotient, range_tameFrameRelationMap]
  have hcard₁ := hcard ▸ (localRootOfUnityOrder_pos p L h).ne'
  simp only [natCast_def] at hcard₁
  have hk : Function.Injective k := tameFrameRelationMap_injective_of_card_ne_zero
    (isOfFinOrder_of_finite σ) (isOfFinOrder_of_finite τ) hcard₁
  -- So `Y ≃ M₀ ⊕ ℤ_p[G]^N` is the quotient of `ℤ_p[G]^(N + 2) = ℤ_p[G]² ⊕ ℤ_p[G]^N` by the image
  -- of `ℤ_p[G]` under `x ↦ (x·(σ - a, τ - b), 0)`.
  let eP : (Fin (N + 2) → Λ) ≃ₗ[Λ] (rel.G →₀ Λ) × (Fin N → Λ) :=
    LinearEquiv.funCongrLeft Λ Λ (finSumFinEquiv.trans (finCongr (Nat.add_comm 2 N))) ≪≫ₗ
      LinearEquiv.sumArrowLequivProdArrow _ _ Λ Λ ≪≫ₗ
      (Finsupp.linearEquivFunOnFinite Λ Λ (Fin 2)).symm.prodCongr (.refl Λ _)
  let φ : (Fin (N + 2) → Λ) →ₗ[Λ] Y :=
    eY.symm.toLinearMap ∘ₗ rel.toQuotient.prodMap LinearMap.id ∘ₗ eP.toLinearMap
  have hφ : Function.Surjective φ :=
    eY.symm.surjective.comp ((rel.surjective_toQuotient.prodMap Function.surjective_id).comp
      eP.surjective)
  -- `φ` is by definition the composite, and `prodMap f id (y, z) = (f y, z)` holds by `rfl`
  -- (`LinearMap.prodMap_apply`); `LinearMap.comp_apply` cannot be used to unfold `φ`, because the
  -- semiring instances of `rel.Quotient` and `TameFrameModule` agree only up to unfolding.
  have hφ' (y : rel.G →₀ Λ) (z : Fin N → Λ) :
      φ (eP.symm (y, z)) = eY.symm (rel.toQuotient y, z) :=
    congrArg (fun w ↦ eY.symm (rel.toQuotient.prodMap LinearMap.id w)) (eP.apply_symm_apply (y, z))
  have hex : Function.Exact (eP.symm.toLinearMap ∘ₗ LinearMap.inl Λ _ _ ∘ₗ k) φ := by
    intro x
    obtain ⟨⟨y, z⟩, rfl⟩ := eP.symm.surjective x
    rw [hφ', LinearEquiv.map_eq_zero_iff, Prod.mk_eq_zero, hrel y]
    simp only [LinearMap.coe_comp, LinearEquiv.coe_coe, Function.comp_apply, LinearMap.inl_apply,
      Set.mem_range, EmbeddingLike.apply_eq_iff_eq, Prod.mk.injEq]
    constructor
    · rintro ⟨⟨r, rfl⟩, rfl⟩
      exact ⟨r, rfl, rfl⟩
    · rintro ⟨r, rfl, rfl⟩
      exact ⟨⟨r, rfl⟩, rfl⟩
  obtain ⟨β, hβ, ⟨eβ⟩⟩ := exists_relationModule_surjective_of_exact hιπ hι hπ hφ hg
  refine ⟨β, hβ, ⟨eβ ≪≫ₗ .ofEq _ _ (LinearMap.exact_iff.mp hex) ≪≫ₗ
    (LinearEquiv.ofInjective (eP.symm.toLinearMap ∘ₗ LinearMap.inl Λ _ _ ∘ₗ k)
      (eP.symm.injective.comp (LinearMap.inl_injective.comp hk))).symm⟩⟩

end TauCeti
