/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ModularForms.Newforms.OrthogonalBasis
public import TauCeti.Algebra.Algebra.Pi
import TauCeti.LinearAlgebra.End.Adjoin
import TauCeti.LinearAlgebra.Eigenspace.JointEigenvector.Basic

/-!
# Complex characters of the newspace Hecke algebra

The complex algebra generated on the new subspace by the good prime Hecke operators and the
diamond operators has exactly one character for each normalized newform. Its character on
`T_p` is the Fourier coefficient `a_p`, and its character on `⟨u⟩` is the nebentypus value
`χ(u)`. Including the diamonds distinguishes forms with different nebentypus.

`heckeTDiamondCuspNewAlgebraEquiv` identifies this algebra with the product of copies of `ℂ`
indexed by
newforms. Every complex character corresponds to a unique normalized newform.

## References

* [F. Diamond and J. Shurman, *A first course in modular forms*][diamondshurman2005],
  Theorem 5.8.2.
* [G. Shimura, *Introduction to the arithmetic theory of automorphic functions*][shimura1971],
  Chapter 3, for the Hecke algebra and its eigenvalue characters.
-/

public noncomputable section

open Matrix.SpecialLinearGroup UpperHalfPlane CongruenceSubgroup HeckeRing.GL2
open scoped MatrixGroups

namespace TauCeti

variable (N : ℕ) [NeZero N] (k : ℤ)

/-- The restriction of a good prime Hecke operator to the new subspace. -/
def heckeTCuspNewEnd {p : ℕ} (hp : p.Prime) (hpN : Nat.Coprime p N) :
    Module.End ℂ (cuspFormsNew N k) :=
  (@heckeTCuspNat N _ k p ⟨hp.ne_zero⟩).restrict
    (fun _ hf ↦ heckeTCuspNat_mem_cuspFormsNew_of_coprime hp hpN hf)

/-- The restriction of a diamond operator to the new subspace. -/
def diamondOpCuspNewEnd (u : (ZMod N)ˣ) : Module.End ℂ (cuspFormsNew N k) :=
  (diamondOpCusp k u).restrict (fun _ hf ↦ diamondOpCusp_mem_cuspFormsNew u hf)

@[simp]
theorem coe_heckeTCuspNewEnd_apply {p : ℕ} (hp : p.Prime) (hpN : Nat.Coprime p N)
    (f : cuspFormsNew N k) :
    (heckeTCuspNewEnd N k hp hpN f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) =
      @heckeTCuspNat N _ k p ⟨hp.ne_zero⟩ f := (rfl)

@[simp]
theorem coe_diamondOpCuspNewEnd_apply (u : (ZMod N)ˣ) (f : cuspFormsNew N k) :
    (diamondOpCuspNewEnd N k u f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) = diamondOpCusp k u f :=
    (rfl)

/-- The complex Hecke algebra on the new subspace, generated by the good `T_p` and diamonds. -/
def heckeTDiamondCuspNewAlgebra : Subalgebra ℂ (Module.End ℂ (cuspFormsNew N k)) :=
  Algebra.adjoin ℂ
    (Set.range (fun p : {p : ℕ // p.Prime ∧ Nat.Coprime p N} ↦ heckeTCuspNewEnd N k p.2.1 p.2.2) ∪
      Set.range (diamondOpCuspNewEnd N k))

/-- The defining generators of the complex newspace Hecke algebra. -/
theorem heckeTDiamondCuspNewAlgebra_def :
    heckeTDiamondCuspNewAlgebra N k = Algebra.adjoin ℂ
      (Set.range (fun p : {p : ℕ // p.Prime ∧ Nat.Coprime p N} ↦ heckeTCuspNewEnd N k p.2.1 p.2.2) ∪
        Set.range (diamondOpCuspNewEnd N k)) := (rfl)

@[simp]
theorem heckeTCuspNewEnd_mem_heckeTDiamondCuspNewAlgebra {p : ℕ} (hp : p.Prime)
    (hpN : Nat.Coprime p N) :
    heckeTCuspNewEnd N k hp hpN ∈ heckeTDiamondCuspNewAlgebra N k :=
  Algebra.subset_adjoin (Or.inl ⟨⟨p, hp, hpN⟩, rfl⟩)

@[simp]
theorem diamondOpCuspNewEnd_mem_heckeTDiamondCuspNewAlgebra (u : (ZMod N)ˣ) :
    diamondOpCuspNewEnd N k u ∈ heckeTDiamondCuspNewAlgebra N k :=
  Algebra.subset_adjoin (Or.inr ⟨u, rfl⟩)

/-- An algebra contains the newspace Hecke algebra exactly when it contains every good prime
Hecke operator and every diamond operator. -/
theorem heckeTDiamondCuspNewAlgebra_le_iff (A : Subalgebra ℂ (Module.End ℂ (cuspFormsNew N k))) :
    heckeTDiamondCuspNewAlgebra N k ≤ A ↔
      (∀ (p : ℕ) (hp : p.Prime) (hpN : Nat.Coprime p N), heckeTCuspNewEnd N k hp hpN ∈ A) ∧
        ∀ u : (ZMod N)ˣ, diamondOpCuspNewEnd N k u ∈ A := by
  rw [heckeTDiamondCuspNewAlgebra_def, Algebra.adjoin_le_iff, Set.union_subset_iff,
    Set.range_subset_iff, Set.range_subset_iff]
  simp

variable {N k}

/-- A good prime Hecke operator acts on a newform basis vector by its eigenvalue. -/
@[simp]
theorem heckeTCuspNewEnd_basis {p : ℕ} (hp : p.Prime) (hpN : Nat.Coprime p N)
    (f : Newform N k) :
    heckeTCuspNewEnd N k hp hpN (Newform.basis N k f) =
      f.eigenvalue ⟨p, hp.pos⟩ hpN • Newform.basis N k f := by
  apply Subtype.ext
  simpa using f.heckeTCuspNat_eq_eigenvalue_smul hp hpN

/-- A diamond operator acts on a newform basis vector by its nebentypus value. -/
@[simp]
theorem diamondOpCuspNewEnd_basis (u : (ZMod N)ˣ) (f : Newform N k) :
    diamondOpCuspNewEnd N k u (Newform.basis N k f) = (f.χ u : ℂ) • Newform.basis N k f := by
  apply Subtype.ext
  simpa using diamondOpCusp_apply_of_mem_cuspFormCharSpace k f.χ u f.mem_charSpace

private theorem heckeTDiamondCuspNewAlgebra_apply_basis (f : Newform N k)
    (T : heckeTDiamondCuspNewAlgebra N k) :
    T.1 (Newform.basis N k f) =
      (Newform.basis N k).repr (T.1 (Newform.basis N k f)) f • Newform.basis N k f := by
  obtain ⟨c, hc⟩ := exists_smul_eq_of_mem_adjoin (v := Newform.basis N k f) (by
    rintro _ (⟨p, rfl⟩ | ⟨u, rfl⟩)
    · exact ⟨_, heckeTCuspNewEnd_basis p.2.1 p.2.2 f⟩
    · exact ⟨_, diamondOpCuspNewEnd_basis u f⟩) T.2
  simp [hc]

namespace Newform

open HeckeRing.GL2.Newform

variable {N : ℕ} [NeZero N] {k : ℤ}

/-- The complex character of the newspace Hecke algebra associated with a normalized newform. -/
def heckeTDiamondCuspNewCharacter (f : Newform N k) : heckeTDiamondCuspNewAlgebra N k →ₐ[ℂ] ℂ :=
  (heckeTDiamondCuspNewAlgebra N k).val.eigenvalueHomOfJointEigenvector
    (fun T ↦ (basis N k).repr (T.1 (basis N k f)) f) (basis N k f) (Module.Basis.ne_zero _ f)
    (fun T ↦ Module.End.mem_eigenspace_iff.mpr (heckeTDiamondCuspNewAlgebra_apply_basis f T))

/-- The coordinate of an operator's image at its newform basis vector is its character. -/
theorem basis_repr_apply_eq_heckeTDiamondCuspNewCharacter (f : Newform N k)
    (T : heckeTDiamondCuspNewAlgebra N k) :
    (basis N k).repr (T.1 (basis N k f)) f = heckeTDiamondCuspNewCharacter f T := by
  rw [heckeTDiamondCuspNewCharacter, AlgHom.eigenvalueHomOfJointEigenvector_apply]

/-- Every operator in the newspace Hecke algebra acts on a newform by its character. -/
@[simp]
theorem apply_basis_eq_heckeTDiamondCuspNewCharacter_smul (f : Newform N k)
    (T : heckeTDiamondCuspNewAlgebra N k) :
    T.1 (basis N k f) = heckeTDiamondCuspNewCharacter f T • basis N k f := by
  rw [← basis_repr_apply_eq_heckeTDiamondCuspNewCharacter]
  exact heckeTDiamondCuspNewAlgebra_apply_basis f T

/-- The character on a good `T_p` is the good Hecke eigenvalue, hence the Fourier coefficient
`a_p` of the normalized newform. -/
@[simp]
theorem heckeTDiamondCuspNewCharacter_apply_heckeTCuspNewEnd (f : Newform N k) {p : ℕ}
    (hp : p.Prime) (hpN : Nat.Coprime p N) :
    heckeTDiamondCuspNewCharacter f ⟨heckeTCuspNewEnd N k hp hpN,
      heckeTCuspNewEnd_mem_heckeTDiamondCuspNewAlgebra N k hp hpN⟩ =
      f.eigenvalue ⟨p, hp.pos⟩ hpN := by
  apply smul_left_injective ℂ (Module.Basis.ne_zero (basis N k) f)
  exact (apply_basis_eq_heckeTDiamondCuspNewCharacter_smul f _).symm.trans
    (heckeTCuspNewEnd_basis hp hpN f)

/-- The character on a diamond operator is the nebentypus value. -/
@[simp]
theorem heckeTDiamondCuspNewCharacter_apply_diamondOpCuspNewEnd (f : Newform N k) (u : (ZMod N)ˣ) :
    heckeTDiamondCuspNewCharacter f ⟨diamondOpCuspNewEnd N k u,
      diamondOpCuspNewEnd_mem_heckeTDiamondCuspNewAlgebra N k u⟩ = (f.χ u : ℂ) := by
  apply smul_left_injective ℂ (Module.Basis.ne_zero (basis N k) f)
  exact (apply_basis_eq_heckeTDiamondCuspNewCharacter_smul f _).symm.trans
    (diamondOpCuspNewEnd_basis u f)

/-- Distinct newforms give distinct characters of the newspace Hecke algebra. The diamond
values determine the nebentypus, and the good prime values then determine the newform. -/
theorem heckeTDiamondCuspNewCharacter_injective :
    Function.Injective (heckeTDiamondCuspNewCharacter (N := N) (k := k)) := by
  intro f g h
  have hχ : f.χ = g.χ := by
    ext u
    simpa only [heckeTDiamondCuspNewCharacter_apply_diamondOpCuspNewEnd] using DFunLike.congr_fun h
      ⟨diamondOpCuspNewEnd N k u, diamondOpCuspNewEnd_mem_heckeTDiamondCuspNewAlgebra N k u⟩
  apply eq_of_forall_prime_eigenvalue_eq hχ
  intro p hp hpN
  simpa only [heckeTDiamondCuspNewCharacter_apply_heckeTCuspNewEnd] using DFunLike.congr_fun h
    ⟨heckeTCuspNewEnd N k hp hpN, heckeTCuspNewEnd_mem_heckeTDiamondCuspNewAlgebra N k hp hpN⟩

/-- Evaluation on the newform basis identifies the complex newspace Hecke algebra with the
product of copies of `ℂ` indexed by normalized newforms. In particular it is a split semisimple
commutative algebra. -/
def heckeTDiamondCuspNewAlgebraEquiv :
    heckeTDiamondCuspNewAlgebra N k ≃ₐ[ℂ] (Newform N k → ℂ) := by
  letI : Module.Finite ℂ (cuspFormsNew N k) := Module.Finite.of_basis (basis N k)
  letI : Module.Finite ℂ (heckeTDiamondCuspNewAlgebra N k) :=
    Module.Finite.of_injective (heckeTDiamondCuspNewAlgebra N k).val.toLinearMap
      Subtype.val_injective
  have hinj : Function.Injective
      (AlgHom.pi (heckeTDiamondCuspNewCharacter (N := N) (k := k))) := by
    intro T S h
    apply Subtype.ext
    apply (basis N k).ext
    intro f
    rw [apply_basis_eq_heckeTDiamondCuspNewCharacter_smul f T,
      apply_basis_eq_heckeTDiamondCuspNewCharacter_smul f S]
    exact congrArg (· • basis N k f) (congrFun h f)
  exact AlgEquiv.ofBijective
    (AlgHom.pi (heckeTDiamondCuspNewCharacter (N := N) (k := k)))
    (AlgHom.pi_bijective_of_injective (K := ℂ) (A := heckeTDiamondCuspNewAlgebra N k)
      (ι := Newform N k) (heckeTDiamondCuspNewCharacter (N := N) (k := k))
      (heckeTDiamondCuspNewCharacter_injective (N := N) (k := k)) hinj)

@[simp]
theorem heckeTDiamondCuspNewAlgebraEquiv_apply (T : heckeTDiamondCuspNewAlgebra N k)
    (f : Newform N k) :
    heckeTDiamondCuspNewAlgebraEquiv T f = heckeTDiamondCuspNewCharacter f T := (rfl)

/-- Every complex character of the newspace Hecke algebra belongs to a normalized newform. -/
theorem heckeTDiamondCuspNewCharacter_surjective :
    Function.Surjective (heckeTDiamondCuspNewCharacter (N := N) (k := k)) := by
  intro ψ
  obtain ⟨f, hf⟩ := (ψ.comp heckeTDiamondCuspNewAlgebraEquiv.symm.toAlgHom).eq_piEvalAlgHom
  exact ⟨f, AlgHom.ext fun T ↦ by
    simpa using (congrArg (fun φ ↦ φ (heckeTDiamondCuspNewAlgebraEquiv T)) hf).symm⟩

/-- The normalized newforms are in bijection with the complex characters of the newspace
Hecke algebra. -/
def heckeTDiamondCuspNewCharacterEquiv : Newform N k ≃ (heckeTDiamondCuspNewAlgebra N k →ₐ[ℂ] ℂ) :=
  Equiv.ofBijective heckeTDiamondCuspNewCharacter ⟨heckeTDiamondCuspNewCharacter_injective,
    heckeTDiamondCuspNewCharacter_surjective⟩

@[simp]
theorem heckeTDiamondCuspNewCharacterEquiv_apply (f : Newform N k) :
    heckeTDiamondCuspNewCharacterEquiv f = heckeTDiamondCuspNewCharacter f := (rfl)

end Newform

/-- The newspace Hecke algebra is commutative, with its existing operator ring structure. -/
instance instCommRingHeckeTDiamondCuspNewAlgebra {N : ℕ} [NeZero N] {k : ℤ} :
    CommRing (heckeTDiamondCuspNewAlgebra N k) where
  __ := (heckeTDiamondCuspNewAlgebra N k).toRing
  mul_comm a b := by
    apply TauCeti.Newform.heckeTDiamondCuspNewAlgebraEquiv.injective
    simp only [map_mul, mul_comm]

end TauCeti
