/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
public import TauCeti.NumberTheory.LocalField.FiniteExtension.IntermediateField
public import TauCeti.NumberTheory.LocalField.Frobenius
public import TauCeti.NumberTheory.LocalField.Unramified.Criterion
import TauCeti.RingTheory.RootsOfUnity.Adjoin

/-!
# Existence and uniqueness of unramified extensions

Let `K` be a nonarchimedean local field with residue field of cardinality `q`, and let `Ω` be an
extension of `K`. For `f ≥ 1` this file defines

`TauCeti.unramifiedExtension K Ω f`,

the intermediate field of `Ω / K` generated by the roots of `X^{q^f} − X`, equivalently by the
`(q^f − 1)`-st roots of unity of `Ω`. It is finite and Galois over `K`. When `Ω` contains a
primitive `(q^f − 1)`-st root of unity `ζ`, for instance when `Ω` is separably closed, it is
`K(ζ)`, the splitting field of `X^{q^f} − X`, and it is unramified of degree `f` over `K`.

Every unramified intermediate field `E` of `Ω / K` is `unramifiedExtension K Ω [E : K]`, for an
arbitrary extension `Ω`. So when `Ω` is separably closed, such as `AlgebraicClosure K`,
`unramifiedExtension K Ω f` is the only unramified intermediate field of `Ω / K` of degree `f`.
These are the finite levels of the maximal unramified extension of `K`.

The local-field structure carried by an intermediate field is not unique as data, but any two
structures compatible with `K` agree (`TauCeti.finiteExtensionValuativeRel_eq`). The theorems
below are therefore stated for an arbitrary compatible structure, and
`TauCeti.existsUnique_isUnramified_finrank_eq` packages the statement for the canonical structure
of `TauCeti.finiteIntermediateFieldValuativeRel`.

## Main definitions

* `TauCeti.unramifiedExtension K Ω f`: the intermediate field generated by the roots of
  `X^{q^f} − X` in `Ω`.

## Main results

* `TauCeti.unramifiedExtension_eq_adjoin_setOf_pow_eq_one`: for `f ≠ 0` it is generated by the
  `(q^f − 1)`-st roots of unity of `Ω`.
* `TauCeti.unramifiedExtension_eq_adjoin_simple`: it is `K(ζ)` for any primitive
  `(q^f − 1)`-st root of unity `ζ` of `Ω`.
* `TauCeti.unramifiedExtension_le_of_dvd`: it contains the unramified extension of degree `d`
  for every `d ∣ f`, when `f ≠ 0`.
* `TauCeti.map_unramifiedExtension_le`: an embedding carries an unramified extension into the
  unramified extension of the same degree in the target.
* `TauCeti.unramifiedExtension_le_restrictScalars_unramifiedExtension`: for an extension `L/K` of
  nonarchimedean local fields inside `Ω`, it lies in the unramified extension of `L` of degree `f`.
* `TauCeti.isGalois_unramifiedExtension`: it is Galois over `K`.
* `TauCeti.isUnramified_unramifiedExtension_of_isPrimitiveRoot`,
  `TauCeti.isUnramified_unramifiedExtension`: it is unramified over `K`.
* `TauCeti.finrank_unramifiedExtension_of_isPrimitiveRoot`,
  `TauCeti.finrank_unramifiedExtension`: it has degree `f` over `K`.
* `IntermediateField.eq_unramifiedExtension_finrank`: every unramified intermediate field `E` of
  `Ω / K` is `unramifiedExtension K Ω [E : K]`.
* `TauCeti.existsUnique_isUnramified_finrank_eq`: for `f ≥ 1`, there is exactly one unramified
  intermediate field of `Ω / K` of degree `f`.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter III, §5.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §7.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing Polynomial IntermediateField

namespace TauCeti

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] (Ω : Type*) [Field Ω] [Algebra K Ω]

/-- **The unramified extension of degree `f`** of a nonarchimedean local field `K` inside an
extension `Ω`: the intermediate field generated by the roots of `X^{q^f} − X`, where `q` is the
cardinality of the residue field of `K`. When `Ω` is separably closed and `f ≥ 1` it is the
unique unramified intermediate field of `Ω / K` of degree `f`. -/
def unramifiedExtension (f : ℕ) : IntermediateField K Ω :=
  adjoin K ((X ^ Nat.card 𝓀[K] ^ f - X : K[X]).rootSet Ω)

/-- The unramified extension of degree `f` is the intermediate field generated by the roots of
`X^{q^f} − X`. -/
theorem unramifiedExtension_def (f : ℕ) :
    unramifiedExtension K Ω f = adjoin K ((X ^ Nat.card 𝓀[K] ^ f - X : K[X]).rootSet Ω) :=
  -- `(rfl)`, not `rfl`: keep the body opaque while exporting this equation across modules.
  (rfl)

/-- Every root of `X^{q^f} − X` in `Ω` lies in the unramified extension of degree `f`. -/
@[simp]
theorem rootSet_subset_unramifiedExtension (f : ℕ) :
    (X ^ Nat.card 𝓀[K] ^ f - X : K[X]).rootSet Ω ⊆ unramifiedExtension K Ω f :=
  subset_adjoin _ _

variable {K Ω} in
/-- The unramified extension of degree `f` is the least intermediate field of `Ω / K` containing
the roots of `X^{q^f} − X`. -/
@[simp]
theorem unramifiedExtension_le_iff {f : ℕ} {E : IntermediateField K Ω} :
    unramifiedExtension K Ω f ≤ E ↔ (X ^ Nat.card 𝓀[K] ^ f - X : K[X]).rootSet Ω ⊆ E :=
  adjoin_le_iff

/-- The unramified extension of degree `0` is `K`: the polynomial `X^{q^0} − X` is zero. -/
@[simp]
theorem unramifiedExtension_zero : unramifiedExtension K Ω 0 = ⊥ := by
  simp [unramifiedExtension]

variable {K Ω} in
/-- The unramified extension of degree `f` lies in that of degree `g` when `f ∣ g` and `g ≠ 0`:
a root of `X^{q^f} − X` is a root of `X^{q^g} − X`. -/
theorem unramifiedExtension_le_of_dvd {f g : ℕ} (hg : g ≠ 0) (h : f ∣ g) :
    unramifiedExtension K Ω f ≤ unramifiedExtension K Ω g := by
  obtain ⟨k, rfl⟩ := h
  refine unramifiedExtension_le_iff.2 fun x hx ↦ rootSet_subset_unramifiedExtension K Ω _ ?_
  rw [Polynomial.mem_rootSet, map_sub, map_pow, aeval_X, sub_eq_zero] at hx ⊢
  refine ⟨FiniteField.X_pow_card_pow_sub_X_ne_zero _ hg Finite.one_lt_card, ?_⟩
  -- `x` is fixed by `y ↦ y ^ (q ^ f)`, hence by its `k`-th iterate `y ↦ y ^ (q ^ (f * k))`.
  have hfix : Function.IsFixedPt (· ^ Nat.card 𝓀[K] ^ f) x := hx.2
  have h := hfix.iterate k
  rwa [pow_iterate, Function.IsFixedPt, ← pow_mul] at h

variable {K Ω} in
/-- An embedding of extensions of `K` carries the unramified extension of degree `f` into the
unramified extension of degree `f` in the target. Equality need not hold, since the target may
contain roots of `X ^ q ^ f - X` that are absent from the source. -/
theorem map_unramifiedExtension_le {E : Type*} [Field E] [Algebra K E] (f : ℕ)
    (ι : Ω →ₐ[K] E) :
    (unramifiedExtension K Ω f).map ι ≤ unramifiedExtension K E f := by
  rw [unramifiedExtension_def, unramifiedExtension_def, adjoin_map, adjoin_le_iff]
  rintro _ ⟨x, hx, rfl⟩
  exact subset_adjoin K _ (Polynomial.rootSet_mapsTo ι hx)

variable {K Ω} in
/-- **Unramified extensions grow with the ground field.** For an extension `L/K` of
nonarchimedean local fields inside `Ω`, the unramified extension of degree `f` of `K` lies in that
of `L`: a root of `X^{q^f} − X` is a root of `X^{q'^f} − X`, where `q' = q^{f(L/K)}` is the
cardinality of the residue field of `L`. -/
theorem unramifiedExtension_le_restrictScalars_unramifiedExtension (L : Type*) [Field L]
    [ValuativeRel L] [TopologicalSpace L] [IsNonarchimedeanLocalField L] [Algebra K L]
    [ValuativeExtension K L] [Algebra L Ω] [IsScalarTower K L Ω] (f : ℕ) :
    unramifiedExtension K Ω f ≤ (unramifiedExtension L Ω f).restrictScalars K := by
  rcases eq_or_ne f 0 with rfl | hf
  · simp
  refine unramifiedExtension_le_iff.2 fun x hx ↦ rootSet_subset_unramifiedExtension L Ω f ?_
  rw [Polynomial.mem_rootSet, map_sub, map_pow, aeval_X, sub_eq_zero] at hx ⊢
  refine ⟨FiniteField.X_pow_card_pow_sub_X_ne_zero _ hf Finite.one_lt_card, ?_⟩
  -- `x` is fixed by `y ↦ y ^ (q ^ f)`, hence by its `f(L/K)`-th iterate `y ↦ y ^ (q' ^ f)`.
  have hfix : Function.IsFixedPt (· ^ Nat.card 𝓀[K] ^ f) x := hx.2
  have h := hfix.iterate (inertiaDegree K L)
  rwa [pow_iterate, Function.IsFixedPt, ← pow_mul, mul_comm f, pow_mul,
    ← natCard_residueField] at h

variable {K Ω} in
/-- **The unramified extension of degree `f` is generated by the `(q^f − 1)`-st roots of unity**
of `Ω`, for `f ≠ 0`. -/
theorem unramifiedExtension_eq_adjoin_setOf_pow_eq_one {f : ℕ} (hf : f ≠ 0) :
    unramifiedExtension K Ω f = adjoin K {x : Ω | x ^ (Nat.card 𝓀[K] ^ f - 1) = 1} := by
  have hq : 1 < Nat.card 𝓀[K] ^ f := Nat.one_lt_pow hf Finite.one_lt_card
  have hsucc : Nat.card 𝓀[K] ^ f = (Nat.card 𝓀[K] ^ f - 1) + 1 := by omega
  -- The roots of `X^{q^f} − X` are `0` and the `(q^f − 1)`-st roots of unity.
  refine le_antisymm (adjoin_le_iff.2 fun x hx ↦ ?_)
    (adjoin_le_iff.2 fun x (hx : x ^ _ = 1) ↦ subset_adjoin _ _ ?_)
  · rw [Polynomial.mem_rootSet, map_sub, map_pow, aeval_X, sub_eq_zero] at hx
    rcases eq_or_ne x 0 with rfl | hx0
    · exact zero_mem _
    refine subset_adjoin _ _ (?_ : x ^ _ = 1)
    have h := hx.2
    rw [hsucc, pow_succ] at h
    exact mul_right_cancel₀ hx0 (by rw [one_mul, h])
  · refine Polynomial.mem_rootSet.2
      ⟨FiniteField.X_pow_card_pow_sub_X_ne_zero _ hf Finite.one_lt_card, ?_⟩
    rw [map_sub, map_pow, aeval_X, hsucc, pow_succ, hx, one_mul, sub_self]

variable {K Ω} in
/-- **The unramified extension of degree `f` is generated by a primitive `(q^f − 1)`-st root of
unity.** -/
theorem unramifiedExtension_eq_adjoin_simple {f : ℕ} (hf : f ≠ 0) {ζ : Ω}
    (hζ : IsPrimitiveRoot ζ (Nat.card 𝓀[K] ^ f - 1)) :
    unramifiedExtension K Ω f = K⟮ζ⟯ := by
  have : NeZero (Nat.card 𝓀[K] ^ f - 1) :=
    ⟨Nat.sub_ne_zero_of_lt (Nat.one_lt_pow hf Finite.one_lt_card)⟩
  rw [unramifiedExtension_eq_adjoin_setOf_pow_eq_one hf]
  exact le_antisymm (adjoin_le_iff.2 fun x hx ↦ hζ.mem_adjoin_of_pow_eq_one hx)
    (adjoin_simple_le_iff.2 (subset_adjoin _ _ hζ.pow_eq_one))

variable {K} in
/-- A separably closed extension of `K` contains a primitive `(q^f − 1)`-st root of unity, for
`f ≠ 0`. -/
theorem exists_isPrimitiveRoot_natCard_pow_sub_one [IsSepClosed Ω] {f : ℕ} (hf : f ≠ 0) :
    ∃ ζ : Ω, IsPrimitiveRoot ζ (Nat.card 𝓀[K] ^ f - 1) := by
  have h := ((isUnit_natCast_natCard_pow_sub_one K hf).map (algebraMap 𝒪[K] K)).map
    (algebraMap K Ω)
  rw [map_natCast, map_natCast] at h
  have : NeZero ((Nat.card 𝓀[K] ^ f - 1 : ℕ) : Ω) := ⟨h.ne_zero⟩
  exact HasEnoughRootsOfUnity.exists_primitiveRoot Ω _

/-- The unramified extension of degree `f` is a finite extension of `K`. -/
instance finiteDimensional_unramifiedExtension (f : ℕ) :
    FiniteDimensional K (unramifiedExtension K Ω f) :=
  finiteDimensional_adjoin fun _ hx ↦ (isAlgebraic_of_mem_rootSet hx).isIntegral

/-- The unramified extension of degree `f` is Galois over `K`, for any extension `Ω` of `K`. For
`f = 0` it is `K` itself. -/
instance isGalois_unramifiedExtension (f : ℕ) : IsGalois K (unramifiedExtension K Ω f) := by
  rcases eq_or_ne f 0 with rfl | hf
  · rw [unramifiedExtension_zero]
    infer_instance
  -- The `(q^f − 1)`-st roots of unity of `Ω` form a cyclic group, of some order `d`; they are
  -- the `d`-th roots of unity of `Ω`, among which there is a primitive one, so the extension
  -- they generate is cyclotomic.
  set n := Nat.card 𝓀[K] ^ f - 1
  have : NeZero n := ⟨Nat.sub_ne_zero_of_lt (Nat.one_lt_pow hf Finite.one_lt_card)⟩
  obtain ⟨g, hg⟩ := IsCyclic.exists_ofOrder_eq_natCard (α := rootsOfUnity n Ω)
  set d := Nat.card (rootsOfUnity n Ω)
  have hζ : IsPrimitiveRoot ((g : Ωˣ) : Ω) d :=
    IsPrimitiveRoot.coe_units_iff.2 (IsPrimitiveRoot.coe_submonoidClass_iff.2 (hg ▸ .orderOf g))
  have hζn : ((g : Ωˣ) : Ω) ^ n = 1 := by
    rw [← Units.val_pow_eq_pow_val, (mem_rootsOfUnity n (g : Ωˣ)).1 g.2, Units.val_one]
  have hset : {x : Ω | x ^ n = 1} = {x | ∃ m ∈ ({d} : Set ℕ), m ≠ 0 ∧ x ^ m = 1} := by
    ext x
    simp only [Set.mem_ofPred_eq, Set.mem_singleton_iff, exists_eq_left]
    refine ⟨fun hx ↦ ⟨Nat.card_pos.ne', ?_⟩, fun ⟨_, hx⟩ ↦ ?_⟩
    · have h := congrArg (fun u : rootsOfUnity n Ω ↦ ((u : Ωˣ) : Ω))
        (pow_card_eq_one' (x := rootsOfUnity.mkOfPowEq x hx))
      rwa [SubgroupClass.coe_pow, Units.val_pow_eq_pow_val, rootsOfUnity.coe_mkOfPowEq,
        OneMemClass.coe_one, Units.val_one] at h
    · obtain ⟨k, hk⟩ := hζ.dvd_of_pow_eq_one n hζn
      rw [hk, pow_mul, hx, one_pow]
  rw [unramifiedExtension_eq_adjoin_setOf_pow_eq_one hf, hset]
  have := isCyclotomicExtension_adjoin_of_exists_isPrimitiveRoot {d} K Ω
    (by rintro m rfl -; exact ⟨_, hζ⟩)
  exact IsCyclotomicExtension.isGalois {d} K _

variable {K Ω} in
/-- **The unramified extension of degree `f` is unramified** when `Ω` contains a primitive
`(q^f − 1)`-st root of unity. This holds for any structure of nonarchimedean local field on it
compatible with `K`. -/
theorem isUnramified_unramifiedExtension_of_isPrimitiveRoot {f : ℕ} (hf : f ≠ 0) {ζ : Ω}
    (hζ : IsPrimitiveRoot ζ (Nat.card 𝓀[K] ^ f - 1))
    [ValuativeRel (unramifiedExtension K Ω f)] [TopologicalSpace (unramifiedExtension K Ω f)]
    [IsNonarchimedeanLocalField (unramifiedExtension K Ω f)]
    [ValuativeExtension K (unramifiedExtension K Ω f)] :
    IsUnramified K (unramifiedExtension K Ω f) := by
  have hL := unramifiedExtension_eq_adjoin_simple hf hζ
  have hn0 : Nat.card 𝓀[K] ^ f - 1 ≠ 0 :=
    Nat.sub_ne_zero_of_lt (Nat.one_lt_pow hf Finite.one_lt_card)
  let ζL : unramifiedExtension K Ω f := ⟨ζ, hL ▸ mem_adjoin_simple_self K ζ⟩
  have hζL : ζL ^ (Nat.card 𝓀[K] ^ f - 1) = 1 := Subtype.ext (by simpa [ζL] using hζ.pow_eq_one)
  -- `ζ` is a root of unity, so it lies in the valuation ring.
  let b : 𝒪[unramifiedExtension K Ω f] := ⟨ζL, (Valuation.mem_integer_iff _ _).2
    ((pow_le_one_iff_of_nonneg zero_le hn0).1 (by rw [← map_pow, hζL, map_one]))⟩
  have hb : b ^ (Nat.card 𝓀[K] ^ f - 1) = 1 := Subtype.ext (by simpa [b] using hζL)
  refine isUnramified_of_adjoin_eq_top_of_isUnit_aeval_derivative (b := b)
    (p := X ^ (Nat.card 𝓀[K] ^ f - 1) - 1) ?_ ?_ ?_
  · -- `ζ` generates the intermediate field `K(ζ)` over `K`.
    exact map_injective _ ((lift_adjoin_simple K _ ζL).trans
      (hL.symm.trans (lift_top K _).symm))
  · rw [map_sub, map_pow, aeval_X, map_one, hb, sub_self]
  · -- The derivative `(q^f − 1) ζ^{q^f − 2}` is a unit, since `q^f − 1` is prime to `p`.
    rw [derivative_sub, derivative_X_pow, derivative_one, sub_zero, map_mul, aeval_C,
      map_natCast, map_pow, aeval_X]
    refine .mul ?_ ((IsUnit.of_pow_eq_one hb hn0).pow _)
    simpa using (isUnit_natCast_natCard_pow_sub_one K hf).map
      (algebraMap 𝒪[K] 𝒪[unramifiedExtension K Ω f])

variable {K Ω} in
/-- **The unramified extension of degree `f` has degree `f`** when `Ω` contains a primitive
`(q^f − 1)`-st root of unity. -/
theorem finrank_unramifiedExtension_of_isPrimitiveRoot {f : ℕ} (hf : f ≠ 0) {ζ : Ω}
    (hζ : IsPrimitiveRoot ζ (Nat.card 𝓀[K] ^ f - 1)) :
    Module.finrank K (unramifiedExtension K Ω f) = f := by
  have hL := unramifiedExtension_eq_adjoin_simple hf hζ
  have hq : 1 < Nat.card 𝓀[K] := Finite.one_lt_card
  have hn0 : Nat.card 𝓀[K] ^ f - 1 ≠ 0 := Nat.sub_ne_zero_of_lt (Nat.one_lt_pow hf hq)
  let L := unramifiedExtension K Ω f
  let _ := finiteIntermediateFieldValuativeRel K Ω L
  let _ := finiteIntermediateFieldTopology K Ω L
  have := finiteIntermediateField_isNonarchimedeanLocalField K Ω L
  have := finiteIntermediateField_valuativeExtension K Ω L
  have : IsUnramified K L := isUnramified_unramifiedExtension_of_isPrimitiveRoot hf hζ
  -- The degree is the order of the arithmetic Frobenius `σ`. It raises `ζ` to the `q`-th power,
  -- so its order is the least `d ≥ 1` with `q^f − 1 ∣ q^d − 1`, which is `f`.
  rw [← IsUnramified.inertiaDegree_eq_finrank, ← orderOf_frobeniusAlgEquiv]
  set σ := frobeniusAlgEquiv (K := K) (L := L)
  let ζL : L := ⟨ζ, hL.ge (mem_adjoin_simple_self K ζ)⟩
  have hζL : IsPrimitiveRoot ζL (Nat.card 𝓀[K] ^ f - 1) :=
    hζ.of_map_of_injective (f := L.val) L.val.injective
  -- Frobenius acts on `ζ` as the `q`-th power map.
  have hnL : IsUnit ((Nat.card 𝓀[K] ^ f - 1 : ℕ) : 𝒪[L]) := by
    simpa using (isUnit_natCast_natCard_pow_sub_one K hf).map (algebraMap 𝒪[K] 𝒪[L])
  have hσ (m : ℕ) : (σ ^ m) ζL = ζL ^ Nat.card 𝓀[K] ^ m := by
    induction m with
    | zero => simp
    | succ m ih =>
      rw [pow_succ', AlgEquiv.mul_apply, ih, map_pow,
        frobeniusAlgEquiv_apply_of_pow_eq_one hnL hζL.pow_eq_one, ← pow_mul, pow_succ']
  refine le_antisymm (orderOf_le_of_pow_eq_one (Nat.pos_of_ne_zero hf) ?_) ?_
  · -- `σ ^ f` fixes the generator `ζ`, since `ζ ^ (q ^ f) = ζ`.
    refine AlgEquiv.coe_toAlgHom_injective (algHom_ext_of_eq_adjoin K hL fun x hx ↦ ?_)
    rw [Set.mem_singleton_iff] at hx
    subst hx
    have h : ζL ^ Nat.card 𝓀[K] ^ f = ζL := by
      rw [← Nat.sub_add_cancel (Nat.one_le_pow _ _ Nat.card_pos), pow_succ, hζL.pow_eq_one,
        one_mul]
    simpa [ζL] using (hσ f).trans h
  · -- `σ ^ d = 1` for the order `d` of `σ`, so `q ^ f − 1 ∣ q ^ d − 1` and `f ≤ d`.
    have hd := orderOf_pos σ
    have h1 := hσ (orderOf σ)
    rw [pow_orderOf_eq_one, AlgEquiv.one_apply] at h1
    have hdvd := hζL.dvd_of_pow_eq_one (Nat.card 𝓀[K] ^ orderOf σ - 1) (by
      rw [pow_sub₀ _ (hζL.ne_zero hn0) (Nat.one_le_pow _ _ Nat.card_pos), pow_one, ← h1,
        mul_inv_cancel₀ (hζL.ne_zero hn0)])
    have hlt : 1 < Nat.card 𝓀[K] ^ orderOf σ := Nat.one_lt_pow hd.ne' hq
    have hle : Nat.card 𝓀[K] ^ f - 1 ≤ Nat.card 𝓀[K] ^ orderOf σ - 1 :=
      Nat.le_of_dvd (by omega) hdvd
    exact (Nat.pow_le_pow_iff_right hq).1 (by omega)

variable {K Ω} in
/-- **Uniqueness of unramified extensions.** Every unramified intermediate field `E` of `Ω / K`
is the unramified extension of degree `[E : K]`, the splitting field of `X^{q^{[E : K]}} − X`.
This holds for any extension `Ω` of `K` and any structure of nonarchimedean local field on `E`
compatible with `K`. -/
theorem _root_.IntermediateField.eq_unramifiedExtension_finrank (E : IntermediateField K Ω)
    [ValuativeRel E] [TopologicalSpace E] [IsNonarchimedeanLocalField E] [ValuativeExtension K E]
    [IsUnramified K E] : E = unramifiedExtension K Ω (Module.finrank K E) := by
  have := finite_of_valuativeExtension K E
  have hf : Module.finrank K E ≠ 0 := Module.finrank_pos.ne'
  -- The residue field of `E` has `q ^ [E : K]` elements.
  have hcard : Nat.card 𝓀[E] = Nat.card 𝓀[K] ^ Module.finrank K E := by
    rw [natCard_residueField K E, IsUnramified.inertiaDegree_eq_finrank]
  -- So `E` contains a primitive `(q ^ [E : K] − 1)`-st root of unity; hence it contains the
  -- unramified extension of degree `[E : K]`, which has the same degree.
  obtain ⟨η, hη⟩ := exists_isPrimitiveRoot_natCard_residueField_sub_one E
  rw [hcard] at hη
  have hηΩ := hη.map_of_injective (f := E.val) E.val.injective
  refine (eq_of_le_of_finrank_eq ?_ (finrank_unramifiedExtension_of_isPrimitiveRoot hf hηΩ)).symm
  rw [unramifiedExtension_eq_adjoin_simple hf hηΩ, adjoin_simple_le_iff]
  exact η.2

section IsSepClosed

variable [IsSepClosed Ω]

/-- The unramified extension of degree `f` is a splitting field of `X^{q^f} − X` over `K`. -/
instance isSplittingField_unramifiedExtension (f : ℕ) :
    IsSplittingField K (unramifiedExtension K Ω f) (X ^ Nat.card 𝓀[K] ^ f - X) := by
  refine adjoin_rootSet_isSplittingField ?_
  rcases eq_or_ne f 0 with rfl | hf
  · simp
  -- `X^{q^f} − X = (X^{q^f − 1} − 1) X`, and `Ω` contains a primitive `(q^f − 1)`-st root of unity.
  obtain ⟨ζ, hζ⟩ := exists_isPrimitiveRoot_natCard_pow_sub_one (K := K) Ω hf
  have hsucc : Nat.card 𝓀[K] ^ f = (Nat.card 𝓀[K] ^ f - 1) + 1 := by
    have := Nat.one_lt_pow hf (Finite.one_lt_card (α := 𝓀[K]))
    omega
  rw [Polynomial.map_sub, Polynomial.map_pow, map_X, hsucc, pow_succ, ← sub_one_mul]
  exact (C_1 (R := Ω) ▸ X_pow_sub_one_splits hζ).mul Splits.X

variable {K Ω} in
/-- **The unramified extension of degree `f` is unramified.** This holds for any structure of
nonarchimedean local field on it compatible with `K`. -/
theorem isUnramified_unramifiedExtension {f : ℕ} (hf : f ≠ 0)
    [ValuativeRel (unramifiedExtension K Ω f)] [TopologicalSpace (unramifiedExtension K Ω f)]
    [IsNonarchimedeanLocalField (unramifiedExtension K Ω f)]
    [ValuativeExtension K (unramifiedExtension K Ω f)] :
    IsUnramified K (unramifiedExtension K Ω f) :=
  isUnramified_unramifiedExtension_of_isPrimitiveRoot hf
    (exists_isPrimitiveRoot_natCard_pow_sub_one (K := K) Ω hf).choose_spec

variable {K Ω} in
/-- **The unramified extension of degree `f` has degree `f`.** -/
@[simp]
theorem finrank_unramifiedExtension {f : ℕ} (hf : f ≠ 0) :
    Module.finrank K (unramifiedExtension K Ω f) = f :=
  finrank_unramifiedExtension_of_isPrimitiveRoot hf
    (exists_isPrimitiveRoot_natCard_pow_sub_one (K := K) Ω hf).choose_spec

/-- **Existence and uniqueness of unramified extensions.** For `f ≥ 1` there is exactly one
intermediate field of `Ω / K` which is unramified of degree `f` over `K`, for its canonical
structure of nonarchimedean local field; it is `TauCeti.unramifiedExtension K Ω f`. -/
theorem existsUnique_isUnramified_finrank_eq {f : ℕ} (hf : f ≠ 0) :
    ∃! E : IntermediateField K Ω, ∃ _ : FiniteDimensional K E,
      letI := finiteIntermediateFieldValuativeRel K Ω E
      letI := finiteIntermediateFieldTopology K Ω E
      haveI := finiteIntermediateField_isNonarchimedeanLocalField K Ω E
      haveI := finiteIntermediateField_valuativeExtension K Ω E
      IsUnramified K E ∧ Module.finrank K E = f := by
  refine ⟨unramifiedExtension K Ω f, ⟨inferInstance, ?_, finrank_unramifiedExtension hf⟩, ?_⟩
  · let _ := finiteIntermediateFieldValuativeRel K Ω (unramifiedExtension K Ω f)
    let _ := finiteIntermediateFieldTopology K Ω (unramifiedExtension K Ω f)
    have := finiteIntermediateField_isNonarchimedeanLocalField K Ω (unramifiedExtension K Ω f)
    have := finiteIntermediateField_valuativeExtension K Ω (unramifiedExtension K Ω f)
    exact isUnramified_unramifiedExtension hf
  rintro E ⟨_, hE, rfl⟩
  let _ := finiteIntermediateFieldValuativeRel K Ω E
  let _ := finiteIntermediateFieldTopology K Ω E
  have := finiteIntermediateField_isNonarchimedeanLocalField K Ω E
  have := finiteIntermediateField_valuativeExtension K Ω E
  exact E.eq_unramifiedExtension_finrank

end IsSepClosed

end TauCeti
