/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Unramified.Existence

/-!
# The maximal unramified subextension of a finite extension of local fields

Let `L/K` be a finite extension of nonarchimedean local fields with compatible valuations, with
`q = #𝓀[K]`, `e = e(L/K)` and `f = f(L/K)`. The residue field of `L` has `q^f` elements, so `L`
contains a primitive `(q^f − 1)`-st root of unity, and the intermediate field
`L₀ = TauCeti.unramifiedExtension K L f` generated by the roots of `X^{q^f} − X` is unramified of
degree `f` over `K`. It is the **maximal unramified subextension** of `L/K`: every unramified
intermediate field lies in it, and `L/L₀` is totally ramified of degree `e`. This factors an
arbitrary finite extension `L/K` as a totally ramified extension of an unramified one, which is
how results about totally ramified extensions, such as the Eisenstein description of the ring of
integers, extend to all finite extensions.

The statements about an intermediate field `E` of `L/K` hold for any structure of nonarchimedean
local field on `E` compatible with `K`; `L` is then a valuative extension of `E` by the instance
`IntermediateField.valuativeExtension_of_isNonarchimedeanLocalField`.

## Main results

* `TauCeti.exists_isPrimitiveRoot_natCard_pow_inertiaDegree_sub_one`: `L` contains a primitive
  `(q^f − 1)`-st root of unity.
* `TauCeti.finrank_unramifiedExtension_inertiaDegree` and
  `TauCeti.isUnramified_unramifiedExtension_inertiaDegree`: `L₀/K` is unramified of degree `f`.
* `TauCeti.le_unramifiedExtension_inertiaDegree_of_isUnramified`: every unramified intermediate
  field of `L/K` lies in `L₀`.
* `TauCeti.eq_unramifiedExtension_inertiaDegree_iff`: `L₀` is the unique intermediate field
  which is unramified over `K` and over which `L` is totally ramified.
* `TauCeti.IsUnramified.unramifiedExtension_inertiaDegree_eq_top`: `L₀ = L` when `L/K` is
  unramified.
* `TauCeti.isTotallyRamified_unramifiedExtension_inertiaDegree`,
  `TauCeti.ramificationIndex_unramifiedExtension_inertiaDegree` and
  `TauCeti.finrank_unramifiedExtension_inertiaDegree_eq_ramificationIndex`: `L/L₀` is totally
  ramified, with ramification index and degree `e`.
* `TauCeti.map_unramifiedExtension_inertiaDegree_le`: maximal unramified subextensions are
  covariant in towers.
* `TauCeti.map_unramifiedExtension_inertiaDegree_eq_iff`: the maximal unramified subextension is
  unchanged in a tower exactly when the top step is totally ramified.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter III, §5.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §7.
-/

public section

open ValuativeRel IsLocalRing

namespace TauCeti

variable (K L : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]

/-- `L` contains a primitive `(q^f − 1)`-st root of unity, where `q = #𝓀[K]` and `f = f(L/K)`:
its residue field has `q^f` elements. -/
theorem exists_isPrimitiveRoot_natCard_pow_inertiaDegree_sub_one :
    ∃ ζ : L, IsPrimitiveRoot ζ (Nat.card 𝓀[K] ^ inertiaDegree K L - 1) := by
  rw [← natCard_residueField K L]
  exact exists_isPrimitiveRoot_natCard_residueField_sub_one L

/-- **The maximal unramified subextension has degree `f`.** The intermediate field of `L/K`
generated by the roots of `X^{q^f} − X`, for `f = f(L/K)`, has degree `f` over `K`. -/
@[simp]
theorem finrank_unramifiedExtension_inertiaDegree :
    Module.finrank K (unramifiedExtension K L (inertiaDegree K L)) = inertiaDegree K L :=
  finrank_unramifiedExtension_of_isPrimitiveRoot inertiaDegree_pos.ne'
    (exists_isPrimitiveRoot_natCard_pow_inertiaDegree_sub_one K L).choose_spec

/-- **The maximal unramified subextension is unramified.** The intermediate field of `L/K`
generated by the roots of `X^{q^f} − X`, for `f = f(L/K)`, is unramified over `K`, for any
structure of nonarchimedean local field on it compatible with `K`. -/
theorem isUnramified_unramifiedExtension_inertiaDegree
    [ValuativeRel (unramifiedExtension K L (inertiaDegree K L))]
    [TopologicalSpace (unramifiedExtension K L (inertiaDegree K L))]
    [IsNonarchimedeanLocalField (unramifiedExtension K L (inertiaDegree K L))]
    [ValuativeExtension K (unramifiedExtension K L (inertiaDegree K L))] :
    IsUnramified K (unramifiedExtension K L (inertiaDegree K L)) :=
  isUnramified_unramifiedExtension_of_isPrimitiveRoot inertiaDegree_pos.ne'
    (exists_isPrimitiveRoot_natCard_pow_inertiaDegree_sub_one K L).choose_spec

variable {K L} in
/-- **Maximality.** Every unramified intermediate field of `L/K`, for any structure of
nonarchimedean local field on it compatible with `K`, lies in the unramified extension of degree
`f(L/K)` inside `L`. -/
theorem le_unramifiedExtension_inertiaDegree_of_isUnramified (E : IntermediateField K L)
    [ValuativeRel E] [TopologicalSpace E] [IsNonarchimedeanLocalField E] [ValuativeExtension K E]
    [IsUnramified K E] : E ≤ unramifiedExtension K L (inertiaDegree K L) :=
  calc E = unramifiedExtension K L (Module.finrank K E) := E.eq_unramifiedExtension_finrank
    _ ≤ unramifiedExtension K L (inertiaDegree K L) :=
      unramifiedExtension_le_of_dvd inertiaDegree_pos.ne'
        (Dvd.intro _ (IsUnramified.inertiaDegree_tower_eq K E L).symm)

/-- **The top step of the factorization has degree `e`.** The degree of `L` over the unramified
extension of degree `f(L/K)` inside `L` is the ramification index `e(L/K)`. -/
@[simp]
theorem finrank_unramifiedExtension_inertiaDegree_eq_ramificationIndex :
    Module.finrank (unramifiedExtension K L (inertiaDegree K L)) L = ramificationIndex K L := by
  have := finite_of_valuativeExtension K L
  have h := Module.finrank_mul_finrank K (unramifiedExtension K L (inertiaDegree K L)) L
  rw [finrank_unramifiedExtension_inertiaDegree, ← ramificationIndex_mul_inertiaDegree K L,
    mul_comm] at h
  exact Nat.eq_of_mul_eq_mul_right inertiaDegree_pos h

section TotallyRamified

variable [ValuativeRel (unramifiedExtension K L (inertiaDegree K L))]
  [TopologicalSpace (unramifiedExtension K L (inertiaDegree K L))]
  [IsNonarchimedeanLocalField (unramifiedExtension K L (inertiaDegree K L))]
  [ValuativeExtension K (unramifiedExtension K L (inertiaDegree K L))]

/-- **The top step of the factorization is totally ramified.** `L` is totally ramified over the
unramified extension of degree `f(L/K)` inside `L`, for any structure of nonarchimedean local
field on the latter compatible with `K`. -/
theorem isTotallyRamified_unramifiedExtension_inertiaDegree :
    IsTotallyRamified (unramifiedExtension K L (inertiaDegree K L)) L :=
  have := isUnramified_unramifiedExtension_inertiaDegree K L
  (IsUnramified.isTotallyRamified_iff_finrank_eq K _ L).2
    (finrank_unramifiedExtension_inertiaDegree K L)

/-- **The top step of the factorization has ramification index `e`.** The ramification index of
`L` over the unramified extension of degree `f(L/K)` inside `L` is `e(L/K)`. -/
@[simp]
theorem ramificationIndex_unramifiedExtension_inertiaDegree :
    ramificationIndex (unramifiedExtension K L (inertiaDegree K L)) L = ramificationIndex K L :=
  have := isUnramified_unramifiedExtension_inertiaDegree K L
  IsUnramified.ramificationIndex_tower_eq K _ L

end TotallyRamified

variable {K L} in
/-- **Uniqueness of the unramified--totally ramified factorization.** An intermediate field
`E` is the maximal unramified subextension of `L/K` exactly when `E/K` is unramified and `L/E`
is totally ramified. -/
theorem eq_unramifiedExtension_inertiaDegree_iff (E : IntermediateField K L)
    [ValuativeRel E] [TopologicalSpace E] [IsNonarchimedeanLocalField E]
    [ValuativeExtension K E] :
    E = unramifiedExtension K L (inertiaDegree K L) ↔
      IsUnramified K E ∧ IsTotallyRamified E L := by
  constructor
  · rintro rfl
    exact ⟨isUnramified_unramifiedExtension_inertiaDegree K L,
      isTotallyRamified_unramifiedExtension_inertiaDegree K L⟩
  · rintro ⟨hE, hLE⟩
    let _ := hE
    rw [E.eq_unramifiedExtension_finrank]
    congr 1
    exact (IsUnramified.isTotallyRamified_iff_finrank_eq K E L).1 hLE

/-- **An unramified extension is its own maximal unramified subextension.** If `L/K` is
unramified, then `L` is generated over `K` by the roots of `X^{q^f} − X`, for `f = f(L/K)`. -/
theorem IsUnramified.unramifiedExtension_inertiaDegree_eq_top [IsUnramified K L] :
    unramifiedExtension K L (inertiaDegree K L) = ⊤ := by
  have := finite_of_valuativeExtension K L
  refine IntermediateField.eq_of_le_of_finrank_eq le_top ?_
  rw [finrank_unramifiedExtension_inertiaDegree, IntermediateField.finrank_top',
    IsUnramified.inertiaDegree_eq_finrank]

section Tower

variable (M : Type*) [Field M] [ValuativeRel M] [TopologicalSpace M]
  [IsNonarchimedeanLocalField M] [Algebra L M] [Algebra K M] [IsScalarTower K L M]
  [ValuativeExtension L M] [ValuativeExtension K M]

/-- **Maximal unramified subextensions are covariant in towers.** The image in `M` of the
maximal unramified subextension of `L/K` lies in the maximal unramified subextension of `M/K`. -/
theorem map_unramifiedExtension_inertiaDegree_le :
    (unramifiedExtension K L (inertiaDegree K L)).map
        (IsScalarTower.toAlgHom K L M) ≤
      unramifiedExtension K M (inertiaDegree K M) :=
  (map_unramifiedExtension_le (inertiaDegree K L) (IsScalarTower.toAlgHom K L M)).trans
    (unramifiedExtension_le_of_dvd inertiaDegree_pos.ne'
      (Dvd.intro _ (inertiaDegree_tower (K := K) (L := L) M).symm))

/-- **Tower compatibility of the unramified--totally ramified factorization.** The maximal
unramified subextension is unchanged in a tower `M/L/K` exactly when the top step `M/L` is totally
ramified. -/
theorem map_unramifiedExtension_inertiaDegree_eq_iff :
    (unramifiedExtension K L (inertiaDegree K L)).map
        (IsScalarTower.toAlgHom K L M) =
      unramifiedExtension K M (inertiaDegree K M) ↔ IsTotallyRamified L M := by
  let U := unramifiedExtension K L (inertiaDegree K L)
  let ι := IsScalarTower.toAlgHom K L M
  let _ : FiniteDimensional K (U.map ι) :=
    LinearEquiv.finiteDimensional (IntermediateField.equivMap U ι).toLinearEquiv
  constructor
  · intro h
    rw [isTotallyRamified_iff_inertiaDegree_eq_one]
    have hrank := congrArg (fun E : IntermediateField K M ↦ Module.finrank K E) h
    rw [(IntermediateField.equivMap U ι).toLinearEquiv.finrank_eq.symm,
      finrank_unramifiedExtension_inertiaDegree,
      finrank_unramifiedExtension_inertiaDegree,
      inertiaDegree_tower (K := K) (L := L) M] at hrank
    exact Nat.eq_of_mul_eq_mul_left (inertiaDegree_pos (K := K) (L := L))
      (by simpa using hrank.symm)
  · intro h
    apply IntermediateField.eq_of_le_of_finrank_eq
      (map_unramifiedExtension_inertiaDegree_le (K := K) (L := L) M)
    calc
      Module.finrank K (U.map ι) = Module.finrank K U :=
        (IntermediateField.equivMap U ι).toLinearEquiv.finrank_eq.symm
      _ = inertiaDegree K L := finrank_unramifiedExtension_inertiaDegree K L
      _ = inertiaDegree K M := by
        rw [inertiaDegree_tower (K := K) (L := L) M,
          IsTotallyRamified.inertiaDegree_eq_one h, mul_one]
      _ = Module.finrank K (unramifiedExtension K M (inertiaDegree K M)) :=
        (finrank_unramifiedExtension_inertiaDegree K M).symm

end Tower

end TauCeti
