/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Galois.Infinite
public import TauCeti.NumberTheory.LocalField.Unramified.Existence
public import TauCeti.NumberTheory.LocalField.UnitFiltration.Basic
public import TauCeti.NumberTheory.LocalField.Uniformizer
import TauCeti.Algebra.CharP.LocalRing
import TauCeti.FieldTheory.Galois.FixedField
import TauCeti.FieldTheory.Kummer.Extension
import TauCeti.GroupTheory.OrderOfElement.Basic
import TauCeti.NumberTheory.LocalField.PowerSubgroup.Basic
import TauCeti.NumberTheory.LocalField.UnitsDecomposition

/-!
# The maximal unramified extension

Let `K` be a nonarchimedean local field with residue field of cardinality `q`, and let `Ω` be an
extension of `K`. This file defines the maximal unramified extension

`TauCeti.maximalUnramifiedExtension K Ω`,

the union `K^{ur}` of the unramified extensions `K_f = TauCeti.unramifiedExtension K Ω f` of all
degrees `f`. It is Galois over `K` and generated by the roots of the polynomials `X^{q^f} − X`.
When `Ω` is separably closed, a finite intermediate field of `Ω / K` lies in `K^{ur}` exactly when
it is unramified over `K`.

For `Ω` separably closed, the arithmetic Frobenius of `K^{ur} / K`,

`TauCeti.maximalUnramifiedFrobenius K Ω : Gal(K^{ur}/K)`,

is the unique automorphism raising every root of every `X^{q^f} − X` to the `q`-th power. It
restricts to the arithmetic Frobenius `TauCeti.frobeniusAlgEquiv` of each `K_f`, and it is a
topological generator of `Gal(K^{ur}/K)`: the subgroup it generates is dense for the Krull
topology. These are the inputs for identifying `Gal(K^{ur}/K)` with the profinite integers,
Frobenius corresponding to `1`.

## Main definitions

* `TauCeti.maximalUnramifiedExtension K Ω`: the union of the unramified extensions `K_f`.
* `TauCeti.maximalUnramifiedFrobenius K Ω`: the arithmetic Frobenius of `K^{ur} / K`.

## Main results

* `TauCeti.maximalUnramifiedExtension_eq_adjoin`: `K^{ur}` is generated by the roots of the
  polynomials `X^{q^f} − X` for `f ≠ 0`.
* `TauCeti.mem_maximalUnramifiedExtension_of_pow_eq_one`: `K^{ur}` contains the roots of unity of
  order prime to the residue characteristic.
* `TauCeti.mem_maximalUnramifiedExtension_of_pow_eq`: for `p ∤ m`, the `m`-th roots of a unit of
  `𝒪[K]` are unramified.
* `TauCeti.isGalois_maximalUnramifiedExtension`: `K^{ur}` is Galois over `K`.
* `IntermediateField.le_maximalUnramifiedExtension_iff`: for `Ω` separably closed, a finite
  intermediate field lies in `K^{ur}` exactly when it is unramified over `K`.
* `TauCeti.maximalUnramifiedFrobenius_apply_of_pow_natCard_pow_eq_self`,
  `TauCeti.eq_maximalUnramifiedFrobenius_iff`: Frobenius is the unique automorphism raising the
  roots of the polynomials `X^{q^f} − X` to the `q`-th power; its `n`-th power raises them to the
  `q^n`-th power (`TauCeti.maximalUnramifiedFrobenius_pow_apply_of_pow_natCard_pow_eq_self`).
* `TauCeti.coe_maximalUnramifiedFrobenius_apply_of_mem`,
  `TauCeti.coe_maximalUnramifiedFrobenius_zpow_apply_of_mem`: it and its integral powers restrict
  to the arithmetic Frobenius of each `K_f` and its powers.
* `TauCeti.fixedField_zpowers_maximalUnramifiedFrobenius`,
  `TauCeti.topologicalClosure_zpowers_maximalUnramifiedFrobenius`: it is a topological generator
  of `Gal(K^{ur}/K)`.
* `TauCeti.X_pow_sub_C_irreducible_unramifiedExtension`,
  `TauCeti.X_pow_sub_C_irreducible_maximalUnramifiedExtension`: a uniformizer `π` of `K` has no
  nontrivial root in `K^{ur}`: for every `m ≠ 0`, `X ^ m − π` is irreducible over each `K_f` when
  `Ω` is separably closed, and over `K^{ur}` when `Ω` is algebraically closed.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter III, §5.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §7.
-/

public section
noncomputable section

open ValuativeRel Polynomial IntermediateField

namespace TauCeti

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] (Ω : Type*) [Field Ω] [Algebra K Ω]

/-- **The maximal unramified extension** `K^{ur}` of a nonarchimedean local field `K` inside an
extension `Ω`: the union of the unramified extensions `TauCeti.unramifiedExtension K Ω f` of all
degrees `f`. When `Ω` is separably closed, its finite subextensions are exactly the unramified
finite extensions of `K` inside `Ω`. -/
def maximalUnramifiedExtension : IntermediateField K Ω :=
  ⨆ f : ℕ, unramifiedExtension K Ω f

/-- The maximal unramified extension is the union of the unramified extensions of all degrees. -/
theorem maximalUnramifiedExtension_def :
    maximalUnramifiedExtension K Ω = ⨆ f : ℕ, unramifiedExtension K Ω f :=
  -- `(rfl)`, not `rfl`: keep the body opaque while exporting this equation across modules.
  (rfl)

/-- The unramified extension of each degree lies in the maximal unramified extension. -/
theorem unramifiedExtension_le_maximalUnramifiedExtension (f : ℕ) :
    unramifiedExtension K Ω f ≤ maximalUnramifiedExtension K Ω :=
  le_iSup (unramifiedExtension K Ω) f

variable {K Ω} in
/-- The maximal unramified extension is the least intermediate field containing the unramified
extensions of all degrees. -/
@[simp]
theorem maximalUnramifiedExtension_le_iff {E : IntermediateField K Ω} :
    maximalUnramifiedExtension K Ω ≤ E ↔ ∀ f, unramifiedExtension K Ω f ≤ E :=
  iSup_le_iff

/-- The unramified extensions of factorial degrees form an increasing chain. -/
private theorem monotone_unramifiedExtension_factorial :
    Monotone fun n : ℕ ↦ unramifiedExtension K Ω n.factorial :=
  fun _ n h ↦ unramifiedExtension_le_of_dvd (K := K) (Ω := Ω) n.factorial_ne_zero
    (Nat.factorial_dvd_factorial h)

/-- The maximal unramified extension is the union of the chain of unramified extensions of
factorial degrees. -/
private theorem iSup_unramifiedExtension_factorial :
    ⨆ n : ℕ, unramifiedExtension K Ω n.factorial = maximalUnramifiedExtension K Ω := by
  refine le_antisymm (iSup_le fun n ↦ unramifiedExtension_le_maximalUnramifiedExtension K Ω _)
    (iSup_le fun f ↦ ?_)
  rcases eq_or_ne f 0 with rfl | hf
  · simp
  exact (unramifiedExtension_le_of_dvd f.factorial_ne_zero
    (Nat.dvd_factorial (Nat.pos_of_ne_zero hf) le_rfl)).trans (le_iSup_of_le f le_rfl)

variable {K Ω} in
/-- Every element of the maximal unramified extension lies in the unramified extension of some
factorial degree. -/
private theorem exists_mem_unramifiedExtension_factorial {x : Ω}
    (hx : x ∈ maximalUnramifiedExtension K Ω) :
    ∃ n : ℕ, x ∈ unramifiedExtension K Ω n.factorial := by
  rwa [← iSup_unramifiedExtension_factorial, ← SetLike.mem_coe,
    coe_iSup_of_directed (monotone_unramifiedExtension_factorial K Ω).directed_le,
    Set.mem_iUnion] at hx

variable {K Ω} in
/-- An element lies in the maximal unramified extension exactly when it lies in the unramified
extension of some degree `f ≠ 0`. -/
@[simp]
theorem mem_maximalUnramifiedExtension_iff {x : Ω} :
    x ∈ maximalUnramifiedExtension K Ω ↔ ∃ f ≠ 0, x ∈ unramifiedExtension K Ω f := by
  refine ⟨fun hx ↦ ?_, fun ⟨f, _, hx⟩ ↦ unramifiedExtension_le_maximalUnramifiedExtension K Ω f hx⟩
  obtain ⟨n, hn⟩ := exists_mem_unramifiedExtension_factorial hx
  exact ⟨n.factorial, n.factorial_ne_zero, hn⟩

/-- **The maximal unramified extension is generated by the roots of the polynomials `X^{q^f} − X`**
for `f ≠ 0`, where `q` is the cardinality of the residue field of `K`. -/
theorem maximalUnramifiedExtension_eq_adjoin :
    maximalUnramifiedExtension K Ω =
      adjoin K {x : Ω | ∃ f ≠ 0, x ^ Nat.card 𝓀[K] ^ f = x} := by
  simp only [maximalUnramifiedExtension_def, unramifiedExtension_def, ← adjoin_iUnion]
  congr 1
  ext x
  simp only [Set.mem_iUnion, Polynomial.mem_rootSet, map_sub, map_pow, aeval_X, sub_eq_zero]
  -- `X^{q^0} − X` is zero, so it has no roots.
  exact ⟨fun ⟨f, hne, hx⟩ ↦ ⟨f, fun hf ↦ hne (by simp [hf]), hx⟩,
    fun ⟨f, hf, hx⟩ ↦ ⟨f, FiniteField.X_pow_card_pow_sub_X_ne_zero _ hf Finite.one_lt_card, hx⟩⟩

variable {K Ω} in
/-- **Roots of unity of order prime to `p` are unramified.** If the residue characteristic of `K`
does not divide `n`, every `n`-th root of unity of `Ω` lies in the maximal unramified extension,
since `n` divides `q ^ φ(n) − 1` for the cardinality `q` of the residue field. -/
theorem mem_maximalUnramifiedExtension_of_pow_eq_one {n : ℕ} (hn : ¬ ringChar 𝓀[K] ∣ n) {ζ : Ω}
    (hζ : ζ ^ n = 1) : ζ ∈ maximalUnramifiedExtension K Ω := by
  have hn0 : n ≠ 0 := by
    rintro rfl
    exact hn (dvd_zero _)
  -- `q` is a power of `p`, hence prime to `n`.
  have hq : (Nat.card 𝓀[K]).Coprime n := by
    let _ := Fintype.ofFinite 𝓀[K]
    obtain ⟨d, hp, hd⟩ := FiniteField.card 𝓀[K] (ringChar 𝓀[K])
    rw [Nat.card_eq_fintype_card, hd]
    exact (hp.coprime_iff_not_dvd.2 hn).pow_left _
  rw [maximalUnramifiedExtension_eq_adjoin]
  exact subset_adjoin _ _ ⟨n.totient, (Nat.totient_pos.2 (Nat.pos_of_ne_zero hn0)).ne',
    pow_pow_totient_eq_self hq hζ⟩

variable {K Ω} in
/-- **Radicals of units are unramified.** If the residue characteristic of `K` does not divide `m`,
every `m`-th root in `Ω` of a unit `u` of `𝒪[K]` lies in the maximal unramified extension: `u` is a
root of unity `ζ` of order `q − 1` times a principal unit `v`, and `v = w ^ m` for some `w ∈ K`, so
that `x / w` is a root of unity of order `m (q − 1)`, prime to the residue characteristic. -/
theorem mem_maximalUnramifiedExtension_of_pow_eq {m : ℕ} (hm : ¬ ringChar 𝓀[K] ∣ m) {u : Kˣ}
    (hu : u ∈ unitFiltration K 0) {x : Ω} (hx : x ^ m = algebraMap K Ω u) :
    x ∈ maximalUnramifiedExtension K Ω := by
  set A := algebraMap K Ω
  have hmu : IsUnit (m : 𝒪[K]) := IsLocalRing.isUnit_natCast_iff_not_dvd.2 hm
  -- Write `u = ζ v` with `ζ ^ (q - 1) = 1` and `v` a principal unit, and `v = w ^ m`.
  set ζv := unitFiltrationZeroEquivProd K ⟨u, hu⟩
  have huζ : u = ζv.1 * ζv.2 := by
    rw [← coe_unitFiltrationZeroEquivProd_symm_apply, ContinuousMulEquiv.symm_apply_apply]
  obtain ⟨w, hw⟩ := unitFiltration_one_le_range_powMonoidHom_of_isUnit hmu ζv.2.2
  have hw0 : A (w : K) ≠ 0 := (_root_.map_ne_zero A).2 w.ne_zero
  -- Then `z = x / w` satisfies `z ^ m = ζ`, so `z` is a root of unity of order `m (q - 1)`.
  set z := x * (A w)⁻¹
  have hzm : z ^ m = A ((ζv.1 : Kˣ) : K) := calc
    z ^ m = A (u : K) / A ((w ^ m : Kˣ) : K) := by simp [z, mul_pow, hx, div_eq_mul_inv]
    _ = A ((ζv.1 : Kˣ) : K) * A ((ζv.2 : Kˣ) : K) / A ((ζv.2 : Kˣ) : K) := by
      rw [← powMonoidHom_apply, hw, huζ, Units.val_mul, map_mul]
    _ = A ((ζv.1 : Kˣ) : K) := mul_div_cancel_right₀ _ ((_root_.map_ne_zero A).2 (Units.ne_zero _))
  have hζ : ((ζv.1 : Kˣ) : K) ^ (Nat.card 𝓀[K] - 1) = 1 := by
    simpa using congrArg Units.val ((mem_rootsOfUnity _ _).1 ζv.1.2)
  have hq : IsUnit ((m * (Nat.card 𝓀[K] - 1) : ℕ) : 𝒪[K]) := by
    rw [Nat.cast_mul]
    exact hmu.mul (by simpa using isUnit_natCast_natCard_pow_sub_one K one_ne_zero)
  have hz : z ∈ maximalUnramifiedExtension K Ω :=
    mem_maximalUnramifiedExtension_of_pow_eq_one (IsLocalRing.isUnit_natCast_iff_not_dvd.1 hq) <| by
      rw [pow_mul, hzm, ← map_pow, hζ, map_one]
  have hxz : x = z * A w := by
    simp only [z]
    field_simp
  rw [hxz]
  exact mul_mem hz (IntermediateField.algebraMap_mem _ (w : K))

/-- The maximal unramified extension is Galois over `K`, as a union of Galois extensions. -/
instance isGalois_maximalUnramifiedExtension : IsGalois K (maximalUnramifiedExtension K Ω) := by
  rw [maximalUnramifiedExtension_def]
  exact ⟨⟩

variable {K Ω} in
/-- An unramified intermediate field of `Ω / K` lies in the maximal unramified extension. This
holds for any extension `Ω` of `K` and any structure of nonarchimedean local field on `E`
compatible with `K`. -/
theorem _root_.IntermediateField.le_maximalUnramifiedExtension (E : IntermediateField K Ω)
    [ValuativeRel E] [TopologicalSpace E] [IsNonarchimedeanLocalField E] [ValuativeExtension K E]
    [IsUnramified K E] : E ≤ maximalUnramifiedExtension K Ω :=
  E.eq_unramifiedExtension_finrank ▸ unramifiedExtension_le_maximalUnramifiedExtension K Ω _

/-- Two `K`-embeddings of `K_f` agreeing on the roots of `X^{q^f} − X` are equal. -/
private theorem algHom_ext_unramifiedExtension {f : ℕ} {A : Type*} [Field A] [Algebra K A]
    {φ ψ : unramifiedExtension K Ω f →ₐ[K] A}
    (h : ∀ x : unramifiedExtension K Ω f, (x : Ω) ^ Nat.card 𝓀[K] ^ f = x → φ x = ψ x) :
    φ = ψ := by
  refine algHom_ext_of_eq_adjoin K (unramifiedExtension_def K Ω f) fun x hx ↦ h _ ?_
  rw [Polynomial.mem_rootSet, map_sub, map_pow, aeval_X, sub_eq_zero] at hx
  exact hx.2

section IsSepClosed

variable [IsSepClosed Ω]

variable {K Ω} in
/-- **The finite subextensions of the maximal unramified extension are its unramified
subextensions.** For `Ω` separably closed, an intermediate field `E` of `Ω / K` carrying a structure
of nonarchimedean local field compatible with `K` lies in `K^{ur}` exactly when it is unramified
over `K`. -/
theorem _root_.IntermediateField.le_maximalUnramifiedExtension_iff (E : IntermediateField K Ω)
    [ValuativeRel E] [TopologicalSpace E] [IsNonarchimedeanLocalField E]
    [ValuativeExtension K E] : E ≤ maximalUnramifiedExtension K Ω ↔ IsUnramified K E := by
  refine ⟨fun hE ↦ ?_, fun _ ↦ E.le_maximalUnramifiedExtension⟩
  have := finite_of_valuativeExtension K E
  have := Algebra.IsSeparable.of_algHom (f := inclusion hE)
  -- `E` is generated by one element, which lies in some `K_f`; so `E ≤ K_f`.
  obtain ⟨α, hα⟩ := Field.exists_primitive_element K E
  obtain ⟨f, hf, hαf⟩ := mem_maximalUnramifiedExtension_iff.1 (hE α.2)
  have hle : E ≤ unramifiedExtension K Ω f := by
    have hEα : E = K⟮(α : Ω)⟯ := by rw [← lift_adjoin_simple, hα, lift_top]
    rw [hEα, adjoin_simple_le_iff]
    exact hαf
  -- `K_f / K` is unramified, hence so is its subextension `E / K`.
  let L := unramifiedExtension K Ω f
  let _ := finiteIntermediateFieldValuativeRel K Ω L
  let _ := finiteIntermediateFieldTopology K Ω L
  have := finiteIntermediateField_isNonarchimedeanLocalField K Ω L
  have := finiteIntermediateField_valuativeExtension K Ω L
  have : IsUnramified K L := isUnramified_unramifiedExtension hf
  let ι : E →ₐ[K] L := inclusion hle
  let _ := ι.toAlgebra
  have : IsScalarTower K E L := .of_algebraMap_eq fun x ↦ (ι.commutes x).symm
  have : ValuativeExtension E L := ι.valuativeExtension
  exact IsUnramified.tower_bot K E L

/-! ### The arithmetic Frobenius of `K^{ur}` -/

/-- The arithmetic Frobenius of the unramified extension of degree `n!`, for its canonical
structure of nonarchimedean local field, as a `K`-embedding into `Ω`. -/
private def frobeniusFactorial (n : ℕ) : unramifiedExtension K Ω n.factorial →ₐ[K] Ω :=
  letI := finiteIntermediateFieldValuativeRel K Ω (unramifiedExtension K Ω n.factorial)
  letI := finiteIntermediateFieldTopology K Ω (unramifiedExtension K Ω n.factorial)
  haveI := finiteIntermediateField_isNonarchimedeanLocalField K Ω
    (unramifiedExtension K Ω n.factorial)
  haveI := finiteIntermediateField_valuativeExtension K Ω (unramifiedExtension K Ω n.factorial)
  haveI : IsUnramified K (unramifiedExtension K Ω n.factorial) :=
    isUnramified_unramifiedExtension n.factorial_ne_zero
  (unramifiedExtension K Ω n.factorial).val.comp (frobeniusAlgEquiv (K := K)).toAlgHom

private theorem frobeniusFactorial_apply {n g : ℕ} (hg : g ≠ 0)
    (x : unramifiedExtension K Ω n.factorial) (hx : (x : Ω) ^ Nat.card 𝓀[K] ^ g = x) :
    frobeniusFactorial K Ω n x = (x : Ω) ^ Nat.card 𝓀[K] := by
  let L := unramifiedExtension K Ω n.factorial
  let _ := finiteIntermediateFieldValuativeRel K Ω L
  let _ := finiteIntermediateFieldTopology K Ω L
  have := finiteIntermediateField_isNonarchimedeanLocalField K Ω L
  have := finiteIntermediateField_valuativeExtension K Ω L
  have : IsUnramified K L := isUnramified_unramifiedExtension n.factorial_ne_zero
  have h := frobeniusAlgEquiv_apply_of_pow_natCard_pow_eq_self (K := K) (L := L) hg
    (x := x) (Subtype.ext (by rw [SubmonoidClass.coe_pow, hx]))
  exact (congrArg Subtype.val h).trans (SubmonoidClass.coe_pow x _)

/-- The `K`-embedding of `K^{ur}` into `Ω` extending the Frobenius of every `K_{n!}`. -/
private def maximalUnramifiedFrobeniusAux : maximalUnramifiedExtension K Ω →ₐ[K] Ω :=
  Subalgebra.iSupLift (fun n : ℕ ↦ (unramifiedExtension K Ω n.factorial).toSubalgebra)
    ((monotone_unramifiedExtension_factorial K Ω).directed_le.mono_comp _
      fun _ _ h ↦ toSubalgebra_le_toSubalgebra.2 h) (frobeniusFactorial K Ω)
    (fun i j h ↦ algHom_ext_unramifiedExtension K Ω fun x hx ↦
      (frobeniusFactorial_apply K Ω i.factorial_ne_zero x hx).trans
        (frobeniusFactorial_apply K Ω i.factorial_ne_zero (inclusion h x) hx).symm)
    (maximalUnramifiedExtension K Ω).toSubalgebra
    (by rw [← iSup_unramifiedExtension_factorial, toSubalgebra_iSup_of_directed
      (monotone_unramifiedExtension_factorial K Ω).directed_le])

private theorem maximalUnramifiedFrobeniusAux_apply {x : maximalUnramifiedExtension K Ω} {g : ℕ}
    (hg : g ≠ 0) (hx : x ^ Nat.card 𝓀[K] ^ g = x) :
    maximalUnramifiedFrobeniusAux K Ω x = (x : Ω) ^ Nat.card 𝓀[K] := by
  obtain ⟨n, hn⟩ := exists_mem_unramifiedExtension_factorial x.2
  refine (Subalgebra.iSupLift_of_mem
    (fun n : ℕ ↦ (unramifiedExtension K Ω n.factorial).toSubalgebra)
    (T := (maximalUnramifiedExtension K Ω).toSubalgebra) x hn).trans ?_
  exact frobeniusFactorial_apply K Ω hg _
    ((SubmonoidClass.coe_pow x _).symm.trans (congrArg Subtype.val hx))

/-- **The arithmetic Frobenius of the maximal unramified extension** `K^{ur} / K`, for `Ω`
separably closed: the unique automorphism raising every root of every polynomial `X^{q^f} − X`,
`f ≠ 0`, to the `q`-th power, where `q` is the cardinality of the residue field of `K`. It
restricts to the arithmetic Frobenius `TauCeti.frobeniusAlgEquiv` of each unramified extension of
finite degree. -/
def maximalUnramifiedFrobenius : Gal(maximalUnramifiedExtension K Ω/K) :=
  (maximalUnramifiedFrobeniusAux K Ω).restrictNormal' (maximalUnramifiedExtension K Ω)

variable {K Ω} in
/-- **The equation of Frobenius on `K^{ur}`.** Arithmetic Frobenius raises every root of
`X^{q^g} − X` in `K^{ur}`, for `g ≠ 0`, to the `q`-th power. -/
theorem maximalUnramifiedFrobenius_apply_of_pow_natCard_pow_eq_self
    {x : maximalUnramifiedExtension K Ω} {g : ℕ} (hg : g ≠ 0) (hx : x ^ Nat.card 𝓀[K] ^ g = x) :
    maximalUnramifiedFrobenius K Ω x = x ^ Nat.card 𝓀[K] := by
  refine Subtype.ext ?_
  rw [SubmonoidClass.coe_pow, ← maximalUnramifiedFrobeniusAux_apply K Ω hg hx]
  exact AlgHom.restrictNormal_commutes (maximalUnramifiedFrobeniusAux K Ω) _ x

variable {K Ω} in
/-- **The equation of the powers of Frobenius on `K^{ur}`.** The `n`-th power of arithmetic
Frobenius raises every root of `X^{q^g} − X` in `K^{ur}`, for `g ≠ 0`, to the `q^n`-th power. -/
theorem maximalUnramifiedFrobenius_pow_apply_of_pow_natCard_pow_eq_self
    {x : maximalUnramifiedExtension K Ω} {g : ℕ} (hg : g ≠ 0) (hx : x ^ Nat.card 𝓀[K] ^ g = x)
    (n : ℕ) : (maximalUnramifiedFrobenius K Ω ^ n) x = x ^ Nat.card 𝓀[K] ^ n := by
  induction n generalizing x with
  | zero => simp
  | succ n ih =>
    -- `x ^ q` is again a root of `X^{q^g} − X`.
    have hxq : (x ^ Nat.card 𝓀[K]) ^ Nat.card 𝓀[K] ^ g = x ^ Nat.card 𝓀[K] := by
      rw [← pow_mul, mul_comm, pow_mul, hx]
    rw [pow_succ, AlgEquiv.mul_apply,
      maximalUnramifiedFrobenius_apply_of_pow_natCard_pow_eq_self hg hx, ih hxq, ← pow_mul,
      ← pow_succ']

variable {K Ω} in
/-- **Uniqueness of Frobenius on `K^{ur}`.** An automorphism of `K^{ur} / K` is the arithmetic
Frobenius exactly when it raises every root of every polynomial `X^{q^g} − X`, `g ≠ 0`, lying in
`K^{ur}` to the `q`-th power. -/
theorem eq_maximalUnramifiedFrobenius_iff {σ : Gal(maximalUnramifiedExtension K Ω/K)} :
    σ = maximalUnramifiedFrobenius K Ω ↔
      ∀ (x : maximalUnramifiedExtension K Ω) (g : ℕ), g ≠ 0 → x ^ Nat.card 𝓀[K] ^ g = x →
        σ x = x ^ Nat.card 𝓀[K] := by
  refine ⟨fun h x g hg hx ↦ h ▸ maximalUnramifiedFrobenius_apply_of_pow_natCard_pow_eq_self hg hx,
    fun h ↦ AlgEquiv.coe_toAlgHom_injective ?_⟩
  refine algHom_ext_of_eq_adjoin K (maximalUnramifiedExtension_eq_adjoin K Ω) fun x hx ↦ ?_
  have ⟨g, hg, hxg⟩ := hx
  let y : maximalUnramifiedExtension K Ω :=
    ⟨x, (maximalUnramifiedExtension_eq_adjoin K Ω).ge (subset_adjoin _ _ hx)⟩
  have hx' : y ^ Nat.card 𝓀[K] ^ g = y := Subtype.ext (by rw [SubmonoidClass.coe_pow, hxg])
  exact (h _ g hg hx').trans
    (maximalUnramifiedFrobenius_apply_of_pow_natCard_pow_eq_self hg hx').symm

variable {K Ω} in
/-- **Compatibility of Frobenius with the finite levels.** On the unramified extension `K_f` of
any degree `f`, the arithmetic Frobenius of `K^{ur}` acts as the arithmetic Frobenius of
`K_f / K`. This holds for any structure of nonarchimedean local field on `K_f` compatible
with `K`. -/
theorem coe_maximalUnramifiedFrobenius_apply_of_mem {f : ℕ}
    [ValuativeRel (unramifiedExtension K Ω f)] [TopologicalSpace (unramifiedExtension K Ω f)]
    [IsNonarchimedeanLocalField (unramifiedExtension K Ω f)]
    [ValuativeExtension K (unramifiedExtension K Ω f)] [IsUnramified K (unramifiedExtension K Ω f)]
    {x : Ω} (hx : x ∈ unramifiedExtension K Ω f) :
    (maximalUnramifiedFrobenius K Ω
        ⟨x, unramifiedExtension_le_maximalUnramifiedExtension K Ω f hx⟩ : Ω) =
      frobeniusAlgEquiv (K := K) (L := unramifiedExtension K Ω f) ⟨x, hx⟩ := by
  rcases eq_or_ne f 0 with rfl | hf
  · -- `K_0 = K`, and both automorphisms fix `K`.
    obtain ⟨c, rfl⟩ := mem_bot.1 (unramifiedExtension_zero K Ω ▸ hx)
    exact (congrArg Subtype.val ((maximalUnramifiedFrobenius K Ω).commutes c)).trans
      (congrArg Subtype.val
        ((frobeniusAlgEquiv (K := K) (L := unramifiedExtension K Ω 0)).commutes c)).symm
  -- Both sides are `K`-embeddings of `K_f` into `Ω` raising the roots of `X^{q^f} − X` to the
  -- `q`-th power.
  have hle := unramifiedExtension_le_maximalUnramifiedExtension K Ω f
  suffices h : ((maximalUnramifiedExtension K Ω).val.comp
      (maximalUnramifiedFrobenius K Ω).toAlgHom).comp (inclusion hle) =
      (unramifiedExtension K Ω f).val.comp (frobeniusAlgEquiv (K := K)).toAlgHom from
    -- Elaborating the evaluation without an expected type keeps unification from unfolding
    -- `maximalUnramifiedFrobenius`.
    (DFunLike.congr_fun h ⟨x, hx⟩ :)
  refine algHom_ext_unramifiedExtension K Ω fun y hy ↦ ?_
  have hy' : inclusion hle y ^ Nat.card 𝓀[K] ^ f = inclusion hle y :=
    Subtype.ext (by rw [SubmonoidClass.coe_pow]; exact hy)
  have hyL : y ^ Nat.card 𝓀[K] ^ f = y := Subtype.ext (by rw [SubmonoidClass.coe_pow, hy])
  simp only [AlgHom.comp_apply, coe_val, AlgEquiv.coe_toAlgHom]
  rw [maximalUnramifiedFrobenius_apply_of_pow_natCard_pow_eq_self hf hy',
    frobeniusAlgEquiv_apply_of_pow_natCard_pow_eq_self hf hyL, SubmonoidClass.coe_pow,
    SubmonoidClass.coe_pow, coe_inclusion]

variable {K Ω} in
/-- **Compatibility of the powers of Frobenius with the finite levels.** On the unramified
extension `K_f` of any degree `f`, the `n`-th power of the arithmetic Frobenius of `K^{ur}` acts as
the `n`-th power of the arithmetic Frobenius of `K_f / K`, for every integer `n`. -/
theorem coe_maximalUnramifiedFrobenius_zpow_apply_of_mem {f : ℕ}
    [ValuativeRel (unramifiedExtension K Ω f)] [TopologicalSpace (unramifiedExtension K Ω f)]
    [IsNonarchimedeanLocalField (unramifiedExtension K Ω f)]
    [ValuativeExtension K (unramifiedExtension K Ω f)] [IsUnramified K (unramifiedExtension K Ω f)]
    (n : ℤ) {x : Ω} (hx : x ∈ unramifiedExtension K Ω f) :
    ((maximalUnramifiedFrobenius K Ω ^ n)
        ⟨x, unramifiedExtension_le_maximalUnramifiedExtension K Ω f hx⟩ : Ω) =
      (frobeniusAlgEquiv (K := K) (L := unramifiedExtension K Ω f) ^ n) ⟨x, hx⟩ := by
  set Φ := maximalUnramifiedFrobenius K Ω
  set φ := frobeniusAlgEquiv (K := K) (L := unramifiedExtension K Ω f)
  have hle := unramifiedExtension_le_maximalUnramifiedExtension K Ω f
  -- `Φ` and `φ` are intertwined by the inclusion `K_f ⊆ K^{ur}`, and so are `Φ⁻¹` and `φ⁻¹`.
  have h₁ (y : unramifiedExtension K Ω f) : Φ (inclusion hle y) = inclusion hle (φ y) :=
    Subtype.ext (coe_maximalUnramifiedFrobenius_apply_of_mem y.2)
  have h₂ (y : unramifiedExtension K Ω f) : Φ⁻¹ (inclusion hle y) = inclusion hle (φ⁻¹ y) :=
    Φ.injective <| by
      rw [h₁, ← AlgEquiv.mul_apply Φ Φ⁻¹, ← AlgEquiv.mul_apply φ φ⁻¹, mul_inv_cancel,
        mul_inv_cancel, AlgEquiv.one_apply, AlgEquiv.one_apply]
  suffices h : ∀ y : unramifiedExtension K Ω f,
      (Φ ^ n) (inclusion hle y) = inclusion hle ((φ ^ n) y) from congrArg Subtype.val (h ⟨x, hx⟩)
  induction n using Int.induction_on with
  | zero => intro y; rw [zpow_zero, zpow_zero, AlgEquiv.one_apply, AlgEquiv.one_apply]
  | succ n ih =>
    intro y
    rw [zpow_add_one, zpow_add_one, AlgEquiv.mul_apply, h₁, ih, AlgEquiv.mul_apply]
  | pred n ih =>
    intro y
    rw [zpow_sub_one, zpow_sub_one, AlgEquiv.mul_apply, h₂, ih, AlgEquiv.mul_apply]

variable {K Ω} in
/-- **Frobenius generates `Gal(K^{ur}/K)` topologically, algebraic form.** The elements of `K^{ur}`
fixed by the arithmetic Frobenius are those of `K`. -/
theorem fixedField_zpowers_maximalUnramifiedFrobenius :
    fixedField (Subgroup.zpowers (maximalUnramifiedFrobenius K Ω)) = ⊥ := by
  refine eq_bot_iff.2 fun y hy ↦ ?_
  have hy1 := (mem_fixedField_zpowers_iff _ y).1 hy
  obtain ⟨f, hf, hyf⟩ := mem_maximalUnramifiedExtension_iff.1 y.2
  -- With its canonical structure, `K_f` is unramified, with Galois group generated by Frobenius.
  let L := unramifiedExtension K Ω f
  let _ := finiteIntermediateFieldValuativeRel K Ω L
  let _ := finiteIntermediateFieldTopology K Ω L
  have := finiteIntermediateField_isNonarchimedeanLocalField K Ω L
  have := finiteIntermediateField_valuativeExtension K Ω L
  have : IsUnramified K L := isUnramified_unramifiedExtension hf
  -- The Frobenius of `K_f` fixes `y`, hence so does all of `Gal(K_f/K)`, so `y ∈ K`.
  have hσ : frobeniusAlgEquiv (K := K) (L := L) ⟨y, hyf⟩ = ⟨y, hyf⟩ := by
    refine Subtype.ext ?_
    rw [← coe_maximalUnramifiedFrobenius_apply_of_mem hyf]
    exact congrArg Subtype.val hy1
  have hbot : (⟨y, hyf⟩ : L) ∈ (⊥ : IntermediateField K L) := by
    rw [← IsGalois.fixedField_top, ← zpowers_frobeniusAlgEquiv (K := K) (L := L)]
    exact (mem_fixedField_zpowers_iff _ _).2 hσ
  obtain ⟨c, hc⟩ := mem_bot.1 hbot
  exact mem_bot.2 ⟨c, Subtype.ext (by simpa using congrArg Subtype.val hc)⟩

variable {K Ω} in
/-- **Frobenius is a topological generator of `Gal(K^{ur}/K)`**: the subgroup it generates is
dense for the Krull topology. -/
theorem topologicalClosure_zpowers_maximalUnramifiedFrobenius :
    (Subgroup.zpowers (maximalUnramifiedFrobenius K Ω)).topologicalClosure = ⊤ := by
  set H := Subgroup.zpowers (maximalUnramifiedFrobenius K Ω)
  -- The closure of `H` is the fixing subgroup of its fixed field, which is contained in that
  -- of `H`, that is `K`.
  have h : (fixedField H.topologicalClosure).fixingSubgroup = H.topologicalClosure :=
    InfiniteGalois.fixingSubgroup_fixedField ⟨_, H.isClosed_topologicalClosure⟩
  have hbot : fixedField H.topologicalClosure = ⊥ :=
    eq_bot_iff.2 ((fixedField_antitone H.le_topologicalClosure).trans
      fixedField_zpowers_maximalUnramifiedFrobenius.le)
  rw [← h, hbot, fixingSubgroup_bot]

variable {K Ω} in
/-- **A uniformizer stays a uniformizer in `K_f`**, so it has no nontrivial root there: for a
uniformizer `π` of `K` and `m ≠ 0`, the polynomial `X ^ m − π` is irreducible over the unramified
extension `K_f` of each degree `f ≠ 0`. -/
theorem X_pow_sub_C_irreducible_unramifiedExtension {π : Kˣ} (hπ : IsUniformizer K π) {m : ℕ}
    (hm : m ≠ 0) {f : ℕ} (hf : f ≠ 0) :
    Irreducible (X ^ m - C (algebraMap K (unramifiedExtension K Ω f) π)) := by
  let L := unramifiedExtension K Ω f
  let _ := finiteIntermediateFieldValuativeRel K Ω L
  let _ := finiteIntermediateFieldTopology K Ω L
  have := finiteIntermediateField_isNonarchimedeanLocalField K Ω L
  have := finiteIntermediateField_valuativeExtension K Ω L
  have : IsUnramified K L := isUnramified_unramifiedExtension hf
  obtain ⟨ϖ, hϖ, hϖπ⟩ := (isUniformizer_iff_exists_irreducible K π).1 hπ
  have h := X_pow_sub_C_irreducible_of_irreducible (K := L)
    (IsUnramified.irreducible_algebraMap (K := K) (L := L) hϖ) hm
  have e : algebraMap 𝒪[L] L (algebraMap 𝒪[K] 𝒪[L] ϖ) = algebraMap K L π := by
    rw [← hϖπ]
    -- `algebraMap 𝒪[L] L` is the inclusion of the ring of integers.
    exact coe_algebraMap_integerRing ϖ
  rwa [e] at h

end IsSepClosed

/-! ### Radicals of a uniformizer over `K^{ur}` -/

section IsAlgClosed

variable [IsAlgClosed Ω]

variable {K Ω} in
/-- **A uniformizer has no nontrivial root in `K^{ur}`**: for a uniformizer `π` of `K` and
`m ≠ 0`, the polynomial `X ^ m − π` is irreducible over the maximal unramified extension. Any
factor has its finitely many coefficients in a single `K_f`, over which `X ^ m − π` is
irreducible. So `K^{ur}(π^{1/m})` has degree `m` over `K^{ur}`. -/
theorem X_pow_sub_C_irreducible_maximalUnramifiedExtension {π : Kˣ} (hπ : IsUniformizer K π)
    {m : ℕ} (hm : m ≠ 0) :
    Irreducible (X ^ m - C (algebraMap K (maximalUnramifiedExtension K Ω) π)) := by
  set E := maximalUnramifiedExtension K Ω
  obtain ⟨α, hα⟩ := IsAlgClosed.exists_pow_nat_eq (algebraMap K Ω π) (Nat.pos_of_ne_zero hm)
  have hmon : (X ^ m - C (algebraMap K E π)).Monic := monic_X_pow_sub_C _ hm
  have hroot : aeval α (X ^ m - C (algebraMap K E π)) = 0 := by simp [hα]
  have hint : IsIntegral E α := ⟨_, hmon, hroot⟩
  -- It suffices that the minimal polynomial `g` of a root `α` over `K^{ur}` has degree `m`.
  set g := minpoly E α
  have hg : g ∣ X ^ m - C (algebraMap K E π) := minpoly.dvd E α hroot
  -- The finitely many coefficients of `g` lie in a common unramified extension `L = K_N`.
  have hcoeff (i : ℕ) : ∃ f ≠ 0, ((g.coeff i : E) : Ω) ∈ unramifiedExtension K Ω f :=
    mem_maximalUnramifiedExtension_iff.1 (g.coeff i).2
  choose F hF hmemF using hcoeff
  set N := ∏ i ∈ Finset.range (g.natDegree + 1), F i
  have hN : N ≠ 0 := Finset.prod_ne_zero_iff.2 fun i _ ↦ hF i
  set L := unramifiedExtension K Ω N
  have hLE : L ≤ E := unramifiedExtension_le_maximalUnramifiedExtension K Ω N
  have hmemL (i : ℕ) : ((g.coeff i : E) : Ω) ∈ L := by
    rcases le_or_gt i g.natDegree with hi | hi
    · exact unramifiedExtension_le_of_dvd hN
        (Finset.dvd_prod_of_mem F (Finset.mem_range.2 (Nat.lt_succ_of_le hi))) (hmemF i)
    · rw [coeff_eq_zero_of_natDegree_lt hi]
      exact zero_mem L
  -- So `g` descends to a monic `q` over `L`, which vanishes at `α`.
  let ι : L →+* E := (inclusion hLE).toRingHom
  have hlifts : g ∈ lifts ι := (lifts_iff_coeff_lifts g).2 fun i ↦ ⟨⟨_, hmemL i⟩, Subtype.ext rfl⟩
  obtain ⟨q, hqg, hqdeg, hqmon⟩ := lifts_and_degree_eq_and_monic hlifts (minpoly.monic hint)
  have hq : aeval α q = 0 := by
    have h : aeval α g = 0 := minpoly.aeval E α
    -- `algebraMap E Ω ∘ ι` is `algebraMap L Ω`: both are the inclusions into `Ω`.
    rwa [← hqg, aeval_def, eval₂_map] at h
  -- Over `L` the minimal polynomial of `α` is `X ^ m − π`, which divides `q`.
  have hirrL := X_pow_sub_C_irreducible_unramifiedExtension (Ω := Ω) hπ hm hN
  have hrootL : aeval α (X ^ m - C (algebraMap K L π)) = 0 := by simp [hα]
  have hmin : minpoly L α = X ^ m - C (algebraMap K L π) :=
    (minpoly.eq_of_irreducible_of_monic hirrL hrootL (monic_X_pow_sub_C _ hm)).symm
  have hle : m ≤ g.natDegree := by
    have h := natDegree_le_of_dvd (minpoly.dvd L α hq) hqmon.ne_zero
    rwa [hmin, natDegree_X_pow_sub_C, natDegree_eq_of_degree_eq hqdeg] at h
  rw [eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hint) hmon hg
    (by rwa [natDegree_X_pow_sub_C])]
  exact minpoly.irreducible hint

end IsAlgClosed

end TauCeti
