/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Category.GradedModuleCat.SimpleFamily
public import TauCeti.Algebra.Category.GradedModuleCat.Ideal

/-!
# Graded simple modules of a nonnegatively graded algebra with split degree-zero part

Let `A` be a `k`-algebra graded by `𝒜 : ℤ → Submodule k A` and let `e ∈ 𝒜 0`.
The quotient construction does not require idempotence.
Write `A₊e` for the left ideal generated by the products `x e` with `x` homogeneous of positive
degree. The graded module `TauCeti.gradedPositiveMulQuotient` is the quotient `Ae / A₊e`,
the cokernel of
the inclusion of graded modules `A₊e ⟶ Ae`.

Suppose that `A` is nonnegatively graded, and that a complete family of orthogonal nonzero
idempotents `eᵢ` of degree zero spans the degree-zero piece `𝒜 0`. This is the situation of the
path-length grading of a path algebra of a finite quiver, or of its quotient by a homogeneous
ideal contained in the arrow ideal. Then `A₊eᵢ` is the graded radical of `A eᵢ`, the intersection
of its maximal graded submodules, so `Sᵢ = A eᵢ / A₊eᵢ` is the graded head of the graded projective
`A eᵢ`, and:

* the graded head `Sᵢ` of `A eᵢ` is one-dimensional, spanned by the class of `eᵢ` in degree zero, so
  `eⱼ` acts on it by `δᵢⱼ` and the graded dimension of `eⱼ • Sᵢ` is `δᵢⱼ`;
* `Sᵢ` is a simple graded module;
* every simple finite graded module `M` is isomorphic to an internal shift `Sᵢ{p}`: take `p` to be
  the top degree of `M` and `m ∈ Mₚ` with `eᵢ m ≠ 0`; positive-degree elements kill `eᵢ m`, so
  `x eᵢ ↦ x eᵢ m` descends to a nonzero map `Sᵢ{p} ⟶ M`, which is injective because `Sᵢ` is
  one-dimensional, and surjective because `M` is simple.

## Main definitions

* `TauCeti.gradedPositiveMulIdeal`: the left ideal `A₊e`.
* `TauCeti.gradedPositiveMulQuotient`: the quotient `Ae / A₊e` for any degree-zero element `e`.
* `TauCeti.gradedPositiveMulQuotientMk`: the quotient map `Ae ⟶ Ae / A₊e`.
* `TauCeti.gradedPositiveMulQuotientLift`: the map `Ae / A₊e ⟶ M`, `[x] ↦ x m`, for `m` killed
  by `A₊e`.

## Main results

* `TauCeti.gradedPositiveMulQuotientMk_eq_zero_iff`: the kernel of `Ae ⟶ Ae / A₊e` is `A₊e`.
* `TauCeti.mem_gradedPositiveMulQuotient_piece_iff`: the degree-`p` piece of `Ae / A₊e` consists
  of the classes of the degree-`p` elements of `Ae`.
* `TauCeti.gradedPositiveMulQuotientLift_gradedPositiveMulQuotientMk`,
  `TauCeti.gradedPositiveMulQuotientLift_unique`: the universal property of `Ae / A₊e`.
* `TauCeti.smulGradedDimension_gradedIdempotentHead`: the graded dimension of `eⱼ • Sᵢ` is `δᵢⱼ`.
* `TauCeti.simple_gradedIdempotentHead`: each graded head `Sᵢ` is a simple graded module.
* `TauCeti.isExhaustiveGradedSimpleFamily_gradedIdempotentHead`: every simple finite graded module
  is isomorphic to a shift of some `Sᵢ`.

## References

* C. Năstăsescu and F. Van Oystaeyen, *Methods of Graded Rings*, Section 2.3, for graded modules
  and their simple objects.
* I. Assem, D. Simson, A. Skowroński, *Elements of the Representation Theory of Associative
  Algebras, Vol. 1*, Sections III.2 and III.3, for the simple tops of the indecomposable
  projectives of a basic algebra.
-/

public section

noncomputable section

namespace TauCeti

open CategoryTheory _root_.DirectSum

universe uk uA uI

section CommRing

variable {k : Type uk} [CommRing k] {A : Type uA} [Ring A] [Algebra k A]
  (𝒜 : ℤ → Submodule k A) [GradedAlgebra 𝒜] {e : A}

/-! ### The head of `Ae` -/

/-- The left ideal `A₊e` generated by the products `x e` with `x` homogeneous of positive
degree. It is the kernel of the quotient map `Ae ⟶ Ae / A₊e`
(`TauCeti.gradedPositiveMulQuotientMk_eq_zero_iff`). -/
def gradedPositiveMulIdeal (e : A) : Ideal A :=
  Ideal.span {y | ∃ p : ℤ, 0 < p ∧ ∃ x ∈ 𝒜 p, x * e = y}

omit [GradedAlgebra 𝒜] in
/-- A product `x e` with `x` homogeneous of positive degree lies in `A₊e`. -/
theorem mul_mem_gradedPositiveMulIdeal {p : ℤ} (hp : 0 < p) {x : A} (hx : x ∈ 𝒜 p) :
    x * e ∈ gradedPositiveMulIdeal 𝒜 e :=
  Ideal.subset_span ⟨p, hp, x, hx, rfl⟩

omit [GradedAlgebra 𝒜] in
/-- A left ideal contains `A₊e` exactly when it contains every positive homogeneous product
`x e`. -/
theorem gradedPositiveMulIdeal_le_iff {J : Ideal A} :
    gradedPositiveMulIdeal 𝒜 e ≤ J ↔
      ∀ (p : ℤ), 0 < p → ∀ x ∈ 𝒜 p, x * e ∈ J := by
  rw [gradedPositiveMulIdeal, Ideal.span_le]
  constructor
  · intro h p hp x hx
    exact h ⟨p, hp, x, hx, rfl⟩
  · intro h y hy
    obtain ⟨p, hp, x, hx, rfl⟩ := hy
    exact h p hp x hx

omit [GradedAlgebra 𝒜] in
private theorem positiveMulIdeal_le (e : A) :
    gradedPositiveMulIdeal 𝒜 e ≤ Ideal.span {e} := by
  rw [gradedPositiveMulIdeal, Ideal.span_le]
  rintro _ ⟨p, -, x, -, rfl⟩
  exact Ideal.mul_mem_left _ x (Ideal.subset_span rfl)

private theorem isHomogeneous_span_singleton (he₀ : e ∈ 𝒜 0) :
    (Ideal.span {e} : Ideal A).IsHomogeneous 𝒜 :=
  Ideal.homogeneous_span 𝒜 _ fun _ hx => ⟨0, (Set.mem_singleton_iff.1 hx) ▸ he₀⟩

private theorem isHomogeneous_positiveMulIdeal (he₀ : e ∈ 𝒜 0) :
    (gradedPositiveMulIdeal 𝒜 e).IsHomogeneous 𝒜 :=
  Ideal.homogeneous_span 𝒜 _ fun _ ⟨p, _, _, hx, hy⟩ =>
    ⟨p, hy ▸ add_zero p ▸ SetLike.GradedMul.mul_mem hx he₀⟩

/-- The inclusion `A₊e ⟶ Ae` of graded modules. -/
private def positiveMulIdealInclusion (he₀ : e ∈ 𝒜 0) :
    GradedModuleCat.ofIdeal 𝒜 (gradedPositiveMulIdeal 𝒜 e) (isHomogeneous_positiveMulIdeal 𝒜 he₀) ⟶
      GradedModuleCat.ofIdeal 𝒜 (Ideal.span {e}) (isHomogeneous_span_singleton 𝒜 he₀) :=
  GradedModuleCat.ofHom (Submodule.inclusion (positiveMulIdeal_le 𝒜 e)) <|
    LinearMap.isHomogeneous_def.2 fun p x hx => by
      rw [GradedModuleCat.mem_ofIdeal_piece_iff] at hx ⊢
      simpa using hx

/-- **The quotient `Ae / A₊e`** by the left ideal generated by the products `x e` with `x`
homogeneous of positive degree, for any degree-zero element `e`; no idempotence is required. When
`A` is nonnegatively graded and its degree-zero piece is spanned by a complete family of nonzero
orthogonal idempotents containing `e`, it is the graded head of `Ae`, a simple graded module
(`TauCeti.simple_gradedIdempotentHead`). -/
def gradedPositiveMulQuotient (he₀ : e ∈ 𝒜 0) : GradedModuleCat.{uA} 𝒜 :=
  GradedModuleCat.cokernelObj (positiveMulIdealInclusion 𝒜 he₀)

/-- The quotient `Ae / A₊e` is finitely generated, as a quotient of the cyclic module `Ae`. -/
instance (he₀ : e ∈ 𝒜 0) : Module.Finite A (gradedPositiveMulQuotient 𝒜 he₀) := by
  have : Module.Finite A (Ideal.span {e} : Ideal A) :=
    Module.Finite.iff_fg.2 (Submodule.fg_span_singleton e)
  exact inferInstanceAs (Module.Finite A
    ((Ideal.span {e} : Ideal A) ⧸ LinearMap.range (positiveMulIdealInclusion 𝒜 he₀).hom))

/-- The quotient `Ae / A₊e` is finite-dimensional when `A` is. -/
instance [Module.Finite k A] (he₀ : e ∈ 𝒜 0) : Module.Finite k (gradedPositiveMulQuotient 𝒜 he₀) :=
  Module.Finite.trans A _

/-- The quotient `Ae / A₊e` is a finite graded module. -/
theorem gradedFiniteModules_gradedPositiveMulQuotient (he₀ : e ∈ 𝒜 0) :
    gradedFiniteModules 𝒜 (gradedPositiveMulQuotient 𝒜 he₀) :=
  gradedFiniteModules_iff.2 inferInstance

variable {𝒜}

/-- **The quotient map `Ae ⟶ Ae / A₊e`**, sending an element of `Ae` to its class. -/
def gradedPositiveMulQuotientMk (he₀ : e ∈ 𝒜 0) :
    (Ideal.span {e} : Ideal A) →ₗ[A] gradedPositiveMulQuotient 𝒜 he₀ :=
  (LinearMap.range (positiveMulIdealInclusion 𝒜 he₀).hom).mkQ

/-- Every element of `Ae / A₊e` is the class of an element of `Ae`. -/
theorem gradedPositiveMulQuotientMk_surjective (he₀ : e ∈ 𝒜 0) :
    Function.Surjective (gradedPositiveMulQuotientMk he₀) :=
  Submodule.mkQ_surjective _

/-- **The kernel of `Ae ⟶ Ae / A₊e` is `A₊e`.** -/
@[simp]
theorem gradedPositiveMulQuotientMk_eq_zero_iff (he₀ : e ∈ 𝒜 0) (x : (Ideal.span {e} : Ideal A)) :
    gradedPositiveMulQuotientMk he₀ x = 0 ↔ (x : A) ∈ gradedPositiveMulIdeal 𝒜 e := by
  -- `gradedPositiveMulQuotientMk` quotients by the range of the inclusion `A₊e ⟶ Ae`, whose
  -- underlying linear map is `Submodule.inclusion`; both unfoldings are definitional.
  change Submodule.Quotient.mk x = 0 ↔ _
  rw [Submodule.Quotient.mk_eq_zero]
  change x ∈ LinearMap.range (Submodule.inclusion (positiveMulIdeal_le 𝒜 e)) ↔ _
  rw [Submodule.range_inclusion, Submodule.mem_comap, Submodule.subtype_apply]

/-- **The homogeneous pieces of `Ae / A₊e`**: the degree-`p` piece consists of the classes of the
elements of `Ae` of degree `p`. -/
@[simp]
theorem mem_gradedPositiveMulQuotient_piece_iff (he₀ : e ∈ 𝒜 0) {p : ℤ}
    {y : gradedPositiveMulQuotient 𝒜 he₀} :
    y ∈ (gradedPositiveMulQuotient 𝒜 he₀).grading.piece p ↔
      ∃ x : (Ideal.span {e} : Ideal A), (x : A) ∈ 𝒜 p ∧ gradedPositiveMulQuotientMk he₀ x = y := by
  refine (GradedModuleCat.mem_cokernelGrading_piece_iff (positiveMulIdealInclusion 𝒜 he₀)).trans
    (exists_congr fun x => and_congr ?_ Iff.rfl)
  exact GradedModuleCat.mem_ofIdeal_piece_iff (isHomogeneous_span_singleton 𝒜 he₀)

/-- **The map `Ae / A₊e ⟶ M` sending the class of `x` to `x m`**, for an element `m` of an
`A`-module `M` killed by `A₊e`. -/
def gradedPositiveMulQuotientLift (he₀ : e ∈ 𝒜 0) {M : Type*} [AddCommGroup M] [Module A M] (m : M)
    (hm : ∀ y ∈ gradedPositiveMulIdeal 𝒜 e, y • m = 0) :
    gradedPositiveMulQuotient 𝒜 he₀ →ₗ[A] M :=
  Submodule.liftQ _ ((LinearMap.toSpanSingleton A M m).comp (Submodule.subtype _)) <| by
    rintro _ ⟨y, rfl⟩
    exact hm y y.2

/-- The map `Ae / A₊e ⟶ M` induced by `m` sends the class of `x` to `x m`. -/
@[simp]
theorem gradedPositiveMulQuotientLift_gradedPositiveMulQuotientMk (he₀ : e ∈ 𝒜 0) {M : Type*}
    [AddCommGroup M] [Module A M] (m : M) (hm : ∀ y ∈ gradedPositiveMulIdeal 𝒜 e, y • m = 0)
    (x : (Ideal.span {e} : Ideal A)) :
    gradedPositiveMulQuotientLift he₀ m hm (gradedPositiveMulQuotientMk he₀ x) = (x : A) • m := by
  unfold gradedPositiveMulQuotientLift gradedPositiveMulQuotientMk
  exact Submodule.liftQ_apply _ _ x

/-- Two linear maps out of `Ae / A₊e` agreeing on the classes of all elements of `Ae` are
equal. -/
@[ext]
theorem gradedPositiveMulQuotient_linearMap_ext (he₀ : e ∈ 𝒜 0) {M : Type*} [AddCommGroup M]
    [Module A M] {f g : gradedPositiveMulQuotient 𝒜 he₀ →ₗ[A] M}
    (h : f ∘ₗ gradedPositiveMulQuotientMk he₀ = g ∘ₗ gradedPositiveMulQuotientMk he₀) : f = g :=
  LinearMap.ext fun y => by
    obtain ⟨x, rfl⟩ := gradedPositiveMulQuotientMk_surjective he₀ y
    exact LinearMap.congr_fun h x

/-- **The map `Ae / A₊e ⟶ M` induced by `m` is unique**: it is the only linear map sending the
class of each `x` to `x m`. -/
theorem gradedPositiveMulQuotientLift_unique (he₀ : e ∈ 𝒜 0) {M : Type*} [AddCommGroup M]
    [Module A M] (m : M) (hm : ∀ y ∈ gradedPositiveMulIdeal 𝒜 e, y • m = 0)
    (f : gradedPositiveMulQuotient 𝒜 he₀ →ₗ[A] M)
    (hf : ∀ x : (Ideal.span {e} : Ideal A), f (gradedPositiveMulQuotientMk he₀ x) = (x : A) • m) :
    f = gradedPositiveMulQuotientLift he₀ m hm :=
  gradedPositiveMulQuotient_linearMap_ext he₀ <| LinearMap.ext fun x => by
    simp [hf]

end CommRing

/-! ### Nonnegative gradings with split degree-zero part -/

section Field

variable {k : Type uk} [Field k] {A : Type uA} [Ring A] [Algebra k A]
  {𝒜 : ℤ → Submodule k A} [GradedAlgebra 𝒜] {I : Type uI} {e : I → A}
  (hneg : ∀ p < 0, 𝒜 p = ⊥) (he : OrthogonalIdempotents e) (he₀ : ∀ i, e i ∈ 𝒜 0)
  (hspan : 𝒜 0 ≤ Submodule.span k (Set.range e)) (hne : ∀ i, e i ≠ 0)

include hneg in
/-- In a nonnegatively graded algebra, every element of `A₊e` has vanishing components in all
degrees `q ≤ 0`. -/
private theorem decompose_eq_zero_of_mem_gradedPositiveMulIdeal {f : A} (hf₀ : f ∈ 𝒜 0) {y : A}
    (hy : y ∈ gradedPositiveMulIdeal 𝒜 f) {q : ℤ} (hq : q ≤ 0) : (decompose 𝒜 y q : A) = 0 := by
  induction hy using Submodule.span_induction generalizing q with
  | mem y hy =>
    obtain ⟨p, hp, x, hx, rfl⟩ := hy
    exact decompose_of_mem_ne 𝒜 (add_zero p ▸ SetLike.GradedMul.mul_mem hx hf₀) (by omega)
  | zero => simp
  | add y z _ _ hy hz => simp [hy hq, hz hq]
  | smul a y _ hy =>
    rw [smul_eq_mul]
    induction a using DirectSum.Decomposition.inductionOn 𝒜 with
    | zero => simp
    | add a b ha hb =>
      rw [add_mul, decompose_add, DirectSum.add_apply, Submodule.coe_add, ha, hb, add_zero]
    | @homogeneous r a =>
      obtain ⟨a, ha⟩ := a
      rcases lt_or_ge r 0 with hr | hr
      · rw [hneg r hr] at ha
        simp [(Submodule.mem_bot k).1 ha]
      · have h := coe_decompose_mul_add_of_left_mem 𝒜 (j := q - r) (b := y) ha
        rw [add_sub_cancel] at h
        rw [h, hy (by omega), mul_zero]

include hneg in
/-- In a nonnegatively graded algebra, an element of `Ae` whose degree-zero component vanishes lies
in `A₊e`. -/
private theorem mem_gradedPositiveMulIdeal_of_decompose_eq_zero {f : A} (hf : IsIdempotentElem f)
    {x : A} (hx : x ∈ (Ideal.span {f} : Ideal A)) (hx₀ : (decompose 𝒜 x 0 : A) = 0) :
    x ∈ gradedPositiveMulIdeal 𝒜 f := by
  classical
  rw [mem_span_singleton_iff_mul_eq_self hf] at hx
  rw [← hx, ← sum_support_decompose 𝒜 x, Finset.sum_mul]
  refine Ideal.sum_mem _ fun p _ => ?_
  rcases lt_trichotomy p 0 with hp | rfl | hp
  · have h : (decompose 𝒜 x p : A) ∈ (⊥ : Submodule k A) := hneg p hp ▸ (decompose 𝒜 x p).2
    simp [(Submodule.mem_bot k).1 h]
  · simp [hx₀]
  · exact mul_mem_gradedPositiveMulIdeal 𝒜 hp (decompose 𝒜 x p).2

omit [GradedAlgebra 𝒜] in
include he hspan in
/-- A degree-zero element of `A eᵢ` is a scalar multiple of `eᵢ`. -/
private theorem exists_eq_smul_of_mem_zero {i : I} {x : A} (hx : x ∈ 𝒜 0)
    (hxi : x ∈ (Ideal.span {e i} : Ideal A)) : ∃ c : k, x = c • e i := by
  classical
  have hmul : ∀ y ∈ Submodule.span k (Set.range e), ∃ c : k, y * e i = c • e i := by
    intro y hy
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨j, rfl⟩ := hy
      by_cases hji : j = i
      · subst j
        exact ⟨1, by rw [(he.idem i).eq, one_smul]⟩
      · exact ⟨0, by rw [he.ortho hji, zero_smul]⟩
    | zero => exact ⟨0, by rw [zero_mul, zero_smul]⟩
    | add y z _ _ hy hz =>
      obtain ⟨a, ha⟩ := hy
      obtain ⟨b, hb⟩ := hz
      exact ⟨a + b, by rw [add_mul, ha, hb, add_smul]⟩
    | smul a y _ hy =>
      obtain ⟨b, hb⟩ := hy
      exact ⟨a * b, by rw [smul_mul_assoc, hb, smul_smul]⟩
  obtain ⟨c, hc⟩ := hmul x (hspan hx)
  rw [mem_span_singleton_iff_mul_eq_self (he.idem i)] at hxi
  exact ⟨c, hxi ▸ hc⟩

variable (e) in
/-- The class of `eᵢ` in the head of `A eᵢ`. -/
private def headGenerator (i : I) : gradedPositiveMulQuotient 𝒜 (he₀ i) :=
  gradedPositiveMulQuotientMk (he₀ i) ⟨e i, Ideal.subset_span rfl⟩

include hneg he hspan in
/-- Every element of the head of `A eᵢ` is a scalar multiple of the class of `eᵢ`. -/
private theorem exists_eq_smul_headGenerator (i : I) (y : gradedPositiveMulQuotient 𝒜 (he₀ i)) :
    ∃ c : k, y = c • headGenerator e he₀ i := by
  obtain ⟨x, rfl⟩ := gradedPositiveMulQuotientMk_surjective (he₀ i) y
  have hx₀ : (decompose 𝒜 (x : A) 0 : A) ∈ (Ideal.span {e i} : Ideal A) :=
    isHomogeneous_span_singleton 𝒜 (he₀ i) 0 x.2
  obtain ⟨c, hc⟩ := exists_eq_smul_of_mem_zero he hspan (decompose 𝒜 (x : A) 0).2 hx₀
  refine ⟨c, ?_⟩
  rw [headGenerator, ← LinearMap.map_smul_of_tower, ← sub_eq_zero, ← map_sub,
    gradedPositiveMulQuotientMk_eq_zero_iff]
  refine mem_gradedPositiveMulIdeal_of_decompose_eq_zero hneg (he.idem i) (Submodule.coe_mem _) ?_
  rw [Submodule.coe_sub, Submodule.coe_smul_of_tower, decompose_sub, decompose_smul,
    DirectSum.sub_apply, DirectSum.smul_apply, Submodule.coe_sub, Submodule.coe_smul_of_tower,
    decompose_of_mem_same 𝒜 (he₀ i), hc, sub_self]

include hneg in
/-- The class of `eᵢ` in the head of `A eᵢ` is nonzero. -/
private theorem headGenerator_ne_zero (i : I) (hne : e i ≠ 0) : headGenerator e he₀ i ≠ 0 := by
  rw [headGenerator, Ne, gradedPositiveMulQuotientMk_eq_zero_iff]
  intro h
  have h₀ := decompose_eq_zero_of_mem_gradedPositiveMulIdeal hneg (he₀ i) h le_rfl
  rw [decompose_of_mem_same 𝒜 (he₀ i)] at h₀
  exact hne h₀

include he in
/-- The idempotent `eⱼ` acts on the class of `eᵢ` by `δᵢⱼ`. -/
private theorem smul_headGenerator [DecidableEq I] (j i : I) :
    e j • headGenerator e he₀ i = if j = i then headGenerator e he₀ i else 0 := by
  rw [headGenerator, ← map_smul]
  split_ifs with hji
  · subst hji
    congr 1
    exact Subtype.ext (he.idem j).eq
  · rw [← map_zero (gradedPositiveMulQuotientMk (he₀ i))]
    congr 1
    exact Subtype.ext (he.ortho hji)

include hneg he hspan in
/-- The degree-zero piece of the head of `A eᵢ` is spanned by the class of `eᵢ`. -/
private theorem head_piece_zero (i : I) :
    (gradedPositiveMulQuotient 𝒜 (he₀ i)).grading.piece 0 =
      Submodule.span k {headGenerator e he₀ i} := by
  ext y
  rw [mem_gradedPositiveMulQuotient_piece_iff]
  refine ⟨?_, fun hy => ?_⟩
  · rintro ⟨x, -, rfl⟩
    obtain ⟨c, hc⟩ :=
      exists_eq_smul_headGenerator hneg he he₀ hspan i (gradedPositiveMulQuotientMk (he₀ i) x)
    exact hc ▸ Submodule.smul_mem _ c (Submodule.mem_span_singleton_self _)
  · obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.1 hy
    exact ⟨c • ⟨e i, Ideal.subset_span rfl⟩, Submodule.smul_mem _ c (he₀ i), by
      rw [LinearMap.map_smul_of_tower, headGenerator]⟩

include hneg he in
/-- The head of `A eᵢ` vanishes outside degree zero. -/
private theorem head_piece_eq_bot (i : I) {p : ℤ} (hp : p ≠ 0) :
    (gradedPositiveMulQuotient 𝒜 (he₀ i)).grading.piece p = ⊥ := by
  refine (Submodule.eq_bot_iff _).2 fun y hy => ?_
  obtain ⟨x, hx, rfl⟩ := (mem_gradedPositiveMulQuotient_piece_iff (he₀ i)).1 hy
  rw [gradedPositiveMulQuotientMk_eq_zero_iff]
  rcases lt_or_gt_of_ne hp with hp | hp
  · rw [hneg p hp, Submodule.mem_bot] at hx
    rw [hx]
    exact Submodule.zero_mem _
  · rw [← (mem_span_singleton_iff_mul_eq_self (he.idem i)).1 x.2]
    exact mul_mem_gradedPositiveMulIdeal 𝒜 hp hx

include hneg he hspan in
/-- **The graded dimension of `eⱼ • Sᵢ` is `δᵢⱼ`**: the graded head `Sᵢ` of `A eᵢ` is
one-dimensional, concentrated in degree zero, and `eⱼ` acts on it by `δᵢⱼ`. -/
theorem smulGradedDimension_gradedIdempotentHead [Module.Finite k A] [DecidableEq I]
    (j i : I) (hne : e i ≠ 0) :
    (gradedPositiveMulQuotient 𝒜 (he₀ i)).smulGradedDimension (e j) = if j = i then 1 else 0 := by
  ext p
  rw [GradedModuleCat.coeff_smulGradedDimension]
  by_cases hp : p = 0
  · subst hp
    rw [head_piece_zero hneg he he₀ hspan, Submodule.smul_span, Set.smul_set_singleton,
      smul_headGenerator he he₀]
    by_cases hji : j = i
    · subst hji
      rw [ite_eq_left rfl, ite_eq_left rfl,
        finrank_span_singleton (headGenerator_ne_zero hneg he₀ j hne), AddMonoidAlgebra.one_def,
        AddMonoidAlgebra.coeff_single, Finsupp.single_eq_same, Nat.cast_one]
    · simp [hji]
  · rw [head_piece_eq_bot hneg he he₀ i hp, Submodule.smul_bot', finrank_bot]
    split_ifs
    · rw [AddMonoidAlgebra.one_def, AddMonoidAlgebra.coeff_single, Finsupp.single_eq_of_ne hp,
        Nat.cast_zero]
    · simp


/-! ### Simplicity and exhaustiveness -/

include hneg he hspan in
/-- **The graded head `Sᵢ` of `A eᵢ` is a simple graded module.** It is one-dimensional, spanned by
the class of `eᵢ`, so a nonzero graded submodule is everything. -/
theorem simple_gradedIdempotentHead (i : I) (hne : e i ≠ 0) :
    Simple (gradedPositiveMulQuotient 𝒜 (he₀ i)) where
  mono_isIso_iff_nonzero {Y} f _ := by
    refine ⟨fun hf hf₀ => headGenerator_ne_zero hneg he₀ i hne ?_, fun hf₀ => ?_⟩
    · -- An isomorphism from `Y` that is zero forces the head to vanish.
      have h : 𝟙 (gradedPositiveMulQuotient 𝒜 (he₀ i)) = 0 := by
        rw [← IsIso.inv_hom_id f]
        subst hf₀
        exact Limits.comp_zero
      simpa using LinearMap.congr_fun (congrArg GradedModuleCat.Hom.hom h) (headGenerator e he₀ i)
    -- A nonzero map into the one-dimensional head is surjective.
    obtain ⟨y, hy⟩ : ∃ y, f.hom y ≠ 0 := by
      by_contra! h
      exact hf₀ (GradedModuleCat.hom_ext (LinearMap.ext h))
    obtain ⟨c, hc⟩ := exists_eq_smul_headGenerator hneg he he₀ hspan i (f.hom y)
    have hc₀ : c ≠ 0 := by
      rintro rfl
      exact hy (by rw [hc, zero_smul])
    have hsurj : Function.Surjective f.hom := fun z => by
      obtain ⟨d, rfl⟩ := exists_eq_smul_headGenerator hneg he he₀ hspan i z
      refine ⟨(d * c⁻¹) • y, ?_⟩
      rw [LinearMap.map_smul_of_tower, hc, smul_smul, mul_assoc, inv_mul_cancel₀ hc₀, mul_one]
    have : Epi f := (GradedModuleCat.epi_iff_surjective f).2 hsurj
    exact isIso_of_mono_of_epi f

variable [Fintype I] (hcomplete : CompleteOrthogonalIdempotents e)

include hneg hcomplete hspan in
/-- **Every simple finite graded module is a shift of a graded head `Sᵢ`.** If `p` is the top
degree of `M` and `m ∈ Mₚ` satisfies `eᵢ m ≠ 0`, then `x eᵢ ↦ x eᵢ m` is an isomorphism
`Sᵢ{p} ≅ M`. -/
theorem isExhaustiveGradedSimpleFamily_gradedIdempotentHead [Module.Finite k A] :
    IsExhaustiveGradedSimpleFamily fun i =>
      (⟨gradedPositiveMulQuotient 𝒜 (he₀ i),
        gradedFiniteModules_gradedPositiveMulQuotient 𝒜 (he₀ i)⟩ :
        (gradedFiniteModules 𝒜).FullSubcategory) := by
  rw [isExhaustiveGradedSimpleFamily_iff]
  intro M hM
  classical
  -- `M` has a nonzero element, hence a nonzero homogeneous piece.
  obtain ⟨x, hx⟩ : ∃ x : M.obj, x ≠ 0 := by
    by_contra! h
    exact id_nonzero M.obj (GradedModuleCat.hom_ext (LinearMap.ext h))
  have hfin := M.obj.grading.finite_piece_ne_bot
  have hne' : hfin.toFinset.Nonempty := by
    by_contra h
    apply hx
    rw [← M.obj.grading.sum_decompose_toFinset hfin x, Finset.not_nonempty_iff_eq_empty.1 h,
      Finset.sum_empty]
  -- Let `p` be the top degree of `M`.
  set p := hfin.toFinset.max' hne'
  have htop : ∀ q, p < q → M.obj.grading.piece q = ⊥ := fun q hq => by
    by_contra h
    exact (hfin.toFinset.le_max' q (hfin.mem_toFinset.2 h)).not_gt hq
  obtain ⟨m, hm, hm₀⟩ := Submodule.exists_mem_ne_zero_of_ne_bot
    (hfin.mem_toFinset.1 (hfin.toFinset.max'_mem hne'))
  -- Some `eᵢ` does not kill `m`, since the `eᵢ` sum to one.
  obtain ⟨i, hi⟩ : ∃ i, e i • m ≠ 0 := by
    by_contra! h
    apply hm₀
    rw [← one_smul A m, ← hcomplete.complete, Finset.sum_smul]
    exact Finset.sum_eq_zero fun i _ => h i
  have hm' : e i • m ∈ M.obj.grading.piece p := by
    simpa using SetLike.GradedSMul.smul_mem (B := M.obj.grading.piece) (he₀ i) hm
  -- Positive-degree elements kill `eᵢ m`, since `p` is the top degree.
  have hkill : ∀ y ∈ gradedPositiveMulIdeal 𝒜 (e i), y • (e i • m) = 0 := by
    intro y hy
    induction hy using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨q, hq, x, hx, rfl⟩ := hy
      have h := SetLike.GradedSMul.smul_mem (B := M.obj.grading.piece)
        (SetLike.GradedMul.mul_mem hx (he₀ i)) hm'
      rw [vadd_eq_add, htop _ (by omega), Submodule.mem_bot] at h
      exact h
    | zero => exact zero_smul A _
    | add y z _ _ hy hz => rw [add_smul, hy, hz, add_zero]
    | smul a y _ hy => rw [smul_eq_mul, mul_smul, hy, smul_zero]
  -- The induced map `Sᵢ{p} ⟶ M` is a nonzero monomorphism into a simple object.
  let φ : (gradedPositiveMulQuotient 𝒜 (he₀ i)).shiftObj p ⟶ M.obj :=
    GradedModuleCat.ofHom (gradedPositiveMulQuotientLift (he₀ i) (e i • m) hkill) <|
      LinearMap.isHomogeneous_def.2 fun q y hy => by
        rw [GradedModuleCat.mem_shiftObj_piece_iff] at hy
        obtain ⟨x, hx, rfl⟩ := (mem_gradedPositiveMulQuotient_piece_iff (he₀ i)).1 hy
        have h := SetLike.GradedSMul.smul_mem (B := M.obj.grading.piece) hx hm'
        rw [vadd_eq_add, sub_add_cancel] at h
        rwa [gradedPositiveMulQuotientLift_gradedPositiveMulQuotientMk, add_zero]
  have hφg : φ.hom (headGenerator e he₀ i) = e i • m := by
    rw [GradedModuleCat.hom_ofHom, headGenerator,
      gradedPositiveMulQuotientLift_gradedPositiveMulQuotientMk,
      ← mul_smul, (hcomplete.idem i).eq]
  have hinj : Function.Injective φ.hom := by
    rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
    intro y hy
    obtain ⟨c, rfl⟩ :=
      exists_eq_smul_headGenerator hneg hcomplete.toOrthogonalIdempotents he₀ hspan i y
    rw [LinearMap.mem_ker, LinearMap.map_smul_of_tower, hφg, smul_eq_zero] at hy
    rw [hy.resolve_right hi, zero_smul]
  have : Mono φ := (GradedModuleCat.mono_iff_injective φ).2 hinj
  have : Epi φ := epi_of_nonzero_to_simple fun h => hi <| by
    rw [← hφg, h, GradedModuleCat.hom_zero, LinearMap.zero_apply]
  have : IsIso φ := isIso_of_mono_of_epi φ
  exact ⟨i, p, ⟨(asIso φ).symm⟩⟩

end Field

end TauCeti
