/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Projective.Basic
public import Mathlib.RingTheory.FiniteType
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.RingTheory.MvPolynomial.Homogeneous
public import TauCeti.RingTheory.GradedAlgebra.Homogeneous.Quotient

/-!
# The homogeneous coordinate ring of a Weierstrass curve

For a Weierstrass curve `W'` over a commutative ring `R`, this file defines the homogeneous
coordinate ring

`R[X, Y, Z] ⧸ (Y²Z + a₁XYZ + a₃YZ² - (X³ + a₂X²Z + a₄XZ² + a₆Z³))`

of the projective cubic, graded by total degree. Its `Proj` is the projective Weierstrass model
`WeierstrassCurve.projModel` of `TauCeti/AlgebraicGeometry/EllipticCurve/Scheme/ProjModel.lean`.
The grading is induced from the grading of `R[X, Y, Z]` by total degree, using
`TauCeti.GradedAlgebra.gradedAlgebraQuotientPiece`.

## Main definitions

* `WeierstrassCurve.Projective.CoordinateRing W'`: the quotient of `R[X, Y, Z]` by the
  homogeneous Weierstrass polynomial `W'.polynomial`.
* `WeierstrassCurve.Projective.grading W'`: its grading by total degree, registered as a
  `GradedAlgebra` instance.
* `WeierstrassCurve.Projective.gradingZeroEquiv W'`: the degree-zero part of the coordinate ring
  is the base ring `R`.
* `WeierstrassCurve.Projective.evalZero W'`: evaluation at the point `[0 : 1 : 0]`.
* `WeierstrassCurve.Projective.evalHom W' g hP`: evaluation at a solution `P` of the projective
  equation of `W'.map g`, for a ring homomorphism `g`.
* `WeierstrassCurve.Projective.coord W' i`: the class of the homogeneous coordinate `Xᵢ`, of
  degree one.

## Main results

* `WeierstrassCurve.Projective.isHomogeneous_polynomial`: the Weierstrass polynomial in projective
  coordinates is homogeneous of degree `3`, so it cuts out a homogeneous ideal.
* `WeierstrassCurve.Projective.bijective_algebraMap_grading_zero`: the degree-zero part of the
  homogeneous coordinate ring is `R`; hence `Proj` of it lies over `Spec R`.
* `WeierstrassCurve.Projective.irrelevant_le_span_range_coord`: the three coordinates generate the
  irrelevant ideal, so the standard charts `D₊(Xᵢ)` cover `Proj` of the coordinate ring.
* `WeierstrassCurve.Projective.equation_coord`: the classes of the coordinates are a solution of the
  equation over the coordinate ring, nonzero over a nontrivial ring (`coord_ne_zero`).
* `WeierstrassCurve.Projective.eq_evalHom` and `WeierstrassCurve.Projective.ringHom_ext`: a ring
  homomorphism out of the coordinate ring is determined by its values on `R` and on the
  coordinates; `evalHom` is the one with prescribed values (`evalHom_comp_algebraMap`,
  `evalHom_comp_coord`).

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*, III.1][silverman2009]
* N. M. Katz and B. Mazur, *Arithmetic Moduli of Elliptic Curves*, 2.2.
-/

public section

namespace WeierstrassCurve.Projective

open MvPolynomial

attribute [local instance] MvPolynomial.gradedAlgebra

variable {R : Type*} [CommRing R] (W' : Projective R)

/-- The Weierstrass polynomial `Y²Z + a₁XYZ + a₃YZ² - (X³ + a₂X²Z + a₄XZ² + a₆Z³)` in projective
coordinates is homogeneous of degree `3`. -/
theorem isHomogeneous_polynomial : W'.polynomial.IsHomogeneous 3 := by
  have hX (i : Fin 3) : (X i : MvPolynomial (Fin 3) R).IsHomogeneous 1 := isHomogeneous_X R i
  have hC (r : R) : (C r : MvPolynomial (Fin 3) R).IsHomogeneous 0 := isHomogeneous_C _ r
  rw [polynomial]
  refine ((((hX 1).pow 2).mul (hX 2)).add ((((hC _).mul (hX 0)).mul (hX 1)).mul (hX 2))).add
    (((hC _).mul (hX 1)).mul ((hX 2).pow 2)) |>.sub ?_
  exact ((((hX 0).pow 3).add (((hC _).mul ((hX 0).pow 2)).mul (hX 2))).add
    (((hC _).mul (hX 0)).mul ((hX 2).pow 2))).add ((hC _).mul ((hX 2).pow 3))

/-- The homogeneous coordinate ring `R[X, Y, Z] ⧸ (W'(X, Y, Z))` of the projective Weierstrass
cubic. -/
abbrev CoordinateRing : Type _ :=
  MvPolynomial (Fin 3) R ⧸ Ideal.span {W'.polynomial}

/-- The ideal generated by the Weierstrass polynomial is homogeneous for the grading of
`R[X, Y, Z]` by total degree. -/
theorem isHomogeneous_span_polynomial :
    (Ideal.span {W'.polynomial}).IsHomogeneous (homogeneousSubmodule (Fin 3) R) := by
  refine Ideal.homogeneous_span _ _ fun p hp => ?_
  rw [Set.mem_singleton_iff.mp hp]
  exact ⟨3, W'.isHomogeneous_polynomial⟩

/-- The grading of the homogeneous coordinate ring by total degree: the degree-`n` part is the
image of the homogeneous polynomials of degree `n`. -/
@[expose] noncomputable def grading (n : ℕ) : Submodule R W'.CoordinateRing :=
  TauCeti.GradedAlgebra.quotientPiece (homogeneousSubmodule (Fin 3) R) _ n

/-- Membership in a graded piece of the homogeneous coordinate ring is being the class of a
homogeneous polynomial of that degree. -/
theorem mem_grading_iff {n : ℕ} {x : W'.CoordinateRing} :
    x ∈ W'.grading n ↔
      ∃ p : MvPolynomial (Fin 3) R, p.IsHomogeneous n ∧ Ideal.Quotient.mk _ p = x :=
  TauCeti.GradedAlgebra.mem_quotientPiece_iff _ _

/-- The class of a homogeneous polynomial of degree `n` lies in the degree-`n` part. -/
theorem mk_mem_grading {n : ℕ} {p : MvPolynomial (Fin 3) R} (hp : p.IsHomogeneous n) :
    Ideal.Quotient.mk (Ideal.span {W'.polynomial}) p ∈ W'.grading n :=
  TauCeti.GradedAlgebra.mk_mem_quotientPiece _ _ hp

/-- The homogeneous coordinate ring is graded by total degree. -/
noncomputable instance : GradedAlgebra W'.grading := by
  unfold grading
  exact TauCeti.GradedAlgebra.gradedAlgebraQuotientPiece _ _ W'.isHomogeneous_span_polynomial

/-- The homogeneous coordinate ring is of finite type over its degree-zero part. -/
instance : Algebra.FiniteType (W'.grading 0) W'.CoordinateRing :=
  -- `R` acts on the coordinate ring through the degree-zero part, by left multiplication.
  haveI : IsScalarTower R (W'.grading 0) W'.CoordinateRing :=
    ⟨fun r a x => smul_mul_assoc r (a : W'.CoordinateRing) x⟩
  .of_restrictScalars_finiteType R _ _

/-- The degree-zero part of the homogeneous coordinate ring is the base ring: the Weierstrass
polynomial has no constant term, so no nonzero constant is a multiple of it, and the degree-zero
polynomials are the constants. -/
theorem bijective_algebraMap_grading_zero : Function.Bijective (algebraMap R (W'.grading 0)) := by
  refine ⟨fun r s h => ?_, fun x => ?_⟩
  · have hrs : C (r - s) ∈ Ideal.span {W'.polynomial} := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub]
      exact sub_eq_zero.mpr congr(($h : W'.CoordinateRing))
    obtain ⟨q, hq⟩ := Ideal.mem_span_singleton'.mp hrs
    have hF : constantCoeff W'.polynomial = 0 := by simp [polynomial]
    simpa [hF, sub_eq_zero] using congr(constantCoeff $hq).symm
  · obtain ⟨p, hp, hpx⟩ := W'.mem_grading_iff.mp x.2
    rw [← totalDegree_zero_iff_isHomogeneous, totalDegree_eq_zero_iff_eq_C] at hp
    refine ⟨p.coeff 0, Subtype.ext ?_⟩
    rw [← hpx, hp]
    simp [IsScalarTower.algebraMap_apply R (MvPolynomial (Fin 3) R) W'.CoordinateRing]

/-- The degree-zero part of the homogeneous coordinate ring is isomorphic to the base ring. -/
noncomputable def gradingZeroEquiv : R ≃ₐ[R] W'.grading 0 :=
  AlgEquiv.ofBijective (Algebra.ofId R _) W'.bijective_algebraMap_grading_zero

@[simp]
theorem gradingZeroEquiv_apply (r : R) : W'.gradingZeroEquiv r = algebraMap R (W'.grading 0) r :=
  W'.gradingZeroEquiv.commutes r

/-- The class of the homogeneous coordinate `Xᵢ` in the homogeneous coordinate ring. -/
noncomputable abbrev coord (i : Fin 3) : W'.CoordinateRing :=
  Ideal.Quotient.mk _ (X i)

/-- Each homogeneous coordinate has degree one. -/
theorem coord_mem_grading (i : Fin 3) : W'.coord i ∈ W'.grading 1 :=
  W'.mk_mem_grading (isHomogeneous_X R i)

/-- The irrelevant ideal of the homogeneous coordinate ring is generated by the three
coordinates: every homogeneous element of positive degree is the class of a polynomial without
constant term. -/
theorem irrelevant_le_span_range_coord :
    (HomogeneousIdeal.irrelevant W'.grading).toIdeal ≤ Ideal.span (Set.range W'.coord) := by
  rw [HomogeneousIdeal.irrelevant_eq_span, Ideal.span_le]
  intro x hx
  simp only [Set.mem_iUnion, SetLike.mem_coe] at hx
  obtain ⟨n, hn, hx⟩ := hx
  obtain ⟨q, hq, rfl⟩ := W'.mem_grading_iff.mp hx
  -- a homogeneous polynomial of positive degree lies in the ideal generated by the variables
  have hqX : q ∈ Ideal.span (X '' Set.univ) := by
    refine mem_ideal_span_X_image.mpr fun m hm ↦ ?_
    obtain ⟨k, hk⟩ : ∃ k, m k ≠ 0 := by
      by_contra! h
      have hm0 : m = 0 := Finsupp.ext h
      exact hn.ne' ((hq (mem_support_iff.mp hm)).symm.trans (by rw [hm0, map_zero]))
    exact ⟨k, Set.mem_univ _, hk⟩
  have := Ideal.mem_map_of_mem (Ideal.Quotient.mk (Ideal.span {W'.polynomial})) hqX
  rwa [Ideal.map_span, Set.image_univ, ← Set.range_comp] at this

/-- Evaluation of the homogeneous coordinate ring at the point `[0 : 1 : 0]`. -/
noncomputable def evalZero : W'.CoordinateRing →ₐ[R] R :=
  Ideal.Quotient.liftₐ _ (aeval ![0, 1, 0]) fun p hp => by
    obtain ⟨q, rfl⟩ := Ideal.mem_span_singleton'.mp hp
    have h : eval ![0, 1, 0] W'.polynomial = 0 := W'.equation_zero
    simp [h]

@[simp]
theorem evalZero_mk (p : MvPolynomial (Fin 3) R) :
    W'.evalZero (Ideal.Quotient.mk _ p) = eval ![0, 1, 0] p := by
  simp [evalZero]

/-- The base ring acts faithfully on the homogeneous coordinate ring, as on the affine coordinate
ring `WeierstrassCurve.Affine.CoordinateRing`. -/
instance : FaithfulSMul R W'.CoordinateRing :=
  -- evaluation at `[0 : 1 : 0]` is a retraction of the structure map
  (faithfulSMul_iff_algebraMap_injective R _).mpr <|
    Function.LeftInverse.injective W'.evalZero.commutes

section Eval

variable {S : Type*} [CommRing S] (g : R →+* S) {P : Fin 3 → S} (hP : (W'.map g).Equation P)

/-- Evaluation of the homogeneous coordinate ring at a solution `P` of the projective Weierstrass
equation of `W'.map g`, for a ring homomorphism `g : R →+* S`: the ring homomorphism
`R[X₀, X₁, X₂] ⧸ (W'(X₀, X₁, X₂)) →+* S` that is `g` on `R` and sends the class of `Xᵢ` to
`Pᵢ`. -/
noncomputable def evalHom : W'.CoordinateRing →+* S :=
  Ideal.Quotient.lift _ (eval₂Hom g P) <| (RingHom.ker _).span_singleton_le_iff_mem.mpr <| by
    simpa [Equation] using hP

/-- `evalHom` sends the class of a polynomial `p` to its value `p(P)`, the coefficients of `p`
being mapped to `S` by `g`. -/
@[simp]
theorem evalHom_mk (p : MvPolynomial (Fin 3) R) :
    W'.evalHom g hP (Ideal.Quotient.mk _ p) = eval₂ g P p :=
  Ideal.Quotient.lift_mk _ _ _

/-- `evalHom` restricts to `g` on the base ring `R`. -/
theorem evalHom_comp_algebraMap : (W'.evalHom g hP).comp (algebraMap R W'.CoordinateRing) = g :=
  -- `algebraMap R W'.CoordinateRing r` is the class of the constant polynomial `C r`
  RingHom.ext fun r ↦ (W'.evalHom_mk g hP (C r)).trans (eval₂_C g P r)

/-- `evalHom` sends the class of each coordinate `Xᵢ` to `Pᵢ`. -/
theorem evalHom_comp_coord : W'.evalHom g hP ∘ W'.coord = P :=
  funext fun i ↦ (W'.evalHom_mk g hP (X i)).trans (eval₂_X g P i)

/-- Pushing the curve over the homogeneous coordinate ring forward along `evalHom` gives the curve
`W'.map g`. -/
theorem map_evalHom :
    (W'.map (algebraMap R W'.CoordinateRing)).map (W'.evalHom g hP) = W'.map g :=
  (W'.map_map _ _).trans (congrArg W'.map (W'.evalHom_comp_algebraMap g hP))

/-- Two ring homomorphisms out of the homogeneous coordinate ring are equal when they agree on the
base ring and on the classes of the coordinates. -/
theorem ringHom_ext {f₁ f₂ : W'.CoordinateRing →+* S}
    (h₁ : f₁.comp (algebraMap R W'.CoordinateRing) = f₂.comp (algebraMap R W'.CoordinateRing))
    (h₂ : f₁ ∘ W'.coord = f₂ ∘ W'.coord) : f₁ = f₂ :=
  Ideal.Quotient.ringHom_ext <|
    MvPolynomial.ringHom_ext (fun r ↦ RingHom.congr_fun h₁ r) (fun i ↦ congrFun h₂ i)

/-- `evalHom` is the only ring homomorphism out of the homogeneous coordinate ring that restricts to
`g` on `R` and sends the class of each coordinate `Xᵢ` to `Pᵢ`. -/
theorem eq_evalHom {f : W'.CoordinateRing →+* S} (h₁ : f.comp (algebraMap R W'.CoordinateRing) = g)
    (h₂ : f ∘ W'.coord = P) : f = W'.evalHom g hP :=
  W'.ringHom_ext (h₁.trans (W'.evalHom_comp_algebraMap g hP).symm)
    (h₂.trans (W'.evalHom_comp_coord g hP).symm)

end Eval

/-- The classes of the homogeneous coordinates form a solution of the Weierstrass equation over the
homogeneous coordinate ring. -/
theorem equation_coord : (W'.map (algebraMap R W'.CoordinateRing)).Equation W'.coord := by
  -- `coord` is the quotient map on the variables, so evaluating there is the quotient map
  change (W'.map _).Equation (Ideal.Quotient.mkₐ R _ ∘ X)
  rw [Equation, map_polynomial, eval_map, ← aeval_def, ← aeval_unique, Ideal.Quotient.mkₐ_eq_mk,
    Ideal.Quotient.mk_singleton_self]

/-- Over a nontrivial ring, the solution given by the classes of the homogeneous coordinates is
nonzero. -/
theorem coord_ne_zero [Nontrivial R] : W'.coord ≠ 0 :=
  fun h ↦ by simpa using congrArg W'.evalZero (congrFun h 1)

end WeierstrassCurve.Projective
