/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
module

public import TauCeti.Algebra.Order.Ring.Ordering.Extension
public import Mathlib.Algebra.Order.Field.Basic
public import Mathlib.Algebra.Order.Hom.Monoid
public import Mathlib.Algebra.QuadraticAlgebra.Basic

/-! # Preserving an order under field extension

The cone generated by nonnegative base elements and extension-field squares
describes precisely the obstruction to extending an order. For a positive
quadratic extension, its scalar coordinate proves that this cone is proper.
The `extensionCone` namespace groups membership, evaluation, and order-extension results.
-/

public section

namespace TauCeti.RealClosure

variable {K L : Type*}

section CommSemiring

variable [CommSemiring K] [PartialOrder K] [IsOrderedRing K] [CommSemiring L]

/-- Nonnegative scalar multiples of squares in an extension form a submonoid. -/
def weightedSquares (f : K →+* L) : Submonoid L where
  carrier := {x | ∃ a : K, 0 ≤ a ∧ ∃ y : L, x = f a * y ^ 2}
  one_mem' := ⟨1, zero_le_one, 1, by simp⟩
  mul_mem' := by
    rintro x y ⟨a, ha, u, rfl⟩ ⟨b, hb, v, rfl⟩
    exact ⟨a * b, mul_nonneg ha hb, u * v, by rw [map_mul]; ring⟩

@[simp] theorem mem_weightedSquares (f : K →+* L) {x : L} :
    x ∈ weightedSquares f ↔ ∃ a : K, 0 ≤ a ∧ ∃ y : L, x = f a * y ^ 2 := (Iff.rfl)

/-- Finite sums of nonnegative scalar multiples of squares. -/
def extensionCone (f : K →+* L) : Subsemiring L := (weightedSquares f).subsemiringClosure

/-- A generating weighted square belongs to the extension cone. -/
theorem extensionCone.weightedSquares_subset (f : K →+* L) :
    (weightedSquares f : Set L) ⊆ extensionCone f := fun _ hx =>
  (Submonoid.subsemiringClosure_mem _).mpr (AddSubmonoid.subset_closure hx)

/-- The generated cone is contained in a subsemiring exactly when its generators are. -/
@[simp] theorem extensionCone.le_iff (f : K →+* L) {S : Subsemiring L} :
    extensionCone f ≤ S ↔ (weightedSquares f : Set L) ⊆ S := by
  rw [extensionCone, Submonoid.subsemiringClosure_eq_closure, Subsemiring.closure_le]

/-- Induction on finite sums of generating weighted squares. -/
@[elab_as_elim] theorem extensionCone.induction (f : K →+* L)
    {motive : (x : L) → x ∈ extensionCone f → Prop}
    (mem : ∀ x (hx : x ∈ weightedSquares f), motive x (extensionCone.weightedSquares_subset f hx))
    (zero : motive 0 (zero_mem _))
    (add : ∀ x y hx hy, motive x hx → motive y hy → motive (x + y) (add_mem hx hy))
    {x : L} (hx : x ∈ extensionCone f) : motive x hx :=
  AddSubmonoid.closure_induction
    (motive := fun x hx => motive x ((Submonoid.subsemiringClosure_mem _).mpr hx))
    mem zero (fun x y _ _ => add x y _ _) ((Submonoid.subsemiringClosure_mem _).mp hx)

/-- Every square belongs to the extension cone. -/
theorem extensionCone.mul_self_mem (f : K →+* L) (x : L) : x * x ∈ extensionCone f :=
  extensionCone.weightedSquares_subset f ⟨1, zero_le_one, x, by simp [pow_two]⟩

/-- The image of a nonnegative base element belongs to the extension cone. -/
theorem extensionCone.map_mem_of_nonneg (f : K →+* L) {x : K} (hx : 0 ≤ x) :
    f x ∈ extensionCone f :=
  extensionCone.weightedSquares_subset f ⟨x, hx, 1, by simp⟩

/-- Ring homomorphisms carry the cone of an extension into the cone of the composite
extension. -/
theorem extensionCone.map_mem_comp {M : Type*} [CommSemiring M] (f : K →+* L) (g : L →+* M)
    {x : L} (hx : x ∈ extensionCone f) : g x ∈ extensionCone (g.comp f) :=
  ((extensionCone.le_iff f (S := (extensionCone (g.comp f)).comap g)).mpr (by
    rintro _ ⟨a, ha, y, rfl⟩
    exact extensionCone.weightedSquares_subset _ ⟨a, ha, g y, by simp⟩)) hx

/-- Algebra homomorphisms preserve the cone generated by the base ordering. -/
theorem extensionCone.map_mem {M : Type*} [CommSemiring M] [Algebra K L] [Algebra K M]
    (f : L →ₐ[K] M) {x : L} (hx : x ∈ extensionCone (algebraMap K L)) :
    f x ∈ extensionCone (algebraMap K M) := by
  simpa only [AlgHom.comp_algebraMap, RingHom.coe_coe] using
    extensionCone.map_mem_comp (algebraMap K L) (f : L →+* M) hx

/-- An additive map nonnegative on the generating weighted squares is
nonnegative on the entire extension cone. -/
theorem extensionCone.map_nonneg {M : Type*} [AddCommMonoid M] [Preorder M]
    [IsOrderedAddMonoid M] (f : K →+* L) (g : L →+ M)
    (hg : ∀ a : K, 0 ≤ a → ∀ y : L, 0 ≤ g (f a * y ^ 2))
    {x : L} (hx : x ∈ extensionCone f) : 0 ≤ g x := by
  induction hx using extensionCone.induction f with
  | mem x hx =>
    obtain ⟨a, ha, y, rfl⟩ := hx
    exact hg a ha y
  | zero => simp
  | add x y _ _ hx hy => simpa only [map_add] using add_nonneg hx hy

end CommSemiring

/-- Every element of the generated cone is nonnegative in any order extending
the base order. -/
theorem extensionCone.nonneg [CommSemiring K] [PartialOrder K] [IsOrderedRing K]
    [CommRing L] [LinearOrder L] [IsOrderedRing L]
    (f : K →+* L) (hf : Monotone f) {x : L} (hx : x ∈ extensionCone f) : 0 ≤ x :=
  extensionCone.map_nonneg f (AddMonoidHom.id L)
    (fun _ ha y => mul_nonneg (by simpa only [map_zero] using hf ha) (sq_nonneg y)) hx

/-- The ordering of the base field extends to a linear ordering of the extension field
exactly when its generated cone is proper. -/
theorem extensionCone.exists_linearOrder_iff [Field K] [PartialOrder K] [IsOrderedRing K]
    [Field L] (f : K →+* L) :
    (∃ o : LinearOrder L, letI := o
      IsStrictOrderedRing L ∧ StrictMono f) ↔ -1 ∉ extensionCone f := by
  constructor
  · rintro ⟨o, ho, hf⟩ h
    let := o
    let := ho
    have := extensionCone.nonneg f hf.monotone h
    norm_num at this
  · intro h
    let P : RingPreordering L :=
      { extensionCone f with
        mem_of_isSquare' := by
          rintro x ⟨y, rfl⟩
          exact extensionCone.mul_self_mem f y
        neg_one_notMem' := h }
    obtain ⟨o, ho, hP⟩ := RingPreordering.exists_linearOrder P
    let := o
    refine ⟨o, ho, ?_⟩
    exact ((monotone_iff_map_nonneg f).mpr fun x hx =>
      hP _ (extensionCone.map_mem_of_nonneg f hx)).strictMono_of_injective f.injective

/-- Adjoining a square root of a nonnegative element does not force a sum of weighted
squares to equal `-1`. -/
theorem extensionCone.neg_one_notMem_quadraticAlgebra [CommRing K] [LinearOrder K]
    [IsOrderedRing K] [Nontrivial K] {a : K} (ha : 0 ≤ a) :
    -1 ∉ extensionCone (algebraMap K (QuadraticAlgebra K a 0)) := by
  intro h
  have := extensionCone.map_nonneg _
    (QuadraticAlgebra.reₗ (R := K) (a := a) (b := 0)).toAddMonoidHom
    (fun b hb y => by
      simpa [pow_two, QuadraticAlgebra.re_mul, mul_assoc] using
        mul_nonneg hb (add_nonneg (mul_self_nonneg y.re) (mul_nonneg ha (mul_self_nonneg y.im)))) h
  norm_num [QuadraticAlgebra.re_one] at this

/-- A nonnegative nonsquare can be adjoined while preserving the base ordering.
Nonsquareness excludes zero, so the radicand is necessarily positive. -/
theorem _root_.QuadraticAlgebra.exists_linearOrder [Field K] [LinearOrder K]
    [IsStrictOrderedRing K] {a : K} (ha : 0 ≤ a) [Fact (¬ IsSquare a)] :
    ∃ o : LinearOrder (QuadraticAlgebra K a 0), letI := o
      IsStrictOrderedRing (QuadraticAlgebra K a 0) ∧
        StrictMono (algebraMap K (QuadraticAlgebra K a 0)) :=
  (extensionCone.exists_linearOrder_iff _).mpr (extensionCone.neg_one_notMem_quadraticAlgebra ha)

end TauCeti.RealClosure
