/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.GradedAlgebra.HomogeneousLocalization.Basic
public import TauCeti.RingTheory.Ideal.AffineBlowup
public import TauCeti.RingTheory.ReesAlgebra.Grading

/-!
# The affine charts of the blowup algebra

Let `I` be an ideal of a commutative ring `R` and `a ∈ I`. Then `a` gives an element `a t` of
degree one of the Rees algebra `R[It]`, and the standard affine open `D₊(a t)` of
`Proj R[It]`, the blowup of `Spec R` along `V(I)`, is the spectrum of the homogeneous
localization `R[It]_(a t)`, the ring of degree zero fractions `(b tⁿ)/(a t)ⁿ` with `b ∈ Iⁿ`.

This file identifies that ring with the affine blowup algebra `R[I/a]` of
`TauCeti/RingTheory/Ideal/AffineBlowup.lean`, the subalgebra of `R_a` generated by the fractions
`i/a` with `i ∈ I`: the fraction `(b tⁿ)/(a t)ⁿ` corresponds to `b/aⁿ`. Thus the explicit
algebras `R[I/a]` are the coordinate rings of the charts of the blowup.

## Main definitions

* `reesAlgebra.awayEquivAffineBlowup S ha`: the isomorphism `R[It]_(a t) ≃ₐ[R] R[I/a]`, for a
  localization `S` of `R` away from `a`.

## Main results

* `reesAlgebra.algebraMap_pow_mul_awayEquivAffineBlowup_mk`: the fraction `x/(a t)ⁿ`, with `x`
  homogeneous of degree `n`, corresponds to the fraction `b/aⁿ` of `S`, where `b` is the
  coefficient of `x`.
* `reesAlgebra.awayEquivAffineBlowup_apply_mk_monomialDegreeOne`: the fraction `(i t)/(a t)`
  corresponds to the generator `i/a` of `R[I/a]`.

## References

* [The Stacks Project, Section *Blowing up*](https://stacks.math.columbia.edu/tag/01OF), in
  particular [Lemma 0804](https://stacks.math.columbia.edu/tag/0804) for the affine charts.
-/

public section

open Polynomial HomogeneousLocalization TauCeti.Localization

namespace reesAlgebra

variable {R : Type*} [CommRing R] {I : Ideal R} {a : R}

variable (S : Type*) [CommRing S] [Algebra R S] [IsLocalization.Away a S]

variable (a) in
/-- Evaluation of the Rees algebra at `t = 1/a`, an `R`-algebra map `R[It] → S`. -/
private noncomputable def evalInv : reesAlgebra I →ₐ[R] S :=
  (aeval (IsLocalization.Away.invSelf a)).comp (reesAlgebra I).val

private theorem evalInv_of_mem_grade {n : ℕ} {x : reesAlgebra I} (hx : x ∈ grade I n) :
    algebraMap R S a ^ n * evalInv a S x = algebraMap R S ((x : R[X]).coeff n) := by
  -- Evaluating the monomial `b Xⁿ` at `1/a` gives `b (1/a)ⁿ`.
  have hev : evalInv a S x =
      algebraMap R S ((x : R[X]).coeff n) * IsLocalization.Away.invSelf a ^ n := by
    simpa [evalInv] using
      congr_arg (aeval (IsLocalization.Away.invSelf a))
        (mem_grade_iff_monomial_coeff.mp hx).symm
  rw [hev, mul_left_comm, ← mul_pow, IsLocalization.Away.mul_invSelf, one_pow, mul_one]

private theorem evalInv_monomialDegreeOne (ha : a ∈ I) :
    evalInv a S (monomialDegreeOne ha) = 1 := by
  simp [evalInv, IsLocalization.Away.mul_invSelf]

/-- The `R`-algebra map `R[It]_(a t) → S` sending `x/(a t)ⁿ` to `x(1/a)`. -/
private noncomputable def awayToLocalization (ha : a ∈ I) :
    Away (grade I) (monomialDegreeOne ha) →ₐ[R] S where
  __ := Away.lift (grade I) (evalInv a S).toRingHom
    (by simpa only [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, evalInv_monomialDegreeOne]
      using (isUnit_one : IsUnit (1 : S)))
  commutes' r := by
    simp only [RingHom.toFun_eq_coe]
    rw [HomogeneousLocalization.algebraMap_eq_comp, RingHom.comp_apply,
      ← HomogeneousLocalization.algebraMap_eq, Away.lift_algebraMap,
      SetLike.GradeZero.coe_algebraMap]
    exact (evalInv a S).commutes r

private theorem awayToLocalization_mk (ha : a ∈ I) {n : ℕ} {x : reesAlgebra I}
    (hx : x ∈ grade I (n • 1)) :
    awayToLocalization S ha (Away.mk (grade I) (monomialDegreeOne_mem_grade ha) n x hx) =
      evalInv a S x := by
  simp [awayToLocalization, evalInv_monomialDegreeOne]

private theorem algebraMap_pow_mul_awayToLocalization_mk (ha : a ∈ I) {n : ℕ}
    {x : reesAlgebra I} (hx : x ∈ grade I (n • 1)) :
    algebraMap R S a ^ n *
        awayToLocalization S ha (Away.mk (grade I) (monomialDegreeOne_mem_grade ha) n x hx) =
      algebraMap R S ((x : R[X]).coeff n) := by
  rw [awayToLocalization_mk]
  exact evalInv_of_mem_grade S (by simpa using hx)

private theorem awayToLocalization_injective (ha : a ∈ I) :
    Function.Injective (awayToLocalization S ha) := by
  refine (injective_iff_map_eq_zero _).mpr fun z hz ↦ ?_
  obtain ⟨n, x, hx, rfl⟩ := Away.mk_surjective (grade I) (monomialDegreeOne_mem_grade ha) z
  have hx' : x ∈ grade I n := by simpa using hx
  have h := algebraMap_pow_mul_awayToLocalization_mk S ha hx
  rw [hz, mul_zero, eq_comm, IsLocalization.map_eq_zero_iff (Submonoid.powers a)] at h
  obtain ⟨⟨_, k, rfl⟩, hk⟩ := h
  -- The numerator `x` is killed by `(a t)ᵏ` in the Rees algebra.
  have hxk : monomialDegreeOne ha ^ k * x = 0 := by
    refine Subtype.ext ?_
    push_cast [coe_monomialDegreeOne]
    rw [← mem_grade_iff_monomial_coeff.mp hx', monomial_pow, monomial_mul_monomial, one_mul, hk,
      map_zero]
  ext1
  rw [Away.val_mk, val_zero, Localization.mk_eq_mk', IsLocalization.mk'_eq_zero_iff]
  exact ⟨⟨_, k, rfl⟩, hxk⟩

private theorem awayToLocalization_mem (ha : a ∈ I)
    (z : Away (grade I) (monomialDegreeOne ha)) :
    awayToLocalization S ha z ∈ I.affineBlowup a S := by
  obtain ⟨n, x, hx, rfl⟩ := Away.mk_surjective (grade I) (monomialDegreeOne_mem_grade ha) z
  exact (Ideal.mem_affineBlowup_iff ha).mpr ⟨n, _, (mem_reesAlgebra_iff I _).mp x.2 n,
    algebraMap_pow_mul_awayToLocalization_mk S ha hx⟩

private theorem exists_awayToLocalization_eq (ha : a ∈ I) {w : S}
    (hw : w ∈ I.affineBlowup a S) : ∃ z, awayToLocalization S ha z = w := by
  obtain ⟨k, y, hy, hyw⟩ := (Ideal.mem_affineBlowup_iff ha).mp hw
  have hx : (⟨monomial k y, monomial_mem.mpr hy⟩ : reesAlgebra I) ∈ grade I (k • 1) := by
    simpa using monomial_mem_grade hy
  refine ⟨Away.mk (grade I) (monomialDegreeOne_mem_grade ha) k _ hx,
    ((IsLocalization.Away.algebraMap_isUnit (S := S) a).pow k).mul_left_cancel ?_⟩
  rw [algebraMap_pow_mul_awayToLocalization_mk, hyw, coeff_monomial_same]

private theorem bijective_awayToLocalization_codRestrict (ha : a ∈ I) :
    Function.Bijective
      ((awayToLocalization S ha).codRestrict _ (awayToLocalization_mem S ha)) :=
  ⟨fun _ _ h ↦ awayToLocalization_injective S ha (congr_arg Subtype.val h),
    fun w ↦ (exists_awayToLocalization_eq S ha w.2).imp fun _ h ↦ Subtype.ext h⟩

/-- **The affine charts of the blowup.** For `a ∈ I`, the homogeneous localization
`R[It]_(a t)` of the Rees algebra, the coordinate ring of the standard affine open `D₊(a t)` of
`Proj R[It]`, is isomorphic to the affine blowup algebra `R[I/a]`; the fraction `x/(a t)ⁿ`
corresponds to `b/aⁿ`, where `x = b tⁿ`. The isomorphism preserves coefficients from `R`. -/
noncomputable def awayEquivAffineBlowup (ha : a ∈ I) :
    Away (grade I) (monomialDegreeOne ha) ≃ₐ[R] I.affineBlowup a S :=
  AlgEquiv.ofBijective _ (bijective_awayToLocalization_codRestrict S ha)

/-- As an element of `S`, the image of `z` under `awayEquivAffineBlowup` is
`awayToLocalization S ha z`: the isomorphism is `awayToLocalization` with its codomain restricted
to `R[I/a]`. -/
private theorem coe_awayEquivAffineBlowup (ha : a ∈ I)
    (z : Away (grade I) (monomialDegreeOne ha)) :
    (awayEquivAffineBlowup S ha z : S) = awayToLocalization S ha z := by
  rw [awayEquivAffineBlowup, AlgEquiv.ofBijective_apply, AlgHom.coe_codRestrict]

/-- The fraction `x/(a t)ⁿ`, for `x = b tⁿ` homogeneous of degree `n`, corresponds to the element
`b/aⁿ` of `R[I/a]`. -/
theorem algebraMap_pow_mul_awayEquivAffineBlowup_mk (ha : a ∈ I) {n : ℕ} {x : reesAlgebra I}
    (hx : x ∈ grade I (n • 1)) :
    algebraMap R S a ^ n *
        (awayEquivAffineBlowup S ha
          (Away.mk (grade I) (monomialDegreeOne_mem_grade ha) n x hx) : S) =
      algebraMap R S ((x : R[X]).coeff n) := by
  rw [coe_awayEquivAffineBlowup, algebraMap_pow_mul_awayToLocalization_mk]

/-- The fraction `(i t)/(a t)` corresponds to the generator `i/a` of `R[I/a]`. -/
@[simp]
theorem awayEquivAffineBlowup_apply_mk_monomialDegreeOne (ha : a ∈ I) {i : R} (hi : i ∈ I) :
    awayEquivAffineBlowup S ha (Away.mk (grade I) (monomialDegreeOne_mem_grade ha) 1
        (monomialDegreeOne hi) (by simpa using monomialDegreeOne_mem_grade hi)) =
      ⟨divBy i a, Ideal.divBy_mem_affineBlowup hi⟩ := by
  refine Subtype.ext ((IsLocalization.Away.algebraMap_isUnit (S := S) a).mul_left_cancel ?_)
  rw [← pow_one (algebraMap R S a), algebraMap_pow_mul_awayEquivAffineBlowup_mk, pow_one,
    algebraMap_mul_divBy, coe_monomialDegreeOne, coeff_monomial_same]

end reesAlgebra
