/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
public import Mathlib.RingTheory.ReesAlgebra

/-!
# The grading of the Rees algebra

Mathlib realizes the Rees algebra `R[It] = ⨁ₙ Iⁿ tⁿ` of an ideal `I` of a commutative ring `R` as
the subalgebra `reesAlgebra I` of `R[X]` of polynomials whose `n`-th coefficient lies in `Iⁿ`,
so that `t` is the variable `X`. This file equips it with its grading by the power of `X`: the
degree `n` piece `reesAlgebra.grade I n` consists of the monomials `r Xⁿ` with `r ∈ Iⁿ`, and
the homogeneous components of an element are its monomials. The degree zero piece is a copy of
`R`, and the irrelevant ideal is generated in degree one by the elements `a t` with `a` running
over generators of `I`.

With this grading, `Proj` of the Rees algebra is the blowup of `Spec R` along `V(I)`; the last
fact says that it is covered by the standard opens `D₊(a t)`.

## Main definitions

* `reesAlgebra.grade I n`: the degree `n` piece of the Rees algebra.
* `reesAlgebra.gradedAlgebra`: the `GradedAlgebra` instance on `reesAlgebra I`.
* `reesAlgebra.gradeZeroEquiv`: the degree zero piece is isomorphic to `R`.
* `reesAlgebra.monomialDegreeOne ha`: the element `a t` of degree one, for `a ∈ I`.

## Main results

* `reesAlgebra.mem_grade_iff`: the elements of degree `n` are the monomials `r Xⁿ` with
  `r ∈ Iⁿ`.
* `reesAlgebra.isInternal_grade`: the Rees algebra is the internal direct sum of its graded
  pieces.
* `reesAlgebra.coe_decompose_apply`: the degree `n` component of `f` is the monomial
  `f.coeff n • Xⁿ`.
* `reesAlgebra.irrelevant_eq_span_monomialDegreeOne`: if `I` is generated by a family `s`, the
  irrelevant ideal of `R[It]` is generated by the elements `sᵢ t`.

## References

* [The Stacks Project, Section *Blowing up*](https://stacks.math.columbia.edu/tag/01OF)
-/

public section

open Polynomial DirectSum

namespace reesAlgebra

variable {R : Type*} [CommRing R] (I : Ideal R)

/-- The degree `n` piece of the Rees algebra `R[It]`: the monomials `r Xⁿ` with `r ∈ Iⁿ`. -/
noncomputable def grade (n : ℕ) : Submodule R (reesAlgebra I) :=
  Submodule.comap (reesAlgebra I).val.toLinearMap (Submodule.map (monomial n) (I ^ n))

variable {I}

/-- The elements of degree `n` of the Rees algebra are the monomials `r Xⁿ` with `r ∈ Iⁿ`. -/
theorem mem_grade_iff {n : ℕ} {f : reesAlgebra I} :
    f ∈ grade I n ↔ ∃ r ∈ I ^ n, monomial n r = (f : R[X]) :=
  Iff.rfl

/-- An element of the Rees algebra has degree `n` exactly when it is the monomial of degree `n`
formed by its `n`-th coefficient. -/
theorem mem_grade_iff_monomial_coeff {n : ℕ} {f : reesAlgebra I} :
    f ∈ grade I n ↔ monomial n ((f : R[X]).coeff n) = f := by
  refine ⟨fun hf ↦ ?_, fun h ↦ mem_grade_iff.mpr ⟨_, (mem_reesAlgebra_iff I _).mp f.2 n, h⟩⟩
  obtain ⟨r, -, hr⟩ := mem_grade_iff.mp hf
  rw [← hr, coeff_monomial_same]

/-- The monomial `r Xⁿ` with `r ∈ Iⁿ` lies in degree `n`. -/
theorem monomial_mem_grade {n : ℕ} {r : R} (hr : r ∈ I ^ n) :
    (⟨monomial n r, monomial_mem.mpr hr⟩ : reesAlgebra I) ∈ grade I n :=
  mem_grade_iff.mpr ⟨r, hr, rfl⟩

/-- The coefficients of an element of degree `n` vanish away from `n`. -/
theorem coeff_eq_zero_of_mem_grade {m n : ℕ} {f : reesAlgebra I} (hf : f ∈ grade I n)
    (hmn : m ≠ n) : (f : R[X]).coeff m = 0 := by
  rw [← mem_grade_iff_monomial_coeff.mp hf, coeff_monomial_of_ne _ hmn]

instance gradedMonoid : SetLike.GradedMonoid (grade I) where
  one_mem := mem_grade_iff.mpr ⟨1, by simp, by simp [monomial_zero_left]⟩
  mul_mem m n f g hf hg := by
    obtain ⟨r, hr, hf⟩ := mem_grade_iff.mp hf
    obtain ⟨s, hs, hg⟩ := mem_grade_iff.mp hg
    exact mem_grade_iff.mpr ⟨r * s, pow_add I m n ▸ Ideal.mul_mem_mul hr hs, by
      rw [Subalgebra.coe_mul, ← hf, ← hg, monomial_mul_monomial]⟩

/-- The degree `n` component of an element of the Rees algebra: the monomial of degree `n` formed
by its `n`-th coefficient. -/
private noncomputable def component (n : ℕ) (f : reesAlgebra I) : grade I n :=
  ⟨⟨monomial n ((f : R[X]).coeff n), monomial_coeff_mem f n⟩,
    monomial_mem_grade ((mem_reesAlgebra_iff I _).mp f.2 n)⟩

private theorem component_add (n : ℕ) (f g : reesAlgebra I) :
    component n (f + g) = component n f + component n g := by
  ext1; ext1
  simp [component]

private theorem component_of_mem {m n : ℕ} {f : reesAlgebra I} (hf : f ∈ grade I m) :
    component n f = if h : m = n then h ▸ ⟨f, hf⟩ else 0 := by
  split_ifs with h
  · subst h
    exact Subtype.ext (Subtype.ext (mem_grade_iff_monomial_coeff.mp hf))
  · ext1; ext1
    simp [component, coeff_eq_zero_of_mem_grade hf (Ne.symm h)]

/-- The decomposition of an element of the Rees algebra into its homogeneous components. -/
private noncomputable def decomposeAux (f : reesAlgebra I) : ⨁ n, grade I n :=
  ∑ n ∈ (f : R[X]).support, of (fun n ↦ grade I n) n (component n f)

private theorem decomposeAux_apply (f : reesAlgebra I) (n : ℕ) :
    decomposeAux f n = component n f := by
  classical
  rw [decomposeAux, DFinsupp.finsetSum_apply]
  simp_rw [of_apply]
  rw [Finset.sum_dite_eq']
  split_ifs with h
  · rfl
  · ext1; ext1
    simp [component, notMem_support_iff.mp h]

private theorem coe_decomposeAux (f : reesAlgebra I) :
    DirectSum.coeAddMonoidHom (fun n ↦ grade I n) (decomposeAux f) = f := by
  rw [decomposeAux, map_sum]
  simp_rw [coeAddMonoidHom_of]
  exact (as_sum_support f).symm

private theorem decomposeAux_coe (x : ⨁ n, grade I n) :
    decomposeAux (DirectSum.coeAddMonoidHom (fun n ↦ grade I n) x) = x := by
  ext n : 1
  rw [decomposeAux_apply]
  induction x using DirectSum.induction_on with
  | zero => ext1; ext1; simp [component]
  | of m y =>
    rw [coeAddMonoidHom_of, component_of_mem y.2, of_apply]
  | add x y hx hy => rw [map_add, component_add, hx, hy, add_apply]

variable (I) in
/-- The Rees algebra is the internal direct sum of its graded pieces. -/
theorem isInternal_grade : IsInternal (grade I) :=
  Function.bijective_iff_has_inverse.mpr ⟨decomposeAux, decomposeAux_coe, coe_decomposeAux⟩

/-- The grading of the Rees algebra `R[It]` by the power of `t`. -/
noncomputable instance gradedAlgebra : GradedAlgebra (grade I) :=
  (isInternal_grade I).gradedAlgebra

/-- The degree `n` component of an element `f` of the Rees algebra is the monomial
`f.coeff n • Xⁿ`. -/
@[simp]
theorem coe_decompose_apply (f : reesAlgebra I) (n : ℕ) :
    ((decompose (grade I) f n : reesAlgebra I) : R[X]) = monomial n ((f : R[X]).coeff n) := by
  have : decompose (grade I) f = decomposeAux f :=
    (isInternal_grade I).1 <| by
      rw [coe_decomposeAux]
      exact (decompose (grade I)).symm_apply_apply f
  rw [this, decomposeAux_apply]
  rfl

variable (I)

/-- The degree zero piece of the Rees algebra is a copy of the base ring `R`. -/
noncomputable def gradeZeroEquiv : R ≃+* grade I 0 :=
  RingEquiv.ofBijective (algebraMap R (grade I 0)) <| by
    refine ⟨fun r s h ↦ ?_, fun f ↦ ?_⟩
    · simpa using congr_arg (fun x : grade I 0 ↦ ((x : reesAlgebra I) : R[X]).coeff 0) h
    · obtain ⟨r, -, hr⟩ := mem_grade_iff.mp f.2
      refine ⟨r, Subtype.ext (Subtype.ext ?_)⟩
      rw [← hr, monomial_zero_left, SetLike.GradeZero.coe_algebraMap, Subalgebra.coe_algebraMap,
        algebraMap_eq]

-- Not `@[simp]`: `gradeZeroEquiv I r` is the simp normal form.
theorem gradeZeroEquiv_apply (r : R) : gradeZeroEquiv I r = algebraMap R (grade I 0) r :=
  RingEquiv.ofBijective_apply _ _ r

@[simp]
theorem coe_gradeZeroEquiv (r : R) :
    ((gradeZeroEquiv I r : reesAlgebra I) : R[X]) = C r := by
  rw [gradeZeroEquiv_apply, SetLike.GradeZero.coe_algebraMap, Subalgebra.coe_algebraMap,
    algebraMap_eq]

@[simp]
theorem gradeZeroEquiv_symm_apply (f : grade I 0) :
    (gradeZeroEquiv I).symm f = ((f : reesAlgebra I) : R[X]).coeff 0 := by
  rw [RingEquiv.symm_apply_eq]
  obtain ⟨r, -, hr⟩ := mem_grade_iff.mp f.2
  ext1; ext1
  rw [coe_gradeZeroEquiv, ← hr, monomial_zero_left, coeff_C_zero]

variable {I}

/-- The element `a t` of degree one of the Rees algebra `R[It]`, for `a ∈ I`. -/
noncomputable def monomialDegreeOne {a : R} (ha : a ∈ I) : reesAlgebra I :=
  ⟨monomial 1 a, monomial_mem.mpr (by rwa [pow_one])⟩

@[simp]
theorem coe_monomialDegreeOne {a : R} (ha : a ∈ I) : (monomialDegreeOne ha : R[X]) = monomial 1 a :=
  (rfl)

theorem monomialDegreeOne_mem_grade {a : R} (ha : a ∈ I) : monomialDegreeOne ha ∈ grade I 1 :=
  monomial_mem_grade (by rwa [pow_one])

/-- If `I` is generated by a family `s`, then every monomial `c tⁿ⁺¹` with `c ∈ Iⁿ⁺¹` lies in the
ideal of the Rees algebra generated by the elements `sᵢ t`. -/
private theorem monomial_succ_mem_span {ι : Type*} {s : ι → R}
    (hs : Ideal.span (Set.range s) = I) {m : ℕ} {c : R} (hc : c ∈ I ^ (m + 1)) :
    (⟨monomial (m + 1) c, monomial_mem.mpr hc⟩ : reesAlgebra I) ∈
      Ideal.span (Set.range fun i ↦
        monomialDegreeOne (hs ▸ Ideal.subset_span ⟨i, rfl⟩ : s i ∈ I)) := by
  set J := Ideal.span (Set.range fun i ↦
    monomialDegreeOne (hs ▸ Ideal.subset_span ⟨i, rfl⟩ : s i ∈ I))
  -- First the monomials of degree one, by induction on the generation of `I` by `s`.
  have hone (i : R) (hi : i ∈ Ideal.span (Set.range s)) (h : monomial 1 i ∈ reesAlgebra I) :
      (⟨monomial 1 i, h⟩ : reesAlgebra I) ∈ J := by
    have hmem {x : R} (hx : x ∈ Ideal.span (Set.range s)) : monomial 1 x ∈ reesAlgebra I :=
      monomial_mem.mpr (by rwa [pow_one, ← hs])
    induction hi using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨k, rfl⟩ := hx
      exact Ideal.subset_span ⟨k, rfl⟩
    | zero =>
      convert J.zero_mem using 1
      ext1
      simp
    | add x y hx' hy' hx hy =>
      convert J.add_mem (hx (hmem hx')) (hy (hmem hy')) using 1
      ext1
      simp
    | smul r x hx' hx =>
      convert J.mul_mem_left (algebraMap R (reesAlgebra I) r) (hx (hmem hx')) using 1
      ext1
      simp [← C_mul_monomial]
  -- Then the monomials of degree `m + 1`, using `Iᵐ⁺¹ = I Iᵐ`.
  have hmem {x : R} (hx : x ∈ I * I ^ m) : monomial (m + 1) x ∈ reesAlgebra I :=
    monomial_mem.mpr (by rwa [pow_succ'])
  suffices ∀ x (hx : x ∈ I * I ^ m), (⟨monomial (m + 1) x, hmem hx⟩ : reesAlgebra I) ∈ J from
    this c (by rwa [← pow_succ'])
  intro x hx
  induction hx using Submodule.mul_induction_on' with
  | mem_mul_mem i hi j hj =>
    convert J.mul_mem_right ⟨monomial m j, monomial_mem.mpr hj⟩
      (hone i (hs ▸ hi) (monomial_mem.mpr (by rwa [pow_one]))) using 1
    ext1
    simp [monomial_mul_monomial, add_comm m 1]
  | add x y hx' hy' hx hy =>
    convert J.add_mem hx hy using 1
    ext1
    simp

/-- **The irrelevant ideal of the Rees algebra.** If the ideal `I` is generated by a family `s`,
then the irrelevant ideal `⨁_{n > 0} Iⁿ tⁿ` of `R[It]` is generated by the elements `sᵢ t` of
degree one. -/
theorem irrelevant_eq_span_monomialDegreeOne {ι : Type*} {s : ι → R}
    (hs : Ideal.span (Set.range s) = I) :
    (HomogeneousIdeal.irrelevant (grade I)).toIdeal =
      Ideal.span (Set.range fun i ↦
        monomialDegreeOne (hs ▸ Ideal.subset_span ⟨i, rfl⟩ : s i ∈ I)) := by
  refine le_antisymm (fun x hx ↦ ?_) (Ideal.span_le.mpr ?_)
  · rw [HomogeneousIdeal.mem_iff, HomogeneousIdeal.mem_irrelevant_iff, GradedRing.proj_apply]
      at hx
    have h0 : (x : R[X]).coeff 0 = 0 := by
      simpa using congr_arg (fun y : reesAlgebra I ↦ (y : R[X])) hx
    rw [as_sum_support x]
    refine Ideal.sum_mem _ fun n hn ↦ ?_
    obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 :=
      Nat.exists_eq_succ_of_ne_zero (by rintro rfl; exact mem_support_iff.mp hn h0)
    exact monomial_succ_mem_span hs ((mem_reesAlgebra_iff I _).mp x.2 _)
  · rintro _ ⟨i, rfl⟩
    rw [SetLike.mem_coe, HomogeneousIdeal.mem_iff, HomogeneousIdeal.mem_irrelevant_iff,
      GradedRing.proj_apply]
    ext1
    simp

end reesAlgebra
