/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Polynomial.Subresultant.Polynomial
import Mathlib.LinearAlgebra.Matrix.Adjugate
import TauCeti.Algebra.Polynomial.Degree.Operations

/-!
# Bézout identities for subresultant polynomials

At every index, the fixed-bound subresultant polynomial is a combination
`A * q + B * p`, where `A` and `B` have degrees below `m - j` and `n - j`, respectively.
Outside the strict range `j < min m n`, the subresultant is zero and both coefficients can be
chosen zero.
The identity holds over any commutative ring, including rings with zero divisors, and allows the
actual degrees of the inputs to be smaller than their formal bounds. Consequently every common
divisor of the inputs divides the subresultant polynomial.

These identities place subresultants in the ideal generated by the inputs and allow common
factors to be tracked through the subresultant family. No invertibility or nonvanishing of a
principal subresultant coefficient is required.

## Main results

* `TauCeti.exists_mul_add_mul_eq_subresultant`: the Bézout identity with strict degree bounds.
* `TauCeti.dvd_subresultant`: every common divisor divides the fixed-bound subresultant.

## References

* S. Basu, R. Pollack, M.-F. Roy, *Algorithms in Real Algebraic Geometry*, second edition,
  Chapter 4: the determinant construction of subresultant Bézout identities.
-/

public section

namespace TauCeti

open Polynomial

variable {R : Type*} [CommRing R]

-- Cramer's rule reads a replaced-row determinant against the first adjugate column.
private theorem subresultantCoeff_eq_coeff_adjugate [DecidableEq R]
    {p q : R[X]} {m n : ℕ} (hm : p.natDegree ≤ m) (hn : q.natDegree ≤ n) (j k : ℕ)
    (i₀ : Fin ((m - j) + (n - j))) (hi₀ : i₀.val = 0) :
    subresultantCoeff p q m n j k =
      (ofFn (m - j) (fun l => (subresultantMatrix p q m n j).adjugate
          (Fin.castAdd (n - j) l) i₀) * q +
        ofFn (n - j) (fun l => (subresultantMatrix p q m n j).adjugate
          (Fin.natAdd (m - j) l) i₀) * p).coeff k := by
  classical
  have hrow := subresultantCoeffMatrix_mulVec hm hn j k
    (fun l => (subresultantMatrix p q m n j).adjugate l i₀) i₀
  simp only [hi₀, ↓reduceIte] at hrow
  rw [subresultantCoeff_def, Polynomial.subresultantCoeffMatrix_eq_updateRow p q m n j k i₀ hi₀,
    ← Matrix.cramer_transpose_apply, Matrix.cramer_eq_adjugate_mulVec,
    ← Matrix.adjugate_transpose, ← hrow]
  exact dotProduct_comm _ _

/-- At every index, a subresultant polynomial is a Bézout combination of its inputs.
The coefficients of `q` and `p` have degrees strictly below `m - j` and `n - j`, respectively.
The formal bounds may exceed the actual degrees, and neither input nor the subresultant is
required to be nonzero. Outside the strict range, both Bézout coefficients can be zero. -/
theorem exists_mul_add_mul_eq_subresultant {p q : R[X]} {m n j : ℕ}
    (hm : p.natDegree ≤ m) (hn : q.natDegree ≤ n) :
    ∃ A B : R[X], A.degree < (m - j : ℕ) ∧ B.degree < (n - j : ℕ) ∧
      A * q + B * p = subresultant p q m n j := by
  classical
  by_cases hj : j < min m n
  · let i₀ : Fin ((m - j) + (n - j)) := ⟨0, by omega⟩
    let M := subresultantMatrix p q m n j
    let v : Fin ((m - j) + (n - j)) → R := fun l => M.adjugate l i₀
    let A := ofFn (m - j) (fun l => v (Fin.castAdd (n - j) l))
    let B := ofFn (n - j) (fun l => v (Fin.natAdd (m - j) l))
    have hA : A.degree < (m - j : ℕ) := ofFn_degree_lt _
    have hB : B.degree < (n - j : ℕ) := ofFn_degree_lt _
    -- The product degree bound handles coefficients beyond the matrix's coefficient window.
    have hdeg := degree_mul_add_mul_lt_of_degree_lt_of_natDegree_le
      hm hn (by omega : j ≤ m) (by omega : j ≤ n) hA hB
    -- The first adjugate column maps to a vector supported in the first row only.
    have hMv (i : Fin ((m - j) + (n - j))) :
        M.mulVec v i = if i = i₀ then M.det else 0 := by
      have h : M.mulVec v = M.det • Pi.single i₀ 1 := by
        -- `v` is definitionally this adjugate column; expose it for `Matrix.mulVec_single_one`.
        change M.mulVec (M.adjugate.col i₀) = _
        rw [← Matrix.mulVec_single_one, Matrix.mulVec_mulVec, Matrix.mul_adjugate,
          Matrix.smul_mulVec, Matrix.one_mulVec]
      simpa [Pi.smul_apply, Pi.single_apply, eq_comm] using congrFun h i
    refine ⟨A, B, hA, hB, ?_⟩
    ext k
    rw [coeff_subresultant]
    by_cases hk : k ≤ j
    · rw [ite_eq_left ⟨hj, hk⟩]
      exact (subresultantCoeff_eq_coeff_adjugate hm hn j k i₀ rfl).symm
    · rw [ite_eq_right (by simp [hk])]
      by_cases hwin : k < (m - j) + (n - j) + j
      · let i : Fin ((m - j) + (n - j)) := ⟨k - j, by omega⟩
        have hi : i ≠ i₀ := by
          intro h
          have := congrArg Fin.val h
          dsimp [i, i₀] at this
          omega
        have h := subresultantMatrix_mulVec hm hn j v i
        rw [hMv, ite_eq_right hi] at h
        simpa [A, B, i, Nat.sub_add_cancel (by omega : j ≤ k)] using h.symm
      · exact coeff_eq_zero_of_degree_lt (hdeg.trans_le
          (WithBot.coe_le_coe.mpr (by omega : (m - j) + (n - j) + j ≤ k)))
  · refine ⟨0, 0, ?_, ?_, ?_⟩
    · simp
    · simp
    · rw [subresultant_eq_zero_of_min_le _ _ _ _ _ (by omega)]
      simp

/-- Every common divisor of the inputs divides their fixed-bound subresultant polynomial.
This also covers indices outside the strict range, where the subresultant polynomial is zero. -/
theorem dvd_subresultant {p q d : R[X]} {m n j : ℕ}
    (hm : p.natDegree ≤ m) (hn : q.natDegree ≤ n) (hp : d ∣ p) (hq : d ∣ q) :
    d ∣ subresultant p q m n j := by
  obtain ⟨A, B, _, _, h⟩ := exists_mul_add_mul_eq_subresultant hm hn
  rw [← h]
  exact dvd_add (dvd_mul_of_dvd_right hq A) (dvd_mul_of_dvd_right hp B)

end TauCeti
