/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic
public import Mathlib.RepresentationTheory.Homological.GroupHomology.FiniteCyclic
public import TauCeti.RepresentationTheory.Invariants
public import TauCeti.RepresentationTheory.Homological.TateCohomology.LowDegree
import Mathlib.Algebra.Homology.HomologicalComplexAbelian

/-!
# Tate cohomology of a finite cyclic group is two-periodic

For a finite cyclic group `G` generated by `g`, the standard periodic resolution alternates the
norm map `N` with `ρ(g) - 𝟙`. Consequently the whole two-sided family of Tate groups of a
representation `M` collapses onto just two modules: every even Tate degree is the homology of

`M --N--> M --(ρ(g) - 𝟙)--> M`,

and every odd Tate degree is the homology of the same two maps in the opposite order.

Mathlib supplies this periodic resolution and its two homology calculations for ordinary group
cohomology in positive degrees and for ordinary group homology, together with the comparisons of
Tate cohomology with ordinary cohomology in degrees `≥ 1` and with ordinary homology in degrees
`≤ -2`. This file assembles those comparisons over all of `ℤ`. The four degree ranges are treated
separately, because the two middle degrees are not ordinary (co)homology at all: degree `0` is
`Mᴳ / N M` and degree `-1` is `ker N / I_G M`, and they are matched with the same two periodic
models through the low-degree identifications of
`TauCeti.RepresentationTheory.Homological.TateCohomology.LowDegree`.

The parities line up across the splice: for `n ≥ 1` an even degree is ordinary cohomology in an
even degree, while for `n = -(i + 1) ≤ -2` an even degree is ordinary homology in an *odd*
degree, and Mathlib's homology calculation in odd degrees produces exactly the model that its
cohomology calculation produces in even degrees.

## Provenance

The corresponding all-degree construction is `Rep.periodicTateCohomology` in
`ClassFieldTheory/Cohomology/FiniteCyclic/UpDown.lean` from `kbuzzard/ClassFieldTheory`, commit
`ccc3323c6750abca25b49b35106f54eb3a398509`. That development builds a periodic complex of its
own; the construction below instead reads the periodicity off Mathlib's imported Tate groups,
through the periodic-resolution calculations `Rep.FiniteCyclicGroup.groupCohomologyIsoEven`,
`groupCohomologyIsoOdd`, `groupHomologyIsoEven` and `groupHomologyIsoOdd`.

## Main definitions

* `Rep.FiniteCyclicGroup.tateCohomologyIso₀`: degree zero is the homology of
  `M --N--> M --(ρ(g) - 𝟙)--> M`.
* `Rep.FiniteCyclicGroup.tateCohomologyIsoNegOne`: degree `-1` is the homology of
  `M --(ρ(g) - 𝟙)--> M --N--> M`.
* `Rep.FiniteCyclicGroup.tateCohomologyIsoEven`: the common explicit model for every even
  integer degree.
* `Rep.FiniteCyclicGroup.tateCohomologyIsoOdd`: the common explicit model for every odd integer
  degree.
* `Rep.FiniteCyclicGroup.periodicIso`: **two-periodicity**, an isomorphism between any two Tate
  degrees congruent modulo two. Taking `n` and `n + 2` gives the usual statement.
* `Rep.FiniteCyclicGroup.periodicFunctor`: the periodic chain complex of underlying modules, as a
  functor of the coefficients. Its homology in an odd degree is the model of degree-zero Tate
  cohomology and in a nonzero even degree the model of Tate cohomology in degree `-1`
  (`periodicHomologyIsoOdd`, `periodicHomologyIsoEven`). Passing to a functor is what makes a
  short exact sequence of representations induce one of complexes, hence a long exact sequence of
  these homology groups; splicing it against the two-periodicity above is the exact hexagon that
  computes Herbrand quotients.
* `Rep.FiniteCyclicGroup.normHomCompSubMap` and `subCompNormHomMap`: functoriality of the two
  short complexes obtained by alternating the norm and `ρ(g) - 𝟙`.

## Main results

* `Rep.FiniteCyclicGroup.natCard_tateCohomology_eq_of_modEq`: Tate degrees congruent modulo two
  have the same cardinality. This is the form the Herbrand quotient is computed with.
* `Rep.FiniteCyclicGroup.shortExact_map_periodicFunctor`: a short exact sequence of
  representations induces a short exact sequence of periodic chain complexes.
* `Rep.FiniteCyclicGroup.homologyMap_comp_periodicHomologyIsoOdd` and
  `homologyMap_comp_periodicHomologyIsoEven`: the odd- and nonzero-even-degree identifications of
  the homology of the periodic complex are natural in the coefficients.
* `Rep.FiniteCyclicGroup.natCard_periodicHomology_odd` and `natCard_periodicHomology_even`: the
  homology of the periodic complex in an odd, respectively a nonzero even, degree has the
  cardinality of Tate cohomology in degree `0`, respectively `-1`.

## References

* K. S. Brown, *Cohomology of Groups*, Chapter VI, §9.
* J.-P. Serre, *Local Fields*, Chapter VIII, §4.
-/

public noncomputable section

universe u

open CategoryTheory LinearMap Rep

namespace Rep.FiniteCyclicGroup

section Generator

variable {R G : Type u} [CommRing R] [Group G] [Fintype G] (M : Rep R G) (g : G)

/-- Degree-zero Tate cohomology of a finite cyclic group generated by `g` is the homology of
`M --N--> M --(ρ(g) - 𝟙)--> M`.

Both sides are `Mᴳ / N M`: the left-hand side by the low-degree identification of degree zero,
the right-hand side because `g` generates, so the kernel of `ρ(g) - 𝟙` is the invariants. -/
def tateCohomologyIso₀ (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M 0 ≅ (normHomCompSub M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  exact calc
  tateCohomology M 0 ≅ ModuleCat.of R
      (M.ρ.invariants ⧸ (range M.ρ.norm).submoduleOf M.ρ.invariants) :=
    TauCeti.TateCohomology.H0IsoNormQuotient M
  _ ≅ (normHomCompSub M g).moduleCatLeftHomologyData.H := by
    refine (Submodule.Quotient.equiv _ _
      (LinearEquiv.ofEq _ _ (by simpa [sub_hom, applyAsHom] using
        invariants_eq_ker_apply_sub M g hg)) ?_).toModuleIso
    refine Submodule.ext fun ⟨x, hx⟩ ↦ ⟨?_, ?_⟩
    · rintro ⟨⟨y, hy⟩, ⟨z, hz⟩, hw⟩
      exact ⟨z, Subtype.ext (hz.trans congr(Subtype.val $hw))⟩
    · rintro ⟨z, hz⟩
      refine ⟨⟨M.ρ.norm z, fun γ ↦ M.ρ.self_norm_apply γ z⟩, ⟨z, rfl⟩, Subtype.ext ?_⟩
      exact congr(Subtype.val $hz)
  _ ≅ (normHomCompSub M g).homology := (ShortComplex.moduleCatHomologyIso _).symm

/-- Degree `-1` Tate cohomology of a finite cyclic group generated by `g` is the homology of
`M --(ρ(g) - 𝟙)--> M --N--> M`.

Both sides are `ker N / I_G M`: the left-hand side by the low-degree identification of degree
`-1`, the right-hand side because `g` generates, so the augmentation submodule is the image of
`ρ(g) - 𝟙`. -/
def tateCohomologyIsoNegOne (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M (-1) ≅ (subCompNormHom M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  exact calc
  tateCohomology M (-1) ≅ ModuleCat.of R
      (ker M.ρ.norm ⧸ (Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm)) :=
    TauCeti.TateCohomology.HNegOneIsoNormKernelQuotient M
  _ ≅ (subCompNormHom M g).moduleCatLeftHomologyData.H := by
    refine (Submodule.Quotient.equiv _ _ (LinearEquiv.refl R _) ?_).toModuleIso
    rw [Representation.FiniteCyclicGroup.coinvariantsKer_eq_range M.ρ g hg]
    refine Submodule.ext fun ⟨x, hx⟩ ↦ ⟨?_, ?_⟩
    · rintro ⟨⟨y, hy⟩, ⟨z, hz⟩, hw⟩
      have hyx : y = x := congr(Subtype.val $hw)
      exact ⟨z, Subtype.ext (by
        simpa [ShortComplex.moduleCatToCycles, sub_hom, applyAsHom, hyx] using hz)⟩
    · rintro ⟨z, hz⟩
      refine ⟨⟨x, hx⟩, ⟨z, ?_⟩, rfl⟩
      simpa [ShortComplex.moduleCatToCycles, sub_hom, applyAsHom] using congr(Subtype.val $hz)
  _ ≅ (subCompNormHom M g).homology := (ShortComplex.moduleCatHomologyIso _).symm

/-- In every even integer degree, Tate cohomology of a finite cyclic group generated by `g` is
the homology of `M --N--> M --(ρ(g) - 𝟙)--> M`.

Positive even degrees are ordinary cohomology in an even degree, degree zero is
`tateCohomologyIso₀`, and a degree `-(i + 1) ≤ -2` is even exactly when `i` is odd, where it is
ordinary homology in an odd degree. -/
def tateCohomologyIsoEven (hg : ∀ x, x ∈ Subgroup.zpowers g) (n : ℤ) (hn : Even n) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M n ≅ (normHomCompSub M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  classical
  rcases n with k | k
  · rcases k with _ | k
    · exact tateCohomologyIso₀ M g hg
    · have hk : Even (k + 1) := by
        rw [Nat.even_iff]
        rw [Int.even_iff, Int.ofNat_eq_natCast] at hn
        omega
      exact (TateCohomology.isoGroupCohomology (k + 1)).app M ≪≫
        groupCohomologyIsoEven M g hg (k + 1) hk
  · have hk : Odd k := by
      rw [Nat.odd_iff]
      rw [Int.even_iff, Int.negSucc_eq] at hn
      omega
    have : NeZero k := ⟨hk.pos.ne'⟩
    exact (TateCohomology.isoGroupHomology (Int.negSucc k) k
        (by rw [Int.negSucc_eq])).app M ≪≫
      groupHomologyIsoOdd M g hg k hk

/-- In every odd integer degree, Tate cohomology of a finite cyclic group generated by `g` is the
homology of `M --(ρ(g) - 𝟙)--> M --N--> M`.

Positive odd degrees are ordinary cohomology in an odd degree, degree `-1` is
`tateCohomologyIsoNegOne`, and a degree `-(i + 1) ≤ -2` is odd exactly when `i` is even and
nonzero, where it is ordinary homology in a nonzero even degree. -/
def tateCohomologyIsoOdd (hg : ∀ x, x ∈ Subgroup.zpowers g) (n : ℤ) (hn : Odd n) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M n ≅ (subCompNormHom M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  classical
  rcases n with k | k
  · have hk : Odd k := by
      rw [Nat.odd_iff]
      rw [Int.odd_iff, Int.ofNat_eq_natCast] at hn
      omega
    have : NeZero k := ⟨hk.pos.ne'⟩
    exact (TateCohomology.isoGroupCohomology k).app M ≪≫ groupCohomologyIsoOdd M g hg k hk
  · rcases k with _ | j
    · exact tateCohomologyIsoNegOne M g hg
    · have hj : Even (j + 1) := by
        rw [Nat.even_iff]
        rw [Int.odd_iff, Int.negSucc_eq] at hn
        omega
      exact (TateCohomology.isoGroupHomology (Int.negSucc (j + 1)) (j + 1)
          (by rw [Int.negSucc_eq])).app M ≪≫ groupHomologyIsoEven M g hg (j + 1) hj

/-- In degree zero, the all-degree even comparison is `tateCohomologyIso₀`. -/
@[simp]
theorem tateCohomologyIsoEven_zero (hg : ∀ x, x ∈ Subgroup.zpowers g) (h0 : Even (0 : ℤ)) :
    tateCohomologyIsoEven M g hg 0 h0 = tateCohomologyIso₀ M g hg := by
  rfl

-- These `simp` lemmas take the parity hypothesis exactly as it occurs on the left-hand side and
-- derive any other parity fact on the right: a hypothesis occurring on the left only inside a
-- proof is not assigned by unification, and `simp` cannot prove it for a symbolic degree.
/-- In a positive even degree, the all-degree comparison is the composite through ordinary
group cohomology. -/
@[simp]
theorem tateCohomologyIsoEven_ofNat_succ (hg : ∀ x, x ∈ Subgroup.zpowers g) (k : ℕ)
    (hk : Even ((k : ℤ) + 1)) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoEven M g hg ((k : ℤ) + 1) hk =
      (TateCohomology.isoGroupCohomology (k + 1)).app M ≪≫
        groupCohomologyIsoEven M g hg (k + 1) ((Int.even_coe_nat (k + 1)).1 hk) := by
  rfl

/-- In a degree at most `-2`, the all-degree even comparison is the composite through ordinary
group homology in the corresponding odd degree. -/
@[simp]
theorem tateCohomologyIsoEven_negSucc (hg : ∀ x, x ∈ Subgroup.zpowers g) (k : ℕ)
    (hk : Even (Int.negSucc k)) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoEven M g hg (Int.negSucc k) hk =
      (let hk' : Odd k := by simpa [Int.negSucc_eq, parity_simps] using hk
       let _ : NeZero k := ⟨hk'.pos.ne'⟩
       let _ := Classical.decEq G
       (TateCohomology.isoGroupHomology (Int.negSucc k) k rfl).app M ≪≫
         groupHomologyIsoOdd M g hg k hk') := by
  rfl

/-- In a positive odd degree, the all-degree comparison is the composite through ordinary group
cohomology. -/
@[simp]
theorem tateCohomologyIsoOdd_ofNat (hg : ∀ x, x ∈ Subgroup.zpowers g) (k : ℕ) (hk : Odd (k : ℤ)) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoOdd M g hg (k : ℤ) hk =
      (let hk' : Odd k := (Int.odd_coe_nat k).1 hk
       let _ : NeZero k := ⟨hk'.pos.ne'⟩
       (TateCohomology.isoGroupCohomology k).app M ≪≫
         groupCohomologyIsoOdd M g hg k hk') := by
  rfl

/-- In degree `-1`, the all-degree odd comparison is `tateCohomologyIsoNegOne`. -/
@[simp]
theorem tateCohomologyIsoOdd_negOne (hg : ∀ x, x ∈ Subgroup.zpowers g)
    (hneg : Odd (-1 : ℤ)) :
    tateCohomologyIsoOdd M g hg (-1) hneg = tateCohomologyIsoNegOne M g hg := by
  rfl

/-- In a degree at most `-2`, the all-degree odd comparison is the composite through ordinary
group homology in the corresponding nonzero even degree. -/
@[simp]
theorem tateCohomologyIsoOdd_negSucc_succ (hg : ∀ x, x ∈ Subgroup.zpowers g) (j : ℕ)
    (hj : Odd (Int.negSucc (j + 1))) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoOdd M g hg (Int.negSucc (j + 1)) hj =
      (let hj' : Even (j + 1) := by simpa [Int.negSucc_eq, parity_simps] using hj
       let _ := Classical.decEq G
       (TateCohomology.isoGroupHomology (Int.negSucc (j + 1)) (j + 1) rfl).app M ≪≫
         groupHomologyIsoEven M g hg (j + 1) hj') := by
  rfl

/-- The generator-dependent comparison underlying two-periodicity. It compares two degrees of the
same parity with the same homology object of the standard periodic resolution, using the even
model or the odd model according to that common parity. -/
def periodicIsoOfGenerator (hg : ∀ x, x ∈ Subgroup.zpowers g) (m n : ℤ)
    (hmn : m ≡ n [ZMOD 2]) : tateCohomology M m ≅ tateCohomology M n := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  have hpar : Even m ↔ Even n := by
    have h : m % 2 = n % 2 := hmn
    rw [Int.even_iff, Int.even_iff, h]
  by_cases hm : Even m
  · exact (tateCohomologyIsoEven M g hg m hm).trans
      (tateCohomologyIsoEven M g hg n (hpar.mp hm)).symm
  · exact (tateCohomologyIsoOdd M g hg m (Int.not_even_iff_odd.mp hm)).trans
      (tateCohomologyIsoOdd M g hg n (Int.not_even_iff_odd.mp (hpar.not.mp hm))).symm

-- The parity of `m` is derived from `hmn` and `hn` on the right-hand side, so that `simp` needs
-- no hypothesis it cannot assign by unification.
/-- In even degrees, `periodicIsoOfGenerator` is the comparison obtained by identifying both Tate
groups with the even homology object of the periodic resolution. Only `n` is assumed even: `m` is
then even because `m ≡ n [ZMOD 2]`. -/
@[reassoc (attr := simp)]
theorem periodicIsoOfGenerator_hom_comp_tateCohomologyIsoEven_hom (hg : ∀ x, x ∈ Subgroup.zpowers g)
    (m n : ℤ) (hmn : m ≡ n [ZMOD 2]) (hn : Even n) :
    (periodicIsoOfGenerator M g hg m n hmn).hom ≫ (tateCohomologyIsoEven M g hg n hn).hom =
      (tateCohomologyIsoEven M g hg m (Int.even_iff.2 (hmn.eq.trans (Int.even_iff.1 hn)))).hom := by
  simp [periodicIsoOfGenerator, Int.even_iff.2 (hmn.eq.trans (Int.even_iff.1 hn))]

/-- In odd degrees, `periodicIsoOfGenerator` is the comparison obtained by identifying both Tate
groups with the odd homology object of the periodic resolution. Only `n` is assumed odd: `m` is
then odd because `m ≡ n [ZMOD 2]`. -/
@[reassoc (attr := simp)]
theorem periodicIsoOfGenerator_hom_comp_tateCohomologyIsoOdd_hom (hg : ∀ x, x ∈ Subgroup.zpowers g)
    (m n : ℤ) (hmn : m ≡ n [ZMOD 2]) (hn : Odd n) :
    (periodicIsoOfGenerator M g hg m n hmn).hom ≫ (tateCohomologyIsoOdd M g hg n hn).hom =
      (tateCohomologyIsoOdd M g hg m (Int.odd_iff.2 (hmn.eq.trans (Int.odd_iff.1 hn)))).hom := by
  simp [periodicIsoOfGenerator, Int.not_even_iff.2 (hmn.eq.trans (Int.odd_iff.1 hn))]

end Generator

section IsCyclic

variable {R G : Type u} [CommRing R] [Group G] [Fintype G]

/-- **Two-periodicity for Tate cohomology of a finite cyclic group.** Tate degrees congruent
modulo two are isomorphic; the case `n` and `n + 2` is the usual periodicity statement. -/
def periodicIso (M : Rep R G) [IsCyclic G] (m n : ℤ) (hmn : m ≡ n [ZMOD 2]) :
    tateCohomology M m ≅ tateCohomology M n := by
  let hgen := isCyclic_iff_exists_zpowers_eq_top.mp (inferInstance : IsCyclic G)
  let g := hgen.choose
  exact periodicIsoOfGenerator M g (fun x ↦ hgen.choose_spec.ge (Subgroup.mem_top x)) m n hmn

/-- Tate cohomology groups of a finite cyclic group in degrees congruent modulo two have the same
cardinality. This is the form used in Herbrand-quotient computations. -/
theorem natCard_tateCohomology_eq_of_modEq (M : Rep R G) [IsCyclic G] (m n : ℤ)
    (hmn : m ≡ n [ZMOD 2]) :
    Nat.card (tateCohomology M m) = Nat.card (tateCohomology M n) :=
  Nat.card_congr (periodicIso M m n hmn).toLinearEquiv.toEquiv

end IsCyclic

section PeriodicComplex

variable {R G : Type u} [CommRing R] [CommGroup G] [Fintype G] (M : Rep R G) (g : G)

variable {M} {N : Rep R G}

variable (R) in
/-- The periodic chain complex `... ⟶ M --N--> M --(ρ(g) - 𝟙)--> M ⟶ 0` of underlying modules,
as a functor of the coefficient representation. It is obtained from Mathlib's
`Rep.FiniteCyclicGroup.chainComplexFunctor` by applying the forgetful functor from representations
to modules degreewise. A morphism of representations therefore acts by its underlying linear map
in every degree.

The body is exposed because consumers identify the value of the functor with
`Rep.FiniteCyclicGroup.moduleCatChainComplex` and its action on a morphism with the underlying
linear map. -/
@[expose]
noncomputable def periodicFunctor (g : G) : Rep R G ⥤ ChainComplex (ModuleCat R) ℕ :=
  chainComplexFunctor R g ⋙
    (forget₂ (Rep R G) (ModuleCat R)).mapHomologicalComplex (ComplexShape.down ℕ)

/-- In every degree, `periodicFunctor` sends a morphism of representations to its underlying linear
map. -/
@[simp]
theorem periodicFunctor_map_f (f : M ⟶ N) (i : ℕ) :
    ((periodicFunctor R g).map f).f i = ModuleCat.ofHom (Hom.hom f).toLinearMap := (rfl)

/-- The value of `periodicFunctor` is the underlying-module periodic chain complex. -/
noncomputable def periodicFunctorObjIso (M : Rep R G) :
    (periodicFunctor R g).obj M ≅ moduleCatChainComplex M g :=
  HomologicalComplex.Hom.isoOfComponents (fun _ ↦ Iso.refl _) (by
    rintro _ j ⟨rfl⟩
    simp only [periodicFunctor, Functor.comp_obj, Functor.mapHomologicalComplex_obj_X,
      Functor.mapHomologicalComplex_obj_d, Iso.refl_hom]
    by_cases hj : Even (j + 1) <;>
      simp only [chainComplexFunctor, forget₂_moduleCat_obj, moduleCatChainComplex,
        HomologicalComplex.alternatingConst_d, ComplexShape.down_Rel, ↓reduceIte, hj] <;>
      ext <;> rfl)

/-- The periodic chain complex functor sends zero morphisms to zero morphisms. -/
instance : (periodicFunctor R g).PreservesZeroMorphisms where
  map_zero X Y := by
    ext i : 2
    rfl

variable (R) in
/-- Evaluating the periodic chain complex in a single degree forgets the group action. -/
noncomputable def periodicFunctorEval (i : ℕ) :
    periodicFunctor R g ⋙ HomologicalComplex.eval (ModuleCat R) (ComplexShape.down ℕ) i ≅
      forget₂ (Rep R G) (ModuleCat R) := .refl _

/-- A short exact sequence of representations induces a short exact sequence of periodic chain
complexes, because in each degree it is the underlying short exact sequence of modules. -/
theorem shortExact_map_periodicFunctor {S : ShortComplex (Rep R G)} (hS : S.ShortExact) :
    (S.map (periodicFunctor R g)).ShortExact := by
  rw [HomologicalComplex.shortExact_iff_degreewise_shortExact]
  intro i
  rw [← ShortComplex.map_comp]
  exact ShortComplex.shortExact_of_iso (ShortComplex.mapNatIso _ (periodicFunctorEval R g i).symm)
    (hS.map_of_exact (forget₂ (Rep R G) (ModuleCat R)))

private theorem down_rel_prev {j : ℕ} :
    (ComplexShape.down ℕ).Rel ((ComplexShape.down ℕ).prev j) j := by
  simp

private theorem down_rel_next {j : ℕ} (hj : j ≠ 0) :
    (ComplexShape.down ℕ).Rel j ((ComplexShape.down ℕ).next j) := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hj
  simp

variable (M)

/-- In an odd degree, the short complex computing the homology of the periodic chain complex is
`M --N--> M --(ρ(g) - 𝟙)--> M`. -/
noncomputable def periodicScIsoOdd {j : ℕ} (hj : Odd j) :
    ((periodicFunctor R g).obj M).sc j ≅ normHomCompSub M g :=
  (HomologicalComplex.shortComplexFunctor (ModuleCat R) (ComplexShape.down ℕ) j).mapIso
      (periodicFunctorObjIso (R := R) (G := G) (g := g) M) ≪≫
    HomologicalComplex.alternatingConstScIsoOdd (ModuleCat.of R M.V)
    (by ext; simp [sub_hom, applyAsHom, norm]) (by ext; simp [sub_hom, applyAsHom, norm])
    (fun _ _ => ComplexShape.down_nat_odd_add) down_rel_prev
    (down_rel_next (by rintro rfl; simp at hj)) hj

/-- In a nonzero even degree, the short complex computing the homology of the periodic chain
complex is `M --(ρ(g) - 𝟙)--> M --N--> M`. -/
noncomputable def periodicScIsoEven {j : ℕ} (hj : Even j) (hj0 : j ≠ 0) :
    ((periodicFunctor R g).obj M).sc j ≅ subCompNormHom M g :=
  (HomologicalComplex.shortComplexFunctor (ModuleCat R) (ComplexShape.down ℕ) j).mapIso
      (periodicFunctorObjIso (R := R) (G := G) (g := g) M) ≪≫
    HomologicalComplex.alternatingConstScIsoEven (ModuleCat.of R M.V)
    (by ext; simp [sub_hom, applyAsHom, norm]) (by ext; simp [sub_hom, applyAsHom, norm])
    (fun _ _ => ComplexShape.down_nat_odd_add) down_rel_prev (down_rel_next hj0) hj

/-- The odd-degree identification `periodicScIsoOdd` is the identity on the first object. -/
@[simp]
theorem periodicScIsoOdd_hom_τ₁ {j : ℕ} (hj : Odd j) :
    (periodicScIsoOdd M g hj).hom.τ₁ = 𝟙 _ := (rfl)

/-- The odd-degree identification `periodicScIsoOdd` is the identity on the middle object. -/
@[simp]
theorem periodicScIsoOdd_hom_τ₂ {j : ℕ} (hj : Odd j) :
    (periodicScIsoOdd M g hj).hom.τ₂ = 𝟙 _ := (rfl)

/-- The odd-degree identification `periodicScIsoOdd` is the identity on the last object. -/
@[simp]
theorem periodicScIsoOdd_hom_τ₃ {j : ℕ} (hj : Odd j) :
    (periodicScIsoOdd M g hj).hom.τ₃ = 𝟙 _ := (rfl)

/-- The even-degree identification `periodicScIsoEven` is the identity on the first object. -/
@[simp]
theorem periodicScIsoEven_hom_τ₁ {j : ℕ} (hj : Even j) (hj0 : j ≠ 0) :
    (periodicScIsoEven M g hj hj0).hom.τ₁ = 𝟙 _ := (rfl)

/-- The even-degree identification `periodicScIsoEven` is the identity on the middle object. -/
@[simp]
theorem periodicScIsoEven_hom_τ₂ {j : ℕ} (hj : Even j) (hj0 : j ≠ 0) :
    (periodicScIsoEven M g hj hj0).hom.τ₂ = 𝟙 _ := (rfl)

/-- The even-degree identification `periodicScIsoEven` is the identity on the last object. -/
@[simp]
theorem periodicScIsoEven_hom_τ₃ {j : ℕ} (hj : Even j) (hj0 : j ≠ 0) :
    (periodicScIsoEven M g hj hj0).hom.τ₃ = 𝟙 _ := (rfl)

/-- In an odd degree the periodic chain complex computes the homology of
`M --N--> M --(ρ(g) - 𝟙)--> M`, the model of degree-zero Tate cohomology. -/
noncomputable def periodicHomologyIsoOdd {j : ℕ} (hj : Odd j) :
    ((periodicFunctor R g).obj M).homology j ≅ (normHomCompSub M g).homology :=
  ShortComplex.homologyMapIso (periodicScIsoOdd M g hj)

/-- In a nonzero even degree the periodic chain complex computes the homology of
`M --(ρ(g) - 𝟙)--> M --N--> M`, the model of Tate cohomology in degree `-1`. -/
noncomputable def periodicHomologyIsoEven {j : ℕ} (hj : Even j) (hj0 : j ≠ 0) :
    ((periodicFunctor R g).obj M).homology j ≅ (subCompNormHom M g).homology :=
  ShortComplex.homologyMapIso (periodicScIsoEven M g hj hj0)

/-- `periodicHomologyIsoOdd` is the map on homology induced by `periodicScIsoOdd`. -/
@[simp]
theorem periodicHomologyIsoOdd_hom {j : ℕ} (hj : Odd j) :
    (periodicHomologyIsoOdd M g hj).hom = ShortComplex.homologyMap (periodicScIsoOdd M g hj).hom :=
  (rfl)

/-- `periodicHomologyIsoEven` is the map on homology induced by `periodicScIsoEven`. -/
@[simp]
theorem periodicHomologyIsoEven_hom {j : ℕ} (hj : Even j) (hj0 : j ≠ 0) :
    (periodicHomologyIsoEven M g hj hj0).hom =
      ShortComplex.homologyMap (periodicScIsoEven M g hj hj0).hom :=
  (rfl)

variable {M}

/-- The short complex `M --N--> M --(ρ(g) - 𝟙)--> M` is functorial in `M`: a morphism of
representations acts by its underlying linear map in each of the three spots. -/
noncomputable def normHomCompSubMap (f : M ⟶ N) : normHomCompSub M g ⟶ normHomCompSub N g where
  τ₁ := ModuleCat.ofHom (Hom.hom f).toLinearMap
  τ₂ := ModuleCat.ofHom (Hom.hom f).toLinearMap
  τ₃ := ModuleCat.ofHom (Hom.hom f).toLinearMap
  comm₁₂ := by ext x; simp [norm_apply, Representation.norm, map_sum, hom_comm_apply]
  comm₂₃ := by ext x; simp [sub_hom, applyAsHom, hom_comm_apply]

/-- On the first object, `normHomCompSubMap g f` is the underlying linear map of `f`. -/
@[simp]
theorem normHomCompSubMap_τ₁ (f : M ⟶ N) :
    (normHomCompSubMap g f).τ₁ = ModuleCat.ofHom (Hom.hom f).toLinearMap := (rfl)

/-- On the middle object, `normHomCompSubMap g f` is the underlying linear map of `f`. -/
@[simp]
theorem normHomCompSubMap_τ₂ (f : M ⟶ N) :
    (normHomCompSubMap g f).τ₂ = ModuleCat.ofHom (Hom.hom f).toLinearMap := (rfl)

/-- On the last object, `normHomCompSubMap g f` is the underlying linear map of `f`. -/
@[simp]
theorem normHomCompSubMap_τ₃ (f : M ⟶ N) :
    (normHomCompSubMap g f).τ₃ = ModuleCat.ofHom (Hom.hom f).toLinearMap := (rfl)

/-- The short complex `M --(ρ(g) - 𝟙)--> M --N--> M` is functorial in `M`: a morphism of
representations acts by its underlying linear map in each of the three spots. -/
noncomputable def subCompNormHomMap (f : M ⟶ N) : subCompNormHom M g ⟶ subCompNormHom N g where
  τ₁ := ModuleCat.ofHom (Hom.hom f).toLinearMap
  τ₂ := ModuleCat.ofHom (Hom.hom f).toLinearMap
  τ₃ := ModuleCat.ofHom (Hom.hom f).toLinearMap
  comm₁₂ := by ext x; simp [sub_hom, applyAsHom, hom_comm_apply]
  comm₂₃ := by ext x; simp [norm_apply, Representation.norm, map_sum, hom_comm_apply]

/-- On the first object, `subCompNormHomMap g f` is the underlying linear map of `f`. -/
@[simp]
theorem subCompNormHomMap_τ₁ (f : M ⟶ N) :
    (subCompNormHomMap g f).τ₁ = ModuleCat.ofHom (Hom.hom f).toLinearMap := (rfl)

/-- On the middle object, `subCompNormHomMap g f` is the underlying linear map of `f`. -/
@[simp]
theorem subCompNormHomMap_τ₂ (f : M ⟶ N) :
    (subCompNormHomMap g f).τ₂ = ModuleCat.ofHom (Hom.hom f).toLinearMap := (rfl)

/-- On the last object, `subCompNormHomMap g f` is the underlying linear map of `f`. -/
@[simp]
theorem subCompNormHomMap_τ₃ (f : M ⟶ N) :
    (subCompNormHomMap g f).τ₃ = ModuleCat.ofHom (Hom.hom f).toLinearMap := (rfl)

/-- The odd-degree identification of the short complexes is natural in the coefficients. -/
theorem sc_map_comp_periodicScIsoOdd (f : M ⟶ N) {j : ℕ} (hj : Odd j) :
    (HomologicalComplex.shortComplexFunctor (ModuleCat R) (ComplexShape.down ℕ) j).map
        ((periodicFunctor R g).map f) ≫ (periodicScIsoOdd N g hj).hom =
      (periodicScIsoOdd M g hj).hom ≫ normHomCompSubMap g f := by
  refine ShortComplex.hom_ext _ _ ?_ ?_ ?_
  all_goals
    simp only [ShortComplex.comp_τ₁, ShortComplex.comp_τ₂, ShortComplex.comp_τ₃,
      periodicScIsoOdd_hom_τ₁, periodicScIsoOdd_hom_τ₂, periodicScIsoOdd_hom_τ₃,
      normHomCompSubMap_τ₁, normHomCompSubMap_τ₂, normHomCompSubMap_τ₃]
    rfl

/-- **Naturality of the odd-degree periodicity.** The homology of the periodic chain complex in
an odd degree is identified with the homology of `M --N--> M --(ρ(g) - 𝟙)--> M` compatibly with
morphisms of representations; in particular the identification does not depend on the odd degree
chosen. -/
theorem homologyMap_comp_periodicHomologyIsoOdd (f : M ⟶ N) {j : ℕ} (hj : Odd j) :
    HomologicalComplex.homologyMap ((periodicFunctor R g).map f) j ≫
        (periodicHomologyIsoOdd N g hj).hom =
      (periodicHomologyIsoOdd M g hj).hom ≫ ShortComplex.homologyMap (normHomCompSubMap g f) := by
  have h : ShortComplex.homologyMap ((HomologicalComplex.shortComplexFunctor (ModuleCat R)
        (ComplexShape.down ℕ) j).map ((periodicFunctor R g).map f) ≫
          (periodicScIsoOdd N g hj).hom) =
      ShortComplex.homologyMap ((periodicScIsoOdd M g hj).hom ≫ normHomCompSubMap g f) := by
    rw [sc_map_comp_periodicScIsoOdd]
  exact (ShortComplex.homologyMap_comp _ _).symm.trans
    (h.trans (ShortComplex.homologyMap_comp _ _))

/-- The even-degree identification of the short complexes is natural in the coefficients. -/
theorem sc_map_comp_periodicScIsoEven (f : M ⟶ N) {j : ℕ} (hj : Even j) (hj0 : j ≠ 0) :
    (HomologicalComplex.shortComplexFunctor (ModuleCat R) (ComplexShape.down ℕ) j).map
        ((periodicFunctor R g).map f) ≫ (periodicScIsoEven N g hj hj0).hom =
      (periodicScIsoEven M g hj hj0).hom ≫ subCompNormHomMap g f := by
  refine ShortComplex.hom_ext _ _ ?_ ?_ ?_
  all_goals
    simp only [ShortComplex.comp_τ₁, ShortComplex.comp_τ₂, ShortComplex.comp_τ₃,
      periodicScIsoEven_hom_τ₁, periodicScIsoEven_hom_τ₂, periodicScIsoEven_hom_τ₃,
      subCompNormHomMap_τ₁, subCompNormHomMap_τ₂, subCompNormHomMap_τ₃]
    rfl

/-- **Naturality of the even-degree periodicity.** The homology of the periodic chain complex in
a nonzero even degree is identified with the homology of `M --(ρ(g) - 𝟙)--> M --N--> M`
compatibly with morphisms of representations. -/
theorem homologyMap_comp_periodicHomologyIsoEven (f : M ⟶ N) {j : ℕ} (hj : Even j)
    (hj0 : j ≠ 0) :
    HomologicalComplex.homologyMap ((periodicFunctor R g).map f) j ≫
        (periodicHomologyIsoEven N g hj hj0).hom =
      (periodicHomologyIsoEven M g hj hj0).hom ≫
        ShortComplex.homologyMap (subCompNormHomMap g f) := by
  have h : ShortComplex.homologyMap ((HomologicalComplex.shortComplexFunctor (ModuleCat R)
        (ComplexShape.down ℕ) j).map ((periodicFunctor R g).map f) ≫
          (periodicScIsoEven N g hj hj0).hom) =
      ShortComplex.homologyMap ((periodicScIsoEven M g hj hj0).hom ≫
        subCompNormHomMap g f) := by
    rw [sc_map_comp_periodicScIsoEven]
  exact (ShortComplex.homologyMap_comp _ _).symm.trans
    (h.trans (ShortComplex.homologyMap_comp _ _))

variable (M)

/-- In an odd degree the homology of the periodic chain complex has the cardinality of
degree-zero Tate cohomology. -/
theorem natCard_periodicHomology_odd (hg : ∀ x, x ∈ Subgroup.zpowers g) {j : ℕ} (hj : Odd j) :
    Nat.card (((periodicFunctor R g).obj M).homology j) = Nat.card (tateCohomology M 0) :=
  Nat.card_congr ((periodicHomologyIsoOdd M g hj).toLinearEquiv.toEquiv.trans
    (tateCohomologyIso₀ M g hg).toLinearEquiv.toEquiv.symm)

/-- In a nonzero even degree the homology of the periodic chain complex has the cardinality of
Tate cohomology in degree `-1`. -/
theorem natCard_periodicHomology_even (hg : ∀ x, x ∈ Subgroup.zpowers g) {j : ℕ} (hj : Even j)
    (hj0 : j ≠ 0) :
    Nat.card (((periodicFunctor R g).obj M).homology j) = Nat.card (tateCohomology M (-1)) :=
  Nat.card_congr ((periodicHomologyIsoEven M g hj hj0).toLinearEquiv.toEquiv.trans
    (tateCohomologyIsoNegOne M g hg).toLinearEquiv.toEquiv.symm)

end PeriodicComplex

end Rep.FiniteCyclicGroup
