/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/

module

public import TauCeti.Algebra.Lie.Orthogonal.TypeD.Basis
public import TauCeti.Algebra.Lie.Orthogonal.TypeD.Serre.PositiveSimpleRootSpan
public import TauCeti.RepresentationTheory.Spin.Polarization.TypeD.ForkWeights
public import TauCeti.RepresentationTheory.Spin.Polarization.TypeD.Representation

/-!
# Positive simple-root data for the type-D spin representation

This file applies the Lie subalgebra generated by the simple positive root vectors to the two
standard half-spin vectors. Their annihilation by this span is the generator-level input for
showing that they are highest-weight vectors once the span is identified with the positive
nilradical of a compatible Borel subalgebra.

It also records the corresponding annihilation equations for the raising generators of the
concrete split orthogonal Lie algebra basis. Together with the Cartan-action calculation in
`CartanWeights.lean`, these are the concrete Lie-basis premises for the two fork highest weights.
-/

open CliffordAlgebra
open TauCeti

public section

namespace TauCeti.SpinPolarizationData

attribute [local instance 100] LieRing.ofAssociativeRing

section Field

universe u v

variable {K : Type u} [Field K] {V : Type v} [AddCommGroup V] [Module K V]
  {Q : QuadraticForm K V} (P : SpinPolarizationData Q)
  {n : ℕ} (b : Module.Basis (Fin n) K P.W) [Invertible (2 : K)]

/-- Every raising generator in the standard split type-`D` Lie basis annihilates the
all-coordinate exterior-basis vector. -/
theorem typeDSpinLieRep_lieBasis_e_exteriorBasis_univ_eq_zero
    (hn : 4 ≤ n) (hline : P.line = ⊥) (i : Fin n) :
    P.typeDSpinLieRep b hline ((TypeDStd.lieBasis (K := K) n hn).e i)
        (b.ExteriorAlgebra (Finset.univ : Finset (Fin n))) = 0 := by
  rw [TypeDStd.lieBasis_e, P.typeDSpinLieRep_apply,
    P.typeDQuadraticEquiv_rootGenerator]
  exact P.spinAction_typeDSimpleRootBivector_exteriorBasis_univ_eq_zero b (by omega) i

/-- Every raising generator in the standard split type-`D` Lie basis annihilates the
exterior-basis vector obtained by erasing the final coordinate. -/
theorem typeDSpinLieRep_lieBasis_e_exteriorBasis_univ_erase_last_eq_zero
    (hn : 4 ≤ n) (hline : P.line = ⊥) (i : Fin n) :
    P.typeDSpinLieRep b hline ((TypeDStd.lieBasis (K := K) n hn).e i)
        (b.ExteriorAlgebra
          ((Finset.univ : Finset (Fin n)).erase (⟨n - 1, by omega⟩ : Fin n))) = 0 := by
  rw [TypeDStd.lieBasis_e, P.typeDSpinLieRep_apply,
    P.typeDQuadraticEquiv_rootGenerator]
  exact P.spinAction_typeDSimpleRootBivector_exteriorBasis_univ_erase_last_eq_zero
    b (by omega) i

end Field

variable {V : Type*} [AddCommGroup V] [Module ℚ V] {Q : QuadraticForm ℚ V}
  (P : SpinPolarizationData Q) {n : ℕ} (b : Module.Basis (Fin n) ℚ P.W)

/-- For the transported type-`D` spin representation, annihilation by every positive simple
generator implies annihilation by their Lie span. -/
theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator
    (hn : 4 ≤ n) {v : ExteriorAlgebra ℚ P.W}
    (hv : ∀ i : Fin n,
      P.typeDSpinSerreRepresentation b hn
          (TauCeti.serreE ℚ (CartanMatrix.D n) i) v = 0) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    TauCeti.TypeDStd.positiveSimpleRootLieSpan n ≤
      TauCeti.lieAnnihilator ℚ _ v := by
  let _ : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
      (ExteriorAlgebra ℚ P.W) :=
    LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
  let _ : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
      (ExteriorAlgebra ℚ P.W) :=
    LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
  apply TauCeti.TypeDStd.positiveSimpleRootLieSpan_le_lieAnnihilator n v
  intro i
  exact by simpa [LieRingModule.compLieHom_apply] using hv i

/-- The all-coordinate exterior-basis vector is annihilated by the positive simple-root Lie span
in the transported type-`D` spin representation. -/
theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator_univ
    (hn : 4 ≤ n) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    TauCeti.TypeDStd.positiveSimpleRootLieSpan n ≤
      TauCeti.lieAnnihilator ℚ _
        (b.ExteriorAlgebra (Finset.univ : Finset (Fin n))) := by
  apply P.typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator b hn
  intro i
  rw [P.typeDSpinSerreRepresentation_serreE b hn]
  rw [← P.typeDSpinRep_serreE_eq_spinAction b hn]
  exact P.typeDSpinRep_serreE_exteriorBasis_univ_eq_zero b hn i

/-- The exterior-basis vector obtained by erasing the final coordinate from the all-coordinate
vector is annihilated by the positive simple-root Lie span in the transported type-`D` spin
representation. -/
theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator_univ_erase_last
    (hn : 4 ≤ n) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    TauCeti.TypeDStd.positiveSimpleRootLieSpan n ≤
      TauCeti.lieAnnihilator ℚ _
        (b.ExteriorAlgebra
          ((Finset.univ : Finset (Fin n)).erase (⟨n - 1, by omega⟩ : Fin n))) := by
  apply P.typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator b hn
  intro i
  rw [P.typeDSpinSerreRepresentation_serreE b hn]
  rw [← P.typeDSpinRep_serreE_eq_spinAction b hn]
  exact P.typeDSpinRep_serreE_exteriorBasis_univ_erase_last_eq_zero b hn i

end TauCeti.SpinPolarizationData
