/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Homology.AInfinity.Coderivation

/-!
# Nonunital A-infinity algebras

An uncurved nonunital `A∞` algebra on an internally `ℤ`-graded module consists of operations
`m n` of degree `2 - n`, with `m 0 = 0`, whose suspended Taylor map extends to a square-zero
degree-one coderivation of the reduced tensor coalgebra.  This file packages that definition and
exposes both of its standard presentations: the bar differential and the unsuspended Stasheff
identities.

The comparison between the presentations uses the degree-`-1` suspension convention.  In
particular, the arity-two identity has the sign `(-1)^|a|` on `m₂(a,m₁(b))`, while the arity-three
identity becomes ordinary associativity when `m₃` vanishes.  Arity zero is explicitly forced to
vanish, rather than being unconstrained data hidden from the bar construction.

## Main definitions

* `TauCeti.AInfinityAlgebra`: an uncurved nonunital `A∞` algebra.
* `TauCeti.AInfinityAlgebra.barDifferential`: its square-zero bar coderivation.
* `TauCeti.AInfinityAlgebra.ofStasheff`: construct an algebra from the unsuspended identities.

## References

* E. Getzler and J. D. S. Jones, *A-infinity algebras and the cyclic bar complex*, Sections 1--2.
* B. Keller, *Introduction to A-infinity algebras and modules*, Sections 3.1 and 3.6.
-/

public section

open scoped DirectSum TensorProduct

universe uR uA

namespace TauCeti

-- Interface provenance: the first `A∞` algebra prototype in
-- `TauCetiRoadmap/DGAInfinity/Suggested.lean` supplied the public shape packaged below.
/-- An uncurved nonunital `A∞` algebra over a commutative ring.

The Taylor map is stored alongside the operations because suspension depends on the degrees of
homogeneous inputs.  `taylor_isSuspension` determines it uniquely from `grading` and `m`, as
recorded by `AInfinity.IsSuspension.taylor_eq`.  Its graded Taylor expansion is the primary bar
coderivation, and `bar_square_zero` is the stored Stasheff law. -/
structure AInfinityAlgebra (R : Type uR) (A : Type uA) [CommRing R] [AddCommGroup A]
    [Module R A] where
  /-- The internal cohomological grading of the carrier. -/
  grading : InternalGrading R A
  /-- The unsuspended arity-`n` operation. -/
  m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A
  /-- The arity-zero operation vanishes: the algebra is uncurved. -/
  m_zero : m 0 = 0
  /-- The operation `m n` has cohomological degree `2 - n`. -/
  m_degree : ∀ n, 0 < n →
    MultilinearMap.IsHomogeneous (m n) (fun _ ↦ grading.piece) grading.piece (2 - n)
  /-- The Taylor map from nonempty suspended tensor words to suspended letters. -/
  taylor : ReducedTensorWords R A →ₗ[R] A
  /-- The Taylor map is the suspension of the displayed operations. -/
  taylor_isSuspension : AInfinity.IsSuspension grading taylor m
  /-- The degree-one coderivation extended from `taylor` squares to zero. -/
  bar_square_zero :
    ReducedTensorWords.gradedCoderiv (grading.shift 1) taylor 1 ∘ₗ
        ReducedTensorWords.gradedCoderiv (grading.shift 1) taylor 1 = 0

namespace AInfinityAlgebra

variable {R : Type uR} {A : Type uA} [CommRing R] [AddCommGroup A] [Module R A]

attribute [simp] AInfinityAlgebra.m_zero

/-- The degree-one coderivation of the reduced bar construction. -/
noncomputable def barDifferential (𝒜 : AInfinityAlgebra R A) :
    ReducedTensorWords R A →ₗ[R] ReducedTensorWords R A :=
  ReducedTensorWords.gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1

/-- The bar differential is the coderivation generated by the stored Taylor map. -/
theorem barDifferential_def (𝒜 : AInfinityAlgebra R A) :
    𝒜.barDifferential =
      ReducedTensorWords.gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1 := by
  rw [barDifferential]

/-- The bar differential is a graded coderivation for the suspended grading. -/
theorem isGradedCoderivation_barDifferential (𝒜 : AInfinityAlgebra R A) :
    ReducedTensorWords.IsGradedCoderivation (𝒜.grading.shift 1) 1 𝒜.barDifferential := by
  simpa only [barDifferential_def] using
    ReducedTensorWords.isGradedCoderivation_gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1

/-- The bar differential has cohomological degree one. -/
theorem isHomogeneous_barDifferential (𝒜 : AInfinityAlgebra R A) :
    LinearMap.IsHomogeneous 𝒜.barDifferential
      (ReducedTensorWords.gradedPiece (𝒜.grading.shift 1))
      (ReducedTensorWords.gradedPiece (𝒜.grading.shift 1)) 1 := by
  simpa only [barDifferential_def] using
    ReducedTensorWords.isHomogeneous_gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1 _
      (𝒜.taylor_isSuspension.isHomogeneous 𝒜.m_degree)

/-- The letter component of the bar differential is its stored Taylor map. -/
@[simp]
theorem letter_comp_barDifferential (𝒜 : AInfinityAlgebra R A) :
    ReducedTensorWords.letter R A ∘ₗ 𝒜.barDifferential = 𝒜.taylor := by
  rw [barDifferential, ReducedTensorWords.letter_comp_gradedCoderiv]

/-- The bar differential squares to zero. -/
@[simp]
theorem barDifferential_sq (𝒜 : AInfinityAlgebra R A) :
    𝒜.barDifferential ∘ₗ 𝒜.barDifferential = 0 := by
  simpa only [barDifferential_def] using 𝒜.bar_square_zero

/-- The square-zero bar law is equivalent to all unsuspended Stasheff identities on homogeneous
inputs. -/
theorem barDifferential_sq_iff_stasheff (𝒜 : AInfinityAlgebra R A) :
    𝒜.barDifferential ∘ₗ 𝒜.barDifferential = 0 ↔
      ∀ (n : ℕ) (_hn : 0 < n) (d : ℕ → ℤ) (x : ℕ → A),
        (∀ i < n, x i ∈ 𝒜.grading.piece (d i)) →
          AInfinity.stasheffSum 𝒜.m d x n = 0 := by
  simpa only [barDifferential_def] using
    𝒜.taylor_isSuspension.comp_self_eq_zero_iff_forall_stasheffSum_eq_zero 𝒜.m_degree

/-- The unsuspended operations of an `A∞` algebra satisfy every Stasheff identity on homogeneous
inputs. -/
theorem stasheff (𝒜 : AInfinityAlgebra R A) (n : ℕ) (hn : 0 < n)
    (d : ℕ → ℤ) (x : ℕ → A) (hx : ∀ i < n, x i ∈ 𝒜.grading.piece (d i)) :
    AInfinity.stasheffSum 𝒜.m d x n = 0 :=
  𝒜.barDifferential_sq_iff_stasheff.mp 𝒜.barDifferential_sq n hn d x hx

/-- Construct an `A∞` algebra from homogeneous operations satisfying the unsuspended Stasheff
identities and a Taylor map realizing their suspension. -/
def ofStasheff (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 : m 0 = 0)
    (hm : ∀ n, 0 < n →
      MultilinearMap.IsHomogeneous (m n) (fun _ ↦ G.piece) G.piece (2 - n))
    (F : ReducedTensorWords R A →ₗ[R] A) (hFm : AInfinity.IsSuspension G F m)
    (hSI : ∀ (n : ℕ) (_hn : 0 < n) (d : ℕ → ℤ) (x : ℕ → A),
      (∀ i < n, x i ∈ G.piece (d i)) → AInfinity.stasheffSum m d x n = 0) :
    AInfinityAlgebra R A where
  grading := G
  m := m
  m_zero := hm0
  m_degree := hm
  taylor := F
  taylor_isSuspension := hFm
  bar_square_zero :=
    (hFm.comp_self_eq_zero_iff_forall_stasheffSum_eq_zero hm).2 hSI

@[simp]
theorem ofStasheff_grading (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 hm F hFm hSI) :
    (ofStasheff G m hm0 hm F hFm hSI).grading = G := (rfl)

@[simp]
theorem ofStasheff_m (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 hm F hFm hSI) :
    (ofStasheff G m hm0 hm F hFm hSI).m = m := (rfl)

@[simp]
theorem ofStasheff_taylor (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 hm F hFm hSI) :
    (ofStasheff G m hm0 hm F hFm hSI).taylor = F := (rfl)

/-- `A∞` algebras are determined by their grading and unsuspended operations; the Taylor map is
forced by the suspension relation and all remaining fields are propositions. -/
@[ext]
theorem ext {𝒜 𝒜' : AInfinityAlgebra R A} (hG : 𝒜.grading = 𝒜'.grading)
    (hm : 𝒜.m = 𝒜'.m) : 𝒜 = 𝒜' := by
  cases 𝒜 with
  | mk G m hm0 hmdeg F hFm hsq =>
    cases 𝒜' with
    | mk G' m' hm0' hmdeg' F' hFm' hsq' =>
      simp only at hG hm
      subst G'
      subst m'
      have hFF' := AInfinity.IsSuspension.taylor_eq hFm hFm'
      subst F'
      rfl

/-! ### Low-arity identities -/

/-- The arity-one identity is `m₁ m₁ = 0`. -/
theorem stasheff_arity_one (𝒜 : AInfinityAlgebra R A) (x : A) : 𝒜.m 1 ![𝒜.m 1 ![x]] = 0 := by
  let E : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 1).curryRight ![])
  suffices E x = 0 by simpa [E] using this
  have hE : E = 0 := by
    apply 𝒜.grading.linearMap_ext
    intro p y hy
    have h := 𝒜.stasheff 1 (by omega) (fun _ ↦ p) (fun _ ↦ y) (fun _ _ ↦ hy)
    simpa [E, AInfinity.stasheffSum_one] using h
  rw [hE, LinearMap.zero_apply]

/-- The arity-two identity is the graded Leibniz rule, with sign `(-1)^(d 0)` on the second
differentiated input. -/
theorem stasheff_arity_two (𝒜 : AInfinityAlgebra R A) (x y : A) (p : ℤ)
    (hx : x ∈ 𝒜.grading.piece p) :
    𝒜.m 1 ![𝒜.m 2 ![x, y]] =
      𝒜.m 2 ![𝒜.m 1 ![x], y] +
        negOnePowCast R p • 𝒜.m 2 ![x, 𝒜.m 1 ![y]] := by
  let L : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 2).curryRight ![x])
  let Q : A →ₗ[R] A :=
    (𝒜.m 2).curryRight ![𝒜.m 1 ![x]] +
      negOnePowCast R p • ((𝒜.m 2).curryRight ![x]).comp ((𝒜.m 1).curryRight ![])
  suffices L y = Q y by simpa [L, Q] using this
  have hLQ : L = Q := by
    apply 𝒜.grading.linearMap_ext
    intro q z hz
    let d : ℕ → ℤ := fun i ↦ if i = 0 then p else q
    let a : ℕ → A := fun i ↦ if i = 0 then x else z
    have ha : ∀ i < 2, a i ∈ 𝒜.grading.piece (d i) := by
      intro i hi
      have hi' : i = 0 ∨ i = 1 := by omega
      rcases hi' with rfl | rfl
      · simpa [a, d] using hx
      · simpa [a, d] using hz
    have h := (AInfinity.stasheffSum_two_eq_zero_iff 𝒜.m d a).mp
      (𝒜.stasheff 2 (by omega) d a ha)
    simpa [L, Q, a, d] using h
  exact LinearMap.congr_fun hLQ y

/-- The arity-three Stasheff identity, with the Koszul signs determined by the degrees of its
first two inputs. -/
theorem stasheff_arity_three (𝒜 : AInfinityAlgebra R A) (a b c : A) (p q : ℤ)
    (ha : a ∈ 𝒜.grading.piece p) (hb : b ∈ 𝒜.grading.piece q) :
    𝒜.m 1 ![𝒜.m 3 ![a, b, c]]
      + 𝒜.m 2 ![𝒜.m 2 ![a, b], c] - 𝒜.m 2 ![a, 𝒜.m 2 ![b, c]]
      + 𝒜.m 3 ![𝒜.m 1 ![a], b, c]
      + negOnePowCast R p • 𝒜.m 3 ![a, 𝒜.m 1 ![b], c]
      + negOnePowCast R (p + q) • 𝒜.m 3 ![a, b, 𝒜.m 1 ![c]] = 0 := by
  let E : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 3).curryRight ![a, b])
      + (𝒜.m 2).curryRight ![𝒜.m 2 ![a, b]]
      - ((𝒜.m 2).curryRight ![a]).comp ((𝒜.m 2).curryRight ![b])
      + (𝒜.m 3).curryRight ![𝒜.m 1 ![a], b]
      + negOnePowCast R p • (𝒜.m 3).curryRight ![a, 𝒜.m 1 ![b]]
      + negOnePowCast R (p + q) •
        ((𝒜.m 3).curryRight ![a, b]).comp ((𝒜.m 1).curryRight ![])
  suffices E c = 0 by simpa [E] using this
  have hE : E = 0 := by
    apply 𝒜.grading.linearMap_ext
    intro r z hz
    let d : ℕ → ℤ := fun i ↦ if i = 0 then p else if i = 1 then q else r
    let x : ℕ → A := fun i ↦ if i = 0 then a else if i = 1 then b else z
    have hx : ∀ i < 3, x i ∈ 𝒜.grading.piece (d i) := by
      intro i hi
      have hi' : i = 0 ∨ i = 1 ∨ i = 2 := by omega
      rcases hi' with rfl | rfl | rfl
      · simpa [x, d] using ha
      · simpa [x, d] using hb
      · simpa [x, d] using hz
    have h := 𝒜.stasheff 3 (by omega) d x hx
    rw [AInfinity.stasheffSum_three] at h
    simpa [E, x, d] using h
  rw [hE, LinearMap.zero_apply]

/-- The arity-four Stasheff identity, with the Koszul signs determined by the degrees of its
first three inputs. -/
theorem stasheff_arity_four (𝒜 : AInfinityAlgebra R A) (a b c d : A) (p q r : ℤ)
    (ha : a ∈ 𝒜.grading.piece p) (hb : b ∈ 𝒜.grading.piece q)
    (hc : c ∈ 𝒜.grading.piece r) :
    𝒜.m 1 ![𝒜.m 4 ![a, b, c, d]] - 𝒜.m 2 ![𝒜.m 3 ![a, b, c], d]
      - negOnePowCast R p • 𝒜.m 2 ![a, 𝒜.m 3 ![b, c, d]]
      + 𝒜.m 3 ![𝒜.m 2 ![a, b], c, d] - 𝒜.m 3 ![a, 𝒜.m 2 ![b, c], d]
      + 𝒜.m 3 ![a, b, 𝒜.m 2 ![c, d]] - 𝒜.m 4 ![𝒜.m 1 ![a], b, c, d]
      - negOnePowCast R p • 𝒜.m 4 ![a, 𝒜.m 1 ![b], c, d]
      - negOnePowCast R (p + q) • 𝒜.m 4 ![a, b, 𝒜.m 1 ![c], d]
      - negOnePowCast R (p + q + r) • 𝒜.m 4 ![a, b, c, 𝒜.m 1 ![d]] = 0 := by
  let E : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 4).curryRight ![a, b, c])
      - (𝒜.m 2).curryRight ![𝒜.m 3 ![a, b, c]]
      - negOnePowCast R p •
        ((𝒜.m 2).curryRight ![a]).comp ((𝒜.m 3).curryRight ![b, c])
      + (𝒜.m 3).curryRight ![𝒜.m 2 ![a, b], c]
      - (𝒜.m 3).curryRight ![a, 𝒜.m 2 ![b, c]]
      + ((𝒜.m 3).curryRight ![a, b]).comp ((𝒜.m 2).curryRight ![c])
      - (𝒜.m 4).curryRight ![𝒜.m 1 ![a], b, c]
      - negOnePowCast R p • (𝒜.m 4).curryRight ![a, 𝒜.m 1 ![b], c]
      - negOnePowCast R (p + q) • (𝒜.m 4).curryRight ![a, b, 𝒜.m 1 ![c]]
      - negOnePowCast R (p + q + r) •
        ((𝒜.m 4).curryRight ![a, b, c]).comp ((𝒜.m 1).curryRight ![])
  suffices E d = 0 by simpa [E] using this
  have hE : E = 0 := by
    apply 𝒜.grading.linearMap_ext
    intro s z hz
    let e : ℕ → ℤ := fun i ↦
      if i = 0 then p else if i = 1 then q else if i = 2 then r else s
    let x : ℕ → A := fun i ↦
      if i = 0 then a else if i = 1 then b else if i = 2 then c else z
    have hx : ∀ i < 4, x i ∈ 𝒜.grading.piece (e i) := by
      intro i hi
      have hi' : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 := by omega
      rcases hi' with rfl | rfl | rfl | rfl
      · simpa [x, e] using ha
      · simpa [x, e] using hb
      · simpa [x, e] using hc
      · simpa [x, e] using hz
    have h := 𝒜.stasheff 4 (by omega) e x hx
    rw [AInfinity.stasheffSum_four] at h
    simpa [E, x, e] using h
  rw [hE, LinearMap.zero_apply]

/-- If the ternary operation vanishes, the arity-three identity says that `m₂` is associative. -/
theorem m_two_assoc_of_m_three_eq_zero (𝒜 : AInfinityAlgebra R A) (h₃ : 𝒜.m 3 = 0)
    (x y z : A) :
    𝒜.m 2 ![𝒜.m 2 ![x, y], z] = 𝒜.m 2 ![x, 𝒜.m 2 ![y, z]] := by
  -- Package the left- and right-associated products as trilinear maps. It then suffices to
  -- compare them on homogeneous first and second inputs via `stasheff_arity_three`.
  let L : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (((𝒜.m 2).domDomCongr (Fin.oneSlotEquiv 0 1).symm).oneSlot (𝒜.m 2)).domDomCongr
      (Fin.blockEquiv 0 2 1)
  let Q : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (((𝒜.m 2).domDomCongr (Fin.oneSlotEquiv 1 0).symm).oneSlot (𝒜.m 2)).domDomCongr
      (Fin.blockEquiv 1 2 0)
  have L_apply (a b c : A) : L ![a, b, c] = 𝒜.m 2 ![𝒜.m 2 ![a, b], c] := by
    simp only [L, MultilinearMap.domDomCongr_apply, MultilinearMap.oneSlot_apply]
    congr 1
    funext i
    obtain ⟨j, rfl⟩ := (Fin.oneSlotEquiv 0 1).surjective i
    rcases j with j | (j | j)
    · exact Fin.elim0 j
    · rcases j with ⟨⟩
      simp only [Equiv.symm_apply_apply, Sum.elim_inr, Sum.elim_inl]
      have hout : Fin.oneSlotEquiv 0 1 (.inr (.inl ())) = (0 : Fin 2) := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_middle_val 0 1
      rw [hout]
      -- Expose the inner tuple selected by `oneSlot` so that `blockEquiv` can be evaluated
      -- coordinatewise; simplification does not unfold vector notation to this form.
      change (𝒜.m 2) (fun j ↦ ![a, b, c] (Fin.blockEquiv 0 2 1 (.inr (.inl j)))) =
        𝒜.m 2 ![a, b]
      congr 1
      funext k
      have hi : Fin.blockEquiv 0 2 1 (.inr (.inl k)) =
          ⟨k, by omega⟩ := by
        apply Fin.ext
        simpa only [Nat.zero_add] using Fin.blockEquiv_middle_val 0 2 1 k
      rw [hi]
      fin_cases k <;> rfl
    · simp only [Equiv.symm_apply_apply, Sum.elim_inr]
      have hout : Fin.oneSlotEquiv 0 1 (.inr (.inr j)) = ⟨1 + j, by omega⟩ := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_suffix_val 0 1 j
      have hin : Fin.blockEquiv 0 2 1 (.inr (.inr j)) = ⟨2 + j, by omega⟩ := by
        apply Fin.ext
        exact Fin.blockEquiv_suffix_val 0 2 1 j
      rw [hout, hin]
      fin_cases j
      rfl
  have Q_apply (a b c : A) : Q ![a, b, c] = 𝒜.m 2 ![a, 𝒜.m 2 ![b, c]] := by
    simp only [Q, MultilinearMap.domDomCongr_apply, MultilinearMap.oneSlot_apply]
    congr 1
    funext i
    obtain ⟨j, rfl⟩ := (Fin.oneSlotEquiv 1 0).surjective i
    rcases j with j | (j | j)
    · simp only [Equiv.symm_apply_apply, Sum.elim_inl]
      have hout : Fin.oneSlotEquiv 1 0 (.inl j) = ⟨j, by omega⟩ := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_inl_val 1 0 j
      have hin : Fin.blockEquiv 1 2 0 (.inl j) = ⟨j, by omega⟩ := by
        apply Fin.ext
        exact Fin.blockEquiv_inl_val 1 2 0 j
      rw [hout, hin]
      fin_cases j
      rfl
    · rcases j with ⟨⟩
      simp only [Equiv.symm_apply_apply, Sum.elim_inr, Sum.elim_inl]
      have hout : Fin.oneSlotEquiv 1 0 (.inr (.inl ())) = (1 : Fin 2) := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_middle_val 1 0
      rw [hout]
      -- As above, expose the inner tuple; the coordinate proof below identifies this middle
      -- block with the final two entries of the original tuple.
      change (𝒜.m 2) (fun j ↦ ![a, b, c] (Fin.blockEquiv 1 2 0 (.inr (.inl j)))) =
        𝒜.m 2 ![b, c]
      congr 1
      funext k
      have hi : Fin.blockEquiv 1 2 0 (.inr (.inl k)) = ⟨1 + k, by omega⟩ := by
        apply Fin.ext
        exact Fin.blockEquiv_middle_val 1 2 0 k
      rw [hi]
      fin_cases k <;> rfl
    · exact Fin.elim0 j
  have hcurry : L.curryRight = Q.curryRight := by
    apply 𝒜.grading.multilinearMap_ext
    intro d a ha
    ext c
    have h := 𝒜.stasheff_arity_three (a 0) (a 1) c (d 0) (d 1) (ha 0) (ha 1)
    rw [h₃] at h
    have hz : 𝒜.m 1 ![(0 : A)] = 0 := (𝒜.m 1).map_coord_zero 0 rfl
    simp only [MultilinearMap.curryRight_apply]
    have hac : Fin.snoc a c = ![a 0, a 1, c] := by
      funext i
      fin_cases i <;> rfl
    rw [hac]
    rw [L_apply, Q_apply]
    apply sub_eq_zero.mp
    simpa only [_root_.zero_apply, hz, smul_zero, add_zero, zero_add] using h
  have hLQ : L = Q := by
    rw [← MultilinearMap.uncurry_curryRight L, ← MultilinearMap.uncurry_curryRight Q,
      hcurry]
  rw [← L_apply, ← Q_apply]
  exact MultilinearMap.congr_fun hLQ ![x, y, z]

end AInfinityAlgebra

end TauCeti
