/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Module.PID
public import TauCeti.RingTheory.AdjoinRoot.Basic
public import TauCeti.RingTheory.Polynomial.Truncated.Basic

/-!
# The indecomposable modules over `k[X]/(Xⁿ)`

Let `k` be a field, `A = k[X]/(Xⁿ)` the truncated polynomial algebra, with `x` the class of `X`,
and for `i ≤ n` let `M_i = A ⧸ (x ^ i)`, a cyclic right `A`-module of dimension `i`. Right
`A`-modules are left `Aᵐᵒᵖ`-modules, and `M_i` is the quotient of the regular module `Aᵐᵒᵖ` by
the ideal generated by `op (x ^ i)`. This file proves that `M_1, …, M_n` are, up to isomorphism,
exactly the indecomposable finitely generated right `A`-modules, and that every finitely
generated right `A`-module is a finite direct sum of them.

The modules `M_i` are the cyclic modules whose stable syzygies and stable morphism spaces over the
self-injective algebra `A` are computed in `TauCeti.Algebra.Category.FGModuleCat.Stable.Syzygy` and
`TauCeti.Algebra.Category.FGModuleCat.Stable.CyclicHom`; the classification says that up to finite
direct sums they are all the finitely generated right `A`-modules.

## Main results

* `TauCeti.isIndecomposableModule_quotient_span_op_root_X_pow_pow`: `M_i` is indecomposable for
  `0 < i ≤ n`.
* `TauCeti.nonempty_linearEquiv_quotient_span_op_root_X_pow_pow_iff`: for `i, j ≤ n`, `M_i` and
  `M_j` are isomorphic only when `i = j`.
* `TauCeti.exists_linearEquiv_quotient_span_op_root_X_pow_pow_of_isIndecomposableModule`: every
  indecomposable finitely generated right `A`-module is isomorphic to some `M_i` with `0 < i ≤ n`,
  packaged with the converse as
  `TauCeti.isIndecomposableModule_iff_exists_linearEquiv_quotient_span_op_root_X_pow_pow`.
* `TauCeti.exists_linearEquiv_directSum_quotient_span_op_root_X_pow_pow`: every finitely generated
  right `A`-module is isomorphic to a finite direct sum of modules `M_i` with `0 < i ≤ n`.

## Implementation notes

A right `A`-module `M` becomes a `k[X]`-module through the surjection `k[X] → A → Aᵐᵒᵖ`, killed by
`Xⁿ`, and `k[X]`-submodules and `Aᵐᵒᵖ`-submodules of `M` agree
(`TauCeti.isIndecomposableModule_iff_isIndecomposableModule_of_algebraMap_surjective`). An
indecomposable `M` is therefore a cyclic primary `k[X]`-module `k[X] ⧸ (pᵉ)` by the structure
theorem over a principal ideal domain
(`TauCeti.exists_linearEquiv_quotient_pow_of_isIndecomposableModule`); as `pᵉ` divides `Xⁿ`, the
prime `p` is associated to `X` and `e ≤ n`, and `k[X] ⧸ (Xᵉ)` is `M_e` with its scalars
restricted. The `k[X]`-linear isomorphism is then `Aᵐᵒᵖ`-linear, by
`LinearEquiv.extendScalarsOfSurjective`. Indecomposability of `M_i` holds because `M_i` is a
quotient ring of the local ring `Aᵐᵒᵖ`, hence local, and a local ring is indecomposable over
itself. The decomposition into the `M_i` is the Krull–Schmidt existence theorem for the Artinian
module `M`, followed by the classification of its indecomposable summands.

## References

The classification is the special case `k[X]/(Xⁿ)` of the description of the indecomposable
modules over a Nakayama algebra: see I. Assem, D. Simson, A. Skowroński, *Elements of the
Representation Theory of Associative Algebras, Vol. 1*, Chapter V.
-/

public section

namespace TauCeti

open Polynomial MulOpposite
open scoped DirectSum

universe u v

variable {K : Type u} [Field K] {n : ℕ}

/-- The surjection `K[X] → K[X]/(Xⁿ) → (K[X]/(Xⁿ))ᵐᵒᵖ` through which a right module over the
truncated polynomial algebra is a `K[X]`-module. -/
private noncomputable abbrev truncatedOpHom (K : Type u) [Field K] (n : ℕ) :
    K[X] →+* (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ :=
  (RingEquiv.toOpposite (AdjoinRoot (X ^ n : K[X]))).toRingHom.comp (AdjoinRoot.mk _)

private theorem truncatedOpHom_surjective : Function.Surjective (truncatedOpHom K n) :=
  (RingEquiv.toOpposite _).surjective.comp (AdjoinRoot.mk_surjective)

/-- For `i ≤ n`, a polynomial maps into the ideal generated by `op (x ^ i)` exactly when it is
divisible by `X ^ i`. -/
private theorem comap_truncatedOpHom_span_op_root_pow {i : ℕ} (hi : i ≤ n) :
    Ideal.comap (truncatedOpHom K n)
        (Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ i)}) =
      Ideal.span {X ^ i} := by
  ext r
  rw [Ideal.mem_comap, Ideal.mem_span_singleton, Ideal.mem_span_singleton, ← AdjoinRoot.mk_X,
    ← map_pow]
  -- Unfold the composite to a divisibility in `AdjoinRoot`, then drop the opposite.
  change op (AdjoinRoot.mk _ (X ^ i)) ∣ op (AdjoinRoot.mk _ r) ↔ _
  rw [← RingEquiv.toOpposite_apply, ← RingEquiv.toOpposite_apply, map_dvd_iff]
  constructor
  · rintro ⟨c, hc⟩
    obtain ⟨q, rfl⟩ := AdjoinRoot.mk_surjective c
    rw [← map_mul, AdjoinRoot.mk_eq_mk] at hc
    obtain ⟨s, hs⟩ := hc
    refine ⟨q + X ^ (n - i) * s, ?_⟩
    rw [mul_add, ← mul_assoc, ← pow_add, Nat.add_sub_cancel' hi]
    linear_combination hs
  · rintro ⟨q, rfl⟩
    exact ⟨AdjoinRoot.mk _ q, map_mul _ _ _⟩

/-- **The cyclic module `M_i = A ⧸ (x ^ i)` over `A = K[X]/(Xⁿ)` is indecomposable** for
`0 < i ≤ n`. -/
theorem isIndecomposableModule_quotient_span_op_root_X_pow_pow {i : ℕ} (hi : 0 < i)
    (hin : i ≤ n) :
    IsIndecomposableModule (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ
      ((AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸
        Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ i)}) := by
  have : NeZero n := ⟨by omega⟩
  set I := Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ i)}
  -- `op (x ^ i)` is nilpotent, so it generates a proper ideal.
  have hI : I ≠ ⊤ := by
    rw [Ne, Ideal.span_singleton_eq_top]
    refine IsNilpotent.not_isUnit ?_
    exact ((isNilpotent_root_X_pow n).pow_of_pos hi.ne').map (RingEquiv.toOpposite _)
  have : Nontrivial (_ ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr hI
  have : IsLocalRing (_ ⧸ I) := .of_surjective' (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  exact (isIndecomposableModule_iff_isIndecomposableModule_of_algebraMap_surjective
    (M := _ ⧸ I) Ideal.Quotient.mk_surjective).mpr (isIndecomposableModule_self _)

/-- **The modules `M_i` are pairwise non-isomorphic**: for `i, j ≤ n`, the cyclic modules
`A ⧸ (x ^ i)` and `A ⧸ (x ^ j)` over `A = K[X]/(Xⁿ)` are isomorphic exactly when `i = j`, since
they have dimensions `i` and `j` over `K`. -/
theorem nonempty_linearEquiv_quotient_span_op_root_X_pow_pow_iff {i j : ℕ} (hi : i ≤ n)
    (hj : j ≤ n) :
    Nonempty (((AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸
        Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ i)}) ≃ₗ[(AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ]
      ((AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸
        Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ j)})) ↔ i = j := by
  refine ⟨fun ⟨e⟩ ↦ ?_, by rintro rfl; exact ⟨LinearEquiv.refl _ _⟩⟩
  rw [← AdjoinRoot.finrank_quotient_span_op_root_X_pow_pow (R := K) hi,
    ← AdjoinRoot.finrank_quotient_span_op_root_X_pow_pow (R := K) hj]
  exact (e.restrictScalars K).finrank_eq

/-- **Every indecomposable finitely generated right module over `A = K[X]/(Xⁿ)` is one of the
`M_i`**: it is isomorphic to `A ⧸ (x ^ i)` for some `0 < i ≤ n`. -/
theorem exists_linearEquiv_quotient_span_op_root_X_pow_pow_of_isIndecomposableModule
    {M : Type v} [AddCommGroup M] [Module (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M]
    [Module.Finite (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M]
    (h : IsIndecomposableModule (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M) :
    ∃ i, 0 < i ∧ i ≤ n ∧ Nonempty (M ≃ₗ[(AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ]
      (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸ Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ i)}) := by
  -- View `M` as a `K[X]`-module through the surjection `K[X] → Aᵐᵒᵖ`.
  let φ := truncatedOpHom K n
  let : Algebra K[X] (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ := φ.toAlgebra
  let : Module K[X] M := Module.compHom M φ
  -- Both actions of `r : K[X]` are, by construction, the action of `φ r`.
  have : IsScalarTower K[X] (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M :=
    ⟨fun r a m ↦ mul_smul (φ r) a m⟩
  have hφ : Function.Surjective (algebraMap K[X] (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ) :=
    truncatedOpHom_surjective
  have : Module.Finite K[X] (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ :=
    .of_surjective (Algebra.linearMap K[X] _) hφ
  have : Module.Finite K[X] M := .trans (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M
  have hX (m : M) : (X ^ n : K[X]) • m = 0 := by
    -- The `K[X]`-action on `M` is the action of `φ`, by construction of `Module.compHom`.
    change φ (X ^ n) • m = 0
    simp [φ]
  have htors : Module.IsTorsion K[X] M := fun m ↦
    ⟨⟨X ^ n, mem_nonZeroDivisors_of_ne_zero (pow_ne_zero n X_ne_zero)⟩, hX m⟩
  obtain ⟨p, hp, e, he, ⟨g⟩⟩ := exists_linearEquiv_quotient_pow_of_isIndecomposableModule htors
    ((isIndecomposableModule_iff_isIndecomposableModule_of_algebraMap_surjective hφ).mpr h)
  -- `Xⁿ` kills `K[X] ⧸ (pᵉ)`, so `pᵉ ∣ Xⁿ`: the prime `p` is associated to `X` and `e ≤ n`.
  have hdvd : p ^ e ∣ X ^ n := by
    have := congrArg g (hX (g.symm (Submodule.Quotient.mk 1)))
    rw [map_smul, g.apply_symm_apply, map_zero, ← Submodule.Quotient.mk_smul, smul_eq_mul,
      mul_one, Submodule.Quotient.mk_eq_zero, Submodule.mem_span_singleton] at this
    obtain ⟨a, ha⟩ := this
    exact ⟨a, by rw [← ha, smul_eq_mul, mul_comm]⟩
  have hpX : Associated p X := hp.associated_of_dvd irreducible_X
    (hp.prime.dvd_of_dvd_pow ((dvd_pow_self p he.ne').trans hdvd))
  have hen : e ≤ n :=
    (pow_dvd_pow_iff X_ne_zero not_isUnit_X).mp ((hpX.pow_pow (n := e)).symm.dvd.trans hdvd)
  refine ⟨e, he, hen, ⟨?_⟩⟩
  -- `K[X] ⧸ (pᵉ) = K[X] ⧸ (Xᵉ)` is `M_e` with scalars restricted to `K[X]`.
  set I := Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ e)}
  let κ : K[X] →ₗ[K[X]] (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸ I :=
    (I.mkQ.restrictScalars K[X]) ∘ₗ Algebra.linearMap K[X] _
  have hκ : Function.Surjective κ := (Submodule.mkQ_surjective I).comp hφ
  have hker : K[X] ∙ p ^ e = LinearMap.ker κ := by
    ext r
    rw [LinearMap.mem_ker]
    -- `K[X] ∙ pᵉ` is by definition the ideal `(pᵉ)`, and `κ r` is the class of `φ r`.
    change r ∈ Ideal.span {p ^ e} ↔ Submodule.Quotient.mk (φ r) = (0 : _ ⧸ I)
    rw [Submodule.Quotient.mk_eq_zero, ← Ideal.mem_comap, comap_truncatedOpHom_span_op_root_pow hen,
      Ideal.span_singleton_eq_span_singleton.mpr hpX.pow_pow]
  exact (g ≪≫ₗ Submodule.quotEquivOfEq _ _ hker ≪≫ₗ κ.quotKerEquivOfSurjective hκ)
    |>.extendScalarsOfSurjective hφ

/-- **The indecomposable finitely generated right modules over `A = K[X]/(Xⁿ)` are exactly the
`M_i`**, up to isomorphism: such a module is indecomposable exactly when it is isomorphic to
`A ⧸ (x ^ i)` for some `0 < i ≤ n`. -/
theorem isIndecomposableModule_iff_exists_linearEquiv_quotient_span_op_root_X_pow_pow
    {M : Type v} [AddCommGroup M] [Module (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M]
    [Module.Finite (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M] :
    IsIndecomposableModule (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M ↔
      ∃ i, 0 < i ∧ i ≤ n ∧ Nonempty (M ≃ₗ[(AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ]
        (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸
          Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ i)}) :=
  ⟨exists_linearEquiv_quotient_span_op_root_X_pow_pow_of_isIndecomposableModule,
    fun ⟨_, hi, hin, ⟨e⟩⟩ ↦
      (isIndecomposableModule_quotient_span_op_root_X_pow_pow hi hin).of_linearEquiv e.symm⟩

/-- **Every finitely generated right module over `A = K[X]/(Xⁿ)` is a direct sum of the `M_i`**:
it is isomorphic to `⨁ j, A ⧸ (x ^ e j)` for finitely many exponents `0 < e j ≤ n`. -/
theorem exists_linearEquiv_directSum_quotient_span_op_root_X_pow_pow
    (M : Type v) [AddCommGroup M] [Module (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M]
    [Module.Finite (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ M] :
    ∃ (k : ℕ) (e : Fin k → ℕ), (∀ j, 0 < e j ∧ e j ≤ n) ∧
      Nonempty (M ≃ₗ[(AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ]
        ⨁ j, (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ ⧸
          Ideal.span {op (AdjoinRoot.root (X ^ n : K[X]) ^ e j)}) := by
  have : Module.Finite K (AdjoinRoot (X ^ n : K[X])) := (monic_X_pow n).finite_adjoinRoot
  have : IsArtinianRing (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ := .of_finite K _
  have : IsNoetherianRing (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ := isNoetherian_of_tower K inferInstance
  obtain ⟨s, hs, ⟨f⟩⟩ :=
    exists_linearEquiv_directSum_isIndecomposableModule (A := (AdjoinRoot (X ^ n : K[X]))ᵐᵒᵖ)
      (M := M)
  choose e he hen g using fun N : s ↦
    exists_linearEquiv_quotient_span_op_root_X_pow_pow_of_isIndecomposableModule (hs N N.2)
  exact ⟨_, e ∘ (Fintype.equivFin s).symm, fun j ↦ ⟨he _, hen _⟩,
    ⟨f ≪≫ₗ DFinsupp.mapRange.linearEquiv (fun N ↦ (g N).some) ≪≫ₗ
      DirectSum.lequivCongrLeft _ (Fintype.equivFin s)⟩⟩

end TauCeti
