/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.FiniteExtension.IntermediateField
public import TauCeti.NumberTheory.LocalField.Herbrand.UpperQuotient
import TauCeti.GroupTheory.Elementary
import TauCeti.GroupTheory.SpecificGroups.Cyclic.CoprimePart
import TauCeti.NumberTheory.LocalField.UnitFiltration.RamificationGroup

/-!
# The p-primary part of upper ramification

Let `L/K` be a finite Galois extension of nonarchimedean local fields, and let `p` be the
residue characteristic. Every positive upper ramification group is contained in the first lower
ramification group `G₁`, hence is a `p`-group. This isolates the wild part of a positive upper
break.

For a cyclic extension, quotient the Galois group by the subgroup generated by the prime-to-`p`
part of a generator. That subgroup has order prime to `p`, so it is disjoint from every positive
upper ramification group. The upper-numbering quotient theorem then shows that a positive upper
break remains a break in the resulting cyclic `p`-extension. This is the cyclic-to-`p`-primary
reduction in the Hasse--Arf theorem.

At the other end of the filtration, an upper break at a nonpositive index is necessarily `-1`
or `0`. Together, these results separate the elementary integral breaks from the positive wild
breaks that require the norm-conductor argument.

## Main results

* `TauCeti.LocalFieldsRamification.isPGroup_upperRamificationGroup_of_pos`: a positive upper
  ramification group is a `p`-group.
* `TauCeti.LocalFieldsRamification.UpperJump.eq_neg_one_or_eq_zero_of_nonpos`: the only
  nonpositive upper breaks are `-1` and `0`.
* `TauCeti.LocalFieldsRamification.UpperJump.fixedField_of_disjoint`: quotienting by a subgroup
  disjoint from the upper group at a break preserves that break in the fixed field.
* `TauCeti.LocalFieldsRamification.UpperJump.exists_isPGroup_intermediateField_of_isCyclic_of_pos`:
  a positive upper break of a cyclic extension is detected in a cyclic `p`-subextension.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter IV, §§2--3, and Chapter V, §7.
-/

public section
noncomputable section

open IntermediateField ValuativeRel

namespace TauCeti.LocalFieldsRamification

variable (K L : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]
  [Module.Finite K L] [IsGalois K L]

/-- A positive upper ramification group is contained in the first lower ramification group.
Indeed, the inverse Herbrand value of a positive index is positive, so its ceiling is at least
one. -/
theorem upperRamificationGroup_le_lowerRamificationGroup_one {u : RamificationIndexDomain}
    (hu : 0 < (u : ℝ)) :
    upperRamificationGroup K L u ≤ lowerRamificationGroup K L 1 := by
  let zero : RamificationIndexDomain := ⟨0, by norm_num⟩
  have hzero : inverseHerbrand K L zero = zero :=
    inverseHerbrand_of_coe_le_zero K L (by simp [zero])
  have hpsi : 0 < (inverseHerbrand K L u : ℝ) := by
    have hzero_lt_u : zero < u := Subtype.mk_lt_mk.2 hu
    have h := inverseHerbrand_strictMono K L hzero_lt_u
    rwa [hzero] at h
  rw [upperRamificationGroup_def, lowerRamificationGroupReal_def]
  exact lowerRamificationGroup_antitone K L (Int.ceil_pos.mpr hpsi)

/-- Every positive upper ramification group is a `p`-group for the residue characteristic `p`.
This is the upper-numbering form of the fact that `G₁` is wild inertia. -/
theorem isPGroup_upperRamificationGroup_of_pos {u : RamificationIndexDomain}
    (p : ℕ) [CharP 𝓀[L] p] (hu : 0 < (u : ℝ)) :
    IsPGroup p (upperRamificationGroup K L u) := by
  have hle := upperRamificationGroup_le_lowerRamificationGroup_one K L hu
  have hp := TauCeti.isPGroup_ramificationGroup (L ≃ₐ[K] L) p (L := L) (i := 1) (by omega)
  rw [← lowerRamificationGroup_def K L] at hp
  intro σ
  obtain ⟨n, hn⟩ := hp ⟨σ, hle σ.2⟩
  refine ⟨n, Subtype.ext ?_⟩
  exact congrArg (fun x : lowerRamificationGroup K L 1 ↦ (x : L ≃ₐ[K] L)) hn

variable {K L} in
/-- The only nonpositive upper ramification breaks are `-1` and `0`. Between these two indices
the upper filtration equals the constant lower filtration `G₀`. -/
theorem UpperJump.eq_neg_one_or_eq_zero_of_nonpos {u : RamificationIndexDomain}
    (hu : UpperJump K L u) (hu0 : (u : ℝ) ≤ 0) :
    (u : ℝ) = -1 ∨ (u : ℝ) = 0 := by
  by_cases hneg : (u : ℝ) = -1
  · exact Or.inl hneg
  · right
    have hneg_lt : (-1 : ℝ) < u := lt_of_le_of_ne u.property (Ne.symm hneg)
    by_contra hzero
    have hu_lt_zero : u < (⟨0, by norm_num⟩ : RamificationIndexDomain) :=
      Subtype.mk_lt_mk.2 (lt_of_le_of_ne hu0 hzero)
    have hdrop := (upperJump_iff K L u).1 hu _ hu_lt_zero
    have hlower : lowerRamificationGroupReal K L u = lowerRamificationGroup K L 0 :=
      lowerRamificationGroupReal_eq_of_sub_one_lt_of_le K L (i := 0)
        (by simpa using hneg_lt) (by simpa using hu0)
    have hlower_zero : lowerRamificationGroupReal K L
        ((⟨0, by norm_num⟩ : RamificationIndexDomain) : ℝ) =
        lowerRamificationGroup K L 0 := by
      simpa using lowerRamificationGroupReal_intCast K L 0
    have hgroup : upperRamificationGroup K L u =
        upperRamificationGroup K L ⟨0, by norm_num⟩ := by
      rw [upperRamificationGroup_of_coe_le_zero K L hu0,
        upperRamificationGroup_of_coe_le_zero K L (by norm_num), hlower, hlower_zero]
    exact hdrop.ne hgroup.symm

variable {K L} in
/-- An upper break survives in the fixed field of a normal subgroup that is disjoint from the
upper ramification group at that break. The quotient map is injective on that upper group, so it
preserves every strict drop after the break. -/
theorem UpperJump.fixedField_of_disjoint (H : Subgroup (L ≃ₐ[K] L)) [H.Normal]
    [ValuativeRel (fixedField H)] [TopologicalSpace (fixedField H)]
    [IsNonarchimedeanLocalField (fixedField H)] [ValuativeExtension K (fixedField H)]
    {u : RamificationIndexDomain} (hu : UpperJump K L u)
    (hdisjoint : Disjoint H (upperRamificationGroup K L u)) :
    UpperJump K (fixedField H) u := by
  refine (upperJump_iff K (fixedField H) u).2 fun v huv ↦ ?_
  have hle := upperRamificationGroup_antitone K L huv.le
  have hquot : H.upperRamificationGroupQuotient v <
      H.upperRamificationGroupQuotient u := by
    refine lt_of_le_of_ne (H.upperRamificationGroupQuotient_antitone huv.le) fun heq ↦ ?_
    have heq_groups : upperRamificationGroup K L v = upperRamificationGroup K L u := by
      apply le_antisymm hle
      intro σ hσ
      have hmap : (σ : (L ≃ₐ[K] L) ⧸ H) ∈ H.upperRamificationGroupQuotient v := by
        rw [heq]
        exact (H.mem_upperRamificationGroupQuotient_mk_iff u σ).2
          ((le_sup_left : upperRamificationGroup K L u ≤
            upperRamificationGroup K L u ⊔ H) hσ)
      have hsup : σ ∈ upperRamificationGroup K L v ⊔ H :=
        (H.mem_upperRamificationGroupQuotient_mk_iff v σ).1 hmap
      obtain ⟨τ, hτ, ρ, hρ, hτρ⟩ := Subgroup.mem_sup_of_normal_right.1 hsup
      have hτu := hle hτ
      have hρu : ρ ∈ upperRamificationGroup K L u := by
        have hρeq : ρ = τ⁻¹ * σ := by rw [← hτρ]; group
        rw [hρeq]
        exact mul_mem (inv_mem hτu) hσ
      have hρone : ρ = 1 := (Subgroup.disjoint_def.1 hdisjoint) hρ hρu
      have hστ : σ = τ := by rw [← hτρ, hρone, mul_one]
      rwa [hστ]
    exact ((upperJump_iff K L u).1 hu v huv).ne heq_groups
  let e : ((L ≃ₐ[K] L) ⧸ H) ≃* (fixedField H ≃ₐ[K] fixedField H) :=
    IsGalois.normalAutEquivQuotient H
  let e' : ((L ≃ₐ[K] L) ⧸ H) →* (fixedField H ≃ₐ[K] fixedField H) := e
  have hmap : (H.upperRamificationGroupQuotient v).map e' <
      (H.upperRamificationGroupQuotient u).map e' :=
    (Subgroup.map_lt_map_iff_of_injective (f := e') e.injective).2 hquot
  calc
    upperRamificationGroup K (fixedField H) v =
        (H.upperRamificationGroupQuotient v).map e' := by
          simpa only [e, e'] using (Subgroup.upperRamificationGroup_fixedField H v).symm
    _ < (H.upperRamificationGroupQuotient u).map e' := hmap
    _ = upperRamificationGroup K (fixedField H) u := by
      simpa only [e, e'] using Subgroup.upperRamificationGroup_fixedField H u

variable {K L} in
/-- A positive upper break of a cyclic extension is detected in a cyclic `p`-subextension, for
the residue characteristic `p`. The subextension is the fixed field of the prime-to-`p` part of
the original cyclic Galois group. Its local-field structures are the canonical ones induced from
`K`. -/
theorem UpperJump.exists_isPGroup_intermediateField_of_isCyclic_of_pos
    [IsCyclic (L ≃ₐ[K] L)] (p : ℕ) [CharP 𝓀[L] p]
    {u : RamificationIndexDomain} (hu : UpperJump K L u)
    (hupos : 0 < (u : ℝ)) :
    ∃ F : IntermediateField K L, ∃ hF : IsGalois K F,
      letI := hF
      letI := finiteIntermediateFieldValuativeRel K L F
      letI := finiteIntermediateFieldTopology K L F
      haveI := finiteIntermediateField_isNonarchimedeanLocalField K L F
      haveI := finiteIntermediateField_valuativeExtension K L F
      IsCyclic (F ≃ₐ[K] F) ∧ IsPGroup p (F ≃ₐ[K] F) ∧ UpperJump K F u := by
  let _ : Fact p.Prime := ⟨CharP.char_is_prime 𝓀[L] p⟩
  obtain ⟨D, -, -, hDcard, hpow, -⟩ :=
    TauCeti.exists_coprimePart_of_isCyclic (Fact.out : p.Prime)
      (C := (⊤ : Subgroup (L ≃ₐ[K] L)))
  let _ : D.Normal := inferInstance
  let F := fixedField D
  let _ := finiteIntermediateFieldValuativeRel K L F
  let _ := finiteIntermediateFieldTopology K L F
  have := finiteIntermediateField_isNonarchimedeanLocalField K L F
  have := finiteIntermediateField_valuativeExtension K L F
  have hpQ : IsPGroup p ((L ≃ₐ[K] L) ⧸ D) :=
    TauCeti.isPGroup_quotient_of_forall_exists_pow_mem fun σ ↦ hpow σ (by simp)
  have hpF : IsPGroup p (F ≃ₐ[K] F) :=
    hpQ.of_equiv (IsGalois.normalAutEquivQuotient D)
  have hcyclicQ : IsCyclic ((L ≃ₐ[K] L) ⧸ D) :=
    isCyclic_of_surjective (QuotientGroup.mk' D) (QuotientGroup.mk'_surjective D)
  let _ := hcyclicQ
  have hcyclic : IsCyclic (F ≃ₐ[K] F) :=
    isCyclic_of_surjective (IsGalois.normalAutEquivQuotient D).toMonoidHom
      (IsGalois.normalAutEquivQuotient D).surjective
  have hdisjoint : Disjoint D (upperRamificationGroup K L u) :=
    TauCeti.disjoint_of_not_dvd_natCard_of_isPGroup hDcard
      (isPGroup_upperRamificationGroup_of_pos K L p hupos)
  have hFjump : UpperJump K F u := hu.fixedField_of_disjoint D hdisjoint
  exact ⟨F, inferInstance, hcyclic, hpF, hFjump⟩

end TauCeti.LocalFieldsRamification
