/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Module.ZMod

import Mathlib.GroupTheory.FiniteAbelian.Duality
import TauCeti.Algebra.Group.TypeTags.Hom
import TauCeti.Algebra.Module.ZMod.Extend
import TauCeti.Algebra.Module.ZMod.Injective
import TauCeti.RingTheory.RootsOfUnity.ZMod

/-!
# The `ℤ/n`-dual of an additive group killed by `n`

An additive commutative group `M` killed by `n ≠ 0` is a `ℤ/n`-module, and its additive
homomorphisms to `ZMod n` are its `ℤ/n`-linear functionals. Written multiplicatively they are the
characters of `Multiplicative M` with values in `Multiplicative (ZMod n)`, a group with enough
roots of unity for the exponent of `M`, so Mathlib's duality theory for finite abelian groups
applies to them. This file records the two consequences that the duality of finite `ℤ/n[G]`-modules
rests on, phrased on `M →+ ZMod n` so that no module instance has to be installed by the caller:
for finite `M` there are exactly as many homomorphisms `M →+ ZMod n` as elements of `M`, and the
homomorphisms to `ZMod n` separate the points of `M`, finite or not. The count is also recorded for
`ℤ/n`-linear maps, for callers that already carry the module structures. The separation statement is
first proved on the finite cyclic subgroup generated by a point, and then extended to `M` along the
inclusion, using that `ZMod n` is an injective `ℤ/n`-module. Together they show that a pairing into
`ZMod n` of a finite group killed by `n` is perfect as soon as one of its adjoints is bijective, the
form in which duality theorems for finite Galois modules are stated. The case `n = p` prime is the
linear algebra of the `𝔽_p`-vector space `M`.

## Main results

* `TauCeti.natCard_addMonoidHom_zmod`: `Nat.card (M →+ ZMod n) = Nat.card M` for finite `M` killed
  by `n`, and `AddEquiv.natCard_addMonoidHom_zmod`: the same count for the homomorphisms
  into any additive group `N ≃+ ZMod n`; `AddEquiv.natCard_linearMap_zmod`: the same count for the
  `ℤ/n`-linear maps of a finite `ℤ/n`-module.
* `TauCeti.exists_addMonoidHom_zmod_apply_ne_zero`: for `a ≠ 0` in `M` killed by `n`, some
  `f : M →+ ZMod n` has `f a ≠ 0`; `TauCeti.exists_distribMulActionHom_apply_ne_zero`: the same
  for equivariant maps to any `N ≃+ ZMod n` when a monoid acts trivially on `M` and `N`.
* `TauCeti.forall_eq_zero_and_exists_eq_of_bijective_flip`: a pairing `M × M' → ZMod n`, `M`
  finite and killed by `n`, one of whose adjoints `M' → (M →+ ZMod n)` is bijective, is perfect;
  `TauCeti.forall_eq_zero_and_exists_eq_of_bijective_flip_of_addEquiv` reads it through additive
  equivalences.
-/

public section

variable {n : ℕ} [NeZero n] {M : Type*} [AddCommGroup M]

namespace TauCeti

/-- A finite additive commutative group killed by `n ≠ 0` has as many additive homomorphisms to
`ZMod n` as elements. -/
theorem natCard_addMonoidHom_zmod [Finite M] (hM : ∀ x : M, n • x = 0) :
    Nat.card (M →+ ZMod n) = Nat.card M := by
  have := hasEnoughRootsOfUnity_multiplicative_zmod_exponent hM
  rw [Nat.card_congr AddMonoidHom.toMultiplicativeUnits,
    CommGroup.card_monoidHom_of_hasEnoughRootsOfUnity, Nat.card_congr Multiplicative.toAdd]

/-- Additive homomorphisms to `ZMod n` detect every nonzero element of an additive commutative
group killed by `n ≠ 0`. The group need not be finite. -/
theorem exists_addMonoidHom_zmod_apply_ne_zero (hM : ∀ x : M, n • x = 0) {a : M} (ha : a ≠ 0) :
    ∃ f : M →+ ZMod n, f a ≠ 0 := by
  let S := AddSubgroup.zmultiples a
  have hS : ∀ x : S, n • x = 0 := fun x => Subtype.ext (hM x)
  have : Finite S := (isOfFinAddOrder_iff_nsmul_eq_zero.2
    ⟨n, NeZero.pos n, hM a⟩).finite_zmultiples
  have := hasEnoughRootsOfUnity_multiplicative_zmod_exponent hS
  obtain ⟨φ, hφ⟩ := CommGroup.exists_apply_ne_one_of_hasEnoughRootsOfUnity (Multiplicative S)
    (Multiplicative (ZMod n)) (a := Multiplicative.ofAdd ⟨a, AddSubgroup.mem_zmultiples a⟩)
    (by simpa [← Subtype.coe_ne_coe] using ha)
  obtain ⟨f, hf⟩ := AddMonoidHom.exists_comp_eq_of_injective_of_baer (Module.Baer.zmod_self n) hM
    S.subtype_injective (AddMonoidHom.toMultiplicativeUnits.symm φ)
  refine ⟨f, fun h => hφ ?_⟩
  have := DFunLike.congr_fun hf ⟨a, AddSubgroup.mem_zmultiples a⟩
  simpa [h, ← Units.val_eq_one, ← toAdd_eq_zero] using this.symm

/-- For `e : N ≃+ ZMod n` with `n ≠ 0` and a monoid `G` acting trivially on `N` and on an
additive commutative group `M` killed by `n`, the equivariant maps `M → N` detect every nonzero
element of `M`: they are all the additive maps, and those to `ZMod n` separate points. -/
theorem exists_distribMulActionHom_apply_ne_zero {G : Type*} [Monoid G] {N : Type*}
    [AddCommGroup N] [DistribMulAction G N] (hN : ∀ (g : G) (y : N), g • y = y)
    (e : N ≃+ ZMod n) [DistribMulAction G M] (hM : ∀ x : M, n • x = 0)
    (hMtriv : ∀ (g : G) (x : M), g • x = x) {a : M} (ha : a ≠ 0) :
    ∃ f : M →+[G] N, f a ≠ 0 := by
  obtain ⟨f, hf⟩ := exists_addMonoidHom_zmod_apply_ne_zero hM ha
  exact ⟨{ e.symm.toAddMonoidHom.comp f with
      map_smul' g x := by rw [MonoidHom.id_apply, hMtriv, hN] },
    fun h ↦ hf (e.symm.map_eq_zero_iff.1 h)⟩

/-- **A pairing into `ZMod n` with a bijective adjoint is perfect.** Let `Φ : M × M' → ZMod n` be
biadditive, with `M` finite and killed by `n ≠ 0`. If every homomorphism `M →+ ZMod n` is
`Φ (-, y)` for exactly one `y`, then `Φ` separates the points of `M`, and every homomorphism
`M' →+ ZMod n` is `Φ (x, -)` for some `x`: the homomorphisms to `ZMod n` separate the points of
`M`, and `M`, `M →+ ZMod n`, `M'` and `M' →+ ZMod n` all have the same order. -/
theorem forall_eq_zero_and_exists_eq_of_bijective_flip {M' : Type*} [AddCommGroup M'] [Finite M]
    (hM : ∀ x : M, n • x = 0) (Φ : M →+ M' →+ ZMod n)
    (hΦ : Function.Bijective Φ.flip) :
    (∀ x : M, (∀ y : M', Φ x y = 0) → x = 0) ∧
      ∀ φ : M' →+ ZMod n, ∃ x : M, ∀ y : M', Φ x y = φ y := by
  have hsep : ∀ x : M, (∀ y : M', Φ x y = 0) → x = 0 := fun x hx => by_contra fun hne => by
    obtain ⟨f, hf⟩ := exists_addMonoidHom_zmod_apply_ne_zero hM hne
    obtain ⟨y, rfl⟩ := hΦ.2 f
    exact hf (hx y)
  have hM' : ∀ y : M', n • y = 0 := fun y => hΦ.1 <| by
    ext x
    rw [map_nsmul, map_zero, AddMonoidHom.nsmul_apply, nsmul_eq_mul, ZMod.natCast_self, zero_mul,
      AddMonoidHom.zero_apply]
  have : Finite (M →+ ZMod n) := Finite.of_injective _ DFunLike.coe_injective
  have : Finite M' := Finite.of_equiv _ (Equiv.ofBijective _ hΦ).symm
  have : Finite (M' →+ ZMod n) := Finite.of_injective _ DFunLike.coe_injective
  have hinj : Function.Injective Φ :=
    (injective_iff_map_eq_zero Φ).2 fun x hx => hsep x fun y => by
      rw [hx, AddMonoidHom.zero_apply]
  refine ⟨hsep, fun φ => ?_⟩
  obtain ⟨x, hx⟩ := (hinj.bijective_of_nat_card_le (by
    rw [natCard_addMonoidHom_zmod hM', Nat.card_congr (Equiv.ofBijective _ hΦ),
      natCard_addMonoidHom_zmod hM])).2 φ
  exact ⟨x, fun y => DFunLike.congr_fun hx y⟩

/-- **A pairing into `ZMod n` that is a perfect pairing up to additive equivalences is perfect.**
If `pair : X → Y → ZMod n` reads, through additive equivalences `eX : X₀ ≃+ X` and
`eY : Y₀ ≃+ Y`, as a biadditive `Φ`, with `X₀` finite and killed by `n`, whose adjoint
`Y₀ → (X₀ →+ ZMod n)` is bijective, then `pair` separates the points of `X`, and every
homomorphism `Y →+ ZMod n` is `pair (x, -)` for some `x`
(`TauCeti.forall_eq_zero_and_exists_eq_of_bijective_flip`). -/
theorem forall_eq_zero_and_exists_eq_of_bijective_flip_of_addEquiv {X Y X₀ Y₀ : Type*}
    [AddCommGroup X] [AddCommGroup Y] [AddCommGroup X₀] [AddCommGroup Y₀] [Finite X₀]
    (hX₀ : ∀ x : X₀, n • x = 0) (pair : X → Y → ZMod n) (eX : X₀ ≃+ X) (eY : Y₀ ≃+ Y)
    (Φ : X₀ →+ Y₀ →+ ZMod n) (hΦ : Function.Bijective Φ.flip)
    (h : ∀ x y, pair (eX x) (eY y) = Φ x y) :
    (∀ x : X, (∀ y : Y, pair x y = 0) → x = 0) ∧
      ∀ φ : Y →+ ZMod n, ∃ x : X, ∀ y : Y, pair x y = φ y := by
  obtain ⟨h₁, h₂⟩ := forall_eq_zero_and_exists_eq_of_bijective_flip hX₀ Φ hΦ
  refine ⟨fun x hx => ?_, fun φ => ?_⟩
  · have := h₁ (eX.symm x) fun y => by rw [← h, eX.apply_symm_apply]; exact hx _
    exact (AddEquiv.map_eq_zero_iff eX.symm).1 this
  · obtain ⟨x, hx⟩ := h₂ (φ.comp eY.toAddMonoidHom)
    refine ⟨eX x, fun y => ?_⟩
    rw [← eY.apply_symm_apply y, h, hx, AddMonoidHom.comp_apply, AddEquiv.coe_toAddMonoidHom]

end TauCeti

/-- For `e : N ≃+ ZMod n` with `n ≠ 0`, a finite additive commutative group killed by `n` has
as many additive homomorphisms to `N` as elements. -/
theorem AddEquiv.natCard_addMonoidHom_zmod {N : Type*} [AddCommGroup N] (e : N ≃+ ZMod n)
    [Finite M] (hM : ∀ x : M, n • x = 0) : Nat.card (M →+ N) = Nat.card M := by
  rw [Nat.card_congr (AddEquiv.addMonoidHomCongrRight (M := M) e).toEquiv,
    TauCeti.natCard_addMonoidHom_zmod hM]

/-- For `e : N ≃+ ZMod n` with `n ≠ 0`, a finite `ℤ/n`-module has as many `ℤ/n`-linear maps to
`N` as elements. -/
theorem AddEquiv.natCard_linearMap_zmod {N : Type*} [AddCommGroup N] [Module (ZMod n) N]
    (e : N ≃+ ZMod n) [Module (ZMod n) M] [Finite M] :
    Nat.card (M →ₗ[ZMod n] N) = Nat.card M := by
  rw [← Nat.card_congr (AddMonoidHom.toZModLinearMapEquiv n).toEquiv,
    e.natCard_addMonoidHom_zmod (ZModModule.char_nsmul_eq_zero n)]
