/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import TauCeti.Probability.Process.Tail.Basic
public import TauCeti.Probability.Process.Cylinder
public import TauCeti.Probability.Exchangeability.Contractability
-- `PrefixDeletion` (the canonical dependency) `public import`s both
-- `Mathlib.Probability.Independence.Conditional` (`CondIndep`/`condIndep_iff`, proof-only here) and
-- `…PathLaw.ProcessShift`, so both transit through this non-public import and are not repeated.
import TauCeti.Probability.DeFinetti.PrefixDeletion
import TauCeti.Probability.DeFinetti.CondExpConvergence

/-!
# Future-level factorization for the de Finetti martingale route

For a contractable process `X`, this file builds the finite-level product factorization of the
block-indicator conditional expectation given the future σ-algebra `tailFamily X (m+1)`. Everything
is phrased through Mathlib's `ProbabilityTheory.CondIndep`.

## Main results

* `condExp_blockIndicatorProd_future_ae_eq_prod` — for `r ≤ m + 1`, the conditional expectation of
  the length-`r` prefix indicator product factors as the product of the single-coordinate
  conditional expectations, with every coordinate replaced by `X 0`.

The induction is organised through three private helpers: `condIndep_prefix_coord_future`
(prefix/coordinate conditional independence given the future, from
`Contractable.condIndep_coord_prefix_tail`, Kallenberg's Lemma 1.3),
`condExp_blockCylinder_inter_preimage_ae_eq_mul` (the resulting conditional-expectation product
split), and `condExp_blockIndicatorProd_future_succ` (the inductive step).

Adapted from `cameronfreer/exchangeability`
(`DeFinetti/ViaMartingale/Factorization.lean`: `block_coord_condIndep`,
`condexp_indicator_inter_of_condIndep`, `finite_level_factorization`).
-/

public section

noncomputable section

open MeasureTheory ProbabilityTheory Filter
open scoped MeasureTheory

namespace TauCeti

namespace Probability

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

omit [MeasurableSpace Ω] in
/-- **Comap-measurability of the block cylinder.** The length-`r` block cylinder is measurable with
respect to the σ-algebra generated by the length-`r` prefix map `ω ↦ (X 0 ω, …, X (r-1) ω)`. -/
private lemma measurableSet_blockCylinder_comap_prefix (X : ℕ → Ω → α) {r : ℕ} (C : Fin r → Set α)
    (hC : ∀ i, MeasurableSet (C i)) :
    MeasurableSet[MeasurableSpace.comap (fun (ω : Ω) (i : Fin r) => X (i : ℕ) ω) inferInstance]
      (blockCylinder X (fun i : Fin r => (i : ℕ)) C) :=
  ⟨Set.univ.pi fun j : Fin r => C j, MeasurableSet.univ_pi fun j => hC j,
    by rw [blockCylinder_eq_preimage_univ_pi]⟩

/-- **Prefix/coordinate conditional independence given the future.** For a contractable process and
`r ≤ m`, the length-`r` prefix `ω ↦ (X 0 ω, …, X (r-1) ω)` and the single coordinate `X r` are
conditionally independent given the future σ-algebra `tailFamily X (m+1)`. -/
private lemma condIndep_prefix_coord_future [StandardBorelSpace Ω] {μ : Measure Ω}
    [IsFiniteMeasure μ] {X : ℕ → Ω → α} (hX : Contractable μ X)
    (hX_meas : ∀ n, Measurable (X n)) {m r : ℕ} (hrm : r ≤ m) :
    CondIndep (tailFamily X (m + 1))
      (MeasurableSpace.comap (fun (ω : Ω) (i : Fin r) => X (i : ℕ) ω) inferInstance)
      (MeasurableSpace.comap (X r) inferInstance)
      (tailFamily_le_ambient (m + 1) fun k _ => hX_meas k) μ := by
  -- Symmetrise `Contractable.condIndep_coord_prefix_tail` (Kallenberg 1.3), then transport it
  -- from `σ(processShift X (m+1))` to `tailFamily X (m+1)` via `tailFamily_eq_comap_shift`.
  have hW_eq : MeasurableSpace.comap (processShift X (m + 1)) inferInstance
      = tailFamily X (m + 1) := by
    rw [tailFamily_eq_comap_shift X (m + 1)]
    congr 1
    funext ω n
    exact processShift_apply X (m + 1) n ω
  simp only [← hW_eq]
  exact (Contractable.condIndep_coord_prefix_tail hX hX_meas hrm).symm

/-- **Product split of the prefix-cylinder/coordinate indicator conditional expectation.** For a
contractable process and `r ≤ m`, the conditional expectation given `tailFamily X (m+1)` of the
indicator of the length-`r` prefix cylinder `blockCylinder X id D` intersected with the coordinate
preimage `X r ⁻¹' B` factors as the product of the two individual conditional expectations. The
coordinate family `D` and the set `B` are assumed measurable. -/
private lemma condExp_blockCylinder_inter_preimage_ae_eq_mul [StandardBorelSpace Ω] {μ : Measure Ω}
    [IsFiniteMeasure μ] {X : ℕ → Ω → α} (hX : Contractable μ X) (hX_meas : ∀ n, Measurable (X n))
    {m r : ℕ} (hrm : r ≤ m) (D : Fin r → Set α) (hD : ∀ i, MeasurableSet (D i)) {B : Set α}
    (hB : MeasurableSet B) :
    μ[(blockCylinder X (fun i : Fin r => (i : ℕ)) D ∩ X r ⁻¹' B).indicator (fun _ => (1 : ℝ))
        | tailFamily X (m + 1)]
      =ᵐ[μ]
    μ[(blockCylinder X (fun i : Fin r => (i : ℕ)) D).indicator (fun _ => (1 : ℝ))
        | tailFamily X (m + 1)]
      * μ[(X r ⁻¹' B).indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)] := by
  have hA_meas : MeasurableSet[MeasurableSpace.comap
      (fun (ω : Ω) (i : Fin r) => X (i : ℕ) ω) inferInstance]
      (blockCylinder X (fun i : Fin r => (i : ℕ)) D) :=
    measurableSet_blockCylinder_comap_prefix X D hD
  have hB_meas : MeasurableSet[MeasurableSpace.comap (X r) inferInstance] (X r ⁻¹' B) :=
    ⟨B, hB, rfl⟩
  exact (condIndep_iff (tailFamily X (m + 1))
    (MeasurableSpace.comap (fun (ω : Ω) (i : Fin r) => X (i : ℕ) ω) inferInstance)
    (MeasurableSpace.comap (X r) inferInstance)
    (tailFamily_le_ambient (m + 1) fun k _ => hX_meas k)
    ((Measurable.of_eval (f := fun (ω : Ω) (i : Fin r) => X (i : ℕ) ω) fun i => hX_meas i).comap_le)
    ((hX_meas r).comap_le) μ).mp
      (condIndep_prefix_coord_future hX hX_meas hrm) _ _ hA_meas hB_meas

/-- **Successor step of the finite-level future factorization.** Assuming the length-`r`
factorization `ih_r` for the truncated coordinate family `fun j => C (Fin.castSucc j)`, the
length-`(r+1)` factorization holds for `C`. Requires `r ≤ m` and every `C i` measurable. -/
private lemma condExp_blockIndicatorProd_future_succ [StandardBorelSpace Ω] {μ : Measure Ω}
    [IsFiniteMeasure μ] {X : ℕ → Ω → α} (hX : Contractable μ X) (hX_meas : ∀ n, Measurable (X n))
    {m r : ℕ} (hrm : r ≤ m) (C : Fin (r + 1) → Set α) (hC : ∀ i, MeasurableSet (C i))
    (ih_r : μ[blockIndicatorProd X (fun i : Fin r => (i : ℕ)) (fun j => C (Fin.castSucc j))
              | tailFamily X (m + 1)]
        =ᵐ[μ] (fun ω => ∏ i : Fin r,
          μ[Set.indicator (C (Fin.castSucc i)) (fun _ => (1 : ℝ)) ∘ X 0
            | tailFamily X (m + 1)] ω)) :
    μ[blockIndicatorProd X (fun i : Fin (r + 1) => (i : ℕ)) C | tailFamily X (m + 1)]
      =ᵐ[μ]
    (fun ω => ∏ i : Fin (r + 1),
      μ[Set.indicator (C i) (fun _ => (1 : ℝ)) ∘ X 0 | tailFamily X (m + 1)] ω) := by
  classical
  set cyl : Set Ω :=
    blockCylinder X (fun i : Fin r => (i : ℕ)) (fun j => C (Fin.castSucc j)) with hcyl
  set pre : Set Ω := X r ⁻¹' C (Fin.last r) with hpre
  -- Successor split of the indicator product, from the `Cylinder` API.
  have hblock_eq : blockIndicatorProd X (fun i : Fin (r + 1) => (i : ℕ)) C
      = (cyl ∩ pre).indicator (fun _ => (1 : ℝ)) := by
    rw [hcyl, hpre]
    exact blockIndicatorProd_succ_eq_indicator_inter X (fun i : Fin (r + 1) => (i : ℕ)) C
  -- CondIndep → condExp product formula, from the split helper.
  have hbridge : μ[(cyl ∩ pre).indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)]
      =ᵐ[μ] μ[cyl.indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)]
          * μ[pre.indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)] := by
    rw [hcyl, hpre]
    exact condExp_blockCylinder_inter_preimage_ae_eq_mul hX hX_meas hrm _
      (fun j => hC (Fin.castSucc j)) (hC (Fin.last r))
  have hcyl_ce : μ[cyl.indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)]
      =ᵐ[μ] (fun ω => ∏ i : Fin r,
        μ[Set.indicator (C (Fin.castSucc i)) (fun _ => (1 : ℝ)) ∘ X 0
          | tailFamily X (m + 1)] ω) := by
    rw [hcyl, ← blockIndicatorProd_eq_indicator]; exact ih_r
  have hpre_ind : (fun ω => (C (Fin.last r)).indicator (fun _ => (1 : ℝ)) (X r ω))
      = pre.indicator (fun _ => (1 : ℝ)) := by
    rw [hpre]; funext ω; simp only [Set.indicator_apply, Set.mem_preimage]
  have hpre_ce : μ[pre.indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)]
      =ᵐ[μ] μ[Set.indicator (C (Fin.last r)) (fun _ => (1 : ℝ)) ∘ X 0 | tailFamily X (m + 1)] :=
    (condExp_congr_ae (EventuallyEq.of_eq hpre_ind.symm)).trans
      (hX.condExp_indicator_future_eq hX_meas (k := 0) (by omega) (by omega) (hC (Fin.last r)))
  calc μ[blockIndicatorProd X (fun i : Fin (r + 1) => (i : ℕ)) C | tailFamily X (m + 1)]
      _ =ᵐ[μ] μ[(cyl ∩ pre).indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)] :=
          condExp_congr_ae (EventuallyEq.of_eq hblock_eq)
      _ =ᵐ[μ] μ[cyl.indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)]
                * μ[pre.indicator (fun _ => (1 : ℝ)) | tailFamily X (m + 1)] := hbridge
      _ =ᵐ[μ] (fun ω => (∏ i : Fin r,
                  μ[Set.indicator (C (Fin.castSucc i)) (fun _ => (1 : ℝ)) ∘ X 0
                    | tailFamily X (m + 1)] ω)
                * μ[Set.indicator (C (Fin.last r)) (fun _ => (1 : ℝ)) ∘ X 0
                    | tailFamily X (m + 1)] ω) := hcyl_ce.mul hpre_ce
      _ =ᵐ[μ] (fun ω => ∏ i : Fin (r + 1),
                  μ[Set.indicator (C i) (fun _ => (1 : ℝ)) ∘ X 0 | tailFamily X (m + 1)] ω) := by
          refine EventuallyEq.of_eq (funext fun ω => ?_)
          rw [Fin.prod_univ_castSucc]

/-- **Finite-level future factorization.**

For a contractable process and any future level `m` with `r ≤ m + 1`, the conditional expectation of
the length-`r` prefix indicator product factors as the product of the single-coordinate conditional
expectations, with every coordinate replaced by `X 0`:
```
μ[∏ i<r 𝟙_{X i ∈ C i} | tailFamily X (m+1)] = ∏ i<r μ[𝟙_{X 0 ∈ C i} | tailFamily X (m+1)]   a.e.
```
-/
lemma condExp_blockIndicatorProd_future_ae_eq_prod
    [StandardBorelSpace Ω]
    {μ : Measure Ω} [IsFiniteMeasure μ]
    (X : ℕ → Ω → α) (hX : Contractable μ X) (hX_meas : ∀ n, Measurable (X n))
    (m : ℕ) (r : ℕ) (C : Fin r → Set α) (hC : ∀ i, MeasurableSet (C i)) (hm : r ≤ m + 1) :
    μ[blockIndicatorProd X (fun i : Fin r => (i : ℕ)) C | tailFamily X (m + 1)]
      =ᵐ[μ]
    (fun ω => ∏ i : Fin r,
      μ[Set.indicator (C i) (fun _ => (1 : ℝ)) ∘ X 0 | tailFamily X (m + 1)] ω) := by
  classical
  induction r with
  | zero =>
    have hle : tailFamily X (m + 1) ≤ (inferInstance : MeasurableSpace Ω) :=
      tailFamily_le_ambient (m + 1) fun k _ => hX_meas k
    rw [blockIndicatorProd_empty X (fun i : Fin 0 => (i : ℕ)) C]
    refine (EventuallyEq.of_eq (condExp_const hle 1)).trans (EventuallyEq.of_eq ?_)
    funext ω; simp
  | succ r ih =>
    exact condExp_blockIndicatorProd_future_succ hX hX_meas (by omega) C hC
      (ih (fun j => C (Fin.castSucc j)) (fun j => hC _) (by omega))

end Probability

end TauCeti
