/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Basis.Fin
public import Mathlib.LinearAlgebra.Dimension.Free
public import Mathlib.LinearAlgebra.FreeModule.Basic
public import Mathlib.LinearAlgebra.FreeModule.PID
public import Mathlib.RingTheory.Int.Basic

/-!
# Primitive vectors in integer modules

A vector in an integer module is primitive when an integer-valued linear functional takes the
value one on it. This basis-free condition says that the cyclic submodule generated by the vector
splits off a copy of `ℤ`. It is invariant under linear equivalence and under changing the sign of
the vector.

For a free integer module, every nonzero vector is a positive integer multiple of a
primitive vector. This is the coordinate-free form of dividing a nonzero integer vector by the
greatest common divisor of its coordinates. It supplies primitive representatives whenever a
rational ray is initially described by arbitrary nonzero lattice vectors.

## Main declarations

* `TauCeti.IsPrimitive`: some integer-valued linear functional takes the value one on the vector.
* `TauCeti.IsPrimitive.eq_one_of_eq_nsmul`: a natural multiplier of a primitive vector
  is one.
* `LinearEquiv.isPrimitive_iff`: primitivity is invariant under integer-linear equivalences.
* `TauCeti.exists_eq_zsmul_isPrimitive`: a nonzero vector in a free integer module is a
  positive integer multiple of a primitive vector.
* `Module.Basis.isPrimitive`: a vector of an integral basis is primitive.
* `TauCeti.IsPrimitive.exists_basis`: conversely, a primitive vector of a finite free integer
  module belongs to some integral basis of it.
-/

public section

namespace TauCeti

variable {M N : Type*} [AddCommGroup M] [AddCommGroup N] [Module ℤ M] [Module ℤ N]

/-- A vector `v` in an integer module is primitive when some integer-valued linear functional
sends it to `1`. Equivalently, the cyclic submodule generated by `v` splits off a copy of `ℤ`. -/
def IsPrimitive (v : M) : Prop := ∃ f : M →ₗ[ℤ] ℤ, f v = 1

/-- A vector is primitive exactly when an integer-valued linear functional takes the value one
on it. This is the introduction and elimination interface for `IsPrimitive`. -/
theorem isPrimitive_def {v : M} : IsPrimitive v ↔ ∃ f : M →ₗ[ℤ] ℤ, f v = 1 := Iff.rfl

/-- A primitive vector is nonzero. -/
theorem IsPrimitive.ne_zero {v : M} (h : IsPrimitive v) : v ≠ 0 := by
  rintro rfl
  obtain ⟨f, hf⟩ := h
  simp at hf

/-- A primitive vector cannot be a nontrivial natural multiple of another vector. -/
theorem IsPrimitive.eq_one_of_eq_nsmul {v w : M} (hv : IsPrimitive v) {m : ℕ}
    (hvw : v = m • w) : m = 1 := by
  obtain ⟨f, hf⟩ := hv
  rw [hvw, map_nsmul, nsmul_eq_mul] at hf
  rcases Int.mul_eq_one_iff_eq_one_or_neg_one.mp hf with h | h
  · exact_mod_cast h.1
  · omega

/-- The zero vector is not primitive. -/
@[simp]
theorem not_isPrimitive_zero : ¬ IsPrimitive (0 : M) := fun h ↦ h.ne_zero rfl

/-- Primitivity is unchanged by the sign action `v ↦ -v`. -/
theorem IsPrimitive.neg {v : M} (h : IsPrimitive v) : IsPrimitive (-v) := by
  obtain ⟨f, hf⟩ := h
  exact ⟨-f, by simp [hf]⟩

/-- Primitivity is invariant under negation. -/
@[simp]
theorem isPrimitive_neg {v : M} : IsPrimitive (-v) ↔ IsPrimitive v :=
  ⟨fun h ↦ by simpa using h.neg, IsPrimitive.neg⟩

end TauCeti

namespace Module.Basis

variable {ι M : Type*} [AddCommGroup M] [Module ℤ M]

/-- A vector of an integral basis is primitive. -/
theorem isPrimitive (b : Module.Basis ι ℤ M) (j : ι) : TauCeti.IsPrimitive (b j) :=
  TauCeti.isPrimitive_def.2 ⟨b.coord j, by simp⟩

end Module.Basis

namespace LinearEquiv

variable {M N : Type*} [AddCommGroup M] [AddCommGroup N] [Module ℤ M] [Module ℤ N]

/-- Primitivity transports along an integer-linear equivalence. -/
@[simp]
theorem isPrimitive_iff (φ : M ≃ₗ[ℤ] N) {v : M} :
    TauCeti.IsPrimitive (φ v) ↔ TauCeti.IsPrimitive v := by
  constructor
  · rintro ⟨g, hg⟩
    exact ⟨g.comp (φ : M →ₗ[ℤ] N), by simpa using hg⟩
  · rintro ⟨f, hf⟩
    exact ⟨f.comp (φ.symm : N →ₗ[ℤ] M), by simpa using hf⟩

end LinearEquiv

namespace TauCeti

variable {M : Type*} [AddCommGroup M] [Module ℤ M]

/-- Every nonzero vector in a free integer module is a positive integer multiple of a
primitive vector. The multiplier is the greatest common divisor of the coordinates in any
integral basis. -/
theorem exists_eq_zsmul_isPrimitive [Module.Free ℤ M] {v : M}
    (hv : v ≠ 0) : ∃ (d : ℤ) (w : M), 0 < d ∧ IsPrimitive w ∧ v = d • w := by
  classical
  let ι := Module.Free.ChooseBasisIndex ℤ M
  let b : Module.Basis ι ℤ M := Module.Free.chooseBasis ℤ M
  let c : ι →₀ ℤ := b.repr v
  let s : Finset ι := c.support
  let d : ℤ := s.gcd c
  have hc0 : c ≠ 0 := fun h ↦ hv (b.repr.injective (h.trans (map_zero b.repr).symm))
  have hs : s.Nonempty := by
    simpa only [s] using Finsupp.support_nonempty_iff.mpr hc0
  obtain ⟨j, hj⟩ := hs
  have hcj : c j ≠ 0 := Finsupp.mem_support_iff.mp hj
  have hd0 : d ≠ 0 := by
    simpa only [d, Finset.gcd_ne_zero_iff] using ⟨j, hj, hcj⟩
  have hd_nonneg : 0 ≤ d := by
    simpa only [d] using (Finset.Int.finsetGcd_nonneg : 0 ≤ s.gcd c)
  have hd : 0 < d := lt_of_le_of_ne hd_nonneg (Ne.symm hd0)
  let q : ι → ℤ := fun k ↦ c k / d
  have hq : (Function.support q).Finite := by
    refine s.finite_toSet.subset fun k hk ↦ ?_
    by_contra hks
    have hck : c k = 0 := Finsupp.notMem_support_iff.mp hks
    exact hk (by simp [q, hck])
  let qf : ι →₀ ℤ := Finsupp.ofSupportFinite q hq
  let w : M := b.repr.symm qf
  have hcd (j : ι) : c j = d * q j := by
    by_cases hj : j ∈ s
    · exact (Int.ediv_mul_cancel (Finset.gcd_dvd hj)).symm.trans (mul_comm _ _)
    · have hcj : c j = 0 := Finsupp.notMem_support_iff.mp hj
      simp [q, hcj]
  have hvw : v = d • w := by
    have hrepr : b.repr v = d • qf := by
      ext j
      simp only [Finsupp.smul_apply, qf, Finsupp.ofSupportFinite_coe, smul_eq_mul]
      simpa only [c, d, q] using hcd j
    calc
      v = b.repr.symm (b.repr v) := (b.repr.symm_apply_apply v).symm
      _ = b.repr.symm (d • qf) := congrArg b.repr.symm hrepr
      _ = d • w := by
        simp only [w, LinearEquiv.map_smul]
        exact Int.cast_smul_eq_zsmul ℤ d _
  have hqgcd : s.gcd q = 1 := by
    simpa only [q, d] using Finset.gcd_div_eq_one (s := s) (f := c) hj hcj
  obtain ⟨a, ha⟩ := Finset.gcd_eq_sum_mul (R := ℤ) s q
  refine ⟨d, w, hd, ?_, hvw⟩
  let f : M →ₗ[ℤ] ℤ := ∑ k ∈ s, a k • b.coord k
  refine isPrimitive_def.2 ⟨f, ?_⟩
  simp only [f, LinearMap.sum_apply, LinearMap.smul_apply, w, b.coord_repr_symm, qf,
    Finsupp.ofSupportFinite_coe, smul_eq_mul]
  simpa only [mul_comm] using (hqgcd.symm.trans ha).symm

/-- A primitive vector of a finite free integer module belongs to an integral basis of it. -/
theorem IsPrimitive.exists_basis [Module.Free ℤ M] [Module.Finite ℤ M] {v : M}
    (hv : IsPrimitive v) :
    ∃ (n : ℕ) (b : Module.Basis (Fin n) ℤ M) (j : Fin n), b j = v := by
  obtain ⟨f, hf⟩ := isPrimitive_def.1 hv
  obtain ⟨m, ⟨c⟩⟩ := Submodule.nonempty_basis_of_pid (Module.finBasis ℤ M) (LinearMap.ker f)
  refine ⟨m + 1, Module.Basis.mkFinCons v c ?_ ?_, 0, ?_⟩
  · intro a x hx hax
    have h := congrArg f hax
    simp only [map_add, map_smul, hf, LinearMap.mem_ker.1 hx, map_zero, add_zero, smul_eq_mul,
      mul_one] at h
    exact h
  · exact fun z ↦ ⟨-f z, by simp [LinearMap.mem_ker, hf]⟩
  · simp

end TauCeti
