/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.F4.ShortRoot.Carrier
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot
import TauCeti.LinearAlgebra.Matrix.Cartan.TypeF4

/-!
# Generation of the short-root type-F4 carrier by root subgroups

The integral toral closure of the twenty-six-dimensional module `V(ϖ₄)` of type `F₄` is defined
from its eight numbered positive and negative simple root subgroups together with its rank-four
split weight torus. This file proves that the torus is redundant: over every commutative ring it
already lies in the elementary subgroup generated by those root subgroups, and the integral
carrier is therefore the root-generated Kostant group scheme.

The represented generators at each node form an `sl₂` triple by
`TauCeti.F4ShortRoot.isSl2Triple_rep_serreRootGenerator`, and every row of the type-`F₄` Cartan
matrix is a primitive integer vector by
`TauCeti.sum_cartanMatrixF4_mul_typeF4CartanBezout`, each row having an entry `-1` at a
neighbouring node. So each simple root is a primitive character of the weight torus, and the
generic Kostant coroot-generation theorem writes every coordinate cocharacter, hence the whole
torus, as a product of root-subgroup elements.

Testing that pointwise containment on the universal point of the torus, over the coordinate ring
of the split torus itself, makes the torus redundant scheme-theoretically as well: the
toral-closure defining Hopf ideal over `ℤ` equals the ideal cut out by the numbered root
subgroups alone. This is an equality of integral carriers; it does not say that the subgroup
generated anew over a base that is not flat over `ℤ` is the base change of the integral carrier,
and in particular it does not identify the companion carrier generated over `𝔽₂`.

## Main results

* `TauCeti.F4ShortRoot.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in the
  elementary subgroup over every commutative ring.
* `TauCeti.F4ShortRoot.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining the
  weight torus to all eight numbered root subgroups gives exactly the elementary subgroup.
* `TauCeti.F4ShortRoot.definingIdeal_eq_kostantGeneratedDefiningIdeal`: the integral toral
  closure is already cut out by the root subgroups alone.
* `TauCeti.F4ShortRoot.groupScheme_eq_kostantGeneratedGroupScheme` and
  `TauCeti.F4ShortRoot.isIso_kostantGeneratedToToral`: the carrier is the root-generated Kostant
  group scheme, and the canonical comparison between them is an isomorphism.
* `TauCeti.F4ShortRoot.groupScheme_hom_ext_of_rootSubgroup`: a morphism out of the carrier is
  determined by its restrictions to the eight numbered root subgroups alone.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.
* `TauCeti.Algebra.Lie.E7.Minuscule.Generation`, the same coroot-generation argument run on the
  minuscule type-`E₇` carrier, whose formal template this file follows with the type-`F₄` Cartan
  rows and short-root weights in place of the type-`E₇` data.
-/

public section

open scoped Matrix

universe v

namespace TauCeti.F4ShortRoot

open CategoryTheory
open TauCeti.DynkinType TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "CM" => CartanMatrix.F₄ᵀ
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => DynkinType.F4.rootGeneratorWeight DynkinType.valid_F4

private theorem rootWeight_sum_mul_bezout (i : Fin 4) :
    ∑ j, rootWeight (.inl i) j * typeF4CartanBezout i j = 1 := by
  have hweight (j : Fin 4) : rootWeight (.inl i) j = CartanMatrix.F₄ i j := by
    simpa only [DynkinType.rank_F4, DynkinType.cartanMatrix_F4] using
      (DynkinType.rootGeneratorWeight_inl (t := DynkinType.F4)
        (ht := DynkinType.valid_F4) i j)
  calc
    ∑ j, rootWeight (.inl i) j * typeF4CartanBezout i j =
        ∑ j, CartanMatrix.F₄ i j * typeF4CartanBezout i j :=
      Finset.sum_congr rfl fun j _ => by rw [hweight j]
    _ = 1 := sum_cartanMatrixF4_mul_typeF4CartanBezout i

private theorem rootWeight_inr_eq_neg_inl (i : Fin 4) :
    rootWeight (.inr i) = -rootWeight (.inl i) := by
  simpa only [DynkinType.rank_F4] using
    (DynkinType.rootGeneratorWeight_inr_eq_neg_root_simpleIndex
      (t := DynkinType.F4) (ht := DynkinType.valid_F4) i).trans
    (congrArg Neg.neg (DynkinType.rootGeneratorWeight_inl_eq_root_simpleIndex
      (t := DynkinType.F4) (ht := DynkinType.valid_F4) i).symm)

/-- Over every commutative ring, the rank-four weight torus of the short-root type-`F₄` module on
the base-changed admissible lattice is contained in the elementary group generated by the eight
positive and negative numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup lattice.toAddSubgroup latticeBasis f4ShortRootWeight A ≤
      kostantElementarySubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  kostantTorusSubgroup_le_kostantElementarySubgroup
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight
    isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
    Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl
    typeF4CartanBezout rootWeight_sum_mul_bezout A

/-- Over every commutative ring, adjoining the rank-four weight torus of the short-root type-`F₄`
module to all eight numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
        f4ShortRootWeight Set.univ A =
      kostantElementarySubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight
    isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
    Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl
    typeF4CartanBezout rootWeight_sum_mul_bezout A

/-! ## Scheme-theoretic generation -/

private theorem universalWeightTorus_mem_elementarySubgroup :
    let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup (Fin 4))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin 4))) A :=
      WithConv.toConv (AlgHom.id ℤ T)
    kostantTorusPoints lattice.toAddSubgroup latticeBasis f4ShortRootWeight A
        (SplitTorus.pointsMulEquiv q) ∈
      kostantElementarySubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A := by
  dsimp only
  apply weightTorusSubgroup_le_elementarySubgroup _
  rw [kostantTorusSubgroup_eq_range]
  exact ⟨_, rfl⟩

/-- **The short-root type-`F₄` integral toral closure is already generated scheme-theoretically by
its eight numbered root subgroups.** Equivalently, adjoining the represented weight torus does not
change the integral defining Hopf ideal. -/
theorem definingIdeal_eq_kostantGeneratedDefiningIdeal :
    definingIdeal =
      kostantGeneratedDefiningIdeal rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis := by
  rw [definingIdeal_def]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight
      universalWeightTorus_mem_elementarySubgroup

/-- The short-root type-`F₄` integral toral closure is the group scheme generated by its eight
numbered simple root subgroups. -/
theorem groupScheme_eq_kostantGeneratedGroupScheme :
    groupScheme =
      kostantGeneratedGroupScheme rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis :=
  kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight
    universalWeightTorus_mem_elementarySubgroup

/-- The canonical inclusion of the root-generated short-root type-`F₄` carrier into its toral
closure is an isomorphism. -/
instance isIso_kostantGeneratedToToral :
    CategoryTheory.IsIso (kostantGeneratedToToral rootGen cartanGen rep lattice.toAddSubgroup
      rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
      f4ShortRootWeight) :=
  isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis f4ShortRootWeight universalWeightTorus_mem_elementarySubgroup

/-- **Two morphisms out of the short-root type-`F₄` carrier agree as soon as they agree on its
eight numbered root subgroups.** This drops the weight-torus hypothesis of
`TauCeti.F4ShortRoot.groupScheme_hom_ext`, which root generation of the carrier makes
redundant. -/
@[ext high]
theorem groupScheme_hom_ext_of_rootSubgroup {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (f g : groupScheme ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup k ≫ f = rootSubgroup k ≫ g) :
    f = g :=
  kostantToralGroupScheme_hom_ext_of_universal_torus_mem_elementary rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis f4ShortRootWeight universalWeightTorus_mem_elementarySubgroup f g
    fun k => by simpa only [rootSubgroup_def] using hroot k

end TauCeti.F4ShortRoot
