/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.Eval
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GeneratedByY

/-!
# Function-field embeddings at a solution of the Weierstrass equation

Let `W` be a Weierstrass curve over a field `K`, and let `(x, y)` be a solution of its equation in
a field `L` over `K` whose first coordinate is transcendental over `K`. Evaluating the coordinate
ring at `(x, y)` is then injective (`WeierstrassCurve.Affine.CoordinateRing.algHom_injective`), so
it extends across the fraction field to a `K`-embedding `K(W) → L` sending the generic point
`(x_W, y_W)` to `(x, y)`. Its image is `K(x, y)`, the subfield generated by the two coordinates.
In particular, when `x` and `y` generate `L` over `K`, the embedding is an isomorphism
`K(W) ≃ₐ[K] L`.

This identifies a field presented by a Weierstrass equation with the function field of the
curve, so that what is computed for `K(W)` — the genus, the constants, the place at infinity —
transfers to it. The curve need not be elliptic.

## Main definitions

* `WeierstrassCurve.Affine.functionFieldLift`: the embedding `K(W) →ₐ[K] L` determined by a
  solution `(x, y)` in `L` with `x` transcendental.
* `WeierstrassCurve.Affine.functionFieldEquivOfAdjoinEqTop`: the isomorphism `K(W) ≃ₐ[K] L` when
  moreover `L = K(x, y)`.

## Main results

* `WeierstrassCurve.Affine.functionFieldLift_genericX` and
  `WeierstrassCurve.Affine.functionFieldLift_genericY`: the embedding sends the generic point to
  `(x, y)`, and `WeierstrassCurve.Affine.eq_functionFieldLift` says it is the only `K`-embedding
  doing so.
* `WeierstrassCurve.Affine.fieldRange_functionFieldLift`: its image is `K(x, y)`.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Proposition 6.1.3.
-/

public section

open Polynomial

open scoped IntermediateField

namespace WeierstrassCurve.Affine

variable {K L : Type*} [Field K] [Field L] [Algebra K L] {W : Affine K} {x y : L}

/-- The evaluation of the coordinate ring at a solution `(x, y)` of the Weierstrass equation is
injective when `x` is transcendental. -/
private theorem evalAlgHom_injective (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) : Function.Injective (CoordinateRing.evalAlgHom h) :=
  CoordinateRing.algHom_injective _ <| by
    rwa [CoordinateRing.mk, AdjoinRoot.mk_C, CoordinateRing.evalAlgHom_of_X]

/-- **The function field of a Weierstrass curve embeds at a solution of its equation**: a
solution `(x, y)` of the Weierstrass equation of `W` in a field `L` over `K`, with `x`
transcendental over `K`, defines the `K`-embedding `K(W) → L` sending the generic point to
`(x, y)`. -/
noncomputable def functionFieldLift (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) : W.FunctionField →ₐ[K] L :=
  IsFractionRing.liftAlgHom (evalAlgHom_injective h hx)

/-- On the coordinate ring, `functionFieldLift` is evaluation at the solution. -/
@[simp]
theorem functionFieldLift_algebraMap (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) (z : W.CoordinateRing) :
    functionFieldLift h hx (algebraMap W.CoordinateRing W.FunctionField z) =
      CoordinateRing.evalAlgHom h z := by
  simp [functionFieldLift, IsFractionRing.liftAlgHom_apply]

/-- `functionFieldLift` sends the generic `x`-coordinate to `x`. -/
@[simp]
theorem functionFieldLift_genericX (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) : functionFieldLift h hx W.genericX = x := by
  rw [genericX_def, functionFieldLift_algebraMap, CoordinateRing.mk, AdjoinRoot.mk_C,
    CoordinateRing.evalAlgHom_of_X]

/-- `functionFieldLift` sends the generic `y`-coordinate to `y`. -/
@[simp]
theorem functionFieldLift_genericY (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) : functionFieldLift h hx W.genericY = y := by
  rw [genericY_def, functionFieldLift_algebraMap, CoordinateRing.mk, AdjoinRoot.mk_X,
    CoordinateRing.evalAlgHom_root]

/-- **Uniqueness of `functionFieldLift`**: a `K`-embedding of `K(W)` into `L` is determined by the
images of the generic coordinates. -/
theorem eq_functionFieldLift (h : (W⁄L).toAffine.Equation x y) (hx : Transcendental K x)
    (f : W.FunctionField →ₐ[K] L) (hfx : f W.genericX = x) (hfy : f W.genericY = y) :
    f = functionFieldLift h hx :=
  AlgHom.toRingHom_injective <| FunctionField.ringHom_ext (fun a ↦ by simp)
    (by simp [hfx]) (by simp [hfy])

/-- **The image of `functionFieldLift` is `K(x, y)`.** -/
@[simp]
theorem fieldRange_functionFieldLift (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) : (functionFieldLift h hx).fieldRange = K⟮x, y⟯ := by
  rw [fieldRange_eq_adjoin_genericX_genericY, functionFieldLift_genericX,
    functionFieldLift_genericY]

/-- **A field generated by a solution of the Weierstrass equation is the function field of the
curve**: if `(x, y)` solves the Weierstrass equation of `W` in `L`, `x` is transcendental over `K`
and `L = K(x, y)`, then `functionFieldLift` is an isomorphism `K(W) ≃ₐ[K] L`. -/
noncomputable def functionFieldEquivOfAdjoinEqTop (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) (hxy : K⟮x, y⟯ = ⊤) : W.FunctionField ≃ₐ[K] L :=
  AlgEquiv.ofBijective (functionFieldLift h hx)
    ⟨(functionFieldLift h hx).toRingHom.injective, fun z ↦ by
      have hz : z ∈ (functionFieldLift h hx).fieldRange := by
        rw [fieldRange_functionFieldLift, hxy]
        trivial
      exact hz⟩

/-- The underlying map of `functionFieldEquivOfAdjoinEqTop` is `functionFieldLift`. -/
@[simp]
theorem coe_functionFieldEquivOfAdjoinEqTop (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) (hxy : K⟮x, y⟯ = ⊤) :
    ⇑(functionFieldEquivOfAdjoinEqTop h hx hxy) = functionFieldLift h hx := (rfl)

/-- The inverse of `functionFieldEquivOfAdjoinEqTop` sends `x` to the generic `x`-coordinate. -/
@[simp]
theorem functionFieldEquivOfAdjoinEqTop_symm_x (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) (hxy : K⟮x, y⟯ = ⊤) :
    (functionFieldEquivOfAdjoinEqTop h hx hxy).symm x = W.genericX := by
  rw [AlgEquiv.symm_apply_eq, coe_functionFieldEquivOfAdjoinEqTop, functionFieldLift_genericX]

/-- The inverse of `functionFieldEquivOfAdjoinEqTop` sends `y` to the generic `y`-coordinate. -/
@[simp]
theorem functionFieldEquivOfAdjoinEqTop_symm_y (h : (W⁄L).toAffine.Equation x y)
    (hx : Transcendental K x) (hxy : K⟮x, y⟯ = ⊤) :
    (functionFieldEquivOfAdjoinEqTop h hx hxy).symm y = W.genericY := by
  rw [AlgEquiv.symm_apply_eq, coe_functionFieldEquivOfAdjoinEqTop, functionFieldLift_genericY]

end WeierstrassCurve.Affine
