/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

import Mathlib.RingTheory.Localization.NormTrace
public import TauCeti.NumberTheory.LocalField.FiniteExtension.Basic
public import TauCeti.NumberTheory.LocalField.GaloisAction
public import TauCeti.NumberTheory.LocalField.InertiaDegree
public import TauCeti.NumberTheory.LocalField.Uniformizer
public import TauCeti.NumberTheory.LocalField.UnitFiltration.Basic
public import TauCeti.RingTheory.Norm.Units
public import Mathlib.RingTheory.Ideal.Norm.RelNorm
public import Mathlib.RingTheory.IntegralClosure.IntegralRestrict
import Mathlib.RingTheory.Norm.Transitivity
import Mathlib.RingTheory.Trace.Basic
import Mathlib.RingTheory.Valuation.Integral
import TauCeti.RingTheory.Norm.Quotient

/-!
# Norm valuations in finite local-field extensions

This file computes the normalized valuation of a field norm in finite extensions of
nonarchimedean local fields. Mapping the norm back to the extension field raises the original
valuation to the extension degree. The intrinsic formula is
`v_K(N_{L/K}(x)) = f(L/K) v_L(x)`.

The formula is the valuation input to the norm-group criterion for unramified extensions, which
`TauCeti.NumberTheory.LocalField.Norm.Unramified.Basic` combines with surjectivity of the norm on
units to identify the entire norm group. Read on ideals rather than on elements, the same formula
says that the norm image of the maximal ideal of `𝒪[L]` is the residue-degree power of the maximal
ideal of `𝒪[K]`.

Ideal norms are read through Mathlib's: the norm image of a principal ideal is
`Ideal.relNorm_singleton`, and the norm image of the maximal ideal is `Ideal.relNorm 𝒪[K] 𝓂[L]`,
the form in which the local discriminant ideal is written.

On the unit filtration the norm is contravariant to the algebra map, which carries `U(K,i)` into
`U(L, e(L/K) i)`: the norm carries `U(L, e(L/K) i)` into `U(K,i)`, because `𝓂[L]^(e i)` is the
ideal generated by `𝓂[K]^i` and the norm commutes with reduction modulo `𝓂[K]^i`. Without the
factor `e(L/K)` the inclusion is false for ramified extensions; the sharp statement carries a
Herbrand shift instead.

## Main results

* `TauCeti.normalizedValuation_algebraMap_norm`: the valuation calculation after applying the
  algebra map to a norm.
* `TauCeti.normalizedValuation_norm`: the normalized valuation of a norm is multiplied by the
  inertia degree.
* `TauCeti.toAdd_normalizedValuation_norm`: the preceding result in additive notation.
* `TauCeti.relNorm_maximalIdeal_eq_maximalIdeal_pow`: the ideal norm of the maximal ideal of
  `𝒪[L]` is the residue-degree power of the maximal ideal of `𝒪[K]`, the ideal-theoretic form of
  `TauCeti.toAdd_normalizedValuation_norm`.
* `TauCeti.normalizedValuationWithZero_norm`: the same formula for arbitrary field elements,
  including zero.
* `TauCeti.norm_mem_maximalIdeal_pow_of_mem`: the norm carries `𝓂[L] ^ m` into
  `𝓂[K] ^ (f(L/K) m)`.
* `TauCeti.irreducible_norm_iff_inertiaDegree_eq_one_of_irreducible`: the norm of an irreducible
  integer is irreducible exactly when the residue degree is one.
* `TauCeti.addVal_norm`: the additive valuation of the norm of an integer is multiplied by the
  inertia degree.
* `TauCeti.comap_zmultiples_inertiaDegree_le_normGroup`: if the units of `K` are norms, the norm
  group contains every element whose valuation is divisible by the residue degree.
* `TauCeti.normUnits_mem_unitFiltration_of_mem` and
  `TauCeti.map_normUnits_unitFiltration_le`: the norm carries `U(L, e(L/K) i)` into `U(K,i)`.
* `TauCeti.continuous_normUnits`: the norm on unit groups is continuous.
* `TauCeti.coe_norm_integerRing` and `TauCeti.coe_trace_integerRing`: the norm and trace of
  `𝒪[L]` over `𝒪[K]` restrict the norm and trace of `L/K`.
* `TauCeti.algebraMap_norm_integerRing_eq_prod_automorphisms` and
  `TauCeti.algebraMap_trace_integerRing_eq_sum_automorphisms`: in a Galois extension, the norm
  and trace of an integer are the product and the sum of its conjugates.

## References

* J.-P. Serre, *Local Fields*, Chapter I, §4 and Chapter V, §2.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §§4 and 7.
-/

public section

open ValuativeRel IsLocalRing IsNonarchimedeanLocalField

namespace TauCeti

variable {K L : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]
  [FiniteDimensional K L]

/-- The norm of a valuation-zero unit has valuation zero in every finite local-field extension. -/
theorem normalizedValuation_norm_eq_one_of_eq_one (x : Lˣ)
    (hx : normalizedValuation L x = 1) :
    normalizedValuation K (Algebra.normUnits K x) = 1 := by
  have hint (y : Lˣ) (hy : normalizedValuation L y = 1) : IsIntegral 𝒪[K] (y : L) := by
    apply (Valuation.Integers.isIntegral_iff_valuation_le_one
      (Valuation.integer.integers (valuation K)) (y : L)).2
    rw [(normalizedValuation_eq_one_iff y).1 hy]
  have hnorm (y : Lˣ) (hy : normalizedValuation L y = 1) :
      0 ≤ (normalizedValuation K (Algebra.normUnits K y)).toAdd := by
    apply (mem_integer_iff_toAdd_normalizedValuation_nonneg _).1
    rw [Valuation.mem_integer_iff, Algebra.coe_normUnits]
    exact (Valuation.Integers.isIntegral_iff_v_le_one
      (Valuation.integer.integers (valuation K))).1
        (Algebra.isIntegral_norm K (hint y hy))
  have hxinv : normalizedValuation L x⁻¹ = 1 := by simp [hx]
  have h₁ := hnorm x hx
  have h₂ := hnorm x⁻¹ hxinv
  simp only [map_inv, toAdd_inv] at h₂
  apply Multiplicative.toAdd.injective
  simp only [toAdd_one]
  omega

/-- **Valuation of a norm in a finite local-field extension.** The normalized valuation of
`N_{L/K}(x)` is `f(L/K)` times the normalized valuation of `x`. -/
@[simp]
theorem normalizedValuation_norm (x : Lˣ) :
    normalizedValuation K (Algebra.normUnits K x) =
      normalizedValuation L x ^ inertiaDegree K L := by
  obtain ⟨t, ht⟩ := normalizedValuation_surjective (K := K) (normalizedValuation L x)
  let u : Lˣ := Units.map (algebraMap K L : K →* L) t
  have hu : normalizedValuation L u =
      normalizedValuation L x ^ ramificationIndex K L := by
    rw [normalizedValuation_algebraMap, ht]
  let y := x ^ ramificationIndex K L * u⁻¹
  have hy : normalizedValuation L y = 1 := by
    simp only [y, map_mul, map_pow, map_inv]
    rw [hu]
    simp
  have hnorm : Algebra.normUnits K u = t ^ Module.finrank K L := by
    apply Units.ext
    simp [u, Algebra.norm_algebraMap]
  have hmap : (normalizedValuation K (Algebra.normUnits K u)).toAdd =
      Module.finrank K L * (normalizedValuation L x).toAdd := by
    rw [hnorm, map_pow, ht, toAdd_pow, nsmul_eq_mul]
  have heq : (normalizedValuation K (Algebra.normUnits K y)).toAdd =
      ramificationIndex K L * (normalizedValuation K (Algebra.normUnits K x)).toAdd -
        (normalizedValuation K (Algebra.normUnits K u)).toAdd := by
    simp [y, toAdd_mul, toAdd_pow, toAdd_inv, sub_eq_add_neg]
  have h := congrArg Multiplicative.toAdd
    (normalizedValuation_norm_eq_one_of_eq_one (K := K) y hy)
  rw [heq, hmap, toAdd_one, ← ramificationIndex_mul_inertiaDegree (K := K) (L := L)] at h
  apply Multiplicative.toAdd.injective
  rw [toAdd_pow, nsmul_eq_mul]
  have he : (ramificationIndex K L : ℤ) ≠ 0 := by
    exact_mod_cast (ramificationIndex_pos (K := K) (L := L)).ne'
  simp only [Nat.cast_mul] at h
  exact mul_left_cancel₀ he (by simpa only [mul_assoc] using (sub_eq_zero.mp h))

/-- **Valuation of a norm after scalar extension.** This is the intrinsic norm formula
multiplied by the ramification index, using `e(L/K) f(L/K) = [L : K]`. -/
theorem normalizedValuation_algebraMap_norm (x : Lˣ) :
    normalizedValuation L (Units.map (algebraMap K L : K →* L) (Algebra.normUnits K x)) =
      normalizedValuation L x ^ Module.finrank K L := by
  rw [normalizedValuation_algebraMap, normalizedValuation_norm, ← pow_mul,
    mul_comm (inertiaDegree K L) (ramificationIndex K L),
    ramificationIndex_mul_inertiaDegree]

/-- **Additive valuation of a norm in a finite local-field extension.** This is
`v_K(N_{L/K}(x)) = f(L/K) v_L(x)`. -/
theorem toAdd_normalizedValuation_norm (x : Lˣ) :
    (normalizedValuation K (Algebra.normUnits K x)).toAdd =
      inertiaDegree K L * (normalizedValuation L x).toAdd := by
  rw [normalizedValuation_norm, toAdd_pow, nsmul_eq_mul]

/-- **Valuation of the field norm in a finite local-field extension**, including zero. -/
@[simp]
theorem normalizedValuationWithZero_norm (x : L) :
    normalizedValuationWithZero K (Algebra.norm K x) =
      normalizedValuationWithZero L x ^ inertiaDegree K L := by
  by_cases hx : x = 0
  · subst x
    have hzero : (0 : WithZero (Multiplicative ℤ)) ^ inertiaDegree K L = 0 :=
      zero_pow ((inertiaDegree_pos (K := K) (L := L)).ne')
    rw [Algebra.norm_zero]
    simpa only [map_zero] using hzero.symm
  · let x' : Lˣ := Units.mk0 x hx
    have hnorm : normalizedValuationWithZero K (Algebra.norm K (x' : L)) =
        normalizedValuationWithZero L (x' : L) ^ inertiaDegree K L := by
      rw [← Algebra.coe_normUnits K x', normalizedValuationWithZero_coe,
        normalizedValuationWithZero_coe, normalizedValuation_norm]
      exact WithZero.coe_pow _ _
    simpa only [x', Units.val_mk0] using hnorm

omit [FiniteDimensional K L] in
/-- The norm of `𝒪[L]` over `𝒪[K]`, a free module of finite rank, is the restriction of the field
norm of `L/K`. -/
@[simp]
theorem coe_norm_integerRing (y : 𝒪[L]) :
    ((Algebra.norm 𝒪[K] y : 𝒪[K]) : K) = Algebra.norm K (y : L) := by
  have := isLocalization_integerRing K L
  exact (Algebra.norm_localization 𝒪[K] (nonZeroDivisors 𝒪[K]) y).symm

omit [FiniteDimensional K L] in
/-- The trace of `𝒪[L]` over `𝒪[K]`, a free module of finite rank, is the restriction of the field
trace of `L/K`. -/
@[simp]
theorem coe_trace_integerRing (y : 𝒪[L]) :
    ((Algebra.trace 𝒪[K] 𝒪[L] y : 𝒪[K]) : K) = Algebra.trace K L (y : L) := by
  have := isLocalization_integerRing K L
  exact (Algebra.trace_localization 𝒪[K] (nonZeroDivisors 𝒪[K]) y).symm

omit [FiniteDimensional K L] in
/-- The norm of an element of `𝒪[L]` lies in `𝒪[K]`. -/
theorem norm_mem_integer {y : L} (hy : y ∈ 𝒪[L]) : Algebra.norm K y ∈ 𝒪[K] := by
  simpa using (Algebra.norm 𝒪[K] (⟨y, hy⟩ : 𝒪[L])).2

-- The ideal-norm statement below is in a section of its own, without `FiniteDimensional K L`
-- in scope: `Ideal.relNorm` is elaborated by type class search, and with a
-- `FiniteDimensional K L` hypothesis in scope that search mentions the hypothesis, so an
-- `omit` of it is rejected.
section IdealNorm

variable {K L : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]

variable (K L) in
/-- **The ideal norm of the maximal ideal of `𝒪[L]` is the residue-degree power of the
maximal ideal of `𝒪[K]`**: `N_{L/K}(𝓂[L]) = 𝓂[K] ^ f(L/K)`, in the form of Mathlib's
`Ideal.relNorm`.

This is the ideal-theoretic form of `TauCeti.toAdd_normalizedValuation_norm`, the valuation
of a norm being `f(L/K)` times the valuation of its argument: a uniformizer of `𝒪[L]` is taken
to an element of `𝒪[K]` of normalized valuation `f(L/K)`, which generates `𝓂[K] ^ f(L/K)` in
the discrete valuation ring `𝒪[K]`. The principal-ideal step reads off
`Ideal.relNorm_singleton`. -/
theorem relNorm_maximalIdeal_eq_maximalIdeal_pow :
    Ideal.relNorm 𝒪[K] 𝓂[L] = 𝓂[K] ^ inertiaDegree K L := by
  let _ : FiniteDimensional K L := finite_of_valuativeExtension K L
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[L]
  have hϖ' : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
  have hπ' : (π : K) ≠ 0 := fun h ↦ hπ.ne_zero (Subtype.ext h)
  -- the norm of the uniformizer of `L` has residue-degree valuation in `K`, and so does the
  -- residue-degree power of the uniformizer of `K`
  have hn' : (normalizedValuation K (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).toAdd
      = (inertiaDegree K L : ℤ) := by
    have hn := toAdd_normalizedValuation_norm (K := K) (L := L) (Units.mk0 (ϖ : L) hϖ')
    simpa only [Units.val_mk0, normalizedValuation_irreducible hϖ, toAdd_ofAdd,
      nsmul_eq_mul, mul_one] using hn
  have hb : (normalizedValuation K (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).toAdd
      = (inertiaDegree K L : ℤ) := by
    rw [map_pow, toAdd_pow, normalizedValuation_irreducible hπ, toAdd_ofAdd,
      nsmul_eq_mul, mul_one]
  have hle : (normalizedValuation K (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).toAdd
      ≤ (normalizedValuation K (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).toAdd :=
    by rw [hb, hn']
  have hle' : (normalizedValuation K (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).toAdd
      ≤ (normalizedValuation K (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).toAdd :=
    by rw [hn', hb]
  -- in the discrete valuation ring `𝒪[K]`, divisibility is comparison of valuations
  have hA : ((Algebra.norm 𝒪[K] ϖ : 𝒪[K]) : K)
      = ((Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ') : Kˣ) : K) := by
    rw [coe_norm_integerRing]
    exact (Algebra.coe_normUnits (R := K) (Units.mk0 (ϖ : L) hϖ')).symm
  have hB : ((π ^ inertiaDegree K L : 𝒪[K]) : K)
      = ((Units.mk0 (π : K) hπ' ^ inertiaDegree K L : Kˣ) : K) := by
    push_cast
    exact (Units.val_pow_eq_pow_val (Units.mk0 (π : K) hπ') (inertiaDegree K L)).symm
  have hco : (algebraMap 𝒪[K] K : 𝒪[K] → K) = ((↑) : 𝒪[K] → K) :=
    Algebra.coe_algebraMap_ofSubsemiring 𝒪[K]
  have hval := Valuation.integer.integers (valuation K)
  have h₁ : (Algebra.norm 𝒪[K] ϖ) ∣ (π ^ inertiaDegree K L : 𝒪[K]) := by
    refine hval.dvd_iff_le.mpr ?_
    rw [hco, hB, hA]
    exact (toAdd_normalizedValuation_le_iff_valuation_le
      (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))
      (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).1 hle'
  have h₂ : (π ^ inertiaDegree K L : 𝒪[K]) ∣ (Algebra.norm 𝒪[K] ϖ) := by
    refine hval.dvd_iff_le.mpr ?_
    rw [hco, hB, hA]
    exact (toAdd_normalizedValuation_le_iff_valuation_le
      (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)
      (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).1 hle
  have hass : Associated (Algebra.norm 𝒪[K] ϖ) (π ^ inertiaDegree K L) :=
    associated_of_dvd_dvd h₁ h₂
  calc Ideal.relNorm 𝒪[K] 𝓂[L]
      = Ideal.relNorm 𝒪[K] (Ideal.span {↑ϖ} : Ideal 𝒪[L]) := by rw [hϖ.maximalIdeal_eq]
    _ = Ideal.span {Algebra.intNorm 𝒪[K] 𝒪[L] ϖ} := Ideal.relNorm_singleton 𝒪[K] ϖ
    _ = Ideal.span {↑(π ^ inertiaDegree K L)} := by
      rw [Algebra.intNorm_eq_norm]
      exact (Ideal.span_singleton_eq_span_singleton).2 hass
    _ = (Ideal.span {↑π} : Ideal 𝒪[K]) ^ inertiaDegree K L :=
        (Ideal.span_singleton_pow (π : 𝒪[K]) (inertiaDegree K L)).symm
    _ = 𝓂[K] ^ inertiaDegree K L := by rw [hπ.maximalIdeal_eq]

variable (K) in
/-- The norm of an element of `𝓂[L] ^ m` lies in `𝓂[K] ^ (f(L/K) m)`. -/
theorem norm_mem_maximalIdeal_pow_of_mem {m : ℕ} {x : 𝒪[L]} (hx : x ∈ 𝓂[L] ^ m) :
    Algebra.norm 𝒪[K] x ∈ 𝓂[K] ^ (inertiaDegree K L * m) := by
  rw [pow_mul, ← relNorm_maximalIdeal_eq_maximalIdeal_pow, ← map_pow]
  exact Ideal.norm_mem_relNorm 𝒪[K] _ hx

end IdealNorm

/-- A unit of `L` is a unit of `𝒪[L]` exactly when its norm is a unit of `𝒪[K]`. -/
-- The left-hand side simplifies via `unitFiltration_zero`, so this is not a simp lemma.
theorem normUnits_mem_unitFiltration_zero_iff {y : Lˣ} :
    Algebra.normUnits K y ∈ unitFiltration K 0 ↔ y ∈ unitFiltration L 0 := by
  rw [mem_unitFiltration_zero, mem_unitFiltration_zero, ← normalizedValuation_eq_one_iff,
    ← normalizedValuation_eq_one_iff, normalizedValuation_norm,
    pow_eq_one_iff_left (inertiaDegree_pos (K := K) (L := L)).ne']

omit [FiniteDimensional K L] in
variable (L) in
/-- **The norm carries `U(L, e(L/K) i)` into `U(K, i)`.** A unit of `𝒪[L]` congruent to `1` modulo
`𝓂[L]^(e i) = 𝓂[K]^i 𝒪[L]` has norm congruent to `1` modulo `𝓂[K]^i`, because the norm commutes
with reduction modulo `𝓂[K]^i`. -/
theorem normUnits_mem_unitFiltration_of_mem {i : ℕ} {y : Lˣ}
    (hy : y ∈ unitFiltration L (ramificationIndex K L * i)) :
    Algebra.normUnits K y ∈ unitFiltration K i := by
  obtain ⟨u, hu, huy⟩ := mem_unitFiltration_iff_exists.mp hy
  have hmap : 𝓂[L] ^ (ramificationIndex K L * i) = (𝓂[K] ^ i).map (algebraMap 𝒪[K] 𝒪[L]) := by
    rw [Ideal.map_pow, map_maximalIdeal_eq_maximalIdeal_pow, ← pow_mul]
  -- `u ≡ 1` modulo `𝓂[K]^i 𝒪[L]`, so its norm is congruent to `N(1) = 1` modulo `𝓂[K]^i`.
  have h1 : Ideal.Quotient.mk ((𝓂[K] ^ i).map (algebraMap 𝒪[K] 𝒪[L])) (u : 𝒪[L]) = 1 := by
    rw [← map_one (Ideal.Quotient.mk _), Ideal.Quotient.eq, ← hmap]
    exact hu
  have hN : (Algebra.normUnits 𝒪[K] u : 𝒪[K]) - 1 ∈ 𝓂[K] ^ i := by
    rw [Algebra.coe_normUnits, ← Ideal.Quotient.eq, map_one, ← Algebra.norm_quotient_mk, h1,
      map_one]
  refine mem_unitFiltration_iff_exists.mpr ⟨Algebra.normUnits 𝒪[K] u, hN, ?_⟩
  rw [Algebra.coe_normUnits, Algebra.coe_normUnits, coe_norm_integerRing, huy]

omit [FiniteDimensional K L] in
variable (K L) in
/-- **The norm carries `U(L, e(L/K) i)` into `U(K, i)`**, as an inclusion of subgroups of `Kˣ`. At
`i = 0` this says that the norm of a unit of `𝒪[L]` is a unit of `𝒪[K]`. -/
theorem map_normUnits_unitFiltration_le (i : ℕ) :
    (unitFiltration L (ramificationIndex K L * i)).map (Algebra.normUnits K) ≤
      unitFiltration K i :=
  Subgroup.map_le_iff_le_comap.mpr fun _ hy ↦ normUnits_mem_unitFiltration_of_mem L hy

omit [FiniteDimensional K L] in
variable (K L) in
/-- The norm on unit groups of compatible local-field extensions is continuous. -/
theorem continuous_normUnits : Continuous (Algebra.normUnits K : Lˣ → Kˣ) := by
  apply continuous_of_continuousAt_one
  rw [ContinuousAt, map_one]
  refine ((hasBasis_nhds_one_unitFiltration (K := L)).tendsto_iff
    (hasBasis_nhds_one_unitFiltration (K := K))).2 ?_
  intro i _
  exact ⟨ramificationIndex K L * i, trivial, fun _ hy ↦
    normUnits_mem_unitFiltration_of_mem L hy⟩

/-- The norm of a uniformizer of `L` is a uniformizer of `K` exactly when the residue degree is
`1`, that is when `L/K` is totally ramified. -/
theorem isUniformizer_normUnits_iff {ϖ : Lˣ} (hϖ : IsUniformizer L ϖ) :
    IsUniformizer K (Algebra.normUnits K ϖ) ↔ inertiaDegree K L = 1 := by
  rw [isUniformizer_def] at hϖ ⊢
  rw [normalizedValuation_norm, hϖ, ← ofAdd_nsmul, Multiplicative.ofAdd.injective.eq_iff,
    nsmul_one]
  exact Nat.cast_eq_one

omit [FiniteDimensional K L] in
/-- The norm of an irreducible element of `𝒪[L]` is irreducible in `𝒪[K]` exactly when the
residue degree of `L/K` is one. -/
theorem irreducible_norm_iff_inertiaDegree_eq_one_of_irreducible {ξ : 𝒪[L]}
    (hξ : Irreducible ξ) : Irreducible (Algebra.norm 𝒪[K] ξ) ↔ inertiaDegree K L = 1 := by
  let _ : FiniteDimensional K L := finite_of_valuativeExtension K L
  have hξL : (ξ : L) ≠ 0 := fun h ↦ hξ.ne_zero (Subtype.ext h)
  let x : Lˣ := Units.mk0 (ξ : L) hξL
  have hnorm0 : ((Algebra.norm 𝒪[K] ξ : 𝒪[K]) : K) ≠ 0 := by
    rw [coe_norm_integerRing]
    exact Algebra.norm_ne_zero_iff.mpr hξL
  have heq : Algebra.normUnits K x =
      Units.mk0 ((Algebra.norm 𝒪[K] ξ : 𝒪[K]) : K) hnorm0 := by
    apply Units.ext
    simp [x]
  have hx : IsUniformizer L x :=
    (isUniformizer_def _).mpr (by simpa [x] using normalizedValuation_irreducible hξ)
  rw [← isUniformizer_normUnits_iff hx, heq]
  refine ⟨fun h ↦ (isUniformizer_def _).mpr (normalizedValuation_irreducible h), fun hnorm ↦ ?_⟩
  obtain ⟨π, hπ, hπeq⟩ := (isUniformizer_iff_exists_irreducible K _).mp hnorm
  have hπnorm : π = Algebra.norm 𝒪[K] ξ := by
    apply Subtype.ext
    simpa using hπeq
  rwa [← hπnorm]

omit [FiniteDimensional K L] in
/-- **The valuation of a norm**: `v_K(N_{L/K}(z)) = f(L/K) v_L(z)` for every `z ∈ 𝒪[L]`, read on
the additive valuations of the discrete valuation rings `𝒪[K]` and `𝒪[L]`. -/
theorem addVal_norm (z : 𝒪[L]) :
    IsDiscreteValuationRing.addVal 𝒪[K] (Algebra.norm 𝒪[K] z) =
      inertiaDegree K L • IsDiscreteValuationRing.addVal 𝒪[L] z := by
  let _ : FiniteDimensional K L := finite_of_valuativeExtension K L
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[L]
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  -- The norm of a uniformizer of `L` generates `N_{L/K}(𝓂[L]) = 𝓂[K] ^ f`.
  have hN : IsDiscreteValuationRing.addVal 𝒪[K] (Algebra.norm 𝒪[K] ϖ) = inertiaDegree K L := by
    -- The ideal norm of `𝓂[L] = (ϖ)` is the principal ideal of `N(ϖ)`.
    have hrel : Ideal.relNorm 𝒪[K] 𝓂[L] = Ideal.span {Algebra.norm 𝒪[K] ϖ} := by
      rw [hϖ.maximalIdeal_eq, Ideal.relNorm_singleton, Algebra.intNorm_eq_norm]
    -- On the other hand it is `𝓂[K] ^ f = (π ^ f)`.
    have hpow : 𝓂[K] ^ inertiaDegree K L = Ideal.span {π ^ inertiaDegree K L} := by
      rw [hπ.maximalIdeal_eq, Ideal.span_singleton_pow]
    have hspan : Ideal.span {Algebra.norm 𝒪[K] ϖ} = Ideal.span {π ^ inertiaDegree K L} := by
      rw [← hrel, ← hpow, relNorm_maximalIdeal_eq_maximalIdeal_pow]
    rw [(IsDiscreteValuationRing.addVal_eq_iff_associated _ _).2
      (Ideal.span_singleton_eq_span_singleton.1 hspan)]
    simp only [IsDiscreteValuationRing.addVal_pow,
      IsDiscreteValuationRing.addVal_uniformizer hπ, nsmul_one]
  rcases eq_or_ne z 0 with rfl | hz
  · have hf : (inertiaDegree K L : ENat) ≠ 0 := by
      exact_mod_cast (inertiaDegree_pos (K := K) (L := L)).ne'
    simp [Algebra.norm_zero, nsmul_eq_mul, hf]
  obtain ⟨k, u, rfl⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hz hϖ
  have hu := IsDiscreteValuationRing.addVal_eq_zero_of_unit
    (Units.map (Algebra.norm 𝒪[K] : 𝒪[L] →* 𝒪[K]) u)
  rw [Units.coe_map] at hu
  simp only [map_mul, map_pow, IsDiscreteValuationRing.addVal_mul, hu,
    IsDiscreteValuationRing.addVal_pow, hN, IsDiscreteValuationRing.addVal_def' u hϖ k, zero_add,
    nsmul_eq_mul, mul_comm]

variable (L) in
/-- The normalized valuation of an element of the norm group `N_{L/K}(Lˣ)` is divisible by the
residue degree `f(L/K)`. -/
theorem inertiaDegree_dvd_of_mem_normGroup {x : Kˣ}
    (hx : x ∈ normGroup K L) :
    (inertiaDegree K L : ℤ) ∣ (normalizedValuation K x).toAdd := by
  obtain ⟨y, hy⟩ := mem_normGroup_iff.mp hx
  have h : Algebra.normUnits K y = x := Units.ext (by simpa using hy)
  subst x
  exact ⟨_, toAdd_normalizedValuation_norm y⟩

/-- If the units of `K` are norms from `L`, then the norm group contains every element of `Kˣ`
whose valuation is divisible by the residue degree `f(L/K)`: such an element is a power of the
norm of a uniformizer of `L` times a unit. -/
theorem comap_zmultiples_inertiaDegree_le_normGroup
    (hU : unitFiltration K 0 ≤ normGroup K L) :
    (AddSubgroup.zmultiples (inertiaDegree K L : ℤ)).toSubgroup.comap (normalizedValuation K) ≤
      normGroup K L := by
  intro x hx
  obtain ⟨k, hk⟩ : (inertiaDegree K L : ℤ) ∣ (normalizedValuation K x).toAdd :=
    Int.mem_zmultiples_iff.mp ((Multiplicative.mem_toSubgroup _ _).mp hx)
  obtain ⟨ϖ, hϖ⟩ := normalizedValuation_surjective (K := L) (Multiplicative.ofAdd 1)
  let y := Algebra.normUnits K ϖ
  have hy : y ∈ normGroup K L := mem_normGroup_iff.2 ⟨ϖ, by simp [y]⟩
  -- `x * y ^ (-k)` has valuation zero, so it is a unit and hence a norm.
  have hunit : x * y ^ (-k) ∈ normGroup K L := by
    refine hU <| (mem_unitFiltration_zero _).2 <| (normalizedValuation_eq_one_iff _).1 ?_
    apply Multiplicative.toAdd.injective
    simp only [y, map_mul, map_zpow, toAdd_mul, toAdd_zpow, toAdd_normalizedValuation_norm, hϖ,
      toAdd_ofAdd, hk, toAdd_one, smul_eq_mul]
    ring
  simpa using mul_mem hunit (zpow_mem hy k)

section Galois

variable [IsGalois K L]

/-- In a Galois extension, the norm of an integer `z` of `L`, read in `𝒪[L]`, is the product of
the Galois conjugates of `z`. -/
theorem algebraMap_norm_integerRing_eq_prod_automorphisms (z : 𝒪[L]) :
    algebraMap 𝒪[K] 𝒪[L] (Algebra.norm 𝒪[K] z) = ∏ σ : L ≃ₐ[K] L, σ • z := by
  apply Subtype.ext
  rw [coe_algebraMap_integerRing, coe_norm_integerRing, Algebra.norm_eq_prod_automorphisms,
    SubmonoidClass.coe_finsetProd]
  simp only [AlgEquiv.coe_smul_integerRing]

/-- In a Galois extension, the trace of an integer `z` of `L`, read in `𝒪[L]`, is the sum of the
Galois conjugates of `z`. -/
theorem algebraMap_trace_integerRing_eq_sum_automorphisms (z : 𝒪[L]) :
    algebraMap 𝒪[K] 𝒪[L] (Algebra.trace 𝒪[K] 𝒪[L] z) = ∑ σ : L ≃ₐ[K] L, σ • z := by
  apply Subtype.ext
  rw [coe_algebraMap_integerRing, coe_trace_integerRing, _root_.trace_eq_sum_automorphisms,
    AddSubmonoidClass.coe_finsetSum]
  simp only [AlgEquiv.coe_smul_integerRing]

end Galois

end TauCeti
