/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.GrothendieckGroup.GroupAlgebra.Finrank
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# Necessary multipliers for induction from prime-to-`p` subgroups

For a finite group `G`, induction from a subgroup of order prime to `p` produces a class
whose dimension is divisible by `ordProj[p] (Nat.card G)`. Additivity of dimension extends
this constraint to the subgroup generated by all such induced classes. In particular,
if a multiple `n` of the trivial class is a sum of these classes, the `p`-part of `|G|`
divides `n`. This explains the necessary prime-power factor in modular Artin induction.

The bound holds over every field: neither characteristic `p` nor cyclicity of the inducing
subgroups is needed. It concerns exact Grothendieck classes, including virtual classes
of negative dimension. The supremum-of-ranges formulation handles any family of subgroups;
the finite linear-combination formulation applies directly to explicit induction identities.

## References

* J.-P. Serre, *Linear Representations of Finite Groups*, Part III, §14.1.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, second edition,
  §VII.3, (7.3.4).
-/

public section

open scoped MonoidAlgebra

namespace TauCeti

universe u

variable {k G : Type u} [Field k] [Group G] [Finite G]
  {p : ℕ} (hp : p.Prime)

include hp

/-- Every class in the subgroup generated by induction from a family of prime-to-`p`
subgroups has dimension divisible by the `p`-part of the group order. -/
theorem ordProj_dvd_finrankK0_of_mem_iSup_range_indK0
    {P : Subgroup G → Prop} (hP : ∀ S, P S → ¬ p ∣ Nat.card S)
    {x : ExactK0 (finiteModulesExactStructure k[G])}
    (hx : x ∈ ⨆ (S : Subgroup G) (_ : P S), (indK0 k S).range) :
    (ordProj[p] (Nat.card G) : ℤ) ∣ finrankK0 k k[G] x := by
  have hle : (⨆ (S : Subgroup G) (_ : P S), (indK0 k S).range) ≤
      (AddSubgroup.zmultiples (ordProj[p] (Nat.card G) : ℤ)).comap (finrankK0 k k[G]) := by
    refine iSup_le fun S ↦ iSup_le fun hS ↦ ?_
    rintro _ ⟨y, rfl⟩
    exact Int.mem_zmultiples_iff.mpr (S.ordProj_dvd_finrankK0_indK0 hp (hP S hS) y)
  exact Int.mem_zmultiples_iff.mp (hle hx)

/-- If an integer multiple of the trivial class is generated by induction from
prime-to-`p` subgroups, the entire `p`-part of the group order divides that multiplier. -/
theorem ordProj_dvd_of_zsmul_one_mem_iSup_range_indK0
    {P : Subgroup G → Prop} (hP : ∀ S, P S → ¬ p ∣ Nat.card S) {n : ℤ}
    (hn : n • (1 : ExactK0 (finiteModulesExactStructure k[G])) ∈
      ⨆ (S : Subgroup G) (_ : P S), (indK0 k S).range) :
    (ordProj[p] (Nat.card G) : ℤ) ∣ n := by
  have h := ordProj_dvd_finrankK0_of_mem_iSup_range_indK0 hp hP hn
  rw [map_zsmul, finrankK0_one] at h
  simpa using h

/-- If a natural-number multiple of the trivial class is generated by induction from
prime-to-`p` subgroups, the entire `p`-part of the group order divides that multiplier. -/
theorem ordProj_dvd_of_nsmul_one_mem_iSup_range_indK0
    {P : Subgroup G → Prop} (hP : ∀ S, P S → ¬ p ∣ Nat.card S) {n : ℕ}
    (hn : n • (1 : ExactK0 (finiteModulesExactStructure k[G])) ∈
      ⨆ (S : Subgroup G) (_ : P S), (indK0 k S).range) :
    ordProj[p] (Nat.card G) ∣ n := by
  exact Int.natCast_dvd_natCast.mp
    (ordProj_dvd_of_zsmul_one_mem_iSup_range_indK0 hp hP (n := (n : ℤ))
      (by simpa only [natCast_zsmul] using hn))

/-- When `p` divides the group order, the trivial class cannot be generated by induction
from subgroups of order prime to `p`. Thus a positive multiplier is essential. -/
theorem one_notMem_iSup_range_indK0_of_dvd_natCard
    {P : Subgroup G → Prop} (hP : ∀ S, P S → ¬ p ∣ Nat.card S)
    (hG : p ∣ Nat.card G) :
    (1 : ExactK0 (finiteModulesExactStructure k[G])) ∉
      ⨆ (S : Subgroup G) (_ : P S), (indK0 k S).range := by
  intro h
  have hpart := ordProj_dvd_of_nsmul_one_mem_iSup_range_indK0 hp hP (n := 1)
    (by simpa using h)
  have hpow : 1 ≤ (Nat.card G).factorization p :=
    (hp.dvd_iff_one_le_factorization (Nat.card_pos.ne')).mp hG
  exact hp.not_dvd_one ((dvd_pow_self p (by omega)).trans hpart)

/-- An explicit integral linear combination of classes induced from prime-to-`p`
subgroups satisfies the same dimension divisibility constraint. -/
theorem ordProj_dvd_finrankK0_linearCombination_indK0 {ι : Type*}
    (S : ι → Subgroup G) (hS : ∀ i, ¬ p ∣ Nat.card (S i))
    (y : ∀ i, ExactK0 (finiteModulesExactStructure k[S i])) (a : ι →₀ ℤ) :
    (ordProj[p] (Nat.card G) : ℤ) ∣
      finrankK0 k k[G] (Finsupp.linearCombination ℤ (fun i ↦ indK0 k (S i) (y i)) a) := by
  classical
  refine ordProj_dvd_finrankK0_of_mem_iSup_range_indK0 hp
    (P := fun T ↦ ∃ i, T = S i) (by rintro T ⟨i, rfl⟩; exact hS i) ?_
  rw [Finsupp.linearCombination_apply, Finsupp.sum]
  apply AddSubgroup.sum_mem
  intro i _
  apply AddSubgroup.zsmul_mem
  exact AddSubgroup.mem_iSup_of_mem (S i)
    (AddSubgroup.mem_iSup_of_mem ⟨i, rfl⟩ ⟨y i, rfl⟩)

/-- In an explicit induction identity for an integer multiple of the trivial class, the
multiplier must contain the `p`-part of the group order. The coefficients may be negative. -/
theorem ordProj_dvd_of_zsmul_one_eq_linearCombination_indK0 {ι : Type*}
    (S : ι → Subgroup G) (hS : ∀ i, ¬ p ∣ Nat.card (S i))
    (y : ∀ i, ExactK0 (finiteModulesExactStructure k[S i])) (a : ι →₀ ℤ) {n : ℤ}
    (hn : n • (1 : ExactK0 (finiteModulesExactStructure k[G])) =
      Finsupp.linearCombination ℤ (fun i ↦ indK0 k (S i) (y i)) a) :
    (ordProj[p] (Nat.card G) : ℤ) ∣ n := by
  have h := ordProj_dvd_finrankK0_linearCombination_indK0 hp S hS y a
  rw [← hn, map_zsmul, finrankK0_one] at h
  simpa using h

/-- In an explicit induction identity for a natural-number multiple of the trivial class,
the multiplier must contain the `p`-part of the group order. The coefficients may be negative. -/
theorem ordProj_dvd_of_nsmul_one_eq_linearCombination_indK0 {ι : Type*}
    (S : ι → Subgroup G) (hS : ∀ i, ¬ p ∣ Nat.card (S i))
    (y : ∀ i, ExactK0 (finiteModulesExactStructure k[S i])) (a : ι →₀ ℤ) {n : ℕ}
    (hn : n • (1 : ExactK0 (finiteModulesExactStructure k[G])) =
      Finsupp.linearCombination ℤ (fun i ↦ indK0 k (S i) (y i)) a) :
    ordProj[p] (Nat.card G) ∣ n := by
  exact Int.natCast_dvd_natCast.mp
    (ordProj_dvd_of_zsmul_one_eq_linearCombination_indK0 hp S hS y a (n := (n : ℤ))
      (by simpa only [natCast_zsmul] using hn))

end TauCeti
