/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.TwoSidedIdeal.Operations
public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.PathsInto

/-!
# Ideals generated by one corner relator per vertex

Let `R` be a quiver with finitely many vertices and arrows, `k` a commutative ring, and let every
vertex `v` carry a relator `r_v` lying in the left corner `e_v kR`, so that `e_v r_v = r_v`. This
file describes the two-sided ideal `I` the relators generate, and the relations among the arrows
into a fixed vertex in the quotient `A = kR / I`.

Since `kR` is generated by its vertex idempotents and arrows,

```text
I = ∑_v r_v kR + ∑_b b I,
```

and cutting this down to the corner of `j` keeps only the relator at `j` and the arrows into `j`
(`TauCeti.PathAlgebra.exists_eq_sum_ofArrow_mul_of_mem_span_of_vertexIdempotent_mul`).

Write `r_j = ∑_{b : i ⟶ j} b c_b`, decomposing the relator along its last arrow. If `y_b` are
elements with `∑_b b y_b ∈ I`, then there is a single `Y` with `e_i y_b ≡ e_i c_b Y` modulo `I` for
every arrow `b : i ⟶ j` (`TauCeti.PathAlgebra.exists_sub_mul_mem_span_of_sum_ofArrow_mul_mem_span`).
In the language of right `A`-modules, the kernel of

```text
⨁_{b : i ⟶ j} e_i A ⟶ e_j A,    (z_b) ↦ ∑_b b z_b
```

is the image of `A ⟶ ⨁_b e_i A`, `y ↦ (e_i c_b y)_b`; when moreover `c_b e_j = c_b` for every
`b`, as for the preprojective relators, `y` may be replaced by `e_j y`, so the image is already that
of `e_j A`. The uniqueness of the last-arrow
decomposition in `kR` (`TauCeti.PathAlgebra.sum_ofArrow_mul_eq_zero_iff`) is what lifts a relation
among the `b z_b` in `A` to the relator.

## Main results

* `TauCeti.PathAlgebra.exists_eq_sum_mul_add_sum_ofArrow_mul_of_mem_span`: every element of `I` is
  `∑_v r_v Y_v + ∑_b b Z_b` with every `Z_b ∈ I`.
* `TauCeti.PathAlgebra.exists_eq_sum_ofArrow_mul_of_mem_span_of_vertexIdempotent_mul`: the same
  for an element of the corner of `j`, with only `r_j` and the arrows into `j` appearing.
* `TauCeti.PathAlgebra.exists_sub_mul_mem_span_of_sum_ofArrow_mul_mem_span`: **the relations
  among the arrows into `j` in `kR / I` are generated by the relator at `j`.**

## References

* D. J. Anick, *Non-commutative graded algebras and their Hilbert series*, J. Algebra 78 (1982),
  for the resolution `A ⊗ R ⟶ A ⊗ V ⟶ A ⟶ k` of an algebra presented by generators and relations.
* P. Etingof and C.-H. Eu, *Koszulity and the Hilbert series of preprojective algebras*, Math.
  Res. Lett. 14 (2007), Section 2, for its form for path algebras with one relator per vertex.
-/

public section

namespace TauCeti

open _root_.Quiver

universe u v w

namespace PathAlgebra

variable {k : Type w} {R : Type u} [Quiver.{v} R]

/-- Left multiplication by a vertex idempotent keeps a corner relator at that vertex and kills the
relators at the other vertices. -/
theorem vertexIdempotent_mul_eq_ite [Semiring k] [DecidableEq R] {r : R → pathAlgebra k R}
    (hl : ∀ v, vertexIdempotent k v * r v = r v) (u v : R) :
    vertexIdempotent k u * r v = if u = v then r v else 0 := by
  split_ifs with h
  · rw [h, hl]
  · rw [← hl v, ← mul_assoc, vertexIdempotent_mul_vertexIdempotent_of_ne h, zero_mul]

section Decomposition

variable [CommRing k] [Fintype R] [∀ a b : R, Fintype (a ⟶ b)] {r : R → pathAlgebra k R}

/-- `F` is a sum `∑ᵥ r_v Y_v + ∑_b b Z_b` whose arrow coefficients `Z_b` lie in the two-sided
ideal generated by the `r_v`. -/
private def IsRelDecomp (r : R → pathAlgebra k R) (F : pathAlgebra k R) : Prop :=
  ∃ (Y : R → pathAlgebra k R) (Z : (Σ i j : R, (i ⟶ j)) → pathAlgebra k R),
    (∀ a, Z a ∈ TwoSidedIdeal.span (Set.range r)) ∧
      F = ∑ v, r v * Y v + ∑ a, ofArrow a.2.2 * Z a

private theorem isRelDecomp_zero : IsRelDecomp r 0 :=
  ⟨0, 0, fun _ => zero_mem _, by simp⟩

private theorem IsRelDecomp.add {F G : pathAlgebra k R} (hF : IsRelDecomp r F)
    (hG : IsRelDecomp r G) : IsRelDecomp r (F + G) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  obtain ⟨Y', Z', hZ', rfl⟩ := hG
  refine ⟨Y + Y', Z + Z', fun a => add_mem (hZ a) (hZ' a), ?_⟩
  simp only [Pi.add_apply, mul_add, Finset.sum_add_distrib]
  abel

private theorem IsRelDecomp.neg {F : pathAlgebra k R} (hF : IsRelDecomp r F) :
    IsRelDecomp r (-F) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨-Y, -Z, fun a => neg_mem (hZ a), ?_⟩
  simp only [Pi.neg_apply, mul_neg, Finset.sum_neg_distrib, neg_add]

private theorem IsRelDecomp.smul {F : pathAlgebra k R} (c : k) (hF : IsRelDecomp r F) :
    IsRelDecomp r (c • F) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨c • Y, c • Z, fun a => ?_, ?_⟩
  · rw [Pi.smul_apply, ← TwoSidedIdeal.mem_asIdeal]
    exact Submodule.smul_of_tower_mem _ c (TwoSidedIdeal.mem_asIdeal.2 (hZ a))
  · simp only [Pi.smul_apply, mul_smul_comm, smul_add, Finset.smul_sum]

private theorem IsRelDecomp.mul_right {F : pathAlgebra k R} (x : pathAlgebra k R)
    (hF : IsRelDecomp r F) : IsRelDecomp r (F * x) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨fun v => Y v * x, fun a => Z a * x,
    fun a => TwoSidedIdeal.mul_mem_right _ _ _ (hZ a), ?_⟩
  simp only [add_mul, Finset.sum_mul, mul_assoc]

private theorem ofArrow_mul_isRelDecomp {i j : R} (b : i ⟶ j) {G : pathAlgebra k R}
    (hG : G ∈ TwoSidedIdeal.span (Set.range r)) : IsRelDecomp r (ofArrow b * G) := by
  classical
  refine ⟨0, fun a => if a = ⟨i, j, b⟩ then G else 0, fun a => ?_, ?_⟩
  · dsimp only
    split_ifs
    · exact hG
    · exact zero_mem _
  · simp only [Pi.zero_apply, mul_zero, Finset.sum_const_zero, zero_add, mul_ite,
      Finset.sum_ite_eq', Finset.mem_univ, ↓reduceIte]

private theorem IsRelDecomp.vertexIdempotent_mul (hl : ∀ v, vertexIdempotent k v * r v = r v)
    (u : R) {F : pathAlgebra k R} (hF : IsRelDecomp r F) :
    IsRelDecomp r (vertexIdempotent k u * F) := by
  classical
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨fun v => if u = v then Y v else 0, fun a => if a.2.1 = u then Z a else 0,
    fun a => ?_, ?_⟩
  · dsimp only
    split_ifs
    · exact hZ a
    · exact zero_mem _
  · simp only [mul_add, Finset.mul_sum, ← mul_assoc, vertexIdempotent_mul_eq_ite hl,
      vertexIdempotent_mul_ofArrow, ite_mul, zero_mul, mul_ite, mul_zero]

/-- **Every element of the relation ideal is a combination of relators and of arrows times
elements of the ideal.** This is the identity `I = ∑ᵥ r_v · kR + ∑_b b · I`, valid because the
path algebra is generated by the vertex idempotents and the arrows. -/
theorem exists_eq_sum_mul_add_sum_ofArrow_mul_of_mem_span
    (hl : ∀ v, vertexIdempotent k v * r v = r v) {F : pathAlgebra k R}
    (hF : F ∈ TwoSidedIdeal.span (Set.range r)) :
    ∃ (Y : R → pathAlgebra k R) (Z : (Σ i j : R, (i ⟶ j)) → pathAlgebra k R),
      (∀ a, Z a ∈ TwoSidedIdeal.span (Set.range r)) ∧
        F = ∑ v, r v * Y v + ∑ a, ofArrow a.2.2 * Z a := by
  classical
  -- `IsRelDecomp r F` is by definition the displayed existential.
  suffices h : IsRelDecomp r F from h
  induction hF using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨v, rfl⟩ := hx
    refine ⟨fun u => if u = v then 1 else 0, 0, fun _ => zero_mem _, ?_⟩
    simp only [mul_ite, mul_one, mul_zero, Finset.sum_ite_eq', Finset.mem_univ, ↓reduceIte,
      Pi.zero_apply, Finset.sum_const_zero, add_zero]
  | zero => exact isRelDecomp_zero
  | add x y _ _ hx hy => exact hx.add hy
  | neg x _ hx => exact hx.neg
  | right_absorb b x _ hx => exact hx.mul_right b
  | left_absorb a x hxI hx =>
    induction a using PathAlgebra.induction_linear with
    | zero => rw [zero_mul]; exact isRelDecomp_zero
    | add a a' ha ha' => rw [add_mul]; exact ha.add ha'
    | single x' c =>
      rw [single_eq_smul_ofPath, smul_mul_assoc]
      refine IsRelDecomp.smul c ?_
      obtain ⟨s, t, p⟩ := x'
      cases p with
      | nil =>
        rw [← vertexIdempotent_eq_ofPath]
        exact hx.vertexIdempotent_mul hl s
      | cons q b =>
        rw [← ofArrow_mul_ofPath, mul_assoc]
        exact ofArrow_mul_isRelDecomp b (TwoSidedIdeal.mul_mem_left _ _ _ hxI)

/-- **The corner form of the relation ideal.** An element `F` of the relation ideal in the corner
`e_j kR` is `r_j Y + ∑_{b : i ⟶ j} b Z_b` with every `Z_b` in the ideal: the relators at the other
vertices and the arrows into the other vertices are killed by `e_j`. -/
theorem exists_eq_sum_ofArrow_mul_of_mem_span_of_vertexIdempotent_mul
    (hl : ∀ v, vertexIdempotent k v * r v = r v) {j : R} {F : pathAlgebra k R}
    (hF : F ∈ TwoSidedIdeal.span (Set.range r)) (hjF : vertexIdempotent k j * F = F) :
    ∃ (Y : pathAlgebra k R) (Z : (i : R) → (i ⟶ j) → pathAlgebra k R),
      (∀ i b, Z i b ∈ TwoSidedIdeal.span (Set.range r)) ∧
        F = r j * Y + ∑ i, ∑ b : i ⟶ j, ofArrow b * Z i b := by
  classical
  obtain ⟨Y, Z, hZ, rfl⟩ := exists_eq_sum_mul_add_sum_ofArrow_mul_of_mem_span hl hF
  refine ⟨Y j, fun i b => Z ⟨i, j, b⟩, fun i b => hZ _, ?_⟩
  rw [← hjF]
  simp only [mul_add, Finset.mul_sum, ← mul_assoc, vertexIdempotent_mul_eq_ite hl,
    vertexIdempotent_mul_ofArrow, ite_mul, zero_mul, Finset.sum_ite_eq, Finset.mem_univ,
    ite_true]
  congr 1
  rw [Fintype.sum_sigma]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [Fintype.sum_sigma, Finset.sum_eq_single j]
  · simp
  · intro t _ ht
    exact Finset.sum_eq_zero fun b _ => by simp [ht]
  · simp

/-- **The relations among the arrows into a vertex are generated by its relator.** Let
`r_j = ∑_{b : i ⟶ j} b c_b`. If `∑_b b y_b` lies in the relation ideal `I`, then one element `Y`
gives `e_i y_b ≡ e_i c_b Y` modulo `I` for every arrow `b : i ⟶ j`.

Read in `A = kR / I`, this is exactness of `A ⟶ ⨁_b e_i A ⟶ e_j A`, `y ↦ (e_i c_b y)_b` and
`(z_b) ↦ ∑_b b z_b`, at its middle term. The element `Y` is arbitrary in `kR`; it may be taken in
`e_j kR` only when `c_b e_j = c_b` for every `b`. -/
theorem exists_sub_mul_mem_span_of_sum_ofArrow_mul_mem_span
    (hl : ∀ v, vertexIdempotent k v * r v = r v) {j : R}
    {c : (i : R) → (i ⟶ j) → pathAlgebra k R} (hrj : r j = ∑ i, ∑ b : i ⟶ j, ofArrow b * c i b)
    {y : (i : R) → (i ⟶ j) → pathAlgebra k R}
    (hy : ∑ i, ∑ b : i ⟶ j, ofArrow b * y i b ∈ TwoSidedIdeal.span (Set.range r)) :
    ∃ Y : pathAlgebra k R, ∀ i b, vertexIdempotent k i * y i b -
      vertexIdempotent k i * c i b * Y ∈ TwoSidedIdeal.span (Set.range r) := by
  classical
  have hj : vertexIdempotent k j * ∑ i, ∑ b : i ⟶ j, ofArrow b * y i b =
      ∑ i, ∑ b : i ⟶ j, ofArrow b * y i b := by
    simp only [Finset.mul_sum, ← mul_assoc, vertexIdempotent_mul_ofArrow, ite_true]
  obtain ⟨Y, Z, hZ, hF⟩ :=
    exists_eq_sum_ofArrow_mul_of_mem_span_of_vertexIdempotent_mul hl hy hj
  refine ⟨Y, fun i b => ?_⟩
  -- Both sides of `hF` are last-arrow decompositions, so their coefficients agree up to `eᵢ`.
  have h0 : ∑ i, ∑ b : i ⟶ j, ofArrow b * (y i b - c i b * Y - Z i b) = 0 := by
    simp only [mul_sub, Finset.sum_sub_distrib, hF, hrj, Finset.sum_mul, mul_assoc]
    abel
  have h := sum_ofArrow_mul_eq_zero_iff.1 h0 i b
  rw [mul_sub, mul_sub, sub_eq_zero, ← mul_assoc] at h
  rw [h]
  exact TwoSidedIdeal.mul_mem_left _ _ _ (hZ i b)

end Decomposition

end PathAlgebra

end TauCeti
