/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.CliffordAlgebra.Spin.SpinorNorm.Basic
public import TauCeti.LinearAlgebra.QuadraticForm.Representation
public import Mathlib.Algebra.Group.Pointwise.Set.Basic
import Mathlib.GroupTheory.Index
import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic

/-!
# The range of the spinor norm

On a finite-dimensional nondegenerate quadratic space in characteristic different from two, the
special orthogonal group is generated by products of two reflections, and the reflection pair
`τ_v τ_w` has spinor norm `[Q v · Q w]`. Hence the image of the spinor norm on `SO(Q)` is the
subgroup of square classes generated by the products of two nonzero values of `Q`. This
reduces the special orthogonal column of a spinor-norm calculation to the value set of the form.

On a nonzero space the special orthogonal group has index two in the orthogonal group.
Consequently the orthogonal spinor-norm image is generated by the special orthogonal image and
the class of any anisotropic reflection.
This reduces the orthogonal column of a local spinor-norm calculation to the special orthogonal
column and one value of the quadratic form.

Since the image of `Spin(Q) → SO(Q)` is the kernel of the spinor norm, the same generators decide
when that map is surjective on `K`-points: exactly when every product of two represented units is a
square. For a form representing `1` this says that every represented unit is a square.

## Main results

* `CliffordAlgebra.range_spinorNorm_eq_closure`: the image of the spinor norm on `SO(Q)` is
  generated by the square classes of products of two represented units.
* `CliffordAlgebra.spinToSpecialOrthogonal_surjective_iff_isSquare_mul`: `Spin(Q) → SO(Q)` is
  surjective exactly when every product of two represented units is a square.
* `CliffordAlgebra.spinToSpecialOrthogonal_surjective_iff_isSquare_of_one_mem`: for a form
  representing `1`, it is surjective exactly when every represented unit is a square.
* `CliffordAlgebra.spinorNorm_range_orthogonal_eq_sup`: the image on `O(Q)` is the image on
  `SO(Q)` joined with the class of one anisotropic value.

## References

O. T. O'Meara, *Introduction to Quadratic Forms*, §55.
-/

public section

namespace CliffordAlgebra

open TauCeti QuadraticMap

universe u v

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V]
  [FiniteDimensional K V] [Invertible (2 : K)]

open scoped Pointwise in
/-- The image of the spinor norm on `SO(Q)` is generated by the square classes of the products
`Q v · Q w` of two represented units. -/
theorem range_spinorNorm_eq_closure (Q : QuadraticForm K V) (hQ : Q.Nondegenerate) :
    (spinorNorm Q hQ).range =
      Subgroup.closure (squareClassHom '' (unitValueSet Q * unitValueSet Q)) := by
  have hval (u : V) [Invertible (Q u)] : unitOfInvertible (Q u) ∈ unitValueSet Q :=
    mem_unitValueSet.mpr ((represents_iff _ _).mpr ⟨u, rfl⟩)
  apply le_antisymm
  · -- Every element of `SO(Q)` is a product of reflection pairs, each of which has spinor norm
    -- in the closure; pull the closure back to a submonoid of `V ≃ₗ[K] V`.
    let H := Subgroup.closure (squareClassHom '' (unitValueSet Q * unitValueSet Q))
    let M : Submonoid (V ≃ₗ[K] V) :=
      ((H.comap (spinorNorm Q hQ)).map (specialOrthogonalGroup Q).subtype).toSubmonoid
    have hM := specialOrthogonalGroup_le_of_reflection_mul_mem Q hQ M fun v w _ _ ↦ by
      refine ⟨reflectionPairSpecialOrthogonal Q v w, ?_, ?_⟩
      · rw [SetLike.mem_coe, Subgroup.mem_comap, Q.spinorNorm_reflectionPairSpecialOrthogonal hQ]
        exact Subgroup.subset_closure
          (Set.mem_image_of_mem _ (Set.mul_mem_mul (hval v) (hval w)))
      · exact LinearEquiv.ext fun x ↦ by simp
    rintro _ ⟨g, rfl⟩
    obtain ⟨g', hg', hgg'⟩ := hM g.2
    rwa [Subtype.ext hgg'] at hg'
  · refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨_, ⟨a, ha, b, hb, rfl⟩, rfl⟩
    obtain ⟨v, hv⟩ := (represents_iff _ _).mp (mem_unitValueSet.mp ha)
    obtain ⟨w, hw⟩ := (represents_iff _ _).mp (mem_unitValueSet.mp hb)
    let _ : Invertible (Q v) := invertibleOfNonzero (hv ▸ a.ne_zero)
    let _ : Invertible (Q w) := invertibleOfNonzero (hw ▸ b.ne_zero)
    refine ⟨reflectionPairSpecialOrthogonal Q v w, ?_⟩
    rw [Q.spinorNorm_reflectionPairSpecialOrthogonal hQ]
    congr 2 <;> exact Units.ext ‹_›

open scoped Pointwise in
/-- **Surjectivity of `Spin(Q) → SO(Q)` on `K`-points.** The Spin action on the special orthogonal
group of a finite-dimensional nondegenerate quadratic space is surjective exactly when the product
of any two units represented by `Q` is a square. -/
theorem spinToSpecialOrthogonal_surjective_iff_isSquare_mul (Q : QuadraticForm K V)
    (hQ : Q.Nondegenerate) :
    Function.Surjective (spinToSpecialOrthogonal Q) ↔
      ∀ a ∈ unitValueSet Q, ∀ b ∈ unitValueSet Q, IsSquare (a * b) := by
  rw [← MonoidHom.range_eq_top, range_spinToSpecialOrthogonal_eq_ker_spinorNorm Q hQ]
  have hgen : ∀ x, x ∈ (spinorNorm Q hQ).range ↔
      x ∈ Subgroup.closure (squareClassHom '' (unitValueSet Q * unitValueSet Q)) := fun x ↦ by
    rw [range_spinorNorm_eq_closure Q hQ]
  have hsc (x : Kˣ) : squareClassHom x = 1 ↔ IsSquare x := by
    rw [← MonoidHom.mem_ker, ker_squareClassHom, Subgroup.mem_square]
  constructor
  · -- Each generator `[a b]` is the spinor norm of some proper isometry, which lies in the kernel.
    intro htop a ha b hb
    obtain ⟨g, hg⟩ := (hgen _).2 (Subgroup.subset_closure
      (Set.mem_image_of_mem squareClassHom (Set.mul_mem_mul ha hb)))
    rw [← hsc, ← hg, ← MonoidHom.mem_ker, htop]
    exact Subgroup.mem_top g
  · -- If every generator is trivial, so is the whole image of the spinor norm.
    intro hsq
    refine eq_top_iff.2 fun g _ ↦ ?_
    have hle : Subgroup.closure (squareClassHom '' (unitValueSet Q * unitValueSet Q)) ≤ ⊥ := by
      rw [Subgroup.closure_le]
      rintro _ ⟨_, ⟨a, ha, b, hb, rfl⟩, rfl⟩
      exact (hsc _).2 (hsq a ha b hb)
    exact hle ((hgen _).1 ⟨g, rfl⟩)

/-- For a finite-dimensional nondegenerate quadratic form representing `1`, the Spin action on
the special orthogonal group is surjective exactly when every unit represented by `Q` is a
square. -/
theorem spinToSpecialOrthogonal_surjective_iff_isSquare_of_one_mem (Q : QuadraticForm K V)
    (hQ : Q.Nondegenerate) (h1 : 1 ∈ unitValueSet Q) :
    Function.Surjective (spinToSpecialOrthogonal Q) ↔ ∀ a ∈ unitValueSet Q, IsSquare a := by
  rw [spinToSpecialOrthogonal_surjective_iff_isSquare_mul Q hQ]
  exact ⟨fun h a ha ↦ by simpa using h a ha 1 h1,
    fun h a ha b hb ↦ (h a ha).mul (h b hb)⟩

/-- The image of the spinor norm on `O(Q)` is generated by its image on `SO(Q)` and the square
class of the norm of any anisotropic vector. -/
theorem spinorNorm_range_orthogonal_eq_sup (Q : QuadraticForm K V)
    (hQ : Q.Nondegenerate) (v : V) [Invertible (Q v)] :
    (orthogonalSpinorNorm Q hQ).range =
      (spinorNorm Q hQ).range ⊔
        Subgroup.zpowers (squareClassHom (unitOfInvertible (Q v))) := by
  have hv : v ≠ 0 := by
    intro he
    have hzero : Q v = 0 := by rw [he]; simp
    exact Invertible.ne_zero (Q v) hzero
  let _ : Nontrivial V := nontrivial_of_ne v 0 hv
  let r : TauCeti.QuadraticMap.orthogonalGroup Q := reflectionOrthogonal Q v
  have hreflection : orthogonalSpinorNorm Q hQ r =
      squareClassHom (unitOfInvertible (Q v)) :=
    orthogonalSpinorNorm_reflectionOrthogonal Q hQ v
  have hso (g : TauCeti.QuadraticMap.orthogonalGroup Q)
      (hg : g ∈ specialOrthogonalWithin Q) :
      orthogonalSpinorNorm Q hQ g ∈ (spinorNorm Q hQ).range := by
    have hg' : g ∈ (specialOrthogonalToOrthogonal Q).range := by
      simpa only [range_specialOrthogonalToOrthogonal] using hg
    obtain ⟨s, hs⟩ := hg'
    refine ⟨s, ?_⟩
    rw [spinorNorm_apply, hs]
  have hneg : (-1 : Kˣ) ≠ 1 := by
    intro h
    have h' : (-1 : K) = 1 := congrArg Units.val h
    exact NeZero.ne (2 : K) (by linear_combination -h')
  have hrnot : r ∉ specialOrthogonalWithin Q := by
    intro hr
    have hdet : orthogonalDet Q r = 1 := by
      rw [orthogonalDet_apply]
      exact mem_specialOrthogonalWithin_iff.mp hr
    exact hneg (by simpa only [r, orthogonalDet_reflectionOrthogonal] using hdet)
  have hindex : (specialOrthogonalWithin Q).index = 2 :=
    index_specialOrthogonalWithin hQ
  apply le_antisymm
  · rintro x ⟨g, rfl⟩
    by_cases hg : g ∈ specialOrthogonalWithin Q
    · exact Subgroup.mem_sup_left (hso g hg)
    · have hgr : g * r ∈ specialOrthogonalWithin Q := by
        rw [Subgroup.mul_mem_iff_of_index_two hindex]
        exact iff_of_false hg hrnot
      have hrr : r * r = 1 := reflectionOrthogonal_mul_self Q v
      have hdecomp : g = (g * r) * r := by rw [mul_assoc, hrr, mul_one]
      rw [hdecomp, map_mul, hreflection]
      exact Subgroup.mul_mem_sup (hso (g * r) hgr) (Subgroup.mem_zpowers _)
  · refine sup_le ?_ ?_
    · rintro x ⟨s, rfl⟩
      exact ⟨specialOrthogonalToOrthogonal Q s, (spinorNorm_apply Q hQ s).symm⟩
    · apply Subgroup.zpowers_le.mpr
      rw [← hreflection]
      exact ⟨r, rfl⟩

end CliffordAlgebra
