/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.WorkedExamples.Cubic23.Invariants
import Mathlib.NumberTheory.NumberField.Ideal.KummerDedekind
import Mathlib.RingTheory.DedekindDomain.Factorization

/-!
# The prime 23 in the cubic field of discriminant −23

For an integral generator `θ` with minimal polynomial `X³ - X² + 1`, reduction modulo `23`
has a double root at `16` and a simple root at `15`. Since `ℤ[θ]` is the full ring of integers,
Kummer–Dedekind identifies the two primes above `23`, their ramification indices and their
residue degrees. In particular, `23` has splitting type `((2, 1), (1, 1))`.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter I, §8, for Kummer–Dedekind.
-/

public section

open Polynomial NumberField NumberField.Ideal UniqueFactorizationMonoid
open scoped NumberField

namespace TauCeti.NumberField.Cubic23

private instance : Fact (Nat.Prime 23) := ⟨by decide⟩

/-- Over `ZMod 23`, the defining cubic factors with a double root at `16`. -/
@[simp] theorem cubic_factorization_mod_twenty_three :
    (X ^ 3 - X ^ 2 + 1 : (ZMod 23)[X]) = (X - C 16) ^ 2 * (X - C 15) := by
  -- The numeral coercions in the product are definitionally equal to the `C` expressions,
  -- but rewriting with `C_eq_natCast` needs the polynomial numerals exposed explicitly.
  rw [show C (16 : ZMod 23) = (16 : (ZMod 23)[X]) from C_eq_natCast 16,
    show C (15 : ZMod 23) = (15 : (ZMod 23)[X]) from C_eq_natCast 15]
  have h23 : (23 : (ZMod 23)[X]) = 0 := CharP.cast_eq_zero _ _
  linear_combination (167 - 32 * X + 2 * X ^ 2) * h23

section Reduction

variable {K : Type*} [Field K] {θ : 𝓞 K}
  (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)

include hmin

/-- Modulo `23`, the minimal polynomial has a double root at `16` and a simple root at `15`. -/
theorem minpoly_mod_twenty_three :
    (minpoly ℤ θ).map (Int.castRingHom (ZMod 23)) =
      (X - C 16) ^ 2 * (X - C 15) := by
  simpa only [hmin, Polynomial.map_add, Polynomial.map_sub, Polynomial.map_pow,
    Polynomial.map_X, Polynomial.map_one] using cubic_factorization_mod_twenty_three

private theorem normalizedFactors_mod_twenty_three :
    normalizedFactors ((minpoly ℤ θ).map (Int.castRingHom (ZMod 23))) =
      {X - C 16, X - C 16, X - C 15} := by
  classical
  rw [minpoly_mod_twenty_three hmin,
    normalizedFactors_mul (pow_ne_zero _ (X_sub_C_ne_zero 16)) (X_sub_C_ne_zero 15),
    (irreducible_X_sub_C (16 : ZMod 23)).normalizedFactors_pow,
    normalizedFactors_irreducible (irreducible_X_sub_C (15 : ZMod 23))]
  simp [(monic_X_sub_C (16 : ZMod 23)).normalize_eq_self,
    (monic_X_sub_C (15 : ZMod 23)).normalize_eq_self]

private theorem monicFactorsMod_twenty_three :
    RingOfIntegers.monicFactorsMod θ 23 = {X - C 16, X - C 15} := by
  classical
  rw [RingOfIntegers.monicFactorsMod, normalizedFactors_mod_twenty_three hmin]
  simp [Multiset.toFinset_cons]

private theorem factor_sixteen_mem :
    (X - C (16 : ZMod 23)) ∈ RingOfIntegers.monicFactorsMod θ 23 := by
  rw [monicFactorsMod_twenty_three hmin]
  simp

private theorem factor_fifteen_mem :
    (X - C (15 : ZMod 23)) ∈ RingOfIntegers.monicFactorsMod θ 23 := by
  rw [monicFactorsMod_twenty_three hmin]
  simp

private theorem factor_root_multiplicity_eq_count (r : ZMod 23) :
    multiplicity (X - C r)
      ((minpoly ℤ θ).map (Int.castRingHom (ZMod 23))) =
      (normalizedFactors ((minpoly ℤ θ).map (Int.castRingHom (ZMod 23)))).count
        (X - C r) := by
  classical
  have h0 : (minpoly ℤ θ).map (Int.castRingHom (ZMod 23)) ≠ 0 := by
    rw [minpoly_mod_twenty_three hmin]
    exact mul_ne_zero (pow_ne_zero _ (X_sub_C_ne_zero 16)) (X_sub_C_ne_zero 15)
  rw [multiplicity_eq_count_normalizedFactors (irreducible_X_sub_C r) h0,
    (monic_X_sub_C r).normalize_eq_self]

private theorem factor_sixteen_multiplicity :
    multiplicity (X - C (16 : ZMod 23))
      ((minpoly ℤ θ).map (Int.castRingHom (ZMod 23))) = 2 := by
  rw [factor_root_multiplicity_eq_count hmin, normalizedFactors_mod_twenty_three hmin]
  have hne : (16 : ZMod 23) ≠ 15 := by decide
  simp [hne]

private theorem factor_fifteen_multiplicity :
    multiplicity (X - C (15 : ZMod 23))
      ((minpoly ℤ θ).map (Int.castRingHom (ZMod 23))) = 1 := by
  rw [factor_root_multiplicity_eq_count hmin, normalizedFactors_mod_twenty_three hmin]
  have hne : (15 : ZMod 23) ≠ 16 := by decide
  simp [hne]

end Reduction

section Primes

variable {K : Type*} [Field K] {θ : 𝓞 K}

/-- The ideal generated by `23` and `θ - 16`. -/
def primeSixteen : Ideal (𝓞 K) := Ideal.span {(23 : 𝓞 K), θ - 16}

/-- The ideal generated by `23` and `θ - 15`. -/
def primeFifteen : Ideal (𝓞 K) := Ideal.span {(23 : 𝓞 K), θ - 15}

end Primes

section KummerDedekind

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}
  (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
  (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)

include hmin hgen

private theorem not_dvd_exponent : ¬ 23 ∣ RingOfIntegers.exponent θ := by
  have h : RingOfIntegers.exponent θ = 1 :=
    RingOfIntegers.exponent_eq_one_iff.mpr (adjoin_eq_top hmin hgen)
  rw [h]
  norm_num

private theorem primeRoot_eq_symm (r : ℕ)
    (hr : (X - C (r : ZMod 23)) ∈ RingOfIntegers.monicFactorsMod θ 23) :
    Ideal.span {(23 : 𝓞 K), θ - r} =
      ((primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)).symm
        ⟨X - C (r : ZMod 23), hr⟩ : Ideal (𝓞 K)) := by
  have hmap : ((X - C (r : ℤ)) : ℤ[X]).map (Int.castRingHom (ZMod 23)) =
      X - C (r : ZMod 23) := by
    simp only [Polynomial.map_sub, Polynomial.map_X, Polynomial.map_C,
      Int.coe_castRingHom, Int.cast_natCast]
  have hf : (X - C (r : ℤ)).map (Int.castRingHom (ZMod 23)) ∈
      RingOfIntegers.monicFactorsMod θ 23 := by
    rw [hmap]
    exact hr
  have h := primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    (not_dvd_exponent hmin hgen) hf
  have hr' : (algebraMap ℤ (𝓞 K)) (r : ℤ) = (r : 𝓞 K) := by simp
  have h23 : (algebraMap ℤ (𝓞 K)) (23 : ℤ) = (23 : 𝓞 K) := by simp
  have hnat : ((23 : ℕ) : 𝓞 K) = (23 : 𝓞 K) := by norm_num
  simpa only [hmap, map_sub, aeval_X, aeval_C, hr', h23, hnat] using h.symm

private theorem primeSixteen_eq_symm :
    primeSixteen (θ := θ) =
      ((primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)).symm
        ⟨X - C 16, factor_sixteen_mem hmin⟩ : Ideal (𝓞 K)) := by
  exact primeRoot_eq_symm hmin hgen 16 (factor_sixteen_mem hmin)

private theorem primeFifteen_eq_symm :
    primeFifteen (θ := θ) =
      ((primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)).symm
        ⟨X - C 15, factor_fifteen_mem hmin⟩ : Ideal (𝓞 K)) := by
  exact primeRoot_eq_symm hmin hgen 15 (factor_fifteen_mem hmin)

/-- The ideal attached to the double root is prime. -/
theorem isPrime_primeSixteen : (primeSixteen (θ := θ)).IsPrime := by
  rw [primeSixteen_eq_symm hmin hgen]
  exact ((primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)).symm
    ⟨X - C 16, factor_sixteen_mem hmin⟩).property.1

/-- The ideal attached to the simple root is prime. -/
theorem isPrime_primeFifteen : (primeFifteen (θ := θ)).IsPrime := by
  rw [primeFifteen_eq_symm hmin hgen]
  exact ((primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)).symm
    ⟨X - C 15, factor_fifteen_mem hmin⟩).property.1

/-- The double-root prime lies above `23`. -/
theorem liesOver_primeSixteen :
    (primeSixteen (θ := θ)).LiesOver (Ideal.span {(23 : ℤ)}) := by
  rw [primeSixteen_eq_symm hmin hgen]
  exact ((primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)).symm
    ⟨X - C 16, factor_sixteen_mem hmin⟩).property.2

/-- The simple-root prime lies above `23`. -/
theorem liesOver_primeFifteen :
    (primeFifteen (θ := θ)).LiesOver (Ideal.span {(23 : ℤ)}) := by
  rw [primeFifteen_eq_symm hmin hgen]
  exact ((primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)).symm
    ⟨X - C 15, factor_fifteen_mem hmin⟩).property.2

/-- The prime from the double root has ramification index two. -/
theorem primeSixteen_ramificationIdx :
    (primeSixteen (θ := θ)).ramificationIdx ℤ = 2 := by
  rw [primeSixteen_eq_symm hmin hgen]
  rw [ramificationIdx_primesOverSpanEquivMonicFactorsMod_symm_apply'
    (not_dvd_exponent hmin hgen) (factor_sixteen_mem hmin)]
  exact factor_sixteen_multiplicity hmin

/-- The prime from the simple root has ramification index one. -/
theorem primeFifteen_ramificationIdx :
    (primeFifteen (θ := θ)).ramificationIdx ℤ = 1 := by
  rw [primeFifteen_eq_symm hmin hgen]
  rw [ramificationIdx_primesOverSpanEquivMonicFactorsMod_symm_apply'
    (not_dvd_exponent hmin hgen) (factor_fifteen_mem hmin)]
  exact factor_fifteen_multiplicity hmin

/-- The prime from the double root has residue degree one. -/
theorem primeSixteen_inertiaDeg :
    (primeSixteen (θ := θ)).inertiaDeg ℤ = 1 := by
  rw [primeSixteen_eq_symm hmin hgen]
  rw [inertiaDeg_primesOverSpanEquivMonicFactorsMod_symm_apply'
    (not_dvd_exponent hmin hgen) (factor_sixteen_mem hmin)]
  simp

/-- The prime from the simple root has residue degree one. -/
theorem primeFifteen_inertiaDeg :
    (primeFifteen (θ := θ)).inertiaDeg ℤ = 1 := by
  rw [primeFifteen_eq_symm hmin hgen]
  rw [inertiaDeg_primesOverSpanEquivMonicFactorsMod_symm_apply'
    (not_dvd_exponent hmin hgen) (factor_fifteen_mem hmin)]
  simp

/-- The two roots yield different primes above `23`. -/
theorem primeSixteen_ne_primeFifteen :
    primeSixteen (θ := θ) ≠ primeFifteen (θ := θ) := by
  intro h
  rw [primeSixteen_eq_symm hmin hgen, primeFifteen_eq_symm hmin hgen] at h
  let e := primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)
  have heq : e.symm ⟨X - C 16, factor_sixteen_mem hmin⟩ =
      e.symm ⟨X - C 15, factor_fifteen_mem hmin⟩ := by
    apply Subtype.ext
    exact h
  have hf := congrArg Subtype.val (e.symm.injective heq)
  have hne : (16 : ZMod 23) ≠ 15 := by decide
  exact hne (by simpa using congrArg (fun f : (ZMod 23)[X] => f.eval 0) hf)

/-- Exactly the primes from roots `16` and `15` lie above `23`. -/
theorem primesOver_twenty_three :
    (Ideal.span {(23 : ℤ)}).primesOver (𝓞 K) =
      {primeSixteen (θ := θ), primeFifteen (θ := θ)} := by
  classical
  let e := primesOverSpanEquivMonicFactorsMod (not_dvd_exponent hmin hgen)
  ext P
  constructor
  · intro hP
    have hf : (e ⟨P, hP⟩).1 ∈
        ({X - C (16 : ZMod 23), X - C (15 : ZMod 23)} :
          Finset ((ZMod 23)[X])) := by
      rw [← monicFactorsMod_twenty_three hmin]
      exact (e ⟨P, hP⟩).2
    simp only [Finset.mem_insert, Finset.mem_singleton] at hf
    rcases hf with hf | hf
    · have heq : e ⟨P, hP⟩ = ⟨X - C 16, factor_sixteen_mem hmin⟩ :=
        Subtype.ext hf
      have hp := congrArg (fun q => (e.symm q : Ideal (𝓞 K))) heq
      exact Set.mem_insert_iff.mpr (Or.inl (by simpa [e, primeSixteen_eq_symm hmin hgen] using hp))
    · have heq : e ⟨P, hP⟩ = ⟨X - C 15, factor_fifteen_mem hmin⟩ :=
        Subtype.ext hf
      have hp := congrArg (fun q => (e.symm q : Ideal (𝓞 K))) heq
      exact Set.mem_insert_iff.mpr (Or.inr (Set.mem_singleton_iff.mpr
        (by simpa [e, primeFifteen_eq_symm hmin hgen] using hp)))
  · intro hP
    rcases Set.mem_insert_iff.mp hP with hP | hP
    · subst P
      exact ⟨isPrime_primeSixteen hmin hgen, liesOver_primeSixteen hmin hgen⟩
    · have hP := Set.mem_singleton_iff.mp hP
      subst P
      exact ⟨isPrime_primeFifteen hmin hgen, liesOver_primeFifteen hmin hgen⟩

/-- There are exactly two primes above `23`. -/
theorem ncard_primesOver_twenty_three :
    ((Ideal.span {(23 : ℤ)}).primesOver (𝓞 K)).ncard = 2 := by
  rw [primesOver_twenty_three hmin hgen]
  simp [primeSixteen_ne_primeFifteen hmin hgen]

/-- The factorization of `23` in the full integer ring is `𝔭₁₆² 𝔭₁₅`. -/
theorem map_span_twenty_three_eq :
    (Ideal.span {(23 : ℤ)}).map (algebraMap ℤ (𝓞 K)) =
      primeSixteen (θ := θ) ^ 2 * primeFifteen (θ := θ) := by
  classical
  let _ : (Ideal.span {(23 : ℤ)}).IsMaximal := Int.ideal_span_isMaximal_of_prime 23
  have h0 : (Ideal.span {(23 : ℤ)}) ≠ (⊥ : Ideal ℤ) := by simp
  rw [Ideal.map_algebraMap_eq_finsetProd_pow h0]
  have hfin : ((Ideal.span {(23 : ℤ)}).primesOver (𝓞 K)).toFinset =
      {primeSixteen (θ := θ), primeFifteen (θ := θ)} := by
    ext P
    simp only [Set.mem_toFinset, primesOver_twenty_three hmin hgen,
      Set.mem_insert_iff, Set.mem_singleton_iff, Finset.mem_insert, Finset.mem_singleton]
  rw [hfin]
  simp [primeSixteen_ne_primeFifteen hmin hgen, primeSixteen_ramificationIdx hmin hgen,
    primeFifteen_ramificationIdx hmin hgen]

end KummerDedekind

end TauCeti.NumberField.Cubic23

end
