/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Map.Basic
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MapsInfinity
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.FunctionField

/-!
# Base change of an isogeny

An isogeny is a coordinate pullback `W₂.CoordinateRing →ₐ[F] W₁.FunctionField` sending the point
at infinity to the point at infinity. This file carries one along a homomorphism `f : F →+* K` of
the base field, producing an isogeny `W₁.map f → W₂.map f`, and records that the construction is
functorial in both arguments.

The mechanism is the coordinate-ring universal property in `Affine/Eval.lean`. The images of the
two coordinate functions under a pullback are a point of `W₂` over `W₁.FunctionField`, and
`WeierstrassCurve.Affine.CoordinateRing.evalAlgHom` constructs a pullback from such a point. A
point of a curve is carried along any ring homomorphism by `WeierstrassCurve.Affine.Equation.map`,
so the base-changed pullback is the point `(f^*x, f^*y)`, read through the identification
`WeierstrassCurve.Affine.FunctionField.map_map_algebraMap` of the two ways of getting `W₂` over
`K(W₁.map f)`. No tensor product appears, and nothing about `W₂.CoordinateRing` beyond its
being generated by the two coordinates is used.

Pointedness survives for the same reason it holds: `MapsInfinity` is integrality of `F[W₁]` over
the pulled-back `F[W₂]`, an integral dependence is a monic polynomial identity, and a ring
homomorphism carries such an identity to another one. The two coordinates therefore stay integral,
and `WeierstrassCurve.Affine.algebraMap_mem_adjoin_genericX_genericY` — the coordinate ring,
inside the function field, lies in the subalgebra they generate — propagates that to the whole
coordinate ring.

The base map is an arbitrary homomorphism of fields, so `f = algebraMap F K` is base change along
a field extension, while `f = σ` an automorphism is the semilinear transport of an isogeny to the
conjugate isogeny `W₁.map σ → W₂.map σ`. That transport is the raw material for a Galois action on
isogenies rather than an action itself: it lands on the conjugate curves, so an action would first
need the identifications `Wᵢ.map σ = Wᵢ` available for curves defined over the fixed field. Both
readings are uses of one construction.

## What is not here

**The degree.** `deg (φ.map f) = deg φ` is not a formal consequence of anything above: it compares
`[K(W₁.map f) : (φ.map f)^*K(W₂.map f)]` with `[F(W₁) : φ^*F(W₂)]`, which needs `F(W₁)` and `K` to
be linearly disjoint over `F`. It is `TauCeti.Isogeny.degree_map`, in
`Isogeny/BaseChange/Degree.lean`. The invariance of the separable and inseparable degrees is not
proved there.

## Main definitions

* `TauCeti.CoordinatePullback.map`: the base-changed coordinate pullback.
* `TauCeti.Isogeny.map`: the base-changed isogeny.

## Main results

* `TauCeti.CoordinatePullback.map_coordinateRingMap`: the defining commuting square — the
  base-changed pullback
  agrees with the original one after `CoordinateRing.map` on the source and
  `FunctionField.map` on the target.
* `TauCeti.CoordinatePullback.MapsInfinity.map`: pointedness survives base change, which is what
  makes `Isogeny.map` well defined.
* `TauCeti.Isogeny.map_fieldPullback_map`: the pointwise commuting square at the level of function
  fields, where an isogeny is usually met; `map_fieldPullback_comp_map` is its homomorphism-level
  companion.
* `TauCeti.Isogeny.id_map`, `TauCeti.Isogeny.comp_map`: base change preserves the identity
  isogeny and composition.
* `TauCeti.Isogeny.map_id`, `TauCeti.Isogeny.map_map`: functoriality in the base map itself.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 0.5** (README:369). Its first milestone
(README:376-378) asks for "base change of Weierstrass equations, coordinate rings, function
fields, points, and isogenies, compatible with identity, composition, degree, separability,
`MapsInfinity`, duals, and induced point maps"; this file is the isogeny entry, with the identity,
composition and `MapsInfinity` clauses. Layer 1's dual-isogeny milestone (README:529-531) opens
"for the **separable** part, base change to `Kˢᵉᵖ`, where `Kˢᵉᵖ(W₁)/φ^*Kˢᵉᵖ(W₂)` **is** Galois",
and `Isogeny.map` is the arrow that base change names there.

Mathlib's `WeierstrassCurve.map_id` and `WeierstrassCurve.map_map` are proved by `rfl`. Their
affine specialisations are therefore definitional equalities too, so the identity and composition
laws below need no explicit transports between mapped curves.
-/

public section

open Polynomial WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace TauCeti

variable {F K L : Type*} [Field F] [Field K] [Field L]
variable {W₁ W₂ W₃ : WeierstrassCurve.Affine F}

namespace CoordinatePullback

/-- **The coordinates of a pullback, carried along `f`, are a point of `W₂.map f`** over the
function field of `W₁.map f`. This is `CoordinateRing.equation_of_algHom` pushed through
`WeierstrassCurve.Affine.FunctionField.map`. -/
private theorem equation_map (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    ((W₂.map f).map (algebraMap K (W₁.map f).FunctionField)).Equation
      (FunctionField.map W₁ f (φ (AdjoinRoot.of W₂.polynomial X)))
      (FunctionField.map W₁ f (φ (AdjoinRoot.root W₂.polynomial))) := by
  rw [← FunctionField.map_map_algebraMap]
  exact (CoordinateRing.equation_of_algHom φ).map _

/-- **Base change of a coordinate pullback** along a homomorphism `f` of the base field: the
pullback whose two coordinate functions are those of `φ`, carried along `f`. -/
noncomputable def map (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    CoordinatePullback (W₁.map f) (W₂.map f) :=
  CoordinateRing.evalAlgHom (equation_map φ f)

/-- The base-changed pullback sends the class of `X` to the carried `x`-coordinate. -/
@[simp]
theorem map_of_X (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    φ.map f (AdjoinRoot.of (W₂.map f).polynomial X) =
      FunctionField.map W₁ f (φ (AdjoinRoot.of W₂.polynomial X)) :=
  CoordinateRing.evalAlgHom_of_X ..

/-- The base-changed pullback sends the class of `Y` to the carried `y`-coordinate. -/
@[simp]
theorem map_root (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    φ.map f (AdjoinRoot.root (W₂.map f).polynomial) =
      FunctionField.map W₁ f (φ (AdjoinRoot.root W₂.polynomial)) :=
  CoordinateRing.evalAlgHom_root ..

/-- **The defining commuting square of the base change.** Carrying a function of `W₂` along `f`
and then pulling it back is pulling it back and then carrying it along `f`. -/
@[simp]
theorem map_coordinateRingMap (φ : CoordinatePullback W₁ W₂) (f : F →+* K)
    (z : W₂.CoordinateRing) :
    φ.map f (CoordinateRing.map W₂ f z) = FunctionField.map W₁ f (φ z) := by
  induction z using AdjoinRoot.induction_on with
  | ih p =>
    have hcoeff : (p.map (mapRingHom f)).map
          (mapRingHom (algebraMap K (W₁.map f).FunctionField)) =
        (p.map (mapRingHom (algebraMap F W₁.FunctionField))).map
          (mapRingHom (FunctionField.map W₁ f)) := by
      rw [Polynomial.map_map, Polynomial.map_map, mapRingHom_comp, mapRingHom_comp,
        FunctionField.map_comp_algebraMap]
    rw [CoordinateRing.map_mk, CoordinateRing.algHom_mk_eq_evalEval,
      CoordinateRing.algHom_mk_eq_evalEval, map_of_X, map_root, hcoeff,
      map_mapRingHom_evalEval]

/-- **The commuting square as an equality of ring homomorphisms.** -/
theorem map_comp_coordinateRingMap (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    (φ.map f).toRingHom.comp (CoordinateRing.map W₂ f) =
      (FunctionField.map W₁ f).comp φ.toRingHom :=
  RingHom.ext <| map_coordinateRingMap φ f

/-- **Base change fixes the identity coordinate pullback.** -/
@[simp]
theorem id_map (W : WeierstrassCurve.Affine F) (f : F →+* K) :
    (id W).map f = id (W.map f) := by
  apply CoordinateRing.algHom_ext
  · rw [map_of_X, id_apply, id_apply, FunctionField.map_algebraMap_coordinateRing,
      CoordinateRing.map_of_X]
  · rw [map_root, id_apply, id_apply, FunctionField.map_algebraMap_coordinateRing,
      CoordinateRing.map_root]

/-- **Base change of a coordinate pullback along the identity is the original pullback.** -/
@[simp]
theorem map_id (φ : CoordinatePullback W₁ W₂) : φ.map (RingHom.id F) = φ := by
  apply CoordinateRing.algHom_ext
  · rw [map_of_X, FunctionField.map_id]
    rfl
  · rw [map_root, FunctionField.map_id]
    rfl

/-- **Base change of a coordinate pullback is functorial in the base map.** -/
@[simp]
theorem map_map (φ : CoordinatePullback W₁ W₂) (f : F →+* K) (g : K →+* L) :
    (φ.map f).map g = φ.map (g.comp f) := by
  apply CoordinateRing.algHom_ext
  · have h : ((φ.map f).map g) (AdjoinRoot.of ((W₂.map f).map g).polynomial X) =
        FunctionField.map W₁ (g.comp f) (φ (AdjoinRoot.of W₂.polynomial X)) := by
      rw [map_of_X, map_of_X, FunctionField.map_map]
    exact h.trans (map_of_X φ (g.comp f)).symm
  · have h : ((φ.map f).map g) (AdjoinRoot.root ((W₂.map f).map g).polynomial) =
        FunctionField.map W₁ (g.comp f) (φ (AdjoinRoot.root W₂.polynomial)) := by
      rw [map_root, map_root, FunctionField.map_map]
    exact h.trans (map_root φ (g.comp f)).symm

/-- **Integral dependence over the pulled-back coordinate ring survives base change.** An integral
dependence is a monic polynomial identity, and `map_comp_coordinateRingMap` carries such an
identity along `f`. -/
theorem isIntegral_map (φ : CoordinatePullback W₁ W₂) (f : F →+* K) {z : W₁.FunctionField}
    (hz : @IsIntegral W₂.CoordinateRing W₁.FunctionField _ _ φ.toRingHom.toAlgebra z) :
    @IsIntegral (W₂.map f).CoordinateRing (W₁.map f).FunctionField _ _
      (φ.map f).toRingHom.toAlgebra (FunctionField.map W₁ f z) := by
  let _ := φ.toRingHom.toAlgebra
  let _ := (φ.map f).toRingHom.toAlgebra
  apply hz.map_of_comp_eq (CoordinateRing.map W₂ f) (FunctionField.map W₁ f)
  rw [RingHom.algebraMap_toAlgebra, RingHom.algebraMap_toAlgebra]
  exact map_comp_coordinateRingMap φ f

/-- **Pointedness survives base change**: a coordinate pullback that maps infinity to infinity
still does so after base change along a homomorphism of the base field. -/
theorem MapsInfinity.map {φ : CoordinatePullback W₁ W₂} (hφ : φ.MapsInfinity) (f : F →+* K) :
    (φ.map f).MapsInfinity := by
  rw [mapsInfinity_iff_isIntegralElem_genericX]
  have h := isIntegral_map φ f ((mapsInfinity_iff_isIntegralElem_genericX φ).1 hφ)
  rwa [FunctionField.map_genericX] at h

end CoordinatePullback

namespace Isogeny

/-- **Base change of an isogeny** along a homomorphism `f` of the base field. -/
noncomputable def map (φ : Isogeny W₁ W₂) (f : F →+* K) : Isogeny (W₁.map f) (W₂.map f) where
  pullback := φ.pullback.map f
  mapsInfinity := φ.mapsInfinity.map f

@[simp]
theorem map_pullback (φ : Isogeny W₁ W₂) (f : F →+* K) :
    (φ.map f).pullback = φ.pullback.map f := (rfl)

/-- **The commuting square at the level of function fields, as an equality of ring
homomorphisms.** -/
theorem map_fieldPullback_comp_map (φ : Isogeny W₁ W₂) (f : F →+* K) :
    ((φ.map f).fieldPullback : (W₂.map f).FunctionField →+* (W₁.map f).FunctionField).comp
        (FunctionField.map W₂ f) =
      (FunctionField.map W₁ f).comp (φ.fieldPullback : W₂.FunctionField →+* W₁.FunctionField) :=
  IsFractionRing.ringHom_ext (A := W₂.CoordinateRing) fun z ↦ by
    rw [RingHom.comp_apply, RingHom.comp_apply, FunctionField.map_algebraMap_coordinateRing]
    simp

/-- **The pointwise commuting square at the level of function fields.** -/
@[simp]
theorem map_fieldPullback_map (φ : Isogeny W₁ W₂) (f : F →+* K) (z : W₂.FunctionField) :
    (φ.map f).fieldPullback (FunctionField.map W₂ f z) =
      FunctionField.map W₁ f (φ.fieldPullback z) :=
  RingHom.congr_fun (map_fieldPullback_comp_map φ f) z

/-- **Base change fixes the identity isogeny.** -/
@[simp]
theorem id_map (W : WeierstrassCurve.Affine F) (f : F →+* K) :
    (Isogeny.id W).map f = Isogeny.id (W.map f) := by
  apply Isogeny.ext
  rw [map_pullback, id_pullback, id_pullback]
  exact CoordinatePullback.id_map W f

/-- **Base change respects composition.** -/
@[simp]
theorem comp_map (ψ : Isogeny W₂ W₃) (φ : Isogeny W₁ W₂) (f : F →+* K) :
    (ψ.comp φ).map f = (ψ.map f).comp (φ.map f) := by
  refine Isogeny.ext (CoordinateRing.algHom_ext ?_ ?_) <;>
  · simp only [map_pullback, comp_pullback, AlgHom.comp_apply,
      CoordinatePullback.map_of_X, CoordinatePullback.map_root]
    exact (map_fieldPullback_map φ f _).symm

/-- **Base change along the identity is the identity.** -/
@[simp]
theorem map_id (φ : Isogeny W₁ W₂) : φ.map (RingHom.id F) = φ :=
  Isogeny.ext <| by
    rw [map_pullback]
    exact CoordinatePullback.map_id φ.pullback

/-- **Base change is functorial in the base map.** -/
@[simp]
theorem map_map (φ : Isogeny W₁ W₂) (f : F →+* K) (g : K →+* L) :
    (φ.map f).map g = φ.map (g.comp f) := by
  apply Isogeny.ext
  rw [map_pullback, map_pullback, map_pullback]
  exact CoordinatePullback.map_map φ.pullback f g

end Isogeny

end TauCeti

end
