/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.BraidWord.PDCode

/-!
# Free cancellation in braid words

The word presentation of a braid has the elementary free relation
`σ i ^ ε σ i ^ (-ε) = 1`.  This file records the relation on words, its closure under
insertion and deletion, and the invariants that the relation preserves.  The relation is the
word-level prerequisite for the second Reidemeister move on braid closures.

The list and group calculations here are the input for the diagrammatic statement that inserting
an inverse pair changes a closure by a Reidemeister-II clasp: that statement must identify the two
new crossings with the corresponding clasp in the PD-code.

## Main declarations

* `TauCeti.BraidWord.FreeCancelStep`: insertion or deletion of one adjacent inverse pair.
* `TauCeti.BraidWord.FreeCancelEquiv`: the equivalence relation generated by those steps.
* `TauCeti.BraidWord.toBraid_freeCancel` and `writhe_closure_freeCancel`: invariance of the
  represented braid and closure writhe under one step.

The closure-level crossing signs and over-pair data for an appended inverse pair are in
`TauCeti.KnotTheory.BraidWord.FreeCancellation.Reidemeister`.

The general crossing-order formula is `TauCeti.BraidWord.crossingsAt_cons_cons_same_index`
in `BraidWord.PDCode`; successor and internal-arc formulas are in `BraidWord.DoubleCrossing`.

## References

* J. Birman, *Braids, Links, and Mapping Class Groups*, Annals of Mathematics Studies 82 (1974),
  Chapter 1.
* W. B. R. Lickorish, *An Introduction to Knot Theory*, Springer GTM 175 (1997), Chapter 1.
-/

public section

namespace TauCeti

namespace BraidWord

open BraidGroup

variable {n : ℕ}

/-- One free-cancellation step inserts or deletes adjacent inverse letters in a braid word. -/
inductive FreeCancelStep : BraidWord n → BraidWord n → Prop
  | insert (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
      FreeCancelStep (u ++ v) (u ++ [(i, ε), (i, -ε)] ++ v)
  | delete (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
      FreeCancelStep (u ++ [(i, ε), (i, -ε)] ++ v) (u ++ v)

namespace FreeCancelStep

/-- A common prefix preserves a free-cancellation step. -/
theorem append_left (pre : BraidWord n) {w w' : BraidWord n} (h : FreeCancelStep w w') :
    FreeCancelStep (pre ++ w) (pre ++ w') := by
  cases h with
  | insert u v i ε =>
    simpa only [List.append_assoc] using insert (pre ++ u) v i ε
  | delete u v i ε =>
    simpa only [List.append_assoc] using delete (pre ++ u) v i ε

/-- A common suffix preserves a free-cancellation step. -/
theorem append_right {w w' : BraidWord n} (h : FreeCancelStep w w') (suf : BraidWord n) :
    FreeCancelStep (w ++ suf) (w' ++ suf) := by
  cases h with
  | insert u v i ε =>
    simpa only [List.append_assoc] using insert u (v ++ suf) i ε
  | delete u v i ε =>
    simpa only [List.append_assoc] using delete u (v ++ suf) i ε

end FreeCancelStep

/-- The equivalence relation generated by free insertion and deletion of inverse pairs. -/
def FreeCancelEquiv : BraidWord n → BraidWord n → Prop := Relation.EqvGen FreeCancelStep

namespace FreeCancelEquiv

/-- Free-cancellation equivalence is an equivalence relation. -/
theorem equivalence : Equivalence (FreeCancelEquiv (n := n)) :=
  Relation.EqvGen.is_equivalence FreeCancelStep

/-- Free-cancellation equivalence is reflexive. -/
@[refl]
theorem refl (w : BraidWord n) : FreeCancelEquiv w w := Relation.EqvGen.refl _

/-- Free-cancellation equivalence is symmetric. -/
@[symm]
theorem symm {w w' : BraidWord n} (h : FreeCancelEquiv w w') : FreeCancelEquiv w' w :=
  Relation.EqvGen.symm _ _ h

/-- Free-cancellation equivalence is transitive. -/
@[trans]
theorem trans {w w' w'' : BraidWord n} (h : FreeCancelEquiv w w')
    (h' : FreeCancelEquiv w' w'') : FreeCancelEquiv w w'' :=
  Relation.EqvGen.trans _ _ _ h h'

/-- A single free-cancellation step is a free-cancellation equivalence. -/
theorem of_step {w w' : BraidWord n} (h : FreeCancelStep w w') : FreeCancelEquiv w w' :=
  Relation.EqvGen.rel _ _ h

/-- The induction principle exposes the generated relation to closure-level consumers. -/
theorem induction {motive : BraidWord n → BraidWord n → Prop}
    (step : ∀ {w w' : BraidWord n}, FreeCancelStep w w' → motive w w')
    (refl : ∀ w : BraidWord n, motive w w)
    (symm : ∀ {w w' : BraidWord n}, FreeCancelEquiv w w' → motive w w' → motive w' w)
    (trans : ∀ {w w' w'' : BraidWord n}, FreeCancelEquiv w w' → FreeCancelEquiv w' w'' →
      motive w w' → motive w' w'' → motive w w'')
    {w w' : BraidWord n} (h : FreeCancelEquiv w w') : motive w w' := by
  induction h with
  | rel _ _ hstep => exact step hstep
  | refl w => exact refl w
  | symm _ _ hww' ih => exact symm hww' ih
  | trans _ _ _ hww' hw'w'' ih ih' => exact trans hww' hw'w'' ih ih'

/-- A common prefix preserves free-cancellation equivalence. -/
theorem append_left (pre : BraidWord n) {w w' : BraidWord n} (h : FreeCancelEquiv w w') :
    FreeCancelEquiv (pre ++ w) (pre ++ w') :=
  induction (motive := fun u v ↦ FreeCancelEquiv (pre ++ u) (pre ++ v))
    (fun h ↦ of_step (h.append_left pre)) (fun _ ↦ refl _)
    (fun _ ih ↦ ih.symm) (fun _ _ ih ih' ↦ ih.trans ih') h

/-- A common suffix preserves free-cancellation equivalence. -/
theorem append_right {w w' : BraidWord n} (h : FreeCancelEquiv w w') (suf : BraidWord n) :
    FreeCancelEquiv (w ++ suf) (w' ++ suf) :=
  induction (motive := fun u v ↦ FreeCancelEquiv (u ++ suf) (v ++ suf))
    (fun h ↦ of_step (h.append_right suf)) (fun _ ↦ refl _)
    (fun _ ih ↦ ih.symm) (fun _ _ ih ih' ↦ ih.trans ih') h

/-- Concatenating freely equivalent words preserves free-cancellation equivalence. -/
theorem append {u u' v v' : BraidWord n} (hu : FreeCancelEquiv u u')
    (hv : FreeCancelEquiv v v') : FreeCancelEquiv (u ++ v) (u' ++ v') :=
  (hu.append_right v).trans (hv.append_left u')

end FreeCancelEquiv

private theorem toBraid_insert (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
    toBraid (u ++ [(i, ε), (i, -ε)] ++ v) = toBraid (u ++ v) := by
  rw [toBraid_append, toBraid_append, toBraid_append, toBraid_cons, toBraid_cons, toBraid_nil,
    mul_one]
  -- `toBraid` maps each letter to `sigma i ^ (ε : ℤ)`; after the append/cons
  -- rewrites above, `change` exposes those two definitional reductions so the
  -- inverse-pair cancellation can be rewritten as `a * a⁻¹ = 1`.
  change u.toBraid * (sigma i ^ (ε : ℤ) * sigma i ^ ((-ε : ℤˣ) : ℤ)) * v.toBraid = _
  rw [Units.val_neg]
  rw [zpow_neg]
  simp

/-- A free-cancellation step does not change the braid represented by a word. -/
theorem toBraid_freeCancel {w w' : BraidWord n} (h : FreeCancelStep w w') :
    toBraid w = toBraid w' := by
  cases h with
  | insert u v i ε => exact (toBraid_insert u v i ε).symm
  | delete u v i ε => exact toBraid_insert u v i ε

/-- Free-cancellation equivalence preserves the represented braid. -/
theorem toBraid_freeCancelEquiv {w w' : BraidWord n} (h : FreeCancelEquiv w w') :
    toBraid w = toBraid w' := by
  induction h with
  | rel _ _ h => exact toBraid_freeCancel h
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Inserting a free-cancelled pair adds two crossings. -/
theorem length_freeCancel_insert (u v : BraidWord n) (i : Fin (n - 1)) (ε : ℤˣ) :
    (u ++ [(i, ε), (i, -ε)] ++ v).length = (u ++ v).length + 2 := by
  simp [List.length_append]
  omega

/-- The closure writhe is unchanged by one free-cancellation step. -/
theorem writhe_closure_freeCancel {w w' : BraidWord n} (h : FreeCancelStep w w') :
    w.closure.writhe = w'.closure.writhe := by
  rw [writhe_closure, writhe_closure]
  exact congrArg (Multiplicative.toAdd ∘ ArtinGroup.exponentSum _) (toBraid_freeCancel h)

/-- The closure writhe is invariant under the equivalence generated by free cancellations. -/
theorem writhe_closure_freeCancelEquiv {w w' : BraidWord n} (h : FreeCancelEquiv w w') :
    w.closure.writhe = w'.closure.writhe := by
  rw [writhe_closure, writhe_closure]
  exact congrArg (Multiplicative.toAdd ∘ ArtinGroup.exponentSum _) (toBraid_freeCancelEquiv h)

end BraidWord

end TauCeti
