/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisGroups.Certificate.Check

import TauCeti.Algebra.BigOperators.Finset.Pairs
import TauCeti.FieldTheory.GaloisGroups.FactorDegrees
import TauCeti.FieldTheory.GaloisGroups.Resolvent.Quintic.Orbit
import TauCeti.FieldTheory.GaloisGroups.Resolvent.Specialization
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.RingTheory.Polynomial.Cyclotomic.Factorization
import Mathlib.Tactic.ComputeDegree
import Mathlib.Tactic.LinearCombination

/-!
# A cyclic quintic certificate

The polynomial `X⁵ + X⁴ - 4X³ - 3X² + 3X + 1` is irreducible modulo `2`.
Together with its second root `X² - 2` in the root field, this supplies a
cyclic-route certificate and proves that its Galois group has label `5T1`.
This polynomial defines the LMFDB number field `5.5.14641.1`.

The file also computes the discriminant and the resolvent sextic of this quintic. Its roots are
`2 cos (2πk/11)`, and if `θ` is one of them then so is `θ² - 2`; iterating, the five roots are
polynomials of degree at most four in `θ`. The discriminant and the six values of Dummit's
`F₂₀`-invariant at these roots are then polynomials in `θ`. Reduced modulo the quintic, the
product of the differences of the roots is `-121`, and the six values become explicit elements of
`ℚ(θ)`. One of them is `-16`, and they are pairwise distinct because `1, θ, θ², θ³, θ⁴` are
linearly independent over `ℚ`, the quintic being irreducible. So the resolvent sextic splits over
`ℚ(θ)` with distinct roots, one of them `-16`. Every reduction modulo the quintic is a
`linear_combination` with an explicit quotient.

## Main results

* `TauCeti.hasSecondRootInRootField_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`:
  the second-root evidence.
* `Polynomial.irreducible_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_zmod_two`:
  the irreducible reduction at `2`.
* `Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two`:
  the factor degrees at `2`.
* `TauCeti.QuinticCertificate.check_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`:
  the certificate checks.
* `TauCeti.hasGaloisLabel_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`:
  the Galois label is `5T1`.
* `TauCeti.discr_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`: the discriminant is `121² = 11⁴`.
* `TauCeti.hasSexticRoot_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`: `-16` is a root of the
  resolvent sextic, which is separable.

## References

* D. S. Dummit, *Solving solvable quintics*, Mathematics of Computation **57** (1991), 387–401.
* H. Cohen, *A Course in Computational Algebraic Number Theory*, Springer 1993, §6.3.
-/

public section
noncomputable section

open Polynomial

namespace TauCeti

/-- The polynomial `X² - 2` supplies formal second-root evidence for the cyclic quintic
`X⁵ + X⁴ - 4X³ - 3X² + 3X + 1`. For this monic irreducible quintic, it represents a second
root in the field generated by one root. -/
theorem hasSecondRootInRootField_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    HasSecondRootInRootField (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1)
      (X ^ 2 - 2) := by
  rw [hasSecondRootInRootField_iff]
  norm_num only [Polynomial.map_add, Polynomial.map_sub, Polynomial.map_mul,
    Polynomial.map_pow, Polynomial.map_X, Polynomial.map_one, Polynomial.map_ofNat]
  let f : ℚ[X] := X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1
  have hf : f.Monic := by
    dsimp [f]
    monicity!
  have hsecond : (f.comp (X ^ 2 - 2)) %ₘ f = 0 ∧ (X ^ 2 - 2) %ₘ f ≠ X %ₘ f := by
    constructor
    · rw [modByMonic_eq_zero_iff_dvd hf]
      refine ⟨X ^ 5 - X ^ 4 - 4 * X ^ 3 + 3 * X ^ 2 + 3 * X - 1, ?_⟩
      dsimp [f]
      simp
      ring_nf
    · have hb : (X ^ 2 - 2 : ℚ[X]) %ₘ f = X ^ 2 - 2 :=
        (modByMonic_eq_self_iff hf).mpr (by
          have hfdeg : f.degree = 5 := by dsimp [f]; compute_degree!
          have hbdeg : (X ^ 2 - 2 : ℚ[X]).degree = 2 := by compute_degree!
          rw [hfdeg, hbdeg]
          decide)
      have hX : (X : ℚ[X]) %ₘ f = X :=
        (modByMonic_eq_self_iff hf).mpr (by
          have hfdeg : f.degree = 5 := by dsimp [f]; compute_degree!
          have hXdeg : (X : ℚ[X]).degree = 1 := by compute_degree!
          rw [hfdeg, hXdeg]
          decide)
      rw [hb, hX]
      intro h
      have := congrArg (fun q : ℚ[X] ↦ q.coeff 0) h
      norm_num at this
  simpa only [f] using hsecond

/-- The reduction of the cyclic quintic modulo `2` is irreducible. -/
theorem _root_.Polynomial.irreducible_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_zmod_two :
    Irreducible (X ^ 5 + X ^ 4 + X ^ 2 + X + 1 : (ZMod 2)[X]) := by
  have hpn : ¬ 2 ∣ 31 := by decide
  apply ZMod.irreducible_of_dvd_cyclotomic_of_natDegree (n := 31) hpn
  · have : Fact (Nat.Prime 31) := ⟨by decide⟩
    rw [cyclotomic_prime]
    refine ⟨∑ i ∈ ({0, 3, 4, 8, 9, 10, 11, 14, 16, 18, 19, 21, 22, 23, 25} : Finset ℕ),
      X ^ i, ?_⟩
    norm_num [Finset.sum_range_succ, Finset.sum_range_zero] at *
    ring_nf
    have h3 : (3 : (ZMod 2)[X]) = 1 := by
      linear_combination (CharTwo.two_eq_zero : (2 : (ZMod 2)[X]) = 0)
    have h5 : (5 : (ZMod 2)[X]) = 1 := by
      linear_combination 2 * (CharTwo.two_eq_zero : (2 : (ZMod 2)[X]) = 0)
    rw [h3, h5]
    ring
  · have hdegree : (X ^ 5 + X ^ 4 + X ^ 2 + X + 1 : (ZMod 2)[X]).natDegree = 5 := by
      compute_degree!
    have horder : orderOf (ZMod.unitOfCoprime 2 (by decide : Nat.Coprime 2 31)) = 5 := by
      apply orderOf_eq_of_pow_and_pow_div_prime (by decide)
      · apply Units.ext
        decide
      · intro p hp hpdvd
        have hple : p ≤ 5 := Nat.le_of_dvd (by decide) hpdvd
        have hp2 := hp.two_le
        have heq : p = 5 := by
          interval_cases p <;> simp_all
        subst p
        apply Ne.intro
        intro h
        have h' := congrArg Units.val h
        have hne : (2 : ZMod 31) ≠ 1 := by decide
        exact hne h'
    simpa only [hdegree] using horder.symm

/-- The cyclic quintic has a single irreducible factor of degree five modulo `2`. -/
@[simp] theorem _root_.Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two :
    (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).factorDegrees 2 = {5} := by
  rw [Polynomial.factorDegrees_eq_singleton_iff]
  have hmap : (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map
      (Int.castRingHom (ZMod 2)) = (X ^ 5 + X ^ 4 + X ^ 2 + X + 1 : (ZMod 2)[X]) := by
    norm_num
    linear_combination (-2 * X ^ 3 - 2 * X ^ 2 + X : (ZMod 2)[X]) *
      (CharTwo.two_eq_zero : (2 : (ZMod 2)[X]) = 0)
  rw [hmap]
  constructor
  · exact Polynomial.irreducible_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_zmod_two
  · compute_degree!

/-- The cyclic-route certificate for the cyclic quintic checks. -/
@[simp] theorem QuinticCertificate.check_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    (QuinticCertificate.cyclic 2 (X ^ 2 - 2)).check
      (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1) = true := by
  have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hf : (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).Monic := by
    monicity!
  have hirr : Irreducible ((X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map
      (Int.castRingHom (ZMod 2))) :=
    (Polynomial.factorDegrees_eq_singleton_iff.mp
      Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two).1
  have hgood : IsGoodPrime (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1) 2 :=
    (isGoodPrime_iff _ 2).mpr <|
      (hf.separable_map_zmod_iff_not_dvd_discr 2).mp
        (PerfectField.separable_of_irreducible hirr)
  rw [QuinticCertificate.check_eq_true_iff, QuinticCertificate.verifies_cyclic_iff]
  exact ⟨HasFactorDegrees.mk hgood
      Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two,
    hasSecondRootInRootField_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1⟩

/-- The cyclic quintic `X⁵ + X⁴ - 4X³ - 3X² + 3X + 1` has Galois label `5T1`. -/
theorem hasGaloisLabel_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    HasGaloisLabel
      ((X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map
        (Int.castRingHom ℚ)) (⟨0, by simp⟩ : TransitiveGroupIndex 5) := by
  have hf : (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).Monic := by
    monicity!
  have h := QuinticCertificate.check_sound hf
    QuinticCertificate.check_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1
  rwa [QuinticCertificate.label_cyclic] at h

/-! ### The roots of the cyclic quintic over `ℂ` -/

private theorem monic_cyclicQuintic :
    (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).Monic := by
  monicity!

-- The cyclic quintic has a complex root.
private theorem exists_cyclicQuintic_eq_zero :
    ∃ θ : ℂ, θ ^ 5 + θ ^ 4 - 4 * θ ^ 3 - 3 * θ ^ 2 + 3 * θ + 1 = 0 := by
  have hdeg : (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℂ[X]).degree = 5 := by
    compute_degree!
  obtain ⟨θ, hθ⟩ := Complex.exists_root
    (f := (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℂ[X])) (by rw [hdeg]; decide)
  exact ⟨θ, by simpa using hθ⟩

variable {θ : ℂ}

/-- The roots of the cyclic quintic, as polynomials in one root `θ`: each is `x ↦ x² - 2` applied
to the previous one, reduced modulo the quintic. -/
private noncomputable def cyclicQuinticRoots (θ : ℂ) : Fin 5 → ℂ :=
  ![θ, θ ^ 2 - 2, θ ^ 4 - 4 * θ ^ 2 + 2, θ ^ 3 - 3 * θ, -θ ^ 4 - θ ^ 3 + 3 * θ ^ 2 + 2 * θ - 1]

-- Over `ℂ` the cyclic quintic is the product of the linear factors at those roots.
private theorem map_cyclicQuintic_eq_prod
    (hθ : θ ^ 5 + θ ^ 4 - 4 * θ ^ 3 - 3 * θ ^ 2 + 3 * θ + 1 = 0) :
    (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map (Int.castRingHom ℂ) =
      ∏ i, (X - C (cyclicQuinticRoots θ i)) := by
  have ht : C θ ^ 5 + C θ ^ 4 - 4 * C θ ^ 3 - 3 * C θ ^ 2 + 3 * C θ + 1 = (0 : ℂ[X]) := by
    simpa only [map_add, map_sub, map_mul, map_pow, map_ofNat, map_one, map_zero] using
      congrArg C hθ
  simp only [Polynomial.map_add, Polynomial.map_sub, Polynomial.map_mul, Polynomial.map_pow,
    Polynomial.map_X, Polynomial.map_ofNat, Polynomial.map_one, Fin.prod_univ_five,
    cyclicQuinticRoots, Matrix.cons_val, map_add, map_sub, map_mul, map_pow, map_neg, map_ofNat,
    map_one]
  linear_combination (-(C θ ^ 9 - 8 * C θ ^ 7 + 21 * C θ ^ 5 - 19 * C θ ^ 3 + 3 * C θ - 1) -
    X * (-C θ ^ 8 - C θ ^ 7 + 7 * C θ ^ 6 + 6 * C θ ^ 5 - 17 * C θ ^ 4 - 9 * C θ ^ 3 +
      16 * C θ ^ 2 + C θ - 3) -
    X ^ 2 * (C θ ^ 6 + C θ ^ 5 - 5 * C θ ^ 4 - 4 * C θ ^ 3 + 7 * C θ ^ 2 + 3 * C θ - 1) -
    X ^ 3 * (-C θ ^ 3 + 2 * C θ)) * ht

-- A root of the cyclic quintic satisfies no nonzero integral relation of degree at most four,
-- because the quintic is irreducible over `ℚ`.
private theorem eq_zero_of_sum_mul_pow_eq_zero
    (hθ : θ ^ 5 + θ ^ 4 - 4 * θ ^ 3 - 3 * θ ^ 2 + 3 * θ + 1 = 0) {a : Fin 5 → ℤ}
    (h : ∑ k, (a k : ℂ) * θ ^ (k : ℕ) = 0) : a = 0 := by
  have hqθ : aeval θ ((X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map
      (Int.castRingHom ℚ)) = 0 := by
    simpa [map_ofNat] using hθ
  have hdeg : (minpoly ℚ θ).natDegree = 5 := by
    rw [← minpoly.eq_of_irreducible_of_monic
        hasGaloisLabel_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1.irreducible hqθ
        (monic_cyclicQuintic.map _), monic_cyclicQuintic.natDegree_map]
    compute_degree!
  have hli := linearIndependent_pow (K := ℚ) θ
  rw [hdeg] at hli
  funext k
  have hk := Fintype.linearIndependent_iff.mp hli (fun k => (a k : ℚ))
    (by simpa [Algebra.smul_def] using h) k
  simpa using hk

/-! ### The discriminant -/

/-- The discriminant of the cyclic quintic `X⁵ + X⁴ - 4X³ - 3X² + 3X + 1` is `121² = 11⁴`, a
square: the Galois group `C₅` consists of even permutations. -/
theorem discr_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).discr = 121 ^ 2 := by
  obtain ⟨θ, hθ⟩ := exists_cyclicQuintic_eq_zero
  have h := monic_cyclicQuintic.discr_map (Int.castRingHom ℂ)
  rw [map_cyclicQuintic_eq_prod hθ, discr_prod_X_sub_C_eq_sq] at h
  -- The product of the differences of the roots reduces to `-121` modulo the quintic.
  have hcalc : ∏ i, ∏ j ∈ Finset.Ioi i, (cyclicQuinticRoots θ i - cyclicQuinticRoots θ j) =
      -121 := by
    rw [prod_prod_Ioi_eq_of_two (m := 3), prod_prod_Ioi_eq_of_two (m := 1)]
    norm_num [Fin.prod_univ_three, Fin.prod_univ_one, Fin.prod_Ioi_zero, Fin.prod_univ_zero,
      cyclicQuinticRoots]
    linear_combination (-2 * θ ^ 31 - θ ^ 30 + 67 * θ ^ 29 + 34 * θ ^ 28 - 1008 * θ ^ 27 -
      523 * θ ^ 26 + 8991 * θ ^ 25 + 4803 * θ ^ 24 - 52859 * θ ^ 23 - 29271 * θ ^ 22 +
      215368 * θ ^ 21 + 124500 * θ ^ 20 - 622326 * θ ^ 19 - 378562 * θ ^ 18 +
      1282702 * θ ^ 17 + 829387 * θ ^ 16 - 1869744 * θ ^ 15 - 1303729 * θ ^ 14 +
      1882159 * θ ^ 13 + 1448738 * θ ^ 12 - 1251800 * θ ^ 11 - 1110673 * θ ^ 10 +
      508353 * θ ^ 9 + 569675 * θ ^ 8 - 107658 * θ ^ 7 - 189738 * θ ^ 6 + 7449 * θ ^ 5 +
      39554 * θ ^ 4 - 97 * θ ^ 3 - 4436 * θ ^ 2 + 405 * θ + 121) * hθ
  rw [hcalc] at h
  apply Int.cast_injective (α := ℂ)
  rw [← eq_intCast (Int.castRingHom ℂ), ← h]
  norm_num

/-! ### The resolvent sextic -/

/-- Integral coordinates, in the powers `1, θ, θ², θ³, θ⁴` of a root, of the six values of
Dummit's invariant at the roots of the cyclic quintic, one for each coset representative. -/
private def cyclicSexticCoords : Fin 6 → Fin 5 → ℤ :=
  ![![-16, 0, 0, 0, 0], ![-13, 16, 21, -7, -6], ![4, 4, -14, 1, 4], ![10, 3, -16, -2, 3],
    ![-11, -10, 2, 3, 1], ![-4, -13, 7, 5, -2]]

/-- The six values of Dummit's invariant at the roots of the cyclic quintic, as polynomials in
the root `θ`. -/
private noncomputable def cyclicSexticRoots (θ : ℂ) (i : Fin 6) : ℂ :=
  ∑ k, (cyclicSexticCoords i k : ℂ) * θ ^ (k : ℕ)

-- The six values are pairwise distinct.
private theorem cyclicSexticRoots_injective
    (hθ : θ ^ 5 + θ ^ 4 - 4 * θ ^ 3 - 3 * θ ^ 2 + 3 * θ + 1 = 0) :
    Function.Injective (cyclicSexticRoots θ) := by
  have hcoords : Function.Injective cyclicSexticCoords := by decide
  intro i j hij
  refine hcoords (sub_eq_zero.mp (eq_zero_of_sum_mul_pow_eq_zero hθ ?_))
  simpa [cyclicSexticRoots, sub_mul, Finset.sum_sub_distrib, sub_eq_zero] using hij

-- The values of the invariant renamed along the six coset representatives.
private theorem eval₂_rename_quinticF20Invariant_cyclicQuinticRoots
    (hθ : θ ^ 5 + θ ^ 4 - 4 * θ ^ 3 - 3 * θ ^ 2 + 3 * θ + 1 = 0) :
    MvPolynomial.eval₂ (Int.castRingHom ℂ) (cyclicQuinticRoots θ)
        (MvPolynomial.rename ⇑(1 : Equiv.Perm (Fin 5)) quinticF20Invariant) =
          cyclicSexticRoots θ 0 ∧
      MvPolynomial.eval₂ (Int.castRingHom ℂ) (cyclicQuinticRoots θ)
        (MvPolynomial.rename ⇑(Equiv.swap (2 : Fin 5) 3) quinticF20Invariant) =
          cyclicSexticRoots θ 1 ∧
      MvPolynomial.eval₂ (Int.castRingHom ℂ) (cyclicQuinticRoots θ)
        (MvPolynomial.rename ⇑(Equiv.swap (3 : Fin 5) 4) quinticF20Invariant) =
          cyclicSexticRoots θ 2 ∧
      MvPolynomial.eval₂ (Int.castRingHom ℂ) (cyclicQuinticRoots θ)
        (MvPolynomial.rename ⇑(Equiv.swap (2 : Fin 5) 4) quinticF20Invariant) =
          cyclicSexticRoots θ 3 ∧
      MvPolynomial.eval₂ (Int.castRingHom ℂ) (cyclicQuinticRoots θ)
        (MvPolynomial.rename ⇑(Equiv.swap 2 3 * Equiv.swap 3 4 : Equiv.Perm (Fin 5))
          quinticF20Invariant) =
          cyclicSexticRoots θ 4 ∧
      MvPolynomial.eval₂ (Int.castRingHom ℂ) (cyclicQuinticRoots θ)
        (MvPolynomial.rename ⇑(Equiv.swap 3 4 * Equiv.swap 2 3 : Equiv.Perm (Fin 5))
          quinticF20Invariant) =
          cyclicSexticRoots θ 5 := by
  simp only [eval₂_rename_quinticF20Invariant]
  simp only [cyclicQuinticRoots, Fin.isValue, Equiv.Perm.coe_one, id_eq, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.cons_val, cyclicSexticRoots, cyclicSexticCoords, Int.reduceNeg,
    Matrix.cons_val', Matrix.cons_val_fin_one, Fin.sum_univ_five, Int.cast_neg, Int.cast_ofNat,
    Fin.coe_ofNat_eq_mod, Nat.zero_mod, pow_zero, mul_one, Int.cast_zero, Nat.one_mod, pow_one,
    zero_mul, add_zero, Nat.reduceMod, Nat.mod_succ, Equiv.swap_apply_def, Fin.reduceEq,
    ↓reduceIte, neg_mul, Int.cast_one, one_mul,
    Equiv.Perm.coe_mul, Function.comp_apply]
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · linear_combination (θ ^ 8 + θ ^ 7 - 8 * θ ^ 6 - 3 * θ ^ 5 + 28 * θ ^ 4 - 9 * θ ^ 3 -
      41 * θ ^ 2 + 20 * θ + 12) * hθ
  · linear_combination (-θ ^ 10 + 12 * θ ^ 8 + 2 * θ ^ 7 - 49 * θ ^ 6 - 12 * θ ^ 5 +
      82 * θ ^ 4 + 19 * θ ^ 3 - 51 * θ ^ 2 - 3 * θ + 5) * hθ
  · linear_combination (θ ^ 10 - 9 * θ ^ 8 + 3 * θ ^ 7 + 25 * θ ^ 6 - 20 * θ ^ 5 -
      15 * θ ^ 4 + 39 * θ ^ 3 - 16 * θ ^ 2 - 20 * θ + 4) * hθ
  · linear_combination (-2 * θ ^ 9 + 2 * θ ^ 8 + 21 * θ ^ 7 - 13 * θ ^ 6 - 73 * θ ^ 5 +
      24 * θ ^ 4 + 94 * θ ^ 3 - 9 * θ ^ 2 - 33 * θ - 2) * hθ
  · linear_combination (θ ^ 10 + θ ^ 9 - 9 * θ ^ 8 - 11 * θ ^ 7 + 29 * θ ^ 6 + 42 * θ ^ 5 -
      37 * θ ^ 4 - 62 * θ ^ 3 + 10 * θ ^ 2 + 29 * θ + 3) * hθ
  · linear_combination (-θ ^ 10 + θ ^ 9 + 11 * θ ^ 8 - 8 * θ ^ 7 - 38 * θ ^ 6 + 20 * θ ^ 5 +
      44 * θ ^ 4 - 17 * θ ^ 3 - 7 * θ ^ 2 + 5 * θ) * hθ

-- Over `ℂ` the resolvent sextic of the cyclic quintic is the product of the linear factors at
-- the six values.
private theorem map_resolventSextic_cyclicQuintic_eq_prod
    (hθ : θ ^ 5 + θ ^ 4 - 4 * θ ^ 3 - 3 * θ ^ 2 + 3 * θ + 1 = 0) :
    (resolventSextic (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1)).map
        (Int.castRingHom ℂ) = ∏ i, (X - C (cyclicSexticRoots θ i)) := by
  obtain ⟨h0, h1, h2, h3, h4, h5⟩ := eval₂_rename_quinticF20Invariant_cyclicQuinticRoots hθ
  rw [resolventSextic_def, ResolventSpec.specialize_map, ResolventSpec.specialize_def,
    map_vietaHom_eq_galResolvent quinticF20Spec.orbitProduct_esymm (map_cyclicQuintic_eq_prod hθ),
    quinticF20Spec_Φ, ← MvPolynomial.map_universalResolvent_eq_galResolvent,
    universalResolvent_quinticF20Invariant, Polynomial.map_prod,
    prod_quinticF20OrbitRepresentatives, Fin.prod_univ_six]
  simp only [Polynomial.map_sub, Polynomial.map_X, Polynomial.map_C, MvPolynomial.coe_eval₂Hom,
    h0, h1, h2, h3, h4, h5]

/-- The integer `-16` is a root of the resolvent sextic of the cyclic quintic
`X⁵ + X⁴ - 4X³ - 3X² + 3X + 1`, and that sextic has nonzero discriminant: over `ℚ(θ)`, for a root
`θ` of the quintic, it splits into six distinct linear factors. -/
theorem hasSexticRoot_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    HasSexticRoot (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1) (-16) := by
  obtain ⟨θ, hθ⟩ := exists_cyclicQuintic_eq_zero
  have hmap := map_resolventSextic_cyclicQuintic_eq_prod hθ
  refine HasSexticRoot.mk ?_ ?_
  · have h := congrArg (eval ((-16 : ℤ) : ℂ)) hmap
    rw [eval_intCast_map, eval_prod] at h
    have h0 : ∏ i, eval ((-16 : ℤ) : ℂ) (X - C (cyclicSexticRoots θ i)) = 0 :=
      Finset.prod_eq_zero (Finset.mem_univ 0)
        (by simp [cyclicSexticRoots, cyclicSexticCoords, Fin.sum_univ_five])
    simpa using h.trans h0
  · intro h0
    have hsep : ((resolventSextic (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1)).map
        (Int.castRingHom ℂ)).Separable := by
      rw [hmap]
      exact separable_prod_X_sub_C_iff.mpr (cyclicSexticRoots_injective hθ)
    rw [(resolventSextic _).separable_map_iff_map_discr_ne_zero _
      (by simp [(monic_resolventSextic _).leadingCoeff]), h0, map_zero] at hsep
    exact hsep rfl

end TauCeti
