/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicTopology.SimplicialComplex.Subdivision.Stellar.Basic

/-!
# Stellar equivalence of simplicial complexes

Starring a face at a fresh vertex (`PreAbstractSimplicialComplex.stellarSubdivision`) is one
*stellar move*. Two complexes are **stellar equivalent** when a finite sequence of stellar moves
and inverse stellar moves carries one to the other. This is the combinatorial relation that
layer 11 of the geometric-topology roadmap (`TauCetiRoadmap/GeometricTopology/README.md`) needs
in order to say that a complex is a combinatorial ball or sphere, namely that it becomes the
standard simplex, respectively the boundary of the standard simplex, *after subdivision*.

The relation is built as `Relation.EqvGen` of the one-move relation, so a proof of
`StellarEquivalent K L` is generated by stellar moves under reflexivity, symmetry, and
transitivity, and induction over that closure is how every invariance result below is proved.

## What this relation is, and what it is not

Newman's and Alexander's theorem is that stellar equivalence coincides with the existence of a
common subdivision, hence — once realizations are available — with PL homeomorphism. That
theorem is *not* proved here, and nothing below asserts it: the definition is taken as the
combinatorial one, following Lickorish, *Simplicial moves on complexes and manifolds*, Geom.
Topol. Monogr. 2 (1999), 299-320, and Rourke--Sanderson, *Introduction to Piecewise-Linear
Topology*, Chapter 2. Naming the relation after the moves that generate it, rather than after
that theorem, keeps the two apart.

A stellar move demands a *fresh* vertex, one spanning no face of the complex yet. That hypothesis
is what makes the move honest. The same-type relation records literal move sequences, while
`StellarEquivalentUpToRelabeling` compares complexes intrinsically: it first embeds both into a
common enlarged vertex type and allows arbitrary injective relabelings.

## Main definitions

* `PreAbstractSimplicialComplex.IsStellarMove`: one starring of a face at a fresh vertex.
* `PreAbstractSimplicialComplex.StellarEquivalent`: a finite chain of such moves.
* `PreAbstractSimplicialComplex.StellarEquivalentUpToRelabeling`: intrinsic stellar equivalence
  in a common enlarged vertex type.

## Main results

* `PreAbstractSimplicialComplex.equivalence_stellarEquivalent`: stellar equivalence is an
  equivalence relation.
* `PreAbstractSimplicialComplex.StellarEquivalent.dimension_eq`: stellar equivalent complexes
  have the same dimension.
* `PreAbstractSimplicialComplex.StellarEquivalent.finite_faces_iff`: stellar equivalence
  preserves and reflects finiteness of the face collection.
* `PreAbstractSimplicialComplex.StellarEquivalentUpToRelabeling.induction_on`: invariants of
  intrinsic stellar equivalence follow from the common-relabeling generators.
* `PreAbstractSimplicialComplex.StellarEquivalentUpToRelabeling.dimension_eq`,
  `finite_faces_iff`, and `ne_bot_iff`: intrinsic stellar equivalence preserves dimension,
  face finiteness, and nonvoidness.
-/

public section

open Finset

namespace PreAbstractSimplicialComplex

variable {ι : Type*} [DecidableEq ι] {K L M : PreAbstractSimplicialComplex ι}
  {σ τ : Finset ι} {v : ι}

/-- `L` is obtained from `K` by one **stellar move**: `L` is the starring of `K` at a face `σ`
using a vertex `v` that `K` does not already use. -/
def IsStellarMove (K L : PreAbstractSimplicialComplex ι) : Prop :=
  ∃ σ : Finset ι, ∃ v : ι, σ ∈ K ∧ ({v} : Finset ι) ∉ K ∧ L = stellarSubdivision K σ v

/-- The witness description of a stellar move. -/
theorem isStellarMove_iff :
    IsStellarMove K L ↔
      ∃ σ : Finset ι, ∃ v : ι, σ ∈ K ∧ ({v} : Finset ι) ∉ K ∧
        L = stellarSubdivision K σ v :=
  Iff.rfl

/-- Starring a face at a fresh vertex is a stellar move. -/
theorem isStellarMove_stellarSubdivision (hσ : σ ∈ K) (hv : ({v} : Finset ι) ∉ K) :
    IsStellarMove K (stellarSubdivision K σ v) :=
  ⟨σ, v, hσ, hv, rfl⟩

/-- A stellar move preserves the dimension. -/
theorem IsStellarMove.dimension_eq (h : IsStellarMove K L) : dimension L = dimension K := by
  obtain ⟨σ, v, hσ, hv, rfl⟩ := h
  exact dimension_stellarSubdivision hv (K.isRelLowerSet_faces hσ).1

/-- A stellar move preserves and reflects finiteness of the face collection. -/
theorem IsStellarMove.finite_faces_iff (h : IsStellarMove K L) :
    K.faces.Finite ↔ L.faces.Finite := by
  obtain ⟨σ, v, hσ, hv, rfl⟩ := h
  exact (finite_faces_stellarSubdivision_iff hσ hv).symm

/-- **Stellar equivalence**: `K` and `L` are joined by a finite sequence of stellar moves and
inverse stellar moves. -/
def StellarEquivalent (K L : PreAbstractSimplicialComplex ι) : Prop :=
  Relation.EqvGen IsStellarMove K L

namespace StellarEquivalent

/-- Every simplicial complex is stellar equivalent to itself. -/
@[refl]
theorem refl (K : PreAbstractSimplicialComplex ι) : StellarEquivalent K K :=
  Relation.EqvGen.refl _

/-- Stellar equivalences compose. -/
@[trans]
theorem trans (h : StellarEquivalent K L) (h' : StellarEquivalent L M) : StellarEquivalent K M :=
  Relation.EqvGen.trans _ _ _ h h'

/-- Stellar equivalence is symmetric. -/
@[symm]
theorem symm (h : StellarEquivalent K L) : StellarEquivalent L K :=
  Relation.EqvGen.symm _ _ h

end StellarEquivalent

/-- A single stellar move is a stellar equivalence. -/
theorem IsStellarMove.stellarEquivalent (h : IsStellarMove K L) : StellarEquivalent K L :=
  Relation.EqvGen.rel _ _ h

/-- An injective relabeling carries a stellar move to the corresponding stellar move between the
image complexes. -/
theorem IsStellarMove.map {κ : Type*} [DecidableEq κ] (h : IsStellarMove K L)
    (f : ι → κ) (hf : Function.Injective f) : IsStellarMove (K.map f) (L.map f) := by
  obtain ⟨σ, v, hσ, hv, rfl⟩ := h
  refine ⟨σ.image f, f v, mem_map_iff.mpr ⟨σ, hσ, rfl⟩, ?_,
    map_stellarSubdivision f hf⟩
  intro hfv
  rw [mem_map_iff] at hfv
  obtain ⟨τ, hτ, hτf⟩ := hfv
  have hvτ : v ∈ τ := hf.mem_finset_image.mp
    (hτf ▸ Finset.mem_singleton_self (f v))
  exact hv (singleton_mem_of_mem hτ hvτ)

/-- A complex is stellar equivalent to any of its starrings at a fresh vertex. -/
theorem stellarEquivalent_stellarSubdivision (hσ : σ ∈ K) (hv : ({v} : Finset ι) ∉ K) :
    StellarEquivalent K (stellarSubdivision K σ v) :=
  (isStellarMove_stellarSubdivision hσ hv).stellarEquivalent

/-- Stellar equivalence is an equivalence relation. -/
theorem equivalence_stellarEquivalent : Equivalence (StellarEquivalent (ι := ι)) :=
  Relation.EqvGen.is_equivalence _

namespace StellarEquivalent

/-- To prove a property of stellar equivalent complexes, it suffices to prove it for a stellar
move and show that it is reflexive, symmetric, and transitive. -/
theorem induction_on (h : StellarEquivalent K L)
    {P : PreAbstractSimplicialComplex ι → PreAbstractSimplicialComplex ι → Prop}
    (rel : ∀ A B, IsStellarMove A B → P A B) (refl : ∀ A, P A A)
    (symm : ∀ A B, P A B → P B A)
    (trans : ∀ A B C, P A B → P B C → P A C) : P K L := by
  induction h with
  | rel A B h => exact rel A B h
  | refl => exact refl _
  | symm A B _ ih => exact symm A B ih
  | trans A B C _ _ ih₁ ih₂ => exact trans A B C ih₁ ih₂

/-- An injective relabeling carries a stellar equivalence to one between the image complexes. -/
theorem map {κ : Type*} [DecidableEq κ] (h : StellarEquivalent K L)
    (f : ι → κ) (hf : Function.Injective f) : StellarEquivalent (K.map f) (L.map f) := by
  induction h with
  | rel _ _ h => exact (h.map f hf).stellarEquivalent
  | refl => exact Relation.EqvGen.refl _
  | symm _ _ _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

/-- Stellar equivalent complexes have the same dimension. -/
theorem dimension_eq (h : StellarEquivalent K L) : dimension L = dimension K := by
  induction h with
  | rel _ _ h => exact h.dimension_eq
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₂.trans ih₁

/-- Stellar equivalence preserves and reflects finiteness of the face collection. -/
theorem finite_faces_iff (h : StellarEquivalent K L) : K.faces.Finite ↔ L.faces.Finite := by
  induction h with
  | rel _ _ h => exact h.finite_faces_iff
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- A complex stellar equivalent to a complex with a face has a face itself. -/
theorem ne_bot (h : StellarEquivalent K L) (hL : L ≠ ⊥) : K ≠ ⊥ := by
  rintro rfl
  exact hL (dimension_eq_bot_iff.mp (h.dimension_eq.trans dimension_bot))

end StellarEquivalent

/-! ### Intrinsic stellar equivalence -/

/-- **Stellar equivalence up to relabeling.** At each generating step, the two complexes are
injectively relabeled inside the common enlarged vertex type `ι ⊕ ℕ`. The generator existentially
quantifies these relabelings, and the equivalence closure lets such comparisons compose. -/
def StellarEquivalentUpToRelabeling (K L : PreAbstractSimplicialComplex ι) : Prop :=
  Relation.EqvGen
    (fun A B => ∃ f g : ι ↪ (ι ⊕ ℕ), StellarEquivalent (A.map f) (B.map g)) K L

/-- A same-type stellar equivalence gives an intrinsic stellar equivalence. -/
theorem StellarEquivalent.stellarEquivalentUpToRelabeling (h : StellarEquivalent K L) :
    StellarEquivalentUpToRelabeling K L := by
  let f : ι ↪ (ι ⊕ ℕ) := ⟨Sum.inl, Sum.inl_injective⟩
  exact Relation.EqvGen.rel _ _ ⟨f, f, h.map f f.injective⟩

namespace StellarEquivalentUpToRelabeling

/-- Every complex is intrinsically stellar equivalent to itself. -/
@[refl]
theorem refl (K : PreAbstractSimplicialComplex ι) : StellarEquivalentUpToRelabeling K K :=
  Relation.EqvGen.refl _

/-- Intrinsic stellar equivalence is symmetric. -/
@[symm]
theorem symm (h : StellarEquivalentUpToRelabeling K L) :
    StellarEquivalentUpToRelabeling L K :=
  Relation.EqvGen.symm _ _ h

/-- Intrinsic stellar equivalences compose. -/
@[trans]
theorem trans (h : StellarEquivalentUpToRelabeling K L)
    (h' : StellarEquivalentUpToRelabeling L M) : StellarEquivalentUpToRelabeling K M :=
  Relation.EqvGen.trans _ _ _ h h'

/-- A stellar equivalence after injectively relabeling both complexes into the common enlarged
vertex type gives an intrinsic stellar equivalence. -/
theorem of_common_relabeling (f g : ι ↪ (ι ⊕ ℕ))
    (h : StellarEquivalent (K.map f) (L.map g)) : StellarEquivalentUpToRelabeling K L :=
  Relation.EqvGen.rel _ _ ⟨f, g, h⟩

/-- To prove a property of intrinsically stellar equivalent complexes, it suffices to prove it
for a common-relabeling generator and show that it is reflexive, symmetric, and transitive. -/
theorem induction_on (h : StellarEquivalentUpToRelabeling K L)
    {P : PreAbstractSimplicialComplex ι → PreAbstractSimplicialComplex ι → Prop}
    (rel : ∀ A B (f g : ι ↪ (ι ⊕ ℕ)), StellarEquivalent (A.map f) (B.map g) → P A B)
    (refl : ∀ A, P A A) (symm : ∀ A B, P A B → P B A)
    (trans : ∀ A B C, P A B → P B C → P A C) : P K L := by
  induction h with
  | rel A B h =>
      obtain ⟨f, g, he⟩ := h
      exact rel A B f g he
  | refl => exact refl _
  | symm A B _ ih => exact symm A B ih
  | trans A B C _ _ ih₁ ih₂ => exact trans A B C ih₁ ih₂

/-- An injective relabeling transports intrinsic stellar equivalence. -/
theorem map {κ : Type*} [DecidableEq κ]
    (h : StellarEquivalentUpToRelabeling K L) (f : ι → κ) (hf : Function.Injective f) :
    StellarEquivalentUpToRelabeling (K.map f) (L.map f) := by
  classical
  let F : ι ⊕ ℕ → κ ⊕ ℕ := Sum.map f id
  have hF : Function.Injective F := hf.sumMap Function.injective_id
  -- Extend each common relabeling over the new ambient vertices outside the image of `f`.
  let extend (a : ι ↪ ι ⊕ ℕ) : κ → κ ⊕ ℕ := Function.extend f (F ∘ a) Sum.inl
  have hext (a : ι ↪ ι ⊕ ℕ) : Function.Injective (extend a) := by
    intro x y hxy
    by_cases hx : ∃ i, f i = x
    · obtain ⟨i, rfl⟩ := hx
      by_cases hy : ∃ j, f j = y
      · obtain ⟨j, rfl⟩ := hy
        simp only [extend, hf.extend_apply, Function.comp_apply] at hxy
        exact congrArg f (a.injective (hF hxy))
      · simp only [extend, hf.extend_apply, Function.comp_apply,
          Function.extend_apply' _ _ _ hy] at hxy
        cases hai : a i with
        | inl k =>
          simp only [F, hai, Sum.map_inl, Sum.inl.injEq] at hxy
          exact False.elim (hy ⟨k, hxy⟩)
        | inr n => simp [F, hai] at hxy
    · by_cases hy : ∃ j, f j = y
      · obtain ⟨j, rfl⟩ := hy
        simp only [extend, hf.extend_apply, Function.comp_apply,
          Function.extend_apply' _ _ _ hx] at hxy
        cases haj : a j with
        | inl k =>
          simp only [F, haj, Sum.map_inl, Sum.inl.injEq] at hxy
          exact False.elim (hx ⟨k, hxy.symm⟩)
        | inr n => simp [F, haj] at hxy
      · simpa only [extend, Function.extend_apply' _ _ _ hx,
          Function.extend_apply' _ _ _ hy, Sum.inl.injEq] using hxy
  have hcomp (a : ι ↪ ι ⊕ ℕ) : extend a ∘ f = F ∘ a :=
    Function.extend_comp hf _ _
  apply h.induction_on
  · intro A B a b he
    apply of_common_relabeling ⟨extend a, hext a⟩ ⟨extend b, hext b⟩
    simpa only [Function.Embedding.coeFn_mk, map_map, hcomp] using he.map F hF
  · intro A
    exact .refl _
  · intro A B h
    exact h.symm
  · intro A B C h h'
    exact h.trans h'

/-- Intrinsically stellar equivalent complexes have the same dimension. -/
theorem dimension_eq (h : StellarEquivalentUpToRelabeling K L) : dimension L = dimension K := by
  apply induction_on h
  · intro A B f g he
    exact (dimension_map_of_injective (K := B) g g.injective).symm.trans
      (he.dimension_eq.trans (dimension_map_of_injective (K := A) f f.injective))
  · intro A
    rfl
  · intro A B ih
    exact ih.symm
  · intro A B C ih₁ ih₂
    exact ih₂.trans ih₁

/-- Intrinsic stellar equivalence preserves and reflects finiteness of the face collection. -/
theorem finite_faces_iff (h : StellarEquivalentUpToRelabeling K L) :
    K.faces.Finite ↔ L.faces.Finite := by
  apply induction_on h
  · intro A B f g he
    exact (finite_faces_map_iff_of_injective (K := A) f f.injective).symm.trans
      (he.finite_faces_iff.trans
        (finite_faces_map_iff_of_injective (K := B) g g.injective))
  · intro A
    rfl
  · intro A B ih
    exact ih.symm
  · intro A B C ih₁ ih₂
    exact ih₁.trans ih₂

/-- Intrinsic stellar equivalence preserves and reflects nonvoidness. -/
theorem ne_bot_iff (h : StellarEquivalentUpToRelabeling K L) : K ≠ ⊥ ↔ L ≠ ⊥ := by
  constructor
  · intro hK hL
    apply hK
    rw [← dimension_eq_bot_iff, ← h.dimension_eq, dimension_eq_bot_iff]
    exact hL
  · intro hL hK
    apply hL
    rw [← dimension_eq_bot_iff, h.dimension_eq, dimension_eq_bot_iff]
    exact hK

/-- A complex intrinsically stellar equivalent to a nonvoid complex is nonvoid. -/
theorem ne_bot (h : StellarEquivalentUpToRelabeling K L) (hL : L ≠ ⊥) : K ≠ ⊥ :=
  h.ne_bot_iff.mpr hL

end StellarEquivalentUpToRelabeling

end PreAbstractSimplicialComplex
