/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Orthogonal.TypeB.SpinCarrier.BaseChange
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.SquareZeroCoroot

/-!
# Generation of the type-B spin carrier by root subgroups

The full-weight type-`Bₙ₊₁` spin carrier is defined from its positive and negative numbered
simple-root subgroups together with its split weight torus. This file proves that the weight torus
is redundant at every rank: the carrier is already the subgroup scheme generated by the root
subgroups alone, the two defining Hopf ideals agree over `ℤ` and after base change, and a
morphism out of the carrier is determined by its restrictions to the root subgroups.

Each simple root string through a spin weight has length at most two, so every numbered root
generator squares to zero on the spin module. The Chevalley rank-one identity

```text
x_α(u) x_{-α}(-u⁻¹) x_α(u) = h_α(u) n_α,      n_α = x_α(1) x_{-α}(-1) x_α(1),
```

then exhibits each coroot value at an arbitrary unit as a product of root subgroup elements. No
coprimality condition on the coordinates of the root is needed, and none is available at rank two:
the long simple root of `B₂` has Cartan row `(2, -2)`, so its values on the weight torus are the
squares of units rather than all units.

Applying the pointwise containment to the universal point of the torus, over the coordinate ring
of the split torus itself, shows that the torus is also redundant scheme-theoretically: the
toral-closure defining ideal over `ℤ` equals the ideal cut out by the numbered root subgroups
alone, so the carrier is the root-generated Kostant group scheme. This is an equality of integral
carriers and of their transports; it does not say that the subgroup generated anew over a
non-flat base is the base change of the integral carrier.

## Main results

* `TauCeti.TypeBSpinCarrier.coordinateCocharacter_mem_elementarySubgroup`: every coroot value of
  the carrier, at every unit of every value ring, lies in the group generated by the numbered root
  subgroups.
* `TauCeti.TypeBSpinCarrier.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in
  the elementary subgroup over every commutative ring.
* `TauCeti.TypeBSpinCarrier.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining
  the weight torus to all numbered root subgroups gives exactly the elementary subgroup.
* `TauCeti.TypeBSpinCarrier.definingIdeal_eq_kostantGeneratedDefiningIdeal`: the integral
  toral-closure carrier is already cut out by the root subgroups alone.
* `TauCeti.TypeBSpinCarrier.groupScheme_eq_kostantGeneratedGroupScheme` and
  `TauCeti.TypeBSpinCarrier.isIso_kostantGeneratedToToral`: the carrier is the root-generated
  Kostant group scheme, and the canonical comparison between them is an isomorphism.
* `TauCeti.TypeBSpinCarrier.baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal`
  states the same equality of ideals after base change to any commutative ring.
* `TauCeti.TypeBSpinCarrier.groupScheme_hom_ext_of_rootSubgroup`: a morphism out of the carrier is
  determined by its restrictions to the numbered root subgroups alone.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.
* `TauCeti.Algebra.Lie.Symplectic.StandardCarrier.ToralGeneration`, which runs the same
  square-zero argument on the standard type-`C` carrier.
* `TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.Generation`, the corresponding statement for
  the type-`D` spin carrier.
* `TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.SchemeGeneration`, which
  the scheme-theoretic section of this file follows.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace TauCeti.TypeBSpinCarrier

open TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

variable (n : ℕ)

/-! ## Generation of the weight torus -/

/-- Every coroot value of the full-weight type-`Bₙ₊₁` spin carrier lies in the group generated by
the numbered root subgroups, at every unit of every value ring. -/
theorem coordinateCocharacter_mem_elementarySubgroup (A : CommAlgCat.{v} ℤ) (d : Fin (n + 1))
    (u : (A : Type v)ˣ) :
    kostantCoordinateCocharacter (lattice n).toAddSubgroup (latticeBasis n) (basisWeight n) A d u ∈
      kostantElementarySubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) A :=
  kostantCoordinateCocharacter_mem_kostantElementarySubgroup_of_sq_eq_zero
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
    (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
    (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n)
    (isCartanWeightVector_latticeBasis n) (isSl2Triple_rep_rootGenerator n d)
    (pow_two_rep_rootGenerator_eq_zero n _) (pow_two_rep_rootGenerator_eq_zero n _) A u

/-- **Over every commutative ring the type-`B` full-spin weight torus on the base-changed
admissible lattice is contained in the elementary group generated by the positive and negative
numbered simple root subgroups.** -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup (lattice n).toAddSubgroup (latticeBasis n) (basisWeight n) A ≤
      kostantElementarySubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) A :=
  kostantTorusSubgroup_le_kostantElementarySubgroup_of_forall_coordinateCocharacter
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
    (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
    (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n) A
    (coordinateCocharacter_mem_elementarySubgroup n A)

/-- Over every commutative ring, adjoining the type-`B` full-spin weight torus to all positive and
negative numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n) Set.univ A =
      kostantElementarySubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) A :=
  kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup_of_sq_eq_zero
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
    (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
    (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n)
    (isCartanWeightVector_latticeBasis n) Sum.inl Sum.inr
    (isSl2Triple_rep_rootGenerator n) (pow_two_rep_rootGenerator_eq_zero n) A

/-! ## Scheme-theoretic generation -/

private theorem universalWeightTorus_mem_elementarySubgroup :
    let T := (DiagonalizableGroup.coordinateRing ℤ
      (SplitTorus.characterGroup (Fin (n + 1)))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin (n + 1)))) A :=
      WithConv.toConv (AlgHom.id ℤ T)
    kostantTorusPoints (lattice n).toAddSubgroup (latticeBasis n) (basisWeight n) A
        (SplitTorus.pointsMulEquiv q) ∈
      kostantElementarySubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) A := by
  intro T A q
  apply weightTorusSubgroup_le_elementarySubgroup n A
  exact (kostantTorusSubgroup_eq_range _ _ _ A).ge ⟨_, rfl⟩

/-- **The full-weight type-`Bₙ₊₁` spin carrier is generated scheme-theoretically by its numbered
root subgroups.** Adjoining the represented weight torus does not change the integral defining
Hopf ideal. -/
theorem definingIdeal_eq_kostantGeneratedDefiningIdeal :
    definingIdeal n =
      kostantGeneratedDefiningIdeal (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n) (latticeBasis n) := by
  rw [definingIdeal_def]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      _ _ _ _ _ _ _ (basisWeight n) (universalWeightTorus_mem_elementarySubgroup n)

/-- The full-weight type-`Bₙ₊₁` spin carrier is the group scheme generated by its numbered
positive and negative simple root subgroups. -/
theorem groupScheme_eq_kostantGeneratedGroupScheme :
    groupScheme n =
      kostantGeneratedGroupScheme (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n) (latticeBasis n) := by
  rw [groupScheme_eq_kostantToralGroupScheme]
  exact
    kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
      _ _ _ _ _ _ _ (basisWeight n) (universalWeightTorus_mem_elementarySubgroup n)

/-- The canonical inclusion of the root-generated type-`Bₙ₊₁` spin carrier into its toral closure
is an isomorphism. -/
instance isIso_kostantGeneratedToToral :
    CategoryTheory.IsIso (kostantGeneratedToToral
      (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
      (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
      (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
      (latticeBasis n) (basisWeight n)) :=
  isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary _ _ _ _ _ _ _ (basisWeight n)
    (universalWeightTorus_mem_elementarySubgroup n)

/-- After base change to any commutative ring, the transported type-`Bₙ₊₁` carrier ideal is the
transport of the root-generated integral ideal. This does not identify it with the common kernel
of the root-subgroup maps formed anew over that ring. -/
theorem baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal
    (A : Type v) [CommRing A] :
    baseChangeDefiningIdeal n A =
      kostantGeneratedGeneralLinearBaseChangeIdeal
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n) (latticeBasis n) A := by
  rw [baseChangeDefiningIdeal_def]
  exact kostantToralBaseChangePresentationIdeal_eq_generated_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ (basisWeight n) (universalWeightTorus_mem_elementarySubgroup n) A

open CategoryTheory in
/-- **Two morphisms out of the type-`Bₙ₊₁` spin carrier agree as soon as they agree on its
numbered root subgroups.** This drops the weight-torus hypothesis of
`TauCeti.TypeBSpinCarrier.groupScheme_hom_ext`, which root generation of the carrier makes
redundant. -/
@[ext high]
theorem groupScheme_hom_ext_of_rootSubgroup {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (f g : groupScheme n ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup n k ≫ f = rootSubgroup n k ≫ g) :
    f = g := by
  refine (cancel_epi (eqToHom (groupScheme_eq_kostantToralGroupScheme n).symm)).1 ?_
  refine kostantToralGroupScheme_hom_ext_of_isIso_kostantGeneratedToToral _ _ _ _ _ _ _
    (basisWeight n) _ _ fun k => ?_
  rw [← Category.assoc, ← Category.assoc, ← rootSubgroup_def, hroot k]

end TauCeti.TypeBSpinCarrier
