/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Category.GradedModuleCat.CartanMap.Basic
public import TauCeti.Algebra.Category.GradedModuleCat.Ideal

/-!
# The classes of the graded projectives `Af` in `K₀^gr(proj A)`

Let `A` be a `k`-algebra graded by `𝒜 : ℤ → Submodule k A`, and let `f` be an idempotent of `A`
for which the left ideal `Af` is homogeneous. The graded module
`TauCeti.GradedModuleCat.ofIdeal 𝒜 (Ideal.span {f}) hI` is generated by `f`, and its underlying
module is projective, being a direct summand of `A`. It is therefore an object of the
full subcategory `TauCeti.gradedFiniteProjectiveModules 𝒜` on which the graded Cartan map is
defined, and so it has a class `[Af]` in `K₀^gr(proj A)`.

This file records that membership only; it needs neither a base field nor finite-dimensionality
of `A`, which enter later when the graded Cartan map is read in idempotent coordinates
(`TauCeti.Algebra.Category.GradedModuleCat.CartanMap.Idempotent.Coordinate`).

## Main results

* `TauCeti.gradedFiniteProjectiveModules_ofIdeal_span_singleton`: the left ideal `Af` generated by
  an idempotent is a finite graded projective.

## References

* C. Năstăsescu and F. Van Oystaeyen, *Methods of Graded Rings*, Section 2.3, for graded modules
  and projectivity in the graded category.
* I. Assem, D. Simson, A. Skowroński, *Elements of the Representation Theory of Associative
  Algebras, Vol. 1*, Section I.4, for the projectives `Af`.
-/

public section

namespace TauCeti

universe uk uA

variable {k : Type uk} [CommRing k] {A : Type uA} [Ring A] [Algebra k A]
  {𝒜 : ℤ → Submodule k A} [GradedAlgebra 𝒜] {f : A}

/-- The left ideal `Af` generated by an idempotent is a finite graded projective, so it has a class
in `K₀^gr(proj A)`. -/
theorem gradedFiniteProjectiveModules_ofIdeal_span_singleton (hf : IsIdempotentElem f)
    (hI : (Ideal.span {f} : Ideal A).IsHomogeneous 𝒜) :
    gradedFiniteProjectiveModules 𝒜 (GradedModuleCat.ofIdeal 𝒜 (Ideal.span {f}) hI) :=
  gradedFiniteProjectiveModules_iff.2
    ⟨inferInstanceAs (Module.Finite A (Ideal.span {f} : Ideal A)), hf.projective_span_singleton⟩

end TauCeti
