/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.E7.Minuscule.BaseChange
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot

/-!
# Generation of the E₇ minuscule carrier by root subgroups

The type-`E₇` minuscule carrier is defined using both its fourteen numbered simple root
subgroups and its rank-seven weight torus. This file proves that, on the underlying
base-changed lattice over any commutative ring, the torus is already contained in the elementary
group generated by the root subgroups.

The represented simple generators at each node form an `sl₂` triple by
`TauCeti.E7Minuscule.isSl2Triple_rep_serreRootGenerator`. The remaining concrete input is
supplied here: every row of the type-`E₇` Cartan matrix contains `-1`, so its entries have an
explicit integral linear combination equal to one. The generic coroot-generation theorem then
puts every coordinate cocharacter, and hence the whole weight torus, in the elementary group.

The pointwise containment can be tested over the coordinate ring of the universal weight-torus
point. This proves that the root-generated and toral-closure defining ideals over `ℤ` are equal,
so the weight torus is also redundant scheme-theoretically. The equality persists after base
change. It does not say that the transported integral carrier equals the subgroup generated anew
over a non-flat base.

## Main results

* `TauCeti.E7Minuscule.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in the
  elementary subgroup over every commutative ring.
* `TauCeti.E7Minuscule.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining the
  weight torus to all numbered root subgroups gives exactly the elementary subgroup.
* `TauCeti.E7Minuscule.definingIdeal_eq_kostantGeneratedDefiningIdeal`: the integral
  toral-closure carrier is already the root-generated carrier.
* `TauCeti.E7Minuscule.groupScheme_eq_kostantGeneratedGroupScheme` and
  `TauCeti.E7Minuscule.isIso_kostantGeneratedToToral`: the corresponding group schemes agree and
  their canonical comparison is an isomorphism.
* `TauCeti.E7Minuscule.baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal`:
  the corresponding equality in the transported presentation over every commutative ring.
* `TauCeti.E7Minuscule.groupScheme_hom_ext_of_rootSubgroup`: a morphism out of the carrier is
  determined by its restrictions to the fourteen numbered root subgroups alone.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace TauCeti.E7Minuscule

open TauCeti.DynkinType TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "CM" => CartanMatrix.E 7
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => DynkinType.E7.rootGeneratorWeight DynkinType.valid_E7

private def cartanNeighbor : Fin 7 → Fin 7 :=
  ![2, 3, 0, 1, 3, 4, 5]

private def cartanBezout (i j : Fin 7) : ℤ :=
  if j = cartanNeighbor i then -1 else 0

private theorem cartan_sum_mul_bezout (i : Fin 7) :
    ∑ j, CM i j * cartanBezout i j = 1 := by
  fin_cases i <;> decide

private theorem rootWeight_sum_mul_bezout (i : Fin 7) :
    ∑ j, rootWeight (.inl i) j * cartanBezout i j = 1 := by
  have hweight (j : Fin 7) : rootWeight (.inl i) j = CM i j := by
    simpa only [DynkinType.rank_E7, DynkinType.cartanMatrix_E7] using
      (DynkinType.rootGeneratorWeight_inl (t := DynkinType.E7)
        (ht := DynkinType.valid_E7) i j)
  calc
    ∑ j, rootWeight (.inl i) j * cartanBezout i j =
        ∑ j, CM i j * cartanBezout i j := by
      apply Finset.sum_congr rfl
      intro j _
      rw [hweight j]
    _ = 1 := cartan_sum_mul_bezout i

private theorem rootWeight_inr_eq_neg_inl (i : Fin 7) :
    rootWeight (.inr i) = -rootWeight (.inl i) := by
  simpa only [DynkinType.rank_E7] using
    (DynkinType.rootGeneratorWeight_inr_eq_neg_root_simpleIndex
      (t := DynkinType.E7) (ht := DynkinType.valid_E7) i).trans
    (congrArg Neg.neg (DynkinType.rootGeneratorWeight_inl_eq_root_simpleIndex
      (t := DynkinType.E7) (ht := DynkinType.valid_E7) i).symm)

/-- Over every commutative ring, the type-`E₇` minuscule weight torus on the base-changed
admissible lattice is contained in the elementary group generated by the fourteen positive and
negative numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup lattice.toAddSubgroup
        latticeBasis e7MinusculeWeight A ≤
      kostantElementarySubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator A := by
  exact kostantTorusSubgroup_le_kostantElementarySubgroup
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
    isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
    Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl cartanBezout
    rootWeight_sum_mul_bezout A

/-- Over every commutative ring, adjoining the type-`E₇` minuscule weight torus to all fourteen
numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight Set.univ A =
      kostantElementarySubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator A := by
  exact
    kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
      isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
      Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl cartanBezout
      rootWeight_sum_mul_bezout A

/-! ## Scheme-theoretic generation -/

private theorem universalWeightTorus_mem_elementarySubgroup :
    let T := (DiagonalizableGroup.coordinateRing ℤ
      (SplitTorus.characterGroup (Fin 7))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin 7))) A :=
      WithConv.toConv (AlgHom.id ℤ T)
    kostantTorusPoints lattice.toAddSubgroup latticeBasis e7MinusculeWeight A
        (SplitTorus.pointsMulEquiv q) ∈
      kostantElementarySubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A := by
  dsimp only
  apply weightTorusSubgroup_le_elementarySubgroup _
  rw [kostantTorusSubgroup_eq_range]
  exact ⟨_, rfl⟩

/-- **The full-weight type-`E₇` toral closure is already generated scheme-theoretically by its
fourteen numbered root subgroups.** Equivalently, adjoining the represented weight torus does not
change the integral defining Hopf ideal. -/
theorem definingIdeal_eq_kostantGeneratedDefiningIdeal :
    definingIdeal =
      kostantGeneratedDefiningIdeal rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis := by
  rw [definingIdeal_def]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
      universalWeightTorus_mem_elementarySubgroup

/-- The type-`E₇` toral-closure group scheme is the group scheme generated by the fourteen
numbered root subgroups. -/
theorem groupScheme_eq_kostantGeneratedGroupScheme :
    groupScheme =
      kostantGeneratedGroupScheme rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis := by
  exact
    kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
      universalWeightTorus_mem_elementarySubgroup

/-- The canonical inclusion of the root-generated type-`E₇` carrier into its toral closure is an
isomorphism. -/
instance isIso_kostantGeneratedToToral :
    CategoryTheory.IsIso (kostantGeneratedToToral rootGen cartanGen rep lattice.toAddSubgroup
      rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
      e7MinusculeWeight) :=
  isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis e7MinusculeWeight universalWeightTorus_mem_elementarySubgroup

/-- After base change to any commutative ring, the transported type-`E₇` carrier ideal is the
transport of the root-generated integral ideal. This does not identify it with the common kernel
of the root-subgroup maps formed anew over that ring. -/
theorem baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal
    (A : Type v) [CommRing A] :
    baseChangeDefiningIdeal A =
      kostantGeneratedGeneralLinearBaseChangeIdeal rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis A := by
  rw [← kostantToralBaseChangePresentationIdeal_eq_generated_of_universal_torus_mem_elementary
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
    universalWeightTorus_mem_elementarySubgroup A]
  apply HopfIdeal.ext
  intro x
  rw [mem_baseChangeDefiningIdeal_iff, mem_kostantToralBaseChangePresentationIdeal_iff,
    kostantToralBaseChangeIdeal_def, definingIdeal_def]

open CategoryTheory in
/-- **Two morphisms out of the full-weight type-`E₇` minuscule carrier agree as soon as they
agree on its fourteen numbered root subgroups.** This drops the weight-torus hypothesis of
`TauCeti.E7Minuscule.groupScheme_hom_ext`, which root generation of the carrier makes
redundant. -/
@[ext high]
theorem groupScheme_hom_ext_of_rootSubgroup {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (f g : groupScheme ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup k ≫ f = rootSubgroup k ≫ g) :
    f = g :=
  kostantToralGroupScheme_hom_ext_of_isIso_kostantGeneratedToToral rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis e7MinusculeWeight f g fun k => by simpa only [rootSubgroup_def] using hroot k

end TauCeti.E7Minuscule
