/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Group.CrossedHom
public import Mathlib.Topology.Algebra.Group.Subgroup
public import Mathlib.Topology.Separation.Hausdorff

/-!
# Uniqueness of continuous crossed homomorphisms

Two continuous crossed homomorphisms into a Hausdorff, additively cancellative semiring are equal
if they have the same unit-valued twist and agree on a topological generating set. No
multiplicativity or continuity of the twist, or continuity of the semiring operations, is needed.
Their agreement propagates to the subgroup generated by the set and then to its topological
closure by continuity.

The algebraic calculus is developed in `TauCeti/Algebra/Group/CrossedHom.lean`. For a continuous
character `χ : G →ₜ* ℤ_pˣ` of a pro-`p` group, continuous crossed homomorphisms `G → ℤ_p` are the
compatible systems of continuous `1`-cocycles with values in the twisted coefficients `I(χ)/pⁱ`.
Their values on a minimal generating tuple are what Labute's prescription property prescribes.

## Main results

* `TauCeti.IsCrossedHom.eq_of_eqOn_of_topologicalClosure_closure_eq_top`: two continuous crossed
  homomorphisms agreeing on a topological generating set are equal.

## References

* J.-P. Serre, *Galois Cohomology*, Ch. I, §2.3.
* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, §2.
-/

public section

namespace TauCeti.IsCrossedHom

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
  {R : Type*} [Semiring R] [IsLeftCancelAdd R] [TopologicalSpace R] [T2Space R]
  {χ : H → Rˣ}

/-- Two continuous crossed homomorphisms for the same unit-valued twist agreeing on a topological
generating set are equal. -/
theorem eq_of_eqOn_of_topologicalClosure_closure_eq_top {F₁ F₂ : H → R} (h₁ : IsCrossedHom χ F₁)
    (h₂ : IsCrossedHom χ F₂) (hc₁ : Continuous F₁) (hc₂ : Continuous F₂) {s : Set H}
    (hs : (Subgroup.closure s).topologicalClosure = ⊤) (h : Set.EqOn F₁ F₂ s) : F₁ = F₂ := by
  have heq : Set.EqOn F₁ F₂ (Subgroup.closure s) := by
    intro g hg
    induction hg using Subgroup.closure_induction with
    | mem x hx => exact h hx
    | one => rw [h₁.map_one, h₂.map_one]
    | mul x y _ _ ihx ihy => rw [h₁.map_mul, h₂.map_mul, ihx, ihy]
    | inv x _ ih =>
      apply (χ x).mul_right_inj.mp
      apply add_left_cancel (a := F₁ x)
      calc F₁ x + (χ x : R) * F₁ x⁻¹ = 0 := by
             rw [add_comm, ← h₁.map_mul, mul_inv_cancel, h₁.map_one]
           _ = F₁ x + (χ x : R) * F₂ x⁻¹ := by
             rw [ih, add_comm, ← h₂.map_mul, mul_inv_cancel, h₂.map_one]
  refine Continuous.ext_on ?_ hc₁ hc₂ heq
  rw [dense_iff_closure_eq, ← Subgroup.topologicalClosure_coe, hs, Subgroup.coe_top]

end TauCeti.IsCrossedHom
