/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Unramified.Coordinate
import TauCeti.Topology.Algebra.Group.Profinite.ZHat.Decomposition

/-!
# The local Weil group

Let `K` be a nonarchimedean local field, `G_K = Field.absoluteGaloisGroup K` its absolute Galois
group, `I_K = TauCeti.inertiaSubgroup K` the inertia subgroup and `K^{ur}` the maximal unramified
extension, so that `1 → I_K → G_K → Gal(K^{ur}/K) → 1` is exact and `Gal(K^{ur}/K) ≃ ℤ̂` carries
arithmetic Frobenius to the canonical generator. The **local Weil group**

`TauCeti.ClassFieldTheory.localWeilGroup K ≤ G_K`

consists of the elements acting on `K^{ur}` as an *integral* power of arithmetic Frobenius: it is
the preimage of `ℤ ⊆ ℤ̂`. It contains inertia, it is normal, and it is generated by inertia
together with any single arithmetic Frobenius lift. Since `ℤ` is dense in `ℤ̂` but not all of it,
`W_K` is a dense proper subgroup of `G_K`.

The degree `weilDegree K : WeilGroup K →* Multiplicative ℤ` records which power of Frobenius an
element induces on `K^{ur}`; it is normalized arithmetically, so that the arithmetic Frobenius
lifts are exactly the elements of degree `1`. It is surjective with kernel inertia, giving the
exact sequence `1 → I_K → W_K → ℤ → 1`, and its image in `ℤ̂` is the unramified coordinate.

The Weil group is wanted as a locally compact group in which `I_K`, with its profinite topology,
is open. That is not the subspace topology of `G_K`: inertia is not open in `G_K`
(`TauCeti.not_isOpen_inertiaSubgroup`), because its image `{1}` in `ℤ̂` is not open. The degree
map is therefore stated on the type synonym `WeilGroup K` of `localWeilGroup K`, which does not
inherit the subspace topology of the subtype; `weilGroupEquivLocalWeilGroup K` identifies the two
as groups.

## Main definitions

* `TauCeti.ClassFieldTheory.localWeilGroup K`: the local Weil group, as a subgroup of `G_K`.
* `TauCeti.ClassFieldTheory.WeilGroup K`: a type synonym for `localWeilGroup K`, with its
  inclusion `weilToAbsolute K : WeilGroup K →* G_K` and the group isomorphism
  `weilGroupEquivLocalWeilGroup K : WeilGroup K ≃* localWeilGroup K`.
* `TauCeti.ClassFieldTheory.weilDegree K : WeilGroup K →* Multiplicative ℤ`: the degree.
* `TauCeti.ClassFieldTheory.inertiaToWeil K : I_K →* W_K`: the inclusion of inertia.

## Main results

* `TauCeti.ClassFieldTheory.mem_localWeilGroup_iff`,
  `TauCeti.ClassFieldTheory.mem_localWeilGroup_iff_unramifiedCoordinate`: `σ ∈ W_K` exactly when
  `σ` acts on `K^{ur}` as an integral power of Frobenius, exactly when its unramified coordinate
  lies in `ℤ ⊆ ℤ̂`.
* `TauCeti.ClassFieldTheory.inertiaSubgroup_le_localWeilGroup`,
  `TauCeti.ClassFieldTheory.localWeilGroup_normal`: `I_K ≤ W_K`, and `W_K` is normal in `G_K`.
* `TauCeti.IsArithFrobeniusLift.zpowers_sup_inertiaSubgroup`: `W_K = ⟨σ⟩ I_K` for every
  arithmetic Frobenius lift `σ`.
* `TauCeti.ClassFieldTheory.dense_localWeilGroup`,
  `TauCeti.ClassFieldTheory.localWeilGroup_ne_top`: `W_K` is dense and proper in `G_K`.
* `TauCeti.ClassFieldTheory.surjective_weilDegree`, `TauCeti.ClassFieldTheory.ker_weilDegree`:
  the exact sequence `1 → I_K → W_K → ℤ → 1`.
* `TauCeti.ClassFieldTheory.range_inertiaToWeil`: the image of inertia in `W_K` is the kernel of
  the degree.
* `TauCeti.ClassFieldTheory.unramifiedCoordinate_weilDegree`,
  `TauCeti.ClassFieldTheory.weilDegree_eq_ofAdd_one_iff`: the degree is the unramified coordinate,
  and the elements of degree `1` are the arithmetic Frobenius lifts.

## References

* A. Weil, *Sur la théorie du corps de classes*, J. Math. Soc. Japan 3 (1951).
* J. Tate, *Number theoretic background*, in *Automorphic forms, representations and
  L-functions*, Proc. Sympos. Pure Math. 33, Part 2 (1979), §1.4.
-/

public section

noncomputable section

namespace TauCeti.ClassFieldTheory

universe u

variable (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-! ### The carrier -/

/-- **The local Weil group** `W_K ≤ G_K` of a nonarchimedean local field `K`: the elements of the
absolute Galois group acting on the maximal unramified extension `K^{ur}` as an integral power of
arithmetic Frobenius. Through `Gal(K^{ur}/K) ≃ ℤ̂` it is the preimage of `ℤ ⊆ ℤ̂`
(`mem_localWeilGroup_iff_unramifiedCoordinate`). -/
def localWeilGroup : Subgroup (Field.absoluteGaloisGroup K) :=
  (Subgroup.zpowers (maximalUnramifiedFrobenius K (AlgebraicClosure K))).comap
    (restrictMaximalUnramifiedHom K)

/-- The local Weil group is the preimage of the powers of arithmetic Frobenius under restriction to
the maximal unramified extension. -/
theorem localWeilGroup_def :
    localWeilGroup K =
      (Subgroup.zpowers (maximalUnramifiedFrobenius K (AlgebraicClosure K))).comap
        (restrictMaximalUnramifiedHom K) :=
  -- `(rfl)`, not `rfl`: keep the body opaque while exporting this equation across modules.
  (rfl)

variable {K}

/-- `σ` lies in the local Weil group exactly when it acts on the maximal unramified extension as an
integral power of arithmetic Frobenius. -/
theorem mem_localWeilGroup_iff {σ : Field.absoluteGaloisGroup K} :
    σ ∈ localWeilGroup K ↔
      ∃ n : ℤ, restrictMaximalUnramifiedHom K σ =
        maximalUnramifiedFrobenius K (AlgebraicClosure K) ^ n := by
  rw [localWeilGroup_def, Subgroup.mem_comap, Subgroup.mem_zpowers_iff]
  exact exists_congr fun _ ↦ eq_comm

/-- **The Weil group is the preimage of `ℤ ⊆ ℤ̂`**: `σ` lies in the local Weil group exactly when
the unramified coordinate of its class in `G_K^{ab}` is an integer. -/
theorem mem_localWeilGroup_iff_unramifiedCoordinate {σ : Field.absoluteGaloisGroup K} :
    σ ∈ localWeilGroup K ↔
      unramifiedCoordinate K (σ : Field.absoluteGaloisGroupAbelianization K) ∈
        (zHat.ofInt : Multiplicative ℤ →* zHat.{u}).range := by
  simp_rw [mem_localWeilGroup_iff, MonoidHom.mem_range, eq_comm (b := unramifiedCoordinate K _),
    ← unramifiedCoordinate_mk_eq_gen_zpow_iff, Multiplicative.exists, zHat.ofInt_ofAdd]

variable (K) in
/-- **Inertia lies in the Weil group**, as the elements acting trivially on `K^{ur}`. -/
theorem inertiaSubgroup_le_localWeilGroup : inertiaSubgroup K ≤ localWeilGroup K := fun σ hσ ↦
  mem_localWeilGroup_iff.2 ⟨0, by
    rwa [zpow_zero, ← MonoidHom.mem_ker, ker_restrictMaximalUnramifiedHom]⟩

/-- An arithmetic Frobenius lift lies in the Weil group. -/
theorem _root_.TauCeti.IsArithFrobeniusLift.mem_localWeilGroup {σ : Field.absoluteGaloisGroup K}
    (hσ : IsArithFrobeniusLift K σ) : σ ∈ localWeilGroup K :=
  mem_localWeilGroup_iff.2 ⟨1, by rw [zpow_one, isArithFrobeniusLift_def.1 hσ]⟩

/-- **The Weil group is generated by a Frobenius lift and inertia**: for every arithmetic Frobenius
lift `σ`, the subgroup generated by `σ` and `I_K` is `W_K`. -/
theorem _root_.TauCeti.IsArithFrobeniusLift.zpowers_sup_inertiaSubgroup
    {σ : Field.absoluteGaloisGroup K} (hσ : IsArithFrobeniusLift K σ) :
    Subgroup.zpowers σ ⊔ inertiaSubgroup K = localWeilGroup K := by
  refine le_antisymm (sup_le (Subgroup.zpowers_le.2 hσ.mem_localWeilGroup)
    (inertiaSubgroup_le_localWeilGroup K)) fun τ hτ ↦ ?_
  obtain ⟨n, hn⟩ := mem_localWeilGroup_iff.1 hτ
  -- `σ ^ n` and `τ` agree on `K^{ur}`, so `τ = σ ^ n * (σ ^ (-n) * τ)` with the second factor in
  -- inertia.
  have hI : (σ ^ n)⁻¹ * τ ∈ inertiaSubgroup K := by
    rw [← ker_restrictMaximalUnramifiedHom, MonoidHom.mem_ker, map_mul, map_inv, map_zpow,
      isArithFrobeniusLift_def.1 hσ, hn, inv_mul_cancel]
  simpa using Subgroup.mul_mem_sup (Subgroup.zpow_mem_zpowers σ n) hI

variable (K)

open scoped IsMulCommutative in
/-- **The Weil group is normal** in `G_K`, being the preimage of a subgroup of the abelian group
`Gal(K^{ur}/K)`. -/
instance localWeilGroup_normal : (localWeilGroup K).Normal := by
  rw [localWeilGroup_def]
  exact Subgroup.Normal.comap inferInstance _

/-- **The Weil group is dense** in `G_K`: its closure contains every Frobenius lift and inertia, and
these generate `G_K` topologically. -/
theorem dense_localWeilGroup :
    Dense (localWeilGroup K : Set (Field.absoluteGaloisGroup K)) := by
  obtain ⟨σ, hσ⟩ := exists_isArithFrobeniusLift K
  rw [dense_iff_closure_eq, ← Subgroup.topologicalClosure_coe, ← hσ.zpowers_sup_inertiaSubgroup,
    hσ.topologicalClosure_zpowers_sup_inertiaSubgroup, Subgroup.coe_top]

/-- **The Weil group is a proper subgroup** of `G_K`, since `ℤ ≠ ℤ̂`. -/
theorem localWeilGroup_ne_top : localWeilGroup K ≠ ⊤ := fun h ↦ by
  set e := maximalUnramifiedGaloisGroupEquivZHat K (AlgebraicClosure K)
  refine zHat.not_surjective_ofInt fun z ↦ ?_
  obtain ⟨σ, hσ⟩ := restrictMaximalUnramifiedHom_surjective K (e.symm z)
  obtain ⟨n, hn⟩ := mem_localWeilGroup_iff.1 (h ▸ Subgroup.mem_top σ)
  refine ⟨Multiplicative.ofAdd n, e.symm.injective ?_⟩
  rw [maximalUnramifiedGaloisGroupEquivZHat_symm_apply_ofInt, ← hn, hσ]

/-! ### The Weil group as a type, and its degree -/

/-- **The local Weil group as a type**: a type synonym for `localWeilGroup K`. It carries the group
structure of the subgroup, but deliberately not the subspace topology of `G_K`, in which inertia is
not open (`not_isOpen_inertiaSubgroup`). -/
def WeilGroup : Type u := localWeilGroup K

instance : Group (WeilGroup K) := inferInstanceAs (Group (localWeilGroup K))

/-- The inclusion `W_K → G_K` of the Weil group into the absolute Galois group. -/
def weilToAbsolute : WeilGroup K →* Field.absoluteGaloisGroup K :=
  (localWeilGroup K).subtype

/-- **The Weil group as a type is the local Weil group**: the group isomorphism
`WeilGroup K ≃* localWeilGroup K`, under which the inclusion `weilToAbsolute K` is the subgroup
inclusion (`coe_weilGroupEquivLocalWeilGroup`). -/
def weilGroupEquivLocalWeilGroup : WeilGroup K ≃* localWeilGroup K :=
  MulEquiv.refl (localWeilGroup K)

/-- The isomorphism `WeilGroup K ≃* localWeilGroup K` is compatible with the inclusions into
`G_K`. -/
@[simp]
theorem coe_weilGroupEquivLocalWeilGroup (w : WeilGroup K) :
    (weilGroupEquivLocalWeilGroup K w : Field.absoluteGaloisGroup K) = weilToAbsolute K w :=
  (rfl)

/-- The element of the Weil group corresponding to `σ ∈ localWeilGroup K` maps to `σ` in `G_K`. -/
@[simp]
theorem weilToAbsolute_weilGroupEquivLocalWeilGroup_symm (σ : localWeilGroup K) :
    weilToAbsolute K ((weilGroupEquivLocalWeilGroup K).symm σ) = σ :=
  (rfl)

/-- The inclusion of the Weil group into `G_K` is injective. -/
theorem injective_weilToAbsolute : Function.Injective (weilToAbsolute K) :=
  Subtype.val_injective

/-- The image of the inclusion `W_K → G_K` is the local Weil group. -/
@[simp]
theorem range_weilToAbsolute : (weilToAbsolute K).range = localWeilGroup K :=
  Subgroup.range_subtype _

variable {K} in
/-- An element of the Weil group lies in the local Weil group of `G_K`. -/
@[simp]
theorem weilToAbsolute_mem_localWeilGroup (w : WeilGroup K) :
    weilToAbsolute K w ∈ localWeilGroup K := by
  rw [← range_weilToAbsolute]
  exact ⟨w, rfl⟩

/-- `n ↦ Frob ^ n` is injective, since arithmetic Frobenius has infinite order. -/
private theorem injective_zpowersHom_maximalUnramifiedFrobenius :
    Function.Injective
      (zpowersHom _ (maximalUnramifiedFrobenius K (AlgebraicClosure K))) := fun _ _ h ↦
  Multiplicative.toAdd.injective (injective_zpow_iff_not_isOfFinOrder.2
    (not_isOfFinOrder_maximalUnramifiedFrobenius K (AlgebraicClosure K)) h)

/-- **The degree of the Weil group**: `w ∈ W_K` has degree `n` when it acts on the maximal
unramified extension as the `n`-th power of arithmetic Frobenius
(`restrictMaximalUnramifiedHom_weilToAbsolute`). -/
def weilDegree : WeilGroup K →* Multiplicative ℤ :=
  ((MulEquiv.subgroupCongr (Subgroup.range_zpowersHom _).symm).trans
      (MonoidHom.ofInjective (injective_zpowersHom_maximalUnramifiedFrobenius K)).symm :
      _ →* _).comp
    ((restrictMaximalUnramifiedHom K).subgroupComap _)

variable {K}

/-- **The characterization of the degree**: an element of degree `n` acts on the maximal
unramified extension as the `n`-th power of arithmetic Frobenius. -/
theorem restrictMaximalUnramifiedHom_weilToAbsolute (w : WeilGroup K) :
    restrictMaximalUnramifiedHom K (weilToAbsolute K w) =
      maximalUnramifiedFrobenius K (AlgebraicClosure K) ^ (weilDegree K w).toAdd := by
  have := MonoidHom.apply_ofInjective_symm (injective_zpowersHom_maximalUnramifiedFrobenius K)
    ((MulEquiv.subgroupCongr (Subgroup.range_zpowersHom _).symm)
      ((restrictMaximalUnramifiedHom K).subgroupComap _ w))
  rw [zpowersHom_apply] at this
  exact this.symm

/-- The degree of `w` is `n` exactly when `w` acts on the maximal unramified extension as the
`n`-th power of arithmetic Frobenius. -/
theorem weilDegree_eq_iff {w : WeilGroup K} {n : Multiplicative ℤ} :
    weilDegree K w = n ↔
      restrictMaximalUnramifiedHom K (weilToAbsolute K w) =
        maximalUnramifiedFrobenius K (AlgebraicClosure K) ^ n.toAdd := by
  rw [restrictMaximalUnramifiedHom_weilToAbsolute, ← zpowersHom_apply, ← zpowersHom_apply,
    (injective_zpowersHom_maximalUnramifiedFrobenius K).eq_iff]

/-- **Arithmetic normalization of the degree**: the elements of degree `1` are exactly the
arithmetic Frobenius lifts. -/
theorem weilDegree_eq_ofAdd_one_iff {w : WeilGroup K} :
    weilDegree K w = Multiplicative.ofAdd 1 ↔ IsArithFrobeniusLift K (weilToAbsolute K w) := by
  rw [weilDegree_eq_iff, toAdd_ofAdd, zpow_one, isArithFrobeniusLift_def]

/-- **The degree is the unramified coordinate**: the unramified coordinate of the class of `w` in
`G_K^{ab}` is the image in `ℤ̂` of the degree of `w`. -/
theorem unramifiedCoordinate_weilDegree (w : WeilGroup K) :
    unramifiedCoordinate K (weilToAbsolute K w : Field.absoluteGaloisGroupAbelianization K) =
      zHat.ofInt (weilDegree K w) := by
  rw [← ofAdd_toAdd (weilDegree K w), zHat.ofInt_ofAdd, unramifiedCoordinate_mk_eq_gen_zpow_iff,
    restrictMaximalUnramifiedHom_weilToAbsolute]

variable (K)

/-- **Exactness on the right**: every integer is the degree of an element of the Weil group, for
instance of a power of an arithmetic Frobenius lift. -/
theorem surjective_weilDegree : Function.Surjective (weilDegree K) := fun n ↦ by
  obtain ⟨σ, hσ⟩ := exists_isArithFrobeniusLift K
  obtain ⟨w, hw⟩ : σ ^ n.toAdd ∈ (weilToAbsolute K).range := by
    rw [range_weilToAbsolute]
    exact zpow_mem hσ.mem_localWeilGroup _
  exact ⟨w, weilDegree_eq_iff.2 (by rw [hw, map_zpow, isArithFrobeniusLift_def.1 hσ])⟩

/-- **Exactness in the middle**: the kernel of the degree is inertia. With `surjective_weilDegree`
and `injective_weilToAbsolute`, this is the exact sequence `1 → I_K → W_K → ℤ → 1`. -/
theorem ker_weilDegree :
    (weilDegree K).ker = (inertiaSubgroup K).comap (weilToAbsolute K) := by
  ext w
  rw [MonoidHom.mem_ker, weilDegree_eq_iff, toAdd_one, zpow_zero, Subgroup.mem_comap,
    ← ker_restrictMaximalUnramifiedHom, MonoidHom.mem_ker]

/-! ### Inertia in the Weil group -/

/-- **The inclusion of inertia into the Weil group**. -/
def inertiaToWeil : inertiaSubgroup K →* WeilGroup K :=
  Subgroup.inclusion (inertiaSubgroup_le_localWeilGroup K)

variable {K} in
/-- An element of inertia maps to itself under `I_K → W_K → G_K`. -/
@[simp]
theorem weilToAbsolute_inertiaToWeil (σ : inertiaSubgroup K) :
    weilToAbsolute K (inertiaToWeil K σ) = σ :=
  (rfl)

variable {K} in
/-- An element of inertia has trivial degree in the Weil group. -/
@[simp]
theorem weilDegree_inertiaToWeil (σ : inertiaSubgroup K) : weilDegree K (inertiaToWeil K σ) = 1 :=
  (ker_weilDegree K).ge (by simp)

/-- The image of inertia in the Weil group is the preimage of `I_K` under `W_K → G_K`, that is,
the kernel of the degree (`ker_weilDegree`). -/
theorem range_inertiaToWeil :
    (inertiaToWeil K).range = (inertiaSubgroup K).comap (weilToAbsolute K) :=
  (Subgroup.inclusion_range _).trans (Subgroup.comap_subtype _ _).symm

end TauCeti.ClassFieldTheory
