/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.IntegerRing.Basic
import TauCeti.NumberTheory.LocalField.InertiaDegree
import TauCeti.RingTheory.DiscreteValuationRing.Monogenic
import TauCeti.RingTheory.LocalRing.Monogenic

/-!
# Integral generators of finite local-field extensions

The integer ring of a finite extension of nonarchimedean local fields is generated by one
integral element over the base integer ring. An integral power basis can be chosen whose
generator also generates the field extension and whose length is the field degree. These results
let ramification and different computations use a generator without imposing a separate
monogenicity hypothesis. When the extension is totally ramified, every uniformizer `ϖ` of `L` is
such a generator, so `1, ϖ, …, ϖ^{e - 1}` is a basis of `𝒪[L]` over `𝒪[K]`, with `e = [L : K]`.
In that basis the additive valuation of an element of `𝒪[L]` is read off from its coordinates.

## Main results

* `TauCeti.exists_integerRing_adjoin_eq_top`: `𝒪[L]` is monogenic over `𝒪[K]`.
* `TauCeti.IsTotallyRamified.integralPowerBasis`: the power basis of `𝒪[L]` over `𝒪[K]` generated
  by a uniformizer of a totally ramified extension, of length `e(L/K)`.
* `TauCeti.IsTotallyRamified.addVal_eq_iInf_integralPowerBasis_repr`: the additive valuation of
  `x ∈ 𝒪[L]` is the least of `e(L/K) · v_K(a_i) + i` over the coordinates `a_i` of `x` in that
  basis.

## References

* J.-P. Serre, *Corps Locaux*, Chapter I, §6, Proposition 18.
* J.-P. Serre, *Corps Locaux*, Chapter III, §6, Proposition 12.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing

namespace TauCeti

variable (K L : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]

/-- The integer ring of a finite extension of nonarchimedean local fields is generated as an
algebra over the base integer ring by one element. -/
theorem exists_integerRing_adjoin_eq_top :
    ∃ x : 𝒪[L], Algebra.adjoin 𝒪[K] {x} = ⊤ := by
  exact IsDiscreteValuationRing.exists_adjoin_eq_top (R := 𝒪[K]) (S := 𝒪[L])

/-- The integer ring of a finite local-field extension has an integral power basis whose
generator also generates the field extension. Its length is `[L : K]`. -/
theorem exists_integerRing_powerBasis_intermediateField_adjoin_eq_top_and_dim_eq_finrank :
    ∃ pb : PowerBasis 𝒪[K] 𝒪[L],
      IntermediateField.adjoin K {((pb.gen : 𝒪[L]) : L)} = ⊤ ∧
      pb.dim = Module.finrank K L := by
  obtain ⟨pb, hpb⟩ := IsDiscreteValuationRing.exists_powerBasis_intermediateField_adjoin_eq_top
    (R := 𝒪[K]) (S := 𝒪[L]) K L
  refine ⟨pb, hpb, ?_⟩
  rw [← pb.finrank, finrank_integerRing K L]

variable {K L}

/-- In a totally ramified extension of nonarchimedean local fields, every uniformizer of `L`
generates `𝒪[L]` as an `𝒪[K]`-algebra. -/
theorem IsTotallyRamified.adjoin_eq_top_of_irreducible (h : IsTotallyRamified K L) {ϖ : 𝒪[L]}
    (hϖ : Irreducible ϖ) : Algebra.adjoin 𝒪[K] {ϖ} = ⊤ :=
  IsLocalRing.adjoin_eq_top_of_algebraMap_residueField_surjective_of_span_eq_maximalIdeal
    ((isTotallyRamified_iff_surjective_algebraMap_residueField K L).1 h) hϖ.maximalIdeal_eq.symm

/-- **The integral power basis of a totally ramified extension.** In a totally ramified extension
`L/K` of nonarchimedean local fields, the powers `1, ϖ, …, ϖ^{e - 1}` of a uniformizer `ϖ` of `L`
form a basis of `𝒪[L]` over `𝒪[K]`, where `e = e(L/K) = [L : K]`. -/
noncomputable def IsTotallyRamified.integralPowerBasis (h : IsTotallyRamified K L) {ϖ : 𝒪[L]}
    (hϖ : Irreducible ϖ) : PowerBasis 𝒪[K] 𝒪[L] :=
  PowerBasis.ofAdjoinEqTop' (IsIntegral.of_finite 𝒪[K] ϖ) (h.adjoin_eq_top_of_irreducible hϖ)

/-- The integral power basis of a totally ramified extension is generated by the chosen
uniformizer. -/
@[simp]
theorem IsTotallyRamified.integralPowerBasis_gen (h : IsTotallyRamified K L) {ϖ : 𝒪[L]}
    (hϖ : Irreducible ϖ) : (h.integralPowerBasis hϖ).gen = ϖ :=
  PowerBasis.ofAdjoinEqTop'_gen ..

/-- The integral power basis of a totally ramified extension has length `e(L/K)`. -/
@[simp]
theorem IsTotallyRamified.integralPowerBasis_dim (h : IsTotallyRamified K L) {ϖ : 𝒪[L]}
    (hϖ : Irreducible ϖ) : (h.integralPowerBasis hϖ).dim = ramificationIndex K L := by
  rw [← PowerBasis.finrank, finrank_integerRing,
    (isTotallyRamified_iff_ramificationIndex_eq_finrank K L).1 h]

/-- **Valuations in the integral power basis.** In a totally ramified extension `L/K` with
uniformizer `ϖ`, the additive valuation of `x ∈ 𝒪[L]` is the least of `e(L/K) · v_K(a_i) + i`,
where `x = ∑ a_i ϖ^i` is the expansion of `x` in the integral power basis. -/
theorem IsTotallyRamified.addVal_eq_iInf_integralPowerBasis_repr (h : IsTotallyRamified K L)
    {ϖ : 𝒪[L]} (hϖ : Irreducible ϖ) (x : 𝒪[L]) :
    IsDiscreteValuationRing.addVal 𝒪[L] x =
      ⨅ i, ramificationIndex K L •
        IsDiscreteValuationRing.addVal 𝒪[K] ((h.integralPowerBasis hϖ).basis.repr x i) +
          (i : ℕ) := by
  conv_lhs =>
    rw [← (h.integralPowerBasis hϖ).basis.sum_repr x]
    simp only [PowerBasis.coe_basis, h.integralPowerBasis_gen, Algebra.smul_def]
  exact addVal_sum_algebraMap_mul_pow_of_irreducible hϖ (h.integralPowerBasis_dim hϖ).le _

end TauCeti
