/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.FiniteDimensional
public import TauCeti.Algebra.Lie.HighestWeight.Weight.Lattice
public import TauCeti.Algebra.Lie.HighestWeight.Weyl.Character
public import TauCeti.LinearAlgebra.RootSystem.Weyl.Dimension

/-!
# The Weyl dimension formula

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero, `H` a Cartan subalgebra, `b` a base of its root system with
Weyl vector `ρ`, and `M` a finite-dimensional module generated by a highest weight vector of
weight `lam`. **The Weyl dimension formula** computes the dimension of `M`:

`dim M = ∏_{α>0} ⟨lam + ρ, α^∨⟩ / ⟨ρ, α^∨⟩`.

Every factor is a quotient of integers, the coroot pairings `TauCeti.coweightPairing` of the
integral weights `lam + ρ` and `ρ`, and the denominators are nonzero, so the identity is stated
in `ℚ`; in its division-free form `dim M · ∏_{α>0} ⟨ρ, α^∨⟩ = ∏_{α>0} ⟨lam + ρ, α^∨⟩` it is an
identity of integers.

The formula is the specialization of the Weyl character formula
`TauCeti.formalCharacter_mul_weylDenominator_eq_weylNumerator` along the exponential
`e^ν ↦ e^{⟨ρ, ν⟩ X}`, and that specialization is carried out for an abstract root pairing in
`TauCeti/LinearAlgebra/RootSystem/Weyl/Dimension.lean`. The root-pairing statement compares two
character identities, `ch M · Δ = N(lam)` and `ch L(0) · Δ = N(0)`; this file supplies both from
the character formula, the second for the one-dimensional module `L(0)`
(`TauCeti.finrank_irreducibleQuotient_zero`), reads the sums of coefficients as dimensions, and
passes from the field `K` to the integers through `TauCeti.intCast_coweightPairing`.

## Main results

* `TauCeti.finrank_mul_prod_coweightPairing_weylVector_eq`: the division-free form
  `dim M · ∏_{α>0} ⟨ρ, α^∨⟩ = ∏_{α>0} ⟨lam + ρ, α^∨⟩` of the dimension formula, in `ℤ`.
* `TauCeti.finrank_eq_prod_coweightPairing_div`: **the Weyl dimension formula**
  `dim M = ∏_{α>0} ⟨lam + ρ, α^∨⟩ / ⟨ρ, α^∨⟩`, in `ℚ`.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §24.3.
* W. Fulton and J. Harris, *Representation Theory: A First Course*, GTM 129, §24.2.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M] {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

section HighestWeightModule

variable (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)

include hv hgen

/-- **The Weyl dimension formula, division-free.** For a finite-dimensional module `M` generated
by a highest weight vector of weight `lam`,

`dim M · ∏_{α>0} ⟨ρ, α^∨⟩ = ∏_{α>0} ⟨lam + ρ, α^∨⟩`,

an identity of integers, the coroot pairings being those of the integral weights `ρ` and
`lam + ρ`. -/
theorem finrank_mul_prod_coweightPairing_weylVector_eq :
    (finrank K M : ℤ) *
        ∏ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
          coweightPairing (weylVector (IsKilling.rootSystem H) b) i
      = ∏ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
          coweightPairing (lam + weylVector (IsKilling.rootSystem H) b) i := by
  have _ := RootPairing.finite_weylGroup (IsKilling.rootSystem H)
  let _ := Fintype.ofFinite (IsKilling.rootSystem H).weylGroup
  have hρ : IsIntegralWeight (weylVector (IsKilling.rootSystem H) b) :=
    isDominantIntegral_weylVector.isIntegralWeight
  have hlam : IsIntegralWeight (lam + weylVector (IsKilling.rootSystem H) b) :=
    hv.isDominantIntegral.isIntegralWeight.add hρ
  -- The character formula for `L(0)`, the second input of the root-pairing statement.
  have _ := finiteDimensional_irreducibleQuotient_of_isDominantIntegral
    (isDominantIntegral_zero (b := b))
  have hg := formalCharacter_mul_weylDenominator_eq_weylNumerator
    (isHighestWeightVector_irreducibleQuotientGenerator b (0 : Dual K H))
    (lieSpan_irreducibleQuotientGenerator_eq_top b 0)
  have key := sum_coeff_mul_prod_coroot'_weylVector_eq (IsKilling.rootSystem H) b
    rootInvariantForm (formalCharacter_mul_weylDenominator_eq_weylNumerator hv hgen) hg
  rw [sum_formalCharacter_coeff_eq_finrank, sum_formalCharacter_coeff_eq_finrank,
    finrank_irreducibleQuotient_zero b] at key
  apply Int.cast_injective (α := K)
  push_cast at key ⊢
  simpa only [intCast_coweightPairing hρ, intCast_coweightPairing hlam, rootSystem_coroot'_apply,
    one_mul] using key

/-- **The Weyl dimension formula.** For a finite-dimensional module `M` generated by a highest
weight vector of weight `lam`,

`dim M = ∏_{α>0} ⟨lam + ρ, α^∨⟩ / ⟨ρ, α^∨⟩`,

the product running over the positive roots, with `ρ` the Weyl vector of the base and
`⟨·, α^∨⟩` the integer coroot pairing `TauCeti.coweightPairing`. Such an `M` is irreducible, so
this is the dimension of `L(lam)` for every dominant integral weight `lam` at which `L(lam)` is
nonzero. -/
theorem finrank_eq_prod_coweightPairing_div :
    (finrank K M : ℚ)
      = ∏ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
          (coweightPairing (lam + weylVector (IsKilling.rootSystem H) b) i : ℚ) /
            (coweightPairing (weylVector (IsKilling.rootSystem H) b) i : ℚ) := by
  have hne : ∏ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
      (coweightPairing (weylVector (IsKilling.rootSystem H) b) i : ℚ) ≠ 0 :=
    Finset.prod_ne_zero_iff.mpr fun i _ ↦ by exact_mod_cast coweightPairing_weylVector_ne_zero i
  rw [Finset.prod_div_distrib, eq_div_iff hne]
  exact_mod_cast finrank_mul_prod_coweightPairing_weylVector_eq hv hgen

end HighestWeightModule

end TauCeti
