/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Subsystem.BaseChange
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel.Flat
public import TauCeti.AlgebraicGeometry.AffineGroupScheme.HopfSpec

/-!
# Flatness of torus and root-subsystem carriers

The closed subgroup scheme generated by a represented weight torus and any selected set of
Kostant root subgroups has torsion-free coordinate algebra over `ℤ`, hence is flat over `ℤ`.
This follows from the common-kernel criterion: the generator maps have additive groups and
a split torus as their sources, all with torsion-free coordinate algebras.

Only the selected root operators are required to be nilpotent. The structural morphism is flat,
and the coordinate algebra presented by the base-change ideal is flat over every commutative
base ring. The result applies in particular to the positive carrier used in constructing a pinning.
-/

public section

open AlgebraicGeometry

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

-- Use the scalar module of the coordinate algebra in the quotient flatness criterion.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]
variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M) (wt : Fin n → κ → ℤ)
variable (S : Set I)
variable (hnilS : ∀ i : S, IsNilpotent
  (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))

/-- The closed carrier generated by the weight torus and the selected root subgroups has
scalar-torsion-free coordinate algebra. In particular its coordinate algebra is flat over `ℤ`. -/
instance isTorsionFree_kostantTorusSubsystemCoordinateHopfAlgebra :
    Module.IsTorsionFree ℤ
      (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)) := by
  rw [kostantTorusSubsystemDefiningIdeal_def]
  refine @CommHopfAlgCat.isTorsionFree_quotient_commonKernelHopfIdeal ℤ _ _
    (GeneralLinear.coordinateHopfAlgebra ℤ n) (S ⊕ Unit) _ _ ?_
  rintro (i | j) <;> infer_instance

/-- The structural morphism of an integral Kostant torus subsystem is flat. -/
instance flat_kostantTorusSubsystemGroupScheme :
    Flat (kostantTorusSubsystemGroupScheme e h ρ M hM b wt S hnilS).X.hom :=
  (moduleFlat_iff_flat_hopfSpec ℤ _).mp inferInstance

/-- The coordinate algebra of a Kostant torus subsystem remains flat after base change
from `ℤ` to any commutative ring. -/
instance flat_kostantTorusSubsystemBaseChangeCoordinateHopfAlgebra
    (A : Type v) [CommRing A] :
    Module.Flat A
      (CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A)) :=
  Module.Flat.of_linearEquiv
    (_root_.CommHopfAlgCat.ofIso
      (kostantTorusSubsystemBaseChangeIso e h ρ M hM b wt S hnilS A)).toAlgEquiv.toLinearEquiv

end TauCeti.UniversalEnvelopingAlgebra
