/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.Reductive.Basic
public import TauCeti.Algebra.AlgebraicGroup.Reductive.Over
public import TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.Generated.Connected
public import TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.Generated.UnipotentRadical
public import TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.Smooth

/-!
# Reductivity of the short-root G₂ carrier over `𝔽₃`

The short-root type-`G₂` carrier over `𝔽₃` is the closed subgroup scheme of `GL₇` generated
by four numbered root subgroups and a rank-two weight torus. It is reductive: smooth,
geometrically connected, and with no nontrivial connected normal smooth unipotent subgroup
after extension to an algebraic closure.

The geometric fibre is identified with the subgroup generated after scalar extension by
`TauCeti.G2ShortRoot.PrimeField.coordinateHopfAlgebraGeneratedIso`. The latter's faithful
simple seven-dimensional standard representation eliminates normal smooth unipotent subgroups,
as proved in `TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.Generated.UnipotentRadical`.

The same identification holds after scalar extension to any field of characteristic three: the
geometric fibre of the scalar-extended carrier is again the subgroup generated over an algebraic
closure. Hence every scalar extension of the carrier to a field is reductive, and the carrier is a
reductive group scheme over `𝔽₃` in the sense of `TauCeti.reductiveCommHopfAlgPropertyOver`:
smooth, with every geometric fibre reductive. That is the reductivity datum a pinning of the
carrier over `𝔽₃` records.

This proves reductivity of the constructed carrier. Identification with the pinned simply
connected group of type `G₂` also requires maximal-torus and root-datum recognition.

## Main results

In the namespace `TauCeti.G2ShortRoot.PrimeField`:

* `reductiveCommHopfAlgProperty_finiteTypeCarrierAlgebra`: the carrier is reductive over `𝔽₃`.
* `reductiveCommHopfAlgProperty_baseChange_finiteTypeCarrierAlgebra`: its scalar extension to
  every field of characteristic three is reductive.
* `reductiveCommHopfAlgPropertyOver_finiteTypeCarrierAlgebra`: the carrier is a reductive group
  scheme over `𝔽₃`.

## References

* J. S. Milne, *Algebraic Groups* (2017), §2.h and Chapter 19.
* J. E. Humphreys, *Linear Algebraic Groups*, §§19 and 26.
* J. C. Jantzen, *Representations of Algebraic Groups*, I.2 and II.2.
-/

public section

open CategoryTheory

namespace TauCeti.G2ShortRoot.PrimeField

universe u

noncomputable section

/-- The prime-field short-root type-`G₂` carrier as a finite-type commutative Hopf algebra. -/
abbrev finiteTypeCarrierAlgebra : FiniteTypeCommHopfAlgCat (ZMod 3) :=
  ⟨carrierAlgebra, inferInstanceAs (Algebra.FiniteType (ZMod 3) carrierAlgebra)⟩

-- The scalar-extension and reductivity argument follows the type-`F₄` companion in
-- `TauCeti.Algebra.Lie.F4.ShortRoot.PrimeField.Reductive`. Transport uses
-- `TauCeti.reductiveCommHopfAlgProperty_of_geometricFiber_iso`.
/-- The short-root type-`G₂` carrier over `𝔽₃` is reductive: smooth and geometrically connected,
with trivial geometric unipotent radical. -/
theorem reductiveCommHopfAlgProperty_finiteTypeCarrierAlgebra :
    reductiveCommHopfAlgProperty (ZMod 3) finiteTypeCarrierAlgebra :=
  reductiveCommHopfAlgProperty_of_geometricFiber_iso (ZMod 3) finiteTypeCarrierAlgebra
    (finiteTypeGeneratedCoordinateHopfAlgebra (AlgebraicClosure (ZMod 3)))
    algebraSmooth_carrierAlgebra geometricallyConnectedCommHopfAlgProperty_carrierAlgebra
    (ObjectProperty.isoMk _ (coordinateHopfAlgebraGeneratedIso _))
    (eq_augmentation_of_isNormal_of_smoothUnipotent _)

/-- **The scalar extension of the short-root type-`G₂` carrier to any field of characteristic three
is reductive.** Over an algebraic closure of `k`, the geometric fibre is the subgroup generated by
the scalar-extended root subgroups and weight torus, whose faithful simple standard
representation eliminates every normal smooth unipotent closed subgroup. -/
theorem reductiveCommHopfAlgProperty_baseChange_finiteTypeCarrierAlgebra
    (k : Type u) [Field k] [Algebra (ZMod 3) k] :
    reductiveCommHopfAlgProperty k
      (FiniteTypeCommHopfAlgCat.baseChange (K := k) finiteTypeCarrierAlgebra) := by
  let K := AlgebraicClosure k
  -- Extending first to `k` and then to `K` is extending from `𝔽₃` to `K` in one step.
  let e : CommHopfAlgCat.baseChange (K := K)
        (CommHopfAlgCat.baseChange (K := k) carrierAlgebra) ≅
      generatedCoordinateHopfAlgebra K :=
    _root_.CommHopfAlgCat.isoMk
        (Bialgebra.TensorProduct.baseChangeTowerBialgEquiv (ZMod 3) k carrierAlgebra K) ≪≫
      coordinateHopfAlgebraGeneratedIso K
  exact reductiveCommHopfAlgProperty_of_geometricFiber_iso k _
    (finiteTypeGeneratedCoordinateHopfAlgebra K) inferInstance
    (geometricallyConnectedCommHopfAlgProperty.of_baseChange k K _
      ((geometricallyConnectedCommHopfAlgProperty K).prop_of_iso e.symm
        (geometricallyConnectedCommHopfAlgProperty_generatedCoordinateHopfAlgebra K)))
    (ObjectProperty.isoMk _ e)
    (eq_augmentation_of_isNormal_of_smoothUnipotent K)

/-- **The short-root type-`G₂` carrier is a reductive group scheme over `𝔽₃`**: it is smooth, and
its geometric fibre over every algebraically closed field of characteristic three is reductive. -/
theorem reductiveCommHopfAlgPropertyOver_finiteTypeCarrierAlgebra :
    reductiveCommHopfAlgPropertyOver (ZMod 3) finiteTypeCarrierAlgebra :=
  (reductiveCommHopfAlgPropertyOver_iff _ _).2 ⟨algebraSmooth_carrierAlgebra, fun k _ _ _ ↦
    reductiveCommHopfAlgProperty_baseChange_finiteTypeCarrierAlgebra k⟩

end

end TauCeti.G2ShortRoot.PrimeField
