/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.PDCode.Jones

/-!
# Reidemeister equivalence of oriented PD-codes

Two diagrams present isotopic oriented links exactly when they are related by a chain of planar
isotopies and Reidemeister moves (Reidemeister's theorem; Lickorish, Chapter 1). On oriented
PD-codes a planar isotopy that keeps the crossings is an isomorphism of codes, generated by
relabelling half-edges and crossings (`TauCeti.OrientedPDCode.relabel`) and by reading a crossing
from another slot (`TauCeti.OrientedPDCode.rotateCrossing`). The Reidemeister moves are the local
moves on PD-codes:

* the first move, a kink added to an arc (`TauCeti.OrientedPDCode.reidemeisterOne`) or to a
  crossing-free circle (`TauCeti.OrientedPDCode.adjoinKink`);
* the second move, a clasp inserted between two distinct arcs
  (`TauCeti.OrientedPDCode.insertClasp`), between an arc and a crossing-free circle
  (`TauCeti.OrientedPDCode.insertCircleClasp`), or between two crossing-free circles
  (`TauCeti.OrientedPDCode.adjoinTwoCircleClasp`);
* the third move, across a triangle of three crossings
  (`TauCeti.OrientedPDCode.reidemeisterThree`).

`TauCeti.OrientedPDCode.IsReidemeisterMove` collects these generators as a relation between
oriented PD-codes with any numbers of crossings, and `TauCeti.OrientedPDCode.ReidemeisterEquiv` is
the equivalence relation they generate. The orientation of every new arc is inherited from the
arcs and circles a move cuts, so each move comes in all of its oriented forms.

A clasp between two distinct arcs is a generator only when the arcs border a common face on the
sides the clasp uses, or lie in different connected components of the underlying graph. The
relation itself places no planarity hypothesis on the codes it relates, but for a planar input
code these are exactly the clasps that can be drawn in the plane: in the first case
`TauCeti.PDCode.isPlanar_insertClasp_iff` keeps planarity, and in the second a drawing can place
the two components so that their two faces meet. Inserting the clasp across two different faces
of one component is excluded: the result is never planar
(`TauCeti.PDCode.not_isPlanar_insertClasp_of_face_ne`). A clasp between two parts of a
single arc is not a generator, since clasp insertion cuts two distinct arcs; such a clasp can be
made by first splitting the arc with a kink, inserting the clasp between the two arcs this
creates, and removing the kink again. The third move needs the three crossings to bound a
triangular face, with an acyclic height order on the three strands
(`TauCeti.PDCode.HasReidemeisterThreeTriangle`). That condition fixes the slots at which the
triangle meets each crossing; the rotations of crossings let it apply however the three crossings
are read.

Each generator keeps the Jones polynomial, the writhe-normalized Kauffman bracket and the number
of components, so these are invariants of Reidemeister equivalence. In particular the
right-handed trefoil is not Reidemeister equivalent to the unknot, nor to its mirror image.
Reidemeister's theorem itself, comparing this relation with ambient isotopy of the realized links,
is not proved here.

## Main definitions

* `TauCeti.OrientedPDCode.IsReidemeisterMove`: the generating moves, an isomorphism of codes or a
  Reidemeister move.
* `TauCeti.OrientedPDCode.ReidemeisterEquiv`: Reidemeister equivalence, the equivalence relation
  they generate, between codes with possibly different numbers of crossings.

## Main results

* `TauCeti.OrientedPDCode.ReidemeisterEquiv.jonesPolynomial_eq`: Reidemeister equivalent codes
  have the same Jones polynomial.
* `TauCeti.OrientedPDCode.ReidemeisterEquiv.normalizedKauffmanBracket_eq`: they have the same
  writhe-normalized Kauffman bracket, over every commutative ring.
* `TauCeti.OrientedPDCode.ReidemeisterEquiv.componentCount_eq`: they have the same number of
  components.
* `TauCeti.OrientedPDCode.not_reidemeisterEquiv_rightHandedTrefoilPDCode_unknot` and
  `TauCeti.OrientedPDCode.not_reidemeisterEquiv_rightHandedTrefoilPDCode_mirror`: the right-handed
  trefoil is neither Reidemeister equivalent to the unknot nor to its mirror image.

## References

* W. B. R. Lickorish, *An Introduction to Knot Theory*, Springer GTM 175 (1997), Chapter 1
  (Reidemeister moves and Reidemeister's theorem) and Chapter 3 (invariance of the Jones
  polynomial, Theorem 3.5).
* K. Reidemeister, *Elementare Begründung der Knotentheorie*, Abh. Math. Sem. Univ. Hamburg 5
  (1927), 24-32.
-/

public section

namespace TauCeti

open LaurentPolynomial

namespace OrientedPDCode

/-- The generating moves of Reidemeister equivalence, between oriented PD-codes with any numbers
of crossings: the isomorphisms of codes and the Reidemeister moves. A move that adds crossings is
stated in the direction that adds them; `TauCeti.OrientedPDCode.ReidemeisterEquiv` symmetrizes. -/
inductive IsReidemeisterMove : (Σ n, OrientedPDCode n) → (Σ n, OrientedPDCode n) → Prop
  /-- Relabelling the half-edges and the crossings. -/
  | relabel {n m : ℕ} (D : OrientedPDCode n) (half : Fin (4 * n) ≃ Fin (4 * m))
      (cross : Fin n ≃ Fin m) : IsReidemeisterMove ⟨n, D⟩ ⟨m, D.relabel half cross⟩
  /-- Reading a crossing from its next slot. -/
  | rotateCrossing {n : ℕ} (D : OrientedPDCode n) (i : Fin n) :
      IsReidemeisterMove ⟨n, D⟩ ⟨n, D.rotateCrossing i⟩
  /-- The first move: a kink added to the arc ending at a half-edge. -/
  | reidemeisterOne {n : ℕ} (D : OrientedPDCode n) (h : Fin (4 * n)) (b : Bool) :
      IsReidemeisterMove ⟨n, D⟩ ⟨n + 1, D.reidemeisterOne h b⟩
  /-- The first move on a crossing-free circle. -/
  | adjoinKink {n : ℕ} (D : OrientedPDCode n) (o b : Bool) :
      IsReidemeisterMove ⟨n, D.adjoinCircle o⟩ ⟨n + 1, D.adjoinKink o b⟩
  /-- The second move between two distinct arcs: inside a face both arcs border on the sides the
  clasp uses, or between two connected components of the underlying graph. -/
  | insertClasp {n : ℕ} (D : OrientedPDCode n) (p q : Fin (4 * n)) (b : Bool) (hqp : q ≠ p)
      (hqe : q ≠ D.edgePair.val p)
      (hpq : D.face (D.edgePair.val p) = D.face q ∨
        q ∉ MulAction.orbit D.toPermutationTriple.monodromyGroup p) :
      IsReidemeisterMove ⟨n, D⟩ ⟨n + 2, D.insertClasp p q b hqp hqe⟩
  /-- The second move between an arc and a crossing-free circle. -/
  | insertCircleClasp {n : ℕ} (D : OrientedPDCode n) (p : Fin (4 * n)) (o b : Bool) :
      IsReidemeisterMove ⟨n, D.adjoinCircle o⟩ ⟨n + 2, D.insertCircleClasp p o b⟩
  /-- The second move between two crossing-free circles. -/
  | adjoinTwoCircleClasp {n : ℕ} (D : OrientedPDCode n) (o₁ o₂ b : Bool) :
      IsReidemeisterMove ⟨n, (D.adjoinCircle o₁).adjoinCircle o₂⟩
        ⟨n + 2, D.adjoinTwoCircleClasp o₁ o₂ b⟩
  /-- The third move, across a triangle of three crossings with an acyclic height order. -/
  | reidemeisterThree {n : ℕ} (D : OrientedPDCode n) (c : Fin 3 ↪ Fin n)
      (h : D.HasReidemeisterThreeTriangle c) :
      IsReidemeisterMove ⟨n, D⟩ ⟨n, D.reidemeisterThree c⟩

/-- **Reidemeister equivalence** of oriented PD-codes, possibly with different numbers of
crossings: the equivalence relation generated by the isomorphisms of codes and the Reidemeister
moves, `TauCeti.OrientedPDCode.IsReidemeisterMove`. -/
def ReidemeisterEquiv {n m : ℕ} (D : OrientedPDCode n) (D' : OrientedPDCode m) : Prop :=
  Relation.EqvGen IsReidemeisterMove ⟨n, D⟩ ⟨m, D'⟩

/-- The defining equation for Reidemeister equivalence: the equivalence relation generated by
`TauCeti.OrientedPDCode.IsReidemeisterMove`, between the codes paired with their numbers of
crossings. -/
theorem reidemeisterEquiv_def {n m : ℕ} (D : OrientedPDCode n) (D' : OrientedPDCode m) :
    ReidemeisterEquiv D D' ↔ Relation.EqvGen IsReidemeisterMove ⟨n, D⟩ ⟨m, D'⟩ := (Iff.rfl)

variable {n m k : ℕ}

namespace ReidemeisterEquiv

/-- Every code is Reidemeister equivalent to itself. -/
@[refl]
theorem refl (D : OrientedPDCode n) : ReidemeisterEquiv D D :=
  Relation.EqvGen.refl _

/-- Reidemeister equivalence is symmetric. -/
@[symm]
theorem symm {D : OrientedPDCode n} {D' : OrientedPDCode m} (h : ReidemeisterEquiv D D') :
    ReidemeisterEquiv D' D :=
  Relation.EqvGen.symm _ _ h

/-- Reidemeister equivalence is transitive. -/
@[trans]
theorem trans {D : OrientedPDCode n} {D' : OrientedPDCode m} {D'' : OrientedPDCode k}
    (h : ReidemeisterEquiv D D') (h' : ReidemeisterEquiv D' D'') : ReidemeisterEquiv D D'' :=
  Relation.EqvGen.trans _ _ _ h h'

/-- The induction principle for Reidemeister equivalence. A `Prop`-valued definition does not
unfold outside the file that introduces it, so this, or rewriting with
`TauCeti.OrientedPDCode.reidemeisterEquiv_def`, is how
`TauCeti.OrientedPDCode.ReidemeisterEquiv` is eliminated: a property of every generating move
that is closed under reflexivity, symmetry and transitivity holds of every Reidemeister
equivalent pair. -/
theorem induction {motive : (Σ n, OrientedPDCode n) → (Σ n, OrientedPDCode n) → Prop}
    (move : ∀ {x y}, IsReidemeisterMove x y → motive x y) (refl : ∀ x, motive x x)
    (symm : ∀ {x y : Σ n, OrientedPDCode n}, ReidemeisterEquiv x.2 y.2 → motive x y →
      motive y x)
    (trans : ∀ {x y z : Σ n, OrientedPDCode n}, ReidemeisterEquiv x.2 y.2 →
      ReidemeisterEquiv y.2 z.2 → motive x y → motive y z → motive x z)
    {D : OrientedPDCode n} {D' : OrientedPDCode m} (h : ReidemeisterEquiv D D') :
    motive ⟨n, D⟩ ⟨m, D'⟩ := by
  suffices ∀ x y, Relation.EqvGen IsReidemeisterMove x y → motive x y from this _ _ h
  intro x y hxy
  induction hxy with
  | rel _ _ hmove => exact move hmove
  | refl x => exact refl x
  | symm _ _ hxy ih => exact symm hxy ih
  | trans _ _ _ hxy hyz ih ih' => exact trans hxy hyz ih ih'

/-- A function of oriented PD-codes that every generating move keeps is an invariant of
Reidemeister equivalence. -/
theorem eq_of_isReidemeisterMove {α : Sort*} (f : (Σ n, OrientedPDCode n) → α)
    (hf : ∀ x y, IsReidemeisterMove x y → f x = f y) {D : OrientedPDCode n}
    {D' : OrientedPDCode m} (h : ReidemeisterEquiv D D') : f ⟨n, D⟩ = f ⟨m, D'⟩ :=
  congrArg (Quot.lift f hf) (Quot.eqvGen_sound h)

end ReidemeisterEquiv

/-- A single generating move relates Reidemeister equivalent codes. -/
theorem IsReidemeisterMove.reidemeisterEquiv {D : OrientedPDCode n} {D' : OrientedPDCode m}
    (h : IsReidemeisterMove ⟨n, D⟩ ⟨m, D'⟩) : ReidemeisterEquiv D D' :=
  Relation.EqvGen.rel _ _ h

/-- Relabelling gives a Reidemeister equivalent code. -/
theorem reidemeisterEquiv_relabel (D : OrientedPDCode n) (half : Fin (4 * n) ≃ Fin (4 * m))
    (cross : Fin n ≃ Fin m) : ReidemeisterEquiv D (D.relabel half cross) :=
  (IsReidemeisterMove.relabel D half cross).reidemeisterEquiv

/-- Reading a crossing from another slot gives a Reidemeister equivalent code. -/
theorem reidemeisterEquiv_rotateCrossing (D : OrientedPDCode n) (i : Fin n) :
    ReidemeisterEquiv D (D.rotateCrossing i) :=
  (IsReidemeisterMove.rotateCrossing D i).reidemeisterEquiv

/-- The first Reidemeister move gives a Reidemeister equivalent code. -/
theorem reidemeisterEquiv_reidemeisterOne (D : OrientedPDCode n) (h : Fin (4 * n)) (b : Bool) :
    ReidemeisterEquiv D (D.reidemeisterOne h b) :=
  (IsReidemeisterMove.reidemeisterOne D h b).reidemeisterEquiv

/-- The first Reidemeister move on a crossing-free circle gives a Reidemeister equivalent code. -/
theorem reidemeisterEquiv_adjoinKink (D : OrientedPDCode n) (o b : Bool) :
    ReidemeisterEquiv (D.adjoinCircle o) (D.adjoinKink o b) :=
  (IsReidemeisterMove.adjoinKink D o b).reidemeisterEquiv

/-- The second Reidemeister move between two distinct arcs, inside a face both border on the sides
the clasp uses or between two connected components, gives a Reidemeister equivalent code. -/
theorem reidemeisterEquiv_insertClasp (D : OrientedPDCode n) (p q : Fin (4 * n)) (b : Bool)
    (hqp : q ≠ p) (hqe : q ≠ D.edgePair.val p)
    (hpq : D.face (D.edgePair.val p) = D.face q ∨
      q ∉ MulAction.orbit D.toPermutationTriple.monodromyGroup p) :
    ReidemeisterEquiv D (D.insertClasp p q b hqp hqe) :=
  (IsReidemeisterMove.insertClasp D p q b hqp hqe hpq).reidemeisterEquiv

/-- The second Reidemeister move between an arc and a crossing-free circle gives a Reidemeister
equivalent code. -/
theorem reidemeisterEquiv_insertCircleClasp (D : OrientedPDCode n) (p : Fin (4 * n))
    (o b : Bool) : ReidemeisterEquiv (D.adjoinCircle o) (D.insertCircleClasp p o b) :=
  (IsReidemeisterMove.insertCircleClasp D p o b).reidemeisterEquiv

/-- The second Reidemeister move between two crossing-free circles gives a Reidemeister equivalent
code. -/
theorem reidemeisterEquiv_adjoinTwoCircleClasp (D : OrientedPDCode n) (o₁ o₂ b : Bool) :
    ReidemeisterEquiv ((D.adjoinCircle o₁).adjoinCircle o₂) (D.adjoinTwoCircleClasp o₁ o₂ b) :=
  (IsReidemeisterMove.adjoinTwoCircleClasp D o₁ o₂ b).reidemeisterEquiv

/-- The third Reidemeister move gives a Reidemeister equivalent code. -/
theorem reidemeisterEquiv_reidemeisterThree (D : OrientedPDCode n) (c : Fin 3 ↪ Fin n)
    (h : D.HasReidemeisterThreeTriangle c) : ReidemeisterEquiv D (D.reidemeisterThree c) :=
  (IsReidemeisterMove.reidemeisterThree D c h).reidemeisterEquiv

/-- Every generating move keeps the Jones polynomial. -/
theorem IsReidemeisterMove.jonesPolynomial_eq {x y : Σ n, OrientedPDCode n}
    (h : IsReidemeisterMove x y) : x.2.jonesPolynomial = y.2.jonesPolynomial := by
  cases h with
  | relabel D half cross => exact (jonesPolynomial_relabel D half cross).symm
  | rotateCrossing D i => exact (jonesPolynomial_rotateCrossing D i).symm
  | reidemeisterOne D h b => exact (jonesPolynomial_reidemeisterOne D h b).symm
  | adjoinKink D o b => exact (jonesPolynomial_adjoinKink D o b).symm
  | insertClasp D p q b hqp hqe => exact (jonesPolynomial_insertClasp D p q b hqp hqe).symm
  | insertCircleClasp D p o b => exact (jonesPolynomial_insertCircleClasp D p o b).symm
  | adjoinTwoCircleClasp D o₁ o₂ b => exact (jonesPolynomial_adjoinTwoCircleClasp D o₁ o₂ b).symm
  | reidemeisterThree D c h => exact (jonesPolynomial_reidemeisterThree D c h).symm

/-- Every generating move keeps the number of components. -/
theorem IsReidemeisterMove.componentCount_eq {x y : Σ n, OrientedPDCode n}
    (h : IsReidemeisterMove x y) : x.2.componentCount = y.2.componentCount := by
  cases h with
  | reidemeisterOne D h b => simp [toPDCode_reidemeisterOne, PDCode.componentCount_eq]
  | insertClasp D p q b hqp hqe => simp [toPDCode_insertClasp, PDCode.componentCount_eq]
  | relabel | rotateCrossing | adjoinKink | insertCircleClasp | adjoinTwoCircleClasp
  | reidemeisterThree => simp

namespace ReidemeisterEquiv

variable {D : OrientedPDCode n} {D' : OrientedPDCode m}

/-- **The Jones polynomial is an invariant of Reidemeister equivalence.** -/
theorem jonesPolynomial_eq (h : ReidemeisterEquiv D D') :
    D.jonesPolynomial = D'.jonesPolynomial :=
  eq_of_isReidemeisterMove (fun x ↦ x.2.jonesPolynomial)
    (fun _ _ ↦ IsReidemeisterMove.jonesPolynomial_eq) h

/-- **The writhe-normalized Kauffman bracket is an invariant of Reidemeister equivalence**, over
every commutative ring: it is the Jones polynomial evaluated at `t^(1/2) = A⁻²`. -/
theorem normalizedKauffmanBracket_eq {R : Type*} [CommRing R] (h : ReidemeisterEquiv D D')
    (a : Rˣ) : D.normalizedKauffmanBracket a = D'.normalizedKauffmanBracket a := by
  rw [← eval₂_jonesPolynomial, ← eval₂_jonesPolynomial, h.jonesPolynomial_eq]

/-- **The number of components is an invariant of Reidemeister equivalence.** -/
theorem componentCount_eq (h : ReidemeisterEquiv D D') :
    D.componentCount = D'.componentCount :=
  eq_of_isReidemeisterMove (fun x ↦ x.2.componentCount)
    (fun _ _ ↦ IsReidemeisterMove.componentCount_eq) h

end ReidemeisterEquiv

/-- **The right-handed trefoil is knotted**: no chain of Reidemeister moves turns its diagram into
the crossing-free unknot, since its Jones polynomial `t + t³ - t⁴` is not `1`. -/
theorem not_reidemeisterEquiv_rightHandedTrefoilPDCode_unknot (o : Bool) :
    ¬ ReidemeisterEquiv rightHandedTrefoilPDCode (unknot o) := by
  intro h
  have h0 := congrArg (fun f : ℤ[T;T⁻¹] ↦ f.coeff 0) h.jonesPolynomial_eq
  simp [← T_zero] at h0

/-- **The right-handed trefoil is chiral**: no chain of Reidemeister moves turns its diagram into
its mirror image, since mirroring substitutes `t⁻¹` for `t` in its Jones polynomial
`t + t³ - t⁴`. -/
theorem not_reidemeisterEquiv_rightHandedTrefoilPDCode_mirror :
    ¬ ReidemeisterEquiv rightHandedTrefoilPDCode rightHandedTrefoilPDCode.mirror := by
  intro h
  have h2 := congrArg (fun f : ℤ[T;T⁻¹] ↦ f.coeff 2) h.jonesPolynomial_eq
  simp at h2

end OrientedPDCode

end TauCeti
