/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Idempotents.Corner
public import TauCeti.RingTheory.Idempotents.Primitive.Basic

/-!
# Homomorphisms between the left ideals generated by two idempotents

Let `A` be an algebra over a commutative semiring `k` and let `e` and `f` be idempotents of `A`.
The left ideals `Ae` and `Af` are the modules an idempotent decomposition of `1` cuts the regular
module into, and this file identifies the homomorphisms between two of them:

`Hom_A(Ae, Af) ≅ eAf`, by `φ ↦ φ e`.

The corner `eAf` is defined in `TauCeti.RingTheory.Idempotents.Corner` as the range of the
`k`-linear map `x ↦ e x f`. When `e` and `f` are idempotent, the identification here is
`k`-linear.

Both directions are elementary. A homomorphism `φ` out of `Ae` is right multiplication by `φ e`
(`TauCeti.coe_apply_eq_mul_apply_generator`, proved for an arbitrary target ideal), which
therefore determines it; and `φ e` lies in `eAf` because `e` is fixed by `e` on the left and every
element of `Af` is fixed by `f` on the right. Conversely right multiplication by an element of
`eAf` is a homomorphism `Ae → Af`.

Specializing to `f = e` recovers the dictionary between the corner ring `eAe` and `End (Ae)` which
`TauCeti.RingTheory.Idempotents.Primitive.Basic` uses to compare primitivity of `e` with
indecomposability of `Ae`; the point of the two-idempotent version is that it computes the
*graded* homomorphism spaces between the indecomposable projectives of a graded algebra with a
distinguished family of idempotents, since the corner inherits the grading of `A`.

## Main definitions

* `TauCeti.cornerToSpanSingletonHom`: right multiplication by an element of `eAf`, as a
  homomorphism `Ae → Af`.

## Main results

* `TauCeti.spanSingletonHomEquivCorner`: **the dictionary `Hom_A(Ae, Af) ≃ₗ[k] eAf`.**
* `TauCeti.coe_apply_eq_mul_apply_generator`: a homomorphism out of `Ae` is right multiplication
  by its value at `e`.

## References

This is the general input to the graded homomorphism spaces of Layer 3 of
`TauCetiRoadmap/ZigzagPreprojective/README.md`. See I. Assem, D. Simson, A. Skowroński, *Elements
of the Representation Theory of Associative Algebras, Vol. 1*, Section I.4.
-/

public section

namespace TauCeti

universe u v

variable (k : Type v) [CommSemiring k] {A : Type u} [Semiring A] [Algebra k A]

/-! ### The dictionary -/

variable {k}
variable {e f : A}

/-- An element of the corner `eAf` is fixed by `f` on the right, hence lies in the left ideal
`Af`. -/
theorem mem_span_singleton_of_mem_cornerSubmodule {e f x : A} (hf : IsIdempotentElem f)
    (hx : x ∈ cornerSubmodule k e f) : x ∈ (Ideal.span {f} : Ideal A) := by
  exact (mem_span_singleton_iff_mul_eq_self hf).2
    (mul_eq_self_of_mem_cornerSubmodule_right hf hx)

/-- The value at the generator of a homomorphism `Ae → Af` lies in the corner `eAf`. -/
theorem apply_generator_mem_cornerSubmodule (he : IsIdempotentElem e) (hf : IsIdempotentElem f)
    (φ : (Ideal.span {e} : Ideal A) →ₗ[A] (Ideal.span {f} : Ideal A)) :
    (φ (spanSingletonGenerator e) : A) ∈ cornerSubmodule k e f := by
  rw [mem_cornerSubmodule_iff k he hf]
  have hright : (φ (spanSingletonGenerator e) : A) * f = (φ (spanSingletonGenerator e) : A) :=
    (mem_span_singleton_iff_mul_eq_self hf).1 (φ (spanSingletonGenerator e)).2
  have hleft : e * (φ (spanSingletonGenerator e) : A) = (φ (spanSingletonGenerator e) : A) := by
    simpa only [coe_spanSingletonGenerator] using
      (coe_apply_eq_mul_apply_generator he φ (spanSingletonGenerator e)).symm
  rw [hleft, hright]

/-- Right multiplication by an element of the corner `eAf`, as a homomorphism `Ae → Af`. -/
def cornerToSpanSingletonHom (hf : IsIdempotentElem f) (x : cornerSubmodule k e f) :
    (Ideal.span {e} : Ideal A) →ₗ[A] (Ideal.span {f} : Ideal A) where
  toFun y := ⟨(y : A) * (x : A), (mem_span_singleton_iff_mul_eq_self hf).2 (by
    rw [mul_assoc, (mem_span_singleton_iff_mul_eq_self hf).1
      (mem_span_singleton_of_mem_cornerSubmodule hf x.2)])⟩
  map_add' y z := Subtype.ext (by simpa using add_mul (y : A) (z : A) (x : A))
  map_smul' a y := Subtype.ext (by simpa using mul_assoc a (y : A) (x : A))

@[simp]
theorem coe_cornerToSpanSingletonHom_apply (hf : IsIdempotentElem f) (x : cornerSubmodule k e f)
    (y : (Ideal.span {e} : Ideal A)) :
    (cornerToSpanSingletonHom hf x y : A) = (y : A) * (x : A) :=
  (rfl)

/-- **The homomorphisms from `Ae` to `Af` are the corner `eAf`**, by evaluation at the generator
`e`. The inverse sends an element of the corner to right multiplication by it. -/
def spanSingletonHomEquivCorner (he : IsIdempotentElem e) (hf : IsIdempotentElem f) :
    ((Ideal.span {e} : Ideal A) →ₗ[A] (Ideal.span {f} : Ideal A)) ≃ₗ[k]
      cornerSubmodule k e f where
  toFun φ := ⟨(φ (spanSingletonGenerator e) : A), apply_generator_mem_cornerSubmodule he hf φ⟩
  map_add' φ ψ := Subtype.ext (by simp)
  map_smul' c φ := Subtype.ext (by simp)
  invFun := cornerToSpanSingletonHom hf
  left_inv φ := by
    refine LinearMap.ext fun y => Subtype.ext ?_
    rw [coe_cornerToSpanSingletonHom_apply]
    exact (coe_apply_eq_mul_apply_generator he φ y).symm
  right_inv x := by
    refine Subtype.ext ?_
    rw [coe_cornerToSpanSingletonHom_apply, coe_spanSingletonGenerator]
    exact mul_eq_self_of_mem_cornerSubmodule he x.2

@[simp]
theorem coe_spanSingletonHomEquivCorner_apply (he : IsIdempotentElem e) (hf : IsIdempotentElem f)
    (φ : (Ideal.span {e} : Ideal A) →ₗ[A] (Ideal.span {f} : Ideal A)) :
    ((spanSingletonHomEquivCorner (k := k) he hf φ : cornerSubmodule k e f) : A) =
      (φ (spanSingletonGenerator e) : A) :=
  (rfl)

@[simp]
theorem coe_spanSingletonHomEquivCorner_symm_apply (he : IsIdempotentElem e)
    (hf : IsIdempotentElem f) (x : cornerSubmodule k e f)
    (y : (Ideal.span {e} : Ideal A)) :
    (((spanSingletonHomEquivCorner (k := k) he hf).symm x) y : A) = (y : A) * (x : A) :=
  (rfl)

end TauCeti
