/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.RayClass.Character.Dirichlet
import TauCeti.NumberTheory.NumberField.Ideal.IntegersRat

/-!
# Dirichlet characters as Hecke characters of the rational field

A complex Dirichlet character modulo a positive integer `n` gives a finite-order Hecke
character of `ℚ`, by the ray class identification for `(n)·∞` and pullback along the
idele-to-ray-class quotient. Changing the Dirichlet level does not change the Hecke character.
Conversely, every finite-order Hecke character of `ℚ` has a unique primitive Dirichlet
representative at the absolute norm of the finite part of its conductor.

The conductors agree: the finite part is generated by the Dirichlet conductor, and the
real place is omitted exactly for an even character. Thus the correspondence retains the
sign obstruction, rather than identifying all characters with characters of finite moduli.

The construction uses `ratDirichletEquiv` and `HeckeCharacter.ofRayClassCharacter`; the
conductor and parity comparisons use the ray-class dictionary in
`TauCeti.NumberTheory.NumberField.Global.RayClass.Character.Dirichlet`.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VII, §6.
-/

public section
noncomputable section

open NumberField
open scoped NumberField

namespace TauCeti.GlobalNumberFields.HeckeCharacter

variable (n : ℕ) (hn : n ≠ 0)

/-- A Dirichlet character modulo `n` as a Hecke character of `ℚ`, through the ray class
group of `(n)·∞`. -/
def ofDirichletCharacter : DirichletCharacter ℂ n →* HeckeCharacter ℚ :=
  (ofRayClassCharacter (ratModulus n hn)).comp (ratDirichletEquiv n hn).symm.toMonoidHom

variable {n hn}

/-- The Dirichlet-to-Hecke map is the pullback of the corresponding ray class character. -/
theorem ofDirichletCharacter_eq_ofRayClassCharacter (ψ : DirichletCharacter ℂ n) :
    ofDirichletCharacter n hn ψ =
      ofRayClassCharacter (ratModulus n hn) ((ratDirichletEquiv n hn).symm ψ) := (rfl)

/-- Evaluation of the Hecke character attached to a Dirichlet character on an idele class. -/
@[simp]
theorem ofDirichletCharacter_apply (ψ : DirichletCharacter ℂ n)
    (c : IdeleClassGroup (𝓞 ℚ) ℚ) :
    ofDirichletCharacter n hn ψ c =
      ψ.toUnitHom (ratModulusEquivZMod n hn (rayClassQuotient (ratModulus n hn) c)) := by
  simp [ofDirichletCharacter, ofRayClassCharacter_apply]

/-- Distinct Dirichlet characters at a fixed level give distinct Hecke characters. -/
theorem ofDirichletCharacter_injective : Function.Injective (ofDirichletCharacter n hn) :=
  (ofRayClassCharacter_injective _).comp (ratDirichletEquiv n hn).symm.injective

/-- The Hecke character attached to a Dirichlet character has finite order. -/
theorem isFiniteOrder_ofDirichletCharacter (ψ : DirichletCharacter ℂ n) :
    (ofDirichletCharacter n hn ψ).IsFiniteOrder := by
  rw [ofDirichletCharacter_eq_ofRayClassCharacter]
  exact isFiniteOrder_ofRayClassCharacter _

/-- Increasing the Dirichlet level preserves the associated Hecke character. -/
@[simp]
theorem ofDirichletCharacter_changeLevel {d : ℕ} (h : d ∣ n)
    (ψ : DirichletCharacter ℂ d) :
    ofDirichletCharacter n hn (ψ.changeLevel h) =
      ofDirichletCharacter d (ne_zero_of_dvd_ne_zero hn h) ψ := by
  have hd : d ≠ 0 := ne_zero_of_dvd_ne_zero hn h
  have hmod : ratModulus d hd ∣ ratModulus n hn := ratModulus_dvd_ratModulus_iff.mpr h
  have hη : (ratDirichletEquiv n hn).symm (ψ.changeLevel h) =
      ((ratDirichletEquiv d hd).symm ψ).induced hmod := by
    apply (ratDirichletEquiv n hn).injective
    simp [ratDirichletEquiv_induced]
  rw [ofDirichletCharacter_eq_ofRayClassCharacter, hη, ofRayClassCharacter_induced,
    ofDirichletCharacter_eq_ofRayClassCharacter]

/-- The finite part of the Hecke conductor is generated by the Dirichlet conductor. -/
@[simp]
theorem conductor_ofDirichletCharacter_finitePart_eq_span (ψ : DirichletCharacter ℂ n) :
    ((ofDirichletCharacter n hn ψ).conductor
      (isFiniteOrder_ofDirichletCharacter ψ)).finitePart =
      Ideal.span {(ψ.conductor : 𝓞 ℚ)} := by
  simp only [ofDirichletCharacter_eq_ofRayClassCharacter, conductor_ofRayClassCharacter,
    RayClassCharacter.conductor_finitePart_eq_span, MulEquiv.apply_symm_apply]

/-- The real place is absent from the Hecke conductor exactly when the Dirichlet character
is even. -/
@[simp]
theorem conductor_ofDirichletCharacter_infinitePart_eq_empty_iff (ψ : DirichletCharacter ℂ n) :
    ((ofDirichletCharacter n hn ψ).conductor
      (isFiniteOrder_ofDirichletCharacter ψ)).infinitePart = ∅ ↔ ψ.Even := by
  simp only [ofDirichletCharacter_eq_ofRayClassCharacter, conductor_ofRayClassCharacter,
    RayClassCharacter.conductor_infinitePart_eq_empty_iff_even, MulEquiv.apply_symm_apply]

/-- A finite-order Hecke character is represented at Dirichlet level `n` exactly when its
conductor divides `(n)·∞`. -/
theorem mem_range_ofDirichletCharacter_iff {χ : HeckeCharacter ℚ} (hχ : χ.IsFiniteOrder) :
    χ ∈ (ofDirichletCharacter n hn).range ↔ χ.conductor hχ ∣ ratModulus n hn := by
  rw [conductor_dvd_iff]
  constructor
  · rintro ⟨ψ, rfl⟩
    exact ⟨(ratDirichletEquiv n hn).symm ψ,
      (ofDirichletCharacter_eq_ofRayClassCharacter ψ).symm⟩
  · rintro ⟨η, rfl⟩
    exact ⟨ratDirichletEquiv n hn η, by
      rw [ofDirichletCharacter_eq_ofRayClassCharacter, MulEquiv.symm_apply_apply]⟩

/-- Every finite-order Hecke character of `ℚ` has a unique primitive Dirichlet representative,
at the absolute norm of the finite part of its conductor. -/
theorem existsUnique_primitive_dirichletCharacter (χ : HeckeCharacter ℚ) (hχ : χ.IsFiniteOrder) :
    ∃ hn : Ideal.absNorm (χ.conductor hχ).finitePart ≠ 0,
      ∃! ψ : DirichletCharacter ℂ (Ideal.absNorm (χ.conductor hχ).finitePart),
        ψ.IsPrimitive ∧ ofDirichletCharacter _ hn ψ = χ := by
  let n := Ideal.absNorm (χ.conductor hχ).finitePart
  have hn : n ≠ 0 := by
    rw [Ne, Ideal.absNorm_eq_zero_iff]
    exact (χ.conductor hχ).finitePart_ne_bot
  have hmod : χ.conductor hχ ∣ ratModulus n hn := by
    refine Modulus.dvd_iff.mpr ⟨?_, ?_⟩
    · rw [ratModulus_finitePart, Rat.RingOfIntegers.ideal_span_absNorm_eq_self]
    · intro w _
      simp only [ratModulus_infinitePart, Finset.mem_singleton]
      exact Subsingleton.elim _ _
  obtain ⟨η, hη⟩ := (conductor_dvd_iff hχ).mp hmod
  have hψ : ofDirichletCharacter n hn (ratDirichletEquiv n hn η) = χ := by
    rw [ofDirichletCharacter_eq_ofRayClassCharacter, MulEquiv.symm_apply_apply]
    exact hη
  refine ⟨hn, ratDirichletEquiv n hn η, ⟨?_, hψ⟩, fun ψ hψ' ↦ ?_⟩
  · rw [DirichletCharacter.isPrimitive_def, ← RayClassCharacter.absNorm_conductor_finitePart]
    rw [← conductor_ofRayClassCharacter η (hη.symm ▸ hχ)]
    simp only [hη]
  · exact ofDirichletCharacter_injective (hψ'.2.trans hψ.symm)

/-- Finite-order Hecke characters of `ℚ` are exactly those obtained from Dirichlet characters
of some nonzero level. -/
theorem isFiniteOrder_iff_exists_dirichletCharacter (χ : HeckeCharacter ℚ) :
    χ.IsFiniteOrder ↔ ∃ (n : ℕ) (hn : n ≠ 0) (ψ : DirichletCharacter ℂ n),
      ofDirichletCharacter n hn ψ = χ := by
  constructor
  · intro hχ
    obtain ⟨hn, ψ, hψ, -⟩ := existsUnique_primitive_dirichletCharacter χ hχ
    exact ⟨_, hn, ψ, hψ.2⟩
  · rintro ⟨n, hn, ψ, rfl⟩
    exact isFiniteOrder_ofDirichletCharacter ψ

end TauCeti.GlobalNumberFields.HeckeCharacter
