/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.HeckeCharacter.UnitCompatibility
public import TauCeti.NumberTheory.NumberField.Global.Adeles.Away

import Mathlib.FieldTheory.AlgebraicClosure

/-!
# The ideal character of a Hecke character

A Hecke character gives a canonical multiplicative character on the fractional ideals prime to
its finite conductor. To evaluate it, represent an ideal by a finite idele and replace the
coordinates at the conductor primes by `1`. The remaining ambiguity consists of integral local
units away from the conductor, on which the character is trivial. Triviality is proved for the
whole finite idele, including infinitely many unit coordinates, using the exact conductor
filtration theorem.

On a principal ideal generated by an element congruent to `1` modulo the finite conductor, the
ideal character is the inverse of the product of the infinite components. For an algebraic
character and a totally positive generator this is the inverse of the embedding monomial. The
inverse follows from the convention that a prime ideal is represented by a local uniformizer.
Finiteness of the narrow ray class group then shows that an algebraic Hecke character has
algebraic values on all fractional ideals prime to its conductor.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VII, §6.
* A. Weil, *Basic Number Theory*, Chapter VII, §3.
-/

public section
noncomputable section

open IsDedekindDomain HeightOneSpectrum IsDedekindDomain.FiniteAdeleRing NumberField
open scoped NumberField nonZeroDivisors

namespace TauCeti.GlobalNumberFields
namespace HeckeCharacter

variable {K : Type*} [Field K] [NumberField K]

private def idealCharacterLift (χ : HeckeCharacter K)
    (S : Finset (HeightOneSpectrum (𝓞 K))) : 𝔸ᶠ[(𝓞 K), K]ˣ →* ℂˣ :=
  (χ.toMonoidHom.comp ((QuotientGroup.mk' (IdeleGroup.principalSubgroup (𝓞 K) K)).comp
    (IdeleGroup.ofFiniteIdele (𝓞 K) K))) *
    (∏ v ∈ S, (χ.finiteComponent v).toMonoidHom.comp
      ((v.ideleFiniteCoord).comp (IdeleGroup.ofFiniteIdele (𝓞 K) K)))⁻¹

private theorem idealCharacterLift_apply (χ : HeckeCharacter K)
    (S : Finset (HeightOneSpectrum (𝓞 K))) (a : 𝔸ᶠ[(𝓞 K), K]ˣ) :
    idealCharacterLift χ S a = χ (QuotientGroup.mk (IdeleGroup.ofFiniteIdele (𝓞 K) K a)) *
      (∏ v ∈ S, χ.finiteComponent v
        (v.ideleFiniteCoord (IdeleGroup.ofFiniteIdele (𝓞 K) K a)))⁻¹ := by
  simp [idealCharacterLift]

private theorem idealCharacterLift_eq (χ : HeckeCharacter K)
    (S : Finset (HeightOneSpectrum (𝓞 K))) (a : 𝔸ᶠ[(𝓞 K), K]ˣ) :
    idealCharacterLift χ S a = χ (QuotientGroup.mk
      (IdeleGroup.ofFiniteIdele (𝓞 K) K a *
        (∏ v ∈ S, IdeleGroup.ofAdicCompletion (𝓞 K) K v
          (v.ideleFiniteCoord (IdeleGroup.ofFiniteIdele (𝓞 K) K a)))⁻¹)) := by
  rw [idealCharacterLift_apply, QuotientGroup.mk_mul, QuotientGroup.mk_inv, map_mul, map_inv,
    QuotientGroup.mk_prod, map_prod]
  simp only [finiteComponent_apply, IdeleClassGroup.ofAdicCompletion_apply]

private theorem ker_toIdealsAway_le_idealCharacterLift (χ : HeckeCharacter K) :
    (toIdealsAway (Modulus.support ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩)).ker ≤
      ((idealCharacterLift χ
        (Modulus.support ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩)).comp
          (adicOrdAway _).subtype).ker := by
  classical
  let 𝔣 : Modulus K := ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩
  intro a ha
  have hunit : (a : 𝔸ᶠ[(𝓞 K), K]ˣ) ∈ integralUnits (𝓞 K) K :=
    (mem_ker_toIdealsAway_iff 𝔣.support a).mp (MonoidHom.mem_ker.mp ha)
  let x := IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ)
  let z : IdeleGroup (𝓞 K) K :=
    ∏ v ∈ 𝔣.support, IdeleGroup.ofAdicCompletion (𝓞 K) K v (v.ideleFiniteCoord x)
  have hcoord (v : HeightOneSpectrum (𝓞 K)) :
      v.ideleFiniteCoord (x * z⁻¹) = if v ∈ 𝔣.support then 1 else v.ideleFiniteCoord x := by
    have hzcoord : v.ideleFiniteCoord z =
        if v ∈ 𝔣.support then v.ideleFiniteCoord x else 1 :=
      v.ideleFiniteCoord_prod_ofAdicCompletion 𝔣.support (fun w ↦ w.ideleFiniteCoord x)
    rw [map_mul, map_inv, hzcoord]
    split_ifs <;> simp
  have hχ := χ.finitePart_eq_one_of_forall_mem_unitFiltration (x * z⁻¹) (fun v ↦ by
    rw [hcoord]
    split_ifs with hv
    · exact (TauCeti.unitFiltration (v.adicCompletion K) _).one_mem
    · have he : χ.conductorExponent v = 0 := by
        have hn : ¬ v.asIdeal ∣ χ.finiteConductor := fun h ↦ hv ((𝔣.mem_support_iff v).mpr h)
        exact not_not.mp ((χ.dvd_finiteConductor_iff v).not.mp hn)
      rw [he, HeightOneSpectrum.mem_unitFiltration_adicCompletion_iff]
      have hu : Valued.v (v.ideleFiniteCoord x : v.adicCompletion K) = 1 := by
        simpa only [x, HeightOneSpectrum.coe_ideleFiniteCoord, IdeleGroup.coe_ofFiniteIdele]
          using (mem_integralUnits_iff.mp hunit) v
      refine ⟨hu, ?_⟩
      simpa using (Valuation.map_sub Valued.v _ _).trans (max_le hu.le (map_one _).le))
  have hfinite : IdeleGroup.ofFiniteIdele (𝓞 K) K
      (IdeleGroup.toFiniteIdele (𝓞 K) K (x * z⁻¹)) = x * z⁻¹ := by
    apply IdeleGroup.ext
    · intro w
      simp [x, z]
    · intro v
      apply Units.ext
      simp only [HeightOneSpectrum.coe_ideleFiniteCoord, IdeleGroup.coe_ofFiniteIdele,
        IdeleGroup.coe_toFiniteIdele]
  rw [hfinite] at hχ
  rw [MonoidHom.mem_ker, MonoidHom.comp_apply, Subgroup.subtype_apply,
    idealCharacterLift_eq]
  exact hχ

/-- The canonical character on fractional ideals prime to the finite conductor of `χ`.
Its value at a prime is the finite component evaluated on a uniformizer at that prime. -/
def idealCharacter (χ : HeckeCharacter K) :
    idealsPrimeTo ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩ →* ℂˣ :=
  (toIdealsAway _).liftOfSurjective (toIdealsAway_surjective _)
    ⟨(idealCharacterLift χ _).comp (adicOrdAway _).subtype,
      ker_toIdealsAway_le_idealCharacterLift χ⟩

/-- Evaluate the ideal character on any finite-idele representative: remove the contributions
at the conductor primes. This also expresses independence of the representative. -/
@[simp]
theorem idealCharacter_apply_toIdealsAway (χ : HeckeCharacter K)
    (a : adicOrdAway (Modulus.support ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩)) :
    χ.idealCharacter (toIdealsAway _ a) =
      χ (QuotientGroup.mk (IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ))) *
        (∏ v ∈ (⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩ : Modulus K).support,
          χ.finiteComponent v (v.ideleFiniteCoord
            (IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ))))⁻¹ := by
  rw [idealCharacter, MonoidHom.liftOfRightInverse_comp_apply]
  exact idealCharacterLift_apply χ _ _

/-- A representative whose conductor coordinates are `1` needs no correction. -/
theorem idealCharacter_apply_toIdealsAway_of_eq_one (χ : HeckeCharacter K)
    (a : adicOrdAway (Modulus.support ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩))
    (ha : ∀ v ∈ (⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩ : Modulus K).support,
      v.ideleFiniteCoord (IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ)) = 1) :
    χ.idealCharacter (toIdealsAway _ a) =
      χ (QuotientGroup.mk (IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ))) := by
  rw [idealCharacter_apply_toIdealsAway]
  have hprod : (∏ v ∈ (⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩ : Modulus K).support,
      χ.finiteComponent v (v.ideleFiniteCoord
        (IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ)))) = 1 :=
    Finset.prod_eq_one fun v hv ↦ by rw [ha v hv, map_one]
  rw [hprod, inv_one, mul_one]

/-- At a prime away from the conductor, the ideal character evaluates the local component
on any uniformizer. In particular the value is independent of the choice of uniformizer. -/
theorem idealCharacter_apply_prime (χ : HeckeCharacter K)
    (I : idealsPrimeTo ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩)
    (v : HeightOneSpectrum (𝓞 K))
    (hI : ((I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) : FractionalIdeal (𝓞 K)⁰ K) = v.asIdeal)
    (u : (v.adicCompletion K)ˣ) (hu : Valued.v (u : v.adicCompletion K) = WithZero.exp (-1)) :
    χ.idealCharacter I = χ.finiteComponent v u := by
  classical
  let 𝔣 : Modulus K := ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩
  let x := IdeleGroup.ofAdicCompletion (𝓞 K) K v u
  have hideal : toFractionalIdeal (IdeleGroup.toFiniteIdele (𝓞 K) K x) =
      (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) := by
    rw [toFractionalIdeal_toFiniteIdele_ofAdicCompletion, hu, WithZero.log_exp]
    simp only [neg_neg, zpow_one]
    apply Units.ext
    rw [HeightOneSpectrum.coe_unitOfPrime, hI]
  let a : adicOrdAway 𝔣.support := ⟨IdeleGroup.toFiniteIdele (𝓞 K) K x, by
    rw [mem_adicOrdAway_iff]
    apply (toFractionalIdeal_mem_idealsAway_iff 𝔣.support _).mp
    rw [hideal]
    exact I.property⟩
  have hI' : toIdealsAway 𝔣.support a = I := by
    apply Subtype.ext
    rw [toIdealsAway_apply]
    exact hideal
  have hxfin : IdeleGroup.ofFiniteIdele (𝓞 K) K
      (IdeleGroup.toFiniteIdele (𝓞 K) K x) = x := by
    apply IdeleGroup.ext
    · intro w
      simp [x]
    · intro v
      apply Units.ext
      simp only [HeightOneSpectrum.coe_ideleFiniteCoord, IdeleGroup.coe_ofFiniteIdele,
        IdeleGroup.coe_toFiniteIdele]
  have hv : v ∉ 𝔣.support := by
    intro hv
    have hzero := (NumberFieldArithmetic.mem_idealsAway_iff.mp I.property) v hv
    rw [hI, FractionalIdeal.count_self] at hzero
    exact one_ne_zero hzero
  rw [← hI', idealCharacter_apply_toIdealsAway_of_eq_one χ a]
  · rw [hxfin]
    exact (χ.finiteComponent_apply v u).symm
  · intro w hw
    rw [hxfin]
    exact w.ideleFiniteCoord_ofAdicCompletion_of_ne (ne_of_mem_of_not_mem hw hv) u

/-- On a principal ideal generated by an element congruent to `1` modulo the finite conductor,
the ideal character is the inverse of the product of the infinite components. -/
theorem idealCharacter_apply_toPrincipalIdeal (χ : HeckeCharacter K) (x : Kˣ)
    (hx : IsCongrOne ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩ x) :
    χ.idealCharacter ⟨toPrincipalIdeal (𝓞 K) K x, hx.toPrincipalIdeal_mem_idealsPrimeTo⟩ =
      (∏ w : InfinitePlace K,
        χ.infiniteComponent w (Units.map (algebraMap K w.Completion).toMonoidHom x))⁻¹ := by
  classical
  let 𝔣 : Modulus K := ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩
  -- Represent the principal ideal by its diagonal finite idele.
  let a : adicOrdAway 𝔣.support := ⟨unitEmbedding (𝓞 K) K x, by
    rw [mem_adicOrdAway_iff]
    apply (toFractionalIdeal_mem_idealsAway_iff 𝔣.support _).mp
    rw [toFractionalIdeal_unitEmbedding]
    exact hx.toPrincipalIdeal_mem_idealsPrimeTo⟩
  have hideal : toIdealsAway 𝔣.support a =
      ⟨toPrincipalIdeal (𝓞 K) K x, hx.toPrincipalIdeal_mem_idealsPrimeTo⟩ := by
    apply Subtype.ext
    rw [toIdealsAway_apply]
    exact toFractionalIdeal_unitEmbedding x
  have hcoord (v : HeightOneSpectrum (𝓞 K)) :
      v.ideleFiniteCoord (IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ)) =
        Units.map (algebraMap K (v.adicCompletion K)).toMonoidHom x := by
    have hfin := congrArg v.ideleFiniteCoord
      (IdeleGroup.prod_ofCompletion_mul_ofFiniteIdele (IdeleGroup.unitEmbedding (𝓞 K) K x))
    simpa only [map_mul, map_prod, HeightOneSpectrum.ideleFiniteCoord_ofCompletion,
      Finset.prod_const_one, one_mul, a, IdeleGroup.toFiniteIdele_unitEmbedding,
      HeightOneSpectrum.ideleFiniteCoord_unitEmbedding] using hfin
  -- Congruence kills the correction factors at the conductor primes.
  have hlocal (v : HeightOneSpectrum (𝓞 K)) (hv : v ∈ 𝔣.support) :
      χ.finiteComponent v (v.ideleFiniteCoord
        (IdeleGroup.ofFiniteIdele (𝓞 K) K (a : 𝔸ᶠ[(𝓞 K), K]ˣ))) = 1 := by
    refine χ.finiteComponent_eq_one_of_mem_unitFiltration ?_
    rw [hcoord, HeightOneSpectrum.mem_unitFiltration_adicCompletion_iff]
    have hdvd := (𝔣.mem_support_iff v).mp hv
    have he : 𝔣.exponent v = χ.conductorExponent v := by
      rw [Modulus.exponent_def]
      exact χ.count_finiteConductor v
    simp only [Units.coe_map, RingHom.toMonoidHom_eq_coe, MonoidHom.coe_ofClass]
    constructor
    · simpa only [HeightOneSpectrum.algebraMap_adicCompletion, Function.comp_apply,
        Algebra.algebraMap_self_apply, valuedAdicCompletion_eq_valuation'] using
        hx.valuation_eq_one hdvd
    · rw [← map_one (algebraMap K (v.adicCompletion K)), ← map_sub,
        HeightOneSpectrum.algebraMap_adicCompletion, Function.comp_apply,
        Algebra.algebraMap_self_apply, valuedAdicCompletion_eq_valuation', ← he]
      exact hx.valuation_sub_one_le hdvd
  rw [← hideal, idealCharacter_apply_toIdealsAway]
  have hprod := Finset.prod_eq_one hlocal
  rw [hprod, inv_one, mul_one]
  -- The full diagonal idele is principal, so its infinite and finite values multiply to one.
  have hprincipal :
      (QuotientGroup.mk (IdeleGroup.unitEmbedding (𝓞 K) K x) : IdeleClassGroup (𝓞 K) K) = 1 :=
    (QuotientGroup.eq_one_iff _).mpr ⟨x, rfl⟩
  have hsplit := congrArg (fun z : IdeleGroup (𝓞 K) K ↦ χ (QuotientGroup.mk z))
    (IdeleGroup.prod_ofCompletion_mul_ofFiniteIdele (IdeleGroup.unitEmbedding (𝓞 K) K x))
  rw [QuotientGroup.mk_mul, map_mul, hprincipal, map_one,
    QuotientGroup.mk_prod, map_prod] at hsplit
  have hinf : (∏ w : InfinitePlace K,
      χ (QuotientGroup.mk (IdeleGroup.ofCompletion (𝓞 K) K w
        (w.ideleInfiniteCoord (IdeleGroup.unitEmbedding (𝓞 K) K x))))) =
      ∏ w : InfinitePlace K,
        χ.infiniteComponent w (Units.map (algebraMap K w.Completion).toMonoidHom x) := by
    simp only [infiniteComponent_apply, IdeleClassGroup.ofCompletion_apply,
      InfinitePlace.ideleInfiniteCoord_unitEmbedding]
  rw [hinf, IdeleGroup.toFiniteIdele_unitEmbedding] at hsplit
  exact eq_inv_of_mul_eq_one_right hsplit

/-- For a matching algebraic infinity type, a totally positive generator congruent to `1`
modulo the finite conductor has ideal-character value the inverse embedding monomial. -/
theorem idealCharacter_apply_toPrincipalIdeal_eq_embeddingCharacter_inv (χ : HeckeCharacter K)
    (n : AlgebraicInfinityType K)
    (hn : χ.infinityType.AgreesOnIdentityComponent (AlgebraicInfinityType.toContinuous n))
    (x : Kˣ) (hx : IsCongrOne ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩ x)
    (hpos : IsTotallyPositive (x : K)) :
    χ.idealCharacter ⟨toPrincipalIdeal (𝓞 K) K x, hx.toPrincipalIdeal_mem_idealsPrimeTo⟩ =
      (n.embeddingCharacter x)⁻¹ := by
  rw [idealCharacter_apply_toPrincipalIdeal χ x hx]
  congr 1
  apply Units.ext
  simpa only [Units.coe_prod] using
    χ.coe_prod_infiniteComponent_eq_embeddingCharacter n hn x hpos

/-- An algebraic Hecke character has algebraic values on every fractional ideal prime to its
finite conductor. Finiteness of the narrow ray class group supplies a positive power that is
principal with a totally positive generator congruent to `1`. -/
theorem IsAlgebraic.isAlgebraic_idealCharacter {χ : HeckeCharacter K} (hχ : χ.IsAlgebraic)
    (I : idealsPrimeTo ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩) :
    _root_.IsAlgebraic ℚ (χ.idealCharacter I : ℂ) := by
  classical
  obtain ⟨n, e, hn⟩ := isAlgebraic_iff.mp hχ
  have hn' : χ.infinityType.AgreesOnIdentityComponent (AlgebraicInfinityType.toContinuous n) :=
    (ContinuousInfinityType.agreesOnIdentityComponent_iff_exists_finiteOrderInfinityType
      χ.infinityType (AlgebraicInfinityType.toContinuous n)).mpr ⟨e, hn⟩
  let 𝔣 : Modulus K := ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, ∅⟩
  let 𝔪 : Modulus K :=
    ⟨χ.finiteConductor, χ.finiteConductor_ne_bot, (narrowModulus K).infinitePart⟩
  let J : idealsPrimeTo 𝔪 := ⟨(I : (FractionalIdeal (𝓞 K)⁰ K)ˣ),
    NumberFieldArithmetic.mem_idealsAway_iff.mpr fun v hv ↦
      (NumberFieldArithmetic.mem_idealsAway_iff.mp I.property) v
        ((𝔣.mem_support_iff v).mpr ((𝔪.mem_support_iff v).mp hv))⟩
  let N := Nat.card (RayClassGroup 𝔪)
  have hN : 0 < N := Nat.card_pos
  have hJ : J ^ N ∈ ray 𝔪 := by
    rw [← rayClassMk_eq_one_iff, map_pow]
    exact pow_card_eq_one'
  obtain ⟨x, hx, hxJ⟩ := mem_ray_iff.mp hJ
  have hfm : 𝔣 ∣ 𝔪 := Modulus.dvd_iff.mpr ⟨dvd_refl _, Finset.empty_subset _⟩
  have hxf : IsCongrOne 𝔣 x := hx.mono hfm
  have hpos : IsTotallyPositive (x : K) := isTotallyPositive_iff.mpr fun w hw ↦
    hx.pos (mem_narrowModulus_infinitePart ⟨w, hw⟩)
  have hI : I ^ N = ⟨toPrincipalIdeal (𝓞 K) K x, hxf.toPrincipalIdeal_mem_idealsPrimeTo⟩ :=
    Subtype.ext hxJ.symm
  have hpower : (χ.idealCharacter I : ℂ) ^ N = (n.embeddingCharacter x : ℂ)⁻¹ := by
    have h := congrArg (fun u : ℂˣ ↦ (u : ℂ))
      (χ.idealCharacter_apply_toPrincipalIdeal_eq_embeddingCharacter_inv n hn' x hxf hpos)
    rw [← hI, map_pow] at h
    simpa only [Units.val_pow_eq_pow_val, Units.val_inv_eq_inv_val] using h
  -- The embedding monomial lies in the algebraic closure of the rationals.
  have hmono : (n.embeddingCharacter x : ℂ) ∈ algebraicClosure ℚ ℂ := by
    rw [AlgebraicInfinityType.coe_embeddingCharacter_apply]
    refine prod_mem fun σ _ ↦ zpow_mem ?_ _
    exact mem_algebraicClosure_iff.mpr
      ((_root_.IsAlgebraic.algHom σ.toRatAlgHom) ((NumberField.isAlgebraic K).isAlgebraic (x : K)))
  have halg : _root_.IsAlgebraic ℚ ((n.embeddingCharacter x : ℂ)⁻¹) :=
    mem_algebraicClosure_iff.mp (inv_mem hmono)
  exact _root_.IsAlgebraic.of_pow hN (hpower.symm ▸ halg)

end HeckeCharacter
end TauCeti.GlobalNumberFields
