/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.PDCode.Alexander.ReidemeisterThree
public import TauCeti.KnotTheory.PDCode.Alexander.ReidemeisterTwo.Basic
public import TauCeti.KnotTheory.PDCode.Alexander.ReidemeisterTwo.CircleArc
public import TauCeti.KnotTheory.PDCode.Alexander.ReidemeisterTwo.Circles
public import TauCeti.KnotTheory.PDCode.Oriented.Reidemeister.Equivalence

/-!
# The Alexander module is an invariant of Reidemeister equivalence

Every generating move of Reidemeister equivalence (`TauCeti.OrientedPDCode.IsReidemeisterMove`)
keeps the Alexander module of an oriented PD-code up to `ℤ[T;T⁻¹]`-linear equivalence: the
isomorphisms of codes and the first move in `TauCeti.KnotTheory.PDCode.Alexander.Invariance`, the
three forms of the second move in `TauCeti.KnotTheory.PDCode.Alexander.ReidemeisterTwo`, and the
third move in `TauCeti.KnotTheory.PDCode.Alexander.ReidemeisterThree`. Hence Reidemeister
equivalent codes have linearly equivalent Alexander modules, and so the same elementary ideals.
For a knot diagram, `E₁` is generated by the Alexander polynomial, which is therefore an invariant
of the Reidemeister class (Crowell–Fox, Chapter VII; Lickorish, Chapter 6).

## Main results

* `TauCeti.OrientedPDCode.ReidemeisterEquiv.nonempty_alexanderModule_linearEquiv`: Reidemeister
  equivalent codes have `ℤ[T;T⁻¹]`-linearly equivalent Alexander modules.
* `TauCeti.OrientedPDCode.ReidemeisterEquiv.elementaryIdeal_eq`: Reidemeister equivalent codes
  have the same elementary ideals.

## References

* R. H. Crowell and R. H. Fox, *Introduction to Knot Theory*, Graduate Texts in Mathematics 57,
  Springer (1977), Chapters VI–VII.
* W. B. R. Lickorish, *An Introduction to Knot Theory*, Graduate Texts in Mathematics 175,
  Springer (1997), Chapters 1 and 6.
-/

public section

open LaurentPolynomial

namespace TauCeti.OrientedPDCode

/-- Every generating move of Reidemeister equivalence keeps the Alexander module up to
`ℤ[T;T⁻¹]`-linear equivalence. -/
theorem IsReidemeisterMove.nonempty_alexanderModule_linearEquiv {x y : Σ n, OrientedPDCode n}
    (h : IsReidemeisterMove x y) :
    Nonempty (x.2.AlexanderModule ≃ₗ[ℤ[T;T⁻¹]] y.2.AlexanderModule) := by
  cases h with
  | relabel D half cross => exact ⟨(D.alexanderModuleRelabelEquiv half cross).symm⟩
  | rotateCrossing D i => exact ⟨(D.alexanderModuleRotateCrossingEquiv i).symm⟩
  | reidemeisterOne D h b => exact ⟨(D.alexanderModuleReidemeisterOneEquiv h b).symm⟩
  | adjoinKink D o b => exact ⟨(D.alexanderModuleAdjoinKinkEquiv o b).symm⟩
  | insertClasp D p q b hqp hqe => exact ⟨(D.alexanderModuleInsertClaspEquiv p q b hqp hqe).symm⟩
  | insertCircleClasp D p o b => exact ⟨(D.alexanderModuleInsertCircleClaspEquiv p o b).symm⟩
  | adjoinTwoCircleClasp D o₁ o₂ b =>
    exact ⟨(D.alexanderModuleAdjoinTwoCircleClaspEquiv o₁ o₂ b).symm⟩
  | reidemeisterThree D c h => exact ⟨(D.alexanderModuleReidemeisterThreeEquiv c h).symm⟩

namespace ReidemeisterEquiv

variable {n m : ℕ} {D : OrientedPDCode n} {D' : OrientedPDCode m}

/-- **The Alexander module is an invariant of Reidemeister equivalence**: Reidemeister equivalent
codes have `ℤ[T;T⁻¹]`-linearly equivalent Alexander modules. -/
theorem nonempty_alexanderModule_linearEquiv (h : ReidemeisterEquiv D D') :
    Nonempty (D.AlexanderModule ≃ₗ[ℤ[T;T⁻¹]] D'.AlexanderModule) := by
  suffices ∀ x y, Relation.EqvGen IsReidemeisterMove x y →
      Nonempty (x.2.AlexanderModule ≃ₗ[ℤ[T;T⁻¹]] y.2.AlexanderModule) from
    this _ _ ((reidemeisterEquiv_def D D').1 h)
  intro x y h
  induction h with
  | rel x y hxy => exact hxy.nonempty_alexanderModule_linearEquiv
  | refl x => exact ⟨LinearEquiv.refl _ _⟩
  | symm x y _ ih => exact ih.map LinearEquiv.symm
  | trans x y z _ _ ihxy ihyz =>
    obtain ⟨e⟩ := ihxy
    obtain ⟨e'⟩ := ihyz
    exact ⟨e.trans e'⟩

/-- **The elementary ideals are invariants of Reidemeister equivalence.** In particular so is the
ideal `E₁` that the Alexander polynomial of a knot diagram generates. -/
theorem elementaryIdeal_eq (h : ReidemeisterEquiv D D') (k : ℕ) :
    D.elementaryIdeal k = D'.elementaryIdeal k := by
  obtain ⟨e⟩ := h.nonempty_alexanderModule_linearEquiv
  rw [elementaryIdeal_def, elementaryIdeal_def]
  exact fittingIdeal_congr e k

end ReidemeisterEquiv

end TauCeti.OrientedPDCode
