/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.Exact.Graded.Basic
public import TauCeti.CategoryTheory.GrothendieckGroup.Abelian
public import TauCeti.CategoryTheory.GrothendieckGroup.Exact
public import TauCeti.CategoryTheory.GrothendieckGroup.Triangulated

/-!
# The grading shift on the Grothendieck groups

The grading shift `{1}` of a graded exact category `TauCeti.GradedExactStructure` is an
autoequivalence whose functor and inverse are both conflation-exact, so it induces an
*automorphism* `TauCeti.GradedExactStructure.shiftEquiv` of the exact Grothendieck group,
sending `[M]` to `[M{1}]`.  Iterating it gives the `ℤ`-action
`TauCeti.GradedExactStructure.shiftZPow` for which the Laurent-coefficient layer will read
`[M{n}] = qⁿ [M]`.

The underlying group of a graded category is not a new object: it is the corresponding ungraded
`K₀`.  Nothing is redefined here.  The namespaces `TauCeti.SplitK0`, `TauCeti.AbelianK0` and
`TauCeti.TriangulatedK0` provide the shift actions and graded universal properties for the split,
abelian and triangulated products, while `TauCeti.GradedExactStructure` provides them for exact
`K₀`.

The grading shift of a graded exact category is bundled with the exact structure, because the
exact structure is itself data and the shift has to be compatible with the chosen one.  In the
split, abelian and triangulated cases the ambient structure is a typeclass, so no bundling is
needed and the shift is passed as a bare autoequivalence, subject only to the hypotheses which
make it act on the group in question: additivity, and in the triangulated case commutation with
the suspension together with triangulatedness of the shift functor.  Those triangulated
hypotheses are lighter than the exact ones in one specific way, recorded at
`TauCeti.TriangulatedK0.shiftZPow`: exactness of the *inverse* shift is a separate assumption for
an exact category, whereas the inverse of a triangulated equivalence is automatically
triangulated.

## Main definitions

* `TauCeti.GradedExactStructure.shiftEquiv`: the automorphism `[M] ↦ [M{1}]` of exact `K₀`.
* `TauCeti.GradedExactStructure.shiftZPow`: the `ℤ`-action generated by that automorphism.
* `TauCeti.GradedExactStructure.ShiftInvariant`: a conflation-additive invariant equipped with a
  compatible invertible shift action.
* `TauCeti.SplitK0.shiftZPow`, `TauCeti.AbelianK0.shiftZPow` and
  `TauCeti.TriangulatedK0.shiftZPow`: the corresponding actions on split, abelian and
  triangulated `K₀`.
* `TauCeti.TriangulatedK0.ShiftInvariant`: a triangle-additive invariant equipped with a
  compatible invertible shift action.

## Main results

* `TauCeti.GradedExactStructure.ShiftInvariant.liftEquiv`: the universal property of exact `K₀`
  in the graded setting.
* `TauCeti.GradedExactStructure.map_shiftEquiv`: a graded conflation-exact functor induces a
  shift-equivariant homomorphism.
* `TauCeti.GradedExactStructure.map_shiftEquiv_of_commShift`: forgetting the grading along a
  conflation-exact functor which commutes with the shift induces a shift-invariant homomorphism.
* `TauCeti.TriangulatedK0.ShiftInvariant.liftEquiv`, `TauCeti.TriangulatedK0.map_shiftEquiv` and
  `TauCeti.TriangulatedK0.map_shiftEquiv_of_commShift`: the same three statements for
  triangulated `K₀`.
* `TauCeti.TriangulatedK0.shiftZPow_of_shift`: the grading shift and the suspension act on
  triangulated `K₀` by commuting operators, the suspension acting by the sign `(-1)ⁿ`.
* `TauCeti.TriangulatedK0.shiftZPow_apply_of_iso_shiftFunctor`: a grading shift isomorphic to the
  suspension acts by `(-1)ⁿ`, so the action factors through the parity of `n`; it is never free,
  and it is nontrivial whenever some class is not its own negative.
* `TauCeti.GradedExactStructure.fromSplit_shiftZPow` and
  `TauCeti.TriangulatedK0.fromSplit_shiftZPow`: the comparisons out of graded split `K₀` are
  equivariant.

## References

* Charles A. Weibel, *The K-book: An Introduction to Algebraic K-theory*, Chapter II,
  Section 7, for the exact `K₀` on which the grading shift acts here; the graded group is that
  group, and has no construction of its own.
* Charles A. Weibel, *The K-book: An Introduction to Algebraic K-theory*, Chapter II,
  Exercise II.9.15, for the triangulated `K₀` on which the grading shift acts here.
* `TauCetiRoadmap/GrothendieckEulerForms/README.md`, Layer 2, which asks for the graded
  Grothendieck groups "each carrying the induced `ℤ`-action `[M{n}]` of the shift, with the
  universal property for invariants equipped with a compatible invertible shift action", and
  defers the Laurent-module repackaging of that action to Layer 6.
-/

public section

namespace TauCeti

open CategoryTheory CategoryTheory.Limits

universe w w' v v' u u'

namespace SplitK0

section Shift

variable {C : Type u} [Category.{v} C] [HasZeroMorphisms C] [HasBinaryBiproducts C]
  [EssentiallySmall.{w} C]

/-- **The `ℤ`-action of a grading shift on split `K₀`**, generated by the equivalence induced by
the autoequivalence. -/
noncomputable def shiftZPow (e : C ≌ C) : ℤ →+ AddAut (SplitK0 C) :=
  zmultiplesHom _ (mapEquiv e)

@[simp]
lemma shiftZPow_apply (e : C ≌ C) (n : ℤ) :
    shiftZPow e n = n • mapEquiv e :=
  (rfl)

/-- The generator of the split `K₀` action sends an object class to the class of its shift. -/
-- Not `@[simp]`: `shiftZPow_apply`, `one_smul`, and `mapEquiv_of` already normalize the left side.
lemma shiftZPow_one_apply_of (e : C ≌ C) (X : C) :
    shiftZPow e 1 (of X) = of (e.functor.obj X) := by
  simp

/-- Shifting by `n + 1` on split `K₀` is shifting by `n` and then once more. -/
lemma shiftZPow_add_one_apply (e : C ≌ C) (n : ℤ) (x : SplitK0 C) :
    shiftZPow e (n + 1) x = mapEquiv e (shiftZPow e n x) := by
  rw [add_comm, map_add, AddAut.add_apply, shiftZPow_apply, one_zsmul]

/-- Shifting by `n - 1` on split `K₀` is shifting by `n` and then back once. -/
lemma shiftZPow_sub_one_apply (e : C ≌ C) (n : ℤ) (x : SplitK0 C) :
    shiftZPow e (n - 1) x = (mapEquiv e).symm (shiftZPow e n x) := by
  rw [sub_eq_neg_add, map_add, AddAut.add_apply]
  simp [shiftZPow]

end Shift

section UniversalProperty

variable {C : Type u} [Category.{v} C] [HasZeroMorphisms C] [HasBinaryBiproducts C]
  [EssentiallySmall.{w} C] {G : Type*} [AddCommGroup G]

variable (C) in
/-- A biproduct-additive invariant equipped with a compatible invertible grading-shift action. -/
@[ext]
structure ShiftInvariant (e : C ≌ C) (σ : AddAut G) extends
    AdditiveInvariant C G where
  /-- The invariant intertwines the grading shift with `σ`. -/
  map_shift : ∀ X : C, obj (e.functor.obj X) = σ (obj X)

namespace ShiftInvariant

variable {e : C ≌ C} {σ : AddAut G}

/-- The homomorphism out of split `K₀` induced by a shift-compatible invariant. -/
noncomputable def lift (a : ShiftInvariant C e σ) : SplitK0 C →+ G :=
  SplitK0.lift a.toAdditiveInvariant

@[simp]
lemma lift_of (a : ShiftInvariant C e σ) (X : C) : a.lift (of X) = a.obj X :=
  SplitK0.lift_of _ X

/-- The induced homomorphism intertwines the grading shift with the target automorphism. -/
theorem lift_mapEquiv (a : ShiftInvariant C e σ) (x : SplitK0 C) :
    a.lift (mapEquiv e x) = σ (a.lift x) := by
  have key : a.lift.comp (mapEquiv e).toAddMonoidHom =
      (σ : G ≃+ G).toAddMonoidHom.comp a.lift :=
    SplitK0.hom_ext fun X => by simp [a.map_shift X]
  exact DFunLike.congr_fun key x

/-- **The universal property of graded split `K₀`**: shift-compatible biproduct-additive
invariants correspond to homomorphisms intertwining the chosen automorphisms. -/
noncomputable def liftEquiv (e : C ≌ C) (σ : AddAut G) :
    ShiftInvariant C e σ ≃
      {f : SplitK0 C →+ G // ∀ x, f (mapEquiv e x) = σ (f x)} where
  toFun a := ⟨a.lift, a.lift_mapEquiv⟩
  invFun f :=
    { toAdditiveInvariant := SplitK0.liftEquiv.symm f.1
      map_shift := fun X => by simpa using f.2 (of X) }
  left_inv a := by ext X; simp
  right_inv f :=
    Subtype.ext
      (SplitK0.lift_unique _ f.1 fun X => (SplitK0.liftEquiv_symm_apply_obj f.1 X).symm).symm

@[simp]
lemma liftEquiv_apply (a : ShiftInvariant C e σ) :
    (liftEquiv e σ a).1 = a.lift :=
  (rfl)

@[simp]
lemma liftEquiv_symm_apply_obj
    (f : {f : SplitK0 C →+ G // ∀ x, f (mapEquiv e x) = σ (f x)}) (X : C) :
    ((liftEquiv e σ).symm f).obj X = f.1 (of X) :=
  SplitK0.liftEquiv_symm_apply_obj f.1 X

end ShiftInvariant

end UniversalProperty

end SplitK0

namespace AbelianK0

section Shift

variable {A : Type u} [Category.{v} A] [Abelian A] [EssentiallySmall.{w} A]

/-- **The `ℤ`-action of a grading shift on abelian `K₀`**, generated by the equivalence induced
by the additive autoequivalence. -/
noncomputable def shiftZPow (e : A ≌ A) [e.functor.Additive] : ℤ →+ AddAut (AbelianK0 A) :=
  zmultiplesHom _ (mapEquiv e)

@[simp]
lemma shiftZPow_apply (e : A ≌ A) [e.functor.Additive] (n : ℤ) :
    shiftZPow e n = n • mapEquiv e :=
  (rfl)

/-- The generator of the abelian `K₀` action sends an object class to the class of its shift. -/
-- Not `@[simp]`: `shiftZPow_apply`, `one_smul`, and `mapEquiv_of` already normalize the left side.
lemma shiftZPow_one_apply_of (e : A ≌ A) [e.functor.Additive] (X : A) :
    shiftZPow e 1 (of X) = of (e.functor.obj X) := by
  simp

/-- Shifting by `n + 1` on abelian `K₀` is shifting by `n` and then once more. -/
lemma shiftZPow_add_one_apply (e : A ≌ A) [e.functor.Additive] (n : ℤ) (x : AbelianK0 A) :
    shiftZPow e (n + 1) x = mapEquiv e (shiftZPow e n x) := by
  rw [add_comm, map_add, AddAut.add_apply, shiftZPow_apply, one_zsmul]

/-- Shifting by `n - 1` on abelian `K₀` is shifting by `n` and then back once. -/
lemma shiftZPow_sub_one_apply (e : A ≌ A) [e.functor.Additive] (n : ℤ) (x : AbelianK0 A) :
    shiftZPow e (n - 1) x = (mapEquiv e).symm (shiftZPow e n x) := by
  rw [sub_eq_neg_add, map_add, AddAut.add_apply]
  simp [shiftZPow]

end Shift

section UniversalProperty

variable {A : Type u} [Category.{v} A] [Abelian A] [EssentiallySmall.{w} A]
  {G : Type*} [AddCommGroup G]

variable (A) in
/-- A short-exact-additive invariant equipped with a compatible invertible grading-shift action. -/
@[ext]
structure ShiftInvariant (e : A ≌ A) [e.functor.Additive] (σ : AddAut G) extends
    AdditiveInvariant A G where
  /-- The invariant intertwines the grading shift with `σ`. -/
  map_shift : ∀ X : A, obj (e.functor.obj X) = σ (obj X)

namespace ShiftInvariant

variable {e : A ≌ A} [e.functor.Additive] {σ : AddAut G}

/-- The homomorphism out of abelian `K₀` induced by a shift-compatible invariant. -/
noncomputable def lift (a : ShiftInvariant A e σ) : AbelianK0 A →+ G :=
  AbelianK0.lift a.toAdditiveInvariant

@[simp]
lemma lift_of (a : ShiftInvariant A e σ) (X : A) : a.lift (of X) = a.obj X :=
  AbelianK0.lift_of _ X

/-- The induced homomorphism intertwines the grading shift with the target automorphism. -/
theorem lift_mapEquiv (a : ShiftInvariant A e σ) (x : AbelianK0 A) :
    a.lift (mapEquiv e x) = σ (a.lift x) := by
  have key : a.lift.comp (mapEquiv e).toAddMonoidHom =
      (σ : G ≃+ G).toAddMonoidHom.comp a.lift :=
    AbelianK0.hom_ext fun X => by simp [a.map_shift X]
  simpa using DFunLike.congr_fun key x

/-- **The universal property of graded abelian `K₀`**: shift-compatible short-exact-additive
invariants correspond to homomorphisms intertwining the chosen automorphisms. -/
noncomputable def liftEquiv (e : A ≌ A) [e.functor.Additive] (σ : AddAut G) :
    ShiftInvariant A e σ ≃
      {f : AbelianK0 A →+ G // ∀ x, f (mapEquiv e x) = σ (f x)} where
  toFun a := ⟨a.lift, a.lift_mapEquiv⟩
  invFun f :=
    { toAdditiveInvariant := AbelianK0.liftEquiv.symm f.1
      map_shift := fun X => by simpa using f.2 (of X) }
  left_inv a := by ext X; simp
  right_inv f :=
    Subtype.ext
      (AbelianK0.lift_unique _ f.1 fun X =>
        (AbelianK0.liftEquiv_symm_apply_obj f.1 X).symm).symm

@[simp]
lemma liftEquiv_apply (a : ShiftInvariant A e σ) :
    (liftEquiv e σ a).1 = a.lift :=
  (rfl)

@[simp]
lemma liftEquiv_symm_apply_obj
    (f : {f : AbelianK0 A →+ G // ∀ x, f (mapEquiv e x) = σ (f x)}) (X : A) :
    ((liftEquiv e σ).symm f).obj X = f.1 (of X) :=
  AbelianK0.liftEquiv_symm_apply_obj f.1 X

end ShiftInvariant

end UniversalProperty

end AbelianK0

namespace GradedExactStructure

section Shift

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasBinaryBiproducts C]
  [EssentiallySmall.{w} C] (E : GradedExactStructure C)

/-- **The grading shift on exact `K₀`**: the automorphism `[M] ↦ [M{1}]` induced by the grading
shift of a graded exact category.  Conflation-exactness of the shift and its inverse constructs
this equivalence with the map induced by the inverse shift as its inverse. -/
noncomputable def shiftEquiv : ExactK0 E.toExactStructure ≃+ ExactK0 E.toExactStructure :=
  ExactK0.mapEquiv E.shift E.shift_exact E.shift_inverse_exact

@[simp]
lemma shiftEquiv_of (X : C) :
    E.shiftEquiv (ExactK0.of X) =
      (ExactK0.of (E.shift.functor.obj X) : ExactK0 E.toExactStructure) :=
  ExactK0.mapEquiv_of _ _ _ X

@[simp]
lemma shiftEquiv_symm_of (X : C) :
    E.shiftEquiv.symm (ExactK0.of X) =
      (ExactK0.of (E.shift.inverse.obj X) : ExactK0 E.toExactStructure) :=
  ExactK0.mapEquiv_symm_of _ _ _ X

/-- The grading shift is the unique endomorphism of exact `K₀` sending the class of an object to
the class of its shift. -/
theorem shiftEquiv_unique (f : ExactK0 E.toExactStructure →+ ExactK0 E.toExactStructure)
    (hf : ∀ X : C, f (ExactK0.of X) = ExactK0.of (E.shift.functor.obj X)) :
    f = E.shiftEquiv.toAddMonoidHom :=
  ExactK0.hom_ext fun X => by simp [hf]

/-- **The `ℤ`-action of the grading shift on exact `K₀`**, sending `n` to the `n`-fold shift
`[M] ↦ [M{n}]`.  Mathlib writes the automorphism group of an additive group additively, so the
`n`-fold shift is `n • E.shiftEquiv`; the Laurent-module repackaging of this action, in which it
becomes multiplication by `qⁿ`, belongs to the coefficient layer downstream. -/
noncomputable def shiftZPow : ℤ →+ AddAut (ExactK0 E.toExactStructure) :=
  zmultiplesHom _ E.shiftEquiv

@[simp]
lemma shiftZPow_apply (n : ℤ) : E.shiftZPow n = n • E.shiftEquiv :=
  -- `(rfl)` rather than `rfl`: a bare `rfl` proof would demand that `shiftZPow` be `@[expose]`,
  -- and this lemma is the supported unfolding interface instead.
  (rfl)

/-- The generator of the `ℤ`-action is the shift itself: `[M{1}]` is the class of `M{1}`. -/
-- Not `@[simp]`: `shiftZPow_apply`, `one_smul`, and `shiftEquiv_of` already normalize this.
lemma shiftZPow_one_apply_of (X : C) :
    E.shiftZPow 1 (ExactK0.of X) =
      (ExactK0.of (E.shift.functor.obj X) : ExactK0 E.toExactStructure) := by
  simp

/-- The inverse generator of the `ℤ`-action is the inverse shift. -/
lemma shiftZPow_neg_one_apply (x : ExactK0 E.toExactStructure) :
    E.shiftZPow (-1) x = E.shiftEquiv.symm x := by
  simp [shiftZPow]

-- Not `@[simp]`: the existing shift action and inverse-equivalence simp lemmas normalize this.
lemma shiftZPow_neg_one_apply_of (X : C) :
    E.shiftZPow (-1) (ExactK0.of X) =
      (ExactK0.of (E.shift.inverse.obj X) : ExactK0 E.toExactStructure) := by
  rw [shiftZPow_neg_one_apply, shiftEquiv_symm_of]

/-- Shifting by `n + 1` is shifting by `n` and then once more: this is `[M{n+1}] = [(M{n}){1}]`. -/
lemma shiftZPow_add_one_apply (n : ℤ) (x : ExactK0 E.toExactStructure) :
    E.shiftZPow (n + 1) x = E.shiftEquiv (E.shiftZPow n x) := by
  rw [add_comm, map_add, AddAut.add_apply, shiftZPow_apply, one_zsmul]

/-- Shifting by `n - 1` is shifting by `n` and then back once. -/
lemma shiftZPow_sub_one_apply (n : ℤ) (x : ExactK0 E.toExactStructure) :
    E.shiftZPow (n - 1) x = E.shiftEquiv.symm (E.shiftZPow n x) := by
  rw [sub_eq_neg_add, map_add, AddAut.add_apply, shiftZPow_neg_one_apply]

end Shift

section UniversalProperty

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasBinaryBiproducts C]
  [EssentiallySmall.{w} C] {G : Type*} [AddCommGroup G]

variable (E : GradedExactStructure C) in
/-- A conflation-additive invariant equipped with a compatible invertible shift action: its value
on `M{1}` is the value on `M` moved by the given automorphism `σ` of the target. -/
@[ext]
structure ShiftInvariant (σ : AddAut G) extends
    ExactK0.AdditiveInvariant E.toExactStructure G where
  /-- The invariant intertwines the grading shift with `σ`. -/
  map_shift : ∀ X : C, obj (E.shift.functor.obj X) = σ (obj X)

namespace ShiftInvariant

variable {E : GradedExactStructure C} {σ : AddAut G}

/-- The homomorphism out of exact `K₀` induced by a shift-compatible invariant.  It is the
ungraded lift; the shift compatibility is extra information about it, not a change of
construction. -/
noncomputable def lift (a : ShiftInvariant E σ) : ExactK0 E.toExactStructure →+ G :=
  ExactK0.lift a.toAdditiveInvariant

@[simp]
lemma lift_of (a : ShiftInvariant E σ) (X : C) : a.lift (ExactK0.of X) = a.obj X :=
  ExactK0.lift_of _ X

/-- **The induced homomorphism is shift-equivariant.** -/
theorem lift_shiftEquiv (a : ShiftInvariant E σ) (x : ExactK0 E.toExactStructure) :
    a.lift (E.shiftEquiv x) = σ (a.lift x) := by
  have key : a.lift.comp E.shiftEquiv.toAddMonoidHom = (σ : G ≃+ G).toAddMonoidHom.comp a.lift :=
    ExactK0.hom_ext fun X => by simp [a.map_shift X]
  simpa using DFunLike.congr_fun key x

/-- **The universal property of exact `K₀` in the graded setting**: for a fixed automorphism `σ`
of `G`, conflation-additive invariants compatible with the grading shift through `σ` correspond
bijectively to the homomorphisms `ExactK0 E →+ G` intertwining the shift with `σ`. -/
noncomputable def liftEquiv (σ : AddAut G) :
    ShiftInvariant E σ ≃
      {f : ExactK0 E.toExactStructure →+ G // ∀ x, f (E.shiftEquiv x) = σ (f x)} where
  toFun a := ⟨a.lift, a.lift_shiftEquiv⟩
  invFun f :=
    { toAdditiveInvariant := ExactK0.liftEquiv.symm f.1
      map_shift := fun X => by simpa using f.2 (ExactK0.of X) }
  left_inv a := by ext X; simp
  right_inv f :=
    Subtype.ext
      (ExactK0.lift_unique _ f.1 fun X => (ExactK0.liftEquiv_symm_apply_obj f.1 X).symm).symm

@[simp]
lemma liftEquiv_apply (a : ShiftInvariant E σ) :
    (liftEquiv σ a).1 = a.lift :=
  (rfl)

@[simp]
lemma liftEquiv_symm_apply_obj
    (f : {f : ExactK0 E.toExactStructure →+ G //
      ∀ x, f (E.shiftEquiv x) = σ (f x)}) (X : C) :
    ((liftEquiv σ).symm f).obj X = f.1 (ExactK0.of X) :=
  ExactK0.liftEquiv_symm_apply_obj f.1 X

end ShiftInvariant

end UniversalProperty

section Functoriality

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasBinaryBiproducts C]
  [EssentiallySmall.{w} C]
variable {D : Type u'} [Category.{v'} D] [Preadditive D] [HasZeroObject D]
  [HasBinaryBiproducts D] [EssentiallySmall.{w'} D]
variable {E : GradedExactStructure C} {F : C ⥤ D} [F.Additive]

/-- **A graded conflation-exact functor induces a shift-equivariant homomorphism** of exact
Grothendieck groups: the commutation isomorphism with the two grading shifts is exactly what
makes the square commute. -/
theorem map_shiftEquiv {E' : GradedExactStructure D} (h : GradedConflationExact E E' F)
    (x : ExactK0 E.toExactStructure) :
    ExactK0.map F h.isConflationExact (E.shiftEquiv x) =
      E'.shiftEquiv (ExactK0.map F h.isConflationExact x) := by
  have key : (ExactK0.map F h.isConflationExact).comp E.shiftEquiv.toAddMonoidHom =
      E'.shiftEquiv.toAddMonoidHom.comp (ExactK0.map F h.isConflationExact) :=
    ExactK0.hom_ext fun X => by
      simpa using ExactK0.of_congr (E := E'.toExactStructure) (h.commShift.app X)
  simpa using DFunLike.congr_fun key x

/-- The equivariance of the induced homomorphism for the inverse shift. -/
theorem map_shiftEquiv_symm {E' : GradedExactStructure D} (h : GradedConflationExact E E' F)
    (x : ExactK0 E.toExactStructure) :
    ExactK0.map F h.isConflationExact (E.shiftEquiv.symm x) =
      E'.shiftEquiv.symm (ExactK0.map F h.isConflationExact x) := by
  refine (AddEquiv.eq_symm_apply _).mpr ?_
  rw [← map_shiftEquiv h, AddEquiv.apply_symm_apply]

/-- **Equivariance for the whole `ℤ`-action**: a graded conflation-exact functor carries `[M{n}]`
to `[(FM){n}]` for every integer `n`. -/
theorem map_shiftZPow {E' : GradedExactStructure D} (h : GradedConflationExact E E' F) (n : ℤ)
    (x : ExactK0 E.toExactStructure) :
    ExactK0.map F h.isConflationExact (E.shiftZPow n x) =
      E'.shiftZPow n (ExactK0.map F h.isConflationExact x) := by
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih => rw [shiftZPow_add_one_apply, map_shiftEquiv h, ih, shiftZPow_add_one_apply]
  | pred k ih => rw [shiftZPow_sub_one_apply, map_shiftEquiv_symm h, ih, shiftZPow_sub_one_apply]

/-- **Forgetting the grading.**  A conflation-exact functor into an ungraded exact category which
commutes with the grading shift induces a homomorphism of exact Grothendieck groups sending the
class of `M{1}` and the class of `M` to the same element, that is, one invariant under the
grading shift.

The factorization of this map through the specialization of graded `K₀` at `q = 1`, and
sufficient hypotheses for the factored map to be an isomorphism, are
`TauCeti.LaurentK0.forgetGrading` and `TauCeti.LaurentK0.forgetGradingEquiv`. -/
theorem map_shiftEquiv_of_commShift {E' : ExactStructure D}
    (hU : E.toExactStructure.IsConflationExact E' F) (comm : E.shift.functor ⋙ F ≅ F)
    (x : ExactK0 E.toExactStructure) :
    ExactK0.map F hU (E.shiftEquiv x) = ExactK0.map F hU x := by
  have key : (ExactK0.map F hU).comp E.shiftEquiv.toAddMonoidHom = ExactK0.map F hU :=
    ExactK0.hom_ext fun X => by
      simpa using ExactK0.of_congr (E := E') (comm.app X)
  simpa using DFunLike.congr_fun key x

/-- Forgetting the grading is invariant under the whole `ℤ`-action, not only under the
generating shift. -/
theorem map_shiftZPow_of_commShift {E' : ExactStructure D}
    (hU : E.toExactStructure.IsConflationExact E' F) (comm : E.shift.functor ⋙ F ≅ F) (n : ℤ)
    (x : ExactK0 E.toExactStructure) :
    ExactK0.map F hU (E.shiftZPow n x) = ExactK0.map F hU x := by
  have hsymm : ∀ y, ExactK0.map F hU (E.shiftEquiv.symm y) = ExactK0.map F hU y := fun y => by
    have h := map_shiftEquiv_of_commShift hU comm (E.shiftEquiv.symm y)
    rw [AddEquiv.apply_symm_apply] at h
    exact h.symm
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih => rw [shiftZPow_add_one_apply, map_shiftEquiv_of_commShift hU comm, ih]
  | pred k ih => rw [shiftZPow_sub_one_apply, hsymm, ih]

end Functoriality

section Comparison

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasBinaryBiproducts C]
  [EssentiallySmall.{w} C] (E : GradedExactStructure C)

/-- **The graded split Grothendieck group maps to the graded exact one.**  The shift of split
`K₀` is `TauCeti.SplitK0.mapEquiv` of the grading shift — no separate construction is needed,
since every additive functor preserves split conflations — and the comparison homomorphism
intertwines it with the shift of exact `K₀`. -/
theorem fromSplit_shiftEquiv (x : SplitK0 C) :
    ExactK0.fromSplit E.toExactStructure (SplitK0.mapEquiv E.shift x) =
      E.shiftEquiv (ExactK0.fromSplit E.toExactStructure x) := by
  have key : (ExactK0.fromSplit E.toExactStructure).comp
        (SplitK0.mapEquiv E.shift).toAddMonoidHom =
      E.shiftEquiv.toAddMonoidHom.comp (ExactK0.fromSplit E.toExactStructure) :=
    SplitK0.hom_ext fun X => by simp
  simpa only [AddMonoidHom.comp_apply, AddEquiv.coe_toAddMonoidHom] using
    DFunLike.congr_fun key x

/-- The comparison from graded split `K₀` to graded exact `K₀` intertwines the whole
`ℤ`-action. -/
theorem fromSplit_shiftZPow (n : ℤ) (x : SplitK0 C) :
    ExactK0.fromSplit E.toExactStructure (SplitK0.shiftZPow E.shift n x) =
      E.shiftZPow n (ExactK0.fromSplit E.toExactStructure x) := by
  have hsymm : ∀ y : SplitK0 C,
      ExactK0.fromSplit E.toExactStructure ((SplitK0.mapEquiv E.shift).symm y) =
        E.shiftEquiv.symm (ExactK0.fromSplit E.toExactStructure y) := fun y => by
    refine (AddEquiv.eq_symm_apply E.shiftEquiv).mpr ?_
    rw [← fromSplit_shiftEquiv, AddEquiv.apply_symm_apply]
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih =>
      rw [SplitK0.shiftZPow_add_one_apply, fromSplit_shiftEquiv, ih,
        shiftZPow_add_one_apply]
  | pred k ih =>
      rw [SplitK0.shiftZPow_sub_one_apply, hsymm, ih, shiftZPow_sub_one_apply]

end Comparison

end GradedExactStructure

namespace TriangulatedK0

open CategoryTheory.Pretriangulated

section Shift

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasShift C ℤ]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] [EssentiallySmall.{w} C]
  (e : C ≌ C) [e.functor.CommShift ℤ] [e.functor.IsTriangulated]

/-- **The `ℤ`-action of a grading shift on triangulated `K₀`**, generated by the isomorphism
induced by the triangulated autoequivalence.

The hypotheses on the grading shift are lighter here than in the exact case.  A graded exact
category must record conflation-exactness of the inverse shift separately, because an
autoequivalence can enlarge the class of conflations strictly; for a triangulated autoequivalence
`CategoryTheory.Equivalence.IsTriangulated.mk'` derives the hypothesis on the inverse from the one
on the functor, since the inverse is an adjoint of a triangulated functor. -/
noncomputable def shiftZPow : ℤ →+ AddAut (TriangulatedK0 C) :=
  zmultiplesHom _ (mapEquiv e)

@[simp]
lemma shiftZPow_apply (n : ℤ) : shiftZPow e n = n • mapEquiv e :=
  (rfl)

/-- The generator of the triangulated `K₀` action sends an object class to the class of its
shift. -/
-- Not `@[simp]`: `shiftZPow_apply`, `one_smul`, and `mapEquiv_of` already normalize the left side.
lemma shiftZPow_one_apply_of (X : C) :
    shiftZPow e 1 (of X) = of (e.functor.obj X) := by
  simp

/-- Shifting by `n + 1` on triangulated `K₀` is shifting by `n` and then once more. -/
lemma shiftZPow_add_one_apply (n : ℤ) (x : TriangulatedK0 C) :
    shiftZPow e (n + 1) x = mapEquiv e (shiftZPow e n x) := by
  rw [add_comm, map_add, AddAut.add_apply, shiftZPow_apply, one_zsmul]

/-- Shifting by `n - 1` on triangulated `K₀` is shifting by `n` and then back once. -/
lemma shiftZPow_sub_one_apply (n : ℤ) (x : TriangulatedK0 C) :
    shiftZPow e (n - 1) x = (mapEquiv e).symm (shiftZPow e n x) := by
  rw [sub_eq_neg_add, map_add, AddAut.add_apply]
  simp [shiftZPow]

omit [e.functor.IsTriangulated] in
/-- **The grading shift commutes with the suspension.**  This is the commutation isomorphism
carried by the grading shift, read at the level of object classes; it is what makes the grading
shift of a graded triangulated category act on triangulated `K₀` at all. -/
theorem of_functor_obj_shift (n : ℤ) (X : C) :
    (of (e.functor.obj (X⟦n⟧)) : TriangulatedK0 C) = of ((e.functor.obj X)⟦n⟧) :=
  of_congr ((e.functor.commShiftIso n).app X)

/-- **The two shifts of a graded triangulated category on `K₀`.**  The suspension already acts by
the sign `(-1)ⁿ`, so the grading action, being additive, absorbs it: internal degree and
cohomological degree do not interact beyond that sign. -/
theorem shiftZPow_of_shift (n m : ℤ) (X : C) :
    shiftZPow e n (of (X⟦m⟧)) = (m.negOnePow : ℤ) • shiftZPow e n (of X) := by
  rw [of_shift, map_zsmul]

/-- **A grading shift isomorphic to the suspension acts by `-1`.**  Nothing forbids the internal
degree shift of a graded triangulated category from being the suspension itself, and then the
generator of the `ℤ`-action is negation. -/
theorem mapEquiv_apply_of_iso_shiftFunctor (h : e.functor ≅ shiftFunctor C (1 : ℤ))
    (x : TriangulatedK0 C) : mapEquiv e x = -x := by
  have key : (mapEquiv e).toAddMonoidHom = -AddMonoidHom.id (TriangulatedK0 C) :=
    hom_ext fun X => by
      simp only [AddEquiv.coe_toAddMonoidHom, mapEquiv_of, AddMonoidHom.neg_apply,
        AddMonoidHom.id_apply]
      rw [of_congr (h.app X), of_shift_one]
  exact DFunLike.congr_fun key x

/-- The inverse of a grading shift isomorphic to the suspension is again negation. -/
theorem mapEquiv_symm_apply_of_iso_shiftFunctor (h : e.functor ≅ shiftFunctor C (1 : ℤ))
    (x : TriangulatedK0 C) : (mapEquiv e).symm x = -x := by
  refine (AddEquiv.symm_apply_eq _).mpr ?_
  rw [mapEquiv_apply_of_iso_shiftFunctor e h, neg_neg]

/-- **The `ℤ`-action of a grading shift isomorphic to the suspension is the sign action**,
`[M{n}] = (-1)ⁿ[M]`.  The generator acts by negation, so the action factors through the parity of
`n`: it is never free, and it is nontrivial exactly when some class is not its own negative — on
a `K₀` of exponent two, negation is the identity and the action collapses.  Contrast
`TauCeti.GradedExactStructure.shiftZPow`, where no such factorization is available, exact `K₀`
having no suspension to be isomorphic to. -/
theorem shiftZPow_apply_of_iso_shiftFunctor (h : e.functor ≅ shiftFunctor C (1 : ℤ)) (n : ℤ)
    (x : TriangulatedK0 C) : shiftZPow e n x = (n.negOnePow : ℤ) • x := by
  have hpred : ∀ m : ℤ, (m - 1).negOnePow = -m.negOnePow := fun m => by
    rw [Int.negOnePow_sub, Int.negOnePow_one, mul_neg, mul_one]
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih =>
    rw [shiftZPow_add_one_apply, ih, mapEquiv_apply_of_iso_shiftFunctor e h, Int.negOnePow_succ,
      Units.val_neg, neg_zsmul]
  | pred k ih =>
    rw [shiftZPow_sub_one_apply, ih, mapEquiv_symm_apply_of_iso_shiftFunctor e h, hpred,
      Units.val_neg, neg_zsmul]

end Shift

section UniversalProperty

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasShift C ℤ]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] [EssentiallySmall.{w} C]
  {G : Type*} [AddCommGroup G]

variable (C) in
/-- A triangle-additive invariant equipped with a compatible invertible grading-shift action. -/
@[ext]
structure ShiftInvariant (e : C ≌ C) [e.functor.CommShift ℤ] [e.functor.IsTriangulated]
    (σ : AddAut G) extends AdditiveInvariant C G where
  /-- The invariant intertwines the grading shift with `σ`. -/
  map_shift : ∀ X : C, obj (e.functor.obj X) = σ (obj X)

namespace ShiftInvariant

variable {e : C ≌ C} [e.functor.CommShift ℤ] [e.functor.IsTriangulated]
  {σ : AddAut G}

/-- The homomorphism out of triangulated `K₀` induced by a shift-compatible invariant. -/
noncomputable def lift (a : ShiftInvariant C e σ) : TriangulatedK0 C →+ G :=
  TriangulatedK0.lift a.toAdditiveInvariant

@[simp]
lemma lift_of (a : ShiftInvariant C e σ) (X : C) : a.lift (of X) = a.obj X :=
  TriangulatedK0.lift_of _ X

/-- The induced homomorphism intertwines the grading shift with the target automorphism. -/
theorem lift_mapEquiv (a : ShiftInvariant C e σ) (x : TriangulatedK0 C) :
    a.lift (mapEquiv e x) = σ (a.lift x) := by
  have key : a.lift.comp (mapEquiv e).toAddMonoidHom =
      (σ : G ≃+ G).toAddMonoidHom.comp a.lift :=
    TriangulatedK0.hom_ext fun X => by simp [a.map_shift X]
  exact DFunLike.congr_fun key x

/-- The induced homomorphism intertwines the inverse grading shift with the inverse target
automorphism. -/
theorem lift_mapEquiv_symm (a : ShiftInvariant C e σ) (x : TriangulatedK0 C) :
    a.lift ((mapEquiv e).symm x) = σ.symm (a.lift x) := by
  refine (AddEquiv.eq_symm_apply σ).mpr ?_
  rw [← lift_mapEquiv, AddEquiv.apply_symm_apply]

/-- The induced homomorphism intertwines the whole `ℤ`-action with the powers of the target
automorphism. -/
theorem lift_shiftZPow (a : ShiftInvariant C e σ) (n : ℤ) (x : TriangulatedK0 C) :
    a.lift (shiftZPow e n x) = (n • σ) (a.lift x) := by
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih =>
    rw [shiftZPow_add_one_apply, lift_mapEquiv, ih, add_comm (k : ℤ) 1, add_zsmul, one_zsmul,
      AddAut.add_apply]
  | pred k ih =>
    rw [shiftZPow_sub_one_apply, lift_mapEquiv_symm, ih, sub_eq_neg_add, add_zsmul,
      AddAut.add_apply, neg_one_zsmul]
    simp

/-- **The universal property of graded triangulated `K₀`**: shift-compatible triangle-additive
invariants correspond to homomorphisms intertwining the chosen automorphisms. -/
noncomputable def liftEquiv (e : C ≌ C) [e.functor.CommShift ℤ] [e.functor.IsTriangulated]
    (σ : AddAut G) :
    ShiftInvariant C e σ ≃
      {f : TriangulatedK0 C →+ G // ∀ x, f (mapEquiv e x) = σ (f x)} where
  toFun a := ⟨a.lift, a.lift_mapEquiv⟩
  invFun f :=
    { toAdditiveInvariant := TriangulatedK0.liftEquiv.symm f.1
      map_shift := fun X => by simpa using f.2 (of X) }
  left_inv a := by ext X; simp
  right_inv f :=
    Subtype.ext
      (TriangulatedK0.lift_unique _ f.1 fun X =>
        (TriangulatedK0.liftEquiv_symm_apply_obj f.1 X).symm).symm

@[simp]
lemma liftEquiv_apply (a : ShiftInvariant C e σ) :
    (liftEquiv e σ a).1 = a.lift :=
  (rfl)

@[simp]
lemma liftEquiv_symm_apply_obj
    (f : {f : TriangulatedK0 C →+ G // ∀ x, f (mapEquiv e x) = σ (f x)}) (X : C) :
    ((liftEquiv e σ).symm f).obj X = f.1 (of X) :=
  TriangulatedK0.liftEquiv_symm_apply_obj f.1 X

end ShiftInvariant

end UniversalProperty

section Functoriality

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasShift C ℤ]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] [EssentiallySmall.{w} C]
variable {D : Type u'} [Category.{v'} D] [Preadditive D] [HasZeroObject D] [HasShift D ℤ]
  [∀ n : ℤ, (shiftFunctor D n).Additive] [Pretriangulated D] [EssentiallySmall.{w'} D]
variable {e : C ≌ C} [e.functor.CommShift ℤ] [e.functor.IsTriangulated]
  {e' : D ≌ D} [e'.functor.CommShift ℤ] [e'.functor.IsTriangulated]
  {F : C ⥤ D} [F.CommShift ℤ] [F.IsTriangulated]

/-- **A graded triangulated functor induces a shift-equivariant homomorphism** of triangulated
Grothendieck groups: the commutation isomorphism with the two grading shifts is exactly what makes
the square commute.

The isomorphism is a hypothesis here, where the exact case bundles it into
`TauCeti.GradedConflationExact`.  That bundling exists because a conflation-exact functor carries
the two exact structures it relates as data; being triangulated is a typeclass on the functor, so
there is nothing for a graded triangulated functor to bundle beyond this isomorphism. -/
theorem map_shiftEquiv (comm : e.functor ⋙ F ≅ F ⋙ e'.functor) (x : TriangulatedK0 C) :
    map F (mapEquiv e x) = mapEquiv e' (map F x) := by
  have key : (map F).comp (mapEquiv e).toAddMonoidHom =
      (mapEquiv e').toAddMonoidHom.comp (map F) :=
    hom_ext fun X => by simpa using of_congr (comm.app X)
  simpa only [AddMonoidHom.comp_apply, AddEquiv.coe_toAddMonoidHom] using
    DFunLike.congr_fun key x

/-- The equivariance of the induced homomorphism for the inverse shift. -/
theorem map_shiftEquiv_symm (comm : e.functor ⋙ F ≅ F ⋙ e'.functor) (x : TriangulatedK0 C) :
    map F ((mapEquiv e).symm x) = (mapEquiv e').symm (map F x) := by
  refine (AddEquiv.eq_symm_apply _).mpr ?_
  rw [← map_shiftEquiv comm, AddEquiv.apply_symm_apply]

/-- **Equivariance for the whole `ℤ`-action**: a graded triangulated functor carries `[M{n}]` to
`[(FM){n}]` for every integer `n`. -/
theorem map_shiftZPow (comm : e.functor ⋙ F ≅ F ⋙ e'.functor) (n : ℤ) (x : TriangulatedK0 C) :
    map F (shiftZPow e n x) = shiftZPow e' n (map F x) := by
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih => rw [shiftZPow_add_one_apply, map_shiftEquiv comm, ih, shiftZPow_add_one_apply]
  | pred k ih =>
    rw [shiftZPow_sub_one_apply, map_shiftEquiv_symm comm, ih, shiftZPow_sub_one_apply]

/-- **Forgetting the grading.**  A triangulated functor into an ungraded pretriangulated category
which commutes with the grading shift induces a homomorphism of triangulated Grothendieck groups
sending the class of `M{1}` and the class of `M` to the same element, that is, one invariant under
the grading shift.

As in the exact case, that invariance is the whole content: no factorization through a quotient of
`TauCeti.TriangulatedK0` is constructed, because the map from the graded group to the ungraded one
is not an isomorphism in general, and shift compatibility alone supplies none of the extra
hypotheses which make it one. -/
theorem map_shiftEquiv_of_commShift (comm : e.functor ⋙ F ≅ F) (x : TriangulatedK0 C) :
    map F (mapEquiv e x) = map F x := by
  have key : (map F).comp (mapEquiv e).toAddMonoidHom = map F :=
    hom_ext fun X => by simpa using of_congr (comm.app X)
  simpa only [AddMonoidHom.comp_apply, AddEquiv.coe_toAddMonoidHom] using
    DFunLike.congr_fun key x

/-- Forgetting the grading is invariant under the whole `ℤ`-action, not only under the generating
shift. -/
theorem map_shiftZPow_of_commShift (comm : e.functor ⋙ F ≅ F) (n : ℤ) (x : TriangulatedK0 C) :
    map F (shiftZPow e n x) = map F x := by
  have hsymm : ∀ y, map F ((mapEquiv e).symm y) = map F y := fun y => by
    have h := map_shiftEquiv_of_commShift (F := F) comm ((mapEquiv e).symm y)
    rw [AddEquiv.apply_symm_apply] at h
    exact h.symm
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih => rw [shiftZPow_add_one_apply, map_shiftEquiv_of_commShift comm, ih]
  | pred k ih => rw [shiftZPow_sub_one_apply, hsymm, ih]

end Functoriality

section Comparison

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasShift C ℤ]
  [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C] [EssentiallySmall.{w} C]
  (e : C ≌ C) [e.functor.CommShift ℤ] [e.functor.IsTriangulated]

/-- **The graded split Grothendieck group maps to the graded triangulated one.**  The shift of
split `K₀` is `TauCeti.SplitK0.mapEquiv` of the grading shift — a triangulated functor is in
particular additive, and every additive functor preserves split conflations — and the comparison
homomorphism intertwines it with the shift of triangulated `K₀`. -/
theorem fromSplit_shiftEquiv (x : SplitK0 C) :
    fromSplit C (SplitK0.mapEquiv e x) = mapEquiv e (fromSplit C x) := by
  have key : (fromSplit C).comp (SplitK0.mapEquiv e).toAddMonoidHom =
      (mapEquiv e).toAddMonoidHom.comp (fromSplit C) :=
    SplitK0.hom_ext fun X => by simp
  simpa only [AddMonoidHom.comp_apply, AddEquiv.coe_toAddMonoidHom] using
    DFunLike.congr_fun key x

/-- The comparison from graded split `K₀` to graded triangulated `K₀` intertwines the whole
`ℤ`-action. -/
theorem fromSplit_shiftZPow (n : ℤ) (x : SplitK0 C) :
    fromSplit C (SplitK0.shiftZPow e n x) = shiftZPow e n (fromSplit C x) := by
  have hsymm : ∀ y : SplitK0 C,
      fromSplit C ((SplitK0.mapEquiv e).symm y) = (mapEquiv e).symm (fromSplit C y) := fun y => by
    refine (AddEquiv.eq_symm_apply (mapEquiv e)).mpr ?_
    rw [← fromSplit_shiftEquiv, AddEquiv.apply_symm_apply]
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih =>
      rw [SplitK0.shiftZPow_add_one_apply, fromSplit_shiftEquiv, ih, shiftZPow_add_one_apply]
  | pred k ih =>
      rw [SplitK0.shiftZPow_sub_one_apply, hsymm, ih, shiftZPow_sub_one_apply]

end Comparison

end TriangulatedK0

end TauCeti
