/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.CategoryTheory.EssentiallySmall
public import Mathlib.GroupTheory.FreeAbelianGroup
public import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# The small presentation of a categorical Grothendieck group

Every categorical Grothendieck group -- split, exact, abelian, or triangulated -- is the quotient
of a free abelian group on the isomorphism classes of objects by a family of additive relations.
Only the relations differ. This file builds that common engine once, for an essentially small
category `C`, so that each Grothendieck group can be obtained by naming its relations.

The generators are `TauCeti.ObjectCode C`, a genuinely small type of codes for the isomorphism
classes of objects: it is `Shrink (Skeleton C)`. The smallness hypotheses are `Prop`-valued, so
`ObjectCode C` takes no data argument and depends only on `C` and the target universe. Its
underlying small model and representatives are nevertheless arbitrary choices. Consequently, the
object-facing API -- `of`, `induction_on`, `hom_ext`, `AdditiveInvariant`, `liftEquiv`, and `map` --
is stated purely in terms of objects of `C`, so callers need not manipulate representatives.

## Main definitions

* `TauCeti.ObjectCode C`: a small type of codes for the isomorphism classes of objects of an
  essentially small category `C`, with `TauCeti.objectCode` the code of an object.
* `TauCeti.freeOf X`: the generator of `FreeAbelianGroup (ObjectCode C)` attached to `X`, and
  `TauCeti.freeLift f`: the additive homomorphism out of that free abelian group determined by a
  function `f` on objects.
* `TauCeti.freeMap F`: the map on the free abelian groups induced by a functor `F`; functoriality
  of presentations requires it to carry each chosen source relation into the subgroup generated
  by the target relations.
* `TauCeti.PresentedK0 rels`: the quotient of `FreeAbelianGroup (ObjectCode C)` by the additive
  subgroup generated by `rels`, with class map `TauCeti.PresentedK0.of`.
* `TauCeti.PresentedK0.AdditiveInvariant rels G`: an isomorphism-invariant function on objects
  whose free extension annihilates every chosen relation.
* `TauCeti.PresentedK0.lift`, `TauCeti.PresentedK0.ofLE`, `TauCeti.PresentedK0.map` and
  `TauCeti.PresentedK0.mapEquiv`: the induced homomorphism of an additive invariant, the
  comparison map to a presentation with more relations, functoriality, and equivalence
  invariance.

## Main results

* `TauCeti.PresentedK0.induction_on` and `TauCeti.PresentedK0.hom_ext`: the induction principle and
  the extensionality principle, both phrased in terms of objects of `C`.
* `TauCeti.PresentedK0.liftEquiv`: the universal property. Additive invariants for `rels`
  correspond bijectively to additive homomorphisms out of `PresentedK0 rels`.

## Implementation notes

`TauCeti.freeLift f` is defined for an arbitrary `f : C → G`, by evaluating `f` at a chosen
representative of each code. Isomorphism invariance of `f` is not needed to define it; it is
needed exactly to compute it on the classes `TauCeti.freeOf X`, and so appears as a hypothesis
of `TauCeti.freeLift_freeOf` rather than as an unused argument of the definition. The bundled
form `TauCeti.PresentedK0.AdditiveInvariant` carries that hypothesis together with the relations.

Relations are packaged as a `Set (FreeAbelianGroup (ObjectCode C))` rather than as an
`AddSubgroup`, and the quotient is taken by `AddSubgroup.closure`. The universal property then has
a hypothesis about the chosen generating relations only, which is what a caller can check.

## References

* Charles A. Weibel, *The K-book: An Introduction to Algebraic K-theory*, Chapter II, Section 6,
  where `K₀` of a small abelian category is presented by generators and relations and the
  set-theoretic care taken here is discussed, and Section 6.1.2 for the universal property of an
  additive invariant.
* `Mathlib/GroupTheory/PresentedGroup.lean` and
  `Mathlib/Algebra/PresentedMonoid/Basic.lean`, whose set-of-relations parameter and
  `mk`/`of`/`closure_range_of`/lift-and-uniqueness/extensionality/map API layout are adapted here
  to additive categorical presentations. The object-facing class map, `AdditiveInvariant`, and
  the comparison map `ofLE` are specific to the categorical construction.
-/

public section

namespace TauCeti

open CategoryTheory

universe w w' w'' v v' v'' u u' u''

section ObjectCode

variable (C : Type u) [Category.{v} C] [EssentiallySmall.{w} C]

/-- `ObjectCode C` is a small type of codes for the isomorphism classes of objects of an
essentially small category `C`. -/
abbrev ObjectCode : Type w := Shrink.{w} (Skeleton C)

variable {C}

/-- The code of an object of `C`. Two objects have the same code exactly when they are
isomorphic; see `TauCeti.objectCode_eq_objectCode_iff`. -/
noncomputable def objectCode (X : C) : ObjectCode C :=
  equivShrink _ (toSkeleton X)

private noncomputable def objectCodeOut (c : ObjectCode C) : C :=
  (fromSkeleton C).obj ((equivShrink _).symm c)

@[simp] private lemma objectCode_objectCodeOut (c : ObjectCode C) :
    objectCode (objectCodeOut c) = c := by
  rw [objectCode, objectCodeOut, toSkeleton_fromSkeleton_obj, Equiv.apply_symm_apply]

lemma objectCode_eq_objectCode_iff {X Y : C} :
    objectCode X = objectCode Y ↔ Nonempty (X ≅ Y) := by
  rw [objectCode, objectCode, Equiv.apply_eq_iff_eq, toSkeleton_eq_toSkeleton_iff]

lemma objectCode_congr {X Y : C} (e : X ≅ Y) : objectCode X = objectCode Y :=
  objectCode_eq_objectCode_iff.2 ⟨e⟩

private noncomputable def isoOfObjectCodeEq {X Y : C} (h : objectCode X = objectCode Y) : X ≅ Y :=
  (objectCode_eq_objectCode_iff.1 h).some

private noncomputable def objectCodeOutIso (X : C) : objectCodeOut (objectCode X) ≅ X :=
  isoOfObjectCodeEq (objectCode_objectCodeOut _)

lemma objectCode_surjective : Function.Surjective (objectCode : C → ObjectCode C) :=
  fun c => ⟨objectCodeOut c, objectCode_objectCodeOut c⟩

end ObjectCode

section Free

variable {C : Type u} [Category.{v} C] [EssentiallySmall.{w} C]

/-- The generator of the free abelian group on object codes attached to an object `X`. -/
noncomputable def freeOf (X : C) : FreeAbelianGroup (ObjectCode C) :=
  FreeAbelianGroup.of (objectCode X)

/-- The object generator is the free generator on its object code. -/
lemma freeOf_def (X : C) : freeOf X = FreeAbelianGroup.of (objectCode X) :=
  (rfl)

lemma freeOf_congr {X Y : C} (e : X ≅ Y) : freeOf X = freeOf Y := by
  rw [freeOf, freeOf, objectCode_congr e]

lemma freeOf_eq_freeOf_iff {X Y : C} : freeOf X = freeOf Y ↔ Nonempty (X ≅ Y) := by
  rw [freeOf, freeOf, FreeAbelianGroup.of_injective.eq_iff, objectCode_eq_objectCode_iff]

@[simp] private lemma freeOf_objectCodeOut (c : ObjectCode C) :
    freeOf (objectCodeOut c) = FreeAbelianGroup.of c := by
  rw [freeOf, objectCode_objectCodeOut]

variable {G : Type*} [AddCommGroup G]

/-- The additive homomorphism out of the free abelian group on object codes determined by a
function on objects, obtained by evaluating at a chosen representative of each code. It computes
as expected on the classes `TauCeti.freeOf X` as soon as the function is invariant under
isomorphism; see `TauCeti.freeLift_freeOf`. -/
noncomputable def freeLift (f : C → G) : FreeAbelianGroup (ObjectCode C) →+ G :=
  FreeAbelianGroup.lift fun c => f (objectCodeOut c)

@[simp] private lemma freeLift_apply_of (f : C → G) (c : ObjectCode C) :
    freeLift f (FreeAbelianGroup.of c) = f (objectCodeOut c) :=
  FreeAbelianGroup.lift_apply_of _ _

lemma freeLift_freeOf {f : C → G} (hf : ∀ ⦃X Y : C⦄, (X ≅ Y) → f X = f Y) (X : C) :
    freeLift f (freeOf X) = f X := by
  rw [freeOf, freeLift_apply_of]
  exact hf (objectCodeOutIso X)

lemma freeLift_unique {f : C → G} (g : FreeAbelianGroup (ObjectCode C) →+ G)
    (hg : ∀ X : C, g (freeOf X) = f X) :
    g = freeLift f := by
  ext c
  rw [← freeOf_objectCodeOut c, hg, freeOf_objectCodeOut, freeLift_apply_of]

lemma freeLift_comp {H : Type*} [AddCommGroup H] (φ : G →+ H) (f : C → G) :
    freeLift (fun X => φ (f X)) = φ.comp (freeLift f) := by
  ext c
  simp

end Free

section Presentation

variable {C : Type u} [Category.{v} C] [EssentiallySmall.{w} C]

/-- The Grothendieck group of `C` presented by the family of relations `rels`: the free abelian
group on the isomorphism classes of objects of `C`, modulo the additive subgroup generated by
`rels`. -/
def PresentedK0 (rels : Set (FreeAbelianGroup (ObjectCode C))) : Type w :=
  FreeAbelianGroup (ObjectCode C) ⧸ AddSubgroup.closure rels

instance (rels : Set (FreeAbelianGroup (ObjectCode C))) : AddCommGroup (PresentedK0 rels) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup (ObjectCode C) ⧸ AddSubgroup.closure rels))

namespace PresentedK0

/-- An additive invariant for the presentation `rels`: a function on objects of `C`, invariant
under isomorphism, whose free extension annihilates every chosen relation. These are exactly the
data that factor through `TauCeti.PresentedK0 rels`; see `TauCeti.PresentedK0.liftEquiv`. -/
@[ext]
structure AdditiveInvariant (rels : Set (FreeAbelianGroup (ObjectCode C))) (G : Type*)
    [AddCommGroup G] where
  /-- The value of the invariant on an object. -/
  obj : C → G
  /-- Isomorphic objects receive equal values. -/
  map_iso : ∀ ⦃X Y : C⦄, (X ≅ Y) → obj X = obj Y
  /-- The free extension of the invariant annihilates every chosen relation. -/
  map_rel : ∀ r ∈ rels, freeLift obj r = 0

variable {rels : Set (FreeAbelianGroup (ObjectCode C))}

/-- The quotient map presenting `TauCeti.PresentedK0 rels`. -/
def mk : FreeAbelianGroup (ObjectCode C) →+ PresentedK0 rels :=
  QuotientAddGroup.mk' (AddSubgroup.closure rels)

lemma mk_surjective : Function.Surjective (mk : _ →+ PresentedK0 rels) :=
  QuotientAddGroup.mk'_surjective _

lemma mk_eq_zero_iff (r : FreeAbelianGroup (ObjectCode C)) :
    (mk r : PresentedK0 rels) = 0 ↔ r ∈ AddSubgroup.closure rels :=
  QuotientAddGroup.eq_zero_iff r

lemma mk_eq_zero_of_mem {r : FreeAbelianGroup (ObjectCode C)} (hr : r ∈ rels) :
    (mk r : PresentedK0 rels) = 0 :=
  (mk_eq_zero_iff r).2 (AddSubgroup.subset_closure hr)

/-- The class of an object of `C` in the presented Grothendieck group. -/
noncomputable def of (X : C) : PresentedK0 rels :=
  mk (freeOf X)

@[simp]
lemma mk_freeOf (X : C) : (mk (freeOf X) : PresentedK0 rels) = of X :=
  (rfl)

@[simp] private lemma mk_freeAbelianGroupOf (c : ObjectCode C) :
    (mk (FreeAbelianGroup.of c) : PresentedK0 rels) = of (objectCodeOut c) := by
  rw [← freeOf_objectCodeOut c, mk_freeOf]

lemma of_congr {X Y : C} (e : X ≅ Y) : (of X : PresentedK0 rels) = of Y := by
  rw [of, of, freeOf_congr e]

private lemma freeLift_of_eq_mk : freeLift (fun X : C => (of X : PresentedK0 rels)) = mk := by
  exact (freeLift_unique mk mk_freeOf).symm

/-- The image of `PresentedK0.of` generates the whole additive group. -/
theorem closure_range_of :
    AddSubgroup.closure (Set.range (of : C → PresentedK0 rels)) = ⊤ := by
  refine eq_top_iff.2 fun x hx => ?_
  clear hx
  obtain ⟨y, rfl⟩ := mk_surjective x
  induction y using FreeAbelianGroup.induction_on with
  | zero => rw [map_zero]; exact zero_mem _
  | of c => exact AddSubgroup.subset_closure ⟨objectCodeOut c, (mk_freeAbelianGroupOf c).symm⟩
  | neg c hc => rw [map_neg]; exact neg_mem hc
  | add a b ha hb => rw [map_add]; exact add_mem ha hb

/-- Induction on the classes of objects of `C`: no skeleton representative is ever mentioned. -/
@[elab_as_elim]
theorem induction_on {motive : PresentedK0 rels → Prop} (x : PresentedK0 rels)
    (zero : motive 0) (of : ∀ X : C, motive (PresentedK0.of X))
    (add : ∀ a b, motive a → motive b → motive (a + b))
    (neg : ∀ a, motive a → motive (-a)) : motive x := by
  let S : AddSubgroup (PresentedK0 rels) :=
    { carrier := {a | motive a}
      zero_mem' := zero
      add_mem' := fun ha hb => add _ _ ha hb
      neg_mem' := fun ha => neg _ ha }
  have hS : AddSubgroup.closure (Set.range (PresentedK0.of : C → PresentedK0 rels)) ≤ S := by
    rw [AddSubgroup.closure_le]
    rintro _ ⟨X, rfl⟩
    exact of X
  refine hS ?_
  rw [closure_range_of]
  trivial

section HomExt

variable {G : Type*} [AddMonoid G]

/-- Two homomorphisms out of a presented Grothendieck group agreeing on the classes of objects of
`C` are equal. -/
@[ext]
theorem hom_ext {f g : PresentedK0 rels →+ G} (h : ∀ X : C, f (of X) = g (of X)) : f = g :=
  AddMonoidHom.eq_of_eqOn_dense closure_range_of (by rintro _ ⟨X, rfl⟩; exact h X)

end HomExt

/-- A homomorphism into a presented Grothendieck group whose range contains the class of every
object of `C` is surjective, since those classes generate. -/
theorem surjective_of_forall_of_mem_range {G : Type*} [AddGroup G] {f : G →+ PresentedK0 rels}
    (h : ∀ X : C, of X ∈ f.range) : Function.Surjective f := by
  rw [← AddMonoidHom.range_eq_top, eq_top_iff, ← closure_range_of, AddSubgroup.closure_le]
  rintro _ ⟨X, rfl⟩
  exact h X

variable {G : Type*} [AddCommGroup G]

/-- The additive homomorphism induced by an additive invariant. -/
noncomputable def lift (a : AdditiveInvariant rels G) : PresentedK0 rels →+ G :=
  QuotientAddGroup.lift _ (freeLift a.obj) (by
    rw [AddSubgroup.closure_le]
    intro r hr
    simpa [AddMonoidHom.mem_ker] using a.map_rel r hr)

@[simp]
lemma lift_mk (a : AdditiveInvariant rels G) (r : FreeAbelianGroup (ObjectCode C)) :
    lift a (mk r) = freeLift a.obj r :=
  QuotientAddGroup.lift_mk' _ _ _

@[simp]
lemma lift_of (a : AdditiveInvariant rels G) (X : C) : lift a (of X) = a.obj X :=
  freeLift_freeOf a.map_iso X

theorem lift_unique (a : AdditiveInvariant rels G) (f : PresentedK0 rels →+ G)
    (hf : ∀ X : C, f (of X) = a.obj X) : f = lift a :=
  hom_ext fun X => by rw [hf, lift_of]

/-- The universal property of a presented Grothendieck group: additive invariants for `rels` with
values in `G` correspond bijectively to additive homomorphisms `PresentedK0 rels →+ G`. -/
noncomputable def liftEquiv : AdditiveInvariant rels G ≃ (PresentedK0 rels →+ G) where
  toFun := lift
  invFun f :=
    { obj := fun X => f (of X)
      map_iso := fun _ _ e => by rw [of_congr e]
      map_rel := fun r hr => by
        rw [freeLift_comp f (fun X : C => (of X : PresentedK0 rels)), freeLift_of_eq_mk,
          AddMonoidHom.comp_apply, mk_eq_zero_of_mem hr, map_zero] }
  left_inv a := by ext X; exact lift_of a X
  right_inv f := (lift_unique _ f fun _ => rfl).symm

@[simp]
lemma liftEquiv_apply (a : AdditiveInvariant rels G) : liftEquiv a = lift a := (rfl)

@[simp]
lemma liftEquiv_symm_apply_obj (f : PresentedK0 rels →+ G) (X : C) :
    ((liftEquiv (rels := rels) (G := G)).symm f).obj X = f (of X) := (rfl)

end PresentedK0

end Presentation

section Functoriality

variable {C : Type u} [Category.{v} C] [EssentiallySmall.{w} C]
  {D : Type u'} [Category.{v'} D] [EssentiallySmall.{w'} D]

/-- The additive homomorphism on free abelian groups on object codes induced by a functor. -/
noncomputable def freeMap (F : C ⥤ D) :
    FreeAbelianGroup (ObjectCode C) →+ FreeAbelianGroup (ObjectCode D) :=
  freeLift fun X => freeOf (F.obj X)

@[simp]
lemma freeMap_freeOf (F : C ⥤ D) (X : C) : freeMap F (freeOf X) = freeOf (F.obj X) :=
  freeLift_freeOf (fun _ _ e => freeOf_congr (F.mapIso e)) X

@[simp]
lemma freeMap_id : freeMap (𝟭 C) = AddMonoidHom.id _ := by
  exact (freeLift_unique _ fun X => by simp).symm

lemma freeMap_comp {E : Type u''} [Category.{v''} E] [EssentiallySmall.{w''} E]
    (F : C ⥤ D) (G : D ⥤ E) : freeMap (F ⋙ G) = (freeMap G).comp (freeMap F) := by
  exact (freeLift_unique _ fun X => by simp).symm

lemma freeMap_congr {F G : C ⥤ D} (h : ∀ X : C, Nonempty (F.obj X ≅ G.obj X)) :
    freeMap F = freeMap G := by
  exact freeLift_unique _ fun X => by simpa using freeOf_congr (h X).some

variable {relsC : Set (FreeAbelianGroup (ObjectCode C))}
  {relsD : Set (FreeAbelianGroup (ObjectCode D))}

/-- The free map of the identity functor preserves every generated relation subgroup. -/
lemma freeMap_id_mapsTo :
    ∀ r ∈ relsC, freeMap (𝟭 C) r ∈ AddSubgroup.closure relsC := by
  intro r hr
  rw [freeMap_id, AddMonoidHom.id_apply]
  exact AddSubgroup.subset_closure hr

/-- A composite free map preserves generated relation subgroups when each of its factors does. -/
lemma freeMap_comp_mapsTo {E : Type u''} [Category.{v''} E] [EssentiallySmall.{w''} E]
    {relsE : Set (FreeAbelianGroup (ObjectCode E))} (F : C ⥤ D) (G : D ⥤ E)
    (hF : ∀ r ∈ relsC, freeMap F r ∈ AddSubgroup.closure relsD)
    (hG : ∀ r ∈ relsD, freeMap G r ∈ AddSubgroup.closure relsE) :
    ∀ r ∈ relsC, freeMap (F ⋙ G) r ∈ AddSubgroup.closure relsE := by
  intro r hr
  rw [freeMap_comp, AddMonoidHom.comp_apply]
  exact (AddSubgroup.closure_le ((AddSubgroup.closure relsE).comap (freeMap G))).2 hG (hF r hr)

namespace PresentedK0

/-- Functoriality: a functor whose induced map on free abelian groups sends every chosen relation
of `relsC` into the subgroup generated by `relsD` induces a homomorphism of presented Grothendieck
groups. -/
noncomputable def map (F : C ⥤ D)
    (h : ∀ r ∈ relsC, freeMap F r ∈ AddSubgroup.closure relsD) :
    PresentedK0 relsC →+ PresentedK0 relsD :=
  QuotientAddGroup.map (AddSubgroup.closure relsC) (AddSubgroup.closure relsD) (freeMap F)
    ((AddSubgroup.closure_le ((AddSubgroup.closure relsD).comap (freeMap F))).2 h)

@[simp]
lemma map_mk (F : C ⥤ D) (h : ∀ r ∈ relsC, freeMap F r ∈ AddSubgroup.closure relsD)
    (r : FreeAbelianGroup (ObjectCode C)) : map F h (mk r) = mk (freeMap F r) :=
  QuotientAddGroup.map_mk _ _ _ _ _

@[simp]
lemma map_of (F : C ⥤ D) (h : ∀ r ∈ relsC, freeMap F r ∈ AddSubgroup.closure relsD) (X : C) :
    map F h (of X) = of (F.obj X) := by
  rw [of, of, map_mk, freeMap_freeOf]

/-- The comparison map to a presentation with more relations: enlarging the family of relations
factors the class map. Taking `rels` to be the split relations and `rels'` the conflations of an
exact structure, this is the canonical comparison from split to exact `K₀`. -/
noncomputable def ofLE {rels rels' : Set (FreeAbelianGroup (ObjectCode C))}
    (h : rels ⊆ AddSubgroup.closure rels') : PresentedK0 rels →+ PresentedK0 rels' :=
  map (𝟭 C) fun r hr => by
    rw [freeMap_id, AddMonoidHom.id_apply]
    exact h hr

@[simp]
lemma ofLE_of {rels rels' : Set (FreeAbelianGroup (ObjectCode C))}
    (h : rels ⊆ AddSubgroup.closure rels') (X : C) : ofLE h (of X) = (of X : PresentedK0 rels') :=
  map_of _ _ X

@[simp]
lemma ofLE_mk {rels rels' : Set (FreeAbelianGroup (ObjectCode C))}
    (h : rels ⊆ AddSubgroup.closure rels') (r : FreeAbelianGroup (ObjectCode C)) :
    ofLE h (mk r) = (mk r : PresentedK0 rels') := by
  rw [ofLE, map_mk, freeMap_id, AddMonoidHom.id_apply]

@[simp]
lemma map_id
    (hId : ∀ r ∈ relsC, freeMap (𝟭 C) r ∈ AddSubgroup.closure relsC :=
      freeMap_id_mapsTo) :
    map (relsC := relsC) (relsD := relsC) (𝟭 C) hId =
      AddMonoidHom.id (PresentedK0 relsC) :=
  hom_ext fun X => by simp

lemma map_comp {E : Type u''} [Category.{v''} E] [EssentiallySmall.{w''} E]
    {relsE : Set (FreeAbelianGroup (ObjectCode E))} (F : C ⥤ D) (G : D ⥤ E)
    (hF : ∀ r ∈ relsC, freeMap F r ∈ AddSubgroup.closure relsD)
    (hG : ∀ r ∈ relsD, freeMap G r ∈ AddSubgroup.closure relsE)
    (hFG : ∀ r ∈ relsC, freeMap (F ⋙ G) r ∈ AddSubgroup.closure relsE :=
      freeMap_comp_mapsTo F G hF hG) :
    map (F ⋙ G) hFG = (map G hG).comp (map F hF) :=
  hom_ext fun X => by simp

/-- Enlarging a relation family to itself induces the identity map. -/
@[simp]
lemma ofLE_refl :
    ofLE (AddSubgroup.subset_closure : relsC ⊆ AddSubgroup.closure relsC) =
      AddMonoidHom.id (PresentedK0 relsC) :=
  hom_ext fun X => by rw [ofLE_of, AddMonoidHom.id_apply]

/-- Comparison maps for successive enlargements of relation families compose. -/
lemma ofLE_comp {rels rels' rels'' : Set (FreeAbelianGroup (ObjectCode C))}
    (h : rels ⊆ AddSubgroup.closure rels') (h' : rels' ⊆ AddSubgroup.closure rels'') :
    (ofLE h').comp (ofLE h) =
      ofLE (Set.Subset.trans h ((AddSubgroup.closure_le (AddSubgroup.closure rels'')).2 h')) :=
  hom_ext fun X => by rw [AddMonoidHom.comp_apply, ofLE_of, ofLE_of, ofLE_of]

lemma map_congr {F G : C ⥤ D} (h : ∀ X : C, Nonempty (F.obj X ≅ G.obj X))
    (hF : ∀ r ∈ relsC, freeMap F r ∈ AddSubgroup.closure relsD)
    (hG : ∀ r ∈ relsC, freeMap G r ∈ AddSubgroup.closure relsD) : map F hF = map G hG :=
  hom_ext fun X => by
    rw [map_of, map_of]
    exact of_congr (h X).some

/-- Equivalence invariance: an equivalence carrying the chosen relations into one another in both
directions induces an isomorphism of presented Grothendieck groups. -/
noncomputable def mapEquiv (e : C ≌ D)
    (h : ∀ r ∈ relsC, freeMap e.functor r ∈ AddSubgroup.closure relsD)
    (h' : ∀ r ∈ relsD, freeMap e.inverse r ∈ AddSubgroup.closure relsC) :
    PresentedK0 relsC ≃+ PresentedK0 relsD where
  toFun := map e.functor h
  invFun := map e.inverse h'
  left_inv x := by
    have hinv : (map e.inverse h').comp (map e.functor h) = AddMonoidHom.id _ :=
      (map_comp e.functor e.inverse h h').symm.trans <|
        (map_congr (fun X => ⟨e.unitIso.symm.app X⟩)
          (freeMap_comp_mapsTo e.functor e.inverse h h') freeMap_id_mapsTo).trans map_id
    exact DFunLike.congr_fun hinv x
  right_inv x := by
    have hinv : (map e.functor h).comp (map e.inverse h') = AddMonoidHom.id _ :=
      (map_comp e.inverse e.functor h' h).symm.trans <|
        (map_congr (fun Y => ⟨e.counitIso.app Y⟩)
          (freeMap_comp_mapsTo e.inverse e.functor h' h) freeMap_id_mapsTo).trans map_id
    exact DFunLike.congr_fun hinv x
  map_add' := map_add _

@[simp]
lemma mapEquiv_of (e : C ≌ D)
    (h : ∀ r ∈ relsC, freeMap e.functor r ∈ AddSubgroup.closure relsD)
    (h' : ∀ r ∈ relsD, freeMap e.inverse r ∈ AddSubgroup.closure relsC) (X : C) :
    mapEquiv e h h' (of X) = of (e.functor.obj X) :=
  map_of e.functor h X

@[simp]
lemma mapEquiv_symm_of (e : C ≌ D)
    (h : ∀ r ∈ relsC, freeMap e.functor r ∈ AddSubgroup.closure relsD)
    (h' : ∀ r ∈ relsD, freeMap e.inverse r ∈ AddSubgroup.closure relsC) (Y : D) :
    (mapEquiv e h h').symm (of Y) = of (e.inverse.obj Y) :=
  map_of e.inverse h' Y

/-- The additive homomorphism underlying equivalence invariance is the functorial map. -/
@[simp]
lemma mapEquiv_toAddMonoidHom (e : C ≌ D)
    (h : ∀ r ∈ relsC, freeMap e.functor r ∈ AddSubgroup.closure relsD)
    (h' : ∀ r ∈ relsD, freeMap e.inverse r ∈ AddSubgroup.closure relsC) :
    ((mapEquiv e h h' : PresentedK0 relsC ≃+ PresentedK0 relsD) :
        PresentedK0 relsC →+ PresentedK0 relsD) = map e.functor h :=
  hom_ext fun X => by simp

/-- Equivalence invariance for the identity equivalence is the identity. -/
@[simp]
lemma mapEquiv_refl
    (h : ∀ r ∈ relsC,
      freeMap (CategoryTheory.Equivalence.refl : C ≌ C).functor r ∈
        AddSubgroup.closure relsC := by
      simpa only [CategoryTheory.Equivalence.refl_functor] using
        (freeMap_id_mapsTo (relsC := relsC)))
    (h' : ∀ r ∈ relsC,
      freeMap (CategoryTheory.Equivalence.refl : C ≌ C).inverse r ∈
        AddSubgroup.closure relsC := by
      simpa only [CategoryTheory.Equivalence.refl_inverse] using
        (freeMap_id_mapsTo (relsC := relsC))) :
    mapEquiv (relsC := relsC) (relsD := relsC) (CategoryTheory.Equivalence.refl : C ≌ C)
      h h' =
        AddEquiv.refl (PresentedK0 relsC) :=
  AddEquiv.toAddMonoidHom_injective <| hom_ext fun X => by simp

/-- Equivalence invariance respects composition of equivalences. -/
lemma mapEquiv_trans {E : Type u''} [Category.{v''} E] [EssentiallySmall.{w''} E]
    {relsE : Set (FreeAbelianGroup (ObjectCode E))} (e : C ≌ D) (f : D ≌ E)
    (h : ∀ r ∈ relsC, freeMap e.functor r ∈ AddSubgroup.closure relsD)
    (h' : ∀ r ∈ relsD, freeMap e.inverse r ∈ AddSubgroup.closure relsC)
    (k : ∀ r ∈ relsD, freeMap f.functor r ∈ AddSubgroup.closure relsE)
    (k' : ∀ r ∈ relsE, freeMap f.inverse r ∈ AddSubgroup.closure relsD)
    (hk : ∀ r ∈ relsC, freeMap (e.trans f).functor r ∈ AddSubgroup.closure relsE :=
      freeMap_comp_mapsTo e.functor f.functor h k)
    (hk' : ∀ r ∈ relsE, freeMap (e.trans f).inverse r ∈ AddSubgroup.closure relsC :=
      freeMap_comp_mapsTo f.inverse e.inverse k' h') :
    (mapEquiv e h h').trans (mapEquiv f k k') =
      mapEquiv (e.trans f) hk hk' := by
  apply AddEquiv.ext
  exact fun x => (DFunLike.congr_fun (map_comp e.functor f.functor h k hk) x).symm

end PresentedK0

end Functoriality

end TauCeti
