/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Casimir
public import TauCeti.Algebra.Lie.HighestWeight.Verma
-- Non-public: the eigenvector criterion appears only inside proofs.
import TauCeti.Algebra.Lie.Weights.Eigenvector

/-!
# The central character of a highest weight module

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, let `H` be a splitting Cartan subalgebra and `b` a base of its root system.
The centre `Z(U(L)) = Subalgebra.center K (UniversalEnvelopingAlgebra K L)` of the enveloping
algebra acts on a highest weight module of weight `lam` **by scalars**, and this file builds the
resulting `K`-algebra homomorphism

`chi_lam : Z(U(L)) →ₐ[K] K`,

the **central character** of `lam`.

## Why the scalar exists

A central `z` commutes with the whole Lie action
(`TauCeti.UniversalEnvelopingAlgebra.representation_lie_of_mem_center`), so it carries a highest
weight vector `v` of weight `lam` into the `lam`-weight space: the Cartan subalgebra still acts on
`z · v` through `lam`. On a *highest weight module* — one generated by `v` — that weight space is
the line `K ∙ v`
(`TauCeti.genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top`), so
`z · v = c • v` for a unique `c`, and centrality propagates the identity from the generator to
the whole module
(`TauCeti.UniversalEnvelopingAlgebra.representation_eq_smul_of_mem_center_of_lieSpan_eq_top`).
Nothing here needs `v` to generate an *irreducible* module, and nothing needs finite
dimensionality: Schur's lemma is not the mechanism, the one-dimensionality of the top weight space
is.

## The character of a weight, not of a module

The construction above takes a highest weight module as input. It does not depend on it, so the
character is attached to the weight alone: the Verma module `M(lam)` maps onto any module carrying
a highest weight vector of weight `lam`, by its universal property
(`TauCeti.existsUnique_lieModuleHom_apply_vermaGenerator`), and a homomorphism of Lie modules
intertwines the two enveloping-algebra actions
(`TauCeti.UniversalEnvelopingAlgebra.map_representation`), so the scalar is the one read off
`M(lam)`. That is
`TauCeti.IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul`, and it makes
`TauCeti.vermaCentralCharacter` the central character *of the weight* `lam`. The vector is not
assumed to generate its module there: any highest weight vector of weight `lam`, anywhere, is an
eigenvector of the centre with eigenvalue `chi_lam`. In particular the irreducible quotient
`L(lam)` has the central character of `lam`, being a highest weight module of that weight
(`TauCeti.isHighestWeightVector_irreducibleQuotientGenerator`).

## Main definitions

* `TauCeti.vermaCentralCharacter`: the central character `chi_lam` of the weight `lam`, a
  `K`-algebra homomorphism `Z(U(L)) →ₐ[K] K`.

## Main results

* `TauCeti.IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul`: **the defining
  property**, on any highest weight vector of weight `lam` in any module, and
  `TauCeti.IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul_of_lieSpan_eq_top`,
  on the whole module when that vector generates it.
* `TauCeti.IsHighestWeightVector.vermaCentralCharacter_eq_of_representation_eq_smul`: the central
  character is the *only* scalar with that property, which is how its values are computed.
* `TauCeti.vermaCentralCharacter_casimirElement`: **the central character sends the Casimir
  element to the Casimir scalar** `⟨lam + rho, lam + rho⟩ - ⟨rho, rho⟩` of Layer 5.

## References

This is the "central characters" half of the first item of Layer 7 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose target signature
`centralCharacter` is pinned in the accompanying `Suggested.lean` and whose text fixes the route
used here: the character is defined through the action of the centre on the one-dimensional top
weight line of the Verma module, and is then shown to be the character of every highest weight
module of that weight, the Casimir eigenvalue of Layer 5 being its value at the Casimir element.
The name `TauCeti.centralCharacter` is already taken by the central character of a simple module
over an arbitrary algebra (`TauCeti/RingTheory/Semisimple/CentralCharacter.lean`), obtained from
Schur's lemma. That construction is not available here: it assumes `[IsAlgClosed K]`,
`[IsSimpleModule A M]` and `[FiniteDimensional K M]`, none of which is assumed in this file, and
`M(lam)` is not known to be simple — simplicity of `M(lam)` is equivalent to antidominance of
`lam` (Humphreys, BGG Category `O`, §4.8).

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §23.2.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, §1.7.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

local notation "U" => _root_.UniversalEnvelopingAlgebra K L

variable {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-! ### A central element acts on a highest weight vector by a scalar -/

/-- A central element of `U(L)` acts on the generator of a highest weight module by a scalar:
commuting with the Lie action, it leaves the generator in the top weight space, which is the line
the generator spans. This existence statement is the input of the construction below; its public
form, in which the scalar is named, is
`TauCeti.IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul`. -/
private theorem exists_representation_eq_smul_of_mem_center
    {u : U} (hu : u ∈ Subalgebra.center K U)
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    ∃ c : K, UniversalEnvelopingAlgebra.representation K L M u v = c • v := by
  -- the image is again an eigenvector of `H` for `lam`, hence lies in the `lam`-weight space
  have hmem : UniversalEnvelopingAlgebra.representation K L M u v ∈
      (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M) :=
    mem_genWeightSpace_of_forall_lie_eq_smul fun x ↦ by
      rw [← UniversalEnvelopingAlgebra.representation_lie_of_mem_center K L M hu,
        hv.lie_eq_smul x, map_smul]
  rw [genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen,
    Submodule.mem_span_singleton] at hmem
  obtain ⟨c, hc⟩ := hmem
  exact ⟨c, hc.symm⟩

private noncomputable def centralScalarAux (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) (u : Subalgebra.center K U) : K :=
  (exists_representation_eq_smul_of_mem_center u.2 hv hgen).choose

private theorem representation_eq_centralScalarAux_smul (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) (u : Subalgebra.center K U) :
    UniversalEnvelopingAlgebra.representation K L M (u : U) v = centralScalarAux hv hgen u • v :=
  (exists_representation_eq_smul_of_mem_center u.2 hv hgen).choose_spec

private theorem centralScalarAux_eq (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {u : Subalgebra.center K U} {c : K}
    (h : UniversalEnvelopingAlgebra.representation K L M (u : U) v = c • v) :
    centralScalarAux hv hgen u = c :=
  smul_left_injective K hv.ne_zero
    ((representation_eq_centralScalarAux_smul hv hgen u).symm.trans h)

/-! ### The central character -/

/-- The central character of a highest weight module: a central element of `U(L)` acts on a module
generated by a highest weight vector of weight `lam` by a scalar, and taking that scalar is a
homomorphism of `K`-algebras `Z(U(L)) →ₐ[K] K`.

It is used only at the Verma module `M(lam)`, where it is `TauCeti.vermaCentralCharacter`: by
`TauCeti.IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul` the character depends
only on `lam` and not on the module, so `chi_lam` is the single public name for the object. -/
private noncomputable def centralCharacterAux (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) : Subalgebra.center K U →ₐ[K] K where
  toFun := centralScalarAux hv hgen
  map_one' := centralScalarAux_eq hv hgen (by simp)
  map_mul' u w := centralScalarAux_eq hv hgen (by
    rw [MulMemClass.coe_mul, map_mul, Module.End.mul_apply,
      representation_eq_centralScalarAux_smul hv hgen w, map_smul,
      representation_eq_centralScalarAux_smul hv hgen u, smul_smul, mul_comm])
  map_zero' := centralScalarAux_eq hv hgen (by simp)
  map_add' u w := centralScalarAux_eq hv hgen (by
    rw [AddMemClass.coe_add, map_add, LinearMap.add_apply,
      representation_eq_centralScalarAux_smul hv hgen u,
      representation_eq_centralScalarAux_smul hv hgen w, add_smul])
  commutes' r := centralScalarAux_eq hv hgen (by simp)

/-! ### The central character of a weight -/

variable (b lam) in
/-- **The central character `chi_lam` of a weight**, read off the Verma module `M(lam)`: the
scalar by which a central element of `U(L)` acts on the canonical generator. By
`TauCeti.IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul` it is the scalar by
which the centre acts on *any* highest weight vector of weight `lam`. -/
noncomputable def vermaCentralCharacter : Subalgebra.center K U →ₐ[K] K :=
  centralCharacterAux (isHighestWeightVector_vermaGenerator b lam)
    (lieSpan_vermaGenerator_eq_top b lam)

variable (b lam) in
private theorem representation_vermaGenerator_eq_vermaCentralCharacter_smul
    (u : Subalgebra.center K U) :
    UniversalEnvelopingAlgebra.representation K L (VermaModule b lam) (u : U)
        (vermaGenerator b lam) =
      vermaCentralCharacter b lam u • vermaGenerator b lam :=
  representation_eq_centralScalarAux_smul (isHighestWeightVector_vermaGenerator b lam)
    (lieSpan_vermaGenerator_eq_top b lam) u

/-- **The defining property of the central character**: a central element of `U(L)` acts on any
highest weight vector of weight `lam`, in any module, by `chi_lam`. The vector is not assumed to
generate its module: the universal property of `M(lam)` maps the canonical generator to it, and a
homomorphism of Lie modules intertwines the two actions of `U(L)`. -/
theorem IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul
    (hv : IsHighestWeightVector b lam v) (u : Subalgebra.center K U) :
    UniversalEnvelopingAlgebra.representation K L M (u : U) v =
      vermaCentralCharacter b lam u • v := by
  obtain ⟨φ, hφ, -⟩ := existsUnique_lieModuleHom_apply_vermaGenerator b lam v hv.lie_eq_smul
    fun _ hx => hv.lie_eq_zero_of_mem_positiveNilradical hx
  calc UniversalEnvelopingAlgebra.representation K L M (u : U) v
      = φ (UniversalEnvelopingAlgebra.representation K L (VermaModule b lam) (u : U)
            (vermaGenerator b lam)) := by
        rw [UniversalEnvelopingAlgebra.map_representation, hφ]
    _ = vermaCentralCharacter b lam u • v := by
        rw [representation_vermaGenerator_eq_vermaCentralCharacter_smul b lam, map_smul, hφ]

/-- **The central character is the only scalar with the defining property**, a highest weight
vector being nonzero. This is how the values of the character are computed. -/
theorem IsHighestWeightVector.vermaCentralCharacter_eq_of_representation_eq_smul
    (hv : IsHighestWeightVector b lam v) {u : Subalgebra.center K U} {c : K}
    (h : UniversalEnvelopingAlgebra.representation K L M (u : U) v = c • v) :
    vermaCentralCharacter b lam u = c :=
  smul_left_injective K hv.ne_zero
    ((hv.representation_eq_vermaCentralCharacter_smul u).symm.trans h)

/-- **A central element acts on a whole highest weight module by the central character of its
weight.** Centrality makes the locus where it acts by that scalar a Lie submodule, and it contains
the generator. -/
theorem IsHighestWeightVector.representation_eq_vermaCentralCharacter_smul_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (u : Subalgebra.center K U) (m : M) :
    UniversalEnvelopingAlgebra.representation K L M (u : U) m =
      vermaCentralCharacter b lam u • m :=
  UniversalEnvelopingAlgebra.representation_eq_smul_of_mem_center_of_lieSpan_eq_top K L M u.2
    (by simpa only [Set.mem_singleton_iff, forall_eq] using
      hv.representation_eq_vermaCentralCharacter_smul u) hgen m

/-! ### The Casimir element -/

variable (b lam) in
/-- **The central character sends the Casimir element to the Casimir scalar**
`⟨lam + rho, lam + rho⟩ - ⟨rho, rho⟩`, so the eigenvalue computed in
`TauCeti/Algebra/Lie/HighestWeight/Casimir.lean` is a value of the central character. -/
@[simp]
theorem vermaCentralCharacter_casimirElement :
    vermaCentralCharacter b lam ⟨casimirElement K L, casimirElement_mem_center K L⟩ =
      casimirScalar b lam :=
  have hv := isHighestWeightVector_vermaGenerator b lam
  hv.vermaCentralCharacter_eq_of_representation_eq_smul
    (casimir_smul_of_isHighestWeightVector hv)

end TauCeti
