/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.CentralCharacter.HarishChandra
public import TauCeti.Algebra.Lie.HighestWeight.Integrability
public import TauCeti.LinearAlgebra.RootSystem.Weyl.DotAction
-- `Invertible (2 : K)`, which the dot action asks of the coefficient field.
public import Mathlib.Algebra.CharP.Invertible
-- Non-public: the simple reflections generate the Weyl group, used only for the final induction.
import TauCeti.LinearAlgebra.RootSystem.SimpleReflections
-- Non-public: elements of `S(H)` are polynomials along lines, and a polynomial with infinitely many
-- roots is zero; both are used only in the density step.
import TauCeti.LinearAlgebra.SymmetricAlgebra.Evaluation
import Mathlib.Algebra.Polynomial.Roots

/-!
# Central characters are constant on dot orbits

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, `H` a splitting Cartan subalgebra and `b` a base of its root system. The
centre `Z(U(L))` acts on every highest weight module of weight `λ` through the central character
`χ_λ = TauCeti.vermaCentralCharacter b λ`. This file proves that `χ_λ` depends only on the orbit of
`λ` under the **dot action** `w · λ = w(λ + ρ) - ρ` of the Weyl group:

`χ_{w · λ} = χ_λ`   (`TauCeti.vermaCentralCharacter_dotAction`).

Read through the Harish-Chandra projection `TauCeti.hcProjection b : Z(U(L)) →ₐ[K] S(H)`, whose
value at `λ` is `χ_λ` (`TauCeti.lift_hcProjection`), this says that the projection takes values in
the **dot-invariants** `S(H)^{W·}` (`TauCeti.hcProjection_mem_dotInvariants`), the polynomial
functions `p` on `H*` with `p(w · λ) = p(λ)` for all `w` and `λ` (`TauCeti.dotInvariants`). This is
the inclusion half of the Harish-Chandra isomorphism `Z(U(L)) ≃ S(H)^{W·}`, and the easy direction
of the theorem that `χ_λ = χ_μ` exactly when `μ ∈ W · λ`.

## The argument

The Weyl group is generated by the simple reflections, so it suffices to treat one simple
reflection `sᵢ`, which acts by `sᵢ · λ = λ - (⟨λ, αᵢ^∨⟩ + 1) αᵢ`.

* **Integral weights: a singular vector.** If `⟨λ, αᵢ^∨⟩ = n` is a natural number, then for a
  nonzero lowering vector `fᵢ` of `αᵢ` the vector `fᵢ^{n+1} · v_λ` of the Verma module `M(λ)` is
  nonzero (`TauCeti.pow_toEnd_vermaGenerator_ne_zero`, from Poincaré--Birkhoff--Witt) and is a
  highest weight vector of weight `sᵢ · λ`
  (`TauCeti.isHighestWeightVector_pow_toEnd_vermaGenerator`, from the integrability relation).
  The centre acts on it by `χ_{sᵢ · λ}`, and also by `χ_λ`, since it acts on all of `M(λ)` by
  `χ_λ`; so the two characters agree.
* **All weights: density.** For a central `z`, both `λ ↦ χ_λ(z)` and `λ ↦ χ_{sᵢ · λ}(z)` are
  polynomial functions of `λ` (`TauCeti.lift_hcProjection`), so along the line `λ + t αᵢ` they are
  polynomials in `t` (`SymmetricAlgebra.exists_polynomial_eval_eq_lift_add_smul`), using
  `sᵢ · (λ + t αᵢ) = sᵢ · λ - t αᵢ`. Since `⟨λ + t αᵢ, αᵢ^∨⟩ = ⟨λ, αᵢ^∨⟩ + 2t`, the integral case
  makes the two polynomials agree at the infinitely many `t` for which this is a natural number,
  hence everywhere, and in particular at `t = 0`.

## Main definitions

* `TauCeti.dotInvariants b`: the dot-invariants `S(H)^{W·}`, the subalgebra of `S(H)` of elements
  `p` with `p(w · λ) = p(λ)` for every Weyl group element `w` and weight `λ`.

## Main results

* `TauCeti.isHighestWeightVector_pow_toEnd_vermaGenerator`: for a simple root `αᵢ` with
  `⟨λ, αᵢ^∨⟩ = n ∈ ℕ`, `fᵢ^{n+1} · v_λ` is a highest weight vector of `M(λ)` of weight
  `λ - (n + 1) αᵢ`.
* `TauCeti.vermaCentralCharacter_dotAction`: **central characters are constant on dot orbits**.
* `TauCeti.hcProjection_mem_dotInvariants`: the Harish-Chandra projection takes values in the
  dot-invariants.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §23.2 and §23.3.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, Chapter 1,
  "Harish-Chandra's theorem".
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

universe u v

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]

local notation "U" => _root_.UniversalEnvelopingAlgebra K

variable {b : (IsKilling.rootSystem H).Base} {lam : Dual K H}

/-! ### The singular vector of an integral simple root -/

/-- **The singular vector of `M(lam)` along an integral simple root.** If `αᵢ` is a simple root with
`lam (αᵢ^∨) = n` a natural number and `f` is a nonzero lowering vector of `αᵢ`, then
`f^{n+1} · v_lam` is a highest weight vector of the Verma module `M(lam)`, of weight
`lam - (n + 1) αᵢ`, the dot reflection of `lam` in `αᵢ`. -/
theorem isHighestWeightVector_pow_toEnd_vermaGenerator {i : H.root} (hi : i ∈ b.support) {n : ℕ}
    (hn : lam ((IsKilling.rootSystem H).coroot i) = (n : K)) {f : L}
    (hf : f ∈ rootSpace H ((-(i : Weight K H L) : Weight K H L) : H → K)) (hf0 : f ≠ 0) :
    IsHighestWeightVector b (lam - (n + 1) • (IsKilling.rootSystem H).root i)
      (((toEnd K L (VermaModule b lam) f) ^ (n + 1)) (vermaGenerator b lam)) := by
  have hfneg : f ∈ negativeNilradical H b :=
    mem_negativeNilradical_of_mem_rootSpace H b (neg_mem_negRoots_of_mem_posRoots b
      (support_subset_posRoots (IsKilling.rootSystem H) b hi)) hf
  exact isHighestWeightVector_pow_toEnd_of_lieSpan_eq_top_of_ne_zero
    (isHighestWeightVector_vermaGenerator b lam) (lieSpan_vermaGenerator_eq_top b lam) hi hn hf
    (pow_toEnd_vermaGenerator_ne_zero b lam hfneg hf0 _)

/-- The central character is unchanged by the dot reflection in a simple root `αᵢ` along which the
weight is integral: the centre acts on the singular vector `fᵢ^{n+1} · v_lam` both by
`χ_{lam - (n+1) αᵢ}` and, as on all of `M(lam)`, by `χ_lam`. -/
private theorem vermaCentralCharacter_sub_nsmul_root {i : H.root} (hi : i ∈ b.support) {n : ℕ}
    (hn : lam ((IsKilling.rootSystem H).coroot i) = (n : K)) :
    vermaCentralCharacter b (lam - (n + 1) • (IsKilling.rootSystem H).root i) =
      vermaCentralCharacter b lam := by
  obtain ⟨h₀, e₀, f, ht, -, hf⟩ :=
    IsKilling.exists_isSl2Triple_of_weight_isNonZero (H.isNonZero_coe_root i)
  have hw := isHighestWeightVector_pow_toEnd_vermaGenerator hi hn hf ht.f_ne_zero
  ext z
  have h := hw.representation_eq_vermaCentralCharacter_smul z
  rw [(isHighestWeightVector_vermaGenerator b
    lam).representation_eq_vermaCentralCharacter_smul_of_lieSpan_eq_top
    (lieSpan_vermaGenerator_eq_top b lam)] at h
  exact (smul_left_injective K hw.ne_zero h).symm

/-! ### Invariance under a simple reflection -/

variable (b) in
/-- The central character is unchanged by the dot reflection `lam ↦ lam - (lam (αᵢ^∨) + 1) αᵢ` in
a simple root, for every weight. Along the line `lam + t αᵢ` both sides, evaluated at a central
element, are polynomials in `t`, and they agree at the infinitely many `t` making the weight
integral along `αᵢ`. -/
private theorem vermaCentralCharacter_sub_smul_root {i : H.root} (hi : i ∈ b.support)
    (lam : Dual K H) :
    vermaCentralCharacter b
        (lam - (lam ((IsKilling.rootSystem H).coroot i) + 1) • (IsKilling.rootSystem H).root i) =
      vermaCentralCharacter b lam := by
  set α := (IsKilling.rootSystem H).root i with hα
  set c := lam ((IsKilling.rootSystem H).coroot i) with hc
  have hαc : α ((IsKilling.rootSystem H).coroot i) = 2 := by
    rw [hα, IsKilling.rootSystem_root_apply, IsKilling.rootSystem_coroot_apply]
    exact IsKilling.root_apply_coroot (H.isNonZero_coe_root i)
  ext z
  rw [← lift_hcProjection, ← lift_hcProjection]
  -- the two sides along the line `lam + t α`, as polynomials in `t`
  obtain ⟨q₁, hq₁⟩ := SymmetricAlgebra.exists_polynomial_eval_eq_lift_add_smul
    (hcProjection b z) lam α
  obtain ⟨q₂, hq₂⟩ := SymmetricAlgebra.exists_polynomial_eval_eq_lift_add_smul
    (hcProjection b z) (lam - (c + 1) • α) (-α)
  -- at `t n = (n - c) / 2` the weight `lam + t n • α` takes the value `n` on `αᵢ^∨`
  let t : ℕ → K := fun n ↦ ((n : K) - c) / 2
  have ht : Function.Injective t := fun m n h ↦ by
    simpa [t, div_left_inj' (two_ne_zero' K)] using h
  have hroot (n : ℕ) : (q₁ - q₂).IsRoot (t n) := by
    have hn : (lam + t n • α) ((IsKilling.rootSystem H).coroot i) = (n : K) := by
      rw [LinearMap.add_apply, LinearMap.smul_apply, hαc, ← hc, smul_eq_mul]
      field_simp [t]
      ring
    have hshift : lam + t n • α - (n + 1) • α = lam - (c + 1) • α + t n • -α := by
      rw [← Nat.cast_smul_eq_nsmul K]
      module
    rw [Polynomial.IsRoot, Polynomial.eval_sub, sub_eq_zero, hq₁, hq₂, lift_hcProjection,
      lift_hcProjection, ← hshift, vermaCentralCharacter_sub_nsmul_root hi hn]
  have h0 := Polynomial.eq_zero_of_infinite_isRoot (q₁ - q₂)
    ((Set.infinite_range_of_injective ht).mono (Set.range_subset_iff.mpr hroot))
  have h := congrArg (Polynomial.eval 0) h0
  rw [Polynomial.eval_sub, Polynomial.eval_zero, sub_eq_zero, hq₁, hq₂, zero_smul, zero_smul,
    add_zero, add_zero] at h
  exact h.symm

/-! ### Invariance under the Weyl group -/

variable (b) in
/-- **Central characters are constant on dot orbits**: `χ_{w · lam} = χ_lam` for every element `w`
of the Weyl group, where `w · lam = w (lam + ρ) - ρ` is the dot action. -/
@[simp]
theorem vermaCentralCharacter_dotAction (w : (IsKilling.rootSystem H).weylGroup)
    (lam : Dual K H) :
    vermaCentralCharacter b (dotAction (IsKilling.rootSystem H) b w lam) =
      vermaCentralCharacter b lam := by
  have hw : w ∈ Subgroup.closure (Set.range fun i : b.support ↦
      RootPairing.weylGroup.ofIdx (IsKilling.rootSystem H) (i : H.root)) := by
    rw [← weylGroup_eq_closure_simple (IsKilling.rootSystem H) b]
    exact Subgroup.mem_top w
  induction hw using Subgroup.closure_induction generalizing lam with
  | mem x hx =>
    obtain ⟨⟨i, hi⟩, rfl⟩ := hx
    rw [dotAction_ofIdx _ b hi, rootSystem_coroot'_apply]
    exact vermaCentralCharacter_sub_smul_root b hi lam
  | one => rw [dotAction_one]
  | mul x y _ _ hx hy => rw [dotAction_mul, hx, hy]
  | inv x _ hx => rw [← hx, dotAction_dotAction_inv]

/-! ### The dot-invariants -/

variable (b) in
/-- **The dot-invariants** `S(H)^{W·}`: the elements `p` of the symmetric algebra `S(H)`, read as
polynomial functions on the weights `H*`, with `p(w · lam) = p(lam)` for every Weyl group element
`w` and every weight `lam`, where `w · lam` is the dot action. -/
noncomputable def dotInvariants : Subalgebra K (SymmetricAlgebra K H) where
  carrier := {p | ∀ (w : (IsKilling.rootSystem H).weylGroup) (lam : Dual K H),
    SymmetricAlgebra.lift (dotAction (IsKilling.rootSystem H) b w lam) p =
      SymmetricAlgebra.lift lam p}
  mul_mem' hp hq w lam := by simp only [map_mul, hp w lam, hq w lam]
  add_mem' hp hq w lam := by simp only [map_add, hp w lam, hq w lam]
  algebraMap_mem' r w lam := by simp only [AlgHom.commutes]

/-- Membership in the dot-invariants: `p(w · lam) = p(lam)` for every Weyl group element `w` and
every weight `lam`. -/
@[simp]
theorem mem_dotInvariants_iff {p : SymmetricAlgebra K H} :
    p ∈ dotInvariants b ↔ ∀ (w : (IsKilling.rootSystem H).weylGroup) (lam : Dual K H),
      SymmetricAlgebra.lift (dotAction (IsKilling.rootSystem H) b w lam) p =
        SymmetricAlgebra.lift lam p :=
  Iff.rfl

/-- **The Harish-Chandra projection takes values in the dot-invariants**: its value at a weight is
the central character, which is constant on dot orbits. -/
theorem hcProjection_mem_dotInvariants (z : Subalgebra.center K (U L)) :
    hcProjection b z ∈ dotInvariants b := fun w lam ↦ by
  rw [lift_hcProjection, lift_hcProjection, vermaCentralCharacter_dotAction]

end TauCeti
