/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.CentralCharacter.Basic
public import TauCeti.Algebra.Lie.Isotypic
public import TauCeti.Algebra.Lie.UniversalEnveloping.CenterEigenspace
import Mathlib.Algebra.Lie.CartanExists
import Mathlib.LinearAlgebra.RootSystem.BaseExists
import TauCeti.Algebra.Lie.HighestWeight.CompleteReducibility
import TauCeti.Algebra.Lie.HighestWeight.FiniteDimensional

/-!
# The centre of `U(L)` on isotypic components

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, `H` a splitting Cartan subalgebra and `b` a base of its root system. The
centre `Z(U(L))` of the universal enveloping algebra acts on every highest weight module of weight
`lam` through the central character `chi_lam = TauCeti.vermaCentralCharacter b lam`. This file
reads that statement on the isotypic components of an arbitrary module, and then, for a
finite-dimensional module over an algebraically closed field, as a decomposition of the module
under the centre.

* **The centre acts on the `L(lam)`-isotypic component by `chi_lam`**
  (`TauCeti.isotypicComponent_irreducibleQuotient_le_centerEigenspace`): every Lie submodule
  equivalent to `L(lam)` is a highest weight module of weight `lam`, so it lies in the centre
  eigenspace `M_{chi_lam}` (`TauCeti.UniversalEnvelopingAlgebra.centerEigenspace`), and so does
  their sum. No finite-dimensionality is needed. Consequently isotypic components whose central
  characters differ are disjoint
  (`TauCeti.disjoint_isotypicComponent_irreducibleQuotient_of_vermaCentralCharacter_ne`).
* **The centre acts semisimply on a finite-dimensional module**
  (`TauCeti.isInternal_centerEigenspace`): by Weyl's theorem such a module is a direct sum of
  irreducible submodules, each a copy of some `L(lam)` with `lam` dominant integral, so it is the
  sum of the centre eigenspaces `M_{chi_lam}` over dominant integral `lam`
  (`TauCeti.iSup_centerEigenspace_vermaCentralCharacter_eq_top`). Centre eigenspaces for distinct
  eigenvalue functions are independent, so the module is the internal direct sum of its centre
  eigenspaces, and the only eigenvalue functions occurring are the central characters of dominant
  integral weights (`TauCeti.exists_isDominantIntegral_eq_vermaCentralCharacter`).

This is the eigenspace-of-the-centre refinement of the isotypic decomposition
`M ≅ ⨁ L(lam)^{m lam}` (`TauCeti.nonempty_lieModuleEquiv_directSum_irreducibleQuotient`): it groups
the isotypic components by central character. That distinct dominant integral weights have
distinct central characters, which would make the two decompositions coincide, is the
Harish-Chandra orbit theorem and is not proved here.

## Main results

* `TauCeti.IsHighestWeightVector.lieSpan_le_centerEigenspace`: the submodule generated by a
  highest weight vector of weight `lam` lies in the centre eigenspace of `chi_lam`.
* `TauCeti.centerEigenspace_irreducibleQuotient_eq_top`: the centre acts on `L(lam)` by
  `chi_lam`.
* `TauCeti.isotypicComponent_irreducibleQuotient_le_centerEigenspace`: **the centre acts on the
  `L(lam)`-isotypic component of any module by `chi_lam`**.
* `TauCeti.iSup_centerEigenspace_vermaCentralCharacter_eq_top`: a finite-dimensional module is
  spanned by the centre eigenspaces of the central characters of dominant integral weights.
* `TauCeti.isInternal_centerEigenspace`: a finite-dimensional module is the internal direct sum of
  its centre eigenspaces.
* `TauCeti.exists_isDominantIntegral_eq_vermaCentralCharacter`: every eigenvalue function with a
  nonzero centre eigenspace in a finite-dimensional module is the central character of a dominant
  integral weight.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §23.2.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, §1.7.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

local notation "U" => _root_.UniversalEnvelopingAlgebra K L

section Isotypic

variable [IsTriangularizable K H L] {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-- **The submodule generated by a highest weight vector of weight `lam` lies in the centre
eigenspace of the central character `chi_lam`.** -/
theorem IsHighestWeightVector.lieSpan_le_centerEigenspace (hv : IsHighestWeightVector b lam v) :
    LieSubmodule.lieSpan K L {v} ≤ centerEigenspace K L M (vermaCentralCharacter b lam) :=
  lieSpan_le_centerEigenspace_iff.mpr fun _ hw z ↦ by
    rw [Set.mem_singleton_iff.mp hw]
    exact hv.representation_eq_vermaCentralCharacter_smul z

variable (b lam) in
/-- **The centre of `U(L)` acts on `L(lam)` by the central character `chi_lam`.** -/
@[simp]
theorem centerEigenspace_irreducibleQuotient_eq_top :
    centerEigenspace K L (irreducibleQuotient b lam) (vermaCentralCharacter b lam) = ⊤ :=
  top_le_iff.mp <| lieSpan_irreducibleQuotientGenerator_eq_top b lam ▸
    (isHighestWeightVector_irreducibleQuotientGenerator b lam).lieSpan_le_centerEigenspace

/-- A Lie submodule equivalent to `L(lam)` lies in the centre eigenspace of `chi_lam`. -/
theorem le_centerEigenspace_of_nonempty_lieModuleEquiv {P : LieSubmodule K L M}
    (e : Nonempty (P ≃ₗ⁅K,L⁆ irreducibleQuotient b lam)) :
    P ≤ centerEigenspace K L M (vermaCentralCharacter b lam) := by
  obtain ⟨e⟩ := e
  intro m hm
  have hw : e ⟨m, hm⟩ ∈ centerEigenspace K L (irreducibleQuotient b lam)
      (vermaCentralCharacter b lam) := by
    rw [centerEigenspace_irreducibleQuotient_eq_top]
    exact LieSubmodule.mem_top _
  simpa using (P.incl.comp (e.symm : _ →ₗ⁅K,L⁆ P)).map_centerEigenspace_le _
    (LieSubmodule.mem_map_of_mem hw)

/-- **The centre of `U(L)` acts on the `L(lam)`-isotypic component of any module by the central
character `chi_lam`**: the isotypic component lies in the centre eigenspace of `chi_lam`. -/
theorem isotypicComponent_irreducibleQuotient_le_centerEigenspace :
    isotypicComponent K L M (irreducibleQuotient b lam) ≤
      centerEigenspace K L M (vermaCentralCharacter b lam) :=
  (isotypicComponent_le_iff K L M _ _).mpr fun _ ↦ le_centerEigenspace_of_nonempty_lieModuleEquiv

/-- **Isotypic components with distinct central characters are disjoint.** -/
theorem disjoint_isotypicComponent_irreducibleQuotient_of_vermaCentralCharacter_ne
    {mu : Dual K H} (h : vermaCentralCharacter b lam ≠ vermaCentralCharacter b mu) :
    Disjoint (isotypicComponent K L M (irreducibleQuotient b lam))
      (isotypicComponent K L M (irreducibleQuotient b mu)) :=
  (disjoint_centerEigenspace (DFunLike.coe_injective.ne h)).mono
    isotypicComponent_irreducibleQuotient_le_centerEigenspace
    isotypicComponent_irreducibleQuotient_le_centerEigenspace

end Isotypic

section FiniteDimensional

variable [IsAlgClosed K] [FiniteDimensional K M] (b : (IsKilling.rootSystem H).Base)

variable (M) in
/-- **A finite-dimensional module is spanned by the centre eigenspaces of the central characters
of dominant integral weights.** By Weyl's theorem the module is a sum of irreducible submodules,
each a copy of some `L(lam)` with `lam` dominant integral, on which the centre acts by
`chi_lam`. -/
theorem iSup_centerEigenspace_vermaCentralCharacter_eq_top :
    ⨆ lam : {l : Dual K H // IsDominantIntegral b l},
      centerEigenspace K L M (vermaCentralCharacter b lam.1) = ⊤ := by
  obtain ⟨k, N, hint, hirr⟩ := exists_isInternal_isIrreducible_of_isKilling K L M
  -- each irreducible summand is a copy of some `L(lam)`, so it lies in `M_{chi_lam}`
  have hN (i : Fin k) : N i ≤ ⨆ lam : {l : Dual K H // IsDominantIntegral b l},
      centerEigenspace K L M (vermaCentralCharacter b lam.1) := by
    have := hirr i
    obtain ⟨lam, hlam, e⟩ :=
      exists_isDominantIntegral_nonempty_lieModuleEquiv_irreducibleQuotient (M := N i) b
    exact le_iSup_of_le ⟨lam, hlam⟩ (le_centerEigenspace_of_nonempty_lieModuleEquiv e)
  exact top_unique <| LieSubmodule.iSup_toSubmodule_eq_top.mp hint.submodule_iSup_eq_top ▸
    iSup_le hN

open Classical in
variable (M) in
/-- **The centre of `U(L)` acts semisimply on a finite-dimensional module**: the module is the
internal direct sum of its centre eigenspaces. -/
theorem isInternal_centerEigenspace :
    DirectSum.IsInternal fun χ : Subalgebra.center K U → K ↦
      (centerEigenspace K L M χ).toSubmodule := by
  rw [DirectSum.isInternal_submodule_iff_iSupIndep_and_iSup_eq_top,
    LieSubmodule.iSupIndep_toSubmodule, LieSubmodule.iSup_toSubmodule_eq_top]
  refine ⟨iSupIndep_centerEigenspace, top_le_iff.mp ?_⟩
  -- the statement is intrinsic; a splitting Cartan subalgebra and a base are chosen to prove it
  obtain ⟨x₀, hx₀⟩ := LieAlgebra.exists_isCartanSubalgebra_engel K L
  have _i : (LieSubalgebra.engel K x₀).IsCartanSubalgebra := hx₀
  obtain ⟨b⟩ := (IsKilling.rootSystem (LieSubalgebra.engel K x₀)).nonempty_base
  rw [← iSup_centerEigenspace_vermaCentralCharacter_eq_top M b]
  exact iSup_le fun lam ↦ le_iSup (fun χ ↦ centerEigenspace K L M χ) _

/-- **The only eigenvalue functions of the centre on a finite-dimensional module are the central
characters of dominant integral weights**: a nonzero centre eigenspace belongs to `chi_lam` for a
dominant integral weight `lam`. -/
theorem exists_isDominantIntegral_eq_vermaCentralCharacter {χ : Subalgebra.center K U → K}
    (h : centerEigenspace K L M χ ≠ ⊥) :
    ∃ lam : Dual K H, IsDominantIntegral b lam ∧ χ = vermaCentralCharacter b lam := by
  by_contra! hne
  refine h (disjoint_self.mp ((iSupIndep_centerEigenspace χ).mono_right (le_top.trans ?_)))
  rw [← iSup_centerEigenspace_vermaCentralCharacter_eq_top M b]
  refine iSup_le fun lam ↦ ?_
  exact le_iSup₂_of_le (f := fun χ' (_ : χ' ≠ χ) ↦ centerEigenspace K L M χ')
    (vermaCentralCharacter b lam.1 : Subalgebra.center K U → K) (hne lam.1 lam.2).symm le_rfl

end FiniteDimensional

end TauCeti
