/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Lie.InvariantVectorField.Basic
public import TauCeti.Geometry.Manifold.Distribution

/-!
# The left-invariant distribution of a Lie subalgebra

A subspace `S` of the Lie algebra `GroupLieAlgebra I G` of a Lie group `G` determines a
distribution on `G`: at `g` it is the image `d(L_g)₁ S` of `S` under the differential at the
identity of left translation by `g`, equivalently the span at `g` of the left-invariant vector
fields generated by `S`. This file proves that `S` is a Lie subalgebra whenever this
left-invariant distribution is involutive, and that conversely, when the model space `E` is
finite-dimensional over a complete field `𝕜`, the distribution of a Lie subalgebra is involutive.
Involutivity is the hypothesis of the Frobenius theorem, which supplies an integral leaf through
the identity; showing that this leaf is a connected immersed Lie subgroup with Lie algebra `S`
takes further arguments. This is the analytic input to the correspondence between Lie
subalgebras and connected Lie subgroups.

The distribution has a global frame: the invariant vector fields generated by a basis of `S`. One
direction of the characterization is immediate, since at the identity the bracket of two
invariant vector fields is the bracket in the Lie algebra. For the other, a vector field `V`
tangent to the distribution near a point is a combination of the frame whose coefficients are the
coordinates of the left Maurer-Cartan form evaluated on `V` (`TauCeti.leftMaurerCartanEval`,
defined in `TauCeti.Geometry.Lie.InvariantVectorField.Basic`). That function is differentiable
wherever `V` is (`MDifferentiableAt.leftMaurerCartanEval`), and the bracket of two such
combinations stays in the distribution because the brackets of the frame fields are the invariant
vector fields of brackets in `S` (`TauCeti.mlieBracket_sum_smul_mem`).

## Main definitions

* `TauCeti.mulInvariantDistribution S`: the left-invariant distribution of a subspace `S` of the
  Lie algebra.

## Main results

* `TauCeti.mem_mulInvariantDistribution_iff`: a tangent vector at `g` lies in the distribution
  exactly when its translate to the identity lies in `S`.
* `TauCeti.map_mfderiv_mul_left_mulInvariantDistribution`: the distribution is invariant under
  left translation.
* `TauCeti.isDistributionFrameOn_mulInvariantDistribution`: the invariant vector fields of a basis
  of `S` form a global frame, so (`TauCeti.isContMDiffDistribution_mulInvariantDistribution`) when
  `S` is finite-dimensional and multiplication is `C^n`, the distribution is `C^m` of rank
  `finrank S` for every `m` with `m + 1 ≤ n`.
* `TauCeti.isInvolutiveDistribution_mulInvariantDistribution_iff`: when `E` is finite-dimensional
  over a complete field, the distribution is involutive exactly when `S` is closed under the
  bracket.

## Implementation notes

The left Maurer-Cartan form evaluated on a vector field takes values in the model space `E`
rather than in `GroupLieAlgebra I G` (see `TauCeti.Geometry.Lie.InvariantVectorField.Basic`), so
statements feeding it back into `GroupLieAlgebra I G` name `E` explicitly.

## References

* J. M. Lee, *Introduction to Smooth Manifolds*, 2nd ed., Springer GTM 218 (2013), Chapter 19
  (involutive distributions, the Frobenius theorem, and Lie subgroups from Lie subalgebras).
* F. W. Warner, *Foundations of Differentiable Manifolds and Lie Groups*, Springer GTM 94 (1983),
  Chapter 3.
-/

public section

noncomputable section

open Bundle Function Module Set VectorField
open scoped ContDiff Manifold Topology

namespace TauCeti

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]

/-- The left-invariant distribution of a subspace `S` of the Lie algebra of `G`: at `g` it is the
image of `S` under the differential at the identity of left translation by `g`. -/
def mulInvariantDistribution (S : Submodule 𝕜 (GroupLieAlgebra I G)) (g : G) :
    Submodule 𝕜 (TangentSpace I g) :=
  S.map (mfderiv I I (g * ·) 1 : GroupLieAlgebra I G →L[𝕜] TangentSpace I g).toLinearMap

variable {S : Submodule 𝕜 (GroupLieAlgebra I G)}

/-- The left-invariant distribution of `S` at `g` consists of the values at `g` of the invariant
vector fields generated by elements of `S`. -/
theorem mem_mulInvariantDistribution {g : G} {v : TangentSpace I g} :
    v ∈ mulInvariantDistribution S g ↔ ∃ w ∈ S, mulInvariantVectorField w g = v :=
  Submodule.mem_map

/-- The invariant vector field generated by an element of `S` is tangent to the left-invariant
distribution of `S`. -/
theorem mulInvariantVectorField_mem_mulInvariantDistribution {w : GroupLieAlgebra I G}
    (hw : w ∈ S) (g : G) : mulInvariantVectorField w g ∈ mulInvariantDistribution S g :=
  mem_mulInvariantDistribution.mpr ⟨w, hw, rfl⟩

/-- At the identity, the left-invariant distribution of `S` is `S` itself. -/
@[simp]
theorem mulInvariantDistribution_one : mulInvariantDistribution S (1 : G) = S := by
  ext v
  simp [mem_mulInvariantDistribution]

section Translation

variable [ContMDiffMul I 1 G]

/-- A tangent vector at `g` lies in the left-invariant distribution of `S` exactly when its
translate to the identity lies in `S`. -/
theorem mem_mulInvariantDistribution_iff {g : G} {v : TangentSpace I g} :
    v ∈ mulInvariantDistribution S g ↔ mfderiv I I (g⁻¹ * ·) g v ∈ S := by
  rw [mem_mulInvariantDistribution]
  constructor
  · rintro ⟨w, hw, rfl⟩
    rwa [mfderiv_inv_mul_mulInvariantVectorField]
  · exact fun h ↦ ⟨_, h, mulInvariantVectorField_mfderiv_inv_mul v⟩

/-- The left-invariant distribution of `S` is invariant under left translation: the differential at
`g` of left translation by `h` carries it at `g` onto it at `h * g`. -/
theorem map_mfderiv_mul_left_mulInvariantDistribution (h g : G) :
    (mulInvariantDistribution S g).map
        (mfderiv I I (h * ·) g : TangentSpace I g →L[𝕜] TangentSpace I (h * g)).toLinearMap =
      mulInvariantDistribution S (h * g) := by
  ext v
  simp only [Submodule.mem_map, mem_mulInvariantDistribution]
  constructor
  · rintro ⟨_, ⟨w, hw, rfl⟩, rfl⟩
    exact ⟨w, hw, (mfderiv_mul_left_mulInvariantVectorField h g w).symm⟩
  · rintro ⟨w, hw, rfl⟩
    exact ⟨_, ⟨w, hw, rfl⟩, mfderiv_mul_left_mulInvariantVectorField h g w⟩

end Translation

section Frame

/-- The invariant vector fields generated by a basis of `S` form a global frame of the
left-invariant distribution of `S`. They are `C^m` when multiplication is `C^n` with
`m + 1 ≤ n`. -/
theorem isDistributionFrameOn_mulInvariantDistribution {m n : ℕ∞ω}
    [ContMDiffMul I n G] (hmn : m + 1 ≤ n) {ι : Type*} (b : Basis ι 𝕜 S) :
    let _ : IsManifold I 1 G := IsManifold.of_le (le_add_self.trans hmn)
    IsDistributionFrameOn I m (mulInvariantDistribution S)
      (fun i ↦ mulInvariantVectorField (b i : GroupLieAlgebra I G)) univ := by
  have : ContMDiffMul I 1 G := ContMDiffMul.of_le (le_add_self.trans hmn)
  intro _
  refine ⟨fun i ↦ ?_, fun {g} _ ↦ ?_, fun {g} _ ↦ ?_⟩
  · exact ((contMDiff_mulInvariantVectorField_modelSpace hmn).comp
      (contMDiff_const.prodMk contMDiff_id)).contMDiffOn
  · refine LinearIndependent.of_comp (mfderiv I I (g⁻¹ * ·) g).toLinearMap ?_
    have : (mfderiv I I (g⁻¹ * ·) g).toLinearMap ∘
        (fun i ↦ mulInvariantVectorField (b i : GroupLieAlgebra I G) g) = S.subtype ∘ b := by
      funext i
      exact mfderiv_inv_mul_mulInvariantVectorField _ g
    rw [this]
    exact b.linearIndependent.map' S.subtype S.ker_subtype
  · -- Left translation by `g`, typed as a map into the tangent space at `g`.
    let L : GroupLieAlgebra I G →ₗ[𝕜] TangentSpace I g := (mfderiv I I (g * ·) 1).toLinearMap
    have hrange : (range fun i ↦ mulInvariantVectorField (b i : GroupLieAlgebra I G) g) =
        L '' (S.subtype '' range b) := by
      rw [← range_comp, ← range_comp]
      rfl
    rw [hrange, Submodule.span_image, Submodule.span_image, b.span_eq, Submodule.map_subtype_top]
    rfl

/-- The left-invariant distribution of a finite-dimensional subspace `S` is a `C^m` distribution
of rank `finrank 𝕜 S` when multiplication is `C^n` with `m + 1 ≤ n`. -/
theorem isContMDiffDistribution_mulInvariantDistribution {m n : ℕ∞ω}
    [ContMDiffMul I n G] (hmn : m + 1 ≤ n) [FiniteDimensional 𝕜 S] :
    let _ : IsManifold I 1 G := IsManifold.of_le (le_add_self.trans hmn)
    IsContMDiffDistribution I m (finrank 𝕜 S) (mulInvariantDistribution S) :=
  let _ : IsManifold I 1 G := IsManifold.of_le (le_add_self.trans hmn)
  (isDistributionFrameOn_mulInvariantDistribution hmn
    (Module.finBasis 𝕜 S)).isContMDiffDistribution

end Frame

/-- A combination of invariant vector fields with function coefficients takes at `g` the value of
the invariant vector field generated by the combination of the generators with the coefficients
at `g`. -/
private theorem sum_smul_mulInvariantVectorField_apply {ι : Type*} (s : Finset ι)
    (c : ι → G → 𝕜) (v : ι → GroupLieAlgebra I G) (g : G) :
    (∑ i ∈ s, c i • mulInvariantVectorField (v i)) g =
      mulInvariantVectorField (∑ i ∈ s, c i g • v i) g := by
  simp only [Finset.sum_apply, Pi.smul_apply', mulInvariantVectorField, map_sum, map_smul]
  rfl

section Involutive

variable [LieGroup I (minSmoothness 𝕜 3) G]

/-- If the left-invariant distribution of `S` is involutive, then `S` is closed under the bracket:
the bracket of two elements of `S` is the value at the identity of the bracket of the invariant
vector fields they generate. -/
theorem lie_mem_of_isInvolutiveDistribution_mulInvariantDistribution
    (hD : IsInvolutiveDistribution I (mulInvariantDistribution S)) {v w : GroupLieAlgebra I G}
    (hv : v ∈ S) (hw : w ∈ S) : ⁅v, w⁆ ∈ S := by
  have h := hD.mlieBracket_mem isOpen_univ
    (mdifferentiable_mulInvariantVectorField v).mdifferentiableOn
    (mdifferentiable_mulInvariantVectorField w).mdifferentiableOn
    (fun g _ ↦ mulInvariantVectorField_mem_mulInvariantDistribution hv g)
    (fun g _ ↦ mulInvariantVectorField_mem_mulInvariantDistribution hw g) (mem_univ 1)
  rwa [mulInvariantDistribution_one] at h

/-- **The left-invariant distribution of a Lie subalgebra is involutive.** If a subspace `S` of the
Lie algebra of `G` is closed under the bracket, then its left-invariant distribution is
involutive. This is the hypothesis of the Frobenius theorem, which supplies the integral leaf
through the identity from which the connected Lie subgroup with Lie algebra `S` is built. -/
theorem isInvolutiveDistribution_mulInvariantDistribution [CompleteSpace 𝕜]
    [FiniteDimensional 𝕜 E] (hS : ∀ v ∈ S, ∀ w ∈ S, ⁅v, w⁆ ∈ S) :
    IsInvolutiveDistribution I (mulInvariantDistribution S) := by
  have : CompleteSpace E := FiniteDimensional.complete 𝕜 E
  have h23 : (2 : ℕ∞ω) ≤ 3 := by norm_num
  have : LieGroup I 2 G := LieGroup.of_le (n := minSmoothness 𝕜 3) (h23.trans le_minSmoothness)
  refine isInvolutiveDistribution_iff.mpr fun U hU V W hV hW hVD hWD x hx ↦ ?_
  let b := Module.finBasis 𝕜 S
  -- The coordinate functionals of `b`, extended to the whole Lie algebra.
  choose φ hφ using fun i ↦ LinearMap.exists_extend (b.coord i)
  -- On `U`, a vector field tangent to the distribution is the combination of the invariant vector
  -- fields of `b` with coefficients the coordinates of the left Maurer-Cartan form evaluated on
  -- it.
  have expand {Y : Π g : G, TangentSpace I g} (hY : ∀ g ∈ U, Y g ∈ mulInvariantDistribution S g) :
      Y =ᶠ[𝓝 x] ∑ i, (fun g ↦ φ i (leftMaurerCartanEval (E := E) Y g)) •
        mulInvariantVectorField (b i : GroupLieAlgebra I G) := by
    filter_upwards [hU.mem_nhds hx] with g hg
    have hmem : leftMaurerCartanEval (E := E) Y g ∈ S := by
      rw [leftMaurerCartanEval_apply]
      exact mem_mulInvariantDistribution_iff.mp (hY g hg)
    have hsum := congrArg Subtype.val (b.sum_repr ⟨_, hmem⟩)
    simp only [Submodule.coe_sum, Submodule.coe_smul] at hsum
    have hgen : ∑ i, φ i (leftMaurerCartanEval (E := E) Y g) • (b i : GroupLieAlgebra I G) =
        leftMaurerCartanEval (E := E) Y g := by
      refine Eq.trans (Finset.sum_congr rfl fun i _ ↦ ?_) hsum
      rw [← b.coord_apply, ← hφ i]
      rfl
    refine Eq.trans ?_ (sum_smul_mulInvariantVectorField_apply _ _ _ g).symm
    rw [hgen, mulInvariantVectorField_leftMaurerCartanEval]
  -- The coefficients are differentiable at `x`.
  have hcoeff {Y : Π g : G, TangentSpace I g} (hY : MDiff[U] (T% Y)) (i) :
      MDiffAt (fun g ↦ φ i (leftMaurerCartanEval (E := E) Y g)) x := by
    -- `φ i` is a linear functional on the finite-dimensional model space, hence continuous.
    let ψ : E →L[𝕜] 𝕜 := LinearMap.toContinuousLinearMap (φ i ∘ₗ LinearMap.id)
    exact ψ.mdifferentiableAt.comp x
      ((hY x hx).mdifferentiableAt (hU.mem_nhds hx)).leftMaurerCartanEval
  rw [(expand hVD).mlieBracket_vectorField_eq (expand hWD)]
  refine mlieBracket_sum_smul_mem (fun i _ ↦ mdifferentiableAt_mulInvariantVectorField _)
    (fun i _ ↦ mulInvariantVectorField_mem_mulInvariantDistribution (b i).2 x)
    (fun i _ j _ ↦ ?_) (fun i _ ↦ hcoeff hV i) (fun i _ ↦ hcoeff hW i)
  rw [← mulInvariantVector_mlieBracket, ← GroupLieAlgebra.bracket_def]
  exact mulInvariantVectorField_mem_mulInvariantDistribution (hS _ (b i).2 _ (b j).2) x

/-- The left-invariant distribution of a subspace `S` of the Lie algebra is involutive exactly when
`S` is closed under the bracket, that is, when `S` is a Lie subalgebra. -/
theorem isInvolutiveDistribution_mulInvariantDistribution_iff [CompleteSpace 𝕜]
    [FiniteDimensional 𝕜 E] :
    IsInvolutiveDistribution I (mulInvariantDistribution S) ↔ ∀ v ∈ S, ∀ w ∈ S, ⁅v, w⁆ ∈ S :=
  ⟨fun hD _ hv _ hw ↦ lie_mem_of_isInvolutiveDistribution_mulInvariantDistribution hD hv hw,
    isInvolutiveDistribution_mulInvariantDistribution⟩

end Involutive

end TauCeti
