/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.Symplectic.Basic
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.UpperTriangular.Basic
public import TauCeti.Algebra.AlgebraicGroup.Solvable.Basic
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Symplectic.IsotropicFlag.Basic

/-!
# The standard complete isotropic flag subgroup of the symplectic group

In paired coordinates `e₀, …, eₘ₋₁, f₀, …, fₘ₋₁`, the standard complete isotropic flag
is spanned successively by `e₀`, by `e₀, e₁`, and so on. Its self-dual completion orders
the full basis as `e₀, …, eₘ₋₁, fₘ₋₁, …, f₀`. This file constructs the finite-type
closed subgroup of `Sp₂ₘ` whose matrices are upper triangular in this order. In the
original paired order these matrices have upper-triangular upper-left block,
lower-triangular lower-right block, and zero lower-left block.

The quotient Hopf algebra represents these matrices over every commutative algebra,
including nonreduced algebras and characteristic two. Its algebra-valued point groups
are solvable. The diagonal symplectic torus factorization is developed in
`TauCeti.Algebra.AlgebraicGroup.Symplectic.IsotropicFlag.DiagonalTorus`. Positive root subgroup
factorizations are developed in
`TauCeti.Algebra.AlgebraicGroup.Symplectic.IsotropicFlag.RootSubgroup`.
These constructions provide the flag subgroup used in the standard symplectic pinning;
no smoothness, connectedness, or Borel maximality assertion is made here.

The construction uses `GeneralLinear.weightParabolicDefiningHopfIdeal`; the quotient
points arguments follow
`TauCeti.Algebra.AlgebraicGroup.SpecialLinear.UpperTriangular.Basic`.

## References

* J. S. Milne, *Algebraic Groups* (2017), §24.6 (symplectic groups and isotropic flags).
* B. Conrad, *Reductive Group Schemes* (2014), §5.1 (pinnings).
-/

public section

open AlgebraicGeometry CategoryTheory WithConv Matrix
open scoped CategoryTheory.MonObj

namespace TauCeti.Symplectic.IsotropicFlag

open GLSymplecticFin.IsotropicFlag

universe u v w

variable (R : Type u) [CommRing R] (m : ℕ)

/-- General-linear upper-triangular weights read in the self-dual flag order. -/
def weights : Fin (m + m) → ℤ :=
  GeneralLinear.UpperTriangular.weights (m + m) ∘ flagOrder m

/-- The flag weight at a basis index is the upper-triangular weight of its flag-order index. -/
@[simp]
theorem weights_apply (i : Fin (m + m)) :
    weights m i = GeneralLinear.UpperTriangular.weights (m + m) (flagOrder m i) := by
  rw [weights, Function.comp_apply]

/-- The flag weights decrease precisely when the flag-order index increases. -/
theorem weights_lt_weights_iff (i j : Fin (m + m)) :
    weights m i < weights m j ↔ flagOrder m j < flagOrder m i := by
  simp only [weights_apply, GeneralLinear.UpperTriangular.weights_lt_weights_iff]

/-- The flag weights are pairwise distinct. -/
theorem weights_injective : Function.Injective (weights m) :=
  (GeneralLinear.UpperTriangular.weights_injective (m + m)).comp (flagOrder m).injective

/-- The Hopf ideal cutting out the standard complete isotropic flag subgroup in `Sp₂ₘ`.
It is the image of `GeneralLinear.weightParabolicDefiningHopfIdeal` for the
upper-triangular weights composed with `flagOrder m`, under symplectic coordinate restriction. -/
noncomputable def definingHopfIdeal : HopfIdeal R (Symplectic.coordinateHopfAlgebra R m) :=
  (GeneralLinear.weightParabolicDefiningHopfIdeal R (weights m)).map
    (Symplectic.coordinateMap R m).hom

/-- The flag ideal is the symplectic restriction of the flag-order weight-parabolic ideal. -/
theorem definingHopfIdeal_def :
    definingHopfIdeal R m =
      (GeneralLinear.weightParabolicDefiningHopfIdeal R (weights m)).map
        (Symplectic.coordinateMap R m).hom := by
  rw [definingHopfIdeal]

/-- The flag ideal is generated by the generic symplectic entries strictly below the
diagonal in the self-dual flag order. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R m).toIdeal =
      Ideal.span ((Symplectic.coordinateMap R m).hom ''
        GeneralLinear.weightParabolicRelationSet R (weights m)) := by
  rw [definingHopfIdeal, HopfIdeal.map_toIdeal,
    GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal, Ideal.map_span]
  rfl

/-- The isotropic flag subgroup is defined by finitely many equations. -/
theorem definingHopfIdeal_toIdeal_fg : (definingHopfIdeal R m).toIdeal.FG := by
  rw [definingHopfIdeal_toIdeal]
  refine Submodule.fg_span (Set.Finite.image _ ?_)
  refine (Set.finite_range fun p : Fin (m + m) × Fin (m + m) ↦
    GeneralLinear.coordinateHopfAlgebraAlgEquiv R (m + m)
      (GeneralLinear.coordinateRingMap R (m + m) (MvPolynomial.X p))).subset ?_
  intro x hx
  obtain ⟨i, j, _, rfl⟩ :=
    (GeneralLinear.mem_weightParabolicRelationSet_iff R (weights m) x).mp hx
  exact ⟨(i, j), rfl⟩

/-- The coordinate Hopf algebra of the standard complete isotropic flag subgroup. -/
noncomputable abbrev coordinateHopfAlgebra : CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

/-- Coordinate restriction from the symplectic group to the isotropic flag subgroup. -/
noncomputable abbrev coordinateMap :
    Symplectic.coordinateHopfAlgebra R m ⟶ coordinateHopfAlgebra R m :=
  CommHopfAlgCat.mkQuotient (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

/-- The closed subgroup scheme of `Sp₂ₘ` of symplectic matrices preserving the standard
complete isotropic flag. -/
noncomputable abbrev groupScheme :=
  CommHopfAlgCat.quotientSpec (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

/-- The closed-subgroup inclusion of the isotropic flag subgroup into the symplectic group. -/
noncomputable abbrev inclusion :=
  CommHopfAlgCat.quotientSpecι (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- A symplectic point belongs to the isotropic flag subgroup precisely when its matrix
is upper triangular after reversing the dual half of the basis. -/
@[simp]
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R) (H := Symplectic.coordinateHopfAlgebra R m)
      (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ↔
      Symplectic.pointsMulEquiv R m (A := A) g ∈ matrixSubgroup m := by
  have hpullback :
      (CommHopfAlgCat.mapPointsFunctor (Symplectic.coordinateMap R m)).app
          (CommAlgCat.of R A) g =
        CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra R (m + m)) (Symplectic.definingHopfIdeal R m)
          (CommAlgCat.of R A) g := by
    rw [CommHopfAlgCat.mapPointsFunctor_app_apply, Symplectic.coordinateMap_def,
      CommHopfAlgCat.quotientPointsHom_apply]
  calc
    _ ↔ (CommHopfAlgCat.mapPointsFunctor (Symplectic.coordinateMap R m)).app
          (CommAlgCat.of R A) g ∈ CommHopfAlgCat.quotientPointsSubgroup
            (GeneralLinear.coordinateHopfAlgebra R (m + m))
            (GeneralLinear.weightParabolicDefiningHopfIdeal R (weights m))
            (CommAlgCat.of R A) := by
      rw [definingHopfIdeal_def]
      exact CommHopfAlgCat.mem_quotientPointsSubgroup_map_iff
        (Symplectic.coordinateMap R m) _ _ g
    _ ↔ (GeneralLinear.pointsMulEquiv (m + m)
          ((CommHopfAlgCat.mapPointsFunctor (Symplectic.coordinateMap R m)).app
            (CommAlgCat.of R A) g) : Matrix _ _ A).BlockTriangular
          (OrderDual.toDual ∘ weights m) :=
      GeneralLinear.mem_weightParabolicDefiningPointsSubgroup_iff_blockTriangular _ _ _
    _ ↔ ((Symplectic.pointsMulEquiv R m (A := A) g).val : Matrix _ _ A).BlockTriangular
          (OrderDual.toDual ∘ weights m) := by
      rw [hpullback, Symplectic.pointsMulEquiv_coe]
    _ ↔ Symplectic.pointsMulEquiv R m (A := A) g ∈ matrixSubgroup m := by
      rw [mem_matrixSubgroup_iff_flagOrder]
      simp only [Matrix.BlockTriangular, Function.comp_apply, OrderDual.toDual_lt_toDual,
        weights_lt_weights_iff]

/-- Identify the defining point subgroup with the flag-preserving symplectic matrices. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ≃* matrixSubgroup m (A := A) :=
  Subgroup.congrOfMapEq (Symplectic.pointsMulEquiv R m (A := A)) <| by
    ext g
    rw [← (Symplectic.pointsMulEquiv R m (A := A)).toMonoidHom_eq_coe,
      Subgroup.mem_map_equiv, mem_definingPointsSubgroup_iff, MulEquiv.apply_symm_apply]

/-- The algebra-valued points of the isotropic flag subgroup are exactly the symplectic
matrices upper triangular in the self-dual flag order. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A) ≃*
      matrixSubgroup m (A := A) :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
      (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)).app
      (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
    (definingPointsSubgroupMulEquiv R m)

/-- The quotient-point inclusion agrees with the inclusion of flag-preserving symplectic
matrices. -/
@[simp]
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) :
    Symplectic.pointsMulEquiv R m (A := A)
        (CommHopfAlgCat.quotientPointsHom
          (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
          (CommAlgCat.of R A) f) =
      (pointsMulEquiv R m (A := A) f : GLSymplecticFin m A) := by
  have h := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m) (CommAlgCat.of R A) f
  calc
    _ = Symplectic.pointsMulEquiv R m (A := A)
          (((CommHopfAlgCat.quotientPointsSubgroupNatIso
            (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)).app
            (CommAlgCat.of R A)).hom f).val :=
      (congrArg (fun g ↦ Symplectic.pointsMulEquiv R m (A := A) g.val) h).symm
    _ = _ := (Subgroup.coe_congrOfMapEq_apply _ _ _).symm

/-- The ambient point of a flag-preserving matrix is the symplectic point of that matrix. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm (g : matrixSubgroup m (A := A)) :
    CommHopfAlgCat.quotientPointsHom
        (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ((pointsMulEquiv R m (A := A)).symm g) =
      (Symplectic.pointsMulEquiv R m (A := A)).symm g.val := by
  apply (Symplectic.pointsMulEquiv R m (A := A)).injective
  rw [pointsMulEquiv_coe, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type v} [CommRing B] [Algebra R B]

/-- The flag-subgroup point equivalence is natural in the value algebra. -/
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) :
    pointsMulEquiv R m (A := B) (AlgHom.mapValue phi f) =
      GLSymplecticFin.IsotropicFlag.map m (phi : A →+* B)
        (pointsMulEquiv R m (A := A) f) := by
  apply Subtype.ext
  rw [GLSymplecticFin.IsotropicFlag.coe_map,
    ← pointsMulEquiv_coe, ← CommHopfAlgCat.mapValue_quotientPointsHom,
    Symplectic.pointsMulEquiv_mapValue, pointsMulEquiv_coe]

/-- The inverse flag-subgroup point equivalence is natural in the value algebra. -/
theorem mapValue_pointsMulEquiv_symm_apply (phi : A →ₐ[R] B)
    (g : matrixSubgroup m (A := A)) :
    AlgHom.mapValue phi ((pointsMulEquiv R m (A := A)).symm g) =
      (pointsMulEquiv R m (A := B)).symm
        (GLSymplecticFin.IsotropicFlag.map m (phi : A →+* B) g) := by
  apply (pointsMulEquiv R m (A := B)).injective
  rw [pointsMulEquiv_mapValue, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

/-- Every algebra-valued point group of the isotropic flag subgroup is solvable. -/
theorem isSolvable_points :
    Group.IsSolvable
      (HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) := by
  exact Group.isSolvable_of_isSolvable_injective
    (f := (pointsMulEquiv R m (A := A)).toMonoidHom)
    (pointsMulEquiv R m (A := A)).injective

end Points



/-- The isotropic flag subgroup has solvable geometric points over every field. -/
theorem geometricallySolvablePointsCommHopfAlgProperty_coordinateHopfAlgebra
    (k : Type u) [Field k] :
    geometricallySolvablePointsCommHopfAlgProperty k (coordinateHopfAlgebra k m) := by
  rw [geometricallySolvablePointsCommHopfAlgProperty_iff]
  exact isSolvable_points k m

end TauCeti.Symplectic.IsotropicFlag
