/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.ProP.MaximalSubgroup
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicInt.Basic
import Mathlib.Topology.Separation.Connected

/-!
# Topological generators of a procyclic pro-`p` group

A pro-`p` group `P` topologically generated by a single element `a` is *procyclic*, and every
element of `P` is a `p`-adic power `a ^ l` with `l ∈ ℤ_[p]`
(`TauCeti.IsProP.mem_topologicalClosure_closure_singleton_iff`). This file identifies which of
those powers again generate: for `P` nontrivial, `a ^ u` topologically generates `P` exactly when
`u` is a unit of `ℤ_[p]`, the non-unit powers lying in the pro-`p` Frattini subgroup. Consequently
any two topological generators of a procyclic pro-`p` group differ by a unit exponent. A
procyclic pro-`p` group is `ℤ/pᵏ` when its generator has finite order, and otherwise the `p`-adic
power map of the generator is injective, so the group is a copy of `ℤ_p`
(`TauCeti.freeProP.nonempty_continuousMulEquiv_of_not_isOfFinOrder`, in
`TauCeti.Topology.Algebra.Group.Profinite.Free.PadicInt`).

This is the change-of-generator statement behind the power-series coordinates of the completed
group algebra `ℤ_p[[P]]` of an infinite procyclic pro-`p` group: the coordinates attached to two
topological generators `a` and `a ^ u` differ by the substitution `X ↦ (1 + X) ^ u - 1`.

## Main results

* `TauCeti.IsProP.topologicalClosure_closure_padicPow_eq_top_iff`: if `a` topologically
  generates the nontrivial pro-`p` group `P`, then `a ^ u` does so exactly when `u` is a unit.
* `TauCeti.IsProP.exists_isUnit_padicPow_eq_of_topologicalClosure_closure_eq_top`: two
  topological generators of a procyclic pro-`p` group differ by a unit exponent.
* `TauCeti.IsProP.padicPowHom_injective_of_not_isOfFinOrder`,
  `TauCeti.IsProP.padicPow_right_injective_of_not_isOfFinOrder`: the `p`-adic power map
  `l ↦ a ^ l` is injective when `a` has infinite order.
* `TauCeti.IsProP.padicPowEquiv`: for a topological generator `a` of infinite order, the
  `p`-adic power map `l ↦ a ^ l` is a topological group isomorphism `Multiplicative ℤ_[p] ≃ₜ* P`.
* `TauCeti.IsProP.exists_continuousMulEquiv_multiplicative_zmod_pow_of_isOfFinOrder`: a pro-`p`
  group topologically generated by an element `a` of finite order is topologically isomorphic to a
  finite cyclic group `ℤ/pᵏ`, by an isomorphism carrying `a` to the generator `1`.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Section 4.3.
-/

public section

namespace TauCeti.IsProP

variable {p : ℕ} [Fact p.Prime] {P : Type*} [Group P] [TopologicalSpace P]
  [IsTopologicalGroup P] [CompactSpace P] [TotallyDisconnectedSpace P]

/-- **A `p`-adic power with exponent divisible by `p` lies in the pro-`p` Frattini subgroup.** -/
theorem padicPow_mem_proPFrattini_of_dvd (hP : IsProP p P) {l : ℤ_[p]} (hl : (p : ℤ_[p]) ∣ l)
    (a : P) : hP.padicPow a l ∈ proPFrattini p P := by
  obtain ⟨m, rfl⟩ := hl
  rw [hP.padicPow_mul, hP.padicPow_natCast]
  exact hP.padicPow_mem isClosed_proPFrattini (pow_mem_proPFrattini a) m

/-- **A unit power of a topological generator is a topological generator, and nothing else is.**
If `a` topologically generates the nontrivial pro-`p` group `P`, then the `p`-adic power `a ^ u`
topologically generates `P` if and only if `u` is a unit of `ℤ_[p]`. -/
theorem topologicalClosure_closure_padicPow_eq_top_iff [Nontrivial P] (hP : IsProP p P) {a : P}
    (ha : (Subgroup.closure ({a} : Set P)).topologicalClosure = ⊤) (u : ℤ_[p]) :
    (Subgroup.closure ({hP.padicPow a u} : Set P)).topologicalClosure = ⊤ ↔ IsUnit u := by
  constructor
  · intro h
    by_contra hu
    -- A non-unit is `p * w`, so `a ^ u = (a ^ w) ^ p` lies in the closed proper Frattini subgroup.
    have hmem : hP.padicPow a u ∈ proPFrattini p P :=
      hP.padicPow_mem_proPFrattini_of_dvd
        ((PadicInt.norm_lt_one_iff_dvd u).mp (PadicInt.not_isUnit_iff.mp hu)) a
    refine hP.proPFrattini_ne_top (top_le_iff.mp (h ▸ ?_))
    exact Subgroup.topologicalClosure_minimal _
      ((Subgroup.closure_le _).mpr (Set.singleton_subset_iff.mpr hmem)) isClosed_proPFrattini
  · rintro ⟨u, rfl⟩
    simpa only [closedZpowers_def, Subgroup.zpowers_eq_closure, ha] using
      hP.closedZpowers_padicPow a u

/-- **Two topological generators of a procyclic pro-`p` group differ by a unit exponent**: if
`a` and `b` both topologically generate `P`, then `b = a ^ u` for a unit `u` of `ℤ_[p]`. -/
theorem exists_isUnit_padicPow_eq_of_topologicalClosure_closure_eq_top (hP : IsProP p P)
    {a b : P} (ha : (Subgroup.closure ({a} : Set P)).topologicalClosure = ⊤)
    (hb : (Subgroup.closure ({b} : Set P)).topologicalClosure = ⊤) :
    ∃ u : ℤ_[p], IsUnit u ∧ hP.padicPow a u = b := by
  rcases subsingleton_or_nontrivial P with _ | _
  · exact ⟨1, isUnit_one, Subsingleton.elim _ _⟩
  obtain ⟨u, rfl⟩ :=
    hP.mem_topologicalClosure_closure_singleton_iff.mp (ha ▸ Subgroup.mem_top b)
  exact ⟨u, (hP.topologicalClosure_closure_padicPow_eq_top_iff ha u).mp hb, rfl⟩

/-! ### Injectivity of the `p`-adic power map, and finite procyclic groups -/

/-- **The `p`-adic power map of an element of infinite order is injective**: if `a ^ l = 1` then
`l = 0`, since no `a ^ (pᵛ)` is `1` (`TauCeti.IsProP.eq_zero_of_padicPow_mem`). -/
theorem padicPowHom_injective_of_not_isOfFinOrder (hP : IsProP p P) {a : P}
    (ha : ¬ IsOfFinOrder a) : Function.Injective (hP.padicPowHom a) := by
  rw [injective_iff_map_eq_one]
  intro l hl
  rw [padicPowHom_apply] at hl
  -- The trivial subgroup is closed and contains no `a ^ (pᵛ)`, so the exponent of `a ^ l = 1`
  -- is `0`.
  have h0 : Multiplicative.toAdd l = 0 :=
    hP.eq_zero_of_padicPow_mem (H := ⊥) (by rw [Subgroup.coe_bot]; exact isClosed_singleton)
      (fun v hv ↦ ha (isOfFinOrder_iff_pow_eq_one.2
        ⟨p ^ v, pow_pos (Fact.out : p.Prime).pos v, Subgroup.mem_bot.1 hv⟩))
      (Subgroup.mem_bot.2 hl)
  rw [← ofAdd_toAdd l, h0, ofAdd_zero]

/-- **The `p`-adic exponent of an element of infinite order is determined by the power**: for `a`
of infinite order, `a ^ l = a ^ l'` forces `l = l'`. -/
theorem padicPow_right_injective_of_not_isOfFinOrder (hP : IsProP p P) {a : P}
    (ha : ¬ IsOfFinOrder a) : Function.Injective (hP.padicPow a) := fun l l' h ↦
  Multiplicative.ofAdd.injective (hP.padicPowHom_injective_of_not_isOfFinOrder ha
    (a₁ := Multiplicative.ofAdd l) (a₂ := Multiplicative.ofAdd l') (by simpa using h))

/-- The `p`-adic power map of a topological generator `a` of infinite order is bijective: it is
injective by `TauCeti.IsProP.padicPowHom_injective_of_not_isOfFinOrder`, and its range is the
closed subgroup generated by `a`. -/
theorem padicPowHom_bijective_of_not_isOfFinOrder (hP : IsProP p P) {a : P}
    (ha : (Subgroup.closure ({a} : Set P)).topologicalClosure = ⊤) (hfin : ¬ IsOfFinOrder a) :
    Function.Bijective (hP.padicPowHom a) := by
  refine ⟨hP.padicPowHom_injective_of_not_isOfFinOrder hfin, fun x ↦ ?_⟩
  rw [hP.topologicalClosure_closure_singleton_eq_range_padicPowHom] at ha
  exact MonoidHom.range_eq_top.mp ha x

/-- **A procyclic pro-`p` group with a generator of infinite order is a copy of `ℤ_p`.** If `a`
topologically generates the pro-`p` group `P` and has infinite order, the `p`-adic power map
`l ↦ a ^ l` is a topological group isomorphism from the additive group of `ℤ_[p]` onto `P`,
sending `1` to `a`. -/
noncomputable def padicPowEquiv (hP : IsProP p P) {a : P}
    (ha : (Subgroup.closure ({a} : Set P)).topologicalClosure = ⊤) (hfin : ¬ IsOfFinOrder a) :
    Multiplicative ℤ_[p] ≃ₜ* P :=
  have hb := hP.padicPowHom_bijective_of_not_isOfFinOrder ha hfin
  (MulEquiv.ofBijective _ hb).toContinuousMulEquiv fun _ ↦
    ((hP.padicPowHom a).continuous.homeoOfEquivCompactToT2
      (f := (MulEquiv.ofBijective _ hb).toEquiv)).isOpen_preimage

/-- The isomorphism `TauCeti.IsProP.padicPowEquiv` is the `p`-adic power map of the generator. -/
@[simp]
theorem padicPowEquiv_apply (hP : IsProP p P) {a : P}
    (ha : (Subgroup.closure ({a} : Set P)).topologicalClosure = ⊤) (hfin : ¬ IsOfFinOrder a)
    (l : Multiplicative ℤ_[p]) : hP.padicPowEquiv ha hfin l = hP.padicPow a l.toAdd :=
  hP.padicPowHom_apply a l

/-- The inverse of `TauCeti.IsProP.padicPowEquiv` returns the `p`-adic exponent of an element
with respect to the generator. -/
@[simp]
theorem padicPow_padicPowEquiv_symm (hP : IsProP p P) {a : P}
    (ha : (Subgroup.closure ({a} : Set P)).topologicalClosure = ⊤) (hfin : ¬ IsOfFinOrder a)
    (x : P) : hP.padicPow a ((hP.padicPowEquiv ha hfin).symm x).toAdd = x := by
  rw [← padicPowEquiv_apply hP ha hfin, ContinuousMulEquiv.apply_symm_apply]

omit [CompactSpace P] in
/-- **A pro-`p` group topologically generated by an element `a` of finite order is a finite
cyclic `p`-group**, hence topologically isomorphic to `ℤ/pᵏ` for some `k` by an isomorphism
carrying `a` to the generator `1`: the cyclic subgroup generated by `a` is finite, hence closed, so
it is the whole group. -/
theorem exists_continuousMulEquiv_multiplicative_zmod_pow_of_isOfFinOrder (hP : IsProP p P)
    {a : P} (ha : (Subgroup.closure ({a} : Set P)).topologicalClosure = ⊤)
    (hfin : IsOfFinOrder a) :
    ∃ k : ℕ, ∃ e : P ≃ₜ* Multiplicative (ZMod (p ^ k)), e a = Multiplicative.ofAdd 1 := by
  have hfinite : Finite (Subgroup.zpowers a) := finite_zpowers.2 hfin
  have hz : Subgroup.zpowers a = ⊤ := by
    rw [← (Set.finite_coe_iff.1 hfinite).isClosed.subgroup_topologicalClosure_eq,
      Subgroup.zpowers_eq_closure, ha]
  have hgen : ∀ x, x ∈ Subgroup.zpowers a := fun x ↦ hz ▸ Subgroup.mem_top x
  have : Finite P := Finite.of_surjective (fun x : Subgroup.zpowers a ↦ (x : P))
    fun x ↦ ⟨⟨x, hgen x⟩, rfl⟩
  obtain ⟨k, hk⟩ := IsPGroup.iff_card.1 (isProP_iff_isPGroup.1 hP)
  exact ⟨k, (zmodMulEquivOfGenerator hgen hk).symm.toContinuousMulEquiv
    fun _ ↦ ⟨fun _ ↦ isOpen_discrete _, fun _ ↦ isOpen_discrete _⟩,
    zmodMulEquivOfGenerator_symm_apply_generator hgen hk⟩

end TauCeti.IsProP
