/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Module.Opposite
public import Mathlib.LinearAlgebra.TensorProduct.Basic
public import Mathlib.LinearAlgebra.Quotient.Basic

/-!
# Tensor products over a noncommutative algebra

For a right `A`-module `M` and a left `A`-module `N`, both modules over a commutative
ring `k`, the balanced tensor product is the quotient of `M ⊗[k] N` by the relations
`(m a) ⊗ n - m ⊗ (a n)`. Right actions are represented by `Module Aᵐᵒᵖ M`.

The universal property identifies linear maps out of this quotient with balanced
`k`-bilinear maps. Pure tensors, induction, extensionality, and functoriality let
consumers work without unfolding the quotient. This is the underlying module
construction for tensoring bimodules and differential graded modules. It is not a
derived tensor product.

The quotient uses Mathlib's `TensorProduct` and `Submodule.liftQ`. The mathematical
construction is the ordinary tensor product used in Keller, *Deriving DG categories*,
Section 6.1.
-/

public section

namespace TauCeti

open MulOpposite
open scoped TensorProduct

variable (k A M N : Type*) [CommRing k] [Semiring A]
  [AddCommGroup M] [Module k M] [Module Aᵐᵒᵖ M]
  [AddCommGroup N] [Module k N] [Module A N]

/-- The submodule generated by the relations moving an `A` action across a tensor. -/
def balancedTensorRelations : Submodule k (M ⊗[k] N) :=
  Submodule.span k {z | ∃ (a : A) (m : M) (n : N),
    z = (op a • m) ⊗ₜ[k] n - m ⊗ₜ[k] (a • n)}

/-- The balancing submodule is spanned by the elementary balancing relations. -/
theorem balancedTensorRelations_def : balancedTensorRelations k A M N =
    Submodule.span k {z | ∃ (a : A) (m : M) (n : N),
      z = (op a • m) ⊗ₜ[k] n - m ⊗ₜ[k] (a • n)} := (rfl)

/-- The tensor product of a right `A`-module and a left `A`-module, balanced over `A`
and linear over `k`. Compatible scalar actions give the usual algebra-relative tensor product. -/
-- Expose the quotient carrier so inherited gradings can use the canonical quotient instances.
@[expose]
def BalancedTensorProduct := (M ⊗[k] N) ⧸ balancedTensorRelations k A M N

namespace BalancedTensorProduct

instance : AddCommGroup (BalancedTensorProduct k A M N) :=
  inferInstanceAs (AddCommGroup ((M ⊗[k] N) ⧸ balancedTensorRelations k A M N))

instance : Module k (BalancedTensorProduct k A M N) :=
  inferInstanceAs (Module k ((M ⊗[k] N) ⧸ balancedTensorRelations k A M N))

variable {M N}

/-- The quotient map from the tensor product over the ground ring. -/
def mkQ : M ⊗[k] N →ₗ[k] BalancedTensorProduct k A M N :=
  (balancedTensorRelations k A M N).mkQ

/-- The balanced quotient map is the submodule quotient map. -/
theorem mkQ_def : mkQ k A (M := M) (N := N) =
    (balancedTensorRelations k A M N).mkQ := (rfl)

/-- The canonical bilinear map to the balanced tensor product. -/
def mk : M →ₗ[k] N →ₗ[k] BalancedTensorProduct k A M N :=
  (TensorProduct.mk k M N).compr₂ (mkQ k A)

/-- The canonical bilinear map is the ground-ring tensor map followed by the quotient. -/
theorem mk_def : mk k A (M := M) (N := N) =
    (TensorProduct.mk k M N).compr₂ (mkQ k A) := (rfl)

/-- A pure tensor in the balanced tensor product. -/
def tmul (m : M) (n : N) : BalancedTensorProduct k A M N := mk k A m n

@[simp]
theorem mk_apply (m : M) (n : N) : mk k A m n = tmul k A m n := (rfl)

@[simp]
theorem mkQ_tmul (m : M) (n : N) : mkQ k A (m ⊗ₜ[k] n) = tmul k A m n := (rfl)

/-- A ground-ring tensor vanishes in the quotient exactly when it lies in the span of
balancing relations. -/
@[simp]
theorem mkQ_eq_zero_iff (z : M ⊗[k] N) :
    mkQ k A z = 0 ↔ z ∈ balancedTensorRelations k A M N :=
  Submodule.Quotient.mk_eq_zero _

@[simp]
theorem zero_tmul (n : N) : tmul k A (0 : M) n = 0 := by
  simp only [tmul, map_zero, LinearMap.zero_apply]

@[simp]
theorem tmul_zero (m : M) : tmul k A m (0 : N) = 0 := by
  simp only [tmul, map_zero]

theorem add_tmul (m m' : M) (n : N) :
    tmul k A (m + m') n = tmul k A m n + tmul k A m' n := by
  simp only [tmul, map_add, LinearMap.add_apply]

theorem tmul_add (m : M) (n n' : N) :
    tmul k A m (n + n') = tmul k A m n + tmul k A m n' := by
  simp only [tmul, map_add]

@[simp]
theorem smul_tmul (r : k) (m : M) (n : N) :
    tmul k A (r • m) n = r • tmul k A m n := by
  simp only [tmul, map_smul, LinearMap.smul_apply]

@[simp]
theorem tmul_smul (r : k) (m : M) (n : N) :
    tmul k A m (r • n) = r • tmul k A m n := by
  simp only [tmul, map_smul]

/-- An `A` action can be moved from the right module to the left module. -/
theorem balance (a : A) (m : M) (n : N) :
    tmul k A (op a • m) n = tmul k A m (a • n) := by
  apply sub_eq_zero.mp
  rw [← mkQ_tmul, ← mkQ_tmul, ← map_sub]
  exact (Submodule.Quotient.mk_eq_zero _).mpr
    (Submodule.subset_span ⟨a, m, n, rfl⟩)

/-- Every balanced tensor is represented by a ground-ring tensor. -/
theorem mkQ_surjective : Function.Surjective (mkQ k A (M := M) (N := N)) :=
  (balancedTensorRelations k A M N).mkQ_surjective

/-- Induction on balanced tensors by pure tensors and addition. -/
@[elab_as_elim]
theorem induction_on {P : BalancedTensorProduct k A M N → Prop}
    (x : BalancedTensorProduct k A M N)
    (ht : ∀ m n, P (tmul k A m n))
    (ha : ∀ x y, P x → P y → P (x + y)) : P x := by
  obtain ⟨z, rfl⟩ := mkQ_surjective k A x
  induction z using TensorProduct.inductionOn with
  | tmul m n => exact ht m n
  | add x y hx hy => simpa using ha _ _ hx hy

variable {k A} {P : Type*} [AddCommGroup P] [Module k P]

/-- Linear maps out of a balanced tensor product agree if they agree on pure tensors. -/
@[ext high]
theorem hom_ext {f g : BalancedTensorProduct k A M N →ₗ[k] P}
    (h : ∀ m n, f (tmul k A m n) = g (tmul k A m n)) : f = g := by
  apply LinearMap.ext
  intro x
  induction x using induction_on with
  | ht m n => exact h m n
  | ha x y hx hy => simp [hx, hy]

/-- Lift a balanced bilinear map through the tensor product. -/
def lift (f : M →ₗ[k] N →ₗ[k] P)
    (hf : ∀ (a : A) m n, f (op a • m) n = f m (a • n)) :
    BalancedTensorProduct k A M N →ₗ[k] P :=
  (balancedTensorRelations k A M N).liftQ (TensorProduct.lift f) (by
    rw [balancedTensorRelations, Submodule.span_le]
    rintro z ⟨a, m, n, rfl⟩
    simp [LinearMap.mem_ker, hf])

@[simp]
theorem lift_tmul (f : M →ₗ[k] N →ₗ[k] P)
    (hf : ∀ (a : A) m n, f (op a • m) n = f m (a • n)) (m : M) (n : N) :
    lift f hf (tmul k A m n) = f m n := (rfl)

/-- The universal property: balanced bilinear maps are precisely linear maps out of
the balanced tensor product. -/
def liftEquiv :
    {f : M →ₗ[k] N →ₗ[k] P // ∀ (a : A) m n, f (op a • m) n = f m (a • n)} ≃
      (BalancedTensorProduct k A M N →ₗ[k] P) where
  toFun f := lift f.1 f.2
  invFun g := ⟨(mk k A).compr₂ g, fun a m n ↦ congrArg g (balance k A a m n)⟩
  left_inv f := by ext m n; rfl
  right_inv g := hom_ext fun _ _ ↦ rfl

@[simp]
theorem liftEquiv_apply (f :
    {f : M →ₗ[k] N →ₗ[k] P // ∀ (a : A) m n, f (op a • m) n = f m (a • n)}) :
    liftEquiv f = lift f.1 f.2 := (rfl)

@[simp]
theorem liftEquiv_symm_apply (g : BalancedTensorProduct k A M N →ₗ[k] P) (m : M) (n : N) :
    (liftEquiv.symm g).1 m n = g (tmul k A m n) := (rfl)

section Map

variable {M' N' M'' N'' : Type*}
  [AddCommGroup M'] [Module k M'] [Module Aᵐᵒᵖ M']
  [AddCommGroup N'] [Module k N'] [Module A N']
  [AddCommGroup M''] [Module k M''] [Module Aᵐᵒᵖ M'']
  [AddCommGroup N''] [Module k N''] [Module A N'']

/-- The map induced by equivariant ground-ring linear maps in both factors. -/
def map (f : M →ₗ[k] M') (g : N →ₗ[k] N')
    (hf : ∀ (a : A) m, f (op a • m) = op a • f m)
    (hg : ∀ (a : A) n, g (a • n) = a • g n) :
    BalancedTensorProduct k A M N →ₗ[k] BalancedTensorProduct k A M' N' :=
  lift (((mk k A).comp f).compl₂ g) (fun a m n ↦ by
    simp only [LinearMap.compl₂_apply, LinearMap.comp_apply, mk_apply, hf, hg]
    exact balance k A a (f m) (g n))

@[simp]
theorem map_tmul (f : M →ₗ[k] M') (g : N →ₗ[k] N')
    (hf : ∀ (a : A) m, f (op a • m) = op a • f m)
    (hg : ∀ (a : A) n, g (a • n) = a • g n) (m : M) (n : N) :
    map f g hf hg (tmul k A m n) = tmul k A (f m) (g n) := (rfl)

@[simp]
theorem map_id : map (A := A) (LinearMap.id : M →ₗ[k] M) (LinearMap.id : N →ₗ[k] N)
    (fun _ _ ↦ rfl) (fun _ _ ↦ rfl) = LinearMap.id :=
  hom_ext fun _ _ ↦ rfl

/-- Tensoring respects composition of equivariant maps. -/
theorem map_comp (f : M →ₗ[k] M') (g : N →ₗ[k] N')
    (f' : M' →ₗ[k] M'') (g' : N' →ₗ[k] N'')
    (hf : ∀ (a : A) m, f (op a • m) = op a • f m)
    (hg : ∀ (a : A) n, g (a • n) = a • g n)
    (hf' : ∀ (a : A) m, f' (op a • m) = op a • f' m)
    (hg' : ∀ (a : A) n, g' (a • n) = a • g' n) :
    map (f'.comp f) (g'.comp g)
        (fun a m ↦ by simp [hf, hf']) (fun a n ↦ by simp [hg, hg']) =
      (map f' g' hf' hg').comp (map f g hf hg) :=
  hom_ext fun _ _ ↦ rfl

/-- Equivariant linear equivalences of the factors identify their balanced tensor products. -/
def congr (f : M ≃ₗ[k] M') (g : N ≃ₗ[k] N')
    (hf : ∀ (a : A) m, f (op a • m) = op a • f m)
    (hg : ∀ (a : A) n, g (a • n) = a • g n) :
    BalancedTensorProduct k A M N ≃ₗ[k] BalancedTensorProduct k A M' N' :=
  LinearEquiv.ofLinearMap (map f.toLinearMap g.toLinearMap hf hg)
    (map f.symm.toLinearMap g.symm.toLinearMap
      (fun a m ↦ by
        apply f.injective
        simpa only [LinearEquiv.coe_coe, LinearEquiv.apply_symm_apply] using
          (hf a (f.symm m)).symm)
      (fun a n ↦ by
        apply g.injective
        simpa only [LinearEquiv.coe_coe, LinearEquiv.apply_symm_apply] using
          (hg a (g.symm n)).symm))
    (by
      apply hom_ext
      intro m n
      simp)
    (by
      apply hom_ext
      intro m n
      simp)

@[simp]
theorem congr_tmul (f : M ≃ₗ[k] M') (g : N ≃ₗ[k] N')
    (hf : ∀ (a : A) m, f (op a • m) = op a • f m)
    (hg : ∀ (a : A) n, g (a • n) = a • g n) (m : M) (n : N) :
    congr f g hf hg (tmul k A m n) = tmul k A (f m) (g n) := (rfl)

@[simp]
theorem congr_symm_tmul (f : M ≃ₗ[k] M') (g : N ≃ₗ[k] N')
    (hf : ∀ (a : A) m, f (op a • m) = op a • f m)
    (hg : ∀ (a : A) n, g (a • n) = a • g n) (m : M') (n : N') :
    (congr f g hf hg).symm (tmul k A m n) = tmul k A (f.symm m) (g.symm n) := (rfl)

end Map

end BalancedTensorProduct

end TauCeti
