/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Order
public import TauCeti.Algebra.AlgebraicGroup.Orthogonal.Basic
public import TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Basic
public import TauCeti.LinearAlgebra.Matrix.SpecialOrthogonalGroup.Basic
import TauCeti.CategoryTheory.Comma.Over

/-!
# The special orthogonal subgroup scheme of `GLₙ`

For a commutative ring `R` and `n : ℕ`, the special orthogonal subgroup scheme `SOₙ` is cut out
of `GL n` by the join of two Hopf ideals that already exist:

* the orthogonal Hopf ideal, generated by the entries of `X Xᵀ - 1`
  (`TauCeti.Orthogonal.definingHopfIdeal`), and
* the determinant kernel, the principal ideal generated by `det X - 1`
  (`TauCeti.SpecialLinear.definingHopfIdeal`).

No new closure computation is needed: the join of Hopf ideals is a Hopf ideal, and its quotient
imposes both families of relations at once — on points, the intersection `Oₙ ∩ SLₙ` inside
`GL n`. On every commutative `R`-algebra `A`, the group of points is Mathlib's group
`Matrix.specialOrthogonalGroup (Fin n) A` of orthogonal matrices of determinant one, because a
point vanishes on the join exactly when it vanishes on both joinands
(`TauCeti.CommHopfAlgCat.quotientPointsSubgroup_sup`), and the two ambient membership criteria
are already identified with orthogonality and determinant one.

As with the orthogonal construction, this is the special orthogonal group of the **standard
symmetric bilinear form**: the scheme of the functor `A ↦ {M | M Mᵀ = 1, det M = 1}` over every
commutative ring. In characteristic two the quadratic-form special orthogonal group (cut out by
the Dickson invariant rather than the determinant) differs from this determinant-one cut, and
smoothness becomes sensitive to the rank and regularity of the form; no smoothness is claimed
here, so the construction is stated over an arbitrary commutative ring without restriction.
This completes the construction-and-points boundary of the `SOₙ` worked example of the
ReductiveGroups roadmap, at the same stage as the symplectic example: construction and points
identification, with no smoothness or reductivity claim.

## Main declarations

* `TauCeti.SpecialOrthogonal.definingHopfIdeal`: the join of the orthogonal Hopf ideal and the
  determinant kernel.
* `TauCeti.SpecialOrthogonal.coordinateHopfAlgebra`: the special orthogonal coordinate Hopf
  algebra, the quotient by the defining Hopf ideal.
* `TauCeti.SpecialOrthogonal.groupScheme` and `TauCeti.SpecialOrthogonal.inclusion`: the special
  orthogonal subgroup scheme and its closed immersion into the general linear group scheme.
* `TauCeti.SpecialOrthogonal.pointsMulEquiv`: the group of algebra-valued points of the special
  orthogonal coordinate Hopf algebra is `Matrix.specialOrthogonalGroup (Fin n) A`.
* `TauCeti.SpecialOrthogonal.pointsMulEquiv_mapValue`: this points identification is natural in
  the value algebra.

## References

* J. S. Milne, *Algebraic Groups* (2017), §2.3, where `SOₙ` appears among the basic examples of
  algebraic groups as the intersection of `Oₙ` with `SLₙ` inside `GLₙ`.
* The Stacks Project, [Tag 022W](https://stacks.math.columbia.edu/tag/022W), for the ambient
  general linear group scheme.

The construction is assembled entirely from the orthogonal and special-linear Hopf ideals of
`TauCeti.Orthogonal` and `TauCeti.SpecialLinear` through the Hopf-ideal join.
-/

public section

open CategoryTheory Matrix WithConv

namespace TauCeti.SpecialOrthogonal

universe u v w

variable (R : Type u) [CommRing R] (n : ℕ)

/-! ### The defining Hopf ideal and quotient -/

/-- **The special orthogonal Hopf ideal**: the join of the orthogonal Hopf ideal and the
determinant kernel in the coordinate Hopf algebra of `GL n`. -/
noncomputable def definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R n) :=
  Orthogonal.definingHopfIdeal R n ⊔ SpecialLinear.definingHopfIdeal R n

/-- The underlying ideal of the special orthogonal Hopf ideal is generated by the orthogonality
relations together with the localized generic determinant minus one. -/
@[simp]
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R n).toIdeal =
      Ideal.span (Orthogonal.relationSet R n) ⊔
        Ideal.span
          {(GeneralLinear.determinantGroupLike R n :
              GeneralLinear.coordinateHopfAlgebra R n) - 1} := by
  rw [definingHopfIdeal, HopfIdeal.sup_toIdeal, ConstantForm.definingHopfIdeal_toIdeal,
    SpecialLinear.definingHopfIdeal_toIdeal]

/-- The coordinate Hopf algebra of the special orthogonal subgroup scheme of `GL n`. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The quotient coordinate morphism from `O(GL n)` to the special orthogonal coordinate Hopf
algebra. -/
noncomputable def coordinateMap :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ coordinateHopfAlgebra R n :=
  CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The special orthogonal coordinate morphism is the quotient by its defining Hopf ideal. -/
theorem coordinateMap_def :
    coordinateMap R n =
      CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R n)
        (definingHopfIdeal R n) := by
  rw [coordinateMap]

/-- The special orthogonal coordinate morphism sends an ambient coordinate to its quotient
class. -/
theorem coordinateMap_apply (h : GeneralLinear.coordinateHopfAlgebra R n) :
    (coordinateMap R n).hom h =
      Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal h := by
  unfold coordinateMap
  exact CommHopfAlgCat.mkQuotient_apply
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n) h

/-- Every orthogonality relation vanishes in the special orthogonal coordinate Hopf algebra. -/
@[simp]
theorem coordinateMap_relationMatrix (i j : Fin n) :
    (coordinateMap R n).hom (Orthogonal.relationMatrix R n i j) = 0 := by
  rw [coordinateMap_apply, Ideal.Quotient.mkₐ_eq_mk]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr
    (definingHopfIdeal_toIdeal R n ▸
      Ideal.mem_sup_left
        (Ideal.subset_span (ConstantForm.relationMatrix_mem_relationSet R n 1 i j)))

/-- The generic determinant maps to one in the special orthogonal coordinate Hopf algebra. -/
@[simp↓]
theorem coordinateMap_determinantGroupLike :
    (coordinateMap R n).hom (GeneralLinear.determinantGroupLike R n) = 1 := by
  rw [coordinateMap_apply]
  apply sub_eq_zero.mp
  rw [← map_one (Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal), ← map_sub,
    Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem, definingHopfIdeal_toIdeal]
  exact Ideal.mem_sup_right (Ideal.subset_span rfl)

/-- The special orthogonal subgroup scheme of `GL n`. -/
noncomputable def groupScheme :=
  CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The quotient-spectrum presentation of the special orthogonal group scheme. -/
private noncomputable def groupSchemeι :=
  CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The closed-subgroup inclusion from the special orthogonal subgroup scheme into the named
general linear group scheme. -/
noncomputable def inclusion : groupScheme R n ⟶ GeneralLinear.groupScheme R n :=
  groupSchemeι R n ≫ (eqToIso (GeneralLinear.groupScheme_def R n).symm).hom

private theorem inclusion_hom_left :
    (inclusion R n).hom.hom.left =
      (CommHopfAlgCat.quotientSpecι
        (GeneralLinear.coordinateHopfAlgebra R n)
        (definingHopfIdeal R n)).hom.hom.left ≫
      ((eqToIso (GeneralLinear.groupScheme_def R n).symm).hom).hom.hom.left := by
  rw [inclusion]
  unfold groupSchemeι
  rfl

/-- The special orthogonal inclusion into the named general linear group scheme is a closed
immersion. -/
instance isClosedImmersion_inclusion :
    AlgebraicGeometry.IsClosedImmersion (inclusion R n).hom.hom.left := by
  let c := (CommHopfAlgCat.quotientSpecι
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).hom.hom.left
  let e₂ := ((eqToIso (GeneralLinear.groupScheme_def R n).symm).hom).hom.hom.left
  have hc : AlgebraicGeometry.IsClosedImmersion c := by
    infer_instance
  have hc₂ : AlgebraicGeometry.IsClosedImmersion (c ≫ e₂) :=
    (MorphismProperty.cancel_right_of_respectsIso _ c e₂).2 hc
  rw [inclusion_hom_left]
  exact hc₂

/-- The special orthogonal coordinate Hopf algebra, bundled with its finite-type property. -/
noncomputable def finiteTypeCoordinateHopfAlgebra : FiniteTypeCommHopfAlgCat R :=
  FiniteTypeCommHopfAlgCat.quotient
    (⟨GeneralLinear.coordinateHopfAlgebra R n, by
      rw [← GeneralLinear.finiteTypeCoordinateHopfAlgebra_obj]
      exact (GeneralLinear.finiteTypeCoordinateHopfAlgebra R n).property⟩ :
      FiniteTypeCommHopfAlgCat R)
    (definingHopfIdeal R n)

/-- The finite-type package has the special orthogonal coordinate Hopf algebra as its underlying
object. -/
@[simp]
theorem finiteTypeCoordinateHopfAlgebra_obj :
    (finiteTypeCoordinateHopfAlgebra R n).obj = coordinateHopfAlgebra R n := by
  rw [finiteTypeCoordinateHopfAlgebra]

/-- The structural morphism of the special orthogonal subgroup scheme is locally of finite
type. -/
instance locallyOfFiniteType_groupScheme :
    AlgebraicGeometry.LocallyOfFiniteType (groupScheme R n).X.hom := by
  unfold groupScheme
  infer_instance

/-! ### Algebra-valued points -/

section Points

-- `Matrix.specialOrthogonalGroup` reads the transpose as a `star`, through the trivial star
-- structure on the commutative coefficient ring, exactly as in
-- `Mathlib.LinearAlgebra.UnitaryGroup`.
attribute [local instance] starRingOfComm

variable {A : Type w} [CommRing A] [Algebra R A]

/-- An ambient point belongs to the subgroup cut out by the special orthogonal Hopf ideal
exactly when its matrix is orthogonal of determinant one. -/
@[simp]
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ↔
      (GeneralLinear.pointsMulEquiv n g : Matrix (Fin n) (Fin n) A) ∈
        Matrix.specialOrthogonalGroup (Fin n) A := by
  rw [definingHopfIdeal, CommHopfAlgCat.quotientPointsSubgroup_sup, Subgroup.mem_inf,
    Orthogonal.mem_definingPointsSubgroup_iff,
    SpecialLinear.mem_definingPointsSubgroup_iff_det_eq_one,
    Matrix.mem_specialOrthogonalGroup_iff]

/-- Read a cut-out ambient point as a special orthogonal matrix. -/
private noncomputable def pointsSubgroupToSpecialOrthogonalGroup
    (g : CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A)) : Matrix.specialOrthogonalGroup (Fin n) A :=
  ⟨(GeneralLinear.pointsMulEquiv n g.1 : Matrix (Fin n) (Fin n) A),
    (mem_definingPointsSubgroup_iff R n g.1).mp g.2⟩

/-- Regard a special orthogonal matrix as a point in the cut-out ambient subgroup, through the
unit `Unitary.toUnits` its orthogonal part defines in the matrix ring. -/
private noncomputable def specialOrthogonalGroupToPointsSubgroup
    (g : Matrix.specialOrthogonalGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A) :=
  ⟨(GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm
      (Unitary.toUnits (⟨(g : Matrix (Fin n) (Fin n) A),
          (Matrix.mem_specialOrthogonalGroup_iff.mp g.2).1⟩ :
        Matrix.orthogonalGroup (Fin n) A)),
    (mem_definingPointsSubgroup_iff R n _).mpr (by
      rw [MulEquiv.apply_symm_apply, Unitary.val_toUnits_apply]
      exact g.2)⟩

/-- The subgroup of `GL n (A)` cut out by the special orthogonal Hopf ideal is
`Matrix.specialOrthogonalGroup (Fin n) A`. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ≃*
      Matrix.specialOrthogonalGroup (Fin n) A where
  toFun := pointsSubgroupToSpecialOrthogonalGroup R n
  invFun := specialOrthogonalGroupToPointsSubgroup R n
  left_inv g := by
    apply Subtype.ext
    unfold specialOrthogonalGroupToPointsSubgroup pointsSubgroupToSpecialOrthogonalGroup
    dsimp only
    rw [Orthogonal.toUnits_mk, MulEquiv.symm_apply_apply]
  right_inv g := by
    apply Subtype.ext
    unfold pointsSubgroupToSpecialOrthogonalGroup specialOrthogonalGroupToPointsSubgroup
    dsimp only
    rw [MulEquiv.apply_symm_apply]
    exact Unitary.val_toUnits_apply _
  map_mul' g h :=
    Subtype.ext (congrArg (fun M : GL (Fin n) A => (M : Matrix (Fin n) (Fin n) A))
      (map_mul (GeneralLinear.pointsMulEquiv (R := R) (A := A) n) g.1 h.1))

/-- **The points identification**: the group of algebra-valued points of the special orthogonal
coordinate Hopf algebra is the special orthogonal group of the value algebra. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A) ≃*
      Matrix.specialOrthogonalGroup (Fin n) A :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
      (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
    (definingPointsSubgroupMulEquiv R n)

/-- Internally, the special orthogonal point equivalence first forms the cut-out ambient
subgroup point and then reads it as a special orthogonal matrix. -/
private theorem pointsMulEquiv_apply_eq
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    pointsMulEquiv R n (A := A) f =
      pointsSubgroupToSpecialOrthogonalGroup R n
        (((CommHopfAlgCat.quotientPointsSubgroupNatIso
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
          (CommAlgCat.of R A)).hom f) :=
  rfl

/-- Under the special orthogonal and general-linear point equivalences, the quotient-point
inclusion is the ordinary inclusion of special orthogonal matrices into `GL n`. -/
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    ((GeneralLinear.pointsMulEquiv n
        (CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
          (CommAlgCat.of R A) f) : GL (Fin n) A) : Matrix (Fin n) (Fin n) A) =
      (pointsMulEquiv R n (A := A) f : Matrix (Fin n) (Fin n) A) := by
  have hcomponent := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
    (CommAlgCat.of R A) f
  rw [pointsMulEquiv_apply_eq]
  exact congrArg
    (fun g => (pointsSubgroupToSpecialOrthogonalGroup R n g : Matrix (Fin n) (Fin n) A))
    hcomponent.symm

/-- The matrix description of special orthogonal points is natural under algebra maps. -/
theorem pointsMulEquiv_mapValue {B : Type v} [CommRing B] [Algebra R B]
    (phi : A →ₐ[R] B)
    (f : WithConv (coordinateHopfAlgebra R n →ₐ[R] A)) :
    pointsMulEquiv R n (A := B)
        (AlgHom.mapValue (H := coordinateHopfAlgebra R n) phi f) =
      Matrix.SpecialOrthogonalGroup.map (phi : A →+* B)
        (pointsMulEquiv R n (A := A) f) := by
  apply Subtype.ext
  have hcoe_lhs := pointsMulEquiv_coe R n
    (AlgHom.mapValue (H := coordinateHopfAlgebra R n) phi f)
  have hcoe_rhs := pointsMulEquiv_coe R n f
  have hnatural := (CommHopfAlgCat.mapValue_quotientPointsHom
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n) phi f).symm
  rw [← hcoe_lhs, hnatural, GeneralLinear.pointsMulEquiv_mapValue,
    Matrix.SpecialOrthogonalGroup.coe_map]
  simpa only [Matrix.GeneralLinearGroup.val_map_apply] using
    congrArg (fun M : Matrix (Fin n) (Fin n) A ↦ M.map (phi : A →+* B)) hcoe_rhs

/-- Naturality of the inverse pointwise equivalence in the value algebra. -/
theorem mapValue_pointsMulEquiv_symm_apply {B : Type v} [CommRing B] [Algebra R B]
    (phi : A →ₐ[R] B) (g : Matrix.specialOrthogonalGroup (Fin n) A) :
    AlgHom.mapValue (H := coordinateHopfAlgebra R n) phi
        ((pointsMulEquiv R n (A := A)).symm g) =
      (pointsMulEquiv R n (A := B)).symm
        (Matrix.SpecialOrthogonalGroup.map phi.toRingHom g) := by
  apply (pointsMulEquiv R n (A := B)).injective
  rw [pointsMulEquiv_mapValue]
  simp

/-- The ambient point attached to a special orthogonal matrix is the general-linear point
attached to the unit of its orthogonal part. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm (g : Matrix.specialOrthogonalGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsHom
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ((pointsMulEquiv R n (A := A)).symm g) =
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm
        (Unitary.toUnits (⟨(g : Matrix (Fin n) (Fin n) A),
            (Matrix.mem_specialOrthogonalGroup_iff.mp g.2).1⟩ :
          Matrix.orthogonalGroup (Fin n) A)) := by
  apply (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).injective
  apply Units.ext
  rw [MulEquiv.apply_symm_apply, Unitary.val_toUnits_apply,
    pointsMulEquiv_coe R n, MulEquiv.apply_symm_apply]

end Points

end TauCeti.SpecialOrthogonal
