/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.FittingIdeal.Basic

/-!
# Computing Fitting ideals from relation generators

The definition of `Submodule.minorsIdeal` allows arbitrary elements of a relation submodule as
rows of a minor. If the relations are generated by a set `s`, multilinearity of the determinant
reduces the ideal to minors whose rows belong to `s`. This gives a presentation formula for
`TauCeti.fittingIdeal` that can be used with explicit finite lists of relations, particularly
when computing the singular locus of a curve from its module of relative differentials.

-/

public section

noncomputable section

open LinearMap Module

namespace TauCeti

variable {R F : Type*} [CommRing R] [AddCommGroup F] [Module R F]

/-- The ideal generated by the `p`-minors formed from rows in a set `s`. -/
def minorsIdealOfSet (s : Set F) (p : ℕ) : Ideal R :=
  Ideal.span {r | ∃ (f : Fin p → Module.Dual R F) (v : Fin p → F),
    (∀ i, v i ∈ s) ∧ (Matrix.of fun i j ↦ f j (v i)).det = r}

/-- The generators defining the minors ideal of a set. -/
theorem minorsIdealOfSet_def (s : Set F) (p : ℕ) :
    minorsIdealOfSet (R := R) s p =
      Ideal.span {r | ∃ (f : Fin p → Module.Dual R F) (v : Fin p → F),
        (∀ i, v i ∈ s) ∧ (Matrix.of fun i j ↦ f j (v i)).det = r} := by
  unfold minorsIdealOfSet
  congr 1

/-- A determinant whose rows belong to `s` lies in `minorsIdealOfSet s p`. -/
theorem det_mem_minorsIdealOfSet {s : Set F} {p : ℕ} (f : Fin p → Module.Dual R F)
    {v : Fin p → F} (hv : ∀ i, v i ∈ s) :
    (Matrix.of fun i j ↦ f j (v i)).det ∈ minorsIdealOfSet s p :=
  Ideal.subset_span ⟨f, v, hv, rfl⟩

/-- Prove a property of every element of `minorsIdealOfSet s p` from the generating
determinants and closure under the ideal operations. -/
theorem minorsIdealOfSet_induction {s : Set F} {p : ℕ} {P : R → Prop} {x : R}
    (hx : x ∈ minorsIdealOfSet s p)
    (hdet : ∀ (f : Fin p → Module.Dual R F) (v : Fin p → F),
      (∀ i, v i ∈ s) → P (Matrix.of fun i j ↦ f j (v i)).det)
    (hzero : P 0) (hadd : ∀ x y, P x → P y → P (x + y))
    (hsmul : ∀ (a x : R), P x → P (a * x)) : P x := by
  rw [minorsIdealOfSet_def] at hx
  induction hx using Submodule.span_induction with
  | mem _ h =>
    obtain ⟨f, v, hv, rfl⟩ := h
    exact hdet f v hv
  | zero => exact hzero
  | add x y _ _ hx hy => exact hadd x y hx hy
  | smul a x _ hx => exact hsmul a x hx

end TauCeti

namespace Submodule

variable {R F : Type*} [CommRing R] [AddCommGroup F] [Module R F]

/-- Minors of a submodule generated by `s` can be computed using only rows in `s`. -/
@[simp]
theorem minorsIdeal_span (s : Set F) (p : ℕ) :
    (Submodule.span R s).minorsIdeal p = TauCeti.minorsIdealOfSet s p := by
  refine le_antisymm (minorsIdeal_le_iff.2 fun f v hv ↦ ?_) ?_
  · exact TauCeti.det_mem_of_mem_span f hv fun _ hw ↦ TauCeti.det_mem_minorsIdealOfSet f hw
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨f, v, hv, rfl⟩
    exact det_mem_minorsIdeal f fun i ↦ Submodule.subset_span (hv i)

end Submodule

namespace TauCeti

variable {R F : Type*} [CommRing R] [AddCommGroup F] [Module R F]

/-- Sets generating the same relation submodule have the same minors ideal. -/
theorem minorsIdealOfSet_eq_of_span_eq {s t : Set F}
    (h : Submodule.span R s = Submodule.span R t) (p : ℕ) :
    minorsIdealOfSet (R := R) s p = minorsIdealOfSet (R := R) t p := by
  rw [← Submodule.minorsIdeal_span, ← Submodule.minorsIdeal_span, h]

variable {R F M : Type*} [CommRing R] [AddCommGroup F] [Module R F]
  [Free R F] [Module.Finite R F] [AddCommGroup M] [Module R M] [Module.Finite R M]

/-- Compute a Fitting ideal from generators of the kernel of a finite free presentation.
No finiteness assumption on the chosen generating set is needed. -/
theorem fittingIdeal_eq_minorsIdealOfSet {φ : F →ₗ[R] M} (hφ : Function.Surjective φ)
    (s : Set F) (hs : Submodule.span R s = LinearMap.ker φ) (k : ℕ) :
    fittingIdeal R M k = minorsIdealOfSet (R := R) s (Module.finrank R F - k) := by
  rw [fittingIdeal_eq_minorsIdeal_ker hφ, ← hs, Submodule.minorsIdeal_span]

end TauCeti
