/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Tame.Character
public import TauCeti.NumberTheory.LocalField.Unramified.ZHat
public import TauCeti.Topology.Algebra.Group.Profinite.Rank
import TauCeti.Algebra.CharP.LocalRing
import TauCeti.NumberTheory.LocalField.TamelyRamified.Basic
import TauCeti.NumberTheory.LocalField.Unramified.Inertia.Finite
import TauCeti.Topology.Algebra.ContinuousMonoidHom.Basic

/-!
# The tame quotient of the absolute Galois group

Let `K` be a nonarchimedean local field with residue characteristic `p` and residue field of order
`q`, let `G_K = Gal(K^{alg}/K)`, and let `P_K ≤ I_K ≤ G_K` be the wild inertia and inertia
subgroups. This file studies the **tame quotient**

`G_K^t = G_K / P_K`,

a profinite group. It proves that `G_K^t` is topologically generated by two elements, and that it
sits in a split exact sequence of profinite groups

`1 → ℤ̂^{(p')}(1) → G_K^t → ℤ̂ → 1`

whose conjugation action is the Iwasawa relation `σ τ σ⁻¹ = τ ^ q`.

### Generation

* The tame character identifies `I_K / P_K` with the prime-to-`p` Tate module `ℤ̂^{(p')}(1)`, which
  is procyclic: a compactness argument on `I_K` produces `τ ∈ I_K` whose tame character has a
  primitive `m`-th root of unity as its level-`m` component for every `m` prime to `p`, and such
  a point generates a dense subgroup of the Tate module. Hence `τ` and `P_K` topologically
  generate `I_K`.
* A Frobenius lift and `I_K` topologically generate `G_K`, so `σ`, `τ` and `P_K` do. Thus
  `G_K^t` is topologically generated by the images of `σ` and `τ`, and its topological generator
  rank is at most `2`.
* The same pair generates every finite quotient `G_K / U` through which wild inertia dies, and
  there the image of `τ` has order prime to `p`: since `P_K` is the Sylow pro-`p` subgroup of
  `I_K`, the image of `I_K` in `G_K / U` has order prime to `p`.
* The image of `τ` alone generates the image of `I_K` in every such finite quotient, and more
  generally topologically generates the image of `I_K` under every continuous homomorphism to a
  Hausdorff group killing `P_K`. At a tamely ramified finite Galois subextension `L` of
  `K^{alg}/K` this says that the restriction of `τ` generates the inertia group `G_0(L/K)`, and so
  has order `e(L/K)`.

The finite form is the input to the count of generators of the absolute Galois group of a `p`-adic
field.

### The exact sequence

* the first map `TauCeti.tameInertiaHom K` is the inverse of the tame character
  `I_K / P_K ≃ₜ* ℤ̂^{(p')}(1)` followed by the inclusion `I_K / P_K ↪ G_K / P_K`, so its image is
  the tame inertia group `I_K / P_K`;
* the second map `TauCeti.tameQuotientToZHat K` is restriction to the maximal unramified extension
  followed by `Gal(K^{ur}/K) ≃ₜ* ℤ̂`, whose kernel is therefore the image of `I_K`;
* the image of an arithmetic Frobenius lift `σ` generates the quotient `ℤ̂`, so `ℤ̂ → G_K^t`,
  `1 ↦ σ`, splits the sequence;
* conjugation by `g ∈ G_K` acts on `ℤ̂^{(p')}(1)` through the action of `g` on the roots of unity,
  by the equivariance of the tame character; a Frobenius lift raises every root of unity of order
  prime to `p` to the `q`-th power, so conjugation by `σ` is `x ↦ x ^ q`.

## Main definitions

* `TauCeti.tameQuotient K`: the tame quotient `G_K / P_K`, a profinite group.
* `TauCeti.toTameQuotient K`: the quotient map `G_K →ₜ* G_K^t`.
* `TauCeti.tameInertiaHom K`: the inclusion `ℤ̂^{(p')}(1) →ₜ* G_K^t` of tame inertia.
* `TauCeti.tameQuotientToZHat K`: the surjection `G_K^t →ₜ* ℤ̂`.

## Main results

* `TauCeti.exists_topologicalClosure_zpowers_inertiaTameCharacter_eq_top`: some element of inertia
  has a tame character that topologically generates `ℤ̂^{(p')}(1)`.
* `TauCeti.topologicalClosure_zpowers_sup_wildInertiaSubgroup`: such an element and wild inertia
  topologically generate inertia.
* `TauCeti.IsArithFrobeniusLift.topologicalClosure_closure_sup_wildInertiaSubgroup`,
  `TauCeti.IsArithFrobeniusLift.topologicalClosure_closure_tameQuotient_eq_top`: together with a
  Frobenius lift, it generates `G_K` modulo wild inertia.
* `TauCeti.isTopologicallyFinitelyGenerated_tameQuotient`,
  `TauCeti.topologicalGeneratorRankNat_tameQuotient_le_two`: the tame quotient is topologically
  generated by two elements.
* `TauCeti.tameInertiaHom_injective`, `TauCeti.ker_tameQuotientToZHat`,
  `TauCeti.tameQuotientToZHat_surjective`: the sequence `1 → ℤ̂^{(p')}(1) → G_K^t → ℤ̂ → 1` is
  exact.
* `TauCeti.range_tameInertiaHom`: the image of `ℤ̂^{(p')}(1)` is the image of inertia.
* `TauCeti.IsArithFrobeniusLift.tameQuotientToZHat_comp_lift`: the continuous homomorphism
  `ℤ̂ → G_K^t` sending `1` to the image of a Frobenius lift splits the sequence.
* `TauCeti.tameInertiaHom_smul`: conjugation in `G_K^t` acts on `ℤ̂^{(p')}(1)` through the
  Galois action on the roots of unity.
* `TauCeti.IsArithFrobeniusLift.smul_eq_pow`: a Frobenius lift acts on `ℤ̂^{(p')}(1)` as
  `x ↦ x ^ q`.
* `TauCeti.IsArithFrobeniusLift.toTameQuotient_mul_tameInertiaHom_mul_inv`,
  `TauCeti.IsArithFrobeniusLift.toTameQuotient_mul_toTameQuotient_mul_inv`: the Iwasawa relation
  `σ τ σ⁻¹ = τ ^ q` in `G_K^t`, for a Frobenius lift `σ` and `τ` in tame inertia.
* `TauCeti.not_dvd_orderOf_mk_of_mem_inertiaSubgroup`: in a finite quotient of `G_K` through
  which wild inertia dies, elements of inertia have order prime to `p`.
* `TauCeti.exists_tameFrame_quotient`: a Frobenius lift `σ` and an element `τ` of inertia whose
  images generate every finite quotient of `G_K` through which wild inertia dies, with the image
  of `τ` of order prime to `p`.
* `TauCeti.map_inertiaSubgroup_eq_topologicalClosure_zpowers`,
  `TauCeti.map_inertiaSubgroup_mk'_eq_zpowers`: a tame inertia generator topologically generates
  the image of `I_K` under every continuous homomorphism to a Hausdorff group killing `P_K`, and
  generates the image of `I_K` in every finite quotient of `G_K` through which `P_K` dies.
* `TauCeti.zpowers_restrictNormal_eq_lowerRamificationGroup_zero`,
  `TauCeti.orderOf_restrictNormal_eq_ramificationIndex`: at a tamely ramified finite Galois
  subextension `L`, it restricts to a generator of `G_0(L/K)`, of order `e(L/K)`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, (7.5.2) and (7.5.3).
* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter IV, §2.
-/

public section

noncomputable section

open ValuativeRel TauCeti.LocalFieldsRamification

namespace TauCeti

universe u

variable (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-! ### The tame quotient -/

/-- The **tame quotient** `G_K^t = G_K / P_K` of the absolute Galois group of `K`: the quotient by
the wild inertia subgroup, which fixes the maximal tamely ramified extension of `K`. -/
abbrev tameQuotient : Type _ :=
  Field.absoluteGaloisGroup K ⧸ wildInertiaSubgroup K

/-- The tame quotient is Hausdorff, since wild inertia is closed. -/
instance : T2Space (tameQuotient K) :=
  haveI := isClosed_wildInertiaSubgroup K
  inferInstance

/-- The tame quotient is totally disconnected, since wild inertia is closed; with compactness, it
is a profinite group. -/
instance : TotallyDisconnectedSpace (tameQuotient K) :=
  haveI := isClosed_wildInertiaSubgroup K
  inferInstance

/-- The quotient map `G_K →ₜ* G_K^t` onto the tame quotient. -/
def toTameQuotient : Field.absoluteGaloisGroup K →ₜ* tameQuotient K :=
  ContinuousMonoidHom.quotientMk _

variable {K} in
/-- The quotient map onto the tame quotient sends `σ` to its class modulo wild inertia. -/
theorem toTameQuotient_apply (σ : Field.absoluteGaloisGroup K) :
    toTameQuotient K σ = (σ : tameQuotient K) :=
  (rfl)

variable {K} in
/-- An element of `G_K` has trivial image in the tame quotient exactly when it is wild. -/
@[simp]
theorem toTameQuotient_eq_one_iff {σ : Field.absoluteGaloisGroup K} :
    toTameQuotient K σ = 1 ↔ σ ∈ wildInertiaSubgroup K :=
  QuotientGroup.eq_one_iff σ

/-- The quotient map onto the tame quotient is surjective. -/
theorem toTameQuotient_surjective : Function.Surjective (toTameQuotient K) :=
  QuotientGroup.mk'_surjective _

/-! ### A topological generator of tame inertia -/

/-- **Tame inertia is procyclic**: some element `τ` of the inertia subgroup has a tame character
that topologically generates `ℤ̂^{(p')}(1)`. -/
theorem exists_topologicalClosure_zpowers_inertiaTameCharacter_eq_top :
    ∃ τ : inertiaSubgroup K,
      (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤ := by
  have : CompactSpace (inertiaSubgroup K) :=
    isCompact_iff_compactSpace.1 (isClosed_inertiaSubgroup K).isCompact
  have hp := CharP.prime_ringChar 𝓀[K]
  -- `K^{alg}` has a primitive `m`-th root of unity for each `m` prime to `p`, as `m ≠ 0` in `K`.
  obtain ⟨τ, hτ⟩ := PrimeToPTateModule.exists_forall_isPrimitiveRoot_proj
    (inertiaTameCharacter K).continuous (proj_inertiaTameCharacter_surjective K) fun m ↦ by
      have : NeZero ((m : ℕ) : K) := ⟨natCast_ne_zero_of_isUnit
        (IsLocalRing.isUnit_natCast_iff_not_dvd.2 (hp.coprime_iff_not_dvd.1 m.2.2.symm))⟩
      exact HasEnoughRootsOfUnity.exists_primitiveRoot (AlgebraicClosure K) m
  exact ⟨τ, PrimeToPTateModule.topologicalClosure_zpowers_eq_top hτ⟩

variable {K} in
/-- **A tame inertia generator and wild inertia generate inertia.** If the tame character of
`τ ∈ I_K` topologically generates `ℤ̂^{(p')}(1)`, then the closed subgroup generated by `τ` and
`P_K` is `I_K`. -/
theorem topologicalClosure_zpowers_sup_wildInertiaSubgroup {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    (Subgroup.zpowers (τ : Field.absoluteGaloisGroup K) ⊔
      wildInertiaSubgroup K).topologicalClosure = inertiaSubgroup K := by
  have : CompactSpace (inertiaSubgroup K) :=
    isCompact_iff_compactSpace.1 (isClosed_inertiaSubgroup K).isCompact
  refine le_antisymm (Subgroup.topologicalClosure_minimal _
    (sup_le (Subgroup.zpowers_le.2 τ.2) (wildInertiaSubgroup_le_inertiaSubgroup K))
    (isClosed_inertiaSubgroup K)) fun σ hσ ↦ ?_
  -- The tame character maps the compact closure `S` of the powers of `τ` in `I_K` onto
  -- `ℤ̂^{(p')}(1)`, so `σ` agrees with some `c ∈ S` modulo the kernel `P_K`.
  set S := (Subgroup.zpowers τ).topologicalClosure
  have hS : S.map (inertiaTameCharacter K).toMonoidHom = ⊤ := by
    rw [MonoidHom.map_topologicalClosure _ (inertiaTameCharacter K).continuous _
      (Subgroup.zpowers τ).isClosed_topologicalClosure.isCompact, MonoidHom.map_zpowers]
    exact hτ
  obtain ⟨c, hcS, hc⟩ : inertiaTameCharacter K ⟨σ, hσ⟩ ∈
      S.map (inertiaTameCharacter K).toMonoidHom := hS ▸ Subgroup.mem_top _
  have hwild : c⁻¹ * ⟨σ, hσ⟩ ∈ (wildInertiaSubgroup K).subgroupOf (inertiaSubgroup K) := by
    rw [← ker_inertiaTameCharacter, MonoidHom.mem_ker, map_mul, map_inv]
    exact inv_mul_eq_one.2 hc
  have hcσ : (c : Field.absoluteGaloisGroup K) ∈ (Subgroup.zpowers
      (τ : Field.absoluteGaloisGroup K)).topologicalClosure := by
    have := (inertiaSubgroup K).subtype.map_topologicalClosure_le continuous_subtype_val _
      ⟨c, hcS, rfl⟩
    rwa [MonoidHom.map_zpowers] at this
  rw [← mul_inv_cancel_left (c : Field.absoluteGaloisGroup K) σ]
  exact mul_mem (Subgroup.topologicalClosure_mono le_sup_left hcσ)
    (Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_right (Subgroup.mem_subgroupOf.1 hwild)))

namespace IsArithFrobeniusLift

variable {K} {σ : Field.absoluteGaloisGroup K}

/-- **The tame frame generates `G_K` modulo wild inertia.** An arithmetic Frobenius lift `σ`, an
element `τ ∈ I_K` whose tame character topologically generates `ℤ̂^{(p')}(1)`, and the wild
inertia subgroup `P_K` together topologically generate the absolute Galois group. -/
theorem topologicalClosure_closure_sup_wildInertiaSubgroup (hσ : IsArithFrobeniusLift K σ)
    {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    (Subgroup.closure {σ, (τ : Field.absoluteGaloisGroup K)} ⊔
      wildInertiaSubgroup K).topologicalClosure = ⊤ := by
  set D := (Subgroup.closure {σ, (τ : Field.absoluteGaloisGroup K)} ⊔
    wildInertiaSubgroup K).topologicalClosure
  -- `D` contains `I_K`, generated by `τ` and `P_K`, and `σ`, which with `I_K` generates `G_K`.
  have hI : inertiaSubgroup K ≤ D := by
    rw [← topologicalClosure_zpowers_sup_wildInertiaSubgroup hτ]
    refine Subgroup.topologicalClosure_mono (sup_le_sup_right ?_ _)
    exact Subgroup.zpowers_le.2 (Subgroup.subset_closure (by simp))
  have hσD : Subgroup.zpowers σ ≤ D :=
    Subgroup.zpowers_le.2 (Subgroup.le_topologicalClosure _
      (Subgroup.mem_sup_left (Subgroup.subset_closure (by simp))))
  rw [eq_top_iff, ← hσ.topologicalClosure_zpowers_sup_inertiaSubgroup]
  exact Subgroup.topologicalClosure_minimal _ (sup_le hσD hI)
    (Subgroup.isClosed_topologicalClosure _)

/-- **The tame frame generates the tame quotient.** The images in `G_K / P_K` of an arithmetic
Frobenius lift `σ` and of an element `τ ∈ I_K` whose tame character topologically generates
`ℤ̂^{(p')}(1)` topologically generate the tame quotient. -/
theorem topologicalClosure_closure_tameQuotient_eq_top (hσ : IsArithFrobeniusLift K σ)
    {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    (Subgroup.closure {(σ : tameQuotient K),
      ((τ : Field.absoluteGaloisGroup K) : tameQuotient K)}).topologicalClosure = ⊤ := by
  have h := topologicalClosure_closure_sup_eq_top_iff.1
    (hσ.topologicalClosure_closure_sup_wildInertiaSubgroup hτ)
  rwa [Set.image_pair] at h

end IsArithFrobeniusLift

/-! ### Generation of the tame quotient -/

/-- **The tame quotient is topologically finitely generated**, by the images of a Frobenius lift
and of a tame inertia generator. -/
theorem isTopologicallyFinitelyGenerated_tameQuotient :
    IsTopologicallyFinitelyGenerated (tameQuotient K) := by
  obtain ⟨σ, hσ⟩ := exists_isArithFrobeniusLift K
  obtain ⟨τ, hτ⟩ := exists_topologicalClosure_zpowers_inertiaTameCharacter_eq_top K
  exact (Set.toFinite _).isTopologicallyFinitelyGenerated
    (hσ.topologicalClosure_closure_tameQuotient_eq_top hτ)

/-- **The tame quotient is topologically generated by two elements.** -/
theorem topologicalGeneratorRankNat_tameQuotient_le_two :
    topologicalGeneratorRankNat (tameQuotient K) (isTopologicallyFinitelyGenerated_tameQuotient K)
      ≤ 2 := by
  classical
  obtain ⟨σ, hσ⟩ := exists_isArithFrobeniusLift K
  obtain ⟨τ, hτ⟩ := exists_topologicalClosure_zpowers_inertiaTameCharacter_eq_top K
  refine (topologicalGeneratorRankNat_le _ (s := {(σ : tameQuotient K),
    ((τ : Field.absoluteGaloisGroup K) : tameQuotient K)}) ?_).trans Finset.card_le_two
  rw [Finset.coe_pair]
  exact hσ.topologicalClosure_closure_tameQuotient_eq_top hτ

/-! ### Tame inertia inside the tame quotient -/

/-- **The inclusion of tame inertia** `ℤ̂^{(p')}(1) →ₜ* G_K^t`: the inverse of the isomorphism
`I_K / P_K ≃ₜ* ℤ̂^{(p')}(1)` given by the tame character, followed by the map
`I_K / P_K → G_K / P_K` induced by the inclusion of inertia. -/
def tameInertiaHom :
    PrimeToPTateModule (ringChar 𝓀[K]) (AlgebraicClosure K) →ₜ* tameQuotient K :=
  let f : inertiaSubgroup K ⧸ (wildInertiaSubgroup K).subgroupOf (inertiaSubgroup K) →*
      tameQuotient K :=
    QuotientGroup.map _ _ (inertiaSubgroup K).subtype le_rfl
  have hf : Continuous f :=
    (QuotientGroup.isQuotientMap_mk _).continuous_iff.2
      (QuotientGroup.continuous_mk.comp continuous_subtype_val)
  (ContinuousMonoidHom.mk f hf).comp ((quotientWildInertiaSubgroupEquiv K).symm : _ →ₜ* _)

variable {K} in
/-- The inclusion of tame inertia sends the tame character of `τ ∈ I_K` to the image of `τ` in
the tame quotient. -/
@[simp]
theorem tameInertiaHom_inertiaTameCharacter (τ : inertiaSubgroup K) :
    tameInertiaHom K (inertiaTameCharacter K τ) = toTameQuotient K τ := by
  rw [tameInertiaHom, ContinuousMonoidHom.comp_toFun, ContinuousMonoidHom.coe_coe,
    quotientWildInertiaSubgroupEquiv_symm_inertiaTameCharacter, ContinuousMonoidHom.coe_mk]
  -- Both sides are the class of `τ` in `G_K / P_K`.
  rfl

/-- **The inclusion of tame inertia is injective**: an element of `I_K` whose image in `G_K / P_K`
is trivial lies in `P_K`, so its tame character is trivial. -/
theorem tameInertiaHom_injective : Function.Injective (tameInertiaHom K) := by
  refine (injective_iff_map_eq_one _).2 fun x hx ↦ ?_
  obtain ⟨⟨τ, hτ⟩, rfl⟩ := inertiaTameCharacter_surjective K x
  rw [tameInertiaHom_inertiaTameCharacter, toTameQuotient_eq_one_iff] at hx
  exact (inertiaTameCharacter_eq_one_iff hτ).2 hx

/-- The image of the inclusion of tame inertia is the image `I_K / P_K` of the inertia subgroup in
the tame quotient. -/
theorem range_tameInertiaHom :
    (tameInertiaHom K).toMonoidHom.range =
      (inertiaSubgroup K).map (toTameQuotient K).toMonoidHom := by
  ext x
  constructor
  · rintro ⟨y, rfl⟩
    obtain ⟨τ, rfl⟩ := inertiaTameCharacter_surjective K y
    exact ⟨τ, τ.2, (tameInertiaHom_inertiaTameCharacter τ).symm⟩
  · rintro ⟨τ, hτ, rfl⟩
    exact ⟨inertiaTameCharacter K ⟨τ, hτ⟩, tameInertiaHom_inertiaTameCharacter ⟨τ, hτ⟩⟩

/-! ### The unramified quotient `ℤ̂` -/

/-- **The surjection `G_K^t →ₜ* ℤ̂`**: restriction to the maximal unramified extension, followed by
the identification `Gal(K^{ur}/K) ≃ₜ* ℤ̂` carrying arithmetic Frobenius to `1`. It is well defined
on the tame quotient because wild inertia fixes `K^{ur}`. -/
def tameQuotientToZHat : tameQuotient K →ₜ* zHat.{u} :=
  let f : Field.absoluteGaloisGroup K →ₜ* zHat.{u} :=
    (maximalUnramifiedGaloisGroupEquivZHat K (AlgebraicClosure K) : _ →ₜ* _).comp
      ⟨restrictMaximalUnramifiedHom K, continuous_restrictMaximalUnramifiedHom K⟩
  ContinuousMonoidHom.quotientLift _ f fun σ hσ ↦ by
    have h := wildInertiaSubgroup_le_inertiaSubgroup K hσ
    rw [← ker_restrictMaximalUnramifiedHom, MonoidHom.mem_ker] at h
    simp [f, MonoidHom.mem_ker, h]

variable {K} in
/-- The image in `ℤ̂` of the class of `σ` is the image of the restriction of `σ` to `K^{ur}`. -/
@[simp]
theorem tameQuotientToZHat_toTameQuotient (σ : Field.absoluteGaloisGroup K) :
    tameQuotientToZHat K (toTameQuotient K σ) =
      maximalUnramifiedGaloisGroupEquivZHat K (AlgebraicClosure K)
        (restrictMaximalUnramifiedHom K σ) :=
  ContinuousMonoidHom.quotientLift_mk _ _ _ σ

/-- **Exactness in the middle**: the kernel of `G_K^t → ℤ̂` is the image of `ℤ̂^{(p')}(1)`, since
both are the image of the inertia subgroup. -/
theorem ker_tameQuotientToZHat :
    (tameQuotientToZHat K).toMonoidHom.ker = (tameInertiaHom K).toMonoidHom.range := by
  have h : (tameQuotientToZHat K).toMonoidHom.ker.comap (toTameQuotient K).toMonoidHom =
      inertiaSubgroup K := by
    ext σ
    rw [Subgroup.mem_comap, MonoidHom.mem_ker, ← ker_restrictMaximalUnramifiedHom,
      MonoidHom.mem_ker, ContinuousMonoidHom.coe_toMonoidHom, ContinuousMonoidHom.coe_toMonoidHom,
      MonoidHom.coe_ofClass, MonoidHom.coe_ofClass, tameQuotientToZHat_toTameQuotient,
      map_eq_one_iff _ (maximalUnramifiedGaloisGroupEquivZHat K (AlgebraicClosure K)).injective]
  rw [range_tameInertiaHom, ← h,
    Subgroup.map_comap_eq_self_of_surjective (toTameQuotient_surjective K)]

variable {K} in
/-- The map `G_K^t → ℤ̂` kills tame inertia: the elementwise form of `ker_tameQuotientToZHat`. -/
@[simp]
theorem tameQuotientToZHat_tameInertiaHom
    (x : PrimeToPTateModule (ringChar 𝓀[K]) (AlgebraicClosure K)) :
    tameQuotientToZHat K (tameInertiaHom K x) = 1 :=
  (ker_tameQuotientToZHat K).ge ⟨x, rfl⟩

/-! ### The conjugation action -/

variable {K} in
/-- **Conjugation acts on tame inertia through the roots of unity**: conjugating the image of
`x ∈ ℤ̂^{(p')}(1)` by the image of `g ∈ G_K` gives the image of `g • x`. This is the equivariance of
the tame character, `TauCeti.inertiaTameCharacter_conj`. -/
theorem tameInertiaHom_smul (g : Gal(AlgebraicClosure K/K))
    (x : PrimeToPTateModule (ringChar 𝓀[K]) (AlgebraicClosure K)) :
    tameInertiaHom K (g • x) =
      toTameQuotient K g * tameInertiaHom K x * (toTameQuotient K g)⁻¹ := by
  obtain ⟨⟨τ, hτ⟩, rfl⟩ := inertiaTameCharacter_surjective K x
  rw [← inertiaTameCharacter_conj g hτ, tameInertiaHom_inertiaTameCharacter,
    tameInertiaHom_inertiaTameCharacter]
  -- `g * τ * g⁻¹` is formed in `Gal(K^{alg}/K)`, whose group structure is not reducibly that of
  -- `Field.absoluteGaloisGroup K`, so `map_mul` does not rewrite; both sides are the class of
  -- `g * τ * g⁻¹` in `G_K / P_K`.
  rfl

namespace IsArithFrobeniusLift

variable {K}

/-- **A Frobenius lift acts on `ℤ̂^{(p')}(1)` as `x ↦ x ^ q`**, since it raises every root of unity
of order prime to `p` to the `q`-th power (`TauCeti.IsArithFrobeniusLift.apply_of_pow_eq_one`). -/
theorem smul_eq_pow {σ : Gal(AlgebraicClosure K/K)} (hσ : IsArithFrobeniusLift K σ)
    (x : PrimeToPTateModule (ringChar 𝓀[K]) (AlgebraicClosure K)) :
    σ • x = x ^ Nat.card 𝓀[K] := by
  refine PrimeToPTateModule.ext fun m ↦ Subtype.ext (Units.ext ?_)
  have h : ((PrimeToPTateModule.proj m x : (AlgebraicClosure K)ˣ) : AlgebraicClosure K) ^
      (m : ℕ) = 1 := by
    simpa using congrArg Units.val ((mem_rootsOfUnity _ _).1 (PrimeToPTateModule.proj m x).2)
  rw [PrimeToPTateModule.coe_proj_smul, AlgEquiv.smul_def, hσ.apply_of_pow_eq_one m.2.2 h]
  simp

variable {σ : Field.absoluteGaloisGroup K}

/-- **The Iwasawa relation on tame inertia**: conjugation by the image of an arithmetic Frobenius
lift `σ` raises the image of every `x ∈ ℤ̂^{(p')}(1)` in the tame quotient to the `q`-th power. -/
theorem toTameQuotient_mul_tameInertiaHom_mul_inv (hσ : IsArithFrobeniusLift K σ)
    (x : PrimeToPTateModule (ringChar 𝓀[K]) (AlgebraicClosure K)) :
    toTameQuotient K σ * tameInertiaHom K x * (toTameQuotient K σ)⁻¹ =
      tameInertiaHom K x ^ Nat.card 𝓀[K] := by
  rw [← map_pow, ← hσ.smul_eq_pow]
  exact (tameInertiaHom_smul σ x).symm

/-- **The Iwasawa relation** `σ τ σ⁻¹ = τ ^ q` in the tame quotient, for an arithmetic Frobenius
lift `σ` and an element `τ` of the inertia subgroup. -/
theorem toTameQuotient_mul_toTameQuotient_mul_inv (hσ : IsArithFrobeniusLift K σ)
    {τ : Field.absoluteGaloisGroup K} (hτ : τ ∈ inertiaSubgroup K) :
    toTameQuotient K σ * toTameQuotient K τ * (toTameQuotient K σ)⁻¹ =
      toTameQuotient K τ ^ Nat.card 𝓀[K] := by
  simpa using hσ.toTameQuotient_mul_tameInertiaHom_mul_inv (inertiaTameCharacter K ⟨τ, hτ⟩)

/-- The image of an arithmetic Frobenius lift in `ℤ̂` is the canonical generator. -/
theorem tameQuotientToZHat_eq_gen (hσ : IsArithFrobeniusLift K σ) :
    tameQuotientToZHat K (toTameQuotient K σ) = zHat.gen := by
  rw [tameQuotientToZHat_toTameQuotient, isArithFrobeniusLift_def.1 hσ,
    maximalUnramifiedGaloisGroupEquivZHat_apply_frobenius]

/-- **The splitting by a Frobenius lift**: the continuous homomorphism `ℤ̂ → G_K^t` sending `1` to
the image of an arithmetic Frobenius lift is a section of `G_K^t → ℤ̂`. -/
theorem tameQuotientToZHat_comp_lift (hσ : IsArithFrobeniusLift K σ) :
    (tameQuotientToZHat K).comp (zHat.lift (toTameQuotient K σ)) =
      ContinuousMonoidHom.id zHat.{u} :=
  zHat.hom_ext (by simp [hσ.tameQuotientToZHat_eq_gen])

/-- **The splitting by a Frobenius lift**, pointwise: `G_K^t → ℤ̂` sends the image of `x ∈ ℤ̂`
under the section `ℤ̂ → G_K^t` determined by an arithmetic Frobenius lift back to `x`. -/
theorem tameQuotientToZHat_lift (hσ : IsArithFrobeniusLift K σ) (x : zHat.{u}) :
    tameQuotientToZHat K (zHat.lift (toTameQuotient K σ) x) = x :=
  DFunLike.congr_fun hσ.tameQuotientToZHat_comp_lift x

end IsArithFrobeniusLift

/-- **The map `G_K^t → ℤ̂` is surjective**, being split by any Frobenius lift. -/
theorem tameQuotientToZHat_surjective : Function.Surjective (tameQuotientToZHat K) := by
  obtain ⟨σ, hσ⟩ := exists_isArithFrobeniusLift K
  exact fun x ↦ ⟨zHat.lift (toTameQuotient K σ) x, hσ.tameQuotientToZHat_lift x⟩

/-! ### The tame frame on finite quotients -/

variable (p : ℕ) [CharP 𝓀[K] p]

variable {K} in
/-- **Inertia has order prime to `p` on a finite tame layer.** In a finite quotient `G_K / U`
through which wild inertia dies, the image of every element of inertia has order prime to the
residue characteristic `p`. -/
theorem not_dvd_orderOf_mk_of_mem_inertiaSubgroup
    (U : OpenNormalSubgroup (Field.absoluteGaloisGroup K))
    (hU : wildInertiaSubgroup K ≤ U.toSubgroup) {τ : Field.absoluteGaloisGroup K}
    (hτ : τ ∈ inertiaSubgroup K) :
    ¬ p ∣ orderOf (τ : Field.absoluteGaloisGroup K ⧸ U.toSubgroup) := by
  have : CompactSpace (inertiaSubgroup K) :=
    isCompact_iff_compactSpace.1 (isClosed_inertiaSubgroup K).isCompact
  -- The image of `I_K` in `G_K / U` is a quotient of `I_K` by the open subgroup `V = I_K ∩ U`,
  -- which contains the Sylow pro-`p` subgroup `P_K`, so `[I_K : V]` is prime to `p`.
  set V := U.comap (inertiaSubgroup K).subtype continuous_subtype_val
  have hV := (isProPSylow_wildInertiaSubgroup K p).not_dvd_index_of_le V.toOpenSubgroup
    fun σ hσ ↦ OpenNormalSubgroup.mem_comap.2 (hU (Subgroup.mem_subgroupOf.1 hσ))
  -- `τ ^ [I_K : V]` lies in `V`, so the order of the image of `τ` divides `[I_K : V]`.
  have hpow := V.toSubgroup.pow_index_mem (⟨τ, hτ⟩ : inertiaSubgroup K)
  refine fun hdvd ↦ hV (hdvd.trans (orderOf_dvd_of_pow_eq_one ?_))
  rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
  exact OpenNormalSubgroup.mem_comap.1 hpow

/-- **The tame frame on the finite tame layers.** There are an arithmetic Frobenius lift `σ` and
an element `τ` of inertia such that for every open normal subgroup `U` of `G_K` containing wild
inertia, the images of `σ` and `τ` generate the finite group `G_K / U` and the image of `τ` has
order prime to the residue characteristic `p`. -/
theorem exists_tameFrame_quotient :
    ∃ σ τ : Field.absoluteGaloisGroup K, IsArithFrobeniusLift K σ ∧ τ ∈ inertiaSubgroup K ∧
      ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        wildInertiaSubgroup K ≤ U.toSubgroup →
          Subgroup.closure {(σ : Field.absoluteGaloisGroup K ⧸ U.toSubgroup),
            (τ : Field.absoluteGaloisGroup K ⧸ U.toSubgroup)} = ⊤ ∧
          ¬ p ∣ orderOf (τ : Field.absoluteGaloisGroup K ⧸ U.toSubgroup) := by
  obtain ⟨σ, hσ⟩ := exists_isArithFrobeniusLift K
  obtain ⟨τ, hτ⟩ := exists_topologicalClosure_zpowers_inertiaTameCharacter_eq_top K
  refine ⟨σ, τ, hσ, τ.2, fun U hU ↦ ⟨?_, not_dvd_orderOf_mk_of_mem_inertiaSubgroup p U hU τ.2⟩⟩
  -- The frame generates `G_K` modulo `P_K ≤ U`, hence topologically generates the discrete
  -- quotient `G_K / U`, where every subgroup is closed.
  have : DiscreteTopology (Field.absoluteGaloisGroup K ⧸ U.toSubgroup) :=
    QuotientGroup.discreteTopology U.isOpen
  have h := topologicalClosure_closure_sup_eq_top_iff.1 (top_le_iff.1 <|
    (hσ.topologicalClosure_closure_sup_wildInertiaSubgroup hτ).ge.trans
      (Subgroup.topologicalClosure_mono (sup_le_sup_left hU _)))
  rwa [Set.image_pair, (isClosed_discrete _).subgroup_topologicalClosure_eq] at h

/-! ### A tame inertia generator generates the finite tame inertia groups -/

variable {K}

/-- **A tame inertia generator generates the image of inertia.** Let `τ ∈ I_K` be an element whose
tame character topologically generates `ℤ̂^{(p')}(1)`. Under a continuous homomorphism `f` from
`G_K` to a Hausdorff group which kills wild inertia, the image of `I_K` is the closed subgroup
generated by `f τ`. -/
theorem map_inertiaSubgroup_eq_topologicalClosure_zpowers {H : Type*} [Group H]
    [TopologicalSpace H] [IsTopologicalGroup H] [T2Space H]
    (f : Field.absoluteGaloisGroup K →* H) (hf : Continuous f)
    (hP : wildInertiaSubgroup K ≤ f.ker) {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    (inertiaSubgroup K).map f = (Subgroup.zpowers (f τ)).topologicalClosure := by
  -- `I_K` is the closure of `⟨τ⟩ ⊔ P_K`, compact as `G_K` is, and `f` kills `P_K`.
  refine (congrArg (Subgroup.map f)
    (topologicalClosure_zpowers_sup_wildInertiaSubgroup hτ)).symm.trans ?_
  rw [f.map_topologicalClosure hf _ (Subgroup.isClosed_topologicalClosure _).isCompact,
    Subgroup.map_sup, MonoidHom.map_zpowers, (Subgroup.map_eq_bot_iff _).2 hP, sup_bot_eq]

/-- **A tame inertia generator generates the finite tame inertia groups.** If the tame character
of `τ ∈ I_K` topologically generates `ℤ̂^{(p')}(1)`, then in every finite quotient `G_K / U`
through which wild inertia dies, the image of `I_K` is the cyclic group generated by the image of
`τ`. -/
theorem map_inertiaSubgroup_mk'_eq_zpowers
    (U : OpenNormalSubgroup (Field.absoluteGaloisGroup K))
    (hU : wildInertiaSubgroup K ≤ U.toSubgroup) {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    (inertiaSubgroup K).map (QuotientGroup.mk' U.toSubgroup) =
      Subgroup.zpowers ((τ : Field.absoluteGaloisGroup K) :
        Field.absoluteGaloisGroup K ⧸ U.toSubgroup) := by
  have : U.toSubgroup.Normal := U.isNormal'
  have : DiscreteTopology (Field.absoluteGaloisGroup K ⧸ U.toSubgroup) :=
    QuotientGroup.discreteTopology U.isOpen
  rw [map_inertiaSubgroup_eq_topologicalClosure_zpowers
    (H := Field.absoluteGaloisGroup K ⧸ U.toSubgroup) _ continuous_quot_mk
    (by rwa [QuotientGroup.ker_mk']) hτ,
    (isClosed_discrete _).subgroup_topologicalClosure_eq, QuotientGroup.mk'_apply]

variable (L : IntermediateField K (AlgebraicClosure K)) [Module.Finite K L] [IsGalois K L]
  [ValuativeRel L] [TopologicalSpace L] [IsNonarchimedeanLocalField L] [ValuativeExtension K L]

/-- **A tame inertia generator restricts to a generator of finite inertia.** If the tame character
of `τ ∈ I_K` topologically generates `ℤ̂^{(p')}(1)`, then for every tamely ramified finite Galois
subextension `L` of `K^{alg}/K`, the restriction of `τ` to `L` generates the inertia group
`G_0(L/K)`. -/
theorem zpowers_restrictNormal_eq_lowerRamificationGroup_zero (hL : IsTamelyRamified K L)
    {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    Subgroup.zpowers (AlgEquiv.restrictNormal (τ : Field.absoluteGaloisGroup K) L) =
      lowerRamificationGroup K L 0 := by
  -- Restriction to `L` kills `P_K`, since its image `G_1(L/K)` is trivial for `L/K` tame.
  have hP : wildInertiaSubgroup K ≤ (AlgEquiv.restrictNormalHom L).ker := by
    have h := map_wildInertiaSubgroup_restrictNormalHom L
    rw [(lowerRamificationGroup_one_eq_bot_iff_isTamelyRamified (K := K) (L := L)).2 hL] at h
    exact (Subgroup.map_eq_bot_iff _).1 h
  have h := map_inertiaSubgroup_eq_topologicalClosure_zpowers (H := Gal(L/K)) _
    (InfiniteGalois.restrictNormalHom_continuous L) hP hτ
  rw [(isClosed_discrete _).subgroup_topologicalClosure_eq] at h
  -- `Field.absoluteGaloisGroup K` is `Gal(K^{alg}/K)`, but its group structure is not reducibly
  -- that of `Gal(K^{alg}/K)`, so `map_inertiaSubgroup_restrictNormalHom` cannot be rewritten.
  exact h.symm.trans (map_inertiaSubgroup_restrictNormalHom L)

/-- **The restriction of a tame inertia generator has order `e`.** If the tame character of
`τ ∈ I_K` topologically generates `ℤ̂^{(p')}(1)`, then for every tamely ramified finite Galois
subextension `L` of `K^{alg}/K`, the restriction of `τ` to `L` has order the ramification index
`e(L/K)`. -/
theorem orderOf_restrictNormal_eq_ramificationIndex (hL : IsTamelyRamified K L)
    {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    orderOf (AlgEquiv.restrictNormal (τ : Field.absoluteGaloisGroup K) L) =
      ramificationIndex K L := by
  rw [← Nat.card_zpowers, zpowers_restrictNormal_eq_lowerRamificationGroup_zero L hL hτ,
    natCard_lowerRamificationGroup_zero]

end TauCeti
