/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.Exact.Stable.Autoequivalence
public import TauCeti.CategoryTheory.Shift.Intertwining

/-!
# The shift on the stable category of a Frobenius exact category

Let `E` be a Frobenius exact structure. Stable suspension is an additive autoequivalence of the
projective stable category, with quasi-inverse the stable loop functor. This file equips the
stable category with the shift by `ℤ` that this autoequivalence generates: its shift by `1` is
stable suspension `Σ`, its shift by `-1` is the stable loop functor `Ω`, and all its shift
functors are additive. This is the translation functor with respect to which the stable category
is triangulated by Happel's standard triangles `X ⟶ Y ⟶ Z ⟶ X⟦1⟧`.

The shift depends on the Frobenius hypothesis `hE`, which is a proposition rather than a class, so
it is a definition and not an instance; statements about it install it with
`letI := hE.stableHasShift`.

## Main definitions

* `TauCeti.ExactStructure.IsFrobenius.stableHasShift`: the shift by `ℤ` on the stable category
  generated by stable suspension.
* `TauCeti.ExactStructure.IsFrobenius.stableShiftFunctorOneIso`: its shift by `1` is stable
  suspension.
* `TauCeti.ExactStructure.IsFrobenius.stableShiftFunctorNegOneIso`: its shift by `-1` is the
  stable loop functor.
* `TauCeti.ExactStructure.IsFrobenius.stableSuspensionObjIsoShift`: the chosen suspension object
  represents the shift by `1`.

## Main results

* `TauCeti.ExactStructure.IsFrobenius.stableSuspensionObjIsoShift_hom_naturality`: the comparison
  from chosen suspension objects to the shift is natural.
* `TauCeti.ExactStructure.IsFrobenius.stableShiftFunctor_additive`: every shift functor of the
  stable category is additive.

## References

* Dieter Happel, *Triangulated Categories in the Representation Theory of Finite Dimensional
  Algebras*, Chapter I, Section 2.
-/

public section

namespace TauCeti

open CategoryTheory CategoryTheory.Limits

universe v v' u u'

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C]
  [HasBinaryBiproducts C]

namespace ExactStructure.IsFrobenius

variable {E : ExactStructure C} (hE : E.IsFrobenius)

/-- The shift by `ℤ` on the stable category of a Frobenius exact structure generated by the
stable suspension autoequivalence. -/
@[instance_reducible]
noncomputable def stableHasShift : HasShift E.ProjectiveStableCategory ℤ :=
  hE.stableSuspension.asEquivalence.hasShift

/-- Transport shift compatibility for a stable functor from the suspension-generated shift to
the chosen stable shift. -/
@[instance_reducible]
noncomputable def commShiftOfStableSuspension
    {D : Type u'} [Category.{v'} D] [Preadditive D] [HasZeroObject D]
    [HasBinaryBiproducts D] {E' : ExactStructure D} (hE' : E'.IsFrobenius)
    (F : E.ProjectiveStableCategory ⥤ E'.ProjectiveStableCategory)
    (hF : letI := hE.stableSuspension.asEquivalence.hasShift
      letI := hE'.stableSuspension.asEquivalence.hasShift
      F.CommShift ℤ) :
    letI := hE.stableHasShift
    letI := hE'.stableHasShift
    F.CommShift ℤ := by
  unfold stableHasShift
  exact hF

/-- The shift by `1` on the stable category of a Frobenius exact structure is stable
suspension. -/
noncomputable def stableShiftFunctorOneIso :
    letI := hE.stableHasShift
    shiftFunctor E.ProjectiveStableCategory (1 : ℤ) ≅ hE.stableSuspension :=
  hE.stableSuspension.asEquivalence.shiftFunctorOneIso

/-- In degree one, transported stable shift compatibility recovers the supplied suspension
comparison. -/
theorem commShiftOfStableSuspension_iso_one
    {D : Type u'} [Category.{v'} D] [Preadditive D] [HasZeroObject D]
    [HasBinaryBiproducts D] {E' : ExactStructure D} (hE' : E'.IsFrobenius)
    (F : E.ProjectiveStableCategory ⥤ E'.ProjectiveStableCategory)
    (α : hE.stableSuspension ⋙ F ≅ F ⋙ hE'.stableSuspension) :
    letI := hE.stableHasShift
    letI := hE'.stableHasShift
    letI := hE.commShiftOfStableSuspension hE' F
      (CategoryTheory.Functor.commShiftOfIntertwining F
        hE.stableSuspension.asEquivalence hE'.stableSuspension.asEquivalence α)
    F.commShiftIso (1 : ℤ) =
      Functor.isoWhiskerRight hE.stableShiftFunctorOneIso F ≪≫ α ≪≫
        Functor.isoWhiskerLeft F hE'.stableShiftFunctorOneIso.symm := by
  unfold commShiftOfStableSuspension stableShiftFunctorOneIso stableHasShift
  exact CategoryTheory.Functor.commShiftOfIntertwining_iso_one F
    hE.stableSuspension.asEquivalence hE'.stableSuspension.asEquivalence α

/-- A functor out of the stable category which intertwines stable suspension with an
autoequivalence `e` of its target commutes coherently with the stable shift and the shift by `ℤ`
generated by `e`. -/
@[instance_reducible]
noncomputable def commShiftOfIntertwiningStableSuspension {D : Type u'} [Category.{v'} D]
    (e : D ≌ D) (F : E.ProjectiveStableCategory ⥤ D)
    (α : hE.stableSuspension ⋙ F ≅ F ⋙ e.functor) :
    letI := hE.stableHasShift
    letI := e.hasShift
    F.CommShift ℤ := by
  unfold stableHasShift
  exact CategoryTheory.Functor.commShiftOfIntertwining F hE.stableSuspension.asEquivalence e α

/-- In degree one, the shift compatibility of a functor intertwining stable suspension with an
autoequivalence `e` recovers the supplied intertwining isomorphism. -/
theorem commShiftOfIntertwiningStableSuspension_iso_one {D : Type u'} [Category.{v'} D]
    (e : D ≌ D) (F : E.ProjectiveStableCategory ⥤ D)
    (α : hE.stableSuspension ⋙ F ≅ F ⋙ e.functor) :
    letI := hE.stableHasShift
    letI := e.hasShift
    letI := hE.commShiftOfIntertwiningStableSuspension e F α
    F.commShiftIso (1 : ℤ) =
      Functor.isoWhiskerRight hE.stableShiftFunctorOneIso F ≪≫ α ≪≫
        Functor.isoWhiskerLeft F e.shiftFunctorOneIso.symm := by
  unfold commShiftOfIntertwiningStableSuspension stableShiftFunctorOneIso stableHasShift
  exact CategoryTheory.Functor.commShiftOfIntertwining_iso_one F
    hE.stableSuspension.asEquivalence e α

/-- The shift by `-1` on the stable category of a Frobenius exact structure is the stable loop
functor. -/
noncomputable def stableShiftFunctorNegOneIso :
    letI := hE.stableHasShift
    shiftFunctor E.ProjectiveStableCategory (-1 : ℤ) ≅ hE.enoughProjectives.stableLoop :=
  hE.stableSuspension.asEquivalence.shiftFunctorNegOneIso hE.stableLoopCompStableSuspensionIso

/-- The chosen suspension object representing `X⟦1⟧` is isomorphic to the shift of `X` in the
stable category. -/
noncomputable def stableSuspensionObjIsoShift (X : C) :
    letI := hE.stableHasShift
    E.projectiveStableFunctor.obj (hE.suspensionObj X) ≅
      (E.projectiveStableFunctor.obj X)⟦(1 : ℤ)⟧ := by
  letI := hE.stableHasShift
  exact
    { hom := eqToHom (hE.stableSuspension_obj_projectiveStableFunctor_obj X).symm ≫
        hE.stableShiftFunctorOneIso.inv.app (E.projectiveStableFunctor.obj X)
      inv := hE.stableShiftFunctorOneIso.hom.app (E.projectiveStableFunctor.obj X) ≫
        eqToHom (hE.stableSuspension_obj_projectiveStableFunctor_obj X)
      hom_inv_id := by simp
      inv_hom_id := by simp }

/-- The forward map from the chosen suspension object to the shift. -/
@[simp]
theorem stableSuspensionObjIsoShift_hom (X : C) :
    letI := hE.stableHasShift
    (hE.stableSuspensionObjIsoShift X).hom =
      eqToHom (hE.stableSuspension_obj_projectiveStableFunctor_obj X).symm ≫
        hE.stableShiftFunctorOneIso.inv.app (E.projectiveStableFunctor.obj X) := (rfl)

/-- The inverse map from the shift to the chosen suspension object. -/
@[simp]
theorem stableSuspensionObjIsoShift_inv (X : C) :
    letI := hE.stableHasShift
    (hE.stableSuspensionObjIsoShift X).inv =
      hE.stableShiftFunctorOneIso.hom.app (E.projectiveStableFunctor.obj X) ≫
        eqToHom (hE.stableSuspension_obj_projectiveStableFunctor_obj X) := (rfl)

/-- The comparison from a chosen suspension object to the shift is natural in morphisms of the
exact category. -/
@[reassoc]
theorem stableSuspensionObjIsoShift_hom_naturality {X Y : C} (f : X ⟶ Y) :
    letI := hE.stableHasShift
    E.projectiveStableFunctor.map
          ((hE.suspensionPresentation X).cokernelMap (hE.suspensionPresentation Y) f) ≫
        (hE.stableSuspensionObjIsoShift Y).hom =
      (hE.stableSuspensionObjIsoShift X).hom ≫
        (E.projectiveStableFunctor.map f)⟦(1 : ℤ)⟧' := by
  let _ := hE.stableHasShift
  rw [← cancel_epi
    (eqToHom (hE.stableSuspension_obj_projectiveStableFunctor_obj X))]
  simpa only [stableSuspensionObjIsoShift_hom, Category.assoc,
    eqToHom_trans_assoc, eqToHom_refl, Category.id_comp,
    hE.stableSuspension_map_projectiveStableFunctor_map] using
      hE.stableShiftFunctorOneIso.inv.naturality (E.projectiveStableFunctor.map f)

/-- Every shift functor on the stable category of a Frobenius exact structure is additive. -/
theorem stableShiftFunctor_additive (n : ℤ) :
    letI := hE.stableHasShift
    (shiftFunctor E.ProjectiveStableCategory n).Additive :=
  have : hE.stableSuspension.asEquivalence.functor.Additive := hE.stableSuspension_additive
  hE.stableSuspension.asEquivalence.shiftFunctor_additive n

end ExactStructure.IsFrobenius

end TauCeti
