/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Quiver.Zigzag.Projective.Syzygy
public import Mathlib.LinearAlgebra.DFinsupp

/-!
# Quadratic projective presentations of zigzag simple modules

The arrow maps out of a vertex assemble to a map from the direct sum of its neighbouring
projectives onto the radical of its projective. Its kernel is generated by nonreturning
length-two paths and differences of backtracks whenever no edge is an isolated component.
This gives an exact quadratic projective presentation under that local branching condition.
The relation family is generally redundant, and no minimality or exactness of higher Koszul
terms is asserted. The maps increase the unshifted degree by one; grading shifts are not bundled.

The results concern the zigzag relation quotient, hence the ordinary zigzag algebra on every
connected component with an edge. All fields, including characteristic two, are allowed.

See Huerfano--Khovanov, *A category for the adjoint representation*, Section 3, for the
zigzag relations and projective modules.
-/

public section

namespace TauCeti

open PathAlgebra DoubledQuiver

variable (k : Type*) [Field k] {V : Type*} (G : SimpleGraph V) [Finite V]

local notation "Z" => nonisolatedZigzagQuotient k G

/-- The direct sum of the vertex projectives neighbouring `i`. In the quadratic presentation
this term is shifted so that its vertex generators have degree one. -/
abbrev ZigzagNeighborProjectives (i : V) :=
  Π₀ j : G.neighborSet i, zigzagProjective k G j.1

/-- The first differential: in the summand at `j`, right multiplication by the arrow `i → j`. -/
noncomputable def zigzagProjectiveArrowSum (i : V) :
    ZigzagNeighborProjectives k G i →ₗ[Z] zigzagProjective k G i := by
  classical
  exact DFinsupp.lsum ℕ fun j => zigzagProjectiveArrowMul k G ⟨(i, j.1), (G.mem_neighborSet i
    j.1).mp j.2⟩

/-- The first differential restricted to one summand is the corresponding arrow map.
The equality decision is supplied by the caller, as required by `DFinsupp.single`; the map
itself does not depend on that choice. -/
@[simp]
theorem zigzagProjectiveArrowSum_single (i : V) [DecidableEq (G.neighborSet i)]
    (j : G.neighborSet i)
    (x : zigzagProjective k G j.1) :
    zigzagProjectiveArrowSum k G i (DFinsupp.single j x) =
      zigzagProjectiveArrowMul k G ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ x := by
  classical
  exact DFinsupp.lsum_single ℕ _ _ _

/-- Quadratic relation labels based at `i`: a nonreturning path `i → j → l`, or a pair
of neighbours specifying the difference of the two backtracks at `i`. Ordered pairs are used;
they give a redundant, choice-free family of relations. -/
abbrev ZigzagQuadraticRelationIndex (i : V) :=
  (Σ j : G.neighborSet i, {l : G.neighborSet j.1 // l.1 ≠ i}) ⊕
    (G.neighborSet i × G.neighborSet i)

/-- The endpoint of the paths in a quadratic relation, hence the vertex of its projective. -/
abbrev ZigzagQuadraticRelationIndex.vertex {i : V} : ZigzagQuadraticRelationIndex G i → V
  | .inl r => r.2.1.1
  | .inr _ => i

/-- The direct sum of vertex projectives indexed by the quadratic relations based at `i`.
In the quadratic presentation this term is shifted so that its vertex generators have degree two. -/
abbrev ZigzagQuadraticRelationProjectives (i : V) :=
  Π₀ r : ZigzagQuadraticRelationIndex G i, zigzagProjective k G r.vertex

/-- A quadratic relation map into the neighbouring projectives. Nonreturning paths use one
summand; differences of backtracks use the difference of two summand maps. -/
noncomputable def zigzagProjectiveQuadraticRelationMap (i : V)
    (r : ZigzagQuadraticRelationIndex G i) :
    zigzagProjective k G r.vertex →ₗ[Z] ZigzagNeighborProjectives k G i := by
  classical
  rcases r with ⟨j, l⟩ | ⟨j, j'⟩
  · exact (DFinsupp.lsingle j).comp
      (zigzagProjectiveArrowMul k G ⟨(j.1, l.1.1), (G.mem_neighborSet j.1 l.1.1).mp l.1.2⟩)
  · exact (DFinsupp.lsingle j).comp
        (zigzagProjectiveArrowMul k G ⟨(j.1, i), ((G.mem_neighborSet i j.1).mp j.2).symm⟩) -
      (DFinsupp.lsingle j').comp
        (zigzagProjectiveArrowMul k G ⟨(j'.1, i), ((G.mem_neighborSet i j'.1).mp j'.2).symm⟩)

/-- The second differential, assembled from all quadratic relation maps. -/
noncomputable def zigzagProjectiveQuadraticDifferential (i : V) :
    ZigzagQuadraticRelationProjectives k G i →ₗ[Z] ZigzagNeighborProjectives k G i := by
  classical
  exact DFinsupp.lsum ℕ (zigzagProjectiveQuadraticRelationMap k G i)

/-- On one relation summand, the second differential is its specified relation map. -/
@[simp]
theorem zigzagProjectiveQuadraticDifferential_single (i : V)
    [DecidableEq (ZigzagQuadraticRelationIndex G i)]
    (r : ZigzagQuadraticRelationIndex G i) (x : zigzagProjective k G r.vertex) :
    zigzagProjectiveQuadraticDifferential k G i (DFinsupp.single r x) =
      zigzagProjectiveQuadraticRelationMap k G i r x := by
  classical
  exact DFinsupp.lsum_single ℕ _ _ _

/-- A nonreturning relation maps into its intermediate-vertex summand by the second arrow. -/
theorem zigzagProjectiveQuadraticRelationMap_nonreturn (i : V)
    [hdec : DecidableEq (G.neighborSet i)] (j : G.neighborSet i)
    (l : G.neighborSet j.1) (hli : l.1 ≠ i) (x : zigzagProjective k G l.1) :
    zigzagProjectiveQuadraticRelationMap k G i (.inl ⟨j, ⟨l, hli⟩⟩) x =
      DFinsupp.single j (zigzagProjectiveArrowMul k G ⟨(j.1, l.1), (G.mem_neighborSet j.1 l.1).mp
        l.2⟩ x) := by
  -- The defining constructor uses classical equality; transport it to the caller's decision.
  cases Subsingleton.elim hdec
    (@Subtype.instDecidableEq V (Membership.mem (G.neighborSet i)) (Classical.decEq V))
  rfl

/-- A backtrack difference maps into the difference of its two neighbour summands. -/
theorem zigzagProjectiveQuadraticRelationMap_backtrack (i : V)
    [hdec : DecidableEq (G.neighborSet i)] (j j' : G.neighborSet i)
    (x : zigzagProjective k G i) :
    zigzagProjectiveQuadraticRelationMap k G i (.inr (j, j')) x =
      DFinsupp.single j (zigzagProjectiveArrowMul k G ⟨(j.1, i), ((G.mem_neighborSet i j.1).mp
        j.2).symm⟩ x) -
        DFinsupp.single j' (zigzagProjectiveArrowMul k G ⟨(j'.1, i), ((G.mem_neighborSet i
          j'.1).mp j'.2).symm⟩ x) := by
  -- The defining constructor uses classical equality; transport it to the caller's decision.
  cases Subsingleton.elim hdec
    (@Subtype.instDecidableEq V (Membership.mem (G.neighborSet i)) (Classical.decEq V))
  rfl

private theorem arrowMul_generator (d : G.Dart) :
    zigzagProjectiveArrowMul k G d (zigzagProjectiveGenerator k G d.snd) =
      zigzagProjectiveBasisFun k G d.fst (.inr (.inl ⟨d, rfl⟩)) := by
  apply Subtype.ext
  simp only [coe_zigzagProjectiveArrowMul_apply, coe_zigzagProjectiveGenerator,
    coe_zigzagProjectiveBasisFun_inr_inl, zigzagVertexIdempotent]
  exact zigzagMk_vertexIdempotent_mul_ofArrow k G d

open Classical in
private theorem arrowMul_arrow (d e : G.Dart) (he : e.fst = d.snd) :
    zigzagProjectiveArrowMul k G d
      (zigzagProjectiveBasisFun k G d.snd (.inr (.inl ⟨e, he⟩))) =
      if e = d.symm then zigzagProjectiveVolume k G d.fst else 0 := by
  classical
  apply Subtype.ext
  simp only [coe_zigzagProjectiveArrowMul_apply, coe_zigzagProjectiveBasisFun_inr_inl]
  split_ifs with h
  · subst e
    have hmul := zigzagMk_ofArrow_mul_ofArrow_symm k G d.symm
    rw [SimpleGraph.Dart.symm_symm] at hmul
    simpa only [coe_zigzagProjectiveVolume, SimpleGraph.Dart.symm_toProd, Prod.snd_swap] using hmul
  · exact zigzagMk_ofArrow_mul_ofArrow_of_ne k G (by
      intro h'
      exact h (by simpa using congrArg SimpleGraph.Dart.symm h'.symm))

private theorem arrowMul_volume (d : G.Dart) :
    zigzagProjectiveArrowMul k G d (zigzagProjectiveVolume k G d.snd) = 0 := by
  apply Subtype.ext
  simp only [coe_zigzagProjectiveArrowMul_apply, coe_zigzagProjectiveVolume,
    ZeroMemClass.coe_zero, zigzagVolume_mul_zigzagMk_ofArrow]

/-- The quadratic differential followed by the arrow differential is zero. -/
@[simp]
theorem zigzagProjectiveArrowSum_comp_quadraticDifferential (i : V) :
    zigzagProjectiveArrowSum k G i ∘ₗ zigzagProjectiveQuadraticDifferential k G i = 0 := by
  classical
  apply DFinsupp.lhom_ext
  intro r x
  rcases r with ⟨j, l⟩ | ⟨j, j'⟩
  · dsimp only [ZigzagQuadraticRelationIndex.vertex] at x
    simp only [LinearMap.comp_apply, zigzagProjectiveQuadraticDifferential_single,
      zigzagProjectiveQuadraticRelationMap, LinearMap.comp_apply, DFinsupp.lsingle_apply,
        zigzagProjectiveArrowSum_single,
      LinearMap.zero_apply]
    apply Subtype.ext
    rw [coe_zigzagProjectiveArrowMul_apply, coe_zigzagProjectiveArrowMul_apply, mul_assoc]
    rw [zigzagMk_ofArrow_mul_ofArrow_of_ne k G (by
      intro h
      have := congrArg (fun d : G.Dart => d.fst) h
      exact l.2 (by simpa using this.symm)), mul_zero]
    rfl
  · dsimp only [ZigzagQuadraticRelationIndex.vertex] at x
    simp only [LinearMap.comp_apply, zigzagProjectiveQuadraticDifferential_single,
      zigzagProjectiveQuadraticRelationMap, LinearMap.comp_apply, LinearMap.sub_apply,
        DFinsupp.lsingle_apply, map_sub,
      zigzagProjectiveArrowSum_single, LinearMap.zero_apply]
    apply Subtype.ext
    simp only [Submodule.coe_sub]
    rw [coe_zigzagProjectiveArrowMul_apply k G ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩,
      coe_zigzagProjectiveArrowMul_apply k G ⟨(j.1, i), ((G.mem_neighborSet i j.1).mp j.2).symm⟩,
      coe_zigzagProjectiveArrowMul_apply k G ⟨(i, j'.1), (G.mem_neighborSet i j'.1).mp j'.2⟩,
      coe_zigzagProjectiveArrowMul_apply k G ⟨(j'.1, i), ((G.mem_neighborSet i j'.1).mp j'.2).symm⟩,
      mul_assoc, mul_assoc]
    have hj := zigzagMk_ofArrow_mul_ofArrow_symm k G (⟨(j.1, i), ((G.mem_neighborSet i j.1).mp
      j.2).symm⟩ : G.Dart)
    have hj' := zigzagMk_ofArrow_mul_ofArrow_symm k G (⟨(j'.1, i), ((G.mem_neighborSet i j'.1).mp
      j'.2).symm⟩ : G.Dart)
    simp only [SimpleGraph.Dart.symm] at hj hj'
    rw [hj, hj', sub_self]
    rfl

open Classical in
private theorem single_arrow_mem_range (i : V) (j : G.neighborSet i)
    (l : G.neighborSet j.1) (hli : l.1 ≠ i) :
    DFinsupp.single j (zigzagProjectiveBasisFun k G j.1
      (.inr (.inl ⟨⟨(j.1, l.1), (G.mem_neighborSet j.1 l.1).mp l.2⟩, rfl⟩))) ∈
      LinearMap.range (zigzagProjectiveQuadraticDifferential k G i) := by
  refine ⟨DFinsupp.single (.inl ⟨j, ⟨l, hli⟩⟩)
    (zigzagProjectiveGenerator k G l.1), ?_⟩
  simp only [zigzagProjectiveQuadraticDifferential_single,
    zigzagProjectiveQuadraticRelationMap, LinearMap.comp_apply, DFinsupp.lsingle_apply]
  exact congrArg (DFinsupp.single j) (arrowMul_generator k G
    ⟨(j.1, l.1), (G.mem_neighborSet j.1 l.1).mp l.2⟩)

open Classical in
private theorem backtrack_difference_mem_range (i : V) (j j' : G.neighborSet i) :
    DFinsupp.single j (zigzagProjectiveBasisFun k G j.1
      (.inr (.inl ⟨⟨(j.1, i), ((G.mem_neighborSet i j.1).mp j.2).symm⟩, rfl⟩))) -
    DFinsupp.single j' (zigzagProjectiveBasisFun k G j'.1
      (.inr (.inl ⟨⟨(j'.1, i), ((G.mem_neighborSet i j'.1).mp j'.2).symm⟩, rfl⟩))) ∈
      LinearMap.range (zigzagProjectiveQuadraticDifferential k G i) := by
  refine ⟨DFinsupp.single (.inr (j, j')) (zigzagProjectiveGenerator k G i), ?_⟩
  simp only [zigzagProjectiveQuadraticDifferential_single,
    zigzagProjectiveQuadraticRelationMap, LinearMap.comp_apply, LinearMap.sub_apply,
      DFinsupp.lsingle_apply]
  rw [arrowMul_generator k G ⟨(j.1, i), ((G.mem_neighborSet i j.1).mp j.2).symm⟩,
    arrowMul_generator k G ⟨(j'.1, i), ((G.mem_neighborSet i j'.1).mp j'.2).symm⟩]

open Classical in
private theorem single_volume_mem_range (i : V)
    (hbranch : ∀ j : G.neighborSet i,
      (∃ l : G.neighborSet j.1, l.1 ≠ i) ∨ (∃ j' : G.neighborSet i, j' ≠ j))
    (j : G.neighborSet i) :
    DFinsupp.single j (zigzagProjectiveVolume k G j.1) ∈
      LinearMap.range (zigzagProjectiveQuadraticDifferential k G i) := by
  classical
  rcases hbranch j with ⟨l, hli⟩ | ⟨j', hj'⟩
  · let r : ZigzagQuadraticRelationIndex G i := .inl ⟨j, ⟨l, hli⟩⟩
    let x := zigzagProjectiveBasisFun k G l.1
      (.inr (.inl ⟨⟨(l.1, j.1), ((G.mem_neighborSet j.1 l.1).mp l.2).symm⟩, rfl⟩))
    refine ⟨DFinsupp.single r x, ?_⟩
    simp only [zigzagProjectiveQuadraticDifferential_single, r,
      zigzagProjectiveQuadraticRelationMap, LinearMap.comp_apply, DFinsupp.lsingle_apply, x]
    rw [arrowMul_arrow k G ⟨(j.1, l.1), (G.mem_neighborSet j.1 l.1).mp l.2⟩
      ⟨(l.1, j.1), ((G.mem_neighborSet j.1 l.1).mp l.2).symm⟩ rfl]
    have hrev : (⟨(l.1, j.1), ((G.mem_neighborSet j.1 l.1).mp l.2).symm⟩ : G.Dart) =
        (⟨(j.1, l.1), (G.mem_neighborSet j.1 l.1).mp l.2⟩ : G.Dart).symm := by
      apply SimpleGraph.Dart.ext
      rw [SimpleGraph.Dart.symm_toProd]
      rfl
    rw [ite_eq_left hrev]
  · let x := zigzagProjectiveBasisFun k G i (.inr (.inl ⟨⟨(i, j.1), (G.mem_neighborSet i j.1).mp
    j.2⟩, rfl⟩))
    refine ⟨DFinsupp.single (.inr (j, j')) x, ?_⟩
    simp only [zigzagProjectiveQuadraticDifferential_single,
      zigzagProjectiveQuadraticRelationMap, LinearMap.comp_apply, LinearMap.sub_apply,
        DFinsupp.lsingle_apply, x]
    rw [arrowMul_arrow k G ⟨(j.1, i), ((G.mem_neighborSet i j.1).mp j.2).symm⟩
      ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ rfl,
      arrowMul_arrow k G ⟨(j'.1, i), ((G.mem_neighborSet i j'.1).mp j'.2).symm⟩
      ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ rfl]
    have hne : (⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ : G.Dart) ≠
        (⟨(j'.1, i), ((G.mem_neighborSet i j'.1).mp j'.2).symm⟩ : G.Dart).symm := by
      intro h
      exact hj' (Subtype.ext (by simpa using (congrArg (fun d : G.Dart => d.snd) h).symm))
    have hrev : (⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ : G.Dart) =
        (⟨(j.1, i), ((G.mem_neighborSet i j.1).mp j.2).symm⟩ : G.Dart).symm := by
      apply SimpleGraph.Dart.ext
      rw [SimpleGraph.Dart.symm_toProd]
      rfl
    rw [ite_eq_left hrev, ite_eq_right hne]
    simp

-- A linear normal-form section: lift each outgoing arrow to its neighbour generator and
-- lift the volume through one fixed backtrack. It is only used to prove exactness.
open Classical in
private noncomputable def arrowSumSection
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V) (j₀ : G.neighborSet i) :
    zigzagProjective k G i →ₗ[k] ZigzagNeighborProjectives k G i :=
  (zigzagProjectiveBasis k G hns i).constr k fun b => match b with
    | .inl _ => 0
    | .inr (.inl d) => DFinsupp.single ⟨d.1.snd, (G.mem_neighborSet i d.1.snd).2 (by simpa only
      [d.2] using d.1.adj)⟩
        (zigzagProjectiveGenerator k G d.1.snd)
    | .inr (.inr _) => DFinsupp.single j₀ (zigzagProjectiveBasisFun k G j₀.1
        (.inr (.inl ⟨⟨(j₀.1, i), ((G.mem_neighborSet i j₀.1).mp j₀.2).symm⟩, rfl⟩)))

open Classical in
private theorem arrowSumSection_basis
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V) (j₀ : G.neighborSet i)
    (b : ZigzagProjectiveBasisIndex G i) :
    arrowSumSection k G hns i j₀ (zigzagProjectiveBasisFun k G i b) =
      match b with
      | .inl _ => 0
      | .inr (.inl d) => DFinsupp.single ⟨d.1.snd, (G.mem_neighborSet i d.1.snd).2 (by simpa only
        [d.2] using d.1.adj)⟩
          (zigzagProjectiveGenerator k G d.1.snd)
      | .inr (.inr _) => DFinsupp.single j₀ (zigzagProjectiveBasisFun k G j₀.1
          (.inr (.inl ⟨⟨(j₀.1, i), ((G.mem_neighborSet i j₀.1).mp j₀.2).symm⟩, rfl⟩))) := by
  rw [← zigzagProjectiveBasis_apply k G hns, arrowSumSection, Module.Basis.constr_basis]

open Classical in
private theorem single_basis_sub_section_mem_range
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V) (j₀ : G.neighborSet i)
    (hbranch : ∀ j : G.neighborSet i,
      (∃ l : G.neighborSet j.1, l.1 ≠ i) ∨ (∃ j' : G.neighborSet i, j' ≠ j))
    (j : G.neighborSet i) (b : ZigzagProjectiveBasisIndex G j.1) :
    DFinsupp.single j (zigzagProjectiveBasisFun k G j.1 b) -
      arrowSumSection k G hns i j₀
        (zigzagProjectiveArrowSum k G i (DFinsupp.single j (zigzagProjectiveBasisFun k G j.1 b))) ∈
      LinearMap.range (zigzagProjectiveQuadraticDifferential k G i) := by
  classical
  rcases b with a | e | a
  · -- The vertex generator is already in the normal-form complement.
    cases a
    rw [zigzagProjectiveBasisFun_inl, zigzagProjectiveArrowSum_single,
      arrowMul_generator k G ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩,
      arrowSumSection_basis]
    simpa only [sub_self] using
      (LinearMap.range (zigzagProjectiveQuadraticDifferential k G i)).zero_mem
  · -- Returning arrows differ from the chosen backtrack; nonreturning arrows are relators.
    by_cases hei : e.1.snd = i
    · have heq : e.1 = (⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ : G.Dart).symm := by
        apply SimpleGraph.Dart.ext
        exact Prod.ext e.2 hei
      rw [zigzagProjectiveArrowSum_single,
        arrowMul_arrow k G ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ e.1 e.2,
        ite_eq_left heq, ← zigzagProjectiveBasisFun_inr_inr k G i (), arrowSumSection_basis]
      have he : e = ⟨⟨(j.1, i), ((G.mem_neighborSet i j.1).mp j.2).symm⟩, rfl⟩ := by
        apply Subtype.ext
        exact heq
      rw [he]
      exact backtrack_difference_mem_range k G i j j₀
    · have hne : e.1 ≠ (⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ : G.Dart).symm := by
        intro h
        exact hei (by simpa using congrArg (fun d : G.Dart => d.snd) h)
      rw [zigzagProjectiveArrowSum_single,
        arrowMul_arrow k G ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ e.1 e.2,
        ite_eq_right hne, map_zero, sub_zero]
      have he : e.1 = (⟨(j.1, e.1.snd), (by simpa only [e.2] using e.1.adj)⟩ : G.Dart) := by
        apply SimpleGraph.Dart.ext
        exact Prod.ext e.2 rfl
      have hindex : e = ⟨⟨(j.1, e.1.snd), (by simpa only [e.2] using e.1.adj)⟩, rfl⟩ :=
        Subtype.ext he
      rw [hindex]
      exact single_arrow_mem_range k G i j
        ⟨e.1.snd, (G.mem_neighborSet j.1 e.1.snd).2 (by simpa only [e.2] using e.1.adj)⟩ hei
  · -- The remaining volume vector is generated using the additional incident edge.
    cases a
    rw [zigzagProjectiveBasisFun_inr_inr, zigzagProjectiveArrowSum_single,
      arrowMul_volume k G ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩, map_zero, sub_zero]
    exact single_volume_mem_range k G i hbranch j

open Classical in
private theorem single_sub_section_mem_range
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V) (j₀ : G.neighborSet i)
    (hbranch : ∀ j : G.neighborSet i,
      (∃ l : G.neighborSet j.1, l.1 ≠ i) ∨ (∃ j' : G.neighborSet i, j' ≠ j))
    (j : G.neighborSet i) (x : zigzagProjective k G j.1) :
    DFinsupp.single j x -
      arrowSumSection k G hns i j₀
        (zigzagProjectiveArrowSum k G i (DFinsupp.single j x)) ∈
      LinearMap.range (zigzagProjectiveQuadraticDifferential k G i) := by
  classical
  let inj : zigzagProjective k G j.1 →ₗ[k] ZigzagNeighborProjectives k G i :=
    DFinsupp.lsingle (R := k) (M := fun j : G.neighborSet i => zigzagProjective k G j.1) j
  let f : zigzagProjective k G j.1 →ₗ[k] ZigzagNeighborProjectives k G i :=
    inj - ((arrowSumSection k G hns i j₀).comp
      ((zigzagProjectiveArrowSum k G i).restrictScalars k)).comp inj
  have hf : ⊤ ≤ ((LinearMap.range (zigzagProjectiveQuadraticDifferential k G i)).restrictScalars
    k).comap f := by
    rw [← span_range_zigzagProjectiveBasisFun_eq_top k G j.1, Submodule.span_le,
      Set.range_subset_iff]
    intro b
    exact single_basis_sub_section_mem_range k G hns i j₀ hbranch j b
  exact hf (Submodule.mem_top : x ∈ (⊤ : Submodule k (zigzagProjective k G j.1)))

private theorem arrowSum_section
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V) (j₀ : G.neighborSet i)
    (x : zigzagProjective k G i) :
    zigzagProjectiveArrowSum k G i (arrowSumSection k G hns i j₀ x) =
      x - zigzagProjectiveHeadCoeff k G i x • zigzagProjectiveGenerator k G i := by
  classical
  let f := ((zigzagProjectiveArrowSum k G i).restrictScalars k).comp
    (arrowSumSection k G hns i j₀)
  let g : zigzagProjective k G i →ₗ[k] zigzagProjective k G i :=
    LinearMap.id - (zigzagProjectiveHeadCoeff k G i).smulRight
      (zigzagProjectiveGenerator k G i)
  have hfg : f = g := by
    apply (zigzagProjectiveBasis k G hns i).ext
    intro b
    simp only [f, g, LinearMap.comp_apply, LinearMap.restrictScalars_apply,
      zigzagProjectiveBasis_apply, arrowSumSection_basis,
      LinearMap.sub_apply, LinearMap.id_apply, LinearMap.smulRight_apply]
    rcases b with a | ⟨d, hd⟩ | a
    · rw [zigzagProjectiveBasisFun_inl, zigzagProjectiveHeadCoeff_generator]
      simp
    · rcases d with ⟨⟨a, v⟩, hadj⟩
      dsimp only at hd
      subst a
      simp only [zigzagProjectiveHeadCoeff_apply, coe_zigzagProjectiveBasisFun_inr_inl]
      rw [zigzagTrivialCoeff_ofArrow k G ⟨(i, v), hadj⟩]
      simp only [Pi.zero_apply, zero_smul, sub_zero]
      rw [zigzagProjectiveArrowSum_single, arrowMul_generator k G ⟨(i, v), hadj⟩]
    · rw [zigzagProjectiveArrowSum_single,
        arrowMul_arrow k G ⟨(i, j₀.1), (G.mem_neighborSet i j₀.1).mp j₀.2⟩
          ⟨(j₀.1, i), ((G.mem_neighborSet i j₀.1).mp j₀.2).symm⟩ rfl]
      have hrev : (⟨(j₀.1, i), ((G.mem_neighborSet i j₀.1).mp j₀.2).symm⟩ : G.Dart) =
          (⟨(i, j₀.1), (G.mem_neighborSet i j₀.1).mp j₀.2⟩ : G.Dart).symm := by
        apply SimpleGraph.Dart.ext
        rw [SimpleGraph.Dart.symm_toProd]
        rfl
      rw [ite_eq_left hrev, zigzagProjectiveBasisFun_inr_inr]
      simp only [zigzagProjectiveHeadCoeff_apply, coe_zigzagProjectiveVolume,
        zigzagTrivialCoeff_zigzagVolume, Pi.zero_apply, zero_smul, sub_zero]
  exact LinearMap.congr_fun hfg x

/-- **The first stage is exact:** the sum of all arrow maps has image the radical of `P_i`.
This statement also applies to an `A₂` component; no branching assumption is needed. -/
theorem range_zigzagProjectiveArrowSum
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V) :
    LinearMap.range (zigzagProjectiveArrowSum k G i) =
      zigzagProjectiveRadicalPower k G i 1 := by
  classical
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    induction x using DFinsupp.induction with
    | h0 => simp
    | @ha j y x _ _ ih =>
        rw [map_add, zigzagProjectiveArrowSum_single]
        exact (zigzagProjectiveRadicalPower k G i 1).add_mem
          (range_zigzagProjectiveArrowMul_le hns ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩
            (LinearMap.mem_range_self _ y)) ih
  · intro x hx
    obtain ⟨j, hj⟩ := hns i
    have hzero : zigzagProjectiveHeadCoeff k G i x = 0 := by
      have hx' : x ∈ (zigzagProjectiveRadicalPower k G i 1).restrictScalars k := hx
      rw [← ker_zigzagProjectiveHeadCoeff_eq_restrictScalars_radicalPower_one hns] at hx'
      exact hx'
    refine ⟨arrowSumSection k G hns i ⟨j, hj⟩ x, ?_⟩
    simp only [arrowSum_section, hzero, zero_smul, sub_zero]

/-- The arrow-sum map and the quotient onto the simple head are exact at `P_i`. -/
theorem range_zigzagProjectiveArrowSum_eq_ker_toHead
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V) :
    LinearMap.range (zigzagProjectiveArrowSum k G i) =
      LinearMap.ker (zigzagProjectiveToHead k G i) := by
  rw [range_zigzagProjectiveArrowSum k G hns i, ker_zigzagProjectiveToHead]

/-- **The second quadratic stage is exact.** The local branching hypothesis says that every
edge out of `i` has another incident edge at one of its endpoints; it excludes precisely an
`A₂` component at `i`. No hypothesis of Koszulity or exactness is assumed. -/
theorem range_zigzagProjectiveQuadraticDifferential_eq_ker
    (hns : ∀ v : V, ∃ w, G.Adj v w) (i : V)
    (hbranch : ∀ j : G.neighborSet i,
      (∃ l : G.neighborSet j.1, l.1 ≠ i) ∨ (∃ j' : G.neighborSet i, j' ≠ j)) :
    LinearMap.range (zigzagProjectiveQuadraticDifferential k G i) =
      LinearMap.ker (zigzagProjectiveArrowSum k G i) := by
  classical
  apply le_antisymm
  · exact LinearMap.range_le_ker_iff.2
      (zigzagProjectiveArrowSum_comp_quadraticDifferential k G i)
  · obtain ⟨j₀, hj₀⟩ := hns i
    let j : G.neighborSet i := ⟨j₀, hj₀⟩
    have hnormal (x : ZigzagNeighborProjectives k G i) :
        x - arrowSumSection k G hns i j (zigzagProjectiveArrowSum k G i x) ∈
          LinearMap.range (zigzagProjectiveQuadraticDifferential k G i) := by
      induction x using DFinsupp.induction with
      | h0 => simp
      | @ha d y x _ _ ih =>
          simpa only [map_add, add_sub_add_comm] using
            (LinearMap.range (zigzagProjectiveQuadraticDifferential k G i)).add_mem
              (single_sub_section_mem_range k G hns i j hbranch d y) ih
    intro x hx
    simpa only [LinearMap.mem_ker.mp hx, map_zero, sub_zero] using hnormal x

/-- The first differential raises the unshifted path degree by one. Thus it has degree zero
when each neighbouring projective is shifted by one. -/
theorem zigzagProjectiveArrowSum_mem_grade (i : V) {p : ℤ}
    {x : ZigzagNeighborProjectives k G i}
    (hx : ∀ j, x j ∈ zigzagProjectiveGrade k G j.1 p) :
    zigzagProjectiveArrowSum k G i x ∈ zigzagProjectiveGrade k G i (p + 1) := by
  classical
  simp only [zigzagProjectiveArrowSum, DFinsupp.lsum_apply_apply,
    DFinsupp.sumAddHom_apply, DFinsupp.sum, LinearMap.toAddMonoidHom_coe]
  exact Submodule.sum_mem _ fun j _ => zigzagProjectiveArrowMul_mem_grade k G
    ⟨(i, j.1), (G.mem_neighborSet i j.1).mp j.2⟩ (hx j)

open Classical in
private theorem single_arrow_mem_grade (i : V) (j j' : G.neighborSet i)
    {l : V} (h : G.Adj j.1 l) {p : ℤ} {x : zigzagProjective k G l}
    (hx : x ∈ zigzagProjectiveGrade k G l p) :
    (DFinsupp.single j (zigzagProjectiveArrowMul k G ⟨(j.1, l), h⟩ x) :
      ZigzagNeighborProjectives k G i) j' ∈ zigzagProjectiveGrade k G j'.1 (p + 1) := by
  classical
  by_cases hne : j' = j
  · subst j'
    rw [DFinsupp.single_eq_same]
    exact zigzagProjectiveArrowMul_mem_grade k G ⟨(j.1, l), h⟩ hx
  · rw [DFinsupp.single_eq_of_ne hne]
    exact Submodule.zero_mem _

/-- Each quadratic relation map raises the degree by one in its neighbouring-projective
coordinates. Its source generator therefore has total degree two after the neighbouring shift. -/
theorem zigzagProjectiveQuadraticRelationMap_mem_grade (i : V)
    (r : ZigzagQuadraticRelationIndex G i) {p : ℤ}
    {x : zigzagProjective k G r.vertex}
    (hx : x ∈ zigzagProjectiveGrade k G r.vertex p) (j : G.neighborSet i) :
    zigzagProjectiveQuadraticRelationMap k G i r x j ∈
      zigzagProjectiveGrade k G j.1 (p + 1) := by
  classical
  rcases r with ⟨j', l⟩ | ⟨j', j''⟩
  · simp only [zigzagProjectiveQuadraticRelationMap, LinearMap.comp_apply,
      DFinsupp.lsingle_apply]
    exact single_arrow_mem_grade k G i j' j ((G.mem_neighborSet j'.1 l.1.1).mp l.1.2) hx
  · simp only [zigzagProjectiveQuadraticRelationMap, LinearMap.sub_apply,
      LinearMap.comp_apply, DFinsupp.lsingle_apply, DFinsupp.sub_apply]
    exact (zigzagProjectiveGrade k G j.1 (p + 1)).sub_mem
      (single_arrow_mem_grade k G i j' j ((G.mem_neighborSet i j'.1).mp j'.2).symm hx)
      (single_arrow_mem_grade k G i j'' j ((G.mem_neighborSet i j''.1).mp j''.2).symm hx)

/-- The second differential raises each unshifted coordinate degree by one. Shifting its source
projectives by two and the neighbouring projectives by one makes it degree zero. -/
theorem zigzagProjectiveQuadraticDifferential_mem_grade (i : V) {p : ℤ}
    {x : ZigzagQuadraticRelationProjectives k G i}
    (hx : ∀ r, x r ∈ zigzagProjectiveGrade k G r.vertex p) (j : G.neighborSet i) :
    zigzagProjectiveQuadraticDifferential k G i x j ∈
      zigzagProjectiveGrade k G j.1 (p + 1) := by
  classical
  simp only [zigzagProjectiveQuadraticDifferential, DFinsupp.lsum_apply_apply,
    DFinsupp.sumAddHom_apply, DFinsupp.sum, LinearMap.toAddMonoidHom_coe,
    DFinsupp.finsetSum_apply]
  exact Submodule.sum_mem _ fun r _ =>
    zigzagProjectiveQuadraticRelationMap_mem_grade k G i r (hx r) j

/-- The neighbouring direct sum is a projective module. -/
instance projective_zigzagNeighborProjectives (i : V) :
    Module.Projective Z (ZigzagNeighborProjectives k G i) := by
  let : ∀ j : G.neighborSet i, Module.Projective Z (zigzagProjective k G j.1) :=
    fun j => zigzagProjective_projective k G j.1
  infer_instance

/-- The direct sum indexed by the quadratic relations is a projective module. -/
instance projective_zigzagQuadraticRelationProjectives (i : V) :
    Module.Projective Z (ZigzagQuadraticRelationProjectives k G i) := by
  let : ∀ r : ZigzagQuadraticRelationIndex G i,
      Module.Projective Z (zigzagProjective k G r.vertex) :=
    fun r => zigzagProjective_projective k G r.vertex
  infer_instance

end TauCeti
