/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.D4.Tripled.BaseChange
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot
import TauCeti.LinearAlgebra.Matrix.Cartan.TypeD

/-!
# Generation of the tripled type-D4 weight torus by root subgroups

The tripled type-`D₄` carrier is defined from its eight positive and negative numbered simple-root
subgroups together with its rank-four split weight torus. This file proves that, over every
commutative ring, the torus is already contained in the elementary subgroup generated by those
root subgroups.

The represented simple generators at each node form an `sl₂` triple by
`TauCeti.D4Tripled.isSl2Triple_rep_serreRootGenerator`, and every row of the type-`D₄` Cartan
matrix has the explicit Bezout certificate `TauCeti.sum_cartanMatrixD_mul_typeDCartanBezout`, so
every simple root is a primitive character of the weight torus. The generic Kostant
coroot-generation theorem then makes the torus redundant in the pointwise generating family.

Testing that containment over the coordinate ring of the universal weight-torus point upgrades it
to the scheme-theoretic statement: the toral-closure and root-generated defining ideals over `ℤ`
agree, so the torus is redundant among the scheme-theoretic generators as well, and the canonical
comparison of the two carriers is an isomorphism. The equality of ideals survives transport along
`ℤ → A`. It does not say that the transported integral carrier is the subgroup generated anew by
the root subgroups over a non-flat base.

## Main results

* `TauCeti.D4Tripled.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in the
  elementary subgroup over every commutative ring.
* `TauCeti.D4Tripled.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining the
  weight torus to all numbered root subgroups gives exactly the elementary subgroup.
* `TauCeti.D4Tripled.definingIdeal_eq_kostantGeneratedDefiningIdeal`: the integral toral-closure
  carrier is already the root-generated carrier.
* `TauCeti.D4Tripled.groupScheme_eq_kostantGeneratedGroupScheme` and
  `TauCeti.D4Tripled.isIso_kostantGeneratedToToral`: the corresponding group schemes agree and
  their canonical comparison is an isomorphism.
* `TauCeti.D4Tripled.baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal`: the
  corresponding equality in the transported presentation over every commutative ring.
* `TauCeti.D4Tripled.groupScheme_hom_ext_of_rootSubgroup`: a morphism out of the carrier is
  determined by its restrictions to the numbered root subgroups alone.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.
* `TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.Generation`, whose formal template this file
  follows with the tripled weights in place of the spin weights.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace TauCeti.D4Tripled

open CategoryTheory
open TauCeti.DynkinType TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

/-- Over every commutative ring, the tripled type-`D₄` weight torus on the base-changed
admissible lattice is contained in the elementary group generated by the positive and negative
numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup lattice.toAddSubgroup latticeBasis d4TripledWeight A ≤
      kostantElementarySubgroup (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  kostantTorusSubgroup_le_kostantElementarySubgroup
    (TauCeti.serreRootGenerator weightTable.cartanMatrix)
    (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis d4TripledWeight
    isCartanWeightVector_latticeBasis (TypeDStd.rootGeneratorWeight 4)
    lie_serreH_serreRootGenerator Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator
    (fun i => funext fun j => by simp) (typeDCartanBezout 4)
    (fun i => by
      simpa only [TypeDStd.rootGeneratorWeight_inl] using
        sum_cartanMatrixD_mul_typeDCartanBezout (n := 4) (by norm_num) i) A

/-- Over every commutative ring, adjoining the tripled type-`D₄` weight torus to all positive and
negative numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
        d4TripledWeight Set.univ A =
      kostantElementarySubgroup (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  (kostantTorusSubsystemSubgroup_univ _ _ _ _ _ _ _ _ A).trans
    (sup_eq_left.2 ((kostantTorusSubgroup_eq_range _ _ _ A).symm.trans_le
      (weightTorusSubgroup_le_elementarySubgroup A)))

/-! ## Scheme-theoretic generation -/

private theorem universalWeightTorus_mem_elementarySubgroup :
    let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup (Fin 4))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin 4))) A :=
      WithConv.toConv (AlgHom.id ℤ T)
    kostantTorusPoints lattice.toAddSubgroup latticeBasis d4TripledWeight A
        (SplitTorus.pointsMulEquiv q) ∈
      kostantElementarySubgroup (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A := by
  intro T A q
  exact weightTorusSubgroup_le_elementarySubgroup A
    ((kostantTorusSubgroup_eq_range _ _ _ A).ge ⟨_, rfl⟩)

/-- **The tripled type-`D₄` carrier is generated scheme-theoretically by its eight numbered root
subgroups.** Adjoining the represented weight torus does not change the integral defining Hopf
ideal. -/
theorem definingIdeal_eq_kostantGeneratedDefiningIdeal :
    definingIdeal =
      kostantGeneratedDefiningIdeal (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis := by
  rw [definingIdeal_def]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      _ _ _ _ _ _ _ d4TripledWeight universalWeightTorus_mem_elementarySubgroup

/-- The tripled type-`D₄` carrier is the group scheme generated by its eight numbered positive and
negative simple root subgroups. -/
theorem groupScheme_eq_kostantGeneratedGroupScheme :
    groupScheme =
      kostantGeneratedGroupScheme (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis :=
  kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ d4TripledWeight universalWeightTorus_mem_elementarySubgroup

/-- The canonical inclusion of the root-generated tripled type-`D₄` carrier into its toral closure
is an isomorphism. -/
instance isIso_kostantGeneratedToToral :
    CategoryTheory.IsIso
      (kostantGeneratedToToral (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
        d4TripledWeight) :=
  isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ d4TripledWeight universalWeightTorus_mem_elementarySubgroup

/-- After base change to any commutative ring, the transported tripled type-`D₄` carrier ideal is
the transport of the root-generated integral ideal. This does not identify it with the common
kernel of the root-subgroup maps formed anew over that ring. -/
theorem baseChangeDefiningIdeal_eq_kostantGeneratedGeneralLinearBaseChangeIdeal
    (A : Type v) [CommRing A] :
    baseChangeDefiningIdeal A =
      kostantGeneratedGeneralLinearBaseChangeIdeal
        (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis A := by
  rw [baseChangeDefiningIdeal_def]
  exact kostantToralBaseChangePresentationIdeal_eq_generated_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ d4TripledWeight universalWeightTorus_mem_elementarySubgroup A

/-- **Two morphisms out of the tripled type-`D₄` carrier agree as soon as they agree on its eight
numbered root subgroups.** This drops the weight-torus hypothesis of
`TauCeti.D4Tripled.groupScheme_hom_ext`, which root generation of the carrier makes redundant. -/
@[ext high]
theorem groupScheme_hom_ext_of_rootSubgroup {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (f g : groupScheme ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup k ≫ f = rootSubgroup k ≫ g) :
    f = g :=
  kostantToralGroupScheme_hom_ext_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ d4TripledWeight universalWeightTorus_mem_elementarySubgroup f g
    fun k => by simpa only [rootSubgroup_def] using hroot k

end TauCeti.D4Tripled
