/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.LinearAlgebra.RootSystem.Base
public import TauCeti.LinearAlgebra.RootSystem.WeylGroup
import Mathlib.Algebra.Group.Submonoid.Membership
import Mathlib.GroupTheory.OrderOfElement

public section

/-!
# Generation of the Weyl group by simple reflections

For a base of a finite reduced crystallographic root system, every root reflection belongs to the
subgroup generated by the reflections in the simple roots. Since the Weyl group is generated by all
root reflections, the simple reflections generate the Weyl group, so every Weyl-group element is
the product of a word in the simple roots of the base.

The proof uses Mathlib's `RootPairing.Base.induction_reflect`,
`RootPairing.reflection_reflectionPerm`, and `RootPairing.weylGroup.induction`: reflecting a
positive root in a simple root conjugates its reflection by the corresponding simple reflection,
while root negation does not change the reflection.

## Main definitions

* `TauCeti.wordProd` is the product of the simple reflections named by a word in the simple roots
  of a base.

## Main results

* `TauCeti.weylGroup_eq_closure_simple` identifies the Weyl group with the subgroup generated by
  its simple reflections.
* `TauCeti.exists_wordProd_eq` writes every Weyl-group element as the product of a word.

## References

This file implements “Simple reflections generate” in Layer 2 of
`TauCetiRoadmap/RepresentationTheory/RootSystems/README.md`. The argument follows the standard
positive-root induction described there.
-/

namespace TauCeti

open Set

universe u v w x

variable {ι : Type u} {R : Type v} {M : Type w} {N : Type x}
  [CommRing R] [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
  (P : RootPairing ι R M N)

private lemma ofIdx_reflectionPerm_self_eq (i : ι) :
    RootPairing.weylGroup.ofIdx P (P.reflectionPerm i i) =
    RootPairing.weylGroup.ofIdx P i := by
  rw [RootPairing.ofIdx_reflectionPerm P i i]
  have hsquare :
      RootPairing.weylGroup.ofIdx P i * RootPairing.weylGroup.ofIdx P i = 1 := by
    rw [mul_eq_one_iff_eq_inv, RootPairing.ofIdx_inv]
  rw [hsquare, one_mul]

/-! ## Words in the simple reflections -/

section Word

variable (b : P.Base)

/-- The product of the simple reflections named by a word in the simple roots of `b`, read from
the left. -/
noncomputable def wordProd (L : List b.support) : P.weylGroup :=
  (L.map fun i : b.support ↦ RootPairing.weylGroup.ofIdx P (i : ι)).prod

@[simp]
lemma wordProd_nil : wordProd P b [] = 1 := by
  simp [wordProd]

@[simp]
lemma wordProd_cons (i : b.support) (L : List b.support) :
    wordProd P b (i :: L) =
      RootPairing.weylGroup.ofIdx P (i : ι) * wordProd P b L := by
  simp [wordProd]

/-- A one-letter word is the simple reflection it names. -/
lemma wordProd_singleton (i : b.support) :
    wordProd P b [i] = RootPairing.weylGroup.ofIdx P (i : ι) := by
  simp

lemma wordProd_append (L L' : List b.support) :
    wordProd P b (L ++ L') = wordProd P b L * wordProd P b L' := by
  simp [wordProd, List.prod_append]

lemma wordProd_concat (L : List b.support) (i : b.support) :
    wordProd P b (L ++ [i]) =
      wordProd P b L * RootPairing.weylGroup.ofIdx P (i : ι) := by
  rw [wordProd_append]
  simp

/-- Reversing a word inverts its product, because each letter is an involution. -/
@[simp]
lemma wordProd_reverse (L : List b.support) :
    wordProd P b L.reverse = (wordProd P b L)⁻¹ := by
  simp [wordProd, List.map_reverse, List.prod_reverse_noncomm, Function.comp_def]

end Word

/-! ## The simple reflections generate -/

section Generation

variable [Finite ι] [CharZero R] [IsDomain R] [P.IsCrystallographic] [P.IsReduced] (b : P.Base)

private lemma ofIdx_mem_closure_simple (i : ι) :
    RootPairing.weylGroup.ofIdx P i ∈
      Subgroup.closure (range fun j : b.support =>
        RootPairing.weylGroup.ofIdx P (j : ι)) := by
  letI := P.indexNeg
  apply b.induction_reflect i
  · intro j hj
    rwa [ofIdx_reflectionPerm_self_eq P j]
  · intro j hj
    exact Subgroup.subset_closure ⟨⟨j, hj⟩, rfl⟩
  · intro j k hj hk
    rw [RootPairing.ofIdx_reflectionPerm P j k]
    exact mul_mem (mul_mem (Subgroup.subset_closure ⟨⟨k, hk⟩, rfl⟩) hj)
      (Subgroup.subset_closure ⟨⟨k, hk⟩, rfl⟩)

/-- The simple reflections associated to a base generate the Weyl group. -/
theorem weylGroup_eq_closure_simple :
    (⊤ : Subgroup P.weylGroup) =
      Subgroup.closure (range fun i : b.support =>
        RootPairing.weylGroup.ofIdx P (i : ι)) := by
  apply le_antisymm
  · rintro ⟨w, hw⟩ -
    induction hw using RootPairing.weylGroup.induction with
    | mem i => exact ofIdx_mem_closure_simple P b i
    | one => exact one_mem _
    | mul g h hg hh hgm hhm =>
      exact mul_mem hgm hhm
  · exact le_top

/-- Every Weyl-group element is the product of a word in the simple reflections. -/
theorem exists_wordProd_eq (w : P.weylGroup) :
    ∃ L : List b.support, wordProd P b L = w := by
  have hw :
      w ∈ Submonoid.closure (range fun i : b.support =>
        RootPairing.weylGroup.ofIdx P (i : ι)) := by
    have hclosure :
        (Subgroup.closure (range fun i : b.support =>
          RootPairing.weylGroup.ofIdx P (i : ι))).toSubmonoid =
            Submonoid.closure (range fun i : b.support =>
              RootPairing.weylGroup.ofIdx P (i : ι)) := by
      apply Subgroup.closure_toSubmonoid_of_isOfFinOrder
      rintro x ⟨i, rfl⟩
      exact isOfFinOrder_iff_pow_eq_one.2 ⟨2, Nat.zero_lt_succ 1, by
        rw [sq, mul_eq_one_iff_eq_inv, RootPairing.ofIdx_inv P i]⟩
    rw [← hclosure, ← weylGroup_eq_closure_simple P b]
    exact Submonoid.mem_top w
  rw [← FreeMonoid.mrange_lift] at hw
  obtain ⟨l, hl⟩ := MonoidHom.mem_mrange.mp hw
  exact ⟨l.toList, by simpa only [wordProd, FreeMonoid.lift_apply] using hl⟩

/-- Deprecated compatibility statement for the old name, which spelled out the list product now
packaged as `TauCeti.wordProd`. -/
@[deprecated exists_wordProd_eq (since := "2026-07-30")]
theorem exists_list_prod_ofIdx_eq (w : P.weylGroup) :
    ∃ l : List b.support,
      (l.map fun (i : b.support) => RootPairing.weylGroup.ofIdx P (i : ι)).prod = w :=
  exists_wordProd_eq P b w

end Generation

end TauCeti
