/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ModularForms.Newforms.Coefficient
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import TauCeti.NumberTheory.MulChar.Basic
import TauCeti.NumberTheory.ModularForms.Newforms.FullEigenform
import Mathlib.Data.Nat.Factorization.Induction

/-!
# Fields generated by newform coefficients and nebentypus values

The coefficient field of a newform is the subfield of `ℂ` generated over `ℚ` by its positive
Fourier coefficients. The character field is generated by the values of its nebentypus. The
good-prime Hecke recurrence recovers character values at good primes from two Fourier
coefficients, and prime factorization extends the field inclusion to every character value.
This inclusion supplies the base field
for studying Galois conjugates within a fixed nebentypus space. Conversely, the Hecke
recurrences generate every coefficient from those at the primes and the character values, so a
subfield of `ℂ` contains the coefficient field exactly when it contains these
(`CoefficientField_le_iff_forall_prime_and_char`).

Use `TauCeti.CharacterField χ` for the character field, or `CharacterField χ` after
`open TauCeti`. Its defining equation, generator membership, and containment criterion are
`CharacterField_def`, `char_mem_CharacterField`, and `CharacterField_le_iff` in the same namespace.

The construction follows the coefficient-field convention of Shimura, *Introduction to the
Arithmetic Theory of Automorphic Functions*, §3. The recurrence is Diamond–Shurman,
*A First Course in Modular Forms*, Proposition 5.8.5.
-/

public section

noncomputable section

open UpperHalfPlane

namespace TauCeti

variable {N : ℕ} {k : ℤ}

/-- The subfield of `ℂ` generated over `ℚ` by the positive-index Fourier coefficients of a
newform. -/
def CoefficientField [NeZero N] (f : HeckeRing.GL2.Newform N k) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ
    (Set.range fun n : ℕ+ => (qExpansion 1 f.toCuspForm).coeff (n : ℕ))

/-- The coefficient field as an adjoin of positive-index Fourier coefficients. -/
theorem CoefficientField_def [NeZero N] (f : HeckeRing.GL2.Newform N k) :
    CoefficientField f = IntermediateField.adjoin ℚ
      (Set.range fun n : ℕ+ => (qExpansion 1 f.toCuspForm).coeff (n : ℕ)) := by
  unfold CoefficientField
  rfl

/-- The Fourier coefficients generating `CoefficientField` belong to it. -/
@[simp]
theorem coeff_mem_CoefficientField [NeZero N] (f : HeckeRing.GL2.Newform N k) (n : ℕ+) :
    (qExpansion 1 f.toCuspForm).coeff (n : ℕ) ∈ CoefficientField f :=
  IntermediateField.subset_adjoin ℚ _ ⟨n, rfl⟩

/-- A field contains `CoefficientField f` exactly when it contains every positive-index
Fourier coefficient of `f`. -/
@[simp]
theorem CoefficientField_le_iff [NeZero N] (f : HeckeRing.GL2.Newform N k)
    (K : IntermediateField ℚ ℂ) :
    CoefficientField f ≤ K ↔
      ∀ n : ℕ+, (qExpansion 1 f.toCuspForm).coeff (n : ℕ) ∈ K := by
  simp only [CoefficientField, IntermediateField.adjoin_le_iff, Set.range_subset_iff,
    SetLike.mem_coe]

/-- The subfield of `ℂ` generated over `ℚ` by the values of a nebentypus character. -/
def CharacterField (χ : (ZMod N)ˣ →* ℂˣ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (Set.range fun u : (ZMod N)ˣ => (χ u : ℂ))

/-- The character field as an adjoin of character values. -/
theorem CharacterField_def (χ : (ZMod N)ˣ →* ℂˣ) :
    CharacterField χ =
      IntermediateField.adjoin ℚ (Set.range fun u : (ZMod N)ˣ => (χ u : ℂ)) := by
  unfold CharacterField
  rfl

/-- Every value of the nebentypus belongs to its character field. -/
@[simp]
theorem char_mem_CharacterField (χ : (ZMod N)ˣ →* ℂˣ) (u : (ZMod N)ˣ) :
    (χ u : ℂ) ∈ CharacterField χ :=
  IntermediateField.subset_adjoin ℚ _ ⟨u, rfl⟩

/-- A field contains `CharacterField χ` exactly when it contains every value of `χ`. -/
@[simp]
theorem CharacterField_le_iff (χ : (ZMod N)ˣ →* ℂˣ) (K : IntermediateField ℚ ℂ) :
    CharacterField χ ≤ K ↔ ∀ u : (ZMod N)ˣ, (χ u : ℂ) ∈ K := by
  simp only [CharacterField, IntermediateField.adjoin_le_iff, Set.range_subset_iff,
    SetLike.mem_coe]

/-- At a prime `p` coprime to the level, the Hecke recurrence gives
`χ(p) = (a_p^2 - a_{p^2}) / p^(k-1)`. -/
theorem char_prime_eq_coeff [NeZero N] (f : HeckeRing.GL2.Newform N k)
    {p : ℕ} (hp : p.Prime) (hpN : Nat.Coprime p N) :
    (f.χ (ZMod.unitOfCoprime p hpN) : ℂ) =
      ((qExpansion 1 f.toCuspForm).coeff p * (qExpansion 1 f.toCuspForm).coeff p -
        (qExpansion 1 f.toCuspForm).coeff (p ^ 2)) / (p : ℂ) ^ (k - 1) := by
  have hp0 : (p : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr hp.ne_zero
  have hpow : (p : ℂ) ^ (k - 1) ≠ 0 := zpow_ne_zero _ hp0
  have hrec := f.toEigenformAwayFromLevel.qExpansion_coeff_prime_pow_add_two f.isNorm
    (p := ⟨p, hp.pos⟩) hp hpN 0
  have hrec' : (qExpansion 1 f.toCuspForm).coeff (p ^ 2) =
      (qExpansion 1 f.toCuspForm).coeff p * (qExpansion 1 f.toCuspForm).coeff p -
        (f.χ (ZMod.unitOfCoprime p hpN) : ℂ) * (p : ℂ) ^ (k - 1) := by
    simpa [f.isNorm] using hrec
  apply (eq_div_iff hpow).mpr
  linear_combination hrec'

/-- The nebentypus value at a good prime belongs to the coefficient field. -/
theorem char_prime_mem_CoefficientField [NeZero N] (f : HeckeRing.GL2.Newform N k)
    {p : ℕ} (hp : p.Prime) (hpN : Nat.Coprime p N) :
    (f.χ (ZMod.unitOfCoprime p hpN) : ℂ) ∈ CoefficientField f := by
  let K := CoefficientField f
  rw [char_prime_eq_coeff f hp hpN]
  exact K.div_mem
    (K.sub_mem (K.mul_mem (coeff_mem_CoefficientField f ⟨p, hp.pos⟩)
      (coeff_mem_CoefficientField f ⟨p, hp.pos⟩))
      (coeff_mem_CoefficientField f ⟨p ^ 2, pow_pos hp.pos _⟩))
    (K.pow_mem (K.natCast_mem p) _)

/-- Every value of the nebentypus of a newform lies in its coefficient field. -/
@[simp]
theorem char_mem_CoefficientField [NeZero N] (f : HeckeRing.GL2.Newform N k)
    (u : (ZMod N)ˣ) : (f.χ u : ℂ) ∈ CoefficientField f := by
  let K := CoefficientField f
  have hnat : ∀ n : ℕ, ∀ hn : Nat.Coprime n N,
      (f.χ (ZMod.unitOfCoprime n hn) : ℂ) ∈ K := by
    intro n
    induction n using induction_on_primes with
    | zero =>
        intro hn
        have hN : N = 1 := by simpa using hn
        subst N
        have hu : ZMod.unitOfCoprime 0 hn = (1 : (ZMod 1)ˣ) := Subsingleton.elim _ _
        simp [hu]
    | one =>
        intro hn
        have hu : ZMod.unitOfCoprime 1 hn = (1 : (ZMod N)ˣ) :=
          Units.ext (by simp)
        simp [hu]
    | prime_mul p n hp ih =>
        intro hpn
        obtain ⟨hpN, hnN⟩ := Nat.coprime_mul_iff_left.mp hpn
        rw [ZMod.unitOfCoprime_mul hpN hnN, map_mul]
        exact K.mul_mem (char_prime_mem_CoefficientField f hp hpN) (ih hnN)
  obtain ⟨n, hn, rfl⟩ := ZMod.exists_unitOfCoprime_eq (d := N) u
  exact hnat n hn

/-- The field generated by the nebentypus values of a newform is a subfield of its
coefficient field. -/
theorem CharacterField_le_CoefficientField [NeZero N] (f : HeckeRing.GL2.Newform N k) :
    CharacterField f.χ ≤ CoefficientField f :=
  (CharacterField_le_iff f.χ (CoefficientField f)).mpr (char_mem_CoefficientField f)

/-- A field contains `CoefficientField f` exactly when it contains the Fourier coefficients of
`f` at the primes and the values of its nebentypus. The coefficients at the remaining indices
follow from the Hecke recurrences. -/
theorem CoefficientField_le_iff_forall_prime_and_char [NeZero N]
    (f : HeckeRing.GL2.Newform N k)
    (K : IntermediateField ℚ ℂ) :
    CoefficientField f ≤ K ↔
      (∀ p : ℕ, p.Prime → (qExpansion 1 f.toCuspForm).coeff p ∈ K) ∧
        ∀ u : (ZMod N)ˣ, (f.χ u : ℂ) ∈ K := by
  refine ⟨fun h ↦ ⟨fun p hp ↦ h (coeff_mem_CoefficientField f ⟨p, hp.pos⟩),
    fun u ↦ h (char_mem_CoefficientField f u)⟩, fun ⟨ha, hχ⟩ ↦ ?_⟩
  refine (CoefficientField_le_iff f K).mpr fun n ↦ ?_
  have hχ' : ∀ p : ℕ,
      (MulChar.ofUnitHom f.toEigenform.χ : DirichletCharacter ℂ N) p ∈ K := by
    intro p
    simpa only [HeckeRing.GL2.Newform.toEigenform_χ] using
      MulChar.apply_mem_of_forall_unit (MulChar.ofUnitHom f.χ) K
        (fun u ↦ by simpa only [MulChar.ofUnitHom_coe] using hχ u) (p : ZMod N)
  have hn := f.toEigenform.qExpansion_coeff_mem_of_forall_prime
    f.toEigenform_qExpansion_coeff_one K (by simpa using ha)
    (fun p _ ↦ mul_mem (hχ' p) (zpow_mem (natCast_mem K p) _)) n
  simpa using hn

end TauCeti
