/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ModularForms.Fricke.OldSpace
public import TauCeti.NumberTheory.ModularForms.Newforms.Conjugate
public import TauCeti.NumberTheory.ModularForms.Newforms.MultiplicityOne
public import TauCeti.NumberTheory.ModularForms.Newforms.Newform
import TauCeti.NumberTheory.ModularForms.AtkinLehner.Hecke
import TauCeti.NumberTheory.ModularForms.Fricke.Hecke
import TauCeti.NumberTheory.ModularForms.Newforms.PeterssonAdjoint
import TauCeti.NumberTheory.ModularForms.Newforms.RingEigenvalue
import TauCeti.NumberTheory.ModularForms.Parity
import TauCeti.NumberTheory.ModularForms.Petersson.Conjugate
import TauCeti.NumberTheory.ModularForms.Petersson.AtkinLehner
import TauCeti.NumberTheory.ModularForms.TrivialNebentypus

/-!
# The Fricke sign and the Fricke pseudo-eigenvalue of a newform

For a newform `f` of level `N`, weight `k` and trivial nebentypus, the normalized Fricke
operator `𝒲_N f = (√N) ^ (2 - k) • (f ∣[k] !![0, -1; N, 0])` is `ε_N · f` for a sign
`ε_N ∈ {1, -1}`, the **Fricke sign** (or Fricke eigenvalue) of `f`. The sign of the functional
equation of `L(s, f)` is `i ^ k · ε_N`.

The argument has three inputs.

* `𝒲_N` preserves the new subspace. It preserves the old subspace
  (`TauCeti.normalizedFrickeOperatorCusp_mem_cuspFormsOld`) and its Petersson adjoint is
  `(-1) ^ k • 𝒲_N`, so it preserves the orthogonal complement.
* On `S_k(N, 1)` the operator `𝒲_N` commutes with the Hecke operators `Tₙ` for `n` prime to `N`.
  At the trivial character the nebentypus-twisted Hecke sum is the plain `Γ₀(N)` slash sum
  (`HeckeRing.GL2.twistedHeckeSlashSum_eq_heckeSlashSum`). That sum commutes with the Fricke
  slash coset by coset
  (`TauCeti.commute_atkinLehnerOperatorCusp_heckeSlashGamma0CuspFormEnd`), and the ring elements
  `Tₙ` with `(n, N) = 1` are generated by double cosets of determinant prime to `N`
  (`HeckeRing.GL2.heckeTCompositeGamma0_mem_closure_coprimeDetCoset`).
* Multiplicity one, in the form
  `HeckeRing.GL2.exists_eq_smul_of_commute_heckeRingHomCusp_of_mem_cuspFormsNew` for a
  commuting involution. `𝒲_N f` is then a good Hecke eigenvector in the new part with the same
  eigenvalues as `f`, hence a multiple `ε • f`, and `𝒲_N ∘ 𝒲_N = (-1) ^ k` forces `ε ^ 2 = 1`,
  since `(-1) ^ k = 1` by the parity lemma when `f ≠ 0` has trivial nebentypus.

For a nontrivial nebentypus `χ` the operator `𝒲_N` carries `S_k(N, χ)` to `S_k(N, χ⁻¹)`, and a
newform goes to a multiple of its conjugate newform `f_ρ`, not of itself (Miyake,
Theorem 4.6.15(2)): `𝒲_N f = λ_N(f) • f_ρ`, the scalar `λ_N(f)` being the **Fricke
pseudo-eigenvalue** of Atkin and Li. The argument is the same multiplicity-one step, now in
`S_k(N, χ⁻¹)`: Fricke multiplies the good eigenvalue `λ_p` by `χ(p)⁻¹`
(`TauCeti.heckeTCuspNat_normalizedFrickeOperatorCusp_eq_smul_iff_heckeTCuspNat_eq_smul`), and
`χ(p)⁻¹ λ_p = conj λ_p` is the eigenvalue of `f_ρ` at `p`. Unitarity of `𝒲_N` and of
`f ↦ f_ρ` for the Petersson product gives `|λ_N(f)| = 1`. For trivial nebentypus `f_ρ = f`, and
the pseudo-eigenvalue is the Fricke sign.

## Main results

* `TauCeti.normalizedFrickeOperatorCusp_mem_cuspFormsNew`,
  `TauCeti.cuspFormsNew_map_normalizedFrickeOperatorCusp`: `𝒲_N` maps the new subspace onto
  itself.
* `TauCeti.commute_normalizedFrickeCharCuspOneEnd_heckeRingHomCuspCharSpace`: on `S_k(N, 1)`,
  `𝒲_N` commutes with `Tₙ` for every `n` prime to `N`.
* `TauCeti.exists_normalizedFrickeOperatorCusp_eq_smul_of_mem_cuspFormsNew`: a nonzero
  form in the new part of `S_k(N, 1)` that is an eigenvector of every good `Tₚ` satisfies
  `𝒲_N f = ε • f` with `ε = 1` or `ε = -1`.
* `HeckeRing.GL2.Newform.frickeSign`: the canonical Fricke sign of a newform of trivial
  nebentypus, together with its eigenvalue equation and sign law.
* `HeckeRing.GL2.Newform.exists_normalizedFrickeOperatorCusp_eq_smul_conj`: `𝒲_N f` is a
  multiple of the conjugate newform `f_ρ`, for every nebentypus.
* `HeckeRing.GL2.Newform.frickePseudoEigenvalue`: the Fricke pseudo-eigenvalue `λ_N(f)`, with
  its equation `𝒲_N f = λ_N(f) • f_ρ`, its uniqueness, and
  `HeckeRing.GL2.Newform.norm_frickePseudoEigenvalue`: `|λ_N(f)| = 1`.
* `HeckeRing.GL2.Newform.frickePseudoEigenvalue_conj`: the pseudo-eigenvalue of `f_ρ` is
  `(-1) ^ k · conj λ_N(f)`.
* `HeckeRing.GL2.Newform.frickePseudoEigenvalue_eq_frickeSign`: for trivial nebentypus the
  pseudo-eigenvalue is the Fricke sign.

## References

* A. O. L. Atkin and J. Lehner, *Hecke operators on `Γ₀(m)`*, Math. Ann. 185 (1970), 134–160.
* A. O. L. Atkin and W.-C. W. Li, *Twists of newforms and pseudo-eigenvalues of `W`-operators*,
  Invent. Math. **48** (1978), 221–243.
* [T. Miyake, *Modular forms*][miyake1989], Theorem 4.6.15.
* [F. Diamond and J. Shurman, *A first course in modular forms*][diamondshurman2005], §5.10.
-/

public section

open Matrix Matrix.SpecialLinearGroup UpperHalfPlane CongruenceSubgroup HeckeRing.GLn

open scoped MatrixGroups ModularForm

/-! ### `𝒲_N` preserves the new subspace -/

namespace TauCeti

variable {N : ℕ} [NeZero N] {k : ℤ}

/-- **The normalized Fricke operator preserves the new subspace**: `𝒲_N` maps
`S_k(Γ₁(N))ⁿᵉʷ` into itself. -/
theorem normalizedFrickeOperatorCusp_mem_cuspFormsNew
    {f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k} (hf : f ∈ cuspFormsNew N k) :
    normalizedFrickeOperatorCusp k f ∈ cuspFormsNew N k := by
  rw [cuspFormsNew_def] at hf ⊢
  exact normalizedFrickeOperatorCusp_mem_peterssonOrthogonal
    (fun _ hg ↦ normalizedFrickeOperatorCusp_mem_cuspFormsOld hg) hf

/-- **The normalized Fricke operator carries the new subspace onto itself.** -/
theorem cuspFormsNew_map_normalizedFrickeOperatorCusp (N : ℕ) [NeZero N] (k : ℤ) :
    (cuspFormsNew N k).map (normalizedFrickeOperatorCusp k) = cuspFormsNew N k := by
  refine le_antisymm (Submodule.map_le_iff_le_comap.mpr fun f hf ↦
    normalizedFrickeOperatorCusp_mem_cuspFormsNew hf) fun f hf ↦ ?_
  refine ⟨(-1 : ℂ) ^ k • normalizedFrickeOperatorCusp k f,
    Submodule.smul_mem _ _ (normalizedFrickeOperatorCusp_mem_cuspFormsNew hf), ?_⟩
  rw [map_smul, normalizedFrickeOperatorCusp_normalizedFrickeOperatorCusp_apply, smul_smul,
    ← mul_zpow, neg_one_mul, neg_neg, _root_.one_zpow, one_smul]

/-! ### `𝒲_N` commutes with the good Hecke operators on `S_k(N, 1)` -/

open HeckeRing.GL2

/-- **The normalized Fricke operator on the trivial-nebentypus space** `S_k(N, 1)`, as the
endomorphism obtained by specializing `normalizedFrickeCharCuspRestrict` to the trivial
character. -/
noncomputable def normalizedFrickeCharCuspOneEnd (k : ℤ) :
    Module.End ℂ (cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)) :=
  (normalizedFrickeOperatorCusp k).restrict fun _ hf ↦ by
    simpa using normalizedFrickeOperatorCusp_mem_cuspFormCharSpace k 1 hf

/-- On underlying cusp forms, `normalizedFrickeCharCuspOneEnd` is
`normalizedFrickeOperatorCusp`. -/
@[simp]
theorem coe_normalizedFrickeCharCuspOneEnd_apply
    (f : cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)) :
    ((normalizedFrickeCharCuspOneEnd k f : cuspFormCharSpace k 1) :
        CuspForm ((Gamma1 N).map (mapGL ℝ)) k) =
      normalizedFrickeOperatorCusp k (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) := by
  exact LinearMap.coe_restrict_apply _ _

/-- The slash sum of a double coset of determinant prime to `N` commutes with the Fricke slash
on a form of trivial nebentypus. This is the `Γ₀(N)` commutation read through the identification
`S_k(N, 1) ≃ S_k(Γ₀(N))`. -/
private lemma heckeSlashSum_slash_frickeGL
    {D : HeckeCoset (Delta0 N) ((Gamma0 N).map (mapGL ℚ)) ((Gamma0 N).map (mapGL ℚ))}
    (hD : CoprimeDetCoset N N D) (f : cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)) :
    heckeSlashSum k D ⇑(f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∣[k] frickeGL ℝ N =
      heckeSlashSum k D (⇑(f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∣[k] frickeGL ℝ N) := by
  have h := congrArg DFunLike.coe (LinearMap.congr_fun
    (commute_atkinLehnerOperatorCusp_heckeSlashGamma0CuspFormEnd (NeZero.pos N) dvd_rfl
      isAtkinLehnerMatrix_fricke hD).eq (cuspFormCharSpaceOneEquiv N k f))
  simpa [coe_atkinLehnerOperatorCusp, atkinLehnerGL_fricke] using h

/-- `𝒲_N` commutes with the Hecke action of a single double coset of determinant prime to
`N`. -/
private lemma commute_normalizedFrickeCharCuspOneEnd_single
    {D : HeckeCoset (Delta0 N) ((Gamma0 N).map (mapGL ℚ)) ((Gamma0 N).map (mapGL ℚ))}
    (hD : CoprimeDetCoset N N D) (c : ℤ) :
    Commute (normalizedFrickeCharCuspOneEnd k)
      (heckeRingHomCuspCharSpace k 1 (HeckeCosetModule.single ℤ D c)) := by
  refine LinearMap.ext fun f ↦ ?_
  have key : normalizedFrickeCharCuspOneEnd k (twistedHeckeSlashCuspFormCharEnd k 1 D f) =
      twistedHeckeSlashCuspFormCharEnd k 1 D (normalizedFrickeCharCuspOneEnd k f) := by
    refine Subtype.ext (DFunLike.coe_injective ?_)
    simp only [coe_normalizedFrickeCharCuspOneEnd_apply, coe_normalizedFrickeOperatorCusp,
      coe_twistedHeckeSlashCuspFormCharEnd, twistedHeckeSlashSum_eq_heckeSlashSum]
    rw [heckeSlashSum_smul k D (det_rightCosetRep_pos_of_delta0 D),
      heckeSlashSum_slash_frickeGL hD f]
  simp [key]

/-- **The normalized Fricke operator commutes with the good Hecke operators on `S_k(N, 1)`**:
for `n` prime to `N`, `𝒲_N Tₙ = Tₙ 𝒲_N`. -/
theorem commute_normalizedFrickeCharCuspOneEnd_heckeRingHomCuspCharSpace {n : ℕ}
    (hn : Nat.Coprime n N) :
    Commute (normalizedFrickeCharCuspOneEnd k)
      (heckeRingHomCuspCharSpace k 1 (heckeTCompositeGamma0 N n)) :=
  commute_map_heckeTCompositeGamma0_of_forall_coprimeDetCoset N _ hn fun _ hD ↦
    commute_normalizedFrickeCharCuspOneEnd_single hD 1

/-! ### The Fricke sign -/

/-- **The Fricke sign**: a nonzero cusp form in the new part of
`S_k(N, 1)` that is an eigenvector of `Tₚ` at every prime `p ∤ N` is an eigenvector of the
normalized Fricke operator, with eigenvalue `1` or `-1`. -/
theorem exists_normalizedFrickeOperatorCusp_eq_smul_of_mem_cuspFormsNew
    {f : cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)}
    (ha : ∀ p : ℕ, p.Prime → Nat.Coprime p N → ∃ c : ℂ,
      heckeRingHomCuspCharSpace k 1 (heckeTCompositeGamma0 N p) f = c • f)
    (hf : (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∈ cuspFormsNew N k)
    (hf0 : (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ≠ 0) :
    ∃ ε : ℂ, (ε = 1 ∨ ε = -1) ∧
      normalizedFrickeOperatorCusp k (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) =
        ε • (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) := by
  -- `𝒲_N ∘ 𝒲_N = (-1) ^ k`, and `(-1) ^ k = 1` since `f ≠ 0` has trivial nebentypus
  have hk : (-1 : ℂ) ^ k = 1 := by
    simpa using (char_neg_one_of_mem_cuspFormCharSpace f.2 hf0).symm
  have hWW : normalizedFrickeCharCuspOneEnd k (normalizedFrickeCharCuspOneEnd k f) = f := by
    rw [Subtype.ext_iff, coe_normalizedFrickeCharCuspOneEnd_apply,
      coe_normalizedFrickeCharCuspOneEnd_apply,
      normalizedFrickeOperatorCusp_normalizedFrickeOperatorCusp_apply, hk, one_smul]
  -- so the multiplicity-one step for a commuting involution applies to `𝒲_N` on `S_k(N, 1)`
  obtain ⟨ε, hε, hWf⟩ := exists_eq_smul_of_commute_heckeRingHomCusp_of_mem_cuspFormsNew
    (fun _ _ hpN ↦ commute_normalizedFrickeCharCuspOneEnd_heckeRingHomCuspCharSpace hpN)
    (fun _ hg ↦ by
      rw [coe_normalizedFrickeCharCuspOneEnd_apply]
      exact normalizedFrickeOperatorCusp_mem_cuspFormsNew hg)
    ha hf hf0 hWW
  exact ⟨ε, hε, by rw [← coe_normalizedFrickeCharCuspOneEnd_apply, hWf, Submodule.coe_smul]⟩

end TauCeti

namespace HeckeRing.GL2

open TauCeti

variable {N : ℕ} [NeZero N] {k : ℤ}

/-- **The Fricke sign of a newform of trivial nebentypus**: `𝒲_N f = ε • f` with `ε = 1` or
`ε = -1`. -/
theorem Newform.exists_normalizedFrickeOperatorCusp_eq_smul (f : Newform N k) (hχ : f.χ = 1) :
    ∃ ε : ℂ, (ε = 1 ∨ ε = -1) ∧
      normalizedFrickeOperatorCusp k f.toCuspForm = ε • f.toCuspForm := by
  revert hχ
  obtain ⟨⟨F, χ, hmem, a, heig, hne⟩, hnew, -⟩ := f
  rintro rfl
  exact exists_normalizedFrickeOperatorCusp_eq_smul_of_mem_cuspFormsNew (f := ⟨F, hmem⟩)
    (fun p hp hpN ↦ ⟨a ⟨p, hp.pos⟩ hpN, heig ⟨p, hp.pos⟩ hpN⟩) hnew hne

/-- **The Fricke sign** `ε_N(f)` of a newform with trivial nebentypus. -/
noncomputable def Newform.frickeSign (f : Newform N k) (hχ : f.χ = 1) : ℂ :=
  (f.exists_normalizedFrickeOperatorCusp_eq_smul hχ).choose

/-- The normalized Fricke operator acts on a trivial-nebentypus newform by its Fricke sign. -/
theorem Newform.normalizedFrickeOperatorCusp_eq_frickeSign_smul
    (f : Newform N k) (hχ : f.χ = 1) :
    normalizedFrickeOperatorCusp k f.toCuspForm = f.frickeSign hχ • f.toCuspForm :=
  (f.exists_normalizedFrickeOperatorCusp_eq_smul hχ).choose_spec.2

/-- The Fricke sign of a trivial-nebentypus newform is `1` or `-1`. -/
theorem Newform.frickeSign_eq_one_or_neg_one (f : Newform N k) (hχ : f.χ = 1) :
    f.frickeSign hχ = 1 ∨ f.frickeSign hχ = -1 :=
  (f.exists_normalizedFrickeOperatorCusp_eq_smul hχ).choose_spec.1

/-- A scalar satisfying the normalized Fricke eigenvalue equation is the Fricke sign. -/
theorem Newform.frickeSign_eq_of_normalizedFrickeOperatorCusp_eq_smul
    (f : Newform N k) (hχ : f.χ = 1) {ε : ℂ}
    (hε : normalizedFrickeOperatorCusp k f.toCuspForm = ε • f.toCuspForm) :
    f.frickeSign hχ = ε :=
  smul_left_injective ℂ f.ne_zero
    ((f.normalizedFrickeOperatorCusp_eq_frickeSign_smul hχ).symm.trans hε)

/-! ### The Fricke pseudo-eigenvalue -/

/-- **The Fricke involution sends a newform to a multiple of its conjugate newform** (Miyake,
Theorem 4.6.15(2)): `𝒲_N f = c • f_ρ` for a newform `f` of any nebentypus `χ`, where `f_ρ` is
the conjugate newform `HeckeRing.GL2.Newform.conj`. The scalar is
`HeckeRing.GL2.Newform.frickePseudoEigenvalue`. -/
theorem Newform.exists_normalizedFrickeOperatorCusp_eq_smul_conj (f : Newform N k) :
    ∃ c : ℂ, normalizedFrickeOperatorCusp k f.toCuspForm = c • f.conj.toCuspForm := by
  -- Both `𝒲_N f` and `f_ρ` lie in the new part of `S_k(N, χ⁻¹)` and are good Hecke
  -- eigenvectors with eigenvalue `conj λ_p` at every prime `p ∤ N`, so multiplicity one on the
  -- new part makes them proportional.
  let F : cuspFormCharSpace k f.χ⁻¹ :=
    ⟨_, normalizedFrickeOperatorCusp_mem_cuspFormCharSpace k f.χ f.mem_charSpace⟩
  let G : cuspFormCharSpace k f.χ⁻¹ := ⟨_, f.χ_conj ▸ f.conj.mem_charSpace⟩
  refine exists_eq_smul_of_forall_prime_heckeRingHomCusp_of_mem_cuspFormsNew (f := G) (g := F)
    (fun p hp hpN ↦ ?_) f.conj.isNew (normalizedFrickeOperatorCusp_mem_cuspFormsNew f.isNew)
    f.conj.ne_zero
  have : NeZero p := ⟨hp.ne_zero⟩
  -- the Fricke operator multiplies `λ_p` by `χ(p)⁻¹`, and `χ(p)⁻¹ λ_p = conj λ_p`
  have hev : (f.χ (ZMod.unitOfCoprime p hpN) : ℂ)⁻¹ * f.eigenvalue ⟨p, hp.pos⟩ hpN =
      starRingEnd ℂ (f.eigenvalue ⟨p, hp.pos⟩ hpN) := by
    conv_lhs => rw [f.toEigenformAwayFromLevel.eigenvalue_eq_mul_conj hp hpN]
    exact inv_mul_cancel_left₀ (Units.ne_zero _) _
  refine ⟨starRingEnd ℂ (f.eigenvalue ⟨p, hp.pos⟩ hpN),
    heckeRingHomCuspCharSpace_heckeTCompositeGamma0_eq_smul_of_heckeTCuspNat_eq_smul hp ?_,
    heckeRingHomCuspCharSpace_heckeTCompositeGamma0_eq_smul_of_heckeTCuspNat_eq_smul hp ?_⟩
  · exact (f.conj.heckeTCuspNat_eq_eigenvalue_smul hp hpN).trans
      (congrArg (· • f.conj.toCuspForm) (f.eigenvalue_conj ⟨p, hp.pos⟩ hpN))
  · rw [← hev]
    exact (heckeTCuspNat_normalizedFrickeOperatorCusp_eq_smul_iff_heckeTCuspNat_eq_smul hpN
      f.mem_charSpace _).mpr (f.heckeTCuspNat_eq_eigenvalue_smul hp hpN)

/-- **The Fricke pseudo-eigenvalue** `λ_N(f)` of a newform `f` (Atkin–Li): the scalar with
`𝒲_N f = λ_N(f) • f_ρ`, where `f_ρ` is the conjugate newform. It has absolute value `1`
(`HeckeRing.GL2.Newform.norm_frickePseudoEigenvalue`), and for trivial nebentypus it is the
Fricke sign (`HeckeRing.GL2.Newform.frickePseudoEigenvalue_eq_frickeSign`). -/
noncomputable def Newform.frickePseudoEigenvalue (f : Newform N k) : ℂ :=
  f.exists_normalizedFrickeOperatorCusp_eq_smul_conj.choose

/-- The normalized Fricke operator sends a newform to its pseudo-eigenvalue times its conjugate
newform. -/
theorem Newform.normalizedFrickeOperatorCusp_eq_frickePseudoEigenvalue_smul (f : Newform N k) :
    normalizedFrickeOperatorCusp k f.toCuspForm = f.frickePseudoEigenvalue • f.conj.toCuspForm :=
  f.exists_normalizedFrickeOperatorCusp_eq_smul_conj.choose_spec

/-- A scalar satisfying the equation `𝒲_N f = c • f_ρ` is the Fricke pseudo-eigenvalue. -/
theorem Newform.frickePseudoEigenvalue_eq_of_normalizedFrickeOperatorCusp_eq_smul
    (f : Newform N k) {c : ℂ}
    (hc : normalizedFrickeOperatorCusp k f.toCuspForm = c • f.conj.toCuspForm) :
    f.frickePseudoEigenvalue = c :=
  smul_left_injective ℂ f.conj.ne_zero
    ((f.normalizedFrickeOperatorCusp_eq_frickePseudoEigenvalue_smul).symm.trans hc)

/-- **The Fricke pseudo-eigenvalue has absolute value `1`.** -/
theorem Newform.norm_frickePseudoEigenvalue (f : Newform N k) :
    ‖f.frickePseudoEigenvalue‖ = 1 := by
  -- `𝒲_N` is Petersson-unitary and conjugation preserves the Petersson norm, so
  -- `⟪f, f⟫ = |λ_N(f)|² ⟪f_ρ, f_ρ⟫ = |λ_N(f)|² ⟪f, f⟫`.
  have h := peterssonInnerCosets_normalizedFrickeOperatorCusp k f.toCuspForm f.toCuspForm
  -- `⟪c • f_ρ, c • f_ρ⟫ = |c|² ⟪f_ρ, f_ρ⟫` and `⟪f_ρ, f_ρ⟫ = conj ⟪f, f⟫ = ⟪f, f⟫`
  rw [f.normalizedFrickeOperatorCusp_eq_frickePseudoEigenvalue_smul, toCuspForm_conj] at h
  simp only [CuspForm.peterssonInnerCosets_smul_left, CuspForm.peterssonInnerCosets_smul_right,
    CuspForm.peterssonInnerCosets_conj_conj, CuspForm.peterssonInnerCosets_conj_symm, ← mul_assoc,
    Complex.mul_conj'] at h
  have hP : CuspForm.peterssonInnerCosets f.toCuspForm f.toCuspForm ≠ 0 :=
    mt (CuspForm.peterssonInnerCosets_self_eq_zero _).mp f.ne_zero
  have hsq : ‖f.frickePseudoEigenvalue‖ ^ 2 = 1 := by
    exact_mod_cast mul_right_cancel₀ hP (h.trans (one_mul _).symm)
  exact (pow_eq_one_iff_of_nonneg (norm_nonneg _) two_ne_zero).mp hsq

/-- **The pseudo-eigenvalues of a newform and of its conjugate multiply to `(-1) ^ k`**:
`λ_N(f) λ_N(f_ρ) = (-1) ^ k`, because `𝒲_N f = λ_N(f) • f_ρ`, `𝒲_N f_ρ = λ_N(f_ρ) • f` and
`𝒲_N ∘ 𝒲_N = (-1) ^ k`. -/
theorem Newform.frickePseudoEigenvalue_mul_frickePseudoEigenvalue_conj (f : Newform N k) :
    f.frickePseudoEigenvalue * f.conj.frickePseudoEigenvalue = (-1 : ℂ) ^ k := by
  have h := normalizedFrickeOperatorCusp_normalizedFrickeOperatorCusp_apply k f.toCuspForm
  rw [f.normalizedFrickeOperatorCusp_eq_frickePseudoEigenvalue_smul, map_smul,
    f.conj.normalizedFrickeOperatorCusp_eq_frickePseudoEigenvalue_smul, conj_conj,
    smul_smul] at h
  exact smul_left_injective ℂ f.ne_zero h

/-- **The pseudo-eigenvalue of the conjugate newform**: `λ_N(f_ρ) = (-1) ^ k · conj λ_N(f)`. Since
`|λ_N(f)| = 1`, its inverse is its complex conjugate. -/
theorem Newform.frickePseudoEigenvalue_conj (f : Newform N k) :
    f.conj.frickePseudoEigenvalue = (-1 : ℂ) ^ k * starRingEnd ℂ f.frickePseudoEigenvalue := by
  have hnorm : starRingEnd ℂ f.frickePseudoEigenvalue * f.frickePseudoEigenvalue = 1 := by
    rw [mul_comm, Complex.mul_conj', f.norm_frickePseudoEigenvalue, Complex.ofReal_one, one_pow]
  linear_combination (-f.conj.frickePseudoEigenvalue) * hnorm + starRingEnd ℂ
    f.frickePseudoEigenvalue * f.frickePseudoEigenvalue_mul_frickePseudoEigenvalue_conj

/-- **For trivial nebentypus the pseudo-eigenvalue is the Fricke sign**: such a newform is its own
conjugate (`HeckeRing.GL2.Newform.conj_eq_self_of_χ_eq_one`), so `𝒲_N f = λ_N(f) • f`. -/
theorem Newform.frickePseudoEigenvalue_eq_frickeSign (f : Newform N k) (hχ : f.χ = 1) :
    f.frickePseudoEigenvalue = f.frickeSign hχ := by
  refine (f.frickeSign_eq_of_normalizedFrickeOperatorCusp_eq_smul hχ ?_).symm
  rw [f.normalizedFrickeOperatorCusp_eq_frickePseudoEigenvalue_smul,
    f.conj_eq_self_of_χ_eq_one hχ]

end HeckeRing.GL2
