/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ClassFieldTheory.Local.CyclicClass
public import TauCeti.NumberTheory.LocalField.UnitFiltration.Basic
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import TauCeti.FieldTheory.IntermediateField.Adjoin.Basic
import TauCeti.NumberTheory.LocalField.FiniteExtension.Basic
import TauCeti.NumberTheory.LocalField.Norm.Unramified.Basic
import TauCeti.NumberTheory.LocalField.Unramified.Maximal

/-!
# The local symbol of two units at a tame exponent

Let `K` be a nonarchimedean local field containing a primitive `n`-th root of unity `ζ`, where the
residue characteristic of `K` does not divide `n`. Then the local symbol `(a, b)` along
`kummerCupPairing ζ hζ` vanishes whenever `a` and `b` are units of the valuation ring. The
extension `K(ⁿ√b)` is unramified, because an `n`-th root of a unit lies in the maximal unramified
extension, and every unit is a norm from an unramified extension; the symbol–norm criterion then
gives `(a, b) = 0`.

This is the local input for the finiteness of the Hilbert symbols of two global elements: away
from the places above `n` and the places at which `a` or `b` is not a unit, their local symbols
vanish.

## Main results

* `TauCeti.ClassFieldTheory.localSymbol_kummerClass_eq_zero_of_mem_unitFiltration`: the local
  symbol of two units vanishes when the residue characteristic does not divide `n`.

## References

* J.-P. Serre, *Local Fields*, Graduate Texts in Mathematics 67, Springer (1979), Chapter XIV,
  §3, Proposition 8.
* J. Neukirch, *Algebraic Number Theory*, Springer (1999), Chapter V, §3, Proposition 3.4.
-/

public section

noncomputable section

namespace TauCeti.ClassFieldTheory

open _root_.IntermediateField ValuativeRel

variable {K : Type} [Field K] [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  {n : ℕ} [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
  (tr : continuousCohomology 2 (muNRep n K) ≃+ ZMod n)

/-- **The local symbol of two units vanishes at a tame exponent.** Let `K` be a nonarchimedean
local field containing a primitive `n`-th root of unity `ζ`, with `n` prime to the residue
characteristic. If `a` and `b` are units of the valuation ring of `K`, then their local symbol
along `kummerCupPairing ζ hζ` is `0`, for every identification `tr : H²(G_K, μₙ) ≃+ ZMod n`. -/
theorem localSymbol_kummerClass_eq_zero_of_mem_unitFiltration (hp : ¬ ringChar 𝓀[K] ∣ n)
    {a b : Kˣ} (ha : a ∈ unitFiltration K 0) (hb : b ∈ unitFiltration K 0) :
    localSymbol (kummerCupPairing ζ hζ) tr (kummerClass K hζ.neZero'.out.isUnit a)
        (kummerClass K hζ.neZero'.out.isUnit b) = 0 := by
  have hn : IsUnit (n : K) := hζ.neZero'.out.isUnit
  -- the radical extension `E = K(s)` generated by an `n`-th root `s` of `b`
  obtain ⟨s, hs⟩ := IsAlgClosed.exists_pow_nat_eq (algebraMap K (AlgebraicClosure K) b)
    (Nat.pos_of_neZero n)
  have : FiniteDimensional K K⟮s⟯ :=
    adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral s)
  have ht : AdjoinSimple.gen K s ^ n = algebraMap K K⟮s⟯ b := Subtype.ext (by simpa using hs)
  let _ := finiteExtensionValuativeRel K K⟮s⟯
  let _ := finiteExtensionNormedFieldTopology K K⟮s⟯
  have := finiteExtension_isNonarchimedeanLocalField K K⟮s⟯
  have := finiteExtension_valuativeExtension K K⟮s⟯
  -- `E / K` is unramified, since `s` lies in the maximal unramified extension
  have : IsUnramified K K⟮s⟯ := (le_maximalUnramifiedExtension_iff K⟮s⟯).1 <|
    adjoin_simple_le_iff.2 (mem_maximalUnramifiedExtension_of_pow_eq hp hb hs)
  -- so the unit `a` is a norm from `E`
  have ha' : normalizedValuation K a = 1 :=
    (normalizedValuation_eq_one_iff a).2 ((mem_unitFiltration_zero a).1 ha)
  refine (localSymbol_eq_zero_iff_mem_normGroup hζ tr hn a b ht
    (adjoin_adjoinSimple_gen_eq_top (K := K) s)).2 ?_
  exact mem_normGroup_iff_dvd_normalizedValuation.2 (by simp [ha'])

end TauCeti.ClassFieldTheory
