/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.IntegralLattice.Orthogonal.Isometry

/-!
# Splitting off a vector of unit norm

A nonzero integral vector generates a cyclic lattice with Gram matrix consisting of its norm.
This file identifies the rationalized restricted form on that cyclic submodule with the
Gram-matrix lattice on `ℚ`, sending `1` to the unit tensor of the chosen vector.

If the norm is a unit of `ℤ`, hence `1` or `-1`, the cyclic lattice splits off orthogonally.
The resulting isometry identifies the entire integral lattice with `⟨1⟩` or `⟨-1⟩` plus
its orthogonal complement. Neither nondegeneracy nor definiteness of the ambient form is
needed. These splittings allow unit-norm vectors to be removed in classification arguments.

The construction uses `LinearEquiv.toSpanNonzeroSingleton`, the abstract-form dictionary
`IntegralLattice.ofIntegralForm`, and the orthogonal splitting isometry.
The mathematical source is O. T. O'Meara, *Introduction to Quadratic Forms*, §82.
-/

public section

open Module TensorProduct

namespace TauCeti.IntegralLattice

universe u

variable {V : Type u} [AddCommGroup V] [Module ℚ V]
variable (L : IntegralLattice V) (x : L)

private noncomputable def spanSingletonBasis (hx : x ≠ 0) :
    Basis (Fin 1) ℤ
      (ofIntegralForm (L.integralForm.restrict (ℤ ∙ x))
        (L.isSymm_integralForm.restrict (ℤ ∙ x))) :=
  (Basis.singleton (Fin 1) ℤ).map
    ((LinearEquiv.toSpanNonzeroSingleton ℤ L x hx).trans
      (ofIntegralForm.carrierEquiv _ _))

private theorem coe_spanSingletonBasis (hx : x ≠ 0) (i : Fin 1) :
    (spanSingletonBasis L x hx i : ℚ ⊗[ℤ] (ℤ ∙ x)) =
      1 ⊗ₜ[ℤ] (⟨x, Submodule.mem_span_singleton_self x⟩ : ℤ ∙ x) := by
  simp [spanSingletonBasis, Basis.singleton_apply]

private theorem gramMatrix_spanSingletonBasis (hx : x ≠ 0) :
    (ofIntegralForm (L.integralForm.restrict (ℤ ∙ x))
      (L.isSymm_integralForm.restrict (ℤ ∙ x))).gramMatrix (spanSingletonBasis L x hx) =
        Matrix.of (fun (_ _ : Fin 1) ↦ L.integralForm x x) := by
  ext i j
  rw [gramMatrix_apply]
  apply Int.cast_injective (α := ℚ)
  rw [integralForm_cast, coe_spanSingletonBasis, coe_spanSingletonBasis,
    ofIntegralForm_form, LinearMap.BilinForm.baseChange_tmul]
  simp

/-- The cyclic lattice generated by a nonzero integral vector has one-entry Gram matrix equal
to its norm. The isometry sends `1` to the unit tensor of the vector. -/
noncomputable def spanSingletonIsometry (hx : x ≠ 0) :
    Isometry
      (ofGramMatrix (Basis.singleton (Fin 1) ℚ)
        (Matrix.of (fun (_ _ : Fin 1) ↦ L.integralForm x x)) (by ext; rfl))
      (ofIntegralForm (L.integralForm.restrict (ℤ ∙ x))
        (L.isSymm_integralForm.restrict (ℤ ∙ x))) :=
  Isometry.ofGramMatrixEq
    (ofGramMatrix.basis (Basis.singleton (Fin 1) ℚ) _ _)
    (spanSingletonBasis L x hx)
    ((gramMatrix_ofGramMatrix _ _ _).trans (gramMatrix_spanSingletonBasis L x hx).symm)

/-- The cyclic isometry sends a rational scalar to the corresponding pure tensor. -/
@[simp]
theorem spanSingletonIsometry_apply (hx : x ≠ 0) (q : ℚ) :
    L.spanSingletonIsometry x hx q =
      q ⊗ₜ[ℤ] (⟨x, Submodule.mem_span_singleton_self x⟩ : ℤ ∙ x) := by
  have h := Isometry.ofGramMatrixEq_apply_basis
    (ofGramMatrix.basis (Basis.singleton (Fin 1) ℚ)
      (Matrix.of (fun (_ _ : Fin 1) ↦ L.integralForm x x)) (by ext; rfl))
    (spanSingletonBasis L x hx)
    ((gramMatrix_ofGramMatrix _ _ _).trans (gramMatrix_spanSingletonBasis L x hx).symm) 0
  rw [ofGramMatrix.coe_basis (Basis.singleton (Fin 1) ℚ)
    (Matrix.of (fun (_ _ : Fin 1) ↦ L.integralForm x x)) (by ext; rfl) 0,
    Basis.singleton_apply, coe_spanSingletonBasis] at h
  have h1 : L.spanSingletonIsometry x hx 1 =
      1 ⊗ₜ[ℤ] (⟨x, Submodule.mem_span_singleton_self x⟩ : ℤ ∙ x) := h
  calc
    L.spanSingletonIsometry x hx q = q • L.spanSingletonIsometry x hx 1 := by
      rw [← map_smul, smul_eq_mul, mul_one]
    _ = q ⊗ₜ[ℤ] (⟨x, Submodule.mem_span_singleton_self x⟩ : ℤ ∙ x) := by
      rw [h1]
      exact (TensorProduct.tmul_eq_smul_one_tmul _ _).symm

/-- The inverse cyclic isometry recovers the coefficient of a pure tensor. -/
@[simp]
theorem spanSingletonIsometry_symm_apply_tmul (hx : x ≠ 0) (q : ℚ) :
    (L.spanSingletonIsometry x hx).symm
      (q ⊗ₜ[ℤ] (⟨x, Submodule.mem_span_singleton_self x⟩ : ℤ ∙ x)) = q := by
  apply (L.spanSingletonIsometry x hx).injective
  simp

private theorem ne_zero_of_isUnit_norm (hx : IsUnit (L.integralForm x x)) : x ≠ 0 := by
  intro h
  simp [h] at hx

/-- A vector of norm `1` or `-1` splits off its canonical rank-one Gram-matrix lattice.
The other summand is the rationalized integral orthogonal complement of the vector. -/
noncomputable def unitNormSplittingIsometry (hx : IsUnit (L.integralForm x x)) :
    Isometry
      ((ofGramMatrix (Basis.singleton (Fin 1) ℚ)
        (Matrix.of (fun (_ _ : Fin 1) ↦ L.integralForm x x))
        (by ext; rfl)).orthogonalSum
        (ofIntegralForm (L.integralForm.restrict (L.integralForm.orthogonal (ℤ ∙ x)))
          (L.isSymm_integralForm.restrict (L.integralForm.orthogonal (ℤ ∙ x))))) L :=
  ((L.spanSingletonIsometry x (ne_zero_of_isUnit_norm L x hx)).orthogonalSum
    (Isometry.refl _)).trans
    (L.orthogonalSumIsometryOfIsCompl (ℤ ∙ x) (L.integralForm.orthogonal (ℤ ∙ x))
      (L.isCompl_span_singleton_orthogonal_of_isUnit x hx) le_rfl)

/-- The splitting sends the rank-one coordinate to its multiple of the chosen vector,
and a pure tensor in the orthogonal complement to its underlying scalar multiple. -/
@[simp]
theorem unitNormSplittingIsometry_apply_tmul (hx : IsUnit (L.integralForm x x))
    (q r : ℚ) (t : L.integralForm.orthogonal (ℤ ∙ x)) :
    L.unitNormSplittingIsometry x hx (q, r ⊗ₜ[ℤ] t) =
      q • (x : V) + r • ((t : L) : V) := by
  simp [unitNormSplittingIsometry]

/-- The inverse splitting recovers the rank-one coordinate and the pure tensor in the
orthogonal complement. -/
@[simp]
theorem unitNormSplittingIsometry_symm_apply_smul_add_smul
    (hx : IsUnit (L.integralForm x x)) (q r : ℚ)
    (t : L.integralForm.orthogonal (ℤ ∙ x)) :
    (L.unitNormSplittingIsometry x hx).symm
        (q • (x : V) + r • ((t : L) : V)) = (q, r ⊗ₜ[ℤ] t) := by
  apply (L.unitNormSplittingIsometry x hx).injective
  simp

/-- The first inverse coordinate is the orthogonal projection coefficient, on every rational
ambient vector. -/
@[simp]
theorem unitNormSplittingIsometry_symm_apply_fst (hx : IsUnit (L.integralForm x x))
    (y : V) :
    ((L.unitNormSplittingIsometry x hx).symm y).1 =
      L.form (x : V) y / (L.integralForm x x : ℚ) := by
  let _ : DecidableEq (Fin 1) := Classical.decEq _
  have h := (L.unitNormSplittingIsometry x hx).map_app (1, 0)
    ((L.unitNormSplittingIsometry x hx).symm y)
  have hx0 : (L.integralForm x x : ℚ) ≠ 0 := Int.cast_ne_zero.mpr hx.ne_zero
  have h1 : L.unitNormSplittingIsometry x hx (1, 0) = (x : V) := by
    simpa using L.unitNormSplittingIsometry_apply_tmul x hx 1 0 0
  rw [h1, Isometry.apply_symm_apply, orthogonalSum_form, orthogonalSumForm_apply,
    ofGramMatrix_form, Matrix.toBilin_apply] at h
  simp only [Fin.sum_univ_one, Basis.singleton_repr, Matrix.map_apply,
    Matrix.of_apply, eq_intCast, map_zero, LinearMap.zero_apply, add_zero,
    one_mul] at h
  exact (eq_div_iff hx0).mpr (by simpa [mul_comm] using h.symm)

end TauCeti.IntegralLattice
