/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.Basic
public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.Transfer.Basic
public import Mathlib.Topology.Instances.ZMod
import TauCeti.RepresentationTheory.Homological.ContCohomology.Bockstein.Integral
import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.Corestriction
import TauCeti.RepresentationTheory.Homological.ContCohomology.Corestriction.Transfer
import TauCeti.Topology.Algebra.Group.Profinite.ProP.Character.Separation
import TauCeti.Topology.Algebra.Group.TopologicalAbelianization.Lift

/-!
# The transfer to the pro-p class module in strict cohomological dimension two

Let `G` be a profinite group with `scd_p G ≤ 2` and let `V` be an open subgroup. The transfer
`Ver : G → V^ab(p)` (`TauCeti.abelianizationProPTransfer`) has the same kernel as the canonical map
`G → G^ab(p)`, so it induces an injection `G^ab(p) → V^ab(p)`; for `V` normal, its image is the
subgroup of `G ⧸ V`-invariants. Together these are NSW (3.6.4)(ii) in `p`-primary form,
`G^ab(p) ≅ V^ab(p)^{G/V}`.

One inclusion of the kernels needs no hypothesis on `G` beyond profiniteness: `Ver` is a
continuous homomorphism to the abelian pro-`p` group `V^ab(p)`, so it factors through `G^ab(p)`
(`TauCeti.abelianizationProPTransfer_eq_one_of_mk_eq_one`). The other inclusion is
NSW (3.3.11) in degree `2` with coefficients `ℤ`, read on characters. A continuous character
`χ : G → ℤ/p^k` has a `p`-primary integral Bockstein `δχ ∈ H²(G, ℤ)`. Because `scd_p G ≤ 2`,
`δχ` is a corestriction from `H²(V, ℤ)`, so it is the corestriction of the Bockstein `δψ` of a
character `ψ` of `V`. Corestriction commutes with the Bockstein, and on characters it is the
transfer (NSW (1.5.9)), so `δχ = δ(ψ ∘ Ver)`. Moving both characters to a common modulus, and
using that the degree-one Bockstein is injective, gives `χ = ψ ∘ Ver` up to a multiplication of
the coefficients. So `χ` kills the kernel of `Ver` (`TauCeti.zmodChar_eq_one_of_transfer_eq_one`).
Finally, continuous characters into the groups `ℤ/p^k` separate the points of the abelian pro-`p`
group `G^ab(p)` (`TauCeti.exists_continuous_zmodChar_of_notMem`). For the kernel, `V` need not be
normal.

The image is the other half of (3.3.11), injectivity of corestriction on the coinvariants. The
image of `Ver` is invariant (`TauCeti.smul_abelianizationProPTransfer`). Conversely, let
`ψ : V^ab(p) → ℤ/p^k` be a continuous character that is trivial on the image of `Ver`. Read on
`V`, its class in `H¹(V, ℤ/p^k)` has trivial corestriction, since that corestriction is `ψ ∘ Ver`,
so its integral Bockstein lies in the subgroup generated by the differences `(g)_* w - w` of
`p`-primary classes `w ∈ H²(V, ℤ)`. Each such `w` is the Bockstein of a character of `p`-power
order of `V`. That character factors through `V^ab(p)`, so `(g)_* w - w` restricts to zero on the
closed subgroup `Z` of the elements of `V` whose classes are invariant. Hence the Bockstein of `ψ`
restricted to `Z` vanishes, and so does that restriction itself, the Bockstein being injective
in degree one. This shows that `ψ` kills the invariants
(`TauCeti.zmodChar_eq_one_of_comp_transfer_eq_one`). The image of `Ver` is compact, hence closed,
and characters separate it from any invariant element outside it.

## Main results

* `TauCeti.zmodChar_eq_one_of_transfer_eq_one`: under `scd_p G ≤ 2`, a continuous character of `G`
  of `p`-power order kills the kernel of the transfer.
* `TauCeti.abelianizationProPTransfer_eq_one_iff`: under `scd_p G ≤ 2`, the kernel of the transfer
  is the kernel of `G → G^ab(p)`.
* `TauCeti.zmodChar_eq_one_of_comp_transfer_eq_one`: under `scd_p G ≤ 2` and for `V` normal, a
  continuous character of `V^ab(p)` of `p`-power order that kills the image of the transfer kills
  the `G ⧸ V`-invariants.
* `TauCeti.abelianizationProPTransfer_range`: under `scd_p G ≤ 2` and for `V` normal, the image of
  the transfer is the subgroup of `G ⧸ V`-invariants of `V^ab(p)`.

## References

* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (1.5.9),
  (3.3.11) and the proof of (3.6.4), (i) ⇒ (ii).
-/

public section

namespace TauCeti

open CategoryTheory ContCohomology _root_.TauCeti.ContinuousCohomology

universe u

attribute [local instance 2000] Ring.toAddCommGroup
attribute [local instance] trivialZModAction integralAction integralContinuousSMul
  cyclicContinuousSMul

section Characters

variable (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The class in `H¹(G, ℤ/n)` of a continuous character, through the trivial-action description
of the explicit `H¹`. -/
private noncomputable def charClass (n : ℕ) :
    Additive (G →ₜ* Multiplicative (ULift.{u} (ZMod n))) ≃+
      continuousCohomology 1 (ofDiscreteModule ℤ G (ULift.{u} (ZMod n))) :=
  (H1EquivOfSmulEqSelf (G := G) (M := ULift.{u} (ZMod n)) fun _ _ ↦ rfl).symm.trans
    (explicitH1AddEquivContinuousCohomology G (ULift.{u} (ZMod n)))

/-- The coefficient map of a homomorphism `f : ℤ/n → ℤ/m` acts on characters by composition
with `f`. -/
private theorem charClass_symm_coeffMap_apply {n m : ℕ} (f : ZMod n →+ ZMod m)
    (x : continuousCohomology 1 (ofDiscreteModule ℤ G (ULift.{u} (ZMod n)))) (g : G) :
    Multiplicative.toAdd (Additive.toMul ((charClass G m).symm
      (coeffMap (ofDiscreteModuleMap ((AddEquiv.ulift.symm.toAddMonoidHom.comp f).comp
        AddEquiv.ulift.toAddMonoidHom).toIntLinearMap fun _ _ ↦ rfl) 1 x)) g) =
      ULift.up (f (Multiplicative.toAdd (Additive.toMul ((charClass G n).symm x) g)).down) := by
  obtain ⟨χ, rfl⟩ := (charClass G n).surjective x
  let F : ULift.{u} (ZMod n) →+[G] ULift.{u} (ZMod m) :=
    { (AddEquiv.ulift.symm.toAddMonoidHom.comp f).comp AddEquiv.ulift.toAddMonoidHom with
      map_smul' := fun _ _ ↦ rfl }
  have h := explicitH1AddEquivContinuousCohomology_coeffMap G (ULift.{u} (ZMod n))
    (ULift.{u} (ZMod m)) F ((H1EquivOfSmulEqSelf (G := G) (M := ULift.{u} (ZMod n))
      fun _ _ ↦ rfl).symm χ)
  -- `h` states the comparison for the coefficient map of the bundled equivariant map `F`, whose
  -- underlying additive map is the composite in the statement; restate it in that form.
  change coeffMap (ofDiscreteModuleMap ((AddEquiv.ulift.symm.toAddMonoidHom.comp f).comp
    AddEquiv.ulift.toAddMonoidHom).toIntLinearMap fun _ _ ↦ rfl) 1 (charClass G n χ) = _ at h
  rw [h]
  simp [charClass]
  -- What is left evaluates the bundled `F`, whose value is the composite
  -- `ULift.up ∘ f ∘ ULift.down` by construction; Mathlib has no `coe_mk` lemma for
  -- `DistribMulActionHom` to rewrite with.
  rfl

/-- Pulling the class of a character back along a continuous homomorphism `φ`, with the identity
of the trivial coefficients, composes the character with `φ`. -/
private theorem map_charClass {H : Type u} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : H →ₜ* G) {n : ℕ} (χ : G →ₜ* Multiplicative (ULift.{u} (ZMod n))) :
    _root_.ContinuousCohomology.map φ (ofDiscreteModulePair (φ : H →* G)
        (AddMonoidHom.id (ULift.{u} (ZMod n))).toIntLinearMap fun _ _ ↦ rfl) 1
        (charClass G n (Additive.ofMul χ)) =
      charClass H n (Additive.ofMul (χ.comp φ)) := by
  simp only [charClass, AddEquiv.trans_apply]
  rw [explicitH1AddEquivContinuousCohomology_map G _ H _ φ (AddMonoidHom.id _) fun _ _ ↦ rfl]
  congr 1
  rw [H1EquivOfSmulEqSelf_symm_apply, H1EquivOfSmulEqSelf_symm_apply, explicitMap1_mk]
  congr 1
  ext h
  simp [cocyclesMap1_coe, cochainsMap1_apply]

variable [CompactSpace G] [TotallyDisconnectedSpace G]

/-- Degree-one corestriction with trivial coefficients `ℤ/n` is the transfer of characters
(NSW (1.5.9)). -/
private theorem corestriction_charClass {V : Subgroup G} [V.FiniteIndex] (hV : IsOpen (V : Set G))
    {n : ℕ} (ψ : V →ₜ* Multiplicative (ULift.{u} (ZMod n))) :
    corestriction V (ULift.{u} (ZMod n)) hV 1 (charClass V n (Additive.ofMul ψ)) =
      charClass G n (Additive.ofMul
        ⟨MonoidHom.transfer ψ.toMonoidHom, continuous_transfer hV ψ.continuous⟩) := by
  have h := explicitH1AddEquivContinuousCohomology_corestriction V (ULift.{u} (ZMod n)) hV
    ((H1EquivOfSmulEqSelf (G := V) (M := ULift.{u} (ZMod n)) fun _ _ ↦ rfl).symm
      (Additive.ofMul ψ))
  refine h.trans (congrArg _ ((H1EquivOfSmulEqSelf (G := G) (M := ULift.{u} (ZMod n))
    fun _ _ ↦ rfl).symm_apply_eq.2 ?_)).symm
  apply Additive.toMul.injective
  refine ContinuousMonoidHom.ext fun g ↦ ?_
  have := DFunLike.congr_fun (H1EquivOfSmulEqSelf_explicitCor1_eq_transfer
    (G := G) (M := ULift.{u} (ZMod n)) (fun _ _ ↦ rfl) hV
    ((H1EquivOfSmulEqSelf (G := V) (M := ULift.{u} (ZMod n)) fun _ _ ↦ rfl).symm
      (Additive.ofMul ψ))) g
  rw [AddEquiv.apply_symm_apply] at this
  exact this.symm

end Characters

variable {p : ℕ} {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G] {V : Subgroup G} [V.FiniteIndex]

omit [TotallyDisconnectedSpace G] [V.FiniteIndex] in
/-- A continuous character `ψ : V → ℤ/p^m` factors through `V^ab(p)`. -/
private theorem exists_comp_abelianizationProPMk [NeZero p] (hV : IsOpen (V : Set G)) {m : ℕ}
    (ψ : V →ₜ* Multiplicative (ULift.{u} (ZMod (p ^ m)))) :
    ∃ ψ' : abelianizationProP p G V →* Multiplicative (ULift.{u} (ZMod (p ^ m))),
      ψ.toMonoidHom = ψ'.comp (abelianizationProPMk p G V) := by
  have : CompactSpace V := isCompact_iff_compactSpace.mp (V.isClosed_of_isOpen hV).isCompact
  have hP : IsProP p (Multiplicative (ULift.{u} (ZMod (p ^ m)))) :=
    ((ZModModule.isPGroup_multiplicative (n := p ^ m) (G := ZMod (p ^ m))).of_pow.of_equiv
      AddEquiv.ulift.symm.toMultiplicative).isProP
  let ψab := TopologicalAbelianization.lift ψ
  refine ⟨maximalProPQuotient.lift hP ψab.toMonoidHom ψab.continuous, ?_⟩
  ext v
  simp [ψab, abelianizationProPMk_apply]

omit [TotallyDisconnectedSpace G] in
/-- The transfer of a continuous character `ψ : V → ℤ/p^m` kills the kernel of the transfer
`G → V^ab(p)`, because `ψ` factors through `V^ab(p)`. -/
private theorem transfer_apply_eq_one [NeZero p] (hV : IsOpen (V : Set G)) {m : ℕ}
    (ψ : V →ₜ* Multiplicative (ULift.{u} (ZMod (p ^ m)))) {g : G}
    (hg : abelianizationProPTransfer p G V g = 1) :
    MonoidHom.transfer ψ.toMonoidHom g = 1 := by
  obtain ⟨ψ', hψ⟩ := exists_comp_abelianizationProPMk hV ψ
  rw [hψ, MonoidHom.transfer_comp, MonoidHom.comp_apply, ← abelianizationProPTransfer_def, hg,
    map_one]

/-- **A character of `p`-power order dies on the kernel of the transfer.** For a profinite
group `G` with `scd_p G ≤ 2` and an open subgroup `V`, every continuous character
`χ : G → ℤ/p^k` is trivial on the kernel of the transfer `Ver : G → V^ab(p)`. This is NSW
(3.3.11) at `n = 2` with integral coefficients, read on characters through the integral
Bockstein maps and (1.5.9). -/
theorem zmodChar_eq_one_of_transfer_eq_one (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) {k : ℕ}
    (χ : G →* Multiplicative (ZMod (p ^ k))) (hχ : Continuous χ) {g : G}
    (hg : abelianizationProPTransfer p G V g = 1) : χ g = 1 := by
  have : NeZero p := ⟨hp.ne_zero⟩
  have : CompactSpace V := isCompact_iff_compactSpace.mp (V.isClosed_of_isOpen hV).isCompact
  -- The class `c ∈ H¹(G, ℤ/p^k)` of `χ`, and its integral Bockstein, a `p`-primary class.
  let up : Multiplicative (ZMod (p ^ k)) →* Multiplicative (ULift.{u} (ZMod (p ^ k))) :=
    AddEquiv.ulift.symm.toMultiplicative.toMonoidHom
  have hup : Continuous up := continuous_of_discreteTopology
  let χ' : G →ₜ* Multiplicative (ULift.{u} (ZMod (p ^ k))) := ⟨up.comp χ, hup.comp hχ⟩
  set c := charClass G (p ^ k) (Additive.ofMul χ') with hc
  have hx : integralBockstein G (p ^ k) 1 c ∈ AddCommGroup.primaryComponent _ p :=
    (mem_primaryComponent_iff_exists_integralBockstein G p _).2 ⟨k, c, rfl⟩
  -- It is the corestriction of a `p`-primary class of `H²(V, ℤ)`, the Bockstein of a character
  -- `ψ` of `V`; so it is the Bockstein of the transfer of `ψ`.
  obtain ⟨y, hy, hyx⟩ := corestriction_surjOn_primaryComponent_of_strictCohomologicalDimensionAt_le
    hp h hV (ULift.{u} ℤ) hx
  obtain ⟨m, d, rfl⟩ := (mem_primaryComponent_iff_exists_integralBockstein V p y).1 hy
  obtain ⟨ψ, rfl⟩ := (charClass V (p ^ m)).surjective d
  let ψT : G →ₜ* Multiplicative (ULift.{u} (ZMod (p ^ m))) :=
    ⟨MonoidHom.transfer (Additive.toMul ψ).toMonoidHom,
      continuous_transfer hV (Additive.toMul ψ).continuous⟩
  have h₁ : integralBockstein G (p ^ m) 1 (charClass G (p ^ m) (Additive.ofMul ψT)) =
      integralBockstein G (p ^ k) 1 c := by
    rw [← hyx, ← corestriction_charClass G hV (Additive.toMul ψ)]
    exact ConcreteCategory.congr_hom
      (integralBockstein_corestriction G (p ^ m) V hV 1) (charClass V (p ^ m) ψ)
  -- Raised to the common modulus `p ^ (k + m)`, the two characters have the same Bockstein,
  -- hence agree, the degree-one Bockstein being injective.
  have hN₁ : p ^ k * p ^ m = p ^ (k + m) := (pow_add p k m).symm
  have hN₂ : p ^ m * p ^ k = p ^ (k + m) := by rw [mul_comm, pow_add]
  have hB {a b : ℕ} [NeZero a] (hab : a * b = p ^ (k + m))
      (x : continuousCohomology 1 (ofDiscreteModule ℤ G (ULift.{u} (ZMod a)))) :
      integralBockstein G (p ^ (k + m)) 1 (coeffMap (ofDiscreteModuleMap
        ((AddEquiv.ulift.symm.toAddMonoidHom.comp (ZMod.mulCastHom b hab)).comp
          AddEquiv.ulift.toAddMonoidHom).toIntLinearMap fun _ _ ↦ rfl) 1 x) =
        integralBockstein G a 1 x := by
    rw [← ConcreteCategory.comp_apply, integralBockstein_mulCastHom]
  have h₂ := integralBockstein_one_injective G (p ^ (k + m))
    ((hB hN₁ c).trans (h₁.symm.trans (hB hN₂ _).symm))
  have h₃ := congrArg (fun x ↦ (Multiplicative.toAdd
    (Additive.toMul ((charClass G (p ^ (k + m))).symm x) g)).down) h₂
  simp only [charClass_symm_coeffMap_apply, hc, AddEquiv.symm_apply_apply] at h₃
  -- The transfer of `ψ` kills `g`, so the raised value of `χ g` vanishes.
  have hψg : ψT g = 1 :=
    transfer_apply_eq_one hV (Additive.toMul ψ) hg
  -- `χ'` is `χ` followed by the lift `ZMod (p ^ k) ≃+ ULift (ZMod (p ^ k))`.
  have hχg : (Multiplicative.toAdd (χ' g)).down = Multiplicative.toAdd (χ g) := rfl
  rw [toMul_ofMul, toMul_ofMul, hψg, hχg, toAdd_one, ULift.zero_down, _root_.map_zero] at h₃
  rw [← toAdd_eq_zero]
  exact ZMod.mulCastHom_injective (p ^ m) hN₁ (pow_ne_zero m hp.ne_zero)
    (h₃.trans (_root_.map_zero _).symm)

/-- **The kernel of the transfer** (NSW (3.6.4)(ii), injectivity, in `p`-primary form). For a
profinite group `G` with `scd_p G ≤ 2` and an open subgroup `V`, an element of `G` dies under the
transfer `Ver : G → V^ab(p)` exactly when it dies in `G^ab(p)`. So `Ver` induces an injection
`G^ab(p) → V^ab(p)`. The prime `p` is needed only for the forward direction. -/
theorem abelianizationProPTransfer_eq_one_iff (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) (g : G) :
    abelianizationProPTransfer p G V g = 1 ↔
      maximalProPQuotient.mk p (TopologicalAbelianization G)
        (g : TopologicalAbelianization G) = 1 := by
  have : NeZero p := ⟨hp.ne_zero⟩
  have : CompactSpace V := isCompact_iff_compactSpace.mp (V.isClosed_of_isOpen hV).isCompact
  let π : G →* maximalProPQuotient p (TopologicalAbelianization G) :=
    (maximalProPQuotient.mk p (TopologicalAbelianization G)).comp
      (QuotientGroup.mk' (commutator G).topologicalClosure)
  have hπ : Continuous π :=
    (maximalProPQuotient.continuous_mk (p := p) (G := TopologicalAbelianization G)).comp
      QuotientGroup.continuous_mk
  constructor
  · -- A character of `G^ab(p)` separating the class of `g` from `1` would be a character of `G`
    -- not killing `g`.
    intro hg
    by_contra hne
    obtain ⟨k, χ, hχ, -, hχg⟩ := exists_continuous_zmodChar_of_notMem
      (isProP_maximalProPQuotient (p := p) (G := TopologicalAbelianization G)) ⊥
      (by rw [Subgroup.coe_bot]; exact isClosed_singleton) (π g)
      (Subgroup.mem_bot.not.mpr hne)
    exact hχg (zmodChar_eq_one_of_transfer_eq_one hp h hV (χ.comp π) (hχ.comp hπ) hg)
  · exact abelianizationProPTransfer_eq_one_of_mk_eq_one hV

section Range

variable [V.Normal]

omit [TotallyDisconnectedSpace G] [V.FiniteIndex] in
/-- Let `Z` be a compact subgroup of the normal subgroup `V` whose elements have
`G ⧸ V`-invariant classes in `V^ab(p)`. Then for a `p`-primary class `w ∈ H²(V, ℤ)`, the
difference `(g)_* w - w` restricts to zero on `Z`: `w` is the Bockstein of a character of
`p`-power order, which factors through `V^ab(p)` and so does not see the conjugation on `Z`. -/
private theorem map_conjNormalMap_sub_eq_zero [NeZero p] (hV : IsOpen (V : Set G))
    (Z : Subgroup V) [CompactSpace Z]
    (hZ : ∀ z ∈ Z, ∀ q : G ⧸ V, q • abelianizationProPMk p G V z = abelianizationProPMk p G V z)
    (g : G) {w : continuousCohomology 2 (ofDiscreteModule ℤ V (ULift.{u} ℤ))}
    (hw : w ∈ AddCommGroup.primaryComponent _ p) :
    _root_.ContinuousCohomology.map (ContinuousMonoidHom.subgroupSubtype Z)
        (ofDiscreteModulePair (ContinuousMonoidHom.subgroupSubtype Z : Z →* V)
          (AddMonoidHom.id (ULift.{u} ℤ)).toIntLinearMap fun _ _ ↦ rfl) 2
        (conjNormalMap V (ULift.{u} ℤ) g 2 w - w) = 0 := by
  have : CompactSpace V := isCompact_iff_compactSpace.mp (V.isClosed_of_isOpen hV).isCompact
  obtain ⟨j, d, rfl⟩ := (mem_primaryComponent_iff_exists_integralBockstein V p w).1 hw
  obtain ⟨φ, rfl⟩ := (charClass V (p ^ j)).surjective d
  set κ : V →ₜ* V :=
    ContinuousMonoidHom.toContinuousMonoidHom (ContinuousAut.conjNormal g⁻¹ : ContinuousAut V)
  set ι : Z →ₜ* V := ContinuousMonoidHom.subgroupSubtype Z
  -- On `Z`, the character `φ` does not see the conjugation `κ`.
  obtain ⟨φ', hφ'⟩ := exists_comp_abelianizationProPMk hV (Additive.toMul φ)
  have hκ : ((Additive.toMul φ).comp κ).comp ι = (Additive.toMul φ).comp ι := by
    refine ContinuousMonoidHom.ext fun z ↦ ?_
    have hz : abelianizationProPMk p G V (κ z) = abelianizationProPMk p G V z := by
      have hκz : κ z = MulAut.conjNormal g⁻¹ (z : V) := Subtype.ext (by simp [κ])
      rw [hκz, ← abelianizationProPMk_conj, hZ z z.2]
    exact (DFunLike.congr_fun hφ' (κ z)).trans
      ((congrArg φ' hz).trans (DFunLike.congr_fun hφ' (z : V)).symm)
  -- Both terms restrict to the Bockstein of the same character of `Z`.
  have hδ (x) := ConcreteCategory.congr_hom (integralBockstein_map V ι (p ^ j) 1) x
  have hconj := ConcreteCategory.congr_hom (integralBockstein_map V κ (p ^ j) 1)
    (charClass V (p ^ j) φ)
  simp only [ConcreteCategory.comp_apply] at hδ hconj
  rw [conjNormalMap_eq_map_of_smul_eq_self _ _ (fun _ _ ↦ rfl), map_sub]
  rw [hconj, hδ, hδ, ← ofMul_toMul φ, map_charClass, map_charClass, map_charClass, hκ,
    sub_self]

/-- Under `scd_p G ≤ 2`, a `p`-primary class of `H²(V, ℤ)` with trivial corestriction restricts to
zero on every compact subgroup `Z` of `V` whose elements have `G ⧸ V`-invariant classes in
`V^ab(p)`: by (3.3.11) it is a sum of differences `(g)_* w - w`, and these restrict to zero. -/
private theorem map_eq_zero_of_corestriction_eq_zero (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G))
    (Z : Subgroup V) [CompactSpace Z]
    (hZ : ∀ z ∈ Z, ∀ q : G ⧸ V, q • abelianizationProPMk p G V z = abelianizationProPMk p G V z)
    {y : continuousCohomology 2 (ofDiscreteModule ℤ V (ULift.{u} ℤ))}
    (hy : y ∈ AddCommGroup.primaryComponent _ p)
    (hcor : corestriction V (ULift.{u} ℤ) hV 2 y = 0) :
    _root_.ContinuousCohomology.map (ContinuousMonoidHom.subgroupSubtype Z)
        (ofDiscreteModulePair (ContinuousMonoidHom.subgroupSubtype Z : Z →* V)
          (AddMonoidHom.id (ULift.{u} ℤ)).toIntLinearMap fun _ _ ↦ rfl) 2 y = 0 := by
  have : NeZero p := ⟨hp.ne_zero⟩
  let R := (_root_.ContinuousCohomology.map (ContinuousMonoidHom.subgroupSubtype Z)
    (ofDiscreteModulePair (ContinuousMonoidHom.subgroupSubtype Z : Z →* V)
      (AddMonoidHom.id (ULift.{u} ℤ)).toIntLinearMap fun _ _ ↦ rfl)
    2).hom.toLinearMap.toAddMonoidHom
  refine (AddSubgroup.closure_le R.ker).2 ?_
    (corestriction_ker_primaryComponent_of_strictCohomologicalDimensionAt_le hp h hV _ hy hcor)
  rintro _ ⟨g, w, hw, rfl⟩
  exact map_conjNormalMap_sub_eq_zero hV Z hZ g hw

/-- **A character that dies on the image of the transfer dies on the invariants.** For a profinite
group `G` with `scd_p G ≤ 2` and an open normal subgroup `V`, a continuous character
`ψ : V^ab(p) → ℤ/p^k` that is trivial on the image of the transfer `Ver : G → V^ab(p)` is trivial
on every `G ⧸ V`-invariant element of `V^ab(p)`. This is NSW (3.3.11) at `n = 2` with integral
coefficients, the injectivity of corestriction on the coinvariants, read on characters. -/
theorem zmodChar_eq_one_of_comp_transfer_eq_one (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) {k : ℕ}
    (ψ : abelianizationProP p G V →* Multiplicative (ZMod (p ^ k))) (hψ : Continuous ψ)
    (hψV : ∀ g : G, ψ (abelianizationProPTransfer p G V g) = 1) {x : abelianizationProP p G V}
    (hx : ∀ q : G ⧸ V, q • x = x) : ψ x = 1 := by
  have : NeZero p := ⟨hp.ne_zero⟩
  have : CompactSpace V := isCompact_iff_compactSpace.mp (V.isClosed_of_isOpen hV).isCompact
  -- The closed subgroup `Z` of the elements of `V` whose class in `V^ab(p)` is invariant.
  let Z : Subgroup V := (FixedPoints.subgroup (G ⧸ V) (abelianizationProP p G V)).comap
    (abelianizationProPMk p G V)
  have hZ : IsClosed (Z : Set V) := by
    have hfix : (FixedPoints.subgroup (G ⧸ V) (abelianizationProP p G V) :
        Set (abelianizationProP p G V)) =
        ⋂ q : G ⧸ V, {y | q • y = y} := by
      ext
      simp
    rw [Subgroup.coe_comap, hfix]
    exact (isClosed_iInter fun q ↦ isClosed_eq (continuous_const_smul q) continuous_id).preimage
      (continuous_abelianizationProPMk p G V)
  have : CompactSpace Z := isCompact_iff_compactSpace.mp hZ.isCompact
  let ι : Z →ₜ* V := ContinuousMonoidHom.subgroupSubtype Z
  -- The class `c ∈ H¹(V, ℤ/p^k)` of the character `ψ` of `V`, and its integral Bockstein.
  let up : Multiplicative (ZMod (p ^ k)) →* Multiplicative (ULift.{u} (ZMod (p ^ k))) :=
    AddEquiv.ulift.symm.toMultiplicative.toMonoidHom
  have hup : Continuous up := continuous_of_discreteTopology
  let χ : V →ₜ* Multiplicative (ULift.{u} (ZMod (p ^ k))) :=
    ⟨(up.comp ψ).comp (abelianizationProPMk p G V),
      (hup.comp hψ).comp (continuous_abelianizationProPMk p G V)⟩
  set c := charClass V (p ^ k) (Additive.ofMul χ)
  have hy : integralBockstein V (p ^ k) 1 c ∈ AddCommGroup.primaryComponent _ p :=
    (mem_primaryComponent_iff_exists_integralBockstein V p _).2 ⟨k, c, rfl⟩
  -- Its corestriction vanishes: on characters, corestriction is the transfer, which is `ψ ∘ Ver`.
  have hcor : corestriction V (ULift.{u} ℤ) hV 2 (integralBockstein V (p ^ k) 1 c) = 0 := by
    have hT : (⟨MonoidHom.transfer χ.toMonoidHom, continuous_transfer hV χ.continuous⟩ :
        G →ₜ* Multiplicative (ULift.{u} (ZMod (p ^ k)))) = 1 := by
      refine ContinuousMonoidHom.ext fun g ↦ ?_
      have hχ : χ.toMonoidHom = (up.comp ψ).comp (abelianizationProPMk p G V) := rfl
      simp only [hχ, MonoidHom.transfer_comp, ContinuousMonoidHom.coe_mk, MonoidHom.comp_apply,
        ← abelianizationProPTransfer_def, hψV, map_one, ContinuousMonoidHom.coe_one, Pi.one_apply]
    rw [← ConcreteCategory.comp_apply, ← integralBockstein_corestriction,
      ConcreteCategory.comp_apply, corestriction_charClass G hV, hT, ofMul_one, _root_.map_zero,
      _root_.map_zero]
  -- By (3.3.11), its restriction to `Z` vanishes.
  have hR := map_eq_zero_of_corestriction_eq_zero hp h hV Z (fun z hz ↦ hz) hy hcor
  -- So the restriction of `χ` to `Z` has trivial Bockstein, hence is trivial.
  have hδ := ConcreteCategory.congr_hom (integralBockstein_map V ι (p ^ k) 1) c
  rw [ConcreteCategory.comp_apply, ConcreteCategory.comp_apply, map_charClass] at hδ
  have hχZ : χ.comp ι = 1 := by
    have h0 := hδ.symm.trans hR
    rw [← _root_.map_zero (integralBockstein Z (p ^ k) 1).hom] at h0
    have := integralBockstein_one_injective Z (p ^ k) h0
    exact ofMul_eq_zero.1 ((map_eq_zero_iff _ (charClass Z (p ^ k)).injective).1 this)
  obtain ⟨v, rfl⟩ := abelianizationProPMk_surjective p G V x
  have hv := DFunLike.congr_fun hχZ ⟨v, hx⟩
  exact AddEquiv.ulift.symm.toMultiplicative.injective (hv.trans (map_one _).symm)

/-- **The image of the transfer** (NSW (3.6.4)(ii), surjectivity, in `p`-primary form). For a
profinite group `G` with `scd_p G ≤ 2` and an open normal subgroup `V`, the image of the transfer
`Ver : G → V^ab(p)` is the subgroup of `G ⧸ V`-invariants of `V^ab(p)`. Together with
`TauCeti.abelianizationProPTransfer_eq_one_iff`, `Ver` induces an isomorphism of `G^ab(p)` onto
`(V^ab(p))^{G/V}`. -/
theorem abelianizationProPTransfer_range (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) :
    (abelianizationProPTransfer p G V).range =
      FixedPoints.subgroup (G ⧸ V) (abelianizationProP p G V) := by
  have : NeZero p := ⟨hp.ne_zero⟩
  have : CompactSpace V := isCompact_iff_compactSpace.mp (V.isClosed_of_isOpen hV).isCompact
  refine le_antisymm ?_ fun x hx ↦ ?_
  · rintro _ ⟨g, rfl⟩
    exact (FixedPoints.mem_subgroup _ _ _).2 fun q ↦ smul_abelianizationProPTransfer p G V q g
  -- The image is compact, hence closed; a character separating `x` from it would contradict
  -- `zmodChar_eq_one_of_comp_transfer_eq_one`.
  by_contra hnx
  have hclosed : IsClosed ((abelianizationProPTransfer p G V).range :
      Set (abelianizationProP p G V)) := by
    rw [MonoidHom.coe_range]
    exact (isCompact_range (continuous_abelianizationProPTransfer p G V hV)).isClosed
  obtain ⟨k, ψ, hψ, hψV, hψx⟩ := exists_continuous_zmodChar_of_notMem
    (isProP_maximalProPQuotient (p := p) (G := TopologicalAbelianization V)) _ hclosed x hnx
  exact hψx (zmodChar_eq_one_of_comp_transfer_eq_one hp h hV ψ hψ
    (fun g ↦ hψV _ ⟨g, rfl⟩) ((FixedPoints.mem_subgroup _ _ _).1 hx))

end Range

end TauCeti
