/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Functoriality
public import TauCeti.Algebra.Lie.UniversalEnveloping.Subalgebra
import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Injective
import Mathlib.LinearAlgebra.Basis.VectorSpace

/-!
# Enveloping algebras of Lie subalgebras and PBW degree

Over any field an injective Lie homomorphism induces an injective map of universal enveloping
algebras, and that map preserves and reflects the PBW filtration. Thus the enveloping algebra of
a Lie subalgebra identifies with the subalgebra generated by its canonical Lie generators, with
the filtration inherited from the ambient enveloping algebra.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §17.2.
-/

public section

namespace TauCeti.UniversalEnvelopingAlgebra

open TauCeti.Algebra.wordFiltration

universe u v w

variable (K : Type u) [Field K] {L : Type v} {M : Type w}
  [LieRing L] [LieAlgebra K L] [LieRing M] [LieAlgebra K M]

attribute [local instance 100] LieRing.ofAssociativeRing

local notation "ιL" =>
  LieHom.toLinearMap (_root_.UniversalEnvelopingAlgebra.ι K :
    L →ₗ⁅K⁆ _root_.UniversalEnvelopingAlgebra K L)
local notation "ιM" =>
  LieHom.toLinearMap (_root_.UniversalEnvelopingAlgebra.ι K :
    M →ₗ⁅K⁆ _root_.UniversalEnvelopingAlgebra K M)

/-- An injective Lie map induces an injective map of PBW associated gradeds. -/
theorem mapAssociatedGraded_injective (f : L →ₗ⁅K⁆ M) (hf : Function.Injective f) :
    Function.Injective (mapAssociatedGraded K f) := by
  intro x y hxy
  obtain ⟨a, rfl⟩ := pbwAssociatedGradedMap_surjective K L x
  obtain ⟨b, rfl⟩ := pbwAssociatedGradedMap_surjective K L y
  have hnat (c : SymmetricAlgebra K L) :=
    AlgHom.congr_fun (mapAssociatedGraded_comp_pbwAssociatedGradedMap K f) c
  simp only [AlgHom.comp_apply] at hnat
  rw [hnat a, hnat b] at hxy
  exact congrArg (pbwAssociatedGradedMap K L)
    (SymmetricAlgebra.map_injective f.toLinearMap hf
      (pbwAssociatedGradedMap_injective K M hxy))

/-- An injective Lie map induces an injective map on every PBW graded piece. -/
theorem mapGradedPiece_injective (f : L →ₗ⁅K⁆ M) (hf : Function.Injective f) (n : ℕ) :
    Function.Injective (mapGradedPiece K f n) := by
  intro x y hxy
  apply DirectSum.of_injective
  apply mapAssociatedGraded_injective K f hf
  simp only [mapAssociatedGraded_of, hxy]

/-- For an injective Lie map, a filtered element whose image drops in degree already drops in
degree in the source. -/
theorem mem_pbwFiltrationPrevious_of_map_mem (f : L →ₗ⁅K⁆ M)
    (hf : Function.Injective f) {n : ℕ} {x : _root_.UniversalEnvelopingAlgebra K L}
    (hx : x ∈ pbwFiltration K L n)
    (hfx : map K f x ∈ pbwFiltrationPrevious K M n) :
    x ∈ pbwFiltrationPrevious K L n := by
  have hx' : x ∈ TauCeti.Algebra.wordFiltration ιL n := by
    rwa [pbwFiltration_def] at hx
  have hfx' : map K f x ∈ TauCeti.Algebra.wordFiltrationPrevious ιM n := by
    rwa [pbwFiltrationPrevious_def] at hfx
  have hzero : mapGradedPiece K f n
      (Submodule.Quotient.mk (⟨x, hx'⟩ : TauCeti.Algebra.wordFiltration ιL n)) = 0 := by
    rw [mapGradedPiece_mk, gradedPiece_mk_eq_zero_iff]
    exact hfx'
  have hz := (mapGradedPiece_injective K f hf n)
    (hzero.trans (map_zero _).symm)
  rw [gradedPiece_mk_eq_zero_iff] at hz
  rwa [pbwFiltrationPrevious_def]

/-- An injective Lie map reflects membership in each PBW filtration step. -/
@[simp]
theorem _root_.UniversalEnvelopingAlgebra.map_mem_pbwFiltration_iff
    (f : L →ₗ⁅K⁆ M) (hf : Function.Injective f)
    (n : ℕ) (x : _root_.UniversalEnvelopingAlgebra K L) :
    map K f x ∈ pbwFiltration K M n ↔ x ∈ pbwFiltration K L n := by
  refine ⟨fun hfx ↦ ?_, map_mem_pbwFiltration K f⟩
  obtain ⟨d, hd⟩ := exists_mem_pbwFiltration K L x
  induction d generalizing x with
  | zero => exact pbwFiltration_mono K L (Nat.zero_le n) hd
  | succ d ih =>
      by_cases hdn : d + 1 ≤ n
      · exact pbwFiltration_mono K L hdn hd
      · have hdrop : map K f x ∈ pbwFiltrationPrevious K M (d + 1) := by
          rw [pbwFiltrationPrevious_succ]
          exact pbwFiltration_mono K M (by omega) hfx
        have hx := mem_pbwFiltrationPrevious_of_map_mem K f hf hd hdrop
        rw [pbwFiltrationPrevious_succ] at hx
        exact ih x hfx hx

/-- The preimage of an ambient PBW filtration step along an injective Lie map is exactly the
source filtration step. -/
@[simp]
theorem comap_pbwFiltration (f : L →ₗ⁅K⁆ M) (hf : Function.Injective f) (n : ℕ) :
    (pbwFiltration K M n).comap (map K f).toLinearMap = pbwFiltration K L n := by
  ext x
  exact _root_.UniversalEnvelopingAlgebra.map_mem_pbwFiltration_iff K f hf n x

/-- For an injective Lie map, the image of a PBW filtration step is the corresponding ambient
step intersected with the range of the enveloping-algebra map. -/
theorem map_pbwFiltration_eq_inf_range_of_injective (f : L →ₗ⁅K⁆ M)
    (hf : Function.Injective f) (n : ℕ) :
    (pbwFiltration K L n).map (map K f).toLinearMap =
      pbwFiltration K M n ⊓ LinearMap.range (map K f).toLinearMap := by
  rw [← comap_pbwFiltration K f hf n, Submodule.map_comap_eq, inf_comm]

/-- An injective Lie homomorphism over a field induces an injective enveloping-algebra map. -/
theorem map_injective (f : L →ₗ⁅K⁆ M) (hf : Function.Injective f) :
    Function.Injective (map K f) := by
  apply (map K f).toLinearMap.ker_eq_bot.mp
  apply bot_unique
  intro x hx
  have hzero : map K f x = 0 := hx
  obtain ⟨n, hn⟩ := exists_mem_pbwFiltration K L x
  induction n with
  | zero =>
      have hdrop := mem_pbwFiltrationPrevious_of_map_mem K f hf hn
        (by rw [hzero]; exact Submodule.zero_mem _)
      simpa using hdrop
  | succ n ih =>
      have hdrop := mem_pbwFiltrationPrevious_of_map_mem K f hf hn
        (by rw [hzero]; exact Submodule.zero_mem _)
      rw [pbwFiltrationPrevious_succ] at hdrop
      exact ih hdrop

/-- An injective Lie map induces an injective map on every PBW filtration step. -/
theorem mapFiltration_injective (f : L →ₗ⁅K⁆ M) (hf : Function.Injective f) (n : ℕ) :
    Function.Injective (mapFiltration K f n) := by
  intro x y hxy
  apply Subtype.ext
  apply map_injective K f hf
  simpa only [mapFiltration_apply] using congrArg Subtype.val hxy

end TauCeti.UniversalEnvelopingAlgebra

namespace LieSubalgebra

open TauCeti.UniversalEnvelopingAlgebra

variable {K : Type u} [Field K] {L : Type v} [LieRing L] [LieAlgebra K L]

/-- The enveloping algebra of a Lie subalgebra is the subalgebra of the ambient enveloping
algebra generated by its canonical Lie generators. -/
noncomputable def universalEnvelopingEquiv (A : LieSubalgebra K L) :
    _root_.UniversalEnvelopingAlgebra K A ≃ₐ[K] envelopingSubalgebra K A :=
  (AlgEquiv.ofInjective (TauCeti.UniversalEnvelopingAlgebra.map K A.incl)
    (map_injective K A.incl Subtype.coe_injective)).trans
    (Subalgebra.equivOfEq _ _ (envelopingSubalgebra_eq_range_map K A).symm)

/-- The enveloping-subalgebra equivalence is the canonical map induced by inclusion. -/
@[simp]
theorem coe_universalEnvelopingEquiv_apply (A : LieSubalgebra K L)
    (x : _root_.UniversalEnvelopingAlgebra K A) :
    (A.universalEnvelopingEquiv x : _root_.UniversalEnvelopingAlgebra K L) =
      TauCeti.UniversalEnvelopingAlgebra.map K A.incl x := by
  simp only [universalEnvelopingEquiv, AlgEquiv.trans_apply,
    Subalgebra.equivOfEq_apply, AlgEquiv.ofInjective_apply]

end LieSubalgebra
