/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Additive subgroups containing a two-sided span

In a ring, the two-sided ideal spanned by a set `s` is the additive subgroup generated by the
products `a * x * b` with `x ∈ s` (Mathlib's `TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure`).
So an additive subgroup contains `TwoSidedIdeal.span s` exactly when it contains every such product.
This is how fullness of an idempotent `e`, `TwoSidedIdeal.span {e} = ⊤`, is used: to show that `1`
lies in an additive subgroup it suffices to show that every `a * e * b` does.

## Main results

* `TauCeti.TwoSidedIdeal.coe_span_subset_addSubgroup_iff`: an additive subgroup contains the
  two-sided ideal spanned by `s` if and only if it contains every product `a * x * b` with `x ∈ s`.
-/

public section

namespace TauCeti

namespace TwoSidedIdeal

variable {R : Type*} [Ring R]

/-- An additive subgroup contains the two-sided ideal spanned by `s` if and only if it contains
every product `a * x * b` with `x ∈ s`. -/
theorem coe_span_subset_addSubgroup_iff {s : Set R} {H : AddSubgroup R} :
    (_root_.TwoSidedIdeal.span s : Set R) ⊆ H ↔ ∀ a, ∀ x ∈ s, ∀ b, a * x * b ∈ H := by
  refine ⟨fun h a x hx b ↦ h ?_, fun h z hz ↦ ?_⟩
  · exact _root_.TwoSidedIdeal.mul_mem_right _ _ _
      (_root_.TwoSidedIdeal.mul_mem_left _ _ _ (_root_.TwoSidedIdeal.subset_span hx))
  · rw [SetLike.mem_coe, _root_.TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure] at hz
    refine (AddSubgroup.closure_le H).2 ?_ hz
    rintro _ ⟨_, ⟨a, -, x, hx, rfl⟩, b, -, rfl⟩
    exact h a x hx b

end TwoSidedIdeal

end TauCeti
